[translation]
10003-StatusMessageJp = "ペロロフェスに一緒に行ってくれる人いますか？"
10003-FullNameJp = "阿慈谷ヒフミ"
10003-FamilyNameJp = "阿慈谷"
10003-PersonalNameJp = "ヒフミ"
10003-SchoolYearJp = "2학년"
10003-CharacterAgeJp = "16세"
10003-BirthdayJp = "11월 27일"
10003-HobbyJp = "페로로 굿즈 수집, 쇼핑, 이야기 들어주기"
10003-WeaponNameJp = "히후미가 늘 들고 다니는 분홍색의 돌격소총.\n\n분홍색으로 채색된 귀여운 모양의 소총은 소녀가 외출할 때 빼놓을 수 없는 필수품이다."
10003-WeaponDescJp = "マイ・ネセシティ"
10003-ProfileIntroductionJp = "트리니티 보충수업부의 다정다감한 소녀.\n\n외모도 성적도 특출나지 않지만, 모나지 않고 상냥한 성품 덕분에 인기가 많다. 주변 사람들의 고민이나 이야기를 잘 들어주지만, 그 때문에 의도치 않게 분위기에 휩쓸려 말썽을 일으키는 경우도 있다."
10003-CharacterSSRNewJp = "이제부터 선생님과 함께…….\n저, 힘낼게요!"
