[translation]
10027-StatusMessageKr = "잠입 임무 수행 중"
10027-FullNameKr = "카쿠다테 카린"
10027-FamilyNameKr = "카쿠다테"
10027-PersonalNameKr = "카린"
10027-SchoolYearKr = "C&C"
10027-CharacterAgeKr = "2年生"
10027-BirthdayKr = "2/2"
10027-HobbyKr = "沼倉愛美"
10027-WeaponNameKr = "お掃除"
10027-WeaponDescKr = "빅 아이"
10027-ProfileIntroductionKr = "カリン専用の対物スナイパーライフル。\n\nたとえそれが空を舞う「白兎」でも、正確無比に撃ち落とす。"
10027-CharacterSSRNewKr = "ミレニアムサイエンススクール所属、今回作戦の最前線に直接参加することになった「C&C」のエージェント。\n\n任務のためであればと言いながら、いそいそと着替える彼女。しかし、普段以上に周囲から集まる視線については、やはりやや気になっている様子。"
