[translation]
10030-StatusMessageJp = "未知の視界を求めて"
10030-FullNameJp = "火宮チナツ"
10030-FamilyNameJp = "火宮"
10030-PersonalNameJp = "チナツ"
10030-SchoolYearJp = "1학년"
10030-CharacterAgeJp = "15세"
10030-BirthdayJp = "8월 22일"
10030-HobbyJp = "철학서적 읽기"
10030-WeaponNameJp = "치나츠가 애용하는 권총.\n\n작고 가벼워 휴대가 편리한 치나츠의 권총은 온천장에서의 잠입 임무에 매우 적합하다."
10030-WeaponDescJp = "サポートポインター"
10030-ProfileIntroductionJp = "공무 중 우연히 온천장을 방문하게 된 게헨나 선도부의 보건 담당.\n\n새로운 의약품의 발주부터 온천개발부의 새로운 음모까지, 그녀를 괴롭히는 문제들은 설국의 온천장에서도 그치질 않지만…… 목가적인 온천장의 풍경은 일상에 지친 그녀를 살짝 나태하게 만든다."
10030-CharacterSSRNewJp = "오늘은 조금…… 여유로워지고 싶네요."
