[translation]
10049-StatusMessageEn = "A member of the After-School Sweets Club."
10049-FullNameEn = "Kyoyama Kazusa"
10049-FamilyNameEn = "Kyoyama"
10049-PersonalNameEn = "Kazusa"
10049-SchoolYearEn = "1st Year"
10049-CharacterAgeEn = "15 years old"
10049-BirthdayEn = "August 5th"
10049-HobbyEn = "\"Casually\" eating desserts"
10049-WeaponNameEn = "Mabinogion"
10049-WeaponDescEn = "A machine gun Kazusa's had for a long time. When asked about the origin of its name, Kazusa gets embarrassed and avoids answering the question."
10049-ProfileIntroductionEn = "A member of the After-School Sweets Club with a relaxed and quiet personality.\n\nShe usually keeps to herself and tends to just go along with the other members' shenanigans. She'll grumble a lot about their constant chaos, but she secretly loves that about her friends."
10049-CharacterSSRNewEn = "Oh, Sensei. I didn't expect to see you here."
