[translation]
10045-StatusMessageKr = "낮잠 중~. 동료는 언제든지 환영"
10045-FullNameKr = "타카나시 호시노"
10045-FamilyNameKr = "타카나시"
10045-PersonalNameKr = "호시노"
10045-SchoolYearKr = "対策委員会"
10045-CharacterAgeKr = "3年生"
10045-BirthdayKr = "1/2"
10045-HobbyKr = "花守ゆみり"
10045-WeaponNameKr = "昼寝、ゴロゴロすること"
10045-WeaponDescKr = "호루스의 눈"
10045-ProfileIntroductionKr = "夏の海用に整備されたホシノのショットガン。\n\n獣道を切り開いたり、虫捕りに使ったりとさまざまな用途で使えるよう手入れされている。"
10045-CharacterSSRNewKr = "アビドス高等学校所属、ゆったりとした夏を求めて無人島にやってきた対策委員会の委員長。\n\n面倒くさがりな態度とは裏腹に、支度を存外しっかりしている。しかし、本人は自身が普段より少し積極的になっている事に気づいていない模様。"
