[translation]
10054-StatusMessageJp = "平和なお祭りになりますように"
10054-FullNameJp = "伊落マリー"
10054-FamilyNameJp = "伊落"
10054-PersonalNameJp = "マリー"
10054-SchoolYearJp = "1학년"
10054-CharacterAgeJp = "15세"
10054-BirthdayJp = "9월 12일"
10054-HobbyJp = "기도, 사색"
10054-WeaponNameJp = "마리가 소지하고 다니는 권총.\n\n보통은 경기의 시작을 알리는 신호탄처럼 평화로운 용도로만 사용되지만, 의도치 않게 불량한 학생들을 향할 때도 있다."
10054-WeaponDescJp = "パイエティー"
10054-ProfileIntroductionJp = "황륜대제 참가를 위해 체육복으로 갈아입은 시스터후드 소녀.\n\n키보토스의 평화를 기원하는 축제라는 말에, 기쁜 마음으로 실행위원 업무에 자원하였다. 하지만 예상과 달리 대회 내내 다툼과 말썽이 끊이질 않고, 특유의 헌신적인 성격과 맞물려 계속해서 트러블에 휘말린다."
10054-CharacterSSRNewJp = "이 대운동회를 통해\n모두가 미움을 거두고 화해하기를……"
