[translation]
10063-StatusMessageKr = "아니 이게 제 잘못임;;?"
10063-FullNameKr = "쿠로사키 코유키"
10063-FamilyNameKr = "쿠로사키"
10063-PersonalNameKr = "코유키"
10063-ClubNameForGachaKr = "세미나"
10063-SchoolYearKr = "1학년"
10063-CharacterAgeKr = "15세"
10063-BirthdayKr = "2월 14일"
10063-HobbyKr = "운 시험하기, 탈출"
10063-WeaponNameKr = "멀리<건>"
10063-WeaponDescKr = "코유키가 당해온 온갖 수모들을 함께 겪은 기관총.\n\n바닷물에 빠진 적도 있어, 수리하는 과정에서 색이 바뀌었다. 성능과는 별개로, 사소한 것은 신경 쓰지 않는 코유키를 닮아 튼튼하다."
10063-ProfileIntroductionKr = "밀레니엄 세미나의 골칫덩이인 천재 소녀.\n\n수학적 암호 해독에 독보적인 재능을 가졌지만 정작 본인은 전혀 자각이 없다. 늘 여러 가지 방법으로 자신의 운을 시험하며, 대부분 호된 꼴을 당함에도 포기하지 않는다."
10063-CharacterSSRNewKr = "생각대로 되지 않을 때,\n비로소 인생은 재미있는 법."
