[translation]
10081-StatusMessageKr = "선생님! 소녀도 모모톡에 가입했사와요!"
10081-FullNameKr = "카데노코지 유카리"
10081-FamilyNameKr = "카데노코지"
10081-PersonalNameKr = "유카리"
10081-SchoolYearKr = "百花繚乱紛争調停委員会"
10081-CharacterAgeKr = "1年生"
10081-BirthdayKr = "6/16"
10081-HobbyKr = "村上まなつ"
10081-WeaponNameKr = "お祈り、駄菓子屋巡り"
10081-WeaponDescKr = "백화요란 제식 소총 - 소녀의 결의"
10081-ProfileIntroductionKr = "ユカリが使用する百花繚乱の制式ライフル。\n\nかつての憧れの象徴であり、理想を追いかけ努力し手に入れた決意の証。そこに込められた心は、誰にも手折ることなどできない。"
10081-CharacterSSRNewKr = "百鬼夜行連合学院所属、百花繚乱紛争調停委員会の1年生。\n\n由緒正しい勘解由小路家の跡継ぎ。家業を継ぐよりも、憧れの百花繚乱に入った少女。百花繚乱であることに誇りを持っており、行動力がある。時には挫けることもあるが、すぐに立ち上がれる芯の強さを持っている。先輩を尊敬しており、その中でも特にナグサを慕っている。"
