[translation]
10084-StatusMessageKr = "당신에게 귀를 기울이고 있습니다."
10084-FullNameKr = "오토세 코타마"
10084-FamilyNameKr = "오토세"
10084-PersonalNameKr = "코타마"
10084-SchoolYearKr = "ヴェリタス"
10084-CharacterAgeKr = "3年生"
10084-BirthdayKr = "1/5"
10084-HobbyKr = "高川みな"
10084-WeaponNameKr = "無線通信、盗聴"
10084-WeaponDescKr = "에코 링크"
10084-ProfileIntroductionKr = "コタマがいつも持ち歩いている拳銃。\n\n発砲音を極限まで抑えたこの拳銃は、静かな山の中でも野生動物から警戒されることなく、作戦を遂行することができる。"
10084-CharacterSSRNewKr = "寒い冬にあわせて暖かい格好に着替えたヴェリタスのメンバー。\n\n外出する気はなかったものの、普段は録音しづらい環境音を収録するチャンスだとポジティブに切り替えている。自然環境で収録できるあらゆる音が好きだが、一番好きなのはやはり先生の声なのだとか。"
