[translation]
10094-StatusMessageKr = "메이드 게이머 외길… 인생?"
10094-FullNameKr = "사이바 모모이"
10094-FamilyNameKr = "사이바"
10094-PersonalNameKr = "모모이"
10094-ClubNameForGachaKr = "게임개발부"
10094-SchoolYearKr = "1학년"
10094-CharacterAgeKr = "15세"
10094-BirthdayKr = "12월 8일"
10094-HobbyKr = "게임"
10094-WeaponNameKr = "유니크・아이디어"
10094-WeaponDescKr = "모모이가 사용하는 돌격소총.\n\n스스로도 잘은 모르겠지만, 메이드에게는 소총이 필요하다고 아무튼 주장하는 중이다."
10094-ProfileIntroductionKr = "\"밀레니엄 학원, 게임 개발부의 시나리오 라이터.\n\n어쩌다 보니 C&C로 오해를 받아, 메이드복까지 입게 되고 말았다. 오해를 풀 사이도 없이 사건에 휘말리고, 휘말리고, 또다시 휘말려 들어가지만…… 특유의 밝고 당당한 태도로, 다가오는 모든 역경에 맞서 나간다.\""
10094-CharacterSSRNewKr = "최고의 메이드, 여기에 등장! 그러니까 우선 게임부터 하자, 선생님!"
