[translation]
10092-StatusMessageKr = "#맹연습중"
10092-FullNameKr = "이바라기 요시미"
10092-FamilyNameKr = "이바라기"
10092-PersonalNameKr = "요시미"
10092-ClubNameForGachaKr = "방과후 디저트부"
10092-SchoolYearKr = "1학년"
10092-CharacterAgeKr = "15세"
10092-BirthdayKr = "8월 29일"
10092-HobbyKr = "이벤트 참가, 한정판 디저트 수집"
10092-WeaponNameKr = "Sweet Driver"
10092-WeaponDescKr = "요시미가 늘 가지고 다니는 돌격소총.\n\n평상시에는 디저트 경쟁에서 이기기 위한 무기로 사용된다. 요시미가 연주하는 기타 소리만큼이나 경쾌한 총성을 울린다."
10092-ProfileIntroductionKr = "방과후 디저트부의 부원이자 급조된 밴드 <슈가러시>의 기타리스트.\n\n분위기에 휩쓸려 시작했지만, 할 거라면 제대로 해야 된다는 마음가짐을 가지고 있다. 밴드의 아이콘이나 심볼, 의상 등 비주얼 적인 부분도 담당하였다."
10092-CharacterSSRNewKr = "똑바로 보라고!\n두 번은 안 해줄 테니까!"
