[translation]
10105-StatusMessageKr = "이 노래에 힘이 깃들기를"
10105-FullNameKr = "이오치 마리"
10105-FamilyNameKr = "이오치"
10105-PersonalNameKr = "마리"
10105-ClubNameForGachaKr = "시스터후드"
10105-SchoolYearKr = "1학년"
10105-CharacterAgeKr = "15세"
10105-BirthdayKr = "9월 12일"
10105-HobbyKr = "기도, 사색"
10105-WeaponNameKr = "Piety"
10105-WeaponDescKr = "마리가 아이돌이 되어서도 놓지 않는 권총.\n\n특유의 디자인이 아이돌 복장과도 세트처럼 어울린다."
10105-ProfileIntroductionKr = "트리니티의 아이돌 유닛 <앤틱 세라핌>의 리더.\n\n처음에는 그저 모두를 돕고자 하는 마음에 시작했던 일이었지만, 어느새 스스로 무대 위에서 노래를 부르는 한 사람의 아이돌로 자리 잡게 되었다.사실 \"모두의 즐거움을 위해 노력한다\"는 부분에서, 옷을 입지 않았을 때에도 아이돌로서의 자질이 있었을지 모른다."
10105-CharacterSSRNewKr = "실은…… 저 또한 동경하고 있었어요. 아이돌."
