[translation]
10129-StatusMessageKr = "오늘은 평안한 하루가 되기를……"
10129-FullNameKr = "모리즈키 스즈미"
10129-FamilyNameKr = "모리즈키"
10129-PersonalNameKr = "스즈미"
10129-ClubNameForGachaKr = "트리니티 자경단"
10129-SchoolYearKr = "2학년"
10129-CharacterAgeKr = "16세"
10129-BirthdayKr = "8월 31일"
10129-HobbyKr = "순찰, 산책"
10129-WeaponNameKr = "세이프티"
10129-WeaponDescKr = "스즈미의 돌격소총. \n\n겨눠진 사람이 기억하는 경우가 있어, 잠복을 위해 귀엽게 꾸몄다."
10129-ProfileIntroductionKr = "트리니티 자경단 잠복 활동의 일환으로, 마법소녀 코스튬을 입게 되었다. \n\n마법소녀에 대해서 잘 아는 것도 없고, 남들 앞에 서는 것도 부끄럽지만, 성실함으로 그 모든 역경에 맞서는 중이다."
10129-CharacterSSRNewKr = "서, 선생님……!\n이 옷은, 취미가 아닙니다!"
