[translation]
10127-StatusMessageJp = "校則は守りましょう……。"
10127-FullNameJp = "桜井ミヨ"
10127-FamilyNameJp = "桜井"
10127-PersonalNameJp = "ミヨ"
10127-SchoolYearJp = "2학년"
10127-CharacterAgeJp = "16세"
10127-BirthdayJp = "8월 24일"
10127-HobbyJp = "타자기 수집"
10127-WeaponNameJp = "미요가 늘 가지고 다니는, 하지만 성격상 거의 사용하지 않는 소총.\n\n탄흔이라는 텍스트를 새기는 수단…… 정도로 취급 중이다."
10127-WeaponDescJp = "キヴォトス・タイプライター"
10127-ProfileIntroductionJp = "와일드헌트 예술학원 소속의 여고생.\n\n비공인 불법 밀수 동아리 특수교역부의 부장. 목표는 특수교역부의 폐부. 하지만 소심한 성격과 늘 폭주하는 부원들 때문에 목표를 이룰 날은 요원해 보인다."
10127-CharacterSSRNewJp = "저도…… 로맨스 소설의 작가가 될 수 있을까요?"
