[translation]
10122-StatusMessageKr = "같이 수영할 사람 모집 중!"
10122-FullNameKr = "미소노 미카"
10122-FamilyNameKr = "미소노"
10122-PersonalNameKr = "미카"
10122-ClubNameForGachaKr = "티파티"
10122-SchoolYearKr = "3학년"
10122-CharacterAgeKr = "17세"
10122-BirthdayKr = "5월 8일"
10122-HobbyKr = "생각하기, 반짝이는 것 찾기"
10122-WeaponNameKr = "Quis ut Deus"
10122-WeaponDescKr = "미카가 애용하는 기관단총.\n\n정성 들인 손질 덕에, 바닷가에서도 별처럼 빛난다."
10122-ProfileIntroductionKr = "티파티의 일원으로, 해변의 바캉스 계획을 주도한 소녀.\n\n친구들을 배려하는 마음으로 시작한 일이지만, 어째 갈수록 꼬여만 가는 느낌. 특히 요즘에는 이런저런 고민으로 잠 못 이루는 날이 많은 듯하다."
10122-CharacterSSRNewKr = "와-오☆ 많이 기다렸어?"
