[translation]
10128-StatusMessageJp = "メディア、アート、テクネー"
10128-FullNameJp = "若狭フユ"
10128-FamilyNameJp = "若狭"
10128-PersonalNameJp = "フユ"
10128-SchoolYearJp = "2학년"
10128-CharacterAgeJp = "16세"
10128-BirthdayJp = "9월 5일"
10128-HobbyJp = "TV 시청, 가전제품 개조"
10128-WeaponNameJp = "후유가 사용하는 제조사 불명의 수상한 기관권총.\n\n이것을 제시하면 대부분의 고객이 후유의 권고사항을 받아들인다. "
10128-WeaponDescJp = "親切な誘い"
10128-ProfileIntroductionJp = "비공인 불법 밀수 동아리 특수교역부의 영업 및 기술 담당.\n\n일감을 수주하고 의뢰인을 대면하는 등, 특수교역부의 얼굴 역할을 맡고 있다. 늘 당당하고 여유로운 태도를 고수하지만, 생각과 다르게 상황이 흘러가면 쉽게 멘탈이 무너지는 의외의 면모도 있다."
10128-CharacterSSRNewJp = "원하는 물건이 있으신가요?"
