[translation]
10133-StatusMessageEn = "Tasklist /S"
10133-FullNameEn = "Tsukatsuki Rio"
10133-FamilyNameEn = "Tsukatsuki"
10133-PersonalNameEn = "Rio"
10133-SchoolYearEn = "3rd Year"
10133-CharacterAgeEn = "17 years old"
10133-BirthdayEn = "June 6th"
10133-HobbyEn = "Designing"
10133-WeaponNameEn = "Policy Maker"
10133-WeaponDescEn = "Rio's self-defense pistol.\n\nThanks to her suit's support, she can fire with even greater precision than before."
10133-ProfileIntroductionEn = "The president of Seminar, Millennium's student council.\n\nAn extraordinary situation calls for an extraordinary outfit. Rio's versatile suit is designed to adapt to any situation: on-site utility, machine work, real-time analysis, and even electronic warfare."
10133-CharacterSSRNewEn = "Leave the electronic warfare to me.\nI'll demonstrate the most logical response."
