[translation]
10133-StatusMessageTw = "Tasklist /S"
10133-FullNameTw = "調月莉央"
10133-FamilyNameTw = "調月"
10133-PersonalNameTw = "莉央"
10133-SchoolYearTw = "3年級"
10133-CharacterAgeTw = "17歲"
10133-BirthdayTw = "6月6日"
10133-HobbyTw = "設計"
10133-WeaponNameTw = "立案者"
10133-WeaponDescTw = "莉央的護身用手槍。\n\n得益於合理戰鬥服的輔助，能夠進行更加精準的射擊。"
10133-ProfileIntroductionTw = "千年科學學園所屬，學生會「研討會」的會長。\n\n為了應對前所未有的危機而換上特殊戰鬥服的狀態。為了能應對現場處理、設備運用、狀況分析乃至於電子戰在內的多種情況，特別注重服裝的泛用性。"
10133-CharacterSSRNewTw = "電子戰的話請交給我吧\n我會向你展示最為合理的解答"
