[translation]
10147-StatusMessageKr = "실험체 상시 모집/문의는 모모톡으로"
10147-FullNameKr = "쿄고쿠 사츠키"
10147-FamilyNameKr = "쿄고쿠"
10147-PersonalNameKr = "사츠키"
10147-ClubNameForGachaKr = "판데모니움 소사이어티"
10147-SchoolYearKr = "3학년"
10147-CharacterAgeKr = "17세"
10147-BirthdayKr = "4월 10일"
10147-HobbyKr = "마인드컨트롤 연구, 쇼핑"
10147-WeaponNameKr = "NK 델타"
10147-WeaponDescKr = "사츠키가 애용하는 권총.\n\n뛰어난 휴대성으로 바닷가에서도 안심. 사실 거의 사용하지 않지만, 손질 자체는 깨끗하게 해두고 있다."
10147-ProfileIntroductionKr = "판데모니움 소사이어티 소속의 의원이자 정보부장.\n\n호화 크루즈 여행이라는 희소식을 듣고 어울리는 복장을 골랐지만, 그 실상은… 아무튼 위험한 바다 위에서 정보부장으로서의 능력을 마음껏 발휘한다."
10147-CharacterSSRNewKr = "불렀어, 선생?\n자아, 자아. 천 년의 협력을 약속해달라고."
