[translation]
10143-StatusMessageKr = "물가에서는 특히 조심해야 한답니다."
10143-FullNameKr = "스노하라 슌"
10143-FamilyNameKr = "스노하라"
10143-PersonalNameKr = "슌"
10143-SchoolYearKr = "梅花園"
10143-CharacterAgeKr = "3年生"
10143-BirthdayKr = "2/5"
10143-HobbyKr = "伊藤静"
10143-WeaponNameKr = "子供たちと遊ぶこと"
10143-WeaponDescKr = "사랑의 매"
10143-ProfileIntroductionKr = "シュンが使用するスナイパーライフル。\n\n訓育とは、時に痛みを伴うものである。"
10143-CharacterSSRNewKr = "夏を迎え水着に着替えた山海経高級中学校所属、訓育支援部「梅花園」の教官。\n\nなぜか先生と一緒に引率する側になっている。普段よりも余裕があり、大人びた雰囲気が漂う。その裏には、いつもと違った一面が隠れているのかもしれない。"
