[translation]
16014-StatusMessageTw = "我是格黑娜學園的伊吹！"
16014-FullNameTw = "丹花伊吹"
16014-FamilyNameTw = "丹花"
16014-PersonalNameTw = "伊吹"
16014-SchoolYearTw = "1年級"
16014-CharacterAgeTw = "11歲"
16014-BirthdayTw = "4月14日"
16014-HobbyTw = "預習與複習、收集玩偶"
16014-WeaponNameTw = "砰砰！醬"
16014-WeaponDescTw = "伊吹很珍惜的槍枝。\n\n原本是從萬魔殿的前輩們手中傳下來的制式步槍，伊吹一直珍惜地使用至今，平時會貼自己喜歡的貼紙或掛吊飾做裝飾。現在已經成為伊吹獨一無二的寶物。"
16014-ProfileIntroductionTw = "格黑娜學園所屬，萬魔殿的議員，如吉祥物一般的少女。\n\n原本是格黑娜學園小學部的成員，因為其能力備受認可，順利躋身只接受格黑娜優秀學生的萬魔殿。是萬魔殿年紀最小的一員，因為其獨有的誠實和可愛深受眾人喜愛。是名為了不給前輩們添麻煩，今天也一樣奮發向上、品行端正的孩子。"
