[translation]
16016-StatusMessageKr = "구호기사단, 많이 사랑해 주세요!"
16016-FullNameKr = "아오모리 미네"
16016-FamilyNameKr = "아오모리"
16016-PersonalNameKr = "미네"
16016-ClubNameForGachaKr = "구호기사단"
16016-SchoolYearKr = "3학년"
16016-CharacterAgeKr = "17세"
16016-BirthdayKr = "11월 23일"
16016-HobbyKr = "의료 용품 수집"
16016-WeaponNameKr = "구호의 증명"
16016-WeaponDescKr = "미네가 애용하는 산탄총.\n\n아이돌 활동이 구호기사단 활동의 연장선이듯, 이 총 또한 아이돌 소품의 연장선일 수 있다."
16016-ProfileIntroductionKr = "트리니티의 아이돌 유닛 <앤틱 세라핌>의 일원.\n\n모두에게 조금 더 친근한 구호기사단의 단장이 되기 위해 스스로 아이돌 이벤트에 지원하였다. 특유의 강직함은 여전하지만, 귀여운 것을 좋아하는 스스로에게도 조금은 더 솔직해진 모습이다."
