[translation]
16020-StatusMessageEn = "Loneliness in the Crowd"
16020-FullNameEn = "Tenjinyama Otogi"
16020-FamilyNameEn = "Tenjinyama"
16020-PersonalNameEn = "Otogi"
16020-SchoolYearEn = "3rd Year"
16020-CharacterAgeEn = "17 years old"
16020-BirthdayEn = "May 20th"
16020-HobbyEn = "Solving puzzles, fantasizing"
16020-WeaponNameEn = "FOX 82-Sniper Rifle"
16020-WeaponDescEn = "A standard sniper rifle Otogi received from SRT Academy.\n\n\nIt enables her to snipe down enemies hiding behind cover, as well as target long-distance enemies. However, the gun is very heavy—so Otogi suffers from chronic shoulder stiffness..."
16020-ProfileIntroductionEn = "The sniper of SRT Academy's FOX Squad. Call sign is \"FOX 4.\"\n\nUnlike other snipers who are mainly lone wolf types, this student befriends others easily and loves to joke around. Thanks to her personality, Otogi is the squad’s cheerleader, lifting everyone's spirits. On the battlefield, she uses her natural presence to demoralize the enemy.\n\nShe's also skilled at handling electronic equipment and is able to fix most machinery."
