[translation]
20005-StatusMessageKr = "새로 산 페로로 튜브 보실 분?"
20005-FullNameKr = "아지타니 히후미"
20005-FamilyNameKr = "아지타니"
20005-PersonalNameKr = "히후미"
20005-ClubNameForGachaKr = "보충수업부"
20005-SchoolYearKr = "2학년"
20005-CharacterAgeKr = "16세"
20005-BirthdayKr = "11월 27일"
20005-HobbyKr = "페로로 굿즈 수집, 쇼핑, 이야기 들어주기"
20005-WeaponNameKr = "마이 네세시티"
20005-WeaponDescKr = "히후미가 늘 들고 다니는 분홍색의 돌격소총.\n\n귀여운 각인이 새겨진 총기는 해변의 바캉스에서도 빼놓을 수 없는 필수품이다."
20005-ProfileIntroductionKr = "친구와 함께 바닷가를 방문한 트리니티 보충수업부의 다정다감한 소녀.\n\n바다를 본 적 없다는 친구를 위해 학교 비품인 크루세이더 전차를 몰래 빌리려고 했지만, 정의실현부에게 그 사실을 들키며 거대한 말썽에 휘말리게 되었다. 전차에 탄 상태에서도 본래의 덜렁거리는 기질은 여전하여, 실수로 전차를 급발진시키는 등, 말썽을 키우는 데 일조하고 있다."
20005-CharacterSSRNewKr = "아하하…… 조금 평범한 수영복이라 부끄럽네요."
