[translation]
20020-StatusMessageKr = "밀레니엄 최고의 천재병약미소녀, 네. 저랍니다."
20020-FullNameKr = "아케보시 히마리"
20020-FamilyNameKr = "아케보시"
20020-PersonalNameKr = "히마리"
20020-SchoolYearKr = "特異現象捜査部"
20020-CharacterAgeKr = "3年生"
20020-BirthdayKr = "12/10"
20020-HobbyKr = "ゆかな"
20020-WeaponNameKr = "今日の運勢の確認、オカルト全般"
20020-WeaponDescKr = "절벽 위의 꽃"
20020-ProfileIntroductionKr = "ヒマリが所持している拳銃。\n\nシンプルで美しいつくりの銃。普段ヒマリが使う姿を見るのは難しい。「本来、高嶺の花というのは簡単に目にすることができないものですから……まるで私のようでしょう？」とはヒマリの談である。"
20020-CharacterSSRNewKr = "ミレニアムサイエンススクール所属、ハッカー集団「ヴェリタス」の元部長で、現特異現象捜査部の部長。\n\n自称超天才病弱美少女ハッカーであり、ミレニアム史上たった3人しか名乗ることを許されていない学位「全知」の所有者らしい……それが真実なのか、そのような学位が実在するのかさえ、全てベールに包まれている。ヒマリ曰く、秘密の多い少女は美しいもの……なのだとか。また、指折りの実力を持つ天才ハッカーであり、同時にオカルトに目がない奇妙な趣向を持つ少女でもある。"
