[translation]
20043-StatusMessageKr = "인생도 맛도, 모험!"
20043-FullNameKr = "시시도우 이즈미"
20043-FamilyNameKr = "시시도우"
20043-PersonalNameKr = "이즈미"
20043-ClubNameForGachaKr = "미식연구회"
20043-SchoolYearKr = "2학년"
20043-CharacterAgeKr = "16세"
20043-BirthdayKr = "5월 11일"
20043-HobbyKr = "괴식 만들기, 괴식 먹기"
20043-WeaponNameKr = "데일리 커트러리"
20043-WeaponDescKr = "이즈미의 기관총.\n\n새로운 맛을 찾아 떠나는 그녀에게, 이 총만큼 든든한 동반자도 없을 것이다."
20043-ProfileIntroductionKr = "기모노를 입었음에도, 언제나와 같은 이즈미\n\n새해에도 이즈미의 음식에 대한 도전은 계속된다. 그것이 그녀가 눈부신 미소를 띠고 있는 하나의 원인이 될 것 같다."
20043-CharacterSSRNewKr = "새로운 맛 조합을 찾으러 가자!"
