[translation]
20052-StatusMessageKr = "출판. 증쇄. 유통."
20052-FullNameKr = "아라마키 야쿠모"
20052-FamilyNameKr = "아라마키"
20052-PersonalNameKr = "야쿠모"
20052-ClubNameForGachaKr = "출판부"
20052-SchoolYearKr = "3학년"
20052-CharacterAgeKr = "17세"
20052-BirthdayKr = "5월 18일"
20052-HobbyKr = "사업 기획서 작성, 철도 노선 분석"
20052-WeaponNameKr = "프라우다"
20052-WeaponDescKr = "야쿠모가 상비 중인 권총.\n\n총에는 여러 가지 사용법이 있기 마련이라고 야쿠모는 입버릇처럼 말한다. 그중 하나는 마감을 지키지 않는 작가를 '성실하게' 만드는 것이라는 모양이다."
20052-ProfileIntroductionKr = "붉은겨울 학원의 출판 동아리 <출판부>의 부장.\n\n잡지 '붉은 곰'의 편집장을 겸업 중이다. 한번 결정하면 아무도 못 말리는 데다, 출판부의 이익을 위해서라면 뭐든 좋다는 무적의 부장님. 그러나 그 이면에는 무언가 순수한 마음이 숨어 있는 것 같다고도……"
20052-CharacterSSRNewKr = "혹시 책에 관심 있으십니까?\n에이, 이야기나 좀 나누자구요."
