[translation]
26000-StatusMessageKr = "상실의 아우프헤벤"
26000-FullNameKr = "히노미야 치나츠"
26000-FamilyNameKr = "히노미야"
26000-PersonalNameKr = "치나츠"
26000-SchoolYearKr = "風紀委員会"
26000-CharacterAgeKr = "1年生"
26000-BirthdayKr = "8/22"
26000-HobbyKr = "香月はるか"
26000-WeaponNameKr = "哲学書を読むこと"
26000-WeaponDescKr = "서포트 포인터"
26000-ProfileIntroductionKr = "チナツが愛用する拳銃。\n\n誰かを撃つ時よりも、業務上の指示などで何かの位置を示す時に使われることの方が多いらしい。"
26000-CharacterSSRNewKr = "ゲヘナ学園所属、風紀委員会の救護担当。\n\n規定、規律、手続きを重視する風紀委員会の数少ない常識人で、アコやイオリのような他の風紀委員達が暴走した時のブレーキ役。言葉使いが硬く、「典型的な風紀委員」といったような冷たい印象を与えがちだが、可愛い動物の前ではとことんメロメロになってしまう優しい少女である。"
