[translation]
26012-StatusMessageKr = "라이프가드 임무 중입니다!"
26012-FullNameKr = "나카츠카사 키리노"
26012-FamilyNameKr = "나카츠카사"
26012-PersonalNameKr = "키리노"
26012-ClubNameForGachaKr = "생활안전국"
26012-SchoolYearKr = "1학년"
26012-CharacterAgeKr = "15세"
26012-BirthdayKr = "10월 22일"
26012-HobbyKr = "맛집 탐방"
26012-WeaponNameKr = "발키리 제식 권총 3호"
26012-WeaponDescKr = "키리노가 발키리 경찰학교에서 지급받은 제식 권총.\n\n라이프가드로서의 사명감 덕분에 명중률이 올라간 기분이다."
26012-ProfileIntroductionKr = "발키리 경찰학교 생활안전국의 열혈 경찰 학생. 이번에는 라이프가드 모드.\n\n임무에 대한 의욕은 넘치지만 실력은 그에 미치지 못한다. 그럼에도 불구하고 업무에 성실히 임하고 있으며, 라이프가드 역할을 수행하기 위해 노력을 아끼지 않고 있다."
