[translation]
8431999016-0-Think-1 = "(บันทึกข้อมูลที่รวบรวมได้\nเรียบร้อยแล้วค่ะ)"
8431999017-0-Think-1 = "(บันทึกข้อมูล\nที่รวบรวมได้เรียบร้อย)"
8431999018-0-Think-1 = "(เนรุต้องได้รับข้อมูลนี้\nด้วยค่ะ)"
8431999019-0-Think-1 = "(เซอาต้องได้ข้อมูลนี้ด้วย)"
8430001000-0-Think-1 = "(ถ้าเอากล่องมาสวมไว้\nตอนอยู่นิ่งๆ ก็จะ\nไม่โดนจับได้ค่ะ)"
8430001000-0-Think-2 = "(ดูจังหวะให้ดี...\nแล้วค่อยๆ ขยับ)"
8430001010-1-Talk-1 = "อ่า..."
8430001010-2-Talk-1 = "คือ..."
8430001010-0-Think-1 = "(อีกนิดหนึ่ง...)"
8430001030-1-Talk-1 = "อีกเดี๋ยวก็จะ\nถึงเวลาติดต่อกันแล้ว"
8430001030-2-Talk-1 = "รีบๆ จัดการให้จบ\nแล้วกลับดีกว่า"
8430001030-0-Think-1 = "(เท่านี้น่าจะพอแล้วนะคะ...)"
8430001040-0-Think-1 = "(ยังมีเรื่องที่ต้องทำอยู่ค่ะ)"
8430001050-0-Think-1 = "(รออีกแป๊บหนึ่งแล้วกันนะคะ)"
8430003000-0-Think-1 = "(น่าจะมีอุปกรณ์เก็บข้อมูล\nอยู่ระหว่างทางสินะ?)"
8430003000-0-Think-2 = "(อยากจะทุบทุกอย่างทิ้ง\nให้หมดจริงๆ เลยเชียว...)"
8430003000-0-Think-3 = "(ภารกิจแฝงตัวนี่\nไม่ใช่งานถนัดฉันเลยจริงๆ)"
8430003000-0-Think-4 = "(เห็นบอกว่าถ้าเริ่ม\nหมดแรง... ก็ให้กิน\nยาฟื้นฟูกำลังนี่สินะ)"
8430003010-0-Think-1 = "(ยังมีงานที่ต้องทำอยู่)"
8430006000-0-Think-1 = "(โดรน... สมกับเป็นมิลเลเนียม\nจริงๆ เลยนะ ต่างจากทรีนิตี้\nจริงๆ ด้วยค่ะ)"
8430006000-0-Think-2 = "(ถ้าเดินไปจนสุดทางนี้...\nก็จะเจอประตูสินะคะ)"
8430006010-0-Think-1 = "(หุ่นยนต์น้องหมา...)"
8430006010-1-Talk-1 = "เซอา ทางนี้"
8430006010-0-Talk-1 = "ริโอะ"
8430006010-1-Talk-2 = "ฉันติดอุปกรณ์สื่อสาร\nไว้กับหุ่นยนต์น้องหมาแล้ว"
8430006010-1-Talk-3 = "ระหว่างทางจะได้บันทึก\nข้อมูลที่รวบรวมมาได้"
8430006020-0-Think-1 = "(เรื่องนี้... ทำคนเดียว\nคงไม่สำเร็จแน่เลย)"
8430006020-0-Think-2 = "(ติดต่อไปหาริโอะ\nน่าจะดีกว่า)"
8430006030-1-Talk-1 = "พวกเขาสร้างทางลับ\nไว้ตรงนี้ด้วย"
8430006030-1-Talk-2 = "ปิดพัดลมระบายอากาศได้\nโดยกดสวิตช์ที่ตู้ไฟฟ้า\nและไปที่ช่องระบายอากาศ"
8430006040-0-Think-1 = "(นี่คือ... ตู้ไฟฟ้า...?)"
8430006050-0-Think-1 = "(ตอนนี้เดินเข้าไปใน\nช่องระบายอากาศได้แล้ว)"
8430006050-0-Think-2 = "(ต้องรีบไปแล้วละ)"
8431001000-0-Think-1 = "(นั่นมัน...?)"
8431001000-0-Think-2 = "(มีอยู่ที่นี่ด้วยสินะ...\nมีประโยชน์จริงๆ เลย)"
8431001010-0-Think-1 = "(มาถึงตอนนี้แล้ว\nลองใช้ดูหน่อยดีมั้ยนะ...)"
8431001011-0-Think-1 = "(อย่างนั้นเองสินะคะ\nมีประโยชน์จริงๆ ด้วย)"
8431002000-0-Think-1 = "(ตอนนี้ก็มาถึงแล้ว...)"
8431002000-0-Think-2 = "(เข้าไปอีกหน่อยดีมั้ยนะ)"
8431002010-0-Think-1 = "(เข้าไปให้ไม่โดนจับ\nน่าจะยากแฮะ)"
8431002010-0-Think-2 = "(มีแผ่นป้องกันเข่า\nที่ริโอะให้มาด้วยนี่นา)"
8431002010-0-Think-3 = "(ได้จังหวะพอดีเลยนะ)"
8431002020-1-Talk-1 = "เสร็จงานนี้แล้ว\nไปหาอะไรอร่อยๆ\nกินฉลองกันเถอะ!"
8431002020-2-Talk-1 = "กินเสร็จแล้วไปฉลองต่อ\nรอบ 2 ได้ด้วยนี่นา?!\nนานๆ ทีนี่นะ!"
8431002020-3-Talk-1 = "ฉันอยากกินเทปันยากิค่ะ!"
8431002030-0-Think-1 = "(พวกมันอาจหนีไปก็ได้\nถ้าฉันส่งเสียงออกไป...)"
8431002030-0-Bulb-1 = "[전구]"
8431002030-0-Think-2 = "(ใช่แล้ว... แผ่นรอง)"
8431002030-0-Think-3 = "(เป็นคนละเอียดรอบคอบ\nจริงๆ เลยนะ)"
8431003000-0-Think-1 = "(อืม... ชักจะยุ่งยากแล้วนะคะ)"
8431003000-0-Think-2 = "(ใช้เครื่องสื่อสารไร้สาย\nติดต่อเนรุได้สินะคะ...)"
8431003000-0-Think-3 = "(ไหนลองดูหน่อยซิ)"
8431003010-0-Talk-1 = "อ่า ฉันเข้าใจสถานการณ์แล้วละ\nจะลองทำอะไรสักอย่าง\nจากทางนี้ก็แล้วกัน"
8431003010-0-Talk-2 = "ตู้ไฟฟ้า? โอเค\nฉันจะลองหาดู"
8431004000-0-Think-1 = "(ทางด้านเซอา...)"
8431004000-0-Think-2 = "(ไม่ใช่เด็กๆ สักหน่อย\nคงจะหาทางเองได้ละมั้ง)"
8431004010-0-Think-1 = "(คงต้องทำอะไรสักอย่าง\nจากทางนั้นอยู่ละมั้ง)"
8431005000-0-Think-1 = "(ถึงจะไม่ค่อยเข้าใจเท่าไร\nแต่คงต้องหาทางหนีออกไป\nให้ได้แล้วละ)"
8431005000-0-Think-2 = "(ลางสังหรณ์ของฉันบอกว่า\nถ้าโดนจับได้คงจบเท่านี้แน่ๆ!)"
8431006000-0-Think-1 = "มันแปลกๆ นะคะ..."
8431006000-0-Think-2 = "(ปกติน่าจะมีการเสริม\nการรักษาความปลอดภัย\nให้แน่นหนาขึ้นนี่นา)"
8431006000-0-Dot-1 = "[…]"
8431006000-0-Exclaim-1 = "[!]"
8431006000-0-Talk-1 = "มันเป็นกับดักค่ะ\nวางแผนแบบนี้ไว้\nตั้งแต่แรกแล้วสินะคะ!"
8431006000-0-Talk-2 = "ต้องให้เนรุช่วยแล้วค่ะ!"
8431006010-0-Exclaim-1 = "[!]"
8431006010-0-Think-1 = "เนรุกำลังตกอยู่ในอันตรายค่ะ!"
8431006020-0-Think-1 = "เซอาคงจะมาเปิดให้ละมั้ง"
8431007000-0-Think-1 = "(ขืนเป็นแบบนี้\nต้องโดนจับแน่ๆ...)"
8431007000-0-Think-2 = "(อะไรบางอย่าง...\nที่จะเอามาขวางทางได้...!)"
85413320101-0-Talk-1 = "ต้องเข้าใจและวิเคราะห์\nสถานการณ์ก่อน"
85413320101-0-Talk-2 = "แต่ก็ไม่ง่ายเลยนะคะ"
85413320102-0-Talk-1 = "ดินแดนเหล็กกล้า...\nคือ 'ปรากฏการณ์ลี้ลับ'\nเลยนะคะ"
85413320102-0-Talk-2 = "ถึงจะต่างจาก\nปรากฏการณ์ลี้ลับ\nที่ฉันคาดไว้นิดหน่อย\nก็เถอะค่ะ"
85413320103-0-Talk-1 = "ในที่สุดก็มาถึง\nตรงนี้ได้แล้วนะคะ"
85413320104-0-Talk-1 = "พวกเราจะหาทางออก\nได้แน่นอนค่ะ"
85433320105-0-Talk-1 = "คุณครู\nฉันฝากการเผด็จศึก\nสุดท้ายด้วยนะคะ"
85433320106-0-Talk-1 = "ต้องหาสิ่งที่\nสามารถทำ\nที่นี่ได้ค่ะ"
85433320107-0-Think-1 = "(ที่คุณครูบอกให้\nกลับไปที่ยานขนส่ง)"
85433320107-0-Think-2 = "(ก็คงมี\nเหตุผลน่ะค่ะ)"
85433320108-0-Think-1 = "(คุณครูบอกว่า\nถ้าเกิดอะไรขึ้นมา...)"
85433320108-0-Think-2 = "(คำพูดนั้นมัน...)"
85433320109-0-Talk-1 = "ขอให้ทุกคน...\nปลอดภัยด้วยนะคะ"
85433320110-0-Talk-1 = "ถึงเวลาจบทุกอย่าง\nแล้วสินะคะ"
85433320110-0-Talk-2 = "พวกฉันก็จะ\nทำให้เต็มที่ค่ะ"
85412670111-0-Talk-1 = "มีอย่างหนึ่งที่ฉันรู้!"
85412670111-0-Talk-2 = "นั่นก็คือ ฉันไม่รู้\nอะไรสักอย่างเลย!"
85412670112-0-Talk-1 = "คุณครูก็ลองดูมั้ย?\nอ่า ไม่เหรอ?\nเอางั้นเหรอ..."
85412670113-0-Talk-1 = "ฉันกำลังทำ\nตามที่พวกรุ่นพี่\nสอนมาน่ะ!"
85412670114-0-Talk-1 = "ว้าว... มีปุ่มที่\nไม่รู้ว่าคืออะไร\nเพียบเลย..."
85412670115-0-Talk-1 = "จุดสุดท้ายแล้ว\nคุณครู! ไปกันเลย!"
85432670116-0-Talk-1 = "ที่รุ่นพี่ฮิมาริ\nพากลับมาด้วย\nมันก็ดีอยู่หรอก..."
85432670117-0-Think-1 = "(คุณครูจะ\nปลอดภัยดีใช่มั้ย?\nจะไม่เป็นอะไรใช่มั้ยนะ...?)"
85432670118-0-Talk-1 = "อาริสึ... เคย์...\nเอมิ... โทคิ...\nประธาน... คุณครู..."
85432670119-0-Talk-1 = "อย่างน้อย...\nอย่างน้อยฉันก็\nต้องยิ้มเข้าไว้!"
85432670120-0-Talk-1 = "มาจบเรื่องนี้กัน คุณครู\nอย่างน้อยก็เพื่อ\nเด็กๆ ทั้งสามคนนั้น!"
85412680121-0-Talk-1 = "นี่มัน...\nอะไรกัน..."
85412680122-0-Talk-1 = "ยินดีต้อนรับค่ะ\nคุณครู"
85412680122-0-Talk-2 = "ที่นี่คือ... น่าจะเป็น\nโรงเก็บยานนะคะ?"
85412680123-0-Talk-1 = "คอร์ของผู้เลื่อมใส\nน่าจะเอาไปใช้\nทำบางอย่างนะ...\nแต่ทำอะไร..."
85412680124-0-Talk-1 = "เคย์จังกับประธาน\nก็อธิบายไว้แล้วนี่นา...\nต้องขอโทษด้วยค่ะ"
85442680125-0-Talk-1 = "ตอนนี้อัปเกรด\nได้แล้วค่ะ!"
85432680126-0-Talk-1 = "คุณครู...\nทุกคน...!"
85432680127-0-Think-1 = "(ต้องตั้งสติไว้\nให้มั่น...!)"
85432680128-0-Talk-1 = "ประธาน...\nไปอยู่ที่ไหน\nแล้วเหรอคะ..."
85432680129-0-Talk-1 = "ขอร้องละ...\nขอให้ทุกคน\nปลอดภัยด้วย...!"
85413310130-0-Talk-1 = "ต้องตีความ\nผลลัพธ์นี้ยังไงนะ..."
85413310131-0-Talk-1 = "ที่นี่คือ\nโรงเก็บยาน..."
85413310131-0-Talk-2 = "แต่รู้สึกเหมือนเป็นพื้นที่\nเทคโนโลยีที่ครอบคลุม\nมากขึ้นเรื่อยๆ เลย"
85413310133-0-Talk-1 = "เพื่อแก้ไข\nสถานการณ์นี้..."
85413310134-0-Talk-1 = "ฉันจะวิเคราะห์\nคอร์ของผู้เลื่อมใส\nที่ได้มาที่นี่เอง"
85413310135-0-Talk-1 = "เตรียมการอัปเกรด\nเสร็จแล้ว"
85413350201-0-Talk-1 = "นี่คือการเริ่มต้น\nเพื่อเป้าหมายแรกสินะคะ"
85413340202-0-Talk-1 = "อาริสึ...\nใจเต้นตึกตักเลยค่ะ!"
85413360203-0-Talk-1 = "ไม่มีที่ให้ซ่อนตัว...\nเลยเหรอ..."
85412670204-0-Talk-1 = "โอ้ว...\nมาที่นี่ครั้งแรกแท้ๆ\nแต่เหมือนเคย\nมาก่อนแล้วเลย!"
85412670204-0-Talk-2 = "รู้สึกแปลกจัง!"
85412680205-0-Talk-1 = "พี่โมโมอิ...\nอย่าชิลเกินสิ"
85413360212-0-Talk-1 = "ถ้าอยู่นอกตู้\nจะอันตรายจริงๆ ด้วย..."
85413330207-0-Talk-1 = "นี่คือ\nชาคาโมมายล์ค่ะ"
85413330207-0-Talk-2 = "ว่ากันว่ามีฤทธิ์\nช่วยให้ผ่อนคลายค่ะ"
85413310208-0-Think-1 = "(การที่ฉัน\nมาอยู่ที่นี่ในตอนนี้)"
85413310208-0-Think-2 = "(เป็นสิ่งที่สมเหตุสมผล\nหรือเปล่า...)"
85413320209-0-Talk-1 = "ในเวลาที่ต้อง\nรับศึกหนัก\nยิ่งต้องมีสติค่ะ"
85413350210-0-Talk-1 = "ฉันจะไม่ยอมให้อาริสึ\nหรือใครต้องบาดเจ็บ\nทั้งนั้นค่ะ"
85413340211-0-Talk-1 = "นี่คือก้าวแรกในการ\nกอบกู้โลกสินะคะ..."
85413340211-0-Talk-2 = "อาริสึจะพยายามค่ะ!"
85413360303-0-Talk-1 = "ที่นี่ก็มี\nเครื่องเล่นเกมด้วยสินะ..."
85412670213-0-Talk-1 = "รู้งี้เอาเกมมา\nมากกว่านี้ก็ดีน่ะสิ!"
85412680214-0-Talk-1 = "จะ... จะกลับไปได้\nอย่างปลอดภัยมั้ยคะ..."
85413360312-0-Think-1 = "(จะมีเกม\nอะไรบ้างนะ...)"
85413330216-0-Talk-1 = "ในฐานะเมดที่เพอร์เฟกต์\nและสุดยอดสายลับ"
85413330216-0-Talk-2 = "ถ้ามีอะไรให้ฉันช่วย\nก็บอกได้เลยนะคะ"
85413310217-0-Talk-1 = "ฉันก็กำลังติดตาม\nสถานการณ์อยู่..."
85413320218-0-Talk-1 = "ให้โหราศาสตร์...\nช่วยบอกอนาคต\nมั้ยคะ..."
85413350301-0-Talk-1 = "ทุกคนจะ\nอยากดื่มอะไร\nกันนะคะ..."
85413340302-0-Talk-1 = "เอาเครื่องเล่นเกม\nมาด้วยค่ะ!"
85413340302-0-Talk-2 = "คุณครูก็มาเล่น\nด้วยกันมั้ยคะ?"
85413360403-0-Talk-1 = "ฉันไม่อยาก...\nร่อนลง...\nอีกแล้วค่ะ... "
85412670304-0-Talk-1 = "ที่นี่ยอดเยี่ยมไปเลย...!"
85412680305-0-Talk-1 = "มะ... มันใหญ่โตมากเลย..."
85413360412-0-Talk-1 = "คุณครู... จะอยู่ข้างๆ ฉัน\nใช่มั้ยคะ...?"
85413330307-0-Talk-1 = "ฉันอยากให้คุณครู\nรับรู้ถึงผลงานของฉันค่ะ"
85413350310-0-Talk-1 = "การหยอดเหรียญ\nในเครื่องที่นี่\nมันจะมีความหมายเหรอ...?"
85413340311-0-Talk-1 = "ในเวลาแบบนี้\nการพักผ่อนก็สำคัญค่ะ!"
85412670313-0-Talk-1 = "สเกลมันเล็กกว่า\nตอนนั้นนิดหน่อย\nหรือเปล่า...?"
85412680314-0-Talk-1 = "พวกเราคือ\nชมรมพัฒนาเกมแท้ๆ..."
85413330316-0-Talk-1 = "ชุดที่เบาขึ้น\nทำให้ฉันเคลื่อนไหว\nได้คล่องตัวขึ้นค่ะ"
85413350401-0-Talk-1 = "ร่างกายนี้\nสร้างขึ้นมาได้ดี\nกว่าที่คิดอีกนะคะ"
85413340402-0-Talk-1 = "ทุกคนยอดเยี่ยมไปเลยค่ะ!"
85413360603-0-Talk-1 = "คุณครูเคยสู้\nกับศัตรูแบบนี้\nมาแล้วสินะคะ..."
85413360612-0-Talk-1 = "ถ้าได้อยู่กับคุณครู\nฉันก็ไม่กลัวค่ะ แหะๆๆ..."
85413330407-0-Talk-1 = "ชักจะเบื่อแล้วค่ะ\nมาเล่นด้วยกันหน่อยสิคะ"
85413310408-0-Think-1 = "(การเล่นเกม\nในเวลาแบบนี้...)"
85413310408-0-Think-2 = "(มันสมเหตุสมผลมั้ยนะ?)"
85413320409-0-Talk-1 = "ของหวานช่วย\nคลายเครียดได้ค่ะ"
85413350410-0-Talk-1 = "ฉันขอยอมรับ\nในผลงานด้านวิศวกรรม\nของเด็กพวกนั้นค่ะ"
85413340411-0-Talk-1 = "การได้มีอิสระ\nคือสิ่งที่ดีค่ะ!"
85413330416-0-Talk-1 = "รู้งี้เอาหนังสือการ์ตูน\nมาเยอะกว่านี้ก็ดีค่ะ"
85413310417-0-Talk-1 = "เครื่องเล่นเกม...\nก็แค่เครื่องจักรกับ\nโปรแกรมง่ายๆ เท่านั้น..."
85413320418-0-Talk-1 = "เครื่องดื่มที่เป็นสีนำโชค\nของวันนี้ก็คือ..."
85413350501-0-Talk-1 = "ทุกคนเหนื่อยกัน\nน่าดูเลยนะคะ"
85413340502-0-Talk-1 = "ทุกคนยอดเยี่ยมมากค่ะ!\nน่าชื่นชมเลยค่ะ!"
85413360803-0-Talk-1 = "ทั้งประธานริโอะ\nทั้งรุ่นพี่ฮิมาริ...\nเก่งสุดๆ ไปเลยนะคะ..."
85412670504-0-Talk-1 = "จริงๆ เลย... ก็นึก\nหวั่นๆ อยู่เหมือนกันนะ\nว่ามันจะเป็นยังไง..."
85412680505-0-Talk-1 = "คิดว่าทุกอย่างจบ\nแล้วเสียอีก..."
85413360812-0-Talk-1 = "ฉันก็เรียนรู้\nอะไรหลายๆ อย่างอยู่..."
85413360812-0-Talk-2 = "ฉันเหมือนจะเข้าใจ\nแต่ก็ไม่เข้าใจ..."
85413310508-0-Talk-1 = "ต้องเตรียมรับมือกับ\nทุกความเป็นไปได้\nให้มากกว่านี้..."
85413320509-0-Talk-1 = "ชงเครื่องดื่มอะไรอุ่นๆ..."
85413320509-0-Talk-2 = "เพื่อพักหายใจ\nหน่อยดีมั้ยนะ?"
85413350510-0-Talk-1 = "เอมิกับโทคิ\nออกไปตรวจสอบ\nยานขนส่งค่ะ"
85413340511-0-Talk-1 = "ความกล้าหาญ...\nคือพลังที่แท้จริงค่ะ!"
85413370206-0-Talk-1 = "ที่นี่ก็สะดวกและมี\nประสิทธิภาพอยู่หรอก..."
85412670513-0-Talk-1 = "ยังไงก็ทำเต็มที่แล้ว!\nอะแฮ่ม!"
85412680514-0-Talk-1 = "แต่ถ้ามันจะ\nเป็นประโยชน์กับทุกคน..."
85413370215-0-Talk-1 = "ถ้าจะขอเปิดแอร์\nหัวหน้าจะว่ามั้ยนะ?"
85413310517-0-Think-1 = "(ถึงจะเคยรู้สึกแบบนี้มาแล้ว\nแต่ชมรมพัฒนาเกม...)"
85413310517-0-Think-2 = "(เป็นชมรมที่คาดเดา\nไม่ได้เลยสินะ...)"
85413320518-0-Talk-1 = "ได้ยินมาว่า\nเราดูดวงจากผงกาแฟ\nได้ด้วยค่ะ"
85413350601-0-Talk-1 = "อาริสึไปนอนพัก\nสักครู่น่ะค่ะ"
85413370306-0-Talk-1 = "เสบียงอาหาร\nก็มีประสิทธิภาพดีนะ..."
85412670604-0-Talk-1 = "เกมที่เอามา\nก็เล่นจนหมดแล้ว..."
85412680605-0-Talk-1 = "คุณเอมิเหรอคะ?\nเห็นบอกว่าร้อน\nก็เลยออกไปข้างนอกค่ะ"
85413370315-0-Talk-1 = "การกินข้าวพร้อมหน้ากัน\nจะมีประสิทธิภาพ\nมากกว่าหรือเปล่า?"
85413330607-0-Talk-1 = "ไม่นานมานี้ฉันมี\nงานอดิเรกทำแล้วค่ะ"
85413310608-0-Think-1 = "(ฉันทำห้องครัว\nเผื่อไว้ให้)"
85413310608-0-Think-2 = "(แต่มันไม่สมเหตุสมผล\nหรือเปล่านะ...)"
85413350610-0-Talk-1 = "คุณครูก็อย่าลืม\nพักผ่อนนะคะ"
85413350610-0-Talk-2 = "อย่าลืมแปรงฟันด้วยค่ะ!"
85412670613-0-Talk-1 = "คุณครู\nมีฮาร์ดดิสก์พกพา\nเหลือมั้ย?"
85412680614-0-Talk-1 = "เกมเมื่อกี้\nเหมือนระดับความยาก\nจะไม่ถูกต้องเลยนะ...?"
85413330616-0-Talk-1 = "มาดูรายการอินเทอร์เน็ต"
85413330616-0-Talk-2 = "ที่ฉันโหลดมาด้วยกันมั้ยคะ?"
85413310617-0-Talk-1 = "อันที่จริง... บางครั้งฉันก็"
85413310617-0-Talk-2 = "ล้มเหลวกับการทำอาหาร\nด้วยไมโครเวฟ"
85413350701-0-Talk-1 = "พอจะเข้าใจความหมาย\nของ 'การพักรบ'\nแล้วละค่ะ..."
85413340702-0-Talk-1 = "อาริสึยังสู้ได้\nมากกว่านี้ค่ะ\nคุณครู!"
85412670704-0-Talk-1 = "นี่เป็นความฝันหรือเปล่า?"
85412670704-0-Talk-2 = "ถ้าตื่นขึ้นมา ก็คง\nอยู่ในห้องชมรมละนะ!"
85412680705-0-Talk-1 = "ได้มาถึงที่แบบนี้\nเลยเหรอเนี่ย..."
85412680705-0-Talk-2 = "พวกเราเป็นแค่\nชมรมพัฒนาเกมแท้ๆ"
85413350710-0-Talk-1 = "ไม่ได้เจ็บป่วยตรงไหน\nใช่มั้ยคะ? ดีค่ะ\nโล่งอกไปทีนะคะ"
85413340711-0-Talk-1 = "ถ้าอยากมีแรง"
85413340711-0-Talk-2 = "ก็ต้องหา\nอะไรกินค่ะ..."
85412670713-0-Talk-1 = "บางครั้งความจริง\nก็คือเกมที่ห่วย..."
85412680714-0-Talk-1 = "ไม่เป็นไรค่ะ...\nก็คุณครูอยู่ตรงนี้นี่คะ"
85413350801-0-Talk-1 = "เด็กตัวขาวพวกนั้นนะ\nจริงๆ เลย...!"
85413340802-0-Talk-1 = "โมโมอิกับมิโดริ\nบอกว่าจะไปพัก\nในห้องส่วนตัวค่ะ..."
85413370706-0-Talk-1 = "รู้สึกอยากไป\nห้องครัว\nยังไงไม่รู้แฮะ"
85413370715-0-Talk-1 = "โลกนี้มีสิ่งที่ถึงจะ\nไม่สมเหตุสมผล\nแต่ก็มีประสิทธิภาพนะ"
85413330807-0-Talk-1 = "ลาดตระเวนเหรอคะ?\nออกคำสั่งมาได้เลยค่ะ"
85413310808-0-Think-1 = "(ควรเริ่มบทสนทนา\nยังไงดีนะ?)"
85413320809-0-Talk-1 = "โล่งอกไปทีนะคะ...\nที่ทุกคนปลอดภัย"
85413350810-0-Talk-1 = "คนที่เป็นพี่อย่างฉัน\nต้องเป็นฝ่ายอดทนค่ะ\nค่ะ แน่นอนค่ะ"
85413340811-0-Talk-1 = "อาริสึ...\nอยากให้ทุกคน\nปลอดภัยค่ะ"
85413340811-0-Talk-2 = "อาริสึหวังแค่นี้เลยค่ะ"
85413370806-0-Talk-1 = "คุณครูก็ดื่มอะไร\nเย็นๆ ด้วยมั้ย?"
85413370815-0-Talk-1 = "จัดระเบียบความคิด\nไม่ได้เลย..."
85413370815-0-Talk-2 = "ถ้าตัวไม่ได้ร้อน\nแต่เป็นหัวที่ร้อน"
85413370815-0-Talk-3 = "จะต้องทำยังไงนะ..."
85413330816-0-Talk-1 = "ที่ฉันยึดมั่นในภารกิจ\nก็เพื่อทุกคนค่ะ"
85413330816-0-Talk-2 = "และก็เพื่อให้\nได้รับคำชมด้วยค่ะ..."
85413310817-0-Think-1 = "(วิธีพูดคุย\nกับผู้คน...)"
85413310817-0-Think-2 = "(ไปขอคำปรึกษา\nเรื่องนี้จากครูดีกว่า...)"
85413320818-0-Talk-1 = "ไม่ต้องเป็นห่วงนะคะ\nฉันยังไหวค่ะ"
85412670904-0-Talk-1 = "ครั้งนี้จะพูดออกไป\nได้มั้ยนะ...\nมาแล้ว! เราเห็นแล้ว!"
85412670904-0-Talk-2 = "ยังไม่...\nชนะอีกเหรอ..."
85412670913-0-Talk-1 = "เราจะชนะใช่มั้ย\nคุณครู?\nฉันเชื่อคุณครูนะ!"
85412689905-0-Talk-1 = "ฉันยัง\nไม่อยากเชื่อเลยค่ะ..."
85412689905-0-Talk-2 = "มาอยู่ที่แบบนี้ได้ยังไงนะ"
85412689914-0-Talk-1 = "ฉันจะทำให้เต็มที่\nจนถึงตอนสุดท้ายเลยค่ะ"
85412689914-0-Talk-2 = "อ่า พอบอกว่าสุดท้าย\nรู้สึกใจคอไม่ดี\nเลยนะคะ..."
85413329909-0-Talk-1 = "การเดินทางอันยาวนาน\nมาถึงจุดไคลแม็กซ์\nแล้วสินะคะ"
85413329918-0-Talk-1 = "คุณครูรู้หรือเปล่าคะ?\nในโหราศาสตร์น่ะ\nไม่มีจุดจบหรอกค่ะ"
85413329918-0-Talk-2 = "ทุกอย่าง\nล้วนเป็นวัฏจักรค่ะ"
