[translation]
10134-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
10134-CVGroup_CharacterGet_Idle1-1 = "อาริสึ ออกโรงค่ะ!"
10134-CVGroup_Cafe_Idle1-1 = "อันนี้เหมือนกับเคย์เปี๊ยบเลยค่ะ!"
10134-CVGroup_Cafe_Idle2-1 = "อาริสึง่วงนิดหน่อยค่ะ..."
10134-CVGroup_Cafe_Idle3-1 = "ที่นี่เป็นเขตห้าม PK ค่ะ!"
10134-CVGroup_Cafe_Idle4-1 = "(สแกนสำเร็จ ไม่พบสัญญาณ... ของศัตรู)"
10134-CVGroup_Cafe_Idle5-1 = "ที่ชาร์จแบตอยู่ไหนคะ?"
10134-CVGroup_WeaponGet_Idle1-1 = "ดาบแห่งแสงช่วยส่องเส้นทางให้กับอาริสึเสมอเลยค่ะ\nเหมือนกับ... คุณครูเลยนะคะ!"
10134-CVGroup_UICarrierLobby_Enter1-1 = "อาริสึ... ใจเต้นตึกตักเลยค่ะ!"
10134-CVGroup_UICarrierLobby_Enter2-1 = "เอาเครื่องเล่นเกมมาด้วยค่ะ!"
10134-CVGroup_UICarrierLobby_Enter2-2 = "คุณครูก็มาเล่นด้วยกันมั้ยคะ?"
10134-CVGroup_UICarrierLobby_Enter3-1 = "ทุกคนยอดเยี่ยมไปเลยค่ะ!"
10134-CVGroup_UICarrierLobby_Enter4-1 = "ทุกคนยอดเยี่ยมมากค่ะ! น่าชื่นชมเลยค่ะ!"
10134-CVGroup_UICarrierLobby_Enter5-1 = "อาริสึยังสู้ได้มากกว่านี้ค่ะ คุณครู!"
10134-CVGroup_UICarrierLobby_Enter6-1 = "โมโมอิกับมิโดริบอกว่าจะไปพักในห้องส่วนตัวค่ะ..."
10134-CVGroup_UICarrierLobby_Idle1-1 = "นี่คือก้าวแรกในการกอบกู้โลกสินะคะ..."
10134-CVGroup_UICarrierLobby_Idle1-2 = "อาริสึจะพยายามค่ะ!"
10134-CVGroup_UICarrierLobby_Idle2-1 = "ในเวลาแบบนี้ การพักผ่อนก็สำคัญค่ะ!"
10134-CVGroup_UICarrierLobby_Idle3-1 = "การได้มีอิสระคือสิ่งที่ดีค่ะ!"
10134-CVGroup_UICarrierLobby_Idle4-1 = "ความกล้าหาญ... คือพลังที่แท้จริงค่ะ!"
10134-CVGroup_UICarrierLobby_Idle5-1 = "ถ้าอยากมีแรง"
10134-CVGroup_UICarrierLobby_Idle5-2 = "ก็ต้องหาอะไรกินค่ะ..."
10134-CVGroup_UICarrierLobby_Idle6-1 = "อาริสึ... อยากให้ทุกคนปลอดภัยค่ะ"
10134-CVGroup_UICarrierLobby_Idle6-2 = "อาริสึหวังแค่นี้เลยค่ะ"
10134-CVGroup_UIEventMission_Enter1-1 = "คุณครู! ภารกิจมาแล้วค่ะ ภารกิจ!"
10134-CVGroup_UIEventMission_Enter2-1 = "งานของวันนี้คืออะไรเหรอคะ?"
10134-CVGroup_UIEventMission_Enter2-2 = "อ๊ะ อาริสึต้องเป็นคนจัดการให้นี่คะ..."
10134-CVGroup_UIEventMission_Enter3-1 = "ขอทักทายทางออนไลน์ค่ะ คุณครู! อาริสึเองนะคะ!"
10134-CVGroup_UIEventMission_Enter4-1 = "กลายเป็นเรื่องใหญ่เข้าให้แล้วนะคะ..."
10134-CVGroup_UIEventMission_Enter4-2 = "แต่เราจะชนะไปด้วยกันค่ะ!"
10134-CVGroup_UIEventMission_Idle1-1 = "ฮุ ฮุ ฮุ..."
10134-CVGroup_UIEventMission_Idle1-2 = "ชุดเกราะใหม่ของอาริสึเป็นยังไงบ้างคะ คุณครู?"
10134-CVGroup_UIEventMission_Idle2-1 = "ถึงจะไม่มีชุดเกราะ..."
10134-CVGroup_UIEventMission_Idle2-2 = "และต่อให้จะไม่มีดาบแห่งแสง..."
10134-CVGroup_UIEventMission_Idle2-3 = "แต่ยังไงอาริสึก็ยังเป็นอาริสึค่ะ"
10134-CVGroup_UIEventMission_Idle2-4 = "ตราบใดที่ได้อยู่กับทุกคน"
10134-CVGroup_UIEventMission_Idle2-5 = "และมีคุณครูอยู่ด้วยน่ะค่ะ!"
10134-CVGroup_UIEventMission_Idle3-1 = "มัลคูธ..."
10134-CVGroup_UIEventMission_Idle3-2 = "เป็นเหมือนกับบอสตัวสุดท้ายสินะคะ!"
10134-CVGroup_UIEventMission_Idle3-3 = "ว่าแต่... คงไม่มีบอสลับตัวอื่นโผล่มาหรอกใช่มั้ยคะ...?"
10134-CVGroup_UIEventMission_Idle4-1 = "ถ้าได้กลับไปอย่างปลอดภัย..."
10134-CVGroup_UIEventMission_Idle4-2 = "อาริสึอยากแนะนำเคย์ให้ทุกคนรู้จักค่ะ!"
10134-CVGroup_UIEventMission_Buy1-1 = "ปาปัม ปาปัม ป๊าม!"
10134-CVGroup_UIEventMission_Buy1-2 = "คุณครูได้รับรางวัลแล้วค่ะ!"
10134-CVGroup_UIEventMission_Buy2-1 = "เยี่ยมมากเลยค่ะ คุณครู!"
10134-CVGroup_UIEventMission_Buy2-2 = "ค่อยๆ ทำไปทีละอย่างนะคะ!"
10134-CVGroup_UIEventMission_Buy3-1 = "ง่า... อาริสึก็อยากไปยินดีกับคุณครูตรงนั้นค่ะ!"
10134-CVGroup_UIEventMission_Buy4-1 = "ค่ะ! อาริสึชอบคุณครูที่เสมอต้นเสมอปลายมากๆ เลยละค่ะ!"
10134-CVGroup_UIEventMission_Interaction1-1 = "ว้าว! อาริสึก็ดีใจค่ะ!"
10134-CVGroup_UIEventMission_Interaction2-1 = "ครั้งนี้ก็ทำได้ดีมากเลยค่ะ คุณครู!"
