[translation]
16019-CVGroup_UITitle_Idle1-1 = "블루, 아카이브."
16019-CVGroup_CharacterGet_Idle1-1 = "퍼펙트 메이드, 퍼펙트 리콘. 아스마 토키입니다.\n같은 배에 탔다고 생각하고, 맡겨만 주십시오."
16019-CVGroup_Cafe_Idle1-1 = "휴식은 중요합니다. 역시 주 3일제가 필요합니다."
16019-CVGroup_Cafe_Idle2-1 = "어디 앉거나 누울 곳은 없을까요."
16019-CVGroup_Cafe_Idle3-1 = "충분한 카페인과 당분은, 임무의 연료입니다."
16019-CVGroup_Cafe_Idle4-1 = "이 카페의 레시피…… 괜찮네요."
16019-CVGroup_Cafe_Idle5-1 = "다음 임무를 위해서라도, 휴식해야 합니다."
16019-CVGroup_WeaponGet_Idle1-1 = "무기를 바꾼다는 것은, 의외로 결심이 필요한 일입니다. 아침 메뉴를 토스트에서 팬케이크로 바꾸는 정도로요.\n하지만 선생님께 받은 것이라면, 조금, 이야기가 다르겠지요."
16019-CVGroup_UICarrierLobby_Enter1-1 = "여기 캐모마일 차입니다."
16019-CVGroup_UICarrierLobby_Enter1-2 = "긴장을 풀어주는 효과가 있다고 하죠."
16019-CVGroup_UICarrierLobby_Enter2-1 = "저의 활약, 선생님만 알아주셨으면 합니다."
16019-CVGroup_UICarrierLobby_Enter3-1 = "심심해지기 시작했습니다. 놀아 주세요."
16019-CVGroup_UICarrierLobby_Enter4-1 = "최근, 취미라고 할 것이 생겼습니다."
16019-CVGroup_UICarrierLobby_Enter5-1 = "정찰인가요? 지시를 부탁드리겠습니다."
16019-CVGroup_UICarrierLobby_Idle1-1 = "퍼펙트 메이드이자 베스트 요원으로서,"
16019-CVGroup_UICarrierLobby_Idle1-2 = "도와드릴 것이 있다면, 말씀 주십시오."
16019-CVGroup_UICarrierLobby_Idle2-1 = "경량 슈트 덕분에, 더 가벼운 동작이 가능해졌습니다."
16019-CVGroup_UICarrierLobby_Idle3-1 = "만화책을 좀 더 가져올 걸 그랬네요."
16019-CVGroup_UICarrierLobby_Idle4-1 = "저장해 둔 인터넷 방송,"
16019-CVGroup_UICarrierLobby_Idle4-2 = "같이 보시겠습니까?"
16019-CVGroup_UICarrierLobby_Idle5-1 = "제가 임무에 충실한 것은, 모두를 위해서입니다."
16019-CVGroup_UICarrierLobby_Idle5-2 = "……그리고 동시에, 칭찬받기 위해서입니다."
16019-CVGroup_UIEventShop_Enter1-1 = "아스마 토키의 상점에 어서 오십시오. 선생님."
16019-CVGroup_UIEventShop_Enter1-2 = "……거짓말이었습니다. 모두의 상점입니다."
16019-CVGroup_UIEventShop_Enter2-1 = "물품 수량은 많이 준비하지 못했습니다만……."
16019-CVGroup_UIEventShop_Enter2-2 = "그래도, 선생님께 도움이 되었으면 합니다."
16019-CVGroup_UIEventShop_Enter3-1 = "아스마 토키. 통신상으로나마 인사드립니다."
16019-CVGroup_UIEventShop_Enter3-2 = "상황이 이렇게 다급하지 않았다면, 직접 뵈었을 텐데요."
16019-CVGroup_UIEventShop_Enter4-1 = "아무리 비상 상황이라도, 토키 표 상점은 영업합니다."
16019-CVGroup_UIEventShop_Idle1-1 = "네. 선생님. 저는 여기에 있습니다."
16019-CVGroup_UIEventShop_Idle1-2 = "도망가지도, 숨지도 않습니다."
16019-CVGroup_UIEventShop_Idle1-3 = "아뇨…… 혹시 사라진다면, 선생님이 저를 애타게 찾아 주시는 걸까요?!"
16019-CVGroup_UIEventShop_Idle2-1 = "어떠신가요, 선생님."
16019-CVGroup_UIEventShop_Idle2-2 = "보온성과 안정성, 그리고 심신 안정 효과도 있는."
16019-CVGroup_UIEventShop_Idle2-3 = "마치 저와도 같은, 우수한 전투복입니다."
16019-CVGroup_UIEventShop_Idle2-4 = "선생님, 저와 함께 슈트의 기능을 확인하시죠."
16019-CVGroup_UIEventShop_Idle2-5 = "원하시는 만큼 제게 붙어 있어도 좋으니, 사양 마시기를."
16019-CVGroup_UIEventShop_Idle3-1 = "잠시 기다려 주십시오."
16019-CVGroup_UIEventShop_Idle3-2 = "퍼펙트 메이드의 기억력으로, 상품 위치를 떠올리겠습니다."
16019-CVGroup_UIEventShop_Idle4-1 = "어쩔 수 없이 온라인 대응 중이지만, 영업에 지장은 없습니다."
16019-CVGroup_UIEventShop_Idle4-2 = "베스트 에이전트는 장소를 가리지 않으니까요."
16019-CVGroup_UIEventShop_Buy1-1 = "구매, 감사합니다."
16019-CVGroup_UIEventShop_Buy1-2 = "말씀만 하시면 저도 구매 가능합니다."
16019-CVGroup_UIEventShop_Buy2-1 = "그것이군요. 알겠습니다."
16019-CVGroup_UIEventShop_Buy2-2 = "재입고가 완료될 때까지, 저와 좋은 시간이라도 보내시겠습니까?"
16019-CVGroup_UIEventShop_Buy3-1 = "이런 걸 좋아하시는 거군요. 알겠습니다."
16019-CVGroup_UIEventShop_Buy4-1 = "네. 여기 있습니다. 다음에 또 찾아 주십시오."
16019-CVGroup_UIEventShop_Buy4-2 = "제 얼굴을 봐서라도요."
16019-CVGroup_UIEventShop_Buy5-1 = "그것은, 좋은 물건입니다."
16019-CVGroup_UIEventShop_Buy6-1 = "그 상품은, 뒤쪽의 선반에서 꺼내주세요."
16019-CVGroup_UIEventShop_Buy7-1 = "잘못 구매한 경우에는 반품이 가능합니다."
16019-CVGroup_UIEventShop_Buy7-2 = "……죄송합니다. 아니라고 합니다."
16019-CVGroup_UIEventShop_Buy8-1 = "원하신다면 저와의 통화권을 서비스로 넣어놓겠습니다."
16019-CVGroup_UIEventShop_Buy8-2 = "당연히 원하시겠지요?"
