[translation]
16020-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
16020-CVGroup_CharacterGet_Idle1-1 = "โอ้ สบายดีมั้ย? เป็นครั้งแรกเลยมั้ยนะที่ฉันทักทายจริงจังแบบนี้\nเท็นจินยามะ โอโทกิ สไนเปอร์จากกองทหาร FOX\nต่อไปก็ขอฝากตัวด้วยนะ คุณครู"
16020-CVGroup_Cafe_Idle1-1 = "(ง่วงจัง… อยากดื่มกาแฟสักแก้ว...)"
16020-CVGroup_Cafe_Idle2-1 = "ดีเลย...! ใช้ช่วงหยุดพักไปเวทเทรนนิ่งดีมั้ยนะ?"
16020-CVGroup_Cafe_Idle3-1 = "โอ้ ทุกคนดูมีพลังล้นเหลือเลยนะ?"
16020-CVGroup_Cafe_Idle4-1 = "(เหมือนเห็นคนที่เคยเจอที่สำนักควบคุมเลยแฮะ...)"
16020-CVGroup_Cafe_Idle5-1 = "โอ้ สินค้าใหม่ของฟรุตเจลลี่\nถ่ายรูปไว้ก่อนดีกว่า"
16020-CVGroup_WeaponGet_Idle1-1 = "ได้รับปืนไรเฟิล FOX รุ่น 82 มาแล้ว สำหรับการซุ่มยิงระยะไกล\nหรือทำลายสิ่งกีดขวาง คงไม่มีอาวุธใดดีไปกว่านี้แล้ว...\nแต่พอยิงไปเรื่อยๆ ไหล่ของฉันก็จะตึงนี่น่ะสิ"
16020-CVGroup_UIEventLobby_Enter1-1 = "ในที่สุดปฏิบัติการก็เริ่มแล้วสินะ..."
16020-CVGroup_UIEventLobby_Enter1-2 = "ความรู้สึกตื่นเต้นพุ่งพล่านขึ้นมาเลย~"
16020-CVGroup_UIEventLobby_Enter2-1 = "ฉันกำลังรออยู่เลย ถ้าไม่มีคุณครู\nก็เริ่มปฏิบัติการไม่ได้นี่นา"
16020-CVGroup_UIEventLobby_Idle1-1 = "<ปฏิบัติการแกะรอยตำนาน> งั้นเหรอ..."
16020-CVGroup_UIEventLobby_Idle1-2 = "ตำนานเป็นสิ่งที่เราไปตามแกะรอยได้จริงๆ เหรอ?"
16020-CVGroup_UIEventLobby_Idle2-1 = "หืม? เรียกฉันเหรอ?"
16020-CVGroup_UIEventLobby_Idle3-1 = "ซูชิเต้าหู้หวานฝีมือนิโกะ\nไม่ว่าจะกินตอนไหนก็อร่อยเหาะตลอดเลย"
16020-CVGroup_UIEventLobby_Idle4-1 = "เป็นห่วงยูกิโนะจัง..."
16020-CVGroup_UIEventLobby_Idle4-2 = "จะยังกังวลเรื่องงานที่ผ่านมาหรือเปล่านะ"
16020-CVGroup_UIEventMission_Enter1-1 = "อ๊ะ คุณครูมาได้จังหวะพอดีเลย"
16020-CVGroup_UIEventMission_Enter1-2 = "ฉันมีลิสต์เรื่องราวที่อยากถามอยู่เพียบเลยละ"
16020-CVGroup_UIEventMission_Enter2-1 = "อ๊ะ พอจะมีเวลาสักครู่มั้ย?"
16020-CVGroup_UIEventMission_Enter2-2 = "ฉันมีเรื่องอยากขอให้ช่วย 2-3 เรื่องน่ะ"
16020-CVGroup_UIEventMission_Idle1-1 = "หืม? ทำไมถึงจ้องผมฉันขนาดนั้นล่ะ?"
16020-CVGroup_UIEventMission_Idle1-2 = "มีอะไรให้ต้องใส่ใจงั้นเหรอ?"
16020-CVGroup_UIEventMission_Idle1-3 = "อ๋อ เวลาอยู่ในที่แคบๆ เส้นผมอาจจะไปเกี่ยวนู่นนี่ได้น่ะ"
16020-CVGroup_UIEventMission_Idle1-4 = "ฉันก็เลยถักผมเองทุกวัน"
16020-CVGroup_UIEventMission_Idle1-5 = "ถึงจะเคยคิดว่ามันน่ารำคาญจนอยากตัดทิ้งเลยก็เถอะ..."
16020-CVGroup_UIEventMission_Idle1-6 = "แต่พอไว้ยาวถึงขนาดนี้แล้วมันก็รู้สึกเสียดายน่ะ"
16020-CVGroup_UIEventMission_Idle2-1 = "ฮะ... เฮือก?! อย่ามาจิ้มกันได้มั้ย?"
16020-CVGroup_UIEventMission_Idle2-2 = "ฉันไม่ชอบที่จู่ๆ ก็ถูกซุ่มโจมตีจากข้างหลังน่ะ..."
16020-CVGroup_UIEventMission_Buy1-1 = "โอ้... อย่างนี้นี่เอง"
16020-CVGroup_UIEventMission_Buy1-2 = "ที่เล่าลือกันให้แซ่ด ก็มีเหตุผลจริงๆ สินะ"
16020-CVGroup_UIEventMission_Buy2-1 = "เสร็จแล้วเหรอ? ว้าว... ไวจังเลย"
16020-CVGroup_UIEventMission_Buy2-2 = "ถ้าฝีมือขนาดนี้เรียกว่า 'ผู้บัญชาการ' น่าจะเหมาะกว่านะ?"
16020-CVGroup_UIEventMission_Interaction1-1 = "อืม วันนี้ทำเท่านี้ก็เพียงพอแล้วละ\nทำได้ดีมากเลย!"
