[translation]
20056-CVGroup_UITitle_Idle1-1 = "블루~ 아카이브!"
20056-CVGroup_CharacterGet_Idle1-1 = "니하하하! 이 코유키에게 와버리셨군요! 선생님!"
20056-CVGroup_Cafe_Idle1-1 = "(어디 보자, 숨을 만한 곳이…….)"
20056-CVGroup_Cafe_Idle2-1 = "(여기…… 세미나 카드로도 결제 되려나?)"
20056-CVGroup_Cafe_Idle3-1 = "설마 여기까지 쫓아오지는 않겠지……?"
20056-CVGroup_Cafe_Idle4-1 = "선생님? 선생님! 어디 계세요?"
20056-CVGroup_Cafe_Idle5-1 = "오늘의 커피는…… 원두가 랜덤?! 으으, 랜덤은 싫은데……."
20056-CVGroup_WeaponGet_Idle1-1 = "……분명, 저의 최고의 행운은 선생님이겠죠! 그러니까! 최선을 다하겠습니다! 감사합니다!"
20056-CVGroup_UIEventLobby_Enter1-1 = "누, 누구야?!"
20056-CVGroup_UIEventLobby_Enter1-2 = "……아, 선생님이셨군요!!"
20056-CVGroup_UIEventLobby_Enter2-1 = "오셨군요 선생님!"
20056-CVGroup_UIEventLobby_Enter2-2 = "판 깔아놨으니,"
20056-CVGroup_UIEventLobby_Enter2-3 = "일단 앉으시죠!"
20056-CVGroup_UIEventLobby_Enter3-1 = "와버리셨군요!"
20056-CVGroup_UIEventLobby_Enter3-2 = "역시 못 참겠죠? 그렇죠?!"
20056-CVGroup_UIEventLobby_Enter4-1 = "후후, 저만 믿으시라고요."
20056-CVGroup_UIEventLobby_Enter4-2 = "탈출은, 이 쿠로사키 코유키의 전문영역이니까!"
20056-CVGroup_UIEventLobby_Enter5-1 = "뭔가 많은 일이 있었던 것 같은데……"
20056-CVGroup_UIEventLobby_Enter5-2 = "뭐, 일단은"
20056-CVGroup_UIEventLobby_Enter5-3 = "밤새 놀아보자……!"
20056-CVGroup_UIEventLobby_Enter5-4 = "……고……요……"
20056-CVGroup_UIEventLobby_Enter5-5 = "피휴우우……."
20056-CVGroup_UIEventLobby_Idle1-1 = "촉감 좋죠? 이 옷, 제법 보들보들 하다고요!"
20056-CVGroup_UIEventLobby_Idle2-1 = "구해주러 오셨군요, 선생님!"
20056-CVGroup_UIEventLobby_Idle2-2 = "에, 선생님도 잡힌 거라고요?!"
20056-CVGroup_UIEventLobby_Idle3-1 = "이 보드게임 이상해요!"
20056-CVGroup_UIEventLobby_Idle3-2 = "제 차례만 되면 터진다니까요!!"
20056-CVGroup_UIEventLobby_Idle4-1 = "북적북적한 반성실이라니……"
20056-CVGroup_UIEventLobby_Idle4-2 = "뭐, 이것도 나쁘진 않다랄까……요?"
