[translation]
20056-CVGroup_UITitle_Idle1-1 = "Blue~~ Archive!"
20056-CVGroup_CharacterGet_Idle1-1 = "วะฮ่าฮ่าฮ่า!\nในที่สุดก็มาหาโคยูกิแล้วสินะคะ! คุณครู!"
20056-CVGroup_Cafe_Idle1-1 = "(ไหนดูซิ มีตรงไหนที่ซ่อนได้บ้าง...)"
20056-CVGroup_Cafe_Idle2-1 = "(ที่นี่... ใช้บัตรของเซมิน่าจ่ายเงินได้มั้ยนะ?)"
20056-CVGroup_Cafe_Idle3-1 = "คงจะไม่ไล่ตามมาถึงที่นี่หรอกใช่มั้ย...?"
20056-CVGroup_Cafe_Idle4-1 = "คุณครู คุณครู! อยู่ไหนเหรอคะ?"
20056-CVGroup_Cafe_Idle5-1 = "กาแฟวันนี้... สุ่มเมล็ดงั้นเหรอ?!\nฮือ ฉันไม่ชอบการสุ่มเลย..."
20056-CVGroup_WeaponGet_Idle1-1 = "แน่นอนว่าโชคดีที่สุดของฉันก็คือคุณครูยังไงล่ะคะ!\nเพราะงั้น! ฉันจะทำให้ดีที่สุดค่ะ! ขอบคุณค่ะ!"
20056-CVGroup_UIEventLobby_Enter1-1 = "คะ... ใครน่ะ?!"
20056-CVGroup_UIEventLobby_Enter1-2 = "อ๊ะ... คุณครูเองเหรอคะ!!"
20056-CVGroup_UIEventLobby_Enter2-1 = "มาแล้วสินะคะ คุณครู!"
20056-CVGroup_UIEventLobby_Enter2-2 = "ฉันปูพื้นไว้ให้แล้ว"
20056-CVGroup_UIEventLobby_Enter2-3 = "มานั่งก่อนสิคะ!"
20056-CVGroup_UIEventLobby_Enter3-1 = "มาแล้วสินะคะ!"
20056-CVGroup_UIEventLobby_Enter3-2 = "คงทนไม่ไหวสินะคะ?\nใช่มั้ยล่ะคะ?!"
20056-CVGroup_UIEventLobby_Enter4-1 = "ฮุฮุ เชื่อมือฉันสิคะ"
20056-CVGroup_UIEventLobby_Enter4-2 = "คุโรซากิ โคยูกิคนนี้น่ะเชี่ยวชาญเรื่องการหลบหนีนะคะ!"
20056-CVGroup_UIEventLobby_Enter5-1 = "เหมือนจะมีเรื่องอะไรเยอะเลยแฮะ..."
20056-CVGroup_UIEventLobby_Enter5-2 = "แต่เอาเป็นว่า"
20056-CVGroup_UIEventLobby_Enter5-3 = "มาสนุกกันทั้งคืนก่อนดีกว่า...!"
20056-CVGroup_UIEventLobby_Enter5-4 = "นะ... คะ..."
20056-CVGroup_UIEventLobby_Enter5-5 = "เฮือก..."
20056-CVGroup_UIEventLobby_Idle1-1 = "สัมผัสดีใช่มั้ยล่ะคะ?\nชุดนี้น่ะนุ่มมากเลยนะคะ!"
20056-CVGroup_UIEventLobby_Idle2-1 = "มาช่วยฉันแล้วสินะคะ คุณครู!"
20056-CVGroup_UIEventLobby_Idle2-2 = "เอ๋ คุณครูก็ถูกจับงั้นเหรอคะ?!!"
20056-CVGroup_UIEventLobby_Idle3-1 = "บอร์ดเกมอันนี้มันแปลกๆ นะคะ!"
20056-CVGroup_UIEventLobby_Idle3-2 = "พอถึงตาฉันทีไร มันก็ระเบิดทุกทีเลยค่ะ!!"
20056-CVGroup_UIEventLobby_Idle4-1 = "ห้องสำนึกผิดวุ่นวายขนาดนี้เลย..."
20056-CVGroup_UIEventLobby_Idle4-2 = "เอาเถอะ แบบนี้ก็คงไม่แย่เท่าไร... สินะคะ?"
