[translation]
10136-CVGroup_Battle_Buffed_1-1 = "ขอบคุณนะ ช่วยสนับสนุนต่อไปด้วยนะ"
10136-CVGroup_Battle_Defense_1-1 = "ยืนยันป้องกันการโจมตีสำเร็จ"
10136-CVGroup_Battle_In_1-1 = "ฉันระวังหลังเอง"
10136-CVGroup_Battle_In_2-1 = "ตรวจพบสัญญาณผิดปกติ"
10136-CVGroup_Battle_Move_1-1 = "ไปยังพื้นที่ต่อไป"
10136-CVGroup_Battle_Move_2-1 = "ควบคุมพื้นที่สำเร็จ"
10136-CVGroup_Battle_Recovery_1-1 = "ยืนยันการสนับสนุนทางยุทธวิธี"
10136-CVGroup_Battle_TacticalAction_1-1 = "ดำเนินยุทธวิธี"
10136-CVGroup_Battle_Victory_1-1 = "เห็นรึเปล่า คุณครู? ฉันทำได้แล้ว"
10136-CVGroup_Battle_Victory_2-1 = "ตอนนี้ไม่เป็นไรแล้วละ คุณครู ไม่มีศัตรูแล้ว"
10136-CVGroup_CommonSkill-1 = "ค่อนข้างร้อนเลยนะเนี่ย"
10136-CVGroup_ExSkill_1-1 = "กำจัดเป้าหมาย"
10136-CVGroup_ExSkill_2-1 = "ไปยังพื้นที่ต่อไป"
10136-CVGroup_ExSkill_3-1 = "ร้อนจริงๆ ด้วยนะ"
10136-CVGroup_ExSkill_Level_1-1 = "อื้อ ฉันจะพยายาม"
10136-CVGroup_ExSkill_Level_2-1 = "เริ่มกำหนดเป้าหมาย"
10136-CVGroup_ExSkill_Level_3-1 = "ตรงนั้น"
10136-CVGroup_Formation_In_1-1 = "ระบุเป้าหมายให้หน่อยสิ"
10136-CVGroup_Formation_In_2-1 = "วันนี้ฉันเป็นพลแม่นปืนละ"
10136-CVGroup_Formation_Select-1 = "ล็อกเป้าหมายหัวใจคุณครู\nคิดแล้วเชียว... ไม่ไหวจริงๆ ด้วย"
10136-CVGroup_Growup_1-1 = "ฉันเก่งขึ้นบ้างรึเปล่านะ"
10136-CVGroup_Growup_2-1 = "การพัฒนาอย่างเหมาะสมเป็นเรื่องสำคัญ\nอย่างน้อยก็เพื่อประสิทธิภาพในการทำภารกิจ"
10136-CVGroup_Growup_3-1 = "ขอบคุณนะ คุณครู\nฉันแข็งแกร่งขึ้นได้เพราะคุณครูเลยละ"
10136-CVGroup_Growup_4-1 = "ฉันเองก็เปลี่ยนไปบ้างรึเปล่านะ?\nเพราะท้ายที่สุดแล้วมนุษย์ก็เปลี่ยนแปลงไป\nจากการเฝ้ามองกันและกัน"
10136-CVGroup_Relationship_Up_1-1 = "ช่วงนี้ฉันคิดเรื่องนี้อยู่บ่อยๆ\nฉันคิดว่าตัวเองมีนิสัยชอบทำตามใจตัวเองอยู่บ้าง\nเพราะงั้น... การมีคุณครูคอยเฝ้าดูฉันอยู่ตลอด\nก็น่าจะเป็นวิธีที่มีประสิทธิภาพกว่าไม่ใช่เหรอ?"
10136-CVGroup_Relationship_Up_2-1 = "มาทางนี้อีกหน่อยสิ\nดูสิ พออยู่ชิดกันแล้วดีขึ้นเยอะเลย\nแชร์ความอบอุ่นของร่างกายกันแบบนี้ มันมีประสิทธิภาพดีใช่มั้ยล่ะ?"
10136-CVGroup_Relationship_Up_3-1 = "พอมองย้อนกลับไป โลกของเราเนี่ยมีเรื่องน่าพิศวงเยอะเลยนะ\nแต่ว่าเรื่องพิศวงที่สุดสำหรับฉัน...\nก็คงเป็นคุณครูละมั้ง\nฮุฮุ เพราะคุณครูน่ะเป็นคนตลกจริงๆ นี่นา"
10136-CVGroup_Relationship_Up_4-1 = "ถ้ามีเรื่องอะไรละก็ ติดต่อฉันนะ\nฉันจะปกป้องคุณครูเอง\nไม่ว่าจะต้องแลกด้วยอะไรก็ตาม"
10136-CVGroup_Tactic_In_1-1 = "เริ่มสำรวจแหล่งพลังงาน"
10136-CVGroup_Tactic_In_2-1 = "ค้นหาและทำลาย"
10136-CVGroup_Tactic_Victory_1-1 = "เป็นไงคุณครู? ฉันทำได้ดีใช่มั้ย?"
10136-CVGroup_Tactic_Victory_2-1 = "พื้นที่นี้ปลอดภัยแล้วละ"
