[translation]
20005-CVGroup_CommonSkill-1 = "This is the highly-exclusive, limited-edition Peroro bomb!"
20005-CVGroup_ExSkill_1-1 = "C-Calm down, Crusadie!"
20005-CVGroup_ExSkill_2-1 = "Wh-Whoa!"
20005-CVGroup_ExSkill_3-1 = "I-I'm going to fall!"
20005-CVGroup_ExSkill_Level_1-1 = "M-Moving!"
20005-CVGroup_ExSkill_Level_2-1 = "W-Wait, the controls are...! "
20005-CVGroup_ExSkill_Level_3-1 = "T-Tank advancing!"
20005-CVGroup_Formation_In_1-1 = "Are we going swimming now?"
20005-CVGroup_Formation_In_2-1 = "It's a perfect day for a vacation!"
20005-CVGroup_Formation_Select-1 = "Eh?"
20005-CVGroup_Growup_1-1 = "Heehee... I wonder if I'm any fancier with this..."
20005-CVGroup_Growup_2-1 = "I'll try even harder!"
20005-CVGroup_Growup_3-1 = "I practiced swimming just in case."
20005-CVGroup_Growup_4-1 = "Anything for Peroro!"
20005-CVGroup_Relationship_Up_1-1 = "As long as I get to spend time with you, Sensei, this summer will be the best one yet!"
20005-CVGroup_Relationship_Up_2-1 = "When I'm with you, Sensei, even the darkest depths of the ocean don't scare me!"
20005-CVGroup_Relationship_Up_3-1 = "My heart... It's all aflutter."
20005-CVGroup_Relationship_Up_4-1 = "Sensei, please spend time with me next summer too!"
