[translation]
20013-CVGroup_CommonSkill-1 = "보안상의 약점, 복구할게."
20013-CVGroup_ExSkill_1-1 = "이런 크래킹은 좋아하지 않지만……."
20013-CVGroup_ExSkill_2-1 = "귀여운 후배들을 위해서라면 어쩔 수 없지."
20013-CVGroup_ExSkill_3-1 = "……하아, 이런 건 이번 뿐이야."
20013-CVGroup_ExSkill_Level_1-1 = "좀 더 보안의식을 갖는 게 좋을 거야."
20013-CVGroup_ExSkill_Level_2-1 = "……응, 전부 보였어."
20013-CVGroup_ExSkill_Level_3-1 = "……BOOM!"
20013-CVGroup_Formation_In_1-1 = "……응? 새로운 보안 취약점이 발견되었나 보지?"
20013-CVGroup_Formation_In_2-1 = "알겠어. 바로 갈게."
20013-CVGroup_Formation_Select-1 = "흐아아암…… 읏! ……커피 좀 부탁해도 될까?"
20013-CVGroup_Growup_1-1 = "응, 역시 배움에 끝은 존재하지 않는 법이야."
20013-CVGroup_Growup_2-1 = "선생님이 가져다 주는 지식은 언제나 새로운 것 뿐이네."
20013-CVGroup_Growup_3-1 = "고마워, 선생님. 조금 더 이해가 늘었어."
20013-CVGroup_Growup_4-1 = "헤에……. 좋은 데이터네."
20013-CVGroup_Relationship_Up_1-1 = "선생님을 해킹 하고 싶지는 않으니까…… \n생각하는 건 솔직하게 알려줬으면 해."
20013-CVGroup_Relationship_Up_2-1 = "나는 항상 여기에서, 선생님을 지원하고 있으니까."
20013-CVGroup_Relationship_Up_3-1 = "선생님처럼 무른 사람은, 아무래도 내버려 둘 수 없어서…….\n……어디까지나 보안의 이야기야."
20013-CVGroup_Relationship_Up_4-1 = "선생님, 그……. 오늘 밤, 심야의 보안 점검을 하러 가도 괜찮을까?"
