[translation]
20040-CVGroup_CommonSkill-1 = "Their weakness is...here."
20040-CVGroup_ExSkill_1-1 = "You're becoming stronger...much stronger."
20040-CVGroup_ExSkill_2-1 = "Now, do your best for me."
20040-CVGroup_ExSkill_3-1 = "How was it? Do you think you've gotten stronger?"
20040-CVGroup_ExSkill_Level_1-1 = "How was it? Effective, right?"
20040-CVGroup_ExSkill_Level_2-1 = "Pandemonium Society, it's an all-out attack!"
20040-CVGroup_ExSkill_Level_3-1 = "Fufu, this is my strength."
20040-CVGroup_Formation_In_1-1 = "It's time for my hypnosis to shine!"
20040-CVGroup_Formation_In_2-1 = "You need me, right?"
20040-CVGroup_Formation_Select-1 = "Heehee, you don't have to grab me like that, you know?"
20040-CVGroup_Growup_1-1 = "Fufu... This feels nice. Aren't things going well?"
20040-CVGroup_Growup_2-1 = "I feel I've gotten a bit stronger."
20040-CVGroup_Growup_3-1 = "Heehee. Keep it up, Sensei. Okay?"
20040-CVGroup_Growup_4-1 = "Phew... The goal is as good as completed. You have my thanks, Sensei."
20040-CVGroup_Relationship_Up_1-1 = "The process of building trust."
20040-CVGroup_Relationship_Up_2-1 = "Do you trust me, Sensei?"
20040-CVGroup_Relationship_Up_3-1 = "Fufu, I feel the distance between us getting smaller. By...quite a bit?"
20040-CVGroup_Relationship_Up_4-1 = "I require you to continue to stay by my side, Sensei. ...Right to refuse? Do you really think you have that? Heehee."
