[translation]
10037-100370010 = "Suspicious..."
10037-100370020 = "What is?"
10037-100370030 = "Snacks are mysteriously disappearing from the School Lunch Club."
10037-100370040 = "Most notably, the pudding count is significantly less than what's recorded on the ledger."
10037-100370050 = "Maybe you miscounted?"
10037-100370060 = "Maybe someone ate them?"
10037-100370070 = "That's impossible."
10037-100370080 = "I've done the math several times, along with other Security Council members."
10037-100370090 = "That's impossible."
10037-100370100 = "The Security Council has been watching the School Lunch Club facility like hawks!"
10037-100370110 = "So if it's not a miscount, and nobody ate them..."
10037-100370120 = "There must be a spy trying to sabotage Red Winter Academy!"
10037-100370130 = "A spy?"
10037-100370140 = "Red Winter Academy is very large. There are students we don't know much about because our student records haven't been fully digitized."
10037-100370150 = "It's very possible there's a spy from another academy among the students."
10037-100370160 = "The spy must be trying to cause internal conflict by going after our weaknesses. How disgraceful."
10037-100370170 = "So starting today, a special spy search operation begins!"
10037-100370180 = "Sensei, we've had another spy incident."
10037-100370190 = "That disgraceful spy stole President Cherino's pudding."
10037-100370200 = "How do you know it was a spy?"
10037-100370210 = "Because Red Winter Academy's security system is flawless!"
10037-100370220 = "Without some kind of sabotage, there's no way this could happen."
10037-100370230 = "So, it must be a spy."
10037-100370240 = "But for some reason, President Cherino thinks I'm the thief."
10037-100370250 = "I do have a hunch why she thinks that."
10037-100370260 = "But I'll catch the spy and prove my innocence!"
10037-100370270 = "Bad news, Sensei."
10037-100370280 = "I'm getting severely punished for shooting President Cherino's statue."
10037-100370290 = "Are you going to the Former Institute?"
10037-100370300 = "I'll visit you when I can."
10037-100370310 = "No, I am not going to the Former Institute!"
10037-100370320 = "Thanks to President Cherino's mercy, I avoided harsh punishment."
10037-100370330 = "But I have to clean the bathroom for a week, just like last time..."
10037-100370340 = "It's embarrassing and disgusting work, but it's President Cherino's order."
10037-100370350 = "I will always follow our president's will!"
10037-100370360 = "You have a lot of work to do."
10037-100370370 = "Huh? What do you mean?"
10037-100370380 = "You're gonna clean the bathroom with me, Sensei."
10037-100370390 = "Says who?!"
10037-100370400 = "Says me, because you were there when the president's statue was destroyed."
10037-100370410 = "It's everyone's duty to protect the mustache's authority. Therefore, you're also responsible for this light treason."
10037-100370420 = "We'll start bright and early tomorrow. Meet me at 7AM in front of the Secretariat building!"
10037-100370430 = "This is nonsense..."
10037-100370440 = "Hey, Sensei."
10037-100370450 = "Could we meet somewhere?"
10037-100370460 = "I'm in trouble and can't tell other Secretariat members."
10037-100370470 = "Okay, I'll be there soon."
10037-100370480 = "What happened?"
10037-100370490 = "I'm sorry to ask you to come to the Secretariat..."
10037-100370500 = "I was arrested by the Security Council."
10037-100370510 = "So you really are in trouble."
