[translation]
13012-130120010 = "Sensei, it's time for patrol!"
13012-130120020 = "We patrolled the north district last time, so let's patrol the central district today!"
13012-130120030 = "But today's supposed to be a day off..."
13012-130120040 = "Why don't we take some rest?"
13012-130120050 = "Nope! Crime happens in the streets, not in the office."
13012-130120060 = "Even as we speak..."
13012-130120070 = "There's crime happening that the civilians need our help to stop!"
13012-130120080 = "If that's supposed to convince me, it's not working."
13012-130120090 = "We have a case on our hands, Sensei!"
13012-130120100 = "According to the report, a thug has taken a hostage in front of a jeweler in Shiba Town."
13012-130120110 = "But it seems the negotiator is stuck in a traffic jam."
13012-130120120 = "Um..."
13012-130120130 = "If I happen to get there first and negotiate successfully..."
13012-130120140 = "Wouldn't the VIPs at Valkyrie value my ability?"
13012-130120150 = "Wouldn't it be better to wait for a professional negotiator?"
13012-130120160 = "I don't think so. Imagine what must be going through the hostage's mind."
13012-130120170 = "I may not be an official officer, but I can't let the negotiation be delayed any longer!"
13012-130120180 = "Kirino, at your service!"
13012-130120190 = "Ugh, Sensei... (T_T)"
13012-130120200 = "I got a warning from the VIPs for the hostage case last time."
13012-130120210 = "If only my aim were better."
13012-130120220 = "How do I become a better shot, Sensei?"
13012-130120230 = "I don't think I can help you there..."
13012-130120240 = "Then could you at least watch me practice?"
13012-130120250 = "Stopping bad habits or posture could help improve my accuracy too."
13012-130120260 = "That I can do."
13012-130120270 = "Thank you, Sensei!"
13012-130120280 = "Then I'll meet you at the shooting range!"
13012-130120290 = "Ugh. I'm so nervous..."
13012-130120300 = "What's the matter?"
13012-130120310 = "Kindergarten students will be visiting Valkyrie in the afternoon..."
13012-130120320 = "And I'll be their guide."
13012-130120330 = "I'm worried that I might get too nervous and make mistakes..."
13012-130120340 = "I'll help you out, then."
13012-130120350 = "You're going to come help me in person?"
13012-130120360 = "That's a relief. Thank you, Sensei!"
13012-130120370 = "You seem to be taking this seriously."
13012-130120380 = "Of course. This is the best opportunity to show the good side of police to the young students."
13012-130120390 = "It was a field trip just like this that inspired me."
13012-130120400 = "I want to come off as cool as the officers did back then."
13012-130120410 = "Kirino."
13012-130120420 = "Huh?"
13012-130120430 = "Whatever you do, don't pull out your gun. Even in a panic."
13012-130120440 = "I-I know that! Give me some credit!"
