[translation]
16009-160090010 = "Domo, Sensei. I am Michiru."
16009-160090020 = "Umm... Michiru? What's going on?"
16009-160090030 = "This is how ninja nerds like us traditionally greet each other!"
16009-160090040 = "You must accept this way of greeting to be my ninja nerd friend...and ultimately, my ninja companion!"
16009-160090050 = "I don't remember agreeing to this..."
16009-160090060 = "Ugh... It's so upsetting to hear that!"
16009-160090070 = "Come on, Sensei... Did you forget?! "
16009-160090080 = "Late at night...under the moon, talking about ambushes...just you and me!"
16009-160090090 = "Oh, just so you know, \"ambush\" is ninja slang for secretive movement in the bushes. Don't forget it!"
16009-160090100 = "I don't remember that at all! What ambush are you talking about?!"
16009-160090110 = "Well, let's not worry about the details!"
16009-160090120 = "Don't be disappointed, though! You have the rare potential to be a ninja."
16009-160090130 = "You have a bright future! As president of the Ninjutsu Research Club, I can vouch for you!"
16009-160090140 = "Um... Th-Thanks, I guess...?"
16009-160090150 = "Wahaha! Don't mention it!"
16009-160090160 = "So, Michiru, why did you contact me today?"
16009-160090170 = "Oh! We're gonna miss the train!"
16009-160090180 = "I must take my leave! I look forward to seeing you again someday! Adios! Sayonara!"
16009-160090190 = "*pop pop pop pop* <- smoke bomb sound"
16009-160090200 = "Huh? Sound effects and everything..."
16009-160090210 = "Umm, anyway, adios! Sayonara!"
16009-160090220 = "I'll visit Schale this afternoon. - Ninja M"
16009-160090230 = "I guess you did give me notice, but..."
16009-160090240 = "That's not how a ninja gives notice. That's more like a mysterious thief..."
16009-160090250 = "Come on! Don't worry about the details!"
16009-160090260 = "Also, mysterious thieves are kind of related to ninjas, so it's okay!"
16009-160090270 = "Everything's related to ninjas, huh?!"
16009-160090280 = "Wahaha! Anyway, I gave you notice, so you shall wait for me!"
16009-160090290 = "I'll see you soon!"
16009-160090300 = "*pop pop pop pop* <- smoke bomb sound"
16009-160090310 = "*swoosh* <- retreating quickly"
16009-160090320 = "...Even more sound effects?"
16009-160090330 = "As you know, I'm president of the Ninjutsu Research Club."
16009-160090340 = "Yeap. Sure."
16009-160090350 = "But it's an unofficial club. Is it okay to call yourself a president?"
16009-160090360 = "Argh! That was unnecessary! I know what I'm doing!"
16009-160090370 = "I work very hard all the time! Studying ninjas, creating content..."
16009-160090380 = "If I keep up the good work, one day I'll be promoting ninjas to everyone in Kivotos and the Ninjutsu Research Club will be recognized as an official club!"
16009-160090390 = "Yeah, I know you're working hard, Michiru. You have my support."
16009-160090400 = "Wahaha! Thanks, Sensei! That means a lot to me."
16009-160090410 = "I'm glad to hear that..."
16009-160090420 = "I'm not just saying that. You have no idea how much you're helping me."
16009-160090430 = "Your support is so powerful that all of my hesitation has completely disappeared!"
16009-160090440 = "Huh?"
16009-160090450 = "I shouldn't hold back on investing into my efforts, right?"
16009-160090460 = "I hear new ninja merch arrived at one of my favorite stores."
16009-160090470 = "I-I mean, ninjutsu tools!"
16009-160090480 = "The stuff is kind of expensive, so I was hesitant...but now I've changed my mind!"
16009-160090490 = "Yeah! It's an investment into my future!"
16009-160090500 = "You're so greedy..."
16009-160090510 = "Wahaha! I'll be waiting for you, Sensei!"
16009-160090520 = "*swoosh* *tatatatat* <- sound of running super fast"
16009-160090530 = "O-Okay... Got it."
16009-160090540 = "Oh, Sensei. Can you look for that thing in the Schale office?"
16009-160090550 = "Thing? What thing?"
16009-160090560 = "The manga I always read. \"Kama-Boko Gale Battle, Volume 19.\" "
16009-160090570 = "I searched the club room everywhere for it but couldn't find it. It's gotta be in the office."
16009-160090580 = "When did you even bring it to Schale?"
16009-160090590 = "Huh...? Well, our club room is temporary, and we don't know when those Hyakkaryouran jerks will invade."
16009-160090600 = "The Yin-Yang Club also comes in and causes commotions."
16009-160090610 = "According to my ninja brain..."
16009-160090620 = "It only made sense to keep the precious item at Schale."
16009-160090630 = "Schale is not a storage facility, Michiru..."
16009-160090640 = "Oh! If you ever get bored, you should read it! I highly recommend the Kama-Boko series!"
16009-160090650 = "Also, I should remind you we're gathering at the park tonight. Don't forget!"
16009-160090660 = "I'll be waiting for you, Sensei!"
16009-160090670 = "What a quick change of subject! "
16009-160090680 = "Anyway, what are you gonna do tonight?"
16009-160090690 = "*shwoop shwoop shwoop shwoop* <- sound of tying shoelaces"
16009-160090700 = "Is that supposed to be a ninja action too...?"
16009-160090710 = "Sensei. I think...that yesterday... "
16009-160090720 = "I think...I caught a cold..."
16009-160090730 = "...Okay. I'll make you some soup."
16009-160090740 = "Um... O-Okay. Thanks, Sensei."
16009-160090750 = "I-I'll be waiting..."
16009-160090760 = "Honorable Sensei."
16009-160090770 = "Ancient records from past eras"
16009-160090780 = "and old records from ancient times..."
16009-160090790 = "Have I piqued your interest?"
16009-160090800 = "Could it be THAT...?! "
16009-160090810 = "The ancient ninja's scrolls?!"
16009-160090820 = "I knew you'd say that, Honorable Sensei! "
16009-160090830 = "But you're wrong!"
16009-160090840 = "Nyahaha! You've fallen into my trap!"
16009-160090850 = "Me?! Wrong?!"
16009-160090860 = "Well technically speaking "
16009-160090870 = "you're like half right... "
16009-160090880 = "So, if you're curious"
16009-160090890 = "meet me by the shopping district entrance we normally meet at!"
16009-160090900 = "I'll be waiting, Honorable Sensei!"
16009-160090910 = "*Shubababa* <- me running super fast"
16009-160090920 = "O-Okay... "
