[translation]
10070-10 = "Blue, Archive."
10070-20 = "I am Konoe Mina, executive officer of Shanhaijing Academy's Genryumon. I'll take care of anything or anyone that gets in our way!"
10070-30 = "They say every lost ship needs a lighthouse to lean on. Ah... F-Forget I said that!"
10070-40 = "The scent of tea hangs in the air... I'm not good at making it, but it came out pretty good."
10070-50 = "A place where nothing moves, not even a muscle... That's what this place is."
10070-60 = "The cafes in Shanhaijing are more like tea houses..."
10070-70 = "It smells good... Maybe I should relax a bit."
10070-80 = "Oh, it's you, Sensei. To meet you in a place like this... This is a small world indeed."
10070-90 = "Oh? You think I'd obviously meet you since we're at Schale...?"
10070-100 = "Y-Yeah..."
10070-110 = "I've been waiting for you, Sensei."
10070-120 = "What does the world have in store for us today? I'm excited."
10070-130 = "No person can live alone..."
10070-140 = "It's a cliché, but I don't hate it."
10070-150 = "Humans should be wary of other humans... But humans must also trust their fellow humans."
10070-160 = "Should I trust you, Sensei? Or..."
10070-170 = "Don't worry so much, Sensei. Everything will be okay by tomorrow."
10070-180 = "Movies are a great thing. Especially those that have passed the test of time."
10070-190 = "They don't survive because they are classics. They are called classics because they survived."
10070-200 = "Sometimes I wish I could really be someone."
10070-210 = "I don't care who it would be. Just anyone greater than me."
10070-220 = "Perhaps, that is why... I enjoy movies."
10070-230 = "Congratulations, Sensei. For what? Why! Your birthday of course!"
10070-240 = "My gift is...top 10 noir movies selected by me!"
10070-250 = "Let's watch them together!"
10070-260 = "Heh... Being wished happy birthday by Sensei. Not bad."
10070-270 = "I can't stand sitting around all day like some kind of desk jockey."
10070-280 = "Hang out with me today!"
10070-290 = "It's a new year... Happy New Year, Sensei."
10070-300 = "Sensei, do you have a new year resolution?"
10070-310 = "Mine, of course, is to live an even more hard-boiled life."
10070-320 = "Is there a Christmas...festival?"
10070-330 = "The word festival seems to mean many different things."
10070-340 = "...What's with the look? I didn't mean anything by it."
10070-350 = "Is it Halloween...? That's a favorite for kids everywhere."
10070-360 = "Maybe I should stop by the Plum Blossom Garden and pass out some candy..."
10070-370 = "Sensei, if it's okay with you, why don't you join me?"
10070-390 = "That's right... I love the world of rainy days."
10070-400 = "Everything becomes so simple."
10070-410 = "White and black. The world of noir."
10070-420 = "The real world is so bright and colorful, it's blinding."
10070-430 = "But most people don't realize this truth..."
10070-440 = "And I'm no exception."
10070-450 = "But the world of noir is not like that."
10070-460 = "It's easy to understand."
10070-470 = "But... then again... An umbrella, at least,"
10070-480 = "should be bright and colorful so you never lose your way."
10070-2600 = "Amazing... It fits perfectly. Like it was mine all along. Heh heh. I'm all ready now. Shall we go?"
