[translation]
20055-10 = "蔚藍……呼……！檔案！"
20055-20 = "千年科學學園……\n遊戲開發部的花岡柚子……\n雖，雖然是這副打扮……\n還請，多多指教……"
20055-30 = "（和平的日常……\n現在已經非常了解\n它的珍貴了）"
20055-40 = "沙發……\n不會突然發射吧……？"
20055-50 = "暖暖又香香的……\n真不錯呢。耶嘿嘿。"
20055-60 = "櫃子……暫時不想\n進去了……嗚嗚。"
20055-70 = "果然，這個……\n有點太華麗了嗎……？\n嗚嗚嗚……"
20055-80 = "嗚咿……！\n這，這副打扮，那個……"
20055-90 = "……歡，歡迎回來，老師。"
20055-100 = "我，我一直在等你，\n老師……！"
20055-110 = "快點出擊……"
20055-120 = "不，不對。\n開始值日生的工作吧……！"
20055-130 = "這件戰鬥服，雖然\n比想像中舒適……"
20055-140 = "卻也比那……更讓人害羞……"
20055-150 = "戰鬥服的觸感，\n總覺得很神奇呢。\n好像能彈開子彈一樣。"
20055-160 = "明明包覆著全身……\n卻總覺得不太安穩……\n嗚嗚……"
20055-170 = "這件戰鬥服……\n好像也能和電腦連動……"
20055-180 = "當值日生的時候……\n能派上用場嗎？"
20055-190 = "會，會熱嗎……？"
20055-200 = "這，這套戰鬥服……\n表面涼涼的，很舒服哦……？"
20055-210 = "生日快樂……！"
20055-220 = "那，那個，\n生日禮物……"
20055-230 = "我準備了遊戲軟體……"
20055-240 = "你，你覺得怎麼樣呢……？"
20055-250 = "謝，謝謝你，老師……"
20055-260 = "謝謝你沒有忘記我……"
20055-270 = "雖然發生了很多事，\n但一年轉眼就過去了呢。"
20055-280 = "……新年快樂，老師。"
20055-290 = "雖，雖然不是聖誕老人服……\n不，不過也是紅色的……\n算是，差不多的東西吧。"
20055-300 = "聖，聖誕快樂，老師！"
20055-310 = "有，有好多打扮比我\n更誇張的人……！"
20055-320 = "啊，沒，沒有，\n不是我也想穿的意思……！"
20055-340 = "請看，老師。"
20055-350 = "這是我守護住的世界。"
20055-360 = "……當然，我知道。"
20055-370 = "見過這片光景的，\n並不只有我一個人。"
20055-380 = "大會的時候，\n你曾經這麼說過吧。"
20055-390 = "現在這個瞬間、\n這款遊戲──\n就是我們的現實。"
20055-400 = "所以，即使是結局\n已定的世界……"
20055-410 = "即使這個世界的大家，"
20055-420 = "都走著相同的劇本……"
20055-430 = "我所做過的選擇、\n這份感情……"
20055-440 = "毫無疑問，是真實的。"
20055-2600 = "練習要像正式來。\n正式來要像遊戲一樣……！\n我，會全力以赴的……！"
