[translation]
10090-130 = "(ยะ... อย่าตกใจนะ\nอย่าตกใจ...!)"
10090-140 = "คุณครู ทุกคน!\nยินดีต้อนรับสู่\nเฮียกคิยาโคค่ะ"
10090-150 = "เพื่อให้ทุกคนมีความทรงจำ\nที่ดีที่สุดในเฮียกคิยาโค!"
10090-160 = "ซาโตฮามะ อุมิกะ\nจะพยายามอย่างเต็มที่ค่ะ!"
10090-170 = "คุณครู... ตอนนี้ฉัน...\nจะไม่เป็นไรใช่ไหมคะ...?"
10090-180 = "ฉัน... จะทำออกมาได้ดีมั้ยคะ?\nฉันกำลังทำได้ดีหรือเปล่าคะ...?"
10090-190 = "อ่า... ขอบคุณนะคะ\nที่ช่วยพูดอย่างนั้น..."
10090-200 = "ถ้าทำให้ทุกอย่าง\nเป็นงานเทศกาลละก็...!"
10090-210 = "คะ? เหมือนบทพูดของคนบ้างาน\nเทศกาลงั้นเหรอคะ? อะไรกัน..."
10090-220 = "ไม่สิ เดี๋ยวนะคะ คนบ้างานเทศกาล...\nงั้นขอเอาอันนี้เป็นแรงบันดาลใจ..."
10090-230 = "ถ้าอยู่ด้วยกันแล้ว\nก็ไม่มีอะไรต้องกลัวค่ะ"
10090-240 = "จะว่าอย่างนี้ได้ไหมนะ\nเพราะการเตรียมงาน\nคือการต้องร่วมมือกัน"
10090-250 = "เพื่อทำออกมาให้เสร็จ\nภายในเวลาที่กำหนดค่ะ"
10090-260 = "ไว้คราวหน้าก็...\nมาที่เฮียกคิยาโคอีกนะคะ"
10090-270 = "ตอนนั้นฉันจะทำให้ได้เห็น\nงานเทศกาลที่ยอดเยี่ยมเลยละค่ะ!"
10090-280 = "อ๊ะ คุณครู!\nขอบคุณที่อยู่ช่วย\nจนถึงจบงานเลยนะคะ"
10090-290 = "โชคดีจริงๆ ค่ะ\nที่มีคุณครูอยู่ด้วย!"
10090-300 = "ฉัน... จะทำออกมาได้ดีมั้ยคะ?\nฉันกำลังทำได้ดีหรือเปล่าคะ...?"
10090-310 = "อ่า... ขอบคุณนะคะ\nที่ช่วยพูดอย่างนั้น..."
10090-320 = "ถ้าทำให้ทุกอย่าง\nเป็นงานเทศกาลละก็...!"
10090-330 = "คะ? เหมือนบทพูดของคนบ้างาน\nเทศกาลงั้นเหรอคะ? อะไรกัน..."
10090-340 = "ไม่สิ เดี๋ยวนะคะ\nคนบ้างานเทศกาล...\nงั้นขอเอาอันนี้เป็นแรงบันดาลใจ..."
10090-350 = "ถ้าอยู่ด้วยกันแล้ว\nก็ไม่มีอะไรต้องกลัวค่ะ"
10090-360 = "จะว่าอย่างนี้ได้ไหมนะ\nเพราะการเตรียมงาน\nคือการต้องร่วมมือกัน"
10090-370 = "เพื่อทำออกมาให้เสร็จ\nภายในเวลาที่กำหนดค่ะ"
10090-380 = "ไว้คราวหน้าก็... มาที่เฮียกคิยาโคอีกนะคะ"
10090-390 = "ตอนนั้นฉันจะทำให้ได้เห็น\nงานเทศกาลที่ยอดเยี่ยม\nเลยละค่ะ!"
10090-530 = "อ๊ะ คุณครู! "
10090-540 = "แหะๆๆ ใช่แล้วค่ะ\nนี่คือร้านค้าพิเศษของการทัศนศึกษา"
10090-550 = "ค่อยๆ ดูของตามใจเลยนะคะ!"
10090-560 = "มีของชิ้นไหนที่ถูกใจมั้ยคะ?"
10090-570 = "หรือว่ามีของอะไร\nที่อยากได้หรือเปล่าคะ?"
10090-580 = "บอกฉันได้ทุกอย่างเลยค่ะ!"
10090-590 = "ร้านค้าทัศนศึกษา\nปิดลงแล้วค่ะ..."
10090-600 = "แต่งานเทศกาลของเฮียกคิยาโค\nจะเริ่มตั้งแต่ตอนนี้นะคะ!"
10090-610 = "คะ? ค่ะ ไม่เป็นไรค่ะ\nทั้งการกระจายของ การจัดการ การค้าขาย"
10090-620 = "ที่ฉันได้บริการร้านเฮียกคิยาโค\nเคียงข้างกับท่านประธาน"
10090-630 = "เลยได้เรียนรู้มาด้วยค่ะ"
10090-640 = "ไม่ได้ลำบากขนาดนั้นหรอกค่ะ\nฉันชินแล้วน่ะค่ะ"
10090-650 = "แต่พอมีคุณครูมาที่นี่ด้วย...\nก็ดีจังเลยนะคะ แหะๆๆ"
10090-660 = "จะเอาอันนั้นเหรอคะ?\nขอบคุณค่ะ!"
10090-670 = "ค่า! เลือกได้ดีเลยค่ะ!"
10090-680 = "ว้าว! ถ้าเป็นฉัน\nฉันก็คงเลือกอันเดียวกันค่ะ!"
10090-690 = "ขอบคุณที่มาอุดหนุนนะคะ\nแหะๆๆ"
