[translation]
10090-130 = "(D-Don't panic. Don't panic!)"
10090-140 = "Sensei! Everyone! Welcome to Hyakkiyako!"
10090-150 = "May you leave Hyakkiyako with many cherished memories!"
10090-160 = "This is Satohama Umika here. I will give it my all!"
10090-170 = "I didn't do too bad just now, did I?"
10090-180 = "How am I doing? Did I do good?"
10090-190 = "Wow... Thank you for that. I really appreciate it..."
10090-200 = "Of course... If I turn everything into a festival—!"
10090-210 = "Huh? I sounded like some kind of festival fiend just now? How?"
10090-220 = "Oh, wait a minute. A festival fiend... I could use that as inspiration..."
10090-230 = "If we work together, we've got nothing to fear!"
10090-240 = "Or so they say. When it comes to work prep, everyone HAS to work together."
10090-250 = "That's the only way we'll be able to finish it before the deadline."
10090-260 = "Please come again...to Hyakkiyako."
10090-270 = "Next time, I'll show you a truly spectacular festival!"
10090-280 = "Oh, Sensei! Thank you so much for staying with us until the end."
10090-290 = "I'm so grateful to have you here!"
10090-300 = "How am I doing? Did I do good?"
10090-310 = "Wow... Thank you for that. I really appreciate it..."
10090-320 = "Of course... If I turn everything into a festival—!"
10090-330 = "Huh? I sounded like some kind of festival fiend just now? How?"
10090-340 = "Oh, wait a minute. A festival fiend... I could use that as inspiration..."
10090-350 = "If we work together, we've got nothing to fear!"
10090-360 = "Or so they say. When it comes to work prep, everyone HAS to work together."
10090-370 = "That's the only way we'll be able to finish it before the deadline."
10090-380 = "Please come again...to Hyakkiyako."
10090-390 = "Next time, I'll show you a truly spectacular festival!"
10090-530 = "Ah, Sensei!"
10090-540 = "Heeheehee. That's right. It's the special field trip store."
10090-550 = "Feel free to explore as you like!"
10090-560 = "Anything catch your eye?"
10090-570 = "Or is there something you need?"
10090-580 = "Whatever it is, just let me know!"
10090-590 = "The field trip shop is now closed..."
10090-600 = "But the Hyakkiyako festival has just begun!"
10090-610 = "Huh? Yes, that's fine. Distribution, management, sales, I can handle it all."
10090-620 = "I ran Momoyodou alongside the boss, you see."
10090-630 = "So I just picked those skills up naturally."
10090-640 = "The work's not hard. I'm used to it by now."
10090-650 = "Anyway, it's really nice to have you here, Sensei. Heeheehee."
10090-660 = "You want to go with that? Thank you!"
10090-670 = "Yes, that's a great choice!"
10090-680 = "Wow! I wanted that one too!"
10090-690 = "Thank you for your business. Heeheehee."
