[translation]
10135-80 = "It's important to stay consistent."
10135-90 = "Are you listening, Sensei?"
10135-100 = "You need to be diligent!"
10135-110 = "What's going on?"
10135-120 = "What? You called me for no reason?"
10135-130 = "Don't call me if you have nothing to talk about!"
10135-140 = "...Once in a while is fine, though, I guess."
10135-150 = "What? You want my sales greeting to be nicer?"
10135-160 = "Geez! There's a time and place for everything!"
10135-170 = "Don't forget to rest when you can, Sensei."
10135-180 = "And to brush your teeth!"
10135-190 = "You're not hurt anywhere, right? Great. That's a relief."
10135-200 = "Is there anything else you need?"
10135-210 = "Whatever you need; don't hesitate to ask."
10135-1810 = "It's something like...a Total Assault in a state of emergency."
10135-1820 = "I'm managing the shop, even if it is remotely."
10135-1830 = "Please hurry, Sensei. I have an emergency on this side!"
10135-1840 = "Malkuth... And those brats..."
10135-1850 = "Seriously! No one listens to anyone around here!"
10135-1860 = "When it's all over... Do you think that we'll be able to get back?"
10135-1870 = "It should be there! Hurry!"
10135-1880 = "Hurry and make your purchase, then get back to command!"
10135-1890 = "What? You want my sales greeting to be nicer?"
10135-1900 = "Geez! There's a time and place for everything!"
10135-1910 = "We can't do this without Sensei..."
10135-1920 = "Is there anything else you need?"
10135-1930 = "Whatever you need; don't hesitate to ask."
10135-1940 = "It's important to stay consistent."
10135-1945 = "It's important to stay consistent."
10135-1946 = "It's important to stay consistent."
10135-1947 = "It's important to stay consistent."
10135-1950 = "Are you listening, Sensei?"
10135-1955 = "Are you listening, Sensei?"
10135-1956 = "Are you listening, Sensei?"
10135-1957 = "Are you listening, Sensei?"
10135-1960 = "You need to be diligent!"
10135-1965 = "You need to be diligent!"
10135-1966 = "You need to be diligent!"
10135-1967 = "You need to be diligent!"
10135-1970 = "Welcome, Sensei."
10135-1975 = "Welcome, Sensei."
10135-1976 = "Welcome, Sensei."
10135-1977 = "Welcome, Sensei."
10135-1980 = "Let's organize what we need to do today."
10135-1985 = "Let's organize what we need to do today."
10135-1986 = "Let's organize what we need to do today."
10135-1987 = "Let's organize what we need to do today."
10135-1990 = "What's going on?"
10135-1995 = "What's going on?"
10135-1996 = "What's going on?"
10135-1997 = "What's going on?"
10135-2000 = "What? You called me for no reason?"
10135-2005 = "What? You called me for no reason?"
10135-2006 = "What? You called me for no reason?"
10135-2007 = "What? You called me for no reason?"
10135-2010 = "Don't call me if you have nothing to talk about!"
10135-2015 = "Don't call me if you have nothing to talk about!"
10135-2016 = "Don't call me if you have nothing to talk about!"
10135-2017 = "Don't call me if you have nothing to talk about!"
10135-2020 = "...Once in a while is fine, though, I guess."
10135-2025 = "...Once in a while is fine, though, I guess."
10135-2026 = "...Once in a while is fine, though, I guess."
10135-2027 = "...Once in a while is fine, though, I guess."
10135-2030 = "I-I'm not ticklish at all!"
10135-2035 = "I-I'm not ticklish at all!"
10135-2036 = "I-I'm not ticklish at all!"
10135-2037 = "I-I'm not ticklish at all!"
10135-2040 = "I'm not ticklish...!"
10135-2045 = "I'm not ticklish...!"
10135-2046 = "I'm not ticklish...!"
10135-2047 = "I'm not ticklish...!"
10135-2050 = "AAAHHH! Take this! TICKLE ATTACK!!"
10135-2055 = "AAAHHH! Take this! TICKLE ATTACK!!"
10135-2056 = "AAAHHH! Take this! TICKLE ATTACK!!"
10135-2057 = "AAAHHH! Take this! TICKLE ATTACK!!"
10135-2060 = "...Here. Go ahead. Take it."
10135-2065 = "...Here. Go ahead. Take it."
10135-2066 = "...Here. Go ahead. Take it."
10135-2067 = "...Here. Go ahead. Take it."
10135-2070 = "Wh-What now?! You want a compliment or something?!"
10135-2075 = "Wh-What now?! You want a compliment or something?!"
10135-2076 = "Wh-What now?! You want a compliment or something?!"
10135-2077 = "Wh-What now?! You want a compliment or something?!"
10135-2080 = "...Good job, Sensei."
10135-2085 = "...Good job, Sensei."
10135-2086 = "...Good job, Sensei."
10135-2087 = "...Good job, Sensei."
10135-2090 = "Yes. I knew you'd pull it off in no time."
10135-2095 = "Yes. I knew you'd pull it off in no time."
10135-2096 = "Yes. I knew you'd pull it off in no time."
10135-2097 = "Yes. I knew you'd pull it off in no time."
10135-2100 = "Why are you patting my head all of a sudden?!"
10135-2105 = "Why are you patting my head all of a sudden?!"
10135-2106 = "Why are you patting my head all of a sudden?!"
10135-2107 = "Why are you patting my head all of a sudden?!"
10135-2110 = "...I didn't tell you to stop, though...?"
10135-2115 = "...I didn't tell you to stop, though...?"
10135-2116 = "...I didn't tell you to stop, though...?"
10135-2117 = "...I didn't tell you to stop, though...?"
