[translation]
20025-740 = "คะคะคะคะ... คุณครู?!\nชะชะชะ... เชิญเลยค่ะ!\nละละ ละ... แล้วก็... ขอโทษด้วยค่ะ!"
20025-750 = "แหะๆ...\nได้เจอคุณครู\nในที่แบบนี้ด้วย..."
20025-760 = "ปะ... เปล่าค่ะ!\nมะ... ไม่ได้มีความหมาย\nพิเศษอะไรหรอกค่ะ...!"
20025-830 = "คะ...คะ?!\nมะมะมะ... มีอะไร...\nเหรอคะคุณครู?!"
20025-840 = "คะ...? ก็แค่...\nลองเรียกดูเฉยๆ เหรอคะ?"
20025-850 = "งะ... งั้นเหรอคะ?\nแหะๆๆ..."
20025-860 = "ฉลองวันปีใหม่...\nกับทุกคนในหน่วยรับจ้าง...\nพร้อมกับคุณครูแบบนี้..."
20025-870 = "แหะๆๆ...\nรู้สึกว่ามันพิเศษ\nมากๆ เลยละค่ะ "
20025-880 = "คิดแล้วเชียวว่าการที่คุณครู\nตะ... ต้องมาอยู่กับ...\nคนอย่างฉัน มันคงไม่สนุก..."
20025-890 = "ไม่ใช่อย่างนั้นเลย...\nงะ... งั้นเหรอคะ..."
20025-900 = "ขะ... ขอบคุณ... นะคะ\nคุณครู"
20025-1250 = "คะคะคะคะ...คุณครู?!\nชะชะชะ... เชิญเลยค่ะ!\nละละ ละ... แล้วก็...ขอโทษด้วยค่ะ!"
20025-1260 = "แหะๆ...\nได้เจอคุณครู\nในที่แบบนี้ด้วย..."
20025-1270 = "ปะ...เปล่าค่ะ!\nมะ...ไม่ได้มีความหมาย\nพิเศษอะไรหรอกค่ะ...!"
20025-1280 = "ฉันเองก็ไม่ค่อยเข้าใจเท่าไร...\nแต่ดูเหมือนว่ามันจะกลายเป็น...\nเรื่องใหญ่ไปแล้วนะคะ"
20025-1290 = "...ทำลายทุกอย่าง\nทิ้งเลยดีมั้ยคะ?"
20025-1300 = "ดูเหมือนท่านอารุ...\nจะสนุกอยู่เลยนะคะ..."
20025-1310 = "ค่อยยังชั่วหน่อยนะคะ\nแหะๆๆ..."
20025-1320 = "ดูเหมือนเรื่องวุ่นวาย\nจะค่อยๆ สงบลงแล้วนะคะ... "
20025-1330 = "คือว่าหุ่นยนต์ตัวนั้น...\nมันอะไรกันคะนั่น...?"
20025-1340 = "คะ...คะ?!\nมะมะมะ... มีอะไร...\nเหรอคะคุณครู?!"
20025-1350 = "คะ...? ก็แค่...\nลองเรียกดูเฉยๆ เหรอคะ?"
20025-1360 = "งะ... งั้นเหรอคะ?\nแหะๆๆ..."
20025-1370 = "ฉลองวันปีใหม่...\nกับทุกคนในหน่วยรับจ้าง...\nพร้อมกับคุณครูแบบนี้..."
20025-1380 = "แหะๆๆ...\nรู้สึกว่ามันพิเศษ\nมากๆ เลยละค่ะ "
20025-1390 = "คิดแล้วเชียวว่าการที่คุณครู\nตะ... ต้องมาอยู่กับ...\nคนอย่างฉัน มันคงไม่สนุก..."
20025-1400 = "ไม่ใช่อย่างนั้นเลย...\nงะ...งั้นเหรอคะ..."
20025-1410 = "ขะ...ขอบคุณ...นะคะ\nคุณครู"
