[translation]
10001085-1 = "ตอนที่ 8;ชัยชนะครั้งที่ 3"
10001085-2 = "ถนนสายหลัก สหภาพเรดวินเทอร์"
10001085-3 = "คะ.. คิดว่าแขนจะหักจริงๆ แล้วเสียอีก..."
10001085-4 = "ท่านประธานเชริโน่! เป็นอะไรไหมคะ?"
10001085-5 = "ฮือออ! โทโมเอะ! สหาย! มันน่ากลัวมากเลย!"
10001085-7 = "ฮึ่ม! เป็นโอกาสดีที่จะกำจัดประธานได้แล้วเชียว..."
10001085-8 = "ไม่ต้องมายุ่งเลยนะครู! ถึงจะเป็นครูก็เถอะ แต่หากมาขวางการปฏิวัติล่ะก็ ฉันจะไม่ยอมอยู่เฉยๆ แน่!"
10001085-9 = "รอเดี๋ยวนะคะทุกคน พวกฉันไม่ได้จะมาสู้กับทุกคนหรอกนะคะ"
10001085-10 = "ถ้าเป้าหมายของทุกคนคือล้มพวกที่กดขี่แรงงาน งั้นทุกคนก็ควรอยู่ฝ่ายเรา#nไม่ใช่มาสู้กับพวกเราแบบนี้สิคะ!"
10001085-11 = "ทำไมถึงคิดว่าประธานเชริโน่จะขวางการปฏิวัติของทุกคนล่ะคะ?"
10001085-12 = "แน่นอนว่าประธานเชริโน่คือผู้นำที่ไม่ทำงาน แถมยังเอาแต่กินของว่างและนอนกลางวันทุกวัน..."
10001085-13 = "ถึงจะเป็นประธานเผด็จการที่สั่งลงโทษโดยไม่พิจารณาไตร่ตรองเวลามีเรื่องไม่ถูกใจก็เถอะ!"
10001085-14 = "เดี๋ยวนะ... หัวหน้าเลขานุการโทโมเอะ ที่ผ่านมามองเราในด้านนั้นมาตลอดเลยงั้นเหรอ?"
10001085-16 = "ฮึ่ม! แต่ความผิดของลูกน้องก็คือเรื่องที่ผู้บังคับบัญชาต้องรับผิดชอบ!#nเพราะฉะนั้น ความรับผิดชอบต่อทุกเรื่องที่เกิดขึ้นในสหภาพเรดวินเทอร์ก็ต้อง#nตกไปอยู่ที่เชริโน่ที่เป็นประธานและตัวแทนคณะบริหาร!"
10001085-17 = "ทั้งเรื่องซ่อมแซมอาคารเรียนเก่าล่าช้า เรื่องไม่แจกพุดดิ้งให้อย่างเหมาะสม#nแล้วก็เรื่องที่วันนี้อากาศหนาวจนสุดขั้วด้วย! ทั้งหมดเป็นเพราะประธานเชริโน่!"
10001085-18 = "แค่การที่ได้มาเป็นประธานสภานักเรียนของเรดวินเทอร์ก็เป็นเรื่องที่น่าประณามแล้ว!"
10001085-19 = "แล้วจะให้ทำยังไงล่ะ! ตามตรรกะของเราแล้ว#nไม่ว่าใครที่ได้ขึ้นมาเป็นประธานก็ต้องโดนประณามกันทั้งนั้น!"
10001085-20 = "มันก็ใช่อยู่หรอก! แต่การวิพากษ์วิจารณ์ผู้มีอำนาจคือพื้นฐานของการเคลื่อนไหวต่อสู้นี่!"
10001085-21 = "การต่อสู้นี้จะไม่จบลงจนกว่าตำแหน่งประธานสภานักเรียนเผด็จการจะหายไปจากโรงเรียนของเรา!"
10001085-22 = "นี่มัน... การปฏิวัติอะไรกันเนี่ย!"
10001085-23 = "[s] \"แต่ตอนนี้เชริโน่ไม่ใช่ประธานสภานักเรียนนี่\""
10001085-24 = "ว่าไงนะ...? ถ้าเชริโน่ไม่ใช่ประธาน แล้วใครกันล่ะที่เป็น...?"
10001085-25 = "ถึงจะน่าโมโหแต่ก็คงต้องบอกสินะ... ตอนนี้คนที่กุมอำนาจประธาน#nของสำนักเลขาธิการเรดวินเทอร์ไม่ใช่เรา แต่เป็นหัวหน้าคณะฯ มารินะต่างหาก"
10001085-26 = "เพราะหัวหน้าคณะฯ มารินะก่อการปฏิวัติ เราก็เลยต้องถูกปลดลงจากตำแหน่ง#nและก็ต้องมาหลบหนีอยู่แบบนี้ยังไงล่ะ!"
10001085-27 = "เชริโน่จัง... เรื่องนี้ไม่ต้องเล่าด้วยท่าทีภาคภูมิใจหรอกค่ะ"
10001085-28 = "ถ้างั้นก็แปลว่า... หัวหน้าคณะฯ มารินะคือคนที่กุมอำนาจอยู่ในตอนนี้#nส่วนประธานเชริโน่ก็เป็นแค่เด็กตัวกะเปี๊ยกคนหนึ่งเท่านั้น... ใช่ไหม?"
10001085-29 = "ว่าไงนะ? เด็กตัวกะเปี๊ยกงั้นเหรอ?!"
10001085-30 = "เอาล่ะเหล่าสหาย! เป้าหมายของเราเปลี่ยนไปแล้ว!"
10001085-31 = "ศัตรูคนใหม่ของเราไม่ใช่เด็กตัวกะเปี๊ยกที่ไม่มีเขี้ยวเล็บอย่างประธานเชริโน่#nแต่เป็นหัวหน้าคณะฯ มารินะที่เป็นอำนาจใหม่ของสำนักเลขาธิการต่างหาก!"
10001085-32 = "พูดว่าเด็กตัวกะเปี๊ยกอีกแล้วนะ!! แถมรอบนี้ยังเป็นเด็กตัวกะเปี๊ยกที่ไม่มีเขี้ยวเล็บด้วย!"
10001085-33 = "พวกเธอไม่ยอมฟังคำพูดของท่านเชริโน่ผู้ยิ่งใหญ่งั้นเหรอ?! ต้องโดนลงโทษ!"
10001085-34 = "เพื่อสิทธิและอิสรภาพของแรงงาน และเพื่อสิ่งสำคัญอื่นๆ..."
10001085-35 = "ไปจู่โจมสำนักเลขาธิการกันเลย!"
10001085-37 = ""
10001085-38 = "วู้ววววว!!"
10001085-40 = "โดนเมินเฉยเลย..."
10001085-41 = "ชมรมผู้รับจ้างเป็นกลุ่มที่น่าเกรงขามตามที่ลือกันเลย การที่ได้พวกนี้มาอยู่ฝั่งเราถือเป็นเรื่องที่ดีนะคะ"
10001085-42 = "ท่านประธานเชริโน่! พวกเราก็ตามนักเรียนพวกนี้ไปสำนักเลขาธิการกันเถอะค่ะ!"
10001085-43 = ""
10001085-44 = "เดี๋ยวก่อนสิ! รอกันก่อน! เราคือหัวหน้านะ!#nจะทิ้งหัวหน้าไว้คนเดียวได้ยังไง!"
