[translation]
10005040-1 = "ตอนที่ 4;ทำตามวิธีที่คุ้นเคย"
10005040-2 = "ทางเดินประตูหลังเพลย์เลาจน์ ตึก B"
10005040-4 = ""
10005040-5 = "เคลียร์... ไม่พบสิ่งผิดปกติค่ะ"
10005040-6 = "ทางนี้ก็ไม่มีการ์ดเฝ้าอยู่เหมือนกัน"
10005040-7 = "ด้านหลังล่ะ?"
10005040-9 = "ไม่มี ดูเหมือนจะมาถึงได้โดยที่ไม่ถูกจับนะ"
10005040-10 = "ขอโทษนะ... ถ้าฉันใจเย็นกว่านั้นระหว่างที่เค้นข้อมูลละก็..."
10005040-11 = "อย่าคิดมากไปเลยค่ะ คาริน ฉันเองก็ทำพลาดไปเหมือนกัน"
10005040-12 = "แล้วอีกอย่าง เราก็ได้เบาะแสตอนที่การ์ดคนนั้นพึมพำออกมาตอนหมดสติไปด้วยนี่คะ"
10005040-13 = "ทั้งที่หมดสติไปแต่ก็เอาแต่พูดว่า \"เพลย์เลาจน์\" นั่นสินะ"
10005040-14 = "อืม... อาจจะพูดคำนั้นมาตั้งแต่ช่วงกลางๆ แล้วก็ได้ แต่ฉันปิดปากไว้ก็เลยไม่ได้ยิน..."
10005040-15 = "แต่ว่าเพลย์เลาจน์คือที่แบบไหนกันแน่น่ะ...?"
10005040-16 = "ถามมาได้ ไหนบอกว่าเป็นชื่อห้องที่ใหญ่ที่สุดที่อยู่ตรงกลางไง? ในแผนผังเขียนไว้แบบนั้นไม่ใช่รึไง"
10005040-17 = "เปล่าสักหน่อย ฉันไม่ได้หมายความว่าแบบนั้น..."
10005040-18 = "ฉันแค่นึกไม่ออกว่าเป็นห้องที่มีไว้เพื่อจุดประสงค์อะไรต่างหากน่ะ"
10005040-19 = "อันที่จริงแล้วฉันก็นึกไม่ออกเหมือนกัน... เพลย์เลาจน์งั้นเหรอ... เป็นสถานที่แบบไหนกันนะคะ?"
10005040-20 = "จะเกี่ยวข้องกับพันธบัตรที่ชิโระอุซางิเอาไปรึเปล่านะคะ?"
10005040-21 = "คุณครู... พอจะรู้อะไรบ้างมั้ยคะ?"
10005040-22 = "[s1] \"เรื่องนั้น...\"\n[s2] \"ถ้าตามชื่อก็คงเป็น 'สถานที่เล่นสนุก' ล่ะนะ\""
10005040-24 = "ว่าแล้วเชียวว่าคุณครูก็คงไม่รู้เหมือนกัน..."
10005040-26 = "สถานที่เล่นสนุก...?"
10005040-28 = "ฮะฮะฮ่า! แล้วมันยังไงล่ะ คิดในทางที่ดีเอาไว้ดีกว่า! สุดท้ายก็กลับมาใช้วิธีแบบปกติจนได้นี่"
10005040-29 = "ไม่เห็นจะต้องรู้เลยว่ายัยนั่นเข้าไปทำอะไรที่นั่นน่ะ!? เราก็แค่ไปที่นั่น จัดการยัยตัวแสบซะ#nแล้วก็ลากกลับไปก็เท่านั้นเอง!"
10005040-30 = "ปกติแล้วพวกเราก็ทำแบบนี้นี่นา ไม่ใช่รึไง?"
10005040-31 = "อืม... ในสถานการณ์แบบนี้ จะเห็นด้วยก็ยังไงอยู่นะคะ..."
10005040-32 = "แต่ว่า... ใช่แล้วค่ะ แบบนั้นก็คงเหมาะกับสถานการณ์ที่ใช้แผน B ตอนนี้ที่สุดแล้วค่ะ"
10005040-33 = "แต่ว่าหัวหน้าห้ามลืมเด็ดขาดเลยนะคะว่าจุดประสงค์ของพวกเราก็คือชิโระอุซางิเท่านั้น"
10005040-34 = "พอเข้าไปใน <เพลย์เลาจน์> ให้เราแยกย้ายกันไปตามหาชิโระอุซางิ และทันทีที่พบตัวก็ให้ติดต่อกัน"
10005040-35 = "หลังรวบตัวได้แล้วก็อย่าทิ้งเวลาให้พวกการ์ดได้ตั้งตัวค่ะ"
10005040-36 = "และเพื่อไม่ให้เกิดเรื่องวุ่นวายขึ้นก็จะอนุญาตให้ใช้ได้แค่ใช้ระเบิดควันกับแฟลชบอมบ์ที่อานุภาพต่ำ#nเท่านั้นค่ะ"
10005040-37 = "ไม่ว่าข้างในห้องนั้นจะเป็นยังไง... ก็ห้ามสู้กับพวกการ์ดเด็ดขาดเลยนะคะ เข้าใจมั้ยคะ?"
10005040-38 = "อึกกก... เงื่อนไขไร้สาระพวกนี้อีกแล้ว..."
10005040-39 = "[s3] \"อาจจะยากไปสักหน่อยแต่ก็ฝากด้วยนะ เนรุ\"\n[s4] \"ถ้าเป็นเนรุละก็ทำได้อยู่แล้ว\""
10005040-40 = ""
10005040-41 = ""
10005040-43 = "..."
10005040-44 = "นะ... หนวกหูน่า! ฉันไม่ชอบให้มาอวยกันแบบนั้นหรอกนะ"
10005040-45 = "ถ้าแค่นั้นล่ะก็ทำได้สบายอยู่แล้ว คิดว่าฉันเป็นใครกันล่ะ?"
10005040-46 = "คอยดูให้ดีเถอะ ฉันจะพายัยนั่นออกมาภายในพริบตาโดยไม่ทันให้ใครรู้ตัวเลย"
10005040-47 = "เห็นด้วย มามัวเสียเวลาอยู่ตรงนี้ต่อไปก็ไม่มีประโยชน์ รีบลงมือกันเถอะ"
10005040-48 = "ดีละ คุณครูตามฉันมาล่ะ ถ้าเกิดอะไรขึ้นฉันจะคอยดูแลเอง เข้าใจมั้ย?"
10005040-49 = "ถ้างั้นจะเริ่มละนะ!"
10005040-51 = "เพลย์เลาจน์"
10005040-53 = "อืม..."
10005040-54 = "ที่นี่คือ <เพลย์เลาจน์> หรือที่ไหนกันแน่เนี่ย?"
10005040-55 = "อะไรกัน...? ดูจากภายนอกแล้วเหมือนร้านเกมที่เสียงดังสุดๆ เลยนี่นา..."
10005040-56 = ""
10005040-59 = ""
10005040-60 = "ยินดีต้อนรับทุกท่านครับ! คงเพิ่งเคยมาที่นี่เป็นครั้งแรกสินะครับ!"
10005040-61 = "หา...? อะไรน่ะ?"
10005040-62 = "ยินดีที่ได้พบนะครับ ผมคือ <เลาจน์ไกด์> ที่รับหน้าที่แนะนำเพลย์เลาจน์แห่งนี้ครับผม!"
10005040-63 = "ผมจะรับหน้าที่อธิบายกฎและวิธีใช้บริการของที่นี่ให้กับทุกท่านเองครับ"
10005040-64 = "ทุกท่านอาจจะทราบกันดีแล้วว่าบริการทุกอย่างบนเรือโกลเด้น ฟลีซ จะต้องใช้เหรียญที่ได้จาก#nการสุ่มล็อตโต้"
10005040-65 = "ว่าไงนะ...? สุ่มล็อตโต้เรอะ...?"
10005040-66 = "อืม... เอ่อ... ยังไม่ทราบหรอกเหรอครับ?"
10005040-67 = "ค่าเงินทั้งหมดที่ใช้บนเรือลำนี้... ทั้งค่าที่พัก อุปกรณ์ความบันเทิง กระทั่งห้องน้ำจะใช้เหรียญ#nที่ได้รับจากการสุ่มเป็นตัวแบ่งระดับบริการที่จะได้รับครับ"
10005040-68 = "เหรียญจะแบ่งออกเป็นตั้งแต่ระดับ D ไปจนถึงระดับ S ปกติแล้วหากได้เป็นเหรียญระดับ A#nก็จะสามารถใช้บริการบนเรือทุกอย่างในระดับหรูได้ครับ!"
10005040-69 = "[s5] \"ถ้างั้นระดับ S ล่ะ?\"\n[s6] \"ถ้าระดับ S จะพิเศษสุดๆ ไปเลยใช่มั้ย?\""
10005040-70 = "ฮุฮุ เป็นคำถามที่ดีครับ ใช่แล้วครับผม ล็อตโต้ระดับ S เป็นระดับที่พิเศษสุดๆ ครับ!"
10005040-71 = "ฮุฮุ เป็นคำถามที่ดีครับ ใช่แล้วครับผม ล็อตโต้ระดับ S เป็นระดับที่พิเศษสุดๆ ครับ!"
10005040-72 = "ที่เรือโกลเด้น ฟลีซแห่งนี้ ระดับ S ถือเป็นของล้ำค่ากว่าทุกสิ่ง..."
10005040-73 = "กรี๊ดดดดด~!!!"
10005040-74 = "...?"
10005040-75 = ""
10005040-77 = ""
10005040-80 = "อ่า~ ให้ตายสิ~ เอาอีกแล้ว~! ได้ระดับ C อีกแล้ว! ทำไมถึงมีแค่ฉันที่ได้ C ล่ะ!"
10005040-81 = "ฉันก็เหมือนกัน วันนี้สุ่มไม่ได้อันดีๆ เลย สุ่มมาตั้งนานเพิ่งได้ระดับ B แค่เหรียญเดียวเอง..."
10005040-82 = "ยังไงเธอก็ได้ระดับ B ไม่ใช่รึไง! ฉันได้แต่ระดับ C ทั้งหมดเลยนะ! ระดับ C อดกินแกงกะหรี่กับ#nคาราอะเกะด้วย!"
10005040-83 = "นี่ คนที่ได้ระดับ A นั่นน่ะ ระดับ A มีอะไรดีๆ บ้าง? ได้ของดีๆ เยอะกว่าพวกเราเยอะเลยใช่มั้ย?"
10005040-84 = "อืม... ก็คงประมาณนั้นล่ะนะ แต่ถ้าเทียบกับระดับ S แล้วก็ไม่เท่าไรหรอก"
10005040-85 = "จากที่ได้ยินมา ถ้ามี <ตั๋ว VIP> ที่แลกได้จากระดับ S ละก็... ไม่ต้องทำตามกฎบนเรือก็ยังได้เลย..."
10005040-86 = "ไม่ต้องทำตามกฎงั้นเหรอ...? ได้สิทธิพิเศษเบอร์นั้นเลยเหรอ?"
10005040-88 = "คุณลูกค้าระดับ C สุ่มได้ระดับ B แล้วนะคะ! ยินดีด้วยที่ได้เลื่อนระดับค่ะ!! ปัมปั่มปาดัม~!"
10005040-89 = "ขอให้ทุกๆ คนโชคดีนะคะ~! สู้ๆ ค่ะ!"
10005040-91 = "ทำอะไรน่ะ...?!"
10005040-92 = "ทำไมถึงมีหน้าคนโชว์หราอยู่บนจอยักษ์แบบนั้นล่ะ? แสดงความยินดีงั้นเหรอ...?"
10005040-93 = "[s7] \"ดูเหมือนจะแสดงความยินดีที่สุ่มล็อตโต้ได้ระดับดีๆ น่ะ\"\n[s8] \"เพราะที่นี่ตัดสินทุกอย่างด้วยระดับของล็อตโต้...\""
10005040-94 = "เฮอะ ดูเหมือนทุกคนจะจดจ่ออยู่กับการเล่นล็อตโต้จนไม่ได้สนใจสิ่งรอบตัวเลย..."
10005040-95 = "เฮอะ ดูเหมือนทุกคนจะจดจ่ออยู่กับการเล่นล็อตโต้จนไม่ได้สนใจสิ่งรอบตัวเลย..."
10005040-96 = "แบบนี้ไม่เป็นไรแน่เหรอครู? คนพวกนี้... เหมือนจะโดดเรียนมาเลยนะ?"
10005040-97 = "ว่าไงนะ...?"
10005040-98 = "ทำไมฉันถึงได้สนใจเรื่องพวกนี้ด้วยน่ะเหรอ?"
10005040-99 = "พะ... พูดอะไรน่ะ? ถึงฉันจะชอบไปสายบ่อยๆ แต่ก็ไม่เคยโดดเรียนเลยนะ!#nเห็นฉันเป็นคนยังไงเนี่ย...!"
10005040-100 = "ฮึ่มมม ช่างเถอะ เรื่องนั้นไม่ใช่เรื่องสำคัญหรอก"
10005040-101 = "ฉันมั่นใจว่ายัยนั่นจะต้องอยู่ที่นี่แน่ๆ..."
10005040-102 = "รอบตัวมีแต่เสียงอึกทึกครึกโครม แถมคนอื่นก็ไม่ค่อยสนใจด้วย ที่ที่เสียงดังแบบนี้น่ะ คงยากต่อการ#nหาตัวเลยละ"
10005040-103 = "เป็นสถานที่สุดเพอร์เฟกต์สำหรับซ่อนตัวของพวกที่ชอบหนีงานหรือหนีรุ่นพี่เลยทีเดียว"
10005040-104 = ""
10005040-105 = "อืม..."
10005040-106 = "แต่ดูแล้ว... ดูไม่เหมาะสำหรับเป็นสถานที่วางแผนสมคบคิดอะไรเลย..."
10005040-107 = "ถ้ายัยนั่นมาที่นี่จริงๆ ละก็... เธอมาทำอะไรกันแน่นะ?"
10005040-108 = ""
10005040-110 = ""
10005040-111 = "[ns9] \"เนรุ...?\"\n[ns10] \"มีอะไรเหรอ?\""
10005040-112 = "เจอตัวแล้ว..."
10005040-113 = "เจอตัวแล้ว..."
10005040-114 = "ตรงนั้น... ยัยนั่น... คุณครูเห็นรึเปล่า? คนที่นั่งอยู่ตรงหน้าเครื่องเล่นนั่นน่ะ"
10005040-115 = ""
10005040-117 = ""
10005040-118 = "ย้าาา~! นี่แหละๆ... มันต้องแบบนี้! อา... วันนี้โชคดีจริงๆ เลยน้า~"
10005040-119 = "ตรงนี้ก็เล่นจบแล้ว..."
10005040-120 = "ไม่สิ ยังไม่จบหรอก ถ้าดวงขึ้นแบบนี้ละก็... ลองเสี่ยงดูอีกรอบดีมั้ยนะ...?"
10005040-121 = ""
10005040-123 = ""
10005040-124 = "ดีละ เอาละนะ!! ลุยเลย โคยูกิ! เชื่อสัญชาตญาณของตัวเองซะ!#nระดับ S ในตำนานอยู่ใกล้แค่เอื้อม!"
10005040-125 = ""
10005040-127 = ""
10005040-129 = "อึ่ก... B...? B งั้นเหรอ...? ทำไมอยู่ๆ ก็เกลือล่ะ!"
10005040-130 = "ฮึ่ยยยย! ไม่อยากเชื่อเลย!! เมื่อกี้ทุ่มไปตั้งเยอะเลยนะ! ออกระดับ S มาให้ชื่นใจหน่อยสิ!"
10005040-131 = "แล้วแบบนี้เมื่อไรจะได้ตั๋ว VIP กันเล่า! ฉันไม่ยอมเด็ดขาด แบบนี้ยอมให้ไม่ได้!"
10005040-132 = ""
10005040-134 = ""
10005040-135 = ""
10005040-136 = "นี่เธอ! หยุดเดี๋ยวนี้นะ! ถ้าทุบเครื่องเล่นอีก เธอจะโดนห้ามเล่นแล้วนะ!"
10005040-137 = "อึก..."
10005040-138 = "ขะ... ขอโทษค่ะ"
10005040-139 = ""
10005040-141 = ""
10005040-143 = ""
10005040-144 = "[ns11] \"เด็กคนนั้นคือชิโระอุซางิเหรอ?\"\n[ns12] \"ทำไมเจอง่ายจัง?\""
10005040-145 = "เฮ้อ... ใช่แล้วล่ะ ยัยนั่นจริงๆ ด้วย"
10005040-146 = "เฮ้อ... ใช่แล้วล่ะ ยัยนั่นจริงๆ"
10005040-147 = "เด็กที่โวยวายอยู่ตรงหน้าตู้และไม่รู้เลยว่าเรามาอยู่ที่นี่ก็คือชิโระอุซางิละ"
10005040-148 = "จริงๆ เลย... ก็ว่าอยู่ว่าเอาพันธบัตรไปทำอะไร..."
10005040-149 = "ยัยนั่นกำลังเล่นล็อตโต้อยู่ใช่รึเปล่าน่ะ? ถามจริง...?"
10005040-150 = "ให้ตายสิ พวกเราต้องลำบากมาถึงที่นี่เพื่อจับยัยเด็กนี่น่ะเหรอ...!!"
10005040-151 = "[s13] \"คิดซะว่าโชคดีที่เจอก็แล้วกันนะ\"\n[s14] \"เป็นเด็กที่ทำอะไรตามใจจริงๆ นะ\""
10005040-152 = "เฮ้อ..."
10005040-153 = "เฮ้อ..."
10005040-154 = "มันก็จริง แบบนี้อาจจะดีกว่าการต้องไปร่วมมือกับผู้ก่อการร้ายแบบที่ยัยนักบัญชีของเซมิน่าบอกก็ได้"
10005040-155 = "ถึงฉันจะอยากให้เป็นแบบนั้นก็เถอะนะ แต่ก็..."
10005040-156 = ""
10005040-158 = ""
10005040-159 = "วอหนึ่งเรียกวอสอง... เนรุพูด เจอตัวชิโระอุซางิแล้ว ฉันจะแจ้งพิกัดให้ รีบมารวมตัวกันด่วน"
10005040-160 = "เข้าใจแล้วค่ะ จะรีบไปค่ะ"
10005040-161 = "เข้าใจแล้ว กำลังไปเดี๋ยวนี้"
10005040-162 = ""
10005040-164 = ""
10005040-165 = "ง่ายดายเกินคาดแฮะ"
10005040-166 = "ถึงจะแค่ช่วงสั้นๆ แต่ก็ทำได้ดีมากนะครู ช่วยได้เยอะเลย"
10005040-167 = "แค่นี้ก็ถือว่าปิดจ๊อบได้แล้วละ เพราะยัยนั่นก็มัวแต่ห่วงเล่นล็อตโต้จนไม่รู้เลยว่ากำลังจะถูกจับ"
10005040-168 = "ยกเว้นแต่ว่าพวกเราจะเปิดเผยตัว..."
10005040-169 = ""
10005040-172 = ""
10005040-173 = ""
10005040-175 = "ว้าว! คุณอาสึนะ! สุ่มได้ระดับ A ได้ในแค่ 10 รอบเองนะคะ!"
10005040-176 = "ยินดีด้วยค่ะ! ถ้าเป็นแบบนี้จะต้องได้ระดับ S แน่ๆ! ตั๋ว VIP อยู่ไม่ไกลแล้วนะคะ~!"
10005040-177 = "ใช่แล้ว แค่พวกเราไม่ถูกโชว์หน้าหราอยู่บนจอมอนิเตอร์ยักษ์แบบนั้นก็พอแล้ว..."
10005040-178 = ""
10005040-181 = "อ๊ะ...?"
10005040-182 = "[s15] \"อาสึนะ...?\"\n[s16] \"ดูเหมือนหน้าจะไปโผล่บนจอมอนิเตอร์ยักษ์แล้วนะ\""
10005040-183 = "วะ... ว่าไงนะ? ทำไมอาสึนะถึงได้..."
10005040-184 = "วะ... ว่าไงนะ? ทำไมอาสึนะถึงได้..."
10005040-185 = "ดะ... เดี๋ยวนะ!? อะไรกันน่ะ!? นั่นมันรุ่นพี่อาสึนะนี่นา...!!"
10005040-186 = "ทำไมรุ่นพี่อาสึนะถึงไปอยู่ตรงนั้น...!!!"
10005040-187 = "เอ่อ..."
10005040-188 = "เอ๋...?"
10005040-189 = "แย่ละสิ..."
10005040-190 = ""
10005040-192 = ""
10005040-193 = "[ns] \"ว่าไง\""
10005040-194 = "อ๊ายยยยย-!!"
10005040-195 = "การ์ด... การ์ดดดด!! มีผู้บุกรุก! มีผู้บุกรุกกกกก-!"
10005040-196 = "มีผู้บุกรุก!? ผู้บุกรุกเหรอ!?"
10005040-197 = "ตรงนี้ๆ... คนที่อยู่ตรงนี้เป็นการ์ดตัวปลอม! คนนี้ด้วย คนนั้นก็ด้วย!"
10005040-198 = "เป็นตัวปลอมทั้งหมดเลย! รีบจับตัวไปเร็วเข้า!!"
10005040-199 = "...! รวมพลกันเร็ว!! จับกุมผู้บุกรุกเดี๋ยวนี้!!"
10005040-200 = ""
10005040-202 = ""
10005040-209 = ""
10005040-210 = "คุณครู..."
10005040-211 = "โทษทีนะ... แต่มันช่วยไม่ได้จริงๆ"
10005040-212 = ""
10005040-214 = ""
