[translation]
10002200-1 = "Afterword; Millennium 60 Fireworks"
10002200-3 = "Hello. I'm Millennium 60, a bomb from Millennium Science School."
10002200-4 = "And I'm full of napalm! I stand a total of 23 centimeters tall and weigh a whopping 44 kilograms."
10002200-5 = "As for my age...that's a secret."
10002200-6 = "You're probably wondering right about now what napalm is doing at the Beach Shack."
10002200-7 = "Well, my original purpose was to demolish abandoned buildings. More efficient equipment has been made for that, so now I'm out of a job."
10002200-8 = "I drifted around Trinity for a while after that until I finally wound up here."
10002200-9 = "In fact, I can't even remember how long ago that was. It feels like I've been here forever."
10002200-10 = "My new home has everything: a nice view of the ocean, refreshing breezes... It's wonderful."
10002200-11 = "Sure, I may seem out of place. I can't deny that I've been collecting dust here like I would have anywhere else back on campus."
10002200-12 = "I'm not desirable like those fireworks over there that people are always buying."
10002200-13 = "When I look at them, I find it both amazing and enviable to see how much joy they bring into people's lives."
10002200-14 = "Would I have been able to put smiles on everyone's faces had I been born as a firework too?"
10002200-15 = "It may sound sad, but thoughts like that are what give me hope for better days still to come."
10002200-16 = "That and—"
10002200-17 = "Sir, over here! Fireworks! I need more fireworks!"
10002200-18 = "Oh. Customers."
10002200-20 = ""
10002200-21 = ""
10002200-23 = "Unacceptable. We picked these out first. Don't expect to steal out from under our noses and not face the consequences."
10002200-24 = "Can't you losers just leave us alone? If anyone here are thugs, it's all of you."
10002200-25 = "What about this one? Is it for sale?"
10002200-26 = "That firework is super-sized!"
10002200-27 = "Super-sized...? Are they talking about me?"
10002200-28 = "Hahaha. I'm afraid not, little lady. That there is napalm, not a firework."
10002200-29 = "Who cares what it is?!"
10002200-30 = "All it needs to do is explode. So does it explode or not?!"
10002200-31 = "Well, I suppose it does. In fact, it'll set off an explosion bright enough to light up the night sky as if the sun were still shining."
10002200-32 = "Huh?"
10002200-33 = "Great, I'll take it. Will this be enough to cover it? "
10002200-34 = "Wrap it up for me!"
10002200-35 = "...Huh?"
10002200-36 = "N-Now wait just a minute. You do realize that's a BOMB and not just a firework, right?"
10002200-37 = "How many times do I have to tell you? I don't care as long as it explodes. If we set it off in midair, that makes it a firework, right?"
10002200-38 = "Anyway, I gotta go. We've got plans tonight. See ya!"
10002200-39 = ""
10002200-40 = ""
10002200-41 = ""
10002200-42 = ""
10002200-43 = "Well, I guess she's not wrong."
10002200-45 = "Hello. I'm Millennium 60, a bomb from Millennium Science School."
10002200-46 = "..."
10002200-47 = "I mean, Millennium 60, a firework from Millennium Science School."
10002200-48 = ""
