[translation]
10003050-1 = "#title;제5화;미식연구회, 너마저……!"
10003050-5 = "1;아카리;01\n2;이즈미 수영복ND;00\n4;하루나;01\n5;준코;00\n#1;a\n#2;a\n#4;a\n#5;a\n#1;h\n#2;h\n#4;h\n#5;h\n#wait;2000"
10003050-8 = "#na;이오리 수영복ND;미식연구회, 너희 문제아들이 여긴 또 어쩐 일이야? 또 무슨 사고를 치려고?"
10003050-9 = "#na;치나츠;(그러고 보면 그때 SNS에서 보았던 계정 중에 분명…….)"
10003050-10 = "#na;하루나;어머, 저희는 딱히 사고를 치러 온 게 아니랍니다?"
10003050-11 = "#na;준코;맞아! 우리는 그냥 옥수수를 팔러 왔을 뿐이라고!"
10003050-12 = "#na;이오리 수영복ND;……?"
10003050-13 = "#na;치나츠;……옥수수?"
10003050-14 = "#st;[0,0];instant;1;"
10003050-17 = "#zmc;instant;500,180;1896\n#na;하루나;여름 해변이나 축제에서 먹는 구운 옥수수는, 왜 그리 맛있는 걸까."
10003050-18 = "#zmc;instant;500,180;1896\n#na;하루나;여러분들은 그 이유가 궁금하지 않으신가요? 분명히 같은 옥수수를 먹는 것이지만, 어째서 맛이 다른가."
10003050-19 = "#zmc;instant;500,180;1896\n#na;하루나;여름을 맞이하여 그 의문에 대해 저희는 끊임없이 궁구에 궁구를 거듭했지만. 결론은 하나."
10003050-21 = "#na;하루나;……직접 해보지 않으면 모른다."
10003050-24 = "#na;하루나;그렇게 생각했기에 이번에 직접 옥수수를 팔아보고자, 해변을 찾아온 거랍니다."
10003050-25 = "5;아카리;02;네☆ 여기서 마침 불량배들과 헬멧단의 다툼이 있다며, 인터넷에서 뜨겁길래 말이에요~\n#5;em;[음표]\n#5;al"
10003050-26 = "1;준코;00;문제아들이 서로 싸우면, 걔네도 그렇고 구경하러 온 사람도 무지 많을 거 아냐? 이건 사업적으로도 훌륭한 판단인 거지!\n#1;ar"
10003050-27 = "5;이즈미 수영복ND;10;맞아! 팔고 남은 건 우리가 먹을 거고!\n#5;a\n#5;em;[반짝]\n#5;greeting"
10003050-28 = "1;준코;05;아니, 다 팔아야지! 무겁게 들고 왔는데!\n#1;hophop\n#1;m3\n#5;dr"
10003050-29 = "#st;[0,0];instant;1;"
10003050-30 = "#clearST\n1;준코;05\n#1;d\n#wait;1000"
10003050-32 = "3;하루나;05;……그런데 왜 해변에 아무도 없는 걸까요?\n#3;em;…\n#3;a"
10003050-33 = "3;이오리 수영복ND;05;그런 건 아무래도 좋아. 축제는 전부 끝났어. 썩 꺼져!\n#3;a\n#3;em;[빠직]\n#3;hophop"
10003050-34 = "3;이오리 수영복ND;05\n1;하루나;99;후후…….\n#1;a\n#3;m5"
10003050-35 = "1;아카리;02;어머나☆ 꺼지라니.\n#1;em;[음표]"
10003050-36 = "1;하루나;02;……후후후. 저희 미식연구회, 미식의 추구를 가로막는 방해물에게서 등을 돌려 도망쳐 본 적은 없습니다.\n#1;em;…"
10003050-37 = "1;아카리;02;하루나가 그렇게 얘기하니, 이어지는 전개는 뻔한 느낌이죠? 게다가 보아하니……."
10003050-38 = "3;이오리 수영복ND;04\n1;아카리;01\n#1;m2\n#wait;1500"
10003050-39 = "1;아카리;05;아무래도 지금은, 선도부장이 보이질 않는 것 같은데요?\n#1;em;[반응]"
10003050-40 = "3;이오리 수영복ND;09;(뜨끔!)\n#3;shake\n#3;em;[?!]"
10003050-42 = "3;치나츠;06;(……이거, 곤란한 느낌이네요.)\n#3;em;[속상함]\n#3;stiff"
10003050-43 = "#st;[0,0];instant;1;"
10003050-44 = "#clearST\n3;치나츠;06\n#3;d\n#wait;1000"
10003050-45 = "3;하루나;99\n#3;a\n#wait;1000"
10003050-46 = "3;하루나;01\n#3;greeting\n#wait;1500"
10003050-47 = "3;하루나;03;후후후……. 그럼 미식을 향한 올곧은 저희의 집념. 여기서 보여드리도록 하죠.\n#3;em;[반짝]"
10003050-48 = "4;이즈미 수영복ND;08;옳소! 옥수수를 먹게 해달라!\n#4;al\n#4;hophop\n#3;m2"
10003050-49 = "#st;[0,0];instant;1;"
10003050-50 = "#clearST\n3;하루나;03\n4;이즈미 수영복ND;08\n#4;d\n#3;d\n#wait;1500"
10003050-52 = "3;이오리 수영복ND;05;간신히 문제아 녀석들을 처리했다고 생각했는데! 이제 와서 또 소동을 일으키게 둘까 보냐! 모두 막아!\n#3;hophop\n#3;em;[!]\n#3;a"
10003050-53 = "#na;선도부원들;넵!!\n#fontsize;100"
10003050-54 = "3;치나츠;06;하아……. 전투, 개시합니다.\n#3;em;[땀]\n#3;stiff"
