[translation]
10004020-1 = "Episode 2;Neverland with Tanghulu"
10004020-2 = "Black Tortoise Promenade"
10004020-3 = "Sensei, look! It's tanghulu made with tangerines!"
10004020-4 = "I've seen tanghulu made with hawthorn fruit, but this is my first time seeing it with tangerines!"
10004020-5 = "The neatly-arranged tangerines at the end of the stick look like golden flower buds. Just looking at them makes me happy."
10004020-6 = "Let's try one, Sensei. You'll love its sweet and sour taste!"
10004020-7 = "[s1] \"I think we should find Shun first.\"\n[s2] \"Let's get snacks later.\""
10004020-8 = "But...the menu at this tanghulu shop changes every season, so if we don't eat it now, who knows when we'll get to eat it again?"
10004020-9 = "But...the menu at this tanghulu shop changes every season, so if we don't eat it now, who knows when we'll get to eat it again?"
10004020-10 = "After I'm done, I'll make sure to brush my teeth and listen to the instructors..."
10004020-11 = "Please, get me one!"
10004020-12 = "Pretty please?"
10004020-13 = ""
10004020-15 = ""
10004020-16 = "[ns3] \"How can I say no to that face?\"\n[ns4] \"Okay, just one, then.\""
10004020-17 = "Wow! Thank you, Sensei!"
10004020-18 = "Wow! Thank you, Sensei!"
10004020-19 = ""
10004020-21 = "(Huh? Sensei seems gentler than usual somehow.)"
10004020-22 = "(Is it because I look like a little kid?)"
10004020-23 = "(It is a bit disrespectful to take advantage of Sensei like this...but for now, I want to enjoy this privilege.)"
10004020-25 = ""
10004020-26 = ""
10004020-27 = "Mmm! So sweet! The tanghulu from the Black Tortoise Promenade is the best."
10004020-28 = "The sugar is finely-coated on each peeled tangerine, so it melts like jelly the moment you put it in your mouth!"
10004020-29 = "How do you like it, Sensei? Isn't it incredible?"
10004020-30 = "[s5] \"Yeah, it's good.\"\n[s6] \"Everything from the Promenade is delicious.\""
10004020-31 = "Right? The Black Tortoise Promenade is the ultimate dining destination for all of Kivotos! Whatever you eat, it exceeds your expectations!"
10004020-32 = "Right? The Black Tortoise Promenade is the ultimate dining destination for all of Kivotos! Whatever you eat, it exceeds your expectations!"
10004020-33 = "President Rumi, who represents the Promenade, has a knack for not only traditional Shanhaijing cuisine, but also fusion cuisine across various schools. She releases wonderful new creations all the time."
10004020-34 = "But Genryumon, the student council of Shanhaijing, seems to dislike the Promenade's food, saying that it upsets the \"tradition\" and \"stability\" of Shanhaijing."
10004020-35 = "According to what I've heard, there are also rumors that the two forces are fighting a fierce battle behind the scenes to control Shanhaijing..."
10004020-36 = "[s] \"Where did you learn all of this, Shunling?\""
10004020-37 = "Th-That's because of...Shun!"
10004020-38 = "I'm always listening to Shun. She's so well-informed. Ahaha..."
10004020-39 = "Genryumon and the Black Tortoise Promenade are both so good to the students of the Plum Blossom Garden, so we hope they don't fight..."
10004020-40 = "It's hard enough taking care of young children. I can only imagine how difficult it must be to manage a huge organization."
10004020-41 = "[s7] \"You sound like an adult.\"\n[s8] \"You're very mature for your age.\""
10004020-42 = "Huh?! Do I look that old?"
10004020-43 = "Huh?! Do I look that old?"
10004020-44 = "I thought I looked so young... Do I still look old?"
10004020-45 = "Am I still acting like an old person, even though I look young?!"
10004020-46 = "[s] \"I meant it as a compliment...\""
10004020-47 = "C-Compliment?"
10004020-48 = "R-Right. Kids want to grow up fast, so being called mature is usually a compliment! Ahaha..."
10004020-49 = "Oh, how silly of me!"
10004020-50 = "[s] \"By the way, what did you mean by looking younger?\""
10004020-51 = "S-Sensei, did you finish the tanghulu? Well, gee... I-I guess Shun isn't here after all."
10004020-52 = "Since she's not at Black Tortoise Promenade, let's go somewhere else she might be."
10004020-53 = "It's this way! This way! Please hurry!"
10004020-54 = ""
10004020-56 = ""
