[translation]
10001030-1 = "Episode 3;Spec Ops No. 227"
10001030-2 = "Red Winter Academy Snowy Mountains"
10001030-4 = ""
10001030-5 = "Ugh... We've already been walking for an hour..."
10001030-6 = "Where is this place we're going? I don't even see anything that looks like a building!"
10001030-7 = "How much farther is our destination?"
10001030-8 = "Red Winter Academy is famous for being the largest of all Kivotos' academies. It takes a little more time to walk to the outskirts, I'm afraid."
10001030-9 = "I get that, but come on!"
10001030-10 = "Ugh... My legs hurt so much. I can't take another step!"
10001030-11 = "Should we rest for a bit, then?"
10001030-12 = ""
10001030-13 = "Actually, no. I have an idea!"
10001030-15 = ""
10001030-16 = ""
10001030-17 = "Comrade, carry me on your back!"
10001030-18 = "[s1] Do as Cherino says.\n[s2] Pretend to not have heard her."
10001030-19 = ""
10001030-21 = ""
10001030-22 = "There's no way you didn't hear me!"
10001030-23 = "If you don't put me on your back, I'll get up there myself!"
10001030-24 = ""
10001030-26 = ""
10001030-29 = "U-Uhhh... I-It's higher up than I thought it would be..."
10001030-30 = "But I can see much farther, and the air here feels so refreshing!"
10001030-31 = "So this is how Marina and Tomoe see the world..."
10001030-32 = ""
10001030-33 = "Wow, look at you go!"
10001030-34 = ""
10001030-35 = "You're like a monkey hanging off a tree! So cute—err...I mean, dignified!"
10001030-36 = "Y-You think so? Heeheehee..."
10001030-37 = "How about a photo to commemorate this moment?"
10001030-38 = ""
10001030-39 = "Feel free! I won't be hidden in the photo if I'm all the way up here!"
10001030-40 = ""
10001030-41 = ""
10001030-43 = ""
10001030-44 = ""
10001030-45 = ""
10001030-47 = ""
10001030-49 = ""
10001030-50 = "Wow! Look, Cherino. You look so tall when you're on Sensei's back!"
10001030-51 = "Let's see..."
10001030-52 = ""
10001030-53 = ""
10001030-54 = "You're right!"
10001030-55 = "Heehee. This is great. Once I'm back in power, I'll have someone let me ride on their back all the time."
10001030-56 = "No one will be able look down on me ever again! Hahaha!"
10001030-57 = "That's a wonderful idea, President Cherino."
10001030-58 = "The sight of you solemnly giving orders from atop someone's back will surely make the students of Red Winter appreciate your authority more than ever."
10001030-59 = "I know, right? Marina will be carrying me on her back when I return to the secretariat!"
10001030-60 = "Of course, she'll be punished for this whole coup business first!"
10001030-61 = "How about a month of feeding the rabbits? Wait, but rabbits are cute. She needs to do something scary and bad..."
10001030-64 = "[ns] \"I-I'm getting tired...\""
10001030-65 = "Oh, are you uncomfortable, Sensei?"
10001030-66 = "Though...I hope you're not implying that our Great Leader is too heavy. She's as light as a feather!"
10001030-67 = "As a representative of Schale, surely you're not considering abandoning the president while she's struggling to walk, right?"
10001030-68 = "[s] \"No, but...\""
10001030-70 = "What's the holdup, Comrade? Marina could be right behind us!"
10001030-71 = "We need to get to the old school building pronto!"
10001030-72 = "Yip, yip!"
10001030-74 = "After that, I walked that mountain road with Cherino on my back for nearly an hour..."
10001030-76 = "Red Winter Academy Former Institute"
10001030-78 = "We've finally arrived, President. Welcome to the Former Institute."
10001030-79 = "Although it's long abandoned, it was once a glorious place where the students of Red Winter Academy lived out their youth and studied hard."
10001030-80 = "Now it just looks like a dirty, old ruin..."
10001030-81 = "And a creepy one at that. Feels like a bear could pop out at any second."
10001030-82 = "Do we really have to stay here, Tomoe?"
10001030-83 = "Yes, but you'll surely return to the secretariat someday."
10001030-84 = "But so long as Chairman Marina is chasing you, going back isn't an option."
10001030-85 = "But if you work hard, I'm sure you'll be able to go back sooner than you think!"
10001030-86 = "R-Really?"
10001030-87 = "I guess nothing can get done unless I wield my power!"
10001030-88 = "Very well, henceforth this building will be mission command, and we will use it to reclaim the secretariat!"
10001030-90 = "Who says you get to decide something like that?!"
10001030-91 = "Wh-Who's there?! Is it be a b-bear?"
10001030-92 = ""
10001030-94 = ""
10001030-98 = ""
10001030-99 = "A-A bear? Where is it?"
10001030-100 = "Calm down, Nodoka. President Cherino just imagined things in her panic."
10001030-102 = "Panic? Me? N-Never!"
10001030-103 = "By the way, aren't you guys...?"
10001030-104 = "Hmph. So you finally recognize us?"
10001030-105 = ""
10001030-106 = "...Actually, no. I've got nothing."
10001030-107 = "What?! You actually forgot who we are? I don't believe this!"
10001030-108 = "We've been patiently waiting here, enduring the Former Institute's decrepitness, because we thought you'd come back and allow us to return to the main campus!"
10001030-109 = "Still not really ringing a bell..."
10001030-110 = "Chief Secretary Tomoe, have we always had a club here at the Former Institute?"
10001030-111 = "Not officially, but there is a holding facility here for suspended students called Spec Ops No. 227."
10001030-112 = "It's for suspensions, though, right? Why are these students still here? Shouldn't they be allowed back to the main campus?"
10001030-113 = "Ah. Well, they can only come back if they receive an order from someone—you."
10001030-114 = "...That's it! You're the pervert who got suspended for stalking our comrade here with a telescope from a rooftop on campus!"
10001030-115 = "I've been so busy leading our glorious academy that I forgot all about it!"
10001030-116 = "You exiled us to this frozen northern hellscape and forgot about us?! How could you be so irresponsible?!"
10001030-117 = "Do you realize how hard it's been to even just survive out here?"
10001030-118 = "Forget snacks. We can't even get a basic meal here!"
10001030-119 = "And we have no heater to deal with the biting cold."
10001030-120 = "And there are bugs in our blankets!"
10001030-121 = "And, occasionally, a hungry bear roams around outside..."
10001030-122 = "S-So there really is a bear here?!"
10001030-123 = "I-I can't stay here, Tomoe. I-Isn't there somewhere else we can go?"
10001030-124 = "Sorry, Cherino, now's the time you need to show what makes you the leader of Red Winter Academy."
10001030-125 = "But bears are so scary..."
10001030-126 = "Anyway, if you're here President, does that mean we can finally leave?"
10001030-127 = "Uh, I..."
10001030-128 = "Unfortunately, we don't have the authority to revoke your suspension right now."
10001030-129 = "Wh-Why not?"
10001030-130 = "President Cherino is on the run. She's been ousted in a coup."
10001030-131 = "It's that darn Marina's fault! If it wasn't for her, I wouldn't be in this miserable place! "
10001030-133 = "So, now you're just a powerless kid?"
10001030-134 = "What a letdown."
10001030-135 = "Grr...! I'm not a kid!"
10001030-136 = "I may not be in charge right now, but I'm still Red Winter Academy's Great Leader, Beautifier of Lands, and Chief of Sanitation... I am the great Cherino, she who stands on high!"
10001030-137 = "Gaze upon my magnificent mustache and know your place!"
10001030-138 = ""
10001030-139 = "Who gives a flip about your fake mustache?!"
10001030-140 = ""
10001030-141 = "Wh-What did you just say...?"
10001030-142 = ""
10001030-143 = ""
10001030-144 = ""
10001030-145 = "T-Tomoe, how did they know the mustache is fake?"
10001030-146 = ""
10001030-147 = "I'm sure it was just a lucky guess. You have nothing to worry about."
10001030-148 = "O-Of course! That girl's just a filthy brat who doesn't know what she's talking about! "
10001030-149 = "Don't think I've forgotten about you perving on Sensei through that telescope on the roof either!"
10001030-150 = "I-I'm not a pervert!"
10001030-151 = "Also, didn't you come all this way on Sensei's back?"
10001030-152 = "(I-I'm kind of jealous, though...)"
10001030-153 = "You're more of a pervert than I am!"
10001030-154 = "That piggyback ride was merely a show of the bond between my comrade and I! You thinking it's perverted actually reveals your own dirty thoughts!"
10001030-155 = "Only a pervert would stalk Sensei!"
10001030-156 = "I never stalked Sensei! That was a totally normal show of respect from afar!"
10001030-157 = "You're just lashing out because you're shorter than me!"
10001030-158 = "You're younger than me, show some respect!"
10001030-159 = "[s] \"They fight like elementary school kids...\""
10001030-160 = "Goodness, they certainly have a lot of spunk, don't they?"
10001030-161 = "However, with Chairman Marina still in charge, nothing will be solved if we keep fighting amongst ourselves."
10001030-162 = "If you don't want to stay here, please help us retake our Great Leader's station."
10001030-163 = "You're saying I have to work together with this little brat?"
10001030-164 = "I refuse!"
10001030-165 = "The feeling's mutual! I won't work with a filthy pervert like her!"
10001030-166 = "You're both stubborn as mules... This is quite the pickle."
10001030-167 = ""
10001030-168 = ""
10001030-170 = ""
10001030-171 = "There are ways of settling disputes like who is the most mature!"
10001030-172 = "Shigure?"
10001030-173 = "Some old stories say a real grown-up can drink a whole keg of wine without getting drunk!"
10001030-174 = "And in that spirit, we'll hold a drinking contest to see who is the brat and who is the grown-up!"
10001030-175 = "Shigure, we may not be on campus, but drinking alcohol is still against Red Winter Academy's rules!"
10001030-176 = "Oh, sorry, I wasn't saying we should use real alcohol."
10001030-177 = "Instead, I've got some special kompot that I made for the Ivan Kupala Festival!"
10001030-178 = "But since our refrigeration here isn't great, it may have fermented a little..."
10001030-179 = "This sounds sketchy..."
10001030-180 = "You don't have to if you're scared, President."
10001030-181 = "Though, I guess you'll never escape your reputation as a coward if you don't accept."
10001030-182 = "S-Scared? Me?! I can drink anything!"
10001030-183 = "M-Me too! There's no way I'm going to lose!"
10001030-184 = "Excellent. It's finally time for last fall's kompot to shine!"
10001030-186 = "Soon thereafter, Shigure reappeared with the fruity sour-smelling drinks."
10001030-187 = ""
10001030-190 = ""
10001030-191 = ""
10001030-192 = ""
10001030-193 = "Um... Shigure, are you sure this doesn't have any alcohol in it?"
10001030-194 = "W-Wait, was she the student who was suspended for spiking kompot with vodka...?"
10001030-195 = "All right, that's enough chitchat."
10001030-196 = "On your mark..."
10001030-197 = "Get set. Go!"
