[translation]
10005015-4 = "แฮ่ก... แฮ่ก... แฮ่ก..."
10005015-5 = "ปะ...เป็นไงบ้าง รอดรึยัง? ยังมีใครตามมาอีกรึเปล่า?"
10005015-6 = ""
10005015-8 = ""
10005015-9 = "ฮู่ว... น่าจะรอดแล้วนะคะ... เหมือนจะไม่มีใครตามมาแล้วค่ะ"
10005015-10 = "ไม่น่าจะมีใครทันเห็นหน้าพวกเราด้วย..."
10005015-11 = "คุณครูไม่เป็นไรใช่มั้ยคะ? บาดเจ็บตรงไหนหรือเปล่าคะ..."
10005015-12 = "[s1] \"ไม่เป็นไร ครูไม่ได้บาดเจ็บหรอก\"\n[s2] \"ช่วงนี้ข้อเข่าไม่ค่อยดีเท่าไร...\""
10005015-13 = "โล่งอกไปทีค่ะ อันที่จริงฉันค่อนข้างกังวลอยู่น่ะค่ะ"
10005015-14 = "อ่ะฮะฮะ... นั่นก็เป็นเรื่องใหญ่อยู่นะคะ..."
10005015-15 = "จะว่าไปแล้ว..."
10005015-16 = "หัวหน้า? คนคนนั้น..."
10005015-18 = "หา...? อ๋อ นี่เหรอ?"
10005015-19 = ""
10005015-21 = ""
10005015-22 = ""
10005015-23 = "อ่ะ... อื้อ? อะไรเนี่ย...?"
10005015-24 = "เอ๊ะ...? อะ...อะไรกันเนี่ย? ที่นี่... ห้องพัก? ทำไมฉันถึงได้มาอยู่ที่ห้องพักได้ล่ะ...?"
10005015-25 = ""
10005015-27 = ""
10005015-29 = "...!! พวกเธอ...!"
10005015-30 = ""
10005015-38 = "แค่กๆ! อึก...!? "
10005015-39 = ""
10005015-41 = ""
10005015-43 = ""
10005015-44 = "ทะ... ทำไมถึงเอาตัวการ์ดมาด้วยล่ะ...?"
10005015-45 = "ถามมาได้ ก็เพราะยัยนี่จำหน้าพวกเราได้น่ะสิ ขืนปล่อยเอาไว้ เดี๋ยวคนอื่นตามหาพวกเราเจอกันพอดี"
10005015-46 = "เพราะงั้นจนกว่าเราจะทำงานนี้เสร็จ ยัยนี่ก็จะต้องอยู่กับเราในห้องนี้ด้วย"
10005015-48 = "เป็นคำพูดที่สมเหตุสมผลมากค่ะ ถึงจะรู้สึกผิดกับคนคนนั้นอยู่ก็ตาม... แต่เพื่อความปลอดภัย#nของแผนการเรา คงไม่มีทางเลือกนะคะ"
10005015-49 = "ไหนๆ ก็อยู่ในสภาพหมดสติไปแล้ว ถ้างั้นก็จับมัดแขนมัดขาเอาไว้..."
10005015-50 = ""
10005015-52 = ""
10005015-53 = "ถึงจะรู้ว่าพวกเราอยู่ที่ห้องพัก แต่เธอก็ยังไม่รู้หมายเลขห้อง เพราะงั้นใส่ผ้าปิดตาเอาไว้ดีกว่า"
10005015-54 = "แล้วก็หาอะไรยัดปากไว้ไม่ให้ส่งเสียงร้องได้ด้วยล่ะ"
10005015-55 = ""
10005015-57 = ""
10005015-58 = "[ns] \"...\""
10005015-60 = "[ns3] \"คือภาพแบบนี้มัน...\"\n[ns4] \"พวกเธอตอนทำภารกิจนี่...โหดได้โล่เลยนะ\""
10005015-61 = "หืม? หมายความว่ายังไงน่ะ?"
10005015-62 = "หืม? หมายความว่ายังไงน่ะ?"
10005015-63 = "ทั้งหมดนี้ก็เพื่อภารกิจนะ อีกอย่าง ทำแค่นี้น่ะร่างกายไม่บาดเจ็บซะหน่อย มันเป็นวิธีที่#nละมุนละม่อมที่สุดแล้ว"
10005015-64 = "ใช่แล้วค่ะ ถ้าคุณครูไม่อยู่ด้วยละก็ หัวหน้าคงจับเธอโยนลงทะเลไปแล้วค่ะ"
10005015-65 = "นี่! อาคาเนะ!"
10005015-66 = "เอาเถอะค่ะ ภารกิจของเราดำเนินมาถึงตรงนี้แล้ว ถึงจะเจอปัญหาอยู่บ้าง แต่ก็ถือเป็นเรื่องปกติ#nที่เจอได้ระหว่างปฏิบัติงาน"
10005015-67 = "เมื่อกี้บอกว่าต่อไปต้องทำอะไรนะ อาคาเนะ?"
10005015-69 = "อืม... นั่นสินะคะ ลอบเข้ามาสำเร็จแล้ว หาสถานที่ตั้งฐานทัพได้แล้ว..."
10005015-70 = "ต่อไปก็บุกยึดห้องควบคุมระบบค่ะ แต่ก่อนหน้านั้น ดูเหมือนเรามีเรื่องอื่นที่จะต้องทำอยู่ค่ะ"
10005015-71 = "เรื่องที่ต้องทำเหรอ?"
10005015-72 = "ค่ะ เห็นปฏิกิริยาของพวกการ์ดเมื่อกี้แล้วใช่มั้ยล่ะคะ เห็นได้ชัดว่าในเรือลำนี้จะมีกฎพิเศษเฉพาะตัว#nอยู่ค่ะ"
10005015-73 = "โดยเฉพาะเรื่องชุดที่ใส่ค่ะ เท่าที่เห็นดูเหมือนชุดนี้น่าจะเป็นชุดที่พวก \"การ์ด\" บนเรือใส่กันนะคะ"
10005015-74 = "อืม... แบบว่า... พอนึกดูแล้ว เมื่อกี้ก็เหมือนได้ยินอยู่เหมือนกันนะ ที่บอกว่า \"ไม่ใช่ทั้งชุดของแขก#nและไม่ใช่ทั้งชุดของการ์ด\" น่ะ"
10005015-75 = "ฉันคิดว่าชุดเมดเป็นชุดที่จะลักลอบเข้าไปได้โดยไม่น่าสงสัยซะอีก..."
10005015-76 = "เพราะที่นี่ไม่ใช่มิลเลเนียมยังไงล่ะคะ"
10005015-77 = "ช่วยไม่ได้นะคะ ถ้าอย่างนั้นก็ต้องเปลี่ยนเป็นชุดที่เหมาะกับปฏิบัติการที่นี่ก่อนค่ะ"
10005015-79 = "ชุดที่เหมาะกับที่นี่...?"
10005015-80 = "ค่ะ ฉันหามาได้สองสามชุดระหว่างทางค่ะ ฮุฮุ"
10005015-81 = ""
10005015-83 = ""
10005015-84 = ""
10005015-85 = "คิดว่าไซซ์น่าจะพอดีอยู่นะคะ เพราะปกติฉันก็วัดเอาไว้บ้าง..."
10005015-86 = "ฮะฮ่าฮ่า สมกับเป็นอาคาเนะเลยนะ จัดการได้รวดเร็วจริงๆ"
10005015-88 = ""
10005015-90 = ""
10005015-91 = "...? เดี๋ยวก่อนนะ อาคาเนะ?"
10005015-92 = "ว่าแต่เธอไปหาชุดพวกนี้มาจากไหนน่ะ? หรือว่าไปถอดมาจากพวกการ์ดที่ฟาดสลบไปเมื่อกี้เหรอ?"
10005015-93 = "แล้วที่บอกว่า \"ปกติก็วัดเอาไว้บ้าง\" นี่หมายถึงยังไง? ไปแอบวัดไซซ์ชุดพวกเราไว้ตอนไหน..."
10005015-94 = "เอาละค่ะ เลิกคุยเรื่องเล็กๆ น้อยๆ กันเถอะค่ะ"
10005015-95 = "ฉันแค่ทำไปเพื่อแผนการของเราเท่านั้น ก่อนอื่นก็ต้องเช็กก่อนว่าใส่ได้พอดีรึเปล่า... ลองใส่ดูเลยมั้ยคะ?"
10005015-96 = "หัวหน้ามาทางนี้หน่อยสิคะ ฉันคิดว่าหัวหน้าน่าจะไม่รู้วิธีใส่ เดี๋ยวฉันช่วยใส่ให้ค่ะ"
10005015-97 = "ว่าไงนะ?"
10005015-98 = "เห็นฉันเป็นเด็กๆ รึไง?"
10005015-99 = "ตายจริง... ขอโทษด้วยค่ะ หัวหน้ารู้วิธีใส่อยู่แล้วใช่มั้ยคะ?"
10005015-100 = "ก็เปล่า..."
10005015-101 = "ฮิฮิ ถ้างั้นฉันจะช่วยเองค่ะ"
10005015-102 = "อื้อ"
10005015-103 = ""
10005015-105 = "คือว่า... อาคาเนะ? ตอบคำถามของฉันก่อนมั้ย..."
10005015-106 = ""
10005015-108 = ""
10005015-109 = "ฉันเพิ่งบอกไปไม่ใช่เหรอคะ?"
10005015-110 = "อย่าไปสนใจเรื่องเล็กๆ น้อยๆ เลยค่ะ"
10005015-111 = "…"
10005015-112 = "เข้าใจแล้ว... ก็ได้ ภารกิจต้องมาก่อนเป็นอันดับแรก เพราะงั้นฉันเห็นด้วย"
10005015-113 = "นี่... ชุดนี้มันใส่ยังไงกันแน่น่ะ? ชุดแปลกๆ นี่มันใช่เสื้อผ้าที่เอาไว้ใส่จริงๆ เหรอ?"
10005015-114 = "ฮิฮิ เดี๋ยวฉันช่วยเปลี่ยนให้เองค่ะ รอสักครู่นะคะ..."
10005015-115 = "ถ้าเปลี่ยนชุดเสร็จแล้ว เราจะไปที่ห้องควบคุมระบบ แล้วก็ดำเนินแผนการขั้นต่อไปค่ะ"
10005015-116 = "หืม...?"
10005015-117 = "คุณครู? ทำไมทำหน้าแบบนั้นล่ะคะ? อยากจะพูดอะไรรึเปล่าคะ?"
10005015-118 = "[s5] \"หายไปคนหนึ่งรึเปล่า...?\"\n[s6] \"อาสึนะล่ะ...?\""
10005015-119 = "ตายจริง...?"
10005015-120 = "ตายจริง...?"
10005015-121 = "อ่ะฮ่า... เข้าใจแล้วค่ะ คุณครูเพิ่งมาร่วมปฏิบัติภารกิจกับพวกเราครั้งแรกสินะคะ"
10005015-122 = "คุณครูไม่ต้องกังวลเรื่องรุ่นพี่อาสึนะหรอก รุ่นพี่เค้าเป็นคนที่เดาทางไม่ค่อยได้น่ะ..."
10005015-123 = "ต้องบอกว่าเป็นคนที่ไม่ฟังคนอื่นต่างหากล่ะ"
10005015-124 = "อ่ะฮะฮะ... รุ่นพี่เค้าเป็นประเภทที่ชอบจัดการงานด้วยวิธีของตัวเองน่ะค่ะ"
10005015-125 = "แค่บรีฟแผนเบื้องต้นระหว่างปฏิบัติการก็พอ จากนั้นรุ่นพี่ก็จะไปจัดการต่อเองค่ะ"
10005015-126 = "ที่จริงแล้วตอนนี้สำหรับพวกเรา... มีบางอย่างที่น่าสนใจกว่าอยู่นิดหน่อยน่ะค่ะ"
10005015-127 = "[s] \"....?\""
10005015-128 = ""
10005015-130 = ""
10005015-132 = ""
10005015-133 = "ฮิฮิ คุณครูคะ...?"
10005015-134 = "ถ้าคุณครูไม่ว่าอะไรละก็..."
10005015-135 = "คือว่าพวกเราจะต้องเปลี่ยนชุดกัน... ช่วยหันหลังไปก่อนได้มั้ยคะ"
10005015-136 = "หรือว่าจะให้พวกเราเปลี่ยนชุดทั้งๆ แบบนี้เลย..."
10005015-137 = "[s7] \"...?\"\n[s8] หันหลังอย่างรวดเร็ว"
10005015-138 = ""
10005015-139 = ""
10005015-142 = "(คุณครูหันหลังให้ และเสียงที่ได้ยินก็มีเพียงเสียงเปลี่ยนชุดของทั้ง 3 คน)"
