[translation]
10008130-1 = "ตอนที่ 13;ความปรารถนาปีใหม่ของเรา"
10008130-2 = "(ถึงจะมีเหตุวุ่นวายตั้งแต่วันแรกของปี แต่พอเวลาผ่านไปความวุ่นวายก็เริ่มคลี่คลายลง)"
10008130-6 = "เหตุการณ์ครั้งใหญ่ที่เกิดขึ้นในวันนี้! ตัวจริงของไดคิจิเดน!"
10008130-7 = "รวมทั้งความจริงที่เกี่ยวข้องกับแก๊งคุโรคาเมะ!"
10008130-8 = "มาฟังความเห็นเกี่ยวกับความจริงเหล่านั้นจากทางสมาชิกคณะกรรมการวินัยเกเฮนน่าที่ทำงานอย่างหนัก เพื่อคลี่คลายเหตุการณ์ในวันนี้กันเลยค่ะ!"
10008130-9 = ""
10008130-11 = ""
10008130-12 = "คุณคิดอย่างไรกับเหตุการณ์ในครั้งนี้คะ?!\n"
10008130-13 = "หืม? สะ...สัมภาษณ์งั้นเหรอ?"
10008130-14 = "เดี๋ยวนะ คือว่า... ตอนนี้ฉันอยากกลับไปพักแล้วน่ะ..."
10008130-16 = "(เรื่องราวอาชญากรรมของแก๊งคุโรคาเมะได้ถูกเผยแพร่ไปทั่วคิโวทอสโดยฝีมือของสำนักข่าวโครโนส)"
10008130-17 = "(ทางคณะกรรมการวินัยได้จับกุมหัวหน้าของแก๊งคุโรคาเมะเอาไว้ได้ และสมาชิกแก๊งที่เหลือก็กระจัดกระจายกันไป) "
10008130-18 = "(และทุกอย่างก็กลับมาเป็นปกติเหมือนเดิม)"
10008130-21 = ""
10008130-22 = "เดี๋ยวสิ! ฉันยอมไม่ได้!"
10008130-23 = "ใช่แล้ว! เรื่องตู้บริจาคเป็นเรื่องหลอกลวงงั้นเหรอ! คิดว่าพูดแบบนั้นแล้วเราจะเชื่อรึไง?!"
10008130-24 = "ความฝันที่จะซื้อหมวกกันน็อกใหม่ของพวกเรา! เอาเงินมานะ!"
10008130-25 = ""
10008130-27 = ""
10008130-28 = "ทำไมมิโกะพาร์ทไทม์อย่างฉันต้องมาจัดการเรื่องพวกนี้ด้วยเนี่ย..."
10008130-29 = "[s] \"เดี๋ยวครูช่วยแล้วกัน\""
10008130-30 = ""
10008130-32 = ""
10008130-33 = "ฮึ่ย...! ให้มันได้แบบนี้เซ่...!"
