[translation]
10001025-1 = "ตอนที่ 2;การยึดอำนาจที่โผงผาง"
10001025-2 = "สำนักงานประธานสหภาพเรดวินเทอร์"
10001025-4 = "สะ... เสียงดังน่าหนวกหูชะมัด! เกิดเรื่องอะไรกันน่ะ?"
10001025-5 = "คนเค้าจะหลับจะนอนกัน! เสียงดังแบบนี้จะไปนอนหลับได้ยังไง!"
10001025-7 = ""
10001025-8 = "ชะ... เชริโน่จัง! เกิดเรื่องฉุกเฉินค่ะ!"
10001025-9 = "เราบอกไปแล้วไม่ใช่เหรอว่าแม้จะมีเรื่องด่วนแค่ไหนก็อย่ารบกวนเวลานอนกลางวัน!"
10001025-10 = "เลขาโทโมเอะก็อยากถูกลงโทษงั้นเหรอ?"
10001025-11 = "แต่ว่า เรื่องนี้มัน..."
10001025-12 = "ฮะ... ฮึ่ม!"
10001025-13 = "ประธานเชริโน่คะ กลุ่มนักเรียนติดอาวุธกำลังบุกมาที่สำนักเลขาธิการค่ะ"
10001025-14 = "ว่าไงนะ? จะเกิดการปฏิวัติอีกแล้วเหรอ? ครั้งนี้เป็นปัญหาอะไรจากชมรมไหนอีก!?"
10001025-15 = "<แนวร่วมปลดปล่อยมินต์ช็อกโกแลต>? หรือว่า <กลุ่มนักปฏิวัติที่ต่อต้านเลมอนในคาราอะเกะ>?"
10001025-16 = "ปัญหาปฏิวัติที่เกิดในชมรมแบบนี้ ให้หัวหน้าคณะฯ มารินะจัดการก็ได้นี่นา"
10001025-17 = "ไม่เห็นจะต้องให้เรื่องเล็กๆ แบบนี้มารบกวนเวลานอนกลางวันเลย!"
10001025-18 = ""
10001025-19 = "เอ่อ... แต่ว่า..."
10001025-20 = "คนที่ก่อการปฏิวัติไม่ใช่ใครอื่น แต่เป็นหัวหน้าคณะความมั่นคง... มารินะ... ค่ะ..."
10001025-22 = "วะ... ว่าไงนะ?!"
10001025-23 = ""
10001025-24 = ""
10001025-26 = "อ่า..."
10001025-27 = "เป็นอะไรรึเปล่าคะท่านประธาน?"
10001025-28 = "มะ... ไม่เป็นไร..."
10001025-29 = "ช่างมันเถอะ! ว่าแต่ทำไมมารินะถึงมาก่อการปฏิวัติล่ะ? เรายังไม่ได้ทำอะไรให้เลยนี่!"
10001025-30 = "เรื่องนั้น... ฉันก็ไม่แน่ใจเหมือนกันค่ะ..."
10001025-31 = "หรือว่า... เป็นเพราะเราแอบกินพุดดิ้งที่มารินะเก็บไว้คราวก่อน?"
10001025-32 = "หรือว่าเพราะเรานอนหลับน้ำลายยืดบนตุ๊กตาหมีตัวโปรดของมารินะ?"
10001025-33 = "[s] \"น่าจะเป็นเรื่องพุดดิ้งนะ\""
10001025-34 = "ทะ... ทำไงดีล่ะสหาย? ไปหาพุดดิ้งมาคืนตอนนี้เลยดีไหม?"
10001025-35 = "แต่พุดดิ้งที่มีในสหภาพเรดวินเทอร์ตอนนี้มีแค่พุดดิ้งจืดๆ ที่ผสมน้ำ..."
10001025-36 = "ที่นี่อันตรายนะคะ กองกำลังป้องกันของมารินะใกล้จะมาถึงสำนักเลขาธิการแล้วค่ะ"
10001025-37 = "ตอนนี้เราเสี่ยงมากที่จะถูกโจมตี คุณครูก็ควรจะหนีออกจากที่นี่พร้อมกับพวกเราค่ะ"
10001025-38 = "ละ... แล้วจะให้หนีไปที่ไหนกันล่ะ?"
10001025-39 = "เรามีอาคารเรียนเก่าที่ไม่ได้ใช้งานอยู่ในที่ดินชายขอบของเรดวินเทอร์ค่ะ"
10001025-40 = "หากไปซ่อนตัวที่นั้น หัวหน้าคณะฯ มารินะก็ไม่น่าจะหาเราเจอได้ง่ายๆ นะคะ"
10001025-41 = "ดะ.. ได้ ถอนกำลังก่อนชั่วคราว!"
10001025-42 = "นี่ไม่ใช่การหนี แต่เป็นการถอยไปตั้งหลัก!"
10001025-43 = ""
10001025-44 = "ค่ะ รีบๆ ไปกันเถอะค่ะ!"
