[translation]
1000905-1 = "Mouthwatering Treats"
1000905-4 = "(As promised, I met up with Izumi and we headed out to the ramen shop.)"
1000905-5 = "What should I eat today?"
1000905-6 = "Strawberry jam is good with anything!"
1000905-7 = "Tonkotsu, shoyu... Don't forget the butter! ♪"
1000905-9 = "Meow!"
1000905-10 = ""
1000905-11 = "It's a cat."
1000905-12 = "Mrrrow..."
1000905-13 = "Aw... It's so cute!"
1000905-14 = "Huh? Why does it keep rubbing against my cheek?"
1000905-15 = "[s] \"Looks like it's hungry.\""
1000905-16 = "Oh, are you hungry too? But I don't have anything to give you right now..."
1000905-17 = "[s] \"I just happen to have something.\""
1000905-19 = "Purr Purr brand cat treats?"
1000905-20 = "Meow, meow, meow!"
1000905-21 = "[s] \"See? Can you come closer? Here, kitty. Here you go.\""
1000905-24 = "Nom nom nom nom."
1000905-27 = "Oh, it's eating it. Wow, it must be really delicious."
1000905-28 = "Meow."
1000905-29 = "Meeeooow."
1000905-30 = "Other cats are coming too! This is so great. Sensei!"
1000905-31 = "[s] \"Cats go crazy for this treat.\""
1000905-32 = "Wow..."
1000905-33 = "Nom nom."
1000905-34 = "Nom nom nom."
1000905-35 = "Nom nom nom nom!"
1000905-36 = "(stare)"
1000905-37 = "[s] \"Huh? Izumi, what's wrong?\""
1000905-38 = "Nom nom nom nom!"
1000905-39 = "...Tasty."
1000905-40 = "[s] \"Uh, Izumi? Wait. You can't really be...\""
1000905-41 = "*gulp*"
1000905-42 = "[s1] \"W-Wait. Izumi?!\"\n[s2] \"Are you stealing the cat treats?!\""
1000905-43 = "Uh, well... You see..."
1000905-44 = "Uh, well... You see..."
1000905-50 = "― Th-The cats...[wa:390] "
1000905-52 = "― were enjoying  themselves eating so much!  I-I couldn't help it![wa:310] "
1000905-55 = "― Eh?! H-Hey,[wa:1320] "
1000905-57 = "― don't scratch me![wa:10] "
1000905-60 = "― Wha~?!  I'm being attacked  by angry cats![wa:380] "
1000905-63 = "[ns3] \"They have a right to be mad! You stole their treats!\"\n[ns4] \"They're not for humans in the first place!\""
1000905-64 = "― B-But they looked so good![wa:1010] "
1000905-65 = "― B-But they looked so good![wa:1010] "
1000905-68 = "― B-Besides! I'm a member of the Gourmet Research Society![wa:1070] "
1000905-70 = "― I have a duty to taste everything![wa:320] "
1000905-73 = "[ns] \"I never knew that duty included animal food...\""
1000905-74 = "― I mean, come on! Premium tuna flavor...[wa:3250] "
1000905-77 = "― Why should"
1000905-79 = "― you guys get to eat such delicacies and not me?![wa:10] "
1000905-82 = "―They need to learn to share![wa:600] "
1000905-85 = "― I-I'm sorry, all right?[wa:1340] "
1000905-87 = "― There's nothing I can do about what's already eaten, though...[wa:670] "
1000905-90 = "― Eek! Don't bite me![wa:410] "
1000905-93 = "After that, Izumi and the street cats tussled for a while. Fortunately, they forgave her after being bribed with more food."
