[translation]
10007065-1 = "#title;제6화;용역부에게 모르스를!"
10007065-2 = "3;노도카 온천 온천장ND;21;헉, 헉, 헉…… 끈질기네요.\n#3;stiff\n#3;a"
10007065-3 = "5;미노리;04;헉, 헉…… 그쪽이야 말로 끈질겨.\n#5;em;[땀]\n#5;al\n#3;m1"
10007065-4 = "5;미노리;09;슬슬 패배를 인정하고 이 온천장을 철거하는 게 어때?"
10007065-5 = "3;노도카 온천 온천장ND;14;절대로 용납할 수 없어요! 이 온천장은 저희들의 유일한 희망이라고요!\n#3;hophop"
10007065-6 = "3;노도카 온천 온천장ND;21;끔찍했던 구교사 시절의 생활로 돌아가느니……"
10007065-7 = "3;노도카 온천 온천장ND;14;차라리 이 온천장과 함께 산화하는 편이 더 나아요!\n#3;em;[빠직]"
10007065-8 = "5;미노리;99;기세만큼은 훌륭하다만……\n#3;dl\n#5;m3"
10007065-9 = "5;미노리;05;용역부의 명예가 걸린 일인만큼 우리도 물러날 수는 없어!\n#5;em;[!]"
10007065-10 = "#st;[0,0];instant;1;"
10007065-13 = "5;미노리;04;큿. 오늘따라 바람이 매서운걸…….\n#5;stiff"
10007065-15 = "3;노도카 온천 온천장ND;20;하, 하하…… 구, 구교사의 추위를 우습게 보셨군요!\n#3;em;[땀]"
10007065-16 = "3;노도카 온천 온천장ND;21;추, 추우시다면 이, 이, 이만 포기하고 돌아가시는 게…… 어, 어떠신가요?\n#3;stiff"
10007065-18 = "3;미노리;04;……아니, 상식적으로 추워 보이는 건 그 쪽의 옷차림이잖아.\n#3;em;…"
10007065-19 = "3;미노리;99;한 겨울의 설산에서 얇은 기모노 한 장만 걸치고 있다니……"
10007065-20 = "3;미노리;00;그 꼴로 앞으로 한 시간은 더 버틸 수 있겠어?\n#3;em;[?]"
10007065-22 = "3;노도카 온천 온천장ND;21;우읏……!\n#3;em;[속상함]\n#3;stiff"
10007065-23 = "#st;[0,0];instant;1;"
10007065-27 = "5;시구레 온천 온천장ND;01\n#5;al\n#3;m1\n#wait;1200"
10007065-28 = "5;시구레 온천 온천장ND;03;노도카, 여기 따듯하게 데운 모르스 가져왔어\n#5;em;[음표]"
10007065-29 = "3;노도카 온천 온천장ND;03;아, 시구레 쨩. 고마워."
10007065-31 = "3;미노리;04;잠깐! 전투 중의 보급이라니, 비겁하다!\n#3;shake\n#3;em;[?!]"
10007065-32 = "3;미노리;09;이 싸움은 <용역부>와 <특별반>이 서로의 명예를 걸고 싸우는 투쟁인 바— 보급품에 기대지 말고 정정당당하게 승부해라!\n#3;hophop"
10007065-33 = "#st;[0,0];instant;1;"
10007065-36 = "1;시구레 온천 온천장ND;01\n#1;ar\n#3;m5\n#wait;1200"
10007065-37 = "1;시구레 온천 온천장ND;00;자, 용역부 친구들도 한잔해.\n#1;em;[반응]"
10007065-38 = "3;미노리;04;……어, 어라? 우리에게도 주는 건가?\n#3;em;[땀]\n#3;stiff"
10007065-39 = "1;시구레 온천 온천장ND;01;응. 지난 봄에 담가 놓은 모르스는 넘칠 만큼 충분하니까."
10007065-40 = "1;시구레 온천 온천장ND;03;감기에 걸리지 않도록 다들 따듯할 때 마셔 둬.\n#1;em;[음표]"
10007065-41 = "3;미노리;99;성의는 고맙게 받겠다만……."
10007065-42 = "3;미노리;05;이런 음료수 한 잔에 흔들릴 만큼 우리 노동자들의 의지는 무르지 않아!\n#3;em;[!]"
10007065-43 = "#st;[0,0];instant;1;"
10007065-45 = "3;미노리;01\n#3;m3\n#1;dl\n#wait;1200"
10007065-46 = "3;미노리;99\n#3;greeting\n#wait;1000"
10007065-47 = "3;미노리;99\n#3;greeting\n#wait;1500"
10007065-48 = "3;미노리;04\n#3;shake\n#3;em;[?!]\n#wait;1500"
10007065-49 = "3;미노리;08;마, 맛있어~!\n#3;em;[반짝]"
10007065-50 = "3;미노리;07;뭐야, 이 모르스? 엄청나게 달고 부드럽잖아?"
10007065-51 = "3;미노리;03;게다가 씁쓰레한 뒷맛과 함께 후끈한 온기가 온몸으로 퍼져나가서…… 추운 곳에서 마시는 음료로는 최고야!\n#3;em;[///]\n#3;stiff"
10007065-52 = "1;시구레 온천 온천장ND;03;후후, 좋아해 주니 다행이네. 내 생각에도 이번에 담근 모르스는 특히나 잘 '발효'되었거든.\n#1;em;[음표]\n#1;ar\n#3;m5"
10007065-53 = "1;시구레 온천 온천장ND;01;따듯하게 데운 모르스는 더 있는데…… 마실래?"
10007065-54 = "3;미노리;03;음, 얼마든지 받겠어!\n#3;em;[반짝]\n#3;hophop"
10007065-56 = "3;미노리;99\n#3;em;…\n#3;a\n#wait;2500"
10007065-57 = "3;미노리;07;후후, 후후후……"
10007065-58 = "3;미노리;03;정말 맛있구나. 이거라면 얼마든지…… \n#3;em;[///]\n#3;stiff"
10007065-59 = "[s] \"……괜찮아, 미노리?\""
10007065-60 = "3;미노리;08;음, 물론이다! 이 따듯한 모르스만 있다면 혹한의 추위가 몰려와도 끄떡없다!\n#3;em;[반응]"
10007065-61 = "3;미노리;07;몸 안쪽에서 열기가 후끈후끈 일어서, 오히려 덥게 느껴질 정도니까!"
10007065-62 = "3;미노리;04;아니…… 땀이 나서 추운 것 같기도 하고…… 어떻게 된 거지?\n#3;em;[땀]"
10007065-63 = "[s] \"역시 괜찮지 않잖아…….\""
10007065-64 = "3;미노리;01;으음. 춥다고 생각했더니 더 추워지는 느낌인데……."
10007065-65 = "3;미노리;99;으으…… 머리도 어지러운 게, 더 이상 견디기가 어려워…….\n#3;stiff\n#3;em;[속상함]"
10007065-66 = "5;시구레 온천 온천장ND;02;저런, 큰일이네. 땀이 식기 전에 어서 온천에 들어가 몸을 덥혀야겠어.\n#5;al\n#3;m1"
10007065-67 = "3;미노리;01;……온천?\n#3;em;[?]"
10007065-68 = "3;미노리;05;지금 우리 용역부에게 게헨나의 머저리들이 건설한 온천에서 몸을 씻으라고 권하는 건가!"
10007065-69 = "5;시구레 온천 온천장ND;01;그렇지 않아, 미노리 부장.\n#5;em;[반응]"
10007065-70 = "5;시구레 온천 온천장ND;00;반강제로 이 온천장을 떠맡기는 했지만, 게헨나의 학생들이 건설한 이 시설의 안정성이 불안한 건 우리도 마찬가지거든."
10007065-71 = "5;시구레 온천 온천장ND;03;그러니까 '키보토스 제일의 건축가들'인 용역부 부원들이 탕 안에 들어가서 직접 이 온천장의 상태를 점검해주었으면 좋겠어.\n#5;greeting\n#5;em;[음표]"
10007065-72 = "3;미노리;01;키보토스 제일의 건축가들……"
10007065-73 = "3;미노리;07;후후, 그야 당연하지. 우리를 따라올 건축가 집단은 키보토스에 존재하지 않으니까!\n#3;em;[반짝]"
10007065-74 = "5;시구레 온천 온천장ND;00;……게다가 따듯한 탕에 몸을 담근 채 마시는 모르스의 맛은 또 각별하다고?\n#5;em;[반응]\n#5;m4"
10007065-75 = "3;미노리;04;………. (딸꾹)\n#3;stiff"
10007065-76 = "#st;[0,0];instant;1;"
10007065-78 = "3;미노리;04\n#3;m2\n#wait;1500"
10007065-79 = "3;미노리;01;(소근) 혹시 모르스 이외의 음료도 있는건가……?\n#3;em;…\n#fontsize;50"
10007065-80 = "5;시구레 온천 온천장ND;03;물론이야. 우리 227호 온천장에는 손님들을 위해 손수 담근 갖가지 과일 음료를 구비해두고 있거든.\n#5;em;[반짝]"
10007065-81 = "5;시구레 온천 온천장ND;01;용역부가 우리 온천장을 손님으로서 찾아준다면, 캄포트든 모르스든 얼마든지 대접할게."
10007065-82 = "3;미노리;99;으음…… 하는 수 없지. 게헨나의 머저리들이 얼마나 형편없는 솜씨로 온천장을 지었는지 탕 안에서 느긋이 살펴봐야겠어.\n#3;em;[땀]"
10007065-83 = "3;미노리;04;……절대로 모르스가 더 마시고 싶어서 그러는 건 아니니까!\n#3;stiff"
10007065-84 = "5;시구레 온천 온천장ND;03;응, 응. 좋은 생각이야.\n#5;em;[음표]"
10007065-85 = "5;시구레 온천 온천장ND;01;다 같이 탕을 쓸 거라면 북쪽 노천의 대욕탕을 추천할게."
10007065-86 = "3;미노리;00;자, 동지들.\n#3;m3\n#5;dr\n#3;em;[반응]"
10007065-87 = "3;미노리;99;온천장의 안전과 더 많은 모르스……"
10007065-88 = "3;미노리;04;아니, 혁명적 휴식을 위하여……\n#3;stiff"
10007065-89 = "3;미노리;02;온천으로 돌격이다!\n#3;closeup\n#3;em;[!]\n#fontsize;80"
10007065-91 = "1;용역알바 붉은겨울;00\n3;용역알바 붉은겨울;00\n5;용역알바 붉은겨울;00\n#1;hophop\n#3;hophop\n#5;hophop\n#1;em;[재잘]\n#3;em;[재잘]\n#5;em;[재잘]\n#1;h\n#3;h\n#5;h"
10007065-92 = "#na;용역알바 붉은겨울;혁명적 휴식을 위하여!\n#fontsize;100"
10007065-93 = "#st;[0,0];instant;1;"
10007065-95 = "1;용역알바 붉은겨울;00\n3;용역알바 붉은겨울;00\n5;용역알바 붉은겨울;00\n#1;h\n#3;h\n#5;h\n#1;dr\n#3;dr\n#5;dr\n#bgshake\n#wait;4000"
10007065-97 = "3;노도카 온천 온천장ND;02;우와, 그 고집스럽던 용역부원들이 시구레 쨩의 설득 앞에 순한 양처럼 변했네요.\n#3;a"
10007065-98 = "5;시구레 온천 온천장ND;03;후후, 그렇게 어려운 일도 아니었는 걸.\n#5;al\n#3;m1\n#5;em;[음표]"
10007065-99 = "5;시구레 온천 온천장ND;01;맛있는 음료 한 잔과 진심을 담은 말 한마디면 부탁은 언제나 통하는 법이라고."
10007065-100 = "3;노도카 온천 온천장ND;13;같은 특별반의 동료이긴 하지만 시구레 쨩은 가끔 무섭다니까…….\n#3;stiff\n#3;em;[땀]"
10007065-101 = "[s] \"저, 시구레.\""
10007065-102 = "5;시구레 온천 온천장ND;02;응? 왜 그래, 선생님?\n#5;em;[?]\n#5;m3\n#3;dl"
10007065-103 = "[s] \"그 음료수, 정말 이상한 거 아니지?\""
10007065-104 = "5;시구레 온천 온천장ND;03;물론이야. 이 모르스는 링곤베리와 설탕, 효모만 가지고 만든 진짜 전통 모르스라고.\n#5;em;[반응]"
10007065-105 = "5;시구레 온천 온천장ND;99;다만 보관 상태가 나빴던 탓에 조금 발효되기는 했지만……."
10007065-106 = "#st;[0,0];instant;1;"
10007065-108 = "5;시구레 온천 온천장ND;01\n#5;d\n#wait;1000"
10007065-109 = "5;시구레 온천 온천장ND;01\n#5;a\n#5;closeup\n#wait;1000"
10007065-111 = "5;시구레 온천 온천장ND;03;의심스러우면 선생도 한 모금 마셔볼래?\n#5;em;[하트]\n#5;greeting\n#5;closeup"
10007065-113 = "#na;(이후, 시구레가 권하는 모르스를 거절하며 도망치듯 온천장 안으로 들어왔다…….)"
