[translation]
1000706-1 = "รักษาสุนทรียศาสตร์"
1000706-2 = "ในเมืองคิโวทอส"
1000706-3 = "ยะฮู้ววว~ ขอบคุณที่เลี้ยงไอศกรีมนะคุณครู!"
1000706-4 = "[s] \"ของขวัญสำหรับมากิที่สอบผ่านข้อสอบซ่อมไงล่ะ\""
1000706-5 = "ฉันต่างหากที่ควรซื้อให้เป็นของตอบแทนที่คุณครูสอนฉัน... "
1000706-6 = "แต่ยังไงก็ขอบคุณนะคุณครู!"
1000706-7 = "จริงด้วยสิคุณครู... รู้รึเปล่าว่าที่แถวๆ นี้มีร้านขายเสื้อเปิดใหม่ด้วยนะ?"
1000706-8 = "ฉันบังเอิญผ่านไปเห็นน่ะ มีเสื้อผ้าผู้ใหญ่เท่ๆ ขายอยู่เยอะเลย"
1000706-9 = "คงจะมีเสื้อที่ถูกใจคุณครูอยู่ด้วยแน่นอน เดี๋ยวฉันเลือกให้เอง ไปกันเถอะ!"
1000706-10 = "[s] \"ก็ได้\""
1000706-11 = "ลั่นลันล้า~ ช็อปปิ้งกับคุณครู~♪"
1000706-12 = "เอ๊ะ กลิ่นอะไรน่ะ?"
1000706-14 = "มะ... มีใครเอาขยะไปวางทิ้งไว้ตรงกำแพงนั่นอีกแล้วสินะ"
1000706-15 = "[s] \"อีกแล้ว? มีเรื่องแบบนี้บ่อยเหรอ?\""
1000706-16 = "อื้อ กำแพงตรงนี้อยู่ตรงมุมอับแล้วก็มีคนมาขีดเขียนกำแพงจนสกปรกไปหมด คนก็เลยชอบ#nเอาขยะมาทิ้งที่ตรงนี้กันน่ะ"
1000706-17 = "พอกำแพงตรงนั้นมันดูเก่าและก็สกปรก คนก็เลยเอาขยะมาทิ้งโดยไม่ได้คิดอะไรกันน่ะ"
1000706-18 = "ถ้าผนังมันตกแต่งสวยกว่านี้อีกสักหน่อยล่ะก็ คงไม่เอาขยะมาวางทิ้งกันไว้แบบนี้แน่ๆ..."
1000706-19 = "[s] \"นั่นน่ะสิ ปัญหาใหญ่เลยนะ\""
1000706-20 = "อื้อ ปัญหาใหญ่จริงๆ นั่นแหละ...."
1000706-22 = ".....\n"
1000706-27 = "ลั่นลัลล้า~♪ เก็บขยะเสร็จหมดแล้ว... แบบนี้คงดูสะอาดขึ้นแล้วล่ะนะ?"
1000706-28 = "[s] \"ทำอะไรอยู่เหรอ?\""
1000706-29 = "วะ...ว้ากกกก!? คะ...คุณครูมาตั้งแต่เมื่อไหร่เนี่ย?"
1000706-30 = "ฉันไม่ได้ทำอะไรน่าสงสัยอยู่สักหน่อย..."
1000706-31 = "[s] \"มาทำความสะอาดกำแพงงั้นเหรอ?\""
1000706-32 = "กะ...ก็คือ... ผนังมันเก่าแล้วสีก็ดูซีดแล้วก็สกปรก... แล้วฉันก็คิดว่าถ้าวาดรูปสวยๆ#nไว้บนกำแพงอาจทำให้คนที่เอาขยะมาทิ้งหยุดคิดสักนิดก่อนที่จะทิ้งขยะได้น่ะ..."
1000706-33 = "แต่ว่าสัญญาต้องเป็นสัญญา... ฉันขอโทษที่ไม่ได้รักษาสัญญา..."
1000706-34 = "คุณครูคงโกรธใช่มั้ย? งืออ..."
1000706-35 = "[s] \"แค่ครั้งนี้ครั้งเดียวนะ\""
1000706-36 = "หืม?"
1000706-37 = "[s] \"ครั้งนี้จะยอมให้เป็นกรณีพิเศษ\""
1000706-38 = "คุณครู... ขอบคุณมากเลย!"
1000706-39 = "[s] \"แต่เดี๋ยวเราจะต้องไปขอโทษเจ้าของที่นี่ด้วยกันนะ\""
1000706-40 = "อึ่ก... ก็ได้... เพราะยังไงฉันก็เป็นฝ่ายผิดนี่นา"
1000706-41 = "พอมีคุณครูอยู่ด้วยแบบนี้ก็รู้สึกอุ่นใจขึ้นมานิดๆ แฮะ ถ้าอยู่คนเดียวก็กลัวว่าจะถูกคุณลุงตำรวจ#nจับไปแบบวันนั้นอีก"
1000706-42 = "คุณครู~ ช่วยฉันจัดการกับเจ้าขยะชิ้นใหญ่นี่หน่อยได้มั้ย?"
1000706-43 = "[s] \"ได้อยู่แล้ว\""
1000706-44 = "ฮุฮุ ขอบคุณนะ"
1000706-45 = "ต่อไปถ้าไม่มีใครเอาขยะมาทิ้งตรงนี้อีกก็คงดีนะ ว่ามั้ย?"
