[translation]
10005015-4 = "*pant* *pant* *pant*"
10005015-5 = "D-Do you think we lost them? Are we safe?"
10005015-9 = "Whew. I don't hear them. We're safe for now."
10005015-10 = "At the very least, I believe our identities are still unknown."
10005015-11 = "Sensei, are you hurt? Can I help you?"
10005015-12 = "[s1] \"Not a scratch on me.\"\n[s2] \"Well, my knees have been hurting lately.\""
10005015-13 = "I'm relieved. I was a little afraid."
10005015-14 = "Ahaha... That's an issue for another time."
10005015-15 = "Moving on to more pressing matters..."
10005015-16 = "President... The guard..."
10005015-18 = "Huh?! Oh. Her."
10005015-23 = "U-Ugh. What's going...?"
10005015-24 = "Huh? This is...a cabin? Why am I in a cabin?"
10005015-29 = "...! Y-You!"
10005015-38 = "*cough* Hngh?! "
10005015-44 = "Wh-Why would you bring the guard?!"
10005015-45 = "I couldn't just leave her there, obviously! She knows our faces now!"
10005015-46 = "We won't hurt her or anything. Just leave her in here until this is over."
10005015-48 = "I have to agree with you for once. I do feel a bit sorry, but for the sake of the mission..."
10005015-49 = "Let's restrain her while she's still unconscious."
10005015-53 = "We should probably blindfold her too. She doesn't know our exact location right now."
10005015-54 = "Stuff her mouth so she can't make noise."
10005015-58 = "[ns] \"...\""
10005015-60 = "[ns3] \"This is a little, um...\"\n[ns4] \"You guys are pretty ruthless when it comes to missions.\""
10005015-61 = "I don't think I understand."
10005015-62 = "I don't think I understand."
10005015-63 = "These are the necessary precautions for any mission. And we're refraining from any lasting damage."
10005015-64 = "And if you weren't here Sensei, the president would've dropped her to the bottom of the ocean already."
10005015-65 = "Wh-What?! Akane!"
10005015-66 = "Anyways, I'm just grateful we've made it this far. It's going pretty smoothly, all things considered.\n\n\n\n"
10005015-67 = "What's next on the agenda, Akane?"
10005015-69 = "Let's see. Now that we've established our base..."
10005015-70 = "It's off to the systems office for us now. But before that..."
10005015-71 = "What's wrong?"
10005015-72 = "I believe this ship's clothing regulations are rather specific. Do you remember the guards' reactions?"
10005015-73 = "This strange bunny outfit seems to be the guard uniform here."
10005015-74 = "I think you're right. I remember the guard saying, \"Those aren't passenger school uniforms or guard outfits.\""
10005015-75 = "The maid uniform was supposed to help us blend in regardless of the environment..."
10005015-76 = "But we're not in Millennium anymore."
10005015-77 = "The easiest way for us to move about will be to adapt to our enemies."
10005015-79 = "Those bunny outfits?"
10005015-80 = "Yes, ma'am. I grabbed one for each of us on the way here."
10005015-85 = "I think you'll find the sizes fit quite well."
10005015-86 = "You sure know how to act fast in a crisis. Nice, Akane!"
10005015-91 = "...Wait a second."
10005015-92 = "Did you just take these off the guards we knocked out?!"
10005015-93 = "And even more concerning, how do you know all our measurements?!"
10005015-94 = "There, there. Don't worry your pretty head about such trivial things.\n\n\n"
10005015-95 = "Should we get dressed and make sure they all fit?"
10005015-96 = "You've never worn something like this before, President. Let me help put it on."
10005015-97 = "What?!"
10005015-98 = "Do you think I'm a little kid? Huh?!"
10005015-99 = "Oh dear, I apologize. Would you like to do it yourself?"
10005015-100 = "I don't know how."
10005015-101 = "Heehee. Then let me help."
10005015-102 = "Fine..."
10005015-105 = "A-Akane? I would, uh, still like an answer to my question..."
10005015-109 = "Do you remember what I said, Karin?"
10005015-110 = "Don't worry about trivial things."
10005015-111 = "..."
10005015-112 = "Y-Yes, understood. Agreed. Let's focus on the mission."
10005015-113 = "Hey! What the hell is this?! Are these even clothes? I can't even tell which way it goes!"
10005015-114 = "Heehee. I'm on my way, Neru."
10005015-115 = "Once everyone is changed, we'll make our way to the systems office."
10005015-116 = "Hm?"
10005015-117 = "Are you okay Sensei? Is something bothering you?"
10005015-118 = "[s5] \"Aren't we missing someone?\"\n[s6] \"...Where's Asuna?\""
10005015-119 = "Huh?"
10005015-120 = "Huh?"
10005015-121 = "Ah, I understand the confusion now. I forgot this was your first time."
10005015-122 = "The best thing to do with Asuna, is to do nothing. She's unpredictable and incorrigible."
10005015-123 = "Not like she'd listen even if you did try!"
10005015-124 = "Ahaha... She's what people would call a free spirit."
10005015-125 = "I'm allowed about two minutes of her attention during briefings before she takes off."
10005015-126 = "But you know, Sensei, there's actually a much more pressing concern right now."
10005015-127 = "[s] \"...?\""
10005015-133 = "Heehee, Sensei."
10005015-134 = "If you don't mind too much..."
10005015-135 = "We need to change now, so could you look the other way please?"
10005015-136 = "Unless you'd like to join in."
10005015-137 = "[s7] \"...Ah.\"\n[s8] Turn around hastily."
10005015-142 = "I turned around to the quiet sounds of them changing clothes."
