[translation]
10000090-1 = "ตอนที่ 9;ความฝันของ[ruby=นินจา]เด็กสาว[/ruby]"
10000090-2 = "(แผนการที่มุทะลุของประธานกลุ่มการค้าเนียนเต็นมารุแห่งย่านการค้าเฮียกคิยาโค#nล้มเหลวอย่างไม่เป็นท่า)"
10000090-3 = "(ส่วนพวกปีศาจก็ชิงหนีไปทันทีที่เนียนเต็นมารุพ่ายแพ้)"
10000090-4 = "(และตอนนี้...)"
10000090-6 = "ฮึ่มม! เด็กพวกนั้นดื้อด้านชะมัด!"
10000090-7 = ""
10000090-8 = "ฮ้าวว... zzZ ถึงจะคลี่คลายสถานการณ์ได้ แต่พวกตัวปัญหาก็ยังเหลืออยู่เยอะแยะเลย~"
10000090-9 = "เราต้องออกไปตรวจตราพื้นที่ก่อนที่พวกมันจะกลับมาแก้แค้นนะ! รุ่นพี่สึบากิ! รุ่นพี่มิโมริ!"
10000090-10 = "อื้ม! ทุกคนพยายามเข้าอีกหน่อยนะคะ เพื่อฉากจบที่สวยงามของเทศกาลยังไงล่ะ!"
