[translation]
10000010-1 = "Episode 1;Welcome to Momoyodou"
10000010-2 = "Momoyodou? The famous tea shop?"
10000010-3 = "Momoyodou's strawberry anmitsu is the best!"
10000010-4 = "Talkin' about Momoyodou, are you? Well, MY favorite there is..."
10000010-5 = ""
10000010-6 = "Shizuko's beautiful smile!"
10000010-8 = "Finding directions to Momoyodou turned out to be pretty easy."
10000010-11 = ""
10000010-12 = "Come on in, Boss! Welcome!"
10000010-13 = "I was told you were coming from the Schale Family. The name's Pina.#nPut 'er there!"
10000010-14 = "[s1] \"The what...?\"\n[s2] \"Where?\""
10000010-15 = "Wait, wait, wait! Pina...! Don't scare off Sensei!"
10000010-16 = "Wait, wait, wait! Pina...! Don't scare off Sensei!"
10000010-17 = "Huh? But, President..."
10000010-18 = "You said to give Sensei a warm welcome whenever I see them!"
10000010-19 = "That is NOT what I meant. I was just talking about making a good first impression. "
10000010-20 = "You can only make a first impression once, after all."
10000010-21 = "The plan was to look as cute as possible upon our first meeting#nso I could get Sensei's affection points WAY up from the onset."
10000010-22 = "[s] \"So, um...\""
10000010-23 = "R-Right! I forgot you were already here, Sensei!"
10000010-24 = "What I meant to say was..."
10000010-25 = "T-Teeheehee...?"
10000010-26 = "M-Moving on... Ahem!"
10000010-27 = ""
10000010-28 = ""
10000010-29 = "It's nice to meet you, Sensei!"
10000010-30 = "Welcome to Momoyodou! Nyan!"
10000010-31 = "[s] \"'Nyan'...?\""
10000010-32 = "Allow me to show you around!"
10000010-33 = "Pina! We have a customer!"
10000010-34 = "Understood. Your wish is my command, Boss!"
10000010-35 = "I told you not like that!"
10000010-37 = "Anyway, it's great that you're here, Sensei!"
10000010-38 = "[s] \"Yep, that's me. Sensei. The one from Schale.\""
10000010-39 = "I guess I should make a formal introduction too, huh?"
10000010-40 = "I'm Kawawa Shizuko."
10000010-41 = "I'm also the president of Allied Hyakkiyako Academy's Festival Operations Department and owner of this traditional tea shop: Momoyodou!"
10000010-42 = "That also makes me the face of Momoyodou—this tea shop's very own idol!"
10000010-43 = "I work here too! Think of me as the muscle!"
10000010-44 = "The name's Pina, and I'm walking the path of justice and chivalry!"
10000010-45 = "[s] \"It's nice to meet you both.\""
10000010-46 = "So is this your first time at Allied Hyakkiyako Academy?"
10000010-47 = "Either way, I should go over some of the Festival Operations Department's general talking points."
10000010-48 = ""
10000010-50 = "To start with: What IS Allied Hyakkiyako Academy?"
10000010-52 = "Hyakkiyako is an academy that has focused on the tourism industry since its founding."
10000010-54 = "Festivals, hot springs, music, entertainment..."
10000010-55 = "Not to mention delicious food!"
10000010-57 = "It's a place where diverse cultures and students come together in harmony!"
10000010-59 = "The Festival Operations Department is in charge of, well, the festivals.#nFestivals are the largest attraction of Hyakkiyako's tourism industry."
10000010-60 = "Our club is tasked with planning, hosting, and the overall management!#nIsn't that right?"
10000010-61 = "Correct! And Momoyodou is our club's cool hideout!"
10000010-62 = "We've been working day and night to prepare for the Hyakkiyako Cherry Blossom Festival!"
10000010-63 = "Impressed? Behold the power of the Festival Operations Department!"
10000010-64 = "[s] \"The streets were certainly bustling.\""
10000010-65 = "Phew. It's good to see the Cherry Blossom Festival has gone well after the effort we put in, but still..."
10000010-66 = "*sigh* We've had some troublemakers recently."
10000010-67 = "They caused another scene just earlier today."
10000010-68 = "[s] \"So that's why you reached out to me.\""
10000010-69 = "Exactly. Sorry to say that we didn't invite you over just to stop and smell the cherry blossoms..."
10000010-71 = ""
10000010-72 = "President! They're up to no good again!"
10000010-73 = "Argh! It's them! Are they the devil or what?! All I had to do was MENTION them!"
10000010-74 = "Uh, I mean..."
10000010-75 = "What could THAT be...? T-Teeheehee."
10000010-76 = "Sorry. Gotta keep up appearances. A-Anyway, I'll tell you everything in detail when we get there!"
10000010-79 = "Hahaha! We are the Mouryo—the spirits dwelling the streets of Hyakkiyako!"
10000010-80 = "So you can call us...the Street Mouryo! Get it?"
10000010-81 = "Come on! Our client wants us to make a ruckus, so let's get to it!"
10000010-83 = "[ns3] \"Is this also part of the festival?\"\n[ns4] \"I didn't realize festivals had gotten so extreme.\""
10000010-84 = "D-Don't be ridiculous! What kind of festival has incendiary explosions?!"
10000010-85 = "D-Don't be ridiculous! What kind of festival has incendiary explosions?!"
10000010-86 = "They're just saboteurs here to ruin the festival!"
10000010-87 = "Sabotaging a festival like this is as low as it gets!"
10000010-89 = "And the Festival Operations Department is powerless to stop us! "
10000010-90 = ""
10000010-92 = "Everyone! Attack!"
