[translation]
10009060-1 = "Episode 6;The Final Confrontation!"
10009060-2 = "South Corrections Bureau Facility 9"
10009060-3 = ""
10009060-4 = ""
10009060-5 = ""
10009060-6 = ""
10009060-8 = "The Security Bureau seems busier than ever."
10009060-9 = "Well, that's because Corrections has had to increase its security more than it ever has before."
10009060-10 = "With all of these improvements, if Wakamo escapes again..."
10009060-11 = "...no one's getting off the hook with a simple apology."
10009060-12 = "Security's been heightened so much that the captain says there shouldn't be a single gap in our defenses."
10009060-13 = "And we have those two students from Millennium backing us up too!#nOur electronic security is in good hands!"
10009060-14 = "I mean, sure. Let's just hope they can do their jobs between all the comments about how bad our cybersecurity was before they got here."
10009060-15 = "Jokes aside, we should be good now..."
10009060-16 = "You don't sound so convinced. What's wrong?"
10009060-17 = "Yeah, something still feels off..."
10009060-18 = "...but maybe I'm overthinking it. That's probably the issue."
10009060-19 = ""
10009060-21 = ""
10009060-23 = ""
10009060-25 = "By the way..."
10009060-26 = "(It's kind of scary how she hasn't said a single word since she got caught. Do you think she's okay?)"
10009060-27 = "(Isn't that a good thing if she can bewitch anyone she comes in contact with like you heard?)"
10009060-28 = "Y-You said I'd been watching too much anime when I told you that!"
10009060-29 = "Did I?"
10009060-30 = "Well, anyway!"
10009060-31 = ""
10009060-33 = ""
10009060-35 = ""
10009060-36 = "Ahem!"
10009060-37 = "Let me give you a word of warning, Miss \"Fox of Calamity\"."
10009060-38 = "Don't even THINK about trying any funny business, you hear me?#nDo you have any idea how much trouble you've caused? "
10009060-39 = "Because of you, I'm staring down the barrel of losing my vacation days, my bonuses, my grades, AND they might force me to write a stinkin' apology letter! No way are you escaping this time."
10009060-41 = "We get bonuses? This is the first I'm hearing of it..."
10009060-42 = "Sh-Shut up, Kirino! I'm trying to do a thing here!"
10009060-43 = "O-Oh, right... I, um, was forced to write a 100-page apology letter because of you, Fox of Calamity!"
10009060-44 = "I thought my wrist was going to fall off..."
10009060-45 = "What are you crying for?! That didn't even happen yet."
10009060-46 = "Whatever."
10009060-47 = "I'm impressed at the fight you've put up thus far."
10009060-48 = "You even got those delinquents to do your dirty work."
10009060-49 = "That Fox of Calamity title isn't just for show, is it?"
10009060-51 = "..."
10009060-52 = "You seemed to be targeting Schale and Sensei."
10009060-53 = "Why would you do something like that? Out for revenge?#nTaking out your frustrations? Well, it's not like it matters."
10009060-54 = "You should just give up. You're up against more than Valkyrie now.#nThere are students from all over cooperating to stop you."
10009060-55 = "That's right! Even the Fox of Calamity won't be able to escape security this tight!"
10009060-56 = "..."
10009060-57 = "Still don't wanna talk, huh?"
10009060-58 = "Maybe you're shaking in your boots!"
10009060-59 = "Not that I could blame you. Just when you thought you were free,#nwe caught you yet again."
10009060-60 = "Now you're under lock and key at the Corrections Bureau and have no hope of escaping again. No one could blame you for accepting your fate."
10009060-62 = "I, uh, think you made your point, Fubuki..."
10009060-63 = "Huh? What's got you so nervous?"
10009060-64 = "I'm just saying... If you say too much, you're gonna jinx it."
10009060-65 = "What are you talking about?"
10009060-66 = "You can't be a good cop if you believe in superstitions like that."
10009060-67 = "I can say whatever I want! It's not like she's suddenly gonna break—"
10009060-68 = ""
10009060-71 = "Ahhh!"
10009060-72 = "Wh-What?! What's wrong?!"
10009060-73 = ""
10009060-77 = ""
10009060-79 = ""
10009060-80 = "Hey, you two. Wakamo hasn't escaped from the Corrections Bureau again, has she?"
10009060-81 = "Huh?"
10009060-82 = "Y-Yes! I-I mean, no, she hasn't! She's right here!"
10009060-83 = "Then would you care to explain to me why I can see her on my security cameras right now?"
10009060-84 = "Why are there more than one of her?"
10009060-85 = "Two, three... They just keep coming!"
10009060-86 = ""
10009060-88 = ""
10009060-89 = "You can't be serious..."
10009060-90 = "Kirino, remove her mask!"
10009060-91 = "M-Me?!"
10009060-92 = "O-Okay...!"
10009060-93 = ""
10009060-95 = ""
10009060-97 = ""
10009060-99 = ""
10009060-100 = ""
10009060-101 = ""
10009060-102 = ""
10009060-103 = "Crud. My cover's blown."
10009060-104 = "Wh-Who's this?!"
10009060-105 = ""
10009060-108 = ""
10009060-109 = "She got us! It's the old switcheroo!"
10009060-110 = "But if she's a fake, where's the real Wakamo?!"
10009060-111 = "This is bad!"
10009060-112 = ""
10009060-115 = ""
10009060-116 = "Tch. Don't tell me..."
10009060-119 = ""
10009060-120 = "At last. It's finally here."
10009060-121 = "Oh, how I've longed for this very moment."
10009060-122 = "This is my chance now that everyone's attention is turned toward the Corrections Bureau."
10009060-123 = "Now, we can finally be alone. "
10009060-124 = "Just you and me...Sensei. ♥"
