[translation]
10007115-1 = "Epilogue;A Day in the Life of Red Winter Academy"
10007115-4 = "Former Hot Springs Resort No. 227"
10007115-6 = ""
10007115-7 = "[ns] \"...\""
10007115-9 = "Th-That was a huge explosion. Are you okay, Sensei?"
10007115-10 = "[s1] \"I managed to get away, so I'm fine.\"\n[s2] \"I'll be all right.\""
10007115-11 = "Thank goodness you aren't hurt."
10007115-12 = "Thank goodness you aren't hurt."
10007115-13 = "The hot springs resort..."
10007115-14 = "It collapsed without a single pillar remaining. This is absolutely tragic."
10007115-15 = ""
10007115-17 = ""
10007115-20 = ""
10007115-21 = "It's the worst."
10007115-22 = "The hot springs we loved dried up, and even the hot springs resort building President Cherino graciously allowed us to keep has been destroyed."
10007115-23 = "Not a single thing has changed from our previous life at the Former Institute!"
10007115-24 = "Actually, to make matters worse, everything is in ashes from the explosion, so things got even worse!"
10007115-25 = ""
10007115-27 = ""
10007115-28 = "Well...I guess this is just how things are."
10007115-29 = "There are so many beautiful things we still haven't seen in this world, so we can't give up because of something like this."
10007115-30 = ""
10007115-32 = ""
10007115-33 = ""
10007115-35 = "And above all, our precious Sensei and friends are safe. I'm grateful for that!"
10007115-36 = "Me too. Thank goodness everyone's safe!"
10007115-37 = "[s] \"I'll be rooting for you, Nodoka.\""
10007115-38 = "Heehee. Thank you, Sensei."
10007115-39 = "If only I weren't covered in dust from the explosion. My hair and clothes are a mess too."
10007115-40 = "It's a pity that the hot springs are gone. I could go for a bath right now."
10007115-42 = "Same here!"
10007115-43 = "There's a bunch of gunk all over my mustache. Unacceptable."
10007115-44 = "Is there a place we can wash up in the Former Institute?"
10007115-45 = "There's a restroom, but the water's been cut off for a while now. The Spec Ops students used to heat water in a barrel and use that."
10007115-46 = "Then are you saying that I, the most powerful person at Red Winter Academy, should return to the Secretariat looking like this? It would tarnish my reputation!"
10007115-47 = ""
10007115-50 = ""
10007115-51 = ""
10007115-52 = "Nodoka, there's one open-air bath over there that didn't get caught up in the explosion."
10007115-53 = "The water's still clean, so I think it's usable."
10007115-54 = "Really?"
10007115-55 = "That's great!"
10007115-56 = "Then let's hurry and get ourselves cleaned up."
10007115-57 = "Wait! How dare the suspended students from the Former Institute try to leave me behind! Unacceptable!"
10007115-58 = "I'm going in the bath as well!"
10007115-60 = "If President Cherino is going, then so am I."
10007115-61 = "I don't want any more loud commotions... I'd just like to relax in a warm bath."
10007115-62 = "Are you trying to monopolize the right to washing as well?"
10007115-63 = "If the Secretariat students are going in the bath, we're going too!"
10007115-65 = "W-Wait a minute! The bath is too small to fit this many people at once!"
10007115-66 = "Why not? I'm okay with everyone being together in a crowded bath."
10007115-67 = "Besides, as long as there's one bath left, the Hot Spring Resort No. 227 is still open right?"
10007115-68 = "I hope you'll continue to serve us while we're here, dear 'manager'."
10007115-69 = "*sigh*"
10007115-70 = "If you put it like that, then I don't have much of a choice, now do I?"
10007115-71 = ""
10007115-73 = ""
10007115-74 = "Hot Springs Resort No. 227 is temporarily open for business!"
10007115-78 = "*sigh* What a great bath. I feel like the day's fatigue is being washed away."
10007115-79 = "It's a pity we won't be able to enjoy such a good bath soon."
10007115-80 = "Is there a way to build new hot springs without causing damage to the Secretariat?"
10007115-81 = "Cherino, you can't get rid of the dirt just by running water over your face like that."
10007115-82 = "Come over here. I'll wash you myself."
10007115-83 = "Ugh! I'm not a child! Don't touch my mustache!"
10007115-84 = ""
10007115-88 = "There's something special about drinking mors in a hot bath."
10007115-89 = "Huh? What's in that sake bottle?"
10007115-90 = "Surely you're not shamelessly drinking in front of Secretariat's Security Council, are you?"
10007115-91 = "No way. This is the special mors I made last spring."
10007115-92 = "It's just a bit fermented."
10007115-93 = "Huh? What did you just say?"
10007115-94 = "Heehee. Nothing at all."
10007115-95 = "If you're so suspicious, would you like a drink as well?"
10007115-96 = "Well, I suppose just a sip."
10007115-97 = ""
10007115-101 = "Comrades! Although we retreated today because of the new weapon of the evil tyrant, this is by no means our defeat! We are taking one step backward to take two steps forward!"
10007115-102 = "Next time, let's sabotage that troublesome tank first to cut off any impending danger and achieve a revolutionary victory!"
10007115-103 = "It's a sabotage! A revolution!"
10007115-104 = ""
10007115-108 = "Ugh. This is why I didn't want to bathe with everyone. Too noisy."
10007115-109 = "[s] \"Still, it's good to see everyone in such high spirits.\""
10007115-110 = "It's hard to imagine Red Winter students any other way."
10007115-112 = "Sensei."
10007115-113 = "I know a lot happened today, but did you enjoy your visit to the resort?"
10007115-114 = "[s3] \"It was a fun day.\"\n[s4] \"I had a blast.\""
10007115-115 = "I'm glad to hear it. Heehee."
10007115-116 = "I'm glad to hear it. Heehee."
10007115-117 = "We may no longer have any hot springs, but I hope you'll come visit us again."
10007115-118 = "Spec Ops No. 227, that is."
10007115-119 = ""
10007115-121 = ""
10007115-122 = ""
10007115-124 = "We'll be waiting for you, Sensei!"
10007115-125 = "Hot Springs Resort No. 227 Daily Logs!"
