[translation]
10005030-1 = "Episode 3;Ruthless Interrogation"
10005030-2 = "We returned to the cabin and approached the Bunny Girl Guard who was still tied up and unconscious."
10005030-3 = ""
10005030-6 = ""
10005030-7 = "M-Mmm... Mmm?"
10005030-9 = "...! Ow!"
10005030-10 = "Wh-What? What's going on?"
10005030-12 = "Huh. She woke up pretty quickly."
10005030-13 = "I'm relieved. She's rather strong, so this will be a wonderful interrogation."
10005030-14 = "Please don't scare her before we've even started."
10005030-15 = "Don't listen to them. As long as you answer our questions, nothing will happen to you."
10005030-17 = "Nothing will happen to me?! You already knocked me out, tied me up, and locked me in here!"
10005030-18 = "Who are you? What school are you from? Are you looking for money?"
10005030-19 = "Do you think you'll get away with this?"
10005030-20 = "...Huh?!"
10005030-21 = "Was that a threat? I'll beat you to a pulp!"
10005030-22 = "E-Eek!"
10005030-23 = "I-If it's money, I can't help you! I'm just a small fry!"
10005030-25 = "Heehee, we're well aware you're small fry."
10005030-26 = "But don't worry your pretty little head."
10005030-27 = "We're simply looking for a friend."
10005030-29 = "A friend? Wh-What do you mean?"
10005030-30 = "Her name is White..."
10005030-31 = "Kurosaki Koyuki. She should've arrived a few days ago. Do you know anything?"
10005030-32 = "Huh? I-I've never heard of her!"
10005030-33 = "You think you can play dumb?"
10005030-34 = "If you're lying, I've been itching to let out my frustration on someone."
10005030-35 = "W-Wait! Wait, stop!"
10005030-36 = "I-I promise you! I have no idea what you're talking about! I swear!"
10005030-37 = "Thousands of people come here every day to play the raffle!"
10005030-38 = "I would never remember all their faces, let alone one name!"
10005030-39 = "That face is looking more and more punchable."
10005030-40 = "Ahhhhhh!"
10005030-41 = "P-Please! I'm not lying!"
10005030-42 = "[s1] \"I think she really doesn't know.\"\n[s2] \"Neru. No violence.\""
10005030-43 = "Ugh!"
10005030-44 = "Ugh!"
10005030-45 = "You can consider yourself lucky. Like, seriously lucky."
10005030-46 = "You really think I feel lucky here?!"
10005030-48 = "She makes a fair point, though. She's just a guard."
10005030-49 = "And even if she was a higher up, she wouldn't just know a random passenger's name."
10005030-50 = "Well, this is awkward."
10005030-51 = "[s3] \"Why don't you try describing her?\"\n[s4] \"Is there anything about her that stands out?\""
10005030-52 = "Ah! That's a good idea."
10005030-53 = "Ah! That's a good idea."
10005030-54 = "Just what I'd expect of Sensei. A physical description could jog her memory."
10005030-55 = "And White Rabbit does stand out. A lot."
10005030-56 = "Hey, you've got ears, right? I'm gonna describe her, so listen up."
10005030-57 = "Any funny business, and I've got an itchy trigger finger! Got it?!"
10005030-59 = "Eek!"
10005030-60 = "I don't think a description would do her justice, but please take a look at this photo."
10005030-61 = ""
10005030-63 = ""
10005030-64 = "This is what our friend looks like."
10005030-65 = "She's boisterous, and you could hear her voice from miles away. The type to draw all the attention to herself."
10005030-66 = "She was probably flippant and the rudest person you've ever met. Do you remember anyone like that?"
10005030-67 = ""
10005030-69 = ""
10005030-70 = "Hmm..."
10005030-71 = "Flippant and rude..."
10005030-72 = ""
10005030-74 = ""
10005030-75 = "Ah!"
10005030-76 = "...\"Ah\"?"
10005030-77 = "*gasp*"
10005030-78 = "She said it! She said \"Ah\"!"
10005030-79 = "Ahahahaha! Got her!"
10005030-80 = "N-No! I don't know! I know nothing. Zilch! Nada! Even if I did, I can't divulge customer information!"
10005030-81 = "Heeheehee! She knows something for sure, for sure!"
10005030-82 = "Her reaction is a dead give away.\n\n\n"
10005030-83 = "Now, how should we coax it out of her?"
10005030-84 = ""
10005030-86 = ""
10005030-87 = ""
10005030-88 = "...!"
10005030-89 = "P-Please! Stop! N-No more! I'm against violence. Against it!"
10005030-90 = "I've been real cooped up on this stupid stealth mission. I finally get some action."
10005030-91 = "Don't talk too soon, okay? I'd be reaaal disappointed."
10005030-92 = "And if for even a second, you feel any kind of resentment... Just know this wouldn't be happening if you had just talked."
10005030-94 = ""
10005030-96 = ""
10005030-97 = "Sensei."
10005030-98 = "[s5] \"Right. Neru, remember the violence thing?\"\n[s6] \"Neru, let's think through our options first.\""
10005030-99 = "...Huh?"
10005030-100 = "...Huh?"
10005030-101 = "Sensei! Are you serious right now? Interrogating this numbskull was your idea in the first place!"
10005030-102 = "And you don't get into this line of work without expecting stuff like this."
10005030-103 = "Do you have a better idea? She's obviously not gonna talk."
10005030-104 = "We're in a hurry! Let's just get this over with!"
10005030-105 = "Wait."
10005030-106 = "Would you let me take a shot at it?"
10005030-107 = "Huh?!"
10005030-108 = "Huh?"
10005030-109 = "[s7] \"You, Karin?\"\n[s8] \"Do you have something in mind?\""
10005030-110 = "Yes, I think my method may work."
10005030-111 = "Yes, I think my method may work."
10005030-112 = "Trust me. No one will get hurt, and I think everyone'll leave laughing."
10005030-113 = "We'll leave laughing...?"
10005030-114 = "Is that really possible here in this situation?"
10005030-115 = "Will you let me try, Sensei?"
10005030-116 = "[s9] \"I'd be happy if this could end in laughter.\"\n[s10] \"Of course. Let's resolve this peacefully.\""
10005030-117 = "Thank you, Sensei. In that case..."
10005030-118 = "Thank you, Sensei. In that case..."
10005030-120 = ""
10005030-122 = ""
10005030-123 = "...! Wh-What's going on? What're you doing?"
10005030-124 = ""
10005030-125 = "G-Get away!"
10005030-126 = "I don't care what you do or say!"
10005030-127 = "I'll never give away a customer's information!"
10005030-128 = "..."
10005030-129 = "Eek?!"
10005030-132 = "Wh-What are you doing?! Hey...! Pfft!"
10005030-133 = "Hahaha! S-Stop! It t-tickles!"
10005030-134 = "P-P-Please! Stop! Hahahahaha! Heeheehee!"
10005030-135 = "Y-You can't! S-S-Stop it! N-Not there! P-Please!"
10005030-136 = "...Not yet."
10005030-137 = "Wahahaha! N-No! N-Not there...! Wahahahaha...!"
10005030-138 = ""
10005030-141 = ""
10005030-142 = "...Oh dear."
10005030-143 = "That certainly is effective. I'm impressed, Karin."
10005030-144 = "I couldn't have predicted this turn of events."
10005030-145 = "..."
10005030-147 = "Ugh! S-Stop! STOOOP! WAHAHAHA!"
10005030-148 = "She's getting too loud."
10005030-149 = "We'll get caught if this goes on. Let me see..."
10005030-150 = ""
10005030-152 = ""
10005030-153 = "...?! Wh-Wha...! Mmph! Mmm!"
10005030-154 = "There. Nice and quiet. Now, shall we continue?"
10005030-155 = "...Um?"
10005030-156 = "Um, Karin...?"
10005030-157 = "Mmm! Mmph! Mmm! Mmph! Mmm-hmph!"
10005030-158 = "Mmph?!"
10005030-159 = "Mmmmph! Mmm-hmm-hmmph!"
10005030-160 = "Mmph!"
10005030-161 = ""
10005030-164 = ""
10005030-165 = "...Hold on."
10005030-166 = "Why're we covering her mouth if we're interrogating her?"
10005030-167 = "This may not be violent but I'm beginning to wonder if it's any better."
10005030-168 = "Hey."
10005030-169 = "This is kinda dangerous. She's gonna pass out."
10005030-170 = ""
10005030-171 = "You may be right. We should probably stop her."
10005030-172 = "Karin. Karin? You should probably let her breathe."
10005030-173 = ""
10005030-176 = "Karin...?"
10005030-177 = "She's way too in the zone. Let me try to stop her."
10005030-179 = ""
10005030-180 = ""
10005030-181 = "Hey, Karin. Stop it. She's going to pass out."
10005030-182 = "! Mmmmph! Mmm-hmm-hmmph!"
10005030-183 = ""
10005030-185 = ""
10005030-186 = ""
10005030-187 = "Mmmmmmmph!!!"
10005030-188 = "Karin!"
10005030-189 = "...HEY!!!"
10005030-190 = "...?! Wh-What happened?"
10005030-191 = "Did you say something, Neru?"
10005030-192 = "Yeah, I called you. Like, a lot."
10005030-193 = "You know... You're not gonna get any information out of her if you cover her mouth."
10005030-194 = "And she's gonna pass out."
10005030-195 = "Oh... Um?"
10005030-196 = ""
10005030-198 = ""
10005030-199 = "...Uh-oh."
10005030-200 = "[s] \"...\""
10005030-201 = ""
10005030-203 = ""
10005030-204 = "Ah!"
10005030-205 = "...She passed out."
