[translation]
10000050-1 = "#title;제5화;축제가 열리는 거리"
10000050-2 = "#na;고용주;뭐? 또 당했다고? 이즈나는? 이즈나는 어딜 갔지?"
10000050-3 = "1;망량즈 A;01;그 녀석도 도움이 안 돼! 닌자라니, 장난치는 거냐구!\n#1;a\n#1;hophop\n#1;em;[!]"
10000050-4 = "5;망량즈 B;04;오늘도 여기 오기 전에, 볼일이 있다면서 뛰쳐나갔음다.\n#5;a"
10000050-5 = "#na;고용주;흐음. 모처럼 좋은 실력을 갖추고 있다고 생각했거늘."
10000050-6 = "#na;고용주;(결국 여기까지인가.)"
10000050-7 = "5;망량즈 B;02;이대로 계속 가면 축제를 방해하기 전에, 전부 그 샬레의 선생님이란 어른한테 당해버릴 검다-\n#5;em;[반응]"
10000050-8 = "#na;고용주;샬레의 선생님. 그 정도의 힘을 지녔다고는 도저히 믿기 힘들지만. 뭐, 하는 수 없지."
10000050-9 = "#na;고용주;지금 상점가 거리에 몇이나 되는 망량즈가 모였지?"
10000050-10 = "1;망량즈 A;05;어, 대충 120명 쯔음?\n#1;em;…"
10000050-11 = "#na;고용주;그럼 좋아. 슬슬 적극적으로 움직일 필요가 있는 국면이군."
10000050-12 = "#na;고용주;특단의 조치다. 지금부터 내가 하는 말을 잘 들어라."
10000050-13 = "1;망량즈 A;05\n5;망량즈 B;02\n#1;d\n#5;d\n#wait;1000"
10000050-14 = "1;망량즈 A;01\n5;망량즈 B;01\n#1;a\n#5;a\n#wait;1000\n#1;closeup\n#5;closeup\n#1;h\n#5;h"
10000050-15 = "#na;(소근소근 쿵떡쿵떡 재잘재잘 깜짝깜짝)"
10000050-16 = "1;망량즈 A;06;엣…… 정말 그래도 돼?\n#1;closeup\n#1;shake\n#1;em;[?!]"
10000050-17 = "5;망량즈 B;04;정말임까? 정말로 저질러버림까? \n#5;closeup\n#5;stiff"
10000050-18 = "#na;고용주;마지막 변수를 제거하기 위해서다."
10000050-19 = "#na;고용주;이번 일만 처리해준다면, 모든 계획은 성공하고, 너희들도 계약대로 거대한 인센티브를 받을 수 있다."
10000050-20 = "1;망량즈 A;05;뭐, 그렇다면야. 알았어. 보스.\n#1;closeup\n#1;greeting"
10000050-21 = "5;망량즈 B;03;넷! 알겠슘돠!\n#5;closeup\n#5;hophop\n#5;em;[반응]"
10000050-22 = "#na;고용주;물론……. 이건 전부 이즈나에겐 비밀이다."
10000050-23 = "#na;고용주;슬슬 마무리를 지을 때다."
10000050-25 = "#place;백야당"
10000050-26 = "#na;(날은 어두워졌지만, 작전회의를 위해 백야당에 모두가 모였다.)"
10000050-27 = "3;미모리;01;그런데 원흉은, 어떻게 찾으면 좋을까요?\n#3;em;[?]\n#3;a"
10000050-28 = "5;시즈코;02;가장 확실한 방법이 있어. \n#5;al\n#5;em;[반응]\n#3;m1"
10000050-29 = "5;시즈코;01;우선 길거리로 나가서, 요리조리 난장판을 만들고 있는 망량즈를 찾은 다음 단번에 포위하는 거야."
10000050-30 = "5;시즈코;05;마츠리부만으로는 힘들었지만, 수행부까지 함께한 지금이라면 가능해!\n#5;hophop\n#5;em;[!]"
10000050-31 = "#3;hide\n1;츠바키;02;포위한 다음엔~?\n#1;a\n#1;em;[?]"
10000050-32 = "5;시즈코;03;그야 포위했다면 단숨에 격퇴! 사로잡아서 포획!\n#5;hophop\n#5;em;[반짝]"
10000050-33 = "5;시즈코;01;그 뒤엔 그네들을 고용한 원흉이 누군지 밝혀내면 끝!\n#5;greeting"
10000050-34 = "5;시즈코;05;필요에 따라선 과격한 방법도 불사하겠어!\n#5;em;[빠직]\n#5;jump"
10000050-35 = "1;츠바키;02\n5;시즈코;05\n3;피나;02;과연! 부장님임다! \n#3;a\n#3;greeting"
10000050-37 = "3;피나;05;의리를 모르는 악당들에겐 새끼손가락 싹둑형인 겁니다!\n#3;closeup\n#3;em;[!]"
10000050-38 = "3;카에데;08;우와…….\n#3;em;…\n#3;stiff"
10000050-39 = "3;카에데;08\n5;미모리;04;어머나…….\n#5;a"
10000050-40 = "3;카에데;08\n5;미모리;04\n1;츠바키;08;후아암…….\n#1;a"
10000050-41 = "[s] 말없이 경악한다."
10000050-42 = "3;카에데;08\n5;미모리;04\n1;츠바키;08\n#1;d\n#3;d\n#5;d\n#wait;1000"
10000050-43 = "3;피나;08;그……, 다시 생각해보니 피나도 거기까진 너무 한 거 같습니다. 부장…….\n#3;a\n#3;stiff\n#3;em;[속상함]"
10000050-44 = "3;시즈코;04;아니아니아니, 거기까지 생각하진 않았거든?!\n#3;shake\n#3;em;[?!]"
10000050-45 = "3;시즈코;05;중요한 건, 붙잡아서 원흉을 불게 만든다. 이거라구!\n#3;hophop"
10000050-46 = "3;시즈코;05;뭣보다 시간이 없어."
10000050-47 = "3;시즈코;06;당장 축제의 클라이맥스가 예정된 것이 바로 내일이니까.\n#3;em;…"
10000050-48 = "1;카에데;00;앗! 들은 적 있어! 불꽃놀이라고 했었지?! 홀로그램으로! 펑펑펑!\n#1;a\n#1;em;[반응]\n#3;m5"
10000050-49 = "3;시즈코;01;응, 이번 백야앵제의 절정이라고 할 수 있는 내일. 축제의 대미를 장식할 불꽃놀이를 준비했어.\n#3;greeting"
10000050-50 = "1;츠바키;02;그때도~ 망량즈가 날뛰면 단순한 소동으로 끝나지 않을 거야~"
10000050-51 = "3;시즈코;06;그리고 사전에 그걸 막지 못한 책임을 물어, 저희 마츠리부 또한…….\n#3;em;…"
10000050-52 = "1;미모리;06;시즈코 쨩……."
10000050-53 = "3;시즈코;99;으응, 아냐. 부정적인 생각은 됐어!\n#3;greeting"
10000050-54 = "3;시즈코;05;빨리 원흉을 찾아서, 내가 받는 스트레스를 그대로 떠넘겨주겠다구! 그 녀석드으을!\n#3;m3\n#3;hophop\n#3;em;[반응]\n#1;dl"
10000050-55 = "[s] \"……이젠 꾸미는 것조차 하지 않는구나.\""
10000050-56 = "#1;hide\n3;시즈코;04;자, 잔말은 됐구요!\n#3;stiff\n#3;em;[땀]"
10000050-58 = "#na;(그렇게 되어 마츠리운영관리부 그리고 수행부와 함께 거리 순찰에 나서게 되었다……만)"
10000050-59 = "3;시즈코;04;정작 망량즈, 그 녀석들, 왜 갑자기 코빼기도 보이지 않는 거얏?!\n#3;a\n#3;em;[?!]\n#3;shake"
10000050-60 = "3;피나;02;피나, 조금 알 거 같습니다! 리모콘 같은 게 분명합니다!\n#3;em;[!]\n#3;a"
10000050-61 = "3;피나;01;피나도 가끔 리모콘을 찾으면 늘 냉장고에서 찾고는 했습니다!\n#3;greeting"
10000050-62 = "3;카에데;11;나! 나요! 그게 뭔지 알고 있어! 분명 머, 머피, 응! 머핀의 법칙인가. 하는 그거야!\n#3;a\n#3;hophop"
10000050-63 = "3;카에데;11\n1;츠바키;01;맛있어 보이는 법칙이네~\n#1;a"
10000050-64 = "3;카에데;11\n1;츠바키;01\n5;미모리;03;그래도 소동이 없으니, 모두 평범하게 축제를 즐기고 있네요.\n#5;a\n#5;em;[반짝]\n#5;greeting"
10000050-65 = "#st;[0,0];instant;1;"
10000050-66 = "#clearST\n3;카에데;11\n1;츠바키;01\n5;미모리;03\n#1;d\n#3;d\n#5;d\n#wait;1000"
10000050-68 = "3;시즈코;04;으으읏! 이럴 리가 없어. \n#3;a\n#3;stiff\n#3;em;[속상함]"
10000050-69 = "3;시즈코;05;망량즈 녀석들이라면 지금이라도 저기서 바로……!"
10000050-70 = "3;시즈코;05\n#3;d\n#wait;1000"
10000050-71 = "#zmc;move;632,-222;1896;1000\n#na;미아;으아아앙~! 엄마~! 아빠~! 어디있어~!\n#fontsize;80"
10000050-73 = "3;미모리;02;어머나, 미아가 된 꼬마 아가씨?\n#3;a\n#3;em;[반응]"
10000050-74 = "3;미모리;02\n5;카에데;01;가만 있을 수 없는 사안 발생!! 수행부 출동 건이야, 츠바키 선배!\n#5;a\n#5;hophop\n#5;em;[!]"
10000050-75 = "3;미모리;02\n5;카에데;01\n1;츠바키;08;출~동~\n#1;a\n#1;em;…"
10000050-76 = "3;미모리;02\n5;카에데;01\n1;츠바키;08\n#1;dr\n#3;dr\n#5;dr\n#wait;1500"
10000050-78 = "3;시즈코;04;으, 응? 자, 잠깐……!\n#3;shake\n#3;em;[?!]\n#3;a"
10000050-79 = "#na;공연 스태프;앗! 시즈코 씨! 여기 있었습니까? 한참을 찾았습니다요!"
10000050-80 = "#na;공연 스태프;내일 있을 불꽃놀이 행사 준비로 상담드릴 게 있습니다만."
10000050-81 = "3;시즈코;04;읏?! 하필 이럴 때……!\n#3;stiff"
10000050-82 = "3;시즈코;05;하지만……. 마츠리부 부장으로서 모른 체 할 수는……. 으윽! 피나! 여기는 맡길게!\n#3;em;[반응]"
10000050-83 = "3;시즈코;05;선생님과 함께 망량즈를 발견하면, 잘 감시해야 해!\n#3;m1"
10000050-84 = "5;피나;03;라져-입니다! 피나에게 맡겨만 주세요!\n#5;al\n#5;hophop"
10000050-85 = "3;시즈코;05\n#3;dl\n#wait;1500"
10000050-86 = "#3;hide\n5;피나;02;음음! 다들 갑자기 바빠져 버렸습니다!\n#5;m3"
10000050-87 = "[s] \"망량즈가 아니었다면, 이게 당연한 거였겠지.\""
10000050-88 = "5;피나;03;과연, 두목! 날카로운 통찰입니다!\n#5;greeting\n#5;em;[반짝]"
10000050-89 = "5;피나;05;망량즈만 아니었으면 축제 준비도 제대로, 저희 마츠리부도 열심히 뛰어다녔을 겁니다!\n#5;hophop"
10000050-90 = "5;피나;08;그런데 이런 일로 모두가 힘들어하다니, 피나도 무척……."
10000050-91 = "5;피나;04;아앗! 실망하고 있을 때가 아닙니다! 지금 두목과 함께 있는 건, 피나 혼자 뿐?!\n#5;stiff"
10000050-92 = "5;피나;02;이건 행동대장으로서, 빈틈을 보이면 안 되는 '씬'이로군요! <의리 없는 냥냥펀치>에서 봤습니다! \n#5;em;[반응]"
10000050-93 = "[s] \"잘 부탁해. 피나.\""
10000050-94 = "5;피나;01;넵! 두목의 신변 보호 및 축제 거리의 치안은…….\n#5;jump"
10000050-95 = "5;피나;03;이 행동대장 피나에게만 맡겨주세요!\n#5;em;[반짝]"
10000050-96 = "#all;hide\n#bgshake\n#na;(와장창!)\n#fontsize;100"
10000050-97 = "[s1] \"말하자마자 트러블이?!\"\n[s2] \"망량즈가 또?!\""
10000050-101 = "1;불량 학생 A;02;아앙? 그러니까 이게 실패라고오?\n#1;a\n#1;em;[반응]"
10000050-102 = "5;불량 학생 B;02;지금 우릴 물로 보는 거냐?! 앙?!\n#5;a\n#5;em;[빠직]\n#5;stiff"
10000050-103 = "#na;노점상 아저씨;하, 하지만 여기 잘 보시면 모서리 끝이 깨져서……."
10000050-104 = "1;불량 학생 A;01;됐고! 뽑기는 전부 성공했으니까. 얌전히 상품권을 내놓으라고!"
10000050-105 = "5;불량 학생 B;03;3천 엔짜리 축제 쿠폰, 그것만 받으면 이 가게의 뽑기를 전부 성공시켜주마!\n#5;em;[재잘]"
10000050-106 = "#na;노점상 아저씨;히, 히이이익!! 어떻게 그런 잔인무도한 짓을! 그렇게 되면 뭘로 장사하라고!"
10000050-107 = "1;불량 학생 A;03;크크큭! 그것이 우리 뽑기 달인이 축제를 즐기는 법이지!\n#1;em;[음표]\n#1;greeting"
10000050-108 = "5;불량 학생 B;03;우리에게 걸린 걸 후회하라고!\n#5;hophop"
10000050-109 = "1;불량 학생 A;03\n5;불량 학생 B;03\n#1;d\n#5;d\n#wait;1000"
10000050-110 = "3;피나;04;저건……! 축제 때면 어김없이 자연발생 하는 뽑기 양아치! \n#3;a\n#3;stiff\n#3;em;[반응]"
10000050-111 = "[s] \"한 여름의 날벌레 같은 거야?!\""
10000050-112 = "3;피나;05;축제 상인들이 두려워하는 뽑기 킬러들입니다! 두목!"
10000050-113 = "3;피나;05;이건 두목과 피나가 나설 때입니다!\n#3;jump"
10000050-114 = "3;피나;05;축제의 평화를 어지럽히는 문제아는, 이 협객 피나가 용서하지 않습니다!\n#3;em;[!]\n#3;closeup\n#3;hophop"
