[translation]
1000105-1 = "การศึกษาแฟชั่น 2"
1000105-2 = "ในเมืองคิโวทอส"
1000105-3 = "คุณครูมานี่เร็ว ฉันเจออะไรบางอย่างด้วยนะ"
1000105-4 = "ฟังจากเพื่อนๆ มา ดูเหมือนว่าช่วงนี้การไปร้องเพลงที่คาราโอเกะจะได้รับความนิยมมากๆ เลยละ"
1000105-5 = "แต่ฉันก็ไม่เข้าใจอยู่ดีว่าการเข้าไปนั่งร้องเพลงในห้องแคบๆ ด้วยกันแบบนั้นมันสนุกตรงไหน..."
1000105-6 = "แต่ถ้าด่วนสรุปทั้งๆ ที่ไม่ได้ไปเห็นด้วยตาก็คงจะไม่เป็นผลดีเท่าไหร่"
1000105-7 = "เอาล่ะคุณครู เราไปลองร้องเพลงที่คาราโอเกะกันเถอะ"
1000105-8 = "[s] \"ไปกับพวกเพื่อนๆ แทนจะไม่สนุกกว่าเหรอ?\""
1000105-9 = "แบบนั้นไม่ได้นะ คาราโอเกะเป็นสถานที่ที่อันตราย"
1000105-10 = "[s] \"อันตรายงั้นเหรอ?\""
1000105-11 = "ก็คาราโอเกะน่ะเป็นแค่ห้องแคบๆ และแถมเก็บเสียงได้ดีด้วย พอเข้าไปข้างในเราก็จะไม่รู้เลยว่า#nมีอะไรเกิดขึ้นบ้างที่ข้างนอก"
1000105-12 = "ถ้าพวกคนร้ายบุกเข้ามาโจมตีตอนเราอยู่ในห้องนั้นล่ะก็... เราคงตกเป็นเป้านิ่งกันแน่ๆ"
1000105-13 = "เพราะงั้นคราวนี้การที่ฉันจะไปกับ <สหายร่วมรบ> ที่ไว้ใจได้อย่างคุณครูก็สมเหตุสมผลแล้ว"
1000105-14 = ""
1000105-15 = "เอาละ ถ้างั้นไปร้องเพลง.... ไม่สิ ไปสืบเรื่องห้องคาราโอเกะกันเถอะ"
1000105-17 = "จากนั้นทั้งสองก็ไปที่คาราโอเกะ และร้องเพลงด้วยกันอย่างสุดเหวี่ยง"
1000105-18 = "คุณครูแอบตกใจเล็กน้อยที่เอมิร้องเพลงได้ดีกว่าที่คิดเอาไว้..."
