[translation]
1000106-1 = "ความสมบูรณ์แบบของแฟชั่น"
1000106-2 = "ร้านขายเสื้อผ้าสตรี ห้างสรรพสินค้า"
1000106-3 = ""
1000106-4 = ""
1000106-5 = ""
1000106-6 = ""
1000106-7 = ""
1000106-8 = "ไม่ได้มาร้านขายเสื้อนานแล้วเหมือนกันนะ#nปกติฉันจะไม่ซื้อชุดใหม่จนกว่าชุดที่มีจะใส่ไม่ได้... เพราะงั้นเลยไม่ได้มาที่ร้านนี้บ่อยๆ"
1000106-9 = "ไหนดูซิ... ช่วงนี้ชั้นในแบบตะขอหน้าก็มีหลายสีเหมือนกันแฮะ... เมื่อก่อนตอนที่มีไม่กี่แบบ#nมันเลือกง่ายกว่าเยอะเลย"
1000106-10 = "ชั้นในแบบตะขอหน้าทำให้เวลาถอดหรือเวลาใส่ง่ายขึ้นเยอะเลย การติดตะขอชั้นในจากทาง#nด้านหลังมันยากมากจริงๆ นะ"
1000106-11 = ""
1000106-12 = ""
1000106-13 = "คุณครู สีหน้าดูไม่ดีเลยนะ... ไม่สบายตรงไหนรึเปล่า?"
1000106-14 = "[s] \"ทำไมถึงชวนครูมาที่นี่ล่ะ....?\""
1000106-15 = "หือ? ก็พิมพ์บอกในข้อความไปแล้วไงล่ะว่าอยากให้คุณครูมาช่วยเลือกเสื้อที่เหมาะกับฉัน#nให้หน่อย"
1000106-16 = "หรือว่าคุณครูมีธุระอย่างอื่นที่ต้องไปทำเหรอ?"
1000106-17 = "เสื้อชั้นในไม่ใช่เสื้อผ้า... งั้นเหรอ? พูดอะไรแบบนั้นล่ะคุณครู เสื้อชั้นในก็เป็นเสื้อผ้าชนิดหนึ่งนะ"
1000106-18 = "ถ้าใส่เสื้อชั้นในที่ไม่พอดีกับร่างกาย จะทำให้ร่างกายเสียสมดุลแล้วก็จะเหนื่อยง่ายในตอนต่อสู้ด้วย การเลือกเสื้อชั้นในให้เหมาะกับร่างกายเป็นเรื่องที่สำคัญมากเลยนะ"
1000106-19 = "[s] \"ปกติก็ใส่เสื้อชั้นในที่สบายตัวอยู่แล้วไม่ใช่เหรอ?\""
1000106-20 = "คือ... เพื่อนๆ ของฉันบอกมาว่าจะต้องใส่ชุดชั้นในที่ดูน่ารักๆ เผื่อเอาไว้สำหรับเวลาฉุกเฉิน....."
1000106-21 = ""
1000106-22 = ""
1000106-23 = "แต่ว่าฉันไม่รู้เลยว่า \"ชุดชั้นในที่ดูน่ารักๆ\" มันเป็นยังไง เพราะงั้นเลยอยากให้คุณครูเลือกให้หน่อย"
1000106-26 = "― คุณครู ชุดนี้เป็นยังไงบ้าง เหมาะกับฉันรึเปล่า?[wa:3460] "
1000106-29 = "― ชุดชั้นในก็เป็นเสื้อผ้าเหมือนกันนี่ ทำไมถึงใส่ให้คนอื่นดูไม่ได้กันล่ะ...[wa:860] "
1000106-32 = "― เสื้อชั้นในตัวนี้ คงจะเล็กไปหน่อยสำหรับฉัน... อืม... มีไซซ์ใหญ่กว่านี้มั้ยนะ[wa:3320] "
1000106-35 = "― อืม...ไม่ดีกว่า ฉันจะลองเปลี่ยน ให้คุณครูดูก่อนดีกว่า[wa:4280] "
1000106-38 = "― ว่าไงนะ...? เปลี่ยนตรงนี้ไม่ได้เหรอ? ก็ห้องเปลี่ยนชุดมันแคบไปนี่นา...[wa:2640] "
1000106-41 = "คุณครูพยายามห้ามเอมิไม่ให้ถอดชุดชั้นในออกตอนอยู่ในร้านขายเสื้อผ้าได้สำเร็จ#nและเอมิก็ซื้อชุดชั้นในกลับมาได้สองสามชุด"
1000106-43 = "วันนี้ขอบคุณมากนะ ต้องขอบคุณคุณครูเลยทำให้ฉันได้ทุกอย่างที่ต้องการมาครบ"
1000106-44 = "คราวหน้าฉันห้ามถอดเสื้อผ้าในร้านค้าแบบนั้นอีกงั้นเหรอ?"
1000106-45 = "เข้าใจแล้วล่ะ วันนี้คุณครูก็ย้ำตั้งหลายครั้งแล้วนี่นา"
1000106-46 = "ถึงมันจะไม่สมเหตุสมผลก็เถอะ แต่ฉันสัญญากับคุณครูแล้ว....#nจะรักษาสัญญาแล้วกันนะ"
