[translation]
10000090-1 = "Episode 9; A Girl's Dream"
10000090-2 = "Date Meowru, the merchant guild president of the Hyakkiyako shopping district, had his crazy plan end in failure."
10000090-3 = "The remaining Mouryo ran away as soon as he surrendered..."
10000090-4 = "...for the most part."
10000090-6 = "Tch. You'll never take us alive!"
10000090-7 = ""
10000090-8 = "*yawn* There are still some stray nuisances around, even though the main incident has been taken care of."
10000090-9 = "We should get back to patrolling in case they try to cause more trouble out of spite. Let's go, Tsubaki! Mimori!"
10000090-10 = "Very well, then. There's still plenty of festival left, so let's make the most of it!"
