[translation]
1000309-1 = "งานจับมือแบบกองโจร"
1000309-2 = "ด้านหน้าคิโวทอส อารีน่า"
1000309-3 = "ซื้อของทุกอย่างมาพร้อมแล้ว ไหนดูซิ..."
1000309-5 = "เอ๊ะ? ทำไมคนมุงกันแบบนั้นล่ะ มีเรื่องอะไรรึเปล่านะ?"
1000309-6 = "โอ้โห คุณครู! ดูนั่นสิคะ! ท่านเพโรโร่ละค่ะ!"
1000309-7 = "เวฟแคทกับพิงค์กี้พาก้าก็มาด้วย...! คงมีโชว์ตุ๊กตาอยู่แน่ๆ เลยค่ะ!"
1000309-8 = "ฉันไม่รู้มาก่อนเลยว่าจะมีการแสดงโชว์ตุ๊กตา MOMO FRIENDS ที่นี่ด้วย..."
1000309-9 = "คะ...คุณครู! นะ...ไหนๆ เราก็มาแล้ว ไปดูโชว์ตุ๊กตาก่อนจะกลับกันดีมั้ยคะ?"
1000309-10 = "[s] \"ได้สิ\""
1000309-11 = "ขอบคุณค่ะคุณครู!"
1000309-12 = "อ๊ะ ดูสิคะคุณครู! แองกี้อาเดลีที่ถูกพวกวายร้ายล้างสมองกำลังจะโจมตีท่านเพโรโร่แล้วค่ะ!"
1000309-13 = "ท่านเพโรโร่ ระวังน้าาาา!"
1000309-15 = "ฟู่วววว... โชว์สนุกมากๆ เลยค่ะ!"
1000309-16 = "ตอนที่ท่านเพโรโร่ตะโกนว่า \"เพโรเพโร่!\" และจัดการเลียพวกวายร้าย ฉันตื่นเต้นจนเหงื่อแตก#nเต็มไปหมดเลยค่ะ!"
1000309-17 = "ไม่คิดเลยว่าจะได้เห็นท่านเพโรโร่ใกล้ๆ แบบนี้... วันนี้โชคดีจริงๆ เลยละค่ะ!"
1000309-18 = ""
1000309-20 = "เอ๊ะ....? มีการแสดงต่องั้นเหรอคะ?"
1000309-21 = "ผู้ที่ต้องการเข้างานจับมือกับท่านเพโรโร่สามารถมาต่อแถวทางนี้ได้เลยค่าาาาา!"
1000309-22 = "งานจับมือกับท่านเพโรโร่...!"
1000309-23 = "ถ้าได้ลองจับปีกที่มีขนนุ่มฟูแบบนั้นล่ะก็... คงต้องรู้สึกดีมากแน่ๆ ค่ะ"
1000309-24 = "[s] \"งั้นก็ไปต่อแถวเลยสิ\""
1000309-25 = "ฮะฮะ... ฉันเองก็อยากไปนะคะ แต่ถ้าไปตอนนี้ก็คงไม่ดี..."
1000309-26 = "คนที่ไปต่อแถวมีแต่เด็กๆ ทั้งนั้นเลย ถ้าฉันไปต่อแถวพวกเขาอาจจะมองฉันแปลกๆ ก็ได้ค่ะ..."
1000309-27 = "แค่ได้ดูโชว์วันนี้ฉันก็พอใจแล้วค่ะ"
1000309-28 = "[s] \"ถ้าชอบจริงๆ ล่ะก็ไม่เห็นต้องสนใจเรื่องพวกนั้นเลย\""
1000309-29 = "ชอบจริงๆ งั้นเหรอคะ...!"
1000309-30 = "ฉันอาจจะยังแสดงความรักที่มีต่อท่านเพโรโร่ไม่มากพอ..."
1000309-31 = ""
1000309-32 = "รีบไปต่อแถวกันเถอะค่ะคุณครู!"
1000309-33 = "[s] \"ครูต้องไปด้วยเหรอ?\""
1000309-34 = "ต้องไปสิคะ! โอกาสที่จะได้จับมือกับท่านเพโรโร่มีไม่บ่อยหรอกนะคะ!"
1000309-35 = "มือจะต้องนุ่มนิ่มนุ๊บนิ๊บน่าจับมากๆ แน่ๆ เลยค่ะ!"
1000309-37 = "หลังจากนั้นคุณครูกับฮิฟุมิก็ไปต่อแถวรอจับมือกับตุ๊กตาเพโรโร่"
1000309-38 = "(คุณครูรู้สึกว่ากลิ่นของตุ๊กตาเพโรโร่เหมือนกับกลิ่นของไก่ผัดหอมๆ...)"
