[translation]
10016020-1 = "ตอนที่2;ความยั่วยวนของร้านขายของข้างทาง"
10016020-2 = "ร้ายขายของริมถนน นอกสนามแข่งขันกีฬา"
10016020-4 = "(หลังจากสิ้นสุดการประชุมคณะกรรมการจัดงาน คุณครูก็ออกมานอกสนามกีฬาเพื่อดูบรรยากาศ#nรอบๆ งานมหกรรมแข่งขันกีฬา)"
10016020-5 = "มาเลยค่า เรายกเมนูเด็ดซานไห่จิงจาก <ย่านการค้าเทพเต่าดำ> มาให้ทุกคนถึงฮาโลเฟสติวัลแล้วค่ะ!"
10016020-6 = "มาลิ้มลองอาหารเลิศรสที่ปกติหารับประทานได้ในซานไห่จิงเท่านั้นดู แล้วลุ้นตัวโก่งไปกับการแข่งขัน#nในฮาโลเฟสติวัลกันเลยค่ะ!"
10016020-7 = "ว้าว มีร้านจากย่านการค้าเทพเต่าดำในงานมหกรรมแข่งขันกีฬาด้วยเหรอคะเนี่ย"
10016020-8 = "ฉันอยากชิมอาหารจากย่านการค้าเทพเต่าดำมานานแล้ว ไม่คิดเลยว่าจะได้มาเจอที่นี่... งั้นลองไปชิม#nกันดูหน่อยมั้ยคะ?"
10016020-9 = "แต่การกินอาหารจีนตั้งแต่เช้ามัน... น่าจะหนักไปหน่อยนะคะ"
10016020-10 = ""
10016020-12 = ""
10016020-13 = "ร้านเฮียกคิยาโคเปิดขายนอกสถานที่ค่ะ!"
10016020-14 = "มาสนุกกับการชมกีฬาไปพร้อมกับเครื่องดื่มซากุระโซดาที่เพิ่งออกมาใหม่สิคะ!"
10016020-15 = "มีขนมโมนากะที่ชิซุโกะทำเองด้วยนะคะ!"
10016020-16 = "เอ๋? นี่มัน <ร้านเฮียกคิยาโค> นี่นา?"
10016020-17 = "เพื่อนฉันที่ไปเทศกาลแห่งค่ำคืนสีขาวครั้งก่อนบอกว่าขนมในร้านเฮียกคิยาโคอร่อยมากเลยละ..."
10016020-18 = "ระหว่างรอการแข่งขันเริ่ม เราลองไปกินดูหน่อยมั้ย?"
10016020-19 = ""
10016020-21 = ""
10016020-22 = "[ns] \"บรรยากาศนอกสนามก็ครึกครื้นน่าดูแฮะ...\""
10016020-24 = ""
10016020-25 = "งื้ม อร่อยสุดๆ ไปเลย~"
10016020-26 = "กินจนอิ่มท้องแล้ว งั้นเราไปที่อื่นกันบ้างมั้ย?"
10016020-27 = ""
10016020-29 = ""
10016020-30 = ""
10016020-31 = "พวกคุณคะ หยุดตรงนั้นก่อนค่ะ!"
10016020-32 = "เอ๊ะ เอ๋...? รองหัวหน้าชมรมทวงความยุติธรรม...?"
10016020-33 = "รับประทานอาหารเสร็จแล้วก็เอาขยะไปทิ้งในถังขยะให้ดีๆ สิคะ"
10016020-34 = "ถ้ากินแล้วทิ้งขยะส่งเดชไปทั่ว ถนนที่นักเรียนคนอื่นตั้งใจตกแต่งไว้มันจะสกปรกเอานะคะ"
10016020-35 = "(อึ้ก... ชมรมทวงความยุติธรรมออกมาทำหน้าที่ในงานมหกรรมแข่งขันกีฬาด้วยเหรอเนี่ย...)"
10016020-36 = "ขะ... ขอโทษค่ะ!"
10016020-37 = ""
10016020-39 = ""
10016020-40 = ""
10016020-41 = ""
10016020-42 = "เฮ้อ... ไม่รู้ว่าเป็นเพราะบรรยากาศของเทศกาลหรือเปล่า ฉันถึงเห็นแต่นักเรียนที่เอาแต่สนุก และไม่รักษากฎกันอยู่แบบนี้น่ะค่ะ"
10016020-43 = "ขออย่าให้มีนักเรียนที่ทำให้ทรีนิตี้เสื่อมเสียชื่อเสียงอีกเลย..."
10016020-44 = "[s] \"ได้เจอกันอีกแล้วนะฮาสุมิ\""
10016020-45 = "...... คุณครู [USERNAME]?"
10016020-46 = "ได้เจอกันอีกแล้วนะคะ เมื่อกี้ต้องขอโทษด้วยนะคะที่เสียมารยาท "
10016020-47 = "สนุกกับงานเทศกาลมั้ยคะ?"
10016020-48 = "[s] \"อื้ม สนุกก็เพราะมีทุกๆ คนเลยนี่แหละ\""
10016020-50 = "[ns] \"ฮาสุมิกำลังทำงานของคณะกรรมการจัดงานเหรอ?\""
10016020-51 = "ค่ะ นอกจากช่วยจัดการการแข่งขันแล้ว การชี้แนะนักเรียนที่ทำผิดระหว่างสนุกกับงานเทศกาล และการรักษาพื้นที่ให้น่ามองก็เป็นงานของกรรมการจัดงานค่ะ"
10016020-52 = "แต่ว่าสถานที่จัดงานมันกว้างกว่าที่คิดเอาไว้มาก และนักเรียนก็มากันเยอะกว่าที่คิดอีกน่ะค่ะ..."
10016020-53 = "ฉันว่าวันนี้แค่งานของคณะกรรมการอย่างเดียวก็ยุ่งไปหมดแล้วค่ะ"
10016020-54 = "[s] \"จะว่าไป ฮาสุมิจะไม่เข้าร่วมการแข่งขันจริงๆ เหรอ?\""
10016020-55 = "คะ...? ก็ต้องอย่างนั้นสิคะ"
10016020-56 = "หน้าที่หลักของคณะกรรมการจัดงานคือการจัดงาน ไม่ใช่การลงแข่งขันน่ะค่ะ"
10016020-57 = "ถึงจะไม่ได้มีกฎห้ามไม่ให้คณะกรรมการจัดงานลงแข่งขันเองก็เถอะค่ะ..."
10016020-58 = "แล้วก็อย่างที่ฉันบอกไปก่อนหน้านี้ ในทรีนิตี้มีนักเรียนที่มีความสามารถโดดเด่นและเป็นเลิศในด้านการ#nแข่งขันกว่าฉันอีกค่ะ"
10016020-59 = "ในเมื่อได้มาเป็นคณะกรรมการจัดงานแล้ว ฉันเลยเลือกที่จะทุ่มเทให้กับการจัดงาน และการชี้แนะพฤติกรรมของนักเรียนค่ะ"
10016020-60 = "[s] \"ต้องเหนื่อยมากแน่ๆ เลย\""
10016020-61 = "ไม่หรอกค่ะ นี่ไม่ใช่เรื่องแปลกใหม่สำหรับฉันด้วยค่ะ"
10016020-62 = "ถึงนี่จะเป็นเทศกาลที่นักเรียนในคิโวทอสตั้งตารอกัน แต่สำหรับฉันมันคือการขยายเวลาทำงานของ#nโรงเรียนที่ฉันทำปกติในทุกวันอยู่แล้วค่ะ"
10016020-63 = "ก็แค่ผดุงความยุติธรรมอย่างเงียบๆ เหมือนที่เคยทำอยู่เสมอแค่นั้น—"
10016020-64 = "โอ๊ะ บังเอิญจังเลยนะคะที่เจอกันที่นี่"
10016020-65 = ""
10016020-67 = ""
10016020-68 = ""
10016020-71 = ""
10016020-72 = "อ๊ะ คุณครู [USERNAME] นี่นา"
10016020-74 = "ว่าไง คุณครู!"
10016020-75 = "[s1] \"สวัสดี! ทุกคนมาร่วมงานเหมือนกันสินะ\"\n[s2] \"ชมรมชิมอาหารก็มาฮาโลเฟสติวัลด้วยเหรอเนี่ย\""
10016020-76 = "ใช่แล้วค่ะ งานมหกรรมแข่งขันกีฬาคือมหกรรมแห่งอาหารรสเลิศมากมายที่หารับประทานในช่วงปกติ#nไม่ได้น่ะค่ะ"
10016020-77 = "ใช่แล้วค่ะ งานมหกรรมแข่งขันกีฬาคือมหกรรมแห่งอาหารรสเลิศมากมายที่หารับประทานในช่วงปกติ#nไม่ได้น่ะค่ะ"
10016020-78 = "ชมรมชิมอาหารของเราที่ต้องเฟ้นหาสุดยอดอาหารเลิศรสจะพลาดโอกาสดีๆ แบบนี้ไม่ได้ค่ะ"
10016020-79 = "[s] \"งานมหกรรมแข่งขันกีฬาคือมหกรรมอาหารรสเลิศงั้นเหรอ...?\""
10016020-80 = "ใช่ค่ะ ก็ <ฮาโลเฟสติวัล> ยังจัดเป็นงานออกร้านสินค้าที่ทำให้เห็นความสามารถของแต่ละโรงเรียนได้#nเต็มที่เลยนี่คะ"
10016020-81 = "ยิ่งเป็นมิลเลเนียมที่โดดเด่นเรื่องทักษะฝีมือแล้ว ก็อาจจะสกัดหรือเสริมรสชาติของอาหารได้ด้วย#nเทคโนโลยีรวมธาตุเคมีที่มีโมเลกุลสูง..."
10016020-82 = "และอาหารที่สร้างขึ้นจากเทคโนโลยีใหม่ก็จะนำความแปลกใหม่มาสู่โลกของอาหารที่ไร้มิติ..."
10016020-83 = "แถมในงาน <ฮาโลเฟสติวัล> ยังมีร้านที่ขายอาหารหลากหลายประเภทอีกด้วยค่ะ"
10016020-84 = "อาหารร้านริมทางที่หารับประทานได้ระหว่างเพลิดเพลินไปกับการชมกีฬาก็เป็นสิ่งที่พบได้เฉพาะใน#nงานมหกรรมแข่งขันกีฬาด้วยค่ะ"
10016020-85 = "ส่วนร้านอาหารท้องถิ่นที่อยู่ในเขตปกครองตนเองอื่นอย่าง <ร้านจากย่านการค้าเทพเต่าดำ> หรือ#n<ร้านเฮียกคิยาโค> ก็มาเปิดขายในงานนี้ด้วย ฉันว่าต้องมีนักเรียนที่มาสนามกีฬาเพียงเพราะอยากจะ#nชิมอาหารร้านเด็ดนี้เหมือนกันค่ะ ★"
10016020-86 = "[s] \"จะว่าไป ครูก็เห็นนักเรียนจากโรงเรียนอื่นเหมือนกัน...\""
10016020-87 = "แล้วก็มีแข่งขันวิ่งกินขนมปังด้วยนะ!"
10016020-88 = "แค่ลงแข่งวิ่งก็กินขนมปังได้ตามใจชอบด้วย แบบนั้นมันสุดยอดไปเลยเนอะว่ามั้ย?"
10016020-90 = "การแข่งขันวิ่งกินขนมปังไม่ใช่การแข่งกินแหลกนะ..."
10016020-91 = "จะว่าไป ฉันได้ยินมาว่างานมหกรรมแข่งขันกีฬาครั้งนี้มีการแข่งกินจุวังโกะโซบะให้ชนะเครื่องทำโซบะ#nอัตโนมัติด้วยนะ..."
10016020-92 = "ฮุฮุ เครื่องนั้นจะทำให้ฉันอิ่มเอมได้มากแค่ไหนน้า เริ่มตื่นเต้นแล้วสิคะ~♥  "
10016020-93 = "ทุกคนจิตใจไม่สงบกันตั้งแต่เช้าเลย... บ้าบอชะมัด"
10016020-94 = ""
10016020-96 = ""
10016020-97 = "นักเรียนกลุ่มนี้..."
10016020-98 = "อุ๊ย ท่านนี้คือรองหัวหน้าชมรมทวงความยุติธรรมสินะคะ"
10016020-99 = "(ปกติได้เจอนักเรียนเกเฮนน่าก็อึดอัดใจอยู่แล้ว แต่นี่ต้องมาเจอชมรมจอมสร้างปัญหาที่มีเกียรติภูมิ#nเสื่อมเสียอีก...)"
10016020-100 = "(เจอแบบนี้มัน... น่ารำคาญจริงๆ เลยนะคะ)"
10016020-101 = "ยินดีที่ได้พบค่ะ แต่ตอนนี้ฉันทำหน้าที่เป็นคณะกรรมการจัดงานของฮาโลเฟสติวัล ไม่ใช่รองหัวหน้า#nชมรมทวงความยุติธรรมค่ะ"
10016020-102 = "หวังว่าจะสนุกกับงานเทศกาล 'อย่างปลอดภัยไร้ปัญหา' กันนะคะ"
10016020-103 = "ฮุฮุ ขอบคุณสำหรับการต้อนรับค่ะ  "
10016020-105 = "ไม่เห็นจะเหมือนการต้อนรับเลย..."
10016020-107 = "อ้อ จริงสิ เมื่อกี้ฉันซื้อของพวกนี้มาจากแผงขายของด้วย..."
10016020-108 = ""
10016020-110 = ""
10016020-111 = "ลองชิมข้าวโพดย่างน้ำตาลฉ่ำๆ ชีสเยิ้มๆ หน่อยมั้ยคะ?"
10016020-112 = "...... (กลืนน้ำลาย)"
10016020-113 = "ตายจริง ไม่ชอบข้าวโพดหรอกเหรอคะ?"
10016020-114 = "ไม่ได้ไม่ชอบหรอกค่ะ... แต่ถ้าเป็นข้าวโพดย่างที่มีทั้งน้ำตาลและชีสเยิ้มๆ แบบนี้..."
10016020-115 = "ดูแล้วก็น่าจะหลายร้อยแคล... มันไม่หนักไปหน่อยสำหรับของว่างเหรอคะ?"
10016020-116 = "ฮุฮุ ปกติทานอาหารนับแคลด้วยเหรอคะ?"
10016020-117 = "ไม่ต้องกังวลหรอกค่ะ แคลอรีแค่นี้ แค่ออกไปวิ่งเดี๋ยวเดียวก็เผาผลาญหมดแล้วค่ะ"
10016020-118 = "อีกอย่าง ยิ่งต้องเคลื่อนไหวร่างกายในงานมหกรรมแข่งขันกีฬาแบบนี้ ยิ่งต้องกังวลว่าน้ำหนักจะลด#nมากกว่าสิคะ? "
10016020-119 = "ต้องกังวลว่าน้ำหนักจะลดงั้นเหรอคะ...?"
10016020-121 = "จะว่าไป ฮารุนะก็ค่อนข้างผอมเลยนะ พอเทียบกับอาหารที่กินในแต่ละวันๆ น่ะ"
10016020-122 = "หรือว่าเธอไดเอตเอาต่างหากเหรอ?"
10016020-123 = "ไม่หรอกค่ะ ฉันไม่ได้ไดเอตอะไรเลย แค่เป็นคนที่กินเท่าไรๆ ก็ไม่อ้วนน่ะค่ะ"
10016020-124 = "การได้กินของอร่อย ทำไมต้องรู้สึกผิดด้วยล่ะคะ อีกอย่าง ฉันว่าการไดเอตเป็นการกระทำที่โง่เขลาค่ะ"
10016020-126 = "....."
10016020-127 = "กะ... กินเท่าไร... ก็ไม่อ้วนเหรอคะ...? การกระทำที่โง่เขลา...?"
10016020-128 = "ไม่... ไม่เด็ดขาด..."
10016020-129 = "ฉันไม่ยกโทษให้เด็ดขาด พวกเกเฮนน่า!"
10016020-130 = "[s] \"ฮะ... ฮาสุมิ......?\""
10016020-131 = "อุตส่าห์ทำเป็นเมิน และปิดจมูกไม่ให้ได้กลิ่นของอร่อยๆ แถวนี้อยู่แท้ๆ..."
10016020-132 = "แต่มายั่วยุต่อหน้าต่อตากันอย่างหน้าไม่อายกันแบบนี้ ยกโทษให้ไม่ได้ค่ะ!"
10016020-133 = "ฉันทนอยู่นานเพราะเห็นแก่คุณครู แต่ฉันจะประกาศกร้าวอีกครั้งค่ะ"
10016020-134 = "ไม่ว่าจะต้องใช้วิธีไหนก็ตาม ฉันก็จะเอาชนะ[ruby=เกเฮนน่า]พวกคุณ[/ruby] และคว้ารางวัลชนะเลิศคะแนนรวมมาให้ได้ค่ะ!"
10016020-135 = ""
10016020-137 = ""
10016020-138 = "ตายจริง ฉันไปพูดอะไรกระทบกระเทือนจิตใจหรือเปล่าคะเนี่ย?"
10016020-139 = "[s] \"ครูว่าเมื่อกี้เป็นความผิดของฮารุนะนะ...\""
10016020-140 = "คะ? พวกฉันก็แค่แนะนำอาหารอร่อยๆ เท่านั้นเองนะคะ?"
10016020-141 = "ใช่ๆ แล้วมาอารมณ์เสียต่อหน้าข้าวโพดแสนอร่อยทำไมน่ะ... ไม่เห็นจะเข้าใจเลย"
10016020-143 = "ก็คงจะมีแต่อิซุมิจอมเซ่อคนเดียวแหละที่คิดว่าถ้าให้ของกินแล้วจะหายโกรธน่ะ"
10016020-144 = "เฮ้อ... ฉันไม่คิดที่จะลงแข่งกินจุเมนูใหม่แปลกๆ อะไรนั่นด้วยหรอก แล้วทำไมถึงได้ตามมาที่นี่ได้นะ?"
10016020-145 = "แถมอาหารส่วนใหญ่ที่ขายในร้านริมทางก็ลองกินมาหมดแล้วด้วย ฉันว่ามันไม่น่าจะมีอะไรอื่นที่อร่อย#nแล้วละ..."
10016020-146 = "[s] \"จุนโกะ\""
10016020-147 = "หืม?"
10016020-148 = "[s] \"วันนี้มาสนุกกับงานแข่งขันกีฬาแบบปกติๆ เถอะนะ\""
10016020-149 = "ถึงจะให้สนุกแบบปกติๆ ก็เถอะ..."
10016020-150 = ""
10016020-153 = "ประกาศ อีกสักครู่จะเริ่มการแข่งขันรายการแรกของ <ฮาโลเฟสติวัล> กันแล้วค่ะ"
10016020-154 = "นักเรียนจากแต่ละโรงเรียนที่ประสงค์จะเข้าแข่งขัน ขอให้มารวมตัวกันที่ห้องพักนักกีฬาด้วยค่ะ"
10016020-156 = "ว้าย! การแข่งขันจะเริ่มแล้ว!"
10016020-157 = "ถ้าขนมปังที่ใช้ในการแข่งวิ่งกินขนมปังหมดเพราะไปถึงช้าล่ะ จะทำยังไงดี?"
10016020-158 = "ยังพอมีเวลาเหลืออยู่ค่ะ"
10016020-159 = "งั้นเราแยกกันไปตามหาอาหารรสเลิศของแต่ละคนกันดีมั้ยคะ?"
10016020-160 = "งั้นฉันขอตัวก่อนนะคะ~ ♥"
10016020-161 = ""
10016020-163 = ""
10016020-165 = "...... ก็ได้ เดี๋ยวฉันมา"
10016020-166 = ""
10016020-168 = ""
10016020-170 = "(หลังจากไปส่งชมรมชิมอาหารแล้ว คุณครูก็กลับเข้ามาในสนามแข่งเพื่อชมการแข่งขัน)"
