[translation]
10011065-8 = "3;미모리;09;후후후. 네, 여러분! 합격입니다! 통과예요.\n#3;em;[반짝]\n#3;greeting\n#3;a"
10011065-9 = "#st;[0,0];instant;1;"
10011065-11 = "1;이즈나;02\n5;츠쿠요;02\n3;미치루;02\n#1;a\n#5;a\n#1;h\n#3;h\n#5;h\n#1;em;…\n#3;em;…\n#5;em;…\n#wait;2500"
10011065-12 = "1;이즈나;02\n3;미치루;02\n5;츠쿠요;03;무, <무념무상의 인법>! 서, 성공이에요!\n#5;em;[반짝]\n#1;h\n#3;h"
10011065-13 = "3;미치루;02\n5;츠쿠요;02\n1;이즈나;03;츠쿠요 공! 대단해요!\n#1;hophop\n#3;h\n#5;h"
10011065-14 = "1;이즈나;02\n5;츠쿠요;02\n3;미치루;07;……다, 다행이다아…….\n#3;em;[땀]\n#3;stiff\n#1;h\n#5;h"
10011065-16 = "3;이로하;01;뭐, 독심술이라고 해도 대충 남의 의중을 읽고 행동한 정도-라고 생각은 하지만요.\n#3;em;[반응]\n#3;a"
10011065-17 = "3;이로하;06;조금 전의 해프닝도 그런 이야기의 연장, 이었던 모양이고.\n#3;greeting"
10011065-18 = "[s] \"미모리는 착한 아이고, 모두를 잘 챙겨주는 타입이니까.\""
10011065-19 = "3;미모리;04;아이참…… 선생님도 그런 말씀을……\n#3;em;[///]\n#3;stiff"
10011065-20 = "3;미모리;99;엣-헴, 그야 이벤트의 일환으로 독심술사를 자처하고 있을 뿐이고.\n#3;greeting"
10011065-21 = "3;미모리;08;정말로 사람의 마음을 읽을 수 있을 리가 없잖아요?\n#3;em;[음표]"
10011065-22 = "3;미모리;09;자, 그럼 인법연구부 여러분. 다시 한번 통과 축하드립니다."
10011065-23 = "3;미치루;03;토, 통과한 거지?! 그럼 얼른-\n#3;hophop"
10011065-24 = "3;미치루;03\n5;미모리;02;아 참, 미치루 쨩.\n#5;em;[반응]\n#3;m1\n#5;al\n#3;h"
10011065-25 = "5;미모리;02\n3;미치루;06;……아, 응?\n#3;em;[?]\n#5;h"
10011065-26 = "5;미모리;99;주최자가 아닌 단순한 협력자라고는 해도, 어트랙션 담당자로서 참가자에게 이런 말을 해선 안 되는 일일지도 모르지만……."
10011065-27 = "5;미모리;01;그래도 말해둘게요."
10011065-28 = "5;미모리;03;미치루 쨩의 상냥함은 멋지다고 생각하지만……. 미치루 쨩이 생각하는 것보다 다들 강하다고 생각해요."
10011065-29 = "3;미치루;02;……어? 강, 해?\n#3;em;[?]"
10011065-30 = "5;미모리;08;후후, 네. 그렇답니다.\n#5;greeting"
10011065-31 = "5;미모리;08\n3;미치루;04;그게 무슨 뜻………\n#5;dr\n#3;m3\n#3;hophop\n#3;em;[땀]"
10011065-32 = "3;이로하;02;통과죠? 그럼 이러고 있을 때가 아니에요. 선생님. 그리고 다른 분들도.\n#3;em;[반응]"
10011065-33 = "3;이로하;05;바로 움직이도록 하죠."
10011065-34 = "3;미치루;02;아, 으, 응…….\n#3;greeting"
10011065-35 = "3;미모리;03;네, 모두 힘내세요~! 아 참 그리고!\n#3;em;[반응]"
10011065-36 = "#st;[0,0];instant;1;"
10011065-38 = "3;미모리;03\n#3;d\n#wait;1000"
10011065-39 = "3;미모리;04;그리고 선생님, 점심부터 그런 생각을 하시는 것은, 그게…….\n#3;em;[///]\n#3;greeting\n#3;a\n#3;closeup"
10011065-40 = "[s3] \"그러니까 오해입니다!\"\n[s4] \"그 이야기라면 나중에 제대로 대화를 나눠보자?!\""
