[translation]
10016070-1 = "Episode 7;Cooperation 2"
10016070-2 = "What's wrong with this stupid tank? It won't move!"
10016070-3 = "[s1] \"That's because it's not a tank...\"\n[s2] \"The Engineering Department removed its combat features during yesterday's repairs...\""
10016070-4 = "Well, that was pretty anti-climactic. We hardly need to call in the cavalry."
10016070-5 = "Well, that was pretty anti-climactic. We hardly need to call in the cavalry."
10016070-6 = "I'm relieved my worries were unfounded. Although, I am surprised that we could wrap this up so quickly."
10016070-7 = ""
10016070-9 = ""
10016070-10 = "Ugh!! Don't look down on us!"
10016070-11 = "Retreat for now! We'll garner more support for our three-day work week and then there'll be nothing you can do to stop our protest!"
10016070-12 = ""
10016070-14 = ""
10016070-16 = "Hey! Get back here!"
10016070-19 = "Hello and welcome back to the Kronos channel! We hope everyone enjoyed a delicious lunch at one of the many food stalls outside the stadium."
10016070-20 = "With morning matches complete, let's see where everyone lands in the rankings!"
10016070-21 = "Gehenna Academy took a surprising lead as soon as the tournament started."
10016070-22 = "Did they manage to keep their first place spot?"
10016070-23 = "Wow! Millennium Science School is now reigning at the top of the leaderboard!"
10016070-24 = "Millennium Science School?! A school better known for their math formulas than their penalty kicks, I don't think anyone was expecting them to perform well!"
10016070-25 = "I guess home field advantage is a real thing."
10016070-26 = "But their lead is hardly a comfortable one, so they better keep their eyes peeled for Gehenna and Trinity right behind them!"
10016070-27 = "With competition this fierce, there's no way to tell who'll emerge the victor after the afternoon games."
10016070-28 = "And the next game we get to look forward to is...the obstacle race!"
10016070-29 = "This race is all about being the fastest athlete there while overcoming the various obstacles laid out throughout the track."
10016070-30 = "You're absolutely right! There's so many difficult obstacles designed to slow down and disrupt the runners!"
10016070-31 = "There's everything from ninja caltrops to bottle caps that look like 500 yen coins, and even stuffed cats in boxes with \"Please adopt me\" written on them..."
10016070-32 = "I think the cats in boxes would distract me from the race!"
10016070-33 = "To make things more interesting, they've added a special rule for this year's race."
10016070-34 = "Instead of a baton, the runners will have a large grenade with an electronic detonator inside."
10016070-35 = "Does that mean runners will be passing off a grenade to each other instead of a traditional baton? That sounds dangerous!"
10016070-36 = "That's what makes it exciting! And as long as it's handed over to the next runner in time, it won't detonate."
10016070-37 = "But take too long, and you'll be disqualified in a shocking explosion!"
10016070-38 = "They implemented this rule to encourage teamwork, rather than each school relying on their ace."
10016070-40 = "Now, which academy will be blessed by the Goddess of Luck this time?"
10016070-42 = "The contestants representing Abydos in the obstacle race are..."
10016070-43 = "Serika, Hoshino, and Shiroko."
10016070-44 = ""
10016070-46 = ""
10016070-47 = "Heh heh. I'm so nervous~"
10016070-48 = "Just leave this to me."
10016070-49 = "Grenades, abandoned cats... Why is it so complicated?!"
10016070-50 = "We have to win this game if we want the prize for first place!"
10016070-51 = ""
10016070-53 = ""
10016070-54 = "Haha... I don't want you to be disappointed if we can't. A small school like ours doesn't stand much of a chance..."
10016070-55 = "But regardless, we'll do our best!"
10016070-56 = "If we put on a good show in the games, maybe more students will be interested in transferring to Abydos!"
10016070-57 = "Hahaha! Allow me to educate you, my adorable underclassman!"
10016070-58 = "You're not going to gain the attention you want by doing well in the field day. Where you're really going to gain traction is by showing off in the grandstands!"
10016070-59 = "...The grandstands?"
10016070-60 = "Yup, yup! The cheer squad is in the grandstands!"
10016070-61 = "Look! I talked to Hoshino and she inspired me to prepare some cheer poses!"
10016070-62 = "Let's go! You can do it!"
10016070-63 = "FIGHT!"
10016070-64 = "Swimsuit Cheer Squad! ☆"
10016070-65 = "What the heck is a Swimsuit Cheer Squad? That sounds stupid!"
10016070-66 = ""
10016070-68 = ""
10016070-69 = "...I prepared something too, actually."
10016070-70 = "Oh no..."
10016070-71 = ""
10016070-73 = ""
10016070-74 = "See? A sixty-millimeter anti-tank rocket."
10016070-76 = "F-For what?!"
10016070-77 = "Warning shots, obviously."
10016070-78 = "Cheering is important to raise your own team's morale, but they say the best defense is attack. You also need to crush your opponent's spirit."
10016070-79 = "As soon as the other teams see me enter with this intimidating rocket, they'll be engulfed with hopelessness and despair."
10016070-80 = "I like it, Shiroko! Having a strong mentality is half the battle."
10016070-81 = "Heehee! How fun! ☆"
10016070-82 = ""
10016070-84 = "But..."
10016070-85 = "There's no way they'll permit that!"
10016070-87 = "Heehee... The large grenades that will be used in the obstacle race might look like old models with a friction igniter, but it's actually an advanced electronic igniter that works with a sensor on the handle!"
10016070-88 = "But because we made them in a hurry yesterday, I'm not quite sure if they'll work properly..."
10016070-89 = "Then it's a craftman's duty to test her invention by participating in the game herself!"
10016070-90 = "Utaha, I'll test the grenade igniter during the game. Can you please help cheer us on?"
10016070-91 = ""
10016070-93 = ""
10016070-94 = "Of course! Leave the cheering to us."
10016070-95 = "Ugh... I wish I could've just entered the race..."
10016070-96 = "Are you still feeling apprehensive, Hibiki?"
10016070-97 = "Remember, you're a member of the cheer squad now! It is your duty to bring the energy and attitude required to cheer on our team!"
10016070-98 = "Come on, now! Put on a happy face! Happy! Faces!"
10016070-99 = "Let's go! Fight! Let's win! Millennium!"
10016070-100 = "M-Millennium...!"
10016070-102 = "*yawn* I'm so tired..."
10016070-103 = "I've been getting mixed up in all these weird incidents since last night..."
10016070-104 = "If I r-relax at all, I might p-pass out..."
10016070-105 = "Look alive, RABBIT squad! The Halo Festival is far from over!"
10016070-106 = "And a diabolical terrorist could be planning their next move as we speak."
10016070-107 = ""
10016070-109 = ""
10016070-110 = "Um... The radar is showing a large object approaching the track..."
10016070-111 = "What is that...?"
10016070-113 = "Ugh... I don't want to be part of this annoying race..."
10016070-114 = "But Ako said if I make it into the top three, she'll give me a General Meal Ticket so I can eat anything I want at the Kivotos Halo Festival..."
10016070-115 = ""
10016070-117 = "So I guess... I can try a little."
10016070-118 = ""
10016070-120 = ""
10016070-121 = ""
10016070-123 = ""
10016070-125 = "And with the bang of the flare gun, the participants are off!"
10016070-126 = ""
10016070-129 = "Look at them go! What speed!"
10016070-130 = ""
10016070-133 = "It looks like the caltrops track didn't cause too much trouble for any of these seasoned athletes. Now they just need to hand the baton, I mean, the grenade to the second runner!"
10016070-134 = "The next obstacle is..."
10016070-135 = "*rumble*"
10016070-136 = "Huh? What's that sound?"
10016070-137 = ""
10016070-139 = ""
10016070-141 = "Those stubborn bastards..."
10016070-142 = "S-Stop following me!"
10016070-143 = ""
10016070-145 = ""
10016070-148 = "Is that a tank?! Why is there a tank barreling down the stadium?"
10016070-149 = "I have the answer to that!"
10016070-150 = "That ball-shaped robot is the cheer bot we made in preparation for the field day."
10016070-151 = "It has an ergonomic round shape and continuous tracks so that it can quickly move across any terrain!"
10016070-152 = "We couldn't use it in the end due to a...minor accident."
10016070-154 = "So the real question is, what is it doing here?"
10016070-155 = "A cheer bot? There's a massive machine gun attached to it!"
10016070-156 = "That's a combat system we installed to instantly subdue any terrorists in the event of an attack on the festival."
10016070-157 = "But that feature unfortunately had to be disabled in the end. It won't work unless it detects a direct threat, or perhaps a powerful shock of some sort."
10016070-158 = "Bang! Bang!"
10016070-159 = "KA-BOOM!"
10016070-160 = "Shiroko! I told you not to use it!"
10016070-161 = "Who in the world fires an anti-tank rocket at an innocent cheer bot?!"
10016070-162 = "...Is that wrong?"
10016070-163 = "Ugh! Of course it is!"
10016070-164 = "That looked really expensive... I hope it's okay."
10016070-166 = "Explosion from a warhead with a penetrative force of four hundred millimeters or higher detected. Activating combat system."
10016070-167 = "Identifying delinquent students within a kilometer radius..."
10016070-168 = "Three students carrying illegal JHP bullets, seven students wearing unauthorized homemade gym clothes, five students eating food while walking..."
10016070-170 = "The criteria for a \"delinquent\" is pretty strict, huh?"
10016070-171 = "We used Seminar's decision-making algorithm for the AI's machine learning."
10016070-172 = "Its parameters might have been affected by a certain cold-hearted treasurer..."
10016070-174 = "Investigation complete. All students within a kilometer radius will be marked as \"delinquent students.\""
10016070-175 = "Power up! Eliminate!"
10016070-176 = "KA-BOOM!"
10016070-178 = "Wh-What's going on?! Why is there a tank attacking us?"
10016070-180 = "Is it going crazy because of the explosion?"
10016070-181 = "Ugh! Shiroko, this is all your fault!"
10016070-183 = "I-I don't have any control over it! Help!"
10016070-184 = "Delinquent students who disrupt the field day will be eliminated."
10016070-186 = "I knew it! The Millennium terrorists finally made their entrance!"
10016070-187 = "We'll get in close and use a grenade. That oughta do the trick."
10016070-188 = ""
10016070-190 = ""
10016070-191 = "...Huh? The grenade just glanced off it like it was a feather..."
10016070-193 = "BOOM!"
10016070-194 = "Saki!"
10016070-196 = "A-Are you getting all this?"
10016070-197 = "A tank suddenly entered the track during the obstacle race and started attacking the students!"
10016070-198 = "How did such a terrifying weapon find its way into the peaceful Halo Festival?!"
10016070-199 = "This is a scoop! Breaking news!"
10016070-201 = "What's that tank, Yuuka?"
10016070-202 = "The operation schedule didn't mention using a tank during the festival!"
10016070-203 = "I-I don't know anything about it either!"
10016070-204 = "I didn't think it was an actual tank! When the protestors took it, I thought it was just a replica or something."
10016070-205 = "I find it rather suspicious how it talks exactly like you."
10016070-206 = "Stuff like \"Eliminate them!\" and \"Delinquents!\""
10016070-207 = "I don't talk like that!"
10016070-208 = "More importantly, what is that tank, Sensei?! What happened while I was asleep yesterday?"
10016070-209 = "[s3] \"Um... So the thing is...\"\n[s4] \"It's kind of a long story...\""
10016070-212 = "You can explain once we get a handle on the situation."
10016070-213 = "Mari, can you please help evacuate the spectators?"
10016070-214 = "Y-Yes!"
10016070-215 = "The rest of you, we're going to subdue that tank!"
10016070-217 = "That's what I was going to say! I don't need your orders!"
10016070-218 = "They're going to write a ten page report after this!"
