[translation]
1001206-1 = "A Date with the Trainer"
1001206-2 = "Shopping Mall Near Millennium"
1001206-3 = "..."
1001206-4 = "Oh, there you are, Trainer."
1001206-5 = "I've been waiting for you."
1001206-6 = "Huh? Did I come to buy more things for training?"
1001206-7 = "N-No! Not this time."
1001206-8 = "I just couldn't think of a better place to meet."
1001206-9 = "Maybe that's because working out is all we talk about."
1001206-10 = "That's why today, I wanted to talk about something else with you..."
1001206-11 = "..."
1001206-12 = ""
1001206-13 = "O-Oh! I'm sorry, Trainer!"
1001206-14 = "You must have been busy today! I feel so selfish for wasting your time like this!"
1001206-15 = "[s1] \"I don't mind. I could use a change of pace?\"\n[s2] \"Oh, so this is supposed to be a date...\""
1001206-16 = "A-Are you sure?"
1001206-17 = "Thanks for putting my mind at ease."
1001206-18 = "...?!"
1001206-19 = "Huh? A d-date? I didn't mean..."
1001206-20 = "I mean, I wouldn't mind that, but..."
1001206-21 = "Hnnnngh..."
1001206-22 = "[s] \"So, where should we go first?\""
1001206-23 = "As it so happens, the diets we planned out let us have sugar and fat today."
1001206-24 = "I think this what people refer to as a cheat day."
1001206-25 = "So if it's all right with you, let's go somewhere to take advantage of that."
1001206-26 = "[s] \"I'm down for something sweet!\""
1001206-27 = "You got it, Trainer!"
1001206-30 = "Wow. It's been so long since I've been to a place like this."
1001206-31 = "I often hear about my classmates' favorite cafes and run by people going in and out of them."
1001206-32 = "I always thought there wouldn't be anything for someone like me..."
1001206-33 = "...but now that I'm here, I can appreciate how cute it is on the inside."
1001206-34 = "Good choice, Trainer."
1001206-35 = "May I take your order?"
1001206-36 = "Oh, please give me a minute."
1001206-37 = ""
1001206-38 = "Um..."
1001206-39 = "Oh, this cake."
1001206-40 = "It's so cute."
1001206-41 = "[s] \"You wanna order that one?\""
1001206-42 = "Yes, Trainer."
1001206-43 = "Oh, but before we order..."
1001206-44 = "Excuse me? I have a question."
1001206-45 = "Sure. What is it?"
1001206-46 = "It's about this cake decorated with the cute mascot."
1001206-47 = "Where can I find the nutritional information for this dessert?"
1001206-48 = "I-I'm sorry?"
1001206-49 = "The total calories, the amount of sugar and fat..."
1001206-50 = "Oh, and I'm sure it won't be much, but I'd also like to know how much protein it contains."
1001206-51 = "Oh, I-I don't know..."
1001206-52 = "[s] \"Hey, Sumire...\""
1001206-53 = "Yes, Trainer?"
1001206-54 = ""
1001206-55 = "Oh..."
1001206-56 = "Oh, I'm doing it again... I'm so sorry."
1001206-57 = "Let's start over and pretend that didn't happen. Sorry."
1001206-59 = "(Afterward, Sumire and I got our desserts and sat down.)"
1001206-60 = "*sigh* I'm still sorry about earlier, Trainer."
1001206-61 = "I know today's a cheat day, but I can't ignore how important my diet is to my training regimen."
1001206-62 = "Having a healthy diet is a key to staying healthy and building muscle mass."
1001206-63 = "That reminds me. Have you been taking the protein supplements I gave you?"
1001206-64 = "There's a limit to the amount of protein you can get from ordinary food, naturally."
1001206-65 = "That's why supplements are made. They make it easy to increase your intake of proteins with high BV."
1001206-66 = "BV? That's biological value. It refers to ingesting nutrients responsible for the maintenance and growth of the body..."
1001206-67 = "[s3] \"Um...Sumire.\"\n[s4] \"Your dessert is looking lonely.\""
1001206-68 = "...Oh."
1001206-69 = "...Oh."
1001206-70 = "Not again!"
1001206-71 = "I'm sorry, Trainer."
1001206-72 = "I got carried away again."
1001206-73 = "That happens whenever I start talking about working out..."
1001206-74 = "I have no excuses anymore, Trainer."
1001206-75 = "[s] \"It's okay. Let's just enjoy the food.\""
1001206-76 = "...If you say so."
1001206-78 = "(After that, Sumire and I ate our delicious desserts.)"
1001206-80 = "[ns] \"Are you ready to head back?\""
1001206-81 = "...Sure."
1001206-82 = "Huh? I look like I'm feeling down?"
1001206-83 = "I-It's just..."
1001206-84 = "I feel guilty for being so hyper focused on training."
1001206-85 = "Today was supposed to be our day off where we could talk about normal stuff."
1001206-86 = "[s5] \"Is that not what we did?\"\n[s6] \"I thought we had a good time together.\""
1001206-87 = "..."
1001206-88 = "..."
1001206-89 = "Heehee. Okay."
1001206-90 = "Excuse me, ma'am! Wait a minute."
1001206-91 = "Huh?"
1001206-92 = "The cake you bought was part of our special promotion. We're giving away these dolls on a first come, first served basis."
1001206-93 = "I didn't think we had any in stock, but I checked and found one left. Here it is!"
1001206-94 = ""
1001206-95 = "S-So cute..."
1001206-96 = "Have a great day!"
1001206-97 = "Wow, Trainer."
1001206-98 = "Isn't it adorable?"
1001206-99 = "[s] \"I think so too, Sumire.\""
1001206-100 = "Heehee. Yeah."
1001206-101 = "One way or another, the days I spend with you always seem to end on a high note."
1001206-102 = ""
1001206-103 = "Um, Trainer."
1001206-104 = "I hope we get to have more days like this together."
1001206-105 = "Thank you for making yourself available!"
1001206-106 = "Trainer."
