[translation]
10010145-1 = "Episode 14;Reap What You Sow Part 4"
10010145-2 = ""
10010145-7 = "..."
10010145-8 = ""
10010145-11 = "W-Welcome back, Sensei. I've been expecting you."
10010145-12 = ""
10010145-16 = "I can tell from the look on your face that things went well.#nI'm glad to hear it."
10010145-17 = "We can finally breathe a sigh of relief thanks to you."
10010145-18 = "Hmm? Did I not hear about what happened on social media?#nActually, I prefer to get my news from the newspaper."
10010145-19 = "Though they chose not to cover that event from the beginning.#nThat isn't surprising, given the subject matter."
10010145-20 = "I suppose that's for the best, but there is still something bothering me."
10010145-21 = "Hmm? Isn't it obvious what it would be?"
10010145-22 = "I used up so much of my precious time on this incident..."
10010145-23 = "And in the end, I helplessly worried over someone I had only just met.#nDoing so took a real toll."
10010145-24 = "I'm relieved things were resolved in the end, but I can't help but wonder what would have happened if things went awry..."
10010145-25 = "Ugh. I hate dwelling on the \"what ifs\". This is why I don't like involving myself with outsiders."
10010145-26 = "I always have to hold their hands to show them how things should be done,#nwhile they always find ways to screw things up in the end.#nSo much useless worry..."
10010145-27 = "Doesn't anyone ever consider how I feel? It's always \"Me, me, me...\"#nYet in the end, I'm the one losing sleep over their problems."
10010145-28 = "*sigh* What am I even saying? I'm sorry you had to see me like this, Sensei."
10010145-29 = "D-Don't mind me. I was only rambling."
10010145-30 = "I guess what I'm trying to say is..."
10010145-31 = "...this is why I keep to myself."
10010145-32 = "[s1] \"I think you're a kind person, Ui.\"\n[s2] \"Your sense of responsibility is unmatched.\""
10010145-33 = "G-Gah. You don't have to say things like that..."
10010145-34 = "G-Gah. You don't have to say things like that..."
10010145-35 = "Anyway, that's all I have to say about the matter."
10010145-36 = ""
10010145-38 = ""
10010145-39 = "By the way...d-did you bring what I asked for?"
10010145-40 = "[s3] \"Of course.\"\n[s4] \"I've got it right here.\""
10010145-41 = "Heh. Heh heh..."
10010145-42 = "Heh. Heh heh..."
10010145-43 = "Thank you. It looks delicious."
10010145-44 = "Huh? Why the lemon smoothie this time and not a cake?"
10010145-45 = "Hmm."
10010145-46 = "Well, to tell you the truth..."
10010145-47 = "...I don't actually like sweets very much. I only have cake on occasion."
10010145-48 = "To make matters worse, they leave behind crumbs, which get all over my desk and books. Nothing is better when reading than a refreshing lemon smoothie—with a lid on it, I might add."
10010145-49 = "E-Even when they're brain-freezingly cold like this one is."
10010145-50 = ""
10010145-52 = ""
10010145-53 = "..."
10010145-54 = "I-I'm sorry that I asked you to retrieve that cake before. It was uncalled for.#nI don't think I ever did give you a proper apology."
10010145-55 = "What?"
10010145-56 = "In that case, you'll bring me lemon smoothies from now on?"
10010145-57 = "What do you mean \"from now on\"? I wouldn't necessarily mind you visiting, but..."
10010145-58 = "*sigh*"
10010145-59 = "There's something about you, Sensei. "
10010145-60 = "I should be more honest with you if you insist on continuing to see me."
10010145-61 = "In that case, there's something important you need to know..."
10010145-63 = "Next time, I'll take an iced Americano."
10010145-64 = "That's my usual coffee order."
10010145-65 = ""
10010145-72 = "Ugh. It's so sour that I can hardly drink it."
10010145-73 = "Maybe I should have asked for an iced Americano in the first place.#nI don't know why I couldn't work up the nerve before..."
10010145-74 = ""
10010145-76 = ""
10010145-77 = "Hmm..."
10010145-78 = "Sensei left a while ago. They should be back at Schale by now."
10010145-79 = "Now's the perfect time."
10010145-80 = "I was so busy working on it that I still haven't had a chance to read it."
10010145-81 = ""
10010145-83 = ""
10010145-85 = "Heh. A perfect copy of the scripture. It was worth going through the extra trouble to make it in secret."
10010145-86 = ""
10010145-90 = "..."
10010145-91 = "The Sisterhood is just as veiled in mystery as ever."
10010145-93 = "Now, then. How would you like to reveal some of their secrets to me?"
10010145-94 = "The Clumsy Sister and the Magician of the Old Library"
