[translation]
10014040-1 = "Episode 4; After-School Sweets Gang?"
10014040-2 = "...The next day."
10014040-3 = "Oh, Sensei... You're so punctual."
10014040-4 = "So, anything new?"
10014040-5 = "Have you talked to Reisa since then or anything?"
10014040-6 = "Sorry, am I being pushy? I've just been impatient for news."
10014040-7 = "What?"
10014040-8 = "You want to talk about it with me first?"
10014040-9 = "I mean, I can do it, but..."
10014040-10 = "Why don't you make Reisa talk? Why me?"
10014040-11 = ""
10014040-13 = ""
10014040-14 = "Ugh, ignore me. It's coming from an adult, so I'll trust you."
10014040-15 = "Let's find somewhere to sit and talk."
10014040-16 = "Hey, cutie!"
10014040-17 = "You look bored. Are you free? Do you wanna play with us?"
10014040-18 = "......?!"
10014040-19 = "[ns] \"That voice sounds familiar...\""
10014040-24 = "......?!"
10014040-25 = "...???"
10014040-26 = "Ha! Ha! Ha! You're freaked, like totally freaked. Intimidation is my middle name."
10014040-27 = "O-Of course she's scared! We're bad, evil people!"
10014040-28 = "Is that right? You really think you're being intimidating?"
10014040-30 = ""
10014040-32 = ""
10014040-33 = "...What is this?"
10014040-34 = "[s3] \"...???\"\n[s4] \"(They're dressed like thugs?!)\""
10014040-35 = "What in the world are you guys doing here? And why are you dressed like that?!"
10014040-36 = "What in the world are you guys doing here? And why are you dressed like that?!"
10014040-37 = "K-Kazusa! No matter what happens, we'll support you however we can! Even if it's like this!"
10014040-38 = "I appreciate it and all, but I don't understand what this achieves."
10014040-39 = "Why are you guys dressed like a bunch of gang members? And why is Natsu talking even weirder than usual?!"
10014040-40 = "Ha! Ha! Ha! We appreciate your concern, but don't push away your fellow conspirators. We are here!"
10014040-41 = "Our future is heading towards a world previously unknown to us..."
10014040-42 = "Your future... An unknown road??"
10014040-43 = ""
10014040-45 = ""
10014040-46 = "Wait a second. Something's wrong here."
10014040-47 = "[s5] \"Yes. Something has gone very wrong.\" \n[s6] \"Epic cosplay fail...\""
10014040-48 = "Today marks the beginning of a new chapter! Our club name will officially be changed to the After-School Sweets Gang."
10014040-49 = "Today marks the beginning of a new chapter! Our club name will officially be changed to the After-School Sweets Gang."
10014040-50 = "Yes! This way, Kazusa, you will feel comfortable and at-home with us."
10014040-52 = "G-Gang?! What? Why?"
10014040-53 = "Someone, please tell me what is going on..."
10014040-54 = "I knew it! She doesn't get it, guys! She's missing the point!"
10014040-55 = "We need to explain why we're doing this."
10014040-56 = "CAUGHT RED-HANDED!"
10014040-58 = ""
10014040-59 = "[ns] \"...Oh. Oh, no.\""
10014040-61 = "...?"
10014040-62 = "That voice..."
10014040-63 = "Why am I feeling deja vu right now?"
10014040-65 = "Yes! I knew it all along!"
10014040-66 = "I let myself believe for a split moment you had turned from your evil ways! But it was always impossible!  "
10014040-67 = "The beast within you will never be tempered!"
10014040-68 = "Now you've formed the After-School Sweets Gang?! How terrifying!"
10014040-69 = "They're going to devour all of mankind like their favorite dessert! That's definitely what it means!"
10014040-70 = "Even Sensei's been kidnapped. They're going to blackmail the schools with them!"
10014040-71 = "All this time, you've been plotting behind the scenes!"
10014040-72 = "And now you have finally established a new organization to bring about your resurrection, Kyoyama Kazusa!"
10014040-73 = "Or should I say..."
10014040-74 = "Cath Palug!!!"
10014040-75 = ""
10014040-77 = ""
10014040-78 = "Cath...what? What does she mean?"
10014040-79 = "A resurrection? New organization...? Are you talking about the thugs? Are they thugs?!"
10014040-80 = "...Cath Pal...what?"
10014040-81 = "Kidnapped...?"
10014040-82 = ""
10014040-84 = ""
10014040-85 = "Kazusa kidnapped Sensei?!"
10014040-86 = "K-Kazusa...? Is that true?!"
10014040-87 = "Are you guys freaking serious?!"
10014040-88 = "[s9] \"Are you serious? You kidnapped me, Kazusa?!\"\n[s10] \"Rumors sure are scary.\""
10014040-89 = "This isn't funny, Sensei!"
10014040-90 = "Don't act all nonchalant about it!"
10014040-91 = "Stop joking around and explain to everyone before this gets out of hand!"
10014040-92 = "Did you just threaten Sensei?!"
10014040-94 = "She even forces adults to do her will! Kyoyama Kazusa, you're ruthless!"
10014040-95 = "...Damn it. It's too late."
10014040-96 = "Hey! What're you saying about Kazusa?!"
10014040-97 = "Kazusa, just make her stop! She's your friend, isn't she?"
10014040-98 = "Her?! My friend?! Are you insane?"
10014040-99 = ""
10014040-102 = ""
10014040-103 = "I'll never forgive you! I will protect this land and its students from your darkness!"
10014040-104 = "Get ready, Kyoyama Kazusa and the After-School Sweets Gang!"
10014040-105 = "I'll finally prevail over you and uphold justice!"
10014040-106 = "I challenge you!"
10014040-107 = "Are you...kidding...me...?"
10014040-108 = ""
10014040-110 = ""
10014040-111 = ""
10014040-112 = "Heehee. We accept."
10014040-113 = "Yes, we do! I may not understand the situation, but I don't need to. You may not speak to Kazusa that way!"
10014040-114 = "All I need to know is that you are hurting my friend, and we won't let you get away with it."
10014040-116 = "Huh?!"
10014040-117 = "Challenge accepted! I will smite you with my justice!"
10014040-118 = "The After-School Sweets Gang will show you the power of friendship and romance!"
10014040-119 = "Go! Attack!"
10014040-120 = "L-Let's go!"
10014040-121 = "Eeeeeek!"
10014040-122 = ""
10014040-128 = ""
10014040-129 = ""
10014040-130 = ""
10014040-131 = ""
10014040-132 = ""
10014040-133 = ""
10014040-134 = ""
10014040-135 = ""
10014040-136 = ""
10014040-137 = "Sensei... What do we do...?"
10014040-138 = "[s13] \"Let's go! After-School Sweets Gang!\"\n[s14] \"Devour everything! Like it's your favorite dessert!\""
10014040-139 = "............"
10014040-140 = "............"
10014040-141 = "This..."
10014040-143 = "This must be punishment for my sins."
