[translation]
10013080-1 = "#title;제8화;헬멧단! 최후의 결전!"
10013080-3 = "2;헬멧단 A;00\n4;헬멧단 B;00\n#2;black\n#4;black"
10013080-5 = "1;미모리 수영복ND;05\n5;이즈나 수영복ND;06\n4;시즈코 수영복ND;05\n2;우미카;05\n#1;a\n#5;a\n#4;a\n#2;a\n#1;h\n#5;h\n#4;h\n#wait;1200"
10013080-6 = "1;미모리 수영복ND;05\n4;시즈코 수영복ND;05\n2;우미카;05;바로 여기예요!\n#2;em;[반응]"
10013080-7 = "2;우미카;05\n5;이즈나 수영복ND;06\n4;시즈코 수영복ND;05;마침내 도착했네! 이곳 <로스트 파라다이스 리조트> 군도에서도 가장 커다란 세력을 자랑하는 헬멧단의 리조트에……!\n#4;em;[!]"
10013080-8 = "2;우미카;05\n1;미모리 수영복ND;02;그런데 시즈코 쨩…….\n#1;stiff"
10013080-9 = "4;시즈코 수영복ND;05\n5;이즈나 수영복ND;10;뭔가 이제까지랑은 분위기가 다른 것 같아요……!\n#5;em;[속상함]"
10013080-13 = "[ns] \"어째, 텅텅 비어 있지 않아……?\""
10013080-14 = "3;치세 수영복ND;01\n#3;em;…\n#wait;2500\n#3;a"
10013080-15 = "3;치세 수영복ND;02;아…….\n#3;em;[반응]"
10013080-16 = "[s] \"치세?\""
10013080-17 = "3;치세 수영복ND;03;반짝반짝 무당벌레 씨-\n#3;em;[반짝]\n#3;greeting"
10013080-18 = "3;이즈나 수영복ND;02;네? 치세 공, 무당벌레라는 건…….\n#3;em;[?]"
10013080-19 = "#st;[0,0];instant;1;"
10013080-23 = "2;헬멧단 A;00\n4;헬멧단 B;00\n#2;ar\n#4;ar\n#2;h\n#wait;1000"
10013080-24 = "2;헬멧단 A;00\n4;헬멧단 B;00\n3;라브;08;……누가 빨강과 검정색이 멋지게 조화를 이룬 무당벌레라는 거냐아앗!\n#3;em;[빠직]\n#3;shake\n#3;a\n#2;m1\n#4;m5"
10013080-25 = "[s] \"의미를 바로 알아듣는 거야?! 굉장하잖아!\""
10013080-27 = "3;시즈코 수영복ND;05;당신이 말로만 듣던 헬멧단의 간부?\n#3;em;[반응]\n#3;a"
10013080-28 = "1;미모리 수영복ND;05;여러분께서 기다렸다는 듯이 저희들을 포위하신다는 건…….\n#1;a"
10013080-29 = "5;이즈나 수영복ND;05;처, 처음부터 전부 함정이었던 건가요?!\n#5;em;[!]\n#5;hophop\n#5;a"
10013080-31 = "3;라브;09;흥! 맞아! 이곳은 처음부터 네 녀석들의 무덤으로 점 찍은 장소다! 잘도 멍청하게 이곳까지 직접 행차하셨구만!\n#3;em;[!]\n#3;jump"
10013080-32 = "[s] \"하지만 어떻게 우리가 올 줄 알고…….\""
10013080-34 = "#na;???;고객에 대한 애프터 서비스는 확실히 책임진다."
10013080-35 = "#na;???;그것이 우리 카이저 코퍼레이션의 사훈이기 때문이지."
10013080-36 = "#st;[0,0];instant;1;"
10013080-40 = "3;카이저 이사(?);00\n#3;black"
10013080-41 = "[ns] \"혹시 그럴지도 모른다고 생각은 했었지만, 너는…….\""
10013080-42 = "3;카이저 이사(?);00;오랜만이군. 샬레의 선생.\n#3;a"
10013080-43 = "[s1] \"카이저 이사……!\"\n[s2] \"아니, 어쩐지 휴양을 즐길 생각으로 한가득이지 않아?!\""
10013080-46 = "3;시즈코 수영복ND;05;앗……! 당신은! 문어 은행에서 만났던 직원!\n#3;em;[!]\n#3;hophop"
10013080-47 = "3;우미카;10;여기서 또 뵙게 되네요!\n#3;em;[?!]"
10013080-48 = "[s] \"심지어 계약을 했다는 게 댁이었어?!\""
10013080-49 = "3;카이저 이사(?);00;그래, 이곳 <로스트 파라다이스 리조트>에 좋은 상품이 있다며 그쪽의 꼬맹이들에게 거래를 제안한 건 나였지.\n#3;em;[반응]"
10013080-50 = "3;카이저 이사(?);00;지난번 샬레의 선생. 네놈과 아비도스들과 엮이는 바람에 그대로 쪽박을 차고, 이사의 자리에서도 물러날 수밖에 없던 탓에"
10013080-51 = "3;카이저 영업사원 이사;00;지금은 <문어 은행>의 현장 영업직을 맡고 있단 말이다!\n#3;closeup\n#fontsize;80"
10013080-52 = "[s] \"과연, 그런 비하인드의 이야기……가 아니라!\""
10013080-53 = "3;카이저 영업사원 이사;00;하지만……. 지금 여기서 뭘 하는 거지?"
10013080-54 = "#st;[0,0];instant;1;"
10013080-56 = "3;시즈코 수영복ND;05\n#3;em;[?]\n#wait;1200"
10013080-58 = "3;카이저 영업사원 이사;00;지금쯤이면 열심히 리조트를 운영하고 있어야 하는 것 아닌가?"
10013080-59 = "3;카이저 영업사원 이사;00\n2;시즈코 수영복ND;05;뭘 하고 있느냐니, 그야 당신이 제멋대로 뿌려 댄 불법 계약서를 회수하러 온 거라고!\n#2;ar\n#2;hophop\n#2;em;[빠직]\n#3;m5"
10013080-60 = "2;시즈코 수영복ND;05\n1;우미카;05;맞아요! 저희에게 사용권을 판매했으면서, 설마 계약서의 허점을 만들어 이런 짓을 꾸미다니!\n#1;em;[!]\n#1;ar\n#2;h"
10013080-61 = "2;시즈코 수영복ND;05\n1;우미카;05\n3;카이저 영업사원 이사;00;무슨 소리지? 너희가 우리 은행을 방문했을 때, 나는 괜찮은 상품이 있다며 제안을 했을 뿐."
10013080-62 = "2;시즈코 수영복ND;05\n1;우미카;05\n3;카이저 영업사원 이사;00;나는 그 어떤 강요도, 강압도 하지 않았다. 그저 돈을 벌고자 하는 마음에 그 상품을 구매한 건 네놈들 쪽이지 않나?\n#3;em;[반응]"
10013080-63 = "1;우미카;05\n3;카이저 영업사원 이사;00\n2;시즈코 수영복ND;09;그건……!\n#2;stiff"
10013080-64 = "1;우미카;05\n2;시즈코 수영복ND;09\n3;카이저 영업사원 이사;00;허나 지금 이런 행위는 곤란하군. 자기 멋대로 다른 리조트들을 찾아가 사용권을 회수한다니.\n#3;em;[...]\n#3;m4\n#2;m1\n#1;dl"
10013080-65 = "2;시즈코 수영복ND;09\n3;카이저 영업사원 이사;00;그런 월권행위를 그냥 넘길 수는 없지. 그래서 직접 애프터케어 서비스를 위해 여기까지 나온 거다."
10013080-66 = "2;시즈코 수영복ND;09\n3;카이저 영업사원 이사;00;보디가드까지 대동하고 말이지.\n#3;em;[!]\n#3;m3\n#2;dl"
10013080-68 = "3;라브;09;헹!\n#3;em;[반응]"
10013080-69 = "3;미모리 수영복ND;05;……이건, 그냥 말장난이로군요. 시즈코 쨩들을 먼저 속인 것은 당신이면서…….\n#3;stiff"
10013080-70 = "3;카이저 영업사원 이사;00"
10013080-71 = "[ns] \"처음부터 백야당을 노리고 벌인 일이지?\""
10013080-72 = "3;카이저 영업사원 이사;00;마츠리운영관리부는 좋은 물건이지. 백귀야행 학원에서 축제를 열 수 있는 권한. 그걸 놀리고 있어서야 쓰나.\n#3;em;[반응]"
10013080-73 = "#st;[0,0];instant;1;"
10013080-76 = "#na;카이저 영업사원 이사;이번 일을 통해 백야당의 명예를 실추시킨다."
10013080-77 = "#st;[0,0];instant;1;"
10013080-81 = "1;수영복 불량배 MG\n3;바니걸 게이머 A\n5;온천 부원 A\n#1;black\n#3;black\n#5;black\n#wait;1000"
10013080-82 = "#na;카이저 영업사원 이사;그걸 위해 다양한 놈들을 이곳 군도로 끌어들였다."
10013080-88 = "#na;카이저 영업사원 이사;이번 해프닝이 백귀야행의 이름을 좀먹고 나면, 그 뒤엔 만신창이가 된 백야당을 사들인다."
10013080-89 = "#na;카이저 영업사원 이사;완벽한 계획이지?"
10013080-91 = "3;카이저 영업사원 이사;00;하지만 이번에도 또다시 네놈에게 방해받아버렸군. 샬레의 선생.\n#3;em;[반응]\n#3;a"
10013080-92 = "[s] \"방해를 받아? 나한테?\""
10013080-93 = "3;카이저 영업사원 이사;00;이번엔 무슨 수를 썼지?"
10013080-94 = "3;카이저 영업사원 이사;00;백야당의 버팀목이 되어주었나? 포기하지 말고 싸우자고 응원이라도 했나? 달콤한 속삭임이라도 주었던가?\n#3;em;…"
10013080-95 = "3;카이저 영업사원 이사;00;무의미하군. 그런 것보다 내가 더 현실적인 제안을 하마."
10013080-96 = "3;시즈코 수영복ND;05;……무슨 소리야?\n#3;em;[?]"
10013080-97 = "3;카이저 영업사원 이사;00;계약을 맺도록 하지. 네놈들에게 투자해주마.\n#3;em;[반응]"
10013080-98 = "3;우미카;04;투, 투자를……? 저희에게? 문어 은행, 아니, 카이저 코퍼레이션이 말인가요?\n#3;stiff"
10013080-99 = "3;카이저 영업사원 이사;00;그래. 여기까지 도달한 걸 보니, 생각보다 괜찮은 놈들이라는 생각이 들어서 말이야.\n#3;greeting"
10013080-100 = "3;카이저 영업사원 이사;00;필시 여기까지 오는 길에, 다양한 이들과 프랜차이즈 계약을 맺었다고 들었다. 우리도 거기에 한 손 거들도록 하지.\n#3;m2"
10013080-101 = "3;카이저 영업사원 이사;00;물론 지금까지는 여러모로 마츠리운영관리부의 이름으로 계약서를 뿌린 탓에 다소 이름에 흠집은 나 있겠지만.\n#3;em;[...]"
10013080-102 = "3;카이저 영업사원 이사;00;그것도 전부 돈이면 해결될 문제다."
10013080-103 = "3;카이저 영업사원 이사;00;자, 우리가 투자하도록 하마. 더욱 많은 돈을 벌 기회다.\n#3;em;[반응]"
10013080-104 = "3;카이저 영업사원 이사;00;이번에야말로 계약 관계를 확실히 하고\n#3;m3"
10013080-105 = "3;카이저 영업사원 이사;00;마츠리운영관리부가 이곳 <로스트 파라다이스 리조트>를 운영하면서 막대한 이익을 벌어들이는 게다.\n#3;closeup\n#3;a"
10013080-106 = "3;카이저 영업사원 이사;00;……설마 바보가 아닌 이상, 이런 좋은 기회를 걷어차지는 않겠지?\n#3;closeup\n#3;em;[!]"
10013080-107 = "#st;[0,0];instant;1;"
10013080-110 = "3;시즈코 수영복ND;05\n5;미모리 수영복ND;06\n1;우미카;04\n#1;a\n#3;a\n#5;a\n#wait;500"
10013080-111 = "3;시즈코 수영복ND;05\n1;우미카;04;사장님…….\n#1;em;[땀]\n#1;stiff"
10013080-112 = "3;시즈코 수영복ND;05\n5;미모리 수영복ND;06;시즈코 쨩."
10013080-113 = "1;우미카;04\n5;미모리 수영복ND;06\n3;시즈코 수영복ND;99;…………."
10013080-114 = "1;우미카;04\n5;미모리 수영복ND;06\n3;시즈코 수영복ND;01;그거, 참 솔깃한 제안인걸.\n#3;em;[반짝]\n#3;greeting\n#3;closeup\n#1;dl\n#5;dr"
10013080-115 = "3;이즈나 수영복ND;06;시즈코 공…….\n#3;em;[속상함]"
10013080-116 = "3;시즈코 수영복ND;99;……하지만."
10013080-117 = "#st;[0,0];instant;1;"
10013080-119 = "3;시즈코 수영복ND;99\n#3;d\n#wait;1000"
10013080-120 = "3;시즈코 수영복ND;05;거절하겠어.\n#3;em;[!]\n#3;closeup\n#3;a"
10013080-121 = "3;카이저 영업사원 이사;00;……뭐? 진심인가?\n#3;em;[?!]"
10013080-123 = "3;니야;00\n#3;a\n#3;sig\n#wait;500"
10013080-124 = "#na;시즈코 수영복ND;니야가 말했었지."
10013080-125 = "#na;시즈코 수영복ND;카이저 코퍼레이션에게 사기를 당했다면, 그냥 돌아가면 된다고."
10013080-126 = "#na;시즈코 수영복ND;저쪽이 더러운 수를 썼다면 이쪽도 똑같이 갚아주면 될 일이라고. 괜히 여기에 남을 필요 따윈 없다고 말이야."
10013080-128 = "3;시즈코 수영복ND;05;하지만 난 남기로 결정했어.\n#3;em;[반응]\n#3;a"
10013080-129 = "3;시즈코 수영복ND;99;물론 앞서 말했다시피 백귀야행이라는 이름의 <브랜드 가치> 때문이기도 하지만…….\n#3;greeting"
10013080-130 = "3;시즈코 수영복ND;01;또 하나의 이유. 그건………"
10013080-131 = "3;시즈코 수영복ND;05;축제를 바보 취급하는 녀석들은 절대로 용서할 수 없어서야!\n#3;closeup\n#fontsize;80"
10013080-132 = "#st;[0,0];instant;1;"
10013080-134 = "3;카이저 영업사원 이사;00\n#3;em;…\n#wait;2500"
10013080-135 = "3;카이저 영업사원 이사;00;무슨 헛소리를…….\n#3;stiff\n#3;em;[속상함]"
10013080-136 = "3;시즈코 수영복ND;05;온천개발부 아이들은\n#3;em;[반응]"
10013080-138 = "#st;[0,0];instant;1;"
10013080-140 = "1;온천 부원 A;00\n5;온천 부원 C;00\n#1;a\n#5;a\n#1;h\n#5;h\n#wait;750"
10013080-141 = "1;온천 부원 A;00\n5;온천 부원 C;00\n2;카스미;01\n4;메구;01\n#2;a\n#4;a\n#2;h\n#4;h\n#wait;750"
10013080-142 = "#na;시즈코 수영복ND;그저 자기가 찾고 싶은 걸 향해 노력하는 녀석들이었어."
10013080-143 = "#na;시즈코 수영복ND;그래서 계약을 하자고 했어."
10013080-144 = "#st;[0,0];instant;1;"
10013080-147 = "1;바니걸 게이머 A;03\n5;바니걸 게이머 B;03\n#1;a\n#5;a\n#1;h\n#5;h\n#wait;750"
10013080-148 = "3;무시퀸 챔피언;03\n#3;a\n#wait;750"
10013080-149 = "#na;시즈코 수영복ND;무시퀸 대회는 어디까지나 자기들이 재미있으니까 여는 축제의 여흥 같은 거였지."
10013080-150 = "#na;시즈코 수영복ND;그것도 좋겠다 싶어 계약하자고 했어."
10013080-151 = "#st;[0,0];instant;1;"
10013080-154 = "1;쿠로카메구미 조원 A;00\n3;냥텐마루;00\n5;쿠로카메구미 조원 C;00\n#1;a\n#3;a\n#5;a\n#1;h\n#3;h\n#5;h"
10013080-155 = "#na;시즈코 수영복ND;하지만 당신네들은 달라. 냥텐마루와 같아."
10013080-156 = "#na;시즈코 수영복ND;이러고 있는 순간에도 군도 여기저기선 <리조트 사냥>이 벌어지면서 손님들이 피해를 보고 있을 거야."
10013080-158 = "3;시즈코 수영복ND;05;가장 즐거워야 할 여름의 한때가 당신, 카이저 코퍼레이션의 욕심 때문에 망가지고 있는 거라구!\n#3;em;[빠직]\n#3;hophop\n#3;a"
10013080-159 = "#st;[0,0];instant;1;"
10013080-161 = "3;시즈코 수영복ND;05\n#3;d\n#wait;800"
10013080-162 = "3;시즈코 수영복ND;05;그런 건 용납 못 해-!\n#3;em;[!]\n#3;closeup\n#3;a"
10013080-163 = "3;시즈코 수영복ND;05;뿐만 아니라, 이런 상황을 만든 너희 카이저 코퍼레이션도 똑같이 용서 못 해!\n#3;closeup\n#3;hophop"
10013080-164 = "3;시즈코 수영복ND;05;그러니 그 웃기지도 않는 제안에 대한 대답이라면 하나!\n#3;closeup"
10013080-165 = "3;시즈코 수영복ND;05;거절이야! 응! 완전 거절! 절대로 NO입니다!\n#3;closeup\n#fontsize;100"
10013080-167 = "5;미모리 수영복ND;03\n1;우미카;10;사장님!\n#5;a\n#1;a\n#1;em;[반짝]\n#5;h"
10013080-168 = "1;우미카;10\n5;미모리 수영복ND;03;시즈코 쨩!\n#5;em;[///]\n#1;h"
10013080-170 = "3;카이저 영업사원 이사;00;……고작 그런 이유로, 돈이 되는 기회를 뻥 차버린다고? 멍청한 선택을 하겠다는 거냐?\n#3;em;[반응]\n#3;a"
10013080-171 = "[s] \"멍청한 선택이 아니야. 시즈코의 결정이다.\""
10013080-172 = "3;카이저 영업사원 이사;00;샬레의 선생……."
10013080-173 = "[s3] \"딱히 처음부터 내가 한 일은 없었어. 모든 건 시즈코가 결심한 거였으니까.\"\n[s4] \"선생인 나는 믿고 따를 뿐이야.\""
10013080-176 = "3;카이저 영업사원 이사;00;바보 같기는……. 대체 그까짓 신념 따위가 뭐라고-!\n#3;stiff"
10013080-177 = "3;카이저 영업사원 이사;00;……뭐, 좋다. 열을 내봤자, 우습기만 할 뿐."
10013080-178 = "3;카이저 영업사원 이사;00;그렇다면 이쪽도 정당하게 헬멧단의 이름으로 <리조트 사냥>을 해서 빼앗으면 그만이다!"
10013080-179 = "3;카이저 영업사원 이사;00;라브, 인원을 전부 불러라!\n#3;em;[!]\n#fontsize;80"
10013080-180 = "3;카이저 영업사원 이사;00\n5;라브;10;하하하! 그것만 기다리고 있었다고!\n#5;em;[재잘]\n#5;al\n#3;m1"
10013080-181 = "#st;[0,0];instant;1;"
10013080-183 = "3;카이저 영업사원 이사;00\n5;라브;01\n#5;m4\n#3;dl\n#wait;1000"
10013080-184 = "5;라브;01\n#5;m3\n#wait;1000"
10013080-186 = "1;PMC 병사 A;00\n3;PMC 병사 B;00\n5;PMC 병사 C;00\n#1;black\n#3;black\n#5;black"
10013080-188 = "1;헬멧단 A;00\n3;헬멧단 B;00\n5;헬멧단;00\n#1;black\n#3;black\n#5;black"
10013080-190 = "1;복면노노미 수영복ND;00\n3;복면호시노 수영복ND;00\n4;복면세리카 수영복;00\n5;복면시로코 수영복;00\n#1;black\n#3;black\n#4;black\n#5;black"
10013080-192 = "1;노노미 수영복ND;00\n2;아야네 수영복ND;00\n3;호시노 수영복ND;00\n4;세리카 수영복;00\n5;시로코 수영복;00\n#1;black\n#2;black\n#3;black\n#4;black\n#5;black"
10013080-195 = "3;라브;08;모두 집합!\n#3;closeup\n#fontsize;100"
10013080-197 = "1;PMC 병사 A;00\n3;PMC 병사 B;00\n5;PMC 병사 C;00\n#1;al\n#3;al\n#5;al\n#1;h\n#3;h\n#wait;1200"
10013080-199 = "1;헬멧단 A;00\n3;헬멧단 B;00\n5;헬멧단;00\n#1;ar\n#3;ar\n#5;ar\n#1;h\n#3;h\n#wait;1200"
10013080-201 = "3;이즈나 수영복ND;04;우, 우와아앗! 수, 숫자가 어, 엄청나게 많아요! 어, 어쩌죠?! 주군?!\n#3;hophop\n#3;em;[땀]\n#3;a"
10013080-202 = "3;이즈나 수영복ND;04\n5;치세 수영복ND;12;음~ 다 같이 축제를 벌이는 거야~?\n#5;em;[?]\n#5;greeting\n#5;a"
10013080-203 = "1;우미카;07;으음! 치세 씨 말대로 축제라면 축제라고도 할 수 있겠지만요-! 사장님?! 어떡해요?!\n#1;hophop\n#1;ar"
10013080-205 = "3;시즈코 수영복ND;06;일단 뒤로 빠지면서! 탈출구를 찾으면……!\n#3;stiff"
10013080-206 = "3;라브;07;하! 도망칠 수 있을 것 같으냐! 어이, 헬멧단 신입들! 뒤를 막아!\n#3;em;[!]\n#3;jump"
10013080-207 = "#st;[0,0];instant;1;"
10013080-210 = "[ns] \"이런! 뒤에도 헬멧단……………………이?\""
10013080-211 = "1;복면노노미 수영복ND;00\n5;복면세리카 수영복;00\n3;복면호시노 수영복ND;00\n#1;black\n#3;black\n#5;black\n#wait;1500"
10013080-212 = "#na;라브;이번에 뛰어난 실력을 지닌 헬멧단 멤버들을 새로 뽑았거든! 자! 실력을 보여줘!"
10013080-213 = "3;복면호시노 수영복ND;00\n#3;black\n#3;em;[재잘]"
10013080-214 = "#na;???;으헤~ 이렇게 해서 무사히 작전 성공~"
10013080-215 = "5;복면세리카 수영복;00\n#5;black\n#5;em;[땀]\n#5;stiff"
10013080-216 = "#na;???;정말로 성공한 거야?! 진짜로?! 이래도 되는 거야?!"
10013080-217 = "1;복면노노미 수영복ND;00\n#1;black\n#1;greeting\n#1;em;[음표]"
10013080-218 = "#na;???;그만큼 엄청난 작전이었단 거죠~☆"
10013080-219 = "5;복면세리카 수영복;00\n1;복면노노미 수영복ND;00\n3;복면호시노 수영복ND;00\n#1;a\n#3;black\n#5;black\n#wait;500"
10013080-220 = "1;복면노노미 수영복ND;00\n3;복면호시노 수영복ND;00\n5;복면세리카 수영복;00\n#3;black\n#5;a\n#wait;500"
10013080-221 = "1;복면노노미 수영복ND;00\n5;복면세리카 수영복;00\n3;복면호시노 수영복ND;00\n#3;a\n#wait;1000"
10013080-223 = "3;복면시로코 수영복;00;응. <헬멧단으로 위장해서 의심받지 않고 적진 깊숙이 숨어들기 작전> 대성공.\n#3;greeting\n#3;em;[반짝]\n#3;a"
10013080-224 = "[s] \"……….\""
10013080-225 = "3;시즈코 수영복ND;06;어, 어, 어어어?!\n#3;em;[?!]\n#3;shake"
10013080-226 = "3;라브;02;응? 왜 그래? 신입들! 저 녀석들의 퇴로를 막고! 해치워버려!\n#3;em;[!]"
10013080-227 = "[s] \"아니…… 저기…….\""
10013080-228 = "3;라브;02\n5;카이저 영업사원 이사;00;……잠깐, 라브. 네놈 설마.\n#5;al\n#5;em;[땀]\n#3;m2"
10013080-229 = "5;카이저 영업사원 이사;00;네놈이 오는 길에 말했던 뛰어난 실력을 가진 헬멧단 신입이라는 게……."
10013080-230 = "3;라브;01;응? 다들 왜 그래?\n#3;em;[?]"
10013080-232 = "#st;[0,0];instant;1;"
10013080-234 = "5;카이저 영업사원 이사;00\n3;라브;01\n1;복면호시노 수영복ND;00\n#3;m4\n#5;dr\n#1;ar\n#wait;1400"
10013080-235 = "1;복면호시노 수영복ND;00"
10013080-236 = "1;호시노 수영복ND;00\n#1;greeting\n#wait;1000"
10013080-237 = "3;라브;11;앗?! 너는! 그때 봤던?!\n#3;em;[!]\n#3;hophop"
10013080-238 = "#st;[0,0];instant;1;"
10013080-240 = "1;호시노 수영복ND;00"
10013080-241 = "1;복면호시노 수영복ND;00\n#1;greeting\n#wait;1200"
10013080-242 = "3;라브;06;으, 으음?! 잘못 봤나?!\n#3;em;[?!]\n#3;shake"
10013080-243 = "1;복면호시노 수영복ND;00\n3;라브;04;아냐! 복잡한 건 됐어! 헬멧단 신입들! 전부 전투 준비……!\n#1;dl\n#3;m3\n#3;em;[반응]"
10013080-244 = "#st;[0,0];instant;1;"
10013080-247 = "3;복면호시노 수영복ND;00\n#wait;1000"
10013080-248 = "3;호시노 수영복ND;21;으헤~\n#3;greeting\n#3;closeup"
10013080-249 = "3;라브;11;어, 어어어어?! 너, 너는?!\n#3;em;[?!]\n#3;shake"
10013080-250 = "3;카이저 영업사원 이사;00;………"
10013080-251 = "3;미모리 수영복ND;02;……어머.\n#3;em;[반응]"
10013080-252 = "3;치세 수영복ND;14;어, 선생님. 나비-\n#3;hophop\n#3;m4"
10013080-253 = "3;카이저 영업사원 이사;00;아, 아비도스……! 네놈들이 어째서 여기에?! 라브, 어떻게 된 거지?!\n#fontsize;100"
10013080-254 = "3;라브;11;자, 잠깐! 나는 분명! 조금은 이상하긴 해도 엄청나게 쿨하고 힙한 헬멧을 쓴 녀석들이라고 생각해서-!!\n#3;em;[!]\n#3;hophop"
10013080-255 = "3;시즈코 수영복ND;05;……선생님 말대로, 엄청나게 기상천외한 방법…….\n#3;em;…"
10013080-256 = "[s] \"아니, 나라고 이런 걸 생각한 건 아니었지만…….\""
10013080-257 = "3;세리카 수영복;08;우리도 당신네가 꾸민 일 때문에! 리조트 사용권 상품에 당첨되어서 온 거라고!\n#3;em;[빠직]\n#3;a"
10013080-258 = "3;세리카 수영복;08\n2;아야네 수영복ND;08;이번 일도 다! 카이저 이사! 당신의 소행이었군요!\n#3;m4\n#2;ar\n#2;em;[!]"
10013080-259 = "3;세리카 수영복;08\n2;아야네 수영복ND;08\n5;카이저 영업사원 이사;00;아니, 잠깐 그럴 리가. 나는 어디까지나 소동을 일으킬 문제아들로만 골라서 사용권을 팔았…….\n#5;al\n#5;em;[땀]\n#2;m1\n#3;m3"
10013080-261 = "3;카이저 영업사원 이사;00;잠깐, 당첨되었다고? 어떻게?\n#3;em;[?!]\n#3;shake"
10013080-262 = "[s] \"그러고 보니 정작 세리카가 어디서 당첨되었는지 듣지는 못했네.\""
10013080-263 = "3;세리카 수영복;04;어, 어? 나, 나 말이야?\n#3;jump"
10013080-264 = "3;세리카 수영복;17;그냥 그……. 시바세키 라멘집에서 마스터가 열었던 스페셜 빙고 대회에서……. 이겨서…… 그게…….\n#3;em;[///]\n#3;stiff\n#fontsize;55"
10013080-265 = "#st;[0,0];instant;1;"
10013080-267 = "3;아야네 수영복ND;04\n5;호시노 수영복ND;12\n1;시로코 수영복;06\n#1;a\n#5;a\n#3;h\n#5;h\n#3;em;…\n#5;em;…\n#1;em;…\n#wait;2500"
10013080-268 = "[ns] \"그렇게 된 거였구나.\""
10013080-269 = "1;시로코 수영복;06\n3;아야네 수영복ND;04\n5;호시노 수영복ND;15;뭐, 덕분에 다 같이 여기 모일 수 있게 되었으니까 그치?\n#3;m5\n#5;m3"
10013080-271 = "3;시즈코 수영복ND;02;응! 덕분에! 엄청나게 든든해졌어!\n#3;em;[!]\n#3;jump"
10013080-272 = "#st;[0,0];instant;1;"
10013080-275 = "1;시즈코 수영복ND;02\n5;호시노 수영복ND;16\n#1;a\n#5;a\n#1;h\n#5;h"
10013080-276 = "[ns] \"그럼 백귀야행과 아비도스, 공동 작전 시작이야!\""
