[translation]
1001002-1 = "Running Machine"
1001002-2 = "Kivotos Streets"
1001002-3 = "(I'm waiting for Shiroko along her morning jogging path.)"
1001002-5 = "Hmm."
1001002-6 = "Did I keep you waiting, Sensei?"
1001002-7 = "[s] \"No, I just got here a moment ago.\""
1001002-8 = "Oh, okay."
1001002-9 = "Meeting you away from school like this feels so different."
1001002-10 = "It sort of reminds me of the first time we met..."
1001002-11 = "Nothing beats a good workout."
1001002-12 = "[s] \"You really like exercising, don't you?\""
1001002-13 = "There you are."
1001002-14 = "Nothing beats working up a good sweat to start the day."
1001002-15 = "..."
1001002-16 = "And taking a shower once I get to school, obviously."
1001002-17 = "Hmm."
1001002-18 = "Do you think you're up for joining me on my morning jog?"
1001002-19 = "[s1] \"I'm not sure about running first thing in the morning...\"\n[s2] \"I'd rather not be exhausted for the rest of the day, honestly.\""
1001002-20 = "Hmm. I can see where you're coming from. I need to do some shopping, anyway, so maybe next time."
1001002-21 = "Hmm. I can see where you're coming from. I need to do some shopping, anyway, so maybe next time."
1001002-22 = "Actually, the market I'm headed to is right over there."
1001002-23 = "It's not that far, so let's run there."
1001002-24 = ""
1001002-25 = "[s] Follow Shiroko."
1001002-27 = "(One hour later...)"
1001002-29 = ""
1001002-30 = ""
1001002-31 = ""
1001002-32 = "..."
1001002-33 = "[s] *pant* ... *pant* ... *pant*..."
1001002-34 = "There you are."
1001002-35 = "I was wondering what was taking you so long..."
1001002-36 = "Was I running too fast? Sorry. "
1001002-37 = "People tell me I tend to get tunnel vision when I have a goal in mind..."
1001002-38 = "[s3] \"I thought the market was close by.\"\n[s4] \"We've been running for an hour...\""
1001002-39 = "Oh..."
1001002-40 = "Oh..."
1001002-41 = "We're about halfway there. "
1001002-42 = "[s] \"Halfway?!\""
1001002-43 = "It's just another hour of running. I'll slow my pace a little, so focus on keeping up, Sensei."
1001002-44 = ""
1001002-45 = "[s] \"W-Wait!\""
1001002-47 = "(I stop Shiroko as she's running and ask to walk.)"
1001002-48 = "(Then we walk for two more hours.)"
1001002-50 = "Here we are. This is the market."
1001002-51 = "Huh?"
1001002-52 = "Sensei, are you okay? You don't look so good..."
1001002-53 = "[s] \"How far did we travel to get here?\""
1001002-54 = "Hmm. About 15 kilometers?"
1001002-55 = "It's just the right distance to stop at when on the way back from a morning run."
1001002-56 = "I was going to go to a convenience store that's further away, but I chose somewhere close since you're with me."
1001002-57 = "It wasn't so bad since we walked, right?"
1001002-58 = "Wait, you can't lie down here, Sensei. We have to walk 15 more kilometers back..."
1001002-59 = "[s] \"End my suffering...\""
1001002-60 = "U-Umm..."
