[translation]
10017085-1 = "ตอนที่ 8;ความฝันในคืนกลางฤดูหนาว"
10017085-2 = "ทางเข้าคาเฟ่ <ไวท์&เมสัน>"
10017085-3 = ""
10017085-4 = "อ๊ากกก!"
10017085-5 = "แพ้อีกแล้ว......!"
10017085-6 = "ปะ... เป็นแบบนี้ไปได้ยังไง?"
10017085-7 = "พลังของเจ้าพวกนั้นเหลือไม่ถึงครึ่งแล้วนี่นา...?"
10017085-8 = "แบบนี้ใครมันจะไปยอมรับได้กันเล่า! เราแพ้ราบคาบง่ายๆ แบบนี้เลยเหรอ...!"
10017085-10 = "คิกคิกคิกคิก!"
10017085-11 = "ยอมรับความเป็นจริงไม่ได้เหรอคะ"
10017085-13 = "ถึงพวกเราจะอ่อนแอลง ก็ไม่ได้หมายความว่าพวกคุณจะแข็งแกร่งขึ้นหรอกนะคะ"
10017085-15 = ""
10017085-17 = ""
10017085-18 = "ฉันไม่ได้อยากฟังคำคมจากปากของเธอหรอกนะ!"
10017085-19 = "ใช่! นี่น่ะเหรอหัวหน้าชมรมอัศวินบรรเทาทุกข์! หัวหน้าประสาอะไรเอาแต่ทำลายข้าวของเค้าไปทั่ว!"
10017085-21 = "ฟังให้ดีนะคะ คริสต์มาสคือวันที่รู้จักกันดีว่าเป็นวันแห่งความสุข และมันก็เป็นอย่างนั้นจริงๆ ค่ะ"
10017085-22 = "แต่แก่นแท้ของวันนี้ก็คือ การขอบคุณ การมองย้อนกลับไป การแบ่งปัน และการเฉลิมฉลองค่ะ"
10017085-23 = "นั่นคือเราควรมองไปรอบๆ ตัวเราอย่างใจกว้าง และปรับเปลี่ยนตัวเองให้ดีขึ้น"
10017085-24 = "แต่ในวันแบบนี้! พวกคุณกลับใช้ประโยชน์จากมิตรไมตรีของคนอื่นแล้วหลอกลวงจนเกิดเรื่องวุ่นวาย!"
10017085-25 = "แบบนี้คงไม่มีทางที่จะจบลงด้วยดีแน่ๆ ค่ะ!"
10017085-27 = ""
10017085-29 = ""
10017085-30 = "ยะ... อย่ามาตลกนะ! ครั้งหน้าไม่ยอมให้แน่!"
10017085-31 = "ไม่น่ามาสะดุดเลย! เกือบจะเป็นไปตามแผนทั้งหมดแล้วเชียว!"
10017085-33 = ""
10017085-35 = ""
10017085-36 = ""
10017085-38 = ""
10017085-40 = ""
10017085-43 = ""
10017085-44 = "หนีไปซะได้นะคะ"
10017085-45 = "น่าโมโหมากเลยค่ะ ถ้าร่างกายพวกเราอยู่ในสภาพสมบูรณ์ละก็...!"
10017085-46 = "ที่เรามาอยู่กันในสภาพนี้มันเป็นเพราะใครกันล่ะคะ..."
10017085-48 = "ทุกคนเป็นยังไงกันบ้างคะ?"
10017085-49 = "เดี๋ยวจะช่วยรักษาให้เองค่ะ! วางใจพวกฉันได้เลย!"
10017085-51 = "อ่า... ขอบคุณค่ะ... แต่คุณทั้งสองไปรักษาสมาชิกชมรมทวงความยุติธรรมคนอื่นก่อนเถอะค่ะ"
10017085-53 = "ไม่ต้องห่วงหรอกค่ะ คนอื่นที่บาดเจ็บได้รับการปฐมพยาบาลไปหมดแล้วค่ะ"
10017085-54 = "ก็พวกฉันเตรียมพร้อมอยู่ทุกเมื่ออยู่แล้วนี่คะ!"
10017085-56 = "เสร็จแล้วเหรอคะ? ไวมากเลย..."
10017085-57 = "ปกติเราก็เป็นหนี้บุญคุณบ่อยๆ อยู่แล้ว... ต้องขอโทษด้วยนะคะ "
10017085-59 = ""
10017085-61 = ""
10017085-62 = "อย่าพูดแบบนั้นสิคะ เรื่องในวันนี้... ก็เป็นความผิดของฉันด้วย..."
10017085-63 = "ขะ... ขอโทษค่ะคุณฮาสุมิ ฉันไม่รู้ว่าจะขอโทษอย่างไรให้หมด แต่ฉันก็จะพยายามอย่างเต็มที่ค่ะ..."
10017085-65 = ""
10017085-67 = ""
10017085-68 = ""
10017085-70 = "(มิเนะเป็นฝ่ายทำลายล้าง ส่วนอัศวินคนอื่นก็คอยตามเก็บสินะ...)"
10017085-71 = "(ไม่ได้เจอเรื่องแบบนี้มานานจนรู้สึกไม่คุ้นเคยเลย แต่เดิมทีมันก็เป็นอย่างนี้แหละค่ะ เฮ้อ...)"
10017085-72 = ""
10017085-73 = "......สรุปว่า มีอะไรจะพูดเกี่ยวกับเหตุการณ์ในครั้งนี้ไหมคะ? หัวหน้ามิเนะ?"
10017085-74 = "ฉันไม่มีข้อแก้ตัวใดๆ ค่ะ"
10017085-75 = ""
10017085-77 = ""
10017085-79 = "หัวหน้า? ทำไมจู่ๆ ก็วางโล่ลงล่ะคะ...? แล้วยังถอดเสื้อคลุม... และส่งปืนให้ฉันด้วย...?"
10017085-80 = "ความผิดนี้ต้องชำระด้วยความตายสถานเดียว!"
10017085-81 = "ฉันขอฝากบทลงโทษทั้งหมดไว้กับรองหัวหน้าฮาสุมิค่ะ!"
10017085-82 = "คะ...?"
10017085-84 = ""
10017085-86 = ""
10017085-87 = "หะ... หัวหน้าคะ..."
10017085-88 = ""
10017085-90 = ""
10017085-91 = "ฮือ... หัวหน้าา~"
10017085-93 = "อย่าร้องเลยค่ะ เซรินะ ฮานาเอะ อัศวินต้องรับผิดชอบต่อสิ่งที่เกิดขึ้น"
10017085-94 = "หากไม่มีใครรับผิดชอบต่อสิ่งที่ก่อเรื่องไป ความเสียใจต่อเหตุการณ์นั้นก็จะทวีคูณขึ้นค่ะ"
10017085-95 = "ฉันจะปลดอาวุธทั้งหมดของฉันและส่งมอบให้ ได้โปรดลงโทษ...!"
10017085-96 = "เฮ้อ..."
10017085-97 = "แค่คลี่คลายความเข้าใจผิดได้ ฉันก็พอใจแล้วค่ะ"
10017085-98 = "อีกอย่าง ฉันกับสมาชิกชมรมทวงความยุติธรรมที่บาดเจ็บก็ได้รับการรักษาแล้วด้วยความช่วยเหลือจาก ชมรมอัศวินบรรเทาทุกข์ค่ะ"
10017085-99 = "ซึรุกิเองก็ไม่เป็นไรแล้วใช่ไหมคะ?"
10017085-100 = "...คิกคิกคิกคิก..."
10017085-101 = "ซึรุกิบอกว่าไม่เป็นไรแล้วค่ะ ให้เหตุการณ์นี้จบลงที่ตรงนี้เถอะค่ะ"
10017085-102 = "ขอบคุณสำหรับหลายๆ เรื่องเลยค่ะ คุณเซรินะ คุณฮานาเอะ"
10017085-104 = ""
10017085-106 = ""
10017085-107 = "เอ๊ะ?! มะ... ไม่เลยค่ะ พวกฉันก็แค่ทำในสิ่งที่ต้องทำในฐานะชมรมอัศวินบรรเทาทุกข์..."
10017085-108 = "พวกฉันต่างหากล่ะคะที่ต้องขอบคุณ ที่คุณให้อภัยความผิดพลาดของชมรมอัศวินบรรเทาทุกข์น่ะค่ะ..."
10017085-110 = "เรื่องนั้น..."
10017085-111 = "ไม่มีอะไรหรอกค่ะ งั้นถือว่าเราเคลียร์กันได้ตรงนี้แล้วกันค่ะ"
10017085-112 = "ลุกขึ้นเถอะค่ะ หัวหน้ามิเนะ ถ้ายังนั่งอยู่แบบนี้ ฉันลำบากใจนะคะ"
10017085-113 = "[s] \"ชมรมทวงความยุติธรรมบอกว่าเคลียร์กันได้แล้วนะ\""
10017085-114 = "แต่ว่า... คุณครูคะ..."
10017085-115 = "[s1] \"ถึงทั้งหมดจะเป็นการปั่นหัวหลอกใช้กันของพวกนักเลง\"\n[s2] \"แต่การที่เรารับฟังปัญหาของคนอ่อนแอ ครูว่าเป็นเรื่องที่น่ายกย่องนะ\""
10017085-118 = "......"
10017085-119 = "ถ้าคุณครูพูดอย่างนี้ ฉันก็ยิ่งละอายใจ.."
10017085-121 = ""
10017085-123 = ""
10017085-124 = "อ่า... ถ้างั้นพวกฉันขอตัวก่อนนะคะ..."
10017085-125 = "ต้องขอโทษด้วยนะคะ... ขอโทษจริงๆ ค่ะ! กำลังจัดปาร์ตี้อยู่แท้ๆ เลย!"
10017085-127 = "นั่นสิ เรามีปาร์ตี้กันนี่นา..."
10017085-128 = "ไหนๆ ก็ไหนๆ แล้ว ชมรมอัศวินบรรเทาทุกข์มาปาร์ตี้กับพวกฉันไหมล่ะคะ?"
10017085-130 = "คะ? พวกฉันเหรอคะ...?"
10017085-131 = "ให้พวกฉันเข้าปาร์ตี้ได้เหรอคะ?!"
10017085-133 = "ค่ะ เรื่องวุ่นวายก็จัดการไปเรียบร้อยแล้ว และปกติถ้ามีคนเยอะๆ ปาร์ตี้ก็จะยิ่งสนุกยังไงล่ะคะ"
10017085-134 = "เราเชิญชมรมอัศวินบรรเทาทุกข์ได้ไหมคะ? ซึรุกิ?"
10017085-135 = "เฮือก? อึก... เอ่อ... อืมมม...."
10017085-136 = ""
10017085-138 = ""
10017085-140 = "ซึรุกิบอกว่าเธอตกใจและก็อายนิดหน่อย แต่ก็ยินดีต้อนรับเข้าปาร์ตี้ค่ะ"
10017085-141 = "คุณครูล่ะ ว่ายังไงบ้างคะ?"
10017085-142 = "[s3] \"ครูเห็นด้วยอย่างยิ่งเลย!\"\n[s4] \"ไปปาร์ตี้กันเลย!\""
