[translation]
1001808-1 = "#title;유원지에서의 약속"
1001808-2 = "#place;놀이공원 정문 입구"
1001808-3 = "2;유즈;01\n#2;a\n#wait;2000"
1001808-4 = "2;유즈;02\n#2;em;[반응]\n#wait;1500"
1001808-5 = "2;유즈;03;선생님, 이쪽이에요, 이쪽.\n#2;m3\n#2;hophop"
1001808-6 = "2;유즈;07;헤헤…… 인형탈 없이 이렇게 선생님과 함께 놀이공원을 거닐 수 있다니, 어쩐지 신기한 느낌이네요…….\n#2;stiff"
1001808-7 = "2;유즈;02;오늘은 아르바이트를 하지 않아도 괜찮으냐고요?\n#2;em;[?]"
1001808-8 = "2;유즈;03;네, 오늘은 비번이거든요.\n#2;greeting"
1001808-9 = "2;유즈;07;마침 공원에서 비번 때 쓰라고 나누어 준 자유이용권이 두 장 있어서…… 제가 일하는 곳에 선생님을 직접 모시고 싶었어요.\n#2;em;[하트]"
1001808-10 = "2;유즈;01;호, 혹시 폐가 되었으려나요……?"
1001808-11 = "[s] \"아니, 나도 놀이공원은 좋아해.\""
1001808-12 = "2;유즈;03;다행이다……. #n혹시라도 바쁘신 선생님을 귀찮게 한 건 아닐까 걱정했거든요."
1001808-13 = "2;유즈;07;그, 그럼 오늘은 함께 놀이기구를 타며 시간을 보내죠……!\n#2;em;[음표]"
1001808-14 = "[s] \"유즈는 어떤 놀이기구를 좋아해?\""
1001808-15 = "2;유즈;01;선생님과 함께 타는 놀이기구라면 무엇이든 좋지만…… 아, 아직은 사람이 무서워서…….\n#2;em;…"
1001808-16 = "2;유즈;02;가능하면 사람이 많지 않은 놀이기구 쪽이 좋아요……."
1001808-17 = "[s1] \"그럼 대관람차를 타러 가자.\"\n[s2] \"그럼 롤러코스터를 타러 가자.\""
1001808-18 = "2;유즈;03;좋아요! 대관람차는 사람도 적고, 멀리서 공원을 한눈에 내려다볼 수 있으니까…….\n#2;em;[하트]"
1001808-19 = "2;유즈;03\n#2;m2\n#wait;1000"
1001808-20 = "2;유즈;07;이쪽이에요, 선생님. 제가 안내할게요!"
1001808-21 = "2;유즈;08;로, 로, 롤러코스터요? 롤러코스터는 대기 줄에 사람도 많고, 놀이기구도 무섭잖아요……!\n#2;em;[?!]\n#2;shake"
1001808-22 = "2;유즈;04;서, 선생님 기다려주세요! 혼자 두고 가지 말아주세요……!\n#2;hophop"
1001808-24 = "#na;그리고 한동안 유즈와 즐겁게 놀이기구를 타며 시간을 보냈다……."
1001808-26 = "3;유즈;03;후우…… 오늘은 즐거웠어요.\n#3;em;[음표]\n#3;a"
1001808-27 = "3;유즈;03;놀이공원은 언제 와도 즐거운 공간이지만, 선생님과 함께 와서 더욱 즐거웠던 것 같아요."
1001808-28 = "[s] \"나도 즐거웠어.\""
1001808-29 = "3;유즈;00;저……\n#3;em;…"
1001808-30 = "3;유즈;00;헤, 헤어지기 전에…… 선생님께 드리고 싶은 선물이 있어요…….\n#3;stiff"
1001808-31 = "3;유즈;02;……선물은 놀이공원 자유이용권이 아니냐고요?"
1001808-32 = "3;유즈;05;아, 아니에요!\n#3;hophop"
1001808-33 = "3;유즈;00;그, 그건…… 제가 선생님과 함께 놀고 싶어서 드린 부탁일 뿐인걸요.\n#3;stiff"
1001808-34 = "3;유즈;99;부원들에게는 각자가 좋아하는 걸 사서 선물했지만, 어른인 선생님께는 무얼 드려도 충분하지 않을 것 같아서…… 긴 고민 끝에 준비했어요…….\n#3;em;…"
1001808-35 = "#st;[0,0];instant;1;"
1001808-37 = "3;유즈;01\n#3;d\n#wait;1000"
1001808-38 = "3;유즈;01\n#3;a\n#3;closeup\n#wait;1500"
1001808-39 = "3;유즈;01\n#3;greeting\n#3;closeup\n#wait;2000"
1001808-40 = "3;유즈;00;선생님이 필요하실 때 언제든지 쓸 수 있는……\n#3;closeup"
1001808-41 = "3;유즈;03;……<유즈의 자유이용권>이에요.\n#3;closeup"
1001808-45 = "#st;[-1200,-530];serial;60;[wa:1500]― 선생님이[wa:550] 아니었다면……[wa:1500] 할 수 없었을[wa:800] 거예요."
1001808-48 = "#st;[-1200,-530];serial;60;[wa:1100]― 모두에게[wa:750] 선물을[wa:500] 할 수 있었던 건,[wa:1200] 선생님 [wa:800]덕분이에요."
1001808-51 = "#st;[-1200,-530];serial;60;[wa:1500]― 선생님이[wa:490] 도와주셨던 것처럼……"
1001808-53 = "#st;[-1200,-630];serial;60;― 제가[wa:800] 선생님께[wa:680] 필요한 순간이 온다면,[wa:1770] 뭐든지 [wa:1000]말씀하세요."
1001808-56 = "#st;[-1200,-530];serial;60;[wa:500]― ……[wa:1300]반드시[wa:1470] 보답할게요."
1001808-59 = "3;유즈;03;좋아해 주시는 것 같아서 다행이에요.\n#3;a"
1001808-60 = "3;유즈;02;이 자유이용권을 사용하면 무엇이든 유즈에게 부탁할 수 있느냐고요? #n네, 그야 물론……\n#3;em;[?]"
1001808-61 = "3;유즈;00;무, 무엇이든지……."
1001808-62 = "3;유즈;08;무, 무슨 생각을 하시는 거예요! 그, 그런 생각으로 건넨 물건은 아니라고요!\n#3;shake\n#3;em;[?!]"
1001808-63 = "3;유즈;05;자, 자유이용권이라지만 이, 이상한 건 절대로! 절대로……!\n#3;hophop"
1001808-64 = "3;유즈;00\n#wait;2500\n#3;em;…"
1001808-65 = "3;유즈;01;……"
1001808-66 = "3;유즈;02;절대로…… 안 되…… 니까요……."
