[translation]
10018020-1 = "Episode 2; Fuuka's Back-Alley Enterprise"
10018020-2 = ""
10018020-6 = ""
10018020-7 = "Amazing..."
10018020-8 = ""
10018020-10 = ""
10018020-11 = ""
10018020-12 = "The hood vent, gas burners, fryer, oven… They're all prone to becoming oily messes."
10018020-13 = "But these are so clean that they look brand new."
10018020-14 = ""
10018020-16 = ""
10018020-17 = "Your refrigerator is incredibly neat and ingredients are well organized and easy to access."
10018020-18 = "The vegetables are kind of bruised, but that must be a supplier problem."
10018020-19 = "As for seasonings, it seems like you dispose of them earlier than their stated shelf life?"
10018020-20 = "Well, if I got someone sick, I'd lose credibility! ...Is that not okay?"
10018020-21 = "N-Not at all!"
10018020-22 = "The kitchen is clean, practically spotless."
10018020-23 = "All that being said... Do you always use the same seasonings when you cook?"
10018020-24 = "Yes. That's all that I was taught..."
10018020-25 = "Hmm... All the ingredients are being seasoned the same..."
10018020-26 = "We might have found our first problem."
10018020-27 = "But before that, I've been thinking about something for a while."
10018020-28 = "Yes, what is it?"
10018020-29 = "You said that you source all your ingredients from Nyao Foods, right?"
10018020-30 = "Yes, I don't have any other option..."
10018020-31 = "Well, honestly, the quality of the ingredients are subpar."
10018020-32 = ""
10018020-34 = ""
10018020-35 = "...I see."
10018020-36 = ""
10018020-38 = ""
10018020-39 = "You aren't the only one who noticed that."
10018020-40 = "When I started buying from Nyao Foods, regulars began complaining about the overall taste of their meals."
10018020-41 = "But Nyao Foods monopolized all distribution in this area. I don't have any other choice."
10018020-42 = "If supplies are an issue, the School Lunch Club can help with that!"
10018020-44 = "Right."
10018020-45 = "It's a bit of a distance to travel, but...would you come with me?"
10018020-46 = ""
10018020-49 = ""
10018020-52 = "...Boss, I'd like to ask for your help."
10018020-53 = "Of course! What can I do for you, Fuuka?"
10018020-54 = "I help you, and you help me find more customers? It's a win-win situation!"
10018020-55 = "I-I'm indebted to you..."
10018020-56 = "Oh, no. No need for that kind of talk. It's only natural to help each other in times of need."
10018020-58 = "We supply food to the Gehenna students, so our quality is guaranteed!"
10018020-60 = "To receive all this help, I don't want to be a burden..."
10018020-61 = "Not at all. It's only natural for people in the culinary community to help where help is needed."
10018020-62 = "We're all committed to helping you."
10018020-63 = "And you couldn't have chosen a more trustworthy savior! I would vouch for Fuuka any day!"
10018020-64 = "[s] \"I can as well.\""
10018020-65 = "See? Even Schale's Sensei is on board!"
10018020-67 = "Hahaha..."
10018020-68 = ""
10018020-70 = ""
10018020-72 = ""
10018020-73 = "Hey, isn't that the owner of Sparrow?"
10018020-74 = "I think so. What's going on here? Why are they talking with Chirp Market's owner?"
10018020-75 = ""
10018020-77 = ""
10018020-78 = "Could it be...?"
10018020-81 = ""
10018020-82 = ""
10018020-83 = "Now that we have the ingredients, shall we get cooking?"
10018020-84 = "Juri, can you get started on prep work?"
10018020-85 = "Leave it to me!"
10018020-89 = "I don't mean to overstep on your established practices, but..."
10018020-90 = "...have you considered using the residual heat to mix the sauce?"
10018020-91 = ""
10018020-93 = ""
10018020-94 = "The meat gets coated in it, and the taste and texture will be completely different."
10018020-95 = "It's almost like caramelizing it."
10018020-96 = "Oh... I didn't think of that!"
10018020-100 = "When making soup, stir-fry the ingredients a bit before adding water."
10018020-101 = "It'll give the whole thing a deeper taste."
10018020-102 = "But couldn't I just end up overcooking the solid ingredients?"
10018020-103 = "That's a risk, for sure."
10018020-104 = "Think of it like a puzzle."
10018020-106 = "Each dish needs its own solution and perfect balance."
10018020-109 = "Bulk cooking is hard."
10018020-110 = "The amount of ingredients can be multiplied by the number of people, but you can't necessarily do that for heat."
10018020-111 = "Is there a solution?"
10018020-112 = "Stir often to make sure things cook evenly."
10018020-113 = "But not too much so as to ruin the more delicate ingredients."
10018020-114 = "You have to be careful to strike the perfect balance."
10018020-118 = "So, we've completed a few new menu items."
10018020-119 = "And now we need someone to evaluate if they are a success..."
10018020-120 = "Haruna?"
10018020-122 = "I've been waiting."
10018020-123 = "Now then, time to dig in."
10018020-124 = ""
10018020-126 = ""
10018020-127 = ""
10018020-128 = ""
10018020-129 = ""
10018020-131 = ""
10018020-132 = "(I-I'm so nervous.)"
10018020-133 = "(I'm just a knot of tension right now.)"
10018020-134 = "[s] \"(What am I so nervous for...?)\""
10018020-135 = ""
10018020-138 = ""
10018020-139 = ""
10018020-140 = ""
10018020-141 = "Thank you for the food."
10018020-142 = "The meal..."
10018020-144 = "*gulp*"
10018020-145 = "[ns] \"(Please, don't blow up, Haruna, or blow anything else up...\")"
10018020-146 = ""
10018020-149 = ""
10018020-150 = ""
10018020-152 = "...passes."
10018020-154 = ""
10018020-155 = "Yes!"
10018020-156 = "Phew..."
10018020-158 = "From a gastronomic perspective, it was impeccable."
10018020-159 = "More importantly, it's a shame to eat food like this alone."
10018020-160 = ""
10018020-162 = ""
10018020-163 = "Why don't you all join me?"
10018020-164 = ""
10018020-166 = ""
10018020-171 = ""
10018020-172 = "Food approved by Haruna... I'm excited! ★"
10018020-173 = "The smell made it so painful to wait that it feels like I haven't eaten all day!"
10018020-174 = ""
10018020-176 = ""
10018020-177 = "Okay, let's—"
10018020-178 = ""
10018020-181 = ""
10018020-182 = ""
10018020-186 = "Where's the owner of this dump?!"
10018020-187 = "You! Who said you could change suppliers?"
10018020-188 = "This is a breach of contract! Didn't you read the fine print?"
10018020-189 = "There will be penalties! Compensation! Bankruptcy! And not the kind that rich people get!"
10018020-190 = ""
10018020-195 = ""
10018020-196 = "Hey! Watch where you're going!"
10018020-197 = ""
10018020-206 = ""
10018020-207 = "My... My food..."
10018020-208 = "I didn't even get to taste it!!!"
10018020-209 = "Oh my! What a tragedy. ★"
10018020-211 = "C-Calling it a tragedy is kind of dramatic."
10018020-212 = "A-And it was your fault anyway! You should have been more considerate of my elbow!"
10018020-213 = "[s] \"Not that I think you'll succeed, but you should at least try to run away.\""
10018020-214 = ""
10018020-216 = ""
10018020-218 = ""
10018020-220 = ""
10018020-221 = ""
10018020-223 = "Absolutely...UNFORGIVABLE!"
