[translation]
10016010-1 = "ตอนที่ 1;คณะกรรมการจัดงานสุดร้อนแรง"
10016010-2 = "สำนักงานคณะกรรมการจัดงานฮาโลเฟสติวัล"
10016010-3 = ""
10016010-5 = ""
10016010-6 = ""
10016010-8 = ""
10016010-9 = ""
10016010-10 = "...ขอบคุณทุกคนเลยนะคะที่มาร่วมงานฮาโลเฟสติวัลทั้งที่น่าจะยุ่งกันมากแท้ๆ"
10016010-11 = "พิธีเปิดก็จบไปเรียบร้อยแล้ว ต่อไปฉันขออธิบายกำหนดการที่จะดำเนินการและข้อควรระวังให้ทราบ#nคร่าวๆ นะ"
10016010-12 = "และถึงแม้ว่าในพิธีเปิดจะมีปัญหาเกิดขึ้น 'เล็กน้อย' ก็ตาม..."
10016010-13 = "ตายจริง ทางโรงเรียนมิลเลเนียมมองว่าอุบัติเหตุที่เกิดขึ้นในพิธีเปิดเป็นแค่ปัญหาเล็กๆ งั้นเหรอคะ?"
10016010-14 = "ระ... เรื่องนั้น คือว่า..."
10016010-15 = "ตัวแทนนักเรียนจากทรีนิตี้พูดแบบนั้นออกมาในที่สาธารณะและทำลายความศักดิ์สิทธิ์ของงานฮาโล#nเฟสติวัล แบบนี้จะปล่อยไปเฉยๆ ไม่ได้นะคะ"
10016010-16 = "ฉันคิดว่าไม่ว่ายังไงเรื่องนี้ทางโรงเรียนทรีนิตี้ก็ต้องรับผิดชอบค่ะ"
10016010-17 = "....."
10016010-18 = "ตะ... ตะ... ต้องขออภัยด้วยค่ะ"
10016010-19 = "ทางพวกเรา <ชมรมซิสเตอร์> ก็ไม่คิดมาก่อนว่าเธอจะพูดอะไรแบบนั้นค่ะ..."
10016010-20 = "มะ... ไม่สิ ที่จริงก็เคยคิดแบบนั้นอยู่บ้าง... แต่ก็ไม่คิดเลย... ไม่คิดว่าเธอจะทำถึงขนาดนี้..."
10016010-21 = "คาดเอาไว้แล้วสินะ..."
10016010-22 = "ฮุฮุ พอเกิดเรื่องแบบนี้ขึ้นแล้ว ทางทรีนิตี้ถอนตัวจากการเป็นคณะกรรมการจัดงานไปไม่ดีกว่าเหรอคะ?"
10016010-23 = "เดี๋ยวคนของคณะกรรมการวินัยจะช่วยเติมที่ว่างตรงนั้นให้เองค่ะ"
10016010-24 = "คะ?! จะเพิ่มนักเรียนของเกเฮนน่าเข้ามาอีกเหรอคะ?"
10016010-25 = "คุณตั้งใจจะทำลายการแข่งขันนี้เหรอคะ เจ้าหน้าที่อาวุโส?"
10016010-26 = "ก็มันดูเหมือนกับว่างานกำลังจะพังไม่เป็นท่าเพราะโรงเรียนบางโรงเรียนอยู่แล้วไม่ใช่เหรอคะ?"
10016010-27 = "คือว่า... ทะ...ทุกคนใจเย็นๆ ก่อนเถอะนะคะ!"
10016010-28 = "<ฮาโลเฟสติวัล> เป็นเทศกาลแห่งสันติภาพที่จัดการแข่งขันอย่างโปร่งใสให้นักเรียนได้ร่วมมือกัน โดยที่ไม่แบ่งแยกสถาบันไม่ใช่เหรอคะ?"
10016010-29 = "แต่ถ้านักเรียนคนอื่นมารู้ว่าทุกคนทะเลาะกันตั้งแต่การแข่งขันยังไม่เริ่มแบบนี้..."
10016010-30 = "ทุกคนคงจะผิดหวังแน่ๆ ค่ะ!"
10016010-31 = "...เอาเป็นว่า เข้าใจแล้วค่ะ"
10016010-32 = "อันที่จริงอาจจะมีนักเรียนไม่น้อยเลยนะคะ ที่รู้สึกสนุกมากกว่าผิดหวัง ถ้ามารู้ว่าคณะกรรมการจัดงาน#nกำลังทะเลาะกันอยู่น่ะค่ะ"
10016010-33 = ""
10016010-35 = ""
10016010-36 = "ขอบคุณที่ช่วยห้ามเอาไว้นะ เธอคืออิโอจิใช่มั้ย? ช่วยไว้ได้เยอะเลย"
10016010-37 = "มะ...ไม่หรอกค่ะ ทางเราเองก็เป็นฝ่ายที่ทำให้เกิดเรื่องเสียหาย ขอโทษจริงๆ ค่ะ..."
10016010-38 = "แล้วอีกอย่างไม่ต้องพูดเป็นทางการขนาดนั้นก็ได้ค่ะ เรียกฉันว่ามารีก็พอแล้วละค่ะ!"
10016010-39 = "(พอจะเข้าใจแล้วว่าทำไมทางทรีนิตี้ถึงต้องส่งเด็กคนนี้มาเป็นคณะกรรมการจัดงานอีกคนหนึ่ง...)"
10016010-45 = "...ด้วยเหตุผลที่ว่ามา เราเลยปรับรายการแข่งขันบางส่วน และเมื่อพิจารณาเวลาในการเตรียมการแล้ว ก็เลยจัดลำดับการแข่งขันใหม่ตามในเอกสารน่ะ"
10016010-46 = "ฉันทราบดีว่าเป็นการเปลี่ยนแปลงที่เร่งด่วน แต่ว่าถ้าทุกโรงเรียนไม่มีใครแย้งอะไร ก็คงจะไม่มีปัญหา#nอะไรกัน..."
10016010-47 = "นักเรียนคนไหนมีคำถามอีกรึเปล่า?"
10016010-48 = "[s] \"ครูขอถามอะไรหน่อยได้มั้ย?\""
10016010-49 = "ค่ะ ถึงจะไม่ใช่นักเรียนก็เถอะค่ะ... คุณครู [USERNAME] จากชาเล่ต์"
10016010-50 = "คุณครูสงสัยเรื่องไหนเหรอคะ?"
10016010-51 = "[s1] \"มิลเลเนียมเป็นเจ้าภาพจัดงานฮาโลเฟสติวัลไม่ใช่เหรอ...\"\n[s2] \"ให้นักเรียนจากที่อื่นทำหน้าที่เป็นคณะกรรมการจัดงานได้ด้วยเหรอ?\""
10016010-52 = "ใช่ค่ะ การแข่งกีฬาใน <ฮาโลเฟสติวัล> จะต้องดำเนินการอย่างยุติธรรมและไม่เอื้อประโยชน์ให้#nโรงเรียนใดโรงเรียนหนึ่ง เลยต้องมีสมาชิกจากโรงเรียนอื่นด้วยค่ะ"
10016010-53 = "ใช่ค่ะ การแข่งกีฬาใน <ฮาโลเฟสติวัล> จะต้องดำเนินการอย่างยุติธรรมและไม่เอื้อประโยชน์ให้#nโรงเรียนใดโรงเรียนหนึ่ง เลยต้องมีสมาชิกจากโรงเรียนอื่นด้วยค่ะ"
10016010-54 = "ถ้าหากให้ทางเจ้าภาพเป็นคนจัดการการแข่งขัน ก็อาจจะเกิดการทุจริตขึ้นได้ง่ายแล้วก็อาจจะเกิดการ#nต่อต้านจากนักกีฬาได้ค่ะ ดังนั้นคณะกรรมการจัดงานจึงประกอบด้วยนักเรียนจากหลายโรงเรียน ไม่ใช่#nแค่โรงเรียนที่เป็นเจ้าภาพจัดงานค่ะ"
10016010-55 = "ยิ่งรวมตัวนักเรียนจากหลากหลายโรงเรียนมากเท่าไร คณะกรรมการจัดงานก็จะรับมือปัญหาได้มี#nประสิทธิภาพมากขึ้น ในกรณีที่มีนักเรียนก่อปัญหาที่ส่งผลกระทบต่อการแข่งขันกีฬาก็จะให้ผู้รับผิดชอบ#nของโรงเรียนนั้นๆ จัดการค่ะ"
10016010-56 = "เพราะแบบนั้นก็เลยมีธรรมเนียมที่ให้สภานักเรียนของแต่ละโรงเรียนมารับหน้าที่เป็นคณะกรรมการจัด#nงานฮาโลเฟสติวัลค่ะ..."
10016010-57 = ""
10016010-58 = "...จะว่าไปแล้วทำไมครั้งนี้ <แพนเดโมเนียม โซไซตี้> กับ <สภาน้ำชา> ถึงไม่มาร่วมงานล่ะ?"
10016010-59 = "ก็นั่นน่ะสิคะ ในฐานะคณะกรรมการวินัยแล้ว พวกเราก็อยากจะเรียกร้องความยุติธรรมด้วยค่ะ"
10016010-60 = "พวกตัวแสบแห่ง <แพนเดโมเนียม โซไซตี้>... ไม่สิ ประธานมาโคโตะปฏิเสธที่จะเข้าร่วมงานด้วยเหตุผล#nดังนี้ค่ะ"
10016010-62 = "จะให้เสาหลักแห่งเกเฮนน่าอย่างแพนเดโมเนียม โซไซตี้ไปทำหน้าที่คณะกรรมการจัดงานที่คอยตาม#nจัดการพวกนักเรียนธรรมดาอย่างนั้นน่ะเหรอ?"
10016010-63 = "ท่านมาโคโตะผู้นี้ไม่มีทางไปทำงานน่ารำคาญแบบนั้นด้วยตัวเองหรอก! ขอปฏิเสธ!"
10016010-64 = "ให้คณะกรรมการวินัยรับผิดชอบเรื่องการจัดการทั้งหมดไปสิ! หึหึหึ!"
10016010-65 = ""
10016010-66 = "...ถ้างั้นแล้วพวกโฮสต์ของสภาน้ำชาล่ะ?"
10016010-67 = "คุณนางิสะที่เป็นโฮสต์ของสภาน้ำชาคนปัจจุบันได้ฝากคำทักทายและแสดงความยินดีมาดังนี้ค่ะ"
10016010-69 = "ฉันรู้สึกเสียใจมากที่ไม่สามารถเข้าร่วม <ฮาโลเฟสติวัล> ได้เนื่องจากภาระงานที่ยุ่งมากค่ะ"
10016010-70 = "และขอฝากคุณฮาสุมินำชาแดงชั้นดีและคำขอโทษจากฉันไปส่งให้ด้วยนะคะ"
10016010-71 = "ถ้าอย่างนั้น... ฉันจะช่วยภาวนาให้งาน <ฮาโลเฟสติวัล> สำเร็จไปได้ด้วยดีนะคะ"
10016010-72 = ""
10016010-73 = "อะไรกันคะนั่น ก็เหมือนกับพูดว่าน่ารำคาญก็เลยมาไม่ได้แค่นั้นเองนี่คะ"
10016010-74 = "ต้องขอโทษด้วยนะคะ แต่ว่าโฮสต์ของสภาน้ำชาน่ะ แค่นั่งอยู่เฉยๆ ก็มีภาระหน้าที่ที่ต้องรับผิดชอบเต็ม#nไปหมดแล้วละค่ะ"
10016010-75 = "คุณนางิสะจะต้องรู้สึกเสียดายอย่างสุดซึ้งแน่นอนค่ะ ที่ต้องปฏิเสธการเข้าร่วมฮาโลเฟสติวัลครั้งนี้"
10016010-76 = "ถ้าจะว่าอย่างนั้น ทางแพนเดโมเนียม โซไซตี้ก็มีงานเยอะแยะ..."
10016010-77 = "เฮ้อ... ฉันคงแก้ต่างให้พวกตัวแสบนั่นไม่ได้จริงๆ ค่ะ"
10016010-78 = "คงปัดงานสำคัญไปให้ท่านประธานฮินะแล้วก็ใช้เวลาไปวางแผนอะไรไร้สาระอยู่แน่ๆ"
10016010-79 = "แต่จะว่าไปแล้ว ชาที่พวกเราดื่มกันอยู่นี่ก็เป็นชาแดงที่สภาน้ำชาให้มางั้นเหรอคะ?"
10016010-80 = "อย่าบอกนะว่า... จะส่งใบเสร็จมาเรียกเก็บเงินแพงหูฉี่ทีหลัง คงไม่ทำแบบนั้นใช่มั้ยคะ?"
10016010-81 = "ไม่ต้องกังวลค่ะ ทางเราได้เตรียมชาแดงที่ถูกที่สุดจากร้านสะดวกซื้อแถวนี้มาเป็นพิเศษเพื่อนักเรียน#nของเกเฮนน่าโดยเฉพาะเลยค่ะ"
10016010-82 = "ตายจริง ต้องขอบคุณสินะคะที่ไม่เอาน้ำประปามาให้ดื่ม"
10016010-83 = "เอ่อ คือว่า... ช่วยคุยกันอย่างนุ่มนวลกว่านี้..."
10016010-84 = ""
10016010-86 = ""
10016010-87 = "...พอจะเข้าใจเหตุผลที่สมาชิกสภานักเรียนของเกเฮนน่ากับทรีนิตี้ไม่มาเข้าร่วมแล้วละ"
10016010-88 = "แต่ว่า..."
10016010-89 = "อย่างน้อยหัวหน้าคณะกรรมการวินัยกับหัวหน้าชมรมทวงความยุติธรรมก็ควรจะมาไม่ใช่เหรอ?!"
10016010-90 = "ทุกคนก็รู้กันดีนี่ว่าในเกเฮนน่ากับทรีนิตี้มีแค่หัวหน้าสองคนนี้เท่านั้นที่แค่หายใจเข้าออกก็ปราบพวก#nเด็กเกเรได้อยู่หมัดน่ะ..."
10016010-91 = "เรื่องนั้น... พอดีว่าท่านประธานฮินะได้รับมอบหมายงานอื่นไปแล้ว..."
10016010-92 = "งานอื่นหมายถึง..?"
10016010-93 = "อย่างที่สุภาษิตขี่ช้างจับตั๊กแตนสอนไว้ เราไม่ควรจะลงแรงมากเกินไปกับงานเล็กๆ นั่นแหละค่ะ"
10016010-94 = "ถึงซึรุกิจะเป็นหัวหน้าชมรมทวงความยุติธรรม แต่หน้าที่การจัดการภายนอก ปกติฉันเป็นคนรับผิดชอบ#nอยู่แล้วค่ะ"
10016010-95 = "แล้วอีกอย่างถ้าให้ซึรุกิมาเป็นคณะกรรมการจัดงาน จำนวนการแข่งขันที่สามารถเข้าร่วมได้ก็อาจจะลดน้อยลง..."
10016010-96 = "อ่า..."
10016010-97 = "นั่นก็หมายความว่า......."
10016010-98 = "เพื่อที่จะสร้างสถิติดีๆ ในงานมหกรรมแข่งขันกีฬา เหล่าหัวหน้าที่สามารถเป็นกำลังของแต่ละโรงเรียนก็#nจะต้องไปเป็นนักกีฬา แล้วก็ให้ 'คนที่ไม่เก่งกีฬา' มาเป็นคณะกรรมการจัดงานสินะ...?"
10016010-100 = "คะ... คนที่ไม่เก่งกีฬาเหรอคะ? พูดเกินไปแล้วนะคะ!"
10016010-101 = "ถึงฉันจะไม่ใช่คนที่ชอบกีฬามากนัก แต่ในฐานะรองหัวหน้าชมรมทวงความยุติธรรม ฉันเองก็แข็งแรง#nอยู่พอตัวค่ะ"
10016010-102 = "อ่า แน่นอนว่าที่เกเฮนน่าก็มีนักกีฬาที่เก่งกาจมากๆ เยอะอยู่แล้ว ฉันก็เลยไม่มีความคิดที่จะต้องไปลง#nแข่งด้วยตัวเองค่ะ"
10016010-103 = "ฉันก็คิดแบบนั้นเหมือนกันค่ะ ถ้าเราให้นักกีฬาที่มีความสามารถลงแข่งก็จะมีโอกาสในการไปคว้า#nชัยชนะมามากกว่าไงคะ"
10016010-104 = ""
10016010-106 = ""
10016010-107 = "ทุกคนเนี่ย... ทำเกินไปรึเปล่าน่ะ?!"
10016010-108 = "ฉันเข้าใจดีที่โรงเรียนจะมองว่าชัยชนะเป็นเรื่องสำคัญ แต่ถึงขั้นไม่เห็นความสำคัญของงานมหกรรม#nแข่งขันกีฬาแล้วสนใจแต่โรงเรียนตัวเองแบบนี้ได้ยังไงน่ะ!"
10016010-109 = "โรงเรียนมิลเลเนียมของพวกเราก็ชอบการเอาชนะเหมือนกันนะ?!"
10016010-111 = "ไม่ใช่ว่านักเรียนของมิลเลเนียมไม่สนใจเรื่องชัยชนะในการแข่งกีฬากันหรอกเหรอคะ?"
10016010-112 = "จริงด้วยค่ะ ตอนแข่งเบสบอลชิงแชมป์ทั่วประเทศก็ไม่ติดอันดับ แล้วยังเป็นที่รู้จักเรื่องความแปลก#nมากกว่าเรื่องการแข่งขันด้วย..."
10016010-114 = "ระ... เรื่องนั้นมันก็จริงอยู่..."
10016010-115 = "แต่ว่าฮาโลเฟสติวัลครั้งนี้ โรงเรียนมิลเลเนียมของเรารับหน้าที่เป็นเจ้าภาพ เพราะงั้นเราจะทำให้เต็มที่!"
10016010-116 = "พวกเราจะแสดงให้เห็นถึงการคว้าชัยชนะที่เปี่ยมไปด้วยความหมายและได้มาด้วยการวิเคราะห์เชิง#nวิทยาศาสตร์และการฝึกฝน!"
10016010-117 = ""
10016010-119 = ""
10016010-120 = ""
10016010-121 = ""
10016010-122 = ""
10016010-124 = "รู้สึกว่า... บรรยากาศจะเลวร้ายกว่าที่คิดนะคะ"
10016010-125 = "ฉันมาเข้าร่วมงานนี้ก็เพราะอยากจะช่วยสนับสนุนสันติภาพในคิโวทอส ทำไมมันถึงกลายเป็นเรื่องแบบ#nนี้ไปได้..."
10016010-126 = "[s3] \"ทุกคนดูมีชีวิตชีวาก็ดีแล้วไม่ใช่เหรอ?\"\n[s4] \"ก่อนการแข่งขันก็ต้องมาฝึกความแข็งแกร่งของจิตใจแบบนี้ละ\""
10016010-127 = "ถ้าคุณครูว่าอย่างนั้นก็คงจะไม่เป็นไรนั่นละค่ะ..."
10016010-128 = "ถ้าคุณครูว่าอย่างนั้นก็คงจะไม่เป็นไรนั่นละค่ะ..."
10016010-129 = ""
10016010-131 = ""
10016010-132 = "อีกอย่าง เสื้อคลุมที่เน้นหน้าอกหน้าใจนั่นมันอะไรกันคะ? นักเรียนจากทรีนิตี้ไม่มีกฏการใส่ชุดกีฬาให้#nถูกระเบียบเหรอคะ?"
10016010-133 = "คือว่า... ฉันก็พยายามจะรูดซิบขึ้นมาแล้ว แต่มันรูดไม่ได้จริงๆ..."
10016010-134 = "ยิ่งไปกว่านั้น นี่คุณอยู่ในฐานะที่จะมาตำหนิคนอื่นเรื่องการแต่งตัวเหรอคะ?!"
10016010-135 = "ขอภาวนาให้งานมหกรรมแข่งขันกีฬาดำเนินไปอย่างราบรื่นด้วยเถอะค่ะ..."
