[translation]
1001505-1 = "Aris' Choice"
1001505-2 = ""
1001505-3 = "Aris was sitting in a corner of the cafe, tapping at her phone."
1001505-4 = "She was so focused on the screen that she didn't notice me approaching."
1001505-5 = "[s1] \"Hi, Aris.\"\n[s2] \"Are you playing a game?\""
1001505-6 = ""
1001505-7 = ""
1001505-8 = "Good morning, Sensei."
1001505-9 = "This game has been popular with other students lately, but it is quite difficult. I do not know what to choose."
1001505-10 = "It is forcing me to make such tough decisions... What a difficult game."
1001505-11 = "[s3] \"What kind of game is it?\"\n[s4] \"What kind of decisions do you have to make?\""
1001505-12 = "The main character is the second prince of the Chromati Kingdom. He is also known as Prince Chest Hair."
1001505-13 = "The main character is the second prince of the Chromati Kingdom. He is also known as Prince Chest Hair."
1001505-14 = "[s] \"You don't say...\""
1001505-15 = "His signature chest hair is supposedly the most attractive quality in the kingdom."
1001505-16 = "[s] \"Interesting...\""
1001505-17 = "All the kings from the neighboring kingdoms are competing to get their hands on the prince..."
1001505-18 = "...and now it is down to the Bearded King and the Bald Emperor."
1001505-19 = "Should Prince Chest Hair choose the Bearded King or Bald Emperor? Which one will make him happy?"
1001505-20 = "Both seem to be good choices, so it is a very hard decision to make."
1001505-21 = "[s5] \"Right...\"\n[s6] \"I can see why this is difficult.\""
1001505-22 = "The Bearded King loves running through the streets naked, so he and the prince share the same hobby."
1001505-23 = "The Bearded King loves running through the streets naked, so he and the prince share the same hobby."
1001505-24 = "But the Bald Emperor is one of the best-looking men in the world. He has won the Beefcake Festival several times and helps the prince train his pecs, making his chest hair shine even more."
1001505-25 = "[s7] \"Where did you find this game again...?\"\n[s8] \"Sounds like a Game of the Year contender.\""
1001505-26 = "Both of them are a great match for the prince...so how am I supposed to decide? It is too hard."
1001505-27 = "Both of them are a great match for the prince...so how am I supposed to decide? It is too hard."
1001505-28 = "[s9] \"I think this is up to you to decide.\"\n[s10] \"Just know I support you in whatever decision you make.\""
1001505-29 = ""
1001505-30 = ""
1001505-31 = "Thank you, Sensei. I know I have to make a decision."
1001505-32 = "Chest hair or naked sprinting?"
1001505-33 = "Bearded or bald?"
1001505-34 = "[s11] \"Game of the Year. In the bag.\"\n[s12] \"I hope she can handle this...\""
1001505-38 = "Aris spent a long time thoughtfully reading through various strategy forums."
1001505-39 = ""
1001505-40 = ""
1001505-41 = ""
1001505-42 = "Eureka!"
1001505-43 = "I would like to return to the academy to test something."
1001505-44 = ""
1001505-45 = "After that, Aris returned to the academy with a smile on her face."
