[translation]
10019070-9 = "#na;히후미;아즈사 쨩…… 저희가 보고 있는 게…… 그, 그게 맞죠……?"
10019070-10 = "#na;아즈사;응. 틀림없어. 저건……."
10019070-11 = "#zmc;instant;100,322;2200\n#na;히후미&아즈사;페로로지라……!!\n#fontsize;100"
10019070-13 = "3;아즈사;04;히후미, 페로로지라가 우리들의 가슴 속에 살아 있다는 게 이런 뜻이었어?\n#3;em;…\n#3;a"
10019070-14 = "3;히후미;04;네? 아, 아뇨. 그런 뜻은 아니었는데…….\n#3;em;[땀]\n#3;stiff\n#3;a"
10019070-15 = "#st;[0,0];instant;1;"
10019070-19 = "#zmc;instant;750,300;1800\n#na;하루나;저희도 확인했습니다. 거대 괴수가 D.U. 시라토리구에 상륙했습니다."
10019070-20 = "#zmc;instant;750,300;1800\n#st;[0,0];instant;1;"
10019070-26 = "#na;준코;우와아-!? 저게 뭐야?!"
10019070-27 = "#na;이즈미;굉장해-!! 눈에서 빔이 나가!!"
10019070-28 = "#na;아카리;일단 저쪽으로 접근해 볼 테니까, 다들 꽉 잡으세요!"
10019070-29 = "#na;하루나;대응 가능한 인원들을 최대한 모아서 저지해 보겠습니다."
10019070-31 = "3;히후미;06;저, 저희도 그쪽으로 합류할게요! 아즈사 쨩, 꽉 잡으세요!\n#3;sig\n#3;a"
10019070-32 = "3;아즈사;02;응!\n#3;sig\n#3;em;[반응]"
10019070-33 = "#st;[0,0];instant;1;"
