[translation]
1001615-1 = "#title;……떨어지지 않는 추억이네요, 선생님."
1001615-6 = "#na;(그렇게 미도리와 함께…….)"
1001615-7 = "#na;(몬스터 사냥 게임에 열을 올리고 있었던 참이었다!)"
1001615-8 = "#st;[0,0];instant;1;"
1001615-10 = "3;미도리;07\n#3;a\n#3;stiff\n#wait;1000"
1001615-11 = "3;미도리;07\n#3;stiff\n#wait;1000"
1001615-12 = "3;미도리;05;선생님, 됐어요! 그로기 터졌어요! 이제 약점 공격만……!\n#3;em;[!]"
1001615-13 = "#st;[0,0];instant;1;"
1001615-17 = "3;미도리;04;어어어?!\n#3;em;[?!]\n#3;shake"
1001615-18 = "[ns] \"미도리? 너 지금 튕겼는데?!\""
1001615-19 = "3;미도리;04;알아요! 게임기가 꺼져 버렸는데요……?\n#3;em;…"
1001615-21 = "#na;(어떻게 해도 게임기가 다시 켜지지 않아, 결국 수리 센터를 찾아가기로 했다…….)"
1001615-23 = "1;미도리;01\n#1;a\n#1;greeting\n#wait;1000"
1001615-25 = "1;미도리;01\n#na;수리 센터 직원;으음……. 이거 좀 어렵겠는데요? 이 게임기, 워낙 옛날 기종이라……."
1001615-26 = "1;미도리;01\n#na;수리 센터 직원;단종된 구식 부품도 좀 있고, 어떤 건 아예 새로 바꿔야 할 것 같은데, 그게 잘 호환될지도 모르겠고……."
1001615-27 = "1;미도리;08;안 되나요……?\n#1;em;…"
1001615-28 = "1;미도리;08\n#na;수리 센터 직원;일단 재고가 있는지 본사에 알아보겠습니다. 잠시만 기다려 주세요."
1001615-29 = "1;미도리;10;부탁드리겠습니다…….\n#1;greeting"
1001615-30 = "#st;[0,0];instant;1;"
1001615-34 = "[ns] \"아쉽네……. 거의 다 잡았는데…….\""
1001615-35 = "1;미도리;07;그러게요. 이번에야말로 사냥 성공일 줄 알았는데요.\n#1;m3\n#1;em;[세로선]"
1001615-36 = "1;미도리;05;무엇보다, 간만에 선생님과 단둘이서만 있을 수 있었던 기회였는데…….\n#fontsize;50"
1001615-37 = "#st;[0,0];instant;1;"
1001615-39 = "1;미도리;99\n#1;em;[한숨]\n#wait;1500"
1001615-42 = "3;미도리;02\n#3;a\n#3;em;[!]\n#wait;1000"
1001615-43 = "3;미도리;02\n#na;수리 센터 직원;오래 기다리셨습니다. 그런데…… 본사에서도 이 부품은 구하기 어렵다고 하네요……."
1001615-44 = "3;미도리;04;그, 그런가요?!\n#3;em;[?!]\n#3;shake"
1001615-45 = "3;미도리;04\n#na;수리 센터 직원;괜찮으시면 새로 구입하시는 게 어떨까요?"
1001615-46 = "3;미도리;08;그렇, 지만……."
1001615-47 = "#st;[0,0];instant;1;"
1001615-49 = "3;미도리;06\n#3;em;…\n#wait;2500"
1001615-50 = "3;미도리;10;어떻게 해도, 안 될까요……? 중고 샵에서 부품을 구한다든가…….\n#3;em;[훌쩍]\n#3;hophop"
1001615-51 = "3;미도리;10\n#na;수리 센터 직원;으으, 일단 저희는 직영점이고, 그런 식의 '허가되지 않은 개조'에 속하는 수리는, 지양하고 있습니다, 손님……."
1001615-52 = "3;미도리;10\n#na;수리 센터 직원;만에 하나 그렇게 수리하려다가 데이터가 손상되기라도 하면, 그때는 더더욱 돌이킬 수 없고요……."
1001615-53 = "3;미도리;04;데, 데이터 손상이요?! 그건 더 안 돼요!\n#3;em;[?!]\n#3;shake"
1001615-54 = "3;미도리;04\n#na;수리 센터 직원;이렇게 하시는 건 어떨까요?"
1001615-55 = "3;미도리;04\n#na;수리 센터 직원;마침 지금 새 기종이 할인 중입니다만, 여기에서 구입하신다면 데이터 이전을 서비스로 해 드리겠습니다."
1001615-56 = "3;미도리;07;……."
1001615-57 = "[ns] \"…….\""
1001615-58 = "3;미도리;07;……이럴 때는, 어쩔 수 없겠죠……?"
1001615-59 = "3;미도리;99;알겠어요. 그렇게 할게요.\n#3;em;[한숨]"
1001615-60 = "3;미도리;07;대금 청구는, 밀레니엄 사이언스 스쿨 게임개발부 앞으로 돌려주세요."
1001615-61 = "3;미도리;05;괜찮겠냐고요? 이거야말로 정당한 부 활동비 청구라고요! 세미나도 양해해 줄 거예요! 그래야만 해요!\n#3;em;[!]"
1001615-62 = "3;미도리;05\n#na;수리 센터 직원;그러면 금방 준비해 드리겠습니다. 데이터 이전까지는 시간이 조금 걸릴 테니, 조금만 더 기다려 주세요."
1001615-63 = "3;미도리;02;네…… 잘 부탁드릴게요.\n#3;greeting"
1001615-64 = "#st;[0,0];instant;1;"
1001615-66 = "3;미도리;07\n#3;em;[속상함]\n#wait;1200"
1001615-67 = "[ns] \"혹시 그 게임기, 모모이와 같이 산 거니?\""
1001615-68 = "3;미도리;02;네? 어, 어떻게 아셨어요?!\n#3;em;[반응]"
1001615-69 = "[s] \"왠지 모르게 말이지…….\""
1001615-70 = "3;미도리;01;네…… 생각해 보니 제가 좀 티 나게 행동하긴 했네요……."
1001615-71 = "3;미도리;99;선생님 말씀대로예요. 언니와 같은 때에 구입한 거죠.\n#3;em;[한숨]"
1001615-72 = "3;미도리;02;언니는 하도 게임을 해 대서 먼저 고장 났지만, 저는 아직까지 어떻게든 쓰고 있었어요."
1001615-73 = "3;미도리;07;……그렇지만 이런 결말이네요……."
1001615-74 = "#st;[0,0];instant;1;"
1001615-77 = "3;미도리;99;너무 그런 표정 하지 마세요. 사실 별것 아니에요. 오히려 당연한 일이죠. 게임기는 소모품이니까요."
1001615-78 = "3;미도리;05;……소모품치고는 좀 비싸서 억울할 때도 있긴 한데, 아무튼요.\n#3;em;[빠직]"
1001615-79 = "3;미도리;07;심지어 이 게임기, 언니가 아끼고 아껴서 먼저 사 준 거예요."
1001615-80 = "3;미도리;07;……저를, 타락시키려고요."
1001615-81 = "#st;[0,0];instant;1;"
1001615-84 = "[ns] \"타, 타락이라니?!\""
1001615-85 = "3;미도리;05;하지만 그렇게밖에 말할 수가 없는걸요!\n#3;em;[!]"
1001615-86 = "3;미도리;07;저는 애초에 게임 그렇게 안 좋아했다구요. 지금은 이런 꼴이지만요……."
1001615-87 = "3;미도리;05;그래도 언니보단 제가 게임을 조금 덜 하니까, 제가 이긴 거예요! 아무튼 그래요!"
1001615-88 = "3;미도리;05;게임으로 승부할 때도, 제가 조금 더 많이 이기니까 제 승리예요!\n#3;hophop\n#3;em;[스팀]"
1001615-89 = "[s] \"그래, 그래…….\""
1001615-90 = "#st;[0,0];instant;1;"
1001615-92 = "3;미도리;07\n#3;em;…\n#wait;2500"
1001615-93 = "3;미도리;99;……하지만, 역시 언니가 대단하다고 생각하기도 해요. 어떻게 그렇게 에너지가 넘치는 걸까요……."
1001615-94 = "3;미도리;01;언제나 도전하고, 새로운 걸 찾아가고, 그걸 자기 이야기 안에 녹여내려고 하고……."
1001615-95 = "3;미도리;02;창작자로서는, 그건 정말 엄청난 자세가 아닐까요."
1001615-96 = "3;미도리;05;그러다가 항상 사고를 치고, 거기에 꼭 저를 말려들어 가게 하는 건 좀 그렇긴 한데요!\n#3;em;[빠직]"
1001615-97 = "3;미도리;07;……그래도, 게임에 너무 부러움을 느끼다가, 무의식적으로 게임을 멀리하려고 했던 저보다는……."
1001615-98 = "[s] \"게임에, 부러움을?\""
1001615-99 = "3;미도리;99;네."
1001615-100 = "3;미도리;01;뭐라고 해야 할까요…….\n#3;em;…"
1001615-101 = "3;미도리;02;요즘 예쁜 일러스트는, 거의 게임에 있잖아요?"
1001615-102 = "3;미도리;07;안 그러려고 해도, 비교하게 된단 말이죠. 프로의 그림들과 제 그림을요……."
1001615-103 = "3;미도리;07;그때는 지금보다 못 그렸으니까, 더 많이 그랬고요."
1001615-104 = "[s1] \"아하, 그런 문제인가…….\"\n[s2] \"원래 어중간할 때가 제일 힘들더라.\""
1001615-107 = "3;미도리;99;맞아요."
1001615-108 = "3;미도리;05;문제를 일으키는 것들은, 언제나 어중간한 것들이라고, 저는 단언할 수 있어요!\n#3;em;[!]"
1001615-109 = "3;미도리;02;……하지만, 언니는 그런 사람이 아니었어요."
1001615-110 = "3;미도리;99;좋은 것을 순수하게 좋다고 이야기하고, 싫은 것은 신경 쓰지 않는 사람이죠."
1001615-111 = "3;미도리;99;세상에는 아직도 좋은 게 너무 많이 있으니까, 그걸 좋아하기에도 인생은 모자란다던가요."
1001615-112 = "3;미도리;02;죄, 죄송해요. 선생님! 옛날 게임기를 보다 보니, 저 혼자만 너무 많이 이야기를 했네요…….\n#3;em;[반응]"
1001615-113 = "[s] \"괜찮아. 미도리의 이야기, 재미있었어.\""
1001615-114 = "3;미도리;01;그, 그러셨나요?\n#3;em;[///]"
1001615-115 = "3;미도리;03;다행이네요……."
1001615-118 = "#na;수리 센터 직원;오래 기다리셨습니다! 데이터 이전 완료되었습니다! 여기 손님의 이전 게임기와, 새로 포장한 새 모델의 게임기입니다!"
1001615-119 = "#st;[0,0];instant;1;"
1001615-122 = "1;미도리;02;네. 감사합니다.\n#1;a\n#1;greeting"
1001615-123 = "1;미도리;02;그런데……. 이건, 어떻게 해야 할까요?\n#1;m3\n#1;em;…"
1001615-124 = "[s3] \"이 게임기 말인데, 거치대랑 투명 찬장을 사서…….\"\n[s4] \"기념품으로 쭉 보관하자!\""
1001615-127 = "1;미도리;01;네? 그, 그렇게까지는…….\n#1;em;[?]"
1001615-128 = "1;미도리;01;그래도 나름 추억의 물건 아니냐고요?"
1001615-129 = "1;미도리;02;그건, 그렇긴 한데요……."
1001615-130 = "1;미도리;04;선생님께서 주시겠다고요?!?!\n#1;shake\n#1;em;[?!]"
1001615-131 = "1;미도리;04;아아아아아아뇨 그건 안 돼요 거기까지 신세를 질 수는……."
1001615-132 = "1;미도리;02;네에? 마침 남는 게 있으니까 괜찮다고요?\n#1;em;[?]"
1001615-133 = "1;미도리;01;……."
1001615-134 = "1;미도리;04;도대체 어떤 부러운 생활을 하시길래, 그런 게 남으시는 건가요?!?!\n#1;hophop"
1001615-135 = "[s] \"어른에게도 게임 할 권리를 허가하라–!\""
1001615-136 = "1;미도리;04;마음 약해지게 그런 말씀을 하시면 저도 어쩔 수가 없잖아요!?!?\n#1;hophop"
1001615-137 = "1;미도리;07;…….\n#1;em;…"
1001615-138 = "1;미도리;02;있잖아요, 선생님. 사실은……."
1001615-139 = "1;미도리;01;언니가 이미, 그런 식으로 이 게임기를 보관하고 있기도 했어요."
1001615-140 = "1;미도리;02;그러니까 저도 그렇게 하는 게 맞았겠지만……."
1001615-141 = "1;미도리;07;……뭔가, 따라 하면 지는 기분도 조금 들었거든요……."
1001615-142 = "[s] \"아, 그 기분 알지…….\""
1001615-143 = "1;미도리;03;알아주셔서 감사합니다……."
1001615-144 = "1;미도리;99;저는 말이죠. 그 이론 믿고 있어요."
1001615-145 = "1;미도리;05;자매는 서로 싸우라고 태어날 때부터 프로그램되어 있다는 이야기 말이에요!\n#1;em;[!]"
1001615-146 = "[s] \"서로 너무 많이 싸우지는 말고…….\""
1001615-147 = "1;미도리;05;괜찮아요!"
1001615-148 = "1;미도리;03;게임 대전하면 제가 더 많이 이기니까요!"
1001615-150 = "#na;(미도리와 함께 돌아와서, 게임 수렵을 이어서 진행했다.)"
1001615-151 = "#na;(이번에는 무리 없이 사냥에 성공할 수 있었다.)"
