[translation]
10010010-1 = "ตอนที่ 1;เปลี่ยนเป็นปฏิบัติการลับแล้วค่ะ..."
10010010-2 = ""
10010010-4 = ""
10010010-5 = "อืม..."
10010010-6 = "มาหาด้วยเหตุผลนี้เองสินะคะ... หนังสือนี้มัน..."
10010010-7 = "ไม่สิ ต้องเรียกว่า สิ่งที่ 'เคยเป็น' หนังสือมากกว่า..."
10010010-8 = "ฮือออ... ขอโทษค่ะ! ต้องขอโทษจริงๆ ค่ะ...! เป็นความผิดของฉันเอง...!"
10010010-9 = "ไม่หรอกค่ะคุณฮินาตะ... ฉันไม่ได้หมายความแบบนั้น..."
10010010-10 = "จะ... ใจเย็นๆ ก่อนนะคะ นี่ไม่ใช่เรื่องที่ต้องขอโทษฉันหรอกค่ะ! อีกอย่าง..."
10010010-11 = ""
10010010-13 = ""
10010010-15 = "ที่นี่คือห้องสมุดนะคะ... ช่วยพูดเบาๆ หน่อยค่ะ"
10010010-17 = "เอ่อ... ค่ะ..."
10010010-19 = "อืม... แต่ยังไงก็เป็นเรื่องใหญ่อยู่ดีค่ะ "
10010010-20 = "ถ้าเกิดเรื่องวุ่นวายขึ้นในงานใหญ่ที่คนสำคัญมากมายมาร่วมงานแบบนั้นจะทำยังไง..."
10010010-21 = ""
10010010-23 = ""
10010010-24 = "เอ๋? แล้วหีบไม้ล่ะคะ?"
10010010-25 = "ได้ยินมาว่ามีหีบไม้ที่ใส่พระคัมภีร์ด้วยไม่ใช่เหรอคะ? ไปอยู่ไหนแล้วล่ะคะ?"
10010010-26 = "คะ...? เอาไปไว้ในแท่นพิธีในวิหารที่จะจัดงานแล้วเหรอคะ?"
10010010-27 = "งั้นก็แปลว่าเป็นแค่หีบเปล่าสินะคะ?"
10010010-28 = "อ๋อ เอาหนังสืออื่นใส่เข้าไปให้ดูมีน้ำหนักแล้วสินะคะ"
10010010-29 = "อื้ม อย่างนี้นี่เองค่ะ เอาคัมภีร์กระบวน 108 ท่าลับพิชิตรักใส่ไว้แทน..."
10010010-30 = ""
10010010-32 = ""
10010010-33 = ""
10010010-34 = "เดี๋ยวนะคะ... เมื่อกี๊พูดว่าคัมภีร์อะไรนะคะ...?"
10010010-35 = "กระบวน 108 ท่าลับพิชิตรักเหรอคะ? ทำไมถึง... ทำไมถึงเป็นคัมภีร์กระบวนท่าลับล่ะคะ?"
10010010-36 = "[s] \"ก็ตอนนั้นพกหนังสือเล่มนั้นไว้พอดี...\""
10010010-37 = "คะ? เพราะตอนนั้นพกคัมภีร์กระบวนท่าลับไว้พอดี ก็เลยใส่ไว้แทนพระคัมภีร์งั้นเหรอคะ?!"
10010010-38 = "หนังสือมีตั้งมากมาย แล้วทำไมถึงพกคัมภีร์นั้นไว้ล่ะคะ? ฉันไม่รู้จะเริ่มจากตรงไหนเลยค่ะ!"
10010010-39 = "คะ? คุณครูยึดมาจากคุณฮานาโกะ... แล้วจะเอาไปคืนที่ห้องสมุดให้งั้นเหรอคะ...? "
10010010-40 = "[s1] \"ครูก็ยุ่งๆ น่ะ... ไม่รู้หรอกว่าเป็นหนังสืออะไร...\"\n[s2] \"ก็ถ้าหีบว่างเดี๋ยวคนอื่นจับได้... ครูก็เลย...\""
10010010-41 = "ถะ... ถ้างั้นก็ไปเปลี่ยนเป็นเล่มอื่นก่อนไม่ดีกว่าเหรอคะ..."
10010010-42 = "ถะ... ถ้างั้นก็ไปเปลี่ยนเป็นเล่มอื่นก่อนไม่ดีกว่าเหรอคะ..."
10010010-43 = ""
10010010-45 = ""
10010010-46 = "แต่ไม่ว่ายังไงก็ต้องมาแก้ไขปัญหาพระคัมภีร์อยู่ดีค่ะ..."
10010010-47 = "อืม... ค่ะ ฉันพอเข้าใจสถานการณ์แล้ว"
10010010-48 = ""
10010010-51 = "ถ้าไม่ <ฟื้นฟู> พระคัมภีร์ที่ขาดเป็นเศษเล็กเศษน้อยแล้วเอาไปไว้ในที่จัดงานละก็..."
10010010-52 = ""
10010010-58 = ""
10010010-59 = ""
10010010-60 = ""
10010010-61 = ""
10010010-62 = ""
10010010-63 = ""
10010010-66 = "คุณซากุระโกะก็จะได้อ่านคัมภีร์กระบวน 108 ท่าลับพิชิตรักต่อหน้าคนเป็นร้อยๆ..."
10010010-67 = "ใช่ค่ะ..."
10010010-69 = "จริงๆ มันก็ฟังดูน่าตื่นเต้นอยู่... แต่ฉันคงต้องช่วยไม่ให้มันเกิดเหตุการณ์นั้นขึ้นค่ะ..."
10010010-70 = "อืม... แต่ว่า... จะทำได้ไหมนะ..."
10010010-71 = ""
10010010-73 = ""
10010010-74 = ""
10010010-76 = "อืม... ขอโทษค่ะคุณครู เรื่องนี้น่าจะเกินความสามารถของฉันค่ะ"
10010010-77 = "จริงๆ บรรณารักษ์อย่างฉันก็สามารถซ่อมแซมหนังสือได้ แต่ก็แค่ใน 'ระดับหนึ่ง'"
10010010-78 = "ถ้ามันเสียหายขนาดนี้ละก็... ฉันคงช่วยให้ดีขึ้นไม่ได้มากค่ะ "
10010010-79 = "จะอธิบายยังไงดีล่ะ... ฉันก็พอซ่อมแซมได้อยู่ แต่นี่มันถึงระดับต้องฟื้นฟูเลย เพราะงั้นเราต้องพึ่ง 'ผู้เชี่ยวชาญตัวจริง' ค่ะ"
10010010-80 = "[s3] \"ไม่ใช่แค่ซ่อมแซม แต่เป็นการฟื้นฟูเหรอ?\"\n[s4] \"ผู้เชี่ยวชาญตัวจริง?\""
10010010-81 = "ค่ะ ถ้าเทียบกับแผล ซ่อมแซมคงเหมือนการทายาและแปะพลาสเตอร์ ส่วนฟื้นฟูคงเหมือนการผ่าตัดใหญ่...?"
10010010-82 = "ค่ะ ถ้าเทียบกับแผล ซ่อมแซมคงเหมือนการทายาและแปะพลาสเตอร์ ส่วนฟื้นฟูคงเหมือนการผ่าตัดใหญ่...?"
10010010-83 = "และหากจะผ่าตัดใหญ่ ก็จะต้องการ 'ผู้เชี่ยวชาญ' มากกว่าฉันใช่ไหมล่ะคะ?"
10010010-84 = ""
10010010-86 = ""
10010010-88 = "แถมหนังสือนี้ยังเป็นหนังสือเก่าแก่อีก... จะมองว่าเป็นวัตถุโบราณยังได้เลยค่ะ"
10010010-89 = "ถึงจะแปะหน้าที่ขาดแล้วจัดเรียงใหม่ให้ถูก แต่ยังไงคนที่ทำต้องมีความสามารถในการถอดความด้วย"
10010010-90 = ""
10010010-92 = "ในทรีนิตี้คงมีไม่กี่คนที่สามารถทำงานหินขนาดนี้ได้... ไม่สิ... ต้องบอกว่าในคิโวทอสมากกว่า"
10010010-93 = "ถะ... ถ้าอย่างนั้น... มันจะเกินกำลังของเราเหรอคะ? ไม่มีวิธีเลยเหรอคะ?!"
10010010-94 = "ฮืออ...!"
10010010-95 = "อะ...อ่า... คุณฮินาตะ"
10010010-96 = "คะ...?"
10010010-97 = ""
10010010-98 = "ชู่ว!"
10010010-100 = "ขอโทษค่ะ..."
10010010-101 = "[s5] \"นี่สินะเสน่ห์ของห้องสมุด\"\n[s6] \"คนอื่นเกือบรู้กันหมดแล้ว...\""
10010010-105 = "ฮู่วว..."
10010010-106 = "มันต้องมีทางออกค่ะ โชคดีที่ฉันพอรู้จักอยู่หนึ่งคน"
10010010-107 = "ถ้าไปหาเธอ บางทีเราอาจจะได้วิธีดีๆ มาก็ได้ค่ะ"
10010010-108 = "เธอเป็นคนเก่งมากกว่าที่คิด ฉันหมายถึง... ภายนอกดูไม่ใช่คนอย่างนั้นน่ะค่ะ"
10010010-109 = "[s7] \"ภายนอกดูไม่ใช่คนอย่างนั้น?\"\n[s8] (ชมหรือบูลลี่กันแน่นะ...?)"
10010010-110 = "เอาเถอะค่ะ เอาเป็นว่าเธอคนนี้เก่งกาจมากจนได้รับฉายาจากพวกเราว่าเป็น 'จอมเวทแห่งห้องสมุดเก่า' เลย... "
10010010-111 = "เอาเถอะค่ะ เอาเป็นว่าเธอคนนี้เก่งกาจมากจนได้รับฉายาจากพวกเราว่าเป็น 'จอมเวทแห่งห้องสมุดเก่า' เลย... "
10010010-112 = "แต่ก็ไม่ได้ใช้เวทมนตร์อะไรหรอกนะคะ แค่แก้ปัญหาได้ฉับไวราวกับเสกขึ้นมาเฉยๆ..."
10010010-113 = "แต่ว่าเรามีปัญหาเล็กๆ น้อยๆ อยู่เรื่องหนึ่งค่ะ..."
10010010-115 = "คะ? ปัญหาอะไรเหรอคะ? คือว่า... อืม..."
10010010-116 = "แบบว่า... เธอค่อนข้างขี้อายน่ะค่ะ ไม่ค่อยคุยกับคนแปลกหน้าเท่าไร... แล้วก็กลัวแสงแดดด้วย..."
10010010-117 = "แถมยังอยู่แต่ในห้องสมุดเก่าทั้งวันทั้งคืน ไม่ยอมออกไปไหนเลย..."
10010010-118 = "แค่เข้าสังคมไม่เก่งน่ะค่ะ... ไม่ใช่คนไม่ดีอะไร..."
10010010-120 = "คะ...? อยากรู้ว่าเป็นใครเหรอคะ? เอ่อ... คือ..."
10010010-121 = "หัวหน้าชมรมอ่านหนังสือของเราเองค่ะ..."
10010010-123 = "หัวหน้าอุยน่ะค่ะ..."
