[translation]
10013040-1 = "#title;제4화;다음 행선지를 향해"
10013040-5 = "[ns] \"……해서 일단 한 군데를 해결한 참이야.\""
10013040-6 = "3;호시노 수영복ND;02;으헤~ 프랜차이즈 계약인가~ 멋진 방법이네~\n#3;sig\n#3;a"
10013040-7 = "#na;시즈코 수영복ND;뭐, 사, 사업적인 결정일 뿐이지만!"
10013040-8 = "[s] \"그래서, 그쪽은 어때?\""
10013040-9 = "3;호시노 수영복ND;02\n1;노노미 수영복ND;02;후후훗~☆ 저희는 방금 막 나쁜 짓만 꾸미는 나쁜 아이들을 혼내 준 참이에요~☆\n#1;em;[반짝]\n#1;sig\n#3;sig\n#1;a"
10013040-10 = "3;호시노 수영복ND;02\n5;시로코 수영복;01;이 지역 근처에서 가장 골칫덩이인 수영복 불량배를 무력화시켰어.\n#5;sig\n#3;sig\n#5;a"
10013040-12 = "2;세리카 수영복;03;우리도 이런 느낌으로 쭉쭉 진행할 테니까!\n#2;sig\n#2;a"
10013040-13 = "4;아야네 수영복ND;05;그럼 계속해서 서, 서로 힘내기로 해요!\n#4;sig\n#4;a"
10013040-14 = "[s] \"응, 고생해.\""
10013040-18 = "3;시즈코 수영복ND;05;후우……\n#3;greeting\n#3;a"
10013040-19 = "[s] \"왜 그래? 시즈코, 표정이 안 좋은데.\""
10013040-20 = "3;시즈코 수영복ND;06;아, 아뇨. 별 건 아니에요…….\n#3;stiff"
10013040-21 = "3;시즈코 수영복ND;06;그냥 문득, 저희 백야당이 당면한 문제를 다른 학교 분들에게 떠넘긴 건 아닐까. 하는 생각이 들어서…….\n#3;em;[속상함]"
10013040-22 = "[s] \"그거라면 걱정할 것 없어, 모두가 도와주고 싶어서 직접 나선 거니까.\""
10013040-23 = "3;시즈코 수영복ND;06;그런, 가요?\n#3;em;[...]"
10013040-24 = "[s1] \"응, 게다가 아비도스 애들은 강하니까.\"\n[s2] \"어떤 일이라도 분명 기상천외하게 뛰어넘어서, 해결해줄 거야.\""
10013040-27 = "3;시즈코 수영복ND;01;네, 선생님께서 직접 그렇게 말씀하실 정도라면……"
10013040-28 = "3;시즈코 수영복ND;02;저도 믿고 맡기겠어요!\n#3;em;[반짝]\n#3;greeting"
10013040-29 = "[s] \"그래서 다음 우리 목적지는 어디야?\""
10013040-30 = "3;시즈코 수영복ND;01;네, 그거라면 이미 루트를 정해 뒀어요.\n#3;em;[반응]"
10013040-31 = "#st;[0,0];instant;1;"
10013040-35 = "5;시즈코 수영복ND;99;<영원토록 끓어오르는 뜨거운 땅을 찾는 유황의 광부들> 이후로 저희가 향해야 하는 곳은 바로……\n#5;a"
10013040-36 = "5;시즈코 수영복ND;05;이곳이에요!\n#5;em;[!]\n#5;hophop\n#5;m3"
