[translation]
1001702-1 = "授勳典禮"
1001702-2 = "赤冬聯邦學園．會長辦公室"
1001702-3 = "唔嗯……想不出什麼好的名字呢。"
1001702-4 = "那種更榮譽、更高貴，並且配的上咱的名字……"
1001702-5 = ""
1001702-6 = "哦哦，你來了呀同志！等你好久了呢！"
1001702-7 = "其實，有件重要的事需要借助同志的智慧，所以才請你過來的。"
1001702-8 = "咱想同志你應該也知道，#n咱在這幾個月裡為了赤冬聯邦學園的發展，不分日夜地努力著。"
1001702-9 = "像是為了進行供餐系統的品質管理，一整天都在試吃布丁，還有在視察學校之前……為了保存體力而睡到中午之類的，其他還有……呃，像是……"
1001702-10 = "總之！因為做了這些了不起的事情，咱非常勞累。獲得相應的報酬也是應該的吧！"
1001702-11 = "於是咱不斷煩惱要如何獎勵自己……最後決定擁有赤冬學園中最高榮譽的勳章了。"
1001702-12 = "勳章不是像布丁那樣吃下去就不見了的東西，在獲得的同時也會被紀錄起來……"
1001702-13 = "永遠留在赤冬聯邦學園的歷史之中──用來獎勵一直努力認真的咱再適合不過了！"
1001702-14 = "但是現在出現了一個問題，那就是……"
1001702-15 = "咱已經獲得赤冬聯邦學園中所有勳章，所以沒有其他可以取得的勳章了！"
1001702-16 = "雖然說咱是學生會長，勳章什麼的只要製作新的就好了。"
1001702-17 = "但問題是，想不出適合新勳章的名字……"
1001702-18 = "所以說同志啊，有沒有那種榮譽、高貴、優雅，#n又能把咱的豐功偉業傳達給後世的好名字呀？"
1001702-19 = "只要戴著就覺得帥氣，幫咱想想這種感覺的名字吧！"
1001702-20 = "[s1] 「Hyper。」\n[s2] 「Ultra。」\n[s3] 「Mega。」"
1001702-21 = ""
1001702-22 = "哦哦，真帥氣！！只要把這些詞連起來的話，肯定能誕生出具有好名稱的勳章的！"
1001702-23 = ""
1001702-24 = "哦哦，真帥氣！！只要把這些詞連起來的話，肯定能誕生出具有好名稱的勳章的！"
1001702-25 = ""
1001702-26 = "哦哦，真帥氣！！只要把這些詞連起來的話，肯定能誕生出具有好名稱的勳章的！"
1001702-27 = "還有什麼其他的嗎！？"
1001702-28 = "嗯？只要在名字前面加上「超」這個字，就能有像必殺技一樣強的感覺？"
1001702-29 = "好，這個也採用！"
1001702-30 = "唔姆，唔姆。原來如此，那個也……"
1001702-33 = "好，決定了！"
1001702-34 = "赤冬最高榮譽的新勳章，#n就決定叫「超．Hyper Ultra Mega Super勇猛努力榮譽章」了！"
1001702-35 = "這樣一來，光是聽到勳章的名字，所有學生都不得不感到佩服了吧？哼哼哼……"
1001702-36 = "嗯？你說對於一起想出名字的同志你，有沒有什麼獎勵是嗎？"
1001702-37 = "這麼說也對……但「超．Hyper Ultra Mega Super勇猛努力榮譽章」#n是代表赤冬聯邦學園最高榮譽的勳章，所以不能隨意給你呢……"
1001702-38 = "沒辦法了。"
1001702-39 = "就把不是最高榮譽卻僅次於它的#n「Hyper Ultra Mega Super勇猛努力榮譽章」賜給你吧。"
1001702-40 = "感到光榮吧，同志！"
1001702-42 = "（之後和潔莉諾一起思考勳章的設計，度過了快樂的時光）"
