[translation]
10013050-1 = "ตอนที่ 5;สัตว์ประหลาดหูขาว 1"
10013050-2 = ""
10013050-7 = "(คุณครูและทุกคนมาถึงชายหาดที่เงียบสงบตามคำสั่งของชิซุโกะ)"
10013050-8 = "[ns] \"ต่อไปคือ <สัตว์ประหลาดหูขาว ผู้เข้าสยบผู้แพ้>... ใช่มั้ย?\""
10013050-9 = "จะว่ายังไงดีนะ... ฉันว่า... ชื่อแต่ละกลุ่มมัน... เวอร์จังเลยนะคะ"
10013050-10 = "สะ... สัตว์ประหลาด...! ศาสตร์นินจาของอิซุนะจะกำจัดพวกมันได้มั้ยคะ...?"
10013050-11 = "อื้ม! ถึงจะยังวางใจไม่ได้ แต่ก็ไม่ต้องกังวลไปหรอกค่ะ! ก็พวกเรามีคุณชิเซะไงคะ!"
10013050-13 = "เฮือก...!!"
10013050-14 = ""
10013050-16 = ""
10013050-17 = ""
10013050-18 = ""
10013050-19 = "วิญญาณร้ายจงหายไป...?"
10013050-20 = "[s] \"ไปดูให้รู้กันเลยว่าเป็นสัตว์ประหลาดตัวจริงหรือแค่คนธรรมดา\""
10013050-21 = "ค่ะ ชมรมพัฒนาออนเซ็นเองก็ใช้สมญานามเวอร์ๆ แต่สุดท้ายก็เป็นคนฝีมือธรรมดา"
10013050-22 = "ไม่รู้เลยว่าต้องเรียกว่าสัตว์ประหลาดหรือเรื่องประหลาดดี"
10013050-23 = "อืม... ฉันว่าสัตว์ประหลาดที่เรียกๆ กัน สุดท้ายแล้วคงไม่มีอะไรมากหรอก..."
10013050-24 = ""
10013050-29 = "อะ.... โอย"
10013050-31 = ""
10013050-33 = ""
10013050-34 = ""
10013050-35 = ""
10013050-36 = "ตะ... ต้องไป..."
10013050-37 = ""
10013050-39 = ""
10013050-40 = "ไปสถานที่แข่งขัน..."
10013050-41 = ""
10013050-43 = ""
10013050-46 = "หืม...? คนเมื่อกี๊...?"
10013050-47 = "ทะ... ท่านประธาน! ไม่ได้มีแค่คนนั้นคนเดียวด้วยนะคะ!"
10013050-48 = ""
10013050-51 = ""
10013050-52 = "ตะ... ต้องรีบไป"
10013050-53 = ""
10013050-55 = ""
10013050-56 = ""
10013050-57 = "ให้ถึง... ก่อนจะสาย..."
10013050-58 = ""
10013050-60 = ""
10013050-63 = "คนคนนี้ก็... เหมือนกับว่า..."
10013050-64 = "[s] \"เหมือนโดนอะไรสิงเลย อะไรอย่างเช่น... สัตว์ประหลาด\""
10013050-65 = ""
10013050-66 = "หา...?! จะเป็นไปได้ยังไงคะ?! จะมีสัตว์ประหลาดอยู่จริงๆ ได้ยังไง...!"
10013050-67 = ""
10013050-72 = "อ๊ะ! เสียงหวูดเรือ! เสียงดังมาจากทางโน้นค่ะ!"
10013050-73 = ""
10013050-78 = "นี่มัน... เรือยักษ์...?"
10013050-79 = "ชื่อของเรือเขียนไว้ว่า..."
10013050-81 = "เรือ <โกลเด้นฟรีซ> ค่ะ"
10013050-82 = "[s] \"โกลเด้นฟรีซ... เหมือนเคยได้ยินมาก่อนเลย...\""
10013050-84 = ""
10013050-87 = "เรือจะเข้าเทียบท่าให้ขึ้นได้ในอีก 30 นาทีนะครับ!"
10013050-88 = "ท่านที่จะเล่นเกมในวันนี้ ขอให้รีบมาขึ้นเรือด้วยนะครับ!"
10013050-89 = ""
10013050-91 = ""
10013050-92 = ""
10013050-93 = "ครับ... ครับ... (เสียงสะท้อน)"
10013050-94 = ""
10013050-96 = ""
10013050-97 = ""
10013050-98 = ""
10013050-101 = "ทะ... ทุกคนแห่กันขึ้นเรือ เหมือนกับกำลังถูกสัตว์ประหลาดสิงจริงๆ เลยค่ะ!"
10013050-102 = "ทะ... ทำยังไงดีคะท่านประธาน?!"
10013050-103 = "ฮึ่ม! น่าสงสัยมาก อยู่เฉยๆ แบบนี้ไม่ได้แล้ว! เราต้องไม่ลืมเป้าหมายของเรา!"
10013050-104 = "ไปขึ้นเรือด้วยกันเลย!"
10013050-105 = "[s] \"อื้ม\""
10013050-106 = ""
10013050-119 = "[ns] \"บรรยากาศดูวุ่นวายจังเลยนะ\""
10013050-120 = ""
10013050-123 = ""
10013050-124 = ""
10013050-125 = ""
10013050-126 = ""
10013050-129 = ""
10013050-130 = ""
10013050-131 = ""
10013050-132 = ""
10013050-133 = ""
10013050-134 = ""
10013050-137 = ""
10013050-139 = "ทุกคนที่มาที่นี่ เหมือนกับจดจ่ออยู่กับอะไรบางอย่างจนวิญญาณหลุดจากร่างไปเลยค่ะ..."
10013050-140 = "ทุกคนมาทำอะไรที่นี่กันแน่คะ?"
10013050-141 = "บรรยากาศที่วุ่นวาย... ทุกคนดูเหมือนสติหลุดลอย... แถมก่อนขึ้นเรือยังมีพูดถึง <เกม> อีก..."
10013050-142 = "ระ... หรือว่า...! ที่นี่คือสถานที่จัดการแข่งขันผิดกฎหมาย...!"
10013050-143 = "[s] \"อ๊ะ เดี๋ยวนะ คนทางโน้นกำลังตะโกนอะไรอยู่\""
10013050-144 = ""
10013050-146 = ""
10013050-148 = "ถะ... ถะ... ถ้างั้นก็ตาฉัน...!"
10013050-149 = "ฉันจะขออัญเชิญพิเศษ <หอยทากมนุษย์>! ออกมาตะ... เต้นไปพร้อมกัน! เพื่อเพิ่มค่าป้องกัน#nของหอยทากมนุษย์!"
10013050-150 = "ถะ... ถ้างั้น...! ฉันขออัญเชิญ <ตั๊กแตนเรียนดี>!"
10013050-151 = "แล้วทำท่าบริดจ์ไปพร้อมกัน...! เพื่อเพิ่มความเร็วของตั๊กแตนเรียนดี!"
10013050-152 = "โจมตีด้วยใบนี้เลยยย!"
10013050-153 = ""
10013050-155 = ""
10013050-156 = ""
10013050-157 = "คะ...?"
10013050-158 = "อ๊ะ... อันนี้ฉัน... เคยเห็นอันนี้มาก่อนค่ะ ที่คาเอเดะจังเคยเล่น..."
10013050-159 = "ใช่แล้วค่ะ มันคือเกมการ์ดมูชิควีนค่ะ!"
10013050-160 = "มู... มูชิควีน?!"
10013050-161 = "[s] \"อ๋อ เป็นอันนี้เองเหรอ\""
10013050-162 = "ดะ... เดี๋ยวก่อนสิ! แล้วทำไมถึงมาเล่นที่นี่ล่ะ?"
10013050-163 = "แล้วทำไมทำหน้าเคร่งเครียดกันขนาดนั้น... เหมือนเล่นเกมการ์ดแบบสติหลุดไปแล้วเลย...?"
10013050-164 = "คาเอเดะจังก็พูดอยู่บ่อยๆ ค่ะ"
10013050-165 = "ว่ามูชิควีนเป็นเกมที่น่ากลัว... ที่เดิมพันด้วยเกียรติยศและความศรัทธาของแต่ละคน!"
10013050-166 = "ใช่ค่ะ! พีน่าก็เคยพูดบ่อยๆ ว่านี่เป็นเกมที่โหดร้าย บางครั้งหากแข่งแล้วแพ้จะต้องถูกผนึกเอาไว้ใน#nการ์ดนั้นด้วยนะคะท่านประธาน!"
10013050-168 = "กะ... เกมนี้น่ากลัวขนาดนั้นเลยเหรอ...!"
10013050-169 = "ไม่ๆๆ ไม่ใช่หรอก ยังไงมันก็แค่เกมเกี่ยวกับอนิเมะไม่ใช่เหรอ?!"
10013050-170 = "[s] \"แต่ทำไมถึงมาจัดแข่งมูชิควีนในที่แบบนี้นะ?\""
10013050-171 = ""
10013050-176 = "ผมรออยู่นานเลยครับ! ดูเอลลิสต์มูชิควีนทุกท่านที่มารวมตัวที่นี่!"
10013050-177 = ""
10013050-181 = ""
10013050-182 = "วันนี้เราจะเปิดการแข่งขันอันร้อนแรงที่เดิมพันด้วยการ์ดของทุกท่าน!"
10013050-183 = "ยินดีต้อนรับเข้าสู่การแข่งขัน 'ซีเคร็ท มูชิควีน' ครับ!"
10013050-184 = "ซะ... ซีเคร็ท?"
10013050-185 = "อย่างที่ทุกท่านทราบ การแข่งขันมูชิควีนที่จัดขึ้นบนเรือไม่ใช่การแข่งขันธรรมดาๆ!"
10013050-186 = "เพราะนี่คือศึกแห่งการเดิมพัน! ผู้ชนะจะได้ทุกอย่าง ส่วนผู้แพ้จะเสียทุกอย่างที่มี!"
10013050-187 = "บนเรือแห่งนี้ ผู้แพ้ต้องเจอการลงโทษอย่างน่าเวทนา นั่นคือต้องเสียการ์ดทุกเด็คที่มี! เตรียมตัวเตรียมใจกันมาแล้วใช่มั้ยครับ!?"
10013050-188 = "นี่มัน... แย่ขนาดนั้นเลยเหรอ?"
10013050-189 = "[s1] \"นะ... นั่นสิ\"\n[s2] \"จะสูบวิญญาณด้วยการแย่งไปยกเด็คเลยเหรอ... น่ากลัวชะมัด...!\""
10013050-190 = "คนพวกนี้มีเหตุผลอะไรถึงต้องมาลงแข่งขันกันนะ..."
10013050-191 = "คุณครูก็อินไปกับเขาด้วยเหรอคะ?!"
10013050-192 = "อีกอย่าง ถ้าการลงโทษมันโหดร้ายขนาดนั้น แล้วทำไมถึงได้มาลงแข่งขันกันล่ะ?!"
10013050-193 = "หากมีโทษสำหรับผู้แพ้ ก็แน่นอนว่าต้องมีรางวัลดีๆ สำหรับผู้ชนะ!"
10013050-194 = "ผู้ชนะในวันนี้จะได้รับแพ็กการ์ดมูชิควีน ลิมิเต็ดเอดิชั่น และ..."
10013050-195 = ""
10013050-197 = ""
10013050-199 = "<ตั๋วใช้งานรีสอร์ต> ที่มอบสิทธิ์ในการบริหารจัดการสนามแข่งนี้ครับ!"
10013050-200 = ""
10013050-202 = ""
10013050-203 = "[ns] \"ใจป้ำมากเลยนะ\""
10013050-204 = "อะไรกันเนี่ยยย?!! กล้าดียังไง?! ถ้าได้ตั๋วนั่นไปละก็ ทุกอย่างของฉันก็จะถูกแย่งไปหมดน่ะสิ? แล้วถ้าแพ้ ไม่เสียดายการ์ดของพวกเธอเหรอไง?!"
10013050-206 = "ไม่เป็นไรหรอก! สำหรับดูเอลลิสต์มูชิควีน หากไม่ชนะก็ต้องตายทั้งเป็นอยู่แล้ว!"
10013050-207 = ""
10013050-209 = ""
10013050-210 = ""
10013050-211 = "อะ... อะไรนะ?"
10013050-212 = "ฉันมาที่นี่เพราะได้รับแจ้งว่ามีพวกก่อความวุ่นวาย!"
10013050-213 = "ใครกันที่กล้าก่อเรื่องในสนามแข่งที่ศักดิ์สิทธิ์แบบนี้!"
10013050-214 = "ไม่ใช่นะ ฉันแค่..."
10013050-215 = "ฮึ่ม ดูจากลักษณะแล้ว พวกเธอไม่ใช่ผู้เข้าแข่งขันของเราใช่มั้ย?"
10013050-216 = "[s] \"ดูจากภายนอกก็รู้แล้วเหรอ?\""
10013050-217 = "คนเป็นดูเอลลิสต์มูชิควีนน่ะ ต้องมีจิตวิญญาณของการ์ดที่เปล่งประกายออกมาจากดวงตา!"
10013050-218 = "พูดอะไรไม่เห็นจะรู้เรื่องเลย?!"
10013050-220 = "ช่างเถอะ ถ้าไม่ได้มาเข้าแข่งขันก็ออกไปจากที่นี่ซะ!"
10013050-221 = "ตั้งแต่นี้ไป ที่แห่งนี้จะเปลี่ยนเป็นสนามรบ!"
10013050-222 = "[s] \"ตอนนี้ก็เหมือนใจกลางสนามรบอยู่แล้วนะ...\""
10013050-223 = "หรือว่าพวกเธอมาที่นี่เพราะ <การล่ารีสอร์ต>?"
10013050-224 = "ถ้าเป็นอย่างนั้นก็ยิ่งยกโทษให้ไม่ได้! คนที่มาขัดขวางการแข่งขันต้องโดนเตะโด่งออกจากเรือ!"
10013050-225 = ""
10013050-228 = ""
10013050-230 = ""
10013050-231 = ""
10013050-232 = "นี่พวกเธอเที่ยวไล่เตะคนที่เข้ามาแบบนี้หมดเลยเหรอ?! คิดว่าตัวเองเป็นโจรสลัดหรือไง?!"
10013050-233 = "ระ... เราจะทำยังไงกันดีคะท่านประธาน?! แบบนี้มีหวังถูกเตะให้ไปลอยกลางทะเลแน่...!"
10013050-234 = "นายท่าน! ถึงทุกคนจะตกอยู่ในอันตราย แต่อิซุนะจะ...!"
10013050-236 = "ฮ้าววว~"
10013050-237 = "เดี๋ยวนะคะ... ถ้าตามที่คุณพูด"
10013050-238 = "ก็แปลว่า หากพวกฉันจะลงแข่งขันมูชิควีน ก็จะยังอยู่บนเรือนี้ได้ใช่มั้ยคะ?"
10013050-239 = "[s] \"มิโมริ?\""
10013050-241 = "หืม? เอ่อ... มันก็ใช่อยู่หรอก?"
10013050-242 = "ถ้าเป็นดูเอลลิสต์มูชิควีน เราก็ไม่ปฏิเสธ..."
10013050-244 = "ทุกคนคะ นี่เป็นโอกาสดีเลยละค่ะ เราไม่จำเป็นต้องสู้ด้วยการล่ารีสอร์ตก็ได้..."
10013050-245 = "แค่เข้าแข่งขันมูชิควีนแล้วเอาชนะให้ได้... เราก็ได้หนังสือสัญญาคืนมาได้นี่คะ"
10013050-246 = "จะให้ไปแข่งยังไงล่ะ? ฉันไม่รู้อะไรเกี่ยวกับมูชิควีน แล้วก็ไม่เคยเล่นเลยด้วย..."
10013050-247 = "มีวิธีค่ะ คนรอบตัวเราที่นี่ต่างเป็นดูเอลลิสต์มูชิควีนที่เชี่ยวชาญกันทั้งนั้นเลยนี่คะ"
10013050-248 = "ทั้งชมรมฝึกฝน ทั้งชมรมเทศกาล!"
10013050-249 = "[s] \"อย่าบอกนะว่า...\""
10013050-250 = "อ้อ!"
10013050-251 = ""
10013050-254 = ""
10013050-256 = ""
10013050-260 = ""
10013050-261 = "ค่ะ! รับทราบค่ะ! หัวหน้า!"
10013050-262 = "ถ้าเป็นเรื่องนั้นละก็! ปล่อยให้เป็นหน้าที่ของพวกฉันได้เลย!"
10013050-264 = "ฮุฮุฮุ! ค่ะ!"
10013050-265 = "ฉันเชื่อใจทั้งสองคนนะคะ! พีน่า! คาเอเดะ!"
10013050-266 = "[s] \"จะเอาจริงเหรอ...?\""
10013050-267 = "ฮึ่ม! การลงทุนมีความเสี่ยง..."
10013050-268 = "รู้ว่าเสี่ยง แต่คงต้องขอลองค่ะ!"
