[translation]
10011040-1 = "#title;제4화;첫 번째 관문: 간판아가씨와 경호원"
10011040-3 = "1;제멋대로 망량즈 A;00\n3;제멋대로 망량즈 B;00\n5;제멋대로 망량즈 리더;00\n2;이부키;00\n4;이로하;00\n#1;black\n#2;black\n#3;black\n#4;black\n#5;black"
10011040-7 = "1;제멋대로 망량즈 A;00\n5;제멋대로 망량즈 B;00\n3;제멋대로 망량즈 리더;00\n#3;ar\n#1;ar\n#5;ar\n#1;h\n#3;h\n#5;h\n#wait;1000"
10011040-8 = "3;제멋대로 망량즈 리더;00\n1;제멋대로 망량즈 A;06;하아하아……. 지, 진짜 저질러버렸다……!\n#1;em;[땀]\n#1;stiff"
10011040-9 = "3;제멋대로 망량즈 리더;00\n5;제멋대로 망량즈 B;04;나, 납치! 해버렸슴다!\n#5;hophop"
10011040-10 = "3;제멋대로 망량즈 리더;00\n1;제멋대로 망량즈 A;00;저, 정말 괜찮은 거겠지? 이걸로!"
10011040-12 = "1;제멋대로 망량즈 A;00\n5;제멋대로 망량즈 B;00\n3;제멋대로 망량즈 리더;00;당황하지 마. 설마 잊은 건 아니겠지? 우리의 이번 목표를.\n#3;em;[!]\n#3;closeup\n#1;dl\n#5;dr"
10011040-14 = "4;제멋대로 망량즈 B;05\n2;제멋대로 망량즈 A;04;자, 잘 기억하고 있다고! 리더! \n#2;em;[땀]\n#2;stiff"
10011040-15 = "4;제멋대로 망량즈 B;05\n2;제멋대로 망량즈 A;04;<와라쿠 공주님>의 주역을 납치해서, 이번 교류회를 엉망으로 만든다!"
10011040-16 = "2;제멋대로 망량즈 A;04\n4;제멋대로 망량즈 B;03;그걸로 음양부가 우리에게 굽신거리게 만든다 작전! 임다!"
10011040-17 = "4;제멋대로 망량즈 B;03\n2;제멋대로 망량즈 A;04\n3;제멋대로 망량즈 리더;00;지금까지 척척 진행된 걸 봐. 이 작전에 빈틈은 없다고.\n#3;a\n#3;em;[반응]\n#4;m5\n#2;m1"
10011040-18 = "4;제멋대로 망량즈 B;03\n2;제멋대로 망량즈 A;04\n3;제멋대로 망량즈 리더;00;누가 뭐라 해도 이번 작전은 키보토스 지식ON 사이트에서 범죄계의 마이스터라고 불리는, 바로 그 <히죽히죽 교수>에게 컨설팅을 받은 작전이니까.\n#3;hophop\n#3;em;[재잘]"
10011040-19 = "3;제멋대로 망량즈 리더;00\n2;제멋대로 망량즈 A;02;히죽히죽 교수라면…….\n#2;em;[...]"
10011040-20 = "3;제멋대로 망량즈 리더;00\n4;제멋대로 망량즈 B;00;크로노스 스쿨에서도 그 행적을 끊임없이 추적한다는! 유명한 사람 아님까?!\n#4;shake\n#4;em;[?!]"
10011040-21 = "4;제멋대로 망량즈 B;00\n2;제멋대로 망량즈 A;02\n3;제멋대로 망량즈 리더;00;맞아. 그만큼 이 작전은 완벽해.\n#3;closeup\n#3;greeting\n#2;dl\n#4;dr"
10011040-22 = "3;제멋대로 망량즈 리더;00;우리는 그저 계획을 실행하면 그만. 그걸로 우리 제멋대로 망량즈가 얼마나 대단한지 백귀야행과 게헨나에게 보여주는 거지.\n#3;em;[반응]"
10011040-24 = "4;제멋대로 망량즈 B;02\n2;제멋대로 망량즈 A;02;그나저나……. 정말로 그 유명한 치세 공주님을 납치하다니…….\n#2;a\n#4;a\n#2;em;…"
10011040-25 = "2;제멋대로 망량즈 A;02\n4;제멋대로 망량즈 B;01;성공했는데도 아직 가슴이 두근거림다…….\n#4;stiff"
10011040-26 = "4;제멋대로 망량즈 B;01\n2;제멋대로 망량즈 A;03;그럼 모처럼이니까, 치세 님의 얼굴을 한번 보고 진정하도록 할까…….\n#2;em;[음표]\n#2;hophop"
10011040-28 = "3;이부키;00\n#3;h\n#3;black"
10011040-32 = "1;제멋대로 망량즈 A;02\n5;제멋대로 망량즈 B;02\n#1;a\n#5;a\n#1;h\n#5;h\n#wait;1000"
10011040-34 = "1;제멋대로 망량즈 A;05\n5;제멋대로 망량즈 B;05\n3;이부키;02\n#1;greeting\n#5;greeting\n#3;black\n#3;h\n#1;h\n#5;h\n#wait;500"
10011040-35 = "1;제멋대로 망량즈 A;05\n5;제멋대로 망량즈 B;05\n3;이부키;02\n#3;a\n#3;stiff\n#1;h\n#3;h\n#5;h\n#wait;1500"
10011040-36 = "1;제멋대로 망량즈 A;04\n5;제멋대로 망량즈 B;04\n3;이부키;02\n#1;em;[?]\n#5;em;[?]\n#1;h\n#3;h\n#5;h\n#wait;1500"
10011040-38 = "3;이부키;09;이부키 등장!\n#3;closeup\n#fontsize;100"
10011040-39 = "3;이부키;01;응응! 이부키 흔들려도 꼬옥 참고 있었어!\n#3;closeup\n#3;hophop"
10011040-40 = "3;이부키;03;이제 이부키는 뭘 하면 돼?!\n#3;em;[반짝]\n#3;closeup"
10011040-41 = "#st;[0,0];instant;1;"
10011040-43 = "3;이부키;03\n#3;closeup\n#3;d\n#wait;1000"
10011040-45 = "1;제멋대로 망량즈 A;02\n5;제멋대로 망량즈 B;02\n3;제멋대로 망량즈 리더;00\n#1;em;…\n#3;em;…\n#5;em;…\n#1;a\n#3;a\n#5;a\n#1;h\n#3;h\n#5;h\n#wait;2500"
10011040-46 = "1;제멋대로 망량즈 A;06\n5;제멋대로 망량즈 B;06\n3;제멋대로 망량즈 리더;00\n#1;em;[?!]\n#3;em;[?!]\n#5;em;[?!]\n#1;hophop\n#3;stiff\n#5;shake\n#1;h\n#3;h\n#5;h"
10011040-47 = "#na;제멋대로 망량즈들;\"\"\"……얜 또 뭐야?!\"\"\""
10011040-48 = "1;제멋대로 망량즈 A;06\n5;제멋대로 망량즈 B;06\n3;제멋대로 망량즈 리더;00;(잠깐?! 치세 공주가 아니라는 건…… 이 복장, 설마 게헨나의 만마전……?)\n#3;em;[?]\n#3;shake"
10011040-49 = "3;제멋대로 망량즈 리더;00\n1;제멋대로 망량즈 A;06;치세 님을 가까이에서 뵙고 직접 사인받고 싶었는데!\n#1;hophop"
10011040-50 = "3;제멋대로 망량즈 리더;00\n5;제멋대로 망량즈 B;06;안타깝슴다!"
10011040-51 = "1;제멋대로 망량즈 A;06\n5;제멋대로 망량즈 B;06\n3;제멋대로 망량즈 리더;00;이게 안타까운 걸로 끝날 일이야?!\n#3;stiff\n#3;em;[빠직]"
10011040-53 = "3;이부키;02;우웅?\n#3;em;[?]"
10011040-54 = "#st;[0,0];instant;1;"
10011040-56 = "3;이부키;02\n5;제멋대로 망량즈 리더;00\n#5;al\n#3;m1\n#3;h\n#5;h\n#wait;1200"
10011040-58 = "1;피나;00\n3;시즈코;00\n5;츠쿠요;00\n4;미치루;00\n2;이즈나;00\n#1;black\n#2;black\n#3;black\n#4;black\n#5;black"
10011040-59 = "#na;???;거기! 너희들! 여기서 뭘 하는 거야?"
10011040-61 = "1;이부키;02\n5;제멋대로 망량즈 리더;00;헉?! 벌써 꼬리를 잡혔나?!\n#5;shake\n#5;em;[?!]\n#1;h\n#5;h"
10011040-62 = "#st;[0,0];instant;1;"
10011040-64 = "1;이부키;02\n5;제멋대로 망량즈 리더;00\n#1;h\n#5;h\n#1;d\n#5;d\n#wait;1500"
10011040-67 = "3;시즈코;01\n#3;a\n#wait;1500"
10011040-68 = "3;시즈코;02;너희, 납치 역이지?! 지금 여기 있을 때가 아니잖아! 비행선의 방송 봤을 거 아냐? 이벤트는 이미 시작되어버렸다고!\n#3;em;[반응]"
10011040-70 = "3;제멋대로 망량즈 B;04;마, 마츠리부의 부장……?\n#3;stiff"
10011040-71 = "5;시즈코;00;사전에 계획한 대로라면 너희가 도망치는 루트는 이쪽이니까 말이야!\n#5;al\n#3;m1"
10011040-72 = "3;제멋대로 망량즈 B;02;어?! 우리가 도망칠 수 있게 도와주는 검까?!\n#3;em;[땀]"
10011040-73 = "3;제멋대로 망량즈 B;02\n1;제멋대로 망량즈 A;02;그, 그러고 보면 들어본 적 있어!\n#1;em;[!]\n#1;ar\n#3;m3"
10011040-74 = "3;제멋대로 망량즈 B;02\n1;제멋대로 망량즈 A;06;마츠리부의 부장은…… 돈을 위해서라면 어떤 일이든 마다하지 않는 비정한 녀석이라고!"
10011040-75 = "1;제멋대로 망량즈 A;06\n3;제멋대로 망량즈 B;06;설마…… 이것도 그 히죽히죽 교수의 계획 중 하나임까?!\n#3;shake\n#3;em;[?!]"
10011040-77 = "3;제멋대로 망량즈 리더;00;그, 그런 것이었나……!\n#3;stiff"
10011040-78 = "1;시즈코;00;응? 뭔가 당치도 않은 오해를 받는 느낌이……. 어디선가 인수인계가 잘못된 걸까?\n#1;em;[?]\n#1;ar\n#3;m5"
10011040-79 = "1;시즈코;02;하여간 이럴 때가 아니야! 자, 이리로!\n#1;em;[반응]\n#1;hophop\n#1;m3"
10011040-80 = "3;제멋대로 망량즈 리더;00;엇, 어엇……?\n#3;stiff"
10011040-81 = "#st;[0,0];instant;1;"
10011040-83 = "3;제멋대로 망량즈 리더;00\n1;시즈코;02\n#3;dr\n#1;dr\n#1;h\n#3;h\n#wait;1500"
10011040-86 = "3;시즈코;99;으음, 뭔가 공연 스태프가 아니라…… 망량즈와 비슷한 거 같아서 꺼림칙한데……\n#3;em;…\n#3;a"
10011040-87 = "3;시즈코;02;아니, 그럴 리가 없지. 공연 도중이고 망량즈가 여기서 튀어나올 리가 없지. 응."
10011040-88 = "#st;[0,0];instant;1;"
10011040-90 = "3;시즈코;01\n#3;greeting\n#wait;1500"
10011040-91 = "3;시즈코;00;자, 이제 보자……. 이벤트 일정에 따르면, 이다음엔 분명……."
10011040-92 = "#st;[0,0];instant;1;"
10011040-94 = "3;시즈코;00\n5;피나;00\n#5;al\n#3;m1\n#3;h\n#wait;1200"
10011040-95 = "5;피나;03;부장! 피나! 도착했습니다~!\n#5;hophop\n#5;em;[반짝]"
10011040-96 = "3;시즈코;02;아, 마침 잘됐네! 좋았어! 우리도 준비하자! 피나!\n#3;em;[반응]"
10011040-100 = "3;미치루;05;망량즈 녀석들은 이리로 도망쳤을 거야……!\n#3;em;[!]\n#3;hophop\n#3;a"
10011040-101 = "3;미치루;05\n1;이즈나;03;이즈나! 놓치지 않겠습니다!\n#1;em;[반짝]\n#1;a\n#1;greeting"
10011040-102 = "3;미치루;05\n1;이즈나;03\n5;츠쿠요;00;하아하아. 가, 갑니다아……!\n#5;stiff\n#5;em;[땀]\n#5;a"
10011040-104 = "#na;???;후후후!"
10011040-105 = "#st;[0,0];instant;1;"
10011040-108 = "3;미치루;02\n5;츠쿠요;02\n1;이즈나;02\n#1;em;[?]\n#3;em;[?]\n#5;em;[?]\n#1;h\n#3;h\n#5;h\n#wait;1200"
10011040-109 = "3;미치루;02\n5;츠쿠요;02\n1;이즈나;02\n#1;d\n#3;d\n#5;d\n#1;h\n#3;h\n#5;h\n#wait;1500"
10011040-111 = "1;시즈코;01\n5;피나;01\n#1;a\n#5;a\n#1;h\n#5;h\n#bgshake\n#wait;2000"
10011040-112 = "1;시즈코;00;거기 잠깐!\n#1;em;[반응]"
10011040-113 = "5;피나;03;여기는 지나갈 수 없습니다!\n#5;hophop\n#5;em;[반짝]"
10011040-114 = "#st;[0,0];instant;1;"
10011040-116 = "1;시즈코;00\n5;피나;03\n#1;d\n#5;d\n#wait;1200"
10011040-118 = "3;미치루;04;뭣……\n#3;em;…\n#3;a"
10011040-119 = "[s] \"시즈코랑…… 피나?\""
10011040-121 = "5;피나;01\n1;시즈코;00;어라? 여러 도전자가 있겠거니 싶긴 했지만, 설마 거기에 선생님과…… 닌자 소녀가 있을 줄이야.\n#1;em;[?]"
10011040-122 = "1;시즈코;03;아잉~ 시즈코 깜짝 놀라버렸어요!\n#1;greeting\n#1;em;[반짝]"
10011040-123 = "5;피나;06;피나도! 가슴이 아픕니다! 한때 함께 대마왕 냥텐마루를 쓰러트렸던 동료가 지금 와서는 적!"
10011040-124 = "5;피나;04;협객의 길은! 너무 비정하고 슬픕니다!\n#5;em;[속상함]\n#5;stiff"
10011040-125 = "[s] \"그 이야기, 어디까지 공유된 거야?!\""
10011040-127 = "3;미치루;04;자, 잠깐! 백야당의 오너잖아! 왜 우리 앞을 막는 거야?! 설마……! 망량즈의 동료인 거야?!\n#3;em;[땀]"
10011040-128 = "5;시즈코;01;아, 그쪽은 분명 자칭 닌자들을 이끌고 다니는 괴짜 집단의 리더……였던가?\n#5;al\n#3;m1"
10011040-129 = "3;미치루;05;윽……! 괴, 괴짜라니! 누가……!\n#3;hophop\n#3;m2"
10011040-130 = "[s] \"괴짜라고 하면 백야당도 한가락 하지.\""
10011040-131 = "5;시즈코;02;네?\n#5;em;[?]"
10011040-133 = "3;츠쿠요;07;저, 드, 드, 들어본 적 있어요! 배, 백야당은 분명…… 매, 매니악한 서비스를 제공하고…… 그, 그에 대한 비, 비용을 청구하는 무서운 곳이라고…….\n#3;stiff\n#3;a\n#fontsize;55"
10011040-134 = "1;이즈나;05;앗! 업계의 어둠이란 거군요! 과연! 이즈나는 속지 않을 거예요!\n#1;em;[!]\n#1;ar\n#3;m5"
10011040-135 = "3;츠쿠요;07\n5;시즈코;05;오해할 소리 하지 마! 대체 어디서 그런 소리를 듣고 떠들어대는 거야! 다들!\n#5;em;[빠직]\n#5;hophop\n#5;al\n#3;m3"
10011040-136 = "[s] \"확실히 백야당의 덜렁이 서비스는 꽤나 매니악하지…….\""
10011040-137 = "3;츠쿠요;07\n5;시즈코;04;선생님까지 그러시는 건가요?!\n#5;shake\n#5;em;[?!]"
10011040-138 = "3;츠쿠요;07\n1;이즈나;05\n5;시즈코;05;전 그냥 공연의 어트랙션 담당일 뿐이라고요!\n#5;hophop\n#1;dl\n#3;dl\n#5;m3"
10011040-140 = "3;시즈코;05\n5;이로하;02;어트랙션……?\n#5;em;[?]\n#5;al\n#3;m1"
10011040-141 = "5;미치루;02;아…… 공연용 시련이란 거야……?"
10011040-142 = "3;시즈코;03;네에! 맞습니다!\n#3;em;[음표]\n#3;hophop"
10011040-143 = "3;시즈코;01;바로 이곳! <첫 번째 관문 어트랙션: 간판 아가씨와 경호원>의 수문장은 다름 아닌 저!\n#3;m3\n#5;dr"
10011040-144 = "3;시즈코;00;백야당의 아이돌이자- 백야당의 오너! 카와와 시즈코와-!"
10011040-145 = "1;피나;03;피나입니다! 두목!\n#1;hophop\n#1;em;[반짝]\n#1;ar\n#3;m5"
10011040-146 = "3;시즈코;99;오늘 이렇게 저희가 첫 관문의 수문장 역할을 맡아 여러분의 앞길을 막은 건…… 후후후, 무엇을 숨기랴……!"
10011040-148 = "3;시즈코;03;저 시즈코! 백야당의 간판 아가씨인 만큼! 들어서는 입구의 간판부터 막아서는 역할에 딱 알맞기 때문……!\n#3;em;[!]\n#3;closeup"
10011040-149 = "#st;[0,0];instant;1;"
10011040-152 = "3;시즈코;03\n#3;d\n#3;closeup\n#wait;1200"
10011040-154 = "2;미치루;02\n4;이로하;02\n1;이즈나;02\n5;츠쿠요;02\n#2;em;…\n#1;em;…\n#4;em;…\n#5;em;…\n#2;a\n#4;a\n#5;a\n#1;a\n#2;h\n#4;h\n#5;h\n#1;h\n#wait;3000"
10011040-155 = "[ns] \"……아, 미안. 혹시 조크였어? 지금 웃을까?\""
10011040-157 = "3;시즈코;04;우와아앙?!\n#3;shake\n#3;em;[?!]"
10011040-158 = "3;시즈코;05;돼, 됐다구요! 그런 쓸데없는 배려! 오히려 슬퍼지니까!\n#3;hophop"
10011040-159 = "3;시즈코;99;어쨌거나 대본은 둘째 치고 다시 시작이에요!\n#3;greeting"
10011040-160 = "3;시즈코;05;납치된 공주님을 구하러 온 여러분을, 저 백야당의 간판 아가씨 시즈코와……!"
10011040-161 = "3;시즈코;05\n5;피나;03;그 경호원, 피나가 상대하겠습니~~다앗!\n#5;hophop\n#5;em;[반짝]\n#5;a\n#3;h\n#3;m1"
