[translation]
10023075-3 = "Argh! No!"
10023075-4 = "You put up an admirable fight, but we were stronger."
10023075-5 = "Now, I have several questions for you, Meitaro."
10023075-6 = "Why and how have all these stolen artworks found their way to this basement?"
10023075-7 = "Um..."
10023075-8 = "I really didn't want to have to resort to this..."
10023075-9 = ""
10023075-11 = ""
10023075-12 = ""
10023075-14 = "But I've hired Shanhaijing's Genryumon guards as my security detail!"
10023075-16 = "Shanhaijing? Genryumon?"
10023075-17 = "[s1] \"You are scrupulous in some sense.\"\n[s2] \"You are going to do everything at any cost, aren't you?\""
10023075-18 = ""
10023075-19 = ""
10023075-22 = ""
10023075-24 = "Reserves, prepare to fight!"
10023075-25 = ""
10023075-28 = ""
10023075-29 = ""
10023075-30 = ""
10023075-32 = "Th-Those guests just..."
10023075-33 = "...transformed into Genryumon guards...! "
10023075-34 = ""
10023075-38 = ""
10023075-41 = ""
10023075-43 = "Wh-What do we do, Sensei? We're way outnumbered!"
10023075-44 = "Tsk. If I had my powered suit here..."
10023075-45 = ""
10023075-47 = ""
10023075-48 = ""
10023075-49 = ""
10023075-50 = ""
10023075-51 = ""
10023075-53 = "What's happening? I can't see!"
10023075-54 = ""
10023075-57 = "This way. Follow me!"
10023075-58 = "[s] \"I recognize that voice!\""
10023075-59 = ""
10023075-70 = "I followed the voice through the blinding, thick smoke and just barely escaped the mansion."
10023075-74 = "*pant* *pant*"
10023075-75 = "I'm...exhausted..."
10023075-77 = "Ow... I can't take another step..."
10023075-78 = "What an evening we've had."
10023075-79 = "Although, night would be more accurate at this point."
10023075-80 = "Is anyone hurt? Are you okay, Sensei? "
10023075-81 = "[s3] \"Great work, everyone. Including you.\" \n[s4] \"I think we have a guest, though.\""
10023075-82 = ""
10023075-83 = ""
10023075-86 = ""
10023075-87 = "Who are you talking about, Sensei?"
10023075-88 = ""
10023075-92 = "Coincidence, whimsy, serendipity, unpredictability... All concepts lending to the greater pursuit of art."
10023075-93 = ""
10023075-95 = ""
10023075-96 = "Who's there?"
10023075-97 = ""
10023075-99 = ""
10023075-102 = ""
10023075-103 = "Heehee. 'Tis I! I hope I find you well. Who could have predicted our next meeting to be under such exciting circumstances? "
10023075-104 = ""
10023075-107 = ""
10023075-109 = ""
10023075-111 = "S-S-Sensei? What the heck is going on?!"
10023075-112 = "[s5] \"Momoi, I know it's confusing! But there's an explanation!\" \n[s6] \"Momoi, we only got out thanks to the Benevolent Thief.\""
10023075-113 = ""
10023075-114 = ""
10023075-116 = "Sensei's right. I had a feeling, but that smoke had to have been... "
10023075-118 = "Nothing's here...no one's here..."
10023075-119 = ""
10023075-121 = ""
10023075-123 = ""
10023075-124 = "[ns7] \"I'm confused by and appreciative of your help.\"\n[ns8] \"Thank you...but why did you help us?\""
10023075-127 = "I understand. Please, allow me to explain and hopefully clear any misunderstandings here."
10023075-128 = "Through...certain means, I came to understand that you were all being fooled by Meitaro."
10023075-129 = ""
10023075-131 = ""
10023075-132 = "The Benevolent Thief gave me a quick, meaningful glance as she spoke."
10023075-135 = ""
10023075-137 = "I thought of the hushed conversation we had through her communication device when the lights went out."
10023075-138 = "Upon confirming that neither C&C nor you, Sensei, were my enemies, I made my move."
10023075-139 = "That's why I pushed you to solve the riddle, Sensei. So you could discover the underground auction hall, and who our true enemy was."
10023075-140 = "And to help our C&C bunny find her way to the treasure."
10023075-142 = "Information...overload... This is way too much for me to process!"
10023075-143 = "So... Are you saying we don't have to fight?"
10023075-145 = ""
10023075-147 = ""
10023075-148 = "Did you think I wouldn't see through your petty tricks, Benevolent Thief?"
10023075-149 = "Why, whatever do you mean?"
10023075-151 = "Sometimes the enemy of your enemy can become an ally. But not always. Not now."
10023075-153 = "C-Can I ask? If you're the Benevolent Thief, you're really one of the Seven Prisoners, right?"
10023075-154 = "Th-That means..."
10023075-156 = "Heehee."
10023075-157 = ""
10023075-159 = ""
10023075-161 = ""
10023075-163 = "What were you trying to say? "
10023075-164 = "That you can't speak to a dangerous criminal like one of the Seven Prisoners? You won't associate with a petty thief?"
10023075-166 = "U-Uh..."
10023075-168 = "The facts are that you are one of the Seven Prisoners, and that your and C&C's target is the same: the Clock King's Crown."
10023075-169 = "So, no. We cannot so carelessly trust a criminal."
10023075-170 = "[s9] \"Just hear me out for one second, everyone.\" \n[s10] \"Hey, stop! I have a suggestion!\""
10023075-173 = "Y-Yes, Sensei?"
10023075-174 = "Oh? Wise words from the one and only Schale's Sensei? "
10023075-176 = "[ns] \"I'd like for us to form an alliance.\""
10023075-177 = ""
10023075-179 = ""
10023075-181 = ""
10023075-182 = ""
10023075-184 = "...When an operation has been compromised, it can be prudent to form potentially advantageous alliances against a common enemy."
10023075-185 = "But that does not apply when that alliance is with one of the Seven Prisoners. We cannot work with criminals."
10023075-186 = "Heehee. I find the suggestion an excellent one! Wise words, indeed!"
10023075-187 = "I suppose those with such narrow-minded world views couldn't understand."
10023075-188 = "Sensei! I am commencing the elimination of a dangerous criminal!"
10023075-189 = "[s11] \"No elimination! Let's just calm down and talk.\" \n[s12] \"Why don't we start with some introductions?\""
10023075-192 = "Fine. Only for you, Sensei."
10023075-193 = "We're actually the Game Development Department, from Millennium Science School."
10023075-194 = "That Meitaro person thought I was a C&C member for some reason and, before we knew it, we were protecting the mansion from you!"
10023075-195 = "He told us that a sneaky thief sent a calling card about stealing his art... Some painting of a knighting ceremony.."
10023075-196 = "And then...somehow the walls started opening and there was this hidden stairwell, and then we found the auction, but it was a day early, and then Meitaro was like, \"Grr! C&C!\" and attacked us..."
10023075-197 = "...How did we end up here?"
10023075-199 = "I suspected as much, but you truly had no idea what you'd gotten yourself into."
10023075-200 = "Wh-What about it! How were we supposed to know?! It's not our fault!"
10023075-201 = "Although you did solve my calling card, even handicapped with your cluelessness. Bravo!"
10023075-202 = "Y-Yeah?!"
10023075-203 = "Well, obviously! We at the Game Development Department have trained endlessly, day in and day out, playing puzzle adventure games for this very moment!"
10023075-204 = "How wonderful. "
10023075-207 = "Well, I've shown my cards. The underground auction hall was my target from the beginning."
10023075-208 = "It was built specifically for the heinous activities you all observed: selling and auctioning off stolen artwork."
10023075-209 = "And overseeing it all is this mansion's owner: Meitaro."
10023075-210 = "I'll have to confirm your intel."
10023075-211 = "But regardless, the facts are clear. All the stolen artworks that C&C has been tracking are in this auction's inventory."
10023075-212 = "What the heck was the artwork exhibition for then?"
10023075-215 = "The revelries upstairs hide the darker truths underneath."
10023075-216 = "I came to this unfortunate basement in search of the Clock King's Crown."
10023075-217 = "The Clock King's Crown is coveted because it is truly one of a kind. There is no other in all of Kivotos."
10023075-218 = "Art is beautiful! Secluding art, hoarding art, assigning such trifling value to art? They debase my principles of beauty."
10023075-220 = "Now then, any questions?"
10023075-221 = "Meitaro has been manipulating your every move from behind the scenes."
10023075-222 = "He is dastardly and conniving. It's beyond the imagination of folks like you."
10023075-223 = "My head hurts... But hold right there! I know better than to trust the villain's story just like that!"
10023075-224 = "Heehee. Perfectly understandable."
10023075-225 = "But humor me for a moment, please."
10023075-226 = "Who would you believe: the one who attacked you, or the one who saved you?"
10023075-227 = "[s13] \"I've been wanting to thank you for saving Midori.\" \n[s14] \"I've been wondering why you saved Midori...\""
10023075-230 = "Yes. I did it for my ideals, of course. "
10023075-231 = "It would be a violation of my standards of beauty if I allowed innocent blood to be spilled before something of true value."
10023075-232 = "[s] \"Standard of beauty...\""
10023075-233 = "Heehee."
10023075-234 = ""
10023075-236 = ""
10023075-238 = ""
10023075-240 = "Back to Sensei of Schale's wondrous idea. I'd like to close the deal. Will you shake my hand?"
10023075-241 = ""
10023075-244 = ""
