[translation]
10023060-1 = "ตอนที่ 6;ไปกันก่อนดีกว่า"
10023060-2 = "(ภารกิจวันแรกผ่านไปอย่างโกลาหล และก็เข้าสู่วันที่สอง)"
10023060-6 = "นี่คือภาพที่จะถูกประมูลในวันพรุ่งนี้สินะครับ ผมคิดว่าจะเข้าร่วมงานด้วย แล้วคุณล่ะครับ?"
10023060-7 = "ผมว่าจะดูบรรยากาศงานก่อนน่ะครับ"
10023060-8 = ""
10023060-11 = ""
10023060-12 = "[ns] (ถึงเมื่อวานจะมีเรื่อง แต่ทุกคนก็ยังไม่ทิ้งความตั้งใจแฮะ)"
10023060-13 = ""
10023060-15 = ""
10023060-16 = ""
10023060-17 = ""
10023060-18 = ""
10023060-19 = ""
10023060-20 = ""
10023060-21 = "เฮ้อ... เหนื่อยชะมัดเลย"
10023060-22 = "[s] \"ทำงานหนักน่าดูเลยนะ โมโมอิ\""
10023060-23 = "อื้ม... พอมาถึงจุดนี้ฉันก็อยากทำให้ดีที่สุดน่ะ ไม่อยากทำแค่ว่าให้มันผ่านๆ ไปเฉยๆ"
10023060-24 = "ฉันรู้สึกแบบนั้นน่ะ"
10023060-25 = "คุณครู ขอโทษนะที่ทำให้ต้องมาพัวพันกับเรื่องแบบนี้ไปด้วย"
10023060-26 = "[s] \"ครูกลับมองว่ามันสนุกดีออก\""
10023060-27 = "...... จริงเหรอ? พูดแบบนี้เดี๋ยวอาจเสียใจทีหลังก็ได้นะ"
10023060-28 = "เพราะเดี๋ยวต่อไปถ้าเกิดเรื่องคล้ายๆ กันแบบนี้อีก พวกฉันจะเรียกให้คุณครูมาช่วยตลอดเลยไงล่ะ!"
10023060-29 = "[s] \"เรียกใช้ได้ตลอดเลยนะ...\""
10023060-30 = ""
10023060-34 = "!!!"
10023060-35 = "[ns] \"เริ่มแล้วเหรอ......!\""
10023060-36 = "นี่มัน!"
10023060-37 = "ใจเย็นๆ ก่อนนะครับ ที่ที่ <จอมโจรแห่งความเสน่หา> มาปรากฏตัว... จะไม่มีใครเสียชีวิตหรอกครับ"
10023060-38 = "จริงด้วยนะครับ งั้นพวกเราก็ไปชมงานกันอย่างเมื่อวานเถอะครับ"
10023060-39 = "ถ้าคุณเมทาโร่ได้ยินแล้วคงเสียใจอยู่บ้าง แต่ผมว่าเหตุการณ์แบบนี้ก็ถือว่าเป็นสีสันของงานดีนะครับ"
10023060-40 = ""
10023060-43 = ""
10023060-44 = ""
10023060-46 = "ทุกคนไม่ค่อยหวั่นไหวกันเท่าไรเลยแฮะ? พอเจอเรื่องเมื่อวานไปแล้ว วันนี้ก็เลยชิลได้งั้นเหรอ?"
10023060-47 = "ถ้างั้นพวกเราก็..."
10023060-48 = "[s] \"อืม เคลื่อนไหวตามที่คุยกันไว้เถอะ\""
10023060-50 = "ฉันจะดูแลภาพวาดให้เองค่ะ"
10023060-51 = "ฉันจะขึ้นไปทางบันไดชั้นบนค่ะ"
10023060-52 = ""
10023060-54 = ""
10023060-56 = ""
10023060-57 = "ส่วนอาริสึจะไปสแตนด์บายเพื่อลอบยิงจากในห้องโถงกลางค่ะ!"
10023060-58 = "ฉันจะไปซ่อนตัว... เพื่อสังเกตการณ์ค่ะ..."
10023060-59 = "[s] \"สู้เค้านะทุกคน!\""
10023060-62 = ""
10023060-63 = "......"
10023060-64 = "......"
10023060-66 = "......"
10023060-68 = "ทำไมไม่เกิดเรื่องอะไรเลยล่ะ?!"
10023060-69 = ""
10023060-73 = "(ตอนนั้นเองก็มีบางอย่างเหมือนลูกแก้วใสกลิ้งมาอยู่ใต้เท้า)"
10023060-74 = "(หยิบขึ้นมาดูดีกว่า...)"
10023060-75 = ""
10023060-78 = "สวัสดีค่ะ ได้ยินเสียงฉันไหมคะ?"
10023060-79 = "[s] \"ใครน่ะ...?\""
10023060-81 = "ลูกแก้วนี้เป็นอุปกรณ์ของฉันเองค่ะ ข้างในมีลำโพงแบบปรับความยาวคลื่นได้ค่ะ นอกจากพวกเราแล้ว#nจะไม่มีใครได้ยินการสนทนานี้ค่ะ"
10023060-82 = "[s] \"เธอคือ...?\""
10023060-83 = "ชู่ว เอาไว้ก่อน"
10023060-84 = "เราไม่มีเวลาแล้วค่ะ ไม่แน่ว่าบางที ตอนนี้พวกเราทุกคนกำลังถูกหลอกอยู่ก็ได้นะคะ"
10023060-85 = "[s] \"ถูกหลอกอยู่เหรอ? ใครหลอก?\""
10023060-86 = "เดี๋ยวก็จะรู้กันแล้วละค่ะ ยิ่งถ้าไขปริศนาในจดหมายเตือนได้ถูกต้อง ก็จะยิ่งรู้ได้ไวขึ้นค่ะ"
10023060-87 = "น่าเสียดายที่การสนทนาต้องจบแค่นี้ค่ะ ตอนนี้ฉันจะมุ่งหน้าไปยังที่ที่ต้องไปค่ะ"
10023060-88 = "จะปิดหูปิดตาทั้งๆ ที่รู้ว่าโดนหลอก หรือจะเสี่ยงอันตรายแล้วก้าวสู่ความจริง..."
10023060-89 = "ชีวิตคือกระบวนการแห่งการตัดสินใจค่ะ ว่าไหมล่ะคะ?"
10023060-90 = ""
10023060-93 = "[ns] \"หายไปแล้วแฮะ...\""
10023060-94 = ""
10023060-97 = ""
10023060-98 = "ไฟมาแล้วครับ!"
10023060-99 = "แล้วจอมโจรแห่งความเสน่หาล่ะ... อืม? เหมือนจะไม่ได้มาเลยนะครับ"
10023060-100 = "งั้นแปลว่านี่เป็นไฟดับธรรมดางั้นเหรอครับ?"
10023060-101 = "หรือว่าหน่วยรักษาความปลอดภัยทำงานสำเร็จอีกครั้ง?"
10023060-102 = ""
10023060-104 = ""
10023060-107 = "คุณครู เป็นอะไรเหรอ?"
10023060-108 = "[s] \"โมโมอิ ช่วยเรียกทุกคนมารวมตัวกันหน่อยได้ไหม?\""
10023060-109 = "เอ๋? แล้วเรื่องเฝ้าสถานที่ล่ะ?"
10023060-110 = "[s] \"ครูจะคุยเรื่องนั้นแหละ\""
10023060-111 = ""
10023060-113 = ""
10023060-115 = "จริงเหรอคะคุณครู?!"
10023060-116 = "ทุกคนถูกหลอกอยู่งั้นเหรอ? ถูกใครหลอกล่ะ?"
10023060-117 = "[s1] \"เรื่องนั้นครูก็ยังไม่รู้\"\n[s2] \"แต่คนนั้นบอกว่าถ้าแกะรหัสจดหมายเตือนได้ เราก็จะรู้ได้\""
10023060-120 = "แล้วเราจะเชื่อเรื่องแบบนั้นได้ยังไงกันล่ะ?"
10023060-121 = "อีกฝ่ายเป็นเจ็ดอาชญากรเลยนะ เธออาจจะโกหกอะไรอยู่ก็ได้"
10023060-122 = "... แต่ตอนมิโดริตกอยู่ในอันตราย จอมโจรแห่งความเสน่หาก็มาช่วยไว้นะ..."
10023060-123 = "นะ... นั่นมันก็น่าขอบคุณอยู่หรอก"
10023060-124 = "เธอแค่อาจจะ... ใจดีขึ้นมาแค่ครั้งเดียวก็ได้ คุณครูคิดยังไงเหรอ?"
10023060-125 = "[s3] \"อืม... ถึงจะได้ชื่อว่าเป็นเจ็ดอาชญากรก็เถอะ\"\n[s4] \"แต่ถ้าเป็นนักเรียน ครูก็อยากฟังเรื่องจากเธอนะ\""
10023060-128 = "อืม ก็คุณครูเป็นคนอย่างนั้นนี่เนอะ..."
10023060-130 = "แต่นอกจากเรื่องนั้นแล้ว... มันมีจุดที่ยังค้างคาใจอยู่หน่อยค่ะ"
10023060-131 = "'ด้านหลังของแอนทิคีเธรา'... ตอนที่เราอ่านคำนี้ คุณเมทาโร่มีท่าทีแปลกๆ ค่ะ"
10023060-132 = "ใช่ ฉันก็คิดแบบนั้นเหมือนกัน! พอถามว่าต้องตีความจดหมายเตือนเพิ่มอีกหรือเปล่า เขาก็บอกว่าไม่#nต้องตีความอะไรแล้วก็ได้!"
10023060-133 = "แถมยังบอกว่าให้ดูแลรูปอัศวินอย่างเดียวก็พอแล้ว แบบนี้ฉันว่าเป็นการคอนเฟิร์มที่ง่ายไปหน่อย..."
10023060-135 = "อาริสึรู้สึกว่ามันแปลกๆ ตั้งแต่ก่อนหน้านี้แล้วค่ะ ตอนนี้คุณเมทาโร่อยู่ที่ไหนก็ไม่รู้ด้วยค่ะ"
10023060-136 = "อ่า... ฉันก็เฝ้าดูห้องโถงกับประตูหน้าอยู่... แต่ไม่เห็นคุณเมทาโร่เลยค่ะ..."
10023060-137 = "[s] \"มีใครตรงนี้เห็นคุณเมทาโร่ไหม?\""
10023060-138 = ""
10023060-140 = ""
10023060-142 = "แบบนี้แปลกๆ นะ? ฝากให้เราเฝ้ารูปวาด แต่เจ้าตัวดันหายไปไหนซะงั้น?"
10023060-143 = "จะว่าไป ตั้งแต่ก่อนเริ่มนิทรรศการ คุณเมทาโร่เขา..."
10023060-144 = "[s5] \"ฮืม... คนที่บอกว่าต้องเฝ้ารูปวาด\"\n[s6] \"พอรู้ว่าจอมโจรโผล่มาก็ไปซ่อนตัวทันทีเลย\""
10023060-147 = "ประโยคไหนในจดหมายเตือนที่ยังไม่ได้ตีความเหรอคะ? "
10023060-148 = "ท่อนที่บอกว่า 'ที่ที่แสงจันทร์สาดไม่ถึง ด้านหลังของท่าเต้นที่หยุดแล้วกับแอนทิคีเธรา'......"
10023060-149 = "มิโดริ ตอนนั้นบอกว่าท่าทีของคุณเมทาโร่มันแปลกๆ ไปใช่ไหม?"
10023060-150 = "อื้ม เหมือนกับว่าเขาพยายามพูดเปลี่ยนเรื่องอย่างนั้นแหละ..."
10023060-151 = "แอนทิคีเธรา... แอนทิคีเธรา..."
10023060-152 = ""
10023060-154 = ""
10023060-155 = ""
10023060-156 = "หรือว่า...?"
10023060-157 = "อ๊ะ นี่คือยูสึในโหมด <UZQueen> นี่คะ! อาริสึรู้ดีค่ะ"
10023060-158 = "[s] \"คิดอะไรออกเหรอ?\""
10023060-159 = "คุณเมทาโร่บอกไว้ว่าในคฤหาสน์นี้... มีนาฬิกาอนาล็อกเรือนใหญ่ใช่ไหมคะ...?"
10023060-160 = "อุปกรณ์แอนทิคีเธรา... อุปกรณ์ทางปฏิทินที่ซับซ้อน ที่เอาไว้คำนวณการเคลื่อนไหวของวัตถุท้องฟ้า..."
10023060-161 = "ถ้าคิดแบบง่ายๆ จะมองว่าเป็นนาฬิกาแบบหนึ่งก็ได้..."
10023060-162 = ""
10023060-165 = ""
10023060-170 = ""
10023060-171 = "นี่สินะคะ นาฬิกาอนาล็อกที่ว่า"
10023060-172 = "ตอนนี้ฉันพอจะรู้แล้วละค่ะว่าท่าเต้นที่หยุดแล้วนั่นคืออะไร"
10023060-173 = ""
10023060-175 = ""
10023060-176 = ""
10023060-177 = ""
10023060-178 = "มีรูปปั้นของนักเต้น... ยืนขนาบข้างอยู่กับนาฬิกาค่ะ"
10023060-179 = "[s] \"หยุดเต้นอยู่จริงด้วย\""
10023060-180 = "อืม... แต่ข้างหลังนาฬิกากับรูปปั้นไม่มีอะไรอยู่เลยนะ?"
10023060-181 = "ช่วยรอก่อนสักครู่นะคะ ลายกระเบื้องปูพื้นตรงนี้มันเหลื่อมๆ เป็นวงกลมค่ะ"
10023060-182 = ""
10023060-184 = ""
10023060-185 = "เหมือนว่าเราสามารถหมุนกระเบื้องเพื่อปรับลายได้เลยค่ะ"
10023060-186 = ""
10023060-188 = ""
10023060-189 = "(โทคิเข้าไปหมุนกระเบื้องอย่างสุขุม)"
10023060-190 = "(และตอนนั้นเอง...!)"
10023060-191 = ""
10023060-195 = ""
10023060-197 = "!!!"
10023060-199 = "[ns] \"กำแพงเปิด.. และมีบันไดออกมาด้วย?!\""
10023060-200 = "บันไดสู่ชั้นใต้ดินสินะคะ"
10023060-201 = "'ที่ที่แสงจันทร์สาดไม่ถึง...' คือแบบนี้เอง"
10023060-202 = "ฉันพอจะเข้าใจแล้วค่ะว่าทำไมคุณเมทาโร่ถึงพูดอ้อมค้อม"
10023060-203 = "[s] \"ถ้างั้น... ข้างใต้นี้จะมีอะไรอยู่กันนะ?\""
10023060-204 = "ฉันไม่รู้ขนาดนั้นหรอกค่ะ แต่หากคุณเมทาโร่กับจอมโจรแห่งความเสน่หาต่างมุ่งหน้ามาที่นี่ละก็..."
10023060-206 = "มะ... ไม่เป็นไรคุณครู! พวกเราชมรมพัฒนาเกมจะปกป้องคุณครูเอง!"
10023060-207 = "พูดเสียงสั่นแบบนั้น มันยิ่งฟังดูไม่น่าเชื่อถือนะพี่"
10023060-209 = "ใช่ค่ะ C&C ก็อยู่ที่นี่ด้วยทั้งคนนะคะ"
10023060-210 = "เราคือสหายที่ตกลงจะร่วมมือกันแล้วนี่คะ งั้นฉันก็จะไปด้วยค่ะ"
10023060-211 = "[s] \"ครูจะเชื่อใจทุกคนนะ!\""
10023060-213 = "รีเฟรชเงื่อนไขเควส! จากนี้คือการผจญภัยในดันเจี้ยนค่ะ! เป็นแนวที่อาริสึชอบเลยค่ะ!"
10023060-214 = "คุณครูต้องมาอยู่ข้างๆ อาริสึนะคะ อาริสึคือผู้กล้า ส่วนคุณครูคือมาสคอตยังไงล่ะคะ!"
10023060-215 = "[s] \"รับทราบ ครูจะเชื่อใจผู้กล้านะ\""
10023060-216 = "ต้องระวังตัว... ด้วยนะคะ คุณครู..."
10023060-217 = "ถ้ากลัวก็มาซ่อนในกล่องได้นะคะ... ถ้านอนขดๆ ตัวหน่อย ก็น่าจะเข้าไปสองคนได้ค่ะ"
10023060-218 = "[s] \"งั้นก็... เข้าไปแล้วระวังตัวกันด้วยนะ!\""
