[translation]
10023010-1 = "Episode 1; Super Momoi Tornado!"
10023010-4 = "Augh! I misclicked!"
10023010-5 = "I got it! Just one more shot!"
10023010-6 = "You're trying to execute a strong attack in a frame battle?! Bold! I like it!"
10023010-7 = "But, too bad! Fall victim to my new special move!"
10023010-8 = "Kneel in front of the Super Momoi Tornado!"
10023010-10 = "Command CD! A, A, B, B, C, C, A, B, C, C, C, and cancel!"
10023010-11 = ""
10023010-13 = ""
10023010-20 = "I'm not done yet! Super Momoi Combo!"
10023010-21 = "Left, right, crouch!"
10023010-22 = ""
10023010-24 = ""
10023010-25 = ""
10023010-26 = ""
10023010-27 = "Left, right, crouch AB!"
10023010-28 = ""
10023010-36 = "The Super Momoi Tornado!"
10023010-37 = ""
10023010-51 = "*thud* *flop*"
10023010-52 = "Momoria Wins!"
10023010-55 = "Hahaha! Victory is mine!"
10023010-56 = "That battle...went on...forever..."
10023010-57 = "My countless defeats against Yuzu...against Midori and Aris and even...even Sensei!"
10023010-58 = "I've finally overcome my losing streak! Today's win will be the catalyst for my rebirth!"
10023010-59 = "People will forever mark this day as the beginning of Momoria's rise to greatness!"
10023010-60 = "E-Excuse me, you're here, like, all the time right?"
10023010-61 = "People have been talking about the student who refuses to leave the arcade until they get a win, every single night..."
10023010-62 = "Who's been saying that? Huh?! It's not just until I get a win!"
10023010-63 = "See, it is her! She gets super defensive if you talk about winning around her."
10023010-64 = "Wow... Does that mean all the rumors are true...?"
10023010-65 = "Does my reputation precede me? Am I famous?!"
10023010-66 = "You must be...the Little Menace!"
10023010-67 = ""
10023010-69 = ""
10023010-70 = "Come again?"
10023010-71 = "Who exactly are you calling the Little Menace?"
10023010-72 = "You, duh! You've been the talk of the arcade recently."
10023010-73 = "You're the one who spams special moves until one connects whenever you're backed into a corner, right?"
10023010-74 = "Right, right! Hey, is it true that if you lose you won't let the other player go home until you beat them? And that if you can't beat them, you'll break the machine and run away screaming?!"
10023010-75 = "That's going way too far! You're making me sound like a bad person!"
10023010-76 = "And what's this nonsense about me spamming special moves when—"
10023010-77 = "Actually...well, that one might be a little true..."
10023010-78 = "Check your socials! People are already posting that the Little Menace is here!"
10023010-79 = "No way? Oh my god. You're right! It's everywhere!"
10023010-80 = "What in the world is happening? Is this real life?"
10023010-81 = ""
10023010-84 = "Why are there so many of you? Where did you come from?!"
10023010-85 = "I told you! It's really her. The Little Menace!"
10023010-86 = "Okay, fine. You were right. Can we go now? I heard she'll force you to play with her all night...at gunpoint, if necessary!"
10023010-87 = "Can someone please explain to me where the name \"Little Menace\" even comes from?!"
10023010-88 = "I'm a really nice person, and I'm not violent either! I'm just a regular, passionate gamer!"
10023010-89 = "I am honored to finally meet the infamous Little Menace."
10023010-90 = ""
10023010-92 = ""
10023010-93 = "Do I know you?!"
10023010-94 = ""
10023010-95 = "I know of you, but you do not know me. My apologies. I am Doda Meitaro."
10023010-96 = "Let us not mince words. I am here to request your services. You are the only one who can help, Little Menace."
10023010-97 = "I'm trying to tell you! I'm not this Little Menace—"
10023010-98 = "Please! It is well within your capabilities. A simple cleaning job."
10023010-99 = "Huh? Really? Just cleaning...?"
10023010-100 = "Yes, that is all. Surely it would be no issue for the likes of you?"
10023010-101 = "W-Well, yeah, sure. I guess cleaning isn't all that hard. But I really feel like you could've asked anybody..."
10023010-102 = "This request was meant for the Little Menace and only the Little Menace. "
10023010-103 = "Thank you for accepting. Here are your next steps."
10023010-104 = "You'll find what you need in that letter, including the declared time and place."
10023010-105 = "Hold on just one second! Slow down!"
10023010-106 = "I look forward to working with you, Little Menace..."
10023010-108 = "Or should I say, Mikamo Neru of C&C."
10023010-109 = ""
10023010-111 = ""
10023010-113 = ""
10023010-114 = "...What?!"
10023010-116 = "...And that just about sums it up."
10023010-117 = "..."
10023010-118 = ""
10023010-120 = ""
10023010-121 = "..."
10023010-122 = "?"
10023010-123 = ""
10023010-125 = ""
10023010-126 = ""
10023010-127 = "Momoi..."
10023010-128 = "Y-Yes?!"
10023010-129 = "Why do you always have to rope us into your messes? You need to learn how to say \"no\" to people!"
10023010-130 = "You weren't there, so you don't get it! I really did try to say something, but I was utterly overpowered... "
10023010-131 = ""
10023010-133 = ""
10023010-134 = "I do not get it either. But I understand that our party has accepted a new quest! Bum bum bum!"
10023010-135 = "A-A new quest...means... We're going to go outside?"
10023010-137 = "Waaah! I don't know how to get myself outta this mess! I messed up again!  "
10023010-138 = "You're right! I should've just said no! I-I'm sowwy...! *sniff*"
10023010-139 = "*sigh* ...You said it's just a cleaning job?"
10023010-140 = "Yup! Pinky promise! I even double-checked!"
10023010-141 = "Well, if it's just a cleaning job... You did say it's something anyone can do."
10023010-142 = "Although, if someone is hiring someone to clean for them, that normally means they need a professional... It won't be easy."
10023010-143 = "Wait! Are you gonna help me, Mido? Really? Really, really?!"
10023010-144 = "You don't have any way of backing out, and we're not just gonna abandon you."
10023010-145 = "So, yeah. We'll pretend that we're C&C members and clean like our lives depend on it."
10023010-146 = "Waaahhh! You're the best, ever! I'm so lucky to have shared a womb with someone like you!"
10023010-147 = "Get off me before I change my mind!"
10023010-148 = ""
10023010-150 = ""
10023010-151 = "I have to leave the clubroom... And go meet people... And talk to them... A-And... And...! Augh...!"
10023010-152 = "We're by your side, Yuzu! You won't be alone!"
10023010-153 = "Rage... Annihilation... Fear... The end of the world inches...ever closer... Despair upon us all...!"
10023010-154 = "Quest accepted! It is quest time! Quest time! Heehee!"
10023010-155 = "So, that being said... Help us out, Sensei!"
10023010-156 = "[s] \"Huh? Me?!\""
10023010-158 = "Duh! With Sensei's authority, we can go pretty much anywhere we want!"
10023010-159 = "And we need a temporary advisor if our client has any hard questions."
10023010-160 = "Isn't it an adult's job to come up with excuses or whatever?"
10023010-161 = "[s] \"We need to discuss your perspective on adults, Momoi...\""
10023010-162 = "If Sensei comes, I will be a fearless hero! After all, it is the mascot that helps the hero be strong and brave. Please join our party, Sensei!"
10023010-163 = "I-I know it's an imposition...but I don't know how I'll find the nerve...without you there, Sensei..."
10023010-164 = "[s1] \"Well, if you put it that way...\" \n[s2] \"Serving as an advisor is part of my responsibilities!\""
10023010-165 = "You mean it, Sensei?! I knew we could count on you!"
10023010-166 = "You mean it, Sensei?! I knew we could count on you!"
10023010-167 = "Nice! As our first order of business, I have a request for our new temporary advisor!"
10023010-168 = "[s3] \"Things are getting good!\" \n[s4] \"Let's do it! What's our first move?\""
10023010-169 = "Find us some maid uniforms!"
10023010-170 = "Find us some maid uniforms!"
10023010-171 = "[s] \"...Come again?\""
10023010-173 = "Toki's Office"
10023010-174 = ""
10023010-175 = "[ns] \"...And that's how I ended up here.\""
10023010-176 = "I have a grasp of the situation."
10023010-177 = "[s] \"Please don't tell Neru... She'd be really, really mad...\""
10023010-178 = "And you didn't think I would be?"
10023010-179 = "[s] \"Ah... Well... I just thought that you'd maybe...want to help me?\""
10023010-180 = "...Understood."
10023010-181 = "Okay. Rest assured. I will protect your secret to my last bullet."
10023010-182 = "[s] \"Thank you! I'll repay you for this one day. I promise.\""
10023010-183 = "Yes. I won't forget that."
