[translation]
10028050-1 = "ตอนที่ 5;รถไฟด่วนสายนรก "
10028050-4 = ""
10028050-6 = ""
10028050-8 = ""
10028050-10 = "...เอ่อ... คือว่า..."
10028050-11 = "ฉันไม่คิดว่าจะเกิดเรื่องแบบนั้นหรอกนะ..."
10028050-12 = "แต่ก็เผื่อๆ ไว้น่ะ..."
10028050-13 = "คุณครูกับเด็กชมรมทวงความยุติธรรมของทรีนิตี้คนนี้..."
10028050-14 = "ไม่ได้ \"เจรจาร่วมมือกับผู้ก่อการร้าย\" อะไรทำนองนั้นใช่มั้ย? ใช่รึเปล่า?"
10028050-15 = "วะฮ่าฮ่าฮ่าฮ่า!! อิโอริ~ อิโอริจังนี่ละก็นะ~"
10028050-16 = "รู้อะไรรึเปล่า? ตอนนี้เธอพูดแบบนั้นออกมาได้อย่างหน้าชื่นตาบานเพราะเธอไม่รู้ว่ามันมีอะไรอยู่ใน#nกระเป๋าใบนี้น่ะ"
10028050-17 = "นี่ไม่ใช่แค่สิ่งของธรรมดา แต่เป็นถึง 'ของสืบทอด' ของทรีนิตี้เชียวนะ?"
10028050-18 = "และถึงฉันจะได้ฟังมาแค่คร่าวๆ ก็เถอะ..."
10028050-19 = ""
10028050-21 = ""
10028050-23 = ""
10028050-24 = ""
10028050-27 = ""
10028050-29 = ""
10028050-31 = ""
10028050-32 = "แต่ทรีนิตี้เป็นโรงเรียนขนาดใหญ่ที่มีอิทธิพลต่อทางการเมืองเลยนะ"
10028050-33 = "หะ... หืม...? ขะ... ของสืบทอด...? ของสืบทอดของทรีนิตี้...?"
10028050-34 = "แล้วทำไมมันถึงมาอยู่ที่นี่..."
10028050-35 = "เอาละๆ งั้นก็อย่าทำให้เรื่องมันยุ่งยากนักเลย~"
10028050-36 = "ในเมื่อมันเป็นแบบนั้น งั้นพวกเราทุกคนก็... มาจริงใจต่อกันกว่านี้อีกสักหน่อยดีมั้ย? ตอนจบที่ทุกคน#nคาดหวังอาจจะไม่ได้อยู่ไกลเกินคาดก็ได้"
10028050-37 = "อิโอริ เราแค่ต้องหยุดรถไฟนี้ แล้วคุมตัวเจ้าหน้าที่และเจ้าพวกแก๊งอันธพาลที่อยู่บนรถไฟนี้ไป เป้าหมายเดิมเป็นแบบนี้ใช่มั้ยล่ะ?"
10028050-38 = "ส่วนคนอย่างฉันน่ะ ไม่จำเป็นต้องจับให้ได้ภายในวันนี้ก็ได้ไม่ใช่เหรอ? ไม่สิ ต้องบอกว่าเก็บไว้สนุก#nวันอื่นก็ได้นี่นา"
10028050-39 = "ส่วนคุณหนูทรีนิตี้ ก็แค่ต้องถือกระเป๋านี้ลงสถานีถัดไปอย่างชิลๆ~"
10028050-40 = "ส่วนฉันก็...?"
10028050-41 = "จริงๆ ทุกคนก็แค่... ไม่ต้องสนใจฉันก็พอแล้ว ฉันจะหายไปอย่างเงียบๆ เอง"
10028050-42 = "ได้ยินแล้วใช่มั้ย? ตอนนี้พวกเราไม่จำเป็นต้องมาทะเลาะใหญ่โตหรอกนะ~ ว่ามั้ย? เราต่างมีเรื่องที่ต้อง#nไปทำกันไง"
10028050-43 = "แล้วก็ช่วยทำเป็นหลับหูหลับตาที่บังเอิญเจอฉันบนรถไฟขบวนเดียวกันสักหน่อย... เท่านั้นเอง"
10028050-44 = "โธ่เอ๊ย~ ทำไมเป็นอย่างนี้กันล่ะ~ ทุกคนไม่ใช่คนที่เพิ่งทำงานมาแค่วันสองวันสักหน่อย..."
10028050-45 = "ปกติแล้วเรื่องราวในโลกมันไม่ได้พอดีเป๊ะไปทุกอย่างหรอกนะ ทุกคนก็รู้กันนี่นา? ใช่มั้ย?"
10028050-46 = "เอาละ! ว่าไงล่ะ อิโอริ? วันนี้เราแยกย้ายไปตามทางของตัวเองก่อนมั้ย...?"
10028050-47 = "ฉันว่าแบบนี้..."
10028050-48 = "...มันก็ไม่ได้แย่เท่าไรนะ?"
10028050-49 = "เอาแต่พูดอะไรเหลวไหลอีกแล้ว!! ถ้าไม่เจอเธอตั้งแต่แรกก็ว่าไปอย่าง แต่นี่ฉันเจอเธอแล้ว คิดว่าฉัน#nจะปล่อยไปง่ายๆ งั้นเหรอ!?"
10028050-50 = "อีกอย่าง ธุระของทางทรีนิตี้ก็ไม่เกี่ยวกับการปฏิบัติหน้าที่ของฉันด้วย!! ตอนนี้สิ่งที่สำคัญคืองานของ#nฉันต่างหาก!"
10028050-51 = ""
10028050-53 = ""
10028050-54 = "........."
10028050-55 = "......ฮู่ว......"
10028050-56 = "[s1] \"......???\"\n[s2] \"อิจิกะ...?\""
10028050-59 = ""
10028050-60 = "ฮึ่ม~ งั้นเหรอ? ก็ไม่รู้สินะ~?"
10028050-61 = "นั่นคือความคิดของคณะกรรมการวินัย... ไม่สิ ของอิโอริจังคนเดียวหรือเปล่า~?"
10028050-62 = "ถึงยังไงตอนนี้กระเป๋าก็อยู่ในมือฉัน..."
10028050-63 = "แบบนี้คุณหนูทรีนิตี้คนนั้นกับคุณครูก็ต้องมาอยู่ข้างฉันน่ะสิ~ ใช่มั้ย คุณหนู~?"
10028050-64 = "........."
10028050-65 = "อย่าเอาแต่ยกเรื่องนั้นมาพูดเลย! นั่นมันคนละเรื่องกัน! และฉันก็ไม่จำเป็นต้องรู้ด้วย!!"
10028050-66 = "ฉันไม่ได้บอกว่าจะกักขังทั้งคู่สักหน่อย ในเมื่อเกิดเรื่องแบบนี้แล้ว ฉันก็แค่จะสอบสวนอะไรนิดๆ หน่อยๆ ก็เท่านั้นเอง!"
10028050-67 = "........."
10028050-68 = "เอาละๆ งั้นก็มาดูการตัดสินใจของทั้งสองคนนี้กัน ยังไงก็ต้องเลือกแก้วชา...? กระโถน? หรืออะไรสัก#nอย่างนี่แล้วมาอยู่ข้างฉันอยู่แล้วละ"
10028050-69 = "ใช่มั้ย? คุณหนูชมรมทวงความยุติธรรม... ที่ชื่ออะไรนะ?"
10028050-70 = "...นิกะจัง?"
10028050-71 = "จะให้ของในกระเป๋าแตกไม่ได้ ใช่มั้ยล่ะ?"
10028050-72 = "........."
10028050-73 = "เฮ้อ~!! ให้ตายเถอะ!! เอาแต่พล่ามเรื่องกระเป๋ามาตั้งแต่เมื่อกี้แล้ว! กระเป๋าของพวกนั้นน่ะ...!!"
10028050-74 = "........."
10028050-75 = "มันจะสำคัญอะไรกันนักกันหนาถึงได้เอามาพูดอยู่ได้...!!"
10028050-76 = ""
10028050-80 = ""
10028050-81 = ""
10028050-82 = ""
10028050-83 = ""
10028050-84 = ""
10028050-85 = ""
10028050-86 = "โอ๊ะ!"
10028050-87 = "...ฮะฮ่า..."
10028050-88 = "ฮะฮ่า! ฮ่าฮ่าฮ่า!!"
10028050-89 = "วะฮ่าฮ่าฮ่าฮ่าฮ่า!!!!"
10028050-90 = "ดูเข้าสิ! ดูสิๆ เป็นอย่างที่คิดไว้เลย ฉันบอกไปตั้งกี่ครั้งแล้วล่ะ?"
10028050-91 = "โธ่ถัง~ อิโอริหนอ อิโอริ~ อิโอริหัวทึบเอ๊ย~!"
10028050-92 = "ทำไมถึงเลือกแต่การต่อสู้ที่ตัวเองแพ้ตลอดเลย~ ถึงได้บอกไงว่าสุดท้ายแล้วฉันก็จะชนะในการต่อสู้#nครั้งนี้"
10028050-93 = "จนกว่าฉันจะให้กระเป๋า... เด็กคนนั้นไม่มีทาง..."
10028050-94 = "ทำอะไรฉัน..."
10028050-95 = ""
10028050-99 = ""
10028050-100 = "เฮือก...!?"
10028050-101 = ""
10028050-102 = ""
10028050-103 = ""
10028050-104 = ""
10028050-105 = ""
10028050-106 = ""
10028050-107 = ""
10028050-108 = ""
10028050-109 = ""
10028050-110 = ""
10028050-112 = "[ns] \"......?\""
10028050-114 = "[ns] \"......!?!?!?!?\""
10028050-117 = ""
10028050-118 = "......อ่า"
10028050-119 = "...เผลอยิงไปจนได้"
10028050-120 = "แหะๆ ไม่น่าเลย"
10028050-121 = "ขอโทษค่า~! พอดีฉันหงุดหงิด ก็เลยเผลอไป~"
10028050-122 = "เผลอไป... ไม่รู้ตัว... อืมม~..."
10028050-123 = ""
10028050-125 = ""
10028050-126 = "...แหะๆ!"
10028050-127 = "[ns3] \"อิจิกะะะะะะ?!?\"\n[ns4] \"กระเป๋า... กระเป๋า...!! แล้วของข้างใน...!?\""
10028050-130 = "อะฮ่าฮ่าฮ่า! นั่นสินะคะ กระเป๋าร่วงไปแล้วละค่ะ!"
10028050-131 = "แต่ก็..."
10028050-132 = "จะให้ทำไงได้ล่ะคะ? เราทำมันไปแล้วนี่นา ค่อยมาเปิดของข้างในดูทีหลังเถอะค่ะ"
10028050-133 = "ฉันก็ไม่รู้แล้วเหมือนกันค่ะ มันคงจะแตกหมดแล้วด้วย อืม ก็ไม่แปลกหรอกนะคะ"
10028050-134 = "เพราะงั้น ไหนๆ ก็เป็นแบบนี้แล้ว"
10028050-135 = "ถ้าต้องเป็นฉันคนเดียวก็คงไม่ยุติธรรม เพราะงั้นทุกคนก็..."
10028050-136 = ""
10028050-137 = ""
10028050-138 = ""
10028050-139 = ""
10028050-140 = ""
10028050-141 = ""
10028050-142 = ""
10028050-144 = ""
10028050-145 = "...ไปลงนรกด้วยกันกับฉันหน่อยนะคะ"
10028050-146 = ""
10028050-154 = "อะฮ่าฮ่าฮ่าฮ่า! ฮ่าฮ่า ฮ่าฮ่าฮ่า! อะฮ่าฮ่าฮ่าฮ่าฮ่า!!!!!!"
10028050-155 = "อะ... อะไรเนี่ย!? ยะ... ยัยเด็กนั่น... อ๊ากกกก~!!"
10028050-156 = "ควบคุมไม่ได้เลย! ใครก็ได้หยุดยัยเด็กนั่นที!!"
10028050-157 = "อ๊ากกก บ้าไปแล้ววววววว!!!"
10028050-158 = ""
