[translation]
10023100-1 = "ตอนที่ 10;ทุกท่านโปรดทราบ นี่เรื่องสำคัญค่ะ"
10023100-2 = ""
10023100-3 = "... วางแผนไว้ตั้งแต่แรกแล้วสินะคะ"
10023100-4 = "ตายจริง เราต่างแค่แสวงหาสิ่งที่ล้ำค่าของตัวเองกันเท่านั้นค่ะ"
10023100-5 = "<มงกุฎเจ้าแห่งนาฬิกา> คือภารกิจของคุณ และสำหรับฉันแล้ว มันคืองานศิลปะและสุนทรียศาสตร์ค่ะ"
10023100-6 = "ปกติคุณเป็นคนแบบนี้เหรอคะ?"
10023100-7 = "แบบนี้... หมายถึงแบบไหนเหรอคะ?"
10023100-8 = "คนที่ทำได้ทุกอย่างเพื่อเป้าหมายของตัวเอง? หรือคนที่หักหลังพันธมิตรได้อย่างง่ายดายหากจำเป็น?"
10023100-9 = "ถ้าไม่ใช่ทั้งสองอย่าง หรือว่าจะเป็นคนที่สละได้ทุกอย่างเพื่อสิ่งที่ตัวเองเชื่อมั่น?"
10023100-10 = "......"
10023100-11 = "หากคุณต้องการคำตอบจริงๆ ฉันก็จะตอบให้ค่ะ"
10023100-12 = "ฉันคือทั้งหมดนั่นแหละค่ะ "
10023100-14 = "ฉันไม่เข้าใจคุณเลยค่ะ"
10023100-15 = "ตายจริง ฉันไม่ได้คาดหวังเลยนะคะ"
10023100-16 = "มีบางคนที่เคยบอกว่าเข้าใจฉันค่ะ แต่สุดท้ายก็ฝากไว้เพียงคำหลอกลวงแล้วก็ทิ้งกันไป"
10023100-17 = "\"ฉันไม่เห็นจะเข้าใจเลย ยกโทษให้ไม่ได้ เธอมันเป็นปีศาจ...\""
10023100-18 = "พวกคุณก็คงจะเป็นอย่างนั้นสินะคะ คุณครูที่อยู่ตรงนั้นก็ด้วย"
10023100-19 = "ฉันคิดว่ามันมีวิธีแก้ไขปัญหาอย่างอื่นอยู่นะคะ"
10023100-20 = "งั้นฉันขอถามอะไรสักอย่างค่ะ สมมติว่าฉันไม่ได้เอามงกุฎไป คุณคิดว่าหลังจากนั้นจะเกิดอะไรขึ้นกับ#nมงกุฎเหรอคะ?"
10023100-21 = "เมทาโร่ก็คงถูกจับกุม และมงกุฎก็จะถูกส่งไปอยู่ในคลังของที่ถูกยึดของวัลคิรี่จนกว่าข้อกล่าวหาจะได้#nรับการพิสูจน์ค่ะ"
10023100-22 = "งั้นเหรอคะ งานศิลปะที่ต้องแบ่งปันกับสาธารณะต้องไปถูกทิ้งให้ฝุ่นเกาะในที่แบบนั้นเหรอคะ?"
10023100-24 = "... ถ้าเป็นแบบนั้น ต่อไปก็น่าจะถูกเก็บไว้ในโซนจำกัดอย่างในพิพิธภัณฑ์นะ?"
10023100-26 = "ก็คงอย่างนั้นค่ะ งานศิลปะนั้นก็คงถูกตัดสินว่าควรเปิดเผยหรือไม่ และหนำซ้ำยังถูกตัดสินโดยคนที่#nไม่รู้จักคุณค่าที่แท้จริงของมันด้วยค่ะ"
10023100-27 = "คุณต้องการสื่ออะไรเหรอคะ จอมโจรแห่งความเสน่หา?"
10023100-28 = "ที่ฉันจะบอกก็คือ ไม่ว่าทางไหนก็ไม่ถูกทั้งนั้นค่ะ "
10023100-29 = ""
10023100-31 = ""
10023100-33 = ""
10023100-34 = ""
10023100-35 = ""
10023100-37 = "ไม่ได้นะคะ!"
10023100-38 = "อาริสึต้องการมงกุฎนั้นเพื่อเคลียร์เควสค่ะ!"
10023100-40 = "ฮุฮุ ฉันไม่น่าจะให้ได้นะคะ"
10023100-41 = "สิ่งเดียวที่ฉันสนใจก็คือ... การที่งานศิลปะของทุกคนได้อยู่ในที่ที่มันควรอยู่ค่ะ"
10023100-42 = "เจรจาไม่เป็นผล... สินะคะ?"
10023100-43 = "ถึงจะได้เป็นพันธมิตรกันแค่ชั่วคราว แต่มันก็สนุกดีค่ะ"
10023100-44 = "ฉันไม่อยากให้เรื่องมันจบแบบนี้เลยค่ะ"
10023100-45 = "ฉันเองก็ไม่ต่างกันหรอกค่ะ"
10023100-46 = "แต่ฉันไม่ชอบอะไรที่มันยุ่งเหยิงน่ะค่ะ"
10023100-47 = "ฉันจะต้องคงความสมบูรณ์แบบ สละสลวย สวยงาม อย่างที่เคยเป็นมาตลอดค่ะ"
