[translation]
1002403-1 = "#title;나만의 서포터"
1002403-2 = "#na;(시로코가 말해준 예상시간 쯤, 알려준 해안도로의 중간 지점으로 미리 나가 있었다.)"
1002403-3 = "#na;(멀리서부터 자전거를 타고 빠르게 다가오던 시로코의 모습이 보였다.)"
1002403-4 = "3;시로코 라이딩;00;……!?\n#3;stiff\n#3;a"
1002403-5 = "3;시로코 라이딩;00;……선생님?"
1002403-6 = "3;시로코 라이딩;04;어째서 여기에……?\n#3;em;[땀]"
1002403-7 = "[s1] \"컨디션 체크 겸 와봤지.\"\n[s2] 손을 흔들어 보인다."
1002403-8 = "3;시로코 라이딩;01;선생님……."
1002403-9 = "3;시로코 라이딩;01;선생님……."
1002403-10 = "3;시로코 라이딩;02;어……. 손에 든 그건……? 에너지 드링크?\n#3;em;[?]"
1002403-11 = "3;시로코 라이딩;02;새 타올까지……. 나를 위해 준비한 거야?"
1002403-12 = "3;시로코 라이딩;01;굳이 이렇게 안 해줘도 스스로 챙긴 것들이 조금은……."
1002403-13 = "3;시로코 라이딩;04;……아, 아니. 고마워. 잘 받을게.\n#3;em;[땀]\n#3;stiff"
1002403-14 = "3;시로코 라이딩;99;……으음……."
1002403-15 = "3;시로코 라이딩;01;아니. 아무 것도. 음…….\n#3;em;[반응]"
1002403-16 = "3;시로코 라이딩;06;역시 걱정 끼치고 있는 걸까? 선생님한테……."
1002403-17 = "3;시로코 라이딩;01;……응? 아니라고?\n#3;em;[?]"
1002403-18 = "3;시로코 라이딩;04;그치만 이렇게 굳이 나와서, 드링크도 주고 타올도……."
1002403-19 = "[s] \"서포터 같은 거라고 생각하면 돼.\""
1002403-20 = "3;시로코 라이딩;01;……!\n#3;em;[!]"
1002403-21 = "3;시로코 라이딩;01;서포터……."
1002403-22 = "3;시로코 라이딩;99;선생님이……"
1002403-23 = "3;시로코 라이딩;03;내 사이클 서포터…….\n#3;em;[반짝]"
1002403-24 = "[s] \"시로코?\""
1002403-25 = "3;시로코 라이딩;02\n#3;em;[반응]\n#wait;1500"
1002403-28 = "#st;[-1200,-530];serial;60;[wa:1200]― ……고마워,[wa:950] 선생님."
1002403-31 = "#st;[-1200,-530];serial;60;[wa:2250]― 그,[wa:1100] 뭐라고 해야 할까……."
1002403-33 = "#st;[-1200,-630];serial;60;― 이렇게[wa:1300] 누군가에게 서포트 받아보는 게[wa:2500] 처음이라……."
1002403-36 = "#st;[-1200,-530];serial;60;[wa:1200]― ……선생님과[wa:400] 함께 있으면,"
1002403-38 = "#st;[-1200,-630];serial;60;[wa:100]― 매일매일[wa:1530] 새로운 일들이 일어나네."
1002403-41 = "#st;[-1200,-530];serial;60;[wa:950]― (……?[wa:1150] 왜지?[wa:1500] 심장 소리가[wa:1450] 멈추지 않아…….)"
1002403-44 = "#st;[-1200,-530];serial;60;[wa:1250]― ……이상하네.[wa:1900] 이런 것도[wa:1250] 처음이야."
1002403-46 = "#clearST\n3;시로코 라이딩;01\n#3;h\n#3;closeup"
1002403-47 = "3;시로코 라이딩;03;고마워, 선생님. 은혜는 나중에 꼭 갚을게.\n#3;closeup"
1002403-48 = "3;시로코 라이딩;03;타올은 다시…….\n#3;closeup"
1002403-49 = "3;시로코 라이딩;01;응? 교체한 걸로 계속 쓰라고……? 으음……. 나는 좋지만…….\n#3;em;[?]\n#3;closeup"
1002403-50 = "3;시로코 라이딩;04;그럼 선생님한테 빈 병이랑 쓰던 타올을 주는 게 되는데……. 역시 좀…….\n#3;em;[땀]\n#3;stiff\n#3;closeup"
1002403-51 = "[s] \"그게 서포터가 할 일이야.\""
1002403-52 = "#st;[0,0];instant;1;"
1002403-54 = "3;시로코 라이딩;99\n#3;em;…\n#wait;2500\n#3;closeup"
1002403-55 = "3;시로코 라이딩;01;……응. 그렇게 할게.\n#3;closeup"
1002403-56 = "3;시로코 라이딩;03;왠지 힘이 나는 것 같아. 힘내서 꼭 완주할게.\n#3;closeup"
1002403-57 = "3;시로코 라이딩;99;이제는…….\n#3;closeup"
1002403-58 = "3;시로코 라이딩;03;나만의 서포터도 있으니까.\n#3;closeup\n#3;greeting\n#3;em;[하트]\n#3;closeup"
1002403-60 = "#na;(시로코에게서 라이딩 지도를 받은 후, 부실로 돌아왔다.)"
