[translation]
10027120-1 = "Chapter 12; A Typical Red Winter Day "
10027120-2 = ""
10027120-3 = "Yakumo?!"
10027120-4 = "Is that...the President?!"
10027120-5 = ""
10027120-7 = ""
10027120-9 = ""
10027120-10 = ""
10027120-11 = "A classic tale of friendship, hard work, and grit. It's so touching that I wish I could write it down somewhere to preserve it for eternity."
10027120-13 = "(...Something's up. Why is she saying such nice things?)"
10027120-15 = "But first, let's talk about that all-important manuscript you promised me."
10027120-17 = "Manuscript?"
10027120-18 = "I mean, I know you asked me to do a manuscript, but..."
10027120-20 = "(Why would she bring that up?)"
10027120-22 = "I'm glad you remember! Now, on that subject..."
10027120-23 = "I've decided I'd rather have the \"Luna\" Volume 22 you wrote instead."
10027120-24 = ""
10027120-26 = ""
10027120-28 = "Wh— Not this! There are so many reasons I can't give this up, but the most important is that I promised it to Momiji!"
10027120-29 = "Ohhh? But what about our contract?"
10027120-30 = "That's— I mean— You—"
10027120-31 = "[s] \"Does it have to be 'Luna'?\""
10027120-32 = "Yes. And I have a very good reason for that."
10027120-33 = "But you can relax. I'm not asking you to transfer ownership forever. It's more like a loan, a favor."
10027120-34 = "Granted, there's a decent chance it'll be a mid- to long-term loan."
10027120-35 = "[s] \"What do you want with a 'Luna' fanfic?\""
10027120-36 = "Y-Yeah! What are you going to do with it? I hope you don't plan to mass publish it..."
10027120-38 = "I don't care how amazing the story is or whether it's a faithful representation of the ending that never existed. You can't do that!"
10027120-39 = ""
10027120-41 = ""
10027120-43 = "..."
10027120-44 = "..."
10027120-45 = "Meru..."
10027120-47 = "What?! Am I wrong?!"
10027120-48 = "What are you talking about? I'm not a monster. I would never publish fanfic for an unfinished series and claim it was canon."
10027120-49 = "Well... Hmph! Why do you want my manuscript then?"
10027120-50 = "It's simple. But before I explain, let's recap what all the fuss has been about."
10027120-51 = "First, Meru had a fight with her friend. And she put herself through hell to make it up to her. "
10027120-52 = "Ah, but you created that hell for me, didn't you?"
10027120-53 = "Then, as if that weren't enough, she enlisted the help of Schale's famous Sensei. Never once did she hesitate to fight, reconcile, and earn the respect of her rivals..."
10027120-54 = "Hey. That's your boss. Do something about it."
10027120-56 = "There's no point asking me. This is who she is."
10027120-58 = "And at the end of it all, she gave everything to create a manuscript! It's a story of friendship, violence, hijinks, and serendipity..."
10027120-59 = "Isn't that a great story?!"
10027120-60 = "[s] \"That...sounds about right!\""
10027120-61 = "Don't you dare agree with her, Sensei!"
10027120-63 = "That is why I, Aramaki Yakumo, have come to a decision. Or rather, I'm enacting the backup plan I developed the moment Meru entered the Publishing Department."
10027120-64 = "Meru's epic, heart-wrenching adventures should be sold— I mean shown to every student in Red Winter, no, Kivotos!"
10027120-65 = "The Publishing Department will use every arrow in its considerable quiver to turn this amazing saga into a live-action movie!"
10027120-66 = ""
10027120-68 = ""
10027120-70 = "...Eh?"
10027120-71 = "...Huh?"
10027120-72 = "What...?"
10027120-73 = ""
10027120-76 = "[ns] \"Huh? The Publishing Department does that kind of thing?\""
10027120-78 = "Of course we do! Collaborations between the publishing and movie industries are all the rage these days. Whether it's an e-book adapted into a movie or a movie adapted into an e-book, it happens all the time."
10027120-79 = "It's an integral part of IP expansion, and its good business!"
10027120-81 = "Hmm... I should have known not to underestimate them once you got involved, Sensei."
10027120-82 = "Even you're impressed?!"
10027120-84 = "If you just let me borrow that manuscript, the possibilities are endless! We could even use it as promotional material! "
10027120-85 = "Don't worry. You can trust me to give it back to you. But we should discuss timeframe. It could be a while. "
10027120-86 = "Uh, how much time are we talking here?"
10027120-87 = "If we manage to stick to our timetable, we could have the movie done in about a year, maybe two?"
10027120-88 = "Why would you think I could wait that long? Or that I would just hand it over? What makes you think—"
10027120-89 = "Ahem. You're not very trusting, are you? Do not underestimate the power of the Publishing Department. We can do big things for you."
10027120-90 = "You think I have trust issues?!"
10027120-91 = "Well, if you really can't give us the full manuscript, then that's that."
10027120-92 = "You're giving up? Just like that? That's not like you. Unless... You're about to do something crazy, aren't you?"
10027120-93 = "I wouldn't call it crazy, but you should know that here in Red Winter, there are a lot of people who would be appalled at your cavalier attitude about contracts. "
10027120-94 = ""
10027120-97 = ""
10027120-98 = "...particularly those who run Red Winter. Secretariat Office! Over here!"
10027120-99 = ""
10027120-101 = ""
10027120-104 = ""
10027120-105 = ""
10027120-106 = "This horrible girl broke a promise to her friend."
10027120-107 = "Then she beat up every member of our Secretariat Office and got away with it!"
10027120-108 = "[s] \"I'm getting roped into this like I'm one of the students! This is awesome!\""
10027120-109 = "S-Sensei?! Why are you here?!"
10027120-110 = "Did you get reported for breaking the school rules?!"
10027120-111 = "[s] \"No!\""
10027120-112 = "How shameful you all are. Even you can't break Red Winter's rules and get away with it, Sensei!"
10027120-113 = "We'll detain you in the Self-Reflection Room! I'm no stranger to the room myself. Trust me. It'll be nice and cozy."
10027120-114 = "[s] \"No!\""
10027120-116 = "You're the one who dragged the Secretariat Office into this, Yakumo."
10027120-117 = "You should be more careful. Contracts can be dangerous. Hee. Hee. Hee."
