[translation]
10020005-6 = ""
10020005-7 = "Now, it's our turn."
10020005-8 = "And now the moment you've all been waiting for... The operation leader is here!"
10020005-9 = ""
10020005-11 = ""
10020005-12 = "I'll brief you all on the Ark Conquest."
10020005-13 = ""
10020005-15 = ""
10020005-17 = ""
10020005-18 = "For this conquest, we must hack the Ark within the time limit and hijack the control authority."
10020005-19 = ""
10020005-23 = "The Ark of Atrahasis is a large, multi-dimensional analysis device. This entire Ark is sort of like a supercomputer."
10020005-24 = "It is comprised of several individual computational devices that all work together to perform a multi-dimensional analysis."
10020005-25 = "With that in mind, we need to focus on occupying each area within the Ark in order to gain total control of it."
10020005-26 = "It's just like King of the Hill!"
10020005-28 = "Actually, yes. Since this conquest is basically about occupying the opponent's land, that's a fair comparison."
10020005-29 = "Our goal is to completely occupy the Ark and gain control of it. It's our only path to victory."
10020005-30 = "You see, once we have control, we can activate the Ark's Self-Destruct Sequence."
10020005-31 = "But our enemies won't make that easy. They'll be relentless throughout the entire conquest."
10020005-32 = "Fortunately, our Sensei is an expert at handling that kind of thing."
10020005-33 = "[s] \"Yes. Leave it to me.\""
10020005-34 = "Now, Aris has managed to freeze all of the Ark's functions for the time being, preventing any multi-dimensional analysis or travel."
10020005-35 = "But, of course, she can't hold it indefinitely. The moment she loses control, the Ark will disappear back into the multiverse."
10020005-36 = "And any hope of us catching the Ark disappears with it."
10020005-37 = "I'll mark the multi-dimensional analysis suppression limit."
10020005-38 = ""
10020005-40 = ""
10020005-42 = ""
10020005-43 = "This is the Conquest's time limit."
10020005-45 = "Now, I can brief you all on the Ark's internal layout."
10020005-46 = ""
10020005-48 = ""
10020005-50 = "The Ark is divided into 4 areas."
10020005-51 = ""
10020005-60 = "There's Area 1..."
10020005-61 = "...Area 2..."
10020005-62 = "...and Area 3 on the outskirts."
10020005-63 = "Area 4 is in the center of the Ark."
10020005-64 = "Utnapishtim's ship has already infiltrated Area 1."
10020005-65 = "Naturally, we'll begin the conquest on the outskirts: Areas 1, 2, and 3. We'll save Area 4 for last."
10020005-66 = "Each Area has its own Dimension Engine that contributes computing power. At the core is the multi-dimensional computation device itself."
10020005-67 = "We must destroy all 4 Dimension Engines before we can gain control of the Ark."
10020005-69 = "To succeed, we must force the Ark to self-destruct."
10020005-70 = "Only then will Kivotos have peace again."
10020005-71 = ""
10020005-73 = ""
10020005-74 = "Once we've done that, Sensei and the rest of us just need to get to the ground safely. Fortunately, the Engineering Department has repaired Utnapishtim's ship, so we're covered there."
10020005-76 = "And that's the end of the briefing. Schale can take it from here."
10020005-77 = "Yes, Sensei. We'll leave it to you."
10020005-78 = ""
10020005-80 = ""
10020005-81 = "You've got this, Sensei. We'll do our best to support you."
10020005-82 = "Hang in there."
10020005-83 = ""
10020005-85 = ""
10020005-86 = "[ns] \"Thanks, Veritas. Let's all do our best.\""
10020005-87 = "Thank you for the briefing, Veritas."
10020005-88 = "Now..."
10020005-89 = "Let the Conquest of the Ark of Atrahasis begin!"
10020005-90 = "[s] \"All right. Let's do this.\""
10020005-92 = "I've prepped everything you need for the operation here. Come by anytime, Sensei."
10020005-93 = "Yes! We'll always support Sensei."
