[translation]
10026060-1 = "ตอนที่ 6;จุดสำรวจ D ประภาคารที่ถูกลืม"
10026060-3 = "ก่อนอื่นก็ขนของพวกนี้..."
10026060-4 = "ฮึบ..."
10026060-5 = "ฮู่ว... ในประภาคารก็มีอะไรให้สำรวจมากกว่าที่คิดอีกนะคะ ถึงจะเป็นเรื่องดีก็เถอะค่ะ"
10026060-6 = "ที่จริงตอนที่บอกว่าประภาคารแห่งนี้เป็นที่ที่พวกสาวกโบราณใช้งาน ฉันคิดว่าข้างในจะว่างเปล่ากว่านี้#nเสียอีก..."
10026060-7 = "...หืม? เอ๋...?"
10026060-8 = "คุณครู...? อยู่ตรงนี้เหรอคะ? ฉันก็นึกว่าจะไปสำรวจกับคนอื่นอยู่ข้างใน..."
10026060-9 = "[s1] \"ครูมาช่วยฮินาตะไงล่ะ\"\n[s2] \"เห็นขนของอยู่คนเดียว น่าจะเหนื่อยแย่เลย\""
10026060-12 = "ยะ... อย่างนั้นเหรอคะ...! ไม่เป็นไรหรอกค่ะ ไม่ต้องทำแบบนี้เพราะฉันก็ได้ค่ะ!"
10026060-13 = "ฉันก็บอกคุณครูอยู่ตลอดไม่ใช่เหรอคะว่าฉันสบายใจที่จะทำงานแบบนี้ ขอให้ฉันได้ทำตรงนี้เถอะค่ะ!"
10026060-14 = "ระ... หรือว่า? เพราะคุณครูเป็นคุณครู... ก็เลยทนดูนักเรียนต้องมาทำงานหนักแบบนี้ไม่ได้หรือเปล่าคะ ...?"
10026060-15 = "...คะ? ไม่ใช่อย่างนั้นหรอกเหรอคะ? แต่ว่า... อืม..."
10026060-16 = "...ฮุฮุ"
10026060-17 = "นั่นสินะคะ ไหนๆ คุณครูก็พูดมาแบบนั้นแล้ว จะให้ถามเซ้าซี้อะไรอีกก็คงจะไม่ดีใช่ไหมคะ"
10026060-18 = "ขอบคุณนะคะ เอาเป็นว่าฉันจะรู้เอาไว้... งั้นฉันจะขอให้ช่วยยกของชิ้นเล็กๆ แล้วกันค่ะ"
10026060-19 = "พวกของชิ้นใหญ่ๆ มันหนักมาก... ฉันจะยกของหนักๆ เองค่ะ"
10026060-20 = ""
10026060-22 = ""
10026060-23 = "...งั้นเราไปกันเลยไหมคะ?"
10026060-25 = "(หลังจากนั้นคุณครูกับฮินาตะก็ช่วยกันลำเลียงของที่สำรวจพบในประภาคารออกมา)"
10026060-26 = "ฮู่ว... เราน่าจะขนของชิ้นใหญ่ๆ ออกกันมาหมดแล้วใช่ไหมคะ?"
10026060-27 = "คนอื่นๆ เห็นบอกว่าจะสำรวจข้างในกันต่ออีกหน่อย... งั้นเรามารอกันอยู่ตรงนี้ก่อนดีไหมคะ?"
10026060-28 = "ทำงานหนักมากเลยนะคะคุณครู ต้องขอบคุณอีกครั้งนะคะ"
10026060-29 = ""
10026060-32 = "...หืม? เสียงเมื่อกี้...? ดังมาจากในป่าหรือเปล่าคะ...?"
10026060-33 = ""
10026060-35 = ""
10026060-37 = ""
10026060-38 = ""
10026060-39 = "......! ว่าแล้วเชียว..."
10026060-40 = "ครั้งนี้ก็คงจะ... กันอีกแล้วสินะคะ"
10026060-41 = ""
10026060-42 = ""
10026060-43 = ""
10026060-45 = ""
10026060-46 = ""
10026060-47 = ""
10026060-48 = ""
10026060-49 = "นี่เรา... เราถูกล้อมไว้หมดแล้วสินะคะ... ไม่นึกเลยว่าจะเป็นไปได้ถึงขนาดนี้..."
10026060-50 = "...คะ?"
10026060-51 = "คนอื่นเหรอคะ? คุณครูคิดว่าเราควรเรียกทุกคนให้มาคอยรับมือกันที่นี่งั้นเหรอคะ...?"
10026060-52 = "อืม... แบบนั้นมัน..."
10026060-53 = ""
10026060-55 = ""
10026060-56 = "[ns3] \"...ฮินาตะ?\"\n[ns4] \"กำลังมองพื้นที่รอบๆ อยู่เหรอ...?\""
10026060-59 = "อ่า... ขอโทษด้วยค่ะ คุณครู คือว่า... ฉันอยากรู้ว่าจะมีประมาณกี่คนได้..."
10026060-60 = "ตอนนี้คุณอุยกับคนอื่นๆ อยู่ในระหว่างการสำรวจที่สำคัญ ถ้าเป็นไปได้ฉันก็อยากให้พวกเธอจดจ่อกับ#nงานให้ได้มากที่สุดค่ะ"
10026060-61 = "และฉันก็กำลังคาดประมาณอยู่ค่ะว่าฉันจะรับมือไหวหรือเปล่า... ถ้าเป็นไปได้น่ะนะคะ"
10026060-62 = ""
10026060-65 = "[ns] \"......???\""
10026060-67 = "[ns5] \"หืม...? จะรับมือคนเดียวงั้นเหรอ!?\"\n[ns6] \"พวกนั้นมีกันหลายสิบคนเลยนะ...!?\""
10026060-70 = "งะ... งั้นเหรอคะ...? แต่การต่อสู้แค่ระดับนั้น ฉันก็ทำได้ดีไม่แพ้ใครเลย..."
10026060-71 = "ที่วิหารมันมีเรื่องอะไรตั้งเยอะตั้งแยะเลยน่ะค่ะ... ถ้าได้รับมือหลายๆ เรื่องในวิหาร เรื่องอื่นๆ ก็คงเรียก#nว่าเรื่องหมูๆ ไปเลย..."
10026060-72 = "ทำไมถึงตกใจขนาดนั้นล่ะคะ...!?  มันแปลกเหรอคะ!?  หรือว่าฉันพูดอะไรผิดไปคะ...!?"
10026060-73 = "หรือว่ามันผิดตรงไหนคะ? การต่อสู้แบบนี้ในชีวิตประจำวันมันก็มีให้เห็นบ่อยๆ ไม่ใช่เหรอคะ??"
10026060-74 = ""
10026060-78 = "มะ... มะ... มาแล้วค่ะ! คุณครู!!"
10026060-79 = "ไม่มีเวลาแล้ว ถ้าคุณครูไม่ว่าอะไรละก็... ฉันจะขวางไว้เองค่ะ! !"
10026060-80 = "[s7] \"กะ... ก็ได้ ลองดูกันสักตั้ง!!\"\n[s8] \"ครูจะสั่งการเอง ระวังตัวด้วยนะ\""
10026060-83 = "...ค่ะ!"
10026060-84 = ""
10026060-86 = ""
10026060-87 = "ขอบคุณค่ะ!!  คุณครู!"
