[translation]
10020035-12 = ""
10020035-13 = ""
10020035-14 = ""
10020035-19 = "อะ...อึก...!!"
10020035-20 = "ดะ...เดี๋ยวก่อน! เธอ...เป็นใครกันแน่?"
10020035-21 = "หนีไปอีกแล้วค่ะ..."
10020035-23 = ""
10020035-25 = ""
10020035-26 = "ระ...รุ่นพี่โฮชิโนะ... เมื่อกี้นี้... "
10020035-27 = "ที่บอกว่าคนคนนั้นไม่ใช่รุ่นพี่ชิโรโกะที่เรารู้จัก หมายความว่ายังไงกันคะ?"
10020035-29 = "......"
10020035-30 = "ชิโรโกะจังน่ะ... ไม่มองกันด้วยแววตาแบบนั้นหรอก"
10020035-31 = "แววตาแบบนั้น... หมายถึง..."
10020035-33 = ""
10020035-35 = ""
10020035-36 = ""
10020035-38 = ""
10020035-40 = "รอนานเลยใช่มั้ย? ด้วยความช่วยเหลือของรุ่นพี่ฮิมาริ ตอนนี้เราแฮ็กเครือข่ายพื้นที่ที่ 4 ของเรือสำเร็จ#nแล้วละ!"
10020035-41 = "ถ้าพื้นที่ที่ 4 ละก็..."
10020035-42 = "คือบริเวณที่จับสัญญาณของชิโรโกะได้ยังไงละ รอเดี๋ยวนะ เดี๋ยวจะเชื่อมต่อหน้าจอให้ดู"
10020035-43 = ""
10020035-45 = ""
10020035-52 = "ทะ...ที่นี่..."
10020035-53 = ""
10020035-55 = ""
10020035-56 = ""
10020035-58 = ""
10020035-60 = ""
10020035-61 = ""
10020035-62 = "ระ...รุ่นพี่ชิโรโกะ?!"
10020035-63 = "ชิโรโกะจัง...?"
10020035-64 = "อื้อ ในที่สุดก็หาเจอแล้วสินะ คุณครู ทุกคน... ฉันกำลังรออยู่เลยละ"
10020035-65 = "[ns] \"ชิโรโกะ?! เป็นอะไรรึเปล่า? ไม่บาดเจ็บตรงไหนใช่มั้ย?!\""
10020035-66 = ""
10020035-68 = "อื้อ ตอนที่กำลังปั่นจักรยานกลับโรงเรียน...ก็ถูกศัตรูลึกลับจับตัวมา"
10020035-69 = "ฉันคิดว่าคนที่ถูกจับเป็นตัวประกันน่าจะเป็นเซริกะมากกว่า เลยชะล่าใจไปหน่อย ขอโทษนะ น่าขายหน้าจริงๆ "
10020035-70 = "หะ...หา?! เดี๋ยวก่อนสิรุ่นพี่ชิโรโกะ? หมายความว่ายังไงน่ะ? ฉันทำไมห้ะ?!"
10020035-71 = "ฉันรู้อยู่แล้วว่าทุกคนจะต้องมาช่วย แต่ตอนนี้ดูเหมือนว่าจะถูกขังไว้นานไป ร่างกายเลยล้าไปหน่อยน่ะ"
10020035-72 = "ดูจากการที่พวกนั้นไม่ทำอะไรฉันเลย เป้าหมายของพวกมันคงไม่ใช่ฉัน แต่เป็นการเจรจาเรียกค่าไถ่#nมากกว่า"
10020035-73 = "อ่า~ แต่ว่านะชิโรโกะจัง ถ้าเป็นตัวประกันก็ควรทำตัวให้สมกับเป็นตัวประกันหน่อยสิ ทำไมถึงทำอะไร#nแบบนั้นเล่า? มีแผนอะไรรึไง?"
10020035-74 = "อ๋อ นี่น่ะเหรอ? ฉันพกติดกระเป๋าไว้ตลอดเลยน่ะ เตรียมพร้อมไว้เผื่อโอกาสเหมาะๆ มาถึง"
10020035-75 = "ฉันรู้สึกได้ว่าที่นี่ถูกโจมตีมาตั้งแต่เมื่อกี้แล้ว เพราะงั้นตอนที่แอบหนีไป... ถ้ามีโอกาสเหมาะๆ ก็อาจได้#nของมีค่าคุ้มเหนื่อย..."
10020035-76 = ""
10020035-78 = ""
10020035-79 = ""
10020035-80 = "ถะ...ถูกจับตัวไว้... ก็ยังไม่วายคิดเรื่องแบบนั้น..."
10020035-81 = "อืม..."
10020035-82 = "เฮ้อ~ ชิโรโกะจังเนี่ยเป็นเด็กที่มองหาโอกาสในยามวิกฤตสิน้า"
10020035-83 = "...แต่ว่านะชิโรโกะจัง ลุงคนนี้เคยบอกไปแล้วไม่ใช่รึไง?"
10020035-84 = ""
10020035-86 = ""
10020035-88 = ""
10020035-90 = ""
10020035-92 = ""
10020035-94 = "อะ...อื้อ "
10020035-95 = "ถ้าพวกเราเคยชินกับวิธีเลวร้ายไปทีละนิดๆ ละก็... ต่อไปพวกเราจะกลายเป็นพวกเศษสวะไปนะ..."
10020035-96 = "และโรงเรียนที่ได้รับการปกป้องไว้ด้วยวิธีแบบนั้นน่ะ ก็คงเรียกว่าโรงเรียนที่แท้จริงของเราไม่ได้..."
10020035-98 = "......"
10020035-99 = "......"
10020035-100 = "รุ่นพี่ชิโรโกะ... สมกับเป็นรุ่นพี่จริงๆ..."
10020035-101 = "แฮ่~ รู้ดีจังน้า ชิโรโกะจัง"
10020035-102 = "เอาเป็นว่าเป็นเด็กดีรออยู่ตรงนั้นก่อนนะ ฉันรู้แล้วว่าตรงนั้นอยู่ตรงไหน เดี๋ยวจะรีบไปช่วยออกมานะ"
10020035-103 = "อื้อ"
10020035-104 = "ส่วนเรื่องที่เหลือ เอาไว้ค่อยคุยกันตอนเจอแล้วกัน ช่วงที่ชิโรโกะจังไม่อยู่น่ะ มีเรื่องเกิดขึ้นเยอะแยะ#nเลยนะ ฟังแล้วน้ำตาไหลแน่นอน"
10020035-105 = "อื้อ ฉันจะรอนะ"
10020035-106 = "รุ่นพี่โฮชิโนะ ทุกคน แล้วก็คุณครู... ฉันรู้อยู่แล้วละว่าทุกคนจะต้องมาช่วย"
10020035-107 = "[s] \"...อื้อ แน่นอน\""
10020035-108 = "ถ้างั้น... (ซ่า)... คอย... อยู่ที่นั่น..."
10020035-109 = ""
10020035-111 = ""
10020035-112 = "......"
10020035-113 = "ชิโรโกะจัง..."
10020035-114 = "...เอาละ ถ้างั้นก็ไม่ต้องลังเลแล้ว มุ่งหน้าไปพื้นที่ต่อไปกันเลยเถอะ"
10020035-115 = "พื้นที่ที่ชิโรโกะถูกขังอยู่คือพื้นที่ที่ 4 ฉันจะไปที่นั่น"
10020035-116 = "ค่ะ! ถึงตอนนี้ฉันจะยังสับสนอยู่ก็จริง..."
10020035-117 = "อื้อ แต่การไปช่วยชิโรโกะจังก่อน สำคัญกว่าการวิเคราะห์สถานการณ์ในตอนนี้ค่ะ!"
10020035-119 = "รอก่อนนะรุ่นพี่! จะไปหาเดี๋ยวนี้แหละ!"
10020035-121 = "ตอนนี้เหลือแค่อย่างเดียวเท่านั้นค่ะ ปราการสุดท้ายของเรือ... เหลือแค่พื้นที่ 4 ค่ะ"
10020035-122 = "ถ้ายึดครองที่นั่นได้ละก็... เราก็จะคุมระบบควบคุมเรือได้ค่ะ"
10020035-123 = "ถ้าแบบนั้นเรืออะทราฮาซิสก็จะได้จบเห่แน่! เพราะเราจะเปิดใช้ระบบทำลายตัวเองไงล่ะ! "
10020035-124 = ""
10020035-126 = ""
10020035-128 = "สถานที่ที่ชิโรโกะตัวจริงถูกขังอยู่คือพื้นที่ปิด พื้นที่ 4 ค่ะ"
10020035-129 = "แต่การจะเปิดประตูเข้าไปยังพื้นที่นั้น เราจะต้องลอบเข้าไปใน <พื้นที่พิเศษ> ที่อยู่บริเวณส่วนบนของ#nเรือ และทำลายห้องควบคุมเรือก่อนค่ะ"
10020035-130 = "พื้นที่พิเศษ..."
10020035-131 = "ค่ะ ที่นั่นเป็นพื้นที่ที่แยกออกไปจากตัวเรือ เป็นพื้นที่ที่ไม่ได้รับผลกระทบจากการแฮ็กระบบของเราค่ะ"
10020035-132 = "หรือก็คือ... ใครบางคนจะต้องลอบเข้าไปใน <พื้นที่พิเศษ> และทำลายห้องควบคุม เพื่อเปิดประตูห้อง#nที่ขังชิโรโกะจังไว้สินะคะ?"
10020035-133 = "ใช่แล้วค่ะ ถ้าทำแบบนั้น เราก็จะปลดล็อกพื้นที่ 4 ที่คุณชิโรโกะถูกขังอยู่ได้ค่ะ"
10020035-134 = ""
10020035-136 = ""
10020035-137 = "...ก็นะ ถ้าอย่างนั้น เราก็คงต้องไปอย่างเดียวสินะ"
10020035-138 = "คุณครู... ระหว่างนั้นช่วยทำลาย <เครื่องทะลุมิติ> แล้วก็ยึดพื้นที่ 4 ทีนะ!"
10020035-139 = "ต้องเก็บกวาดรอบๆ ให้ชิโรโกะจังหนีไปได้ด้วย"
10020035-140 = "[s] \"เข้าใจแล้ว ระวังตัวด้วยนะทุกคน\""
10020035-142 = "ค่ะ! ไม่ต้องห่วงนะคะ"
10020035-143 = "อื้อ ฝากด้วยนะ!"
10020035-144 = "ถ้างั้น... พวกเราไปที่ <พื้นที่พิเศษ> ก่อนนะ แล้วเจอกัน"
10020035-145 = ""
10020035-148 = "สิ่งที่เรากำลังเผชิญหน้าอยู่ตอนนี้... คงเป็นการต่อสู้ครั้งสุดท้ายของปฏิบัติการยึดเรืออะทราฮาซิสแล้ว#nสินะคะ......"
10020035-149 = "ใช่แล้วค่ะ การต่อสู้ครั้งสุดท้าย..."
10020035-150 = "คือว่านะ... ดูเหมือนพวกศัตรูเองก็คิดว่านี่เป็นการต่อสู้ครั้งสุดท้ายแล้วเหมือนกัน"
10020035-151 = "โมโมกะจัง...?"
10020035-152 = ""
10020035-155 = ""
10020035-156 = "ศัตรูจำนวนมหาศาลกำลังแห่มาทางพวกเราแล้ว "
10020035-157 = "คะ...คะ?!"
10020035-159 = "...ต้องเตรียมการป้องกันเรืออุตนาพิชทิมอีกครั้งค่ะ"
10020035-160 = ""
10020035-163 = "ฮุฮุ เรื่องนั้นไม่ต้องห่วง"
10020035-165 = "การป้องกันที่นี่น่ะ ให้เป็นหน้าที่ของพวกเราเองค่ะ"
10020035-166 = "ช่วยไม่ได้นะ ไหนๆ ก็มาถึงที่นี่แล้วนี่นา"
10020035-167 = "ใช่แล้วค่ะ ถ้าเรื่องความวินาศสันตะโรละก็ ไว้ใจได้เลยค่ะ-★"
10020035-168 = "ว่าแต่เสบียงอวกาศนี่จะกินได้เมื่อไรเหรอ...?"
10020035-170 = "ส่วนทางนี้พวกเรา... จะหาทางขัดขวางไว้เองค่ะ"
10020035-171 = "ค่ะ ทางนี้ให้เป็นภารกิจของพวกเราได้เลยนะคะ คุณครู"
10020035-172 = "อาริสึจัง... ร่างกายโอเคแล้วใช่มั้ย?"
10020035-173 = ""
10020035-174 = "ค่ะ ถึงจะยังไม่สมบูรณ์เต็มร้อย แต่อาริสึก็ไปสู้พร้อมทุกคนไหวค่ะ!"
10020035-175 = "แต่ยังไงก็ห้ามฝืนตัวเองนะ อาริสึ!"
10020035-177 = "ค่ะ!"
10020035-179 = "คุณครูคะ ถ้าอย่างนั้นปฏิบัติการยึดครองครั้งสุดท้าย... ขอฝากด้วยนะคะ"
