[translation]
10029020-1 = "ตอนที่ 2;ของพื้นๆ"
10029020-2 = "... และด้วยการนี้..."
10029020-3 = "... พวกเราก็เลยสร้าง 'ของพื้นๆ' ของคิโวทอสให้ทั้งสามคน และมันก็คือปืนที่เหมาะสมที่สุดกับแต่ละคน"
10029020-4 = "เป็นการทำงานที่ตื่นเต้นทีเดียวเลยละ ฉันตั้งใจทำมากจนลืมวันลืมคืนเลย"
10029020-5 = "การสร้าง 'ปืนเพื่อผู้ใช้พลังจิตที่มาจากโลกอื่น' นี่เป็นโอกาสที่ไม่ได้มีง่ายๆ เลยนะ"
10029020-6 = "พูดตามตรง ฉันค่อนข้างเชื่อครึ่งไม่เชื่อครึ่งกับคำว่า 'ผู้ใช้พลังจิต' ด้วยซ้ำ..."
10029020-7 = "แต่กับ 'คนที่รู้ทุกอย่าง' ที่ไม่ใช่ใครอื่นแล้ว การคาดหวังน่าจะดีกว่าการสงสัยน่ะนะ"
10029020-8 = "งั้นก่อนอื่นก็..."
10029020-9 = "เอ้านี่ รับไปสิ นี่คือปืนสำหรับผู้ใช้พลังไฟฟ้า ส่วนอีกสองกระบอกที่เหลือฉันจะฝากคุณครูไว้"
10029020-10 = "เอ๋? หะ... หืม...? เอ่อ..."
10029020-11 = ""
10029020-13 = ""
10029020-14 = ""
10029020-16 = "อะ... อะไรกัน นี่ปืนจริงเหรอ? ... จะให้ฉันถือของแบบนี้ติดตัวเหรอ?"
10029020-17 = "แต่ว่ามัน..."
10029020-19 = "ไม่ต้องปฏิเสธหรอก เธออาจจะรู้สึกต่อต้าน แต่ก็อย่างที่บอกไปว่ากรอบความคิดของที่นี่กับที่นั่น#nมันแตกต่างกันในหลายๆ ด้าน"
10029020-20 = "ทั้งฮาโลที่ปรากฏอยู่บนหัวของมิโคโตะตอนนี้ แล้วก็การที่สามารถถูกปืนยิงได้เหมือนกับพวกฉัน"
10029020-21 = "นี่ไม่ใช่สิ่งที่มีในที่ที่มิโคโตะจากมาไม่ใช่เหรอ? เธอบอกไว้เองนี่?"
10029020-22 = "ระ... เรื่องนั้นฉันก็เข้าใจอยู่..."
10029020-23 = "อืม..."
10029020-24 = "...เอาเถอะ ก็ได้ ช่วยไม่ได้สินะ เข้าเมืองตาหลิ่วก็คงต้องหลิ่วตาตามละนะ"
10029020-25 = "นั่นมันก็เรื่องหนึ่ง ว่าแต่ปืนนี่พวกเธอสร้างให้ใหม่เพื่อฉันเลยเหรอ? ฉันรู้สึกขอโทษขึ้นมาเลยแฮะ..."
10029020-26 = "ฉันได้ของแบบนี้จากพวกเธอด้วย แบบนี้ยิ่งละอายกับท่าทีที่ผ่านมาของฉันน่ะ..."
10029020-27 = "...หืม?"
10029020-28 = "......? ไฟที่อยู่ในปืนนี้..."
10029020-29 = ""
10029020-31 = ""
10029020-32 = ""
10029020-33 = "...หืม? ว่าไงนะคุณครู?"
10029020-34 = "ขอถามเผื่อๆ ไว้ว่าปืนนี้มีฟังก์ชันอะไรแปลกๆ บ้างหรือเปล่างั้นเหรอ...?"
10029020-35 = ""
10029020-37 = ""
10029020-38 = "...จะเป็นแบบนั้นไปได้ยังไงกันเล่า"
10029020-39 = "[s1] \"แล้วเมื่อกี้เว้นวรรคให้คิดมากทำไม!?\"\n[s2] \"มีอะไรใช่มั้ย!?  มีแน่นอนเลย!\""
10029020-42 = "ฟังก์ชันแปลกๆ งั้นเหรอคะ!!  ไม่มีทางหรอกค่ะ! มันเป็นอะไรที่สุดยอดต่างหาก!!"
10029020-43 = "นี่คือปืนที่สามารถดึงพรสวรรค์ของผู้ใช้งานออกมาได้ค่ะ! นี่แหละที่เรียกว่า <เรลกัน>!!"
10029020-44 = "......? เรลกัน...?"
10029020-45 = "เดี๋ยวก่อน เธอพูดว่าเรลกันงั้นเหรอ..."
10029020-46 = "แน่นอนว่านี่เป็นปืนที่สามารถใช้เหมือนปืนทั่วไปได้ แต่ว่าปืนนี้มีฟังก์ชันพิเศษเสริมอยู่ด้วยค่ะ! และนั่นก็คือฟังก์ชันในการยิงปืนออกไปโดยใช้แรงแม่เหล็กไฟฟ้า!!"
10029020-48 = "มันก็เลยเป็นปืนที่เหมาะสมที่สุดกับผู้ใช้พลังไฟฟ้ายังไงล่ะคะ!!"
10029020-49 = ""
10029020-51 = ""
10029020-52 = "และที่พวกฉันพูดกันก็คือ... ถ้าเจ้าของปืนสามารถสร้างไฟฟ้าในร่างกายได้จริงๆ ละก็...!!"
10029020-53 = "นะ... แน่นอนว่าพวกฉันไม่ได้ระแวงคนที่เพิ่งเจอเป็นครั้งแรกหรอกนะ..."
10029020-54 = "แต่มันก็เป็นเรื่องที่เราไม่คุ้นเคยกันเลย ในฐานะวิศวกรแล้ว มันค่อนข้างยากที่จะยอมรับน่ะ ถ้าฟังแล้วรู้สึกไม่ดี ฉันก็ขอโทษนะ"
10029020-56 = "ไม่หรอก ไม่เป็นไร นี่ไม่ใช่ครั้งแรกหรอกที่ฉันเจอเรื่องแบบนี้"
10029020-57 = "ส่วนปืนกระบอกนี้... ฉันก็ขอบคุณอยู่หรอกนะ... แต่ฉันไม่คิดว่าจะต้องใช้น่ะ แค่พกติดตัวไว้ก็พอมั้ย..."
10029020-58 = "เดี๋ยวก็ได้ใช้ แล้วก็ถ้าจะแค่พกติดตัวไว้ก็ไม่เป็นไร"
10029020-59 = "โดยเฉพาะถ้าไปไหนมาไหนกับคุณครูแล้ว คนอื่นก็จะคิดว่ามันเป็นงานราชการน่ะ"
10029020-60 = "พูดออกมาอย่างไม่สะทกสะท้านเลยนะ... เอาจริงๆ ระหว่างมาที่นี่ฉันก็เห็นการยิงปืนต่อสู้อยู่หลายครั้ง#nอยู่หรอก..."
10029020-61 = "... พอมาลองคิดดูอีกที นี่มันความฝันจริงๆ หรือเปล่า? เรื่องแบบนี้ไม่มีทางเป็นจริงได้นี่ หรือว่านี่ก็คือผลจากอินเดียนโปกเกอร์"
10029020-62 = "โลกที่การต่อสู้กันด้วยปืนเป็นเรื่องธรรมดางั้นเหรอ... เหลือเชื่อเลย..."
10029020-63 = "ผู้ใช้พลังจิตพูดอะไรแบบนั้นอีกแล้ว..."
10029020-64 = "เอาเถอะ ไหนๆ ตอนนี้ก็ได้ปืนมาแล้ว ระหว่างที่หัวหน้าสืบค้นเกี่ยวกับ 'เครื่องมือ' นั้นอยู่ พวกเราก็ต้องไปตามหาอีกสองคนที่เหลือ"
10029020-65 = "อ่า จะว่าไปแล้ว..."
10029020-66 = "ฉันขอถามล่วงหน้าได้ไหมว่าอีกสองคนที่เหลือเป็นคนแบบไหน? เผื่อจะเป็นคนที่ฉันรู้จักน่ะ"
10029020-67 = "หรือบางที พวกเขาอาจจะมาจากโลกอื่นก็ได้..."
10029020-68 = "นักเรียนหญิง ผมยาวสีบลอนด์ ใส่ชุดนักเรียนเหมือนกันกับเธอ"
10029020-69 = "ส่วนอีกคนก็นักเรียนหญิงผมดำ ที่ใส่ชุดนักเรียนที่แตกต่างออกไปหน่อย"
10029020-71 = "คนผมบลอนด์ถืออะไรคล้ายๆ รีโมตอยู่ด้วย"
10029020-72 = "ผมยาวสีบลอนด์...? ชุดนักเรียนมัธยมต้นโทคิวะได...?"
10029020-73 = "... รีโมต...?"
10029020-74 = ""
10029020-76 = ""
10029020-77 = "... อ่า"
10029020-78 = "... เฮ้อ"
10029020-79 = "จริงเหรอเนี่ย นักเรียนก็มีตั้งเยอะตั้งแยะ แต่ทำไมต้องเป็นยัยนั่นด้วยนะ..."
10029020-80 = "... \"ยัยนั่น\" งั้นเหรอ? เป็นคนรู้จักเหรอ?"
10029020-81 = "...ก็พอจะรู้จักอยู่คนหนึ่ง คิดว่าน่าจะใช่นะ"
10029020-82 = "และถ้าเป็นยัยนั่นจริงๆ ละก็ ฉันว่าน่าจะต้องรีบหาตัวให้เจอเร็วๆ กันแล้วละ"
10029020-83 = "... หืม? ... หมายความว่ายังไงน่ะเหรอ?"
10029020-84 = "ก็ยัยเด็กคนนั้นมีพลังในการควบคุมคนอื่นน่ะสิ ฉันไม่รู้หรอกนะว่าเธอจะไปก่อเรื่องอะไรบ้าง"
10029020-85 = "พลังในการควบคุมจิตใจ...!?  มีพลังแบบนี้จริงงั้นเหรอ? ไม่เคยได้ยินเรื่องแบบนี้มาก่อนเลย!"
10029020-86 = "ถ้ารู้ก่อน ก็คงใส่เครื่องขยายคลื่นสมองในปืนให้แล้ว...!!"
10029020-87 = "[s3] \"เดี๋ยวๆ ไม่ต้องขนาดนั้น...\"\n[s4] \"ต้องบอกว่าดีแล้วที่ไม่รู้หรือเปล่านะ\""
10029020-90 = "เพราะแบบนี้สินะ ตอนที่หายตัวไปฉันถึงไม่รู้ตัว ถ้าคนนั้นใช้พลังอะไรแบบนั้นก็คงจับสังเกตอะไร#nไม่ได้หรอกเนอะ"
10029020-91 = "แต่ยังไงการตามตัวก็ไม่น่าจะยากขนาดนั้นนะ"
10029020-92 = "... อืม หัวหน้าบอกไว้ว่าหาตัวเจอแล้ว"
10029020-93 = "หืม? อะ... อะไรกัน เจอแล้วงั้นเหรอ? หาเจอได้ยังไง..."
10029020-94 = "แค่ดูจากกล้องวงจรปิดในเมืองก็หาตัวได้ง่ายๆ แล้วน่ะ อย่างที่บอกไปว่าพวกเธอสะดุดตามาก"
10029020-95 = "ก็เป็นนักเรียนที่เดินเตร็ดเตร่ตามถนนโดยไม่มีปืนนี่นะ..."
10029020-96 = "คนแบบนี้มีน้อยกว่านักเรียนที่เดินแก้ผ้าในเมืองมากกว่าอีกค่ะ! ทั้งในทางสถิติ! และตามความเป็นจริง#nด้วยค่ะ!"
10029020-97 = "ที่นี่มันเมืองอะไรกันแน่เนี่ย..."
10029020-98 = "เอาเถอะ งั้นเราออกเดินทางกันได้เลยใช่มั้ย? แล้วก็..."
10029020-99 = ""
10029020-101 = ""
10029020-102 = "ถือ 'ของพื้นๆ' ของเมืองนี้ไปด้วย?"
10029020-103 = "[s5] \"ปรับตัวได้ง่ายกว่าที่เห็นนะเนี่ย\"\n[s6] \"ดีละ งั้นก็ไปกันเลย\""
10029020-106 = "... อืม"
10029020-107 = "ออกเดินทางได้"
