[translation]
10025090-1 = "ตอนที่ 9;กระต่ายในน้ำ"
10025090-2 = ""
10025090-3 = "เฮ้! รีบๆ กันหน่อย!"
10025090-4 = "เราต้องรีบสลับของที่อยู่ในลังใส่กุ้งให้เสร็จก่อนที่หมอกจะจางลงนะ"
10025090-5 = "ได้เลยกัปตัน!"
10025090-7 = "...โชคดีที่หมอกลงหนากว่าที่คิดนะ ถ้าหมอกในทะเลเยอะขนาดนี้ ต่อให้ทำอะไรบนเรือก็ไม่มีใครเห็น"
10025090-8 = "แต่พอทัศนวิสัยแย่จนมองไม่เห็นหมู่บ้านจากบนเรือแบบนี้ก็ไม่สบายใจอยู่หน่อยแฮะ..."
10025090-9 = "เอาเถอะ ถ้ามีลางหรือสัญญาณอะไรแปลกๆ ก็แค่ติดเครื่องยนต์แล้วหนีออกไปยังทะเลไกลโพ้นก็พอ"
10025090-10 = ""
10025090-13 = ""
10025090-14 = "เอ่อ ประธาน... ไม่สิ กัปตัน ให้ทำยังไงกับกุ้งแช่แข็งเดิมที่อยู่ในลังเหรอ?"
10025090-15 = "ไหงมาถามอะไรเหมือนคนไม่เคยมาก่อนอย่างนั้นเล่า?"
10025090-16 = "มันไม่ใช่ของแพงอะไร โยนๆ ทิ้งลงไปในทะเลให้หมดเลย"
10025090-17 = "แต่ว่า... จะทิ้งกุ้งสภาพดีแบบนี้ไปเฉยๆ เลยเหรอ?"
10025090-18 = "พอคิดว่าต้องทิ้งวัตถุดิบดีๆ ไปหมด ก็ไม่ค่อยสบายใจเลย..."
10025090-20 = "ฮึ่ย บอกแล้วไงว่าอย่ามาเสียดายของถูกๆ แบบนั้น ถ้ายังยึดติดกับของหยุมหยิมพวกนี้ แล้วเมื่อไรจะได้#nจับเงินก้อนโตกับเขาล่ะ?"
10025090-22 = "ถ้าทำเรื่องนี้สำเร็จ พวกเธอไม่ได้กินแค่กุ้งหรอก แต่จะได้กินปลากะพงแดงที่ดีที่สุดไปทุกมื้อเลย..."
10025090-23 = "ไม่ต้องไปสนใจกุ้งที่มันไม่อร่อยนั่นเลยน่า"
10025090-24 = "...ฉันละไม่เข้าใจจริงๆ ว่าทำไมคนถึงได้ชอบกินสัตว์น้ำที่ไม่มีรสชาติและมีเนื้อสัมผัสแปลกๆ นั่นด้วย"
10025090-25 = "รับทราบ..."
10025090-26 = ""
10025090-28 = ""
10025090-30 = "กัปตัน มีเรือเล็กๆ ลำหนึ่งกำลังค่อยๆ มุ่งหน้ามาทางเราด้วย"
10025090-31 = "...ทำยังไงดี? จะปล่อยๆ ไปไหม?"
10025090-32 = "ชาวบ้านยาโตอูระคนไหนที่ใจกล้าบ้าบิ่นเข้ามาใกล้ๆ <เรือส่งวิญญาณ> กันล่ะนั่น...?"
10025090-33 = "มองเห็นไม่ค่อยชัดเลย แต่ดูจากการแต่งตัวแล้วไม่น่าใช่ชาวบ้านนะ... คงจะเป็นนักท่องเที่ยวจากข้าง#nนอกนั่นละ"
10025090-34 = "คนนอกพวกนี้ ทำให้รำคาญไม่รู้จักจบสิ้นเลยนะ..."
10025090-36 = "ห้องเครื่อง เดินเครื่องด้วยความเร็วเต็มพิกัด ไปฝั่งตรงข้ามให้เร็วที่สุดเลย!"
10025090-37 = "เดินเครื่องด้วยความเร็วเต็มพิกัด..."
10025090-39 = ""
10025090-42 = "ระ... ระเบิด...? หอบังคับการเรือ นี่มันอะไรกันเนี่ย?!"
10025090-43 = "จะ... จู่ๆ ก็เกิดระเบิดขึ้นตรงใต้ตัวเรือ... ใบพัดเรือไม่ทำงานเลย!"
10025090-44 = "ว่าไงนะ? ทำไมต้องมาระเบิดเอาตอนนี้ด้วย..."
10025090-45 = "ลองหยุดฉุกเฉินก่อน แล้วควบคุมหางเสือให้เรือแล่นดูซิ!"
10025090-46 = "ทำอะไรไม่ได้เลย... สงสัยใบพัดเรือพังไปแล้ว!"
10025090-47 = "เราไม่ได้ไปติดหินโสโครกอะไรสักหน่อย ทำไมใบพัดเรือถึงพังได้ล่ะ?!"
10025090-48 = "กัปตัน เรือเล็กลำนั้นกำลังเข้าใกล้มาเรื่อยๆ เลย... แล้วมันก็เพิ่มความเร็วขึ้นเรื่อยๆ ด้วย!"
10025090-49 = "อึกกก...!"
10025090-51 = "ทุกคนเตรียมตัวต่อสู้!! เปิดศึกต่อสู้บนเรือนี่แหละ!"
