[translation]
10025110-1 = "บทส่งท้าย;พัสดุจากหมู่บ้านชาวประมง"
10025110-3 = ""
10025110-4 = "สวัสดีค่ะท่านผู้ชมทุกท่าน! ทุกท่านอยู่กับคาซามากิ มาอิแห่งชมรมข่าวโครโนสค่ะ"
10025110-5 = "รายการ <เช้านี้ที่คิโวทอส> วันนี้ ฉันมาอยู่ที่หมู่บ้านยาโตอูระ หมู่บ้านชาวประมงเล็กๆ ที่อยู่ชายขอบ#nของท่าเรือคาเนะซากิค่ะ"
10025110-6 = "นอกจากเรื่องกุ้งรสชาติดีที่หมู่บ้านนี้หาได้แล้ว หมู่บ้านนี้ก็ไม่เป็นที่รู้จักในเรื่องอื่นอีกเลย แต่ไม่นานมานี้หมู่บ้านนี้ก็ได้กลายเป็นจุดเช็กอินสุดฮอตในโซเชียลค่ะ!"
10025110-7 = "และสาเหตุที่หมู่บ้านนี้ได้รับความสนใจจากชาวเน็ตขึ้นมาก็เพราะแชนแนลตกปลา <หมีขาวตกปลา TV> ได้มาถ่ายทำที่นี่และได้ยอดรับชมทะลุสิบล้านวิวเลยค่ะ!"
10025110-8 = "ในคลิปจะเห็นได้ว่าหมู่บ้านนี้มีทิวทัศน์ธรรมชาติที่สวยงาม และมีจุดตกปลาสำหรับนักตกปลามือใหม่#nเป็นจำนวนมาก ด้วยเหตุนี้หมู่บ้านยาโตอูระจึงกลายเป็นสถานที่ท่องเที่ยวแห่งใหม่ที่ต้องมาเยือนค่ะ"
10025110-9 = "นอกจากนี้ปลาคูซายะย่างของหมู่บ้านนี้ยังได้รับการประเมินที่ดีจากบรรดาเหล่านักชิม ทำให้มีนักท่อง#nเที่ยวจำนวนไม่น้อยมาที่นี่เพื่อชิมเมนูนี้ด้วยละค่ะ"
10025110-10 = "สิบล้านวิวเลยเหรอ น่าอิจฉาจัง... พวกเราก็อัปวิดีโอลงแชนแนลอยู่เรื่อยๆ นี่นา เมื่อไรจะถึงสิบล้านวิวแบบนั้นบ้างนะ?"
10025110-11 = "... ถ้าแชนแนลไม่โดนปิดบ่อยๆ เพราะเฟคนิวส์ ป่านนี้เราก็คงได้ยอดวิวเยอะๆ ไปแล้ว....."
10025110-12 = "หนวกหูน่า!"
10025110-13 = "อืม... บางท่านอาจจะเคยมีประสบการณ์ไม่ดีจากการท่องเที่ยวเพราะได้ไปเจอคนในพื้นที่ที่แล้งน้ำใจ ทำให้การพักร้อนแสนสนุกต้องล่มไม่เป็นท่านะคะ"
10025110-14 = "แต่กับหมู่บ้านยาโตอูระแห่งนี้ ชาวบ้านทุกคนเป็นมิตรและต้อนรับนักท่องเที่ยวด้วยบรรยากาศสดใส นักท่องเที่ยวที่ได้ประสบการณ์น่าประทับใจกลับมา ก็เลยรีวิวหมู่บ้านนี้ลงโซเชียลกันเยอะเลยค่ะ"
10025110-15 = ""
10025110-19 = "อ้อ... ลองดูทางโน้นสิคะ ชาวประมงกำลังทอดสมอเรืออยู่ตรงท่าเรือฝั่งโน้นด้วยค่ะ"
10025110-20 = "ฉันจะรีบไปสัมภาษณ์พวกเขาเดี๋ยวนี้เลยค่ะ!"
10025110-22 = ""
10025110-26 = ""
10025110-27 = ""
10025110-28 = ""
10025110-29 = ""
10025110-30 = ""
10025110-31 = ""
10025110-32 = ""
10025110-33 = ""
10025110-34 = "สวัสดีค่ะ ฉันมาจากรายการ <เช้านี้ที่คิโวทอส> นะคะ!"
10025110-35 = "... อะไรเนี่ย?"
10025110-36 = "(เอ๋? ทำไมตอบรับอย่างไม่เป็นมิตรเลยล่ะ...)"
10025110-37 = "อ่า ไม่มีอะไรมากหรอกค่ะ ฉันแค่อยากขอสัมภาษณ์..."
10025110-38 = "ที่นี่ไม่ใช่ที่ที่ให้มาเดินทอดน่องเล่นนะ หลบไปซะ! เดี๋ยวก็ล้มจนเจ็บตัวไปหรอก"
10025110-39 = ""
10025110-41 = ""
10025110-42 = ""
10025110-43 = ""
10025110-44 = "คุมะไก ใจดีกับคนนอกหน่อยไม่ได้หรือไง!"
10025110-45 = "อึก... ขอโทษที"
10025110-47 = ""
10025110-50 = ""
10025110-51 = "ขอโทษนะ พอดีฉันกำลังทำงานผูกเชือกที่อันตรายอยู่ ก็เลยอารมณ์เป็นอย่างนั้นน่ะ เข้าใจกันหน่อยนะ"
10025110-53 = "มะ... ไม่เป็นไรเลยค่ะ ฉันต่างหากที่ต้องขอโทษที่มาขัดจังหวะระหว่างทำงาน"
10025110-54 = "ผู้อาวุโสคะ ช่วยแนะนำเสน่ห์ของหมู่บ้านนี้อย่างสั้นๆ หน่อยได้ไหมคะ?"
10025110-56 = "อืม... สำหรับคนที่อาศัยอยู่ที่นี่อย่างฉันแล้ว ที่นี่ก็แค่หมู่บ้านธรรมดาที่จับกุ้งขายเท่านั้น ไม่ได้มีอะไร#nพิเศษนักหรอก"
10025110-58 = "งะ... งั้นเหรอคะ...?"
10025110-60 = "แต่ถ้ามีคนเข้ามาเที่ยวชมหมู่บ้านธรรมดาๆ ของเราละก็ ฉันก็อยากจะให้กลับไปพร้อมกับความทรงจำ#nดีๆ น่ะนะ"
10025110-61 = "เวลาไปเลือกซื้อหรือกินกุ้งในเขตอื่น จะได้คิดถึงกุ้งจากหมู่บ้านของเราอีกครั้งไง ฮ่ะฮ่า!"
10025110-63 = "... อย่างนั้นเหรอคะ ฉันพอจะรู้แล้วค่ะว่าทำไมผู้คนถึงมาเที่ยวที่หมู่บ้านนี้!"
10025110-64 = "แต่ว่า... ที่จริงฉันได้ยินข่าวลือบางอย่างเกี่ยวกับหมู่บ้านนี้มาด้วยค่ะ"
10025110-65 = "เคยได้ยินเรื่องเกี่ยวกับ <ตัวตนแห่งห้วงลึก> ไหมคะ?"
10025110-67 = ""
10025110-69 = ""
10025110-71 = "ตามข่าวลือที่มีว่อนอินเทอร์เน็ตแล้ว ถ้าเราไปวางเครื่องสังเวยและท่องคาถาบนแนวปะการังยักษ์ สิ่งมีชีวิตลึกลับที่อยู่ในท้องทะเลลึกจะต้อนปลามาให้ค่ะ..."
10025110-72 = "มีใครเคยได้เห็นเหตุการณ์แบบนั้น หรือมีใครรู้รายละเอียดเรื่องนี้อีกไหมคะ?"
10025110-74 = "ไม่รู้สิ... ที่จริงมันก็มีตำนานแบบนี้เล่าส่งต่อกันมารุ่นสู่รุ่น แต่ตำนานมันก็เป็นแค่ตำนานไม่ใช่เหรอ?"
10025110-75 = "ถ้ามีสิ่งมีชีวิตลึกลับที่ต้อนปลามาให้จริงๆ ก็ไม่มีทางที่ชาวประมงอย่างพวกเราจะไม่รู้หรอก"
10025110-77 = "มันก็จริงอยู่หรอกค่ะ..."
10025110-78 = "งั้นเรื่องนี้เป็นข่าวลือสดๆ ร้อนๆ เลยค่ะ พอจะรู้เกี่ยวกับเรื่อง <เสียงกรีดร้องจากคลังคูซายะ> ไหมคะ?"
10025110-79 = "<เสียงกรีดร้องจากคลังคูซายะ> ...?"
10025110-80 = "ค่ะ พยานนิรนามที่ได้เห็นเหตุการณ์บอกว่าในคลังเก็บปลาคูซายะของหมู่บ้านยาโตอูระ บางครั้งก็จะได้ยิน#nเสียงร้องโหยหวนออกมาจากในนั้นว่า 'ฉันไม่ชอบกุ้ง~ ยิ่งคูซายะยิ่งไม่ชอบเข้าไปใหญ่~' ด้วยละค่ะ"
10025110-82 = ""
10025110-84 = ""
10025110-85 = "... เพิ่งจะเคยได้ยินเป็นครั้งแรกเลยแฮะ"
10025110-86 = "มันเป็นเสียงของลมในยามรุ่งสางที่พัดผ่านเสาเก่าๆ จนได้ยินเป็นเสียงหวีดหวิวหรือเปล่า?"
10025110-87 = "บางทีเสาไม้ต้นเก่าๆ ก็ส่งเสียงดังเอี๊ยดอ๊าดเหมือนเสียงคนกรีดร้องได้เหมือนกันนะ"
10025110-89 = "งะ... งั้นเหรอคะ..."
10025110-91 = ""
10025110-93 = ""
10025110-94 = "(กระซิบ) ผู้อาวุโส เหมือนว่าเจ้าพ่อค้าคนนั้นจะหนีไปอีกครั้งแล้วละ"
10025110-95 = "ชิ น่ารำคาญชะมัด..."
10025110-96 = "ส่งชาวประมงออกไปค้นหาให้ทั่วหมู่บ้าน แล้วก็ตรวจดูกล้องวงจรปิดหน้าปากทางเข้าหมู่บ้านด้วย"
10025110-97 = "ถ้าจะหนีออกจากหมู่บ้านนี้ละก็ไม่มีวิธีอื่นแล้ว"
10025110-99 = "เอ่อ... พวกคุณพูดถึงอะไรกันเหรอคะ...?"
10025110-101 = "ไม่มีอะไรหรอก"
10025110-102 = "ถ้างั้นก็ขอให้มีช่วงเวลาดีๆ ในหมู่บ้านของเรานะ พวกฉันขอไปทำงานกันก่อน..."
10025110-103 = ""
10025110-105 = ""
10025110-108 = ""
10025110-109 = "...หมู่บ้านนี้มันน่าเที่ยวจริงหรือเปล่าเนี่ย?"
10025110-111 = ""
10025110-113 = "โคะอุซางิ การ์เด้น"
10025110-115 = ""
10025110-116 = "ร้อนจัง..."
10025110-117 = "ร้อนจังเลยนะคะ..."
10025110-118 = "จะไหม้แล้ว...."
10025110-119 = "... ถ้าได้ไปว่ายน้ำในทะเลเย็นๆ ก็ดีน่ะสิ"
10025110-120 = "เหมือนเรากลับมาจากทะเลกันนานมากแล้วเลยแฮะ..."
10025110-121 = "... นั่นสิคะ เรากลับจากหมู่บ้านยาโตอูระกันมาได้ไม่กี่วันเท่านั้น แต่รู้สึกเหมือนมันเป็นความทรงจำที่#nยาวนานยังไงก็ไม่รู้ค่ะ"
10025110-122 = ""
10025110-124 = ""
10025110-125 = "... มันสนุกมากเลยละ"
10025110-126 = "ตอนแรกฉันก็ประหม่าไม่เบาเพราะข่าวลือที่น่ากลัวนั่น แต่ชาวบ้านที่นั่นก็จิตใจดีกันหมดทุกคน..."
10025110-127 = "เราทั้งได้ตกปลาทะเลกลางค่ำคืนแสนเย็นสบาย และได้กินอาหารทะเลกันจนหนำใจ..."
10025110-128 = "...เหมือนเราไม่ได้สนุกกันแบบนี้มานานมากเลยละ"
10025110-129 = "นั่นสิ เพราะหลังจากที่สถาบันพิเศษ SRT ถูกยุบไป ก็เกิดเรื่องต่างๆ มากมายจนไม่มีเวลาได้พักกันเลย"
10025110-130 = "ถึงปฏิบัติการครั้งนี้จะเป็นงานของ SRT ก็เถอะ แต่เหมือนว่าเราได้ไปพักร้อนกันมาด้วยเลยเนอะ"
10025110-131 = "... นั่นสิคะ สุดท้ายก็เป็นไปตามที่คุณครูพูดไว้จริงด้วยค่ะ"
10025110-132 = "การรู้และจดจ่อในเป้าหมายของเราอย่างชัดเจนก็เป็นเรื่องที่สำคัญ แต่หากเราไม่ปล่อยวางให้หัวใจ#nและสมองได้พักบ้าง ก็มีโอกาสสูงที่จะตัดสินอะไรผิดพลาดเพราะความกลัวที่มาจากความไม่รู้..."
10025110-133 = "ในฐานะหัวหน้ากองทหาร RABBIT ฉันได้ตระหนักรู้จากปฏิบัติการครั้งนี้เลยละค่ะ ว่าการพักผ่อนที่#nเหมาะสมเป็นเรื่องสำคัญแค่ไหน"
10025110-134 = "แต่ที่ที่เราจะอยู่ได้จนกว่าจะฟื้นฟูสถาบันพิเศษ SRT เสร็จก็มีแต่โคะอุซางิ การ์เด้นนี่แหละ"
10025110-135 = "มาตั้งใจมุ่งมั่นแล้วทำให้ดีที่สุดเพื่อการฟื้นฟูสถาบัน SRT กันเถอะ!"
10025110-136 = ""
10025110-138 = ""
10025110-139 = "จะว่าไปนี่ก็ใกล้จะถึงเวลาอาหารกลางวันแล้ว นี่โมเอะออกไปหาข้าวกล่องเหลือทิ้งถึงไหนกันเนี่ย?"
10025110-140 = ""
10025110-142 = ""
10025110-144 = ""
10025110-145 = "... สุดยอดเลย! ทุกคนมาดูนี่สิ!"
10025110-146 = "นี่ โมเอะ เธอออกไปหาข้าวกล่องตั้งนานแล้วนะ ทำไมเพิ่งมาเอาป่านนี้..."
10025110-147 = "ฮุฮุ... ซากิ ฉันมั่นใจว่าถ้าเธอได้เห็นของที่ฉันเอามาละก็ เธอต้องบ่นฉันไม่ออกแน่"
10025110-148 = "ดูให้ดีนะ! <ข้าวกล่องต้นสนพรีเมียมสุดลิมิเต็ด> จากเอ็นเจล 24! แล้วก็ได้มา 4 กล่อง 4 หน้าเลยด้วย!"
10025110-149 = "นี่ไม่ใช่ข้าวกล่องยี่ห้อต้นไผ่หรือต้นบ๊วย แต่เป็นข้าวกล่องที่ติดสติกเกอร์ต้นสนเลยเหรอ...? ยี่ห้อนี้มัน#nแพงมากเลยนะ...?"
10025110-150 = "ใช่ นี่คือข้าวกล่องสุดหรูที่ทำจากสินค้าขึ้นชื่อของแต่ละพื้นที่ และปกติจะขายหมดเกลี้ยงจนไม่มีเหลือ#nทิ้งเลยด้วย..."
10025110-151 = "วันนี้ตอนที่ฉันตรวจดูตารางขนส่งของร้านสะดวกซื้อ ก็เห็นว่ามีสาขาหนึ่งที่มีข้าวกล่องต้นสนที่จัดไว้ว่า#nเป็นของเหลือทิ้งน่ะ! ก็เลยรีบไปเอามาก่อนที่คนอื่นจะมาเอาไป!"
10025110-153 = "ที่วันนี้กลับมาช้ากว่าทุกทีก็เพราะแบบนี้เองสินะคะ"
10025110-154 = "เราได้กินข้าวกล่องคุณภาพดีกันตั้งแต่มื้อกลางวันเลยเหรอเนี่ย... ขอบใจมากเลยนะโมเอะ!"
10025110-155 = "เอาละ งั้นมาดูกันดีกว่าว่ามีข้าวกล่องหน้าอะไรบ้าง"
10025110-156 = ""
10025110-158 = ""
10025110-159 = ""
10025110-160 = "หน้าแซลมอน เนื้อวัว ไก่คาราอะเกะ... อ๊ะ มีกุ้งเทมปุระด้วย!"
10025110-161 = "... การขนส่งกุ้งสำหรับร้านสะดวกซื้อกลับมาเป็นปกติแล้วสินะคะ"
10025110-162 = "นั่นสิ ฮุฮุ พอได้เห็นข้าวกล่องหน้ากุ้งใน D.U. แบบนี้แล้วก็คิดถึงเลยเนอะ"
10025110-164 = "ถ้างั้นฉันจะระลึกถึงความลำบากของชาวประมง และขอจัดการข้าวกล่องกล่องนี้..."
10025110-165 = "...เดี๋ยวก่อน ซากิ หยุดเลยนะ"
10025110-166 = "ทำไมเธอถึงได้เลือกข้าวกล่องก่อนเพื่อนล่ะ?"
10025110-168 = "หืม? โมเอะ เธอเคยบอกว่าชอบกินเนื้อวัวหรือไม่ก็เนื้อไก่มากกว่าอาหารทะเลไม่ใช่เหรอ?"
10025110-169 = "ถึงฉันจะกระดากปากที่พูดแบบนี้ก็เถอะ... แต่ปฏิบัติการระเบิดใต้น้ำที่ผ่านมาฉันทำได้ยอดเยี่ยมเลยนะ แบบนี้ก็ต้องได้รางวัลเป็นสิทธิ์การเลือกข้าวกล่องก่อน..."
10025110-170 = "ไม่ได้ วันนี้ฉันก็อยากกินกุ้งเหมือนกัน!"
10025110-171 = "อีกอย่าง คนที่ไปเจอข้าวกล่องพวกนี้มาก็คือฉันนะ!"
10025110-172 = "ฉันด้วย... วันนี้ฉันก็อยากกินกุ้งมากกว่าเนื้อเหมือนกัน..."
10025110-174 = "...ฉันก็ด้วยค่ะ"
10025110-175 = "... วันนี้แข่งขันกันดุเดือดเลยแฮะ"
10025110-177 = "ถ้างั้นก็ช่วยไม่ได้ มาเป่ายิงฉุบตัดสินกัน...!"
10025110-178 = ""
10025110-180 = ""
10025110-186 = ""
10025110-187 = "สวัสดีครับ สวนสาธารณะนี้มีคุณสึคิยูกิ มิยาโกะไหมครับ?"
10025110-188 = "ค่ะ ฉันเองค่ะ สึคิยูกิ มิยาโกะ..."
10025110-189 = "พอดีมีพัสดุส่งมาถึงคุณน่ะครับ"
10025110-190 = "เอาละ... ช่วยเซ็นชื่อตรงนี้ให้ด้วยนะครับ"
10025110-191 = ""
10025110-193 = ""
10025110-194 = ""
10025110-195 = ""
10025110-196 = "เอ่อ... พัสดุนั่นคือของฉันจริงๆ เหรอคะ? ที่อยู่คือ... สวนสาธารณะเหรอคะ...?"
10025110-197 = "ใช่ครับ ที่อยู่ในการจัดส่งก็ระบุไว้ตรงนี้ครับ"
10025110-198 = "<คุณสึคิยูกิ มิยาโกะ เต็นท์ประเภท A หมายเลข 1 หน้าก๊อกน้ำ สวนสาธารณะในโคะอุซางิ ทาวน์ D.U.> ถูกไหมครับ?"
10025110-200 = "รู้กระทั่งตำแหน่งของเต็นท์เลยเหรอเนี่ย..."
10025110-202 = "ข้อมูลก็ถูกอยู่หรอกค่ะ แต่ว่าใครเป็นคนส่งมาเหรอคะ...?"
10025110-203 = "ส่งมาจากหมู่บ้านชาวประมง หมู่บ้านยาโตอูระครับ!"
10025110-204 = "ของข้างในเป็นของที่ต้องแช่แข็ง วันนี้ก็เลยส่งด่วนมาให้ตั้งแต่เช้าเลยครับ"
10025110-205 = "ถ้าวางทิ้งไว้ในอุณหภูมิห้อง ของข้างในอาจจะเสียได้ ถ้าเป็นไปได้ก็ให้เปิดแล้วจัดการเลย และถ้าเหลือก็ให้แช่แข็งไว้นะครับ"
10025110-206 = "ถ้างั้นก็ ขอให้วันนี้เป็นวันที่ดีนะครับ"
10025110-208 = ""
10025110-213 = "พัสดุจากหมู่บ้านยาโตอูระเหรอ? ส่งมาทำไมกันนะคะ...?"
10025110-214 = "แถมยังบอกว่าของข้างในอาจเสียได้อีก สงสัยจังว่าส่งอะไรมา"
10025110-215 = "เหมือนได้กลิ่นคาวจางๆ ออกมาจากกล่องเลย..."
10025110-217 = "... ฉันจะเปิดดูให้เอง"
10025110-218 = ""
10025110-220 = ""
10025110-221 = ""
10025110-222 = ""
10025110-225 = "นี่มัน..."
10025110-226 = "... กุ้งนี่นา? กุ้งตัวใหญ่เบิ้มเลยด้วย!"
10025110-227 = "กะ... กุ้งแพงๆ เต็มกล่องเลย..."
10025110-228 = "มีประโยคอะไรเขียนไว้ข้างในกล่องด้วยค่ะ"
10025110-229 = ""
10025110-231 = ""
10025110-232 = ""
10025110-233 = ""
10025110-234 = "<ถึงนักท่องเที่ยวใจดีที่บังเอิญผ่านมาทุกคน ส่งคำขอบคุณจากใจ จากชาวประมงยาโตอูระทุกคน>"
10025110-235 = "...ไม่น่าใช่พัสดุที่ส่งมาผิดนะคะ"
10025110-237 = "'นักท่องเที่ยวใจดีที่บังเอิญผ่านมา' เหมือนจะหมายถึงพวกเราเลยนะ"
10025110-238 = "...ใช้คำซะหรูเชียว"
10025110-239 = "การปราบปรามอาชญากรน่ะ มันเป็นงานของ SRT อยู่แล้ว พอได้รับของตอบแทนแบบนี้ก็รู้สึกเกรงใจขึ้น#nมาเลยแฮะ"
10025110-240 = "แต่เราก็จะปฏิเสธของขวัญที่ส่งมาไม่ได้นี่คะ รับของขวัญนี้ไว้ด้วยความขอบคุณกันเถอะค่ะ"
10025110-241 = "อ๊ะ จริงสิ ซากิ ข้าวกล่องหน้ากุ้งเทมปุระที่เธออยากกินเมื่อกี้น่ะ เอาไปได้เลยนะ ฉันกินอันนี้เอาแล้วกัน"
10025110-242 = "กลับคำพูดง่ายๆ แบบนี้ได้ไง...!"
10025110-244 = "แต่จะว่าไปแล้ว กุ้งพวกนี้มันมีเหลือเฟือถึงขนาดที่กินกัน 10 คนก็ยังกินเหลือเลย... แล้วพวกเราจะกิน#nหมดเหรอ?"
10025110-245 = "เราไม่มีตู้เย็นด้วย จะเหลือทิ้งไว้ก็อาจจะเสียก็ได้..."
10025110-247 = "นะ... นั่นสินะคะ ถ้าปล่อยให้กุ้งเสีย ก็จะรู้สึกผิดกับชาวประมงที่อุตส่าห์ส่งมาให้อีก..."
10025110-248 = "ถ้างั้น เราเอากุ้งพวกนี้ไปแบ่งให้คุณครู [USERNAME] ที่ช่วยพวกเราคลี่คลายเหตุการณ์นี้ดีไหมคะ?"
10025110-249 = "เอาสิ!"
10025110-251 = ""
10025110-257 = ""
10025110-258 = "คุณครูคะ พอจะมีเวลาบ้างหรือเปล่าคะ?"
10025110-259 = "คือว่า พวกฉันมาด้วยเรื่องปฏิบัติการกุ้งคราวก่อนน่ะค่ะ..."
10025110-260 = "ตะ... ตอนนั้นเราได้ความช่วยเหลือจากคุณครูมากมายเลย เพราะงั้น..."
10025110-261 = "...จะมัวอ้อมค้อมไปถึงไหนของเธอเนี่ย?"
10025110-262 = "ถ้าเขินที่จะบอก ก็บอกพร้อมกันก็ได้นี่"
10025110-263 = "ถะ... ถ้างั้นก็... พร้อมกัน..."
10025110-265 = "...พวกฉันอยากเลี้ยงตอบแทนคุณครูค่ะ!"
10025110-267 = ""
10025110-270 = "(หลังจากนั้นคุณครูก็ไปที่โคะอุซางิ การ์เด้น และปิ้งบาร์บีคิวกุ้งมื้อใหญ่กินกับกองทหาร RABBIT อย่าง#nสนุกสนาน)"
10025110-271 = ""
10025110-274 = "(วันต่อมามีปลาคูซายะ 10 ที่มาส่งที่ชาเล่ต์... และการกินปลาคูซายะให้หมดก็ไม่ใช่เรื่องง่ายเลย)"
10025110-275 = "ปฏิบัติการพิเศษภาคฤดูร้อน! การไล่ล่าของกระต่าย และเรื่องเร้นลับของกุ้งที่หายไป"
