[translation]
10026050-1 = "ตอนที่ 5;จุดสำรวจ C สวนเลมอนที่ถูกทิ้งร้าง"
10026050-2 = "(จุดสำรวจ C คือที่ราบกว้างกลางภูเขาที่มีต้นเลมอนอยู่อย่างแน่นขนัด)"
10026050-3 = "(ต้นไม้ที่ถูกละเลยเป็นเวลานานเติบโตอย่างอัดแน่นและรกมากจนแทบจะมองทางข้างหน้าไม่เห็น)"
10026050-4 = ""
10026050-7 = "[ns1] \"หืม? นี่เราหลงทางหรือเปล่า...?\"\n[ns2] \"แต่ละจุดสำรวจช่างซับซ้อนเหลือเกิน\""
10026050-10 = "เอ๋ คุณครู...? อยู่ตรงนั้นเหรอคะ...?"
10026050-11 = ""
10026050-14 = ""
10026050-15 = "[ns] \"ฮานาโกะ?\""
10026050-16 = "คุณครูก็หลงทางเหมือนกันสินะคะ แต่ก็นะ ต้นไม้มันเยอะเสียขนาดนี้น่ะค่ะ"
10026050-17 = "พูดตามตรง ถ้ามีต้นเลมอนเยอะขนาดนี้ ฉันว่าควรเรียกว่าป่าเลมอนมากกว่าสวนเลมอนมากกว่าอีกค่ะ"
10026050-18 = "ฮุฮุ..."
10026050-19 = "...คะ?"
10026050-20 = "...ฉันรู้ได้ยังไงว่าที่นี่เป็น 'สวน' งั้นเหรอคะ...?"
10026050-21 = "ก็..."
10026050-22 = ""
10026050-24 = ""
10026050-25 = "เอ๋... นั่นสิ... นะคะ?"
10026050-26 = "อืม ฉันต้องตอบยังไงดีนะ? ตอบว่าเป็น... สัญชาตญาณดีไหม?"
10026050-27 = "สัญชาตญาณของฉันมันบอกอย่างนั้นน่ะค่ะ"
10026050-28 = "อืมมม ทำหน้าแบบนี้ แสดงว่าไม่เชื่อจริงๆ ด้วย แต่ก็ไม่ได้ซักไซ้อะไรอีก..."
10026050-29 = "จะว่าไป ฉันว่าคุณครูเหมือนจะตระหนักได้ว่าฉันมีเจตนาอะไรบางอย่างอยู่เบื้องหลังเลยค่ะ"
10026050-30 = "มีอะไรที่อยากถามเยอะเลยใช่ไหมคะ? อย่างเช่น ทำไมถึงจัดเตรียมที่แบบนี้ไว้ และทำไมฉันถึงพา#nโคฮารุจังมาด้วย"
10026050-31 = "คุณครู... ไม่ว่าอะไรใช่ไหมคะ? ถ้าฉันจะปกปิดเรื่องนี้ไว้ในใจแบบนี้?"
10026050-32 = "[s3] \"ก็ไม่เห็นเป็นไรเลยนี่? มันเป็นงานของฮานาโกะนี่นา\"\n[s4] \"ครูก็อยากรู้อยู่หรอกนะ แต่ก็ไม่ถึงกับตั้งข้อสงสัยน่ะ\""
10026050-35 = "อ่า..."
10026050-36 = "เจอปฏิกิริยาที่คาดไม่ถึงอีกแล้ว... แต่ยังไงฉันก็ไม่คิดเลยค่ะว่าคุณครูจะตอบแบบนั้น"
10026050-37 = "บางทีฉันอาจจะได้รับความไว้วางใจมากกว่าที่คิดอีกก็ได้นะคะ?"
10026050-38 = "งั้นตอนนี้ถือว่าปล่อยผ่านไปก่อน แต่ถ้าครั้งหน้ามี 'โอกาส' ก็ค่อยเอาไว้ดูบรรยากาศ..."
10026050-39 = "[s] \".........\""
10026050-41 = "[ns7] \"แต่ถ้าอยากบอก ก็บอกได้ตลอดเลยนะ\"\n[ns8] \"พูดมาขนาดนี้แล้ว ถ้าครูปล่อยผ่านก็คงเสียใจใช่ไหม?\""
10026050-44 = "............"
10026050-45 = "ฮุฮุ..."
10026050-46 = "...คุณครูเนี่ย... ต้องบอกว่า... เป็นคนที่ไม่เคยทำให้ผิดหวังเลยนะคะ"
10026050-47 = "อืม นั่นสินะคะ เหมือนถูกส่งไม้วิ่งผลัดให้อย่างนั้นแหละค่ะ"
10026050-48 = "ฉันไม่ค่อยจะคุ้นชินกับวิธีนี้เท่าไรเลย..."
10026050-49 = "แต่ไหนๆ คุณครูก็พูดอย่างนั้นมาแล้ว... งั้นฉันทำอย่างที่คุณครูว่าดีไหมคะ?"
10026050-50 = "อืม ก็ตอนนี้มันฤดูร้อนนี่คะ"
10026050-54 = "เอาเป็นว่า ฉันจะลองทายดูนะคะ เพราะบางทีคุณครูเองก็อาจจะ..."
10026050-55 = "คิดว่าฉันเตรียมสถานการณ์ทั้งหมดนี้มาเพื่อคุณอุยและโคฮารุจังใช่ไหมคะ?"
10026050-56 = "แม้ว่าฉันจะไม่ได้อธิบายให้คุณครูฟังต่างหาก แต่คุณครูก็ไม่ได้กังวลอะไร แล้วก็เอาแต่เชื่อถือฉันด้วย"
10026050-57 = "เกาะห่างไกลที่เป็นเหมือนสถานที่พักผ่อนหย่อนใจ สถานที่ที่ไม่ต่างจากแหล่งท่องเที่ยว"
10026050-58 = "ถึงจะเป็นการสำรวจซากปรักหักพัง แต่ก็ใส่ชุดว่ายน้ำราวกับว่ามาเที่ยวฤดูร้อน"
10026050-59 = "ที่จริงแล้วนี่เป็นสิ่งที่โคฮารุจังคาดหวังมาตลอด แล้วก็ประจวบเหมาะกับที่คุณอุยงานเข้าพอดี..."
10026050-60 = "ฉันก็เลยได้แผนการที่เหมาะสมที่จะคลี่คลายทุกอย่างได้ในคราวเดียวค่ะ"
10026050-61 = "...ค่ะ"
10026050-62 = "สุดท้ายแล้วทุกอย่างก็... เรียกได้ว่าถูกต้องเหมาะสมค่ะ"
10026050-63 = "ส่วนเรื่องที่คุณครูอาจจะคาดเดาไว้แล้วบ้าง..."
10026050-64 = "............"
10026050-65 = "แต่ว่า... คุณครูคะ..."
10026050-66 = "เรื่องนี้แค่... สะ... สมมตินะคะ"
10026050-67 = ""
10026050-69 = ""
10026050-70 = "ถ้าฉันบอกว่า... บางทีคนที่ควรมาที่แบบนี้... ไม่ใช่แค่โคฮารุจังหรือคุณอุย..."
10026050-71 = "คุณครูจะว่ายังไงเหรอคะ?"
10026050-72 = "[s9] \"...ฮานาโกะ?\"\n[s10] \"พูดแบบนั้นหมายความว่า...\""
10026050-75 = "ก็แบบ อืม... ที่จริงแล้วมันเป็นเรื่องธรรมชาตินี่คะ?"
10026050-76 = "ยังไงฉันก็เป็นเด็กม.ปลายในวัยบานสะพรั่ง"
10026050-77 = "ถ้าไม่มองความคิดของคนรอบข้างแล้ว... ฉันก็มีจิตใจเป็นเด็กสาวธรรมดาคนหนึ่ง"
10026050-78 = "บางครั้งก็มีความหวังที่ไร้เดียงสา... และต้องการอะไรเหมือนกับโคฮารุจังหรือคนอื่นๆ"
10026050-79 = "ที่บอกว่าทำเพื่อใครบางคนน่ะ... มันคือข้อแก้ตัวที่ทำให้ตัวเองสบายใจ หรือไม่ก็ข้ออ้างเพื่อตัวเองก็#nเท่านั้น"
10026050-81 = "แต่จริงๆ แล้วภายในใจฉันเองก็แค่อยากทำด้วยเหมือนกัน"
10026050-84 = "ถ้าบอกว่าเสียดายที่ก่อนหน้านี้ฉันไม่ได้ไปด้วย..."
10026050-85 = ""
10026050-86 = "จะว่าแบบนั้นก็ใช่ว่าจะไม่ถูกนะคะ ฮุฮุ"
10026050-87 = "[s] \".........\""
10026050-88 = "อืม คุณครูไม่พูดอะไรเลยนะคะ ...สำหรับเด็กแบบนั้นแล้ว นี่มันเป็นเรื่องที่น่าอึดอัดใจหรือเปล่าคะ?"
10026050-89 = "ค่ะ น่าเสียดายอยู่นะคะ แต่บางทีมันก็อาจจะไม่ใช่เรื่องที่สมควรเท่าไรหรอกค่ะ"
10026050-90 = "[s11] \"ไม่หรอก ครูแค่คิดว่าฮานาโกะก็มีเวลาให้ตัวเองแล้วน่ะ\"\n[s12] \"ครูดีใจที่ฮานาโกะเปิดใจพูดแบบนี้ออกมาได้นะ\""
10026050-93 = "............"
10026050-94 = "อืม งั้นเหรอคะ?"
10026050-95 = "อืม... พอมาคิดดูแล้วก็น่าจะใช่นะคะ"
10026050-96 = "แต่พอมาถึงที่แบบนี้ และได้อยู่ในสถานการณ์ที่มีแต่เราสองคนจริงๆ..."
10026050-97 = "ฉันก็ไม่อยากเสียเวลาไปกับการพูดล้อเล่นหรือคุยไร้สาระเหมือนปกติน่ะค่ะ เรื่องนอกเหนือจากนั้น#nฉันก็ทำได้"
10026050-98 = "จะยังไงก็เถอะ คุณครูคะ"
10026050-99 = "กับความสัมพันธ์นี้... ที่เหมือนในตอนนี้"
10026050-100 = "จะเป็นอะไรไหมคะถ้าในอนาคตฉันจะหวังกับมันอีกหน่อย?"
10026050-101 = "[s] \"ได้สิ\""
10026050-102 = "...เอ๋ ตอบทันทีเลยเหรอ?"
10026050-103 = "ตอบเร็วไปไหมคะ? คุณครูจะตอบง่ายๆ แบบนี้... ก็ได้เหรอคะ?"
10026050-104 = "บางทีนี่อาจจะเป็นการขอร้องที่น่าหนักใจมากกว่าที่คุณครูคิดก็ได้นะคะ"
10026050-105 = "[s13] \"อื้ม ก็นี่มันฤดูร้อนนี่นา\"\n[s14] \"ก็เป็นเด็กม.ปลายวัยกำลังบานสะพรั่งนี่นา\""
10026050-108 = "...ฮุฮุ"
10026050-109 = "ดีเลยค่ะ ถ้างั้นต่อไปฉันจะลองคาดหวังให้มากกว่าเดิมหน่อยนะคะ"
10026050-110 = "...คุณครูรู้ใช่ไหมคะ? เห็นอย่างนี้ ฉันก็ความจำดีใช่เล่นเลยนะคะ"
10026050-111 = ""
10026050-113 = ""
10026050-114 = "สัญญาที่คุณครูให้ไว้ ฉันไม่มีทางลืมแน่ค่ะ♡"
10026050-115 = ""
10026050-117 = ""
10026050-119 = "(จากนั้นคุณครูกับฮานาโกะก็เดินเตร่ในสวนเลมอนและกลับไปที่ค่ายสำรวจด้วยกัน)"
10026050-120 = ""
10026050-123 = "(และเมื่อกลับไปแล้วก็ต้องฟังโคฮารุดุว่าจะลงโทษอยู่หลายครั้ง ด้วยเหตุผลเพียงแค่ไปอยู่ด้วยกันมา#nสองต่อสอง)"
