[translation]
10021022-2 = ""
10021022-3 = ""
10021022-4 = "จำนวนคงเหลือของวงจรหลบหนี - 1 ครั้ง"
10021022-13 = "[ns] (อะ... อ่า...)"
10021022-14 = "...!!"
10021022-15 = "..."
10021022-16 = ""
10021022-19 = "[ns1] (สุดท้ายก็กลายเป็นแบบนี้งั้นเหรอ...)\n[ns2] (สุดท้ายก็จะไม่ได้บอกในสิ่งที่ต้องบอกงั้นเหรอ...)"
10021022-24 = "[ns] แต่ว่า... เรื่องนี้เท่านั้นที่ต้องทำให้ได้"
10021022-26 = "[ns3] รับผิดชอบหน้าที่ของผู้ใหญ่\n[ns4] ทำหน้าที่ของผู้ใหญ่"
10021022-32 = "สีสันเชื่อมโยงกับผู้ครองกล่องแล้ว!"
10021022-33 = "เรื่องนี้... คาดไม่ถึงจริงๆ สีสันมีปฏิกิริยาตอบสนองกับความเจ็บปวดของคนคนนั้นงั้นรึ? หรือว่า..."
10021022-34 = "เป็นไปไม่ได้ คนผู้นั้นไม่มีทั้ง <ความสูงส่ง> <ความลึกลับ> และ <ความกลัว> เลยแม้แต่น้อย <สีสัน> ไม่มีเหตุผลที่จะต้องเชื่อมโยงกับตัวตนที่ไร้ค่าแบบนั้น"
10021022-36 = "นี่มัน...?"
10021022-37 = "คนคนนั้นจะกลายเป็นผู้นำทางสีสันงั้นรึ? เป็นผู้นำแทนเทพมรณะน่ะรึ?"
10021022-39 = "ไม่อาจเข้าใจได้"
10021022-40 = "ไม่อาจเข้าใจได้"
10021022-41 = "ไม่อาจเข้าใจได้"
10021022-43 = "ถึงแม้จะไม่อาจเข้าใจได้... แต่หากพวกเราใช้กล่องใบนั้นไม่ได้แล้วละก็ คงไม่มีความจำเป็นที่จะต้อง#nทำความเข้าใจอีกต่อไป"
10021022-44 = "จงสถาปนาตัวเองขึ้นเป็นผู้นำทางสีสันอย่างที่ต้องการเถิด ผู้ถือครองกล่องเอ๋ย..."
10021022-46 = "เราขอมอบนาม [ruby=คุณครูแห่งคำลวง]เพลนาพาเทส[/ruby] ให้กับเจ้า"
10021022-47 = "อย่าได้คิดว่าตัวเจ้ามีสิทธิ์ในการตัดสินใจใดๆ ด้วยตนเอง ผู้นำทางสีสันเป็นเพียงตัวแทนในการแถลง#nเจตจำนงของนักบวชนิรนามอย่างพวกเราเท่านั้น"
10021022-48 = "พวกเราจะใช้พลังของกล่องนั้นอย่างดีเอง"
10021022-50 = "ส่วนตัวเจ้าจะต้องเสียใจกับทางเลือกนี้ไปชั่วกัลปาวสาน-!!"
10021022-51 = ""
10021022-56 = "[ns5] \"เพลนาพาเทส... มีบางอย่างที่อยากจะบอก...\"\n[ns6] \"เหตุผลที่กลายเป็นผู้นำทางสีสัน และเหตุผลที่ต้องมาที่นี่...\""
10021022-65 = "ขอโทษนะ...คุณครู.... เพราะฉัน...."
10021022-66 = "เพราะฉัน.... เพราะฉัน...มีชีวิตอยู่... เพราะฉันไม่ยอมตายๆ ไป..."
10021022-67 = "...เพราะความผิดพลาดของฉัน......"
10021022-68 = ""
10021022-73 = "...คุณครู?"
10021022-74 = ""
10021022-77 = "เธอไม่ควรเสียใจและตำหนิตัวเองที่ยังมีชีวิตอยู่"
10021022-78 = ""
10021022-81 = "เธอไม่ควรคิดว่าการอยากมีความสุขเป็นเรื่องผิดพลาด"
10021022-82 = ""
10021022-85 = "อย่าวางใจและคิดว่าถ้าตายไปแล้วจะไม่ต้องพบกับความเจ็บปวดอีก"
10021022-86 = ""
10021022-89 = "อย่าคิดว่าเหตุผลที่เธอถือกำเนิดมาเพียงเพื่อพบพานกับความทุกข์"
10021022-90 = "เธอไม่ควรคิดแบบนั้น"
10021022-91 = "ไม่ควรที่จะต้องมี[ruby=นักเรียน]เด็ก[/ruby]คนไหนที่รู้สึกแบบนั้น"
10021022-92 = ""
10021022-95 = "หาก <โลก> ของเด็กคนไหนไร้ความสุขและเต็มไปด้วยความเจ็บปวดละก็"
10021022-96 = "และถ้าหากเด็กคนนั้นปรารถนาให้ชีวิตที่เต็มไปด้วยความสิ้นหวังและความโศกเศร้านี้สิ้นสุดลงโดยเร็ว"
10021022-97 = "และหากคำอธิษฐานนั้นยังคงล่องลอยอยู่ ณ ที่ใดในโลกใบนี้ละก็"
10021022-98 = "ถ้าเป็นเช่นนั้น......"
10021022-99 = ""
10021022-102 = "ก็คือความผิดของเหล่าผู้ที่รับผิดชอบต่อโลกนั้นๆ ไม่ใช่ความผิดของเด็กคนนั้น"
10021022-103 = "เด็กไม่ควรที่จะต้องมารับผิดชอบภาระหน้าที่ของผู้รับผิดชอบต่อ <โลก>"
10021022-104 = ""
10021022-107 = "ต่อให้เด็กคนนั้นจะก่อบาปมากมายเพียงใด หรือจะก่อความผิดที่มิอาจลบล้างได้แค่ไหน"
10021022-108 = ""
10021022-111 = "ก็ไม่ควรเป็นเช่นนั้น"
10021022-112 = ""
10021022-115 = "สิ่งนั้นไม่ว่าเมื่อไร..."
10021022-116 = "ก็เป็นสิ่งที่เหล่าผู้ใหญ่ที่ใช้ชีวิตอยู่บนโลกใบเดียวกับเด็กเหล่านั้น ต้องรับผิดชอบ"
10021022-117 = ""
10021022-126 = "อะ...อะไรกัน มะ...ไม่นะ......"
10021022-127 = "ไม่นะ... ไม่ๆๆ ไม่นะๆๆ...!! หยุดนะ หยุดสิ หยุดดดด-!!"
10021022-128 = "ไม่นะ คุณครู... ไม่นะ...!!!!!"
10021022-129 = "ไม่นะ ไม่นะ ไม่ๆๆๆๆ ไม่นะ คุณครู!!!!!!"
10021022-130 = ""
10021022-135 = "อย่าเข้าใจผิดนะ!!"
10021022-136 = "นั่นไม่ใช่[ruby=นักเรียน]เด็ก[/ruby]อย่างที่เจ้าเข้าใจหรอก!!"
10021022-138 = "นั่นคือการปรากฏตัวของพระเจ้า!! สิ่งนั้นคือความลึกลับ ความหวาดกลัว และความสูงส่ง!!"
10021022-139 = "สิ่งนั้นคือแสงสว่าง ความหวาดกลัว คือผู้ที่ยืนหยัดได้ด้วยตนเอง และคือความเชื่อ สิ่งนั้น... คือตัวตนที่#nน่าพิศวงเกินกว่าที่เจ้าจะเข้าใจได้!!"
10021022-140 = "สิ่งนั้นคือเครื่องหมายของโลกแห่งสัญญะที่แปรสภาพ และถ่ายทอดออกมาสู่โลกแห่งความเป็นจริง!!"
10021022-141 = "[ns] (ไม่ใช่หรอก)"
10021022-143 = "[ns7] (เด็กคนนั้นน่ะ...) \n[ns8] (สิ่งที่ฉันรู้ก็คือเด็กคนนั้น...)"
10021022-146 = "[ns9] (ชอบปั่นจักรยาน... ชอบออกกำลังกาย...) \n[ns10] (ทำหน้ากากเองและชวนไปปล้นธนาคาร...)\n[ns11] (นั่นคือสึนาโอกามิ ชิโรโกะ นักเรียนปี 2 คณะกรรมการแผนงานอะบิดอส)"
10021022-150 = "[ns] \"เป็นแค่เด็กที่กำลังเจ็บปวดอยู่ในโลกที่ฉันเอื้อมมือไปถึงได้แค่นั้น\""
10021022-151 = "ส่วนตัวเจ้าจะต้องเสียใจกับทางเลือกนี้ไปชั่วกัลปาวสาน-!!"
10021022-152 = "[ns] \"อาจเป็นแบบนั้นก็ได้... แต่ถึงจะเป็นอย่างนั้นก็ตาม...\""
10021022-163 = "ปกป้องเด็กในฐานะผู้ใหญ่ ปกป้องนักเรียนในฐานะคุณครู#nนั่นคือความรับผิดชอบของผู้ใหญ่ และเป็นหน้าที่ของคุณครู"
10021022-164 = ""
10021022-167 = "ไม่ว่าจะต้องใช้วิธีอะไรก็ตาม#nไม่ว่าจะต้องแลกด้วยอะไรก็ตาม"
10021022-168 = ""
10021022-180 = "คุณ...ครู...?"
10021022-181 = ""
10021022-185 = "เข้าใจแล้วค่ะ ฉันจะทำความประสงค์ของคุณค่ะ คุณครู"
10021022-186 = "ถึงแม้มันจะหมายถึงการทำลายโลกทั้งใบก็ตาม......"
10021022-187 = ""
10021022-192 = "[ns] ฟังสิ่งที่เพลนาพาเทสอยากจะบอก"
10021022-194 = "ขอฝากนักเรียนพวกนั้นด้วยนะ"
10021022-198 = "[ns] ตอบกลับ"
