[translation]
10039070-1 = "#title;제7화;앤틱 세라핌 비기닝"
10039070-3 = "#stm;[0,0];instant;150;[log=마리]\"모두 싸움을 멈춰 주세요!\"[/log]"
10039070-5 = "#st;[0,0];instant;1;"
10039070-7 = "1;미카;04\n5;나기사 스탠딩;04\n#1;h\n#5;h\n#5;em;[?]\n#wait;1000"
10039070-8 = "5;나기사 스탠딩;04;……? 누구시죠……?"
10039070-9 = "1;미카;11;……! 서, 선생님까지……!?\n#1;em;[?!]\n#1;shake"
10039070-11 = "1;사쿠라코 아이돌;04\n5;미네 아이돌;10;……선생님? 마리 씨……?\n#5;em;[?]\n#1;a\n#5;a"
10039070-12 = "1;사쿠라코 아이돌;04;어째서 이런 곳에…….\n#1;em;[땀]"
10039070-13 = "1;사쿠라코 아이돌;12;아니, 그보다도 어째서 오토바이……?\n#1;stiff\n#fontsize;50"
10039070-14 = "#st;[0,0];instant;1;"
10039070-16 = "1;사쿠라코 아이돌;12\n5;미네 아이돌;10\n#1;d\n#5;d\n#wait;1500"
10039070-17 = "3;마리;04\n#3;a\n#wait;1500"
10039070-18 = "3;마리;04;사, 사정은 모르지만……! 그래도 싸움은 안 돼요, 여러분!\n#3;em;[!]"
10039070-19 = "3;마리;05;서로 조금만 물러서 주시고, 대화로 해결해 주세요! 여기 선생님도 모시고 왔으니까요!"
10039070-20 = "3;마리;08;오늘은 좋은 날이잖아요? 다른 날도 아니고, 소통과 화합을 상징하는 저희 [ruby=카니발]사육제[/ruby] 기간이잖아요?\n#3;em;[?]"
10039070-21 = "3;마리;05;부디 총을 거두시고, 대화와 이해로……!!\n#3;stiff"
10039070-22 = "[ns1] \"우선 모두 진정하자! 총들은 내리고!\"\n[ns2] \"무슨 일인지 말해 줄 수 있겠어?\""
10039070-25 = "3;나기사 스탠딩;10;으, 으음……."
10039070-26 = "3;나기사 스탠딩;02;곤란하군요. 다른 분도 아닌 선생님께, 이런 모습을 보여 드리고 싶진 않았는데 말이죠.\n#3;em;[반응]"
10039070-27 = "3;나기사 스탠딩;07;설명 드리자면 다소 길 수도 있겠지만……. 네, 그렇죠. 다른 분도 아닌 선생님이시니, 말씀은 드려야겠지요."
10039070-28 = "3;나기사 스탠딩;13;지금 이건……. 저희 트리니티의 중대한…….\n#3;em;[...]"
10039070-29 = "3;나기사 스탠딩;13\n#na;사쿠라코 아이돌;……마리!!"
10039070-30 = "3;나기사 스탠딩;13\n#na;사쿠라코 아이돌;마침 잘 왔어요, 마리! 안 그래도 괜찮다면 이곳으로 와 달라고 부탁하려 했거든요."
10039070-31 = "3;나기사 스탠딩;11;……?"
10039070-32 = "3;나기사 스탠딩;13;……??? 무슨……?\n#3;em;[?]"
10039070-34 = "3;마리;02;……?\n#3;a"
10039070-35 = "3;마리;08;네, 네? ……저, 저를요……?\n#3;em;[땀]"
10039070-36 = "3;사쿠라코 아이돌;01;그렇답니다. ……물론 이건 마리의 의사를 들어야겠지만 말이지요."
10039070-37 = "#st;[0,0];instant;1;"
10039070-39 = "3;사쿠라코 아이돌;07\n#3;em;[...]\n#wait;2500"
10039070-40 = "3;사쿠라코 아이돌;07\n5;미네 아이돌;01\n#3;m1\n#5;a\n#3;h\n#5;h\n#wait;1000"
10039070-41 = "3;사쿠라코 아이돌;07\n5;미네 아이돌;01\n#3;h\n#5;h\n#3;greeting\n#wait;1000"
10039070-42 = "3;사쿠라코 아이돌;07\n5;미네 아이돌;01\n#5;em;[반응]\n#3;h\n#5;h\n#wait;1000"
10039070-43 = "5;미네 아이돌;05;……!!"
10039070-44 = "5;미네 아이돌;02;이거 놀랍군요. 마침 저도 같은 생각을 하고 있었는데 말이지요."
10039070-45 = "3;사쿠라코 아이돌;03;후후. 역시……. 저만 그렇게 생각한 게 아니었던 것 같군요.\n#3;em;[음표]"
10039070-47 = "3;마리;04;같은……생각이요……?"
10039070-48 = "3;마리;08;죄, 죄송합니다만……. 무슨 말씀이신지……. 도통 이해가…….\n#3;em;[땀]"
10039070-50 = "5;미네 아이돌;01\n1;사쿠라코 아이돌;99;……후후."
10039070-51 = "1;사쿠라코 아이돌;02;나름대로 생각한 끝에 내린 결론들이지요. 물론 저희의 생각이 맞다면……이지만요."
10039070-52 = "#st;[0,0];instant;1;"
10039070-54 = "5;미네 아이돌;01\n1;사쿠라코 아이돌;01\n#1;em;[...]\n#5;em;[...]\n#1;h\n#5;h\n#wait;2500"
10039070-55 = "1;사쿠라코 아이돌;07;……마리."
10039070-56 = "5;미네 아이돌;02;마리 씨."
10039070-57 = "1;사쿠라코 아이돌;02\n5;미네 아이돌;02\n#na;사쿠라코&미네;……괜찮다면 마리도 함께, 저희의 지도자/리더가 돼 주실 수 있을까요?\n#1;h\n#5;h\n#1;closeup\n#5;closeup"
10039070-59 = "3;마리;08;……!? 네!?!?\n#3;shake\n#3;em;[?!]"
10039070-60 = "3;나기사 스탠딩;04;……!?\n#3;shake"
10039070-61 = "[ns3] \"마리도 함께……!?\"\n[ns4] \"지도자!? 리더!?\""
10039070-64 = "3;사쿠라코 아이돌;07;그동안 저희 연습에만 치중한다는 변명으로, 마리 스스로의 기분에 대해 고려하지 않은 저희의 실책을 사과하고 싶어요.\n#3;em;[반응]"
10039070-65 = "3;사쿠라코 아이돌;01;저희를 위해 준비를 도와주던 마리에게서, 사실 저희들 이상으로 그 활동을 즐기고 있었다는 사실을 떠올렸답니다."
10039070-66 = "3;사쿠라코 아이돌;99;실은 마리가……. 저희보다 훨씬 더 잘……."
10039070-67 = "3;사쿠라코 아이돌;02;아니, \"근본적으로 아이돌에 걸맞는\" 사람이었는데 말이죠.\n#3;em;[한숨]"
10039070-68 = "3;사쿠라코 아이돌;01;저도 미네 단장님과 헤어진 후, 고민을 하며 <아이돌>이라는 존재에 대해 근본적으로 조금 더 찾아봤답니다."
10039070-69 = "3;사쿠라코 아이돌;02;끊임없이 안팎으로 노력하며 공부하고, 연습하고, 땀을 흘리고,"
10039070-70 = "3;사쿠라코 아이돌;17;빛나는 무대와 이벤트를 만들고 많은 사람들을 기쁘게 하기 위해 빛나는 사람. ……이라고 하더군요.\n#3;em;[...]"
10039070-71 = "3;사쿠라코 아이돌;02;……저는 지금의 마리 이상으로, 저 말에 맞는 사람을 최근 본 적이 없습니다."
10039070-72 = "3;사쿠라코 아이돌;99;마리야 말로 아이돌에 어울리는……."
10039070-73 = "3;사쿠라코 아이돌;03;……아니, 이미 저희에게는 아이돌이나 다름없는 존재였던 겁니다.\n#3;em;[반짝]\n#3;closeup"
10039070-74 = "3;미네 아이돌;99;저도 깨닫는 게 늦어 죄송했습니다. 떠올려 보면, 너무나 알기 쉬운 분위기였는데 말이죠.\n#3;greeting"
10039070-75 = "3;미네 아이돌;02;애초에 저희의 방향성과 연습 또한 모두 마리 씨의 가이드 하에서 이루어진 것."
10039070-76 = "3;미네 아이돌;03;마리 씨만 좋으시다면, 오히려 그 자리가 마리 씨가 즐길 수 있는 자리가 되었으면 합니다.\n#3;em;[반응]"
10039070-77 = "3;미네 아이돌;03;저희의 목표는 어디까지나 다른 분들께 다가가고 싶다는 것뿐, 누가 리더를 맡는지는 중요하지 않으니까요."
10039070-78 = "3;미네 아이돌;03\n1;사쿠라코 아이돌;99;게다가 마리는 지금도 수많은 자매님들과 학우분들께 신뢰받고 있는 몸…….\n#3;m5\n#1;a"
10039070-79 = "1;사쿠라코 아이돌;17;그 진실성도 더욱더 모두에게 와닿을 수 있겠지요. ……저희는 그렇게 믿습니다."
10039070-81 = "3;마리;02;그, 그게 무슨 말씀……. 그 말씀은 즉……."
10039070-82 = "#st;[0,0];instant;1;"
10039070-84 = "3;마리;02\n#3;em;[...]\n#wait;2500"
10039070-85 = "3;마리;08\n#3;em;[?!]\n#3;shake\n#wait;800"
10039070-86 = "3;마리;08;자, 잠깐만요! 그렇다는 건……!!"
10039070-87 = "3;마리;04;저……. 저도……!?\n#3;em;[?]\n#3;jump"
10039070-89 = "5;미네 아이돌;01\n1;사쿠라코 아이돌;99;……네. 맞아요. 지금 여기서, 그 말씀을 드리고자 합니다."
10039070-90 = "5;미네 아이돌;99;네, 마리. 갑작스러운 제안이라 당혹스러우시다면 죄송합니다만…….\n#5;em;[반응]"
10039070-91 = "1;사쿠라코 아이돌;07;……마리."
10039070-92 = "1;사쿠라코 아이돌;02\n5;미네 아이돌;02\n#na;사쿠라코&미네;……저희와 함께, <아이돌>이 돼 주었으면 해요.\n#1;h\n#5;h\n#1;closeup\n#5;closeup\n#fontsize;80"
10039070-94 = "3;마리;01;여러분…….\n#3;a"
10039070-95 = "#st;[0,0];instant;1;"
10039070-97 = "3;마리;02\n#3;em;[...]\n#wait;2500"
10039070-98 = "3;마리;04\n#3;em;[?]\n#wait;1500"
10039070-99 = "3;마리;04;어라……. 그, 그럼…….\n#3;stiff"
10039070-100 = "3;마리;08;설마……. 이 자리는 처음부터…….\n#3;em;[땀]"
10039070-101 = "[ns5] \"새 리더를 뽑는다는 게…….\"\n[ns6] \"아이돌 유닛 이야기였…….\""
10039070-104 = "3;사쿠라코 아이돌;07;……?\n#3;em;[?]"
10039070-105 = "3;사쿠라코 아이돌;04;그렇습니다만……. 음? 달리 뭐가 있나요?"
10039070-106 = "3;미네 아이돌;99;이건 매우 중대한 일입니다, 선생님. 저희의 사활을 걸었다 해도 과언이 아닌 이야기지요.\n#3;em;[반응]"
10039070-107 = "3;미네 아이돌;01;……? 음?"
10039070-108 = "3;미네 아이돌;02;왜 그러시죠? 그 표정은…….\n#3;em;[...]"
10039070-109 = "3;미네 아이돌;04;……아."
10039070-110 = "3;미네 아이돌;10;혹시 사실 저희가 착각을 했고, 마리 씨는 딱히 그런 걸 바라지 않으셨다던……가……!!\n#3;em;[!]"
10039070-111 = "3;미네 아이돌;10\n1;사쿠라코 아이돌;12;……!!\n#3;m5\n#1;a"
10039070-112 = "1;사쿠라코 아이돌;10;서, 설마……! 우, 우리가 또 괜한 착각으로 마리에게 짐을 얹고 있는 건……!!\n#1;em;[땀]\n#1;stiff"
10039070-114 = "3;마리;08;아, 아뇨! 아니에요! 절대 그런 뜻은 아니고……!\n#3;jump"
10039070-115 = "3;마리;07;저도 사실 하면서 즐거웠으니까요! 시켜만 주신다면야 정말로 기쁠 것 같……!!"
10039070-116 = "#st;[0,0];instant;1;"
10039070-118 = "3;마리;07\n#3;em;[...]\n#wait;2500"
10039070-119 = "3;마리;08\n#3;em;[?!]\n#3;shake\n#wait;800"
10039070-120 = "3;마리;08;아, 아으……!? 흐에으……!? 제, 제가 무슨 말을……!!!\n#3;stiff"
10039070-121 = "3;마리;09;잊어 주세요. 방금 건 잊어 주세요……!!\n#3;hophop\n#3;em;[훌쩍]"
10039070-122 = "3;마리;08;아, 아니. 그 이전에……! 정말 이제 와서 제가 갑자기 끼어들어도 괜찮은 걸까요……?"
10039070-123 = "3;마리;08;곡도 두 분이서 부르시도록 나눠 놓았었고……. 저는 아직 옷도 없는데……!\n#3;stiff"
10039070-125 = "#st;[0,0];instant;1;"
10039070-127 = "5;미네 아이돌;01\n1;사쿠라코 아이돌;07\n#5;h\n#1;h\n#wait;1000"
10039070-128 = "5;미네 아이돌;11\n1;사쿠라코 아이돌;03\n#5;h\n#1;h\n#5;em;[음표]\n#1;em;[음표]\n#wait;1500"
10039070-129 = "[ns7] \"……그거라면 걱정 안 해도 돼.\"\n[ns8] 품에서 준비해 둔 사진을 꺼내 든다."
10039070-133 = "3;마리;04;……선생님?\n#3;em;[?]"
10039070-134 = "#st;[0,0];instant;1;"
10039070-137 = "3;마리;04\n#3;d\n#wait;1000"
10039070-139 = "5;마리;08;……!?!?! 선생님……!?!?\n#5;em;[?!]\n#5;shake\n#5;a"
10039070-141 = "5;미네 아이돌;01\n1;사쿠라코 아이돌;04;……! 그건……!!\n#1;em;[!]"
10039070-142 = "1;사쿠라코 아이돌;02;역시 선생님께서는 다 염두에 두고 계셨던 거군요."
10039070-143 = "5;미네 아이돌;99;감사합니다, 선생님. 다소 급하게 추진하게 되는 것이 유일한 걱정이었는데, 이걸 이렇게…….\n#5;greeting"
10039070-145 = "3;마리;08;그, 그렇지만……. 그렇지만……!"
10039070-146 = "3;마리;09;으으, 으으으……!?!?\n#3;em;[땀]\n#3;stiff"
10039070-147 = "[ns] \"……마리.\""
10039070-149 = "[ns9] \"마리가 모두를 위하는 만큼, 모두 마리를 위하고 있어.\"\n[ns10] \"하고 싶은 게 있다면, 솔직하게 말해도 좋아.\""
10039070-152 = "3;마리;08;그……. 그런……. 그럴 수가…….\n#3;em;[///]"
10039070-153 = "3;마리;08;그럼……. 그러면…….\n#3;stiff"
10039070-154 = "3;마리;04;그……."
10039070-155 = "3;마리;04;…………………….\n#3;stiff"
10039070-156 = "3;마리;02;……자……."
10039070-157 = "3;마리;02;……잘……. 부탁드리겠습니다…….\n#3;stiff"
10039070-158 = "#st;[0,0];instant;1;"
10039070-160 = "3;마리;02\n#3;em;[...]\n#wait;2500"
10039070-161 = "3;마리;07;……헤헤.\n#3;em;[반짝]\n#3;closeup"
10039070-162 = "#st;[0,0];instant;1;"
10039070-164 = "3;미네 아이돌;12\n#3;em;[!]\n#3;shake\n#wait;1200"
10039070-165 = "3;사쿠라코 아이돌;15\n#3;em;[!]\n#3;shake\n#wait;1200"
10039070-166 = "1;시스터후드;04\n3;트리니티 학생;07\n5;티파티 행정관;02\n#1;h\n#3;h\n#5;h\n#1;em;[!]\n#3;em;[!]\n#5;em;[!]\n#1;shake\n#3;shake\n#5;shake\n#wait;1500"
10039070-167 = "[ns11] \"……!!! 이 위력은……!!\"\n[ns12] \"이건…… 이건 된다……!!!\""
10039070-172 = "#na;일동;마-리! 마-리! 마-리! 마-리!"
10039070-173 = "#na;마리;에, 에……!? 그, 그만……! 그만하세요, 제발……!!"
10039070-174 = "#na;마리;제발……!!!"
10039070-175 = "5;나기사 스탠딩;04\n1;미카;03\n#1;h\n#5;h"
10039070-176 = "5;나기사 스탠딩;04\n1;미카;03\n#5;em;[...]\n#5;h\n#1;h\n#wait;2500"
10039070-177 = "1;미카;14;…………."
10039070-178 = "1;미카;14;……뭐 할 말 없어, 나기 쨩?"
10039070-179 = "1;미카;02;있어야 할 거 같은데?\n#1;em;[?]"
10039070-180 = "#st;[0,0];instant;1;"
10039070-182 = "5;나기사 스탠딩;04\n1;미카;02\n#5;em;[!]\n#5;shake\n#5;h\n#1;h\n#wait;1500"
10039070-183 = "5;나기사 스탠딩;04;미, 미카 씨. 그…….\n#5;stiff\n#5;m3\n#1;dl"
10039070-184 = "5;나기사 스탠딩;04;……이건…… 이건 그러니까…….\n#5;em;[땀]"
10039070-186 = "3;미카;01;……그러니까?\n#3;em;[?]\n#3;closeup"
10039070-187 = "3;나기사 스탠딩;04;……그…….\n#3;closeup"
10039070-188 = "3;나기사 스탠딩;15;……크, 크윽.\n#3;stiff\n#3;em;[세로선]\n#3;closeup"
10039070-189 = "#st;[0,0];instant;1;"
10039070-191 = "3;미카;01\n#3;em;[...]\n#wait;2500"
10039070-192 = "3;미카;99;……흐응~☆\n#3;em;[음표]"
10039070-193 = "3;미카;15;우선 여기 우리가 계속 서 있으면 다른 사람들한테도 민폐니 돌아갈까?"
10039070-194 = "3;미카;99;돌아가서……."
10039070-195 = "3;미카;14;……이야기할 게 좀 많겠다, 그치~?\n#3;closeup\n#fontsize;80"
