[translation]
1003302-1 = "การพบกันอีกครั้ง"
1003302-2 = "(คุณครูมีธุระเลยออกมาจากสำนักงานชาเล่ต์ครู่หนึ่ง และเดินไปตามท้องถนน)"
1003302-3 = "นี่! จะเอายังไงเรื่องไอศกรีมของฉัน!"
1003302-4 = "เฮือกกก?! มะ...มีอะไรเหรอ"
1003302-5 = "ก็นายจามเลยทำให้ท่านพี่ตกใจจนทำไอศกรีมหล่นเลยไม่เห็นเหรอ! ท่านพี่ตั้งตารอ#nชิมไอศกรีมมานานแค่ไหนรู้ไหม!"
1003302-6 = "ยกโทษให้ไม่ได้! ชดใช้ค่า「ซอต์ฟไอศกรีม Mk.02 วานิลลาฟรุ๊ต กิกะจัมโบ้ดีลักซ์ ฤดูใบไม้ผลิ ลิมิเต็ดเอดิชั่น」มาซะ!"
1003302-7 = "มะ...ไม่ยุติธรรมเลย! แค่จามเองนะ!"
1003302-8 = "[s] \"พวกเธอใจเย็นๆ ก่อนสิ”"
1003302-9 = "คุณเป็นใครน่ะ?"
1003302-10 = "ท่านพี่ นั่นคุณครูของชาเล่ต์นี่?"
1003302-11 = "โฮ่... คุณครูคนดังของชาเล่ต์งั้นเหรอ?#nนี่คิดจะเข้ามาจุ้นจ้านเรื่องของเราหรือยังไง?"
1003302-12 = "ก็ดี... ถ้างั้นก็ชดใช้ไอศกรีมแทนหมอนั่นมาก็แล้วกัน!"
1003302-13 = "[s1]“อ๊ะ โหดร้ายสุดๆ!”\n[s2]“ก็อยากซื้อให้หรอกนะ แต่ช่วงนี้กระเป๋าแห้งมากเลย”"
1003302-16 = "ใครสนเรื่องนั้นกันไม่ทราบ! ถ้าชดใช้ไม่ได้ก็จ่ายด้วยร่างกายซะ...!"
1003302-17 = ""
1003302-20 = ""
1003302-21 = ""
1003302-23 = ""
1003302-27 = "[ns] “หะ...หืม?”"
1003302-28 = "ขะ... ขอบคุณที่ช่วยนะ!"
1003302-29 = "แค่จามผิดที่ผิดทางนิดเดียวเกือบเป็นเรื่องใหญ่แล้วซะแล้ว!"
1003302-30 = "คุณครูจากชาเล่ต์สุดยอดจริงๆ!"
1003302-31 = "[s] \"เดี๋ยวนะ เมื่อกี้ไม่ใช่ฉันสักหน่อย... \""
1003302-32 = "ช่วงเปลี่ยนฤดูแบบนี้ ผมเองก็หยุดจามไม่ได้เลย..."
1003302-33 = "ฮะ.. ฮะ... "
1003302-34 = "ฮัดชิ้ว!"
1003302-35 = ""
1003302-38 = "คะ... แค่จามเองนะ!!"
1003302-39 = ""
1003302-41 = ""
1003302-43 = "[ns3] “จู่โจมกะทันหันแบบนี้ หรือว่า...?”\n[ns4] (ต้องรีบออกไปจากที่นี่แล้ว...!)"
1003302-47 = "(จากนั้นการพยายามหลบหลีกกระสุนและระเบิดที่เกิดขึ้นกะทันหันอย่างเอาเป็นเอาตายก็เริ่มขึ้น)"
1003302-51 = "เดี๋ยวสิ! ตรงนี้เป็นพื้นที่ก่อสร้างนะ ห้ามผ่านเข้าไปเด็ดขาด!"
1003302-52 = "เรากำลังจะระเบิดตึกแล้ว..."
1003302-53 = ""
1003302-56 = "พวกเราระเบิดเองได้ ไม่ต้องมาช่วยระเบิดให้หรอกน่า!"
1003302-57 = ""
1003302-59 = ""
1003302-62 = "(หลังจากนั้นคุณครูก็วิ่งหลบระเบิดจนมาถึงที่ที่ไม่มีผู้คน)"
1003302-64 = "หืม? นั่นคุณครูจากชาเล่ต์นี่นา? "
1003302-65 = "ฮ่ะฮ่ะฮ่า! เฮ้ ครู!"
1003302-66 = "หน้าแดงเชียว มีเรื่องอะไรงั้นเหรอ...?"
1003302-67 = ""
1003302-70 = ""
1003302-71 = "อะ...อึ่ก?!"
1003302-72 = ""
1003302-74 = ""
1003302-76 = "[ns] “อึ่ก!”"
1003302-86 = "(คุณครูไม่รู้ว่าวิ่งมาไกลขนาดไหน แต่ก็หนีมาจนถึงที่ที่บริเวณโดยรอบไม่มีผู้คนเลย)"
1003302-89 = "[ns] “แฮ่ก แฮ่ก... แค่นี้คงไกลพอแล้วนะ”"
1003302-90 = ""
1003302-93 = "ฮุฮุฮุ ทีนี้ก็ไม่มีใครมาขวางทางแล้วนะคะ"
1003302-94 = ""
1003302-97 = ""
1003302-98 = "[ns5] “คิดแล้วเชียวว่าเป็นเธอ...”\n[ns6] “วาคาโมะจริงๆ ด้วยสินะ”"
1003302-99 = "ตายจริง... คุณครูทราบอยู่แล้วว่าเป็นฉันเหรอคะ...?"
1003302-100 = "ตายจริง... คุณครูทราบอยู่แล้วว่าเป็นฉันเหรอคะ...?"
1003302-101 = "หรือว่า..."
1003302-102 = "คุณท่านเฝ้ารอฉันอยู่ตลอดเลยเหรอคะ...?"
1003302-103 = "[s] \"หืมมม?\""
1003302-104 = "ฉะ...ฉันทนไม่ไหวอีกต่อไปแล้วค่ะ"
1003302-107 = "― มีความสุขจังเลยค่ะ..."
1003302-110 = "― วาคาโมะผู้นี้"
1003302-112 = "― ทำทุกอย่างก็เพื่อให้ได้เจอกับคุณท่าน...![wa:2010] "
1003302-115 = "― ไม่ว่าจะยังไง  ฉัน....[wa:1670] "
1003302-117 = "― ก็อยากจะบอกความรู้สึกที่มีนี้ กับคุณท่านด้วยตัวเองค่ะ...[wa:270] "
1003302-120 = "―การที่ได้มาพบกันแบบนี้ คงจะเป็น...[wa:300] "
1003302-122 = "― เพราะพรหมลิขิตที่ด้ายแดง...แห่งโชคชะตาผูกเราไว้แน่ค่ะ...[wa:300] "
1003302-125 = "― อ่า... ถะ... ถ้าเอาแต่จ้องกันแบบนั้น...[wa:3640] "
1003302-127 = "― ถึงจะเป็นฉันคนนี้ ก็เขินเหมือนกันนะคะ...[wa:2020] "
1003302-130 = "― แค่เพียง สายตาของคุณท่าน ก็ทำให้ฉัน...[wa:1940] "
1003302-132 = "― รู้สึกสั่นสะท้านไปทั่วร่างกาย...[wa:10] "
1003302-135 = "― แต่ถ้า... คุณท่านต้องการแบบนั้น... ก็ได้เสมอค่ะ ♡[wa:6220] "
1003302-138 = "― เอาล่ะ มาทางนี้สิคะ[wa:1070] "
1003302-140 = "― เข้ามาใกล้ๆ ฉัน เข้ามาใกล้อีกนิด... อุฮุฮุ♡[wa:3610] "
1003302-143 = "เข้ามาใกล้ๆ อีกสิคะ คุณครู..."
1003302-144 = "[s] “วาคาโมะ!”"
1003302-145 = "เอ๊ะ?!"
1003302-146 = "[s7] \"ทำแบบนั้นไม่ได้นะ! ทำให้คนอื่นเดือดร้อนได้ยังไง!\"\n[s8] \"บอกตั้งกี่ครั้งแล้วว่าทำแบบนี้มันไม่ดี?\""
1003302-149 = "คะ...? ตะ...แต่ว่า! "
1003302-150 = "ฉันแค่อยากพบคุณครูอีกครั้งเองนะคะ...!"
1003302-151 = "[s] \"แต่การทำให้คนอื่นเดือดร้อนก็ถือว่าเป็นเรื่องที่ไม่ถูกต้องนะ\""
1003302-152 = "ตะ... แต่ว่า ความรู้สึกในใจของวาคาโมะ..."
1003302-153 = "มันท่วมท้นออกมาจนฉันไม่รู้ว่าจะทำยังไงดีเลยค่ะ...."
1003302-154 = "ได้โปรดเชื่อฉันเถอะนะคะ..."
1003302-155 = "[s] “เรื่องนั้นก็ดีใจอยู่หรอก แต่ถ้าทำแบบนี้อีกครูอาจเกลียดวาคาโมะก็ได้นะ”"
1003302-156 = "...!!"
1003302-157 = "ไม่นะคะ จะยังไงก็ได้ขอแค่อย่าเกลียดวาคาโมะเลยนะคะ!"
1003302-158 = "ถ้าฉันถูกคุณท่านเกลียดละก็... ฉันคง... ฉันคง..."
1003302-159 = "ขอโทษค่ะ! ขอโทษค่ะ! ขอโทษค่ะ ขอโทษค่ะคุณครู! ยกโทษให้ฉันด้วยนะคะ...!"
1003302-160 = "วาคาโมะน่ะ.....! จะไม่มีวัน ไม่มีวัน... ทำให้คุณครูผิดหวังอีก...! ได้โปรดเชื่อฉันเถอะนะคะ...!"
1003302-161 = "ได้โปรดอย่าเกลียดฉันเลยนะคะ ได้โปรดยกโทษให้ด้วยเถอะค่ะ..."
1003302-162 = "[s] “ถ้าวาคาโมะสำนึกผิดแล้วจริงๆ ครูจะยกโทษให้”"
1003302-163 = ""
1003302-165 = ""
1003302-166 = "คุณครู..."
1003302-167 = ""
1003302-170 = "อ๊ะ มีคนมาขัดจังหวะอีกแล้ว"
1003302-171 = "จากนี้วาคาโมะจะพยายามอย่างหนักเพื่อไม่ทำให้คุณครูผิดหวังอีกค่ะ"
1003302-172 = "วันนี้... ฉันต้องขอตัวไปก่อนแล้วละค่ะ"
1003302-173 = "ครั้งหน้า... ฉันมาหาคุณท่านอีกได้ใช่ไหมคะ...?"
1003302-174 = "[s] \"ได้สิ\""
1003302-175 = "ถ้าอย่างนั้นไว้พบกันใหม่นะคะ!"
1003302-176 = ""
1003302-178 = ""
1003302-180 = "(คุณครูยืนมองวาคาโมะที่วิ่งหายออกไปจนลับตา)"
