[translation]
10039110-1 = "ย้อนวันวาน;บ้านผีสิงหลังเลิกเรียน"
10039110-3 = "โอ้ว... นี่คือคาเฟ่ในธีมบ้านผีสิงของทรีนิตี้สินะ..."
10039110-4 = "ดีละ เข้าไปดูกันเถอะว่าจะน่ากลัวมากกว่าของโรงเรียนเราสักแค่ไหน"
10039110-5 = "ตื่นเต้นจัง จะหลอนแค่ไหนนะ~"
10039110-6 = ""
10039110-11 = ""
10039110-12 = ""
10039110-15 = ""
10039110-16 = "ยะ... ยินดี... ต้อนรับ..."
10039110-17 = ""
10039110-20 = ""
10039110-21 = "ฉันคือ... แฟรงเกนนัตสึสไตน์... พร้อมรับออเดอร์แล้ว~"
10039110-22 = "เอ่อ... ไม่เห็นน่ากลัวสักนิดเลย...?"
10039110-23 = "นะ... นั่นน่ะสิ... มันออกไปทางน่ารักด้วยซ้ำ..."
10039110-24 = ""
10039110-26 = ""
10039110-27 = "..."
10039110-28 = "ชิ... ไม่สำเร็จเหรอเนี่ย งั้นก็ต้องเจอผีตัวต่อไป..."
10039110-29 = ""
10039110-31 = ""
10039110-32 = "ไปเลย วิญญาณโบราณอาฆาต...!"
10039110-34 = "เจ้าแห่งความตายที่ปีนขึ้นมาจากนรกขุมสุดท้าย! แสดงให้โลกมนุษย์ได้เห็น#nถึงความสิ้นหวังและคำสาปแช่งที่ชั่วร้ายเลย...!!"
10039110-35 = ""
10039110-38 = ""
10039110-39 = "เฮือก...!"
10039110-40 = "มะ... เหมือนจะมีอะไรน่าขนลุกออกมาเลย...!"
10039110-41 = ""
10039110-43 = ""
10039110-47 = ""
10039110-49 = ""
10039110-51 = ""
10039110-52 = "นัตสึ ยัยบื้อนี่! ทำไมถึงเกริ่นนำใหญ่โตแบบนี้ล่ะ จะเล่นใหญ่ไปถึงไหน!"
10039110-53 = ""
10039110-55 = ""
10039110-56 = "..."
10039110-57 = ""
10039110-59 = ""
10039110-61 = "ฮะ... แฮร่... ฉันคือวิญญาณโบราณ มัมมี่ที่น่าสะพรึง..."
10039110-62 = "ถ้าไม่รีบสั่ง จะโดนสาปนะ... "
10039110-63 = ""
10039110-65 = ""
10039110-67 = ""
10039110-68 = "นี่มัน... คาเฟ่ธีมผีน้อยน่ารักหรอกเหรอ...?"
10039110-69 = "คิดว่าจะได้เจอผีน่ากลัวๆ เสียอีก...?"
10039110-71 = "..."
10039110-72 = "ไม่เห็นลูกค้าจะกลัวเลย ยัยนัตสึคนบื้อ!!!"
10039110-73 = "อึก... อุตส่าห์เลือกผีที่ทุกคนรู้จักมาแล้วเชียว..."
10039110-74 = "แต่ครั้งนี้จะไม่เหมือนเดิมหรอก!"
10039110-75 = ""
10039110-77 = ""
10039110-78 = "เปลวไฟแห่งนรกจะลุกโชน เสียงคำรามอันน่าสยดสยองจะทำให้โลกสั่นสะเทือน! เงาชั่วร้ายจะกลืนกินทุกสิ่ง!"
10039110-80 = "<แคทส์ พาลูค>! ปีศาจแห่งนรกจงเผยตัว!!"
10039110-81 = ""
10039110-83 = ""
10039110-85 = ""
10039110-86 = "บอกแล้วไงว่าอย่าเรียกชื่อนั้น!! ฉันเป็นแค่มนุษย์หมาป่านะ!!"
10039110-87 = "อะไรกัน... แค่ชื่อ 'มนุษย์หมาป่า' ก็พอใจแล้วเหรอ? คิดจะใช้ชีวิตด้วยความตั้งใจแค่นั้นน่ะเหรอ? ต้องมีชื่อเฉพาะสิจะได้ยิ่งมีอิมแพ็ก!"
10039110-88 = ""
10039110-90 = ""
10039110-91 = "เฮ้อ... รีบไปรับออเดอร์เถอะ ปีศาจแห่งนรก...!!"
10039110-92 = ""
10039110-94 = ""
10039110-96 = "ฉันคงต้องฆ่าเธอก่อนแล้วละ!!"
10039110-97 = ""
10039110-100 = ""
10039110-101 = ""
10039110-102 = ""
10039110-104 = ""
10039110-105 = ""
10039110-106 = ""
10039110-107 = ""
10039110-109 = ""
10039110-110 = "นี่คาเฟ่มุกตลกเจ็บตัวเหรอ...?"
10039110-111 = "ฮืม ได้แค่นี้สินะ..."
10039110-114 = "นี่ แบบนี้จะไหวเหรอ? ลูกค้ากำลังผิดหวังอยู่นะ?"
10039110-115 = "ไม่เป็นไรหรอก ที่จริงแล้วยิ่งความคาดหวังของลูกค้าต่ำ ก็จะยิ่งดีนะ"
10039110-116 = "เพราะ 'ของจริง' ของเรารออยู่ต่างหากยังไงล่ะ"
10039110-117 = ""
10039110-119 = ""
10039110-122 = "พอบอกว่าเป็นบ้านผีสิง ฉันก็เลยคาดหวังมากเกินไปน่ะ"
10039110-123 = "ก็ช่วยไม่ได้สินะ ที่นี่ก็คงมีเอกลักษณ์บางอย่างของตัวเองนั่นละ"
10039110-124 = "ปกติถ้าจะเที่ยวที่แบบนี้ก็ต้องไปที่สวนสนุกเลยด้วย..."
10039110-125 = "ไหนๆ ก็มาแล้ว เราสั่งของหวานกินกันดีกว่า มีอะไรบ้างนะ?"
10039110-126 = "ขอสั่งของหวานค่ะ~! มีเมนูให้ดูมั้ยคะ?"
10039110-127 = ""
10039110-132 = ""
10039110-133 = "หืม?"
10039110-134 = ""
10039110-138 = "อะ... อะไรกัน..."
10039110-139 = ""
10039110-141 = ""
10039110-145 = ""
10039110-147 = ""
10039110-148 = "..."
10039110-150 = "..."
10039110-152 = "นะ... นั่นมัน..."
10039110-153 = ""
10039110-155 = ""
10039110-156 = ""
10039110-157 = "..."
10039110-158 = "เอ่อ... ขะ... ขอสั่ง..."
10039110-159 = ""
10039110-161 = ""
10039110-162 = ""
10039110-164 = ""
10039110-166 = ""
10039110-167 = "วะ... ว้ากก!!"
10039110-168 = "นะ... หนีเร็ว!!!"
10039110-169 = ""
10039110-171 = ""
10039110-173 = "..."
10039110-174 = "ละ... ลูกค้าหนีไปแล้ว...? ฉันแค่ยืนนิ่งๆ แบบที่นัตสึบอกเองนะ..."
10039110-175 = "เยี่ยมไปเลย ปิดฉากได้ดีสุดๆ"
10039110-176 = "การปรากฏตัวที่นำความหวาดผวามายังบ้านผีสิงหลังเลิกเรียน... เธอคนนั้นก็คือฆาตกรหน้ากาก มิสมินต์! "
10039110-177 = "ใบหน้าที่ไร้อารมณ์ ก้าวเดินที่ไม่เคยหยุดนิ่ง และการเหวี่ยงไม้อย่างหนักหน่วง"
10039110-179 = "นี่ละความกลัวที่จะบีบรัดหัวใจของทุกคน"
10039110-180 = "นะ... นัตสึ... เราทำแบบนี้ถูกต้องแล้วเหรอ...?"
10039110-181 = "อืม ถูกต้องแน่แท้เลยละ"
10039110-183 = "ถูกต้องกับผีน่ะสิ!! เราเปิดคาเฟ่กันนะ จะทำให้ลูกค้าหนีไปก่อนสั่งขนมได้ยังไง!!"
10039110-184 = "เรื่องนั้นสำคัญด้วยเหรอ? ตอนนี้ไอริคือไอคอนแห่งความสยองขวัญในเจนเนอเรชั่นใหม่ต่อจากไมเคิล ไมเยอส์เลยนะ...!!"
10039110-185 = "แล้วไอริก็เป็นคนเดียวที่ทำหน้าที่แม่ค้าผีได้เป็นอย่างดีในคาเฟ่บ้านผีสิงที่วุ่นวายแห่งนี้ด้วย!"
10039110-186 = "แม่ค้าผีมีหน้าที่ไล่ลูกค้าด้วยรึไง!!"
10039110-187 = "ถ้ายังเป็นแบบนี้ เราคงขายอะไรไม่ได้เลย!! แล้วเราก็เจ๊งกันพอดี! แล้วจะทำยังไงกับเครื่องดื่มกับพวก#nของหวานที่เราเตรียมมาล่ะ?!"
10039110-188 = "ผู้ที่เอาชนะความสยองขวัญนี้ได้เท่านั้นที่จะสั่งได้...!!"
10039110-190 = "มันยากเกินไปหรือเปล่า!!"
10039110-191 = ""
10039110-193 = ""
10039110-195 = ""
10039110-196 = ""
10039110-199 = "[ns] \"ไอริ ยอดมากเลยนะ...\""
10039110-200 = ""
10039110-202 = ""
10039110-203 = "คะ... คุณครู?! มาอยู่ตั้งแต่เมื่อไรคะ?!"
10039110-204 = "[s1] \"น่าจะตั้งแต่ตอนวิญญาณโบราณนะ...\"\n[s2] \"น่าจะตั้งแต่ตอนปีศาจแห่งนรกนะ...\""
10039110-205 = ""
10039110-206 = ""
10039110-209 = ""
10039110-210 = "ฮะ... เฮือก!! แอบยืนดูพวกเราอยู่เหรอ!!! ลืมๆ ไปเลยนะ!!!"
10039110-211 = "ถ้าพูดเรื่องนี้อีกรอบ ฉันจะพังร้านให้เละเลย!!"
10039110-213 = "ส่วนตัวคุณครูคิดว่าไงบ้างล่ะ? คาเฟ่นี้ใช้ได้มั้ย?"
10039110-214 = "[s] \"อื้อ ครูว่าน่ารักดี\""
10039110-216 = "[ns3] \"แต่ไอริน่ากลัวจริงๆ นะ\"\n[ns4] \"แต่ไอริทำหน้าแล้วก็ทำท่าน่ากลัวมากเลย\""
10039110-220 = "งะ... งั้นเหรอคะ... ฉันฟังแล้วก็เหมือนจะรู้สึกดี แต่ก็รู้สึกแปลกๆ ด้วย..."
10039110-221 = "คุณครูเค้าชมน่า เป็นคำชมขั้นสูงสุดเลยละ"
10039110-222 = "นั่นแปลว่าเรามีพรสวรรค์ในด้าน 'ความสยองขวัญ' เลยนะ ไม่ธรรมดาเลยละไอริ สมแล้วที่เป็นหัวหน้า#nของพวกเรา"
10039110-223 = "มะ... มันไม่ใช่อย่างนั้นนะ..."
10039110-224 = ""
10039110-226 = ""
10039110-228 = "น่าอิจฉาจังเลยนะ เพราะไม่ว่าฉันจะทำให้น่ากลัวแค่ไหน ก็ได้ยินแค่คำว่า 'ว้าย' เบาๆ เอง..."
10039110-229 = "[ns] \"หลอกครูหน่อยสิ โยชิมิ!\""
10039110-230 = ""
10039110-232 = ""
10039110-233 = "งะ... เงียบไปเลยนะ!! เดี๋ยวได้โดนผีหักคอหรอก!!"
10039110-235 = "เฮ้อ ไหนๆ ก็คุยเรื่องนี้กันแล้ว ฉันว่าปล่อยให้เป็นแบบนี้ไม่ได้แล้ว ธีมคาเฟ่ของเราคือบ้านผีสิงนะ"
10039110-236 = "เรามีกันตั้ง 4 คน แต่จะให้ไอริน่ากลัวอยู่คนเดียวได้ไง?"
10039110-237 = "นี่พวกเธอ ตีความตัวละครผีของตัวเองกันน้อยไปหรือเปล่า?"
10039110-238 = ""
10039110-241 = ""
10039110-242 = "ว่าไงนะ?"
10039110-243 = "นี่เธอจะพูดอะไรน่ะ?"
10039110-245 = "ไม่ว่าจะหาชุดกับพร็อพไม่ทันแค่ไหนก็ตาม แต่การแสดงออกถึงตัวละครผีของตัวเองก็เป็นหน้าที่ของ#nแต่ละคน"
10039110-246 = "จริงๆ แล้วตัวละครผีของพวกเธอน่ากลัวกว่าของไอริด้วยซ้ำ ถ้าดูจากจำนวนคนที่ฆ่าได้ในหนังละก็ ตัวละครผีของพวกเธอน่ะเหนือกว่าเยอะเลย"
10039110-247 = "ถะ... ถึงจะอย่างนั้นก็เถอะ..."
10039110-249 = "แล้วทำไมถึงจะทำให้บ้านผีสิงของเรามันน่ารักมากกว่าน่ากลัวล่ะ?!"
10039110-250 = ""
10039110-252 = ""
10039110-253 = "ทำไมถึงอยากถูกมองว่าเป็นเด็กม.ปลายล่ะ เราต้องถูกมองว่าเป็นผีสิ!!"
10039110-254 = "ใครบอกว่าเป็นอย่างนั้นกันเล่า!! ฉันไม่ได้อยากให้คนอื่นมองว่าน่ารักสักหน่อย!!"
10039110-255 = "งั้นก็ไปศึกษามาอีก! ไปหาข้อมูลว่าต้องทำยังไงถึงจะทำให้คนกลัวได้มากกว่านี้!"
10039110-256 = "งะ... เงียบไปเลยนะ! แล้วชุดเฉิ่มๆ ของเธอน่ะ คิดว่าจะทำให้คนอื่นกลัวได้งั้นเหรอ?!"
10039110-257 = "ก็แฟรงเกนสไตน์เป็นผีที่อ่อนแอที่สุดในบรรดาผีทั้งหมดนี่ แฟรงเกนสไตน์ไม่ค่อยทำร้ายใครหรอกนะ"
10039110-258 = "คารมคมคายนักนะยัยนี่!"
10039110-259 = "ฮึ่ย น่าโมโห! พอโต้แย้งทฤษฎีของฉันไม่ได้ ก็เลยจะใช้กำลังสินะ!"
10039110-260 = ""
10039110-262 = ""
10039110-263 = ""
10039110-264 = ""
10039110-265 = "จับยัยนี่มัดไว้เลย! มัดห้อยหัวไว้น่าจะน่ากลัวกว่าเดิมนะ!"
10039110-266 = ""
10039110-268 = ""
10039110-269 = ""
10039110-271 = "แฟรงเกนสไตน์จะไม่ยอมหรอก! จะไม่ยอมจนกว่าชาตินี้จะเจอของหวานขั้นสุดยอด!!"
10039110-272 = ""
10039110-277 = ""
10039110-278 = "ทะ... ทุกคน... ใจเย็นๆ แล้วมานั่งคิดกันเถอะ"
10039110-279 = "เป้าหมายของเราคือการทำให้ลูกค้ากลัวงั้นเหรอ?"
10039110-280 = ""
10039110-283 = ""
10039110-284 = "เอ๋...? ไม่ใช่อย่างนั้นหรอกเหรอ?"
10039110-286 = "พวกเราไม่ได้เปิด 'บ้านผีสิง' แต่เปิด 'คาเฟ่' ในธีมบ้านผีสิงกันต่างหาก"
10039110-287 = "ฉันไม่คิดว่าเราต้องเข้าหาลูกค้าด้วยความน่ากลัวเท่านั้นหรอกนะ"
10039110-288 = "งั้นเหรอ..."
10039110-289 = "พอเอาแต่มุ่งเน้นกับธีมของคาเฟ่ ฉันก็มีความคิดแบบนั้นโดยไม่รู้ตัวเลย..."
10039110-290 = "อืม แล้วผีที่น่ารักก็มีเยอะแยะไปด้วย..."
10039110-291 = ""
10039110-294 = ""
10039110-295 = "เดี๋ยวสิ ทำไมถึงมากังวลกันตอนนี้ล่ะ? เราต้องทำตามคอนเซ็ปต์ที่วางไว้ตั้งแต่ตอนแรกไม่ใช่หรือไง?"
10039110-296 = "นี่! เราจะหาความสมบูรณ์แบบตั้งแต่แรกไม่ได้หรอกนะ!"
10039110-297 = "เดี๋ยวสิ นี่เป็นเพราะเธอต่างหาก! ก็เธอชอบเอาคอนเซ็ปต์เพี้ยนๆ มาเสนอเราอยู่เรื่อย...!"
10039110-298 = "เดี๋ยวเหอะ!! แล้วจะเอายังไงล่ะ?!"
10039110-299 = ""
10039110-301 = ""
10039110-303 = ""
10039110-304 = "[ns] \"ค่อยยังชั่วหน่อยนะที่เห็นทุกคนมีพลังล้นเหลือกัน...\""
10039110-307 = "(บ้านผีสิงหลังเลิกเรียนเปลี่ยนมาชูความน่ารักมากกว่าความน่ากลัว จากนั้นก็เลยได้รับเสียงตอบรับที่ดี#nจากลูกค้า)"
10039110-308 = ""
10039110-311 = "(ว่ากันว่าการแต่งหน้าของไอริเป็นที่นิยมกันมากในหมู่นักเรียนที่ชื่นชอบเรื่องสยองขวัญ...)"
