[translation]
10033040-1 = "ตอนที่ 4;ง่ายใช่ไหมล่ะคะ?"
10033040-2 = "กิจกรรมต่อไปที่พวกเราเตรียมไว้ให้ก็คือ การฝึกงานฝีมือแบบดั้งเดิมของเฮียกคิยาโคค่ะ!"
10033040-3 = "และที่ที่ทุกคนอยู่กันตรงนี้ก็คือโรงศิลปะที่เราใช้ประดิษฐ์งานศิลปหัตถกรรมจากดินเหนียวสีขาวค่ะ"
10033040-4 = "งานศิลปหัตถกรรมของที่นี่สวยงามจนใช้เป็นของที่ระลึกในเขตต่างๆ ของเฮียกคิยาโคเลยนะคะ!"
10033040-5 = "ถึงจะยังรู้สึกแปลกใหม่ในตอนแรก แต่ถ้าได้ลองจับและปั้นดินเหนียวด้วยตัวเอง และถ่ายทอดความเป็นตัวเองออกผ่านงานศิลปะละก็...!"
10033040-6 = ""
10033040-9 = ""
10033040-10 = "แปลว่าให้เราปั้นได้ตามใจชอบเลยใช่มั้ย?"
10033040-11 = "ถ้างั้นก็... ดีละ ฉันได้ไอเดียแล้ว! ฉันจะทำเป็นหอคอยที่มีแขน 2 ข้างออกมา!"
10033040-12 = "จะปั้นเป็นหอคอย แต่ทำไมถึงมีหน้าตาด้วยล่ะ?"
10033040-14 = "ให้คอยสอดส่องดูแลไง... ติดไว้ตรงหน้าหอคอยอันหนึ่ง หลังหอคอยอันหนึ่ง แล้วก็ตรงยอดหอคอยอีกอัน...!"
10033040-15 = "จากนั้นก็ใส่แขนทั้ง 2 ข้างเข้าไป...!"
10033040-17 = "เป็นหอคอยที่... เห็นแล้วน่าหงุดหงิดชะมัด"
10033040-18 = "นั่นน่ะเป็นจุดสำคัญเลยนะ!"
10033040-20 = "เอาที่สบายใจเลย... ส่วนของฉันก็ติดแมงกระพรุนไว้กับอะมีบา แล้วใส่ขาไดโนเสาร์เข้าไป...!"
10033040-21 = "อะ... เอ่อ... ทุกคนคะ?! ทำไมถึง..."
10033040-22 = "[ns1] \"เหมือนกำลังปั้นอะไรที่แหวกแนวไปจากงานฝีมือดั้งเดิมเลยนะ...\"\n[ns2] \"แบบนี้จะไม่เป็นไรเหรอ?\""
10033040-25 = "โฮ่โฮ่โฮ่... ไม่เป็นไรหรอกครับ ไม่เป็นไรอยู่แล้ว จะเรียกว่านี่เป็นวัฒนธรรมใหม่ก็ได้ครับ"
10033040-26 = "วัฒนธรรมเป็นสิ่งที่พัฒนาจากการแลกเปลี่ยนและการเปลี่ยนแปลงอยู่แล้ว... และประเพณีของวันนี้#nก็คือปัจจุบันของเมื่อวานครับ"
10033040-28 = "ติดระเบิดควันสีขาวไว้ที่ระเบิดมือแบบแท่ง! แล้วก็ปิดจบด้วย... อืม... ด้วยอะไรดีนะ?"
10033040-29 = "ระเบิดทำลายรถถังมั้ย? ทั้งราบและก็กว้างดีด้วย น่าจะเอามาใช้เป็นฐานได้ดีเลยนะ!"
10033040-30 = "ดีละ งั้นก็ผสมเยลลีนาปาล์มกับกระสุนปืนลูกซอง...!"
10033040-31 = "ว่าแต่นี่มันงานฝีมือจริงเหรอ?"
10033040-32 = "งานศิลปะก็คือระเบิด! ฉันเคยได้ยินมาจากสักที่น่ะ!"
10033040-34 = "[ns] \"จะไม่เป็นไรจริงๆ เหรอ?!\""
10033040-35 = "อะ... อืม...!"
10033040-37 = "มีไอเดียอะไรบ้างมั้ย คิราระจัง?"
10033040-38 = "อืม~ เป็นกระเป๋าน่าจะดีนะ กระเป๋าถือดินเหนียวดีมั้ย?"
10033040-39 = "ธรรมดาไปรึเปล่า แต่มันก็เหมาะกับเธอดีนะ เอ๋ คุณครู? ทำไมทำหน้าอย่างนั้นล่ะ?"
10033040-40 = "[s3] \"กำลังฮีลตัวเองอยู่น่ะ\"\n[s4] \"เหมือนมีโจ๊กอุ่นๆ ซึมลงไปในกระเพาะที่อักเสบเลย...\""
10033040-43 = "อะฮ่าฮ่าฮ่า ถึงจะไม่รู้ว่าหมายถึงอะไร แต่ที่พูดมาก็ตลกดีนะ!"
10033040-45 = "ทะ... ทุกคนคะ?! ถึงฉันจะไม่ค่อยแน่ใจ แต่นั่นมัน... ระเบิดหรือเปล่าคะ?! ถ้ามันบึ้มขึ้นมาล่ะ...?!"
10033040-47 = "ไม่เป็นไรหรอก นี่เป็นสารประกอบระเบิดแบบ A ต่อให้จุดไฟก็แค่ไหม้เฉยๆ มันไม่ระเบิดออกมาหรอก ถ้ามีท่อจุดชนวนละไม่ว่า"
10033040-48 = "อย่างที่เห็นว่าถ้ามองจากภายนอกก็เหมือนกับดินเหนียวสีขาว ถ้างั้นมันก็เหมาะที่จะอยู่ในโรงศิลปะนี้#nแล้วละ"
10033040-50 = "มันแปลกตั้งแต่เอาของพรรค์นี้เข้ามาในโรงศิลปะแล้วค่ะ...!!"
10033040-51 = ""
10033040-54 = ""
10033040-55 = "ก็นะ... เด็กโรงเรียนเรามีอิสระกันมากเลยใช่มั้ยล่ะ?"
10033040-56 = "อะฮ่าฮ่าฮ่า แต่ยังไงครูก็อยู่ที่นี่ด้วยทั้งคน คงไม่เป็นไรหรอกน่า ฉันเชื่อในตัวครูอยู่แล้ว!"
10033040-57 = "[s] \"ครูจะสู้ๆ นะ...\""
10033040-59 = "โอ้ว! งานปั้นที่เป็นรูปดาบนี่นา! ดูเหมือนสัญลักษณ์ของอัศวินเลยนะคะ!"
10033040-60 = "เรื่องอัศวินอะไรนั่นฉันไม่รู้หรอก แต่ระหว่างเดินมาฉันเห็นของแบบนี้แขวนตกแต่งอยู่น่ะ ก็เลยลองทำตามดู"
10033040-61 = "ยอดไปเลยค่ะ ยอดเลย ถ้างั้นก็เพิ่มดินเหนียวรูปด้วงกว่างเข้าไปตรงนี้...! แล้วทำเป็นนักรบด้วงกว่างกันดีกว่า!"
10033040-62 = "นักรบด้วงกว่างเหรอ... แบบนั้นใครจะไปอดใจไหว! ถ้างั้นฉันจะปั้นนายพลด้วงคีมมายืนประจัญหน้ากัน#nเลย!"
10033040-64 = "ฮ้าววว.... ตั้งใจทำกันจังเลยนะ ระวังอย่าให้เลยเวลาละ... คร่อก zzZ..."
10033040-65 = "จะ... จะว่าไป กำหนดการต่อไปของเรา..."
10033040-67 = "(ในระหว่างที่ทุกคนสนุกสนานไปกับการทำงานฝีมือ...)"
10033040-68 = ""
10033040-69 = "ตอนนี้ละ...!"
10033040-70 = ""
10033040-74 = "[ns] \"หืม? ตุ๊กตางานฝีมือที่จัดแสดงไว้หน้าทางเข้าโรงศิลปะ...?\""
10033040-75 = "ขยับได้งั้นเหรอ?!"
10033040-76 = "กำลังเข้ามาทางนี้แล้วค่ะ!"
10033040-77 = "เฮือก! ฉากนี้ทำให้ฉันนึกถึงการต่อสู้นองเลือดของอัศวินซอมบี้ที่กลับมาอีกครั้งในเรื่อง <เหมียวมาเฟีย - ราตรีที่ตุ๊กตาขยับได้> เลยค่ะ!"
10033040-79 = "อะไรน่ะ มีอะไรขยับอยู่ตรงนั้นด้วย"
10033040-80 = "เป็นกิจกรรมจากโรงศิลปะให้เราทำงั้นเหรอ?"
10033040-81 = ""
10033040-83 = ""
10033040-85 = "อ๊ะ ไม่สิคะ ทุกคน! ถ้าจู่ๆ ก็กรูกันไปอย่างนั้นละก็..."
10033040-86 = "อย่างน้อยเราต้องทำงานศิลปะตรงนี้ให้เสร็จภายใน 23 นาทีนะคะ... นี่ไม่ใช่เวลาไปสนใจอย่างอื่น...!"
10033040-87 = "เอ๋?! เรื่องนั้นสำคัญกว่าตุ๊กตาขยับได้เหรอ?!"
10033040-88 = "คะ? ตุ๊กตาขยับได้เหรอคะ?"
10033040-89 = ""
10033040-93 = "หืม?! ทำไมถึงขยับล่ะคะ?! นะ... นี่เป็นกิจกรรมที่พีน่าเตรียมไว้เหรอคะ?!"
10033040-95 = "ฉันขอจับดูหน่อย!"
10033040-96 = "ถ้าลองทุบตรงไหนแล้วจะขยับอีกมั้ยนะ? สารตั้งต้นระเบิดยังอยู่มั้ย? มีใครมีท่อจุดชนวนรึเปล่า?"
10033040-98 = "อะ... อะไรน่ะ?! คนพวกนี้ ทำไมไม่กลัวกันเลยสักนิดล่ะ?!"
10033040-99 = "เกิดอะไรขึ้นกันนะ...? เราก็ทำงานในโรงศิลปะมาครึ่งชีวิตแล้ว แต่ไม่เคยเจอเรื่องแบบนี้เลย...!"
10033040-100 = ""
10033040-102 = ""
10033040-103 = "เข้าใจแล้ว! ไขปริศนาทั้งหมดได้แล้ว!"
10033040-104 = "[ns] \"เดี๋ยวก่อน! ชมรมพัฒนาออนเซ็นเหรอ?!\""
10033040-106 = ""
10033040-107 = "ฮุฮุฮุ... ถึงจะหลอกทุกคนได้ แต่หลอกสายตาของชมรมพัฒนาออนเซ็นไม่ได้หรอก!"
10033040-108 = "แม้ว่าหัวหน้าคาสุมิจะถูกไล่ตามด้วยเหตุผลหลายอย่าง ไม่สิ ถึงจะงานยุ่งจนมาเข้าร่วมทัศนศึกษาด้วย#nไม่ได้..."
10033040-109 = "แต่หัวหน้าก็บอกว่าอย่าทิ้งความฝันเกี่ยวกับออนเซ็นเด็ดขาด! และเบาะแสของออนเซ็นก็มีอยู่ทุกที่!"
10033040-110 = ""
10033040-113 = ""
10033040-114 = "ถูกต้องที่สุด!"
10033040-115 = ""
10033040-117 = ""
10033040-120 = "[ns] \"สิ่งที่อยากจะสื่อ... คืออะไรเหรอ...?\""
10033040-121 = "มันก็เรื่องง่ายๆ! คิดว่าทำไมตุ๊กตางานฝีมือที่ไม่มีทางขยับได้ ถึงได้ขยับขึ้นมากันล่ะ..."
10033040-122 = "นั่นเป็นเพราะ! สายน้ำใต้ดินที่ไหลอยู่ใต้พื้นดินตรงนี้มีพลังงานแรงมากยังไงล่ะ! ต้องเป็นแบบนี้ไม่ผิดแน่!"
10033040-124 = "คะ...?"
10033040-125 = "[s] \"ไม่ได้นะ... แบบนี้ก็แปลว่า...!\""
10033040-127 = ""
10033040-128 = "ออนเซ็นอยู่ที่ไหน มีพวกเราอยู่ที่นั่น! และต่อให้ไม่มีออนเซ็น ก็ยังมีพวกเราอยู่ดี!"
10033040-129 = "ถ้ามีสายน้ำใต้ดินไหลอยู่ งานที่เหลือก็แค่พัฒนาที่ตรงนั้นแล้วสร้างบ่อออนเซ็นขึ้นมา!"
10033040-130 = "จะว่าไป เราจะทำยังไงกับตุ๊กตางานฝีมือพวกนี้ดีล่ะ?"
10033040-131 = "เอาไว้ใช้เป็นมาสคอตหลังจากสร้างบ่อออนเซ็นเสร็จแล้วดีมั้ย?"
10033040-132 = ""
10033040-134 = ""
10033040-135 = "จริงด้วย แบบนั้นดีเลย!"
10033040-136 = "เอาละ มาระเบิด! ขุดเจาะ! แล้วก็พัฒนาออนเซ็นกันเลย!"
10033040-137 = ""
10033040-139 = ""
10033040-140 = "ทุกคนฟังให้ดีนะ นี่คือเวลาของออนเซ็นนน!!!"
10033040-142 = "คนพวกนี้สติสมประกอบหรือเปล่า?!"
10033040-144 = "เอาแล้ว เริ่มอีกแล้วแฮะ..."
10033040-145 = "อะฮ่าฮ่าฮ่า แบบนี้มันไม่อันตรายเหรอ?"
10033040-147 = "ไม่ได้นะคะ... ถ้าเป็นแบบนี้... การทัศนศึกษาต้อง...!"
10033040-148 = "......"
10033040-149 = "เป็นแบบนี้สินะ ทุกสิ่งที่เกิดขึ้นล้วนมีเหตุผล..."
10033040-150 = "นี่ต้องเป็นวัฒนธรรมใหม่แน่นอน... ต้องเป็นสิ่งที่โลกสั่งสอนเราไม่ผิดแน่...!"
10033040-151 = "นั่นมันก็จริง...!"
10033040-152 = "[ns] \"ไม่น่าจะใช่อย่างนั้นนะ!\""
10033040-154 = "[ns] \"ไม่ได้การละ ไกด์ทุกคนมารวมตัวกันทางนี้!\""
10033040-156 = "ค่ะ... ค่ะ! คุณครู!"
10033040-157 = "ใช่แล้วค่ะ... นี่ไม่ใช่เวลาที่จะมาเฝ้าดูอยู่เฉยๆ นะคะ! ฉันจะทำตามคำสั่งของคุณครูไปจนกว่าชีวิตจะ#nหาไม่เลยค่ะ!"
10033040-158 = "ว้าวว! โล่งอกไปทีนะที่มีคุณครูอยู่ด้วย..."
10033040-159 = "ทุกคนมาหลบข้างหลังฉันก่อน...!"
10033040-161 = "ยะโฮ่~ พวกเราก็มาด้วยนะครู! อุมิกะจัง!"
10033040-162 = "เฮ้อ... อายจนอยากแทรกแผ่นดินหนีเลย"
10033040-163 = "[s] \"เอริกะ? คิราระ?\""
10033040-165 = "ก่อนอื่น... ช่วยทำให้ชมรมออนเซ็นสงบสติอารมณ์หน่อยนะคุณครู"
10033040-166 = "แล้วที่เหลือ พวกฉันจะหาทางจัดการดู เอาตามนี้นะ?"
