[translation]
10039040-1 = "Episode 4;The Road to Pop Idol Stardom: The Song"
10039040-2 = "Hmm... Let's see here... Hmm..."
10039040-3 = "Costumes, check. Dance training, check."
10039040-4 = "So far, so good. Thanks to you, Sensei."
10039040-5 = "Now, we just need to pick a song, and we'll be all done."
10039040-6 = "We'll be all...done."
10039040-7 = ""
10039040-9 = ""
10039040-10 = "[ns1] \"....Mari?\"\n[ns2] \"Is there something on your mind?\""
10039040-13 = "...?! H-Huh?! No, it's nothing."
10039040-14 = "I was just...zoning out. I must be tired. Heehee."
10039040-15 = "Well, no time for that. I need to find a song."
10039040-16 = "Sensei, perfect timing."
10039040-17 = "Huh...?"
10039040-18 = "Who's there?"
10039040-19 = "[ns3] \"...? Utaha?\"\n[ns4] \"Sounds like...\""
10039040-23 = ""
10039040-24 = "...Heehee. I couldn't help but overhear."
10039040-25 = "I'm almost hurt, Sensei. Pop idols, that's so much fun I just..."
10039040-26 = ""
10039040-28 = ""
10039040-29 = "I can't believe you left me out of the loop."
10039040-30 = "[s5] \"What was that hesitation just now?\"\n[s6] \"What was that about fun?\""
10039040-33 = "Oh, don't sweat the details. Anyway, you sounded like you might need help."
10039040-34 = "What do you need? Costumes? Choreography...?"
10039040-35 = "...A song?"
10039040-36 = "Ah, a song! Perfect. I have plenty of them ready to go."
10039040-37 = "...Huh? You want to know why I have songs ready?"
10039040-38 = "Well, it's because..."
10039040-39 = "...I plan to participate too."
10039040-40 = "[s7] \"You?\"\n[s8] \"An idol engineer?\""
10039040-43 = "Heehee. I thought you might have that reaction."
10039040-44 = "I was hoping to get the whole department involved, but no, it's just me."
10039040-45 = "Hibiki, Kotori, and I couldn't agree on the direction of the music."
10039040-46 = "Maybe my tastes were too progressive for them."
10039040-47 = "But spreading what I love to other people, that's part of a pop idol's role."
10039040-48 = "So maybe they'll change their minds once they see me onstage."
10039040-49 = "A pop idol's...role...?"
10039040-50 = "Well, of course. Every idol has a reason, something that compels them to perform."
10039040-51 = "The desire to convey a message, words they want to say, a name they want to call out..."
10039040-52 = "Or...a burning desire to show everyone the true nature of the masterpiece \"Mirrorball Thundergun.\" Whatever their truest, deepest feelings are."
10039040-53 = "And if someone can make an audience feel that same passion, they're a meister in their own right."
10039040-54 = "By the way, we haven't met. Are you..."
10039040-55 = "...from the Sisterhood? Ah, I see."
10039040-56 = "...Huh?"
10039040-57 = "I see. So she's the idol-in-training, not you."
10039040-58 = "[s9] \"What were you thinking...?\"\n[s10] \"It's a student event, a student event!\""
10039040-61 = "I'm just kidding."
10039040-62 = "Anyway, that's cool. In fact, it makes me want to help even more."
10039040-63 = "You'll make a wonderful idol, Sister. I have a meister's eye for the potential of raw gems."
10039040-64 = "Oh, really?! Thank you!"
10039040-65 = ""
10039040-67 = ""
10039040-68 = ""
10039040-69 = "...W-Wait, what?"
10039040-70 = "...Me? You think... Me?"
10039040-71 = "Wait, but..."
10039040-72 = "Oh, are you NOT the one who wants to be an idol here?"
10039040-73 = "So it WAS Sensei...?"
10039040-74 = "[s11] \"No, of course not.\"\n[s12] \"Like I said, no.\""
10039040-77 = "Haha... Thanks for the kind words, but I'm only helping out."
10039040-78 = "I know a couple of the idols, and I'm trying to make sure they have what they need."
10039040-79 = "Um..."
10039040-80 = ""
10039040-82 = ""
10039040-83 = "...Hm."
10039040-84 = "Well, all right. I understand."
10039040-85 = "It's a shame, though. You really are a wonderful gem."
10039040-86 = "N-no, I...! Look, I really appreciate you saying that, but I'm not that kind of a person."
10039040-87 = "...Oh, you said you might have a song for us. Do you?"
10039040-88 = "Of course. That's what brought me over here."
10039040-89 = "You don't mind me helping out, do you, Sensei?"
10039040-90 = ""
10039040-92 = ""
10039040-93 = "[ns13] \"Go right ahead.\"\n[ns14] \"I trust you.\""
10039040-96 = "Heehee. I'm glad to have your confidence."
10039040-97 = "Sister, let me give you some directions... Good, if you could just go there and wait for us. I have something to talk to Sensei about."
10039040-98 = "Directions to...what?"
10039040-99 = "A karaoke place nearby. Singing and listening is essential for choosing a song."
10039040-100 = "Go wait for us there, and we'll come along soon. You can go alone, right?"
10039040-101 = "Yes, of course!"
10039040-102 = "Thank you, Utaha! I'll... I'll see you there!"
10039040-103 = ""
10039040-105 = ""
10039040-106 = ""
10039040-107 = ""
10039040-108 = "...Hm."
10039040-109 = "Hmmm..."
10039040-110 = ""
10039040-113 = "[ns15] \"...Utaha?\"\n[ns16] \"Is what you want to say...about Mari?\""
10039040-116 = "Just one little thing I wanted to check on."
10039040-117 = "That girl..."
10039040-118 = "Are you SURE she doesn't want to be a pop idol herself?"
10039040-119 = "Why am I asking that again? Well..."
10039040-120 = "Well it seems to me, she really DOES want to do it herself."
10039040-121 = "I think she just doesn't quite realize it yet. I'm surprised you hadn't already suggested it to her."
10039040-122 = "Anyway, that's all I wanted to talk about. Figured I wouldn't be able to sleep tonight if I didn't bring it up."
10039040-123 = "Hm?"
10039040-124 = "You have something in mind? You're in \"wait and see\" mode for now?"
10039040-125 = "Heehee, I knew it was something like that... Well, you're the teacher, so I guess you'd know how to handle it."
10039040-126 = "I hope we can all see her up on stage."
10039040-127 = ""
10039040-129 = ""
10039040-130 = "By the way, Sensei. I think you'll appreciate my song. Here, take a listen..."
10039040-131 = "[s] \"Oh, it's THAT genre!\""
10039040-133 = "After that, Utaha and I went to the karaoke place and helped Mari pick out a song."
10039040-135 = ""
10039040-136 = ""
10039040-137 = ""
10039040-140 = "- The Song Cleared -"
10039040-142 = ""
10039040-145 = "The next day..."
10039040-146 = "Oh, my goodness, this... This is all so much..."
10039040-147 = "You must have gone through so much trouble..."
10039040-148 = "We... We didn't mean to burden you this much."
10039040-149 = "We weren't asking you to go this far... We only wanted you to choose one of our proposals..."
10039040-150 = "I suppose that from your perspective, you couldn't give it less than your all. So this is what we drove her to, Captain Mine."
10039040-151 = "Um..."
10039040-152 = "You don't have to keep saying \"we\"..."
10039040-153 = ""
10039040-155 = ""
10039040-156 = ""
10039040-157 = "Heh... No, actually, I'm just as responsible."
10039040-158 = "We burdened you, that's the fact of the matter. Even now, you have dark circles under your eyes."
10039040-159 = "We're both very sorry."
10039040-161 = "No, no, it wasn't a burden at all! Absolutely not."
10039040-162 = "I enjoyed it. The dark circles are just because...I stayed up late last night picking out a song."
10039040-163 = "Yes. As Mari said, we should be thanking you, not apologizing."
10039040-164 = "And thanks to you, I think we've both found our way forward."
10039040-165 = "Sakurako?"
10039040-166 = "So..."
10039040-167 = "It's already a bit late to say this, but Mari, please go and rest."
10039040-168 = ""
10039040-171 = ""
10039040-172 = ""
10039040-173 = ""
10039040-174 = "H-Huh...?"
10039040-175 = "Well, you must be tired. It must have been an ordeal going out and gathering all this."
10039040-176 = "I promise, Captain Mine and I will put it all to good use."
10039040-177 = "That's right. Not a drop of your effort will go to waste."
10039040-179 = "...Oh, right. Of course..."
10039040-181 = "...? Mari...?"
10039040-182 = "What's wrong...? Is there something bothering you?"
10039040-184 = "*gasp* Um, well, a little... I mean, no! No, it's fine. I'm just tired, like you said. Haha..."
10039040-185 = "Yeah, um, you two hang in there! I'm going to go now!"
10039040-186 = ""
10039040-188 = ""
10039040-189 = ""
10039040-190 = "Mari..."
10039040-191 = "That was odd..."
10039040-192 = "What do you think she was trying to say?"
10039040-193 = "Well, regardless, we need to start practicing at once."
10039040-194 = "We need to break in the costumes, study the song, clear our schedule for the dance lessons..."
10039040-195 = "No time to lose! Her sacrifice will not be in vain!"
10039040-197 = "S-Sacrifice?! Isn't that a bit extreme...?"
10039040-198 = "Sakurako...!"
10039040-199 = "Fine, fine. Let's start right away, as you said."
10039040-200 = ""
10039040-202 = ""
10039040-205 = ""
10039040-206 = "..."
10039040-207 = ""
10039040-210 = ""
10039040-211 = ""
10039040-212 = "Yes, this is Sister Iochi Mari."
10039040-213 = "...Ah, Sister Hinata."
10039040-214 = "Just calling to check in. I'm free now, if you need any help."
10039040-215 = "...Oh?"
10039040-216 = "You're almost finished? So today's work is..."
10039040-217 = "...all wrapped up? I, um, I see. Thank you. You must've really blazed through it all."
10039040-218 = "...Right. Right, okay."
10039040-219 = "Sure, I'll call you soon."
10039040-220 = ""
10039040-222 = ""
10039040-224 = "...Apparently, I have some free time all of a sudden. Maybe I can actually rest."
10039040-225 = "Hmm..."
10039040-226 = "But what is this..."
10039040-228 = "...This strange feeling...?"
