[translation]
10034090-1 = "Afterword 1;Shiina Tsumugi"
10034090-4 = ""
10034090-5 = "[ns1] \"...We're here.\"\n[ns2] \"I think it's this building.\""
10034090-8 = "This is the address she gave us, yeah. Although this isn't the only concert venue around."
10034090-10 = "One thing's for sure, this won't be some borrowed practice room, or rooftop, or any of our other little spots."
10034090-11 = "Nope. We're in a whole different league here."
10034090-12 = "Feels like she's way more professional than we are."
10034090-13 = ""
10034090-15 = ""
10034090-17 = ""
10034090-18 = "Can we just walk in like this? Don't we need to buy tickets or something?"
10034090-19 = "That's how it usually goes."
10034090-20 = "Then again, we don't HAVE to drop in on her right now. If she's got a show today, like she said, she's gotta be busy."
10034090-21 = "True. We can just message her later and say we watched the show, and we liked it."
10034090-22 = ""
10034090-24 = ""
10034090-26 = ""
10034090-27 = "Airi, as our esteemed leader, do you want to handle that?"
10034090-28 = "I already said I'm not doing president things..."
10034090-29 = "President or not, you remain our leader. Why not embrace the prestige?"
10034090-30 = "Of course, staying modest is also a form of \"rock.\""
10034090-31 = "Urgh... That's not it..."
10034090-33 = "All right, let's just go in. Sensei, you've met Tsumugi, right?"
10034090-34 = "[s] \"Yes, she had a bit of a Natsu vibe.\""
10034090-35 = "Huh...?"
10034090-36 = "Ehh... I have a bad feeling about this..."
10034090-37 = "Hm..."
10034090-38 = "L-Let's just go in! Haha...!"
10034090-39 = ""
10034090-41 = ""
10034090-42 = ""
10034090-43 = ""
10034090-44 = ""
10034090-45 = ""
10034090-52 = "WE ALL NEED TO DIIIEEE!!!"
10034090-53 = "OOOWAAAH!!!"
10034090-54 = ""
10034090-55 = ""
10034090-57 = "EVERYBODY DIIIEEE!!!"
10034090-58 = "WAAAH!!!"
10034090-59 = ""
10034090-61 = ""
10034090-62 = ""
10034090-63 = "..."
10034090-64 = "..."
10034090-65 = "..."
10034090-66 = "..."
10034090-67 = ""
10034090-69 = ""
10034090-70 = "...\"A bit of a Natsu vibe,\" you say."
10034090-71 = "[s3] \"Well, uh... Um... It's...\"\n[s4] \"No, she was different when I saw her...\""
10034090-72 = ""
10034090-73 = ""
10034090-75 = ""
10034090-77 = "...I might have to rethink my life."
