[translation]
10038060-1 = "ตอนที่ 6;เราในอนาคตอันไกลโพ้น "
10038060-6 = ""
10038060-7 = "ที่นี่ไม่สะดวกตรงไหนหรือเปล่าคะคุณครู...?"
10038060-8 = "[s1] \"ไม่เลย ครูสบายดี แล้วทุกคนล่ะ?\"\n[s2] \"ไม่ต้องห่วงนะ แล้วคิซากิ มินะ... แล้วรูมิล่ะ?\""
10038060-11 = "ถ้าเป็นเรื่องของ 3 ท่านนั้น ไม่สิ... 2 ท่านกับอีก 1 คนนั้น คุณครูไม่ต้องห่วงหรอกค่ะ"
10038060-12 = "บางที... คุณครูอาจต้องไปยังที่นั่นในเร็วๆ นี้ด้วย ทางย่านการค้าเทพเต่าดำของเราจะพาคุณครูไปใน#nที่ที่ปลอดภัยที่สุดเองค่ะ"
10038060-13 = "สำหรับพวกเราแล้ว นี่ไม่ใช่เรื่องไม่ดีหรอกค่ะ เพราะเท่ากับว่าเราจะได้ใช้หนี้บุญคุณส่วนหนึ่งของท่าน#nประมุขคิซากิด้วย"
10038060-14 = "แต่นั่นก็หลังจากที่ทุกอย่างเข้าที่เข้าทางอย่างปลอดภัย... และท่านประมุขได้ตำแหน่งของตัวเองกลับ#nมาแล้วค่ะ"
10038060-15 = "[s] \"สถานการณ์ในโรงเรียนเป็นยังไงบ้าง?\""
10038060-16 = "ค่ะ ท่านประธานยังอยู่ในร่างเด็กเหมือนเดิม ส่วนนักเรียนที่ยังมีอาการของโรคเด็กลงก็..."
10038060-17 = "ตอนนี้เป็นการยากที่พวกเธอจะออกมาเตร็ดเตร่ข้างนอก นั่นเป็นเพราะสายตาจากคนรอบข้างน่ะค่ะ"
10038060-18 = "โดยเฉพาะนักเรียนที่เป็นที่รู้จักหน้าค่าตาอย่างท่านประธานค่ะ"
10038060-19 = "แต่เครือข่ายข้อมูลของย่านการค้าเทพเต่าดำยังแข็งแกร่งอยู่ เราก็เลยยังสืบหาข่าวสารจากข้างนอก#nนั่นได้อยู่ค่ะ "
10038060-20 = "ฉันจะขอแจ้งข้อมูลของฝ่ายมังกรดำก่อนเลยแล้วกันค่ะ..."
10038060-21 = ""
10038060-23 = ""
10038060-25 = "ตอนนี้ภายในมังกรดำมีการวิพากษ์วิจารณ์เกี่ยวกับท่านประมุขอยู่ค่ะ ที่จริงต้องบอกว่า... เป็นการกล่าว#nโทษมากกว่าการวิพากษ์วิจารณ์ด้วยซ้ำ..."
10038060-28 = "อย่ามองฉันด้วยสีหน้าแบบนั้นสิคะ ตอนแรกฉันก็ไม่อยากจะเชื่อหูของตัวเองหรอกค่ะ"
10038060-29 = "แน่นอนว่าสมาชิกมังกรดำทุกคนไม่ได้มีทีท่าแบบนั้น ตามที่ได้ยินมาส่วนใหญ่จะเป็นสมาชิกมังกรดำ#nหัวรุนแรงที่มีความคิดเห็นแบบนั้นค่ะ"
10038060-30 = "สิ่งที่พวกอนุรักษ์นิยมหัวรุนแรงคิดว่าเป็นปัญหาก็คือตำแหน่งของท่านประมุขในตอนนี้ค่ะ"
10038060-31 = "ถ้าจะเปรียบเทียบกับของโรงเรียนอื่น ก็คงเป็นกระบวนการในการขึ้นมาเป็นประธานนักเรียนน่ะค่ะ..."
10038060-37 = ""
10038060-38 = "ถ้าพิจารณาดูแล้ว การได้รับตำแหน่งของประมุขคิซากินั้น มันไม่ปกติตั้งแต่กระบวนการแล้วค่ะ!"
10038060-39 = "เดิมทีแล้วตำแหน่งประมุขควรเป็นของนักเรียนปี 3 แต่ประมุขคิซากิได้เป็นประมุขตั้งแต่ตอนอยู่ปี 2 ค่ะ!"
10038060-40 = ""
10038060-42 = ""
10038060-44 = "แต่นั่นก็... น่าจะเป็นเพราะการยกย่องของมังกรดำในตอนนั้นไม่ใช่เหรอคะ? และหนึ่งในสาเหตุที่ทำให้#nเกิดปัญหานั้นก็คือ..."
10038060-45 = "ประมุขคนก่อนหน้าประมุขคิซากิถูกปลดออกค่ะ"
10038060-46 = "การปลดประมุขออก... เป็นเรื่องไม่น่ายินดีที่ปกติแล้วจะไม่เกิดขึ้น และไม่ควรปล่อยให้เกิดขึ้นด้วยค่ะ..."
10038060-47 = "แต่เพราะเกิดเรื่องแบบนั้นไปแล้ว ประมุขคิซากิถึงได้ทำลายประเพณีและได้ขึ้นมาเป็นประมุขยังไงล่ะ"
10038060-48 = "พูดอีกนัยหนึ่งก็คือ ตำแหน่งของประมุขคิซากิมีแง่มุมที่ขัดต่อประเพณีตั้งแต่แรกแล้วค่ะ!"
10038060-49 = "แต่การตัดสินใจครั้งนั้น... เป็นการตัดสินใจที่เป็นเอกฉันท์ไม่ใช่เหรอคะ...?"
10038060-50 = "ก็เพราะอย่างนั้นไงล่ะ! ตอนนี้เลยถึงเวลาแล้วที่เราจะแก้ไขกระบวนการที่บิดเบี้ยวมาตั้งแต่เริ่มต้น!"
10038060-53 = "[ns] \"ไม่บอกให้คิซากิรู้จะดีกว่าหรือเปล่า...\""
10038060-54 = "ฉันว่าควรทำตรงกันข้ามมากกว่าค่ะ เพราะถ้ามารู้ทีหลัง ท่านคงตำหนิอย่างเงียบๆ ว่า 'เหตุใดจึงไม่บอกเราตั้งแต่แรก?'"
10038060-55 = "แล้วก็คงพูดว่า 'คนที่เป็นประมุขต้องรับฟังทุกคำวิจารณ์เกี่ยวกับตัวเอง' แน่นอนค่ะ"
10038060-56 = ""
10038060-58 = ""
10038060-59 = "คะ? ฉันทำเหมือนท่านประมุขเลยงั้นเหรอคะ? อืม... ค่ะ ขอบคุณค่ะ"
10038060-60 = "จู่ๆ ฉันก็คิดแบบนี้ขึ้นมา... คุณครูนี่ช่างเป็นคนที่ปฏิบัติต่อทุกคนอย่างบริสุทธิ์ใจจังเลยนะคะ..."
10038060-61 = "[s] \"คนเป็นครูต้องอยู่ข้างนักเรียนอยู่แล้ว!\""
10038060-62 = "นี่ถึงเป็นเรื่องยากสำหรับฉันค่ะ เพราะฉันไม่รู้ว่าควรจะปฏิบัติต่อคุณครูยังไง..."
10038060-63 = ""
10038060-65 = ""
10038060-66 = "มะ... ไม่มีอะไรค่ะ ฉันจะรายงานข้อมูลต่อค่ะ"
10038060-67 = ""
10038060-69 = ""
10038060-70 = "ส่วนชมรมวิจัยศาสตร์การปรุงยา... หรือต้องบอกว่าชินทานิ ไคที่เป็นต้นตอที่แท้จริงของเรื่องทั้งหมด เธอไม่สนใจเกี่ยวกับสถานการณ์ในซานไห่จิงเท่าไรค่ะ"
10038060-73 = ""
10038060-74 = "หืม? การโต้เถียงกันในมังกรดำรุนแรงกว่าที่คิดไว้อย่างนั้นเหรอ?"
10038060-75 = "เนื้อหาหลักของการโต้เถียงกันก็คือ มังกรดำและซานไห่จิงจะถูกปกครองต่อไปในรูปแบบไหน เมื่อประมุขคิซากิไม่อยู่ในตอนนี้"
10038060-76 = "และประมุขคิซากิมีคุณสมบัติในการรับตำแหน่งประมุขหรือเปล่า... อย่างนั้นเหรอ?"
10038060-77 = "ฉันจำเป็นต้องรู้ด้วยหรือไง? เรื่องแบบนั้นเป็นประโยชน์ต่อการทำน้ำอมฤตให้เสร็จสมบูรณ์งั้นหรือ?"
10038060-78 = "เอาเวลาที่จะกังวลเกี่ยวกับข่าวลือที่ไร้ประโยชน์แบบนั้นมาทุ่มเทในการทำน้ำอมฤตเถอะ"
10038060-79 = ""
10038060-81 = ""
10038060-82 = "ตอนนี้วัตถุดิบยังขาด ยังแปรรูปได้ไม่พอ เหนือสิ่งอื่นใด โสมหมื่นปีก็ยังขาดอยู่เยอะมาก"
10038060-83 = "ไปขอสิ่งที่ยังขาดจากมังกรดำ และถ้ายังไม่พอ ก็ไปขอจากย่านการค้าเทพเต่าดำด้วย ฉันจะกลับไปที่#nห้องวิจัย"
10038060-84 = "ไม่มีใครที่เป็นประโยชน์จริงๆ เลยสักคน"
10038060-85 = ""
10038060-87 = ""
10038060-90 = "นั่นก็เลยทำให้... ย่านการค้าเทพเต่าดำของเราที่หยุดทำกิจการมาครึ่งหนึ่งแล้วได้รับการกดดันจาก#nชมรมวิจัยศาสตร์การปรุงยาค่ะ"
10038060-91 = "ถ้าเป็นซานไห่จิงในยาม 'ปกติ' แล้วละก็ มังกรดำต้องเป็นฝ่ายรับผิดชอบในการไกล่เกลี่ยและแก้ไข#nสถานการณ์แบบนี้ แต่ในตอนนี้... ก็อย่างนั้นละคะ"
10038060-95 = "ย่านการค้าเทพเต่าดำก็ต้องรับผิดชอบค่ะ! จะปล่อยไปไม่ได้เด็ดขาด!"
10038060-96 = "เหตุการณ์นี้ต้องมีสาเหตุมาจากพวกย่านการค้าเทพเต่าดำแน่นอน!"
10038060-97 = "พอมีการควบคุมย่านการค้า คนพวกนั้นก็เลยมีจิตใจพยาบาท และก่อความวุ่นวายแบบนี้ขึ้นเพื่อจะ#nยกเลิกเทศกาลเงาจันทร์ค่ะ!"
10038060-98 = "นั่นเป็นการคาดเดาที่เกินไปหน่อยหรือเปล่าคะ...? ยังไม่มีหลักฐานในข้อกล่าวหานั้นเลยนะคะ..."
10038060-99 = "สมาชิกคนอื่นที่อยู่ที่นี่ก็ต้องทำให้ชัดเจนค่ะ! ว่าตัวเองจะอยู่ข้างมังกรดำที่คอยรักษาประเพณีของ#nซานไห่จิง หรือจะอยู่ข้างใครคนใดคนอื่น!"
10038060-100 = "ในยามนี้ที่ตำแหน่งประมุขว่างอยู่ชั่วคราว ถ้าเราไม่ปกป้องมังกรดำกับซานไห่จิงไว้ แล้วใครจะมาทำแบบนั้นคะ!"
10038060-101 = "ตอนนี้ทุกอย่างอยู่ในความวุ่นวาย... ฉันเองก็ยอมรับค่ะว่าเราต้องรีบหาคนที่จะมาเป็นบรรทัดฐานในการ#nคลายความสับสนอลหม่าน..."
10038060-102 = "แต่ว่าเราจะไปหาคนคนนั้นจากที่ไหนเหรอคะ...?"
10038060-103 = "เราต้องกลับคืนสู่ประเพณีดั้งเดิม เราไม่มีทางเลือกอื่นค่ะ"
10038060-104 = "แต่ว่า... จะทำยังไงเหรอคะ...?"
10038060-105 = ""
10038060-107 = ""
10038060-108 = ""
10038060-110 = "ฉันแนะนำว่าให้เราคัดเลือกชมรมและบุคคลที่เหมาะสมกับประเพณีของซานไห่จิงที่สุดค่ะ"
10038060-113 = "[ns] \"มังกรดำกำลังหาคนมาแทนคิซากิอย่างนั้นเหรอ...?\""
10038060-114 = "..."
10038060-115 = "ขอพูดอย่างตรงไปตรงมานะคะ ในฐานะของสมาชิกย่านการค้าเทพเต่าดำ ฉันไม่ค่อยชอบใจมังกรดำ#nมากนักหรอกค่ะ"
10038060-116 = "แต่ก็ต้องยอมรับว่าซานไห่จิงจำเป็นต้องมีมังกรดำ และฉันคิดว่าจะเป็นเช่นนั้นต่อไปในอนาคตด้วยค่ะ"
10038060-117 = "แต่ไม่อยากเชื่อเลยนะคะว่ามังกรดำจะกำจัดประมุขคิซากิออกด้วยเหตุผลที่ว่าท่านทำสิ่งที่ขัดกับ#n'ประเพณี'..."
10038060-118 = "[s] \"......\""
10038060-120 = "[ns] \"ครูอยากฟังเรื่องจากเรย์โจวต่อให้จบก่อน\""
10038060-121 = ""
10038060-123 = ""
10038060-124 = "ค่ะ เข้าใจแล้วค่ะ แต่ฉันก็บอกข้อมูลที่ได้รับมากับคุณครูไปเกือบหมดแล้วค่ะ"
10038060-125 = "เรื่องที่ยังไม่ได้บอกก็คงเป็น... เรื่องที่... ตอนนี้พวกหัวรุนแรงในมังกรดำตกลงที่จะหาคนอื่นที่จะมา#nแทนประมุขคิซากิแล้วค่ะ"
10038060-128 = ""
10038060-129 = "ชมรมการแสดงงิ้วเหรอคะ...?"
10038060-130 = "ไม่คิดว่าชมรมการแสดงงิ้วเป็นชมรมที่เหมาะสมที่สุดเหรอคะ? ชมรมนั้นรักษาและสืบทอดการแสดงงิ้ว#nที่เรียกได้ว่าเป็นวัฒนธรรมดั้งเดิมของซานไห่จิงไว้ได้ถึงทุกวันนี้นะคะ"
10038060-131 = "การแสดงงิ้วเป็นงานที่ต้องใช้พละกำลังเป็นอย่างมาก คางุยะเองก็ฝึกฝนสมาชิกอย่างเข้มงวด ความสามารถในการต่อสู้ของชมรมการแสดงงิ้วก็อยู่ในระดับแนวหน้าของซานไห่จิงด้วยค่ะ"
10038060-132 = "แต่ว่ามันจะถูกต้องเหรอคะ? ฉันหมายถึง... นั่นจะเป็นการตัดสินใจที่สอดคล้องกับประเพณีเหรอคะ?"
10038060-133 = "..."
10038060-134 = ""
10038060-136 = ""
10038060-137 = "ฉันอยากแสดงความคิดเห็นอีกอย่างหนึ่งอยู่พอดีค่ะ"
10038060-138 = "เพื่อตัดสินใจเรื่องนั้น ฉันว่าเราปล่อยตัวคางุยะก่อน แล้วมาฟังความคิดเห็นจากเธอดีมั้ยคะ?"
10038060-139 = ""
10038060-141 = ""
10038060-143 = ""
10038060-145 = "[ns] \"จะไม่เป็นอะไรเหรอ?!\""
10038060-146 = "ฉันก็... ไม่รู้เหมือนกันค่ะว่าต้องตีความเรื่องนี้ยังไง และมันตีความได้อย่างไรบ้าง"
10038060-147 = "ฉันก็เลยมาแจ้งเรื่องนี้เพื่อจะขอคำปรึกษาจากคุณครูค่ะ"
10038060-148 = ""
10038060-151 = "ไม่หรอกค่ะ คุณครูไม่ต้องกดดันถึงขนาดนั้นก็ได้นะคะ คุณครูแค่... พูดอะไรกับฉันบ้างก็พอค่ะ"
10038060-152 = "พอมาคิดดูแล้ว แค่การที่คุณครูช่วยรับฟังฉันอย่างนี้ ฉันก็รู้สึกขอบคุณแล้วค่ะ"
10038060-153 = "[s5] \"อืม... ถามว่าครูคิดยังไงน่ะเหรอ...\"\n[s6] \"นี่เป็นแค่ความเห็นส่วนตัวของครู แค่ฟังผ่านๆ ไปก็พอนะ...\""
10038060-156 = "ขอบคุณค่ะ คุณครู ในอีกทางหนึ่ง นี่ก็เหมือนเรากำลังเรียนอยู่เลยนะคะ "
10038060-157 = "ให้ฉันนั่งลง ยืนขึ้น แล้วแสดงความเคารพดีมั้ยคะ? อ่า... ไม่จำเป็นต้องทำถึงขนาดนั้นก็ได้เหรอคะ? ค่ะ เข้าใจแล้วค่ะ"
10038060-158 = "ฉันรู้จักคำว่า 'อำนาจไม่อาจว่างเปล่าได้' มั้ยน่ะเหรอคะ? ก็เคยได้ยินมาบ้างนะคะ..."
10038060-159 = "อ่า... อย่างนี้นี่เองสินะคะ ปกติแล้วคำพูดนั้นอาจหมายความว่า 'หากที่ใดสูญเสียอำนาจไป ก็ย่อมมีคน#nทะเยอทะยานที่อยากจะเข้าไปอยู่ในที่นั้น'"
10038060-160 = "แต่ก็ยังหมายความว่า 'ย่อมมีการผลักดันคนใดคนหนึ่งให้เข้าไปอยู่ในตำแหน่งนั้นตามความต้องการ#nของคนเบื้องล่าง' ก็ได้อย่างนั้นเหรอคะ...?"
10038060-161 = "ท้ายที่สุดแล้ว อำนาจเป็นเรื่องของความรับผิดชอบและแหล่งที่มา"
10038060-162 = "อย่างนี้สินะคะ... ในชีวิตของเราย่อมเจอกับเหตุการณ์และการเคลื่อนไหวต่างๆ และความรับผิดชอบ#nต่อสิ่งเหล่านั้นย่อมต้องเกิดขึ้นอย่างหลีกเลี่ยงไม่ได้"
10038060-163 = "และต้องมีใครสักคนที่จะชี้นำ ตัดสินใจ และรับผิดชอบการตัดสินใจนั้น..."
10038060-164 = ""
10038060-166 = ""
10038060-167 = "และในแง่นั้น การที่คนที่ทะเยอทะยานได้ขึ้นสู่ตำแหน่งนั้นก็จะเป็นการดีกับตัวเองกว่าสินะคะ?"
10038060-168 = "เพราะอย่างน้อยคนที่มีความทะเยอทะยานคนนั้นจะสามารถทำตามความปรารถนาของตัวเองได้"
10038060-169 = "แต่หากเป็นการขึ้นสู่ตำแหน่งนั้นโดยการยกย่องหรือโดยความปรารถนาจากคนอื่น ทั้งๆ ที่ตัวเองไม่ได้#nต้องการละก็..."
10038060-170 = ""
10038060-172 = ""
10038060-173 = "..."
10038060-174 = "หัวหน้าคางุยะที่ฉันรู้จัก ไม่ใช่คนที่มีความทะเยอทะยานค่ะ"
10038060-175 = "เธอใกล้เคียงกับศิลปินที่เข้มงวดและไม่มีความยืดหยุ่นมากกว่าค่ะ"
10038060-176 = "[s7] \"ใช่ ดังนั้นถ้าคางุยะถูก 'ยกย่อง' ให้รับตำแหน่งนั้น...\" \n[s8] \"ใช่ แล้วถ้าคางุยะคนนี้ได้รับการ 'คัดเลือก' ขึ้นมา...\""
10038060-185 = ""
10038060-186 = "อย่างนี้สินะคะ..."
10038060-187 = ""
10038060-189 = ""
10038060-190 = "บางทีนั่นอาจจะเป็น... โศกนาฏกรรมของพวกเราทุกคนก็ได้ค่ะ"
10038060-197 = ""
10038060-198 = "คุณถูกปล่อยตัวแล้วค่ะ ออกมาเถอะค่ะ หัวหน้าคางุยะ"
10038060-199 = ""
10038060-201 = ""
10038060-203 = ""
10038060-204 = "กะทันหันจังเลยนะคะ นี่คือเจตนารมณ์ของท่านประมุขงั้นเหรอ?"
10038060-205 = ""
10038060-208 = ""
10038060-209 = "..."
10038060-210 = "เป็นเจตนารมณ์ของมังกรดำค่ะ..."
10038060-212 = "ฉันขอถามความหมายที่แฝงอยู่ในคำตอบนี้ได้มั้ยคะ?"
10038060-213 = "ฉันจะอธิบายสถานการณ์โดยละเอียดอีกที เชิญออกไปจากที่นี่ก่อนเถอะค่ะ"
10038060-219 = ""
10038060-220 = "และที่กล่าวมา... คือเหตุการณ์ทั้งหมดที่เกิดขึ้นในซานไห่จิงที่ช่วงที่ผ่านมาค่ะ"
10038060-221 = "เดี๋ยวก่อน... เดี๋ยวก่อนนะคะ คุณกำลังบอกว่า... ท่านประมุขหายไปอย่างไร้ร่องรอย ส่วนชินทานิ ไค ก็กลับมาอยู่ในชมรมวิจัยศาสตร์การปรุงยา... ไม่สิ ที่สำคัญกว่านั้นก็คือ..."
10038060-222 = "โรคเด็กลงที่แสดงอาการประหลาดกำลังระบาดอยู่ในซานไห่จิง ย่านการค้าเทพเต่าดำจึงอยู่ภายใต้#nการควบคุม..."
10038060-223 = "และตอนนี้เราก็ไม่รู้ว่าควรจัดเทศกาลเงาจันทร์หรือเปล่า...?"
10038060-224 = "ทำไมถึงเกิดเรื่องแบบนี้ในซานไห่จิงได้คะ...!"
10038060-225 = ""
10038060-227 = ""
10038060-229 = "..."
10038060-231 = "และเพราะเกิดเรื่องอย่างนั้นไงคะ หัวหน้าคางุยะ เพื่อแก้ไขความสับสนและความไม่เป็นระเบียบนี้ แม้จะเป็นเพียงชั่วคราวก็ตาม "
10038060-232 = "ทางมังกรดำได้ข้อสรุปว่าเราจำเป็นต้องมีกลุ่มที่รักษาและปกป้องประเพณีของซานไห่จิงได้ดีที่สุดค่ะ"
10038060-233 = "แล้วกลุ่มที่ว่านั่นก็คือชมรมการแสดงงิ้วสินะคะ"
10038060-235 = "ใช่แล้วค่ะ"
10038060-236 = ""
10038060-239 = ""
10038060-240 = "ฉันจะถือว่ามันเป็นเกียรตินะคะ แต่ว่า... เมื่อดูจากบรรยากาศแล้ว พวกคุณน่าจะมีเหตุผลอื่นที่ปล่อยตัว#nฉันมาแบบนี้"
10038060-241 = "ใช่แล้วค่ะ ฉันขอพูดอย่างตรงไปตรงมานะคะ"
10038060-242 = ""
10038060-244 = ""
10038060-245 = ""
10038060-247 = "ฉันอยากให้คุณขึ้นมาเป็นประมุขค่ะ จะแค่ชั่วคราวก็ได้ค่ะ"
10038060-248 = ""
10038060-251 = ""
10038060-253 = "...!"
10038060-255 = "ซานไห่จิงในตอนนี้ต้องการประเพณีและความมีระเบียบค่ะ จากการสอบสวนครั้งก่อน ได้ยินมาว่าคุณก็#nเห็นด้วยกับการกลับเข้าโรงเรียนอย่างชั่วคราวของชินทานิ ไคด้วย"
10038060-256 = "ช่างบังเอิญที่ตอนนี้เรื่องนั้นเป็นจริงขึ้นมาแล้ว ถ้าเราใช้ประโยชน์จากสถานการณ์นี้ คุณสามารถนำซานไห่จิงได้ในอย่างที่คุณต้องการค่ะ"
10038060-257 = ""
10038060-259 = ""
10038060-260 = ""
10038060-262 = "..."
10038060-264 = "ฉันไม่รู้ว่าต้องบอกเรื่องนี้กับท่านประมุขและท่านประธานยังไงเลยค่ะ"
10038060-265 = "[s] \"เรื่องนั้นครูจะหาทางให้เอง\""
10038060-266 = "ขอบคุณค่ะ แต่ว่า... เรื่องที่จะเกิดหลังจากนั้นก็เป็นปัญหาค่ะ จากนี้พวกฉันคงต้องคำนึงถึงความเป็น#nไปได้ทั้งหมด และคิดวางแผนสำหรับก้าวต่อไปแล้วสินะคะ"
10038060-267 = "การที่หัวหน้าคางุยะเข้ารับตำแหน่งนั้น ก็ไม่ใช่ว่าจะไม่เป็นปัญหาด้วยค่ะ"
10038060-268 = "เพราะยังไงก็ต้องมีการโต้แย้งในเรื่องความชอบธรรมอยู่แล้วค่ะ"
10038060-269 = "ค่ะ ใช่แล้วค่ะ นักเรียนคนเดียวที่มีคุณสมบัติในการรับช่วงต่อได้... ก็บังเอิญว่าเป็นชินทานิ ไคค่ะ "
10038060-272 = ""
10038060-273 = "เพราะถึงจะว่าอย่างไร เธอก็เป็นคนที่โค่นท่านประมุขคิซากิได้ และ... ก็มีเหตุผลส่วนตัวของเธอด้วย"
10038060-274 = "เหนือสิ่งอื่นใด เธอคือศิษย์เก่าของซานไห่จิงค่ะ"
10038060-277 = "แต่ยังไงชมรมวิจัยศาสตร์การปรุงยาก็ตัดสินใจที่จะไม่ยุ่งเกี่ยวกับเรื่องนี้ อย่างน้อยก็เรื่องคุณสมบัติของชินทานิ ไคน่ะค่ะ..."
10038060-278 = "ถ้ามีการโยกย้ายเรื่องนี้ให้มังกรดำ... หรือให้ชมรมอื่นไม่ว่าจะในรูปแบบใดก็ตาม เรื่องนี้ก็อาจจะราบรื่น#nกว่านี้ก็ได้ค่ะ"
10038060-279 = "แต่สิ่งที่เกิดขึ้นตอนนี้..."
10038060-280 = "[s] \"สุดท้ายแล้วหลายๆ อย่างจะขึ้นอยู่กับการเลือกของคางุยะสินะ\""
10038060-281 = "ค่ะ..."
10038060-282 = "ที่จริงไม่ใช่ 'หลายๆ อย่าง' หรอกค่ะ ต้องบอกว่า 'ทุกๆ อย่าง' มากกว่าค่ะ"
10038060-285 = "เข้าใจแล้วค่ะ"
10038060-286 = "ทั้งสถานการณ์ที่ซานไห่จิงเผชิญอยู่ ทั้งการฟื้นฟูขนบธรรมเนียมประเพณีและกฎระเบียบ... ที่เป็นสิ่งที่#nซานไห่จิงของพวกเราต้องการในตอนนี้"
10038060-287 = ""
10038060-290 = ""
10038060-291 = "ถ้าอย่างนั้นฉันก็ต้อง...!"
10038060-292 = "..."
10038060-293 = ""
10038060-296 = ""
10038060-297 = "..."
10038060-298 = "ขอปฏิเสธค่ะ ฉันไม่อาจรับตำแหน่งประมุขได้หรอกค่ะ"
10038060-299 = ""
10038060-302 = ""
10038060-303 = "ทำไมล่ะคะ?!"
10038060-304 = "...!"
10038060-306 = "เพราะสิ่งที่มังกรดำกำลังขอร้องจากฉันและชมรมการแสดงงิ้วเพื่อจะรักษาประเพณีของซานไห่จิงไว้ คือการขอร้องที่จะทำลายประเพณีของซานไห่จิงยังไงล่ะคะ"
10038060-307 = "ระ... เรื่องนั้นมัน...!"
10038060-308 = "เหนือสิ่งอื่นใด ตอนนี้เรายังไม่รู้ว่าท่านประมุขคิซากิอยู่ที่ไหน ถ้าฉันจะไปดำรงตำแหน่งนั้น ก็เท่ากับว่า#nฉันแย่งชิงอำนาจมาสิคะ นั่นคือความไม่จงรักภักดีอย่างไม่ต้องสงสัยเลยค่ะ"
10038060-310 = "(หัวหน้าคางุยะ...)"
10038060-312 = "ฉันเป็นเพียงศิลปินที่เขียนบทและแสดงงิ้ว สมาชิกคนอื่นในชมรมการแสดงงิ้วก็ไม่ต่างกันค่ะ"
10038060-313 = "จริงอยู่ที่ฉันแข็งแกร่งกว่านักเรียนคนอื่นในชมรม และฝึกฝนทุกคนมาอย่างเข้มงวด แต่ฉันก็ทำไปเพื่อ#nการแสดงงิ้วค่ะ"
10038060-314 = "ยิ่งไปกว่านั้น นั่นคือการทำเพื่อซานไห่จิง ฉันไม่ได้มีจุดประสงค์อื่นแฝงไว้แต่อย่างใดค่ะ"
10038060-315 = "หากทุกอย่างที่ฉันทำไปเป็นการทำเพื่อประโยชน์ส่วนตัวแม้แต่เพียงน้อย ฉันก็ยินดีที่จะรับโทษค่ะ ต่อให้ต้องถูกไล่ออกจากโรงเรียนฉันก็ยอมค่ะ"
10038060-316 = "แต่ว่าตอนนี้ซานไห่จิง...!"
10038060-317 = "ค่ะ... ฉันเข้าใจวิสัยทัศน์ของมังกรดำค่ะ "
10038060-318 = "แน่นอนว่าหากความสับสนวุ่นวายนี้ยังดำเนินต่อไป นักเรียนทุกคนในซานไห่จิงก็จะพลอยได้รับผล#nกระทบไปด้วย..."
10038060-319 = "เข้าใจแล้วค่ะ ในฐานะของคนที่ใกล้ชิดกับประเพณีของซานไห่จิง และในฐานะของหัวหน้าของชมรม#nที่รักษาประเพณีของซานไห่จิงมาจวบจนถึงทุกวันนี้"
10038060-320 = "ฉันจะพยายามอย่างเต็มที่เพื่อการรักษาซานไห่จิงภายใต้ระเบียบของโรงเรียนค่ะ"
10038060-321 = ""
10038060-324 = ""
10038060-325 = "เท่านั้นก็เพียงพอแล้วค่ะ"
10038060-326 = ""
10038060-328 = ""
10038060-329 = "ขอฝากเนื้อฝากตัวด้วยนะคะ หัวหน้าคางุยะ..."
10038060-332 = ""
10038060-333 = "ส่วนนี่คือ... เรื่องที่ทางชมรมวิจัยศาสตร์การปรุงยาฝากมาแจ้งค่ะ..."
10038060-334 = ""
10038060-337 = ""
10038060-338 = ""
10038060-339 = "'ทรัพยากรทุกอย่างในซานไห่จิงเป็นของชมรมวิจัยศาสตร์การปรุงยา ขอให้สนับสนุนทุกอย่างกับเรา'"
10038060-340 = "ฉันขอถามเพื่อความแน่ใจนะคะ ก่อนหน้านี้ทางชมรมวิจัยศาสตร์การปรุงยาร้องขออะไรแบบนี้บ่อยหรือ#nเปล่าคะ?"
10038060-341 = "ไม่ค่ะ ตรงกันข้ามเลยด้วยซ้ำ ถ้าเป็นชมรมวิจัยศาสตร์การปรุงยาเดิม พวกเธอจะบอกว่า 'พวกเราจะไม่#nเรียกร้องใดๆ เพราะงั้นอย่าสนใจอะไรพวกเราเลย' มากกว่าค่ะ..."
10038060-342 = "ถ้าเป็นอย่างนั้น แสดงว่านี่คือข้อเรียกร้องของชมรมวิจัยศาสตร์การปรุงยาที่เปลี่ยนใหม่... ไม่สิ ที่จะกลับไปสู่อดีตที่เคยเป็น..."
10038060-343 = "..."
10038060-344 = "แต่ถึงอย่างไร ฉันคิดว่าคงเป็นเรื่องยากที่จะยอมรับและทำตามข้อเรียกร้องแบบนั้นค่ะ..."
10038060-345 = "มันก็ใช่อยู่หรอกค่ะ แต่ทั้งหัวหน้าคางุยะ ทั้งพวกฉันน่ะ... ก็มาอยู่ตรงนี้ได้เพราะชมรมวิจัยศาสตร์การ#nปรุงยาที่เปลี่ยนใหม่นี้"
10038060-346 = "ถ้าจะปฏิเสธข้อเรียกร้องของชมรมวิจัยศาสตร์การปรุงยาในตอนนี้... ก็น่าจะเกิดสถานการณ์ที่น่าลำบากใจตามมานะคะ"
10038060-347 = "อืม..."
10038060-348 = "เราจะทำตามข้อเรียกร้องของชมรมวิจัยศาสตร์การปรุงยาอย่างชั่วคราวไปก่อน แล้วค่อยคิดหาทาง#nแก้ไขภายหลังจะดีมั้ยคะ...?"
10038060-349 = "นั่นคือความคิดเห็นของมังกรดำเหรอคะ?"
10038060-350 = ""
10038060-352 = ""
10038060-353 = "..."
10038060-354 = "(ไม่มีใครอยากรับผิดชอบเลยสินะ...)"
10038060-355 = "เข้าใจแล้วค่ะ ฉันจะลองทำตามความคิดเห็นนั้นดูค่ะ "
10038060-357 = "ถ้าอย่างนั้น สรุปว่าหัวหน้าคางุยะก็เห็นด้วยกับข้อเสนอนี้นะคะ"
10038060-358 = ""
10038060-360 = ""
10038060-362 = ""
10038060-363 = ""
10038060-364 = "ฮู่ว..."
10038060-365 = ""
10038060-367 = ""
10038060-369 = ""
10038060-370 = ""
10038060-373 = "บ้านก็เป็นดั่งที่พักแรมที่มาอยู่เพียงชั่วครู่ เพราะเราต่างก็เป็นนักเดินทางที่จะต้องจากไปในสักวัน"
10038060-374 = "อำนาจและตำแหน่ง เปรียบดั่งสายลมที่พัดผ่านไป แต่เมื่อราตรีมาถึง และถามหาเส้นทางที่นี่"
10038060-375 = ""
10038060-378 = "ชมรมการแสดงงิ้วจะต้องไปยังแห่งหนไหน และซานไห่จิง... จะก้าวไปในทิศทางใด..."
10038060-380 = "..."
10038060-381 = "ท่านประมุขจะกังวลเกี่ยวกับเรื่องนี้มาโดยตลอดหรือเปล่านะ..."
