[translation]
10031050-1 = "#title;제5화;의장님의 홍보 전략"
10031050-2 = "#na;(만마전의 게헨나 특별 파티 준비를 돕기로 한 세 번째 날을 맞이해, 오늘도 만마전을 찾게 되었다.)"
10031050-3 = "[ns] \"복도까지 전부 파티 사양으로 꾸미고 있구나.\""
10031050-4 = "#na;(파티에 맞춰 점차 화려하게 변모해 가고 있는 게헨나 학원의 복도를 걷고 있을 때였다.)"
10031050-8 = "2;키라라;01\n4;에리카;01\n#4;h\n#2;h\n#4;a\n#2;a"
10031050-9 = "4;에리카;02;응?\n#4;em;[반응]"
10031050-10 = "2;키라라;03;와앗~! 쌤이네~! 안녕안녕~\n#2;em;[음표]\n#2;greeting"
10031050-11 = "[s] \"아, 에리카, 키라라. 안녕. 이런 데서 다 만나네.\""
10031050-12 = "4;에리카;04;그건 오히려 우리가 하고 싶은 말인걸. 느닷없이 우리 학교 복도에서 선생님을 마주치다니…….\n#4;stiff"
10031050-13 = "4;에리카;04;이런 걸 두고 갑작스럽다고 할지…….\n#4;em;[땀]"
10031050-14 = "2;키라라;99;응~ 그야말로 서프라이즈! \n#2;jump"
10031050-15 = "2;키라라;01;후후, 뭔가 오늘 하루는 운이 좋을 것 같네~"
10031050-16 = "[s] \"우, 운이 좋을 것 같다니……? 왜?\""
10031050-17 = "4;에리카;02;아, 키라라 쨩이 말한 거라면 그거야. 느낌적 느낌이라고 할까.\n#4;em;[반응]"
10031050-18 = "4;에리카;99;으음~ 요컨대 말하자면 아무 생각 없이 걷는 길에…… 무심코 내려다본 길바닥에서 우연히 네잎클로버를 발견한 느낌……같은 거려나?"
10031050-19 = "2;키라라;00;아하하핫~! 에리카 쨩의 말이 맞아. 딱 그 느낌!\n#2;hophop\n#2;em;[재잘]"
10031050-20 = "[s] \"잘은 모르겠지만…… 그렇게 생각해 준다면 기쁜 것 같기도…….\""
10031050-21 = "4;에리카;02;그래서 선생님이 여긴 어쩐 일이야? \n#4;em;[?]"
10031050-22 = "4;에리카;04;아…… 만마전의 요청으로 며칠 뒤에 있을 <게헨나 특별 파티>의 준비를 돕기 위해 왔다고……"
10031050-23 = "4;에리카;12;그거참, 듣기만 해도 고생이네."
10031050-24 = "2;키라라;03;아하하핫~! 대박~! 이번 파티, 쌤도 도와주고 있었구나~\n#2;em;[재잘]\n#2;hophop"
10031050-25 = "2;키라라;02;앗, 그럼, <그거>도 쌤의 아이디어야? \n#2;em;[전구]"
10031050-26 = "4;에리카;06;아니, 키라라 쨩. 아무리 그래도 그건 아니겠지……\n#4;stiff"
10031050-27 = "2;키라라;08;그래도 혹시 모르잖아~?\n#2;em;[재잘]"
10031050-28 = "[s] \"<그거>……라니?\""
10031050-29 = "4;에리카;12;그게…… 파티 준비가 계속되면서, 최근 여기저기에 설치되기 시작한 조형물이 하나 있거든.\n#4;em;…"
10031050-30 = "2;키라라;99;그런데 그게 있지~ 엄청 특이하게 생긴 데다가 보기만 해도 빵~ 터지는 물건이라. 게헨나 학생들 사이에서 화제거든~"
10031050-31 = "2;키라라;03;아하핫! 우리도 그걸 찾아서 SNS에 찍어 올리면 좋아요 좀 받을 수 있지 않으려나~ 하고 찾던 참이었는데~\n#2;em;[음표]"
10031050-32 = "[s] \"……??\""
10031050-33 = "4;에리카;02;아, 말로만 설명해도 모르겠지."
10031050-34 = "2;키라라;01;내가 보여줄게! 이거야. 이거!"
10031050-35 = "#st;[0,0];instant;1;"
10031050-37 = "2;키라라;01\n4;에리카;01\n#4;h\n#2;h\n#2;greeting\n#wait;500"
10031050-41 = "[ns] \"………이건…….\""
10031050-42 = "2;키라라;03;그치? 쌤도 빵 터지지?\n#2;jump"
10031050-43 = "4;에리카;00;선생님도 도와주고 있고, 뭔가 잔뜩 기합이 들어간 느낌이라. 이번 파티는 더 재밌을지도 모르겠네."
10031050-44 = "2;키라라;01;그럼 쌤이 준비를 도와준 파티! 기대하고 있을게!"
10031050-45 = "2;키라라;01\n4;에리카;01\n#4;h\n#2;h"
10031050-46 = "[ns] \"으응……. 응원, 고마워.\""
10031050-48 = "#na;(그렇게 키라라와 에리카와 헤어진 뒤, 곧바로 만마전의 집무실에 도착했다.)"
10031050-49 = "#st;[0,0];instant;1;"
10031050-53 = "3;마코토;99\n#3;a\n#wait;1000"
10031050-54 = "3;마코토;03;크크큭…… 방문을 환영한다. [USERNAME] 선생.\n#3;greeting"
10031050-55 = "[s] \"아, 마코토. 몸은 어때? 괜찮아?\""
10031050-56 = "3;마코토;02;응?\n#3;em;[?]"
10031050-57 = "3;마코토;99;아아, 그거라면 괜찮다."
10031050-58 = "3;마코토;10;뭔가, 어제는 중요한 파티 준비를 하다가 본의 아니게 기억이 희미해진 참이다만."
10031050-59 = "3;마코토;01;그런 건 살다 보면 종종 있는 일이니, 신경 쓸 필요 없다."
10031050-60 = "[s] \"종종 있다고 말할 정도의 일이야?!\""
10031050-61 = "3;마코토;99;흐음, 뭐 지나간 일은 지나가 버린 대로 내버려두기로 하고.\n#3;em;…"
10031050-62 = "3;마코토;03;중요한 건 지금부터 이어질 미래. 오늘도 어김없이 선생과 함께 파티 준비에 매진할 뿐이야."
10031050-63 = "[s3] \"아, 파티 준비하니 말인데…….\"\n[s4] \"그렇지 않아도 여기 오는 길에 조금 이상한 걸 봤다고 할지.\""
10031050-66 = "3;마코토;02;게헨나 학교 복도에 이상한 조형물이 있었다고……?\n#3;em;[?]"
10031050-67 = "3;마코토;01;으음, 파티를 맞이해서 게헨나의 학생 중 누군가 흥에 겨워 기습적으로 설치한 물건일지도 모르겠군."
10031050-68 = "3;마코토;99;그런 거라면 조만간 아랫것들을 움직여서 처리하도록 하고."
10031050-69 = "3;마코토;01;그보다 중요한 건 그런 게 아니다. 선생이여.\n#3;em;[반응]"
10031050-70 = "3;마코토;10;마침 오늘 드디어 이 몸이 이번 파티 준비에 있어 가장 공을 들였던 바로 그 <물건>이 완성된 참이니까."
10031050-71 = "3;마코토;10;오늘은 그걸 선생에게 보여주고자 집무실로 부른 거니까 말이지.\n#3;em;…"
10031050-72 = "[s] \"<물건>이 완성되었다니, 뭘 만들었길래…….\""
10031050-73 = "3;마코토;03;키키킷. 바로…… 이것이다!\n#3;em;[재잘]\n#3;hophop"
10031050-74 = "#st;[0,0];instant;1;"
10031050-76 = "3;마코토;03\n#3;d\n#wait;1000"
10031050-79 = "[ns] \"아까 오는 길에 키라라가 보여준 그 이상한 거다!\""
10031050-80 = "3;마코토;04;뭣이?! 그거참 실례되는 말을 하는군!\n#3;a\n#3;hophop\n#3;em;[?!]"
10031050-81 = "3;마코토;04;이것의 어디가 이상하다는 것이냐! 선생이여!"
10031050-82 = "3;마코토;99;어디까지나 이번 파티를 위해 특별 주문 제작한…… 이 하누마 마코토 님의 이지적이고 용감한 모습을 과감한 터치와 대담한 조형으로 표현한 동상이거늘……!\n#3;stiff"
10031050-83 = "3;마코토;03;누가 봐도 위풍당당한 엄청나게 멋진 동상이지 않나!\n#3;jump\n#3;em;[!]\n#fontsize;80"
10031050-84 = "[s] \"딴 건 몰라도 흥에 겨워서 만들어 낸 물건인 건 알겠어!\""
10031050-85 = "#st;[0,0];instant;1;"
10031050-88 = "[ns] \"많이 만든 것 같은데, 뭔가 목적이 있는 거야……?\""
10031050-89 = "3;마코토;02;만든 이유? 그야 두 말이 필요 없이……"
10031050-90 = "3;마코토;10;이번 <게헨나 특별 파티>의 홍보용이다!\n#3;closeup"
10031050-91 = "#st;[0,0];instant;1;"
10031050-93 = "3;마코토;10\n#3;d\n#3;closeup\n#wait;2000"
10031050-94 = "3;마코토;10\n#3;a\n#wait;1000"
10031050-95 = "3;마코토;00;이번 파티는 이 몸이 전력을 다해 준비한 행사다. 그렇다면 그에 어울리는…… 이 몸의 완벽한 위용을 드러내 줄 수 있는 물건이 필요한 것이 당연하겠지."
10031050-96 = "3;마코토;99;그러니 특별 주문한 이 동상들을 파티가 열리는 동안 게헨나 전역에 잔뜩 배치하면……."
10031050-97 = "3;마코토;03;이 하누마 마코토 님의 위엄에 대해, 우리 만마전의 위대함에 대해…… 모든 게헨나 학생에게 널리 알리는 것이 가능하겠지! 키키키킷!!!\n#3;em;[재잘]\n#3;hophop"
10031050-98 = "3;마코토;10;그렇지 않아도 이미 SNS상에선 뜨거운 반향을 일으키고 있다! 이것을 봐라!"
10031050-99 = "#st;[0,0];instant;1;"
10031050-101 = "3;마코토;10\n#3;greeting\n#wait;1000"
10031050-103 = "#na;<키라키라 우루룽☆>: 아하하핫~! 이것 봐! 대박~! 동상이 엄청 많아~!"
10031050-104 = "#na;<GehEricha0201>: 뭐랄까. 통행에 방해될 정도로 많은 느낌인데. 이거 괜찮은 거 맞아?"
10031050-105 = "#na;<akusi-girl>: 아까 보니까 불량배 녀석들이 잔뜩 옮기고 있는 거 같던데?"
10031050-106 = "#na;<#Nyanko&>: 완전 구려."
10031050-107 = "3;마코토;10\n#3;a"
10031050-108 = "[ns5] \"뜨거운 반향……인가?\"\n[ns6] \"그런데…… 이 정도로 많은 숫자면 비용도 많이 든 거 아냐?\""
10031050-111 = "3;마코토;03;칫칫칫.\n#3;em;[재잘]"
10031050-112 = "3;마코토;99;아니다. 선생. 비용 문제라면 전-혀 신경 쓸 필요 없다. 왜냐하면……."
10031050-113 = "3;마코토;03;이번 동상의 제작 비용은 물론, 게헨나 학원 각지에 이를 배치하기 위해 필요했던 인력 고용의 재원까지 전부 만마전의 이름이 아닌, 선도부 앞으로 지불 계약이 되어있기 때문이지!\n#3;em;[!]\n#3;jump"
10031050-114 = "[s] \"………으, 응?\""
10031050-115 = "3;마코토;10;선도부의 예산안을 결정하는 건 우리 만마전이니 말이다!"
10031050-116 = "3;마코토;10;키키킷! 선도부의 예산을 끌어다 파티를 꾸린다! 그걸 통해 선도부 놈들 재정에 타격을 가하고……! 이 몸은 파티를 홍보하고! 선도부는 예산을 빼앗겨 울상 짓게 될 터!\n#3;em;[재잘]"
10031050-117 = "3;마코토;03;그야말로 일석이조! 꿩 먹고 알 먹고! 도랑 치고 가재 잡고! 마당 쓸고 동전 줍고!\n#3;jump\n#3;em;[!]"
10031050-118 = "3;마코토;10;한 가지로 여럿을 해내는 이 마코토 님의 천재적인 계획인 게지!"
10031050-119 = "3;마코토;03;크큭. 크크크큭! 키키키키킷!!\n#3;em;[재잘]\n#3;hophop"
10031050-120 = "[s] \"마코토, 참고로 그 사실을 선도부는…….\""
10031050-121 = "3;마코토;10;모른다!\n#3;closeup\n#fontsize;100"
10031050-122 = "3;마코토;99;원래라면 선도부장이 나서서 방해하려고 들겠지만, 지금 그 녀석은 이 마코토 님의 계략에 의해………\n#3;closeup"
10031050-123 = "3;마코토;03;현재진행형으로 피아노 연습에 정신이 팔려 있으니 말이야……!\n#3;closeup"
10031050-124 = "3;마코토;10;그 빈틈을 노린 이 몸의 완벽한 작전!\n#3;closeup\n#3;jump"
10031050-126 = "#na;마코토;아아! 스스로가 전율스러울 정도로군!!"
10031050-127 = "#st;[0,0];instant;1;"
