[translation]
10038030-1 = "Episode 3;One Adult, Many Children"
10038030-2 = ""
10038030-3 = "This park is usually filled with students..."
10038030-4 = "But now, there's no one here. It feels desolate. "
10038030-5 = "There's no sign of the Peking Opera Club members who used to practice here, or the students who would chat over tanghulu or mango waffles..."
10038030-6 = "......"
10038030-7 = ""
10038030-9 = ""
10038030-10 = "Oh, but there is one food stand still here! Let's go eat something, Sensei. I've got a craving for an egg tart!"
10038030-11 = ""
10038030-13 = ""
10038030-14 = "Me too, me too! I'll even brush my teeth really good afterwards!"
10038030-15 = "[s] \"Uh... Yeah... Okay...\""
10038030-16 = ""
10038030-17 = "Thank you!"
10038030-20 = "Sensei, Sensei! Did you know? They've started selling banji here at the Peach Blossom Spring!"
10038030-21 = "The third-year girls...try to avoid it...'cause it goes against tradition, but..."
10038030-22 = "...once you try it, you've got to have another one!"
10038030-23 = "What's a banji? I've never heard of it."
10038030-24 = "Heehee... A banji is...!"
10038030-25 = ""
10038030-27 = ""
10038030-29 = "It's a chilled fruit cream cake, filled with fresh cream and fruits inside a thin crust!"
10038030-30 = "Mango's the most famous, but you can fill it with whatever you like! Green tea, chocolate, strawberries, whatever!"
10038030-32 = "Oh wow, that sounds delicious!"
10038030-33 = "I REALLY want to try it, Sensei!"
10038030-34 = "[s] \"But didn't you just have an egg tart...?\""
10038030-35 = ""
10038030-37 = ""
10038030-38 = ""
10038030-39 = ""
10038030-40 = ""
10038030-42 = ""
10038030-43 = "Please? Pretty please?!"
10038030-44 = "It goes great with a strong green tea!"
10038030-45 = "The green tea balances out the richness of the fruits and cream, so you can take each bite with a clean palate..."
10038030-46 = ""
10038030-47 = "Can we, please? Pretty please?!"
10038030-48 = ""
10038030-51 = "[ns] \"All right...\""
10038030-52 = ""
10038030-54 = ""
10038030-55 = "Yay! Thank you!"
10038030-56 = "Kiki likes Sensei best!"
10038030-57 = ""
10038030-59 = ""
10038030-60 = "What's wrong? You almost did a spit take!"
10038030-61 = "Sensei, you can't do that! You're an adult! You should watch your manners in a public place. Even I know that!"
10038030-62 = "[s] \"Yeah... Okay...\""
10038030-66 = ""
10038030-67 = "We've been eating a lot! We should try to walk it off!"
10038030-68 = "Great idea! And this is the perfect place for it, too. It's always so calm!"
10038030-69 = "And if we're lucky, we'll meet a panda... Hey, over there!"
10038030-70 = ""
10038030-72 = ""
10038030-73 = ""
10038030-75 = "Um...wouldn't that be dangerous? Pandas are bears, you know..."
10038030-76 = "It's okay! The pandas here are used to people. They enjoy being near them!"
10038030-77 = ""
10038030-79 = ""
10038030-80 = "The ones that live on this side enjoy bamboo shoots, so if you pick one and hand it to them...!"
10038030-81 = ""
10038030-85 = "Puu?"
10038030-86 = ""
10038030-89 = "Bieee!"
10038030-90 = "Look! He's eating it!"
10038030-91 = "Oooh! I want to try! I want to try!"
10038030-92 = "[s] \"Okay, but don't get too close...\""
10038030-93 = ""
10038030-94 = "O-Okay!"
10038030-97 = ""
10038030-98 = "I'm back!"
10038030-99 = "Whew... What an incredibly satisfying day."
10038030-100 = "Really? I'm so glad!"
10038030-101 = "How about you, Sensei?"
10038030-102 = "[s] \"Well, as long as the students enjoyed it...\""
10038030-103 = "We're more like Plum Blossom Garden children than actual students."
10038030-104 = "[s] \"Then as long as the children enjoyed it...\""
10038030-105 = "But what's with that face? You look so distant, like you've reached enlightenment or something."
10038030-106 = "Oh, it's nothing? I don't have to worry about it? Hmm... Really...?"
10038030-107 = ""
10038030-113 = ""
10038030-114 = "Oh, Sensei! Welcome to the Plum Blossom Garden. I heard you played with the children today. You must be exhausted."
10038030-115 = ""
10038030-117 = ""
10038030-118 = "Hi, it's been a while! ...Oh, and who's that next to you?"
10038030-119 = ""
10038030-122 = ""
10038030-123 = "H-Her name's Kiki. She recently transferred here! Shun recommended her."
10038030-124 = ""
10038030-126 = ""
10038030-127 = "Hello, Instructor Kokona! My name is Kiki. It's a pleasure to meet you!"
10038030-128 = ""
10038030-131 = ""
10038030-132 = "*gasp*"
10038030-133 = "Y-You see that, Sensei? I AM a bona fide instructor!"
10038030-134 = ""
10038030-136 = ""
10038030-140 = ""
10038030-142 = ""
10038030-143 = "H-Hmm? You're smiling at me all of a sudden. And why are you patting my head...?!"
10038030-144 = "What? You say it's good to know that the world's still functioning properly? What do you mean by that...?"
10038030-145 = ""
10038030-148 = ""
10038030-149 = "I-I'm going to go...look for Shun. Over that way."
10038030-150 = ""
10038030-152 = ""
10038030-153 = "I'll come with you!"
10038030-154 = ""
10038030-156 = ""
10038030-158 = "W-Wait! Shun is..."
10038030-159 = ""
10038030-162 = "Hmm... Where IS Shun today, anyway?"
10038030-163 = "[s] \"I'll...go help find her.\""
10038030-164 = "Sensei? That's kind of you to offer, but you don't really have to..."
10038030-165 = "Huh? This is something you HAVE to do? You're saying a lot of confusing things today..."
10038030-166 = ""
10038030-168 = ""
10038030-169 = ""
10038030-170 = "All right, I'll leave it to you. I have to go take care of the other children."
10038030-171 = "Which I can do, as a Plum Blossom Garden instructor! No trouble at all!"
10038030-173 = ""
10038030-174 = "Whoa, we almost got caught. Kokona's got a good sense about these sorts of things."
10038030-175 = "Hmm."
10038030-176 = "At least we've achieved our intended goal of covertly investigating Shanhaijing. Well done, everyone."
10038030-177 = "...How do you think it went, Madam?"
10038030-178 = "Hmm... How should I say this...?"
10038030-179 = ""
10038030-183 = "Kisaki...?"
10038030-184 = ""
10038030-186 = ""
10038030-188 = ""
10038030-190 = ""
10038030-191 = "Huh?!"
10038030-192 = "Oh, hello! My name is Kiki. I just transferred here, so I don't know many people. What's your name?"
10038030-193 = ""
10038030-195 = ""
10038030-196 = "......"
10038030-197 = "......"
10038030-198 = "Kisaki, what...are you doing...?"
10038030-199 = "S-So, like I said, I'm Kiki..."
10038030-200 = "This is all a bit much..."
10038030-201 = "......"
10038030-202 = "Heh, I guess there's no fooling you. "
10038030-203 = "...Can someone explain? Kisaki? Sensei?"
10038030-204 = "[s] \"Let's...take this someplace else first.\""
10038030-207 = ""
10038030-208 = ""
10038030-209 = ""
10038030-210 = "...Okay, I've checked that there's no one around and our voices shouldn't carry too far."
10038030-211 = "And even if someone does see us, they'll just think the Plum Blossom Garden children are at the park with their instructor."
10038030-212 = "So come out with it already, Kisaki. What are you up to?"
10038030-214 = "It's nothing to worry about."
10038030-215 = "We simply...chose an outfit that happened to fit our needs here."
10038030-216 = "Oh... You're undercover. I see..."
10038030-217 = "I am aware that you go undercover from time to time, you know."
10038030-218 = "But why the whole \"Kiki\" business?"
10038030-219 = "Well... A covert investigation outfit must take into consideration the timing, the situation, the surrounding circumstances..."
10038030-220 = "Okay, if you say so. Heh, I'm reminded of the time you snuck in with that Black Tortoise Promenade disguise."
10038030-221 = "Ah, of course you remember that. Visually, that disguise was perfect. Everything was going right."
10038030-222 = "And then you tried to cook. That was bound to give you away! Heehee! "
10038030-223 = "Be glad I was the one who caught you. If someone else had figured it out, you'd have had a political problem on your hands."
10038030-224 = "And I've paid that debt in full."
10038030-225 = "I know, I know. Just reminiscing."
10038030-226 = "Right, so what are YOU up to, exactly?"
10038030-227 = "Me? Well...since the Moonlight Festival might or might not be held this year, I wanted to make sure the Plum Blossom Garden children all got moon cakes."
10038030-228 = "Would you like one? I have a few left."
10038030-229 = "A moon cake... I've missed those. Thank you, I really appreciate it."
10038030-230 = "How about you, Sensei? The moon cakes from the Black Tortoise Promenade are a local specialty."
10038030-231 = "[s] \"In that case, I can't refuse...\""
10038030-232 = ""
10038030-234 = ""
10038030-236 = ""
10038030-239 = "As I took a bite of the moon cake, a rich and savory flavor filled my mouth."
10038030-241 = "For some time, all was quiet as we shared the snacks..."
10038030-244 = "...This reminds me of days gone by. Remember when we shared the very first moon cakes we made together?"
10038030-245 = "Ugh, you still remember that...?"
10038030-246 = "We used egg yolks, walnuts, and red bean paste."
10038030-247 = "You need to learn to let go of the past..."
10038030-248 = "It was just so intense. The red bean pastes tasted slightly burnt, the egg yolk was half-cooked, and the walnuts were so broken apart there was no crunch."
10038030-249 = "Kisaki, you were the one who pressed the moon cakes into the mold."
10038030-250 = "Yes, and that's why they were crumbled mush."
10038030-251 = "They barely qualified as \"moon cakes\" at all."
10038030-252 = "Well, you can't expect to be perfect the first time. It's all part of the process."
10038030-253 = "Very true. But still..."
10038030-254 = "No matter how much time passes, I still remember those moon cakes."
10038030-255 = "...That was right around the time I set my goal to become a chef."
10038030-256 = "Would you say you've achieved that?"
10038030-257 = "I'm not sure. I guess I did, kind of. What about you, Kisaki?"
10038030-258 = "Me...? Hard to say. You remember, I never wanted to be a president."
10038030-259 = "......"
10038030-260 = "Well, you've made a good one."
10038030-261 = "And I say that as my whole street goes into the red from all your restrictions..."
10038030-262 = ""
10038030-265 = ""
10038030-266 = "...I'm so sorry. I don't even have the words."
10038030-267 = "No, no. I wasn't looking for an apology. Not a serious one. "
10038030-268 = "Truth is, we all had some operating funds saved up, and most people understand you're doing what you have to do. More importantly..."
10038030-269 = "After everything that's been going on at the Promenade, the members really don't have much right to complain."
10038030-270 = "...Still, it's not going to be easy trying to calm the kids down later."
10038030-271 = "I can only imagine."
10038030-272 = "Well, I'm sure you have it harder. Just stay determined like always, and I'm sure you'll work it out."
10038030-273 = "\"Stay determined...\""
10038030-274 = "Hmm? What's up?"
10038030-275 = "YOU were determined, when we started out."
10038030-276 = "I'm not sure I ever was."
10038030-277 = "Well..."
10038030-278 = "[s] \"Even so, you'll still work it out.\""
10038030-279 = ""
10038030-281 = ""
10038030-282 = "...What do you mean, Sensei?"
10038030-283 = "[s1] \"If you HAD been determined, you'd have a problem now...\"\n[s2] \"If you were never determined, then you haven't lost it.\""
10038030-286 = "So you're saying I can't lose something I never had."
10038030-287 = "Fufu... I suppose that does make sense. That's a whole other way to look at it."
10038030-288 = "So what's your honest opinion of how I've been handling things so far?"
10038030-289 = "[s] \"...I know you are doing your best.\""
10038030-290 = "...I see."
10038030-291 = "But sometimes, just doing one's best doesn't get the job done."
10038030-293 = "Ah, the Black Tortoise Promenade has a similar saying."
10038030-294 = "\"Cooking hard doesn't matter if the food isn't good.\""
10038030-295 = "Right, that's the same meaning. Just like how the Eastern Alchemy Society always puts in so much effort..."
10038030-296 = "Don't tease Saya too much."
10038030-297 = "I wasn't trying to single out Saya, but...there was that other problem before..."
10038030-298 = ""
10038030-300 = ""
10038030-301 = ""
10038030-302 = "Hold on... The Eastern Alchemy Society...?"
10038030-305 = "...Yes. People are talking. Not many yet, but they are..."
10038030-306 = ""
10038030-308 = "The head of the Eastern Alchemy Society is missing..."
10038030-309 = ""
10038030-312 = "Eastern Alchemy Society President Saya is cooperating with the investigation, but we haven't had any useful testimony yet."
10038030-313 = "The assumption is that Tyke Syndrome is related to the Eastern Alchemy Society. That would mean..."
10038030-314 = ""
10038030-317 = "W-Wait! This is unfair! The Eastern Alchemy Society has nothing to do with this!"
10038030-318 = "(Let me think about this from a different perspective. If I wanted to return to Shanhaijing...)"
10038030-319 = ""
10038030-322 = "It would be difficult for an expelled student to return without any formal process."
10038030-323 = "Doubly so for Shintani Kai..."
10038030-324 = ""
10038030-326 = ""
10038030-327 = "*gasp*"
10038030-328 = "What is it? What's wrong, Kisaki?"
10038030-329 = "That's what I was missing. The Eastern Alchemy Society is in great danger!"
10038030-330 = "The Eastern Alchemy Society? Why there?"
10038030-331 = ""
10038030-333 = ""
10038030-337 = ""
10038030-338 = "Madam President? What is it?"
10038030-339 = "Mina, we need recon at the Eastern Alchemy Society right now."
10038030-340 = "*gasp* I was just about to tell you: The Eastern Alchemy Society just sent us an urgent message!"
10038030-341 = ""
10038030-343 = ""
