[translation]
10030080-1 = "Epilogue;Short-Lived Resolution"
10030080-4 = "One week after New Year's Day..."
10030080-6 = "Veritas Hackers' Lounge"
10030080-9 = "Urgh... Gah..."
10030080-10 = ""
10030080-12 = ""
10030080-14 = "Hang in there, Hare! You almost have it!"
10030080-15 = "Just a bit more... You're about to set a new club record!"
10030080-16 = ""
10030080-19 = ""
10030080-20 = ""
10030080-21 = ""
10030080-23 = ""
10030080-25 = "Ugh... I-I did it!"
10030080-26 = "Amazing! It was your first try, but you added a whole ten kilograms from the previous record!"
10030080-27 = "I thought that I had improved a fair amount, but I still have a long way to go to keep up with you, Hare."
10030080-28 = "It's embarrassing when you put it like that..."
10030080-29 = "Still, I suppose I've been training rigorously lately."
10030080-30 = "If it's an exercise that requires strength, I think I can manage it without too much difficulty."
10030080-32 = "Good. Then are we ready to start training stamina?"
10030080-33 = ""
10030080-37 = ""
10030080-38 = "...Hello."
10030080-39 = ""
10030080-41 = ""
10030080-42 = "Ah! Welcome!"
10030080-44 = "It's been a while, Vice President."
10030080-45 = "I don't think we've seen you in the club room since the new year sunrise. Have you been busy?"
10030080-47 = "Yes. Quite a few firms have been booking security consultations with the start of the new year..."
10030080-48 = "My voice is a little hoarse from introducing myself and saying happy new year so often...and it's not like I've been yelling or anything."
10030080-49 = "Hey, you're not pushing yourself too hard, right?"
10030080-50 = "There will always be more work, but once you lose your health you can't get it back."
10030080-51 = "...Why not take it easy next week?"
10030080-52 = "Right. Rest is important..."
10030080-53 = "I'll try to take a break once things slow down...but for now I'll just thank you for your concern."
10030080-54 = "So, what have you been up this past week?"
10030080-55 = "I heard your voices as I approached the club room. Were you putting together some kind of workout routine?"
10030080-56 = "After a whole year spent inside the club room, it's nice to see you creating an exercise itinerary. It makes me feel like the camping trip paid off."
10030080-57 = ""
10030080-60 = ""
10030080-61 = "Oh. Well, actually..."
10030080-62 = "It's a workout plan, but..."
10030080-63 = ""
10030080-66 = ""
10030080-69 = "I was playing a training campaign in Fitness Simulator!"
10030080-70 = ""
10030080-72 = ""
10030080-74 = ""
10030080-75 = "...What?"
10030080-76 = "Oh, you might not know about Fitness Simulator, it was just released."
10030080-77 = "Fitness Simulator is a game where you play as an aspiring athlete training their various physical abilities. It has a heartwarming story of fighting to overcome your problems, so it's a huge hit right now!"
10030080-78 = "However, there's a cap on the number of stats that can be developed on the first playthrough..."
10030080-79 = "So it takes a lot of time and repeated campaigns to max out the main character's stats."
10030080-80 = "Then... The strength and stamina exercises you were talking about weren't related to real-world exercises..."
10030080-81 = "...But to a video game character?"
10030080-82 = "Yup! That's right!"
10030080-83 = "Just out of curiosity..."
10030080-84 = "When was the last time you went outside the club room?"
10030080-86 = "Yesterday... No, the day before?"
10030080-87 = "It's been a lot longer than that. We've been here since we got back from camping."
10030080-88 = "It takes at least three days to play through all of Fitness Simulator's training modes, so it couldn't be helped."
10030080-90 = "...And your plans for next week?"
10030080-91 = ""
10030080-92 = "Ah, BOOM Eternal comes out next week. It's a reboot of the classic action game series BOOM."
10030080-93 = ""
10030080-94 = "As members of Veritas, we're on a quest for truth! We can't afford to miss out on reviewing the hottest new games in Kivotos!"
10030080-95 = "By the way, I heard that Frenzy MAX is giving out limited promo cans by raffle if you post and verify your BOOM Eternal gameplay on social media..."
10030080-96 = "This could be our chance to set a new speedrunning record before most students have a chance to finish the game."
10030080-97 = "How about it, Chihiro? The game comes out at midnight, so we'll play straight through to dawn."
10030080-98 = ""
10030080-100 = ""
10030080-102 = ""
10030080-104 = ""
10030080-106 = "Thank you, everyone... I appreciate your honesty."
10030080-107 = ""
10030080-109 = ""
10030080-111 = "I see that I need to give you another strong lesson on healthy living!"
10030080-112 = ""
10030080-115 = ""
10030080-117 = "Uwahhh! Please, just this once, have mercy!"
10030080-125 = "Cyber New Year March"
