[translation]
1003420-1 = "ความจริงใจของกุลสตรีที่เพียบพร้อม"
1003420-2 = ""
1003420-3 = "เชิญค่ะคุณครู!"
1003420-4 = "วันนี้ฉันอยากโชว์ผลการฝึกทำอาหารให้คุณครูดู... ก็เลยเชิญคุณครูมาที่นี่น่ะค่ะ"
1003420-5 = "ถ้างั้นเราไปที่ห้องคหกรรมกันเลยมั้ยคะ?"
1003420-6 = "ห้องคหกรรม ชมรมฝึกฝน"
1003420-7 = "ที่นี่เป็นห้องคหกรรมของชมรมฝึกฝนเราค่ะ "
1003420-8 = "ถึงจะเป็นห้องคหกรรมแต่เราก็ใช้ห้องนี้สำหรับฝึกฝนทำอาหาร และฝึกความแข็งแกร่งของจิตใจ... และใช้ประโยชน์ในอีกหลายๆ ด้านเลย...ละค่ะ...?"
1003420-10 = ""
1003420-11 = ""
1003420-12 = ""
1003420-14 = ""
1003420-16 = ""
1003420-17 = ""
1003420-19 = ""
1003420-21 = ""
1003420-23 = "ทำไมห้องคหกรรมถึงเละเทะแบบนี้กันล่ะคะ?!"
1003420-24 = "อ๊ะ มิโมริจัง คือว่า... เมื่อคืนพวกแก๊งปีศาจบุกเข้ามาก่อเรื่องวุ่นวายที่ห้องคหกรรมน่ะ"
1003420-25 = "กว่าจะเก็บกวาดให้เรียบร้อยก็คงจะใช้เวลานานพอสมควรเลย วันนี้คงจะใช้ห้องคหกรรมไม่ได้แล้วละ..."
1003420-26 = "..."
1003420-27 = "คงทำแบบนั้นไม่ได้หรอกค่ะ"
1003420-29 = ""
1003420-30 = ""
1003420-31 = ""
1003420-33 = ""
1003420-35 = ""
1003420-36 = ""
1003420-38 = ""
1003420-40 = ""
1003420-42 = ""
1003420-44 = "มิโมริจัง?!"
1003420-45 = "งานพวกนี้น่ะ... ถ้าใช้แรงฮึดสักหน่อยก็ทำความสะอาดได้หมดแล้วค่ะ!"
1003420-46 = "[s] \"ถ้างั้นเดี๋ยวครูช่วยอีกแรงแล้วกัน\""
1003420-47 = "คะ?! คุณครูจะช่วยทำความสะอาดงั้นเหรอคะ?!?!"
1003420-48 = "มะ...ไม่ต้องหรอกค่ะคุณครู! เดี๋ยวฉันทำเองค่ะ ปล่อยให้เป็นหน้าที่พวกฉันเถอะค่ะ! ยังไงที่นี่ก็เป็นห้อง#nคหกรรมของชมรมฝึกฝนของพวกเราค่ะ!"
1003420-49 = "หากเป็นกุลสตรีที่เพียบพร้อมแล้วละก็... พอจะคาดเดาไว้ล่วงหน้าได้แล้วละค่ะว่าพวกแก๊งปีศาจจะเข้า#nมาก่อความวุ่นวายที่นี่"
1003420-50 = "ควรจะรู้ว่าพวกนั้นจะบุกเข้ามาแล้วทำลายสถานที่เละเทะแบบนี้...!"
1003420-51 = "[s] \"ครูว่าไม่น่าใช่แบบนั้นนะ?!\""
1003420-52 = "แต่... แต่ว่า..."
1003420-53 = "เพราะฉันไม่เตรียมการอะไรไว้ ห้องคหกรรมก็เลยตกอยู่ในสภาพนี้ค่ะ..."
1003420-54 = "แล้วถ้าฉันยังต้องให้คุณครูเข้ามาช่วยอีก ฉันก็คง..."
1003420-55 = "[s1] \"เรื่องนั้นไม่เป็นไรหรอก\"\n[s2] \"บางครั้งให้คนอื่นช่วยบ้างก็เป็นเรื่องดีนะ\""
1003420-58 = "..."
1003420-59 = "ถ้าคุณครูว่าอย่างนั้นละก็... เข้าใจแล้วค่ะ"
1003420-60 = "ขอรบกวนด้วยนะคะ คุณครู"
1003420-61 = "ถะ...ถ้างั้น อย่างน้อยก็เพื่อคุณครูที่สละเวลามาที่นี่...!"
1003420-62 = "ในฐานะรองหัวหน้าชมรมฝึกฝน มิซุฮะ มิโมริ ผู้นี้..."
1003420-63 = "จะดึงเอาพลังทั้งหมดที่มีออกมา แล้วตั้งใจทำความสะอาดอย่างเต็มที่ค่ะ!"
1003420-64 = "[s] \"ตอนปกติก็ทำเกินร้อยอยู่แล้วนี่นา!?\""
1003420-65 = "ไม่ได้หรอกค่ะ! เพื่อที่จะเป็นกุลสตรีที่เพียบพร้อมที่สมบูรณ์แบบ ฉันจะต้องตั้งใจให้มากกว่านี้ค่ะ!"
1003420-66 = "เพราะงั้นฉันคงไม่มีทางเลือกอื่นนอกจากจะเอา 'สิ่งนั้น' ออกมาค่ะ!"
1003420-67 = ""
1003420-69 = ""
1003420-73 = "[ns] \"นั่นมัน หรือว่าจะเป็นสิ่งนั้น?!\""
1003420-74 = "ถ้าอย่างนั้นก็เริ่มกันเลยนะคะ!"
1003420-77 = "(มิโมริในโหมดจริงจัง(?) ดูสุดยอดมากๆ แล้วก็... ดูน่ากลัวนิดหน่อยไปพร้อมๆ กัน...)"
1003420-79 = ""
1003420-83 = ""
1003420-84 = "ฮู่ว... ขอบคุณที่ช่วยนะคะ คุณครู"
1003420-85 = "คะ? ฉันต่างหากที่เป็นฝ่ายทำงานอย่างหนักงั้นเหรอคะ? ฮิฮิ..."
1003420-86 = "แค่นี้สบายมากค่ะ แต่ฉันก็รู้สึกผิดอยู่ดี... ที่ให้คุณครูมาช่วยแบบนี้น่ะค่ะ"
1003420-87 = "ถ้าอย่างนั้น ก็เอาเจ้านี่เก็บ..."
1003420-88 = ""
1003420-90 = ""
1003420-92 = "คะ? ผ้ากันเปื้อน... น่ารักดีงั้นเหรอคะ?"
1003420-93 = "คุณครูเนี่ย จริงๆ เลยนะคะ... ชอบพูดล้อเล่นอยู่เรื่อยเลย"
1003420-94 = "ไม่ได้ล้อเล่นงั้นเหรอคะ...?"
1003420-95 = "..."
1003420-96 = "คะ...คุณครูคงจะเหนื่อยแล้ว ถ้างั้นเราย้ายที่นั่งกันก่อนดีกว่านะคะ!"
1003420-97 = ""
1003420-99 = "ช่วยรอตรงนี้สักครู่นะคะ ฉันจะชงชามาให้ค่ะ"
1003420-100 = ""
1003420-102 = ""
1003420-105 = ""
1003420-107 = ""
1003420-108 = ""
1003420-110 = ""
1003420-112 = "นี่ค่ะ เชิญดื่มได้เลยค่ะ คุณครู ฉันเตรียมขนมมาด้วยนะคะ"
1003420-113 = "อันที่จริง... ฉันเชิญคุณครูมาที่นี่ก็เพราะอยากโชว์ผลการฝึกฝนให้คุณครูได้เห็นค่ะ..."
1003420-114 = ""
1003420-120 = "รสชาติถูกปากหรือเปล่าคะ? น้ำชาร้อนเกินไปหรือเปล่าคะ?"
1003420-121 = "[s] \"ขนมอร่อยมากเลย ชาก็กลิ่นหอมมากเลยด้วย\""
1003420-122 = "ฮิฮิ ค่อยยังชั่วหน่อยค่ะ..."
1003420-123 = "คะ? ผ้ากันเปื้อนนั่น... คืออะไรงั้นเหรอคะ?"
1003420-124 = "..."
1003420-125 = "เรื่องนั้น... คือว่านี่เป็นผ้ากันเปื้อนชิ้นแรกที่ฉันซื้อมาหลังจากอ่านการ์ตูนแล้วฝันอยากเป็นกุลสตรีที่#nเพียบพร้อมน่ะค่ะ "
1003420-126 = "มันเป็นของเก่า... ที่ฉันใช้และดูแลรักษาอย่างดีมาโดยตลอดน่ะค่ะ"
1003420-127 = "[s] \"ถึงจะพูดแบบนั้น แต่มันดูใหม่มากเลยนะ?\""
1003420-128 = "ฮิฮิ งั้นเหรอคะ? อันที่จริง ฉันปะชุนรอยขาดเล็กๆ มาหลายครั้งแล้ว แถมด้ายตรงปลายก็ขาดหลุดรุ่ย#nแล้วด้วยค่ะ"
1003420-129 = "แต่สำหรับฉันแล้ว... มันเป็นผ้าพันกันเปื้อนที่ไม่มีอะไรมาทดแทนได้เลยค่ะ "
1003420-130 = "ทั้งสวมใส่สบาย แล้วก็ยังทำให้รู้สึกสบายใจด้วย..."
1003420-131 = "ใส่ได้ทั้งตอนทำความสะอาด ทำอาหาร ซักผ้า เย็บผ้า อ่านใจคน... ใช้งานได้หลากหลายอย่างเลยค่ะ"
1003420-132 = "[s] \"อ่านใจ...?\""
1003420-133 = "อ๊ะ ระ...เรื่องนั้น...!"
1003420-134 = "ไม่ใช่นะคะ ฉันพูดผิดไปเองค่ะ!"
1003420-136 = "(คุณครูพยายามถามเรื่องการอ่านใจที่มิโมริบอก แต่มิโมริก็เฉไฉเปลี่ยนเรื่องคุยไปทุกครั้ง...)"
1003420-137 = ""
1003420-138 = "ฉันซื้อมาตอนเด็กกว่านี้มากเลยค่ะ ตอนแรกที่ซื้อมามันดูใหญ่มากจนตอนใช้ต้องพับหลายทบเลยค่ะ"
1003420-139 = "ตอนนั้น... ฉันคิดว่าเมื่อไรที่โตพอที่จะใส่ผ้ากันเปื้อนอันนี้ได้พอดีแล้ว ฉันก็คงได้กลายเป็นกุลสตรีที่#nเพียบพร้อมในแบบที่ตัวเองต้องการค่ะ"
1003420-140 = "ฮิฮิ... พูดแล้วก็คิดถึงตอนนั้นจัง แล้วก็รู้สึกอายด้วยค่ะ"
1003420-141 = "[s] \"ไม่เห็นต้องอายเลยนี่นา?\""
1003420-142 = "งั้นเหรอคะ..."
1003420-143 = "ตัวฉันในตอนนั้นคิดว่าฉันจะทำทุกอย่างได้ตามที่ต้องการแน่ๆ ค่ะ"
1003420-144 = "แต่พอโตพอที่จะใส่ผ้ากันเปื้อนได้พอดีแล้ว..."
1003420-145 = "ฉันก็ไม่แน่ใจแล้วว่าตัวเอง... ได้กลายเป็นคนที่ตัวเองอยากจะเป็นจริงๆ หรือยังน่ะค่ะ"
1003420-147 = "(คุณครูคิดจะคุยกับมิโมริเพื่อบอกให้เธอรู้ว่าตอนนี้เธอก็พยายามได้ดีมากพอแล้ว)"
1003420-148 = "อ๊ะ คุณครู... เมื่อกี้กำลังคิดว่าจะบอกฉันว่าตอนนี้ฉันพยายามได้ดีมากพอแล้วใช่มั้ยคะ?"
1003420-149 = "[s] \"ไหงเป็นงี้อะ? รู้ก่อนเฉยเลย?!\""
1003420-150 = "ฮิฮิ... คำพูดแบบนี้สมกับเป็นคุณครูดีนะคะ เท่านี้ฉันก็สบายใจแล้วค่ะ ขอบคุณนะคะ "
1003420-151 = "[s3] \"เป็นเพราะผ้ากันเปื้อนรึเปล่าน่ะ!\"\n[s4] \"ใส่ผ้ากันเปื้อนแล้ว ความสามารถในการอ่านใจจะเพิ่มขึ้นจริงเหรอ?\""
1003420-154 = "คะ...คะ?! ฉันไม่เคยพูดอะไรแบบนั้นเลยนะคะ...?"
1003420-155 = ""
1003420-158 = "ยะ...อย่าทำสีหน้าเหมือนจะบอกว่า 'ครูเข้าใจทุกอย่างแล้ว' แบบนี้สิคะ...!"
1003420-159 = "คุณครูคะ? คุณครู?!"
1003420-161 = "(หลังจากนั้น ถึงมิโมริจะแสดงท่าทางเขินอายออกมา แต่เธอก็พยายามบ่ายเบี่ยงไม่ตอบคำถามคุณครู#nตลอด...)"
