[translation]
10036100-1 = "#title;제10화;Yo DJ Pump This Party"
10036100-2 = "1;미사키 수영복;01;무대는 멀쩡한 예비 부품으로 교체 완료.\n#1;a\n#1;greeting"
10036100-3 = "3;아츠코 수영복;01;DJ 기자재는 다행히 총을 안 맞은 것 같아. 신기할 정도인걸.\n#3;a"
10036100-4 = "5;히요리 수영복;03;개, 객석도 준비 완료에요……!\n#5;a\n#5;jump"
10036100-5 = "#st;[0,0];instant;1;"
10036100-7 = "1;미사키 수영복;01\n3;아츠코 수영복;01\n5;히요리 수영복;03\n#1;h\n#3;h\n#5;h\n#1;d\n#3;d\n#5;d\n#wait;1000"
10036100-8 = "3;사오리 수영복;04;이렇게 직접 도와줄 필요는 없다만…….\n#3;a"
10036100-9 = "3;아츠코 수영복;03;함께 즐기는 축제니까. 그리고 일손은 많을수록 좋잖아?"
10036100-10 = "#st;[0,0];instant;1;"
10036100-12 = "3;아츠코 수영복;03\n#3;d\n#wait;1000"
10036100-13 = "2;헬멧단 단원 A;00;다른 쪽도 준비 완료!\n#2;a\n#2;jump"
10036100-14 = "2;헬멧단 단원 A;00;불청객 녀석들을 놓쳐버린 건…… 조금 속이 쓰리지만."
10036100-15 = "2;헬멧단 단원 A;00;일단 방해꾼도 싹 물러갔고, 이제 본격적으로 축제의 밤을 즐겨 보자고!"
10036100-16 = "4;헬멧단 단원 B;00;어…… 그게 말야.\n#4;a\n#4;em;…"
10036100-17 = "4;헬멧단 단원 B;00;DJ 공연은 다른 행사로 대체해야 할 것 같아."
10036100-18 = "#st;[0,0];instant;1;"
10036100-21 = "1;미사키 수영복;04\n5;히요리 수영복;17\n2;사오리 수영복;02\n4;아츠코 수영복;02\n#1;h\n#2;h\n#4;h\n#5;h\n#1;em;…\n#2;em;…\n#4;em;…\n#5;em;…\n#wait;2500"
10036100-22 = "1;미사키 수영복;04\n5;히요리 수영복;17\n2;사오리 수영복;02\n4;아츠코 수영복;02\n#na;사오리&아츠코&미사키&히요리;어째서……?\n#1;h\n#2;h\n#4;h\n#5;h\n#1;em;[?]\n#2;em;[?]\n#4;em;[?]\n#5;em;[?]"
10036100-24 = "3;헬멧단 단원 B;00;그게…… DJ B.o.B, 아까 한참 총격전이 벌어질 때 도망가더라고.\n#3;em;[땀]"
10036100-25 = "3;헬멧단 단원 B;00;'납치당하는 건 싫어어~' 라면서."
10036100-26 = "3;헬멧단 단원 B;00;나도 경황이 없어서 붙잡질 못했어."
10036100-27 = "3;아츠코 수영복;26;하지만 DJ 공연은 모두가 기다리던 메인 이벤트잖아!\n#3;jump"
10036100-28 = "3;히요리 수영복;11;……역시 망했어요!\n#3;em;[훌쩍]"
10036100-29 = "3;히요리 수영복;10;우리한테 여름밤의 추억 같은 건 과도한 사치였던 거예요!"
10036100-30 = "3;히요리 수영복;04;결국 우린 DJ 음악 대신 음침한 파도 소리나 들으면서 모랫바닥에서 잠을 청해야겠네요……."
10036100-31 = "3;히요리 수영복;04;그러다가 밀물에 휩쓸려서 아무도 모르는 무인도까지 떠내려가 버릴 거예요……!\n#3;em;[세로선]\n#3;stiff"
10036100-32 = "3;히요리 수영복;11;패션 잡지 저번 호에서 '무인도에 갈 때 가져갈 아이템' 특집을 읽어 둘 걸 그랬어요!\n#3;hophop"
10036100-33 = "[s] \"자, 자, 진정해.\""
10036100-34 = "#st;[0,0];instant;1;"
10036100-36 = "3;히요리 수영복;11\n#3;d\n#wait;1000"
10036100-37 = "2;헬멧단 단원 A;00\n4;헬멧단 단원 B;00\n#2;h\n#4;h\n#2;a\n#4;a\n#wait;1000"
10036100-38 = "2;헬멧단 단원 A;00;당신은…… 샬레의 선생?\n#2;em;[?]"
10036100-39 = "2;헬멧단 단원 A;00;뭔가 해결 방법이 있는 거야?"
10036100-40 = "[s] \"내 생각엔, DJ 공연을 멈출 필요는 없을 것 같아.\""
10036100-41 = "4;헬멧단 단원 B;00;물론 공연용 턴테이블이나 스피커, 음원 같은 건 그대로 두고 간 거라 아깝긴 하지.\n#4;em;…"
10036100-42 = "4;헬멧단 단원 B;00;하지만 정작 그걸 이용해서 공연할 DJ가 없잖아?"
10036100-43 = "[s] \"후후, 걱정 마시죠!\""
10036100-44 = "#st;[0,0];instant;1;"
10036100-46 = "2;헬멧단 단원 A;00\n4;헬멧단 단원 B;00\n5;사오리 수영복;01\n#2;h\n#4;h\n#5;h\n#2;m1\n#4;m3\n#5;al\n#wait;1000"
10036100-47 = "5;사오리 수영복;06;서, 선생? 왜 나를 앞으로 내세우는 건가?\n#5;stiff\n#5;em;[?]"
10036100-48 = "[s] \"여기, DJ B.o.B의 수제자가 있으니까!\""
10036100-49 = "5;사오리 수영복;04;선생, 그게 무슨?!\n#5;em;[?!]\n#5;shake"
10036100-50 = "5;사오리 수영복;10;서, 설마 나보고 공연을 하라는 건가……?!"
10036100-51 = "#st;[0,0];instant;1;"
10036100-53 = "2;헬멧단 단원 A;00\n4;헬멧단 단원 B;00\n5;사오리 수영복;10\n#2;h\n#4;h\n#5;h\n#2;d\n#4;d\n#5;d\n#wait;1000"
10036100-54 = "1;미사키 수영복;01\n3;아츠코 수영복;01\n5;히요리 수영복;01\n#1;h\n#3;h\n#5;h\n#1;a\n#3;a\n#5;a\n#wait;1000"
10036100-55 = "[ns1] 세 사람에게 살짝 눈짓을 한다.\n[ns2] (찡긋)"
10036100-58 = "1;미사키 수영복;02\n3;아츠코 수영복;21\n5;히요리 수영복;17\n#na;아츠코&미사키&히요리;……!\n#1;h\n#3;h\n#5;h\n#1;em;[!]\n#3;em;[!]\n#5;em;[!]"
10036100-59 = "3;아츠코 수영복;15;응, 그러네~ 삿 쨩이 디제잉 하는 모습, 보고 싶은걸.\n#3;em;[음표]"
10036100-60 = "5;히요리 수영복;12;마, 맞아요! 공연만 기다리고 있었는데, 취소되면 슬프잖아요……헤헤.\n#5;jump"
10036100-61 = "1;미사키 수영복;04;……나까지 해야 돼?\n#fontsize;50\n#1;em;…"
10036100-62 = "[s] \"응?! 뭐라고? 미사키, DJ 공연만 기다리고 있었다고?\""
10036100-63 = "1;미사키 수영복;07\n3;아츠코 수영복;15\n5;히요리 수영복;12\n#na;미사키 수영복;그런 말 안 했어!\n#3;dr\n#5;dr\n#1;hophop\n#1;m3"
10036100-64 = "1;미사키 수영복;08;그, 그러니까…… 축제의 메인 이벤트를 취소하면 안 되는 거잖아.\n#1;em;[///]\n#1;stiff"
10036100-66 = "3;사오리 수영복;04;하지만, 난 DJ가 아니다."
10036100-67 = "3;사오리 수영복;06;내게 모두를 즐겁게 해 줄 능력 같은 건……."
10036100-68 = "[s] \"능력은 중요하지 않아. 중요한 건 하고 싶은지 아닌지야.\""
10036100-69 = "3;사오리 수영복;02;……."
10036100-70 = "3;사오리 수영복;05;선생은, 그렇게 말하는 건가."
10036100-71 = "3;사오리 수영복;13;내가 하고 싶은 일…… 그건…… 역시……."
10036100-72 = "#st;[0,0];instant;1;"
10036100-74 = "3;사오리 수영복;13\n#3;em;…\n#wait;2500"
10036100-75 = "3;사오리 수영복;05;역시 잘 모르겠다."
10036100-76 = "[s] \"분명 깨닫는 흐름이었는데?!\""
10036100-77 = "3;사오리 수영복;03;하지만 한 가지는 알 것 같아."
10036100-78 = "3;사오리 수영복;99;지금, 내가 하고 싶은 일은……."
10036100-79 = "3;사오리 수영복;13;아까 무대에서 느꼈던 그 이름 모를 감정을, 한 번만 더 느껴보는 것…… 그뿐이다."
10036100-80 = "3;사오리 수영복;03;해보겠어, 선생.\n#3;em;[반응]"
10036100-81 = "3;사오리 수영복;14;아니, 해보고 싶다."
10036100-82 = "1;미사키 수영복;02\n3;아츠코 수영복;18\n5;히요리 수영복;13\n#1;h\n#3;h\n#5;h\n#1;a\n#3;a\n#5;a"
10036100-83 = "1;미사키 수영복;09;선생님 때문에 부추기는 데 동참하긴 했지만…… 리더가 디제잉이라니, 상상도 못 해봤는데.\n#1;em;[땀]"
10036100-84 = "5;히요리 수영복;03;사오리 언니가 음악……."
10036100-85 = "5;히요리 수영복;04;하다가 잘 안되면 턴테이블에 총알구멍을 내는 건 아닐까요……?\n#5;em;[세로선]"
10036100-86 = "3;아츠코 수영복;99;삿 쨩은 잘 해낼 수 있을 거야."
10036100-88 = "#na;아츠코 수영복;어느 정도 답을 찾은 것 같으니까."
10036100-89 = "#st;[0,0];instant;1;"
10036100-92 = "#na;동물 사회자;자, 자, 밀지 마세요! 밀지 마세요!"
10036100-93 = "#na;동물 사회자;소란은 지나가고, 이제 다시 축제의 열기가 <무법자 해변>을 덮을 때가 되었습니다!"
10036100-94 = "#na;동물 사회자;그럼 모두 함께, 한 번 놀아볼까요!"
10036100-95 = "#na;동물 사회자;뮤직! 큐!\n#fontsize;80"
10036100-96 = "#st;[0,0];instant;1;"
