[translation]
10038090-1 = "ตอนที่ 9;สำหรับทุกความยุ่งยาก"
10038090-2 = ""
10038090-3 = ""
10038090-4 = ""
10038090-8 = ""
10038090-9 = ""
10038090-12 = ""
10038090-14 = ""
10038090-16 = "มะ... มังกรดำ?! แล้วก็ท่านประมุขด้วย!?"
10038090-17 = "พวกท่านมีธุระอะไรถึงที่นี่...?"
10038090-19 = "อืม เรามาเพราะอยากให้มีการปล่อยตัวยาคูชิ ซายะ"
10038090-21 = "มะ... หมายถึงซายะ หัวหน้าชมรมวิจัยศาสตร์การปรุงยาคนก่อนเหรอคะ?!"
10038090-22 = "แบบนั้นมัน...!"
10038090-24 = "หืม มีปัญหาอะไรอย่างนั้นหรือ?"
10038090-25 = ""
10038090-28 = ""
10038090-29 = "..."
10038090-30 = "คือว่า... พวกฉันได้รับคำสั่งจากชมรมวิจัยศาสตร์การปรุงยา... ให้คุมตัวยาคูชิ ซายะไว้ให้นานที่สุด#nเท่าที่จะทำได้ค่ะ..."
10038090-31 = "ข้อหาของเธอก็คือ... บริหารชมรมวิจัยศาสตร์การปรุงยาอย่างเหมาะสมไม่ได้ค่ะ..."
10038090-33 = "พวกเธอคิดว่าคำสั่งของชมรมวิจัยศาสตร์การปรุงยาหนักแน่นกว่าคำสั่งของประมุขอย่างนั้นหรือ?"
10038090-34 = "ฮุฮุ ถ้าไม่ทำตามคำสั่งของท่านประมุข ก็รู้ไว้ด้วยว่าพวกเธออาจถูกลงโทษได้ตามความเหมาะสม"
10038090-35 = "อืม มินะ อย่าขู่ให้มากเกินไปเลย หากคำพูดนั้นออกมาจากปากของหัวหน้าคณะกรรมการ น้ำหนักของ#nคำพูดก็อาจจะเปลี่ยนไปเล็กน้อยก็ได้"
10038090-36 = ""
10038090-38 = ""
10038090-39 = "ขะ... ขออภัยค่ะ ท่านประมุข!"
10038090-40 = ""
10038090-42 = ""
10038090-44 = ""
10038090-45 = "ได้โปรดพิจารณาด้วยค่ะ... ท่านประมุข"
10038090-47 = "บอกเรามาว่าเป็นเพราะเหตุอันใด"
10038090-49 = "เอ่อ... เกี่ยวกับเรื่องโรคระบาดที่แพร่อยู่ในซานไห่จิงตอนนี้น่ะค่ะ"
10038090-50 = "โรคที่เมื่อติดเชื้อแล้วจะเด็กลง จนเรียกกันว่าโรคเด็กลงน่ะค่ะ..."
10038090-52 = "ผู้ที่ทำให้โรคเด็กลงระบาด... ก็คือคนนั้น... ที่ท่านประมุขเองก็อาจจะคาดเดาได้ค่ะ..."
10038090-53 = ""
10038090-55 = ""
10038090-57 = "พวกฉันรู้ดีว่าคำสั่งของชมรมวิจัยศาสตร์การปรุงยาไม่อาจอยู่เหนือคำสั่งของท่านประมุขได้..."
10038090-58 = "แต่ถ้าพวกฉันไม่ทำตามคำสั่งของชมรมวิจัยศาสตร์การปรุงยา พวกฉันก็จะไม่ได้รับยารักษา และยาป้องกันโรคเด็กลงค่ะ..."
10038090-60 = "..."
10038090-61 = "เข้าใจแล้ว เช่นนั้นเราจะปล่อยตัวยาคูชิ ซายะในนามของมังกรดำ"
10038090-62 = ""
10038090-65 = ""
10038090-66 = "คะ? ถ้าอย่างนั้น...?!"
10038090-67 = "แล้วสิ่งที่จะตามมาจากเรื่องที่จะเกิดขึ้นต่อจากนี้...!"
10038090-69 = "ใช่แล้วละ มังกรดำจะเป็นผู้รับผิดชอบทั้งหมด และประมุขริวเกะ คิซากิจะเป็นคนรับผิดชอบเอง"
10038090-70 = ""
10038090-72 = ""
10038090-73 = "ตำแหน่งประมุขมีไว้เพื่อแบกรับเรื่องยุ่งยากอยู่แล้วไม่ใช่หรือ?"
10038090-74 = ""
10038090-77 = ""
