[translation]
10038080-1 = "Episode 8;To You, Who Would Waver a Thousand Times"
10038080-3 = ""
10038080-5 = ""
10038080-7 = ""
10038080-9 = ""
10038080-10 = "I, Kaguya, of the Peking Opera Club, greet you, Madam."
10038080-12 = "Yes, and how are you? Managing Genryumon well?"
10038080-13 = "...It's all rather new to me, but I expect I'll grow accustomed in time."
10038080-14 = "Not much to do with Peking opera, but then, perhaps you plan to hand off that role."
10038080-15 = "Why don't you give it to Genryumon? They clearly have time on their hands."
10038080-16 = "......"
10038080-17 = "Let me ask you this, Kaguya. What is it you desire?"
10038080-18 = "Does the Peking Opera Club intend to replace Genryumon?"
10038080-19 = "Not at all. The Peking Opera Club's purpose is there in the name. "
10038080-20 = "And because of that purpose, we're the ideal stewards of the Shanhaijing traditions."
10038080-21 = "Which traditions would those be, exactly?"
10038080-22 = "Oh, there's far more to them than any simple words could express."
10038080-23 = "Then allow me to express them in larger words. When you speak of tradition, do you speak of our ethos, our guiding principles?"
10038080-24 = "......"
10038080-25 = "To stand against tyranny, to protect the weak, to remember kindness, to endure all for what is right. Is that not the tradition we pride ourselves on most?"
10038080-26 = "Why do you ask me of what you already know...?"
10038080-27 = ""
10038080-29 = ""
10038080-31 = "Because...I want you to trust me."
10038080-32 = ""
10038080-34 = ""
10038080-35 = "What do you mean...?"
10038080-36 = "People have doubted the choices I've made. You, and all the others standing with you, among what I'm sure are many others."
10038080-37 = "But tell me, are the traditions of Shanhaijing, those you uphold, so fragile?"
10038080-38 = "*gasp*"
10038080-39 = ""
10038080-40 = "Huh!"
10038080-42 = "Were they so insignificant that a spat of intrigue from a few outsiders could bring them all crashing down?"
10038080-43 = "That's..."
10038080-44 = ""
10038080-46 = ""
10038080-47 = "Have faith."
10038080-48 = ""
10038080-51 = ""
10038080-52 = "In yourself. And if not in yourself, then in Shanhaijing, in its strength, in its history!"
10038080-53 = "The roots of Shanhaijing run deep. They're not so easily shaken! And they will continue to grow deeper!"
10038080-54 = "Madam...!"
10038080-55 = "One more question, in all sincerity. Who is the greater threat to our institution? Myself, or Shintani Kai?"
10038080-56 = "I think... I think that answer is clear."
10038080-57 = "Then would it not be right for you and the Peking Opera Club to step aside and choose another path?"
10038080-58 = "...Would you be willing to allow such a thing?"
10038080-59 = "Ah, now there is an interesting question. Hmm..."
10038080-60 = "Would you stand down out of principle or practicality?"
10038080-61 = "Both principle and practicality."
10038080-62 = "Ah, then may I ask what you mean by that?"
10038080-63 = "The shortest part of the answer is that we can help each other stop the spread of Tyke Syndrome. We think we know what's causing it. "
10038080-65 = "Ah..."
10038080-66 = "Yes, then we can all work together on medications and preventative measures."
10038080-67 = "...You are a woman of great understanding and shining grace."
10038080-68 = "You mentioned a longer part of the answer?"
10038080-69 = ""
10038080-71 = ""
10038080-73 = ""
10038080-74 = "......"
10038080-75 = "Madam, I have a request."
10038080-76 = ""
10038080-78 = ""
10038080-79 = ""
10038080-80 = "Please, punish me here and now."
10038080-81 = "[s] \"What...?!\""
10038080-83 = "...Go on."
10038080-84 = "You must. To restore your authority as president."
10038080-85 = "If you let me go unpunished, no one will obey your orders. No one will listen to you."
10038080-86 = "So show your strength and issue the decree yourself, at once!"
10038080-87 = "No. Laws exist so that strength need not be shown so crudely."
10038080-88 = "But in troubled times, laws often fail."
10038080-89 = "Left unenforced, they become mere ink on paper, and virtue turns to vulnerability!"
10038080-90 = "It is tragic that this situation exists, where strength must be shown. I know that very well."
10038080-91 = "But it does exist. And now you must not hesitate. No ruler can. You understand."
10038080-94 = "Carve a path of righteousness through this blighted field."
10038080-95 = "Do not allow evil to fester."
10038080-96 = "Think of your people. Their safety, their livelihoods."
10038080-97 = ""
10038080-101 = "A usurper has placed their way of life in jeopardy. Me."
10038080-104 = "Draw your weapon, Madam. Prove you have the power to lead. "
10038080-105 = "Let every shot become a declaration. You ARE the president. You HAVE the power. And you WILL wield it, as the people's leader and protector."
10038080-106 = ""
10038080-108 = ""
10038080-109 = "And if that righteous path has a few spent casings upon it, that will only prove how hard you fought."
10038080-110 = ""
10038080-112 = ""
10038080-113 = ""
10038080-114 = "You once sought to give me advice through a performance of yours."
10038080-115 = "What do you think of that now?"
10038080-117 = "...In retrospect, I should have chosen my methods more carefully."
10038080-118 = "But I stand by the message I sent."
10038080-119 = "It showed my loyalty, and the path I'd chosen."
10038080-120 = "If I could turn back time and return to that moment, I would offer the same advice a hundred times, face prison for a thousand years, and suffer ten thousand expulsions."
10038080-121 = ""
10038080-123 = ""
10038080-125 = ""
10038080-126 = "You raise another interesting point."
10038080-128 = "How could I punish one so loyal?"
10038080-129 = ""
10038080-131 = ""
10038080-132 = "......"
10038080-134 = "I am not the person I was when I gave you that advice. You must make that distinction."
10038080-135 = ""
10038080-137 = "I am now a usurper, and there is no changing that."
10038080-138 = "Usurpers must be punished and displayed in the streets, as an example for all to see."
10038080-141 = ""
10038080-142 = "Otherwise, your orders will not stand, and your laws, however noble, will not hold."
10038080-143 = ""
10038080-145 = ""
10038080-146 = "But you did not become a usurper by your own will."
10038080-147 = "......"
10038080-148 = "I didn't wish to say this, but on that point, I must respond."
10038080-149 = "Then I will listen."
10038080-150 = ""
10038080-153 = ""
10038080-154 = "You yourself did not become the president by your own will either."
10038080-155 = "And yet, do you not carry all the responsibilities of that position?"
10038080-156 = "That is why I have always respected you."
10038080-157 = "That is why I always considered you a blessing upon Shanhaijing."
10038080-158 = "And if I must die here for you, then I shall, and would do so again and again."
10038080-160 = "Is that the path you choose, in this moment?"
10038080-161 = "It has already been chosen."
10038080-162 = ""
10038080-164 = ""
10038080-165 = "Then I will not walk upon it."
10038080-166 = ""
10038080-168 = ""
10038080-169 = "[ns] \"Kisaki...!\""
10038080-170 = "What...do you mean?"
10038080-171 = "Let me show you."
10038080-172 = ""
10038080-174 = ""
10038080-175 = "The path that the President of Shanhaijing will walk from this day forward."
10038080-176 = ""
10038080-178 = ""
10038080-179 = "Madam...?"
