[translation]
1004103-1 = "Uncontrollable Body"
1004103-2 = "..."
1004103-3 = "[s] \"...\""
1004103-4 = "How does this keep happening? I wasn't planning on seeing you."
1004103-5 = "[s] \"You never are.\""
1004103-6 = "I can't deny that. What do you want?"
1004103-7 = "[s] \"Nothing much, but...\""
1004103-8 = "Okay. Bye."
1004103-9 = "[s] \"W-Wait!\""
1004103-10 = "You are incorrigibly persistent."
1004103-11 = "[s] \"I was hoping we could bond a little more.\""
1004103-12 = "What for?"
1004103-13 = "[s] \"Human connection is very important.\""
1004103-14 = "I disagree."
1004103-15 = "Humans are just castaways trapped in isolated islands known as our bodies"
1004103-16 = "Everyone is born alone, and everyone dies alone."
1004103-17 = "Whatever connections happen in between are just delusions."
1004103-18 = "[s] \"Has anyone ever told you you're a bit cynical?\""
1004103-19 = "..."
1004103-20 = "*sigh*"
1004103-21 = "Whatever you say."
1004103-22 = "Fine. What do you want to do?"
1004103-23 = "[s] \"Um... Oh, how about we get some fresh air?\""
1004103-24 = "..."
1004103-25 = "Consider this me following orders."
1004103-27 = "..."
1004103-28 = "[s] \"Flowers.\""
1004103-29 = "Yeah, flowers."
1004103-30 = "[s] \"The river.\""
1004103-31 = "That's a river."
1004103-32 = "[s] \"Uh... Umm.\""
1004103-33 = "..."
1004103-34 = "That's it. Nothing deeper. A river and flowers.  "
1004103-35 = "[s] \"If that's how you see it...\""
1004103-36 = "Can we leave? *sniffle* I only came under your orders."
1004103-37 = "[s] \"Why do you always wear a mask?\""
1004103-38 = "No reason. *sniffle*"
1004103-39 = "[s1] \"You don't take off your mask on walks?\"\n[s2] \"Your mask defeats the purpose of fresh air, you know.\""
1004103-40 = "I-I mean... Wait... That's... D-Don't come...closer... Ah..."
1004103-41 = "I-I mean... Wait... That's... D-Don't come...closer... Ah..."
1004103-42 = "A-A-Ah..."
1004103-43 = "Achoo!"
1004103-44 = "[s] \"...?!\""
1004103-45 = "Achoo!"
1004103-46 = "Aaachoo!"
1004103-47 = "Achoo, aaachoo!"
1004103-48 = "[s] \"...\""
1004103-49 = "Ugh... The pollen..."
1004103-50 = "[s] \"Misaki... Your...\""
1004103-51 = "Look. I-I have allergies, okay?"
1004103-52 = "[s] \"No, it's not that. Your nose is running.\""
1004103-53 = "Huh?"
1004103-54 = "Arghhhhhh?!"
1004103-55 = "I need tissues...! Help! It won't stop running?!"
1004103-56 = "[s3] \"H-Hold on! Wait! Here!\"\n[s4] \"I have a handkerchief!\""
1004103-57 = ""
1004103-58 = ""
1004103-60 = ""
1004103-61 = ""
1004103-63 = "Moments later."
1004103-65 = "*sigh*"
1004103-66 = "[s] \"...A-Are you okay, Misaki?\"  "
1004103-67 = "...Please get me out of here."
1004103-70 = "[ns] \"Here, I got you a drink.\""
1004103-71 = "Thank you, Sensei."
1004103-72 = "*sigh*"
1004103-73 = "...My body sucks."
1004103-74 = "[s] \"You do have some pretty bad allergies...\""
1004103-75 = "It didn't get too bad thanks to you."
1004103-76 = "[s] \"Really??? I'm glad I could help!\""
1004103-77 = "..."
1004103-78 = "[s] \"Maybe it's a sign we should be friends!\""
1004103-79 = "You created this situation."
1004103-80 = "Don't celebrate it."
1004103-81 = "[s] \"...I'm very sorry.\""
1004103-82 = "..."
1004103-83 = "Still, thank you..."
1004103-84 = "I'll wash the handkerchief and give it back."
1004103-85 = "[s] \"Huh? No, just give it back as is.\""
1004103-86 = "..."
1004103-87 = "[s] \"Sorry. I thought it was funny.\""
1004103-88 = "*sigh*"
