[translation]
1004305-1 = "A Fluttering Heart Near a Bonfire"
1004305-3 = "Preparations are complete."
1004305-4 = "Great job, everyone!"
1004305-5 = ""
1004305-10 = "[ns] \"Phew, finally finished...\""
1004305-11 = "There was a lot of commotion, but in the end we were able to prepare for the festival without much issue."
1004305-12 = ""
1004305-15 = "When I had some time, I replied to Wakamo on MomoTalk."
1004305-16 = "[s] \"I'm done with work. Where are you?\""
1004305-17 = ""
1004305-20 = "Wakamo didn't respond for a while, which was unusual."
1004305-21 = "[s] \"Wakamo hasn't replied yet. That's strange...\""
1004305-22 = ""
1004305-25 = "The weather is getting bad. "
1004305-26 = "It's very windy, so the waves are going to be rough."
1004305-27 = ""
1004305-30 = "Suddenly, I got nervous."
1004305-31 = ""
1004305-34 = "[ns] \"...I'll be right back.\""
1004305-35 = "Sensei? The storm is getting worse. Wait!"
1004305-48 = "I kept looking around nervously for a while."
1004305-52 = "[ns] \"*pant pant* There you are...\""
1004305-53 = ""
1004305-54 = ""
1004305-55 = "Oh, Sensei! You're here!"
1004305-58 = "[ns] \"...Wakamo, what are you doing here?\""
1004305-59 = "Really?"
1004305-60 = "I was waiting for you, of course!"
1004305-61 = "[s] \"You were waiting for me? In this weather? Why?\""
1004305-62 = "Heeheehee. What kind of a question is that? You're silly."
1004305-63 = "The answer is obvious..."
1004305-64 = "You and I made a promise."
1004305-65 = "\"...I'm busy right now. Can you wait a little?\""
1004305-66 = "That's what you said, so I obeyed your words."
1004305-67 = "It doesn't matter if it rains or snows. I'll wait for you anywhere."
1004305-68 = "That's what a promise means."
1004305-69 = "[s] \"A promise... You also said that in the fireworks storage.\""
1004305-72 = "Heeheehee! I promised you I'd make today a special day."
1004305-73 = "These obstacles have been interrupting us..."
1004305-74 = "Yes! I'm going to blow up all the fireworks! "
1004305-77 = "[ns] \"So you tried to keep your promise.\""
1004305-78 = "Yes, that's right."
1004305-79 = "Um... Did I do something wrong?"
1004305-80 = "Did I make another mistake?"
1004305-81 = "[s1] \"No, it was wrong of me to make you wait at a place like this.\"\n[s2] \"No, I did. I should have explained things better.\""
1004305-82 = "Huh?"
1004305-83 = "Huh?"
1004305-84 = "No, I'm used to waiting. This is nothing..."
1004305-85 = ""
1004305-87 = ""
1004305-88 = ""
1004305-90 = ""
1004305-92 = "*gasp* S-Sensei?!"
1004305-93 = ""
1004305-95 = "[ns3] \"...You're not okay at all.\"\n[ns4] \"You're freezing, Wakamo!\""
1004305-96 = "Sensei..."
1004305-97 = "Sensei..."
1004305-98 = "You...are..."
1004305-99 = "...so warm."
1004305-100 = "[s] \"Wakamo. Just one second!\""
1004305-101 = "Oh, h-huh?"
1004305-108 = "Is this...a bonfire...?"
1004305-109 = "[s5] \"Before we go back, why don't you get warm here a little?\"\n[s6] \"I'll stay with you by the fire.\""
1004305-110 = ""
1004305-111 = ""
1004305-113 = ""
1004305-114 = "...!"
1004305-115 = "O-Okay..."
1004305-116 = ""
1004305-118 = ""
1004305-119 = ""
1004305-121 = "Th-Then...I'll sit there."
1004305-124 = "― Heehee. How warm...[wa:2190] "
1004305-127 = "― Well, perhaps it's the bonfire keeping me warm, but...[wa:750] "
1004305-130 = "― Your voice and every word you speak...[wa:2690] "
1004305-133 = "― When I think about[wa:740] "
1004305-135 = "― how they're mine and only mine, in this moment..."
1004305-138 = "― I still feel like...[wa:370] "
1004305-140 = "― I'm not good enough for you.[wa:440] "
1004305-143 = "― By being by your side, I've caused you countless troubles.[wa:2180] "
1004305-145 = "― And I'll make many, many more mistakes.[wa:1740] "
1004305-148 = "― Despite that, you're really sure...[wa:3170] "
1004305-150 = "― I can stay close to you...?[wa:2220] "
1004305-153 = "[ns] \"Yes, of course.\""
1004305-154 = "― Thank you...[wa:240] "
1004305-156 = "― This is why I...[wa:2560] "
1004305-160 = "We gazed at the sea in front of the bonfire while Wakamo was warming herself."
