[translation]
1004502-1 = "สมบัติของเกาะที่ซ่อนอยู่"
1004502-2 = "(หลังจากอ่านแชตของโฮชิโนะ คุณครูก็ไปที่โถงห้องพัก)"
1004502-7 = "(...)"
1004502-8 = "แหะๆ... ใช่แล้ว อันนี้ละ ของแบบนี้ละที่ฉันหาอยู่..."
1004502-9 = ""
1004502-12 = "(...?)"
1004502-13 = "อืม... เยี่ยมเลยๆ กำลังมองหาของดีๆ แบบนี้อยู่เลย..."
1004502-14 = "[s1] \"โฮชิโนะ...?\"\n[s2] เดินไปตามทางที่ได้ยินเสียง"
1004502-15 = ""
1004502-16 = ""
1004502-19 = ""
1004502-21 = "...? หืม?"
1004502-22 = "เอ๋ นั่นใครน่ะ ครูเองเหรอ?"
1004502-23 = "บอกให้ทำเป็นไม่รู้ไม่เห็นไง แล้วมาที่นี่ทำไม? ครูเนี่ย จริงๆ เลยน้า~"
1004502-24 = "[s3] \"มาทำอะไรอยู่ที่นี่เหรอ?\"\n[s4] \"เมื่อกี้พูดอะไรอยู่คนเดียวน่ะ...\""
1004502-25 = "หืม...?"
1004502-26 = "หืม...?"
1004502-27 = "อ๋อ หมายถึงนี่น่ะเหรอ ก็ไม่มีอะไรหรอก..."
1004502-28 = ""
1004502-30 = ""
1004502-31 = "นี่ไง..."
1004502-32 = ""
1004502-35 = "[ns5] \"แผนที่แนะนำรีสอร์ต?\"\n[ns6] \"แบบนี้ในฮอลล์ก็น่าจะมีเยอะไม่ใช่เหรอ?\""
1004502-36 = "ฮี่ๆ ไม่รู้อะไรเลยสินะครู"
1004502-37 = "ฮี่ๆ ไม่รู้อะไรเลยสินะครู"
1004502-38 = "ลองมาดูใกล้ๆ ก่อนสิ"
1004502-39 = "เห็นร่องรอยการใช้งานใช่ไหม? นี่เป็นโบรชัวร์ที่คนที่เคยมาพักที่นี่ขีดเขียนสัญลักษณ์เอาไว้น่ะ"
1004502-40 = "ของแบบนี้มีคุณค่ามากกว่าของชิ้นใหม่ว่าไหมล่ะ? เพราะมันเป็นสิ่งที่ผ่านประสบการณ์การใช้งาน#nจากคนอื่นมาแล้วน่ะ"
1004502-41 = "ฉันเลยมาตามหามันในห้องพักไงล่ะ เผื่อจะมีใครที่ทำสัญลักษณ์แนะนำสถานที่ดีๆ เอาไว้ๆ บ้าง"
1004502-42 = "พูดอีกอย่างคือนี่คือแผนที่ขุมทรัพย์ชนิดหนึ่งเลย ฮิฮิฮิ"
1004502-43 = "ครูคิดว่าฉันมัวแต่ไปนอนอีกแล้วล่ะสิ"
1004502-44 = "หืม? ฉันถูกใจสถานที่ไหนมากที่สุดงั้นเหรอ?"
1004502-45 = "ถามได้ดีมาก ฉันกำลังคิดว่าดูห้องนี้เสร็จก็จะไปที่นั่นพอดีเลย..."
1004502-46 = "งั้นไหนๆ แล้ว..."
1004502-47 = ""
1004502-49 = ""
1004502-51 = ""
1004502-53 = "ครูก็ไปด้วยกันเลยไหม?"
1004502-54 = "ไปหา \"สมบัติ\" ที่อยู่บนแผนที่นี้กันไงล่ะ"
1004502-60 = ""
1004502-61 = "อืม... เกือบถึงแล้ว น่าจะอยู่แถวๆ นี้นะ..."
1004502-62 = "ฮ่า... วิวสุดยอดเลยน้า สมกับเป็นสถานที่ที่ทุกคนต่างแวะมาชมวิวกัน"
1004502-63 = ""
1004502-65 = ""
1004502-66 = "และทางด้านนั้นก็คือ..."
1004502-67 = ""
1004502-69 = ""
1004502-70 = "โอ้โฮ..."
1004502-71 = "[s] \"โฮชิโนะ?\""
1004502-72 = ""
1004502-74 = ""
1004502-76 = "...!!!"
1004502-77 = ""
1004502-80 = ""
1004502-81 = "[ns] \"โฮชิโนะ!?\""
1004502-88 = "― ว้าว... ดีจัง สุดยอดไปเลย[wa:1500] "
1004502-90 = "― เหมือนกับเป็น... สรวงสวรรค์เลยละ[wa:60] "
1004502-93 = "― ร่มเงาไม้เย็นสบาย...ลมทะเลที่พัดเอื่อยๆ[wa:2710] "
1004502-95 = "― เสียงคลื่นเบาๆ...[wa:690] "
1004502-98 = "― อา~ คุ้มกับที่มาจริงๆ น้า~[wa:750] "
1004502-100 = "― สุดยอดเลย ที่นี่... เหมือนกับสถานที่ในฝันเลย[wa:1400] "
1004502-103 = "― ครูเองก็... อย่ามัวแต่ยืนแบบนั้นสิ[wa:2160] "
1004502-105 = "― ลองมาเอนหลังนอนดูหน่อยมั้ย?"
1004502-108 = "― ถึงจะไม่กว้างมากก็เถอะ แต่มาลองนอนดูมั้ย?[wa:470] "
1004502-110 = "― มันสบายมากเลยนะ~"
1004502-113 = "[ns7] \"แค่เห็นสีหน้าโฮชิโนะตอนนี้ ครูก็พอใจแล้วละ\"\n[ns8] \"ไม่ต้องห่วงครูหรอก โฮชิโนะนอนเถอะ\""
1004502-114 = "― แฮ่~ เอาอย่างนั้นเหรอ...[wa:530] "
1004502-115 = "― แฮ่~ เอาอย่างนั้นเหรอ...[wa:530] "
1004502-117 = "― ก็นะ ฉันคิดแล้วละว่าครูจะพูดแบบนั้น[wa:880] "
1004502-120 = "― แต่ก็ไม่เป็นไรหรอก[wa:250] "
1004502-123 = "― ก็... เพราะแบบนั้นละมั้ง... ฉันเลยชอบครูน่ะ[wa:1090] "
1004502-125 = "― ฮิฮิฮิ...[wa:10] "
1004502-128 = "[ns9] \"สุดท้ายก็มาหาที่นอนสินะ\"\n[ns10] \"กะแล้วเชียวว่าต้องมาหาที่นอน\""
1004502-129 = "อย่าพูดอะไรน่าเศร้าแบบนั้นสิ... ตอนที่ฉันไม่อยู่ครูก็คิดจะมาแอบงีบที่นี่เหมือนกันไม่ใช่เหรอ?"
1004502-130 = "อย่าพูดอะไรน่าเศร้าแบบนั้นสิ... ตอนที่ฉันไม่อยู่ครูก็คิดจะมาแอบงีบที่นี่เหมือนกันไม่ใช่เหรอ?"
1004502-131 = ""
1004502-133 = ""
1004502-134 = ""
1004502-135 = "อืม... ก็นะ"
1004502-136 = "เอาเป็นว่า... ต่อไปถ้าจะมาที่นี่ก็เรียกฉันมาด้วยคนล่ะ"
1004502-138 = "(สุดท้ายทั้งสองคนก็แอบงีบด้วยกันก่อนกลับ)"
