[translation]
10043025-4 = ""
10043025-5 = "อะ... อึก..."
10043025-6 = "การแข่งขันก็แย่ พอจะระบายความเครียดก็แพ้อีก แบบนี้หัวร้อนเป็น 2 เท่าเลย..."
10043025-7 = ""
10043025-9 = ""
10043025-13 = "อืม คงเป็นแค่แฟนเบสบอลที่หัวรุนแรงสินะคะ"
10043025-14 = "รู้สึกเสียใจนิดหน่อยนะคะเนี่ย..."
10043025-15 = "[s] \"ไม่เป็นไรนะ ไม่เป็นไร...\""
10043025-16 = ""
10043025-20 = "หลังจากความยากลำบากที่เผชิญมา! ในที่สุด! เบรฟส์ก็ทำไป 3 เอาต์แล้วครับ!"
10043025-21 = "ตอนนี้ยังเป็นช่วงต้นของอินนิ่งที่ 2 อยู่เลย เริ่มเป็นห่วงเรื่องลำดับการขว้างแล้วสินะครับ หวังว่าในเกมรุกของท้ายอินนิ่งที่ 2 ทีมเบรฟส์จะโต้กลับได้นะครับ"
10043025-22 = ""
10043025-24 = ""
10043025-25 = "อ๊ะ จะเปลี่ยนเกมรุกเกมรับแล้วสินะคะ"
10043025-26 = "ถ้าอย่างนั้น... ก็เป็นเวลาที่ผู้ร้ายจะติดต่อกลับมาอีกรอบ"
10043025-27 = "..."
10043025-28 = "เทรนเนอร์ น่าจะต้องรีบไปหาเรย์แล้วละค่ะ"
10043025-29 = "[s] \"งั้นครูขอไปก่อนนะ\""
10043025-30 = "ค่ะ ไม่ต้องห่วงฉันนะคะ แล้วเราจะได้เจอกันใหม่ในสนามกีฬาแห่งนี้ค่ะ"
10043025-31 = "ฉันจะเดินสำรวจต่อไปในแบบของฉันค่ะ"
10043025-32 = "ฝากเรื่องการเจรจาด้วยนะคะ!"
