[translation]
10046250-2 = ""
10046250-3 = "ฮืมม ขอโทษนะคะ~"
10046250-4 = "ไม่ทราบว่าคุณคือผู้ดูแลชายหาดนี้หรือเปล่าคะ?"
10046250-5 = "ผู้ดูแล... จะว่าอย่างนั้นก็ได้ค่ะ"
10046250-6 = "ว่าแต่มีเรื่องอะไรเหรอคะ?"
10046250-7 = "อ๊ะ ยินดีที่ได้รู้จักค่ะ ฉันชื่อว่าคาวาวะ ชิซุโกะ เป็นเจ้าของและมาสคอตประจำร้านเฮียกคิยาโคค่ะ"
10046250-8 = "อ่า... ร้านชื่อดังของเฮียกคิยาโคสินะคะ... ได้ยินมาว่าพวกคุณมาเปิดร้านริมทางในชายหาดด้วย"
10046250-9 = "ใช่ค่ะ แล้วฉันก็ได้รับอนุญาตให้จัดงานเทศกาลที่ชายหาดด้วยค่ะ"
10046250-10 = "หืม...?"
10046250-11 = "ขอโทษนะคะ เท่าที่ฉันรู้มา งานเทศกาลอยู่ในความรับผิดชอบของชมรมจัดงานเทศกาลนี่คะ?"
10046250-12 = "ฮืมม... อะแฮ่มม! ที่จริงฉันก็เป็นหัวหน้าชมรมจัดงานเทศกาลด้วยค่ะ"
10046250-13 = "อ๊ะ งั้นเหรอคะ?! ขอโทษที่เสียมารยาทนะคะ"
10046250-14 = "แต่ก็สุดยอดไปเลยนะคะ ทั้งเป็นเจ้าของร้านค้าชื่อดัง แล้วก็ต้องจัดงานเทศกาลของเฮียกคิยาโคอีก..."
10046250-15 = "ฮุฮุ..."
10046250-16 = "มะ... ไม่หรอกค่ะ แค่นี้น่ะไม่เหลือบ่ากว่าแรงฉันหรอกค่ะ~ คนรอบตัวฉันก็ช่วยเหลือกันเยอะด้วยค่ะ~"
10046250-17 = "อ๊ะ! จะว่าไป เรื่องงานเทศกาลน่ะค่ะ!"
10046250-18 = ""
10046250-19 = ""
10046250-20 = ""
10046250-21 = ""
10046250-22 = ""
10046250-24 = ""
10046250-25 = "นี่ไม่ใช่สภาพแวดล้อมที่เหมาะกับการจัดงานเทศกาลเลยนะคะ...!"
10046250-26 = "ไหนว่าเป็นการเปิดชายหาดส่วนตัวของสภาน้ำชาเป็นครั้งแรกเลยล่ะคะ?!"
10046250-27 = "ถ้างั้นก็ต้องมีนักท่องเที่ยวไฮโซโก้หรู แล้วก็กระเป๋าหนักกว่านี้สิ...!"
10046250-28 = ""
10046250-30 = ""
10046250-31 = "มะ... ไม่สิ... ฉันคิดว่าจะเป็นชายหาดที่มีความสงบเรียบร้อยมากกว่านี้น่ะค่ะ~"
10046250-32 = "แบบนี้อย่าว่าแต่งานเทศกาลเลยค่ะ ของที่ร้านเราเอามาขายตอนนี้ก็น่าจะขายไม่ได้เลยด้วย..."
10046250-33 = "อ่า... แหะๆๆ คือว่า..."
10046250-34 = "ต้องขอโทษด้วยนะคะ พอฉันจัดการคนเดียว ก็เลยมีข้อบกพร่องหลายจุดเลย ต้องขออภัยในความไม่สะดวกด้วยนะคะ"
10046250-35 = "อืม~ คนช่วยงานไม่พอสินะคะ?"
10046250-36 = "คะ? อ่า... ค่ะ... จะว่าอย่างนั้นก็ได้ค่ะ"
10046250-37 = "ดีละ..."
10046250-38 = "งั้นก็เอาอย่างนี้ค่ะ ฉันจะช่วยดูแลชายหาดให้อีกแรงค่ะ"
10046250-39 = "คะ? อ่า... ไม่ต้องทำถึงขนาดนั้นก็ได้..."
10046250-40 = "ต้องสิคะ! ฉันต้องทำค่ะ!"
10046250-41 = "พวกเราอุตส่าห์ขนวัตถุดิบมาถึงที่นี่ ค่าขนส่งกับค่าติดตั้งร้านค้าก็...!"
10046250-42 = "ก็ตั้งแพงนะคะ! แพงมากเลยด้วย!"
10046250-43 = "......"
10046250-44 = "อ๊ะ... ที่ฉันจะบอกก็คือ~ ฉันอยากช่วยให้ทุกคนมีช่วงเวลาแสนสนุกในชายหาดน่ะค่ะ..."
10046250-45 = ""
10046250-47 = ""
10046250-48 = ""
10046250-49 = ""
10046250-50 = "......"
10046250-51 = "......"
10046250-52 = "งั้นเอาตามนั้นนะคะ!"
10046250-53 = "อ่า... ค่ะ"
