[translation]
10046025-3 = "แหม อิจิกะจัง~ แบบนี้มันไม่เกินไปหน่อยเหรอ? เราไม่ใช่คนแปลกหน้ากันเสียหน่อย"
10046025-4 = "ฉันอยากให้เราเป็นคนแปลกหน้าไปเสียเลยค่ะ!"
10046025-5 = "โธ่ถัง~ เราคนประเภทเดียวกันแท้ๆ ทำไมเป็นแบบนี้ไปได้ล่ะ?"
10046025-6 = "ใครเป็นคนประเภทเดียวกับคุณคะ!! เลิกพูดเหลวไหลแล้วหยุดอยู่ตรงนั้นเลยค่ะ!!"
10046025-7 = "วะ~ ฮะฮ่า! แรงดีไม่มีตกเลยนะ!"
10046025-8 = ""
10046025-10 = ""
10046025-12 = "......"
10046025-13 = ""
10046025-15 = ""
10046025-16 = "อ๊ะ ขอโทษค่ะ ฉันสติหลุดไปเดี๋ยวหนึ่งน่ะ"
10046025-17 = "นี่เป็นครั้งแรกเลยค่ะที่ฉันเห็นอิจิกะแสดงความรู้สึกแบบนั้นออกมา"
10046025-18 = "อิจิกะมีความสัมพันธ์ที่ไม่ดีกับนักเรียนเกเฮนน่าหรือเปล่าคะ... โดยเฉพาะเด็กที่ชื่อคาสุมิคนนั้นน่ะ?"
10046025-19 = "[s1] \"ถ้าจะให้เล่า เรื่องมันน่าจะยาวน่ะ\"\n[s2] \"เป็นเรื่องแย่ ยาก และเศร้าเลยละ...\""
10046025-20 = ""
10046025-21 = ""
10046025-23 = ""
10046025-24 = "ถึงฉันจะยังไม่ค่อยเข้าใจ แต่คงมีอะไรบางอย่างสินะคะ"
10046025-25 = ""
10046025-27 = ""
10046025-29 = ""
10046025-30 = "อืมม~ ตอนนี้คงไม่เหมาะที่จะสู้แบบเผชิญหน้ากันแล้วละ! ทุกคน ถอยก่อน! ถอนกำลัง!"
10046025-31 = ""
10046025-33 = ""
10046025-35 = ""
10046025-36 = ""
10046025-38 = "คิดว่าฉันจะปล่อยให้หนีไปเหรอคะ! รุ่นพี่ฮาสุมิ! ฉันจะไล่ตามไปเองค่ะ!"
10046025-39 = ""
10046025-41 = ""
10046025-42 = "ฮุฮุ นึกถึงปฏิการร่วมครั้งแรกของเราเลยนะคะ ตกลงค่ะ ฉันจะเป็นแนวหลังให้เองค่ะ"
10046025-43 = ""
10046025-47 = "ทุกคน หยุดก่อน!!"
10046025-48 = ""
10046025-50 = ""
10046025-51 = "คุณมิกะ...?"
10046025-52 = ""
10046025-54 = ""
10046025-56 = ""
10046025-57 = "ขอร้องละ ช่วยหยุดไล่ตามชมรมพัฒนาออนเซ็นก่อนเถอะนะ"
10046025-58 = "แต่ถ้าปล่อยไป เดี๋ยวชมรมพัฒนาออนเซ็นก็..."
10046025-59 = "อื้อ ฉันรู้ เดี๋ยวพวกนั้นก็กลับมาทำลายชายหาดส่วนตัวแห่งนี้อีกใช่มั้ยล่ะ?"
10046025-60 = "แต่เดี๋ยวนางิจังก็จะมาถึงแล้ว"
10046025-61 = ""
10046025-63 = ""
10046025-64 = "เป้าหมายของทริปนี้คือการทำให้นางิจังได้พักผ่อนเต็มที่"
10046025-65 = "ถ้านางิจังมาเห็นพวกเราต่อสู้หรือเจอร่องรอยการต่อสู้ละก็ นางิจังต้องกังวลมากแน่นอน"
10046025-66 = "เพราะงั้นเรื่องการไล่ตามเกเฮนน่าหรือจับกุมเด็กพวกนั้น... ฉันอยากให้เอาไว้ก่อนน่ะ"
10046025-67 = "และถ้าจำเป็นจริงๆ ฉันว่าเรายอมสละพื้นที่ของชายหาดบางส่วนให้ก็ได้ เพราะสิ่งที่สำคัญที่สุดก็คือ..."
10046025-68 = ""
10046025-70 = ""
10046025-72 = "ไม่สร้างความวุ่นวาย... และไม่ให้นางิจังต้องมาเหนื่อยกับเรื่องนี้..."
10046025-73 = "อื้อ..."
10046025-74 = "ฉันขอโทษนะ ทั้งคุณครูและทุกคนเลย แต่สำหรับทริปนี้ ฉันขอให้ทุกคนให้ความร่วมมือตามนี้นะ"
10046025-75 = "[s3] \"ยอดเยี่ยมเลยนะ มิกะ\"\n[s4] \"ครูก็จะช่วยเต็มที่เลย\""
10046025-76 = ""
10046025-77 = ""
10046025-79 = ""
10046025-81 = ""
10046025-82 = "น่าละอายจริงๆ เลยค่ะ... พวกฉันเผลอทำในสิ่งที่ไม่ใช่หน้าที่ของตัวเองไปเสียได้"
10046025-83 = "ค่ะ... จริงด้วยค่ะ เป้าหมายของทริปนี้คือการทำให้คุณนางิสะได้มาพักผ่อนแท้ๆ..."
10046025-84 = "งั้นพวกฉันก็ควรตรวจตราสถานที่และทำสิ่งที่จำเป็นก่อน น่าละอายจริงๆ เลยค่ะ"
10046025-85 = ""
10046025-87 = ""
10046025-88 = "รีบไปจัดการงานที่เหลือกันเถอะค่ะ เราไม่มีเวลามากแล้วนี่คะ"
10046025-96 = "ไม่น่าเชื่อเลยนะคะ..."
10046025-97 = "ขนอุปกรณ์ก่อสร้างมามากพอที่จะสร้างอาคารได้หลายหลังเลย... พวกนั้นตั้งใจจะสร้างอะไรที่นี่กัน#nคะเนี่ย?"
10046025-98 = "ก็คงเป็นออนเซ็นละค่ะ"
10046025-99 = "แบบนี้นี่เอง... เพราะแบบนี้ชมรมพัฒนาออนเซ็นก็เลยมีแต่ชื่อเสียสินะคะ"
10046025-100 = "ในเมื่อเรายึดอุปกรณ์มาได้ขนาดนี้ พวกนั้นก็คงทำงานต่อทันทีไม่ได้หรอกค่ะ"
10046025-101 = "อย่างน้อยในช่วงวันหยุดพักร้อนนี้น่ะนะคะ..."
10046025-102 = "แหะๆๆ... อื้อ หวังว่าจะเป็นอย่างนั้นนะ"
10046025-103 = "ยังไงก็ขอให้ทริปนี้จบลงด้วยดีก่อนแล้วกัน"
10046025-104 = "อื้อ ขอแค่ให้ทริปนี้จบลงด้วยดีก่อน แล้วหลังจากนั้นจะเป็นยังไงก็ได้"
10046025-105 = ""
10046025-107 = ""
10046025-108 = "คุณมิกะ?"
10046025-109 = ""
10046025-111 = ""
10046025-112 = "ไม่มีอะไรหรอก"
10046025-113 = "ขอบใจนะทุกคน"
10046025-115 = "มะ... ไม่เป็นไรค่ะ! นี่เป็นเรื่องที่พวกฉันต้องทำอยู่แล้วค่ะ!"
10046025-117 = "ใช่ค่ะ"
10046025-118 = "ถึงยังไงฉันก็อยากแสดงความขอบคุณน่ะ"
10046025-119 = "ฮิฮิ..."
10046025-121 = "คุณมิกะ...??"
10046025-122 = "[s5] \"มิกะ...?\"\n[s6] \"จู่ๆ ก็หัวเราะอะไรเหรอ...?\""
10046025-123 = ""
10046025-124 = ""
10046025-126 = ""
10046025-127 = "อ่า... อื้อ ไม่มีอะไรหรอก ก็แค่..."
10046025-128 = "รู้สึกว่า... ทริปพักผ่อนนี้กำลังผ่านไปได้ด้วยดีน่ะ! ต้องขอบใจทุกคนเลยนะ ฉันรู้สึกดีจังเลย"
10046025-129 = "อื้อ...!"
10046025-130 = "ทุกอย่างจะต้องออกมาดีเองละ!!"
