[translation]
10041030-1 = "Episode 3;How To Get Someone Mad"
10041030-6 = "One hour ago..."
10041030-9 = "Rio's hideout, right after Seia left..."
10041030-12 = "..."
10041030-13 = ""
10041030-16 = ""
10041030-17 = "...??"
10041030-18 = ""
10041030-20 = ""
10041030-21 = "What... What's making you worry so much?"
10041030-22 = ""
10041030-25 = ""
10041030-26 = "I didn't say anything about being worried."
10041030-27 = "Not everything needs to be said out loud. The look on your face says it all."
10041030-28 = "No it doesn't."
10041030-29 = "...It doesn't."
10041030-30 = ""
10041030-32 = ""
10041030-33 = ""
10041030-34 = "Am I THAT obvious?"
10041030-35 = "There are two things that piss me off. One is when people start to say something and then don't finish, and the other is—"
10041030-36 = "I never intended to make you angry."
10041030-37 = "...Which pisses me off MORE, when you say it with that face."
10041030-38 = "*sigh*"
10041030-39 = "It's SUPER obvious. Like, I'd-be-rude-if-I-ignored-it obvious."
10041030-40 = "Just spill whatever's on your mind. Quit dancing around it."
10041030-42 = "I... I don't have anything to say. At least not anything rational."
10041030-43 = "Besides, if I did say it now, I'm not sure how you'd respond. Let's gather more information first, and then when circumstances are better—"
10041030-45 = "See, now you're pissing me off more! Stop it already!"
10041030-46 = ""
10041030-48 = ""
10041030-49 = "If you want to say it, say it! If you're not going to, forget about it!"
10041030-50 = "There might come a time when I have to bring it up—"
10041030-51 = "Then say it now!! It's just the two of us here. What are you worried about?!"
10041030-52 = "Just the two of us..."
10041030-53 = ""
10041030-55 = ""
10041030-56 = "...Would it be all right, if I only told you...?"
10041030-57 = "If I didn't know you better, I'd have already hit you for jerking me around."
10041030-58 = "Are you trying to frustrate me to death, or what?"
10041030-59 = ""
10041030-61 = ""
10041030-62 = ""
10041030-63 = "If I wasn't going to help, I would have already said so. And it's not like you've never told me anything strange before."
10041030-64 = "Worst case, I'll tell you to stop talking. So go ahead. What's the big deal?"
10041030-66 = "...All right."
10041030-67 = "The big deal is Yurizono Seia. She's a variable we hadn't planned on."
10041030-69 = "Ah, I thought it might be about her."
10041030-70 = "Are you worried that she's not going to do her job properly? That she's going to cause problems? Or that she's going to spill our information?"
10041030-71 = "No, at the very least, I trust her competence and integrity. Not that I have any other option, under the circumstances."
10041030-72 = "On paper, she ought to do fine, and I don't expect her actions to have any negative impact on us specifically."
10041030-73 = "But she is the kind of person who...tends to take action on her own initiative."
10041030-74 = "So? Good for her. What's our problem with her, then?"
10041030-75 = "...We don't have a problem with her. She has a problem with herself."
10041030-76 = ""
10041030-78 = ""
10041030-79 = ""
10041030-81 = "She's still the same person at heart, but...recent events have taken their toll on her."
10041030-82 = ""
10041030-84 = "She seems anxious now, always looking over her shoulder."
10041030-85 = "And she's obsessed with the need to prove herself. She's barely even acknowledged Sensei coming along with her."
10041030-88 = "That is odd. Normally, everything goes smoother when Sensei's around."
10041030-89 = "And she has been blabbing about proving herself a lot."
10041030-90 = "She must be pretty insecure."
10041030-91 = "...Anyway."
10041030-92 = "Even if she lost her powers, her intuition and decision making skills are not to be ignored. Perhaps she'll actually bring back useful information."
10041030-93 = "But even so, we should only consider that an added bonus. We shouldn't rely on her."
10041030-94 = "I'm thankful for her proposal, but we're going to go ahead as planned."
10041030-95 = ""
10041030-97 = ""
10041030-98 = "On that note, we need you to infiltrate Millennium Data Center and check the overall flow of data, throughout the event preparation period."
10041030-99 = "That's a tough assignment. The Data Center, of all places."
10041030-100 = "Isn't that the tightest-locked place in the school? Almost nobody could break in there."
10041030-101 = "I factored that in when I chose you for the job. Do you see any problems with that?"
10041030-102 = ""
10041030-104 = ""
10041030-105 = "...Huh!"
10041030-106 = "So you can be charming occasionally. No problems. I'm Mikamo Neru, after all."
10041030-107 = "Sit back and wait here, Miss Client."
10041030-108 = ""
10041030-110 = ""
10041030-111 = "I'll have it done in just a sec! ♪"
