[translation]
10045030-1 = "#title;제3화;제2회전: 폭주 제트보트"
10045030-2 = "3;키쿄 수영복;04\n#3;a\n#3;em;[...]\n#wait;2500"
10045030-3 = "2;나구사 수영복;02;키쿄? 아직도 기분이 안 좋아?\n#2;a\n#3;m4\n#2;em;[?]"
10045030-4 = "2;나구사 수영복;01;뭐 맛있는 거라도 줄까?"
10045030-5 = "3;키쿄 수영복;99;……걱정해 줘서 고맙지만 괜찮아."
10045030-6 = "3;키쿄 수영복;02;닭꼬치는 나중에 먹을게.\n#3;em;[반응]"
10045030-7 = "2;나구사 수영복;02;나는 닭꼬치 준다고 말한 적 없는데?"
10045030-8 = "#st;[0,0];instant;1;"
10045030-10 = "2;나구사 수영복;01\n3;키쿄 수영복;02\n#2;h\n#3;h\n#2;greeting\n#wait;800"
10045030-11 = "2;나구사 수영복;01\n3;키쿄 수영복;02\n#2;h\n#3;h\n#2;greeting\n#wait;800"
10045030-12 = "2;나구사 수영복;03;우물우물.\n#2;stiff"
10045030-14 = "3;키쿄 수영복;04;먹으면서 말하면 설득력 없는데…….\n#3;em;[땀]\n#3;closeup"
10045030-15 = "3;키쿄 수영복;99;……후우. 아니다. 나도 줘.\n#3;closeup"
10045030-16 = "3;키쿄 수영복;01;먹어서 체력을 조금이라도 채워 놔야지.\n#3;closeup"
10045030-17 = "3;키쿄 수영복;13;(어떻게든 보트 위에서 버텨야 하니까.)\n#3;closeup\n#3;em;[속상함]\n#3;stiff"
10045030-18 = "3;나구사 수영복;03;응. 여기.\n#3;em;[반짝]\n#3;greeting"
10045030-19 = "1;유카리 수영복;03;후후, 이곳의 닭꼬치도 참 맛있사와요.\n#1;ar\n#1;em;[음표]"
10045030-20 = "5;렌게 수영복;01;일단 먹으면서 어떤 보트인지 구경이나 하러 가자.\n#5;a\n#5;em;[반응]"
10045030-25 = "#na;렌게 수영복;오…… 저건가?"
10045030-26 = "#st;[0,0];instant;1;"
10045030-29 = "1;유카리 수영복;09;오오……! 소녀, 이런 보트는 처음 타보아요!\n#1;a\n#1;em;[음표]"
10045030-30 = "[ns1] \"1회전 통과 축하해.\"\n[ns2] \"다들 사전 답사하러 온 거야?\""
10045030-33 = "5;키쿄 수영복;04;선생님. 이거…… 정말로 안전한 거야?\n#5;em;[...]\n#5;a"
10045030-34 = "5;키쿄 수영복;01;물에 떨어지면 바로 구출되는 거지?"
10045030-35 = "[s3] \"응. 구조대가 상시 대기 중이니까.\"\n[s4] \"만일의 사태엔 대비하고 있으니까 안심해.\""
10045030-38 = "1;유카리 수영복;09\n5;키쿄 수영복;99;……그렇다면 다행이네.\n#5;m3\n#1;dl"
10045030-39 = "5;키쿄 수영복;99;(수영을 못해도 어떻게든 얼버무릴 수 있겠어.)\n#5;em;[반짝]"
10045030-41 = "3;렌게 수영복;09;왜? 설마 떨어질까 불안해?\n#3;em;[재잘]"
10045030-42 = "3;키쿄 수영복;04;무, 무슨 소리를.\n#3;stiff"
10045030-43 = "3;키쿄 수영복;02;모든 상황에 대처해야 하는 게 작전참모인 내 역할이야. 설마 그걸 잊은 건 아니겠지?\n#3;em;[?]"
10045030-44 = "3;키쿄 수영복;99;다들 알겠지만 이전 경기에서 우릴 방해하던 녀석들도 그대로 살아남았어."
10045030-45 = "3;키쿄 수영복;05;이번엔 또 어떤 짓을 저지를지 몰라."
10045030-46 = "[s5] \"후후, 그거라면 걱정하지 마.\"\n[s6] \"남을 방해할 정도의 여유는 없을 테니까.\""
10045030-49 = "3;키쿄 수영복;04;……자기 혼자 살아남기도 바쁠 거라는 이야기인가.\n#3;em;[땀]"
10045030-50 = "3;유카리 수영복;02;그 정도로 위험하다면…… 우리 이렇게 해보아요.\n#3;em;[반응]"
10045030-51 = "3;유카리 수영복;00;서로 팔짱을 끼고 안전 바를 잡는 것이어요! 어떠한가요?\n#3;jump"
10045030-52 = "4;키쿄 수영복;01\n2;렌게 수영복;02;오, 그거 정말 좋은 생각이네.\n#3;hide"
10045030-53 = "4;키쿄 수영복;99;수영복을 입고 밀착이라니……. 하지만 다른 방법이 없겠어.\n#4;em;[한숨]"
10045030-55 = "3;나구사 수영복;02;그럼 제일 왼쪽에 내가 앉고, 오른쪽 끝에 렌게가 앉자."
10045030-56 = "3;나구사 수영복;01;유카리와 키쿄는 중앙에 들어가면 될 거야."
10045030-58 = "4;키쿄 수영복;01\n2;렌게 수영복;09;좋아! 나구사 선배의 봉인 해제된 오른손의 힘을 보여주는 거야!\n#2;em;[!]"
10045030-59 = "4;키쿄 수영복;04;……그러니까 그런 말 묘하게 중2병 같으니까 다른 사람들 앞에서 하지 말라고."
10045030-60 = "4;키쿄 수영복;04\n2;렌게 수영복;09\n3;나구사 수영복;99;나는 괜찮아. 이걸로 모두가 즐거워한다면.\n#3;a\n#4;m5\n#2;m1"
10045030-61 = "2;렌게 수영복;09\n3;나구사 수영복;09;후후, 보여줄게. 황혼의 그림자에 유폐되어 있던 내 진정한 힘을.\n#3;em;[반짝]"
10045030-62 = "2;렌게 수영복;09\n4;키쿄 수영복;04;진짜로 걱정되니까 그만둬…….\n#4;em;[땀]"
10045030-64 = "3;유카리 수영복;13;아무튼 이걸로 대비책도 마련했으니 다 같이 통과해 버리어요!\n#3;closeup\n#3;em;[음표]"
10045030-66 = "#na;잠시 후……."
10045030-69 = "3;시즈코 수영복ND;02;여러분, 오래 기다리셨습니다! 드디어 두 번째 경기의 준비가 끝났어요!\n#3;a\n#3;em;[반응]"
10045030-70 = "#st;[0,0];instant;1;"
10045030-72 = "3;시즈코 수영복ND;02\n#3;m5\n#wait;1000"
10045030-74 = "3;시즈코 수영복ND;01;예고했던 대로 이번 경기는 폭주하는 제트보트!"
10045030-75 = "3;시즈코 수영복ND;00;30인의 선수들이 두 대의 제트보트에 나누어 타서 최종 10인이 남을 때까지 무한 잠수와 드리프트가 이어집니다!"
10045030-76 = "3;시즈코 수영복ND;03;모두 날아가지 않게 조심해 주세요, 냥냥!\n#3;em;[재잘]"
10045030-77 = "#st;[0,0];instant;1;"
10045030-79 = "3;시즈코 수영복ND;03\n#3;d\n#wait;1000"
10045030-80 = "[ns] \"그럼 선수들 탑승!\""
10045030-81 = "5;키쿄 수영복;01\n4;나구사 수영복;01\n1;유카리 수영복;01\n2;렌게 수영복;01\n#4;a\n#5;a\n#1;a\n#2;a\n#1;h\n#2;h\n#4;h\n#5;h\n#wait;1000"
10045030-82 = "4;나구사 수영복;02;다들 기억해. 서로 팔짱을 끼고 안전바를 잡는 거야."
10045030-83 = "1;유카리 수영복;00;네! 반드시 모두 살아남는 것이어요!\n#1;em;[!]"
10045030-84 = "#st;[0,0];instant;1;"
10045030-86 = "5;키쿄 수영복;01\n4;나구사 수영복;02\n1;유카리 수영복;00\n2;렌게 수영복;08\n#1;h\n#2;h\n#4;h\n#5;h\n#2;em;[반응]\n#4;em;[반응]\n#wait;1500"
10045030-87 = "5;키쿄 수영복;01\n4;나구사 수영복;02\n1;유카리 수영복;00\n2;렌게 수영복;08\n#1;h\n#2;h\n#4;h\n#5;h\n#1;dr\n#2;dr\n#4;dr\n#5;dr\n#wait;1500"
10045030-89 = "3;시즈코 수영복ND;02;모두 탑승하셨나요?\n#3;a\n#3;em;[?]"
10045030-90 = "3;시즈코 수영복ND;00;제2회전, 폭주 제트보트……!\n#3;jump"
10045030-91 = "[ns] \"시작—!!\""
10045030-96 = "#na;렌게 수영복;크으으윽! 이 속도는……?!"
10045030-97 = "#st;[0,0];instant;1;"
10045030-100 = "#na;유카리 수영복;꺄, 꺄아아아악……!!\n#fontsize;80"
10045030-101 = "#na;나구사 수영복;최대한 밀착해! 떨어지지 않게 서로에게 힘을 빌려주는 거야!\n#fontsize;80"
10045030-102 = "#st;[0,0];instant;1;"
10045030-105 = "2;렌게 수영복;04\n4;키쿄 수영복;13;무리야……! 이건 무리……!!\n#4;em;[땀]\n#2;closeup\n#4;closeup"
10045030-106 = "2;렌게 수영복;25\n4;키쿄 수영복;13\n#na;렌게 수영복;큭, 내가 어떻게든 몸으로라도……!\n#2;closeup\n#2;stiff\n#2;h\n#4;closeup"
10045030-107 = "2;렌게 수영복;25\n4;키쿄 수영복;09;으으윽! 고마워.\n#4;closeup\n#2;closeup"
10045030-108 = "2;렌게 수영복;25\n4;키쿄 수영복;02;네 등, 생각보다 부드럽네.\n#4;closeup\n#4;greeting\n#2;closeup"
10045030-109 = "2;렌게 수영복;19\n4;키쿄 수영복;02\n#na;렌게 수영복;등 아니거든!!\n#2;closeup\n#2;h\n#2;em;[///]\n#4;closeup"
10045030-110 = "2;렌게 수영복;19\n4;키쿄 수영복;04;아……. 미안.\n#4;closeup\n#2;closeup\n#fontsize;50"
10045030-111 = "2;렌게 수영복;25\n4;키쿄 수영복;04\n#na;렌게 수영복;사과하지 마!\n#2;closeup\n#2;h\n#2;em;[!]\n#4;closeup"
10045030-112 = "#st;[0,0];instant;1;"
10045030-118 = "#na;유카리 수영복;꺄아아아아앙!!\n#fontsize;80"
10045030-119 = "#na;키쿄 수영복;윽, 유카리? 그건 내 꼬리야……!"
10045030-120 = "#na;유카리 수영복;죄, 죄송하여요! 소녀, 이걸 놓치면 탈락이어요……!!"
10045030-121 = "#na;키쿄 수영복;하, 하지만, 거긴……!"
10045030-122 = "#na;유카리 수영복;죄송하여요오오오……!!"
10045030-123 = "#na;키쿄 수영복;괘, 괜찮아! 어떻게든 버틸 테니…… 아앗……!!"
10045030-124 = "#st;[0,0];instant;1;"
10045030-127 = "3;나구사 수영복;07;그래! 모두가 힘을 합치는 거야……!\n#3;closeup"
10045030-128 = "3;키쿄 수영복;13;이런 식으로 합치고 싶진 않았어……!\n#3;closeup\n#3;em;[속상함]"
10045030-129 = "3;렌게 수영복;16;아핫핫! 이게 청춘인가!!\n#3;closeup\n#3;em;[재잘]\n#fontsize;80"
10045030-131 = "3;시즈코 수영복ND;03;비명이 끊이질 않네요……!\n#3;em;[음표]\n#3;a"
10045030-132 = "3;시즈코 수영복ND;03\n#na;선수 A;누구야! 이런 엉망진창인 종목을 생각한― 보글보글보글."
10045030-133 = "3;시즈코 수영복ND;03\n#na;선수 B;꺄아아아악!!"
10045030-134 = "#st;[0,0];instant;1;"
10045030-136 = "3;시즈코 수영복ND;03\n#3;h"
10045030-138 = "3;시즈코 수영복ND;00;자아! 탈락자가 속출하는 가운데, 다음 라운드 진출자 10인은 과연 누구가 될까요!"
10045030-139 = "3;시즈코 수영복ND;02;끝까지 함께 지켜보아요, 냥냥!\n#3;em;[재잘]"
