[translation]
10040110-1 = "ย้อนวันวาน;เครื่องดื่มขั้นสุด"
10040110-2 = "(ในระหว่างที่จิฮิโระ ยูกะ และโนอาออกไปซื้อขนม...)"
10040110-3 = "ฮื้ม~ สนุกจังเลย"
10040110-4 = "ถึงจะเล่น <BOOM> มาแล้วเป็นสิบๆ รอบ แต่ก็ยังตื่นเต้นในทุกครั้งที่ได้เล่นเลยนะ สมแล้วละที่เป็น#nเกมระดับตำนาน"
10040110-5 = "ถึงครั้งนี้จะตื่นเต้นในทางอื่นก็เถอะนะ"
10040110-6 = "ถ้ารุ่นพี่จิฮิโระบอกว่าอยากเปลี่ยนปืนประจำตัวเป็นปืนลูกซองขึ้นมาละก็ ไม่ว่ายังไงเราก็ต้องขัดขวาง#nไว้ให้ได้นะ..."
10040110-8 = "แหะ... แหะๆ... คงจะจริงน่ะนะที่บอกว่าเวลาเล่นเกม นิสัยคนจะเปลี่ยนไปได้เหมือนกับตอนขับรถ"
10040110-9 = "เมื่อกี้ตื่นเต้นมากจนจู่ๆ ก็คอแห้งขึ้นมาเลยแฮะ"
10040110-10 = "รุ่นพี่ฮาเระ ฉันขอดื่ม <มอนสเตอร์แม็กซ์> ที่อยู่ตรงนี้ได้มั้ย?"
10040110-11 = "อื้อ ได้สิ แต่ว่ากระป๋องนั้นมัน..."
10040110-12 = ""
10040110-14 = ""
10040110-17 = ""
10040110-18 = "แค่ก แค่ก...!"
10040110-19 = "อะไรเนี่ย ทำไม <มอนสเตอร์แม็กซ์> กระป๋องนี้มันเปรี้ยวแบบนี้! หมดอายุแล้วหรือเปล่าเนี่ย?"
10040110-20 = "เมื่อกี้ฉันถึงได้พูดเตือนไง...  <มอนสเตอร์แม็กซ์> กระป๋องนั้นเป็นรสบ๊วยที่เพิ่งออกมาใหม่น่ะ"
10040110-21 = "รสบ๊วยงั้นเหรอ?!"
10040110-23 = "<มอนสเตอร์แม็กซ์> ขยันออกรสอะไรมากมายจังเลยนะคะ ตอนออกรสโจ๊กถั่วแดงเมื่อเดือนก่อน ในโซเชียลก็พูดถึงกันใหญ่เลย"
10040110-25 = "ถึงมันจะไม่ค่อยอร่อย แต่ถ้ากินเพื่อให้ตื่นละก็ถือว่าใช้ได้เลย ปกติแล้วรสเปรี้ยวจะทำให้เราตื่นตัวน่ะ"
10040110-26 = "อึก รสเปรี้ยวของบ๊วยทำเอาฉันรู้สึกอยากกินข้าวขาวขึ้นมาเลย"
10040110-27 = "หรือไม่ก็เป็นสาเกสักอึกก็ได้..."
10040110-28 = ""
10040110-30 = ""
10040110-31 = ""
10040110-32 = "รุ่นพี่ จู่ๆ ฉันก็ปิ๊งไอเดียนี้ขึ้นมาน่ะ..."
10040110-33 = "ถ้าเราเอา <มอนสเตอร์แม็กซ์> รสบ๊วยมาผสมกับสาเก งั้นก็จะให้ความรู้สึกเหมือนเรากินข้าวหน้าบ๊วย#nตากแห้งมั้ย?"
10040110-35 = "ไม่หรอกค่ะ"
10040110-36 = "มันไม่น่าจะออกมาเป็นรสนั้นนะ..."
10040110-38 = "แต่ถ้าเราผสมอาหารสองรสชาติเข้าด้วยกัน บางทีเราก็จะได้รสชาติใหม่ที่แตกต่างไปจากของเดิมโดย#nสิ้นเชิงไม่ใช่เหรอ?"
10040110-39 = "ฉันว่าเครื่องดื่มสองอย่างนี้น่าจะผสมผสานกันจนเกิดเป็นรสที่อร่อยขึ้นก็ได้..."
10040110-40 = ""
10040110-42 = ""
10040110-43 = "ฮุฮุ เป็นไอเดียที่น่าสนใจนะคะ"
10040110-44 = "ตะ... ตกใจหมดเลย! ตื่นขึ้นมาตั้งแต่เมื่อไรเนี่ย?"
10040110-45 = "น่าจะตั้งแต่ตอนที่ทุกคนเล่นเกม <BOOM> ในทีวีนะ...?"
10040110-46 = "แต่ฉันรู้สึกได้ถึงความป่าเถื่อนที่หน้าทีวี ก็เลยแกล้งทำเป็นหลับต่อน่ะค่ะ"
10040110-48 = "ก็นะ... การเล่น <BOOM> ของรองหัวหน้าก็ถือว่าป่าเถื่อนเลยละ"
10040110-49 = "จะว่าไป ฉันว่าการผสมมอนสเตอร์แม็กซ์รสบ๊วยกับสาเกฟังดูน่าสนุกมากๆ เลยนะคะ"
10040110-50 = "ปาร์ตี้ของเราก็มีเครื่องดื่มเต็มห้องเลยด้วย งั้นลองมาผสมรสอื่นกันด้วยมั้ยคะ?"
10040110-51 = "ฟังดูน่าสนุกงั้นเหรอ... พูดเหมือนกับว่าเคยผสมเครื่องดื่มมาก่อนแล้วอย่างนั้นละ?"
10040110-52 = "ฉันยังไม่เคยผสมบ๊วยกับสาเกค่ะ แต่ว่าก่อนหน้านี้ก็เคยทดลองทำเครื่องดื่มจากของในตู้เย็นของ#nเซมิน่ามาบ้างแล้ว"
10040110-53 = "ในอินเทอร์เน็ตก็มีบอกไว้เยอะแยะเลยนี่คะ ที่บอกว่าถ้าใส่ซอสทาบาสโก้ในน้ำมะเขือเทศก็จะได้น้ำรส#nพิซซ่า หรือถ้าผสมซีอิ๊วกับนม ก็จะออกมาเป็นนมรสข้าวเกรียบ..."
10040110-54 = "แหวะ... ตอนที่ทำน่ะ ได้รับอนุญาตจากสมาชิกเซมิน่าคนอื่นหรือเปล่า?"
10040110-55 = ""
10040110-57 = ""
10040110-58 = "คะ...? ไม่เห็นต้องขออนุญาตเลยนี่คะ?"
10040110-59 = "ว่าไงนะ...?"
10040110-61 = "ที่ฉันจะสื่อก็คือ ถ้าเราต้องขออนุญาตกับทุกเรื่องเล็กน้อยในโลก เราก็ไม่ได้ทำอะไรกันพอดีค่ะ ลงมือทำไปก่อน แล้วค่อยมาขอโทษทีหลังง่ายกว่าค่ะ!"
10040110-63 = "เป็นตรรกะที่ยอดเยี่ยมไปเลยนะ..."
10040110-64 = "ฉันเข้าใจถึงความยากลำบากของยูกะแล้วละค่ะ"
10040110-66 = "ว่าแต่หลังจากทำไปแล้วได้รับการยกโทษหรือเปล่า?"
10040110-67 = "เฮ้อ... ฉันมีประวัติเยอะจนไม่ได้รับการยกโทษง่ายๆ หรอกค่ะ..."
10040110-68 = "ก็ไม่แปลกหรอก..."
10040110-69 = "แต่นี่เป็นครั้งแรกเลยนะที่ฉันจะได้ทำการทดลองกับมอนสเตอร์แม็กซ์ ตื่นเต้นจังเลยค่ะ"
10040110-70 = "เอาละ ทุกคนคะ รีบผสมเครื่องดื่มก่อนที่รุ่นพี่ที่น่ารำคาญจะกลับมาเถอะค่ะ!"
10040110-71 = "ว่าแต่เราจะผสมได้ตามใจชอบเลยเหรอ? ถ้าเกิดรุ่นพี่จิฮิโระจับได้ทีหลัง เราอาจโดนดุว่าทำของกิน#nเสียของนะ..."
10040110-72 = "โอ้ว...?"
10040110-73 = "นี่เป็นภาพที่คาดไม่ถึงเลยนะคะ เหล่าแฮ็กเกอร์ของเวอริทัสที่ค้นคว้าทางวิชาการและมุ่งแสวงหาความ#nจริงกำลังลังเลที่จะค้นพบความเป็นไปได้ใหม่ๆ ที่อยู่ตรงหน้าเพียงเพราะกลัวว่ารุ่นพี่จะดุเหรอคะเนี่ย..."
10040110-74 = "ฉันขอถามเผื่อๆ ไว้นะคะ..."
10040110-75 = ""
10040110-77 = ""
10040110-78 = "ป๊อดกันเหรอ...?"
10040110-80 = "บะ... บ้าเหรอ? ว่าใครป๊อดน่ะ?!"
10040110-81 = "พอได้ฟังแบบนี้ก็เกิดความรู้สึกอยากเอาชนะแปลกๆ แฮะ..."
10040110-82 = "น้องเล็กของเซมิน่ามีพรสวรรค์ในการยั่วยุคนอื่นตามข่าวลือจริงๆ เลยนะคะ"
10040110-83 = "แต่คิดว่าพูดแบบนั้นแล้วฉันจะกลัวหรือไง? ต่อให้ไม่พูดแบบนั้น ฉันก็กำลังจะผสมเครื่องดื่มอยู่แล้ว"
10040110-84 = "เอาละ ผสม <มอนสเตอร์แม็กซ์> รสบ๊วยกับสาเกที่ทำมาจากข้าวในอัตราส่วน 1:1"
10040110-85 = ""
10040110-87 = ""
10040110-88 = "ถึงจะมาพูดเอาป่านนี้ก็เถอะ แต่ผสมออกมาแล้วได้สีสวยเลยนะคะ"
10040110-89 = "ถึงจะมาพูดเอาป่านนี้งั้นเหรอ ฟังแล้วมันตงิดๆ นะ..."
10040110-91 = "ฮืม ดูจากภายนอกแล้วเป็นสีชมพูน่ากินเลย ถ้าดูจากสีละก็ ฉันไม่รู้สึกว่ารสชาติมันจะแปลกเลยละ"
10040110-92 = "แล้วรู้สึกเหมือนได้กินข้าวหน้าบ๊วยตากแห้งจริงๆ มั้ยคะ?"
10040110-93 = ""
10040110-96 = ""
10040110-98 = ""
10040110-99 = "ไม่นะ..."
10040110-100 = "กลิ่นหอมหวานของข้าวกับรสเปรี้ยวของบ๊วย..."
10040110-101 = "ให้ความรู้สึกเหมือนดื่มสาเกที่ทำจากข้าวบูดที่ทิ้งไว้นานเลย"
10040110-103 = "ไม่สำเร็จเหรอเนี่ย"
10040110-104 = "แต่ก็นะ การมิกซ์เสียงหลายๆ เสียงก็ไม่ได้แปลว่าจะออกมาเป็นเสียงที่น่าฟังตลอดนี่คะ"
10040110-106 = "อ๊ะ จะว่าไป~ เห็นว่าถ้าผสมเครื่องดื่มรสเปรี้ยวกับนม ก็จะเป็นนมเปรี้ยวนะคะ~"
10040110-107 = "งั้นถ้าเราผสมนมกับเครื่องดื่มรสบ๊วยที่มีสาเกผสมอยู่ด้วย ก็อาจจะได้นมเปรี้ยวในรสที่ไม่เคยมีมาก่อน#nก็ได้นะ...?"
10040110-108 = "ไม่มีทางหรอก ถ้าจะทำนมเปรี้ยวน่ะ ต้องใช้กรดที่พบในน้ำส้มสายชู..."
10040110-109 = ""
10040110-111 = ""
10040110-112 = ""
10040110-113 = "มากิ หรือว่าเธอ..."
10040110-114 = "ฮุฮุ ถ้าทำไปตั้งขนาดนั้นแล้ว จะทดลองอะไรต่ออีกหน่อยก็ไม่เป็นอะไรหรอก"
10040110-115 = "เอาละ มาผสมเครื่องดื่มที่เราสงสัยในรสชาติกันมาตลอดในวันนี้ให้หมดเลย!"
10040110-117 = "GO!"
10040110-118 = ""
10040110-123 = ""
10040110-124 = ""
10040110-125 = "อืม..."
10040110-126 = "อืมม..."
10040110-127 = "แปลกจัง เราก็ไม่ได้ใส่เครื่องเทศอะไรลงไปสักหยดเลยนี่นา..."
10040110-128 = "แต่ทำไมมีกลิ่นแสบจมูกแบบนี้ล่ะ..."
10040110-129 = "ยิ่งไปกว่านั้นสีที่ออกมายังเป็นสีม่วงเข้มน่าสยดสยองอีก รู้สึกเลยว่าแค่จิบเข้าไปแค่เดียวก็จะทำให้#nท้องไส้ปั่นป่วนได้เลย"
10040110-130 = "ไม่ว่ารสชาติจะเป็นยังไง แต่ถ้าเราโดนรุ่นพี่จิฮิโระจับได้ละก็ เรื่องคงไม่จบแค่การโดนดุอย่างเดียวแน่"
10040110-131 = "ถ้ารุ่นพี่จิฮิโระรู้ว่าพวกเราใช้ครึ่งหนึ่งของเครื่องดื่มที่เตรียมมาในการทดลองผสมอะไรนี่ละก็..."
10040110-132 = "ใช้ครึ่งหนึ่งของเครื่องดื่มไปทำอะไรนะ...?"
10040110-133 = ""
10040110-135 = ""
10040110-137 = ""
10040110-138 = "ระ... รุ่นพี่จิฮิโระ? กลับมาตั้งแต่เมื่อไรน่ะ?"
10040110-139 = "เมื่อกี้เลย แล้วฉันก็เหมือนจะได้ยินเรื่องอะไรแปลกๆ ด้วยนะ"
10040110-140 = "แล้วน้ำสีแปลกๆ ที่อยู่ในแก้วนี้มันอะไรกัน?"
10040110-141 = "คะ... คือว่ามัน..."
10040110-142 = "ชะ... ใช่! พอดีโคยูกิจังบอกว่าถ้าผสมเครื่องดื่มหลายๆ อย่างเข้าด้วยกัน ก็จะได้เครื่องดื่มที่มีรสชาติ#nน่าทึ่งน่ะ!"
10040110-144 = "หักหลังกันเหรอ...???????!"
10040110-146 = "โค~ ยู~ กิ~? อาศัยจังหวะที่พวกฉันไปร้านสะดวกซื้อแล้วตื่นขึ้นมาก่อเรื่องอีกแล้วเหรอ..."
10040110-147 = "ครั้งนี้ต้องทำให้สำนึกผิดอย่างจริงจังแล้วละ!"
10040110-149 = "ไม่ใช่อย่างนั้นนะ...!!"
10040110-151 = "แงงงงงงง!!!"
