[translation]
10046040-1 = "ตอนที่ 4;ไม่ขอเจรจากับนักชิม"
10046040-2 = "ถึงจะไม่รู้รายละเอียดมาก..."
10046040-3 = "แต่เท่าที่ได้ยินจากคุณครู เห็นว่าคุณอยากได้วัตถุดิบสำหรับทำบาร์บีคิวอย่างเร่งด่วนเลยเหรอคะ? แล้วก็อยากได้แบบที่พร้อมย่างเลยด้วย?"
10046040-4 = ""
10046040-6 = ""
10046040-7 = "อะ... อื้อ! อย่างที่ว่าเลยละ!"
10046040-8 = "คุณครูบอกว่าไม่ใช่เรื่องแปลกที่ชมรมชิมอาหารของเกเฮนน่าจะมีของแบบนั้นติดตัวน่ะ!"
10046040-9 = "ที่จริงฉันคิดว่ามันแปลกนิดหน่อย แต่คุณครูก็ไม่มีทางโกหกเรื่องแบบนี้อยู่แล้ว..."
10046040-10 = ""
10046040-13 = ""
10046040-14 = "ทำไมจู่ๆ ถึงอยากได้เซ็ตบาร์บีคิวขึ้นมาเหรอ?"
10046040-15 = "ฉันพอเดาได้อยู่นะ ของแบบนี้ก็มีอยู่บ่อยไม่ใช่เหรอ? ความรู้สึกที่ว่า ตอนนี้ต้องเป็นอันนี้เท่านั้น! อะไรแบบนี้น่ะ!"
10046040-16 = "มันก็มีบ้างน่ะนะ แต่ปกติแล้วเราขอร้องเรื่องแบบนั้นกับนักเรียนโรงเรียนอื่นกันเหรอ?"
10046040-17 = "แล้วนี่ยังเป็นสภาน้ำชาอีก? สภาน้ำชาเป็นคนใหญ่คนโตในทรีนิตี้เลยไม่ใช่เหรอ? แค่ออกคำสั่ง ลูกน้องในชมรมก็น่าจะไปหามาให้ทันทีเลยนี่?"
10046040-18 = "สภาน้ำชาเหรอ? งั้นก็ดื่มชากับกินคุกกี้ได้ทุกเวลาเลยน่ะสิ? น่าอิจฉาจัง~!"
10046040-19 = "ไม่หรอก... อืม? มันเหมือนจะไม่ใช่ แต่ก็อาจจะคล้ายๆ นะ...?"
10046040-20 = ""
10046040-22 = ""
10046040-24 = "ฉันไม่รู้ว่าคุณครูรู้เรื่องนี้ได้ยังไงหรอกนะคะ"
10046040-25 = "แต่พวกเราก็บังเอิญมีเซ็ตบาร์บีคิวกันจริงๆ ค่ะ เป็นของคุณภาพดีที่ไม่ว่าใครได้เห็นก็ต้องร้องว้าวเลย#nละค่ะ"
10046040-26 = "[s1] \"มีจริงๆ เหรอ?!\"\n[s2] \"ครูแค่ลองถามเฉยๆ นะเนี่ย!\""
10046040-29 = "คุณครูถึงกับตกใจเลยเหรอ?"
10046040-30 = "แต่ยังไงก็โล่งอกไปทีนะ~ จากนี้ก็แค่อธิบายเพื่อโน้มน้าวให้นักเรียนพวกนั้นยอมให้มาก็พอ"
10046040-31 = "เอ่อ... เธอคือฮารุนะจัง... จากเกเฮนน่าใช่มั้ยนะ?"
10046040-32 = "ถ้าฉันจะขอเซ็ตบาร์บีคิวนั้นจะได้มั้ย?"
10046040-33 = "แน่นอนว่าฉันไม่ได้จะขอฟรีๆ หรอกนะ! ฉันจะจ่ายเงินให้สมราคาด้วย เรียกราคามาได้เลย..."
10046040-34 = ""
10046040-36 = ""
10046040-37 = "อ๊ะ จริงสิ ตอนนี้ฉันทำแบบนั้นไม่ได้แล้ว..."
10046040-38 = "แต่ยังไงฉันก็จะตอบแทนให้อย่างเหมาะสมเลยนะ!"
10046040-39 = "ฮุฮุ นี่คือการเจรจาต่อรองเหรอคะ? น่าสนใจนะคะเนี่ย ถ้าเป็นถึงสภาน้ำชา ก็น่าจะได้การตอบแทนที่#nคุ้มค่าอย่างไม่ต้องสงสัยเลย"
10046040-40 = "เอาตามนั้นมั้ย...!"
10046040-41 = "แต่ว่า... ฉันขอปฏิเสธค่ะ"
10046040-42 = "งะ... ไหงงั้นล่ะ?!"
10046040-43 = "พวกฉันคือนักชิม ประสบการณ์กับคุณค่าที่ได้จากการชิมอาหารรสเลิศแลกด้วยเงินจำนวนมากไม่ได้#nหรอกค่ะ"
10046040-44 = "ยิ่งไปกว่านั้น ความพยายามที่จะเปลี่ยนอาหารเป็นเงินเพราะถือความสะดวกสบายเข้าว่า ก็ทำให้ฉันรู้สึกถูกเหยียดหยามด้วยค่ะ"
10046040-46 = "ว่าแล้วเชียว..."
10046040-47 = ""
10046040-49 = ""
10046040-50 = "คุณมิกะ ขออภัยที่เข้ามาแทรกนะคะ แต่จากนี้ให้ฉันจัดการเถอะค่ะ"
10046040-51 = "อย่าเลยค่ะ รุ่นพี่ฮาสุมิ... มันเร็วเกินไปนะคะ"
10046040-52 = "ฉันว่าเรามาคุยกันอีกสักหน่อย... ถ้าได้คุยกันละก็... อืม~"
10046040-53 = ""
10046040-57 = ""
10046040-60 = ""
10046040-61 = "ฉันก็เห็นด้วยกับรุ่นพี่ฮาสุมิค่ะ... ฉันรู้สึกได้ว่าอีกฝ่ายไม่ใช่คนที่เจรจาอย่างสันติได้ค่ะ"
10046040-62 = "คุณครูเองก็ด้วยค่ะ"
10046040-63 = "[s3] \"หะ... หืม?!\"\n[s4] \"ทำไมครูถึงโดนไปด้วยล่ะ?!\""
10046040-66 = "จู่ๆ ก็บอกว่าจะแนะนำคนให้ แต่ไม่คิดเลยนะคะว่าจะเป็นชมรมชิมอาหาร"
10046040-67 = "คุณครูคิดบ้างหรือเปล่าคะว่าคนพวกนั้นสร้างความเสียหายให้เขตปกครองตนเองทรีนิตี้มาเท่าไรแล้ว?"
10046040-68 = "แล้วยังจะพาคุณมิกะมาเผชิญหน้าพวกคนอันตรายเหล่านี้อีก"
10046040-69 = "[s5] \"ไม่นะ! แต่ก็ไม่อันตรายเท่ากับที่ฮาสุมิคิดหรอก...\"\n[s6] \"เด็กพวกนี้ไม่อันตราย... ซะทีไหนกันล่ะเนอะ...\""
10046040-70 = ""
10046040-71 = ""
10046040-73 = ""
10046040-74 = "เห็นมั้ยล่ะคะ! คุณครูเองก็คิดเหมือนกันไม่ใช่เหรอคะ!"
10046040-75 = "ฉันไม่ขอเจรจาต่อรองค่ะ เอาวัตถุดิบมาเดี๋ยวนี้..."
10046040-77 = "ดะ... เดี๋ยว!"
10046040-78 = ""
10046040-80 = ""
10046040-81 = ""
10046040-83 = "เดี๋ยวก่อนนะ ฮาสุมิจัง"
10046040-84 = ""
10046040-86 = ""
10046040-87 = ""
10046040-88 = "ฉันอยากคุยต่ออีกหน่อยน่ะ บางทีเราอาจได้ข้อตกลงระหว่างกันก็ได้นะ"
10046040-89 = "ถ้าเกิดการต่อสู้ขึ้น ฉันเกรงว่ามันจะเป็นเรื่องใหญ่กว่าเดิมน่ะ"
10046040-90 = "บางทีนางิจังหรือเซอาจังอาจจะจับสังเกตได้... เพราะงั้นฉันขอละนะ"
10046040-91 = "ฉันอยากให้วันนี้ไม่มีเรื่องวุ่นวายอะไรเลยน่ะ"
10046040-92 = ""
10046040-94 = ""
10046040-96 = "คุณมิกะ..."
10046040-97 = ""
10046040-99 = ""
10046040-100 = "งั้นก็ช่วยไม่ได้สินะคะ ถ้าคุณมิกะขออย่างนั้น ฉันก็จะจับตาดูสถานการณ์ให้ก่อนค่ะ"
10046040-101 = "แต่ถ้าฉันเห็นว่ามันอันตรายแม้แต่นิดเดียว ฉันจะเข้าไปแทรกแซงโดยไม่ลังเลเลยค่ะ"
10046040-102 = "อื้อ เท่านั้นก็เพียงพอแล้วละ! ขอบใจนะ ฮาสุมิจัง!"
10046040-105 = ""
10046040-106 = ""
10046040-107 = ""
10046040-108 = "เอ่อ... คือว่า... ฮารุนะจัง?"
10046040-109 = "เมื่อกี้ฉันน่าจะพูดจาไม่รอบคอบเกินไปหน่อยน่ะ ขอโทษนะ"
10046040-110 = "ฮุฮุ ไม่เป็นไรค่ะ ฉันรู้ดีว่าปรัชญาของพวกเรามักถูกคนอื่นเข้าใจผิดอยู่บ่อยๆ ค่ะ"
10046040-111 = "คุณไม่ใช่สมาชิกชมรมของเราด้วยซ้ำ แต่ก็ยังพยายามจะเข้าใจปรัชญาของพวกเรา ต้องบอกว่าน่าประทับใจมากเลยนะคะ"
10046040-112 = "ถ้างั้นก็... อืม... สรุปว่าเราเปลี่ยนอาหารรสเลิศเป็นเงินไม่ได้ใช่มั้ย?"
10046040-113 = "งั้นเอาแบบนี้มั้ยล่ะ? ถ้าให้วัตถุดิบทำบาร์บีคิวที่มีตอนนี้กับฉัน... ไว้อีก 2 วัน... ไม่สิ ในอีก 3 วัน ฉันจะหาวัตถุดิบบาร์บีคิวที่ดีกว่านี้มาให้!"
10046040-114 = "เป็นข้อเสนอที่น่าสนใจนะคะ"
10046040-115 = "คุณค่าของอาหารรสเลิศไม่อาจแปลงเป็นเงินได้... ก็เลยจะตอบแทนอาหารรสเลิศ ด้วยอาหารรสเลิศขั้นกว่า"
10046040-116 = "ฮุฮุฮุ นี่สินะสภาน้ำชาที่เขาร่ำลือกัน เป็นคนที่น่าสนุกพอตัวเลยนะคะ"
10046040-117 = "สะ... สรุปว่า?"
10046040-118 = "นั่นสินะคะ ถ้าคำนึงถึงความเอาใจใส่ของคุณแล้ว ฉันก็อยากตอบรับให้มากที่สุดเท่าที่จะทำได้"
10046040-119 = "แต่ยังไงก็ต้องขอปฏิเสธค่ะ"
10046040-120 = ""
10046040-122 = ""
10046040-123 = "หืม?! เมื่อกี้เราเจรจากันด้วยดีเลยไม่ใช่เหรอ?! ไหงเป็นงี้ได้ล่ะ?!"
10046040-124 = "อย่างที่ฉันบอกไปก่อนหน้านี้ว่าเรื่องนี้ก็ไม่ง่ายสำหรับฉันเหมือนกันค่ะ ก็ข้อเสนอของคุณมิกะไม่ต่าง#nจากการอภิปรายเกี่ยวกับอาหารรสเลิศนี่คะ"
10046040-125 = "แต่ว่าความรู้สึก ความประทับใจ ความสุขและความอิ่มเอมจากการได้กินอาหารอร่อยๆ จะอยู่ได้นานแค่ไหนกันคะ?"
10046040-126 = "หนึ่งอาทิตย์? หนึ่งวัน? หรือไม่กี่ชั่วโมง? ไม่หรอกค่ะ ที่จริงมันเกือบจะระเหยไปทันทีเลยค่ะ"
10046040-127 = "แต่เมื่อเทียบกันแล้ว วัตถุดิบที่เตรียมมาเพื่ออาหารรสเลิศนั้น รวมถึงเวลาที่ใช้ในการฝึกปรือฝีมือ เพื่อรังสรรค์อาหารนั้นมันไม่มีที่สิ้นสุดเลยค่ะ แล้วของพวกฉันก็ไม่อาจย้อนกลับมาได้ด้วย"
10046040-128 = "ฉันเลยให้นิยามของการกินอาหารรสเลิศว่า... เป็นการกระทำที่สูญเปล่าที่ละทิ้งคุณค่าถาวรนับไม่ถ้วน เพื่อประสบการณ์เพียงแค่ชั่วขณะ"
10046040-129 = "เพราะงั้นฉันก็เลยจะปฏิเสธข้อเสนอของคุณมิกะค่ะ"
10046040-130 = "ฉันกับสมาชิกชมรมตัดสินใจว่าจะกินบาร์บีคิวกันตอนนี้เลย นี่คือเหตุผลที่เพียงพอที่จะปฏิเสธแล้วค่ะ"
10046040-131 = ""
10046040-133 = ""
10046040-135 = ""
10046040-136 = ""
10046040-137 = "อ่า... หมายความว่าอะไรเนี่ย? รู้สึกเหมือนมีเซอาจัง 2 คนเลย"
10046040-138 = ""
10046040-140 = ""
10046040-141 = "สรุปว่าคุยกันดีๆ ไม่ได้ใช่มั้ยคะ? คุณมิกะ จากนี้ให้พวกฉันรับผิดชอบเถอะค่ะ"
10046040-142 = "ฮาสุมิจัง?!"
10046040-143 = "อย่างที่ฉันบอกไปเมื่อกี้ว่าถ้าจะสู้กับเกเฮนน่า เราสู้ด้วย 'สามัญสำนึก' ไม่ได้ค่ะ"
10046040-144 = "กับชมรมชิมอาหารยิ่งแล้วใหญ่ แม้แต่การสนทนาก็ถือว่าเปลืองน้ำลายค่ะ"
10046040-145 = ""
10046040-148 = ""
10046040-149 = "โอ้โห ใครไปปล่อยข่าวลือของพวกเราไว้ขนาดนั้นคะเนี่ย~"
10046040-150 = "เดี๋ยวก่อน! เมื่อกี้พูดแรงไปหรือเปล่า?!"
10046040-152 = "ถ้าดูจากสารพันปัญหาที่พวกคุณไปก่อไว้ ก็ควรจะขอบคุณฉันด้วยซ้ำนะคะที่ฉันไม่จับกุมพวกคุณเอา#nเสียตั้งแต่ตอนนี้เลย!"
10046040-153 = "ฉันจะไม่ประนีประนอมกับพวกคุณให้เสียเวลาค่ะ!"
10046040-155 = "ตายจริง ฉันต่างหากล่ะคะที่อยากพูดประโยคนั้น"
10046040-156 = "เส้นทางแห่งการชิมอาหารรสเลิศไม่ใช่เส้นทางแห่งการประนีประนอมหรอกค่ะ แล้วบาร์บีคิวเซ็ตนี้ ก็มีไว้เพื่อการค้นคว้าของชมรมชิมอาหารด้วย"
10046040-157 = "แบบนี้ยิ่งเข้าใจง่ายหน่อยนะคะ อิจิกะ!"
10046040-158 = ""
10046040-160 = ""
10046040-161 = "ค่ะ!"
10046040-163 = "ดะ... เดี๋ยวก่อน! ทุกคน! ใจเย็นๆ กันก่อนนะ!"
10046040-165 = "คุณมิกะ คุณครู ไม่ต้องกังวลค่ะ ฉันจะตอบแทนราคาให้อย่างสาสมเลยค่ะ"
10046040-166 = "แค่เปลี่ยนวิธีเจรจาจากการใช้คำพูดเป็นการใช้กระสุนปืนก็เท่านั้นค่ะ"
10046040-167 = "กลายเป็นแบบนี้ไปเสียได้นะคะ แหะๆ"
10046040-168 = ""
10046040-170 = ""
10046040-172 = "[ns7] \"อ่า... สุดท้ายก็เป็นอย่างนี้เหรอ?\"\n[ns8] \"กลายเป็นเรื่องโกลาหล★ ขึ้นมาเลย...\""
10046040-173 = ""
10046040-174 = ""
10046040-177 = ""
10046040-180 = "เดี๋ยวก่อนค่ะ"
10046040-181 = ""
10046040-183 = ""
10046040-184 = ""
10046040-186 = ""
10046040-187 = "ก่อนเราจะสู้กัน ฉันขอถามอะไรสักอย่างได้มั้ยคะ?"
10046040-188 = "คุณมิกะ"
10046040-189 = ""
10046040-191 = ""
10046040-192 = "หืม? ถามฉันเหรอ?"
10046040-193 = "ใช่ค่ะ ทำไมคุณมิกะถึงยึดมั่นถือมั่นกับบาร์บีคิวจังเลยล่ะคะ?"
10046040-194 = "นี่อาจฟังดูหยาบคายก็ได้ แต่คุณมิกะดูไม่ใช่คนที่เดินทางสายอาหารรสเลิศเหมือนกับพวกฉัน"
10046040-195 = "ฉันก็เลยสงสัยว่ามีเหตุผลอะไรหรือเปล่าที่จะต้องได้วัตถุดิบบาร์บีคิวไปในตอนนี้เลยน่ะค่ะ"
10046040-196 = ""
10046040-198 = ""
10046040-199 = "ระ... เรื่องนั้น..."
10046040-200 = ""
10046040-202 = ""
10046040-204 = ""
10046040-205 = "ฉันมีเพื่อนขี้กังวลอยู่คนหนึ่งน่ะ"
10046040-206 = "ถ้ามีอะไรผิดเพี้ยนไปจากแผนการที่วางไว้ เพื่อนคนนั้นก็จะกระสับกระส่ายจนทนไม่ได้"
10046040-207 = "อย่างเช่น กลางวันนี้เราตั้งใจไว้ว่าจะกินบาร์บีคิวกัน แต่ถ้าแผนการนั้นล่มขึ้นมา ตัวเองก็จะเก็บไปคิดว่าเกิดปัญหาอะไรขึ้นจนไม่ได้พักผ่อน..."
10046040-208 = "นิสัยน่ารำคาญมากเลยว่ามั้ยล่ะ?"
10046040-209 = "เธอคนนั้นเป็นเพื่อนคนสำคัญมากๆ ของฉัน แต่ฉันกลับช่วยอะไรไม่ได้เลย..."
10046040-210 = "อย่าว่าแต่ช่วยเลย ฉันเอาแต่สร้างปัญหาให้มากกว่าด้วยซ้ำ"
10046040-211 = "วันนี้ฉันก็เลยอยากให้เพื่อนคนนั้นลืมทุกอย่างแล้วได้พักผ่อนจริงๆ น่ะ"
10046040-212 = "แม้ว่ามันจะไม่ราบรื่นก็เถอะ..."
10046040-213 = ""
10046040-215 = ""
10046040-217 = "อย่างนี้นี่เอง... มีเหตุผลแบบนี้อยู่เบื้องหลังสินะคะ"
10046040-218 = "อืม... แต่ถึงจะเป็นอย่างนั้น แต่ถ้าเราตกลงกันได้..."
10046040-219 = ""
10046040-221 = ""
10046040-222 = ""
10046040-223 = "นี่ๆ ฮารุนะ..."
10046040-224 = "วันนี้เราให้บาร์บีคิวไปไม่ได้เหรอ?"
10046040-225 = "คุณอิซุมิ...?"
10046040-226 = "ถึงฉันจะพูดไม่เก่งเท่าฮารุนะ แต่ของอร่อยๆ น่ะ มันจะยิ่งอร่อยถ้าได้กินด้วยกันไม่ใช่เหรอ?"
10046040-227 = "ถ้าเราเมินเฉยต่อเรื่องนี้แล้วมากินบาร์บีคิวกัน อืม... ฉันว่ามันไม่น่าจะอร่อยเท่าไรนะ"
10046040-229 = "ฉันก็เห็นด้วย"
10046040-230 = "คุณจุนโกะก็ด้วยเหรอ...?"
10046040-231 = "จะว่ายังไงดีล่ะ พอได้ฟังเหตุผลของทางนั้นแล้ว ฉันก็ไม่รู้สึกว่านี่เป็นเรื่องของคนอื่นน่ะ"
10046040-232 = "และต่อให้พวกเราไม่ได้กินบาร์บีคิวในตอนนี้ ก็ไม่ได้เป็นปัญหาใหญ่อะไรนี่?"
10046040-233 = "ฉันเพิ่งจะรู้ด้วยซ้ำว่าของที่เรามีคือบาร์บีคิว..."
10046040-234 = "ทั้ง 2 คนคิดแบบนี้กันสินะคะ แล้วคุณอาคาริ..."
10046040-235 = ""
10046040-237 = ""
10046040-238 = "ไม่สิ ฉันก็ไม่น่าถามนะคะ คำตอบน่ะชัดเจนอยู่แล้ว"
10046040-239 = ""
10046040-241 = ""
10046040-243 = "ฮุฮุฮุ ฮารุนะรู้จักฉันดีอย่างที่คิดไว้เลยนะคะ~"
10046040-244 = "ในเมื่อสมาชิกชมรมคิดเห็นอย่างนั้น..."
10046040-245 = "ก็ได้ค่ะ ฉันจะให้วัตถุดิบทำบาร์บีคิวค่ะ"
10046040-246 = ""
10046040-249 = ""
10046040-250 = "จริงเหรอ?!"
10046040-251 = "เอาจริงดิ?!"
10046040-252 = "[s] \"ว่าไงนะ?!\""
10046040-253 = ""
10046040-255 = ""
10046040-256 = "ทะ... ทุกคน? คิดว่าฉันเป็นคนยังไงกันคะ?"
10046040-257 = "อ่า... ให้พูดตรงๆ เหรอ? หรือว่าให้พูดแบบรักษาน้ำใจกันบ้าง?"
10046040-258 = "แค่ถามมาแบบนั้นฉันก็เจ็บปวดแล้วค่ะ..."
10046040-259 = ""
10046040-261 = ""
10046040-262 = "แต่แน่นอนว่าฉันไม่ได้จะให้ฟรีๆ หรอกนะคะ คุณต้องทำตามเงื่อนไขที่ให้ไว้ค่ะ"
10046040-263 = "เมื่อกี้สัญญาว่าจะหาวัตถุดิบบาร์บีคิวที่คุณภาพดีกว่ามาให้ภายใน 3 วันใช่มั้ยล่ะคะ?"
10046040-264 = "อื้อ! ขอบใจนะ! แล้วฉันจะรักษาสัญญานะ!"
10046040-265 = "นี่ค่ะ วัตถุดิบบาร์บีคิวที่ว่า"
10046040-266 = ""
10046040-268 = ""
10046040-269 = ""
10046040-270 = ""
10046040-271 = "สำเร็จแล้ว คุณครู! ตอนนี้ก็แค่รีบกลับไปแล้วเตรียมย่าง..."
10046040-272 = ""
10046040-274 = ""
10046040-275 = ""
10046040-276 = "......"
10046040-277 = ""
10046040-279 = ""
10046040-280 = "หืม?"
10046040-281 = "[s9] \"มีอะไรเหรอ มิกะ?\"\n[s10] \"วัตถุดิบมีปัญหาอะไรเหรอ?\""
10046040-284 = "เปล่าหรอก ก็แค่กล่องกับของในกล่องนี้... เป็นวัตถุดิบทำบาร์บีคิวที่ฉันเตรียมมาตั้งแต่แรกเลยนี่นา?"
10046040-285 = ""
10046040-287 = ""
10046040-289 = ""
10046040-290 = "โอ้"
10046040-291 = "เอาแล้ว~ เป็นเรื่องแล้วมั้ยล่ะ"
10046040-292 = ""
10046040-294 = ""
10046040-296 = "สรุปว่าผู้ต้องสงสัยที่โจมตีรถบรรทุกส่งวัตถุดิบอาหารก็คือชมรมชิมอาหารงั้นเหรอ...?"
10046040-297 = ""
10046040-299 = ""
10046040-301 = "การเจรจาเมื่อกี้เป็นโมฆะค่ะ!"
10046040-302 = "คุณมิกะ!! เพียงแค่คุณออกคำสั่งตอนนี้ ฉันจะไปจับผู้ก่อการร้ายพวกนั้นมาให้เกลี้ยงเลยค่ะ!!"
10046040-303 = "......"
10046040-304 = ""
10046040-306 = ""
10046040-307 = ""
10046040-308 = "(ไม่ได้การแล้วละ แบบนี้คงห้ามไม่ได้แล้ว)"
10046040-309 = "(ถึงจะดูเหมือนยอมผ่อนปรนให้อยู่ตลอด แต่เดิมทีแล้วคุณมิกะก็มีชื่อว่าเป็นเหยี่ยวที่นิยมความรุนแรง)"
10046040-310 = "(แบบนี้คงหลีกเลี่ยงการปะทะไม่ได้แล้วละ อืม...)"
10046040-311 = "(เตรียมคิดไว้ดีกว่าว่าจะไปรายงานคุณนางิสะยังไงดี)"
10046040-312 = ""
10046040-316 = "โล่งอกไปทีนะ... นึกว่าจะหายไปแล้วเสียอีก"
10046040-317 = ""
10046040-319 = ""
10046040-320 = ""
10046040-321 = ""
10046040-322 = ""
10046040-323 = "ขอโทษนะ ฮาสุมิจัง ครั้งนี้ถือว่าเห็นแก่ฉันเถอะนะ ฉันขอร้องละ"
10046040-324 = "คะ...?"
10046040-325 = "ฉันรู้ว่ามันน่าอึดอัดใจและรู้สึกไม่ยุติธรรม แต่ฉันก็อยากกลับไปก่อนจะสายไปกว่านี้น่ะ"
10046040-326 = "ฉันไม่เป็นไรหรอกค่ะ... แต่คุณมิกะโอเคกับผลลัพธ์แบบนี้เหรอคะ?"
10046040-327 = "อื้อ ตอนนี้ฉันมีเรื่องอื่นที่สำคัญกว่านี่นา"
10046040-328 = ""
10046040-330 = ""
10046040-332 = "......"
10046040-334 = "ฉัน... ฉันก็ไม่แน่ใจเหมือนกัน แต่นี่พวกเราเพิ่งรอดตายกันมาใช่มั้ย?!"
10046040-335 = "ฉัน... ฉันรู้สึกเหมือนตอนเจอประธานคณะกรรมการวินัยเลยละ"
10046040-337 = "ฮุฮุ.. ฮุฮุฮุ..."
10046040-338 = "ฉันไม่ได้ตั้งใจให้เป็นแบบนี้ แต่ก็รู้สึกเหมือนโชคเข้าข้างเลยนะคะ"
10046040-339 = "ความดีที่ฉันเคยทำไว้มันเริ่มส่งผลแล้วใช่มั้ยคะเนี่ย?"
10046040-341 = "พูดออกมาได้นะ..."
10046040-343 = "แหะๆ... นี่สินะคะที่เรียกกันว่ามิตรภาพของเด็กผู้หญิง~★"
10046040-346 = "มาช้าเกินไปหรือเปล่านะ?!"
10046040-347 = "อืม... เราพยายามรีบกันแล้วแท้ๆ แต่กว่าจะมาถึงก็ปาไปบ่าย 3 โมงแล้วสินะคะ"
10046040-348 = "พวกฉันจะเตรียมของให้ก่อนค่ะ คุณมิกะไปตามคนอื่นในสภาน้ำชาเถอะค่ะ..."
10046040-349 = "อะ... อื้อ! งั้นฉันรบกวนด้วยนะ!"
10046040-350 = ""
10046040-358 = "อึกกก...!"
10046040-359 = "นางิสะ เกร็งไหล่มากเกินไปแล้วค่ะ"
10046040-360 = "ลองผ่อนคลายให้มากกว่านี้หน่อยค่ะ... อืม ให้อธิบายการเคลื่อนไหวด้วยคำพูดนี่เป็นเรื่องยากจังเลย#nนะคะ"
10046040-361 = "เอาละ ฉันจะเอานิ้วไปกดให้ ลองคลายแรงตรงนั้นดูนะคะ..."
10046040-362 = ""
10046040-366 = "เจ็บจัง...?!"
10046040-367 = ""
10046040-370 = "คะ... คิดจะเอาให้ตายเลยเหรอคะ?!"
10046040-371 = "แค่ฉันเอานิ้วไปจิ้มก็ตายได้แล้วเหรอคะ?"
10046040-372 = ""
10046040-375 = ""
10046040-376 = "อ๊ะ คุณครู มิกะด้วย"
10046040-377 = "[s11] \"ทำอะไรกันอยู่เหรอ?\"\n[s12] \"ท่าทางกำลังสนุกกันอยู่เลยนะ?\""
10046040-380 = "พวกฉันเล่นโยคะกันอยู่ค่ะ นี่เป็นงานอดิเรกเล็กๆ น้อยๆ ของฉันด้วย"
10046040-381 = "ค่ะ... พอดีคุณเซอาแนะนำให้ลองเล่นดู..."
10046040-382 = "ฉันไม่คิดเลยนะคะว่านางิสะจะตั้งใจฟังและทำตามอย่างว่าง่ายแบบนี้น่ะ"
10046040-383 = "อ๊ะ จริงสิ มิกะ เตรียมมื้อกลางวันราบรื่นดีหรือเปล่าคะ? ฉันเหมือนได้กลิ่นปิ้งย่างมาจากที่ไหนเลย"
10046040-384 = ""
10046040-386 = ""
10046040-387 = "อ่า เรื่องนั้นน่ะ~ พอดีมันใช้เวลานิดหน่อย ก็เลยเพิ่งได้มาย่างเอาตอนนี้น่ะ"
10046040-388 = "ทุกคนน่าจะหิวกันแล้ว ขอโทษที่ทำให้รอกันนะ~★"
10046040-389 = "เห็นว่ามื้อกลางวันคือบาร์บีคิวใช่มั้ยคะ? ฉันว่าบาร์บีคิวไม่น่าจะใช้เวลาเตรียมนานขนาดนั้นนะ..."
10046040-390 = ""
10046040-392 = ""
10046040-393 = "อ๊ะ จริงสิ"
10046040-394 = ""
10046040-397 = ""
10046040-398 = ""
10046040-399 = "ฉันฝากเตรียมน้ำชาด้วยได้มั้ยคะ?"
10046040-400 = "หืม...?"
10046040-401 = "ใช่ค่ะ ตอนนี้มื้อกลางวันของเราก็ล่าช้าแล้ว ฉันว่ากว่าจะกินเสร็จก็น่าจะเป็นเวลาน้ำชาพอดีน่ะค่ะ"
10046040-402 = "เอะ... เอ๋?"
10046040-403 = ""
10046040-405 = ""
10046040-407 = "รบกวนเตรียมชาให้ด้วยได้มั้ยคะ?"
10046040-408 = ""
10046040-410 = ""
10046040-411 = ""
