[translation]
1004503-1 = "#title;산지 직송의 신선한 재료"
1004503-2 = "#na;(호시노의 부탁을 받고 해변으로 향했다.)"
1004503-7 = "#na;???;어어, 선생. 여기야 여기~."
1004503-8 = "[s] \"호시노?\""
1004503-12 = "3;호시노 수영복ND;15\n#3;a\n#wait;1500"
1004503-13 = "3;호시노 수영복ND;17;부탁한 대로 혼자 왔군, 고마워. 선생.\n#3;em;[음표]"
1004503-14 = "3;호시노 수영복ND;02;그럴 리야 없다고 생각하긴 했지만, 혹시라도 세리카 쨩이나 아야네 쨩이 알면 안 되거든."
1004503-15 = "3;호시노 수영복ND;01;응? 무슨 일이냐고?\n#3;em;[반응]"
1004503-16 = "3;호시노 수영복ND;16;아아, 뭐-. 그리 대단한 건 아니고……."
1004503-17 = "3;호시노 수영복ND;15;지친 몸을 이끌고 구석에서 조금 쉬고 있었더니, 두 사람이 찾아와서 잔소리를……."
1004503-18 = "#st;[0,0];instant;1;"
1004503-20 = "3;호시노 수영복ND;15\n#3;em;…\n#wait;2500"
1004503-21 = "3;호시노 수영복ND;99;아무튼 그래서 해가 지기 전까지, 다 같이 먹을 해산물을 좀 채취해야 하는데 말이지……."
1004503-22 = "3;호시노 수영복ND;01;……응? 결국 지원군으로 부른 거냐고?"
1004503-23 = "3;호시노 수영복ND;03;에헤헤. 정답.\n#3;em;[반짝]\n#3;greeting"
1004503-24 = "3;호시노 수영복ND;15;다른 애들에게 비밀로 해달라고 한 건, 선생이 오는 걸 막을 게 뻔했기 때문이야."
1004503-25 = "3;호시노 수영복ND;99;'가끔은 혼자서 해주세요, 제발!'이라고 하면서 말이야……."
1004503-26 = "#st;[0,0];instant;1;"
1004503-28 = "3;호시노 수영복ND;01\n#3;d\n#wait;1000"
1004503-29 = "3;호시노 수영복ND;01\n#3;a\n#3;closeup\n#wait;1000"
1004503-31 = "3;호시노 수영복ND;15;어쨌든 선생도 여기까지 왔으니, 불쌍한 아저씨를 두고 혼자 돌아가지는 않겠지?\n#3;em;[반응]\n#3;closeup"
1004503-32 = "3;호시노 수영복ND;17;선생이잖아? 곤경에 처한 학생을 두고 갈 생각은 아니잖아? 응?\n#3;closeup"
1004503-33 = "[s1] \"그렇게 나오시겠다 이거지.\"\n[s2] \"뭐 그럼 나도 밥값 좀 해볼까.\""
1004503-34 = "3;호시노 수영복ND;03;으헤-. 역시 선생이야. 그럼 잘 부탁한다고.\n#3;em;[음표]\n#3;hophop\n#3;closeup"
1004503-35 = "3;호시노 수영복ND;03;으헤-. 역시 선생이야. 그럼 잘 부탁한다고.\n#3;em;[음표]\n#3;hophop\n#3;closeup"
1004503-36 = "3;호시노 수영복ND;15;이왕 선생이랑 하는 거니…….\n#3;closeup"
1004503-37 = "3;호시노 수영복ND;20;나도 아주 놀지는 않을 거고.\n#3;em;…\n#3;closeup"
1004503-40 = "#na;(이후 한동안 호시노와 함께 바닷가에서 먹을 것들을 채취했다.)"
1004503-46 = "3;호시노 수영복ND;04;우와……. 이게 다 뭐야……?\n#3;em;[땀]\n#3;stiff\n#3;a"
1004503-47 = "3;호시노 수영복ND;00;사람이 없는 곳이라서 그런지 정말 엄청나네. 물보다 해산물이 더 많은 수준이잖아."
1004503-48 = "#st;[0,0];instant;1;"
1004503-50 = "3;호시노 수영복ND;01\n#3;m2\n#wait;1200"
1004503-51 = "3;호시노 수영복ND;01\n#3;greeting\n#wait;1500"
1004503-52 = "3;호시노 수영복ND;00;선생, 이거 보여? 이렇게 큰 전복은 태어나서 처음 보는데? 이게 이렇게까지 클 수 있는 거였어?"
1004503-53 = "3;호시노 수영복ND;03;이것 봐, 선생. 벌써 소쿠리가 다 차 버렸어. 아직 여기 한 바퀴 둘러보지도 못했는데 말이지.\n#3;m4\n#3;hophop\n#3;em;[반짝]"
1004503-54 = "3;호시노 수영복ND;02;굉장하네……. 바다란 볼 때마다 놀랍구만.\n#3;stiff"
1004503-55 = "[s3] \"평소보다 활력이 넘치네.\"\n[s4] \"묘하게 들떠 있는걸. 호시노.\""
1004503-56 = "#st;[0,0];instant;1;"
1004503-57 = "#st;[0,0];instant;1;"
1004503-59 = "3;호시노 수영복ND;08\n#3;shake\n#3;em;[?!]\n#wait;2000"
1004503-60 = "3;호시노 수영복ND;10\n#3;em;…\n#wait;2500"
1004503-61 = "3;호시노 수영복ND;11;……흠……."
1004503-62 = "3;호시노 수영복ND;15;……그런가?"
1004503-63 = "3;호시노 수영복ND;02;으헤……. 뭐, 그런 걸지도. 선생이 말한 대로일지도 모르지.\n#3;em;[음표]\n#3;m3"
1004503-64 = "3;호시노 수영복ND;17;대충 여기선 '여름이니까. 바다니까' 같은 이유로 변명거리를 대 놓고……."
1004503-65 = "3;호시노 수영복ND;15;응? 왜 굳이 그런 식으로 계속 이유를 대냐고?\n#3;em;[?]"
1004503-66 = "3;호시노 수영복ND;02;에이, 선생도 알잖아. 이렇게 하지 않으면, 앞으로 계속 이런 모습을 보여야 한다고."
1004503-67 = "3;호시노 수영복ND;17;한정적인 경우라고 정해두지 않으면 여러모로 피곤해진단 말이야."
1004503-68 = "3;호시노 수영복ND;99;……물론 반대로 말하면."
1004503-69 = "3;호시노 수영복ND;15;그런 한정적인 상황이라고 정했으니까, 평소에는 못 할 행동들도 할 수 있는 거고 말이지.\n#3;em;…"
1004503-70 = "#st;[0,0];instant;1;"
1004503-72 = "3;호시노 수영복ND;15\n#3;d\n#wait;1000"
1004503-73 = "3;호시노 수영복ND;15\n#3;a\n#3;closeup\n#wait;1000"
1004503-75 = "3;호시노 수영복ND;17;……바로 지금처럼. 선생이랑 같이하는 지금 이런 행동들.\n#3;em;[반응]\n#3;closeup"
1004503-76 = "3;호시노 수영복ND;15;꽤 재밌다고-. 즐겁다고 느낀다고-.\n#3;closeup"
1004503-77 = "3;호시노 수영복ND;16;그치만 여름이니까, 무인도의 바다에서 다른 누구도 없는 곳이니까 하는 말이야. 알겠지?\n#3;closeup"
1004503-78 = "3;호시노 수영복ND;02;그리고 선생이니까 하는 말이야. 다른 사람들의 귀에는 들어가지 않게 해줘-.\n#3;closeup"
1004503-79 = "3;호시노 수영복ND;15;뭐, 어련히 알아서 지켜줄 거라 생각하고는 있지만 말이지.\n#3;closeup"
1004503-80 = "3;호시노 수영복ND;20;……그렇지?\n#3;em;[?]\n#3;closeup"
1004503-81 = "[s5] \"물론이지.\"\n[s6] \"항상 '공범'이니까 말이야.\""
1004503-82 = "#st;[0,0];instant;1;"
1004503-83 = "#st;[0,0];instant;1;"
1004503-85 = "3;호시노 수영복ND;10\n#3;em;…\n#wait;2500\n#3;closeup"
1004503-86 = "3;호시노 수영복ND;99\n#wait;1500\n#3;closeup"
1004503-87 = "3;호시노 수영복ND;02;……에헤헤.\n#3;em;[///]\n#3;stiff\n#3;closeup"
