[translation]
10046280-2 = ""
10046280-3 = "ระ... รุ่นพี่อิจิกะ!"
10046280-4 = "เอ๋? มีธุระอะไรที่นี่คะ? หรือว่ากำลังหลงทางอยู่..."
10046280-5 = "มะ... ไม่ใช่อย่างนั้นหรอกค่ะ!"
10046280-6 = "พอดีฉันได้ยินว่ารุ่นพี่อิจิกะออกมาลาดตระเวนอยู่คนเดียว..."
10046280-7 = "อ่า... อ่า อย่างนั้นสินะ"
10046280-8 = "ฉันก็เลยรวบรวมความกล้าแล้วออกมาหา..."
10046280-9 = "แต่ว่าฉันมารบกวนหรือเปล่าคะ...?"
10046280-10 = "รุ่นพี่อิจิกะน่าจะไม่อยากได้ความช่วยเหลือจากฉันแท้ๆ..."
10046280-11 = "......"
10046280-12 = "เอ่อ... ช่วยอะไรฉันหน่อยได้มั้ยคะ?"
10046280-13 = "คะ?!"
10046280-14 = "ฉันได้รับมอบหมายงานนี้มาก็จริง แต่ตอนนี้ฉันเริ่มทำคนเดียวไม่ไหวแล้วน่ะค่ะ"
10046280-15 = "ขอโทษที่ขอร้องระหว่างมาพักผ่อนนะคะ แต่ว่าช่วยลาดตระเวนกับฉันสักเดี๋ยวได้มั้ยคะ?"
10046280-16 = "มะ... ไม่ต้องขอโทษเลยค่ะ!"
10046280-17 = "ฮุฮุ ขอบคุณค่ะ ถ้างั้นก็ไปกันเลยมั้ยคะ?"
10046280-18 = "ค่ะ ได้ค่ะ!"
