[translation]
10047100-1 = "Episode 10;Wish-Fulfilling Magic"
10047100-3 = "There's a saying, isn't there? \"On Doom's Day...the bell sings alone.\""
10047100-4 = "You really believe that? It's just a schoolyard urban legend!"
10047100-5 = "Urban legend or not, it's really ringing! It's so ominous..."
10047100-6 = ""
10047100-8 = ""
10047100-9 = "This...is not something ominous."
10047100-10 = "This is the sound of a girl's true heart. It is the sound of someone cherishing us all."
10047100-11 = "It is the sound of respectful disagreement, the ring of anxiety and regret..."
10047100-12 = "And...the sound of guilt and self-blame overcoming the weight of helplessness."
10047100-13 = "She tells her true story in her own way."
10047100-14 = "Heh, yes. We hear you...the beat of your beautiful, worried heart ringing above us."
10047100-16 = "Top of the Nameless Bell Tower"
10047100-18 = "Shyaah! What am I even doing here?!"
10047100-19 = "How could they be so stupid? How could they get caught?"
10047100-20 = "Now that it's come to this..."
10047100-21 = "You better finish the job, you hear me?! You idiot seniors!"
10047100-24 = "Caw! Cacaw!!!"
10047100-25 = "Eek! There's a murder of crows, too?!"
10047100-26 = ""
10047100-28 = ""
10047100-29 = "They're spooked... Let's take our chance."
10047100-30 = ""
10047100-32 = ""
10047100-33 = ""
10047100-35 = ""
10047100-37 = "Master! Take my hand!"
10047100-38 = "Everyone, it's time to complete the spell! The Wish-Fulfilling Magic is upon us!"
