[translation]
10041050-1 = "ตอนที่ 5;ความรู้สึกด้านลบ"
10041050-4 = "1 ชั่วโมงก่อน..."
10041050-7 = "ณ ที่ซ่อนตัวของริโอะ ทันทีที่เซอาออกไป"
10041050-8 = ""
10041050-10 = ""
10041050-11 = ""
10041050-12 = "เนรุ..."
10041050-13 = ""
10041050-16 = ""
10041050-17 = "มีอะไร...?"
10041050-18 = "ฉันอยากถามอะไรอย่างหนึ่ง"
10041050-19 = "แต่มันเป็นคำถามส่วนตัวที่ไม่เกี่ยวกับงาน ก็เลยกังวลใจน่ะ"
10041050-20 = ""
10041050-22 = ""
10041050-23 = "อะไรเหรอ...????"
10041050-24 = "ฉันอิงจากข้อมูลที่ผ่านมาของเธอ เพื่อคาดเดาว่าเธอจะมีท่าทียังไงถ้าฉันถามคำถามนี้ แต่ก็ไม่แน่ใจหรอกว่าจะถูกต้องหรือเปล่า"
10041050-25 = "ก็ถามอยู่นี่ไงว่าจะถามอะไร"
10041050-26 = "สมมติฉันถามไป แล้วเธอ..."
10041050-27 = ""
10041050-29 = ""
10041050-30 = ""
10041050-33 = ""
10041050-35 = "โธ่เอ๊ย! ให้ตายเถอะ!"
10041050-36 = "เธอนี่นะ จริงๆ เลย!! เฮ้อ!!"
10041050-37 = "ถ้าพูดอะไรแบบนั้นอีกที ฉันจะไม่อยู่เฉยๆ แล้วนะ มีอะไรก็บอกมาเลย จะถามอะไรก็ถามมาให้มันจบๆ เถอะน่า!"
10041050-38 = ""
10041050-40 = ""
10041050-42 = ""
10041050-43 = "เข้าใจแล้ว..."
10041050-44 = "ฉันกังวลเกี่ยวกับยูริโซโนะ เซอา"
10041050-45 = "ยัยสภาน้ำชาน่ะเหรอ? ทำไมล่ะ เพราะดูไม่มั่นคงทางอารมณ์หรือไง? หรือกลัวว่าจะสร้างปัญหาอะไร#nขึ้นมา?"
10041050-46 = "เปล่าหรอก ฉันไม่ได้คิดอย่างนั้น ความไว้วางใจของฉันที่มีต่อเซอายังเหมือนเดิม"
10041050-47 = "เรื่องที่ฉันกังวลมันเป็นเรื่องที่ต่างออกไปจากนั้นน่ะ มันเกี่ยวกับเรื่องที่ฉันพูดกับเซอาไปเมื่อก่อนหน้านี้"
10041050-48 = "ก่อนหน้านี้เธอพูดอะไรไปนะ...?"
10041050-49 = ""
10041050-51 = ""
10041050-52 = "อ๋อ... ที่บ่นไปน่ะเหรอ?"
10041050-53 = "ตอนแรกเหมือนว่าเซอาจะยอมรับมันแต่โดยดี ทั้งเข้าใจและขอโทษกลับด้วย"
10041050-54 = "แต่สิ่งที่เราแสดงออกกับผู้อื่นมันอาจจะแตกต่างกับความรู้สึกจริงๆ ก็ได้ ฉันเองพอได้เจอเรื่องนู่นนี่มา ก็รู้สึกอย่างนี้น่ะ"
10041050-55 = "และในแง่นั้น ฉันก็เลยกังวลว่า..."
10041050-56 = ""
10041050-58 = ""
10041050-59 = "คำที่ฉันพูดไปจะทำให้เซอาเสียความรู้สึก หรือทำให้เซอามองฉันในทางที่ไม่ดี... หรือเปล่าน่ะ"
10041050-60 = ""
10041050-62 = ""
10041050-63 = "ว่าไงนะ...?"
10041050-64 = "สรุปเลยก็คือ ฉันสงสัยว่ายูริโซโนะ เซอาจะมีความคิดในแง่ลบกับฉันหรือเปล่า... แบบนี้น่ะ"
10041050-65 = "ถ้ายังไม่เข้าใจ ฉันจะเปลี่ยนคำอธิบายให้ นี่คือปัญหาเรื่องจิตใจและความรู้สึกภายใน..."
10041050-66 = "ไม่ๆ ฉันไม่ได้ถามเพราะไม่เข้าใจหรอก"
10041050-67 = "สรุปประเด็นก็คือ เธอพูดจาไม่ดีใส่เซอา แล้วมากลัวว่าถ้าเซอาเกลียดเธอขึ้นมาจะทำยังไงดีน่ะเหรอ?"
10041050-68 = "ฉันไม่เคยพูดสรุปขนาดนั้นนะ..."
10041050-69 = "แล้วมันจะเป็นอย่างอื่นไปได้เหรอ? มันก็ตามที่ฉันพูดนั่นละ"
10041050-70 = "แต่ว่า... แต่ในสถานการณ์นั้น ฉันก็ไม่มีทางเลือกอื่นนอกจากต้องพูดแบบนั้นออกไป"
10041050-71 = "นี่เป็นปัญหาใหญ่ที่ส่งผลต่อโรงเรียน ฉันจึงต้องให้ความสำคัญกับเรื่องนั้นมากกว่าความรู้สึกส่วนตัว"
10041050-72 = "ฉันต้องเกลี้ยกล่อมให้เซอาเข้าใจ และต้องพยายามยกเหตุผลที่หนักแน่นที่สุดเท่าที่จะทำได้"
10041050-73 = "แต่ถึงอย่างนั้น ถ้าหากว่าเรื่องนั้นทำให้เซอาคิดเป็นปฏิปักษ์ต่อฉัน หรือมองฉันในแง่ลบขึ้นมา..."
10041050-74 = "ถ้าเป็นอย่างนั้น ฉัน... ฉันคง..."
10041050-75 = ""
10041050-78 = ""
10041050-79 = "โอ๊ย! น่าอึดอัดชะมัด!!"
10041050-80 = "อึดอัดๆๆ! เกิดมายังไม่เคยอึดอัดอะไรขนาดนี้มาก่อนเลย!!"
10041050-81 = "ไร้สาระน่า! ยัยนั่นไม่มีทางเอาเรื่องนั้นมาคิดมากแล้วบูดบึ้งกับเธอหรอก!"
10041050-82 = "แค่ดูก็รู้แล้วว่าไม่ได้เป็นอย่างนั้นน่ะ"
10041050-83 = "แล้วไหนเธอบอกว่าที่พูดแบบนั้นไปเพราะจำเป็นยังไงล่ะ? ถ้างั้นมันก็ช่วยไม่ได้อยู่แล้วไม่ใช่เหรอ?"
10041050-84 = ""
10041050-87 = ""
10041050-88 = "ตอนอยู่ต่อหน้าละกล้าพูดทุกอย่างเพื่อความถูกต้อง แต่พอพูดไปแล้วก็มากังวลอยู่คนเดียวว่า#n'แง~ ถ้าเค้าเกลียดฉันขึ้นมาล่ะจะทำยังไง~'"
10041050-89 = "เธอนี่มันจริงๆ เลย เป็นคนประเภทที่สร้างความน่ารำคาญระดับสิบเลยนะเนี่ย"
10041050-90 = "แล้วกับฉันล่ะ? ไม่สนใจฉันบ้างเหรอ? ไม่กังวลว่าฉันจะไม่ชอบหรือเกลียดเธอบ้างหรือไง?"
10041050-91 = "ทำไมที่ผ่านมาไม่เคยถามฉันแบบนั้นบ้างเลยล่ะ?"
10041050-92 = ""
10041050-94 = ""
10041050-96 = "มิคาโมะ เนรุ..."
10041050-97 = "ถ้ามีเรื่องแบบนั้นเกิดขึ้น ฉันไม่อยู่เฉยๆ หรอก แต่ข้อมูลมากมายที่ผ่านมาก็เป็นเครื่องพิสูจน์แล้ว"
10041050-98 = "ไม่ว่าฉันจะมีท่าทียังไง เธอก็ให้ความสำคัญกับความรู้สึกและการตัดสินใจของเธอก่อน เธอจึงไม่ทำอะไรที่แตกต่างไปจากความตั้งใจเดิม และไม่รู้สึกว่าต้องทำอย่างนั้นด้วย"
10041050-99 = "นี่เธอมองฉันว่าเป็นสิ่งมีชีวิตเซลล์เดียวหรือไง?"
10041050-100 = "ฉันไม่ได้หมายความในเชิงดูหมิ่นแบบนั้น..."
10041050-101 = ""
10041050-103 = ""
10041050-104 = "แต่ถ้านั่นเป็นการถามเพื่อความเข้าใจว่ามีส่วนที่คล้ายกันหรือเปล่า ก็ต้องบอกว่าใช่ จะว่าอย่างนั้นก็ได้"
10041050-105 = ""
10041050-107 = ""
10041050-109 = "เฮอะ! ตอบได้ดีเลยนะ งั้นก็ลองรับ 'ความรู้สึกแง่ลบ' ของฉันไปบ้างเป็นไง! ยัยคนน่าอึดอัด!!"
10041050-110 = ""
10041050-115 = "ดะ... เดี๋ยวก่อน...! ตอนนี้การค้นหาข้อมูลมัน...!"
10041050-116 = ""
10041050-122 = "พบบางอย่างจากระบบตรวจตรา...!!"
10041050-123 = "ฟะ... ฟิตเนสเซ็นเตอร์! ไปที่ฟิตเนสเซ็นเตอร์เดี๋ยวนี้เลย เนรุ!! นี่ไม่ใช่เวลาจะมามัวเอ้อระเหยอยู่อย่าง#nนี้แล้ว!!"
10041050-124 = "ก็แล้วใครมันจะไปรู้กันเล่า!!!"
