[translation]
1004003-1 = "Being Tall Isn't So Bad"
1004003-2 = "I arrived at the agreed-upon meeting spot right on time."
1004003-3 = "There were more people than I expected. While looking around, I found Tsukuyo among the crowd."
1004003-4 = "My intuition from twenty-seven years and four months of model scouting is telling me that you can be a star!"
1004003-5 = "You'll be the tallest top model in Kivotos!"
1004003-7 = "No! I-I want to be a ninja, not a model!"
1004003-8 = "A ninja? Haha! That's interesting."
1004003-9 = "We could probably work that angle!"
1004003-10 = "N-No... I...I meant a real ninja..."
1004003-11 = "*gasp* S-Sensei?!"
1004003-12 = "P-Please help!"
1004003-13 = "[s] \"Excuse me.\""
1004003-14 = ""
1004003-16 = ""
1004003-18 = "Oh."
1004003-27 = "Huh? W-Wait...! I'm not a bad person! I really see a lot of potential in you!"
1004003-28 = "You're a future superstar! Please, give me a chance!"
1004003-30 = "[ns1] \"Phew, we should be safe here.\"\n[ns2] \"Are you okay, Tsukuyo? Are you hurt anywhere?\""
1004003-31 = "I-I'm okay...but..."
1004003-32 = "I-I'm okay...but..."
1004003-33 = "Waaaah! *cry*"
1004003-34 = "I was so scared, Sensei!"
1004003-35 = "*sniffle* I know I stand out because of my height...but I wanna be left alone...!"
1004003-36 = "And my problems inconvenienced you...! S-Sorry...! *sob*"
1004003-37 = "[s] \"It wasn't an inconvenience at all.\""
1004003-38 = "*hiccup* R-Really?"
1004003-39 = "I'm happy to hear that...but...this always happens to me..."
1004003-40 = "I'm so tall...which makes me noticeable..."
1004003-41 = "S-So, a lot of strange people approach me...and I get sucked into weird situations..."
1004003-42 = "Last week, I ran into a Helmet Gangster while I was walking down the street..."
1004003-43 = "\"You're so tall. You'd look great in this helmet. Why don't you join us?\""
1004003-44 = "I-I was so surprised when they approached me...I ran away..."
1004003-45 = "I don't know what to do when people act like that."
1004003-46 = "[s3] \"That's how the Helmet Gangsters recruit people?\"\n[s4] \"I wouldn't know how to react to that either...\""
1004003-47 = "Right...? I just panicked..."
1004003-48 = "Right...? I just panicked..."
1004003-49 = "That's not the only problem my height causes!"
1004003-50 = "My very existence is an inconvenience..."
1004003-51 = "I block your view just standing next to you."
1004003-52 = "You could become unlucky like me...or lose your appetite... All because of me."
1004003-53 = "I'm sorry I'm so tall..."
1004003-54 = "[s5] \"(She has surprisingly low self-esteem...)\"\n[s6] \"It's okay! There's nothing wrong with you!\""
1004003-55 = "There's no merit in being this tall..."
1004003-56 = "There's no merit in being this tall..."
1004003-57 = "[s] \"Tsukuyo, you should change your perspective.\""
1004003-58 = "What do you mean?"
1004003-59 = "[s7] \"You're tall enough to see over a crowd. \"\n[s8] \"You can see things others can't see!\""
1004003-60 = "My height...can be helpful?"
1004003-61 = "My height...can be helpful?"
1004003-62 = "S-S-Sensei?!"
1004003-63 = ""
1004003-65 = ""
1004003-67 = ""
1004003-68 = "E-Excuse me, Sensei?! Y-You're so close to me...!"
1004003-69 = "[s] \"Square your shoulders, straighten your back, and look around.\""
1004003-70 = "..."
1004003-71 = "Square my shoulders, straighten my back, and look around..."
1004003-72 = "..."
1004003-73 = "Wh-Where's my sister? *cry*"
1004003-74 = "Sensei! I see a crying child! She must be in trouble!"
1004003-75 = "[s] \"She needs a ninja like you. Let's help her.\""
1004003-76 = "Oh... Yes!"
1004003-82 = "Tsukuyo and I went to help the crying child, who'd lost her sister."
1004003-84 = "Th-Thank you for finding my sister! How can I repay you?"
1004003-85 = "N-No worries! It's no problem for a real ninja like me!"
1004003-86 = "Huh...? N-Ninja...?"
1004003-87 = "Thank you, tall lady!"
1004003-88 = "Hey! Don't be rude!"
1004003-89 = "No! It's okay! I was able to find her thanks to my height!"
1004003-90 = "T-Take care! Don't let go of your sister's hand, okay?"
1004003-91 = "Okies!"
1004003-92 = ""
1004003-96 = "[ns] \"That was amazing, Tsukuyo!\""
1004003-97 = "You were right, Sensei."
1004003-98 = "I've always thought of my height as...a huge inconvenience... It puts me in weird situations..."
1004003-99 = "I hunch my back and look at the ground to avoid people's gazes. I thought it was better to make myself smaller..."
1004003-100 = "But when you had me stand up, I realized how much I was missing!"
1004003-101 = "Th-Thank you, Sensei!"
1004003-102 = "[s] \"No problem. But it was all you.\""
1004003-103 = "That's not true! Thanks to you, I realized that being tall isn't something I should hate."
1004003-104 = "So, from now on I'm going to be brave!"
1004003-105 = "Oh! Th-There you are! Superstar of the future!"
1004003-106 = "...?"
1004003-108 = ""
1004003-110 = "*pant* I'm not gonna let you go this time! You have the potential to become a top star in Kivotos!"
1004003-112 = "A-A-Again?! Eeeek!"
1004003-113 = "I...I hate being tall! Waaaah!"
1004003-114 = ""
1004003-116 = ""
1004003-117 = "[ns] \"W-Wait, Tsukuyo!\""
1004003-119 = "I followed Tsukuyo and comforted her until she calmed down."
