[translation]
10049080-1 = "ตอนที่ 8;ลองถามแก๊งหมวกกันน็อกดูสิ!"
10049080-2 = "แงงง ฉันผิดไปแล้ว!!!"
10049080-3 = "วะ... ไว้ชีวิตฉันด้วย!! แล้วฉันจะบอกจุดอ่อนของหัวหน้าให้!!!"
10049080-4 = "หัวหน้าของเรามือไม่ค่อยมีแรง ขนาดฝาขวดแยมยังเปิดไม่ออกเลยค่ะ!!"
10049080-5 = "อ๊ะ! แล้วก็! หัวหน้าไม่กล้านอนชั้นบนของเตียง 2 ชั้นด้วย!"
10049080-6 = "นี่!!!!"
10049080-7 = ""
10049080-10 = ""
10049080-11 = ""
10049080-12 = ""
10049080-14 = "โอ้!"
10049080-15 = "ฮู่ว..."
10049080-16 = "โล่งอกไปทีที่มีแบตเตอรี่รถยนต์อยู่นะคะ"
10049080-17 = "โกดังนี้ไฟดับ ก็เลยต้องเปิดไฟด้วยแบตเตอรี่น่ะค่ะ"
10049080-18 = "จะว่าไป เมื่อกี้คุยเรื่องอะไรกันอยู่เหรอคะ...?"
10049080-19 = "[s1] \"ราบุนอนเตียง 2 ชั้นไม่ได้น่ะ\"\n[s2] \"ราบุเปิดฝาขวดแยมไม่ได้น่ะ\""
10049080-22 = "โธ่เอ๊ย จริงๆ เลย!! ครูเนี่ย!!!"
10049080-23 = "ก็ต้องมีบ้างละค่ะ"
10049080-24 = "เอาละ ฉันอยากคุยทีละอย่างให้เคลียร์ค่ะ..."
10049080-25 = "คุณชิมิโกะก่อนเลย ชุดที่คุณใส่มัน...?"
10049080-26 = "อ๊ะ... ค่ะ! ฉันแต่งตัวเป็น 'เอร่า' หัวหน้าวายร้ายในสาวน้อยเวทมนตร์ เฮฟวี่ แคลิเบอร์ค่ะ"
10049080-27 = "มันก็... น่าจะเป็นอย่างนั้นนะคะ..."
10049080-28 = "ว่าแต่หายไปอยู่ไหนมาคะ?"
10049080-29 = "อ่า... ก็พวกคุณ 2 คนขอให้ฉันสวมบทหัวหน้าฝ่ายวายร้ายไม่ใช่เหรอคะ?"
10049080-30 = "คะ? ก็ใช่ค่ะ...?"
10049080-31 = "ถ้าหัวหน้าวายร้ายมาปรากฏตัวพร้อมสาวน้อยเวทมนตร์ตั้งแต่เริ่มเรื่อง... มันก็แปลกๆ สิคะ"
10049080-33 = "ตามพล็อตแล้วมันก็จริงอยู่ค่ะ คุณสึซึมิ!"
10049080-34 = "[ns] \"พอมาคิดดู มันก็จริงนะ!\""
10049080-36 = "......"
10049080-37 = "แต่ยังไงก็ค่อยยังชั่วที่การจู่โจมได้ผลดีนะคะ..."
10049080-38 = "คุณชิมิโกะมาปรากฏตัวในเวลาที่เราต้องการที่สุดเลยค่ะ"
10049080-39 = ""
10049080-41 = ""
10049080-42 = "ต่อไปก็คุณโคะมาคาเสะ ราบุ"
10049080-43 = "ฉันจะถามอยู่ตั้งแต่เช้าแล้ว..."
10049080-44 = "แต่เพิ่งจะได้มาถามเอาตอนนี้นะคะ"
10049080-45 = "คุณวางแผนก่อเหตุอะไรในสวนสนุกคะ?"
10049080-46 = "ว่าไงนะ? หมายความว่ายังไง?"
10049080-48 = "เมื่อ 3 วันก่อน ฉันได้ยินพวกคุณคุยกันหลังห้องสมุดเก่าค่ะ!"
10049080-49 = "คุณพูดว่าสวนสนุกน่าจะเละจนไม่มีชิ้นดี แล้วก็จะมีคนเจ็บด้วยค่ะ!"
10049080-50 = "แล้ววันนี้ก็ขนระเบิดมือกันมาเพียบเลยด้วย!"
10049080-52 = "หา? เธอได้ยินพวกฉันคุยเรื่องนั้นเหรอ?"
10049080-53 = "ก็บอกแล้วว่าเรื่องแบบนั้นให้คุยกันใน MOMOTALK!"
10049080-55 = "นี่พวกเธอพูดเรื่องอะไรกันน่ะ?"
10049080-56 = "วางแผนจะระเบิดสวนสนุกแล้วทำให้คนอื่นบาดเจ็บกันงั้นเหรอ?"
10049080-57 = "ฉันสอนพวกเธอให้ทำเรื่องอะไรแบบนั้นหรือไง!!"
10049080-59 = "ปะ... เปล่านะคะ หัวหน้า!! พวกฉันจะทำแบบนั้นไปทำไมคะ?!"
10049080-60 = "ถ้ามีระเบิดมือหรือพลังที่จะทำให้อะไรเละเทะได้ พวกฉันคงไปทำงานพาร์ทไทม์รื้อถอนอาคารแล้วค่ะ!"
10049080-61 = "จะทำงานแบบนั้นต้องกินข้าวให้มีแรงด้วยเหอะ!"
10049080-63 = "ถ้างั้นพวกเธอคุยเรื่องอะไรกันแน่?"
10049080-65 = "ฉันจำไม่ได้เลย แต่น่าจะเป็นการพูดเกี่ยวกับ 'คนคนนั้น' นะคะ"
10049080-66 = "เหมือนจะพูดว่าถ้าคนคนนั้นขัดขืนและหนีไป ก็น่าจะลงเอยด้วยการต่อสู้ อะไรประมาณนี้..."
10049080-68 = "เดี๋ยวก่อน เดี๋ยวก่อนค่ะ แล้ว 'คนคนนั้น' คือใครคะ?"
10049080-69 = "ค่อยๆ อธิบายมาทีละอย่างเลยค่ะ"
10049080-71 = "ถ้าบอกแล้วจะเลิกมารบกวนพวกฉันมั้ยล่ะ? ฮะ?"
10049080-72 = "แน่นอนสิคะ เว้นแต่ว่าพวกคุณคิดทำเรื่องอะไรไม่ดีค่ะ"
10049080-73 = ""
10049080-74 = "[ns] \"ครูจะรับรองคำพูดของสึซึมิให้เอง\""
10049080-75 = "ชิ ครูก็มาเอี่ยวด้วยเหรอเนี่ย..."
10049080-76 = "ก็ได้ๆ เฮ้อ..."
10049080-77 = "ตอนนี้พวกฉันทำงานคล้ายๆ งานหน่วยปราบปรามอยู่น่ะ"
10049080-78 = "แก๊งหมวกกันน็อกทำงานหน่วยปราบปรามเหรอคะ? มีอำนาจทำแบบนั้นด้วยเหรอคะ?"
10049080-79 = "แล้วทำไมถึงจะไม่ได้ล่ะ? จะทำเรื่องดีๆ ต้องได้รับอนุญาตด้วยหรือไง?"
10049080-80 = ""
10049080-82 = ""
10049080-83 = "อะไรดีก็ว่าดีสิ ขอแค่หาเงินได้ ยิ่งเป็นงานขาวสะอาด พวกเราก็ยิ่งชอบ"
10049080-84 = "จะได้ไม่ต้องคอยระวังวัลคิรี่ คณะกรรมการวินัย แล้วก็ชมรมทวงความยุติธรรมด้วย"
10049080-85 = "เอาเถอะ... เอาเป็นว่าหมู่นี้มีสินค้าปลอมวางขายเกลื่อนกลาดเลย"
10049080-86 = "ได้ยินว่าถ้าจับตัวคนที่ปล่อยสินค้านั้นออกมาได้ บริษัทที่ได้รับผลกระทบก็จะมีเงินรางวัลมอบให้"
10049080-87 = "ฉันก็เลยพยายามจะจับคนค้าขายพวกนั้น เพื่อจะเอาเงินรางวัลยังไงล่ะ"
10049080-89 = "สินค้าปลอม... งั้นเหรอคะ?"
10049080-90 = "ใช่ ระเบิดมือพวกนี้ก็ด้วย"
10049080-91 = "โฆษณาซะเพ้อเจ้อเลยละ บอกว่าเป็นระเบิดมือเจอร์เมเนียมบ้างละ แรงจากสลักระเบิดรูปสามเหลี่ยม#nจะช่วยให้สุขภาพดีบ้างละ..."
10049080-92 = "นอกจากนี้ยังมีของเก๊ไร้คุณภาพที่ราคาถูกด้วย"
10049080-93 = "ทั้งลูกโป่งที่ลมรั่ว ถังป๊อปคอร์นปลอมที่ไม่แข็งแรง"
10049080-94 = "ระเบิดมือกับถังป๊อปคอร์นตรงนั้นฉันแอบยึดมาได้ แต่ยังตามตัวคนที่ขายไม่ได้น่ะ"
10049080-95 = "ก็สวนสนุกมันกว้างซะขนาดนี้ หาให้ตายก็คงไม่เจอหรอก ชิ"
10049080-96 = "ลูกโป่งลมรั่ว... ถังป๊อปคอร์นที่ไม่แข็งแรง...?"
10049080-97 = ""
10049080-98 = "เพิ่งซื้อลูกโป่งมาแท้ๆ แต่ลมมันรั่วออกไปหมดแล้วง่า!"
10049080-99 = "ฝาถังป๊อปคอร์นปิดไม่อยู่จนหล่นพื้นไปแล้ว! แงงง..."
10049080-100 = "แงงงงง..."
10049080-101 = "ขออันใหม่ได้มั้ยครับ! เปลี่ยนให้หน่อย!"
10049080-103 = ""
10049080-104 = ""
10049080-105 = ""
10049080-106 = ""
10049080-107 = ""
10049080-108 = ""
10049080-109 = "ทำไมถึงยอมแก้เชือกให้ล่ะ? จะปล่อยกลับบ้านเหรอ?"
10049080-110 = "ก่อนอื่นเลย คุณราบุ... แล้วก็สมาชิกแก๊งหมวกกันน็อกทุกคน"
10049080-111 = "ฉันขอโทษที่เข้าใจผิดจนไปขัดขวางการทำงานของพวกคุณนะคะ"
10049080-113 = "ว่าไงนะ? เฮอะ! คิดว่ามายุ่งเรื่องคนอื่นแล้วพอมาขอโทษกันดื้อๆ แบบนี้แล้วเรื่องจะจบเหรอ?"
10049080-114 = ""
10049080-116 = ""
10049080-117 = ""
10049080-118 = "ฉันขอโทษจากใจจริงค่ะ"
10049080-119 = ""
10049080-121 = ""
10049080-122 = "อะ... เอ่อ?! กะ... ก็ได้?"
10049080-123 = "ก็นะ... ใครๆ ก็เข้าใจผิดกันได้ทั้งนั้นละ"
10049080-124 = "ถ้าขอโทษกันแล้วก็แล้วไป! งั้นก็จบเรื่องนี้กันแค่นี้!"
10049080-126 = "ฉันก็ต้องขอโทษเหมือนกันค่ะ ฉันเข้าใจพวกคุณผิดไปค่ะ..."
10049080-127 = "ฉันเองก็...! จะขอโทษยังไงดี...!"
10049080-129 = "บอกแล้วไงว่าแล้วๆ กันไป!!!"
10049080-130 = "ฉันเข้าใจสถานการณ์แล้วค่ะ คุณราบุ"
10049080-131 = "ส่วนงานที่คุณเล่าให้ฟัง ขอให้พวกฉันเข้าไปช่วยได้มั้ยคะ?"
10049080-132 = "เอ๋?! ทำไมจู่ๆ ถึงจะช่วยล่ะ? ไม่ได้มีเจตนาแอบแฝงอะไรใช่มั้ย?"
10049080-133 = "ฉันแค่อยากชดเชยที่ไปขัดขวางการทำงานของคุณราบุด้วยการกระทำน่ะค่ะ"
10049080-134 = "คุณราบุคิดว่าคนพวกนั้นไม่ยุติธรรมหรือเปล่าคะ?"
10049080-135 = "จะให้ฉันพูดเรื่องนี้มันก็กระไรอยู่ แต่จะให้บอกว่าพวกนั้นเป็นคนดีก็ไม่ได้หรอก"
10049080-136 = "คนพวกนั้นทำให้คนบริสุทธิ์ต้องเดือดร้อนใช่หรือเปล่าคะ?"
10049080-137 = "ถ้าโดนหลอกขายของแบบนั้นบ้าง เป็นฉันก็น่าจะหัวร้อนอยู่นะ?"
10049080-138 = "เข้าใจแล้วค่ะ"
10049080-139 = "ฉันรู้ตำแหน่งดีค่ะ แล้วคนพวกนั้นก็น่าจะยังไปไหนไม่ไกลด้วย"
10049080-140 = "กลุ่มรักษาความสงบจะช่วยเองค่ะ"
10049080-142 = "...!"
10049080-143 = "ฉันพร้อมแล้วค่ะ!"
10049080-144 = "งั้นชมรมอ่านหนังสือก็จะช่วยอีกแรงค่ะ!"
10049080-145 = ""
10049080-146 = "[ns3] \"ครูก็พร้อมแล้ว!\"\n[ns4] \"ครูจากชาเล่ต์ก็พร้อมแล้ว!\""
10049080-150 = "คิกคิก ก็ได้ ถ้าจะออกตัวช่วยแบบไม่คิดเงิน ใครจะไปปฏิเสธลงล่ะ"
10049080-151 = "แล้วฉันก็ไม่รู้ด้วยว่าพวกนั้นมีกันกี่คน"
10049080-152 = ""
10049080-154 = ""
10049080-155 = "พวกเธอมาจากกลุ่มรักษาความสงบกับชมรมอ่านหนังสืองั้นสินะ?!"
