[translation]
10044050-1 = "Episode 5;Vroom Vroom Race Association"
10044050-3 = "Everyone! There's..."
10044050-4 = "...something incredible...it could change Kivotos..."
10044050-5 = ""
10044050-8 = ""
10044050-9 = "That's it!"
10044050-10 = "We found it! Heehee, I love it when the news comes straight to me!"
10044050-11 = "Cap— I mean, \"President\"! What should we do?!"
10044050-12 = "Get everyone we can on the road right now!"
10044050-13 = "We're taking control of that train!"
10044050-14 = ""
10044050-16 = ""
10044050-17 = ""
10044050-18 = "Ooh! Orders from the president! Go!"
10044050-19 = ""
10044050-21 = ""
10044050-22 = ""
10044050-23 = ""
10044050-24 = ""
10044050-25 = "...Hold on."
10044050-26 = "What?"
10044050-27 = "You heard it on the news, right?"
10044050-28 = "...Yes, and?"
10044050-29 = "Then...we might not be the only ones going after it."
10044050-30 = "..."
10044050-31 = "Good point."
10044050-33 = "What? A freight train full of cash?"
10044050-35 = "A weapon that can take over Kivotos? You sure?"
10044050-37 = "This really is..."
10044050-39 = "...a treasure train!!"
10044050-40 = "Everything we want is right there!"
10044050-41 = "Finders keepers!!"
10044050-44 = ""
10044050-46 = "*huff* Wh-What is...?!"
10044050-47 = "We're on the news. Should've recorded it."
10044050-48 = "Ugh! Seriously? We just HAPPENED to stumble right into a live stream!"
10044050-49 = "[ns] \"Wow, when's the last time things went THIS wrong...?\""
10044050-51 = "All right, let's just find it first and get it out of here!"
10044050-52 = "S-Sure, yes. Things should be safe once the train gets running..."
10044050-53 = ""
10044050-55 = ""
10044050-57 = ""
10044050-58 = "Okay. Phew. We're here first!"
10044050-59 = "Let's find the train."
10044050-60 = ""
10044050-62 = ""
10044050-64 = ""
10044050-66 = "*huff* *huff* Freight train, where are you...?"
10044050-67 = "Hey, are you those CCC people who called earlier?"
10044050-69 = "Yuppies. Where train?"
10044050-70 = "Th-This way...!"
10044050-71 = ""
10044050-74 = ""
10044050-75 = ""
10044050-76 = "Hm? Aren't they...?"
10044050-77 = "What? You know them?"
10044050-78 = "Uh...yeah! They're the jerks who ordered that pizza!"
10044050-79 = "The one you told us about?"
10044050-80 = "That's right! The Highlanders!"
10044050-81 = "Oooh! Well, we've got 'em now! Let's teach 'em a lesson!"
10044050-82 = "Heehee, someone just ordered a beatdown!"
10044050-84 = "Hey, you!"
10044050-85 = ""
10044050-88 = ""
10044050-90 = "Ho ho...it's just not your day, is it?"
10044050-91 = "And now, sweet revenge."
10044050-93 = "..."
10044050-94 = "Whooo?"
10044050-95 = "You ALREADY FORGOT? I got FIRED because of you!"
10044050-96 = "Oh, you're that terrible pizza driver from earlier!"
10044050-97 = "Yeah, and they fired me on the spot because you complained!"
10044050-98 = "That was my FIRST DAY! I usually last for two, at least!"
10044050-99 = "You can't have it good, fast, AND cheap, you know!"
10044050-101 = "Well, if you're gonna make deliveries, don't drive like you're in a biker gang!"
10044050-102 = "Yeah, that was barely even pizza by the time you got it there!"
10044050-103 = "Bikes are lame anyway."
10044050-105 = "Oh, you just keep diggin' that hole!"
10044050-106 = "Let's teach 'em a little respect! Get 'em!"
