[translation]
1004102-1 = "The Body Is a Prison"
1004102-2 = ""
1004102-4 = "..."
1004102-5 = "[s] \"...\""
1004102-6 = "What're you doing here?"
1004102-7 = "[s] \"Well... Um...\""
1004102-8 = "Do you want something?"
1004102-9 = "Spit it out."
1004102-10 = "[s] \"I didn't necessarily want anything in particular...\""
1004102-11 = "Okay. Bye."
1004102-12 = "[s] \"W-Wait!\""
1004102-13 = "...What?"
1004102-14 = "[s1] \"Misaki, you seem kind of...mysterious.\"\n[s2] \"I can't figure out what you're thinking.\""
1004102-15 = "Yes. And?"
1004102-16 = "Yes. And?"
1004102-17 = "[s3] \"I was hoping to talk to you more...\"\n[s4] \"I want to get to know you...\""
1004102-18 = "..."
1004102-19 = "..."
1004102-20 = "*sigh*"
1004102-21 = ""
1004102-23 = ""
1004102-24 = ""
1004102-25 = ""
1004102-26 = "It's my responsibility to keep everyone safe."
1004102-27 = "We're playing hide-and-seek with the trackers every day."
1004102-28 = "So, out of principle, you shouldn't even be in contact with me, Sensei."
1004102-29 = "However..."
1004102-30 = "I guess it doesn't matter. At the end of the day, our lives are in your hands."
1004102-31 = "So, what do you want to do? I don't have much going on today."
1004102-32 = "[s] \"Maybe we can just talk...?\" "
1004102-33 = "... "
1004102-34 = "[s] \"Okay, bad idea. Can I help you with anything?\""
1004102-35 = "No."
1004102-36 = "Well, actually. I can think of one thing."
1004102-37 = "[s] \"Oh, good! Just name it!\""
1004102-38 = "Then..."
1004102-40 = ""
1004102-41 = "Calibration complete."
1004102-42 = "[s] \"All set?\""
1004102-43 = "Yeah. Our GPS is old, so I needed to recalibrate it from high up."
1004102-44 = "But I can't exactly waltz into any building, so I just lived with it."
1004102-45 = "I won't get lost anymore, thanks to you."
1004102-46 = "[s] \"I'm relieved I was able to help.\""
1004102-47 = "Relieved?"
1004102-48 = "[s] \"You're pretty unpredictable. I didn't know what you might've needed.\""
1004102-49 = "Interesting."
1004102-50 = "People do say that a lot. I don't pay them much mind."
1004102-51 = "I'm all done here."
1004102-52 = "[s] \"Sh-Should we get something to eat once we get down? Are you hungry?\""
1004102-53 = "No."
1004102-54 = "Let's head down."
1004102-55 = ""
1004102-57 = ""
1004102-58 = "[s] \"...A-All right.\""
1004102-63 = "..."
1004102-64 = "[s] \"...\""
1004102-65 = "..."
1004102-66 = "I'm making you uncomfortable, huh? Sorry. That's how it is around me."
1004102-67 = "I have no passion or interest in anything. "
1004102-68 = "You asked me if I was hungry before."
1004102-69 = "...I'm not very interested in food."
1004102-70 = "All that matters is I don't die of starvation."
1004102-71 = "[s] \"But being hungry is bad for you too!\""
1004102-72 = "That's true. But the body is just a vessel that'll return to the earth at the end of its cycle."
1004102-73 = "[s] \"Ah... I see.\""
1004102-74 = "It is what it is."
1004102-75 = "[s] \"Is there anything that's important to you?\""
1004102-76 = "Don't think so."
1004102-77 = "I wonder if there could be."
1004102-78 = "After all, everything is in vain."
1004102-79 = ""
1004102-86 = "What?!"
1004102-87 = ""
1004102-90 = ""
1004102-92 = "[ns] \"It seems like the elevator stopped.\""
1004102-93 = "...?!"
1004102-94 = "Why...Why is this happening..."
1004102-95 = "Attention. The building's power went out due to an error in the fire safety system. Please expect the systems to be down for the next hour."
1004102-96 = "A-An hour?! Wait!"
1004102-97 = "Hold on! What do you mean an hour?"
1004102-98 = "[s] \"We'll just have to wait it out.\""
1004102-99 = "No! We have to do something. A whole hour...?"
1004102-100 = "[s] \"Do you have somewhere you need to be?\""
1004102-101 = "No, but...!"
1004102-102 = "I...I just..."
1004102-103 = "[s] \"Just sit and relax. It'll be fine.\"  "
1004102-104 = "S-Sit? Right now?"
1004102-105 = "[s] \"Are you okay? Don't worry, we'll be safe here.\""
1004102-106 = "D-Don't...make me...talk..."
1004102-107 = "[s] \"...Misaki? Your face is losing its color.\""
1004102-108 = "..."
1004102-109 = "[s5] \"What's wrong?\"\n[s6] \"Are you okay?\"\n[s7] \"Are you feeling ill? Please tell me.\""
1004102-110 = "D-Don't talk to me..."
1004102-111 = "D-Don't talk to me..."
1004102-112 = "D-Don't talk to me..."
1004102-113 = "R-Right... I...clau...."
1004102-114 = "[s8] \"Huh? Misaki, what did you say?\"\n[s9] \"Clau...? What does that mean?\"\n[s10] \"Misaki, you need to tell me what's wrong!\""
1004102-115 = "I have claustrophobia!"
1004102-116 = "I have claustrophobia!"
1004102-117 = "I have claustrophobia!"
1004102-118 = "[s] \"...\""
1004102-119 = "Ugh. Get me out. I can't..."
1004102-120 = ""
1004102-122 = ""
1004102-123 = ""
1004102-124 = ""
1004102-125 = "[ns] \"Misaki! The door is opening!\""
1004102-126 = ""
1004102-127 = "*buzz* We had no idea anyone was trapped in the elevator! Our apologies for the inconvenience."
1004102-128 = "[s] \"Thank you for rescuing us.\""
1004102-130 = "..."
1004102-131 = "[s11] Get down and apologize.\n[s12] Grovel with your head on the ground."
1004102-132 = "Sensei..."
1004102-133 = "Sensei..."
1004102-134 = "[s] \"I'm really sorry, Misaki.\""
1004102-135 = "It's not your fault... You didn't know."
1004102-136 = "I wouldn't have imagined an Arius agent who infiltrated the underground catacombs could be claustrophobic, either."
1004102-137 = "I just don't like small, dark places."
1004102-138 = "My body freaks out in those environments. That's not your fault."
1004102-139 = "[s] \"O-Okay...\""
1004102-141 = "Misaki left, seeming gloomier than ever."
