[translation]
1004905-1 = "Bad Timing"
1004905-2 = "I was taking a long-awaited day off."
1004905-3 = "I slept in and eventually went out to go to the convenience store for lunch."
1004905-4 = ""
1004905-8 = ""
1004905-9 = ""
1004905-10 = ""
1004905-11 = "............"
1004905-12 = "What?!"
1004905-13 = "[ns] \"...?\""
1004905-15 = "[ns1] \"...Is someone there?\"\n[ns2] Follow the sound to the source."
1004905-18 = ""
1004905-19 = ""
1004905-20 = ""
1004905-21 = "...!!!"
1004905-22 = "...She ran away."
1004905-23 = "[ns3] Follow her. \n[ns4] \"Why are you avoiding me...\""
1004905-26 = ""
1004905-27 = ""
1004905-28 = ""
1004905-29 = ""
1004905-30 = ""
1004905-31 = "...! Argh! Ouch..."
1004905-32 = "[s] \"...Kazusa?\""
1004905-35 = "― Umm.[wa:680] "
1004905-37 = "― Did you recognize me right away?[wa:10] "
1004905-40 = "― I see..."
1004905-42 = "― Y-Yeah, figures. Of course you would...[wa:480] "
1004905-45 = "― N-No,[wa:490] "
1004905-47 = "― it wasn't like I was avoiding you...[wa:10] "
1004905-50 = "― I-I just...um...[wa:1240] "
1004905-52 = "― Well, um... I haven't done my makeup yet.[wa:1140] "
1004905-55 = "―Don't look too closely...![wa:2660] "
1004905-58 = "― I told you, Sensei."
1004905-60 = "― Don't come any closer![wa:180] "
1004905-63 = "[ns5] \"Maybe you shouldn't be so concerned about it.\"\n[ns6] \"Why does it matter if you're wearing makeup?\""
1004905-64 = "― R-Really? ...Is that so?[wa:2640] "
1004905-65 = "― R-Really? ...Is that so?[wa:2640] "
1004905-67 = "― Well... I hope that's the case...[wa:1160] "
1004905-70 = "― What's with your reaction...?[wa:650] "
1004905-73 = "― H-Hey! Don't laugh! What's so funny?[wa:520] "
1004905-75 = "― Hey!!!"
1004905-78 = "*sigh* Forget it. I won't win by getting mad at you."
1004905-79 = "Are you done shopping yet? Then leave. I can't browse in peace because of you."
1004905-80 = "Huh?!"
1004905-81 = "You didn't have a chance to get anything because you were following me around...?"
1004905-82 = "...Oh."
1004905-83 = "Oh, really... Hahaha..."
1004905-84 = "Hahaha..."
1004905-85 = ""
1004905-87 = ""
1004905-88 = ""
1004905-89 = "I said stop it!!!"
1004905-90 = "......"
1004905-91 = "We were eventually scolded by a worker for \"disturbing the peace\"."
1004905-94 = ""
1004905-95 = "Ugh... I'm mortified."
1004905-96 = "To be clear, this is your fault, Sensei!"
1004905-97 = "Are you serious? You had fun?"
1004905-98 = "You're really trying to push my buttons today!"
1004905-99 = "I'm trying to portray my best self to you! Can you be a little more considerate of all my effort?"
1004905-100 = "*sigh* Why am I spending all my energy on my day off?"
1004905-101 = "...So...going back to before..."
1004905-102 = "Did you really mean what you said?"
1004905-103 = "[s7] \"What? That I don't care if you don't have makeup on?\"\n[s8] \"Are you gonna make me say it again?"
1004905-104 = "...W-Well, yeah."
1004905-105 = "I'm just kind of embarrassed about the whole thing."
1004905-106 = "Ugh, I shouldn't be so insecure."
1004905-107 = "Okay, okay. I should just believe you."
1004905-108 = "But I don't want to hear about this ever again. Otherwise, I'll crack you in the head so hard you'll have memory loss."
1004905-109 = "O-Okay..."
1004905-110 = ""
1004905-112 = ""
1004905-113 = "Bye! I'll see you later, Sensei!"
1004905-114 = ""
1004905-116 = ""
1004905-117 = "[ns] \"...\""
1004905-118 = "Kazusa ran off into the distance, and I returned to work."
