[translation]
10051100-1 = "ตอนที่ 10;ตอนจบของโชว์"
10051100-4 = "ห้องพักในงานแฟชั่นโชว์"
10051100-5 = "ใกล้จะถึงเวลาขึ้นรันเวย์แล้วสินะ"
10051100-6 = "เตรียมตัวพร้อมหรือยัง?"
10051100-7 = "..."
10051100-8 = "ทิ้งความกังวลไป แล้วเตรียมใจให้พร้อม"
10051100-9 = "เพราะนี่จะเป็นรันเวย์เดบิวต์จริงๆ ของเธอยังไงล่ะ"
10051100-10 = "เดบิวต์จริงๆ งั้นเหรอคะ?"
10051100-11 = "งานแฟชั่นโชว์ที่เธอเคยเดินก่อนหน้านี้น่ะเป็นแค่งานเล็กๆ การเดินแบบที่ยังเก้ๆ กังๆ ของเธอตอนนั้น#nก็เลยยังไม่ใช่ปัญหาใหญ่ยังไงล่ะ"
10051100-12 = "แน่นอนว่าผลงานครั้งนั้นทำให้เธอมีชื่อเสียง... แต่นั่นก็เป็นชื่อเสียงในฐานะ 'มือใหม่' เท่านั้น"
10051100-13 = "แต่งานวันนี้เป็นถึงงานแฟชั่นโชว์ฉลองปีใหม่ที่กำลังจะมาถึง และจะมีผู้ชมมากกว่าเดิมหลายเท่าเลยละ"
10051100-14 = "เพราะงั้นหลังจากจบงานนี้ ชื่อของเธอก็จะเป็นที่รู้จักในวงกว้างมากขึ้น"
10051100-15 = ""
10051100-17 = ""
10051100-18 = ""
10051100-19 = "และวันนี้... เธอจะได้เกิดใหม่ในฐานะนางแบบมืออาชีพอย่างแท้จริง"
10051100-20 = "นางแบบมืออาชีพ..."
10051100-21 = "ฉัน... เนี่ยนะคะ?"
10051100-22 = "ใช่แล้ว ตื่นเต้นใช่มั้ยล่ะ?"
10051100-23 = "..."
10051100-24 = "หรือว่ายังรู้สึกค้างคาใจอยู่? ยังอยากกลับไปอยู่อีกเหรอ?"
10051100-25 = "ฉะ... ฉัน..."
10051100-26 = "เอ่อ..."
10051100-27 = "ถ้าอยู่ในจุดที่ลังเลแบบนั้น ก็ลองนึกถึงความพยายามทั้งหมดที่เธอทำมาสิ"
10051100-28 = "ทั้งควบคุมอาหารอย่างเข้มงวด ทั้งออกกำลังกาย ฝึกฝน..."
10051100-30 = "อย่าปล่อยให้พรสวรรค์และความพยายามที่เธอทุ่มเทไปสูญเปล่าสิ เข้าใจมั้ย?"
10051100-31 = "ขะ... เข้าใจแล้วค่ะ..."
10051100-32 = ""
10051100-35 = "ถึงเวลาแล้วครับ เตรียมตัวได้เลยครับ"
10051100-36 = "เอาละ โชว์ฝีมือมาให้เต็มที่ล่ะ"
10051100-37 = "ค่ะ..."
10051100-38 = ""
10051100-40 = ""
10051100-41 = ""
10051100-43 = ""
10051100-44 = "มีคนมาเยอะกว่างานแฟชั่นโชว์ครั้งก่อนมากเลยค่ะ หัวหน้า!"
10051100-45 = "นั่นสินะ... งานก็สเกลใหญ่กว่าครั้งก่อนเยอะเลย..."
10051100-46 = "เดี๋ยวสึคุโยะก็จะเดินแบบออกมาด้วยใช่มั้ย...?"
10051100-47 = "ใช่ค่ะ หัวหน้า"
10051100-48 = "พองานจบ เราอาจได้เจอสึคุโยะตัวเป็นๆ ก็ได้ค่ะ"
10051100-49 = "ได้ยินว่าตอนออกจากงาน พวกนางแบบกับเจ้าหน้าที่ในงานจะใช้เส้นทางเดียวกันน่ะค่ะ"
10051100-50 = "สึคุโยะ..."
10051100-51 = "แต่ว่านะ อิซุนะจัง"
10051100-52 = "ค่ะ หัวหน้า?"
10051100-53 = ""
10051100-55 = ""
10051100-56 = "ข้าน้อย... จำเป็นต้องเจอสึคุโยะด้วยเหรอ?"
10051100-57 = "คะ?!"
10051100-58 = ""
10051100-62 = "อ่า..."
10051100-63 = "งานเริ่มแล้วค่ะ..."
10051100-64 = ""
10051100-70 = ""
10051100-71 = ""
10051100-72 = ""
10051100-73 = ""
10051100-74 = "สึคุโยะนี่นา..."
10051100-75 = "ท่านสึคุโยะ..."
10051100-76 = "นี่สินะที่บอกว่าคนเราเปล่งประกายออกมาได้..."
10051100-77 = "ท่าเดินดูเป็นธรรมชาติกว่าแต่ก่อนเยอะเลยนะคะ"
10051100-78 = "ตอนนี้เป็น... นางแบบจริงๆ แล้วสินะ..."
10051100-79 = "ได้ใส่ชุดสวยๆ ยืนอยู่บนรันเวย์..."
10051100-80 = "ได้แสงสปอตไลท์สาดส่องมาที่ตัว... พร้อมวิ่งไปข้างหน้าด้วยสุดกำลัง..."
10051100-81 = "วิ่ง... "
10051100-82 = ""
10051100-84 = ""
10051100-85 = "เดี๋ยวนะ วิ่งทำไม?"
10051100-87 = "สึคุโยะ?! ทำไมจู่ๆ ก็วิ่งขึ้นมาล่ะ?!"
10051100-88 = "หา...?!"
10051100-89 = "หัวหน้า! จู่ๆ ท่านสึคุโยะก็กระโดดลงมาจากรันเวย์ค่ะ!!"
10051100-90 = "ทำไมล่ะ?!!!"
10051100-93 = "[log]1 นาทีก่อน[/log]"
10051100-96 = "(ผู้คนเยอะเต็มไปหมดเลย...)"
10051100-97 = "(ฮู่ว...)"
10051100-98 = "(ไม่เป็นไรหรอก ทำตามที่ฝึกฝนมาก็พอ)"
10051100-99 = "(ใช่ ถ้าเดินไปแบบนี้ละก็...)"
10051100-100 = "(จากนั้น... ฉันจะเป็นยังไงนะ?)"
10051100-101 = ""
10051100-102 = ""
10051100-103 = "(อ๊ะ เริ่มแล้ว...!)"
10051100-104 = ""
10051100-106 = ""
10051100-107 = "(หืม?)"
10051100-108 = "(เดี๋ยวนะ คนคนนั้นที่อยู่ในฝูงชนกำลังทำอะไรอยู่น่ะ...?!)"
10051100-110 = ""
10051100-111 = ""
10051100-112 = ""
10051100-113 = "(อะ... อะ... อะ... อะไรน่ะ?!)"
10051100-114 = "(ทำไมคนคนนั้นถึงมีระเบิดในกระเป๋าล่ะ?!)"
10051100-115 = "(แล้วตอนนี้ยังพยายามจะดึงสลักระเบิดอีก...!)"
10051100-116 = "(ว่าแต่ทำไมผู้คนรอบๆ ถึงอยู่เฉยกันหมดเลย?!)"
10051100-117 = "(อย่าบอกนะว่ามีฉันคนเดียวที่เห็นคนคนนั้นจากบนนี้?!)"
10051100-118 = "(ฮือออ...!)"
10051100-119 = "(ทำไมนะ? ทำไมจู่ๆ ก็มาก่อเรื่องแบบนี้ล่ะ?!)"
10051100-120 = "(ไม่สิ ตอนนี้ไม่ใช่เวลามาถามหาสาเหตุ!)"
10051100-121 = "(ต้องรีบหยุดระเบิดนั่นก่อน!)"
10051100-122 = "(ตะโกนออกมาดีมั้ยนะ? ไม่สิ แบบนั้นก็จะยิ่งเกิดความวุ่นวายกันไปใหญ่...!)"
10051100-123 = "(จะทำยังไงดีล่ะ...!)"
10051100-124 = ""
10051100-128 = "[log]นินจาน่ะ [wa:1000]ไม่ว่าจะ[/log]"
10051100-130 = "[log]อยู่ในสถานการณ์ที่จนมุมแค่ไหน...[/log]"
10051100-132 = ""
10051100-133 = "ก็ไม่ยอมถอยให้ความอยุติธรรมอยู่แล้ว...!"
10051100-134 = "ฮึ่มม...!"
10051100-135 = ""
10051100-138 = "พรวดดด!"
10051100-139 = "สึคุโยะ?! ทำไมจู่ๆ ก็วิ่งอย่างนั้นล่ะ?!"
10051100-140 = "เอ๋?!"
10051100-151 = "หัวหน้า! จู่ๆ ท่านสึคุโยะก็กระโดดลงมาจากรันเวย์ค่ะ!!"
10051100-153 = ""
10051100-154 = ""
10051100-157 = ""
10051100-160 = "โครมม!!"
10051100-162 = ""
10051100-163 = "จะ... จับตัวได้แล้วค่ะ!"
10051100-164 = ""
10051100-166 = ""
10051100-167 = "ทะ... ทะ... ทำอะไรของเค้าน่ะ?!"
10051100-168 = "เฮือกก...!"
10051100-169 = ""
10051100-172 = ""
10051100-173 = "สึคุโยะ!"
10051100-174 = "ท่านสึคุโยะ!"
10051100-175 = "ทำอะไรน่ะ?! ชุดขาดหมดแล้วนะ?!"
10051100-176 = "แล้ว... แฟชั่นโชว์ล่ะ...!"
10051100-177 = "ท่านหัวหน้า! เราต้องไปแย่งกระเป๋าของคนนั้นมาก่อนค่ะ!"
10051100-178 = "มีระเบิดอยู่ในกระเป๋าค่ะ!!"
10051100-179 = ""
10051100-181 = ""
10051100-182 = ""
10051100-183 = ""
10051100-184 = "แย่งกระเป๋ามาได้แล้วค่ะ! มีระเบิดอยู่ข้างในจริงด้วยค่ะ!"
10051100-185 = "เฮือก...! "
10051100-186 = "นี่มันระเบิดขนาดรุนแรงที่ห้ามจำหน่ายในร้านสะดวกซื้อกับซูเปอร์มาร์เก็ตไม่ใช่เหรอ?!"
10051100-187 = "แต่ที่สำคัญกว่านั้น... สึคุโยะ! เป็นอะไรหรือเปล่า?!"
10051100-188 = "ฉันไม่ได้บาดเจ็บตรงไหนค่ะ"
10051100-189 = "ถึงชุดจะขาดบ้างนิดหน่อยก็เถอะ..."
10051100-190 = "แหะๆ ไม่น่ามองเลยใช่มั้ยคะ?"
10051100-191 = "มะ... ไม่ใช่อย่างนั้นสักหน่อย! เป็นถึงนางแบบ มาทำให้ชุดเสียหายได้ยังไง?!"
10051100-192 = "แล้วชุดนี้ก็น่าจะแพงมากเลยไม่ใช่เหรอ?!"
10051100-193 = "ไม่ต้องห่วงหรอกค่ะ ท่านหัวหน้า"
10051100-194 = "อะไรกัน จะไม่ให้ห่วงได้ยังไงล่ะ?!"
10051100-195 = "สึคุโยะ ก็เธอ..."
10051100-197 = "เป็นนางแบบนี่นา..."
10051100-198 = ""
10051100-200 = ""
10051100-201 = ""
10051100-202 = "คะ...?"
10051100-203 = "หืม...?"
10051100-204 = "ไม่ใช่เหรอ?"
10051100-205 = "ฉันก็ยังเป็นสึคุโยะนี่คะ?"
10051100-206 = "ไม่ใช่ ฉันไม่ได้หมายความแบบนั้น..."
10051100-207 = "ไม่หรอกค่ะ เราพูดเรื่องเดียวกันอยู่ค่ะ"
10051100-208 = "ฉันคือโอโนะ สึคุโยะ นักเรียนร่างใหญ่ ตัวสูง ขี้อายและชื่นชอบนินจา นั่นคือฉันค่ะ"
10051100-209 = "แล้วนางแบบล่ะ...?"
10051100-210 = "ที่จริงฉันก็ไม่แน่ใจค่ะ"
10051100-211 = "ถึงคนรอบข้างจะพากันชื่นชมและบอกว่าฉันเป็นสุดยอดนางแบบ"
10051100-212 = "แต่ทุกครั้งที่ฉันได้ยินคำพูดแบบนั้น และพอต้องเผชิญขั้นตอนต่างๆ ตามวิถีนางแบบ..."
10051100-213 = "ฉันก็อึดอัดและลำบากใจ เหมือนกับการใส่เสื้อผ้าที่ไม่พอดีตัวเลยค่ะ..."
10051100-214 = "เสื้อผ้าที่ไม่พอดีตัว..."
10051100-215 = "แต่ท่านหัวหน้าก็ได้เห็นแล้วนี่คะ ว่าเสื้อผ้าที่ไม่พอดีตัว... เสื้อผ้าที่ต้องฝืนใส่... "
10051100-216 = "สักวันมันก็จะฉีกขาดแบบนี้ละค่ะ..."
10051100-217 = "สึคุโยะ..."
10051100-218 = "ท่านหัวหน้า ฉันขอกลับไปดีกว่าค่ะ"
10051100-219 = ""
10051100-221 = ""
10051100-222 = "กลับไปยังชมรมวิจัยศาสตร์นินจาของเรา"
10051100-223 = ""
10051100-225 = ""
10051100-226 = "..."
10051100-227 = "ฮะ... ฮือ..."
10051100-228 = "ทะ... ท่านหัวหน้า?!"
10051100-229 = "ร้องไห้ทำไมคะ?!"
10051100-230 = "ขะ... ข้าน้อยคิดว่าสึคุโยะจะไม่กลับมาซะแล้ว..."
10051100-231 = "ก็สึคุโยะมีพรสวรรค์ที่ชัดเจนมาก... แตกต่างกับข้าน้อยเลย..."
10051100-232 = "ข้าน้อยก็เลยคิดว่าไม่ควรรั้งไว้"
10051100-233 = ""
10051100-234 = "เพราะไม่อยากให้พรสวรรค์ที่สึคุโยะทุ่มเทค้นหามาอย่างหนักต้องสูญเสียไปเพราะข้าน้อยน่ะ..."
10051100-235 = "นั่นก็เลยเป็นเหตุผลที่ข้าน้อยคิดว่าการไม่กลับมาจะดีกับตัวสึคุโยะมากกว่า แล้วข้าน้อยก็เป็นกำลังใจ#nให้อย่างสุดหัวใจเลย ก็พอสึคุโยะอยู่บนรันเวย์แล้วมีออร่าสุดๆ ไปเลยยังไงล่ะ"
10051100-236 = "แต่ว่า..."
10051100-237 = ""
10051100-238 = ""
10051100-239 = "แต่ถึงจะคิดแบบนั้น ใจหนึ่งข้าน้อยก็อยากรั้งไว้อยู่ดี!"
10051100-240 = "ก็กิจกรรมของชมรมวิจัยศาสตร์นินจาที่มีสึคุโยะอยู่ด้วยมันสนุกมากๆ เลยนี่นา!"
10051100-241 = "เพราะงั้น เพราะแบบนั้น..."
10051100-242 = ""
10051100-244 = ""
10051100-245 = "ท่านหัวหน้า..."
10051100-246 = ""
10051100-248 = ""
10051100-249 = ""
10051100-250 = "ว่าแต่ ท่านสึคุโยะ"
10051100-251 = "ตอนนี้คนที่ลงไปนอนกองกับพื้นกำลังขยับตัวแล้วค่ะ!"
10051100-252 = ""
10051100-254 = "เฮือก...!"
10051100-255 = "ละ... ลืมเรื่องมือวางระเบิดไปเลยค่ะ...!"
10051100-256 = ""
10051100-258 = ""
10051100-259 = "แต่ว่า คนคนนี้... คุ้นๆ หน้าเหมือนเคยเห็นที่ไหนมาก่อนเลย...?"
10051100-260 = ""
10051100-262 = ""
10051100-263 = "อ๊ะ!"
10051100-264 = "นางแบบคนนั้นที่โดนลูกหลงจากการต่อสู้ในงานแฟชั่นโชว์ครั้งที่แล้วนี่นา!"
10051100-265 = "อิซุนะก็จำได้ค่ะ! คนนี้ถูกหามไปรักษาตัวจนท่านสึคุโยะต้องไปเป็นนางแบบแทน..."
10051100-266 = "ละ... แล้วทำไมนางแบบคนนี้ถึง...?"
10051100-267 = ""
10051100-269 = ""
10051100-271 = "โอยยย... ปวดหัวจัง..."
10051100-272 = ""
10051100-274 = ""
10051100-275 = "ดะ... เดี๋ยวนะ แล้วระเบิดของฉันล่ะอยู่ไหน?!"
10051100-276 = "พวกฉันยึดระเบิดนั้นมาแล้วค่ะ"
10051100-277 = "ทำไมคุณถึงมาก่อเรื่องแบบนี้ล่ะคะ?"
10051100-278 = "ทำไมน่ะเหรอ? ถามได้ดีเลย"
10051100-280 = "ทั้งหมดก็เพราะเธอยังไงล่ะ!"
10051100-281 = "คะ?!"
10051100-282 = "ก็วันนั้นเธอแย่งงานฉันไปนี่!"
10051100-283 = "รันเวย์ที่เธอได้เดิน ชุดที่ได้ใส่ สปอตไลท์ คำชื่นชมจากผู้คน..."
10051100-284 = "ทั้งหมดนั่นน่ะ! เดิมทีแล้วมันเป็นของฉันต่างหาก!"
10051100-285 = "พูดเหลวไหลอะไรน่ะ? ตอนนั้นสึคุโยะไม่ได้อยากทำงานนั้นแทนสักหน่อย"
10051100-286 = "งะ... เงียบไปเลยนะ!"
10051100-287 = "เอาเถอะ... แค่เสียระเบิดไปลูกเดียว ฉันไม่ท้อหรอก!"
10051100-288 = "ต้องพังกว่านี้อีก! ฉันจะพังงานแฟชั่นโชว์นี้ให้เรียบเลย!"
10051100-289 = "แค่นี้ก็พังไม่เป็นท่าแล้วนะ?"
10051100-290 = "หนวกหูน่า! ทางนี้ พวกปีศาจ!!"
10051100-291 = ""
10051100-295 = ""
10051100-298 = ""
10051100-300 = ""
10051100-301 = "พะ... พวกปีศาจกำลังบุกเข้ามาจากข้างนอกค่ะ!"
10051100-302 = "ยัยนี่จ้างพวกปีศาจเข้ามาเลยเหรอ...?"
10051100-303 = "เดี๋ยวนะ หรือว่าพวกปีศาจที่ไปก่อเรื่องที่ร้านขายผ้าตอนนั้นก็..."
10051100-304 = "พวกปีศาจที่โจมตีพนักงานส่งอาหารของไชน์แคทก็ด้วย...?"
10051100-305 = "[s1] \"จะว่าไป เหมือนนิยะก็เคยพูดทำนองนี้นะ\"\n[s2] \"นิยะก็บอกว่าพวกปีศาจก่อเรื่องกันหนักขึ้นเหมือนกัน\""
10051100-308 = "วะฮ่าฮ่า! ใช่แล้วละ!"
10051100-309 = "ใช่! ทั้งหมดเป็นแผนการของฉัน! ฉันเป็นคนจ้างพวกปีศาจไปเล่นงานเอง!"
10051100-310 = "จะได้เป็นการบ่อนทำลายงานแฟชั่นโชว์ครั้งนี้อย่างช้าๆ ยังไงล่ะ!!"
10051100-311 = "ทะ... ท่านหัวหน้าคะ พวกปีศาจมากันเยอะเกินไปแล้วค่ะ...!"
10051100-312 = "ไม่หรอก ไม่เป็นไรหรอกนะ สึคุโยะ"
10051100-313 = ""
10051100-315 = ""
10051100-316 = "ฝากเรื่องสั่งการได้ใช่มั้ย ท่านอาจารย์?"
10051100-317 = "[s] \"ได้อยู่แล้ว!\""
10051100-318 = "ดีละ ชมรมวิจัยศาสตร์นินจา!"
10051100-319 = ""
10051100-321 = ""
10051100-322 = ""
10051100-323 = "ออกปฏิบัติการได้!!"
