[translation]
10056060-1 = "#title;제6화;밀항자"
10056060-2 = "#place;협소한 선박 조타실 내부"
10056060-4 = "1;사유리;02\n5;코토네;04\n3;마키나;02\n#1;h\n#3;h\n#5;h\n#1;a\n#3;a\n#5;a\n#1;em;…\n#3;em;…\n#5;em;…\n#wait;2500"
10056060-5 = "1;사유리;02\n5;코토네;04\n3;마키나;04;……보물지도?\n#3;em;[?]"
10056060-6 = "#st;[0,0];instant;1;"
10056060-8 = "1;사유리;02\n5;코토네;04\n3;마키나;04\n#1;h\n#3;h\n#5;h\n#1;d\n#3;d\n#5;d\n#wait;1000"
10056060-9 = "3;코코로;02;응. 어제 의뢰를 한 그 학생에게 받았어.\n#3;a\n#3;greeting"
10056060-10 = "3;코코로;01;여기 그려진 포인트가 D.U.로부터 12해리 밖에 위치한 블루홀의 위치인데, 이곳에 오래 전 침몰한 화물선의 화물이 가라앉아 있대."
10056060-11 = "3;코코로;03;평범한 사람은 접근조차 어려운 곳이라, 우리가 해저에 묻힌 화물을 인양해주면 수수료만 받고 매입해 주겠다는데……"
10056060-12 = "3;코코로;02;다, 다들 어떻게 생각해……?"
10056060-13 = "3;코토네;01;블루홀에 가라 앉은 보물이라면 쉽게 인양하기 어려울 테니 우리에게 부탁을 한 것도 이해는 가지만……\n#3;em;…"
10056060-14 = "3;코토네;99;……역시 수상한 부분이 꽤 있네."
10056060-15 = "3;사유리;23;수상해~\n#3;jump\n#3;em;[한숨]"
10056060-16 = "3;코토네;02;우선. 이미 오래전에 침몰한 화물선의 위치를 알고 있었더라면, 진작에 인양 시도를 해도 이상하지 않았을 텐데."
10056060-17 = "3;코토네;01;이제 와서 우리에게 의뢰를 하는 이유가 뭐야?\n#3;em;[?]"
10056060-18 = "3;코코로;02;그, 그게 이 화물선에 실려 있었던 건, 당시에는 그리 인기가 없었던 캐릭터 피규어였다고 하는데……\n#3;stiff"
10056060-19 = "3;코코로;03;최근에 이 캐릭터의 인기가 급상승하면서 한정판 피규어의 가격도 덩달아 올라, 요새는 부르는 게 값일 정도래."
10056060-20 = "3;코코로;13;어제 제시한 수수료를 제외한 보수는 대략 이 정도……\n#3;greeting"
10056060-21 = "#st;[0,0];instant;1;"
10056060-23 = "3;코코로;13\n#3;d\n#wait;1000"
10056060-24 = "1;사유리;02\n5;마키나;02\n#1;h\n#5;h\n#1;a\n#5;a\n#wait;1000"
10056060-25 = "1;사유리;04\n5;마키나;17\n#1;h\n#5;h\n#1;em;[?!]\n#5;em;[?!]\n#1;shake\n#5;shake\n#wait;1500"
10056060-26 = "5;마키나;17;우와, 이게 얼마야? 빚을 모두 갚고도 남을 정도의 거금이잖아?\n#5;stiff"
10056060-27 = "1;사유리;19;……정어리맛 아이스크림 와플콘을 평생 먹고도 남을 돈이야."
10056060-28 = "3;코코로;02;응. 게다가 다른 화물도 가져오는 대로 전부 매입해 줄 테니, 값나가는 것들을 발견하면 모두 가져다 달라고 했는데……\n#1;hide\n#5;hide"
10056060-29 = "3;코코로;11;여, 역시 너무 수상한가……?\n#3;em;[땀]\n#3;stiff"
10056060-30 = "3;코토네;02;아니. 의뢰인의 말도 충분히 일리는 있어.\n#3;em;[반응]"
10056060-31 = "3;코토네;99;골동품의 가치라는 것도 시간에 따라 오르내리는 법이니 예전에는 굳이 인양할 가치가 없었던 물건을 인양하고 싶어질 수도 있지."
10056060-32 = "3;코토네;02;게다가 이런 정보는 아는 사람이 적으면 적을수록 유리하기 때문에 큰 기업체에 견적을 부탁하는 것도 부담스러웠을 테니……"
10056060-33 = "3;코토네;03;의뢰인의 태도가 아주 이해가 가지 않는 것도 아니야."
10056060-34 = "3;마키나;14;그럼 고민할 필요가 없잖아? 바로 가서 준비하고 물건을 쓸어 담을 준비를 하자고!\n#3;hophop\n#3;em;[재잘]"
10056060-35 = "#st;[0,0];instant;1;"
10056060-37 = "3;마키나;14\n#3;d\n#wait;1000"
10056060-38 = "3;코코로;03\n#3;a\n#wait;1000"
10056060-39 = "5;코토네;02;하지만 코코로도 알고 있잖아? 블루홀을 탐사하는 것은 다른 지형을 탐사하는 것보다 훨씬 위험하다는 걸.\n#5;em;[?]\n#3;m1\n#5;al"
10056060-40 = "3;코코로;10;윽……\n#3;stiff"
10056060-41 = "5;코토네;01;심도를 확인하기 어렵고, 시야 확보도 어렵고."
10056060-42 = "3;사유리;10;루스카가 살고 있을지도 몰라~\n#3;closeup\n#3;em;[반짝]\n#5;hide\n#fontsize;80"
10056060-43 = "3;마키나;04;아니, 그건 [ruby=UMA]미확인 생명체[/ruby]잖아.\n#3;stiff"
10056060-44 = "#st;[0,0];instant;1;"
10056060-46 = "1;코코로;10\n5;코토네;99\n#3;hide\n#1;h\n#5;h\n#5;em;[한숨]\n#wait;1500"
10056060-47 = "1;코코로;10\n5;코토네;01;여하튼 코코로가 이렇게 다급해 보이는 건 처음보는 것 같은데."
10056060-48 = "5;코토네;02;어제 아일랜드에서 무슨 소리라도 들은 거야?"
10056060-49 = "#st;[0,0];instant;1;"
10056060-51 = "1;코코로;10\n5;코토네;02\n#1;h\n#5;h\n#1;m3\n#5;dr\n#1;em;…\n#wait;2500"
10056060-52 = "1;코코로;06;그게……"
10056060-53 = "#st;[0,0];instant;1;"
10056060-55 = "1;코코로;06\n#1;stiff\n#wait;1500"
10056060-56 = "1;코코로;08;이번에 빚을 갚지 못하면 부를 폐부하게 될지도 몰라서."
10056060-57 = "3;마키나;04;폐부라면…… 더 이상 다이빙을 할 수 없다는 말이야?\n#1;hide\n#5;hide\n#3;jump\n#3;em;[!]"
10056060-58 = "3;코코로;06;응. 아마 다른 동아리처럼 수상 활동을 해야 하겠지."
10056060-59 = "3;사유리;06;그건 싫은데……"
10056060-60 = "3;코토네;08;……왜 그랬는지 이해가 가네.\n#3;em;[한숨]"
10056060-61 = "3;코코로;08;응. 물 밖으로…… 나가고 싶지는 않으니까."
10056060-62 = "3;코코로;08;게다가 항해를 마쳤는데도, 물 속에서 아무런 성과도 얻지 못하고 돌아가게 된다면……\n#3;stiff"
10056060-63 = "3;코코로;06;……을 마주할 면목도 없고.\n#fontsize;50"
10056060-64 = "[s] \"누구에게 면목이 없는데?\""
10056060-65 = "3;코코로;02;그야……"
10056060-66 = "3;코코로;04;우, 우, 우, 우앗?!\n#3;shake\n#3;em;[?!]"
10056060-67 = "3;코코로;09;서, 서, 선생님?! 어, 언제부터 여기에 계셨었나요?\n#3;stiff\n#3;m2"
10056060-68 = "[s] \"처음부터……?\""
10056060-69 = "3;마키나;04;이, 이 배에는 어째서 타고 있는 거야?"
10056060-70 = "[s1] \"어제 시간이 너무 늦어서 여기 선실에서 잠깐 눈을 붙였는데—\"\n[s2] \"일어나 보니 배가 출발하고 있어서……\""
10056060-73 = "3;마키나;28;이런, 출발하기 전에 하부 선실 확인하는 걸 깜박했더니……\n#3;em;[땀]"
10056060-74 = "3;코코로;10;어, 어쩌지……? 지, 지금이라도 배를 돌려야 하나……?"
10056060-75 = "[s3] \"이야기는 이미 들었어.\"\n[s4] \"보물을 찾으러 간다고 하지 않았어?\""
10056060-78 = "3;코코로;04;하, 하지만 먼 바다에 나가는 건 여러모로 위험할지도 모르는데……\n#3;jump"
10056060-79 = "3;코코로;08;그, 그리고 선생님의 시간을 생각 이상으로 빼앗게 될 지도 모르고……"
10056060-80 = "[s] \"괜찮아. 오늘은 특별한 일정도 없었거든.\""
10056060-81 = "#st;[0,0];instant;1;"
10056060-84 = "[ns5] \"그리고 작업 이외의 다이빙을 하는 모습도 보고 싶은데.\"\n[ns6] \"이번만 허락해 주면 안 될까……?\""
10056060-87 = "3;코코로;10;으읏…… 알겠습니다.\n#3;stiff"
10056060-88 = "3;코코로;08;대, 대신 선생님은 배 안에만 계셔야 해요!\n#3;hophop"
10056060-90 = "3;코코로;02;일정을 고려하면 오늘 자정까지는 다이빙을 마치고 돌아갈 수 있을 것 같은데……\n#3;a\n#3;greeting\n#fontsize;50"
10056060-91 = "3;코코로;00;잘 하면 몰래 트라이던트의 순찰 구역을 몰래 빠져나왔다는 사실을 들키지 않고 돌아갈 수 있을지도……"
10056060-92 = "[s] \"왜 보고하지 않고 몰래 빠져나온 거야?\""
10056060-93 = "#st;[0,0];instant;1;"
10056060-95 = "3;코코로;04\n#3;em;[!]\n#3;jump\n#wait;1500"
10056060-96 = "3;코코로;08;그건…… 아일랜드가 이 계획을 허가해 주지 않을 거라고 생각했거든요.\n#3;stiff"
10056060-97 = "3;코코로;08;안 그래도 잔뜩 빚을 지고 있는 상태인데, 보물지도 같은 희박한 가능성을 근거로 멀리 다이빙을 나가겠다고 요청을 해도……"
10056060-98 = "3;코코로;10;괜히 기름값만 낭비한다고 한 소리 들을 것 같아서요."
10056060-99 = "#st;[0,0];instant;1;"
10056060-101 = "3;코코로;10\n#3;em;…\n#wait;2500"
10056060-102 = "3;코코로;06;……실망스러운 시선은 더 이상 받고 싶지 않아요."
10056060-103 = "[s] \"아일랜드에 진지하게 도움을 구해본 적은 없어?\""
10056060-104 = "3;코코로;02;네? 따, 딱히 먼저 도움을 구한 적은 없지만……\n#3;em;[?]"
10056060-105 = "3;코코로;08;괜히 어려운 상황을 드러내서, 배에서 쓸모없는 사람 취급당하는 건 싫은 걸요."
10056060-106 = "3;마키나;09;맞아. 안 그래도 생산성 없는 취미 활동에 비싼 장비를 낭비한다고 싫은 소리를 듣는 마당에.\n#3;em;[속상함]"
10056060-107 = "3;코토네;01;거절당할 일을…… 굳이 물을 필요는 없다고 생각했어."
10056060-108 = "[s7] \"확실히 불편한 점을 드러내는 건 누구에게나 두려운 일이지.\"\n[s8] \"약한 모습을 숨기는 것도 이해가 가.\""
10056060-111 = "#st;[0,0];instant;1;"
10056060-114 = "[ns] \"하지만 때로는……\""
10056060-116 = "3;사유리;02;……선생님, 괜찮아?\n#3;em;[?]"
10056060-117 = "3;사유리;01;얼굴이 포도맛 아이스크림처럼 보라색으로 바뀌었는데."
10056060-118 = "[s9] \"미안. 사실 이런 작은 배를 타는 건 오랜만이라……\"\n[s10] \"원래, 이렇게 많이 흔들렸던가……?\""
10056060-121 = "3;마키나;02;응? 이만하면 별로 흔들리는 것도 아닌데."
10056060-122 = "3;마키나;13;선생님도 보기보다 멀미에 약하네. 하하.\n#3;em;[재잘]"
10056060-123 = "[s] \"……뭔가 멀미약 같은 건 없니?\""
10056060-124 = "3;코토네;02;멀미약은 없지만……\n#3;em;[반응]"
10056060-125 = "3;코토네;03;혹시 괜찮으면 이거라도 씹을래?\n#3;greeting"
10056060-126 = "#st;[0,0];instant;1;"
10056060-129 = "[ns] \"이거, 도대체 무슨 맛 껌이야?!\""
10056060-130 = "3;사유리;10;그거 말린 다시마야~\n#3;jump"
10056060-131 = "3;사유리;08;바다 냄새가 진한 제품이라 나는 좋아해.\n#3;closeup\n#3;em;[반짝]"
10056060-132 = "#st;[0,0];instant;1;"
10056060-134 = "3;사유리;08\n#3;closeup\n#3;d\n#wait;1000"
10056060-136 = "[ns] \"우욱……\""
10056060-137 = "3;마키나;18;우왓, 큰일이다.\n#3;shake\n#3;em;[?!]"
10056060-138 = "3;마키나;04;사유리, 양동이 가져와. 양동이!\n#3;hophop"
10056060-139 = "#st;[0,0];instant;1;"
10056060-141 = "3;마키나;04\n2;사유리;04\n#2;h\n#3;h\n#2;ar\n#wait;500"
10056060-147 = "#na;(이후 한동안 멀미에 시달리며, 블루홀을 향한 항해를 계속했다.)"
10056060-150 = "1;나나미 교룡;01\n#1;black"
10056060-152 = "1;나나미 교룡;01\n5;수상한 오디세이아 학생;01\n#1;h\n#5;h\n#1;black\n#5;al\n#wait;1000"
10056060-153 = "5;수상한 오디세이아 학생;03;돌아왔습니다, 용왕님.\n#5;greeting"
10056060-154 = "#na;???;음, 수고가 많았다.\n#1;em;[반응]"
10056060-155 = "#na;???;헤어졌던 옛 가신들을 찾느라 한동안 신경 쓰지 못했었는데—"
10056060-156 = "#na;???;표정을 보아하니 좋은 소식을 들고 온 모양이구나."
10056060-157 = "5;수상한 오디세이아 학생;08;네, 용왕님.\n#5;em;[음표]"
10056060-158 = "5;수상한 오디세이아 학생;02;용왕님의 용궁에 어울리는 보물을 인양할 재원을 구했습니다.\n#5;m4"
10056060-159 = "1;나나미 교룡;01\n#na;???;호오, 흥미롭구나. 전에는 본 적이 없는 얼굴인데.\n#1;m2\n#1;h\n#1;black"
10056060-160 = "#st;[0,0];instant;1;"
10056060-162 = "1;나나미 교룡;01\n5;수상한 오디세이아 학생;02\n#1;h\n#5;h\n#1;black\n#1;greeting\n#wait;1500"
10056060-163 = "#na;???;깊은 물을 자유로이 오가는 고래의 자손들이라.\n#1;em;…"
10056060-164 = "5;수상한 오디세이아 학생;03;그들은 현재 곤경에 빠져 있으니, 용왕님께서 지금과 같이 자비를 베풀어 주신다면 분명 충실한 심복이 되어 줄 것입니다."
10056060-165 = "#na;???;그야 물론이지. 새로운 가신은 언제나 환영이니까.\n#1;em;[재잘]"
10056060-166 = "#na;???;그럼 손님을 맞을 준비를 해야겠구나."
10056060-167 = "#st;[0,0];instant;1;"
10056060-169 = "1;나나미 교룡;01\n5;수상한 오디세이아 학생;03\n#1;m3\n#5;dr\n#1;h\n#5;h\n#1;black\n#wait;1000"
10056060-170 = "1;나나미 교룡;01\n#na;???;자, 어서 오거라. 새로운 가신들이여.\n#1;closeup\n#1;black"
10056060-172 = "#na;???;여의 용궁에!"
