[translation]
10052010-1 = "Binah, the Contemplator of Disparity"
10052010-2 = "Momoi, checking in!"
10052010-3 = "That was...quite the drop."
10052010-4 = "Ugh, my head is still spinning... One minute..."
10052010-6 = "[ns] \"Where...are we?"
10052010-9 = "What do you mean? Look around you!"
10052010-10 = "If you use your eyes..."
10052010-11 = "Oh, boy... How can I even BEGIN to explain this...?"
10052010-12 = "Hm? Isn't it just a big pit? A dungeon? A hub? A well? A hollow?"
10052010-13 = "Those are ALL gross oversimplifications, Momoi."
10052010-14 = "S-Simple names are the best, Kei! Nothing \"gross\" about them!"
10052010-19 = "That...was loud."
10052010-20 = "That was mechanical, artificial. Something is moving down there. Operating."
10052010-21 = "[s] \"You think it's Binah?"
10052010-22 = "...Likely, yes."
10052010-27 = "Has everyone landed safely? I'm detecting Binah's signal. However... "
10052010-28 = "Is there an issue, Himari?"
10052010-29 = "Its signal is considerably weaker than those of the other prophets. We can speculate on why, but..."
10052010-30 = "I know why! It's sleeping!"
10052010-31 = "...That's certainly a possibility. "
10052010-32 = "Or it could also be that this pit is so deep that it's muffling Binah's signal."
10052010-33 = "[s] \"But why is this only happening here?\""
10052010-34 = "We have no present way of knowing, but we should proceed with caution."
10052010-35 = "Hm? What do you mean, Rio?"
10052010-36 = "Binah's existence predates Decagrammaton's emergence. "
10052010-37 = "The Abydos Student Council allegedly researched Binah, but they've since lost any pertinent information."
10052010-38 = "In fact, we STILL don't know why an AI structure like Binah was operating in the Abydos Desert."
10052010-39 = "So, you two are saying that Binah is a bit...odd?"
10052010-40 = "Indeed, but we are also speculating. There must be a reason why Binah was placed separately in a place like this."
10052010-41 = "Whatever the reason is, I think it's time we woke Binah up."
10052010-42 = "\"Wake\"...? I like that word. I was thinking of doing something similar."
10052010-43 = "Yuzu? If I specify the angle and velocity, will you please fire one of your grenades accordingly?"
10052010-44 = "Wh-What?! A grenade...? Why...?"
10052010-45 = "With a predictable trajectory and specific attention to acoustics, we should be able to estimate the rough size and depth of that hole. "
10052010-46 = "I've already thoroughly analyzed the specifications of your gun, Yuzu. "
10052010-47 = "Since grenades are significantly slower than bullets, we should be able to arc it into a terminal, free-falling state."
10052010-48 = "The projectile will also explode when it lands, which will give us further data. "
10052010-49 = "I sent observation drones to your location. They should be arriving now."
10052010-56 = "I'll shoot, then!"
10052010-63 = "[ns] \"Uh... Did you learn anything?\""
10052010-64 = "...It's deeper than I expected. To give you a rough idea of the size, the width at the bottom is—"
10052010-65 = "Now, now. Let's put it simply. How about we just say that it's bigger than what we imagined?"
10052010-71 = "?! Everyone, watch out! We've detected seismic activity!"
10052010-78 = "S-Sensei! Rio! Himari!"
10052010-79 = "Something is moving at the bottom of the pit!"
10052010-80 = "I-I think it's Binah!"
10052010-81 = "I knew it... I woke it up... Augh..."
10052010-82 = "[s] \"Yeah. That's what it looks like.\""
10052010-83 = "All according to plan, I'd say."
10052010-84 = "[ns] \"This area...is ours to conquer!\""
10052010-85 = "...It's far too early for a line like that."
