[translation]
1005305-1 = "วัฒนธรรมการเชียร์ที่มีวิจารณญาณ"
1005305-2 = "ห้องพักผ่อนชาเล่ต์"
1005305-6 = "สวัสดีค่ะคุณครู ฉันมีเรื่องจะสอบถามเกี่ยวกับงานฮาโลเฟสติวัลนิดหน่อยค่ะ"
1005305-7 = "เรื่องคำขอปรับเปลี่ยนตารางเข้าเวรและคำขออื่นๆ..."
1005305-8 = "อ๊ะ คุณครูกำลังพักผ่อนอยู่เหรอคะ ฉันมารบกวนคุณครูรึเปล่า..."
1005305-9 = "[s] \"ไม่หรอก ครูกำลังจะกลับไปทำงานพอดี\""
1005305-10 = "งั้นเหรอคะ ถ้างั้นรบกวนตรวจสอบเอกสารนี่ให้หน่อยนะคะ"
1005305-11 = "ว่าแต่คุณครูดูอะไรอยู่เหรอคะ?"
1005305-12 = "<...ขณะที่ฉันกำลังรายงานอยู่นี้ แบตเตอร์ของมิลเลเนียมก็เข้าประจำที่แล้วค่ะ...>"
1005305-13 = "ถ่ายทอดสดการแข่งขันเบสบอลของทีมมิลเลเนียม..."
1005305-14 = "พอนึกดูแล้ววันนี้มีการแข่งคัดเลือกระดับภูมิภาครอบแรกด้วยนี่นา"
1005305-15 = "[s] \"การแข่งอินเตอร์ไฮเบสบอลแข่งแยกจากงานฮาโลเฟสติวัลเหรอ?\""
1005305-16 = "ค่ะ ก็เพราะเบสบอลเป็นกีฬายอดฮิตในคิโวทอสเลยนี่คะ"
1005305-17 = "งานฮาโลเฟสติวัลจะรวมการแข่งขันหลายๆ รายการเอาไว้ แต่การแข่งอินเตอร์ไฮจะจัดการแข่งขัน#nแยกออกมา เพื่อคัดเลือกโรงเรียนตัวแทนด้วยค่ะ"
1005305-18 = "แต่อย่างที่ฉันเคยบอกไปแหละค่ะ ทีมเบสบอลของโรงเรียนมิลเลนียม ถือว่าเป็นทีมที่อ่อนที่สุดจน#nมักจะถูกคัดออกในรอบคัดเลือกบ่อยๆ ค่ะ"
1005305-19 = "ฉันเลยไม่ค่อยได้ดูการแข่งเบสบอลบ่อยเท่าไรค่ะ"
1005305-23 = "[ns1] \"ครูคงใช้เวลาตรวจเอกสารนานหน่อยนะ...\"\n[ns2] \"ครูคงใช้เวลานานนิดหน่อย ยูกะรอได้รึเปล่า?\""
1005305-24 = "ไม่เป็นไรค่ะ ฉันรอได้ค่ะ"
1005305-25 = "ค่ะ รอได้ค่ะ"
1005305-26 = "ระหว่างที่รอคุณครู ฉันจะนั่งดูการแข่งไปก็แล้วกันค่ะ"
1005305-28 = "(หลังจากนั้นไม่นาน...)"
1005305-30 = "<พิชเชอร์ขว้างออกไปแล้วค่ะ... เอ้าต์!>"
1005305-31 = "<อา... แบตเตอร์ของทางมิลเลเนียม เอ้าต์ทั้ง 3 ครั้งเลยนะคะ!>"
1005305-32 = "อึก..."
1005305-33 = "[s] \"มีอะไรรึเปล่า?\""
1005305-34 = "ปะ... เปล่าค่ะ ฉันเผลอคิดเรื่องอื่นนิดหน่อยค่ะ... ฮะฮะ..."
1005305-35 = "อย่าใส่ใจเรื่องเล็กน้อยเลยค่ะ"
1005305-37 = "<บุกตอนสิ้นสุดอินนิ่งที่ 5 แบตเตอร์ของมิลเลเนียมต้องคิดหนักแล้วค่ะ...>"
1005305-38 = "<พิชเชอร์ขว้างลูกออกไปแล้วค่ะ!>"
1005305-39 = "...!!"
1005305-40 = "<บอลลอยโด่งขึ้นไป... ทู เอ้าต์! ตามด้วย... ทรี เอ้าต์!>"
1005305-41 = "อะไรเนี่ย! บุกติดต่อกันเลยเหรอ...!"
1005305-42 = "[s] \"มีอะไรเหรอ?\""
1005305-43 = "อ๊ะ ขอโทษด้วยค่ะ ฉันเผลอเสียงดังไปซะแล้ว..."
1005305-44 = "[s3] \"ไม่ต้องขอโทษหรอก\"\n[s4] \"เวลาอินหนักๆ ใครๆ ก็เป็นได้น่า\""
1005305-45 = "มะ...ไม่ได้ค่ะ!"
1005305-46 = "มะ... ไม่ใช่อย่างนั้นสักหน่อยค่ะ!"
1005305-47 = "การอินกับผลการแข่งขันเกินไปจนคุมตัวเองไม่อยู่ ไม่ใช่วิธีการเชียร์ที่ถูกต้องเลยค่ะ!"
1005305-48 = "เราต้องคอยเชียร์และให้กำลังใจนักกีฬาโดยไม่ยึดติดกับผลแพ้ชนะ เพื่อให้สนุกกับกีฬาได้อย่าง#nสร้างสรรค์สิคะ"
1005305-49 = "ถ้าทีมที่เชียร์แพ้ก็อาจจะอารมณ์เสียนิดหน่อย แต่ก็ไม่ควรยึดติดกับเรื่องการแพ้ชนะมากไปค่ะ"
1005305-50 = "[s] \"ถ้ายูกะพูดแบบนั้น ก็คงจะเป็นแบบนั้นนั่นแหละ...\""
1005305-52 = "ทำไมถึงตีไม่ได้สักลูกเลยเนี่ย...?"
1005305-53 = "มีโอกาสหวดลูกได้ตั้งหลายครั้งแล้วแท้ๆ...!"
1005305-54 = "<โรงเรียนมิลเลเนียมบุกที่ท้ายอินนิ่งที่ 7 ตอนนี้แบตเตอร์กำลังเจอสถานการณ์หน้าสิ่วหน้าขวาน เอ้าต์ 2 จาก 3 และนี่คือลูกตัดสินแล้วค่ะ...>"
1005305-55 = "ฮือ... ตีให้โดนสักลูกเหอะ ขอร้อง..."
1005305-56 = "<พิชเชอร์เตรียมขว้างลูก... ขว้างออกไปแล้วค่ะ!>"
1005305-60 = "<บอลถูกตีออกไปไกลลิ่วเลยค่ะ! อะ... ออกนอกกำแพงไปแล้วค่ะ!>"
1005305-61 = "เยส! แบบนั้นแหละๆ โฮมรัน! โฮมรัน!"
1005305-62 = "คุณครูเห็นรึเปล่าคะ? เมื่อกี้แบตเตอร์โรงเรียนเราทำโฮมรันได้! พลิกสถานการณ์ได้เลิศสุดๆ ไปเลย! "
1005305-63 = "นั่นมันลูกฟาสต์บอลที่เร็วมากจนมองตามไม่ทันเลยแท้ๆ แต่กลับตีลูกนั้นได้... สุดยอดเลยใช่มั้ยคะ?"
1005305-64 = "สมกับเป็นชมรมเบสบอลของเราจริงๆ! ฉันเชื่อฝีมือพวกเธออยู่แล้ว!"
1005305-65 = "ลุยไปเลย! มิลเลเนียม! พุ่งทะยานไปเลย!"
1005305-66 = "[ns] \"คือว่า คุณยูกะ...?\""
1005305-68 = "[ns] \"นั่งจ่อติดทีวีเกินไปแล้ว...\""
1005305-72 = "เอ่อ..."
1005305-73 = "คะ... คือว่าเมื่อกี้นี้..."
1005305-74 = "ฉันเผลอจดจ่อกับการแข่งมากไปหน่อย..."
1005305-75 = "คือว่าอย่าเข้าใจผิดนะคะ! ปกติฉันไม่ได้อินกับการแข่งขนาดนี้หรอกค่ะ!"
1005305-76 = "ดะ...เดี๋ยวสิคะ...! ทำไมถึงขำแรงแบบนั้นคะ!"
1005305-77 = "ก็บอกว่าคุณครูเข้าใจผิดยังไงล่ะคะ ฟังฉันอธิบายหน่อยสิคะ!"
1005305-79 = "(คุณครูก็นั่งปลอบยูกะที่ลนลานทำอะไรไม่ถูกอยู่พักใหญ่ จากนั้นทั้งคู่ก็มานั่งดูการแข่งเบสบอล#nด้วยกัน)"
1005305-80 = "(...และสุดท้ายชมรมเบสบอลมิลเลเนียมก็เอาชนะการแข่งขันมาได้...)"
