[translation]
10050005-1 = "#title;프롤로그;No Risk, No Return."
10050005-2 = "#place;붉은겨울 학원 도서관"
10050005-3 = "1;모미지;06\n5;메루;15\n#1;h\n#5;h\n#1;a\n#5;a\n#1;em;…\n#5;em;…\n#wait;2500"
10050005-4 = "1;모미지;06\n5;메루;15\n#1;h\n#5;h\n#1;falldownL\n#5;falldownR\n#wait;1500"
10050005-5 = "#1;hide\n#5;hide\n#bgshake\n#wait;1500"
10050005-6 = "#wait;1500"
10050005-7 = "#na;모미지;메루 선배, 괜찮아요……?"
10050005-8 = "#na;메루;모미지 눈에는 이게 괜찮은 걸로 보여……?"
10050005-9 = "#na;모미지;아니긴 하죠……."
10050005-10 = "3;메루;01;……한 가지 알게 된 것이 있어.\n#3;greeting\n#3;a"
10050005-11 = "3;모미지;02;뭔데요, 선배?\n#3;a\n#3;greeting\n#3;em;[?]"
10050005-12 = "3;메루;02;사람이, 3일 정도 굶으면 의외로 배고픔을 안 느끼게 되는구나……."
10050005-13 = "3;모미지;99;그 대신 몸에 힘이 하나도 안 들어가지만요…….\n#3;em;[땀]"
10050005-14 = "3;모미지;02;그리고 그건 정말 잠깐 그러고 마는 거지, 조금만 더 굶으면 음식 생각밖에 안 나게 될걸요?"
10050005-15 = "3;메루;15;이미 그러고 있으니까 괜찮지 않을까…….\n#3;stiff"
10050005-16 = "3;모미지;04;안 괜찮아요……."
10050005-17 = "5;메루;02;공용 급식소 내부 공사…… 언제 끝난대?\n#3;m1\n#5;al\n#5;em;[?]"
10050005-18 = "3;모미지;02;내일이래요. 일단은."
10050005-19 = "5;메루;01;그러면 이 참극도 내일이면 끝나겠네……. 다행이야…….\n#5;em;[음표]"
10050005-20 = "3;모미지;01;덧붙여서, 어제도 내일 끝난다고 말했더랬죠……."
10050005-21 = "5;메루;04;……용역부 애들, 또 파업했대?\n#5;m4"
10050005-22 = "3;모미지;99;안 봐도 뻔하죠……. \n#3;em;[한숨]"
10050005-23 = "5;메루;05;……일주일은 더 걸리겠구만……."
10050005-24 = "3;모미지;04;우리, 이제 정말로 뭔가를 해야 하지 않을까요……?\n#3;m3\n#5;dr\n#3;em;[땀]"
10050005-25 = "3;모미지;04;도서관에 남은 부원들이, 바닥에 그대로 엎어져서, 좀비 같은 눈빛으로 서로를 쳐다보기 시작했는데요…….\n#3;stiff"
10050005-26 = "3;메루;05;뭔가를 안 해서 이렇게 된 게 아니라, 뭔가를 해서 이렇게 된 거잖아……."
10050005-27 = "3;메루;05;모든 건, 책도 안 팔리고 웹사이트 유료 구독자 수도 늘어나지 않아서 이렇게 된 거니까!\n#3;closeup\n#fontsize;80"
10050005-28 = "3;메루;15;아, 힘도 없는데 너무 큰소리쳤다…….\n#3;stiff"
10050005-29 = "#st;[0,0];instant;1;"
10050005-30 = "#clearST"
10050005-31 = "3;메루;15\n#3;falldownL\n#wait;1500"
10050005-32 = "#3;hide\n#bgshake\n#wait;1500"
10050005-33 = "3;모미지;06;우우우…… 이게 다 동아리 활동비를 제때 지급해 주지 않는 사무국 때문이에요…….\n#3;a\n#3;em;[훌쩍]"
10050005-34 = "3;모미지;04;책이라도 팔아서, 활동 비용을 충당하려 했지만 결국 실패하고 말았죠……."
10050005-35 = "3;모미지;04;지식해방전선의 앞날은, 그야말로 중요 페이지가 잘려 나간 한정 애장판 동인지의 운명처럼 캄캄해지고 말 거예요…….\n#3;stiff"
10050005-36 = "3;모미지;06;이것으로 문명은 암흑 속에 잠기고, 인류는 마침내 퇴보한 끝에…….\n#3;em;[세로선]"
10050005-37 = "#st;[0,0];instant;1;"
10050005-38 = "#clearST"
10050005-39 = "#all;hide"
10050005-40 = "#wait;1000"
10050005-41 = "3;야쿠모;01\n#3;black"
10050005-42 = "3;야쿠모;00;어디 보자, 잘 지냈나요. 지식해방전선? 반가우면서도 반갑지 않은 출판부의 책임자, 등장입니다. 힛. 힛. 히.\n#3;a\n#3;em;[음표]"
10050005-43 = "4;타카네;07\n3;야쿠모;00\n#na;타카네;여전히 볼품 사나운 모습이로군요, 메루리 씨. 익히 알고 있을 것이라고 생각했습니다만, 도서관 바닥은 침대가 아니랍니다? 적당히 그만 일어나 주세요.\n#4;h\n#4;a\n#3;m2"
10050005-44 = "4;타카네;07\n3;야쿠모;00\n#na;메루;그래, 그래……. 뭐든 말해 봐……."
10050005-45 = "4;타카네;15;네……? 메루리 씨가 이렇게 무미건조한 대응을?! 괜찮아요, 메루리 씨? 어디 큰일 난 거 아니죠!?\n#4;shake\n#4;em;[?!]"
10050005-46 = "#all;hide"
10050005-47 = "3;모미지;06;큰일, 이라면 큰일인데요. 야쿠모 선배, 타카네 선배……."
10050005-48 = "3;야쿠모;02;흐음? 이러면 계획했던 것과는 뭔가 다른 전개를 맞게 되는 것 같은데, 그 큰일이란 건 뭔가요. 모미지?"
10050005-49 = "3;모미지;04;……뭔가 먹을 거, 없으세요……?\n#3;em;[땀]\n#3;stiff"
10050005-50 = "4;타카네;17\n2;야쿠모;02\n#na;야쿠모&타카네;네……?\n#3;hide\n#2;h\n#4;h"
10050005-51 = "#all;hide"
10050005-52 = "#na;메루;으악! 아아악! 배 아파!\n#bgshake"
10050005-53 = "3;타카네;05;3일이나 굶은 위에 갑자기 음식물을 급하게 집어넣으니, 경련이 일어나잖아요. 자, 여기 물이라도 마시도록 하세요.\n#3;a\n#3;greeting\n#3;em;[한숨]"
10050005-54 = "3;모미지;07;감사합니다. 야쿠모 선배, 타카네 선배……. 한 때는 정말로 어떻게 되는 건가 했어요.\n#3;a"
10050005-55 = "5;야쿠모;03;무슨 말씀을요. 어려울 때는 서로 돕고 살아야죠. 물론 비용은 확실하게 청구하겠지만요? 힛. 힛. 히.\n#3;m1\n#5;al\n#5;em;[반짝]"
10050005-56 = "#all;hide"
10050005-57 = "3;메루;04;네 비용 청구는 뭔가 무섭긴 한데……. 아냐, 됐어. 죽어가던 동아리 하나 살려준 건데, 이번만은 어쩔 수 없겠지…….\n#3;greeting\n#3;a"
10050005-58 = "1;모미지;02\n5;야쿠모;02;문제의 원인이 동아리 활동비 지급 지연에 있다는 것은 알았습니다. 그런데, 그런 것 치고도 상태가 상상 이상으로 심각하던데요?\n#3;hide"
10050005-59 = "1;모미지;04;그게…… 이렇게 된 거, 출판 일정을 당겨서라도 일단 활동비를 벌자는 생각에……. 조금, 이래저래 무리를 했더니…….\n#1;em;[땀]"
10050005-60 = "3;타카네;02;아, 저번 주에 출판부로 가져온 긴급 원고가 그 건이었군요. 어쩐지 인쇄 비용까지 저희에게 외상으로 부탁하셨던 것도……\n#1;hide\n#5;hide"
10050005-61 = "3;메루;05;……그런 일을 하지 말아야 했는데, 그 사실을 몰랐어…….\n#3;em;[속상함]"
10050005-62 = "1;야쿠모;01;그래서 우리 출판부는 그 외상 대금의 이자를 받으러 온 김에, 이런 현실을 마주하게 된 것이라는 결론이겠네요.\n#1;ar\n#3;m5"
10050005-63 = "1;야쿠모;10;자, 그러면 이자 주세요. 이자.\n#1;em;[음표]"
10050005-64 = "3;메루;05;지금 우리 처지를 봤잖아! 당장 먹을 것도 없는 처지에 무슨 이자야! 배 째!\n#3;jump"
10050005-65 = "1;야쿠모;02;정말 째도 돼요?\n#1;m2"
10050005-66 = "3;메루;04;……할 거야?\n#3;em;[땀]"
10050005-67 = "1;야쿠모;09;네. 그리고 이자도 받을 거고요."
10050005-68 = "3;메루;10;악마다……. 여기 악마가 있어!\n#3;stiff"
10050005-69 = "#all;hide"
10050005-70 = "3;타카네;02;그렇지만 그것도 이상하군요. 메루리 씨. 아무리 당신의 작품이 대개 안 팔릴 만한 물건이고, 제멋대로 만들기 일쑤인 데다.\n#3;em;[?]"
10050005-71 = "3;타카네;01;시장의 반응 같은 건 거의 신경도 안 쓰는, 안하무인격인 이야기들이기는 하지만……."
10050005-72 = "5;메루;09;이자 받으러 온 거야, 사람 속 긁으러 온 거야? 하나만 해!\n#3;m2\n#5;al\n#5;em;[스팀]\n#5;hophop"
10050005-73 = "3;타카네;05;사람 말을 끝까지 들어요! 어쨌든 코어 팬들이 없는 것은 아닌 데다, 모미지 씨라는 우수한 편집자가 있을 텐데, 식비를 확보할 수 없을 정도로 팔리지 않았다니요?\n#3;m3\n#5;dr\n#3;jump"
10050005-74 = "3;모미지;06;그게…… 저희도, 이렇게 안 팔릴 줄은 몰랐어요…….\n#3;em;[세로선]"
10050005-75 = "3;야쿠모;02;……혹시 남은 재고 있나요? 좀 보죠."
10050005-76 = "#all;hide"
10050005-77 = "#wait;1000"
10050005-78 = "#wait;2500"
10050005-79 = "#all;hide"
10050005-80 = "3;메루;04;어, 어때……?\n#3;a\n#3;em;[?]"
10050005-81 = "3;타카네;99;……일단, 원인은 알았어요.\n#3;a\n#3;greeting"
10050005-82 = "3;모미지;04;뭐, 뭔가요……?\n#3;a\n#3;em;[땀]"
10050005-83 = "3;타카네;02;메루리 씨. 당신의 원고는 본디 제멋대로이고 안하무인격인 데다, 읽는 사람보다 창작자 본인을 우선시하는 부분이 엄청나게 강하죠."
10050005-84 = "3;타카네;01;그 부분이 거꾸로 작용해서, 나름의 좁고 깊은 팬층을 형성한 부분도 있었지만, 그럼에도 대중성을 확보하는 데에는 어려움이 있었어요."
10050005-85 = "3;타카네;09;하지만 이건 뭔가요! 메루리 씨 특유의 깊은 맛도 나지 않고, 어정쩡하게 대중성을 따르려다가 이것도 저것도 안 되고 말았잖아요!\n#3;em;[빠직]\n#3;jump"
10050005-86 = "3;타카네;05;이래서는 코어 팬도 대중도, 어느 쪽 하나 못 잡는 반쪽짜리 원고밖에 되지 않아요! 평점 5점에 2점……. 아뇨, 1.5점 주겠어요!"
10050005-87 = "3;타카네;09;아뇨, 메루리 씨는 대답하지 않아도 돼요. 어떻게 된 건가요, 모미지 씨?"
10050005-88 = "1;모미지;04;그, 그게. 이번에는 뭔가 다른 걸 만들어야 한다고, 정말로 먹힐 만한 걸 해야 한다고…….\n#1;ar\n#3;m5\n#1;em;[속상함]"
10050005-89 = "1;모미지;04;거기에다 마감을 당긴 것 때문에, 메루 선배는 또다시 폭주해 버리고, 제가 편집이나 첨삭을 할 물리적인 시간 자체가…….\n#1;stiff"
10050005-90 = "3;타카네;16;……네. 그건 확실히 납득할 만한 이유네요……. 또 다른 문제도 있어 보이지만요."
10050005-91 = "#all;hide"
10050005-92 = "3;메루;02;그건 뭔데……?\n#3;em;[?]"
10050005-93 = "3;야쿠모;99;다시 한번 상기해 보도록 하죠. 우리 출판부의 모토는 출판. 증쇄. 유통. 그리고, 그렇기 때문에……."
10050005-94 = "3;야쿠모;05;그 삼각형을 담당하는 자로서, 이 마케팅 전략은 용서할 수 없는 수준이네요!\n#3;closeup"
10050005-95 = "2;모미지;04\n4;메루;04\n#na;모미지;히익?!\n#3;hide\n#2;h\n#2;em;[?!]\n#2;shake"
10050005-96 = "2;모미지;04\n4;메루;07;으엑!?\n#4;shake"
10050005-97 = "3;야쿠모;05;타카네의 말마따나 완전 자기 좋을 대로 만든 데다, 작업물 홍보를 위해 샘플을 업로드한 사이트도 완전히 듣도 보도 못한, 저기 어디 구석에 있는 사이트잖아요?!\n#2;hide\n#4;hide"
10050005-98 = "1;모미지;06;그, 그건 업로드 비용이 모자라서…….\n#1;em;[속상함]\n#1;ar\n#3;m4"
10050005-99 = "3;야쿠모;05;무른 소리는 그만둬요! 인터넷 공간은 그야말로 무에서 유를 만드는 것도 가능한, 절반 정도의 무법천지! \n#1;dl\n#3;m3\n#3;hophop"
10050005-100 = "3;야쿠모;05;하려고만 하면 이것보다는 더 나은 사이트에서 홍보하는 것도 얼마든지 가능했다고요! 팔 생각이 있는 건가요, 없는 건가요!"
10050005-101 = "5;메루;04;조, 좋은 걸 만들면 알아서 잘 팔리게 마련이야!\n#3;m1\n#5;al\n#5;em;[!]"
10050005-102 = "3;야쿠모;04;무른 소리 그 두 번째! 마케팅이라는 개념이 괜히 있는 줄 아나요? \n#3;em;[한숨]"
10050005-103 = "3;야쿠모;99;잘 만들었는데도 홍보를 엉망으로 해서 창고행이 된 상품들의 숫자가 얼마나 될지, 저도 정확히는 알 수 없지만!"
10050005-104 = "3;야쿠모;05;지식해방전선의 도서관에 보관되고 있는 장서의 숫자만큼은 될 거라고 자신할 수 있어요!\n#3;m2"
10050005-105 = "5;메루;04;과장된 거 아니야?!\n#5;em;[땀]"
10050005-106 = "#all;hide"
10050005-107 = "3;야쿠모;05;아뇨! 인류의 역사와 그 기간을 생각해 보면 오히려 넘고도 남을 거라고요! 이래서 창작자란 분들은……!\n#3;closeup"
10050005-108 = "3;야쿠모;05;스스로 뭘 만들 줄만 알지, 그걸 알리고 퍼져 나가게 하는 것에는 관심도 없다니까요!\n#3;hophop\n#3;em;[스팀]\n#3;closeup"
10050005-109 = "3;메루;10;뭔가 너 오늘따라 흥분하는 정도가 너무 심한 것 같은데?!\n#3;stiff"
10050005-110 = "3;타카네;10;……그건 당신이 부장님의 역린을 건드렸기 때문인 것 같은데요. 메루리 씨."
10050005-111 = "#all;hide"
10050005-112 = "3;야쿠모;01;아무튼, 사정은 알았어요. 지식해방전선. 이 재고들이 제값에 거래되지 않으면…… 확실히 우리 출판부로서도 곤란한 상황이라는 거군요.\n#3;a\n#3;greeting"
10050005-113 = "3;야쿠모;02;어라? 그런데 그렇다면……? 흐음. 흠. 으흠? 이거 혹시……?\n#3;em;[전구]"
10050005-114 = "1;타카네;06;부장님? 저 지금 살짝 불안해지기 시작했는데요……?\n#1;ar"
10050005-115 = "3;야쿠모;07;있어 봐요, 타카네. 힛. 힛. 히.\n#1;dl\n#3;em;[음표]"
10050005-116 = "3;야쿠모;03;좋아요, 메루. 우리 거래 좀 합시다."
10050005-117 = "5;메루;05;거래……? 윽, 너랑은 웬만해선 그런 이야기 나누고 싶지 않은데…….\n#3;m1\n#5;al"
10050005-118 = "3;야쿠모;09;들어 봐요. 사람이 속고만 사셨나."
10050005-119 = "5;메루;09;너한테는 주로 그랬어…….\n#5;em;[땀]"
10050005-120 = "3;야쿠모;08;아니, 이거 돈 되는 이야기라니까요? 운영비, 필요하잖아요? 아니에요?"
10050005-121 = "5;메루;05;으윽……. 좋아. 본론만 이야기해.\n#5;stiff"
10050005-122 = "3;야쿠모;03;이야기의 빠른 진행, 감사합니다. 결론은 이거예요. 우리들이 지식해방전선의 재고 판매를 대행하도록 하죠.\n#3;m3\n#5;dr\n#3;em;[반응]"
10050005-123 = "#all;hide"
10050005-124 = "2;모미지;02\n4;타카네;02\n#na;모미지;네……?\n#2;h\n#2;em;[?]"
10050005-125 = "2;모미지;02\n4;타카네;17;……네?\n#4;stiff"
10050005-126 = "3;야쿠모;07;물론 세상에 공짜 점심 같은 건 없답니다. 홍보와 마케팅에 특히 취약한 당신들을 대신해, 우리가 그 비용과 수고를 부담하고…….\n#2;hide\n#4;hide"
10050005-127 = "3;야쿠모;11;그 대신 수익을 일정 비율로 분배해, 그 수수료를 챙겨 가겠다는 거죠. 어때요?\n#3;em;[음표]"
10050005-128 = "3;메루;04;시, 싫어! 너랑 거래해서 뭐가 제대로 된 기억이 별로 없었단 말이야!\n#3;hophop"
10050005-129 = "1;모미지;05;메루 선배, 메루 선배! 여기에서는…… 야쿠모 선배의 말도 일리가 있다고 생각해요……!\n#1;ar\n#3;m5\n#1;em;[!]"
10050005-130 = "1;모미지;01;어차피 우리 힘으로 이 대량의 재고를 어떻게 할 수 없는 것도 맞고, 홍보와 판매에서 우리가 모자란 부분이 있는 것도 사실이고……."
10050005-131 = "1;모미지;02;재고를 떠안고 장렬하게 침몰하느니, 이런 식으로라도 해결하는 게 좋지 않을까요?\n#1;m3\n#3;dr"
10050005-132 = "1;모미지;06;무엇보다 저 공간 다 어떻게 할 거예요……. 책은 부피도 크고 무겁기까지 하다고요…….\n#1;em;[세로선]"
10050005-133 = "#all;hide"
10050005-134 = "3;야쿠모;03;어라, 역시 말이 통하지 않습니까. 이야아, 이야기를 나눌 수 있는 거래 상대라는 것은, 정말 귀한 것이라고요?"
10050005-135 = "3;메루;05;크윽, 분하다……! 하지만 모미지의 말대로 달리 뾰족한 방법이 없는 것도 사실이기는 해……. 좋아. 알았어. 받아들이겠어!\n#3;stiff\n#3;em;[속상함]"
10050005-136 = "3;야쿠모;09;좋아요. 그러면 우선 계약서부터 작성하도록 하죠. 비율은, 어디 보자, 1대 9 어때요?"
10050005-137 = "5;메루;02;……혹시나 해서 묻는 건데, 우리가 9지?\n#3;m1\n#5;al\n#5;em;[?]"
10050005-138 = "3;야쿠모;10;그럴 리가요?"
10050005-139 = "5;메루;05;그럴 줄 알았어, 이 날강도 녀석!\n#5;m4\n#5;em;[빠직]\n#5;jump"
10050005-140 = "#all;hide"
10050005-141 = "3;타카네;14;부장님, 부장님! 제가 봐도 그 비율은 조금 과도하다는 생각이 들 정도인데요?!\n#3;em;[땀]\n#3;stiff"
10050005-142 = "#all;hide"
10050005-143 = "#place;붉은겨울 교내 거리"
10050005-144 = "3;타카네;99;하아……. 어떻게든 계약을 성립시켰네요.\n#3;em;[한숨]\n#3;a"
10050005-145 = "3;타카네;01;이제 우리는 이 재고를 판매하면 되고, 그리고 정해진 비율만큼의 액수를 송금하면 되는 거군요."
10050005-146 = "3;야쿠모;04;그렇다고는 해도 양이 제법 되네요. 이것 참, 도대체 얼마나 손해액을 메꾸려던 심산이었는지.\n#3;a\n#3;em;[땀]"
10050005-147 = "3;야쿠모;03;어쨌든, 갑시다. 타카네! 우리 출판부의 저력을, 확실하게 보여 주는 거예요!\n#3;jump"
10050005-148 = "#all;hide"
10050005-149 = "#all;hide"
10050005-150 = "#all;hide"
10050005-151 = "3;야쿠모;09\n#3;a\n#3;em;…\n#wait;2500"
10050005-152 = "3;야쿠모;12;이럴, 수가……!\n#3;stiff"
10050005-153 = "#st;[0,0];instant;1;"
10050005-154 = "#clearST"
10050005-155 = "3;야쿠모;12\n#3;falldownR\n#wait;1500"
10050005-156 = "#3;hide\n#bgshake\n#wait;1500"
10050005-157 = "3;타카네;11;하나도, 안 팔렸네요…….\n#3;a\n#3;em;[속상함]"
10050005-158 = "3;야쿠모;13;어째서죠?! 분명 완벽한 판매 전략이었는데!\n#3;a\n#3;greeting"
10050005-159 = "3;타카네;02;굳이 분석해 보자면…… 우선, 메루리 씨의 책은 그 나름대로 읽을 만한 부분이 있지만…….\n#3;em;[반응]"
10050005-160 = "3;타카네;01;붉은겨울에서는, 이미 다들 익숙해질 대로 익숙해진 패턴이라는 거죠."
10050005-161 = "3;타카네;11;그것도 모자라 이번 원고는, 말씀드린 것처럼 대중성도 매니악함도 잡지 못한, 어정쩡한 것이기도 했고요.\n#3;em;[한숨]"
10050005-162 = "3;타카네;02;아무리 좋은 이야기도 세 번 이상 들으면 질리는 법이잖아요? 그리고 대부분의 창작자는 평생 한 가지 테마의 변주만 할 수 있다고 하죠.\n#3;m4"
10050005-163 = "3;타카네;99;우수한 창작자는 두 가지, 그리고 불세출의 천재가 세 개 이상이라고 하고요. 물론 메루리 씨 나름대로 여러 변화를 시도하려 한 것은 맞겠지만…….\n#3;em;…"
10050005-164 = "3;타카네;01;적어도 붉은겨울에서는, 그 변화마저도 전부 익숙해져 버렸다는 것이었겠죠……."
10050005-165 = "1;야쿠모;02;……그래요. 좋은 지적이에요. 타카네. 하지만 보다 근본적인 문제가 또 하나 있어요.\n#1;ar\n#3;m5"
10050005-166 = "3;타카네;02;그건 뭔가요, 부장님?\n#3;em;[?]"
10050005-167 = "#all;hide"
10050005-168 = "3;야쿠모;05;그건 바로, 붉은겨울 학생들은 다들 지갑 사정이 넉넉하지 않다는 겁니다!\n#3;closeup"
10050005-169 = "3;타카네;14;그 부분을 이야기하시면 우리 모두 상처받는 결말밖에는 나오지 않는다고요?!\n#3;hophop\n#3;closeup"
10050005-170 = "3;야쿠모;02;그렇지만 봐요. 사람은 돈이 없으면 문화생활부터 줄이기 마련이잖아요?\n#3;em;[반응]"
10050005-171 = "5;타카네;17;부장님, 그러고도 출판업을 한다고 말씀하시는 건가요……?\n#3;m1\n#5;al"
10050005-172 = "3;야쿠모;09;오히려 이런 부분을 잊지 말아야 출판업을 한다고 말할 수 있는 겁니다!"
10050005-173 = "5;타카네;04;그, 그렇지만 그렇게 어려운 상황이 닥친다고 해도, 어떻게든 활로를 찾아내는 것이 우리 출판부의 사명인 것이 아닐까요……?!\n#5;em;[땀]"
10050005-174 = "3;야쿠모;03;어차피 출판부 동아리 운영비의 절반 이상은, 체리노 회장 선전물과 <붉은 곰> 인쇄 수고비로 충당되잖아요!\n#3;jump"
10050005-175 = "5;타카네;15;그걸 우리 입으로 말해 버리면 너무 슬퍼지지 않을까요? 그렇지 않아도 이전 <붉은 곰>의 편집장이 숙청된 뒤로, 아직 모습을 보이지 않고 있는데!\n#5;stiff"
10050005-176 = "3;야쿠모;04;네…… 그랬죠. 그래서 오갈 데 없어진 편집부 학생들을 우리 출판부로 편입했던 거고요."
10050005-177 = "5;타카네;06;하아…… 그 일이 있기 전에도, 출판부는 그럭저럭 살림을 꾸려 갈 정도로는 벌고 있었는데 말이죠.\n#5;em;[한숨]"
10050005-178 = "3;야쿠모;10;오히려 편집부를 편입하게 된 것으로, 출판부의 재정은 훨씬 나아졌습니다만?\n#3;m2"
10050005-179 = "5;타카네;11;그렇기는 해도, 저는 사무국의 간섭을 받게 된 것이 조금, 편하지 않아서요……."
10050005-180 = "3;야쿠모;07;힛. 힛. 히. 타카네는 그렇게 말할 수 있죠. 평론가니까요. \n#3;em;[음표]"
10050005-181 = "3;야쿠모;08;하지만 출판부의 이른바…… '살림살이'를 맡고 있는 저로서는, 지금의 처지도 그다지 나쁘지 않다고요?"
10050005-182 = "3;야쿠모;09;아무튼, 알았어요. 수수께끼는 풀렸습니다. 저는 문제의 근본적인 원인에 접근했어요.\n#3;m3\n#5;dr\n#3;em;[반응]"
10050005-183 = "3;타카네;17;그건 뭔가요, 부장님?\n#3;stiff"
10050005-184 = "3;야쿠모;07;그건 바로……."
10050005-185 = "3;야쿠모;03;돈이 없는 곳에서, 돈을 벌려고 했던 것이 잘못이었다는 거였어요!\n#3;closeup\n#bgshake"
10050005-186 = "3;야쿠모;09;붉은겨울의 재정 상태는 다른 학원에 비해 객관적으로 부족한 것이 사실입니다!\n#3;closeup"
10050005-187 = "3;야쿠모;08;아무리 마른 수건도 쥐어짜면 물이 나온다고는 하지만, 그 속담도 적용될 수 있는 곳이 있고 없는 곳이 있어요!\n#3;jump\n#3;closeup"
10050005-188 = "3;타카네;14;부, 분명 틀린 말씀은 아니지만, 당장 저희가 무언가를 할 수 있는 것도 아니지 않나요?\n#3;em;[땀]"
10050005-189 = "1;야쿠모;08;아니요. 있습니다. 타카네. 있고 말고요.\n#1;ar\n#3;m4"
10050005-190 = "3;타카네;17;그게…… 뭔가요?\n#3;em;[?]"
10050005-191 = "1;야쿠모;09;장사는 첫째도 입지, 둘째도 입지, 셋째도 입지라고 하죠."
10050005-192 = "1;야쿠모;03;돈이 없다면, 돈이 있는 곳으로 가야 합니다. 거기에 한층 더, 책을 그 나름대로 읽는 문화가 정착된 곳이라면 더욱 좋겠죠.\n#1;m2"
10050005-193 = "3;타카네;04;그런 곳이 있을까요?\n#3;stiff"
10050005-194 = "1;야쿠모;07;있고 말고요. 그곳은 바로…….\n#1;em;[음표]"
10050005-195 = "#all;hide"
10050005-196 = "#na;야쿠모;……트리니티 종합학원입니다."
10050005-197 = "#all;hide"
10050005-198 = "3;타카네;17\n#3;a\n#3;em;…\n#wait;2500"
10050005-199 = "3;타카네;14;잠깐만요, 부장님?! 그렇다는 말씀은 혹시 트리니티로 직접 들어가서 판촉 활동을 하시겠다는 건가요?! 타 학교 자치구인데요!?!?\n#3;em;[?!]\n#3;shake"
10050005-200 = "3;야쿠모;03;리스크가 없이는 리턴도 없는 법입니다! 자, 따라와요. 타카네! 템포에 늦어지면 버리고 갈 겁니다!\n#3;hophop"
10050005-201 = "#st;[0,0];instant;1;"
10050005-202 = "#clearST"
10050005-203 = "3;야쿠모;03\n#3;dl\n#wait;1500"
10050005-204 = "3;타카네;14\n#3;al\n#wait;1000"
10050005-205 = "3;타카네;15;부장님? 부장님?!?!\n#3;jump"
10050005-206 = "#st;[0,0];instant;1;"
10050005-207 = "#clearST"
10050005-208 = "3;타카네;15\n#3;dl\n#wait;1500"
10050005-209 = "#all;hide"
10050005-210 = "#video;10050"
