[translation]
10052180-1 = "Day of Wrath"
10052180-2 = "[log][FF6666]Then a new heaven and a new land,[/log]"
10052180-4 = "[log][FF6666]for the first heaven and the first land had passed away,[/log]"
10052180-6 = "[log][FF6666]and there was no longer any sea.[/log]"
10052180-13 = "H-Huh?! What is this?!"
10052180-14 = "Kyaaah?! W-We're being...pulled toward the sky!!!"
10052180-15 = "The Steel Continent's energy... It's converging on the altar again!"
10052180-18 = "After crossing this land, build an altar upon the summit of the desolate mountain."
10052180-19 = "That charcoal shall touch your lips, and you will be cleansed of sins."
10052180-20 = "Cast in the name of God, ye not guilty."
10052180-25 = "This place is..."
10052180-26 = "...So this is the \"altar.\" The tower's apex..."
10052180-27 = "This is where you were, Sensei..."
10052180-28 = "[s] \"Yes. That's the case...\""
10052180-30 = "H-Hahahaha, but why would they bring us...here too?"
10052180-31 = "I can see why. They've \"invited\" us here, where they have the home advantage."
10052180-32 = "I do not know exactly what to call it, but they seem to be very insecure."
10052180-33 = "T-Toki?! Sometimes, even if something is true, you shouldn't always say it..."
10052180-38 = "[ns] \"Himari! Can you get the transport ship here??!\""
10052180-39 = "Eh? Yes, we landed quite close by."
10052180-40 = "But why...?"
10052180-41 = "[ns1] \"Go back to the transport ship for now!\"\n[ns2] \"Analyze the prophet cores we've collected!\"\n[ns3] \"Get us all the data you can!\""
10052180-46 = "[ns] \"(And, if things go south...!)\""
10052180-47 = "Why now, of all times?"
10052180-48 = "(Do they think...things will go south?)"
10052180-49 = "(But then what will become of you, Sensei...?)"
10052180-50 = "..."
10052180-51 = "..."
10052180-52 = "... ..."
10052180-53 = "...Understood. Sensei."
10052180-54 = "Yuzu! Momoi! Midori! This way!"
10052180-55 = "What? Huh? U-Us?!"
10052180-56 = "Himari?! What do you need us for...?"
10052180-60 = "Kyaaah?!"
10052180-64 = "..."
10052180-65 = "[ns] \"Are you okay?\""
10052180-66 = "...You'd do well to worry about yourself first."
10052180-67 = "Fine. Honestly, it's as if someone's attached 500 kilogram weights to all my limbs. Is this what dying feels like?"
10052180-68 = "All of this because it hid itself away inside its precious energy pillar and powered its second body."
10052180-69 = "I CANNOT understand it! Not even the worst, most self-centered brat would behave like this!"
10052180-70 = "K-Kei...? Are you really okay...?"
10052180-71 = "I'm fine. I'm not okay, but I'm fine."
10052180-72 = "If I don't get to land a solid punch on that little...!"
10052180-75 = "..."
10052180-79 = "..."
10052180-83 = "... ..."
10052180-89 = "I'd come back to haunt them even after I DIED!!"
