[translation]
10050040-1 = "Episode 4;Covert Ops"
10050040-2 = ""
10050040-3 = "Now, here's to another great day of sales!"
10050040-4 = ""
10050040-5 = ""
10050040-6 = ""
10050040-7 = ""
10050040-8 = ""
10050040-9 = "President? Is it me...or are there a lot more students compared to yesterday?"
10050040-10 = "You're right... Something feels different. And their uniforms are black..."
10050040-11 = ""
10050040-13 = ""
10050040-14 = ""
10050040-15 = ""
10050040-16 = ""
10050040-17 = ""
10050040-18 = ""
10050040-19 = "The Trinity students...don't look happy about them being around either."
10050040-20 = "This might not be the right comparison, but it does remind me of how our students react when the Secretariat comes around."
10050040-21 = "Eh, it probably doesn't have anything to do with us. Some internal Trinity affairs, I bet. C'mon, we've got books to sell."
10050040-22 = "Let's keep on making money!"
10050040-23 = ""
10050040-28 = "Oh, there you are!"
10050040-29 = ""
10050040-31 = ""
10050040-32 = ""
10050040-35 = "Oh? Who are you?"
10050040-36 = "Shh. Lower your voice and follow me."
10050040-37 = "Huh? What? What is this...?"
10050040-42 = "A Gym Somewhere"
10050040-43 = "*huff* *huff* Why are you in such a hurry...?"
10050040-44 = "Where is this? And what do Trinity students...?"
10050040-45 = "Just a little longer now."
10050040-46 = "Everyone! They're here! It's safe now!"
10050040-47 = ""
10050040-51 = ""
10050040-52 = ""
10050040-53 = ""
10050040-54 = "What in the world...?"
10050040-55 = "...Would you mind explaining the situation to us, to begin with?"
10050040-56 = "Yes, it's safe to speak now. It's those students you saw on the way here, the ones wearing black uniforms."
10050040-57 = "They're the Justice Task Force...a type of disciplinary team that handles Trinity's security and makes sure students are following the rules."
10050040-58 = "Of course, they all work really hard, but rumor has it that the president of the Justice Task Force can fold people like a crumpled can..."
10050040-59 = "Just add in a little corruption and blame, and it's basically the Secretariat..."
10050040-60 = "B-But why are those people being so...?"
10050040-61 = "That's because...the Justice Task Force is looking for you."
10050040-62 = "For us...?"
10050040-63 = "I suppose the natural question would be why, but I can posit a few reasons."
10050040-64 = "Basically, since this morning, you two are officially wanted criminals."
10050040-65 = ""
10050040-67 = ""
10050040-68 = "They've yet to announce it to the public, but word spreads quickly here."
10050040-69 = "We've been able to confirm that the Justice Task Force has been searching for you."
10050040-70 = "And, from what the rumors say, their orders have come directly from the Tea Party."
10050040-71 = "The \"Tea Party\"...? That sounds rather...pleasant."
10050040-72 = "Well..."
10050040-74 = "Y-You mean... Trinity's triumvirate student council is...after us?"
10050040-75 = "...In other words, it's like President Cherino put out a warrant for us."
10050040-76 = "No, no. If it were her, I'd have a hundred-and-one ways to get out of the situation."
10050040-77 = "This is precisely why I was against this plan to begin with, President!"
10050040-78 = "It's not over yet, Takane! Look around."
10050040-79 = "If the Trinity student body wanted us out, don't you think they would've handed us over to the Justice Task Force already?"
10050040-80 = "I...suppose so."
10050040-81 = "If they find you two... They'll likely ban you. For life."
10050040-82 = "All of the money you've earned will be confiscated."
10050040-83 = "That's not right! It's a suppression of economic activity!"
10050040-84 = "And they'd also confiscate the books you brought with you..."
10050040-85 = "That's not right! It's a suppression of cultural activity!"
10050040-86 = "Exactly. We feel the same way, which is why we've brought you here!"
10050040-87 = "Come to think of it, where is this place?"
10050040-88 = "Thank you for asking. This is..."
10050040-89 = "...the Secret Base of the Trinity Ladies!"
10050040-90 = "They call themselves the Trinity Ladies?!"
10050040-91 = "President, hush!"
10050040-92 = "We cleared out a gym that wasn't being used and created this space for ourselves."
10050040-93 = "Of course, the Justice Task Force is completely unaware of its existence."
10050040-94 = "We've all kept the secret amongst ourselves. Hence, a secret base."
10050040-95 = ""
10050040-97 = ""
10050040-98 = "There are secrets and schemes interwoven all throughout this school... Terrifying, Trinity. Truly terrifying..."
10050040-99 = "Saying that as the Publishing Department seems a bit self-flagellating..."
10050040-100 = "Even so, this is an opportunity in itself."
10050040-101 = "Nothing sells better than banned material! Suppression is like a medal for culture!"
10050040-102 = "Even if the scene isn't much, if it's censored, that in itself is promotion and boosts sales several times over!"
10050040-103 = "Speaking of medal, that reminds me of the Mustache Medal..."
10050040-104 = "That one really is useless..."
10050040-105 = "Anyway, we've received your message, loud and clear."
10050040-106 = "Yes. Thank you for bringing us to your safe space."
10050040-107 = "Now then... Shall we begin today's...sales event?"
10050040-108 = ""
10050040-110 = ""
10050040-111 = "The stage is set..."
10050040-112 = "...May I request that we proceed, Takane? Heh, heh, heh."
10050040-113 = "...Is this truly necessary?"
10050040-114 = "It's in the name of marketing, Takane. In the name of marketing!"
10050040-115 = "I can't even think about it without feeling embarrassed."
10050040-116 = "Think of it this way, Takane. This is all for the promotion of cultural activity!"
10050040-117 = "U-Ugh... A-All right, President..."
10050040-119 = ""
10050040-120 = ""
10050040-121 = ""
10050040-122 = ""
10050040-123 = ""
10050040-124 = "Hello, Koharu. It feels like it's been a while."
10050040-125 = "Y-Yeah... I suppose... I've seen a lot of Task Force members out today. Did something happen?"
10050040-126 = "Well... Uh... Apparently there's been some strange book being distributed to the students."
10050040-127 = "We were ordered to find the source and investigate the scale of the operation."
10050040-128 = "It's being framed as the Justice Task Force providing support for the Library Committee's operation."
10050040-129 = "But some members have been saying that it's actually a direct order from the Tea Party..."
10050040-130 = "A d-direct order?! It's that important?!"
10050040-131 = "I guess so..."
10050040-132 = "You know, I think... I heard something about that book..."
10050040-133 = "Really? Do you have a lead?"
10050040-134 = "N-No. I really just heard it in passing..."
10050040-135 = "Oh, that's a shame. If you do happen to come across anything that may be useful, please let me know!"
10050040-136 = "It's unusual for us to have zero intel going into an operation like this."
10050040-137 = "A-Although I'm still only a first year, so I don't have all that much experience to compare this to."
10050040-138 = "Even still, it feels like there's been a systematic effort from the top to hide what's really going on."
10050040-139 = "U-Uh, yes. I'll see what I can find. But you haven't uncovered anything...at all?"
10050040-140 = "Actually, we have! We managed to secure several copies of what looks like samples of books one and two."
10050040-141 = "Wh-What's it like? C-Can I take a look?"
10050040-142 = "Huh? Well... Since you were a member of the Force too, Koharu, and I think basically everyone's seen it already..."
10050040-143 = "Here you go."
10050040-144 = "Let's see here..."
10050040-145 = ""
10050040-147 = ""
10050040-148 = "KYAAAH?!"
10050040-149 = ""
10050040-151 = ""
10050040-153 = "K-Koharu?! Koharu?!?!"
10050040-155 = "W-Well... Uh, really, honestly, it's not because I want to read it or anything..."
10050040-156 = "...and it's JUST so I can better assist the Justice Task Force..."
10050040-157 = "...Do you have the next one?"
10050040-158 = "Not yet..."
10050040-159 = "Do you want to keep that one? I have more, so it'd be okay."
10050040-160 = "Th-Thank you. In that case... If you find something while investigating...c-can you show me?"
10050040-161 = "I-I'll look really, really hard too!"
10050040-162 = "Yes. Sure. Thank you for your cooperation. Then, good work!"
10050040-163 = "O-Okay. I'll do my best...!"
10050040-164 = ""
10050040-166 = ""
10050040-167 = "..."
10050040-168 = ""
10050040-170 = ""
10050040-172 = "I-I really don't have any ulterior motives...! I'm someone...who will become an elite member of the Justice Task Force!"
10050040-173 = "A-Anyway, what do I do with this...?"
10050040-174 = "Wait... So if this is a joint operation between the Justice Task Force and the Library Committee...?"
10050040-176 = "Justice Task Force Club Room"
10050040-177 = "*sigh*"
10050040-178 = "[s] \"You seem exhausted...\""
10050040-179 = "My apologies, Sensei. This is not the best reflection of our capabilities."
10050040-180 = "But we really are having a hard time finding any leads."
10050040-181 = "We did not anticipate the general lack of cooperation from the students."
10050040-182 = "They responded to every question with, \"I don't know,\" or a quick subject change."
10050040-183 = "I thought about it, and I believe I know why. Perhaps the book emits evil waves..."
10050040-184 = "...and is bewitching all of the students at Trinity."
10050040-185 = "[s] \"I think that's too much of a conspiracy...\""
10050040-186 = "I have to agree. Twiddling my thumbs in this office and receiving reports isn't doing me any good."
10050040-187 = "It's time I make my own moves. I will assist in the patrols."
10050040-188 = ""
10050040-190 = ""
10050040-191 = "Hello, Sensei. How are you? Oh, where's Mashiro?"
10050040-192 = "Ah... She's out on patrol? She's very diligent. Passionate, too."
10050040-193 = "If only she'd stayed for a bit longer. I just got the samples of the sequel."
10050040-194 = "[s] \"What? Really?\""
10050040-195 = "Yes. Want to take a look?"
10050040-196 = ""
10050040-198 = ""
10050040-201 = "[ns] \"Huh...?\""
10050040-203 = "[ns1] \"(This story feels oddly familiar...)\"\n[ns2] \"(Especially this plot twist, and the character development...)\""
10050040-206 = "What's wrong, Sensei?"
10050040-207 = "It's nothing?"
10050040-208 = "..."
10050040-209 = "If you say so. I'll take your word for it, Sensei."
