[translation]
10052120-1 = "พิธีกรรม"
10052120-11 = "อ๊ายยยยย?!?!"
10052120-12 = "แนวป้องกันที่ 2 ของเรา...? จริงเหรอคะเนี่ย?!"
10052120-17 = "..."
10052120-18 = "มาสรุปสถานการณ์ตอนนี้กันเถอะ ไม่ต้องตัดสินใจอะไร แค่บอกข้อเท็จจริงก็พอ"
10052120-20 = "ค่ะ ค่ะ...! ตะ... ตอนนี้พื้นที่ของผู้เลื่อมใส... เหลือแค่ 2 แห่งค่ะ"
10052120-21 = "มากกว่า 70% ของ[ruby=เน็ตซาช]ดินแดนเหล็กกล้า[/ruby]ตกไปเป็นของศัตรูแล้วค่ะ"
10052120-22 = "แล้วอีก 2 พื้นที่ที่เหลือ ก็อาจใช้ได้แค่เพื่อยื้อเวลาเท่านั้นค่ะ..."
10052120-24 = "อื้อ ความน่าจะเป็นคือปัจจัยที่เรามองข้ามไม่ได้ ยังไงก็ต้องถูกเจาะเข้ามาอยู่แล้วละ"
10052120-25 = "อะ... อึกกก...!!!"
10052120-26 = "ตั้งสติไว้ ไอน์ เราต้องยอมรับในสิ่งที่ต้องยอมรับสิ จะได้คิดหาแผนสำรองได้ไงล่ะ"
10052120-27 = "พวกเรา... ทำอะไรผิดพลาดไป... ตั้งแต่ตรงไหนเหรอคะ...?"
10052120-28 = "พะ... พะพะพะพะพะ... เพราะฉันเคยดูถูกคนพวกนั้นไว้ใช่มั้ยคะ...?!"
10052120-29 = "ขอโทษด้วยค่ะ... ขอโทษนะคะ ซอฟ ขอโทษค่ะ ออร์ ขอโทษค่ะ... พี่มัลคูธ แงงงงงง!!!"
10052120-34 = "ชู่ว ไม่เป็นไรค่ะ ไอน์ ไม่ต้องกังวลหรอกค่ะ เรื่องนี้ไม่ใช่ปัญหาที่ไอน์พูดถึงหรอกค่ะ"
10052120-35 = "นี่อาจเป็นเพราะมีตัวแปรที่ไม่คาดคิดอย่างสึคัตสึกิ ริโอะเข้ามาแทรกแซงก็ได้ค่ะ"
10052120-36 = "หรือไม่ก็อาจเป็นเพราะท่านธิดากับหญิงรับใช้ที่ได้ชื่อว่ากุญแจนั่นค่ะ"
10052120-37 = "ถ้าไม่ใช่อย่างนั้น ปัญหาก็อาจอยู่ที่คุณครูเองเลยก็ได้"
10052120-38 = "..."
10052120-39 = "หรืออาจจะด้วยเหตุผลง่ายๆ ว่าทางนั้นมีพลังต่อสู้มากกว่าเรามากน่ะ"
10052120-41 = "พะ... เพราะพวกเราเปิดดินแดนเหล็กกล้า... เร็วกว่าที่วางแผนเอาไว้นิดหน่อย... หรือเปล่าคะ...?"
10052120-43 = "แต่ถ้าเราไม่เปิดในตอนนั้น... เราก็คงไม่ได้เจอกับพี่มัลคูธแบบในตอนนี้หรอกค่ะ..."
10052120-44 = "มันก็จริงนะ..."
10052120-46 = "ใช่ค่ะ แล้วฉันก็รู้สึกขอบคุณไอน์ ซอฟ และออร์ในเรื่องนั้นอยู่เสมอค่ะ"
10052120-47 = "พี่มัลคูธ..."
10052120-48 = "ซอฟกับออร์ก็มาทางนี้ด้วยสิคะ ฉันจะกอดให้ครบทุกคนเลยค่ะ"
10052120-53 = "หะ... หืม...?"
10052120-61 = "แน่นอนว่านี่อาจไม่ใช่วิธีที่จะแก้ไขสถานการณ์ได้"
10052120-62 = "และถ้ามองอีกมุมหนึ่ง ก็อาจเป็นการกระทำที่ดูไร้ความหมายสิ้นดีก็ได้ค่ะ"
10052120-63 = "แต่ถึงยังไง นี่ก็น่าจะช่วยปลอบประโลมใจได้บ้างนะคะ?"
10052120-64 = "ใครจะรู้ล่ะคะ ถ้าเราทำแบบนี้ ไอเดียดีๆ อาจผุดขึ้นมาในใจพวกเราทุกคนก็ได้ค่ะ"
10052120-68 = "ฮือ... แงงงงงง..."
10052120-69 = "อื้อ เอาละๆ ไม่เป็นไรนะคะ ร้องออกมาให้หมดเลยค่ะ ที่นี่มีแค่พวกเราค่ะ"
10052120-70 = "ไม่เป็นไรค่ะ ทุกคนมีฉันอยู่ตรงนี้ค่ะ ถึงฉันจะย้ำคำพูดเดิมอยู่บ่อยๆ แต่ฉันก็ดีใจมากที่ได้เจอกับไอน์ ซอฟ และออร์นะคะ"
10052120-76 = "เอาละ ตอนนี้เรากำลังสูญเสียการควบคุมในแต่ละพื้นที่ของเน็ตซาช หรือก็คือดินแดนเหล็กกล้า นี่คือความจริงที่ต้องยอมรับ"
10052120-77 = "แต่ถ้ามองในมุมที่ต่างออกไป นี่ก็ยังไม่ใช่ปัญหาที่ร้ายแรงนักค่ะ"
10052120-78 = "ถ้าเราได้ร่างกายของกุญแจ... ถ้าได้ร่างกายที่เคย์ใช้งานอยู่มาเป็นของพวกเราอีกครั้งละก็ เราก็จะฟื้นสถานการณ์ได้ค่ะ"
10052120-79 = "พะ... พูดง่ายๆ ก็คือ... สุดท้ายแล้วนี่ก็คือ... ปัญหาเรื่องระดับการรักษาความปลอดภัยและก็สิทธิ์การ#nเข้าถึงค่ะ!"
10052120-80 = "ถึงดินแดนเหล็กกล้าจะหยุดการขยายตัวไปแล้ว แต่นั่นก็เป็นปัญหาที่ยังแก้ไขได้อยู่"
10052120-81 = "และถ้าเราได้อำนาจควบคุมแต่ละพื้นที่ของเน็ตซาชกลับมา เราก็จะเริ่มกระบวนการขยายพื้นที่ใหม่ได้#nทันที"
10052120-82 = "กองกำลังที่เหลือตอนนี้คือผู้เลื่อมใส 2 ตน"
10052120-83 = "แล้วก็"
10052120-84 = "ฉันสินะคะ"
10052120-85 = "..."
10052120-86 = "ก่อนหน้านี้ ร่างกายของฉันไม่อาจทนต่อแรงขับเคลื่อนจากพลังที่ได้รับมา"
10052120-87 = "พูดอีกอย่างก็คือ ถ้าแก้ปัญหาเรื่องความทนทานได้ละก็ ฉันก็จะปลดปล่อยศักยภาพทั้งหมดของตัวเอง#nได้อย่างเต็มที่ค่ะ"
10052120-88 = "เรื่องนั้นให้เป็นหน้าที่ของพวกเราเถอะค่ะ!"
10052120-89 = "ใช่ค่ะ! พวกเราจะทำให้พี่มัลคูธทะยานสู่จุดสูงสุดในร่างกายที่สมบูรณ์แบบเลยค่ะ!!!"
10052120-90 = "แล้วเราก็ยังมีโอกาสในการใช้ประโยชน์จากผู้เลื่อมใสอยู่อีกนิดหน่อยด้วยค่ะ"
10052120-92 = "เอ๋... อย่างนั้นเหรอ?"
10052120-94 = "ค่ะ เรื่องนี้ไอน์จะอธิบายให้ฟังเองค่ะ"
10052120-98 = "อะ... เอ่อ... คือว่า...!"
10052120-99 = "เหล่าผู้เลื่อมใสที่เคยอยู่ด้านในดินแดนเหล็กกล้าอาจจะกลับมาเป็นส่วนหนึ่งของเน็ตซาชได้อีกครั้ง...!"
10052120-100 = "แต่ว่าผู้เลื่อมใสที่ไปอยู่ด้านนอก... ที่ไปอยู่ในสถานที่ค่อนข้างโดดเดี่ยวบริเวณชายขอบของดินแดน#nเหล็กกล้า... ก็จะเหลือเป็นซากอยู่อย่างนั้นค่ะ..."
10052120-101 = "เรื่องนั้นฉันก็รู้อยู่แล้วนะ ว่าแต่ทำไมเหรอ?"
10052120-105 = "อ๊ะ หรือว่า...?"
10052120-106 = "ใช่ค่ะ ใช่แล้วค่ะ"
10052120-107 = "เป็นไปได้งั้นเหรอ?!"
10052120-108 = "ถ้าเราเอาสิ่งนั้นมาไว้ที่นี่ได้... น่ะค่ะ..."
10052120-109 = "อ่า... ปัญหาอยู่ที่การขนส่งงั้นสินะ..."
10052120-111 = "แล้วเราก็ต้องทำให้เงียบเชียบที่สุดเท่าที่จะเป็นไปได้ด้วยค่ะ..."
10052120-113 = "แค่เงื่อนไขเดียวก็ว่ายากแล้ว ยังมีเงื่อนไขอื่นที่ยากขึ้นด้วยสินะ..."
10052120-114 = "ระ... หรือว่าจะเกินกำลังเราคะ...?"
10052120-115 = "..."
10052120-116 = "ถ้ามันเป็นงานง่ายๆ ตั้งแต่แรกก็หมดสนุกกันพอดีน่ะสิ ว่ามั้ยล่ะ?"
10052120-121 = "โอ้ พอจะรู้อะไรเหมือนกันสินะคะ ซอฟ"
10052120-123 = "จะ... จริงเหรอคะ?!"
10052120-124 = "อื้อ กำลังการผลิตหุ่นรับใช้ยังพอมีเหลืออยู่อีกนิดหน่อยน่ะ"
10052120-125 = "ค่อยยังชั่วหน่อยนะคะ! ถ้างั้นฉันจะช่วยอีกแรง...!"
10052120-126 = "ไม่ได้หรอก เธอต้องอยู่ที่นี่ ไอน์"
10052120-127 = "คะ... คะ...?! ฉะ... ฉันไม่มีประโยชน์อะไรสินะคะ..."
10052120-128 = "ไม่ใช่แบบนั้นสักหน่อย เพราะเธอสำคัญที่สุดต่างหากล่ะ แล้วจากนี้ไปเธอก็จะงานยุ่งที่สุดเลยด้วย"
10052120-129 = "ฉะ... ฉันเหรอคะ?"
10052120-130 = "ใช่ค่ะ จากนี้ไปน่ะ ถ้าเราไม่มีไอน์ เราก็จะทำอะไรไม่ได้เลยค่ะ"
10052120-135 = "ว่าไงนะคะ?!"
10052120-136 = "ฟังให้ดีนะ ไอน์ มีสองอย่างหลักๆ ที่เธอต้องช่วยทำ..."
10052120-144 = "เข้าใจมั้ย...?"
10052120-149 = "..."
10052120-150 = "ไอน์? ยังโอเคมั้ยคะ?"
10052120-156 = "อะ... ไอน์?!?!"
10052120-157 = "นี่เรามอบภาระให้ไอน์มากเกินไปหรือเปล่าคะ?"
10052120-158 = "แต่ว่า ไอน์คะ ขอร้องละค่ะ นี่ฉันพูดจริงจังนะคะ"
10052120-159 = "ถ้าไม่ใช่ไอน์ละก็ โอกาสสำเร็จของพวกเราก็จะลดลงไปมากเลยละค่ะ"
10052120-160 = "เรื่องการเสริมความแข็งแกร่งให้พี่มัลคูธที่เป็นหนึ่งในสองอย่างที่ไอน์ต้องช่วยทำน่ะ พวกฉันจะกลับมาช่วยทดสอบให้ได้ค่ะ"
10052120-161 = "แต่งานอีกอย่างหนึ่งเป็นงานที่มีแค่ไอน์เท่านั้นที่ทำได้ นี่คือความจริงที่หลีกเลี่ยงไม่ได้ค่ะ"
10052120-166 = "..."
10052120-167 = "เข้าใจแล้วค่ะ ฉันจะลองทำดูค่ะ ไม่สิ ฉันจะทำให้ค่ะ"
10052120-168 = "ไม่ว่าอะไรจะเกิดขึ้น ฉันจะพยายามให้ถึงที่สุดเลยค่ะ!"
10052120-169 = "ไม่สิ ฉันจะสละชีวิตให้เลยค่ะ!"
10052120-170 = "ใจเย็นๆ นะ ไอน์ ใจเย็นๆ ก่อน จะตายไม่ได้สิ พวกเราจะตายไม่ได้หรอกนะ..."
10052120-171 = "นะ... นั่นสินะคะ...? แต่ถึงยังไง..."
10052120-172 = "ฉันก็จะทำจนตัวตายเลยค่ะ!"
10052120-173 = "ถึงนี่จะเป็นแค่การพูดเปรียบเปรย แต่ที่เราพยายามกันอยู่ตอนนี้ ก็เพื่อไม่ให้เกิดเรื่องแบบนั้นนี่คะ?"
10052120-178 = "..."
10052120-179 = "ขอบใจนะ ไอน์"
10052120-180 = "ถ้างั้นฉันขอฝากร่างกายของฉันด้วยนะคะ"
10052120-181 = "ค่ะ!!!"
10052120-190 = "การถามเพื่อแยกแยะระหว่างสิ่งที่มีอยู่จริงกับไม่มีอยู่จริง ในตอนนี้คงจะเป็นเรื่องที่ล้าสมัยไปแล้ว จะมีหรือไม่มีอยู่จริง มันอยู่ที่ว่าเราให้ความหมายกับมันยังไงมากกว่า"
10052120-191 = "สรุปก็คือ ทั้งสองอย่างนั้นไม่ได้แตกต่างกันอย่างมีนัยสำคัญ ก็เหมือนเวลาเราพูดว่า จำนวนจินตภาพนั้นมีอยู่จริง"
10052120-192 = "มันก็เหมือนกับความเป็นไปได้ที่ว่า ณ ที่ใดที่หนึ่ง อาจมีจักรวาลเวลาไหลย้อนกลับ และซ้ายขวาถูกสลับกัน"
10052120-196 = "!!!"
10052120-197 = "ได้ยินหรือเปล่าคะ อาริสึ?"
10052120-198 = "ค่ะ ค่ะ! ได้ยินค่ะ! ส่วนเนื้อหาที่ได้ยิน...!"
10052120-199 = "เนื้อหา... ที่ได้ยิน..."
10052120-200 = "แง! เหมือนจะจำได้ แต่ก็จำไม่ได้ค่ะ!"
10052120-201 = "ไม่ต้องกังวลค่ะ ครั้งนี้ฉันก็ได้ยินเหมือนกัน สรุปแล้วมันก็คือการเปรียบเทียบเรื่องจักรวาลกลับด้านค่ะ"
10052120-202 = "คะ? จักรวาล... กลับด้านเหรอคะ?"
10052120-203 = "ค่ะ หมายถึงจักรวาลที่ซ้ายและขวาสลับกัน และเวลาก็ไหลย้อนกลับน่ะค่ะ "
10052120-204 = "ถึงจะฟังดูแปลก แต่ก็ยังไม่มีหลักฐานใดที่บ่งชี้ว่าจักรวาลแบบนั้นเป็นสิ่งที่เป็นไปไม่ได้ค่ะ"
10052120-205 = "ถ้าอย่างนั้น... เจ้าของเสียงคนนั้นก็คือ...?"
10052120-206 = "เคย์? พอจะรู้อะไรบ้างมั้ยคะ?"
10052120-207 = "จะบอกว่าไม่รู้ก็คงไม่ได้หรอกค่ะ แต่ในขณะเดียวกัน... มันก็เป็นเรื่องยากที่จะพูดมันออกมา"
10052120-208 = "ขอโทษด้วยนะคะ อาริสึ ฉันไม่ได้อยากจะปิดบังอะไรคุณเลย แต่ว่าเรื่องนี้มันเป็นเรื่องที่ฉันบอกคุณ#nไม่ได้ค่ะ..."
10052120-209 = "..."
10052120-210 = "เคย์ นี่คือปัญหาที่อาริสึ คุณครู และทุกคน... ต้องเปลี่ยนแปลงสิ่งที่ต้องทำหรือเปล่าคะ?"
10052120-211 = "คะ? เปล่าค่ะ... ไม่ใช่อย่างนั้นหรอกค่ะ แต่ว่า..."
10052120-212 = "อึก... ถ้าเกิดมันเข้ามาแทรกแซงตรงนี้ละก็..."
10052120-213 = "อย่างนั้นสินะคะ ถ้าอย่างนั้นอาริสึก็จะทำในสิ่งที่อาริสึต้องทำต่อไปค่ะ"
10052120-214 = "ก็การคิดมากเกินไปในเรื่องที่ไม่อาจรู้ได้ มันไม่เกิดประโยชน์อะไรนี่คะ"
10052120-218 = "ค่ะ... อาริสึ ทำตามนั้นเถอะค่ะ ตอนนี้เราเหลือพื้นที่... แค่ 2 แห่งแล้วค่ะ"
