[translation]
10051050-1 = "ตอนที่ 5;อีกด้านของนินจา"
10051050-2 = "สวนด้านหลังสถานที่จัดงานแฟชั่นโชว์"
10051050-3 = "ไม่นะ... แบบนี้แฟชั่นก็ไปต่อไม่ได้น่ะสิ...!"
10051050-4 = "เอ่อ... แต่ยังไงเราก็ได้ชุดกลับมาแล้วนะ"
10051050-5 = "ใช่ มันก็จริง แต่ถ้ามีคนเจ็บแบบนี้..."
10051050-7 = "ฉันไม่โอเคเลยสักนิด!!"
10051050-8 = "เฮือก!"
10051050-9 = "ดูให้เต็มตาสิ! ก็คนที่นอนสลบอยู่คือนางแบบของฉันยังไงล่ะ!"
10051050-10 = "นางแบบของฉันโดนลูกหลงจากการต่อสู้ของพวกเธอนะ!"
10051050-11 = ""
10051050-13 = ""
10051050-14 = ""
10051050-15 = "อะไรกัน มาโทษพวกเรางั้นเหรอ?"
10051050-16 = "คะ... คนที่นอนสลบอยู่ตรงนี้..."
10051050-17 = "คือนางแบบที่จะเดินแฟชั่นโชว์วันนี้เหรอคะ?!"
10051050-18 = "แล้วทำไมถึงไม่อยู่ในงาน แต่มานอนสลบอยู่ตรงนี้ล่ะ?!"
10051050-19 = "[s] \"น่าจะเพราะการต่อสู้เมื่อกี้น่ะ...\""
10051050-20 = "เอ๋ พวกเราสู้กับแก๊งหมวกกันน็อกต่างหาก แล้วทำไมจู่ๆ นางแบบคนนี้ถึงโผล่มาได้...?"
10051050-21 = "ดูนี่สิคะ หัวหน้า! ถึงจะนอนสลบอยู่ แต่นางแบบคนนี้ยื่นมือไปทางกระเป๋าใส่เสื้อผ้าค่ะ!"
10051050-22 = "แสดงว่ากำลังวิ่งไปคว้ากระเป๋า แต่ก็สลบไปกลางคันสินะ...!"
10051050-23 = "คงรีบวิ่งเข้าไปในเหตุการณ์ต่อสู้เพื่อหยิบกระเป๋า แต่โดนลูกหลงจากกระสุนปืนเข้าก่อนแน่เลยค่ะ! นินนิน!"
10051050-24 = "ก็เป็นไปได้นะ...!"
10051050-25 = "ปะ... เป็นการอนุมานที่สมเหตุสมผลเลยค่ะ...!"
10051050-26 = "ดีมาก! เป็นเหตุผลเฉียบแหลมเลย สมกับที่เป็นนินจาจริงๆ อิซุนะจัง!"
10051050-27 = "มาเล่นบทนักสืบอะไรกันอยู่ตรงนี้! แล้วที่บอกว่าสมกับที่เป็นนินจา มันหมายความว่ายังไงกันน่ะ?!"
10051050-28 = "ช่างเถอะ... นี่! ฟื้นสิ! เธอคือนางแบบคนสำคัญของแฟชั่นโชว์นี้นะ! ลุกขึ้น! ลุกขึ้นเร็วเข้า!"
10051050-29 = "หลีกทางหน่อยครับ ดูสภาพคนเจ็บแล้ว ต่อให้เขย่าตัวสักแค่ไหนก็ลุกขึ้นมาไม่ไหวหรอกครับ"
10051050-30 = "ว่าไงนะ?!"
10051050-31 = "เธอได้รับการกระทบกระเทือนทางสมองครับ ดูสิครับ ตรงขากรรไกรกับหลังศีรษะมีรอยกระสุนชัดเจน#nเลยครับ"
10051050-32 = "ต่อให้ปลุกจนได้สติขึ้นมา แต่ก็คงควบคุมร่างกายไม่ได้หลายชั่วโมงเลยครับ"
10051050-33 = "พระเจ้าช่วย...!"
10051050-34 = ""
10051050-36 = ""
10051050-37 = "งั้นก็แสดงว่าเดินแบบไม่ไหวน่ะสิ?"
10051050-38 = "คุณจะให้คนป่วยไปเดินแบบงั้นเหรอครับ?"
10051050-39 = "ตกลงว่าได้หรือไม่ได้ ฉันอยากได้คำตอบแค่ Yes หรือ No เท่านั้น"
10051050-40 = "ไม่ไหวหรอกครับ... แค่เดินธรรมดายังยากเลย"
10051050-41 = "ต่อให้เจ้าตัวจะบอกว่าเดินแบบไหว แต่ตอนนี้ต้องพักรักษาตัวก่อนครับ"
10051050-42 = "เฮ้อ งั้นเหรอ..."
10051050-43 = "ก็ได้ ถ้าผู้เชี่ยวชาญว่าอย่างนั้น ก็คงเป็นอย่างนั้นละ"
10051050-44 = "งั้นพวกผมจะย้ายผู้ป่วยไปนะครับ"
10051050-45 = ""
10051050-47 = ""
10051050-48 = "แต่ว่า... ฉันจะเอายังไงกับแฟชั่นโชว์ดีล่ะ... เฮ้อ..."
10051050-49 = "ก็ได้ ตอนนี้คงไม่มีทางเลือกอื่นแล้ว..."
10051050-50 = "ถ้างั้นก็ พวกเธอน่ะ"
10051050-51 = "คะ?!"
10051050-52 = "ฮึ่ม ขอบใจที่ตามหาชุดจนเจอนะ"
10051050-53 = "แต่ถ้าฝีมือการยิงปืนของพวกเธอดีกว่านี้หน่อย ก็คงไม่เจอปัญหานี้..."
10051050-54 = "ช่างเถอะ ฉันขอตัวก่อนแล้วกัน"
10051050-55 = ""
10051050-57 = ""
10051050-59 = "ห้องพักในงานแฟชั่นโชว์"
10051050-60 = "ฮู่ว..."
10051050-61 = "เฮ้ออออออ..."
10051050-62 = "ทำยังไงดีล่ะ... แล้วจะให้ใครมาใส่ชุดของฉันแทนนางแบบคนนั้น..."
10051050-63 = "เอ่อ คุณดีไซเนอร์ครับ เรารีบหานางแบบสำรองมาก่อนดีมั้ยครับ?"
10051050-64 = "พูดได้ดีเลยนะ"
10051050-65 = "ว่าแต่เห็นชุดนี้หรือยัง? ไหนลองบอกมาซิว่าคิดยังไงกับชุดนี้?"
10051050-66 = "ก็... เป็นชุดที่สวยเลยนะครับ...?"
10051050-67 = "ไม่ใช่ ฉันหมายถึงไซซ์ต่างหาก ไซซ์ของชุดน่ะ! ดูชุดที่เริ่ดหรูแต่ขนาดใหญ่นี่สิ!"
10051050-68 = "ฉันออกแบบชุดนี้ให้นางแบบที่ตัวสูง 180 ซม. เลยนะ!"
10051050-69 = "แล้วในห้องนี้มีนางแบบที่สูงขนาดนั้นหรือเปล่าล่ะ?"
10051050-70 = "มะ... ไม่มีครับ!"
10051050-71 = "ก็นั่นแหละปัญหา! ผู้หญิงตัวสูง 180 ซม. หาไม่ได้ง่ายๆ หรอกนะ! แล้วถ้าจะให้มาหาอย่างกะทันหัน#nแบบนี้แล้วด้วย..."
10051050-72 = ""
10051050-74 = ""
10051050-75 = "ไม่สิ พอมาคิดดู ก็มีเด็กคนนั้นอยู่นี่นา..."
10051050-76 = "เด็กคนนั้นงั้นเหรอครับ?"
10051050-77 = "โอโนะ สึคุโยะ"
10051050-78 = "หมายถึงใครเหรอครับ?"
10051050-79 = "สมองทึบจริงเชียว! ก็เจ้าหน้าที่รักษาความปลอดภัยที่ยืนอยู่ตรงประตูหน้าไง! แล้วเมื่อกี้ก็ไปต่อสู้ในสวนด้วย!"
10051050-80 = "นายเป็นทีมงานของงานนี้ แต่ไม่ได้จำชื่อเจ้าหน้าที่รักษาความปลอดภัยในงานเลยเหรอ?"
10051050-81 = "ปกติก็ไม่เคยจำนะครับ...?"
10051050-82 = "ช่างเถอะ! เอาเป็นว่าเราต้องไปพาเด็กคนนั้นมาให้ได้"
10051050-83 = "ครับ?! จะให้เจ้าหน้าที่รักษาความปลอดภัยมาเดินแบบงั้นเหรอครับ?!"
10051050-84 = "ใช่ ฉันเห็นพรสวรรค์ของเด็กคนนั้นตั้งแต่แวบแรกที่มองแล้ว เธอไม่ได้มีดีแค่ความสูงหรอก ทั้งออร่าอันเป็นเอกลักษณ์ และสัดส่วนร่างกายที่สมดุล..."
10051050-85 = "ไปพาตัวเด็กคนนั้นมา เดี๋ยวนี้เลย"
10051050-86 = "จะ... จะเอาแบบนั้นจริงๆ เหรอครับ?!"
10051050-87 = ""
10051050-89 = ""
10051050-91 = "แล้วดูเหมือนฉันกำลังล้อเล่นอยู่หรือไงเล่า?"
10051050-92 = "ขะ... เข้าใจแล้วครับ!!"
10051050-93 = ""
10051050-95 = ""
10051050-97 = "สวนด้านหลังสถานที่จัดงานแฟชั่นโชว์"
10051050-98 = "คะ?! จะให้ฉันไปเป็นนางแบบงั้นเหรอคะ?!"
10051050-99 = "ใช่ครับ เราไม่มีเวลาแล้วครับ! "
10051050-100 = "ตะ... ตะ... ตะ... แต่ฉันไม่เคยเรียนการเป็นนางแบบมาก่อนเลยนะคะ?! จะให้คนอย่างฉันไปเดินแบบได้ยังไงคะ?!"
10051050-101 = "ผมก็คิดแบบนั้นเหมือนกัน! แต่คุณดีไซเนอร์ไชน์แคทยืนกรานว่ายังไงก็ต้องพาตัวคุณไปให้ได้ครับ...!"
10051050-102 = "ฮะ... เฮือกก...!"
10051050-103 = "ถือว่าผมขอร้องละครับ... แล้วก็ไม่ต้องห่วงนะครับ คุณดีไซเนอร์ต้องให้ค่าตอบแทนอย่างเหมาะสม#nแน่นอนครับ!"
10051050-105 = "อึกก... ตะ... แต่ถึงยังไงก็..."
10051050-106 = "รู้ใช่มั้ยครับว่าห้องพักอยู่ตรงไหน? เชิญคุณไปก่อนได้เลยครับ ส่วนผมจะไปจัดการงานอื่นแล้วรีบเข้าไปครับ!"
10051050-107 = ""
10051050-109 = ""
10051050-111 = "เฮือกกก... ท่านหัวหน้าคะ ฉัน คะ... ควรทำยังไงดีคะ?"
10051050-112 = "ฉันจะเป็นนางแบบได้ยังไงกัน? แล้วนี่ก็เป็นงานใหญ่มากด้วย..."
10051050-113 = "ที่สำคัญเลย ฉันว่าผู้คนคงไม่ชอบเด็กผู้หญิงตัวใหญ่อย่างฉันหรอกค่ะ...!"
10051050-114 = "ฉันอาจจะโดนคนในงานโห่ใส่ก็ได้...!"
10051050-115 = "ฉันสิ้นหวังและท้อแท้จนอยากขังตัวเองในห้องแคบๆ แล้วดูแต่หนังของปรมาจารย์ผู้กำกับชิบะ จนเฉาตายไปเลยค่ะ...!"
10051050-116 = "ไม่สิ ทำแบบนั้นไม่ได้นะ สึคุโยะ"
10051050-117 = ""
10051050-119 = ""
10051050-120 = "สึคุโยะ จำได้หรือเปล่าว่าข้าน้อยพูดไว้ยังไงตอนเจอสึคุโยะครั้งแรกน่ะ?"
10051050-121 = "ท่านหัวหน้าบอกว่าฉันตัวใหญ่มากค่ะ..."
10051050-122 = "กะ... ก็ยอมรับว่าพูดแบบนั้นไปด้วย!"
10051050-123 = "แต่เพราะเป็นอย่างนั้น ถึงเป็นนินจาที่แข็งแกร่งได้ คำนี้ต่างหากที่สำคัญ!"
10051050-124 = "...!"
10051050-125 = "นินจาที่แข็งแกร่งแบบนั้นไม่มาท้อแท้กับอุปสรรคแค่นี้หรอก!"
10051050-126 = "ท่านหัวหน้า...!"
10051050-127 = "ที่สำคัญที่สุดก็คือ ดีไซเนอร์แถวหน้าของวงการถึงกับเลือกให้เธอไปเป็นนางแบบเลยนะ!"
10051050-128 = "เพราะงั้นก็ต้องเชิดหน้าอย่างสง่าผ่าเผยสิ สึคุโยะ!"
10051050-129 = "และต่อให้บางอย่างจะไม่เป็นไปตามแผนที่วางไว้..."
10051050-130 = "แต่เรื่องนี้คือความผิดของผู้จัดนั่นละ! ข้าน้อยเคยอ่านเจอมาจากตำรารวมคำคมของท่านอาจารย์!"
10051050-131 = "[s1] \"ครูเคยพูดแบบนั้นด้วยเหรอ?!\"\n[s2] \"ครูมีตำรารวมคำคมด้วยเหรอ?!\""
10051050-134 = "อึกก..."
10051050-135 = ""
10051050-137 = ""
10051050-138 = "ก็ได้ค่ะ ฉันจะลองดูค่ะ...!"
10051050-140 = "ห้องพักในงานแฟชั่นโชว์"
10051050-142 = "หืม? ใครน่ะ?"
10051050-143 = ""
10051050-147 = ""
10051050-148 = "มาแล้วเหรอ ตัดสินใจมาแล้วหรือยัง?"
10051050-149 = "ค่ะ...!"
10051050-150 = "ฉันรู้ว่าเธอมีพรสวรรค์ของนางแบบ แต่เส้นทางนี้ก็ไม่ง่ายเลยละ"
10051050-151 = "แต่ฉันก็รับประกันให้ได้ว่าถ้าเธอพยายามจนถึงที่สุด ความสำเร็จและชื่อเสียงจะเป็นของเธอ"
10051050-152 = "ฉะ... ฉันไม่ได้หวังชื่อเสียงใหญ่โตหรอกค่ะ...!"
10051050-153 = "จะว่าไป ชุดที่เธอใส่อยู่ตอนนี้... คือชุดของนินจาใช่มั้ย?"
10051050-154 = "ฉันไม่รู้หรอกนะว่านินจาคืออะไร แต่ตอนนี้เธอต้องบอกลามันก่อนแล้วละ"
10051050-155 = "เสื้อผ้าที่จะเปล่งประกายบนตัวเธอวันนี้ไม่ใช่ชุดนินจา แต่เป็นชุดที่ฉันออกแบบต่างหาก"
10051050-156 = "เอ้านี่ รับไปสิ ไปเปลี่ยนเป็นชุดนี้มานะ ห้องเปลี่ยนชุดอยู่ทางโน้น"
10051050-157 = "เอ่อ..."
10051050-158 = "ทำไมล่ะ? ฉันไม่มีเวลาอยู่หรอกนะ มีอะไรก็พูดสั้นๆ ให้ตรงประเด็นเลย"
10051050-159 = "คือว่า... ฉันขอเป็นนางแบบแค่วันนี้วันเดียวนะคะ..."
10051050-160 = "ถ้าเสร็จงานของวันนี้ ฉันจะต้องกลับไปยังชมรมวิจัยศาสตร์นินจาค่ะ...!"
10051050-161 = "อะ... เอาเป็นว่าฉันจะรีบไปเปลี่ยนชุดมานะคะ!"
10051050-162 = ""
10051050-164 = ""
10051050-165 = ""
10051050-166 = "อืม..."
10051050-168 = "แต่มันจะเป็นไปตามใจเธอได้เหรอ...?"
10051050-170 = "เวทีหลัก งานแฟชั่นโชว์"
10051050-172 = "ฮู่ว... งานแฟชั่นโชว์ใกล้จะเริ่มแล้วสินะ"
10051050-173 = "ท่านสึคุโยะจะเป็นยังไงตอนเดินออกมานะคะ?"
10051050-174 = "อิซุนะอยากเห็นไวๆ แล้วค่ะ!"
10051050-175 = "โอ๊ะ สงสัยจะเริ่มแล้วละ!"
10051050-176 = ""
10051050-178 = ""
10051050-182 = ""
10051050-183 = ""
10051050-184 = ""
10051050-185 = ""
10051050-186 = ""
10051050-187 = ""
10051050-188 = ""
10051050-189 = ""
10051050-190 = ""
10051050-191 = "หัวหน้า..."
10051050-192 = "หืม...?"
10051050-193 = "ตรงหน้าเรา... คืออะไรเหรอคะ?"
10051050-194 = "นี่มัน..."
10051050-196 = "งานศิลปะชัดๆ..."
