[translation]
10055155-2 = "3;호시노 수영복ND;13\n#3;em;[훌쩍]\n#3;a\n#wait;1000"
10055155-3 = "3;호시노 수영복ND;13;당~ 했~ 다~\n#3;stiff"
10055155-4 = "#st;[0,0];instant;1;"
10055155-6 = "3;호시노 수영복ND;13\n#3;falldownL\n#wait;1500"
10055155-8 = "3;시로코 수영복;02;아직이야. 한 번 더 승부해.\n#3;a\n#3;em;[반응]"
10055155-9 = "3;시로코 수영복;02\n#na;호시노 수영복ND;시로코 쨩은 쌩쌩하네~ 이 아저씨는 이제 젊은이들 체력은 못 따라가겠어~"
10055155-10 = "5;세리카 수영복;12;아니, 그러니까 나이 차이 얼마 안 난다고!\n#5;a\n#5;em;[빠직]"
10055155-11 = "5;세리카 수영복;06;애초에 가재하고 아야네 쨩이 싸웠는데 왜 선배가 쓰러지는 거야! 빨리 일어나!\n#5;hophop"
10055155-12 = "1;아야네 수영복ND;09;아하하…… 시로코 선배. 일단 여기서는 잠깐 휴식하죠.\n#1;a\n#1;em;[땀]"
10055155-13 = "3;시로코 수영복;04;아야네……?"
10055155-14 = "3;시로코 수영복;06;어째서 배신을……? 설마, 마인드 컨트롤……?\n#3;stiff"
10055155-15 = "3;노노미 수영복ND;03;시로코 쨩은 발상이 엉뚱해서 귀엽다니까요☆\n#1;hide\n#5;hide\n#3;em;[음표]"
10055155-16 = "3;노노미 수영복ND;02;여기서는 아야네 쨩의 말을 따르죠. 우리 가재군도, 다음 경기를 위해서 푹 쉬어야 하니까요~"
10055155-17 = "3;이로하 수영복;02;다음 경기……? 어라, 이거 경기였나요……?\n#3;em;[?]"
10055155-18 = "3;아야네 수영복ND;02;네? 혹시 모르셨나요? 저희는 선생님이 같이 계시길래 당연히 알고 참여한 줄……."
10055155-19 = "3;아야네 수영복ND;11;그러면, ……아앗!\n#3;shake"
10055155-20 = "3;아야네 수영복ND;11;죄송합니다! 아무것도 모르는 분들께 승부를 걸었을 줄이야!\n#3;em;[훌쩍]"
10055155-21 = "2;이로하 수영복;01\n4;마코토 수영복;99;음, 용서해 주마.\n#4;em;[한숨]\n#3;hide"
10055155-22 = "2;이로하 수영복;04;아니, 고생은 저랑 소라게가 다했는데, 왜 마코토 선배가 거들먹……."
10055155-23 = "3;치아키 수영복;08;그나저나, 경기는 무슨 말인가요?! 혹시 축제인가요?! 여기는 평범한 무인도가 아니었던 거네요?!\n#2;hide\n#4;hide\n#3;closeup\n#3;em;[반짝]"
10055155-24 = "3;호시노 수영복ND;02;으헤~ 분하지만, 패배자인 우리는 순순히 대답해 주는 수밖에 없겠네.\n#3;em;[재잘]"
10055155-25 = "3;호시노 수영복ND;01;지금 이 섬에서 벌어지는 것은, 지상최강의 갑각류를 가리는 최악최흉의 배틀로얄……."
10055155-26 = "3;호시노 수영복ND;14;──이름하여 <천하게일무술대회>-!!\n#3;closeup"
10055155-27 = "4;마코토 수영복;21\n2;이로하 수영복;06;……이름 구려.\n#3;hide"
10055155-28 = "4;마코토 수영복;21;오오, 이 얼마나 직관적이면서 유머 감각 넘치는 이름인가!\n#4;em;[반짝]"
10055155-29 = "3;아야네 수영복ND;02;룰은 간단해요. 참가자는 자신의 별을 가지고 있고, 승자는 패자에게서 이 별을 하나 빼앗을 수 있어요.\n#4;hide\n#2;hide\n#3;em;[반응]"
10055155-30 = "3;아야네 수영복ND;03;그렇게 가장 먼저 다섯 개의 별을 모으는 팀이 우승하는 대회에요."
10055155-31 = "3;세리카 수영복;02;그리고, 놀라지 말라고! 우승자에게는 세계 최강의 게라는 명예와…….\n#3;em;[...]"
10055155-32 = "3;세리카 수영복;05;무려 어떤 소원이든 들어주는 <여왕의 소원권>이 한 장 주어져!\n#3;jump"
10055155-33 = "3;세리카 수영복;13;이 대회에서 우승해서 학교 빚을 단번에 갚아버릴 거야!"
10055155-34 = "2;이로하 수영복;02\n4;마코토 수영복;04;뭣?! 그게 사실이냐?!\n#4;em;[?!]\n#4;shake\n#3;hide"
10055155-35 = "2;이로하 수영복;04;아니, 과장이겠죠.\n#2;em;[한숨]"
10055155-36 = "3;아야네 수영복ND;09;아하하…… 저희도 조금 이상하다고 생각하기는 하는데요.\n#2;hide\n#4;hide\n#3;em;[땀]"
10055155-37 = "3;아야네 수영복ND;02;어라? 그러고 보니, 저희는 어쩌다 이런 대회에 참가한 거죠……?"
10055155-38 = "3;아야네 수영복ND;02\n#na;호시노 수영복ND;아야네 쨩~ 여기 가재군의 치료를 도와줬으면 하는데~"
10055155-39 = "3;아야네 수영복ND;16;아, 네! 금방 갈게요!\n#3;em;[!]"
10055155-40 = "#st;[0,0];instant;1;"
10055155-42 = "3;아야네 수영복ND;16\n#3;d\n#wait;2000"
10055155-43 = "3;마코토 수영복;06;…….\n#3;a"
10055155-44 = "3;마코토 수영복;21;표류 끝에 도착한 섬에서, 우연히 타이거샤크마루와 만나, 이런 대회가 개최되고 있다는 걸 알게 되다니…….\n#3;em;[...]"
10055155-45 = "3;마코토 수영복;21;이건 정말이지……."
10055155-46 = "3;마코토 수영복;15;그야말로, 천운! 하늘이 우리에게 거머쥐라고 내어준 기회나 다름없다!\n#3;closeup"
10055155-47 = "3;마코토 수영복;16;모두들! 잘 들어가! 우리 만마전은 지금부터 <천하게일무술대회>의 우승을 위해전 총력전을 선포한다!\n#3;closeup\n#3;em;[!]"
10055155-48 = "3;이부키 수영복;09;총력전-!\n#3;em;[음표]"
10055155-49 = "3;마코토 수영복;15;우리 목표는 이 대회의 우승! 자, 다들! 이 몸을 따라 전진이다!\n#3;em;[반짝]"
