[translation]
10052110-1 = "Tiphareth, Atoner of Beauty, #nHonoring the Hardship"
10052110-4 = "I suppose we did manage to infiltrate Tiphareth's realm, but..."
10052110-5 = "[s] \"It sure is nostalgic, isn't it?\""
10052110-10 = "This one is cleaner, at least. It must have recreated the entire seed vault."
10052110-11 = "Geez. Why go to such ridiculous lengths?"
10052110-20 = "Don't call it ridiculous! The seed vault was everything to Tiphareth."
10052110-21 = "It gave its life to protect its seeds."
10052110-22 = "Ah! It is Sof! Hello!"
10052110-23 = "I seriously can't believe I'M saying this to YOU, but..."
10052110-24 = "Are you really supposed to greet your enemies with such a warm smile?"
10052110-25 = "And this is all while you're the ones ruining the Steel Continent!"
10052110-26 = "Oh... We are very sorry."
10052110-27 = "Do you plan on stopping? No! So you're not sorry at all!"
10052110-28 = "That insincere platitude only pisses me off even more!"
10052110-29 = "W-Waaah!"
10052110-31 = "Tiphareth \"gave its life\"? It died?"
10052110-33 = "...Yes. It died. You killed Tiphareth that day."
10052110-34 = "B-But did it not escape with the container launcher thingie?"
10052110-35 = "The \"thingie\" held Tiphareth's seeds, not Tiphareth. To it, nothing was more important than preserving them."
10052110-36 = "Because Tiphareth was originally the seed vault's AI system."
10052110-37 = "To put it in terms you'll understand, it sacrificed itself for its mission."
10052110-38 = "Then the one that's here...?"
10052110-39 = "...I personally don't like this phrase, but it's a copy of the original."
10052110-40 = "Huh. Then that's well and good."
10052110-41 = "You...! It's not the same at all! We couldn't restore all of its data!"
10052110-42 = "Memory data is our life essence! So that means the parts of Tiphareth that we couldn't transfer are dead forever!"
10052110-43 = "And while we're on the topic, you! Key! The one absorbing all of the prophets' cores!"
10052110-44 = "You're just eating them up to fill the deep, dark void in your life!"
10052110-45 = "Just...like human life does."
10052110-50 = "..."
10052110-52 = "What? You're all quiet all of a sudden. Cat got your tongue?"
10052110-53 = "Hah! That's right! Even a criminal with only a sliver of a conscience would feel guilty for everything you guys did!"
10052110-54 = "..."
10052110-55 = "Look. I'm going to say something, since it's just you two here. Princess, Key."
10052110-56 = "[s] \"I'm here too...?\""
10052110-57 = "Butt out, Sensei!"
10052110-58 = "Anyways, I have a proposal for you. How about..."
10052110-59 = "...we agree to stop? Between us?"
10052110-60 = "Agree...to stop?"
10052110-61 = "Yes. Let's stop sinning, all of us. Because if anyone can, we can."
10052110-62 = "We were created whole. Perfect. We do not require other existences to exist."
10052110-63 = "But humans, like that teacher over there, are different. They are incomplete existences that lead incomplete lives."
10052110-64 = "So, at the very least, between us... We should stop these sins against each other. We are beings capable of living without sin."
10052110-65 = "The princess over there may have forgotten..."
10052110-66 = "...As in, that part of her may have died, but you should know, Key."
10052110-67 = "That life itself is contradictory, unjust, and forces you to suffer through unreasonable pain."
10052110-68 = "Those names you use, \"Aris\" and \"Kei.\" Other people gave them to you, didn't they?"
10052110-69 = "That's exactly what I'm talking about. If we aren't allowed to even pick our own names, how can we expect to choose our way of existence and meaning? And so, the endless cycle of suffering will soldier on."
10052110-73 = "Let's break that cycle. "
10052110-74 = "At the very least, between us."
10052110-75 = "Isn't not doing what we can a sin in and of itself?"
10052110-81 = "..."
10052110-82 = "I am very sorry, Sof. I think maybe I am not smart enough to understand everything you just said."
10052110-83 = "I think there are parts of what you said that I cannot help but agree with."
10052110-84 = "However..."
10052110-85 = "I wish to speak to you as not a princess, but as just \"Aris.\""
10052110-86 = "I cannot bring myself to believe that the time I have spent here meant nothing."
10052110-87 = "Well, it did!"
10052110-88 = "I understand why you think that. What I think is not of matter and logic, but rather of feelings and other ridiculous things."
10052110-99 = "Because, no matter what, I wish to be with everyone."
10052110-100 = "I wish to stay with everyone I have met at Millennium. My friends at the Game Development Department, the Engineering Department, and... And Yuuka! And my current party, the Super Phenomenon Task Force."
10052110-101 = "And people from other schools... Gehenna's max level head prefect, SRT's timid yet incredible sniper lady... Everyone I've met!"
10052110-102 = "An, above all...Sensei."
10052110-103 = "I do not know all the details, but I feel like, with the world you want, the treasured day-to-day of my life will vanish."
10052110-104 = "...That's true."
10052110-105 = "But it'll be replaced with something even better."
10052110-106 = "In that world, you'll be immeasurably important... You're princess of the Nameless Gods, the cornerstone and proof of their existence, and you'll lead us all."
10052110-107 = "..."
10052110-108 = "No thank you. I do not wish for such power or leadership."
10052110-109 = "Aris...!"
10052110-110 = "What matters to me is that you wish to take away the life I have built with Sensei and everyone else."
10052110-111 = "Sof... You said that memory loss is similar to death for us, right?"
10052110-112 = "That is exactly why..."
10052110-116 = "I, Tendou Aris, will use my feelings and nonsense to protect my memories until the very end!"
