[translation]
1006405-1 = "Gamju and the Cat"
1006405-2 = "The next morning while I was waiting for Kayoko by the temple grounds..."
1006405-3 = "Oh, Sensei? Did you arrive first and wait outside?"
1006405-4 = "It's a chilly day today and you weren't waiting indoors..."
1006405-5 = "[s] \"It's okay, I didn't wait too long anyway.\""
1006405-6 = ""
1006405-8 = ""
1006405-9 = ""
1006405-10 = "But, my hands are so cold..."
1006405-11 = "Best we go inside and warm up."
1006405-12 = "Surely there would be a place where they sell hot drinks near here."
1006405-13 = "How about some sweet gamju?"
1006405-14 = "It's just been brewed so it's real hot. Grab a cup before it gets cold!"
1006405-15 = "I wonder if it's because it's the New Year that they're passing out gamju on the temple grounds."
1006405-16 = "Sensei, why don't we go and warm ourselves with gamju before we go buy an amulet?"
1006405-17 = "[s] \"Sure.\""
1006405-18 = "Over here! Two cups of gamju, please."
1006405-22 = "[ns1] \"Ahh, so warm...\"\n[ns2] \"I can feel my insides warming up...\""
1006405-23 = "Heehee. I've missed this taste."
1006405-24 = "Heehee. I've missed this taste."
1006405-25 = "This reminds me of my first time drinking gamju without a worry in the world."
1006405-26 = "[s] \"Did something happen a while back?\""
1006405-27 = "Well, gamju is a fermented beverage, so it does have some traces of alcohol in it, right?"
1006405-28 = "There were a few students who couldn't hold their alcohol well, so they ended up causing a huge mess when they occasionally drank gamju."
1006405-29 = "So every year when I drink gamju, I don't get to enjoy the flavor of it because I get worried about making sure there aren't any drunk students around me..."
1006405-30 = "But this wouldn't be a concern if I'm with you Sensei, since you're an adult."
1006405-31 = "[s] \"Have you not been drunk from gamju before, Kayoko?\""
1006405-32 = "Well of course not! You can't get drunk from something that's practically a juice, right?"
1006405-33 = "I mean, I'm not sure what would happen if I had several drinks in a row, but..."
1006405-34 = "Gamju is sweet and delicious, but I've already warmed up enough with just this cup."
1006405-35 = "Alright then, now that our bodies are warm, shall we..."
1006405-36 = ""
1006405-39 = "Oh..."
1006405-40 = "I'm sorry, Sensei, could you wait here just a moment?"
1006405-41 = "There's something that's on my mind..."
1006405-42 = "[s] \"Sure, go on ahead.\""
1006405-43 = "Then, I'll be right back."
1006405-44 = ""
1006405-46 = ""
1006405-48 = "But more than 10 minutes had gone by and Kayoko still hadn't come back..."
1006405-50 = "[ns] Follow Kayoko in the direction she was headed."
1006405-51 = ""
1006405-52 = ""
1006405-53 = "There, there, there's a good one. Heehee..."
1006405-54 = "Do you live near here? You seem to be quite familiar with a human's hand."
1006405-55 = ""
1006405-58 = "Oh I see, your meows are so cute."
1006405-59 = ""
1006405-61 = ""
1006405-62 = "Kitty kitty, soft kitty ♪"
1006405-63 = "[s3] \"You look like you're having fun.\"\n[s4] \"You were playing with these cats?\""
1006405-64 = "S-Sensei...?! How did you manage to come here...?"
1006405-65 = "S-Sensei...?! How did you manage to come here...?"
1006405-66 = "I wasn't coming back, so you found your way here...? I-I'm sorry... I got distracted playing with these cats..."
1006405-67 = "So...um...did...you..."
1006405-68 = "...see all that?"
1006405-69 = "[s] \"...Yup.\""
1006405-70 = "So I didn't mean to use a cute voice..."
1006405-71 = "Actually, yes it was intended, but it was because I thought no one was watching..."
1006405-72 = ""
1006405-74 = ""
1006405-75 = "...This is all because of the gamju."
1006405-76 = "I'm certain that the gamju we drank earlier...impeded my judgment..."
1006405-77 = "I will never drink gamju from now on...!"
1006405-79 = "...Later, I consoled the bashful Kayoko and went to buy the amulet."
