[translation]
1006502-1 = "Hyakkiyako's Ambassador Kaho"
1006502-2 = "Just about 30 minutes after Kaho told me she would visit Schale..."
1006502-3 = ""
1006502-6 = "Sensei, thank you for waiting."
1006502-7 = "[s] \"Oh, hello. Come on in.\""
1006502-8 = ""
1006502-13 = ""
1006502-14 = "Hello, [USERNAME] Sensei."
1006502-15 = "[s] \"Hi, Kaho. You got here much earlier than I expected.\""
1006502-16 = "I apologize that I had to visit all of a sudden."
1006502-17 = "I really should've scheduled ahead."
1006502-18 = "But as I've already told you about the matter, I thought it'd be better to discuss with you earlier than dragging it out any longer."
1006502-19 = "[s] \"Oh, so speaking of which...\""
1006502-20 = ""
1006502-22 = ""
1006502-23 = "[ns] \"I have no idea what this matter is, so if you could explain...\""
1006502-24 = "Ah, I see. I understand."
1006502-25 = "I am well aware that it might be too much to ask for someone to understand everything from the letter I sent."
1006502-26 = "And it's nothing out of the ordinary that you are experiencing difficulty."
1006502-27 = "[s] \"Oh, y-yeah, right?\""
1006502-28 = "Therefore, would you please give me some time..."
1006502-29 = "I mean, an opportunity?"
1006502-30 = "If you are okay with it, I'll do my best to explain everything to you with this opportunity so you can understand everything easily."
1006502-31 = "And in fact, I'm here for that, actually."
1006502-32 = "[s1] \"Ah, yes, I would love it.\"\n[s2] \"I mean, I would have asked you to do the same.\""
1006502-35 = "Thank you."
1006502-36 = "Then, as you have given me the permission..."
1006502-37 = ""
1006502-39 = ""
1006502-40 = "I, Kuwakami Kaho, the Lead Strategist of Hyakkiyako's Tourism and Cultural Industries..."
1006502-41 = "...Will begin the presentation on the proposal for the Schale-Hyakkiyako Collaborative Tour Business!"
1006502-42 = "[s] \"...What...?\""
1006502-43 = ""
1006502-45 = ""
1006502-46 = "Please, look at the chart over this way."
1006502-47 = ""
1006502-49 = ""
1006502-50 = "Ahem, this chart is the sales graph of Allied Hyakkiyako Academy's annual tour business."
1006502-51 = ""
1006502-53 = ""
1006502-54 = "The annual sales of Allied Hyakkiyako Academy has been increasing over the course of three years with a 150% growth rate."
1006502-55 = "And such smooth growth can be considered a very successful result that can seldom be found in all of Kivotos..."
1006502-56 = "[s] \"...Excuse me...?\""
1006502-57 = "Of course, you may wonder if such growth can be maintained in the future..."
1006502-58 = "...Or if it can be guaranteed, which are separate questions."
1006502-59 = "No business can flourish for an eternity..."
1006502-60 = "And we at the Hyakkiyako are well aware that something must keep fueling or the business falls in no time."
1006502-61 = "[s] \"Ummm, okay...?\""
1006502-62 = "However, the tour business we run at Hyakkiyako boasts many features that set us apart from the industry standard."
1006502-63 = "It has been proven that Hyakkiyako as the brand name has already built a strong foundation, according to various statistics...!"
1006502-64 = ""
1006502-66 = ""
1006502-67 = ""
1006502-68 = ""
1006502-70 = ""
1006502-78 = "Kaho suddenly started passionately promoting Hyakkiyako."
1006502-79 = "Her explanation, however, had lots of industry-specific vocabulary and it was mostly very hard to understand."
1006502-80 = "As I was completely lost, trying to understand, Kaho's promotion had reached its climax."
1006502-85 = "...is what I would believe the crucial point you must consider, and if you could trust us Hyakkiyako and cooperate..."
1006502-86 = "It is without a doubt that we could foresee a new opportunity of growth via collaboration with Schale..."
1006502-87 = "I would like to tell you that it would even be possible to create a new flow that would lead the culture of Kivotos altogether!"
1006502-88 = "And that would be the end of the presentation that I, Kuwakami Kaho, have prepared. Thank you."
1006502-89 = ""
1006502-97 = "Whew."
1006502-98 = "Then Sensei, please let me know if you have any questions or anything unclear that you'd like explained further."
1006502-99 = ""
1006502-102 = "[ns] \"...So, I mean...\""
1006502-103 = ""
1006502-104 = "[ns] \"I'm sorry, Kaho, but I didn't understand a single bit of what you said.\""
1006502-105 = "..."
1006502-106 = "Tch."
1006502-107 = "[s] \"Oh, I think I said that wrong, but what I actually meant is...!\""
1006502-108 = "No, it's okay. I only realized that Schale's Sensei does not fall easily, as I've heard..."
1006502-109 = "Right. I have just realized that."
1006502-110 = "I've presented with enough data, but you were able to see the whole thing with keen eyes."
1006502-111 = "...I suppose the numbers on the chart were not enough to convince you."
1006502-112 = "You mean, that what's truly important is not the numbers, but rather heart..."
1006502-113 = "I should prove my trust in you, I see."
1006502-114 = "[s] \"What?\""
1006502-115 = "...Understood."
1006502-116 = "To prove your trust is not easy work."
1006502-117 = "However, I, Kuwakami Kaho, will not step back."
1006502-118 = ""
1006502-120 = ""
1006502-121 = "[USERNAME] Sensei, if you could kindly grant me another opportunity..."
1006502-122 = "I, though I may be unworthy, I will do my best to earn your trust..."
1006502-123 = "I will b-b-be the person in charge for [USERNAME] Sensei to improve the relationship between Schale and Allied Hyakkiyako Academy and our future collaborative works..."
1006502-124 = "...d-devoting my full heart..."
1006502-125 = "...i-into the service..."
1006502-126 = "...f-for you..."
1006502-128 = "[ns] \"Hey, I don't know what you're thinking, but I'm pretty sure it's wrong!\""
1006502-129 = ""
1006502-130 = "...H-Huh?"
1006502-131 = "I-Is that so...?"
1006502-132 = "But..."
1006502-133 = "[s] \"What is 'the matter' you've been talking about the whole time in the first place?\""
1006502-134 = "Excuse me?"
1006502-136 = "And after talking to Kaho about multiple things, the conclusion was..."
1006502-139 = ""
1006502-140 = "I-I-I-I..."
1006502-141 = "I am so sorry!"
1006502-142 = "I-I never expected that the inquiry on the collaborative works with Schale..."
1006502-143 = "...would still be in my mailbox, unsent...!"
1006502-144 = "[s] \"Yeah, I knew something was off...\""
1006502-145 = "And not knowing the truth, I just went on explaining things that you wouldn't know anything about..."
1006502-146 = "I-I am so sorry once again! It is all my fault!"
1006502-147 = "If I were to have delivered that mail, we'd have been..."
1006502-148 = "[s] \"Oh, regarding what you've told me, by the way...\""
1006502-149 = ""
1006502-151 = ""
1006502-152 = "[ns] \"I'm sorry, but Schale would not be able to accept your offer.\""
1006502-153 = "Wait, Schale can't...accept a...collaboration proposal?"
1006502-154 = "...Schale is only a Federal Investigation Club that listens to the concerns of students and resolves them..."
1006502-155 = "It is not a club that revolves around economical value...you say..."
1006502-156 = "...Which means... I-I have been..."
1006502-157 = "...thinking of the whole thing wrong in the first place...?"
1006502-158 = "[s] \"I suppose that's what happened.\""
1006502-159 = "Ah, ahhh.... oh..."
1006502-160 = "I...see..."
1006502-161 = "I...just wanted to spread the word of Hyakkiyako's culture, and I had thought Schale's Sensei, who has helped countless Hyakkiyako students..."
1006502-162 = "...would be able to have a good discussion followed up by a great result..."
1006502-163 = "But it was...merely my imagination..."
1006502-164 = "I went crazy for nothing, and made you confused."
1006502-165 = "...I am sorry for being such a disappointment."
1006502-166 = "[s] \"No, I don't think you are a disappointment.\""
1006502-167 = "...What?"
1006502-168 = "[s] \"That just means you really wanted to advertise Hyakkiyako, right?\""
1006502-169 = ""
1006502-171 = ""
1006502-172 = ""
1006502-174 = "Kaho wanted to advertise Hyakkiyako so badly that she even visited Schale and passionately made an appeal with all these charts she prepared."
1006502-175 = "That's not just because she's the ambassador..."
1006502-176 = "But she purely wanted to let others know what she really liked."
1006502-177 = ""
1006502-179 = ""
1006502-181 = "[ns] \"(And she almost went on a rampage because of that....)\""
1006502-182 = ""
1006502-185 = "[ns] \"I would never be disappointed by true passion from your heart.\""
1006502-186 = ""
1006502-188 = ""
1006502-189 = "...I...see..."
1006502-190 = "You...can even understand me..."
1006502-191 = "...Yes."
1006502-192 = "Thank you, Sensei."
1006502-193 = "I now know what Schale actually does, and what my misunderstandings are."
1006502-194 = "I suppose the matter on collaborative work can be put aside for now."
1006502-195 = "[s] \"Thank you for understanding. Since you're here though, do you have any other concerns...\""
1006502-196 = "Instead..."
1006502-197 = "[s] \"...Instead...?\""
1006502-198 = ""
1006502-200 = ""
1006502-201 = "As things have turned out this way, for the better relationship between Schale and Allied Hyakkiyako Academy..."
1006502-202 = "I would like to present you the idea I've just thought of..."
1006502-203 = "Would you like to spare some time for me, Sensei?"
1006502-204 = "[s] \"Uhhh, um... Sure, I guess...?\""
1006502-205 = "Heh heh. Thank you."
1006502-207 = "Then, let me begin my presentation."
1006502-209 = "And then I spent something of a Hyakkiyako passion-fueled time with Kaho."
