[translation]
1006703-1 = "Reason for Existence"
1006703-2 = "Schale Executive Office"
1006703-4 = "Schale is peaceful today, too. That's good."
1006703-5 = "Oh, Sensei. Could you hand me the potato chips over there?"
1006703-6 = ""
1006703-10 = "[ns1] \"It's a good thing that you find yourself comfortable here...\"\n[ns2] \"I feel like you find yourself a bit too comfortable, you know?!\""
1006703-13 = ""
1006703-14 = "Hmm? Is that a major issue? No?"
1006703-15 = "Then it's not really a big deal. Don't worry. I'll restock the chips I ate."
1006703-17 = "I had been struggling with a problem."
1006703-18 = "It wasn't serious, but Toki was beginning to get a little too comfortable at Schale."
1006703-19 = "I had a serious talk with Toki a couple days ago, but..."
1006703-20 = ""
1006703-21 = "Why do I visit Schale so often?"
1006703-22 = "There are several reasons, but the biggest reason would be that my affiliation is not clear."
1006703-23 = "And that makes it hard for me to act with my upperclassmen despite having the call sign Zero-Four from C&C."
1006703-24 = "And that makes Schale the most efficient place for me."
1006703-25 = "Here, I can take orders easily, and take any actions necessary in response to any situation."
1006703-26 = "Under those circumstances, I think anyone would choose to stay in Schale. Right?"
1006703-28 = "I had nothing to say in response to that at the time."
1006703-29 = "And so, things escalated..."
1006703-30 = ""
1006703-31 = "Hmm. I'm thirsty now that I've been only eating salty stuff. Sensei, let me drink the green tea over there."
1006703-32 = ""
1006703-34 = ""
1006703-36 = ""
1006703-37 = ""
1006703-39 = ""
1006703-41 = "Oh, the tea branch is standing. Today's the lucky day."
1006703-42 = "The fragrance is great, and it tastes good. I didn't know you were into green tea."
1006703-43 = "[s] \"Umm... I sort of received it as a gift.\""
1006703-44 = "Is that so. As expected. I may be slightly disappointed."
1006703-45 = "[ns] \"Why?!\""
1006703-46 = "What do you plan to get for lunch today?"
1006703-47 = "Don't worry about me. I am totally okay if you order for one and enjoy it by yourself."
1006703-48 = "I will be completely fine. I will experience no change of heart nor visceral emotional response."
1006703-49 = ""
1006703-56 = "[ns3] \"Hello, this is Schale... Can I order for two?\" \n[ns4] \"Two orders of Special Healthy Lunch Set, please...\""
1006703-59 = "Oh, you ordered two."
1006703-60 = "I have no choice but to eat it with you, then."
1006703-61 = "[s] \"Right. You have to eat both the veggies and protein...\""
1006703-62 = "If you say it like that, you make it sound like I've only been eating unhealthy food..."
1006703-63 = "[s] \"You weren't...?\""
1006703-64 = "..."
1006703-65 = "The past is in the past. We must forget it quickly, and step towards the bright future."
1006703-66 = "[s] \"At least try to make an excuse...!\""
1006703-72 = "[ns] \"Speaking of which, Toki...\""
1006703-73 = ""
1006703-74 = "Yes?"
1006703-75 = "Yes. Of course, I go back to my office when the day is over."
1006703-76 = "Why don't I stand by at my own office?"
1006703-77 = "..."
1006703-78 = "Do you... feel burdened that I'm staying here...?"
1006703-79 = "[s5] \"Nonono, it's not like that!\"\n[s6] \"I just felt that you wouldn't find any fun visiting an empty office!\""
1006703-82 = "I don't particularly feel that way."
1006703-83 = "So that means I can stay here, right?"
1006703-84 = "[s] \"Well, if you say so...\""
1006703-85 = "I thought so."
1006703-86 = "Hmm? But you are worried about the rumors about Schale?"
1006703-88 = "Because of Toki, strange rumors started circulating..."
1006703-89 = ""
1006703-90 = "Did you hear that? Schale's Sensei apparently..."
1006703-91 = "Yes, I did! Sensei makes the students wear bunny costumes... and apparently enjoys it, huh?"
1006703-92 = "I heard Sensei was a good person, but you really can't tell..."
1006703-93 = "It was just yesterday that someone saw a student going into Schale in a bunny costume..."
1006703-94 = "Like so..."
1006703-96 = ""
1006703-98 = "I tried to talk to Toki about it..."
1006703-99 = "Hmm. Nothing too important. They are merely rumors that are far apart from the truth."
1006703-100 = "To begin with, I am the only student who visits Schale wearing a bunny costume."
1006703-101 = "And you don't enjoy it, so it is completely wrong."
1006703-102 = "...Or, have you been secretly enjoying it?"
1006703-103 = "[ns] \"Nope, not at all!\""
1006703-104 = "I knew you would say so."
1006703-105 = "Anyways, I don't think we need to take measures against every false rumor we hear."
1006703-106 = "So I would say the case is closed here."
1006703-107 = "[s] \"Would it really be okay...?\""
1006703-108 = "Of course. I have no issues with it."
1006703-109 = "Hmm? Your reputation? Hmm... I'm not sure. I'll put my decision on hold."
1006703-110 = ""
1006703-114 = "Oh, the delivery is here."
1006703-115 = ""
1006703-117 = ""
1006703-118 = "I'll go get it."
1006703-119 = ""
1006703-122 = "Sensei? Why are you in such a hurry? Hmm? You'll get it yourself?"
1006703-123 = "..."
1006703-124 = "Affirmative, though I don't really understand..."
1006703-126 = "For some reason, the lunch I ate with Toki didn't go down well after that."
