[translation]
1006205-1 = "Concerning Hobbies"
1006205-2 = "Schale Executive Office"
1006205-3 = "Toki and I began work on the day's duties at Schale."
1006205-4 = ""
1006205-9 = "[ns] \"Toki.\""
1006205-10 = "What is it, Sensei?"
1006205-11 = "[s] \"You seem used to this kind of work.\""
1006205-12 = "Perhaps. I'm not sure what you mean by \"this kind of work.\""
1006205-13 = "[s] \"Just what we're doing now—organizing files and materials, that kind of thing.\""
1006205-14 = "Ah, I see. Well, it may be insensitive of me to bring this up, but this was frequently among the duties assigned to me by the person I used to assist."
1006205-15 = "Of course, I am also perfectly capable of cooking, cleaning, or any other housekeeping you might require."
1006205-16 = "[s1] \"I think you're doing more than enough...\"\n[s2] \"Do you ever feel like you're working too hard?\""
1006205-19 = "Hm. You're referring to my work for Schale?"
1006205-20 = "I'm not sure that I agree. Sometimes, there's so little work that I feel a bit awkward."
1006205-21 = "I am a superior maid. You may assign me more duties if you wish."
1006205-22 = "For example, I am escorting you now, but I am also capable of repelling enemies, suppressing crowds, defusing explosives, tracking, annihilating, intercepting, destroying, and exterminating. Please call on me if you need any of those services."
1006205-23 = "[s] \"But none of those things have anything to do with being a maid?!\""
1006205-24 = "Perhaps not. And yet, going above and beyond is one of the qualities of a superior maid."
1006205-25 = "[s] \"I-Is that so?\""
1006205-26 = "It is. As a perfect maid, you can trust me to give you correct information."
1006205-27 = "[s3] \"In that case... What do you do on weekends?\"\n[s4] \"I'd like to hear about your hobbies!\""
1006205-30 = "...Hobby? Time off?"
1006205-31 = "I'm sorry, I'm not sure what you're talking about. Please explain the concept to me."
1006205-32 = "Something you do when you have time to spare? Are you testing me by asking such difficult questions?"
1006205-33 = "I generally worked through the weekend. I very rarely had time off from my duties."
1006205-34 = "[s5] \"H-How... How could this be?\"\n[s6] \"You can't waste your student years like this!\""
1006205-37 = "S-Sensei?"
1006205-38 = "What do you mean, you can't let this pass? Oh, are we going somewhere right now? Sensei? I said before, you can't just drag me around by the arm—"
1006205-39 = ""
1006205-41 = ""
1006205-43 = "Downtown Kivotos"
1006205-44 = "[ns] \"So, how'd you like the movie?\""
1006205-45 = "I didn't understand it at all."
1006205-46 = "Why did the characters begin shooting in the middle of a chase? In fact, what reason was there to escalate the situation to a shootout at all?"
1006205-47 = "If they had simply handled the situation better from the beginning, instead of acting so clearly suspicious, the incident would've ended without anyone being hurt."
1006205-48 = "[s] \"But that's...the core concept of the screenplay...\""
1006205-49 = "I noticed many other flaws. For example..."
1006205-51 = "Toki then spent more than half an hour outlining the film's many inconsistencies."
1006205-53 = "...That concludes my report."
1006205-54 = "[s] \"...Great work.\""
1006205-55 = "It was nothing."
1006205-56 = "Oh? I see. You're saying that generally, a movie is simply enjoyed, and one doesn't typically spend so much time nitpicking it."
1006205-57 = "It seems that I still need training in the art of watching a movie. In the future, I'll put more effort in."
1006205-59 = "Shopping Street"
1006205-60 = "[ns] \"This time, let's try manga...\""
1006205-61 = "I've heard the saying, \"a picture is worth a thousand words,\" but I'm not sure I agree."
1006205-62 = "My qualm is this. When it comes to information density and efficiency, is this method truly the best?"
1006205-63 = "Despite what people say, I think the content of this image could be conveyed far more densely in a written medium, with less expenditure of ink and paper. In terms of efficiently conveying information, I believe a video medium to be superior."
1006205-64 = "So... What is intended by using the picture format? Not only does it have the problems that I already described, but it takes so much time and effort to create."
1006205-65 = "I assume there must be some reason, but it eludes me."
1006205-67 = ""
1006205-68 = ""
1006205-69 = "Shopping is truly an intricate ritual."
1006205-70 = "You make the decision, with knowledge and intent, to buy so many unnecessary things."
1006205-71 = "I'm not sure I understand. All acts must have meaning, don't you think?"
1006205-72 = "And yet shopping doesn't seem to have any."
1006205-73 = "[ns] \"So you didn't enjoy it after all...\""
1006205-75 = "I continued to try out a number of hobbies with Toki."
1006205-76 = "Toki showed interest in exactly...none of them."
1006205-78 = "Downtown Kivotos"
1006205-79 = "[ns] \"Good work... Toki...\""
1006205-80 = "I did nothing difficult or praiseworthy."
1006205-81 = "In fact, I believe you've done most of the work today."
1006205-82 = "..."
1006205-83 = "Um, Sensei?"
1006205-84 = "[s] \"Hm?\""
1006205-85 = "I'm still not sure...what sort of thing a hobby is."
1006205-86 = "Is it a technical skill that requires mastery, such as the skill of escorting someone?"
1006205-87 = "Is it an activity that requires success and understanding, or something of that nature?"
1006205-88 = "Toki was looking at me with an uncharacteristic look of anxiety."
1006205-89 = "I chose my words carefully."
1006205-90 = "[s] \"A hobby is...\""
1006205-91 = "Yes?"
1006205-92 = "[s7] \"It's not important whether you're good or bad at it.\"\n[s8] \"It's only important that you enjoy doing it.\""
1006205-95 = "Something that I enjoy... Something I do just because I want to."
1006205-96 = "[s9] \"There's no need to rush to find one.\"\n[s10] \"When you've found the perfect hobby, you'll know it.\"\n[s11] \"You don't need to have one, but it can be nice.\""
1006205-100 = "..."
1006205-101 = "So, my hobby could be..."
1006205-102 = "...Heehee."
1006205-103 = "[s] \"What? Did you already think of something?\""
1006205-104 = "It's nothing! Nevermind."
1006205-105 = ""
1006205-107 = ""
1006205-108 = "Then, Sensei."
1006205-109 = "Should we go back?"
1006205-110 = "I'll escort you back to Schale."
1006205-111 = "[s] \"It seems like there's something you're not telling me...\""
1006205-112 = "Hm, I wonder. What could that be?"
1006205-113 = ""
1006205-115 = ""
1006205-118 = "[ns] \"You're really not going to tell me?\""
1006205-119 = "Well, how could I tell you when I hardly know myself?"
1006205-120 = "[ns] \"Nice diversion.\""
1006205-122 = "Toki and I chatted and walked back to Schale together."
