[translation]
1006202-1 = "กิจวัตรประจำวัน"
1006202-2 = "สำนักงานชาเล่ต์"
1006202-8 = "(คุณครูมาทำงานทันเวลาอย่างหวุดหวิด)"
1006202-9 = "(และตอนนั้นเอง...)"
1006202-10 = "สวัสดีค่ะคุณครู"
1006202-11 = "[s1] \"ใครน่ะ?!\"\n[s2] \"โทคิเหรอ...?\""
1006202-12 = "......"
1006202-13 = "อย่างนี้นี่เอง คุณครูลืมเรื่องของฉันไปหมดสิ้นแล้วสินะคะ"
1006202-14 = "ไม่เป็นไรหรอกค่ะ ฉันไม่เสียใจกับเรื่องแค่นี้หรอกค่ะ ไม่ได้รู้สึกอะไรเลยจริงๆ ค่ะ แต่ถึงจะลืมไป#nแล้วจริงๆ ฉันก็ให้อภัยได้ค่ะ"
1006202-15 = "แต่ฉันสงสัยจังว่า... ชุดเมดและที่คาดผมสุดแวววาวของฉันจะให้อภัยคุณครูรึเปล่า?"
1006202-16 = "[ns3] \"คะ...ครูไม่ได้ลืมนะ! แค่มันกะทันหันไปน่ะ! ครูขอโทษ!\""
1006202-18 = "[ns4] \"โทคิ! โทคิใช่มั้ย? อาซุมะ โทคิ!\""
1006202-19 = "จำได้แล้วสินะคะ ขอบคุณค่ะคุณครู"
1006202-20 = "ขอบคุณที่จำฉันได้นะคะ"
1006202-21 = "แต่ฉันคิดไม่ถึงเลยว่าคุณครูจะตกใจมากขนาดนี้ ฉันคงไม่ได้ทำอะไรเกินไปใช่มั้ยคะ?"
1006202-22 = "[ns5] \"มะ... ไม่เลย! นักเรียนมาหาครูตามที่ต้องการได้เสมอแหละ!\""
1006202-24 = "[ns6] \"แต่ยังไงก็... ไว้คราวหน้าลองส่งข้อความให้ครูล่วงหน้าหน่อยก็ดีนะ\""
1006202-25 = "ก็บอกไปในแชตแล้วนี่คะ...?"
1006202-26 = "[s7] \"เรื่องนั้นก็จริงอยู่หรอก...\""
1006202-27 = "เพียงแต่ฉันไม่ได้บอกว่าเป็นตัวเองก็เท่านั้นเองค่ะ"
1006202-28 = "[ns8] \"ก็ควรจะบอกหน่อยสิ\""
1006202-29 = "อยากรู้ว่าฉันมาที่ชาเล่ต์ทำไมตั้งแต่เช้าเหรอคะ?"
1006202-30 = "อยากรู้ว่าฉันมาที่ชาเล่ต์ทำไมตั้งแต่เช้าเหรอคะ?"
1006202-31 = "พอดีจู่ๆ ฉันก็มีเวลาว่างขึ้นมาน่ะค่ะ"
1006202-32 = "[s] \"อธิบายให้ชัดกว่านี้หน่อยได้มั้ย?\""
1006202-33 = "คะ? ยากจังเลยนะคะ การอธิบายเนี่ย..."
1006202-34 = "[s] (มันยากขนาดนั้นเลยเหรอ...)"
1006202-35 = "ฉันเคยทำงานให้มาดามคนหนึ่งน่ะค่ะ"
1006202-36 = "ฉันเป็นทั้งบอดี้การ์ดและผู้ช่วยให้มาดาม"
1006202-37 = "แต่ว่า... ตอนนี้เกิดเรื่องขึ้นนิดหน่อยค่ะ"
1006202-38 = "มาดามทิ้งคำสั่งไว้ให้ฉัน 2-3 อย่าง แล้วก็หายตัวไปค่ะ"
1006202-39 = "ตอนนี้ฉันก็เลยไม่ต่างจากคนตกงานค่ะ ก็เลยกำลังคิดว่าจากนี้จะทำยังไงต่อดี"
1006202-40 = "[s] \"คิดหาวิธีแก้ปัญหาด้วยตัวเองสินะ... ยอดเยี่ยมมากเลย\""
1006202-41 = "และฉันก็ได้ข้อสรุปว่า ฉันจะมาทำงานประจำกับคุณครูที่ชาเล่ต์ค่ะ"
1006202-42 = "[s] \"ทำไมล่ะ?\""
1006202-43 = "ก็เพราะฉันคิดว่าชาเล่ต์ควรรับผิดชอบที่ทำให้ฉันต้องตกอยู่ในสภาพนี้ค่ะ"
1006202-44 = ""
1006202-48 = "มีปัญหาอะไรรึเปล่าคะ? หรือว่าเพิ่งจะคิดได้เหรอคะว่าสิ่งที่ตัวเองทำไปมันหนักหนาขนาดไหน?"
1006202-49 = "[s] \"ชักออกนอกเรื่องไปใหญ่แล้ว!\""
1006202-50 = "ฉันไม่ได้ออกนอกเรื่องเลยค่ะ นี่เป็นข้อสรุปที่สมเหตุสมผลที่สุดแล้วค่ะ"
1006202-51 = ""
1006202-53 = ""
1006202-55 = "เพราะอย่างนั้น จากนี้ไปฉันจะมาช่วยดูแลคุณครูค่ะ"
1006202-56 = "[ns] \"เดี๋ยวก่อนสิ! โทคิจัง? คุณโทคิ? ท่านโทคิ?\""
1006202-58 = "(แม้คุณครูจะคัดค้าน แต่ 'การดูแลคุณครู' ของโทคิก็เริ่มขึ้นแล้ว...)"
1006202-60 = "ถนนในเมือง"
1006202-61 = ""
1006202-64 = ""
1006202-65 = ""
1006202-66 = ""
1006202-69 = "โฮ่... ดูนั่นสิๆ คุณครูจากชาเล่ต์เอาชุดเมดให้เด็กนักเรียนใส่แล้วพาเดินตามต้อยๆ เลย"
1006202-70 = "คุณครูจากชาเล่ต์ก็เป็นคนดีอยู่หรอกนะ... แต่ก็มีข่าวลือว่าบางครั้งก็ทำอะไรไม่ดีกับนักเรียนด้วย#nมันเป็นเรื่องจริงเหรอนั่น?"
1006202-72 = "คนแถวนี้พูดถึงเรากันใหญ่เลยนะคะ พวกเขากำลังชื่นชมในการปฏิบัติหน้าที่ของฉันอยู่สินะคะ"
1006202-73 = "คุณครูไม่คิดว่านี่คือตัวอย่างของเมดที่ยอดเยี่ยมเหรอคะ?"
1006202-74 = "[s] \"ครูว่าพวกเขากำลังเข้าใจผิดมากกว่าชื่นชมอยู่นะ...?\""
1006202-75 = ""
1006202-77 = ""
1006202-79 = "ก็ดีค่ะ งั้นฉันคงต้องแสดงด้านที่สมบูรณ์แบบของฉันให้เห็น และแสดงให้ทุกคนเห็นว่าฉันสามารถ#nปกป้องคุณครูจากภัยคุกคามได้ค่ะ"
1006202-80 = "เพิ่มระดับการคุ้มกัน เปิดโหมดต่อสู้"
1006202-81 = ""
1006202-87 = ""
1006202-88 = ""
1006202-89 = "ตายแล้ว! อยู่ดีๆ ก็ให้เด็กถอดชุดนักเรียนออกด้วยเหรอเนี่ย?"
1006202-90 = "มาทำอะไรหน้าไม่อายกลางถนนที่ผู้คนขวักไขว่แบบนี้กันเนี่ย คงเป็นคนไม่ดีตามข่าวลือจริงๆ สินะ..."
1006202-91 = "[ns9] \"ไม่ใช่นะ ไม่ใช่แบบนั้น! คุณโทคิ!\"\n[ns10] \"ช่วยปิดโหมดต่อสู้ก่อนเถอะ!\""
1006202-94 = ""
1006202-96 = ""
1006202-98 = ""
1006202-102 = ""
1006202-104 = "น่าเสียดายจังค่ะ ลดระดับการคุ้มกันเป็นระดับ 1... แต่ยังไง ฉันก็จะคุ้มกันคุณครูต่อไปค่ะ"
1006202-106 = "อ๊ะ คุณครู พอจะมีเวลาสักครู่มั้ยคะ?"
1006202-107 = ""
1006202-109 = ""
1006202-110 = ""
1006202-111 = "ช่วยรอสักครู่นะคะ ถ้าอยากจะคุยกับคุณครู ก็ต้องคุยกับฉันก่อนค่ะ"
1006202-112 = "เอ๋...?"
1006202-113 = "อยากคุยกับคุณครูด้วยเหตุผลอะไรเหรอคะ? คุยหัวข้ออะไร? และจะคุยยังไงคะ?"
1006202-114 = "คาดว่าจะใช้เวลาเท่าไร และคิดว่าภายในเวลาที่กำหนดจะพูดคุยธุระเสร็จตามที่คิดไว้หรือเปล่าคะ?"
1006202-115 = "อะ... เอ่อ... ฉันแค่..."
1006202-116 = "[ns] \"ดะ... เดี๋ยวก่อน! เดี๋ยว!\""
1006202-118 = "(แล้วคุณครูก็ได้รับ 'การดูแล(?)' จากโทคิแบบนี้ไปตลอดทั้งวัน)"
1006202-119 = "(วันนี้ช่างเป็นวันที่... แปลกใหม่... มากกว่าที่เคย)"
1006202-124 = "[ns] \"วันนี้ขอบใจมากนะ... โทคิ...\""
1006202-125 = "แต่คุณครูดูเหนื่อยมากเลยนะคะ ไม่เป็นไรใช่มั้ยคะ?"
1006202-126 = "ไม่ต้องเป็นห่วงงั้นเหรอคะ? แต่ว่า..."
1006202-127 = "......"
1006202-128 = "หรือว่าคุณครูรู้สึกว่าการดูแลของฉันในวันนี้เป็นการรบกวนเกินไปหรือเปล่าคะ?"
1006202-129 = "[s] \"ไม่ใช่อย่างนั้นหรอก แต่ครูก็คิดว่ามันเข้มงวดเกินไปหน่อย...\""
1006202-130 = "ฉันกลับคิดว่านี่มันยืดหยุ่นกว่าปกติไปด้วยซ้ำค่ะ"
1006202-131 = "คะ? คิดว่าฉันล้อเล่นเหรอคะ?"
1006202-132 = ""
1006202-134 = ""
1006202-136 = "มองตาฉันสิคะ ฉันดูเหมือนนักเรียนที่ชอบพูดล้อเล่นเรื่อยเปื่อยงั้นเหรอคะ?"
1006202-137 = "[s] \"ที่ครูถามก็เพราะคิดว่าโทคิไม่ได้ล้อเล่นเลยยังไงล่ะ?!\""
1006202-138 = "งั้นก็โล่งอกไปทีค่ะ นี่เป็นการพิสูจน์แล้วว่าคุณครูเป็นคนที่มีวงจรความคิดปกติค่ะ"
1006202-139 = "[s] \"เอาเถอะ แต่ตอนที่มาช่วยครูน่ะ ไม่ต้องทำขนาดนั้นก็ได้...\""
1006202-140 = "อย่างงั้นเหรอคะ...?"
1006202-141 = "ฉันว่าคุณครูควรจะต้องตระหนักถึงตำแหน่งและความสำคัญของตัวเองให้มากกว่านี้นะคะ"
1006202-142 = "ถ้าคุณครูพูดอย่างนั้นก็... เข้าใจแล้วค่ะ"
1006202-143 = "[s11] \"วันนี้ครูสนุกมากเลยนะที่ได้ใช้เวลากับโทคิ\"\n[s12] \"แต่ต่อไปครูอยากให้ทำตัวสบายๆ กับครูกว่านี้หน่อยนะ\""
1006202-146 = "ทำตัวสบายๆ งั้นเหรอคะ...?"
1006202-147 = "เข้าใจแล้วค่ะคุณครู ถ้างั้นก็..."
1006202-148 = "นี่ครู ต่อไปก็ฝากตัวด้วยล่ะ เข้าใจรึเปล่า?"
1006202-149 = ""
1006202-153 = "ล้อเล่นค่ะ ฉันแค่เลียนแบบตามที่คุณเมดดีเด่นทำน่ะค่ะ ไม่ต้องตกใจขนาดนั้นก็ได้ค่ะคุณครู"
1006202-154 = "[s] \"ไหนว่าไม่ใช่คนที่ชอบล้อเล่นตามอำเภอใจไง!\""
1006202-155 = "โอกาสมาถึงแล้ว ก็ควรคว้าเอาไว้ไม่ใช่รึไงคะ"
1006202-156 = "[s] \"หักหลังนี่นา! หักหลังหัวใจของครู!\""
1006202-157 = "......"
1006202-158 = "ใช่ค่ะ เมื่อกี้ฉันเพิ่งหักหลังหัวใจของคุณครูไป ถือว่าเป็นชัยชนะของฉันค่ะ (ชูสองนิ้ว)"
1006202-159 = "[s] \"กลายเป็นคนแพ้ซะงั้น... ตอนนี้ครูหมดความมั่นใจที่จะเป็นครูแล้ว...\""
1006202-160 = "แบบนั้นก็แย่สิคะ คุณครูยังต้องได้รับความช่วยเหลือจากฉันนะคะ"
1006202-161 = "เพราะฉะนั้น ต้องสั่งงานให้คนว่างๆ อย่างฉันทำค่ะ"
1006202-162 = "[s] \"ครูแค่ถามเฉยๆ นะ นี่คือวิธี 'ทำตัวสบายๆ' ของโทคิเหรอ...?\""
1006202-163 = "...คิคิ"
1006202-164 = "แล้วถ้าใช่ คุณครูจะทำยังไงล่ะคะ?"
1006202-165 = "[s] \"ก็ได้... ถ้าโทคิสะดวกแบบนี้ก็... หึหึ... หึหึหึ\""
1006202-166 = "ขอบคุณที่ช่วยพูดแบบนี้นะคะคุณครู"
1006202-168 = "(จากนั้นโทคิก็กลับไปด้วยสีหน้าที่ดูพอใจมาก)"
1006202-169 = "(และในวันต่อมา...)"
1006202-173 = ""
1006202-176 = ""
1006202-178 = "สวัสดีค่ะคุณครู"
1006202-179 = "[s] \"รู้สึกเดจาวูแปลกๆ แฮะ!\""
1006202-180 = "ขอบคุณที่จำกันได้นะคะคุณครู"
1006202-181 = "วันนี้ฉันก็จะมาคุ้มกันคุณครูค่ะ"
1006202-182 = ""
1006202-184 = ""
1006202-186 = ""
1006202-187 = "ไปกันเลยมั้ยคะ?"
1006202-189 = "(คุณครูรู้สึกได้ว่าวันนี้ก็ต้องเป็นวันที่วุ่นวายอีกวันหนึ่งอย่างแน่นอน...)"
