[translation]
1006102-1 = "Easily Misunderstood"
1006102-5 = "Concerned by Sakurako's MomoTalk, I went to the grand cathedral at an hour when there was nothing scheduled."
1006102-6 = ""
1006102-8 = ""
1006102-9 = "I spotted Sakurako praying at the other end of the mostly-empty chapel."
1006102-10 = "..."
1006102-11 = "[s1] Approach and wait for her prayer to end.\n[s2] Approach and join her prayer."
1006102-12 = ""
1006102-13 = ""
1006102-15 = ""
1006102-17 = ""
1006102-19 = "...?"
1006102-20 = ""
1006102-22 = ""
1006102-23 = ""
1006102-24 = "Hmm...?"
1006102-25 = ""
1006102-27 = ""
1006102-28 = ""
1006102-29 = "H-Huh? Sensei?! When did you get here?"
1006102-30 = "[s3] \"I'm sorry if I interrupted.\"\n[s4] \"I didn't mean to surprise you...\""
1006102-31 = "N-No. That's fine. As a matter of fact, I just finished prayer."
1006102-32 = "N-No. That's fine. As a matter of fact, I just finished prayer."
1006102-33 = "But...what are you doing here?"
1006102-34 = "At this time, no one really..."
1006102-35 = "Huh?"
1006102-36 = "You came...because I called you?"
1006102-37 = "I'm afraid I don't know what you mean. I've never called..."
1006102-38 = "My... MomoTalk?"
1006102-39 = ""
1006102-42 = "[ns5] \"You said you wanted a chance to talk...\"\n[ns6] Show her your MomoTalk history."
1006102-43 = ""
1006102-45 = ""
1006102-46 = "Ah. It's possible that..."
1006102-47 = ""
1006102-49 = ""
1006102-50 = "Ah. What I said..."
1006102-51 = "Um. S-So. The truth is, the messages I sent..."
1006102-52 = "They really were just meant to be a hello. There wasn't a deeper meaning."
1006102-53 = "...Honestly."
1006102-54 = "*sigh*"
1006102-55 = "I owe you an apology. It seems I've caused yet another misunderstanding."
1006102-56 = "[s7] \"Hey, no worries.\"\n[s8] \"What do you mean, another misunderstanding?\""
1006102-59 = "Um... The trouble is, I always seem to be misunderstood by others."
1006102-60 = "My interactions with others always feel a bit...stilted. Perhaps I cause them to feel awkward? I'm not sure."
1006102-61 = "Perhaps my position of leadership causes the other Sisters to feel a sense of distance."
1006102-62 = "I consider the failing mine. I've been seeking advice from the other Sisters to improve myself, but so far, I have not been successful."
1006102-63 = "Ah, but not for lack of trying on their part, of course! They are all good people and do their best to understand me. In fact, they sometimes even give me advice proactively."
1006102-64 = "When I sent you the MomoTalk message today, I was attempting to put some advice from another Sister to use."
1006102-65 = "She told me, if I added a laugh sound before or after a message, it would sound friendlier."
1006102-66 = "[s9] \"Aha...\"\n[s10] \"So that's what the 'Heeheehee' was about.\""
1006102-69 = "To be frank, it worries me a bit. It wouldn't be so troubling if it only affected me personally, but I'm a member of Trinity Cathedral's Sisterhood."
1006102-70 = "As a Sister, one hopes to be kindly and easy to talk to."
1006102-71 = "When I mentioned I was hoping for a chance to speak with you... I wanted to ask your counsel regarding this very problem."
1006102-72 = ""
1006102-74 = ""
1006102-75 = ""
1006102-76 = "Ah, I digress, though. I hope we can discuss this at some point in the future."
1006102-77 = "Anyway. My apologies for disturbing your day over nothing, Sensei. Perhaps I could walk you out?"
1006102-78 = ""
1006102-80 = ""
1006102-81 = "This way..."
1006102-82 = ""
1006102-84 = ""
1006102-87 = "Park in Front of Trinity Cathedral"
1006102-88 = "Well, this is as far as I go. Farewell, then."
1006102-89 = "It was a pleasure to talk to you today, even if only for a short while."
1006102-90 = "Heehee."
1006102-91 = "Please have a blessed—"
1006102-92 = ""
1006102-96 = ""
1006102-97 = ""
1006102-99 = "Oh, it's Sister Sakurako. Hey, Sister Sakurako!"
1006102-100 = "Good morning. Is your day going well?"
1006102-102 = "Oh, Sisters!"
1006102-103 = "Heehee. Good morning."
1006102-104 = "I wish you peace today, as all days, Sisters."
1006102-105 = ""
1006102-107 = ""
1006102-108 = ""
1006102-109 = "Please know that I am always watching over you. In every moment, no matter how small..."
1006102-110 = ""
1006102-113 = ""
1006102-115 = "Heehee... Anyways, have a blessed day."
1006102-116 = ""
1006102-119 = "Eeek! Uh, um, yes!"
1006102-120 = "W-Well, same to you! We have to be off!"
1006102-121 = ""
1006102-123 = ""
1006102-125 = "Oh... Be careful! You could hurt yourself, going that fast..."
1006102-126 = ""
1006102-129 = "[ns11] \"A 'heehee' at that moment...\"\n[ns12] \"I see how it is.\""
1006102-132 = "...Hmm? Sensei, I didn't catch that."
1006102-133 = "Oh, nothing to worry about?"
1006102-134 = "I understand."
1006102-135 = "In that case, I'll be going."
1006102-136 = ""
1006102-138 = ""
1006102-140 = "I watched Sakurako's veil flutter behind her for a moment as she left before returning to Schale."
