[translation]
1007402-1 = "วันนี้ปลอดภัยค่ะ"
1007402-2 = "(สถานที่ที่ฮานาโกะบอกมาก็คือป่าที่อยู่ในส่วนลึกของเกาะ)"
1007402-3 = "(แสงแดดอบอุ่น สายลมพัดเอื่อยๆ เย็นสบาย ทำให้ที่นี่ดูเป็นสถานที่พิเศษ)"
1007402-4 = "อ๊ะ คุณครู... มาเร็วกว่าที่คิดอีกนะคะ"
1007402-5 = ""
1007402-8 = ""
1007402-9 = "ฮุฮุ ไม่ต้องรีบร้อนมาแบบนี้ก็ได้นะคะ..."
1007402-10 = "...หืม?"
1007402-11 = "คุณครู... เป็นอะไรไปเหรอคะ? ดูเหมือน... กำลังประหม่าอยู่เลยนะคะ...?"
1007402-12 = "[s1] \"มะ...ไม่ใช่แบบนั้นสักหน่อย! ในมือถืออะไรอยู่น่ะ?\"\n[s2] \"ว่าแต่ว่าในมือถืออะไรอยู่น่ะ?\""
1007402-15 = "อ้อ นี่เหรอคะ? ผลไม้น่ะค่ะ ที่นี่มีผลไม้จากหลากหลายเขตภูมิอากาศรวมอยู่เยอะมากเลยค่ะ"
1007402-16 = "แปลกมากเลยใช่มั้ยล่ะคะ ดูนี่สิคะคุณครู มีทั้งกล้วย พีช แล้วก็สตรอว์เบอร์รี่..."
1007402-17 = "แล้วก็ยังมีแตงโม... รวมถึงผลไม้เปลือกแข็งต่างๆ เต็มไปหมด... "
1007402-18 = "...? คุณครู?"
1007402-19 = "[s3] \"เอ่อ อ้อ... อื้อ นั่นสินะ\"\n[s4] \"คือว่าผลไม้ที่พูดมาพวกนั้นน่ะ มันรู้สึกแบบ...\""
1007402-20 = ""
1007402-21 = ""
1007402-23 = ""
1007402-24 = ""
1007402-25 = "...อ่า"
1007402-26 = "อ่ะ...ฮ่า... ฮุฮุ ฉันพอเข้าใจแล้วละค่ะ"
1007402-27 = "อืม... พอคิดแบบนั้นก็รู้สึกผิดขึ้นมานิดๆ อยู่นะคะ เหมือนเมื่อก่อนก็เคยมีสถานการณ์คล้ายๆ กัน#nแบบนี้เกิดขึ้นเหมือนกันสินะคะ?"
1007402-28 = "ฉันพอจะทราบค่ะว่าคุณครูกังวลเรื่องอะไร แต่คราวนี้ไม่ต้องกังวลหรอกนะคะ"
1007402-29 = "ไม่สิ ไม่ใช่ 'คราวนี้'... แต่ควรจะเป็น 'ที่นี่' มากกว่ารึเปล่านะ?"
1007402-30 = "ยังไงก็เถอะค่ะ ไม่ต้องห่วงว่าจะเกิด 'เรื่องแบบนั้น' ที่นี่หรอกนะคะ ตอนนี้น่ะ... ไม่ใช่ช่วงเวลาแบบ 'ตามปกติ' นี่คะ"
1007402-31 = "...คะ?"
1007402-32 = "ตอนนี้ต่างกับเวลาปกติยังไงน่ะเหรอคะ? ก็ต้องต่างสิคะ อันดับแรก ที่นี่ไม่ใช่เขตของทรีนิตี้ ไม่มีใคร#nคอยจับตาดูพวกเราหรอกค่ะ"
1007402-33 = "ถึงจะทำให้คุณครูลำบากใจในสถานที่แบบนี้... ก็คงไม่มีความหมายอะไรใช่มั้ยล่ะคะ?"
1007402-34 = "[s5] \"เป็นประเภททำอะไรต้องมีความหมายสินะ\"\n[s6] \"อย่างน้อยก็รู้ตัวสินะว่าทำให้ลำบากใจน่ะ!\""
1007402-37 = "แต่ว่า... เรื่องนี้ก็เป็นเพราะคุณครูทั้งหมดเลยนะคะ ฉันเตือนคุณครูไปก่อนแล้วนี่คะ"
1007402-38 = "คนที่เมินคำเตือนและตามฉันก็คือคุณครูเองนะคะ"
1007402-39 = "แต่ฉันไม่ได้ไม่พอใจเรื่องนั้นหรอกนะคะ"
1007402-40 = ""
1007402-42 = ""
1007402-43 = "ฮุฮุ..."
1007402-44 = "[s7] \"ฮานาโกะ?\"\n[s8] \"เมื่อกี้ว่าอะไรนะ?\""
1007402-47 = "ฮุฮุฮุ เอาเป็นว่าเหมือนกับที่บอกไปตอนนั้นค่ะ เรื่องพวกนี้... คุณครูคงจะรับมือได้ใช่มั้ยล่ะคะ?"
1007402-48 = "ฉันแค่... อยากรักษาความเงียบสงบและความรู้สึกสบายๆ แบบในตอนนี้เอาไว้ให้ได้นานที่สุดค่ะ"
1007402-49 = "อยู่ที่นี่ฉันไม่ต้องใส่ใจสายตาคนอื่น ไม่ต้องกังวลว่าคนอื่นจะคิดยังไง หรือคาดหวังอะไรจากฉัน"
1007402-50 = "อยู่ที่นี่มันตรงกันข้ามเลยค่ะ ฉันสามารถพูดหรือแสดงสิ่งที่คิด สิ่งที่ต้องการออกมาได้ตรงๆ อย่างอิสระ"
1007402-51 = "ถ้าเกิดว่าคุณอุยหรือโคฮารุจังอยู่ที่นี่ละก็ ฉันก็คงเอาผลไม้พวกนี้ไปให้แล้วชวนคุยอะไรสนุกๆ"
1007402-52 = "แต่น่าเสียดายที่ตอนนี้... ที่นี่มีแค่ฉันกับคุณครูเท่านั้นน่ะค่ะ เพราะงั้น... ไม่ต้องกังวลหรอกนะคะ"
1007402-53 = "อ๊ะ หรือว่าที่จริงแล้วคุณครูมีจุดประสงค์แอบแฝง..."
1007402-54 = "มาหาฉันที่นี่ แล้วก็คาดหวัง 'การปฏิบัติตัวแบบปกติ' ของฉันอยู่หรือเปล่าคะ? ถ้าเป็นแบบนั้นละก็#nฉันคงจะเผลอพูดอะไรแปลกๆ ไปโดยไม่ได้สนใจความต้องการของคุณครูไปซะแล้ว..."
1007402-55 = "ถ้างั้นอย่างน้อยในตอนนี้ ฉันนี้ก็ควรเติมเต็มความคาดหวังของคุณครู..."
1007402-56 = "[s9] \"เปล่า เปล่าเลย! แบบที่เป็นอยู่ตอนนี้แหละดีแล้ว!\"\n[s10] \"ไม่เป็นไร เป็นแบบตอนนี้ต่อไปนั่นแหละดีแล้ว\""
1007402-59 = "...ฮุฮุ"
1007402-60 = "เข้าใจแล้วค่ะ ถ้างั้นก่อนอื่น..."
1007402-61 = ""
1007402-63 = ""
1007402-64 = "...เรากลับไปที่แคมป์กันก่อนเถอะค่ะ รบกวนช่วยถือพวกนี้ให้หน่อยนะคะ"
1007402-65 = ""
1007402-67 = ""
1007402-69 = "(หลังจากนั้นคุณครูก็แบ่งผลไม้จากฮานาโกะมาช่วยถือ แล้วเดินกลับไปที่แคมป์ด้วยกัน)"
1007402-70 = "(และทันทีที่กลับไปถึงแคมป์ ฮานาโกะก็ใช้ผลไม้ที่นำกลับมาทำบางอย่างให้ทุกคนดูจนทำให้เกิด#nบรรยากาศแปลกๆ ขึ้นในแคมป์...)"
