[translation]
1007302-1 = "Something Seems Off"
1007302-4 = "I wandered around for quite a bit, trying to find Ui."
1007302-11 = "I finally spotted her in a distant corner of the beach, perched between some boulders."
1007302-15 = "[ns1] \"There you are.\"\n[ns2] \"Is everything okay, Ui?\""
1007302-20 = "Ah."
1007302-21 = "Sensei? Why are you here? Wait, before that..."
1007302-22 = "HOW are you here? I thought I was off-the-grid out here..."
1007302-23 = "...Excuse me? "
1007302-24 = "You just kept looking for me...? F-For how long?"
1007302-29 = "S-S-Since the MomoTalk?!"
1007302-30 = "I don't understand. Why would you do such a thing?"
1007302-31 = "I assured you there was no problem... Well, that any problem was just because of me..."
1007302-32 = "You can't just come running at every problem, Sensei. What am I supposed to do?"
1007302-33 = "[s3] \"I couldn't just leave you alone.\"\n[s4] \"I don't do anything I don't want to, Ui.\""
1007302-36 = "E-Even so... Um..."
1007302-37 = "Oh... Why I'm out here?"
1007302-38 = "Well..."
1007302-39 = "It's seems even more trivial to say out loud..."
1007302-43 = "*sigh*"
1007302-47 = "How do I best put this? The swimsuits, the beach games... I just don't fit in with this kind of scene."
1007302-48 = "So I was embarrassed being out here. That's it. I'm sorry it's anti-climactic."
1007302-49 = "I'm obviously not bubbly and charming like the others, and no one is taking a second look at this face..."
1007302-50 = "I'm a self-aware person. I know the things other people say about me, the way the room shifts when I walk in it."
1007302-51 = "I do better staying in the library, or somewhere indoors at the very least... I'd be more comfortable there...not wearing this swimsuit..."
1007302-52 = "How do I put my feelings into words? I feel... Ugh."
1007302-53 = "It's just overwhelming. I don't know how to handle a place or situation like this."
1007302-54 = "...Oh."
1007302-55 = "Wait. Please don't start trying to reassure me."
1007302-56 = "\"You're so cute in that swimsuit,\" or some other compliment like that, right? But I'm fine. Really."
1007302-57 = "I wasn't looking for someone to give me fake niceties... I have no delusions about the reality of things."
1007302-58 = "Hearing compliments I can't believe in will only make me feel worse."
1007302-59 = "...Yeah..."
1007302-60 = "...What?"
1007302-61 = "What do you mean? What were you going to say then?"
1007302-62 = "[s5] \"Isn't this a place meant for people to find comfort?\"\n[s6] \"Don't you think you're paying a little too much attention to yourself?\""
1007302-65 = "What... What do you mean?"
1007302-66 = "Hmm... Wait, let me think about this for a second..."
1007302-70 = "Um..."
1007302-71 = "I... guess...?"
1007302-72 = "If you look at it from that perspective, it's much less crowded here than Trinity."
1007302-73 = "Visitors here are few and far between..."
1007302-74 = "I can't say those few visitors exactly make me excited, but it's not the worst thing to see one or two people milling about."
1007302-75 = "[s7] \"A lot of people around here probably feel the same way.\"\n[s8] \"That's what drives people to come to far out places like this.\""
1007302-78 = "I see... We're all out here because of similar feelings..."
1007302-79 = "I think I get it."
1007302-82 = "People who seek out isolated places are probably all trying to, well, avoid people."
1007302-83 = "So hiding out here isn't so different from me hiding away in my library."
1007302-86 = "It's certainly...plausible."
1007302-87 = "But...can I do that, even wearing clothing like this?"
1007302-88 = "[s9] \"It's a nice change of pace too, isn't it?\"\n[s10] \"Why not consider it a kind of...escape?\""
1007302-91 = "Hm..."
1007302-92 = "Like an escape... From the everyday me back at Trinity..."
1007302-93 = "I can see the logic. After all, someone who walks around in something like this every day must not have all their synapses firing."
1007302-94 = "[s11] \"Oh. Uh. Hm.\"\n[s12] \"W-Well...\""
1007302-97 = "...I'm kidding."
1007302-98 = "I don't mean this in a bad way at all, but you're very persuasive, Sensei."
1007302-99 = "Speaking with you actually does make me feel better. It always feels genuine."
1007302-100 = "...I mean it."
1007302-101 = "You can't persuade someone with empty words."
1007302-105 = "People just come to me for things they need, so I'm used to that. Compliments that mean nothing, niceties for the sake of manners."
1007302-106 = "You start to see the pattern when it happens over and over again, and conversations feel bland and like a waste of effort."
1007302-107 = "That's when I started to distance myself from people. My relationships were all superficial."
1007302-108 = "I think it was too late for me to go back by the time I realized who I'd become."
1007302-109 = "I started to really embrace the isolation, so I wasn't used to socializing anymore. I take criticism to heart and avoid people as much as I can."
1007302-110 = "I've actually kind of enjoyed having juniors who are so straightforward and always willing to nag me... So I really appreciate all of them."
1007302-111 = "...That's depressing, huh? Pitiful. But that's just me."
1007302-112 = "Despite all of that, I can't seem to escape that persistent handful of people who find me no matter where I hide."
1007302-113 = "You're all so weird..."
1007302-114 = "For some reason, my underclassmen treat me like an actual senior to rely on, and then people follow me all the way out here to help me with my problems."
1007302-115 = "...Including you, Sensei. Actually, you're probably the worst one."
1007302-116 = "[s13] \"Ah! Well, that's a given!\"\n[s14] \"Birds of a feather flock together?\""
1007302-121 = "...Heh..."
1007302-122 = "...Heehee... Oh, geez..."
1007302-123 = "...Sure."
1007302-124 = "...We can leave it at that."
