[translation]
1007803-1 = "ฉันชอบการระเบิด"
1007803-3 = "(ในช่วงเย็นๆ ค่ำๆ คุณครูออกไปที่ไซต์ก่อสร้างที่ถูกทิ้งร้างตามที่คาสุมิบอก)"
1007803-4 = "[ns1] \"ไซต์ก่อสร้างที่ถูกทิ้งร้างสินะ\"\n[ns2] \"รอบนี้มาระเบิดที่นี่เหรอ...\""
1007803-7 = "โอ้ว~ ต้องอย่างนี้สิคุณครู! มาตรงเวลานัดเลยนะ!"
1007803-8 = ""
1007803-11 = "ใช่แล้ว ตามที่ฉันบอกไปเลย! ที่นี่คือกองบัญชาการลับที่ 89 ของฉันในเดือนนี้"
1007803-12 = "หืม? ระหว่างที่ไม่ได้เจอกัน เหมือนจำนวนฐานลับจะเพิ่มขึ้นงั้นเหรอ?"
1007803-13 = "วะฮะฮะฮ่า! มันก็แน่นอนอยู่แล้ว! ตรงจุดที่ถูกยกเลิกกับจุดที่ทำไม่สำเร็จตามแผน ฉันก็นับหมด#nด้วยเหมือนกัน!"
1007803-14 = "แต่จำนวนครั้งมันไม่สำคัญหรอก เอาเถอะๆ..."
1007803-15 = "ตอนนี้เราไม่มีเวลาว่างมายืนคุยกันอยู่หรอกนะ~"
1007803-16 = "เอาละคุณครู รีบตามฉันมา! ฉันจะเล่าแผนการที่น่าตื่นตาตื่นใจให้ฟัง!!"
1007803-17 = ""
1007803-19 = ""
1007803-21 = ""
1007803-22 = "ฮืม... ประมาณนี้ก็น่าจะได้แล้วแหละเนอะ"
1007803-23 = "ขอโทษที่เอาแต่เรียกคุณครูมาในที่ซอมซ่อนะ... แต่ฉันต้องซ่อนตัวน่ะ ไม่งั้นเดี๋ยวจะงานเข้าเอาได้"
1007803-24 = "พอดีว่าคนมันมีชื่อเสียงน่ะนะ คนอื่นก็เลยอยากได้ตัวกันไปทั่วเลย"
1007803-25 = "ทั้งคณะกรรมการวินัย ทั้งบริษัทผลิตอาวุธ ไหนจะพวกแก๊งอันธพาลที่มาระเบิดท่อประปาตอนที่ฉันทำ#nงานระเบิดของตัวเองอีก..."
1007803-26 = "เฮ้อ ฉันรู้ดีว่าเราอาจเจอเรื่องแบบนี้ได้ในชีวิต แต่พอฉันสร้างออนเซ็นสำเร็จ ทุกคนก็จะดีใจกันแน่ๆ!"
1007803-27 = "...หืม? คุณครู? ทำหน้าแบบนั้นหมายความว่ายังไง?"
1007803-28 = "...หืม?"
1007803-29 = "ฉันถูกไล่ล่าและโดนขัดขวางการทำงานอยู่ตลอด แต่ทำไมถึงยังดูชิลแบบนี้ได้งั้นเหรอ?"
1007803-30 = "แล้วก็ตอนที่ฉันทำงานไม่สำเร็จ สงสัยว่าฉันเสียดายหรือท้อแท้หรือเปล่างั้นเหรอ?"
1007803-31 = ""
1007803-33 = ""
1007803-34 = "...ฮะฮ่า"
1007803-35 = "คุณครู บางทีเราอาจมีเรื่องที่คิดไม่เหมือนกันอยู่นิดหน่อยนะ"
1007803-36 = "คุณครูน่าจะคิดว่าฉันชอบ 'การพัฒนาออนเซ็นให้สำเร็จ' อยู่ก็ได้..."
1007803-37 = "แน่นอนว่าฉันตั้งเป้าหมายให้ทุกแผนการพัฒนาออนเซ็นสำเร็จลุล่วง แต่นั่นก็ไม่ได้แปลว่าฉันจะ 'รับไม่ได้หากทำไม่สำเร็จ' นี่"
1007803-38 = "คุณครู..."
1007803-39 = "ฉันน่ะชอบการระเบิดทุกประเภทเป็นชีวิตจิตใจเลย พอจะเข้าใจความหมายของคำนี้มั้ย?"
1007803-40 = "มันหมายความว่า... ต่อให้เป็น 'การระเบิดที่ไม่สำเร็จ' ฉันก็ชอบเหมือนกัน"
1007803-41 = "ใช่แล้วละ ฉันน่ะชอบการระเบิดเป็นชีวิตจิตใจ ทั้งการระเบิดขนาดใหญ่ ขนาดเล็ก ทั้งการระเบิดที่สำเร็จและไม่สำเร็จ"
1007803-42 = "ระเบิดที่ทำให้ถูกไล่ล่า ระเบิดที่ถูกขัดขวาง หรือระเบิดที่ฉันต้องฟันฝ่าจนสำเร็จ...!"
1007803-43 = "ฉันชอบการระเบิดในที่ที่ใครก็คาดไม่ถึง จนเกิดเป็นทิวทัศน์ใหม่ที่ไม่เคยมีให้เห็นมาก่อนน่ะ"
1007803-44 = "แต่ถึงจะต้องเศร้าทุกครั้งที่เสียดินระเบิดที่เตรียมมาอย่างดีไป เพราะถูกพวกกรรมการวินัยมาขัดขวาง ฉันก็#nไม่เป็นไรหรอกนะ~"
1007803-45 = "แล้วฉันก็ชอบทุกที่ที่จะมีน้ำพุร้อนออกมาได้ด้วย! ส่วนที่ที่เห็นแล้วมีหวังว่า 'ถ้ามีน้ำพุร้อนตรงนี้ก็น่าจะ#nสวยเลย' ก็ไม่เลวด้วยเหมือนกัน!"
1007803-46 = "สิ่งสำคัญไม่ได้อยู่ที่ผลลัพธ์ แต่อยู่ที่การเตรียมการเพื่อสร้างออนเซ็นต่างหาก! มันเป็นทุกอย่างของ#nกระบวนการระเบิดน่ะ!"
1007803-47 = "ที่ที่สามารถขุดได้ ที่ที่ควรจะขุด และสิ่งที่เกิดได้ในสถานที่นั้น ฉันชอบหมดเลย! เป็นไงล่ะ? พอจะ... เข้าใจความรู้สึกนี้มั้ย?"
1007803-48 = "และหนึ่งในสถานที่นั้น..."
1007803-49 = "ที่ฉันหมายตาไว้อยู่ก็คือ... อาคาร <ชาเล่ต์>"
1007803-50 = ""
1007803-53 = "[ns3] \"...เดี๋ยวก่อน ว่าไงนะ?\"\n[ns4] \"......หืม!?\""
1007803-56 = "วะฮะฮะฮะฮ่า!! ดูทำหน้าตกใจเข้าสิ"
1007803-57 = "...ทีนี้เข้าใจหรือยังล่ะคุณครู?"
1007803-58 = "ฉันอยากให้คุณครูเข้ามามีส่วนร่วมในแผนการระเบิดของฉันอย่างกระตือรือร้นมากกว่านี้"
1007803-59 = "จะคิดว่านี่เป็นการข่มขู่ฉันก็ไม่ติดนะ ฉันคุ้นเคยกับการถูกตักเตือนแล้วน่ะ"
1007803-60 = "จะไม่ชอบฉันเพราะมองว่าฉันเป็นตัวปัญหาก็ได้ เพราะสิ่งที่สำคัญไม่ใช่ความรู้สึกของอีกฝ่าย แต่เป็นการตัดสินใจของฉันต่างหาก"
1007803-61 = "ที่ฉันพูดไปก่อนหน้านี้คือสิ่งที่ฉันคิดมาตลอด ต่อให้จะไม่เกี่ยวกับคุณครูก็เถอะ"
1007803-62 = "เพราะอย่างนั้น... ฉันอยากให้คุณครูช่วยพิจารณา 'อย่างจริงจัง' อีกหน่อย"
1007803-63 = "...เข้าใจความสำคัญของเรื่องนี้แล้วใช่มั้ยคุณครู?"
1007803-64 = "นี่คือการทำเพื่อฉันเอง และเพื่อคุณครูเอง"
1007803-65 = "จากนี้พวกเราจะมาหารือเรื่องจุดระเบิดต่อไปกัน"
1007803-66 = "และถ้าจำเป็นก็จะระเบิดวันนี้เลยด้วย"
1007803-67 = "...ต่อให้จะดึกแค่ไหนฉันก็ไม่หวั่น"
1007803-68 = "[s] \".........\""
1007803-70 = "[ns5] \"......ก็ได้ ครูจะรับข้อเสนอนั้นให้\"\n[ns6] \"แต่ครูก็ไม่ได้ยอมง่ายขนาดนั้นหรอกนะ\""
1007803-73 = "วะฮะฮะฮะฮะฮ่า!!! ดีละ ดีเลย! ต้องแบบนี้สิ!"
1007803-74 = "งั้นเราไปหาสถานที่อย่างจริงๆ จังๆ กันเลยมั้ย?"
1007803-75 = "สถานที่ที่... ทั้งฉันและคุณครู! และทุกๆ คนจะมีความสุขด้วยกันได้!"
1007803-76 = "สถานที่จุดระเบิดใหม่ที่น่าตื่นตาตื่นใจ!!"
1007803-78 = "(หลังจากนั้นคุณครูกับคาสุมิก็ง่วนกันอยู่บนแผนที่เพื่อหารือเรื่องพิกัดที่จะระเบิดถัดไปจนถึงดึกดื่น)"
1007803-79 = "(คุณครูพยายามโน้มน้าวให้ระเบิดในพื้นที่ที่ปลอดภัย จนต้องอยู่หารือกันถึงดึกดื่นเพราะมีความเห็นไม่#nตรงกัน)"
1007803-82 = "(กว่าคาสุมิจะได้พิกัดพื้นที่ระเบิดที่ตรงใจและเผลอหลับคาแผนที่ไปก็เป็นเวลารุ่งสางแล้ว)"
