[translation]
1008605-1 = "#title;히나와 피아노"
1008605-3 = "#na;(히나의 부름을 받고 도착한 파티 홀엔 어딘지 모르게 적막이 감돌고 있었다.)"
1008605-4 = "[ns] \"여기가 맞을 텐데, 히나는 어디에…….\""
1008605-5 = "#na;히나 드레스;아, 선생님. 시간에 딱 맞춰 와줬구나."
1008605-6 = "[s] \"아, 히나──\""
1008605-12 = "[ns1] \"히나가 피아노 앞에……?\"\n[ns2] \"저기, 히나가 이곳에 날 부른 이유가…….\""
1008605-13 = "#st;[-1200,-530];serial;60;[wa:800]― [log=히나 드레스]지금부터……[/log]"
1008605-14 = "#st;[-1200,-530];serial;60;[wa:800]― [log=히나 드레스]지금부터……[/log]"
1008605-15 = "#st;[-1200,-630];serial;60;[wa:1500]― [log=히나 드레스]선생님을 위해 [wa:1200]연주할게.[/log]"
1008605-18 = "[ns] \"피아노 연주라면 저번에 게헨나 파티에서 했었잖아?\""
1008605-19 = "#st;[-1200,-530];serial;60;[wa:400]― [log=히나 드레스]아, [wa:600]아니. [wa:1500]그때는…….[/log]"
1008605-20 = "#st;[-1200,-630];serial;60;[wa:1650]― [log=히나 드레스]두, [wa:800]둘만 있던 게, [wa:1200]아니었으니까……. [/log]"
1008605-23 = "#st;[-1200,-530];serial;60;― [log=히나 드레스]그…… [wa:1900]피아노를 [wa:900]계속 연습했던 건…….[/log]"
1008605-24 = "#st;[-1200,-630];serial;60;[wa:2600]― [log=히나 드레스]선생님에게 들려주기 위해서…….[wa:80] [/log]"
1008605-27 = "#st;[-1200,-530];serial;60;― [log=히나 드레스]이대로, [wa:1300]들려주지 못하면……[/log]"
1008605-28 = "#st;[-1200,-630];serial;60;[wa:2800]― [log=히나 드레스]분명 [wa:700]후회할 것 같았으니까.[/log]"
1008605-31 = "[ns] \"히나가 그렇게 말한다면, 알았어. 그럼 정좌하고 들을게.\""
1008605-32 = "#st;[-1200,-530];serial;60;[wa:500]― [log=히나 드레스]으, [wa:300]응?[/log]"
1008605-33 = "#st;[-1200,-630];serial;60;[wa:1300]― [log=히나 드레스]아니, [wa:500]그, [wa:400]그렇게 대단한 건 아니, [wa:1400]야…….[/log]"
1008605-36 = "#st;[-1200,-530];serial;60;― [log=히나 드레스]그런 식으로 [wa:900]기대하면……[/log]"
1008605-37 = "#st;[-1200,-630];serial;60;[wa:2000]― [log=히나 드레스]좀 [wa:700]곤란할지도.[/log]"
1008605-40 = "[ns] \"히나가 나를 위해 연주해 주는 거잖아. 전력으로 들어야지.\""
1008605-41 = "#st;[-1200,-530];serial;60;[wa:400]― [log=히나 드레스]아……. [wa:1900]으, [wa:1500]으응…….[/log]"
1008605-42 = "#st;[-1200,-630];serial;60;[wa:1750]― [log=히나 드레스]그래……. [wa:1950]당신은, [wa:1500]늘 그랬지.[/log]"
1008605-45 = "#st;[-1200,-530];serial;60;[wa:300]― [log=히나 드레스]응……[/log]"
1008605-46 = "#st;[-1200,-630];serial;60;[wa:1900]― [log=히나 드레스]그럼, [wa:1100]제대로 들어줘.[/log]"
1008605-49 = "#st;[-1200,-530];serial;60;[wa:100]― [log=히나 드레스]……당신에게 전하는, [wa:2200]나만의 연주를.[/log]"
1008605-56 = "#na;(히나의 연주를 들으며, 그렇게 우리는 조용히 둘만의 시간을 함께했다.)"
