[translation]
1008003-1 = "Everyone Has a Weakness"
1008003-2 = "I met with Shokuhou at an empty playground."
1008003-3 = ""
1008003-6 = ""
1008003-7 = "I was curious what sort of place this would be... I certainly wasn't expecting this."
1008003-8 = "So? Why did you call me here, Sensei?"
1008003-9 = "...Oh?"
1008003-10 = "Because I'm having trouble concentrating... You thought I should get some fresh air?"
1008003-11 = "If it were that simple, surely I would have already done so..."
1008003-12 = "Well, I suppose it's not a terrible idea to get out for a bit."
1008003-13 = "Hm?"
1008003-14 = "Since we're here, you'd like to go for a short jog?"
1008003-15 = "Ah... Hmm... Well, well. There's really no need to do something like that."
1008003-16 = "Rather, I don't think it would be wise..."
1008003-17 = "It's not suitable for an intelligent person such as myself, you know."
1008003-18 = ""
1008003-21 = "Sensei?! Are you listening? It looks as though you're getting ready to run..."
1008003-22 = "[s1] \"We'll take it easy!\"\n[s2] \"It's just a light jog!\""
1008003-25 = ""
1008003-28 = "Sensei! Where are you going by yourself?!"
1008003-29 = "W-Wait! Not so fast...!"
1008003-30 = ""
1008003-32 = ""
1008003-33 = ""
1008003-34 = "We didn't even complete one lap before..."
1008003-35 = ""
1008003-40 = "[ns] \"...?\""
1008003-42 = "[ns3] \"...Shokuhou?\"\n[ns4] \"You've gotten quiet all of a sudden...\""
1008003-48 = ""
1008003-49 = ""
1008003-50 = ""
1008003-51 = ""
1008003-52 = "*pant* S-Stop... *pant*"
1008003-53 = "I have...called out so many times... *pant* *pant*"
1008003-54 = "*pant* *pant*"
1008003-55 = "Ugh..."
1008003-56 = ""
1008003-58 = ""
1008003-61 = "[ns5] \"Shokuhou?!\"\n[ns6] \"Are you okay?! Shokuhou!\""
1008003-67 = "I picked Shokuhou up off the ground and rushed her to the hospital."
1008003-68 = ""
1008003-69 = "..."
1008003-70 = "...Hmm? Oh my..."
1008003-71 = "Did I faint..."
1008003-72 = ""
1008003-75 = "...Sensei?"
1008003-76 = "Have you been waiting by my side this entire time? ...Why are you looking at me like that?"
1008003-77 = "...?"
1008003-78 = "You're sorry...? Ah. Is it because of what happened at the park?"
1008003-79 = "You don't owe me an apology. If anything, I'm a bit embarrassed about what happened."
1008003-80 = "I know I can seem haughty, but that couldn't be further from the truth. It's simply that I'm cautious."
1008003-81 = "Hmm... By the way... I don't really remember what happened after I fell..."
1008003-82 = "You brought me to a doctor, yes? I imagine they gave me a physical check-up."
1008003-83 = "That's just fine. Did they find anything to be concerned about?"
1008003-84 = "Hm?"
1008003-85 = "You're avoiding my question. Did they find something worrying?"
1008003-86 = "If there are any strange symptoms that have arisen since coming here..."
1008003-87 = "[s7] \"No, it's not exactly like that...\"\n[s8] \"It's just that...\""
1008003-90 = ""
1008003-93 = "...?"
1008003-94 = "So there's nothing overtly wrong. Isn't that a good thing?"
1008003-95 = "The doctor got...angry? Why...?"
1008003-96 = "Oh."
1008003-97 = "So my body is weak from a lack of exercise, is that it...?"
1008003-98 = ""
1008003-100 = ""
1008003-101 = "H-Hmm..."
1008003-102 = "I see... Well... As it happens..."
1008003-103 = "I'm the sort to rely on my mind, not my body..."
1008003-104 = "..."
1008003-105 = "Sensei?"
1008003-106 = "I hardly need to use my ability to see what you're thinking..."
1008003-107 = "Even if you shoot me those looks..."
1008003-109 = "I won't do it."
