[translation]
1008602-1 = "ฮินะกับชุดเดรส (1)"
1008602-2 = "สวัสดีคุณครู ฉันมาแล้ว"
1008602-3 = "[s1] \"เข้ามาสิ ฮินะ! อยากดื่มอะไรมั้ย?\"\n[s2] \"กาแฟ? ชาแดง? อ้อ มีชาอู่หลงกับโคล่าด้วย...\""
1008602-6 = "งั้นฉันขอกาแฟแล้วกัน"
1008602-7 = "[s] \"โอเค ครูจะตั้งใจชงให้เลย!\""
1008602-8 = ""
1008602-11 = "พอวันนี้ได้มาสำนักงานชาเล่ต์..."
1008602-12 = "ก็รู้สึกว่าไม่ได้มาที่นี่นานแล้วเลยนะ..."
1008602-13 = "[s] \"การที่ฮินะมาหาครูที่ชาเล่ต์ เป็นเหมือนฝันเลยละ\""
1008602-14 = "จะ... จริงๆ เลย นี่ไม่ใช่เรื่องจะต้องตื่นเต้นเกินไปสักหน่อย..."
1008602-15 = ""
1008602-17 = ""
1008602-18 = "หืม? ที่วางอยู่บนโต๊ะ... คือราเม็งถ้วยที่กินเหลือไว้เหรอ...?"
1008602-19 = "นอกจากนั้นยังมี... เสื้อผ้าที่วางไว้เกลื่อน... แล้วก็ภาชนะอาหารที่ยังไม่จัดให้เข้าที่...."
1008602-20 = "คุณครู ที่อยู่ตรงนี้คือของเล่นเหรอ...?"
1008602-21 = "[s] \"อ๊ะ อันนั้นน่ะเหรอ....\""
1008602-22 = "คุณครู..."
1008602-23 = "[s3] \"พะ... พอดีช่วงนี้งานของชาเล่ต์มีเยอะจนไม่มีเวลาใส่ใจเลย\"\n[s4] \"แต่ครูก็ตั้งใจจะจัดการเร็วๆ นี้แหละ! จริงๆ นะ...!\""
1008602-26 = "ดะ... เดี๋ยวก่อน ฉันไม่ได้จะบ่นว่าคุณครูสักหน่อย"
1008602-27 = "เพราะถ้างานยุ่ง บางทีฉันก็จะไม่มีเวลาจัดข้าวของรอบๆ ตัวเหมือนกัน"
1008602-28 = "ฉันน่ะไม่ว่าอะไรหรอก..."
1008602-29 = "แต่นอกจากฉันแล้วก็ยังมีนักเรียนคนอื่นอีกหลายคนที่แวะมาที่ชาเล่ต์ เพราะงั้นฉันว่าคุณครูควรทำตัว#nให้เป็นตัวอย่างของนักเรียนหน่อย"
1008602-30 = "[s] \"อึก...! พูดถูกจนเถียงไม่ออกเลย...\""
1008602-31 = "ถ้าคุณครูไม่ว่าอะไรละก็... ไว้ฉันแวะมาช่วยจัดข้าวของที่ชาเล่ต์ดีมั้ย?"
1008602-32 = "เห็นแบบนี้ฉันก็มั่นใจว่าฉันจัดของและทำความสะอาดได้ดีเลยนะ..."
1008602-33 = "ตะ... แต่ฉันก็จะมาตอนที่คุณครูสะดวกให้มาเท่านั้นนะ..."
1008602-34 = "[s5] \"แต่ฮินะก็งานยุ่งเรื่องคณะกรรมการวินัยอยู่แล้วนะ\"\n[s6] \"ครูไปทำให้เดือดร้อนขนาดนั้นไม่ได้หรอก\""
1008602-37 = "อ่า... ก็ได้"
1008602-38 = "......"
1008602-39 = ""
1008602-41 = ""
1008602-42 = "ถ้าคุณครูว่าอย่างนั้นละก็ เข้าใจแล้ว"
1008602-43 = "[s] \"อ่า... ฮินะ ครูทำอะไรผิดไปรึเปล่า...\""
1008602-44 = "ไม่หรอก ทำผิดอะไรกันล่ะ ไม่มีทางเป็นแบบนั้นอยู่แล้ว"
1008602-45 = "เฮ้อ... งั้นฉันจะเข้าเรื่องเลยแล้วกัน คุณครู"
1008602-46 = "[s] \"อะ... อื้ม...!\""
1008602-47 = "อืม..."
1008602-48 = "คือ... ที่ฉันมาขอคำปรึกษากับคุณครูในวันนี้"
1008602-49 = "ก็เพราะว่าครั้งนี้จะมีจัดปาร์ตี้สังสรรค์ในเกเฮนน่าโดยแพนเดโมเนียม โซไซตี้น่ะ ถึงมันจะกะทันหันไป#nหน่อยก็เถอะ..."
1008602-50 = "[s] \"ปาร์ตี้สังสรรค์เหรอ... ในเกเฮนน่าก็มีอะไรแบบนี้สินะ...\""
1008602-51 = "มันเป็นปาร์ตี้ที่เชิญบุคคลสำคัญในเกเฮนน่า รวมถึงผู้มีตำแหน่งสูงในแวดวงการเมืองและธุรกิจของ#nคิโวทอสมาเข้าร่วมน่ะ"
1008602-52 = "ถ้าให้พูดตามตรง ฉันก็ไม่อยากจะไปร่วมงานแบบนั้น แล้วก็คิดว่ามันไม่มีความหมายด้วย"
1008602-53 = "แต่ในเมื่อมันเป็นงานที่เกี่ยวข้องกับส่วนรวม ในฐานะประธานกรรมการแล้วฉันก็ควรไปให้คนอื่นเห็น#nหน้าเห็นตาหน่อย"
1008602-54 = "สุดท้ายก็เลยต้องไปเข้าร่วมน่ะ"
1008602-55 = "ถึงจะไม่อยากไปเลยก็เถอะ"
1008602-56 = ""
1008602-58 = ""
1008602-59 = "อืม ก็ช่วยไม่ได้นะ... ต่อให้ไม่อยากไป แต่มันก็เป็นหน้าที่"
1008602-60 = "[s] (คงไม่อยากไปจริงๆ สินะ...)"
1008602-61 = "แต่ว่า... มีปัญหาอยู่อย่างหนึ่ง... อ่า... จะให้พูดเองมันก็ยังไงๆ อยู่"
1008602-62 = "แต่ฉันไม่คุ้นเคยกับงานเลี้ยงสังสรรค์แบบนี้สักเท่าไร..."
1008602-63 = "ฉันก็เลยไม่รู้เลยว่าจะต้องเตรียมตัวยังไงดีสำหรับงานครั้งนี้ แล้วก็ไม่รู้ด้วยว่าต้องเริ่มจากตรงไหน"
1008602-64 = "ก็เลยอยากขอความช่วยเหลือจากคุณครู... ถึงได้มาหาแบบนี้น่ะ"
1008602-65 = "การมาขอคำปรึกษาและพึ่งพาคุณครูแม้กระทั่งเรื่องเล็กน้อยแบบนี้น่ะ... ฉันก็รู้ดีว่าในฐานะประธาน#nกรรมการแล้วมันเป็นการกระทำที่ไม่ถูกต้องนัก"
1008602-66 = "แต่ว่า..."
1008602-67 = "[s] \"ไม่หรอก ฮินะ ครูดีใจด้วยซ้ำที่อยากจะพึ่งพากัน\""
1008602-68 = "อืม งั้นเหรอ...?"
1008602-69 = "[s] \"อืม สิ่งที่ต้องเตรียมก่อนไปร่วมงานปาร์ตี้เหรอ...\""
1008602-71 = "[ns] \"ฮินะมีชุดเดรสหรือยังล่ะ?\""
1008602-72 = "ชุดเดรสเหรอ...?"
1008602-73 = "[s7] \"ถ้าเป็นงานสำคัญๆ ครูว่าเราควรเลือกชุดให้เข้ากับกาลเทศะนะ\"\n[s8] \"แต่นี่ก็เป็นเรื่องพื้นฐานอยู่แล้ว ถ้าครูพูดอะไรผิดไปละก็...\""
1008602-76 = "อืม คุณครูพูดถูกแล้วละ"
1008602-77 = "อ่า จริงด้วยสินะ พอเป็นเรื่องที่แน่นอนอยู่แล้ว ฉันก็เลยยิ่งมองข้ามไปน่ะ"
1008602-78 = "พอมาคิดดูแล้ว ถ้าใส่เครื่องแบบของคณะกรรมการวินัยที่เคยใส่อยู่ทุกวันไปงานปาร์ตี้ก็คงจะแตกต่าง#nจากคนอื่น"
1008602-79 = "คงต้องเตรียมชุดเดรสแล้วละ"
1008602-80 = "นอกจากชุดที่เข้ากับงานเลี้ยงสังสรรค์แล้ว... ก็ต้องมีเครื่องประดับและรองเท้าที่เข้ากับชุดด้วย...#nอืม... คงต้องให้ความสำคัญกับการแต่งตัวน่าดูเลยนะ"
1008602-81 = "ขอบคุณนะ คุณครู ฉันพอรู้แล้วละว่าควรจะเริ่มเตรียมอะไรบ้าง"
1008602-82 = "[s] \"โล่งอกไปทีนะที่ครูช่วยได้\""
1008602-84 = "[ns] \"ไหนๆ ก็พูดถึงเรื่องนี้แล้ว ให้ครูไปซื้อชุดกับฮินะ...\""
1008602-85 = "หืม? ไม่เป็นไร ไม่ต้องซื้อใหม่หรอก"
1008602-87 = "[ns] \"ที่นี่คือ... ที่เก็บของเหรอ?\""
1008602-88 = "อืม เป็นที่เก็บของที่ฉันใช้อยู่น่ะ"
1008602-89 = "ฉันจะเก็บของเก่าๆ หรือของใช้ส่วนตัวที่ไม่ค่อยได้ใช้ไว้ที่นี่"
1008602-90 = "แล้วชุดเดรสที่ฉันเคยใส่เมื่อนานมาแล้วก็น่าจะอยู่ที่ไหนสักแห่งในนี้แหละ"
1008602-91 = "[s] \"อืม... ความรู้สึกเหมือนเดจาวูยังไงไม่รู้...\""
1008602-92 = "เสื้อผ้าที่ไม่ค่อยใส่บ่อยๆ น่าจะเก็บไว้ในชั้นวางฝั่งนี้นะ... ขอฉันหาเดี๋ยวนะ"
1008602-93 = ""
1008602-95 = ""
1008602-96 = "น่าจะอยู่ที่ไหนสักแห่งในนี้..."
1008602-97 = "อ่า..."
1008602-98 = ""
1008602-101 = "[ns] \"อ๊ะ ครูหาเจอแล้ว นี่ไง...\""
1008602-103 = ""
1008602-105 = "อ่า..."
1008602-106 = "[s] \"เอ๋... นี่ไม่ใช่ชุดเดรส แต่เป็นชุดบัลเล่ต์...\""
1008602-107 = "ดะ... เดี๋ยวก่อน! คุณครู! ชุดที่อยู่ในมือนั่น...!"
1008602-108 = ""
1008602-111 = ""
1008602-112 = ""
1008602-113 = "ฮู่ว... งั้นมาหากันต่อเถอะ"
1008602-114 = "[s] \"ฮินะ ชุดเมื่อกี้มันชุดบัลเล่ต์...\""
1008602-115 = "เอาละ มาหากันต่อเถอะ คุณครู"
1008602-116 = "[s] \"ขะ... เข้าใจแล้ว\""
1008602-117 = ""
1008602-119 = ""
1008602-120 = "ฮู่ว... ตรงนี้ไม่น่าจะมีแล้ว งั้นต่อไปคงต้องหาตรงนั้นแทน... มันควรจะอยู่แถวๆ นี้สิ..."
1008602-121 = ""
1008602-123 = ""
1008602-124 = "ต้องอยู่แถวๆ นี้..."
1008602-125 = "อ่า..."
1008602-126 = ""
1008602-129 = "[ns] \"ดีละ ครั้งนี้ต้องใช่ชุดเดรสแน่ๆ...\""
1008602-132 = "[ns] \"หืม...? นี่มันชุดพละนี่นา...\""
1008602-133 = "อ่า ชุดนั้นอยู่ตรงนั้นนี่เอง ฉันลืมไปแล้วว่าเอาไปเก็บไว้ที่ไหน ก็เลยหาอยู่นานเลย"
1008602-134 = "[s] \"............\""
1008602-135 = ""
1008602-138 = ""
1008602-140 = ""
1008602-141 = ""
1008602-142 = "คุณครู...?! มะ... เมื่อกี้คุณครูจะทำอะไรน่ะ?!"
1008602-143 = "[s] \"มะ... ไม่นะ ไม่ได้จะทำอะไรเลย\""
1008602-144 = "แต่ฉันเห็นว่ายื่นหน้าเข้าไปใกล้ชุดนะ..."
1008602-145 = "ช่างเถอะ คงไม่มีอะไรหรอก"
1008602-146 = "ฉันอาจจะแค่อารมณ์อ่อนไหวไปหน่อยก็ได้"
1008602-147 = "[s9] \"ขอโทษนะ ครูสารภาพดีกว่า เป็นอย่างที่ว่านั่นละ\"\n[s10] \"อืม คนเรามันก็ลืมตัวกันได้...\""
1008602-148 = "วะ... ว่าไงนะ?!"
1008602-149 = "เฮ้อ... ให้ตายสิ ประมาทไม่ได้เลยจริงๆ"
1008602-150 = "อืม..."
1008602-151 = "ฮู่ว... ยะ... ยังไงตอนนี้สิ่งสำคัญคือการหาชุดเดรส..."
1008602-152 = "งั้นก็หาต่อเถอะ..."
1008602-154 = "(หลังจากนั้นทั้งสองคนก็ช่วยกันค้นหาไปทั่วห้องเก็บของ จนสุดท้ายก็ได้เจอชุดที่ตามหา)"
1008602-156 = "อ่า... หาเจอแล้ว"
1008602-157 = "เจอแล้วละคุณครู ชุดที่ฉันเคยใส่เมื่อนานมาแล้ว นี่ไง"
1008602-158 = ""
1008602-160 = ""
1008602-162 = "โล่งอกไปทีนะที่หาเจอ ไม่จำเป็นต้องเสียเงินซื้อใหม่โดยเปล่าประโยชน์แล้ว"
1008602-163 = "[s] \"อืม ฮินะ แต่ครูว่าชุดนี้มัน...\""
1008602-164 = "งั้นรอตรงนี้เดี๋ยวนะ ฉันจะไปเปลี่ยนชุดมาเดี๋ยวนี้ละ"
1008602-165 = "คุณครูช่วยบอกฉันหน่อยว่าในสายตาของคุณครูแล้ว ชุดนี้เหมาะกับฉันรึเปล่า"
1008602-166 = "[s] \"ถ้าเรื่องนั้นครูช่วยได้อยู่แล้ว แต่ว่าชุดนี้มัน...\""
1008602-167 = "เอาละ"
1008602-168 = ""
1008602-170 = ""
1008602-171 = "ถ้างั้นก็ทำแบบนี้... เริ่มใส่จากตรงนี้..."
1008602-172 = "อืม ส่วนตรงนี้ก็ทำแบบนี้..."
1008602-173 = "เอ๋...? ทำไมถึงใส่ไม่เข้านะ..."
1008602-174 = ""
1008602-177 = "อ่า..."
1008602-178 = "[s] \"ฮินะ?! โอเคดีป่าว?! เหมือนได้ยินเสียงแปลกๆ เลย...!\""
1008602-179 = "มะ... ไม่เป็นไร! ไม่ใช่เรื่องใหญ่อะไรหรอก...!"
1008602-180 = "ก็แค่... พยายามยัดตัวเองลงชุด... จนชุดขาดน่ะ!"
1008602-181 = "[s] \"นั่นเรื่องใหญ่เลยนะ?!\""
1008602-182 = "อะ... เอาเถอะน่า คุณครู...! อย่าเพิ่งเดินมาทางนี้นะ... ห้ามเดินเข้ามาเด็ดขาดเลย!"
1008602-183 = "ถ้าเข้ามา ฉันไม่ยกโทษให้จริงๆ ด้วย...!"
1008602-184 = "[s] \"รับทราบ...\""
1008602-188 = "เฮ้อ... ชุดขาดจนได้..."
1008602-189 = "ฉันเอาชุดที่เคยใส่เมื่อก่อนมาใส่ซ้ำอยู่หลายครั้ง ก็เลยคิดว่าครั้งนี้ก็น่าจะใส่ชุดนี้ได้ด้วยน่ะ"
1008602-190 = "นี่ฉันโตขึ้นแบบที่ตัวเองก็ไม่รู้ตัวงั้นเหรอ?"
1008602-191 = "[s] \"เอ่อ ฮินะ ชุดเดรสนั่นใส่ครั้งสุดท้ายเมื่อไรเหรอ?\""
1008602-192 = "หืม...? ครั้งสุดท้ายที่ใส่ ก็น่าจะตอนปาร์ตี้คริสต์มาส..."
1008602-193 = "น่าจะตอน ป.2 น่ะ?"
1008602-194 = "[s] \"ชุดที่เคยใส่ตอน ป.2 จะใส่พอดีกับตอนนี้ได้ยังไง?!\""
1008602-195 = "งะ... งั้นเหรอ...?"
1008602-196 = "การเติบโต... ก็เป็นปัญหายากอยู่สินะ..."
1008602-197 = "งั้นจะทำยังไงดีล่ะ..."
1008602-198 = "[s] \"ฮินะ ในเมื่อเป็นแบบนี้ เราไปซื้อชุดใหม่กันมั้ย?\""
1008602-199 = "ไปซื้อชุด... กับคุณครูเหรอ?"
1008602-200 = "อืม... ก็คงไม่มีทางเลือกอื่น เพราะถ้าจะเข้าร่วมงานปาร์ตี้ก็ต้องเตรียมตัว..."
1008602-201 = "และคุณครูก็มาเพื่อช่วยฉันเรื่องนั้น"
1008602-202 = "ถ้างั้น... ถึงจะทำให้คุณครูลำบาก แต่ฉันขอรบกวนหน่อยได้มั้ย?"
1008602-203 = "[s] \"ได้อยู่แล้ว! วางใจครูได้เลย!\""
1008602-204 = "อื้ม... ขอบคุณนะ"
1008602-205 = "งั้นไว้เราไปด้วยกันนะ..."
1008602-206 = ""
1008602-208 = ""
