[translation]
1008802-1 = "เวลาที่เงียบสงบ"
1008802-3 = "(คุณครูมุ่งหน้าไปยังที่ที่คาโยโกะบอก และที่นั่นคือซอยเล็กๆ แถวโรงละครโอเปร่า)"
1008802-4 = "(ซอยนี้เหมือนเป็นซอยลับที่อยู่ห่างไกล ถ้าไม่ตั้งใจหาดีๆ คงไม่รู้ว่ามีที่แบบนี้อยู่ด้วย)"
1008802-5 = ""
1008802-9 = "อ่า... ครู"
1008802-10 = "มาเร็วกว่าที่คิดอีกนะ ทางนี้ๆ"
1008802-11 = ""
1008802-16 = ""
1008802-17 = "[ns1] \"คาโยโกะ?\"\n[ns2] \"มาอยู่คนเดียวในที่แบบนี้เหรอ?\""
1008802-20 = "อ่า... ก็ใช่"
1008802-21 = "ใกล้ๆ โรงละครโอเปร่ามีคนพลุกพล่านซะส่วนมากน่ะ มันไม่เหมาะจะนั่งพักเงียบๆ หรอก"
1008802-22 = "แต่ตอนนี้ฉันก็อยู่ระหว่างทำงาน จะไปไหนไกลก็คงไม่ได้..."
1008802-23 = ""
1008802-25 = ""
1008802-26 = "ก็เลยมาหาที่เงียบๆ แบบนี้น่ะ"
1008802-27 = "ครูไม่เคยทำหรอกเหรอ? แบบนี้เรียกว่ายังไงนะ?"
1008802-28 = "อืม..."
1008802-29 = "โดดงาน...?"
1008802-30 = "[s3] \"ครูขอใช้สิทธิ์ที่จะไม่พูดแล้วกัน\"\n[s4] \"ขอไปตอบในชั้นศาลแทนได้มั้ย?\""
1008802-33 = "ฮุฮุ..."
1008802-34 = "ฉันได้คำตอบแล้วละ ครูไม่ต้องพูดอะไรมากกว่านี้ก็ได้"
1008802-35 = "แล้วก็ไม่ต้องห่วงให้มากไปหรอกนะ"
1008802-36 = "ฉันแค่มาพักแป๊บเดียว เดี๋ยวก็กลับไปแล้วละ"
1008802-37 = ""
1008802-39 = ""
1008802-40 = "หืม...?"
1008802-41 = "คิดว่าตัวเองไม่น่ามา เพราะฉันอยากพักคนเดียวงั้นเหรอ?"
1008802-42 = ""
1008802-44 = ""
1008802-45 = "ไม่หรอก"
1008802-46 = "ถ้างั้นฉันจะบอกไปทำไมล่ะว่าอยู่ที่นี่ ที่ครูมาที่นี่ก็เพราะฉันเป็นคนบอกพิกัดไปต่างหากล่ะ"
1008802-47 = "แต่ก็นะ... ถ้าเป็นกับคนอื่นฉันคงพูดอ้อมค้อมหรือเปลี่ยนเรื่องคุยไปแล้ว แต่นี่เป็นครู งั้นฉันถึงบอกไปไง"
1008802-48 = "ครูไม่ต้องห่วงฉันหรอกนะ แล้วต่อให้ครูอยู่ที่นี่ ฉันก็ไม่ได้อึดอัดหรือทำตัวไม่ถูกหรอก"
1008802-49 = "กลายเป็นว่าฉันชอบเสียด้วยซ้ำที่เราไม่ต้องทำอะไรเลยและมานั่งคุยกันแบบนี้"
1008802-50 = "ถ้าจะให้พูดให้ชัดเจนก็คือ ครูเป็นคนที่อยู่ด้วยแล้วสบายใจน่ะ"
1008802-51 = "แต่ว่า..."
1008802-52 = ""
1008802-54 = ""
1008802-55 = "ฮุฮุ..."
1008802-56 = "ขอโทษนะ ฉันเอาแต่พูดอะไรตั้งเยอะอยู่คนเดียวเลย ทั้งที่ไม่ได้คิดจะทำแบบนี้เลย"
1008802-57 = "ครูเองก็คงมาพักผ่อนเหมือนกัน ถ้าฉันเอาแต่ชวนคุยก็คงไม่ได้พักพอดี"
1008802-58 = "ถ้างั้น..."
1008802-59 = ""
1008802-61 = ""
1008802-62 = "ก็มานั่งพักด้วยกันนะ..."
1008802-69 = "(หลังจากนั้นคุณครูกับคาโยโกะก็นั่งมองท้องฟ้ายามเย็นด้วยกัน)"
1008802-70 = "(ไม่มีการสนทนาใดๆ เป็นเวลากว่า 10 นาที)"
1008802-72 = ""
1008802-73 = ""
1008802-75 = ""
1008802-76 = "อ่า... กี่โมงแล้วเนี่ย..."
1008802-77 = "[s5] \"เรากลับเข้าไปกันมั้ย?\"\n[s6] \"เราพักแบบไม่ได้คุยอะไรกันเลยจริงๆ นะเนี่ย\""
1008802-78 = ""
1008802-80 = ""
1008802-81 = "ฮุฮุ..."
1008802-82 = ""
1008802-84 = ""
1008802-85 = "กลับก็ได้..."
1008802-86 = ""
1008802-88 = ""
1008802-89 = "ฮุฮุ..."
1008802-90 = ""
1008802-92 = ""
1008802-93 = "นั่นสินะ..."
1008802-96 = "― [log=카요코 드레스]ดีจังเลยนะ...[/log][wa:830] "
1008802-99 = "― [log=카요코 드레스]ที่ได้...[/log]"
1008802-101 = "― [log=카요코 드레스]มาอยู่กับใครสักคน แล้วนั่งเหม่อลอยแบบนี้[/log][wa:1820] "
1008802-104 = "― [log=카요코 드레스]เหมือนว่า... ฉันไม่เคยทำมาก่อนเลย[/log][wa:500] "
1008802-107 = "― [log=카요코 드레스]ใช่... ปกติฉันคิดว่า[/log][wa:540] "
1008802-109 = "― [log=카요코 드레스]ชอบอยู่คนเดียวมาตลอด[/log]"
1008802-112 = "[ns7] \"พอได้มานั่งเหม่อ ครูก็สบายใจไปด้วยนะ\"\n[ns8] \"ถ้าได้ทำแบบนี้บ่อยๆ ก็คงจะดีนะ\""
1008802-113 = "― [log=카요코 드레스]จริงเหรอ...?[/log][wa:770] "
1008802-114 = "― [log=카요코 드레스]จริงเหรอ...?[/log][wa:770] "
1008802-117 = "― [log=카요코 드레스]ฮุฮุ ค่อยยังชั่วนะ ที่คุณครูก็ชอบทำแบบนี้ด้วย[/log][wa:1360] "
1008802-120 = "― [log=카요코 드레스]มันดีอยู่แล้วละ ที่ได้มาอยู่เงียบๆ แบบนี้น่ะ[/log][wa:2720] "
1008802-123 = "― [log=카요코 드레스]อ้อ... แต่ใช่ว่าฉันจะไม่ชอบเวลาปกติหรอกนะ[/log][wa:2020] "
1008802-125 = "― [log=카요코 드레스]แต่ถ้าเป็นคุณครู... ก็น่าจะเข้าใจนะ [/log][wa:230] "
1008802-128 = "― [log=카요코 드레스]ฮู่ว... เอ่อ...[/log][wa:2700] "
1008802-131 = "― [log=카요코 드레스]ช่วยอยู่ด้วยกันต่อ...[/log]"
1008802-133 = "― [log=카요코 드레스]อีกนิด... อีกนิดหนึ่งเถอะนะ[/log][wa:2180] "
1008802-136 = "ขอบคุณที่มาหานะครู ฉันไม่ได้พักผ่อนสนุกๆ แบบนี้มานานเลยละ"
1008802-137 = "ที่จริง... มันดีกว่าการพักผ่อนอยู่คนเดียวเอามากๆ เลย"
1008802-138 = "หืม...?"
1008802-139 = "ไม่ต้องพูดตามมารยาทขนาดนั้นก็ได้งั้นเหรอ? หมายความว่ายังไงน่ะ?"
1008802-140 = "[ns9] \"กฎตอนนี้คือห้ามพูดไม่ใช่เหรอ?\"\n[ns10] \"หมายความอย่างที่คิดแหละ\""
1008802-141 = ""
1008802-142 = ""
1008802-144 = ""
1008802-145 = "อ้อ"
1008802-146 = "ฮุฮุ..."
1008802-147 = "ครู ฉันรู้สึกแบบนี้มาตลอดเลยละ..."
1008802-148 = ""
1008802-150 = ""
1008802-151 = ""
1008802-152 = "ครูเป็นคนตลกจริงๆ เลยนะ"
