[translation]
1008006-1 = "มาตรฐานสูง"
1008006-2 = "(คุณครูออกไปหาโชคุโฮวเพราะคิดว่าเธอกำลังตกอยู่ในสถานการณ์ลำบาก)"
1008006-3 = ""
1008006-7 = ""
1008006-8 = "...เอ๋? คุณครู?"
1008006-9 = "มาเพราะเป็นห่วงฉันงั้นเหรอ"
1008006-10 = "คุณครูเป็นคนใจดีเลยนะเนี่ย ฉันคิดแบบนี้มาหลายครั้งแล้วด้วยนะ"
1008006-11 = "แต่ว่า อืม... จะว่ายังไงดีนะ"
1008006-12 = "ถึงจะเป็นคุณครูก็เถอะ แต่ก็มีบางเรื่องที่รู้สึกยากที่จะขอร้องอยู่ดี..."
1008006-13 = "[s1] \"ยากจะขอร้องเหรอ?\"\n[s2] \"ไม่ใช่เรื่องการหาร้านอาหารหรอกเหรอ?\""
1008006-16 = "ก็ใช่ ฉันกำลังหาร้านอาหารอยู่..."
1008006-17 = "แต่ว่าฉันค่อนข้างเลือกเยอะอยู่น่ะ ต่อให้หิวแค่ไหนก็ยังไม่ทิ้งนิสัยพวกนั้นไม่ได้ซะที"
1008006-18 = "ฉันไม่ใช่คนที่กินง่ายๆ หรือกินอะไรก็ได้น่ะ มนุษย์แบบนี้น่ะตัวปัญหาเลยใช่ไหมล่ะ?"
1008006-19 = "ในโลกเดิมที่ฉันเคยอยู่ก็มีร้านที่ฉันไปกินอยู่บ่อยๆ อยู่ 2-3 ร้าน และต่อให้ไม่ใช่ร้านพวกนั้น ฉันก็มัก#nจะวิเคราะห์สภาพของร้านที่จะเข้าไปก่อนอยู่ดี..."
1008006-20 = "แต่พอมาอยู่ที่นี่มันก็ไม่ได้ง่ายแบบนั้น หรือว่าบางทีตอนนี้ฉันควรตั้งสมาธิแล้วลองใช้พลังดูนะ?"
1008006-21 = "[s3] \"ต้องขนาดนั้นเลยเหรอ...?\"\n[s4] \"ต้องทำให้เป็นเรื่องใหญ่อย่างนั้นเลยเหรอ?\""
1008006-24 = "มันก็แน่นอนอยู่แล้วมั้ย? เราต้องให้ความสำคัญกับสิ่งที่เราจะเอาเข้าปากสิ"
1008006-25 = "ปกติแล้วฉันกินแค่อาหารที่ทำจากวัตถุดิบออร์แกนิกสดใหม่เท่านั้น นี่คือเงื่อนไขพื้นฐานเลยละ"
1008006-26 = "แต่ร้านอาหารส่วนมากก็ไม่ได้ทำเหมือนกับที่ตัวเองโฆษณาร้านไว้... เราก็เลยไม่อาจรู้ได้..."
1008006-27 = "ว่าพวกเขาใช้วัตถุดิบออร์แกนิกจริงๆ หรือเปล่า? แล้วร้านนั้นเชื่อถือได้จริงๆ หรือเปล่า?"
1008006-28 = "ถ้าไม่ลองอ่านใจดู เราก็ไม่อาจรู้ความคิดของเจ้าของร้านหรือเชฟได้เลย"
1008006-29 = "เพราะอย่างนั้น ตอนนี้ฉันถึงได้ลำบากใจอยู่ยังไงล่ะ"
1008006-30 = "พออยู่ที่นี่ ฉันก็ตรวจสอบเรื่องอาหารไม่ได้เลย แต่ถ้าจะให้ไปกินอาหารที่ไม่แน่ใจเรื่องวัตถุดิบ..."
1008006-31 = "สู้ให้ฉันอดอาหารซะยังดีกว่า ฉันพูดจริงนะคุณครู"
1008006-32 = ""
1008006-35 = "[ns5] \"เรื่องกินคือจริงจังมาก...\"\n[ns6] \"รสนิยมการกินเป็นแบบนี้นี่เอง\""
1008006-38 = "...หืม?"
1008006-39 = "อะไรน่ะ ทำไมทำสีหน้าแบบนั้น? คิดอะไรดีๆ ออกงั้นเหรอ?"
1008006-40 = "...หืม?"
1008006-41 = "ขอให้ไว้ใจคุณครูสักครั้งงั้นเหรอ? หมายถึงอะไร? คุณครูจะทำอาหารให้ฉันเองหรือไง?"
1008006-42 = "...อ้าว ไม่ใช่เหรอ?"
1008006-43 = "จะแนะนำร้านอาหารให้...?"
1008006-44 = "คุณครู... ไม่ได้ยินที่ฉันพูดไปเมื่อกี้เหรอ? ฉันไม่ใช่คนที่จะกินอะไรก็ได้ง่ายๆ หรอกนะ..."
1008006-45 = "...หืม? ตั้งใจฟังที่ฉันพูดทุกคำเลยงั้นเหรอ?"
1008006-46 = "...แต่ก็ยังมั่นใจ...?"
1008006-47 = ""
1008006-49 = ""
1008006-50 = "โฮ่..."
1008006-51 = "พอฟังคุณครูพูดแบบนั้น ฉันก็ชักสงสัยขึ้นมาแล้วละ"
1008006-52 = "งั้นลองไปร้านที่จะแนะนำดูดีมั้ยนะ? แต่ว่าคุณครู เมื่อกี้ฉันก็บอกไปแล้วเนอะ?"
1008006-53 = "ว่าต่อให้ฉันไม่ได้อ่านใจ แต่พอชิมฉันก็รู้ได้ทันทีเหมือนกันเลยนะ"
1008006-54 = "ถ้ามันไม่ผ่านเกณฑ์ของฉัน ฉันจะกลับเลยนะ รู้เอาไว้ก่อนด้วยล่ะ"
1008006-55 = "ถ้างั้นก็... ไปกันเลยมั้ย?"
1008006-57 = ""
1008006-58 = "...ที่นี่เหรอ? "
1008006-59 = "ดูสะอาดสะอ้านดีนี่ ถึงจะยังไม่แน่ใจเรื่องอาหารก็เถอะ..."
1008006-60 = "ไหนๆ คุณครูก็แนะนำร้านนี้มาแล้ว งั้นฉันก็จะเลือกสั่งเมนูตามคุณครูก็แล้วกัน"
1008006-61 = "อืม... จะสั่งแบบนั้นเหรอ..."
1008006-62 = "รับทราบครับ งั้นคุณคนที่มาด้วย..."
1008006-63 = "ฉันขอเมนูเดียวกันค่ะ "
1008006-64 = "ครับ ได้เลยครับ ช่วยรอสักครู่นะครับ"
1008006-66 = "(หลังจากนั้นไม่นาน)"
1008006-68 = ""
1008006-73 = "อาหารที่สั่งได้แล้วครับ เชิญรับประทานให้อร่อยนะครับ!"
1008006-74 = ""
1008006-76 = ""
1008006-77 = "อืม... เป็นที่แบบนี้เองสินะ"
1008006-78 = "คุณครูดูมั่นใจมากเลยนะเนี่ย หรือว่าจะรู้จักกับเจ้าของร้านหรือเชฟที่นี่?"
1008006-79 = "อ้าว ไม่ใช่หรอกเหรอ? แล้วทำไมถึงได้ดูสบายๆ แบบนี้ล่ะ"
1008006-80 = "อาหารที่นี่อาจจะถูกปากคุณครู แต่ความจริงแล้วร้านนี้อาจจะเอาวัตถุดิบอะไรไม่รู้มาทำอาหารก็ได้นี่?"
1008006-81 = "ไม่มีทางเป็นอย่างนั้นเด็ดขาดงั้นเหรอ?"
1008006-82 = "เด็ดขาด' เลยงั้นเหรอ..."
1008006-83 = "อ่า ฉันไม่ได้จะหาเรื่องหรอกนะ ก็แค่คุณครูมีท่าทีต่างจากที่เห็น ฉันก็เลยประหลาดใจนิดหน่อยน่ะ"
1008006-84 = "คุณครูเป็นคนประเภทที่พูดอย่างรอบคอบอยู่แล้วนี่นา อะไรดีก็ว่าดี ประมาณนั้นน่ะ?"
1008006-85 = "ฉันก็เลยประหลาดใจที่คุณครูแสดงท่าทางที่มั่นใจออกมาได้ ถึงแม้จะอยู่ในสถานการณ์ที่มั่นใจได้#nไม่เต็มร้อยก็ตาม"
1008006-86 = "จะว่ายังไงดี..."
1008006-87 = "คงมีวิธีตรวจสอบที่น่าเชื่อถือ เลยทำให้มั่นใจในอาหารร้านนี้สินะ?"
1008006-88 = ""
1008006-90 = ""
1008006-91 = "ที่พูดมาก็ไม่ใช่ว่าจะผิดงั้นเหรอ? หืม...?"
1008006-92 = "[s7] \"ที่คิโวทอสก็มีนักกินตัวยงเยอะเลยละ\"\n[s8] \"ถ้าร้านนี้ไม่อร่อยจริง ป่านนี้คงมีใครมาระเบิดทิ้งไปแล้ว\""
1008006-95 = "พูดอะไรไม่เห็นจะเข้าใจเลย..."
1008006-96 = "งั้นก็ดี เราชักจะคุยกันนานไปแล้ว ไหนลองชิมดูหน่อยซิ..."
1008006-97 = ""
1008006-99 = ""
1008006-100 = ""
1008006-101 = ""
1008006-102 = ""
1008006-104 = "...โอ้?"
