[translation]
1010805-1 = "อาฟเตอร์ ดาร์ก"
1010805-2 = "(คุณครูมุ่งหน้าไปยังโรงเรียนมิลเลเนียมเพื่อให้คำปรึกษากับเหล่านักเรียน)"
1010805-3 = "(กว่าจะให้คำปรึกษานักเรียนครบทุกคน ก็เป็นเวลามืดค่ำแล้ว...)"
1010805-5 = "คุณครู ขอบคุณที่วันนี้มาให้คำปรึกษานะคะ!"
1010805-6 = "พอได้ความคิดเห็นจากคุณครู ฉันก็เลยพอจะนึกออกแล้วค่ะว่าจะออกแบบถังขยะที่จะวางไว้ใน#nโรงเรียนยังไงดี"
1010805-7 = "[s1] \"ถ้าความคิดเห็นของครูมีประโยชน์ก็โล่งอกไปทีนะ\"\n[s2] \"ต่อไปก็หลีกเลี่ยงฟังก์ชันระเบิดตัวเองของถังขยะด้วยนะ\""
1010805-10 = "จะว่าไป ขอโทษด้วยนะคะที่ทำให้คุณครูต้องอยู่ถึงดึกดื่นขนาดนี้"
1010805-11 = "คุณครูมาให้คำปรึกษาพวกฉันตั้งแต่กลางวันแล้ว แบบนี้ก็คงยังไม่ได้ทานข้าวเย็นใช่มั้ยคะ... จะทำยังไงดีล่ะ?"
1010805-12 = "[s] \"ไม่เป็นไร ครูกลับไปกินที่ชาเล่ต์ก็ได้\""
1010805-13 = "ค่ะ ถ้างั้นก็เดินทางกลับดีๆ นะคะ!"
1010805-17 = "[ns3] (หิวจนไส้กิ่วแล้ว ไปซื้ออะไรกินดีกว่า...)\n[ns4] (คงรอให้ถึงชาเล่ต์ไม่ไหว ไปร้านสะดวกซื้อดีกว่า)"
1010805-21 = "ยินดีต้อนรับค่ะ เอ็นเจล 24 สาขาวิทยาเขตมิลเลเนียมค่ะ"
1010805-22 = "รับเป็นสลัดไก่และขนมปังปิ้งนะคะ ทานตอนนี้เลยมั้ยคะ? เดี๋ยวฉันอุ่นขนมปังให้ค่ะ"
1010805-23 = "[s] \"อื้อ ฝากอุ่นให้ร้อนๆ เลยนะ\""
1010805-24 = "ขอบคุณค่ะ แล้วแวะมาใหม่นะคะ!"
1010805-26 = "(หลังจากกินสลัดและขนมปังแก้หิว และกำลังจะเดินออกจากร้านสะดวกซื้อ)"
1010805-27 = "[ns5] (เอ๊ะ นักเรียนคนนั้น...)\n[ns6] \"ยูกะ...?\""
1010805-31 = "― [log=유우카 파자마]อั้ม ง่ำง่ำ... อาหย่อย...[/log][wa:3990] "
1010805-34 = "― [log=유우카 파자마]วะ... ว้าย?! [/log][wa:260] "
1010805-38 = "― [log=유우카 파자마]คะ... คุณครู?[/log][wa:1230] "
1010805-40 = "― [log=유우카 파자마]มาทำอะไรที่นี่เวลานี้...[/log][wa:420] "
1010805-43 = "― [log=유우카 파자마]คะ... คือว่า อันนี้... คือ... [/log][wa:1940] "
1010805-45 = "― [log=유우카 파자마]ฉันนอนไม่หลับ ก็เลยลงมาเดินเล่น [/log][wa:1210] "
1010805-48 = "― [log=유우카 파자마]แล้วก็เห็นไก่ทอดเอ็นเจล [/log][wa:1530] "
1010805-50 = "― [log=유우카 파자마]ในใบปลิวของร้านสะดวกซื้อ...[/log]"
1010805-53 = "― [log=유우카 파자마]แต่ก็ช่วยไม่ได้นี่คะ![/log][wa:910] "
1010805-55 = "― [log=유우카 파자마]ก็ไก่ทอดเอ็นเจลที่ทอดใหม่ๆ ในเวลานี้[/log][wa:710] "
1010805-58 = "― [log=유우카 파자마]มันทั้งร้อนและก็ชุ่มฉ่ำที่สุดเลยนี่คะ![/log][wa:1520] "
1010805-60 = "― [log=유우카 파자마]ถ้าไม่ซื้อก็เสียดายแย่ค่ะ[/log][wa:170] "
1010805-63 = "― [log=유우카 파자마]แต่ว่า... ฉันไม่ได้ออกมา [/log][wa:3020] "
1010805-65 = "― [log=유우카 파자마]กินมื้อดึกแบบนี้ทุกคืนหรอกนะคะ...[/log][wa:790] "
1010805-68 = "― [log=유우카 파자마]ถ้าไม่ติดอะไรละก็[/log][wa:2550] "
1010805-70 = "― [log=유우카 파자마]คุณครูก็ลองชิมสักคำมั้ยคะ?[/log][wa:1080] "
1010805-73 = ""
1010805-74 = "[ns7] \"ขอบใจนะ แต่ครูขอปฏิเสธดีกว่า กินเยอะๆ ล่ะ\"\n[ns8] \"เวลานี้ยังกินไก่ทอดได้อีก กระเพาะเด็กม.ปลายนี่สุดยอดไปเลยนะ...\""
1010805-77 = "ยะ... อย่าทำหน้าตกใจอย่างนั้นสิคะ!"
1010805-78 = "ฮือ... ถ้ารู้ว่าจะบังเอิญเจอคุณครูที่นี่ ฉันคงเลือกกินของว่างเบาๆ แทน..."
1010805-79 = "อย่างเยลลี่บุก หรือไม่ก็ขนมเต้าหู้..."
1010805-80 = "[s] \"ช่วงนี้ก็ยังนอนไม่หลับอยู่เหรอ?\""
1010805-81 = "อ่า... คือว่าเรื่องนั้น..."
1010805-82 = "ถ้าให้พูดตามตรงก็คงอย่างนั้นน่ะค่ะ..."
1010805-83 = "หมู่นี้ฉันไม่ได้บังคับให้ตัวเองต้องนอนให้หลับอย่างที่คุณครูแนะนำอยู่"
1010805-84 = "แต่พอนอนลงบนเตียงเท่านั้นละ ความคิดมากมายก็เข้ามาในหัวของฉันค่ะ"
1010805-85 = "ฉันอ่อนไหวกับทั้งเสียงพัดลมของคอมพิวเตอร์เซิร์ฟเวอร์ที่ดังทั้งวันทั้งคืน แสงไฟนีออนที่ลอดเข้ามา#nทางผ้าม่าน ไหนจะเสียงรถบรรทุกที่บรรทุกสินค้ามาเต็มคันอีก..."
1010805-86 = "แล้วก็ยังคิดด้วยว่าในค่ำคืนที่เงียบสงบแบบนี้ น่าจะมีคนอื่นที่ยังทำงานเพื่อวันพรุ่งนี้อยู่ แล้วฉันจะหลับได้เหรอ"
1010805-87 = "แน่นอนว่าการที่ใครบางคนทำงานอยู่จนดึกดื่นจะทำให้ฉันได้พักผ่อนบ้าง แต่จิตใจที่เหนื่อยล้า#nกลับทำให้ร่างกายนอนไม่หลับค่ะ"
1010805-88 = "ฉันก็เลยออกมาเดินเล่นเพื่อจะทำให้ร่างกายเหนื่อยลงบ้าง... แต่สุดท้ายก็มากินไก่ทอดอมน้ำมันของ#nร้านสะดวกซื้อซะงั้น ใช้ไม่ได้เลยว่ามั้ยคะ?"
1010805-89 = "[s] \"อืม แต่ครูคิดว่านั่นเป็นทางเลือกที่ดีนะ\""
1010805-90 = ""
1010805-93 = "[ns9] \"การเดินเล่นเบาๆ ก็เป็นประโยชน์ต่อการนอนนะ\"\n[ns10] \"ถ้าหิวมากก็คงนอนไม่หลับ ลงมากินอะไรให้อิ่มก็ไม่เลวหรอก\""
1010805-96 = "จริงเหรอคะ...?"
1010805-97 = "แต่คุณครูก็พูดแต่เรื่องดีๆ กับนักเรียนเสมอเลย แบบนี้มันก็ยากที่จะเชื่อนะคะ"
1010805-98 = "[s11] \"แต่ไก่ทอดมันย่อยนาน งั้นไปเดินเล่นต่ออีกหน่อยมั้ย?\"\n[s12] \"ไปเดินย่อยต่ออีกหน่อยมั้ยล่ะ จะได้กลับไปนอนสบายๆ\""
1010805-101 = "ฮุฮุ ดีค่ะ"
1010805-102 = "งั้นฉันจะแนะนำทางเดินลับที่ฉันไปเดินเล่นบ่อยๆ ให้เองค่ะ"
1010805-103 = "ตอนนี้ก็มืดแล้วด้วย เดินตามฉันมาให้ดีนะคะ"
1010805-105 = "(จากนั้นคุณครูก็เดินเล่นไปในเส้นทางที่ไร้ผู้คนในมิลเลเนียมกับยูกะ)"
