[translation]
1010906-1 = "#title;그 위의 작은 얼룩"
1010906-2 = "#place;샬레 집무실"
1010906-4 = "#na;(다음 날, 노아와 함께 샬레의 업무를 처리하던 중……)"
1010906-5 = "#st;[0,0];instant;1;"
1010906-8 = "[ns] \"점심 식사 직후라 그런지 뭔가 나른하네……\""
1010906-10 = "[ns] \"노아, 혹시 커피 내리면 같이 마실래?\""
1010906-11 = "3;노아;01;아, 안 그래도 저도 커피 한 잔이 그리운 참이었어요.\n#3;a"
1010906-12 = "3;노아;03;그럼. 한 잔 부탁드리겠습니다.\n#3;em;[하트]"
1010906-14 = "3;노아;01"
1010906-17 = "[ns1] \"자, 여기 블랙커피.\"\n[ns2] \"가득 담았으니 마실 때 조심히—\""
1010906-20 = "3;노아;01\n#3;d\n#wait;2000"
1010906-21 = "3;노아;01\n#3;a\n#3;closeup\n#wait;1000"
1010906-22 = "3;노아;04\n#3;closeup\n#3;shake\n#bgshake\n#wait;500"
1010906-23 = "[ns] \"앗, 뜨거워!\""
1010906-24 = "3;노아;04;괘, 괜찮으신가요. 선생님?\n#3;closeup\n#3;em;[땀]"
1010906-25 = "[s] \"괜찮아. 노아는 다치지 않았어?\""
1010906-26 = "3;노아;03;네, 저도 괜찮아요.\n#3;closeup\n#3;em;[재잘]"
1010906-27 = "3;노아;02;컵이 흔들리면서 커피가 조금 넘쳐흐른 모양이네요. 차가운 물로 손을 식혀 주세요.\n#3;closeup"
1010906-28 = "3;노아;01;바닥에 흐른 커피는 닦으면 되고…… 치마에 커피 자국이 조금 생기긴 하지만, 신경 쓰일 정도는 아니네요.\n#3;closeup"
1010906-29 = "[s3] \"미안, 흰 치마라서 신경 쓰일 텐데.\"\n[s4] \"신경 쓰이면 다른 옷으로 갈아입고 와도 괜찮아.\""
1010906-32 = "#st;[0,0];instant;1;"
1010906-34 = "3;노아;01\n#3;closeup\n#3;d\n#wait;1000"
1010906-35 = "3;노아;01\n#3;a\n#wait;1000"
1010906-36 = "3;노아;01;아뇨, 괜찮아요. 어차피 오늘 돌아가면 바로 세탁할 예정이었고—"
1010906-37 = "#st;[0,0];instant;1;"
1010906-39 = "3;노아;02\n#3;em;…\n#wait;2500"
1010906-40 = "3;노아;01\n#3;em;[전구]\n#wait;1000"
1010906-41 = "3;노아;05;—아니, 역시 이 상태로는 업무를 하는 동안 계속 신경이 쓰일 것 같긴 하네요."
1010906-42 = "3;노아;03;그럼 잠시 실례하겠습니다, 선생님. 바로 '편한 옷'으로 갈아입고 올게요.\n#3;greeting"
1010906-43 = "#st;[0,0];instant;1;"
1010906-45 = "3;노아;03\n#3;d\n#wait;2000"
1010906-47 = "#na;(잠시 후……)"
1010906-49 = "3;노아 파자마;01\n#3;a\n#wait;1000"
1010906-50 = "3;노아 파자마;01;다녀왔습니다~\n#3;em;[음표]"
1010906-51 = "[s] \"노아, 그 차림은……?\""
1010906-52 = "3;노아 파자마;02;네? 말씀드린 대로의 '편한 옷'인걸요.\n#3;em;[?]"
1010906-53 = "3;노아 파자마;03;지난번에 여벌 잠옷을 샬레에 두고 가길 잘했네요."
1010906-54 = "3;노아 파자마;01;오늘은 남은 당번 시간 동안 이 옷을 입고 업무를 진행하겠습니다.\n#3;em;[재잘]"
1010906-55 = "[s] \"하지만 다른 학생이 보고 오해를 하면 어쩌지……?\""
1010906-56 = "3;노아 파자마;08;그야, 커피가 묻어서 다른 옷으로 갈아입었다고 하면 다들 납득해 주지 않을까요?\n#3;em;[?]"
1010906-57 = "#st;[0,0];instant;1;"
1010906-59 = "3;노아 파자마;08\n#3;d\n#wait;1000"
1010906-60 = "3;노아 파자마;01\n#3;a\n#3;closeup\n#wait;1000"
1010906-61 = "3;노아 파자마;03;그도 아니라면, 뭔가 걱정되는 다른 문제라도 있으신가요?\n#3;closeup\n#3;em;[하트]"
1010906-62 = "[s5] \"그건 아니지만……\"\n[s6] \"잠옷도 흰색이니, 일하는 데 불편할까 봐.\""
1010906-65 = "#st;[0,0];instant;1;"
1010906-67 = "3;노아 파자마;03\n#3;closeup\n#3;d\n#wait;1000"
1010906-68 = "3;노아 파자마;03;괜찮아요. 어차피 흰 옷을 입고 일상을 보내는 데에는 익숙하거든요.\n#3;a\n#3;em;[음표]"
1010906-69 = "3;노아 파자마;01;다들 흰 옷만 입으면 관리하기 불편하지 않냐고 자주 물어보지만, 흰 옷만의 장점도 많답니다."
1010906-70 = "3;노아 파자마;05;흰 바탕의 옷은 어떤 색과도 조화롭게 어우러지고, 잡스러운 것이 묻었을 때 털어내기도 쉽거든요."
1010906-71 = "3;노아 파자마;99;게다가 빛을 잘 반사하는 성질 덕분에 열을 잘 머금지 않으니, 더위에 약한 제게는 꼭 맞는 색이랍니다."
1010906-72 = "3;노아 파자마;99;거기에 더해 가끔 이렇게 '얼룩'이 묻게 되면…… 오랫동안 그 흔적을 선명하게 곱씹어 볼 수 있으니까요.\n#fontsize;50\n#3;em;…"
1010906-73 = "[ns] \"노아.\""
1010906-74 = "3;노아 파자마;09;네, 네?! 방금 제가 뭔가 이상한 소리를 했나요?\n#3;shake\n#3;em;[?!]"
1010906-75 = "[s7] \"그게 아니라. 흰 옷에 묻은 커피 얼룩은 지우기 어려우니까……\"\n[s8] \"괜찮다면 지금 바로 세탁실에 가서 얼룩을 지우고 와도 돼.\""
1010906-78 = "3;노아 파자마;04;……."
1010906-79 = "3;노아 파자마;07;선생님은 정말……"
1010906-80 = "3;노아 파자마;05;의외의 부분에서 둔감하시네요.\n#3;em;[한숨]"
1010906-81 = "[s] \"응? 어째서 기분이 상한 거야?\""
1010906-82 = "3;노아 파자마;10;……몰라요.\n#3;em;…"
1010906-84 = "#na;(이후, 어째서인지 토라진 노아를 달래주느라 한동안 애를 먹었다……)"
