[translation]
101050-1 = "#title;제5화;일상 속의 균열 3"
101050-4 = "3;사키;11;자, 준비는 모두 끝났어. 모에, 네 차례야.\n#3;em;[!]\n#3;a"
101050-5 = "5;모에;11;정말이지? 진짜 저질러 버려도 되는 거지? 하아, 하아……\n#5;a\n#3;m1"
101050-6 = "3;사키;12;여기까지 와서 도망친다는 선택지를 고를 수는 없잖아."
101050-7 = "3;사키;05;자, 망설이지 말고 해버려!\n#3;em;[반응]\n#3;m2"
101050-8 = "5;모에;16;그럼 사양하지 않고……"
101050-10 = "3;모에;05;죽어라, 이 말벌 녀석들—!\n#3;closeup\n#fontsize;100"
101050-11 = "#st;[0,0];instant;1;"
101050-15 = "3;상점 주인 시바;01;우와…… 그 거대하던 말벌집이 순식간에 불타 없어졌네……\n#3;em;[반응]\n#3;a"
101050-16 = "3;상점 주인 시바;01;도와줘서 정말 고마워. 창고 뒤꼍에서 거대한 말벌집을 발견했을 때는 어찌해야 하나 정말 난감했거든.\n#3;greeting"
101050-17 = "1;미야코;03;아닙니다. 시민을 위협하는 중대한 위험 요소를 제거하는 것은 SRT의 의무니까요.\n#1;a"
101050-18 = "5;사키;03;맞아. 민간인이 함부로 말벌집을 건드린다면 크게 다칠 수도 있거든.\n#5;a"
101050-19 = "5;사키;02;일부 말벌은 치명적인 신경독을 갖고 있다고 하니, 만반의 준비를 갖추고 일시에 태워버리는 게 상책이지.\n#5;m3\n#3;dl\n#1;dl\n#5;em;[반응]"
101050-21 = "3;모에;14;뭐야. 벌써 끝난 거야?\n#3;em;[?]"
101050-22 = "3;모에;15;나는 거대한 말벌집이 있다고 해서 1시간 정도는 태울 수 있지 않을까 기대했는데. 생각보다 싱겁네."
101050-23 = "5;미유;04;1시간 넘게 태워야 하는 크기의 벌집이라니…… 상상도 하고 싶지 않아……\n#5;a\n#3;m1\n#5;em;[땀]"
101050-25 = "3;상점 주인 시바;01;예전에는 이런 일이 생기면 방제업자를 부르거나, 소방서에 신고해서 해결했을 텐데……\n#3;closeup\n#3;em;[한숨]"
101050-26 = "3;상점 주인 시바;01;코우사기 타운의 재개발이 확정된 이후로는 관공서도, 인프라도 모두 빠져나가서. 어지간한 문제는 주민들이 알아서 해결하는 수밖에 없었거든."
101050-27 = "3;상점 주인 시바;01;이런 일이 반복되다 보니…… 우리도 슬슬 이사를 가야할 지 고민하던 중이었어."
101050-28 = "#st;[0,0];instant;1;"
101050-30 = "3;미야코;99\n#3;h\n#3;em;…\n#wait;2500"
101050-31 = "3;미야코;02;……언제까지 이곳에 있을지는 모르겠지만, 어려운 일이 생긴다면 공원에 찾아와 주세요.\n#3;em;[반응]"
101050-32 = "3;미야코;03;SRT의 대원으로서, 시민들의 안전을 위해 언제든 협력하겠습니다.\n#3;greeting"
101050-33 = "1;상점 주인 시바;01;그렇게 말하니 의지가 되네, 후훗.\n#1;a\n#3;m5"
101050-34 = "1;상점 주인 시바;01;참, 내 정신 좀 봐. 도움을 받아 놓고 답례를 하는 걸 깜박하고 있었네.\n#1;em;[반응]"
101050-35 = "#st;[0,0];instant;1;"
101050-37 = "3;미야코;02\n1;상점 주인 시바;01\n#1;dl\n#3;h\n#wait;1000"
101050-38 = "#1;hide\n3;미야코;04;아뇨. 저희는 마땅히 해야 할 일을 했을 뿐이니 답례 같은 건—\n#3;m4"
101050-39 = "#st;[0,0];instant;1;"
101050-41 = "3;미야코;04\n2;상점 주인 시바;01\n#2;ar\n#3;h\n#wait;1000"
101050-42 = "2;상점 주인 시바;01;자, 우리 가게에서 팔고 있는 냉장 닭꼬치 팩이야.\n#2;greeting"
101050-44 = "3;상점 주인 시바;01;지금은 파리만 날리고 있지만, 옛날에는 이 닭꼬치 팩을 사려고 다른 구에서 찾아올 정도로 인기였다구?\n#3;em;[반짝]\n#3;closeup"
101050-45 = "#st;[0,0];instant;1;"
101050-47 = "1;사키;02\n5;미유;02\n3;미야코;08\n#3;em;…\n#3;h\n#1;h\n#5;h\n#wait;2500"
101050-48 = "3;미야코;08;냉장된 닭꼬치 팩…… 그것도 신선한 파가 꿰어진 고급품……"
101050-49 = "1;사키;02;유통기한도 지나지 않았고, 상태도 좋은 음식을……"
101050-50 = "5;미유;02;저희에게…… 그냥 주신다고요……?\n#5;em;[?]\n#5;stiff"
101050-51 = "#1;hide\n#5;hide\n3;상점 주인 시바;01;으응…… 무슨 문제라도 있니?\n#3;em;[땀]"
101050-52 = "3;상점 주인 시바;01;혹시라도 닭꼬치가 싫다면—"
101050-53 = "#all;hide\n#na;일동;감사히 받겠습니다!\n#fontsize;100"
101050-55 = "#place;코우사기 공원"
101050-57 = "3;미유;03;맛있어……!\n#3;a\n#3;em;[반짝]"
101050-58 = "1;사키;03;그러게. 이번 건 정말 잘 구워졌는데? 고기에 불맛이 가득해.\n#1;a\n#1;em;[음표]\n#3;m5"
101050-59 = "#3;hide\n5;모에;13;후후, 불을 쓰는 건 내가 또 전문이니까!"
101050-60 = "5;모에;05;으음. 화력이 조금 부족한 것 같은데…… 좀 더 장작을 넣어볼까?\n#5;em;[반응]"
101050-61 = "#st;[0,0];instant;1;"
101050-63 = "1;사키;03\n5;모에;05\n#1;d\n#5;d\n#wait;1000"
101050-65 = "3;미야코;07;신선한 파의 향기와 닭고기의 기름진 맛이 정말 잘 어울리네요.\n#3;a\n#3;em;[반짝]"
101050-66 = "5;모에;07;응. 특히나 바삭하게 튀겨진 이 닭껍질의 기름진 맛이 최고야!\n#5;al"
101050-67 = "1;사키;03;아, 정말 이렇게 신선한 음식을 먹는 게 얼마 만인지……\n#1;ar"
101050-68 = "5;미유;04;최근에는 계속 통조림 안에 든 염장 고기만 먹었으니까……\n#5;em;[세로선]"
101050-69 = "#1;hide\n#5;hide\n3;모에;11;어차피 냉장고도 없으니, 받은 고기는 남기지 말고 모조리 구워버리자고!\n#3;closeup"
101050-73 = "3;미야코;99;뭔가…… 평화로운 느낌이네요.\n#3;a"
101050-74 = "5;사키;01;진짜. 이 모닥불 주변의 풍경만 보고 있으면 캠핑을 나온 것 같아.\n#5;em;…\n#5;a"
101050-75 = "1;미유;03;후후…… 그렇게 생각하니 어쩐지 즐거워.\n#1;a"
101050-76 = "3;미야코;02;최근에는 발키리도, 총학생회도 조용하고……"
101050-77 = "3;미야코;01;샬레의 선생님께서도 최근엔 바쁘신 지 연락이 없으셨으니까요."
101050-78 = "1;모에;15;연락해도 안 받을 거지만!\n#1;em;[반응]"
101050-79 = "5;사키;05;맞아! 그런 이상한 어른의 연락 따윈 필요 없다고!\n#5;jump"
101050-80 = "1;미유;04;그, 그래도 가끔은 찾아와 주셨으면 좋겠는데……\n#1;em;…"
101050-81 = "#st;[0,0];instant;1;"
101050-83 = "5;사키;04\n1;미유;04\n3;미야코;99\n#3;h\n#1;h\n#5;h\n#wait;1500"
101050-84 = "3;미야코;03;뭐, 그래도 아무 일 없다는 건 좋은 일이겠지요. 키보토스의 학생들에게는.\n#3;em;[반짝]"
101050-85 = "5;사키;06;그건 그렇지만, 역시 우리에게는……"
101050-86 = "1;미유;06;응……"
101050-87 = "#st;[0,0];instant;1;"
101050-89 = "5;사키;06\n1;미유;06\n3;미야코;03\n#1;d\n#3;d\n#5;d\n#wait;1500"
101050-90 = "3;모에;13\n#3;a\n#3;em;…\n#wait;2500"
101050-91 = "3;모에;12;아, 그러고 보니 전에 받은 사이다. 지금 가져와서 마실까?\n#3;em;[반응]"
101050-92 = "3;모에;02;냉장고 대용으로 분수대에 담가 놓았으니까 지금이면 엄청 시원할 거야!"
101050-93 = "5;사키;02;전에 <엔젤 24>에 온 불량 학생들을 쫓아주었을 때 소라가 준 사이다 말이야?\n#5;a\n#3;m1"
101050-94 = "5;사키;01;그거, 오랜만에 구한 탄산음료라고 중요한 날 먹겠다며 아껴 두고 있었던 거 아니었어?\n#5;em;[?]"
101050-95 = "3;모에;13;이렇게 귀한 닭꼬치를 먹을 수 있는 날이 바로 중요한 날 아니겠어?"
101050-96 = "3;모에;09;이렇게 된 참에 전에 따온 버섯도 같이 구워 버리자고!\n#3;em;[!]"
101050-97 = "5;사키;07;좋았어. 그럼 지금 바로 가져올까?\n#5;em;[반짝]"
101050-98 = "#st;[0,0];instant;1;"
101050-100 = "3;모에;02\n5;사키;03\n#3;dr\n#5;dr\n#3;h\n#5;h\n#wait;200"
101050-102 = "2;미유;09;나, 나도 같이 가……!\n#2;hophop\n#2;ar"
101050-103 = "#st;[0,0];instant;1;"
101050-105 = "2;미유;09\n#2;dr\n#wait;1500"
101050-108 = "#place;방위실장 사무실"
101050-109 = "3;카야;01\n#3;a\n#wait;1500"
101050-110 = "3;카야;02\n#3;h\n#wait;2500"
101050-111 = "3;카야;02;방첩망……?"
101050-112 = "3;카야;01;……."
101050-113 = "#st;[0,0];instant;1;"
101050-115 = "3;카야;01\n#3;greeting\n#3;h\n#wait;1500"
101050-116 = "3;카야;00;네. 말씀하세요."
101050-117 = "3;카야;00;……."
101050-118 = "3;카야;00;……그렇군요. 알겠습니다."
101050-119 = "#st;[0,0];instant;1;"
101050-121 = "3;카야;00\n#3;greeting\n#3;h\n#wait;1500"
101050-122 = "3;카야;12;……드디어 시작이군요.\n#3;em;…\n#3;closeup"
101050-125 = "#place;게마트리아의 회의실"
101050-128 = "5;골콩트;01\n1;마에스트로;01\n3;검은 양복;01\n#1;a\n#5;a\n#3;a\n#1;h\n#3;h\n#5;h\n#3;em;…\n#wait;2500"
101050-129 = "1;마에스트로;01;색채가 이곳으로 오고 있다고……?"
101050-131 = "3;베아트리체;01;네. 그걸로 <샬레>도, <이름 없는 신>도, <방주>도 모두 다 사라지게 될 거예요. 어떤가요, 정말 확실한 방법이지 않나요?\n#3;closeup"
101050-132 = "3;마에스트로;01;그리고 이 키보토스도 사라지겠지.\n#3;closeup\n#3;stiff"
101050-133 = "3;골콩트;01;……무슨 짓이죠? 마담? 우리의 탐구를 망칠 셈인가요?\n#3;closeup"
101050-134 = "#all;hide\n#na;베아트리체;네, 상관없어요. 제가 진짜 원하던 것은 그게 아니었다는 걸 알게 되었거든요."
101050-135 = "#na;검은 양복;……."
101050-136 = "3;베아트리체;01\n#3;h"
101050-137 = "3;베아트리체;01;일부이지만, 저는 의식을 통해 <색채>와 접촉했었죠. 그걸로 진정으로 제가 원하는 걸 깨달을 수 있었어요.\n#3;em;[반응]"
101050-138 = "3;베아트리체;01;제가 진정으로 해야만 하는 것…… 그것은 이런 시시한 실험이나 탐구가 아니었어요. 그래요…… 가장 위대한 존재가 되기 위해선……."
101050-139 = "3;베아트리체;01;세계의 멸망과 창생의 권한을 가져야 해요…… 즉, <파괴>하고 <창조>하는 절대자가 되는 것. 그것만이 유일한 방법……."
101050-140 = "3;베아트리체;01;해석되지 않고, 이해되지 않으며, 소통되지 않는 채 그저 도래하기만 하는 불길한 빛. 목적도, 소통도 되지 않는 불가해한 관념. 아아 그래요, 그것만이……."
101050-141 = "3;베아트리체;02;그 [USERNAME] 선생을 없앨 수 있는 방법……!\n#3;closeup\n#fontsize;100"
101050-142 = "3;마에스트로;01;무슨 광인의 작태냐. 이성을 잃었군.\n#3;stiff"
101050-143 = "1;검은 양복;01;……그렇군요. 마담, 당신은 이미 자신의 증오에게 잡아먹혀 버렸군요. 안타까운 일입니다. \n#1;a\n#3;m5"
101050-144 = "1;검은 양복;01;게마트리아는 탐구자이자 구도자. 이해할 수 없는 광기야말로 우리가 타파해야 할 숙적인데…… 베아트리체, 당신은 게마트리아의 자격을 잃었습니다.\n#1;em;…"
101050-146 = "3;베아트리체 실각;01;뭐라고? 감히……. 지금 나에겐 색채의 힘이 흐르고 있다!\n#3;stiff\n#3;closeup"
101050-147 = "3;베아트리체 실각;01;네놈들이 그토록 두려워하던 그 광기의 힘이…….\n#3;closeup"
101050-148 = "3;검은 양복;01;그런 것 같군요. 골콩트, 그녀를 배웅해주시죠.\n#3;closeup"
101050-149 = "3;골콩트;01;네. 그동안 즐거웠습니다. 마담.\n#3;closeup\n#3;greeting"
101050-150 = "#st;[0,0];instant;1;"
101050-154 = "3;베아트리체 실각;01;……?!\n#3;closeup\n#3;em;[?!]\n#3;shake"
101050-157 = "#all;hide\n#na;베아트리체 실각;……크, 크아아아아아아아-?!\n#fontsize;100"
101050-158 = "#na;검은 양복;과연. 헤일로를 파괴하는 폭탄보다 확실한 것 같군요."
101050-159 = "#na;골콩트;네. 신비는 해석이 불가능하기에 신비이지만, 그녀는 알기 쉬운 존재니까요."
101050-160 = "#all;hide\n#na;베아트리체 실각;으아아아아아아아-! \n#fontsize;100\n#bgshake"
101050-161 = "5;골콩트;01\n1;마에스트로;01\n3;검은 양복;01;저희에게 색채에 대항할 방법이 없다고 생각했습니까? 사실은 당신이 색채와 접촉한 것을 알게 된 순간부터 준비하고 있었습니다."
101050-162 = "3;검은 양복;01\n1;마에스트로;01\n5;골콩트;01\n#na;데칼코마니;그렇다!!\n#5;h\n#5;em;[!]\n#fontsize;100"
101050-163 = "1;마에스트로;01;귀하와는 세계관이 달라서 충돌이 많았지만 귀하의 야망에는 경의를 표한다. 베아트리체.\n#1;stiff"
101050-164 = "#na;베아트리체 실각;---------------------------!!\n#fontsize;100"
101050-165 = "#all;hide\n#st;[0,0];instant;1;"
101050-173 = "1;마에스트로;01\n5;골콩트;01\n3;검은 양복;01\n#1;h\n#3;h\n#5;h\n#1;a\n#3;a\n#5;a\n#wait;1500"
101050-174 = "3;검은 양복;01;……."
101050-175 = "5;골콩트;01;안타깝네요. 신이 되겠다고 외치는 엑스트라는 보통 이런 결말을 맞이한다는 걸 몰랐던 걸까요? 그녀가 시학에 대해 조금만 더 이해도가 있었다면……."
101050-176 = "1;마에스트로;01;광기는 확실히 두려운 개념이군. 그녀가 어떤 괴물로 변하게 될지 궁금하긴 했지만……. 이대로 두었다간 더 성가신 일이 벌어졌겠지.\n#1;stiff"
101050-177 = "3;검은 양복;01;다시 한자리가 비었군요. 뭐, 충원은 나중에 논의하는 걸로 하고."
101050-180 = "#na;검은 양복;그럼 다음 논의를 진행하시죠."
101050-181 = "#na;마에스트로;……."
101050-182 = "#na;골콩트;……."
101050-184 = "#nextepisode;다음화;전조"
