[translation]
1010605-1 = "ไอดอลเปล่งประกาย"
1010605-2 = "(คุณครูออกมารอซากุระโกะก่อนเวลานัด)"
1010605-3 = "มาถึงเร็วจังนะคะ คุณครู"
1010605-4 = ""
1010605-7 = "น่าทึ่งจังเลยนะคะ นี่ก็นานแล้วที่คุณครูไม่ได้ชวนฉันมาเจอในสถานที่แบบนี้..."
1010605-8 = "อ้อ ฉันไม่ได้ไม่ชอบหรอกค่ะ ตรงกันข้าม ฉันรู้สึกมีกำลังใจขึ้นมาเพราะคุณครูให้ออกมาเจอกันค่ะ"
1010605-9 = "หืม...? เป็นอะไรเหรอคะ...?"
1010605-10 = "อ้อ สงสัยว่าทำไมฉันถึงใส่ชุดนี้ ทั้งที่ไม่มีงานสินะคะ"
1010605-11 = "ขอโทษด้วยค่ะ ดูเหมือนจะมีเรื่องเข้าใจผิดนะคะ"
1010605-12 = "อันที่จริง วันนี้ฉันก็ไม่เชิงว่าไม่มีงานหรอกค่ะ เรียกว่าพอมีเวลาว่างนิดหน่อยจะดีกว่าค่ะ"
1010605-13 = "คุณครูอุตส่าห์สละเวลามาเจอกันทั้งที แต่ถ้าฉันต้องกลับไปทำงานก่อนก็คงเสียมารยาทใช่มั้ยคะ..."
1010605-14 = "คะ...?"
1010605-15 = "เรื่องแบบนั้นไม่ต้องเป็นห่วงก็ได้งั้นเหรอคะ? หมายความว่ายังไง..."
1010605-16 = "[s1] \"ไปเดินเล่นด้วยกันสักเดี๋ยวมั้ย?\"\n[s2] \"ไปเดินตรงนี้ด้วยกันมั้ย? ไม่นานหรอก\""
1010605-19 = "คะ...? ทำไมจู่ๆ ก็..."
1010605-20 = "ขะ... เข้าใจแล้วค่ะ คุณครูต้องมีเหตุผลในการทำทุกอย่างอยู่แล้วละค่ะ"
1010605-21 = "งั้นก็ไปกันเถอะค่ะคุณครู แต่ฝากคุณครูเป็นไกด์ให้หน่อยนะคะ"
1010605-22 = "[s3] \"ซากุระโกะต้องชอบแน่นอนเลยละ\"\n[s4] เริ่มเดินนำ"
1010605-28 = "เอ่อ... คุณครู?"
1010605-29 = "ฉันไม่ได้สงสัยอะไรหรอกนะคะ แต่ถ้าคุณครูไม่ว่าอะไร..."
1010605-30 = "คุณครูช่วยบอกฉันก่อนได้มั้ยคะว่าเราจะไปที่ไหนกัน..."
1010605-31 = "[s5] \"มาถึงพอดีเลยละ\"\n[s6] \"ก็ที่นี่ไง\""
1010605-34 = "...?"
1010605-35 = "ที่นี่... งั้นเหรอคะ?"
1010605-36 = "นี่มันบนถนนนะคะ... เราไม่ได้จะไปนั่งที่ไหนกันหรอกเหรอคะ?"
1010605-37 = "คะ...? ข้างหลัง?"
1010605-38 = "ให้ฉันดูข้างหลังเหรอคะ? ฝั่งตรงข้าม... เหรอคะ...?"
1010605-39 = "ทำไมถึงพูดอย่างนั้นล่ะคะ..."
1010605-40 = "...?"
1010605-41 = "หืม...?"
1010605-43 = "...!?"
1010605-46 = "― [log=사쿠라코 아이돌]นะ... นี่มัน...?! [/log][wa:790] "
1010605-48 = "― [log=사쿠라코 아이돌]อะ... อะไรกันเหรอคะ...?! [/log][wa:1130] "
1010605-51 = "― [log=사쿠라코 아이돌]โปสเตอร์ของฉัน... เหรอคะ?[/log][wa:1760] "
1010605-53 = "― [log=사쿠라코 아이돌]มะ... ไม่ค่ะ... ถ้าดูก็รู้ค่ะ...! [/log][wa:620] "
1010605-56 = "[ns7] \"ชมรมซิสเตอร์ขอให้ครูช่วยในโปรเจกต์นี้น่ะ\"\n[ns8] \"ทุกคนขอให้ช่วย ครูเลยช่วยเลือกรูปกับสถานที่น่ะ\""
1010605-59 = "― [log=사쿠라코 아이돌]ซิสเตอร์คนอื่นๆ กับคุณครูเหรอคะ...?[/log][wa:1900] "
1010605-61 = "― [log=사쿠라코 아이돌]ฉะ... ฉันต้องพูดว่ายังไงดีคะเนี่ย...[/log][wa:1320] "
1010605-64 = "[ns9] \"ครูทำซากุระโกะตกใจเหรอ?\"\n[ns10] \"ไม่ชอบเหรอ?\""
1010605-67 = "― [log=사쿠라코 아이돌]เอ่อ... ไม่ค่ะ ขอโทษด้วยค่ะ [/log][wa:3160] "
1010605-68 = "― [log=사쿠라코 아이돌]ฉันไม่ได้จะตำหนิอะไรหรอกค่ะ... [/log][wa:1270] "
1010605-71 = "― [log=사쿠라코 아이돌]มันแค่ยากที่จะถ่ายทอดออกมาเป็นคำพูดน่ะค่ะ... [/log][wa:820] "
1010605-74 = "― [log=사쿠라코 아이돌]แต่ว่า นั่นสินะคะ... สิ่งนี้ฉันบอกได้อย่างชัดเจนค่ะ [/log][wa:4000] "
1010605-77 = "― [log=사쿠라코 아이돌]ในส่วนลึกของหัวใจฉัน[/log][wa:1900] "
1010605-79 = "― [log=사쿠라코 아이돌]รู้สึกดีใจมากๆ เลยละค่ะ[/log][wa:640] "
1010605-82 = "เป็นเรื่องที่คาดไม่ถึงเลยจริงๆ นะคะ เรื่องแบบนี้น่ะ..."
1010605-83 = "ฉันคิดเสมอว่าคนอื่นจะไม่กล้าเข้าหาหรือทำอะไรให้ฉันน่ะค่ะ"
1010605-84 = "แต่เมื่อลองคิดดูแล้ว ช่วงนี้ก็เกิดเรื่องคล้ายๆ กันอยู่บ้างค่ะ"
1010605-85 = "บางทีฉันอาจจะมีความคิดที่น่าอึดอัดแบบนั้นอยู่ฝ่ายเดียวก็ได้ค่ะ"
1010605-86 = "[s11] \"นี่เป็นผลของความพยายามของซากุระโกะนะ\"\n[s12] \"ทุกคนรู้ดีว่าซากุระโกะเป็นคนดีนะ\""
1010605-89 = "งั้นเหรอคะ... ถ้าอย่างนั้นก็ค่อยยังชั่วค่ะ"
1010605-90 = "ที่ผ่านมา... ฉันคิดว่าทุกคนมองว่าฉันเป็นคนแปลกเสียอีกค่ะ ฮุฮุ..."
1010605-91 = "[s13] (แต่มันก็จริงอยู่บ้างนะ...)\n[s14] \"นั่นมันคนละเรื่องกับเรื่องนี้น่ะ...\""
1010605-94 = "แน่นอนว่าส่วนใหญ่เป็นประสบการณ์ที่ช่วยให้ฉันได้รู้ในสิ่งที่ฉันไม่รู้ มากกว่าเป็นประสบการณ์ที่ทำให้#nเกิดอะไรใหม่ๆ ค่ะ"
1010605-95 = "แต่ถึงยังไง ทุกอย่างก็... น่าจะเป็นเพราะชุดและอีเวนต์ไอดอลครั้งนี้ก็ได้นะคะ"
1010605-96 = "ดีแล้วที่ฉันเข้าร่วมอีเวนต์ค่ะ..."
1010605-97 = "ค่ะ..."
1010605-98 = "ฉันคิดว่าตัวเองทำได้ดีมากที่รวบรวมความกล้าไปเขียนใบสมัครในวันนั้นค่ะ"
1010605-99 = ""
1010605-101 = ""
1010605-102 = "เพราะงั้น... วันนี้ฉันเลยรู้สึกว่าอยากกล้าหาญขึ้นมาอีกหน่อยค่ะ"
1010605-103 = "คุณครูคะ..."
1010605-104 = "อย่างที่ฉันบอกไปว่าวันนี้ฉันพอมีเวลาว่างอยู่บ้าง"
1010605-105 = "อย่างน้อยก็ขอให้ฉันได้ใช้เวลาที่เหลือนี้..."
1010605-106 = ""
1010605-108 = ""
1010605-109 = "ดูรูปที่คุณครูช่วยเลือกให้กับคุณครูที่นี่ต่อได้มั้ยคะ?"
1010605-111 = "(หลังจากนั้นคุณครูก็ดูรูปกับซากุระโกะและได้ใช้เวลาที่เหลือด้วยกัน)"
