[translation]
101110-1 = "Episode 11; Escape 1"
101110-2 = "What? Wait, wait."
101110-3 = "O-Of course we trust you, Sensei...but we can't fight PMC under these conditions."
101110-4 = "We have injured people, and..."
101110-5 = ""
101110-9 = ""
101110-10 = "Here! We found them!"
101110-11 = "Eek! They're here!"
101110-12 = "We don't have a choice! We're fighting!"
