[translation]
1012106-1 = "ทะเลในฤดูร้อนกับยูคาริในยามราตรี"
1012106-2 = "(คุณครูกำลังกลับจากร้านสะดวกซื้อ ระหว่างนั้นก็ได้เจอนักเรียนที่ดูคุ้นๆ)"
1012106-3 = ""
1012106-6 = "อ๊ะ ท่านอาจารย์?"
1012106-7 = "ท่านอาจารย์มาทำอะไรที่นี่... อ้อ ไปซื้อของกลับมาสินะเจ้าคะ"
1012106-8 = "ไม่เจ้าค่ะ ไม่ได้เป็นการรบกวนข้าเลยเจ้าค่ะ ข้ากลับดีใจด้วยซ้ำ"
1012106-9 = "ข้า... ข้าแค่กำลังมองทะเลอยู่น่ะเจ้าค่ะ"
1012106-10 = "ตอนกลางวันที่นี่จะมีบรรยากาศวุ่นวายแต่ก็น่ารื่นรมย์ แต่พอตกกลางคืนที่นี่กลับเงียบสงบอย่าง#nเหลือเชื่อ..."
1012106-11 = "การที่ข้าเห็นทิวทัศน์แบบนี้แล้วรู้สึกเศร้า คงหมายความว่าข้าเปลี่ยนไปแล้วน่ะเจ้าค่ะ"
1012106-12 = ""
1012106-15 = "ก่อนได้รู้จักท่านอาจารย์ <ทะเลแบบนี้> คือทะเลปกติของข้าเจ้าค่ะ"
1012106-16 = "......"
1012106-17 = ""
1012106-19 = ""
1012106-20 = "ฮืมม~ ฮืม~♪"
1012106-21 = "ยูคาริแห่งท้องทะเลคือเรือรบไร้พ่าย~♪ อยู่ในน้ำก็ไร้อุปสรรคกล้ำกราย~♪"
1012106-22 = "[ns1] (จู่ๆ ก็ร้องเพลงเหรอ...?!)\n[ns2] (ฟังอยู่เงียบๆ ดีกว่าเนอะ...)  "
1012106-25 = "แม้ลอยอยู่บนน้ำ ก็จงสง่างามดุจดอกบัวที่ไม่เปียกน้ำ... หากเสื้อผ้ากับเรือนผมเปียกน้ำ ศักดิ์ศรีของครอบครัวก็จะเสียหาย..."
1012106-26 = "นี่คือคำที่ข้าได้ฟังบ่อยๆ มาตั้งแต่เด็กๆ แล้วเจ้าค่ะ"
1012106-27 = "แต่ว่าวันนี้น่ะ ฮุฮุ! อย่าว่าแต่เสื้อผ้าเลยเจ้าค่ะ ข้ากระโดดจ๋อมลงทะเลจนเปียกโชกไปทั้งตัวเลย!"
1012106-28 = "ถ้าคนในตระกูลมาเห็นเข้า คงตกใจจนเป็นลมไปตรงนั้นแน่นอนเจ้าค่ะ"
1012106-29 = "[ns3] \"วันนี้สนุกมั้ย?\"\n[ns4] \"ยูคาริเสียดายเหรอ?\""
1012106-30 = "เจ้าค่ะ! ข้าสนุกสุดเหวี่ยงเลยเจ้าค่ะ!"
1012106-31 = "ท่านอาจารย์เปลี่ยนให้โลกของข้าเป็นโลกที่สดใสเสมอเลยเจ้าค่ะ"
1012106-32 = "ถ้าพูดว่า \"ยูคาริผู้นี้ไม่เสียดายกับการเลือกใดๆ เลย!\" ก็คงเป็นการโกหก..."
1012106-33 = "แต่ข้าก็สนุกมากๆ จริงๆ เจ้าค่ะ แล้วท่านอาจารย์ก็จะบอกว่านั่นคือสิ่งที่สำคัญที่สุดใช่มั้ยเจ้าคะ? ฮุฮุ"
1012106-34 = "อีกอย่าง... นี่คือความลับของข้าที่แม้แต่คนในตระกูลก็ยังไม่รู้ แต่ข้าจะแอบบอกท่านอาจารย์เจ้าค่ะ"
1012106-35 = ""
1012106-37 = ""
1012106-38 = ""
1012106-39 = "ที่บอกว่าข้าไม่เคยทำให้เสื้อผ้าเปียกเลยเมื่อมาทะเล มันเป็นเรื่องโกหกเจ้าค่ะ"
1012106-40 = "ทุกครั้งที่มาทะเล ข้าจะมายืนมองน้ำใสๆ แล้วก็แอบเอาเท้าลงไปจุ่มน้ำทะเลด้วย"
1012106-41 = "นั่นคือวิธีการเล่นสนุกในทะเลของข้าเจ้าค่ะ"
1012106-43 = "(แล้วคุณครูกับยูคาริก็นั่งชมทะเลยามค่ำคืนด้วยกันอยู่นาน)"
1012106-44 = ""
1012106-48 = "อ๊ายย!"
1012106-49 = "[ns] \"มีเรื่องอะไรเหรอ ยูคาริ?!\""
1012106-50 = "ข้าอารมณ์ดีจนรั้งท่านอาจารย์ไว้นานเกินไปแล้วเจ้าค่ะ!"
1012106-51 = "ท่านอาจารย์ออกมาข้างนอกเพราะธุระเรื่องอื่นนี่เจ้าคะ?!"
1012106-52 = "(ไอศกรีมที่คุณครูซื้อมาจากร้านสะดวกซื้อกำลังละลายจนสังเกตได้...)"
1012106-53 = "รีบกลับเถอะเจ้าค่ะ ท่านอาจารย์! ไม่ต้องห่วงยูคาริผู้นี้นะเจ้าคะ!"
1012106-54 = "[s5] \"ไม่เป็นไรหรอก ยังไงก็ละลายหมดแล้ว...\"\n[s6] \"ตอนนี้ HP ของโมริโมริคุงเหลือศูนย์แล้วละ\""
1012106-57 = "อ๊ะ... เป็นเพราะได้มาเจอข้าแท้ๆ เชียว..."
1012106-58 = "[s7] \"ในเมื่อเป็นแบบนี้ก็ช่วยไม่ได้ละนะ ไปเดินเล่นกันเถอะ...\"\n[s8] \"ครูว่าจะไปสำรวจทะเลยามค่ำคืน ไปด้วยกันมั้ยล่ะ?\""
1012106-61 = "...!"
1012106-62 = ""
1012106-64 = ""
1012106-65 = ""
1012106-66 = "เจ้าค่ะ! ข้าจะติดตามไปด้วยทุกที่เลยเจ้าค่ะ!"
1012106-68 = "(หลังจากนั้นคุณครูกับยูคาริก็แวะไปตลาดโต้รุ่งริมทะเลแล้วได้กินของอร่อยด้วยกัน)"
