[translation]
1012806-1 = "#title;후유의 공간"
1012806-2 = "#na;(일단 후유가 오라는 곳으로 오긴 했는데…….)"
1012806-3 = "#st;[0,0];instant;1;"
1012806-5 = "1;미술 관람객 A;01\n4;미술 관람객 B;01\n2;미술 관람객 C;01\n5;미술 관람객 D;01\n#1;a\n#2;a\n#4;a\n#5;a\n#1;h\n#2;h\n#4;h\n#5;h\n#wait;1000"
1012806-6 = "1;미술 관람객 A;01\n4;미술 관람객 B;01\n2;미술 관람객 C;01\n5;미술 관람객 D;01\n#na;미술 관람객 A;와일드헌트 출신 학생의 전시회라면 볼 가치가 있지.\n#1;h\n#1;em;[반응]"
1012806-7 = "1;미술 관람객 A;01\n4;미술 관람객 B;01\n2;미술 관람객 C;01\n5;미술 관람객 D;01\n#na;미술 관람객 B;기대되는걸요, 후후.\n#4;h\n#4;jump"
1012806-9 = "#na;(방문객들이 생각보다 꽤 많았다.)"
1012806-10 = "#na;(그러다가 전시회의 포스터를 봤는데…….)"
1012806-11 = "[ns] \"와카사 후유 작가 미디어아트 개인전……?\""
1012806-12 = "#na;후유;넵, 그렇습니다!"
1012806-13 = "3;후유;00\n#3;a"
1012806-14 = "3;후유;09;이곳이 바로 저의 개인전 전시회장!\n#3;em;[!]"
1012806-15 = "3;후유;00;저의 세계로 선생님을 초대합니다!"
1012806-16 = "[s] \"……방금 엄청 예술가 같았어요, 실장님!\""
1012806-17 = "3;후유;34;헤헤, 그래요?\n#3;em;[재잘]"
1012806-18 = "3;후유;23;……가 아니라! 저도 와일드헌트 예술학원의 학생이거든요, 선생님!"
1012806-19 = "3;후유;07;오늘만큼은 특수교역부의 영업실장이 아니라……."
1012806-20 = "3;후유;00;한 명의 예술가로 봐 달라고요, 선생님?\n#3;em;[음표]"
1012806-21 = "[s1] \"음 그러면 오늘은 뭐라고 불러야 하지?\"\n[s2] \"화백님? 작가님?\""
1012806-24 = "3;후유;34;음 뭐, 그냥……"
1012806-25 = "3;후유;33;……후유 쨩, 정도?\n#3;em;[///]\n#fontsize;50"
1012806-26 = "3;후유;25;자 뭐 어쨌든! 일단 같이 안으로 들어가 보실까요?\n#3;jump"
1012806-27 = "3;후유;24;무려 작가 본인에게 전시회 에스코트를 받을 수 있는 절호의 기회라고요?"
1012806-29 = "#na;(전시관 안은 굉장히 어두웠다.)"
1012806-30 = "#na;(그리고 곳곳에 미디어아트를 영사하는 스크린들만이 빛을 내고 있었다.)"
1012806-31 = "3;후유;00;일단 이 작품부터 보실까요.\n#3;em;[반응]\n#3;a"
1012806-32 = "3;후유;01;만약 이 전시회 자체를 한 편의 시집에 비유한다면……."
1012806-33 = "3;후유;08;이 작품은 일종의 서시라고 할 수 있습니다."
1012806-34 = "[s] \"이후 볼 작품들의 인상을 집약한 작품…… 그런 건가?\""
1012806-35 = "3;후유;14;정확합니다!\n#3;em;[!]"
1012806-36 = "3;후유;08;그래서 이 안의 작품들을 어떤 순서로 관람하건……"
1012806-37 = "3;후유;01;이 작품을 무조건 가장 먼저 볼 수밖에 없도록 전시관 초입에 디스플레이 해 두었죠."
1012806-38 = "[s] \"작품의 배치 순서에도 굉장히 신경을 많이 쓰는구나.\""
1012806-39 = "3;후유;99;물론이죠. 작품들의 위치, 각도, 조명의 조도와 색상, 스크린의 밝기, 동선의 구성…….\n#3;em;[…]"
1012806-40 = "3;후유;13;전시를 구성하는 모든 요소에는 예술가의 의도가 함유되어 있다고요."
1012806-41 = "3;후유;03;자, 그럼 이어서 계속 보실까요?"
1012806-42 = "#st;[0,0];instant;1;"
1012806-44 = "3;후유;01\n#3;m5\n#3;em;[재잘]\n#3;hophop\n#wait;1500"
1012806-45 = "3;후유;12\n#3;m2\n#wait;1500"
1012806-46 = "3;후유;11\n#3;m2\n#3;em;[음표]\n#3;jump\n#wait;1200"
1012806-48 = "#na;(그렇게 후유의 작품들을 차근차근 봐 나가던 중…….)"
1012806-49 = "3;후유;99\n#3;a"
1012806-50 = "3;후유;99;……해서, 이 오브제의 모티브에 대해서 말씀드리자면…….\n#3;greeting"
1012806-51 = "#st;[0,0];instant;1;"
1012806-54 = "3;후유;28\n#3;stiff\n#3;em;[…]\n#wait;2500"
1012806-55 = "3;후유;25;……아하, 슬슬 배가 고프신 거군요, 선생님?"
1012806-56 = "[s] \"아니 방금 그 소리는 후유 쨩한테서…….\""
1012806-57 = "3;후유;27;후후, 이거 어쩔 수 없군요. \n#3;em;[땀]"
1012806-58 = "3;후유;24;예술가가 된 도리로 VIP 관람객의 배고픔을 외면할 수는 없죠.\n#3;closeup"
1012806-59 = "[s] \"저 아닌데요……!\""
1012806-60 = "3;후유;25;쉬잇.\n#3;closeup"
1012806-61 = "3;후유;23;일단 따라오라고요, 선, 생, 님?\n#3;closeup\n#3;em;[///]"
1012806-62 = "#st;[0,0];instant;1;"
1012806-64 = "3;후유;33\n#3;closeup\n#3;greeting\n#wait;1200"
1012806-66 = "#na;(그렇게 후유에게 이끌려 간 곳은…….)"
1012806-67 = "#st;[0,0];instant;1;"
1012806-71 = "#na;(전시실 구석에 숨겨져 있던 문의 안쪽이었다.)"
1012806-72 = "[ns] \"이, 이곳은……?\""
1012806-75 = "#st;[-1200,-530];serial;60;[wa:490]― [log=후유]이곳은 [wa:1440]스크린의 뒤편이에요.[/log]"
1012806-77 = "#st;[-1200,-630];serial;60;― [log=후유]즉, [wa:1370]작품의 뒷면…….[/log]"
1012806-80 = "#st;[-1200,-530];serial;60;[wa:540]― [log=후유]작가만이 드나들 수 있는 공간이죠.[/log]"
1012806-83 = "#st;[-1200,-530];serial;60;― [log=후유]이곳에 들어올 유일한 방법은……[/log]"
1012806-85 = "#st;[-1200,-630];serial;60;― [log=후유]작가인 저의 허락을 [wa:1290]받는 것뿐이죠. [/log]"
1012806-88 = "#st;[-1200,-530];serial;60;[wa:530]― [log=후유]그러니까,[wa:1500] 여기는 지금……[/log]"
1012806-90 = "#st;[-1200,-630];serial;60;― [log=후유]선생님과[wa:1050] 저, [wa:2660]단둘만 [wa:1620]있……는…….[/log]"
1012806-93 = "#st;[-1200,-530];serial;60;[wa:250]― [log=후유]그 [wa:650]아니아니아니![/log]"
1012806-95 = "#st;[-1200,-630];serial;60;― [log=후유]그, 그게 아니라……![/log]"
1012806-98 = "#st;[-1200,-530];serial;60;― [log=후유]아무튼![/log]"
1012806-100 = "#st;[-1200,-630];serial;60;[wa:80]― [log=후유]도시락을 만들어 왔는데요…….[/log]"
1012806-103 = "[ns]\"후유 쨩이 싼 도시락?!\""
1012806-104 = "#st;[-1200,-530];serial;60;[wa:620]― [log=후유]그게, [wa:1450]혹시, [wa:830]괜찮으시다면…….[/log]"
1012806-106 = "#st;[-1200,-630];serial;60;― [log=후유]……도시락, [wa:2720]먹고 갈래요?[/log]"
1012806-109 = "#na;(이후 함께 도시락을 먹었다.)"
1012806-110 = "#na;(요리를 잘 한다던 후유의 말은, 정말이었다.)"
