[translation]
1012505-1 = "เติมมานา"
1012505-2 = ""
1012505-3 = ""
1012505-4 = ""
1012505-5 = ""
1012505-6 = "สวัสดีค่ะมาสเตอร์"
1012505-7 = "ว้าว ฉันไม่ได้ออกมานอกสถาบันแบบนี้นานแล้วนะคะ"
1012505-8 = "อ่า ตื่นเต้นจัง..."
1012505-9 = "[s] \"ดูไม่ออกเลยว่าตื่นเต้น...\""
1012505-10 = "เปล่านะคะ"
1012505-11 = "อย่างน้อยก็ตื่นเต้นกว่าช่วงที่ผ่านมาค่ะ"
1012505-12 = "ฉันยังจำมันได้ดีเลยละค่ะ ปีศาจร้ายที่ฉันสร้างขึ้นบนผืนผ้าแคนวาสในห้องเรียน..."
1012505-13 = ""
1012505-15 = ""
1012505-16 = "อ๊าาา! พอพูดถึงเรื่องนั้นภาพมันก็เข้ามาในหัวอีกแล้วค่ะ! ในเวลาแบบนี้ต้องใช้เวทมนตร์ลบความทรงจำสินะ...!"
1012505-17 = ""
1012505-23 = "[ns] \"คะ... ครูเข้าใจแล้ว เลิกเอาหนังสือตีหัวเถอะ!\""
1012505-24 = ""
1012505-25 = ""
1012505-26 = "ฮู่ว..."
1012505-27 = "ถ้างั้นคงต้องใช้เวทมนตร์ชนิดอื่นมาคลี่คลายสถานการณ์แล้วค่ะ"
1012505-28 = "เพราะงั้นมาสเตอร์คะ ช่วยแนะนำหน่อยสิคะว่าฉันจะฟื้นฟูมานาของตัวเองยังไงดี?"
1012505-29 = "[s] \"เวทมนตร์ที่ช่วยเติมเต็มจิตวิญญาณอันหิวโหยล่ะ เป็นไง?\""
1012505-30 = "โฮ่ แค่ได้ยินก็ฟังดูน่าสนใจแล้วค่ะ"
1012505-31 = "ดีเลยค่ะ เรามาลองเวทมนตร์นั้นกันเถอะค่ะ"
1012505-38 = ""
1012505-39 = "โฮ่ ที่นี่คือ...?"
1012505-40 = "[s1] \"ร้านราเม็งที่ครูมาบ่อยๆ น่ะ\"\n[s2] \"ใกล้สำนักงานแล้วก็อร่อยเหาะ\""
1012505-43 = "สถานที่ที่มาสเตอร์มาบ่อยๆ..."
1012505-44 = "อย่างนี้นี่เองสินะคะ...#nได้กลิ่นหอมฟุ้งของมานาที่อบอวลอยู่ที่นี่เลยค่ะ"
1012505-45 = "ถ้าเป็นที่นี่จะต้องเติมเต็มจิตวิญญาณอันหิวโหยได้แน่ๆ ค่ะ"
1012505-46 = "ฉันกำลังหิวพอดีเลย เรารีบไปหาที่นั่งกันเถอะค่ะ"
1012505-47 = ""
1012505-52 = ""
1012505-53 = "อืม มาสเตอร์มีเมนูแนะนำบ้างมั้ยคะ?"
1012505-54 = "[s] \"ขอแนะนำทงคตสึราเม็ง\""
1012505-55 = "โฮ่ ราเม็งที่สกัดมานาเข้มข้นจากกระดูกที่อัดแน่นด้วยพลังเวทสินะคะ"
1012505-56 = "เรียกว่าเป็นเวทมนตร์ที่เติมเต็มจิตวิญญาณอันหิวโหยได้อย่างแท้จริงเลยค่ะ"
1012505-57 = "ถ้างั้นฉันจะสั่งเมนูทงคตสึราเม็งตามที่มาสเตอร์แนะนำค่ะ"
1012505-59 = "(หลังจากนั้นคุณครูกับเอริก็ตั้งใจ \"เติม\" มานาให้จิตวิญญาณอันหิวโหยกันอย่างเต็มที่)"
1012505-60 = ""
1012505-68 = ""
1012505-69 = "ฮู่ว รู้สึกได้เลยค่ะว่ามานาฟื้นฟูกลับมาแล้ว"
1012505-70 = "[s3] \"ตอนนี้เติมพลังจนอิ่มแล้ว เราไปที่ห้องสมุดกันเถอะ\"\n[s4] \"ครูรู้จักที่ดีๆ ที่มีหนังสือเกี่ยวกับรหัสยศาสตร์ที่เอริชอบด้วย\""
1012505-73 = "โฮ่ ห้องสมุดเหรอคะ"
1012505-74 = "ฉันสนใจในเรื่องรหัสยศาสตร์นะคะ แต่สิ่งที่ฉันสนใจกว่าก็คือหนังสือที่ถูกตราไว้ว่าเป็นหนังสือต้องห้ามของสถาบันค่ะ"
1012505-75 = "ถ้าได้อ่านหนังสือต้องห้ามนั่น เวทมนตร์ของฉันต้องพัฒนาขึ้นกว่านี้แน่นอนเลยค่ะ อุฮุฮุ"
1012505-76 = "[s] \"นะ... หนังสือต้องห้ามของไวลด์ฮันต์เหรอ? หนังสืออะไรน่ะ?\""
1012505-77 = "หนังสือที่ชื่อว่า \"เทคนิคการผูกเงื่อนเชือกที่ใช้งานได้จริง\" ค่ะ"
1012505-78 = "ถ้ารู้เทคนิคการผูกเชือกเงื่อนแบบต่างๆ ก็จะช่วยเพิ่มโอกาสในการหลบหนีการไล่ล่าของฝ่ายดูแลหอพักให้มากขึ้นค่ะ"
1012505-79 = "[s] \"เพราะงั้นเลยกลายเป็นหนังสือต้องห้ามเหรอ?\""
1012505-80 = "เปล่าค่ะ เหตุผลมัน... แปลกกว่านั้นเยอะเลย..."
1012505-81 = "ฉันได้ยินมาว่ามีศิลปินคนหนึ่งที่ใช้เชือกผูกตัวเองตามเงื่อนที่เขียนไว้ในหนังสือเล่มนั้น#nแล้วเดินไปตามถนนน่ะค่ะ"
1012505-82 = "เป็นเงื่อนรูปเต่าละมั้ง? อะไรประมาณนั้นน่ะค่ะ สงสัยจังว่ามันเป็นปมแบบไหนกันนะคะถึงได้ถูกห้ามแบบนั้น?"
1012505-83 = "มาสเตอร์รู้รึเปล่าคะ?"
1012505-84 = "[s] \"ไม่รู้ววววว!!\""
1012505-85 = "เอาเถอะค่ะ ถ้าได้อ่านดูเดี๋ยวก็รู้เองนั่นแหละค่ะ"
1012505-86 = "อุฮุฮุ ตื่นเต้นรอแล้วละค่ะ"
1012505-88 = "(จากนั้นคุณครูกับเอริก็แวะไปดูหนังสือประเภทต่างๆ ที่ร้านหนังสือด้วยกัน)"
1012505-90 = ""
1012505-91 = ""
1012505-92 = ""
1012505-93 = ""
1012505-94 = ""
1012505-95 = ""
1012505-97 = "(ทั้งสองคนไปยังสถานที่ต่างๆ และช่วยเอริเติมมานาให้กลับมาเหมือนเดิม)"
1012505-99 = ""
1012505-100 = ""
1012505-101 = ""
1012505-102 = ""
1012505-103 = ""
1012505-104 = ""
1012505-106 = ""
1012505-107 = ""
1012505-108 = ""
1012505-109 = ""
1012505-110 = ""
1012505-112 = ""
1012505-113 = ""
1012505-114 = ""
1012505-115 = ""
1012505-119 = ""
1012505-120 = "ฮู่ว ไปเดินเที่ยวมาเต็มที่เลยนะคะ"
1012505-121 = "ขอบคุณนะคะมาสเตอร์ วันนี้สนุกมากเลยค่ะ"
1012505-122 = "[s] \"ครูก็สนุกมากเหมือนกัน\""
1012505-123 = "บางทีถ้ามีอะไรสักอย่างที่เก็บไว้เป็นที่ระลึกถึงช่วงเวลานี้ก็คงดีนะคะ"
1012505-124 = "เรามาถ่ายรูปด้วยกันดีมั้ยคะ?"
1012505-125 = "[s] \"เอาสิ!\""
1012505-126 = ""
1012505-128 = ""
1012505-129 = ""
1012505-130 = "อุฮุฮุ ฉันจะถ่ายแล้วนะคะ เอ้า มองทางนี้ค่ะ..."
1012505-131 = "หนึ่ง สอง สาม~!"
1012505-133 = ""
1012505-134 = ""
1012505-135 = ""
1012505-136 = "ไหนดูซิ..."
1012505-137 = "โฮ่... รูปออกมาสวยเลยค่ะ"
1012505-138 = "......"
1012505-139 = "รูปถ่ายนี่สะดวกดีจริงๆ เลยนะคะ"
1012505-140 = "แค่กดปุ่มปุ่มเดียวก็เก็บภาพตรงหน้าไว้ได้แล้ว"
1012505-141 = "อาจเป็นเพราะแบบนั้นละมั้งคะ...? #nถึงเคยพูดกันว่าจิตรกรหลายๆ คนถึงกับรู้สึกสิ้นหวังเลยตอนที่มีการคิดค้นกล้องถ่ายรูปขึ้น"
1012505-142 = "เพราะบางครั้งภาพที่ถ่ายได้ในชั่วพริบตาก็อาจได้รับการประเมินค่าว่าดีกว่าภาพวาดที่ต้องใช้เวลา#nวาดนาน"
1012505-143 = "แต่พวกจิตรกรก็ไม่ยอมแพ้หรอกนะคะ"
1012505-144 = "เพราะเหล่าจิตรกรแต่ละคนได้ถ่ายทอด <ทัศนียภาพแห่งจิตใจ> หรือ <ผัสสะ> ที่มีเพียงพวกเขาเท่านั้นที่จะรับรู้ได้ลงบนผืนผ้าใบแคนวาสรูปค่ะ"
1012505-145 = "เห็นได้ชัดว่าผู้คนสมัยนั้นคิดว่าการวาด <สิ่งที่มองไม่เห็น> คือจุดแข็งของการวาดภาพค่ะ"
1012505-146 = "เวลาที่มองภาพวาดที่เปี่ยมด้วยจิตใจของเหล่าจิตรกร...#nฉันก็อยากวาดสิ่งที่มองไม่เห็นเหล่านั้นออกมาเหมือนกันค่ะ"
1012505-147 = "[s] \"ยังรู้สึกแบบนั้นใช่มั้ย?\""
1012505-148 = "แน่นอนค่ะ! เพราะฉันรักการวาดรูปมากพอๆ กับเรื่องรหัสยศาสตร์เลยค่ะ!"
1012505-149 = "คอยดูได้เลยค่ะ! สักวันหนึ่ง ฉันจะกลายเป็นจิตรกรที่มีชื่อเสียงและทุกๆ บ้านก็จะต้องมีรูปของฉัน#nติดเอาไว้!"
1012505-150 = "[s5] \"ครูชักอยากได้สักรูปไปแขวนไว้บ้างแล้วสิ\"\n[s6] \"ครูจองรูปไว้ก่อนเลยได้มั้ย?\""
1012505-153 = "คะ? ตอนนี้น่ะเหรอคะ?"
1012505-154 = "ถะ... ถ้าตอนนี้ยังไม่ไหวหรอกค่ะ... ช่วยรอก่อนนะคะ! ฉันจะวาดภาพที่ยอดเยี่ยมให้เป็นของขวัญมาสเตอร์เองค่ะ!"
1012505-155 = "ค่ะ... ฉันจะมัวมาซึมอยู่แบบนี้ไม่ได้"
1012505-156 = "ขอบคุณนะคะ มาสเตอร์ ที่ช่วยให้ฉันนึกถึงสิ่งที่ผลักดันให้ฉันเลือกเรียนศิลปะได้"
1012505-157 = "ฉันจะพยายามค่ะ! อย่างน้อยก็เพื่อมาสเตอร์ที่เชื่อในตัวฉัน!"
1012505-158 = "[s] ต้องอย่างนี้สิ! ครูเป็นกำลังใจให้นะ\""
1012505-159 = "อ่า แหะๆๆ..."
1012505-160 = "น่าแปลกจังเลยนะคะ"
1012505-161 = "วันนี้ก่อนที่ฉันจะมาพบกับมาสเตอร์ฉันรู้สึกไม่ดีมากๆ แต่ตอนนี้กลับรู้สึกมีกำลังใจมากขนาดนี้"
1012505-162 = "อย่างที่คิดเลย มาสเตอร์นี่เชี่ยวชาญเรื่องวัจนมนตราจริงๆ สินะคะ"
1012505-164 = "(เอริเล่าถึงความฝันของเธอต่อด้วยสีหน้าที่สดใสขึ้นกว่าเดิม)"
1012505-165 = "(หลังจากนั้น คุณครูก็ไปส่งเอริที่สถาบันก่อนที่จะดึกจนเกินไป)"
