[translation]
1013505-1 = "I Need Help"
1013505-2 = "I urgently headed to Millennium!"
1013505-7 = "Gotcha, Kei-Kei!"
1013505-8 = "P-Please, let me go!"
1013505-9 = "Don't you like us, Kei-Kei?"
1013505-10 = "It's not that, b-but... Well..."
1013505-11 = "Aw, she's embarrassed! See, I told you. She has a charm all her own, totally different from Aris'."
1013505-12 = "(Why does Aris just get to be \"Aris,\" and I have to be \"Kei-Kei\"?)"
1013505-16 = "[ns1] \"I was worried this was urgent...\"\n[ns2] \"But it looks like it's just 'Dote on Kei-Kei Time.'\""
1013505-19 = "Sensei?! Great timing! As a teacher, please rescue a student in crisis—"
1013505-20 = "Oh, it's Sensei! Hello, Sensei!"
1013505-21 = "Would you like to join us for \"Dote on Kei-Kei Time?\" It's great for stress-relief."
1013505-22 = "[s] \"Of course I would!\""
1013505-23 = "What?!"
1013505-24 = "..."
1013505-26 = "I WAS AN IDIOT TO TRUST THIS ADULT!"
1013505-29 = "So, you're Aris' twin sister, right?"
1013505-30 = "Huh? Y-Yes... It's something...like that. Yes..."
1013505-31 = "Wow, that must be so fun. Two sets in the GDD. But wait! Your hair! Your shades are polar opposites."
1013505-32 = "Oh! I see! You're fraternal twins!"
1013505-33 = "Uh... Ugh... Yes... Let's go with that..."
1013505-34 = "Now it's MY turn to give Kei-Kei a special quest!"
1013505-35 = "This again..."
1013505-36 = "Oh, do you not like it?"
1013505-37 = "It's not that—!"
1013505-41 = "..."
1013505-42 = "...I don't dislike it, exactly."
1013505-43 = "It's just a little embarrassing, and I'm not used to it, so..."
1013505-45 = "Awwwwww!"
1013505-47 = "Ugh, I have a terrible feeling...!"
1013505-49 = "Kei-Kei is so cute!!"
1013505-54 = "[ns] \"Kei-Kei really IS so cute!!\""
1013505-55 = "Why are you joining them?!"
1013505-56 = "On that note, will you please take this to the lecture hall in the next building?"
1013505-57 = "Ah, sure... It's a delivery quest, is it?"
1013505-58 = "Yes. And this time, it's a quest with the reward upfront. Here, have this necklace."
1013505-59 = "...!"
1013505-60 = "It's...quite pretty. "
1013505-61 = "The decorations aren't so extravagant that they're distracting, and the gemstone has a blue chrome luster and a slightly yellow tint..."
1013505-62 = "Th-This looks quite precious. Are you sure I should have it?"
1013505-64 = "It's fine, it's fine. It's just leftovers from the New Material Development Club. We would have recycled it otherwise."
1013505-65 = "That's an artificial diamond. If you looked at its base components, it's just carbon!"
1013505-67 = "I see... Artificial diamonds have improved a lot, haven't they?"
1013505-69 = "Then we'll leave it to you!"
1013505-70 = "Come to us if you need more quests!"
1013505-72 = "Ha...yeah. N-No thank you, actually... I think this will do."
1013505-73 = "...?"
1013505-74 = "How long do you intend on standing there, Sensei? And what's with that face?"
1013505-75 = "[s] \"Well, it's just...\""
1013505-76 = "...Just?"
1013505-77 = "[s] \"I was honored to witness something so amazing!\""
1013505-78 = "Gaaaaaah!!"
1013505-81 = "Ugh, really... Why do I get all the attention...?"
1013505-82 = "Stop, stop. I know what you're going to say. You're going to say it's so lovely that I'm appreciated and cherished or whatever."
1013505-83 = "...Oh, stop pouting! Really, you're such a—!"
1013505-84 = "[s] \"How's school life treating you?\""
1013505-85 = "..."
1013505-86 = "Well, it's not bad. It's all right."
1013505-87 = "[s] \"My Kei translator says that means, 'I really like it! It's wonderful!'\""
1013505-88 = "Don't be so weird! Why are you translating me?! We're speaking the same language."
1013505-89 = "*huff* *puff* *huff*"
1013505-90 = "Look, I'm on a quest, so please don't be a bother."
1013505-91 = "Huh? I told you, I'm on a ques..."
1013505-92 = "...!!"
1013505-93 = "E-Errand!! An errand!"
1013505-94 = "Get that satisfied look off your face!"
1013505-95 = "[s] \"I didn't say anything!\""
1013505-96 = "And you better not start!"
1013505-97 = "[s] \"What about freedom of expression?\""
1013505-98 = "You're the EXCEPTION, Sensei!"
1013505-99 = "Oh, it's Kei. What's up?"
1013505-106 = "Ah...? Good timing. I got a ques—I mean, a REQUEST to deliver this."
1013505-107 = "Let's see... Aha, the results are in. The superconductivity of this metal compound is..."
1013505-108 = "No offense, but couldn't this have been an email?"
1013505-109 = "I would agree with you for most cases, but this is exceptional."
1013505-110 = "Why is that?"
1013505-111 = "Security reasons! Only our club is allowed to know the results. We can't let our confidential data leak to other groups!"
1013505-112 = "The internet's only two downsides are security vulnerabilities and data retention limits!"
1013505-113 = "Ah, I see what you mean. That's a big reason why it's so difficult to dispose of data written to magnetic tape."
1013505-114 = "If I had the funds, I'd archive all our work on crystal data disks, a mountain of them! But I don't think that's happening."
1013505-115 = "Say, Kei. Since you've gone through all the trouble of finding me, how about we hit the arcade?"
1013505-116 = "H-Huh? Well..."
1013505-117 = "Hm? What's wrong? You had so much fun last time."
1013505-118 = "I did! Well, that is to say..."
1013505-119 = "[s] \"Aha! So Kei-Kei likes gaming too!\""
1013505-120 = "That's right, Sensei! You'd be surprised! She's really into it!"
1013505-121 = "No! That's, well, it was only a...!"
1013505-122 = "Huh...? Oh, do you mean that you didn't like it? You only came along because you felt pressured?"
1013505-123 = "That's also not it! None of this is what I'm saying!"
1013505-127 = "[ns] \"Well, what is it, then? Kei-Kei?\""
1013505-128 = "Y-Y-Y—"
1013505-130 = "YOU'RE A TERRIBLE ADULT FOR PLAYING DUMB LIKE THIS. YOU KNOW EXACTLY WHAT'S GOING ON!"
