[translation]
1013008-1 = "The Giving Sister"
1013008-2 = ""
1013008-3 = "Hello, Subaru! Oh, Sensei, you too!"
1013008-4 = "Hello. I hope you're doing well."
1013008-5 = ""
1013008-7 = ""
1013008-8 = "Oh? Subaru, isn't that the..."
1013008-10 = "...legendary corn stick? In the rumored and limited-time barbecue cheese flavor?"
1013008-11 = "Wh-What?"
1013008-12 = "Well, yes..."
1013008-13 = ""
1013008-15 = ""
1013008-16 = "..."
1013008-17 = "Do you want it?"
1013008-18 = ""
1013008-20 = ""
1013008-21 = ""
1013008-22 = "I'd...be honored!"
1013008-23 = "Haha, very well. Here you go."
1013008-24 = "Really? Sweet, thank you!"
1013008-25 = ""
1013008-27 = ""
1013008-28 = "..."
1013008-29 = "(I'd been saving that for later...)"
1013008-30 = "[s] \"Are you all right, Subaru?\""
1013008-31 = "Huh? Of course I am. It's nothing."
1013008-32 = "Oh, but my face said I wasn't alright?"
1013008-33 = "Stop looking at my face so much! You're just making things up!"
1013008-35 = ""
1013008-36 = "Wait, the custard-flavored juice?"
1013008-37 = "Custard is already such a tasty dessert. And they made it into a juice? Wow."
1013008-38 = "That's right. It's nice and cold."
1013008-39 = "..."
1013008-40 = "Umm... Subaru...?"
1013008-41 = "If I may... Can I have a sip?"
1013008-42 = "..."
1013008-43 = "More than that. Take the whole thing."
1013008-44 = "Are you sure?!"
1013008-45 = "Positive. But try to share with the others too, okay?"
1013008-46 = "Thank you so much!"
1013008-47 = ""
1013008-49 = ""
1013008-50 = ""
1013008-51 = "(That wasn't easy to get...)"
1013008-52 = "[s] \"Are you all right...?\""
1013008-53 = "What?!"
1013008-54 = "..."
1013008-55 = "Yes, of course. Always."
1013008-57 = ""
1013008-58 = "Thank you!"
1013008-59 = "Don't mention it."
1013008-60 = ""
1013008-61 = "Amazing! You're the best, Subaru!"
1013008-62 = "It... It was nothing. Enjoy."
1013008-64 = "For Subaru's sake, I'll skip the details, but..."
1013008-65 = "After everything was over, Subaru was basically empty-handed."
1013008-66 = ""
1013008-67 = "..."
1013008-68 = "[s] \"...\""
1013008-69 = "..."
1013008-70 = "[s] \"...\""
1013008-71 = "Wh-Why are you looking at me like that...?"
1013008-72 = "[s] \"You don't need to be strong for me.\""
1013008-73 = "No... You got it all wrong."
1013008-74 = ""
1013008-76 = ""
1013008-77 = "But still..."
1013008-78 = "That last treat, though... It's a bit of a shame."
1013008-79 = "[s1] \"Subaru, you leave me no choice.\" \n[s2] \"You need to be kidnapped.\""
1013008-82 = "...Huh?"
1013008-83 = ""
1013008-84 = "S-Sensei? What is this place...?"
1013008-85 = "Huh? \"Eat first and ask questions later\"?"
1013008-86 = "..."
1013008-87 = "Oh, I see what this is. Look, I'm not a charity ca—"
1013008-89 = "Here is your order. Please take your time and enjoy."
1013008-90 = ""
1013008-92 = ""
1013008-93 = ""
1013008-94 = "[ns] \"...Are you sure?\""
1013008-95 = "O-Of course! I'm fine!"
1013008-96 = "B-But, let me just ask you this..."
1013008-97 = "...Did you...order only...my favorites, somehow...?"
1013008-98 = "[s3] \"We hung out together, Subaru!\"\n[s4] \"When you were at Schale and tried everything!\""
1013008-101 = "!"
1013008-102 = "Th-That's a touching sentiment."
1013008-104 = "She waited until I looked away and was momentarily distracted."
1013008-105 = ""
1013008-106 = ""
1013008-107 = ""
1013008-108 = "A small bit of food disappeared, all without my notice."
1013008-110 = "Afterwards, I was momentarily fascinated by so many other different things in the cafe."
1013008-111 = ""
1013008-112 = ""
1013008-113 = ""
1013008-114 = "The food vanished, morsel by morsel!"
1013008-115 = ""
1013008-116 = "[ns] \"Oh, that's weird.\""
1013008-117 = "Huh? What?"
1013008-118 = "[s] \"I think the food is disappearing.\""
1013008-119 = "M-Maybe you ate some without thinking...?"
1013008-120 = "I should work on my excuses?"
1013008-121 = "Th-That's a pretty good lesson, Sensei."
1013008-122 = "..."
1013008-123 = "Yes, I confess! It was me."
1013008-124 = "...I bet you dislike high school girls who eat this much, huh?"
1013008-125 = "[s] \"...!\""
1013008-126 = ""
1013008-129 = "[ns5] \"Not at all! You all should eat well and grow!\"\n[ns6] \"There's nothing better than well-fed students!\""
1013008-132 = "Y-You mean it?"
1013008-133 = "..."
1013008-134 = "Thank...you."
1013008-135 = "Huh? Besides that, you mean...I still have something I need to work on?"
1013008-136 = "The manner in which I...satisfy my desires...?"
1013008-137 = "...Sensei, you're not just going around saying things like that to all the other students, are you?"
1013008-138 = ""
1013008-140 = ""
1013008-141 = "Why are you averting your gaze? Look into my eyes and tell me the truth!"
1013008-143 = "I dodged her piercing glare and deliberately dragged her around town."
1013008-144 = ""
1013008-145 = ""
1013008-146 = ""
1013008-147 = ""
1013008-148 = ""
1013008-149 = ""
1013008-150 = ""
1013008-151 = "[ns] \"How do you like it?\""
1013008-152 = "...I guess I feel a bit dazed."
1013008-153 = "It's not the fear of the unknown, but rather..."
1013008-154 = "...It's all unfamiliar. And it seems everyone else has experienced this type of casual outing often."
1013008-155 = "I've tried resolving conflicts outside of Arius before...but this..."
1013008-156 = ""
1013008-158 = ""
1013008-159 = "The so-called \"sunny-side\" of life..."
1013008-160 = "I've never done things like this before, you see..."
1013008-161 = "*gasp*"
1013008-162 = "What is this music, Sensei?!"
1013008-163 = "WE ALL NEED TO DIIIEEE!!!"
1013008-165 = "Subaru's eyes sparkled. I took her to the record shop."
1013008-166 = ""
1013008-167 = "Heavy...metal? This is a type of music?"
1013008-168 = "Do I like it? Uh, um, I don't know what to say... Maybe..."
1013008-169 = "It's powerful!"
1013008-170 = "[ns] \"Of course it is!\""
1013008-171 = "It feels energetic, fast, and like it's bursting with life, danger, and edge!"
1013008-172 = "Above all, I love that the lyrics are demanding that this cruel world be dragged to hell!"
1013008-173 = "[ns] \"Please don't actually drag it!\""
1013008-174 = ""
1013008-175 = "Wow. That was amazing, Sensei. "
1013008-176 = "My ears and heart are still pounding..."
1013008-177 = "Huh? You think I had an innate affinity for metal? Perhaps..."
1013008-178 = "I'm not really sure about that. It just struck me, that's all."
1013008-179 = "...Especially the lyrics."
1013008-180 = "[s] \"...Do you still want the world to be dragged to hell?\""
1013008-181 = "..."
1013008-182 = "Well, I don't know really. "
1013008-183 = "On one hand, yes, but maybe not sincerely."
1013008-184 = "But you told me that a person's heart is never simple, you know?"
1013008-185 = "..."
1013008-186 = "So, maybe I'm willing to be convinced that the world is still worthwhile. If you have anything to say in its defense..."
1013008-187 = "[ns] \"Whoa! That's a lot of pressure!\""
1013008-188 = "Oh, is it? You're an adult!"
1013008-189 = "[s] \"Adults aren't all-knowing.\""
1013008-190 = "But you showed me so much, Sensei."
1013008-191 = "[s] \"I can't say that I didn't...\""
1013008-193 = "We joked about trivial things as I walked her back."
