[translation]
1014206-1 = "A Secret Signal Between Two"
1014206-2 = "So we went to the beach."
1014206-3 = ""
1014206-4 = ""
1014206-6 = ""
1014206-7 = "Nice spike!"
1014206-8 = "Oh no, that got me...!"
1014206-9 = "That sound...?"
1014206-10 = "Sensei, this way."
1014206-13 = ""
1014206-14 = ""
1014206-15 = ""
1014206-16 = "[ns] \"Oh, they're playing beach volleyball.\""
1014206-17 = "Oh, Nagusa and Sensei!"
1014206-18 = "Hey, you two! Do you want to join in on our game?"
1014206-19 = ""
1014206-21 = ""
1014206-22 = ""
1014206-23 = "Sounds good to me. How about you, Sensei?"
1014206-24 = "[s1] \"I'll watch.\"\n[s2] \"I won't be a help anyway.\""
1014206-27 = "It is more enjoyable to play together, though."
1014206-28 = "Ah, I see..."
1014206-29 = "Are you...one who finds watching more enjoyable?"
1014206-30 = ""
1014206-32 = ""
1014206-33 = "Sensei, you truly are..."
1014206-34 = "[s] \"I don't know what you're thinking, but the answer is no!\""
1014206-36 = "In the end, she convinced me to join the beach volleyball game."
1014206-37 = ""
1014206-38 = "Then, Sensei and Nagusa will be one team!"
1014206-39 = "That should balance things out!"
1014206-40 = "[s] \"I'll try not to be a burden.\""
1014206-41 = ""
1014206-44 = "A burden? Never."
1014206-45 = "And my right hand is at its best."
1014206-46 = "Worry not. In this condition, I cannot lose."
1014206-47 = "[s3] \"S-Still, I can't leave everything to you, Nagusa.\"\n[s4] \"Is there any strategy where I can be of help?\""
1014206-50 = ""
1014206-52 = ""
1014206-53 = ""
1014206-54 = "A strategy..."
1014206-55 = "We shall make a few signals."
1014206-56 = "A method to communicate without the opponents' understanding."
1014206-57 = "Our secret signal."
1014206-59 = "And so the match began."
1014206-60 = ""
1014206-61 = "[fffbab]GO[-]"
1014206-62 = "[fffbab]RYOU[-]"
1014206-63 = "[fffbab]NA[-]"
1014206-64 = "[fffbab]GU[-]"
1014206-65 = "[fffbab]SA[-]"
1014206-67 = ""
1014206-68 = "[ffaecd]HYAK[-]"
1014206-69 = "[ffaecd]KI[-]"
1014206-70 = "[ffaecd]YA[-]"
1014206-71 = "[ffaecd]KO[-]"
1014206-72 = "[ffaecd]STU[-]"
1014206-73 = "[ffaecd]DEN[-]"
1014206-74 = "[ffaecd]TS[-]"
1014206-75 = "[ffaecd] [-]"
1014206-76 = "[ffaecd] [-]"
1014206-79 = ""
1014206-81 = "[fffbab]VS[-]"
1014206-84 = ""
1014206-85 = "The opponent serves first."
1014206-86 = "To take the lead, the first defense is important."
1014206-90 = "― [log=나구사 수영복]We will proceed with this plan first.[/log][wa:571] "
1014206-92 = "― [log=나구사 수영복]I expect they intend to begin with their full force.[/log][wa:370] "
1014206-95 = "― [log=나구사 수영복]...Sensei?[/log][wa:4521] "
1014206-97 = "― [log=나구사 수영복]Are you not paying attention to my signals?[/log][wa:720] "
1014206-100 = "― [log=나구사 수영복]It's unlike you to get distracted so easily.[/log][wa:1530] "
1014206-102 = "― [log=나구사 수영복]What is it that caught your eye...?[/log]"
1014206-105 = "― [log=나구사 수영복]Ah... I see.[/log][wa:5761] "
1014206-107 = "― [log=나구사 수영복]...I apologize. [/log][wa:10] "
1014206-110 = "― [log=나구사 수영복]I see how that would mar your focus. [/log]"
1014206-112 = "― [log=나구사 수영복]It is all because... I am a mysterious beauty.[/log][wa:1860] "
1014206-115 = "― [log=나구사 수영복]These are standard signs in beach volleyball...[/log][wa:1201] "
1014206-117 = "― [log=나구사 수영복]Would it be wise to attempt a different approach? [/log][wa:430] "
1014206-120 = "― [log=나구사 수영복]...No. The hour is upon us.[/log][wa:3771] "
1014206-123 = "― [log=나구사 수영복]We must persevere, Sensei.[/log][wa:1293] "
1014206-125 = "― [log=나구사 수영복]If it is us two... It will be okay.[/log][wa:1530] "
1014206-128 = "And the match began."
1014206-129 = "Regardless of the result, everyone had a great time."
1014206-131 = ""
1014206-132 = ""
1014206-133 = ""
1014206-134 = ""
1014206-135 = ""
1014206-136 = ""
1014206-138 = "And after the match..."
1014206-139 = ""
1014206-140 = "Ahaha, I had so much fun today!"
1014206-141 = "Have a good time, you two!"
1014206-142 = ""
1014206-144 = ""
1014206-145 = ""
1014206-146 = "\"Good time\"? Wh-What could they mean?"
1014206-147 = "[s5] \"Probably literally.\"\n[s6] \"Keep fully enjoying this great time together.\""
1014206-150 = "..."
1014206-151 = "...Yes, you're right."
1014206-152 = "Quite a lot has occurred recently."
1014206-153 = "Without you, my hand would likely still be tainted by the ominous powers of the spirit realm."
1014206-154 = "Thanks to you, Sensei..."
1014206-155 = "I've learned how to reach out to others."
1014206-156 = "I have realized that I have the strength to move forward."
1014206-157 = "It may be true that nothing will be as it was..."
1014206-158 = "However, none of that concerns me. Not with you by my side."
1014206-159 = "...Ah."
1014206-160 = "It wasn't my intention to speak so candidly."
1014206-161 = ""
1014206-163 = ""
1014206-164 = ""
1014206-165 = "[ns] \"N-Nagusa...?\""
1014206-166 = "What is done is done, so please allow me to make my meaning clear."
1014206-167 = "Despite my many failings..."
1014206-168 = "...and the fact that my beauty is my greatest strength..."
1014206-169 = "...Thank you. For all you have done and do, Sensei."
1014206-171 = "Nagusa and I enjoyed the rest of our beach trip together until the sun went down."
