[translation]
102060-1 = "Episode 6; First Sanctum - Abydos Desert District"
102060-3 = "The operation has commenced!"
102060-4 = "The second unit will lure the target to the trans-desert railway, and we'll join you at the rendezvous point to secure a route to the guardian."
102060-5 = "And don't forget! Watch out for Binah's laser! Please!"
102060-9 = "Yup, yup! Understood ☆"
102060-10 = "Time to gooo!"
102060-11 = "We're gonna kick some butt!"
102060-13 = "That's our signal. You guys good?"
102060-14 = "I'm always ready!"
102060-15 = "U-Understood!"
102060-16 = "Let's start, Kayoko."
102060-18 = "Okay, I'll operate the railway."
102060-27 = "O-Oh! O-Over there...!"
102060-28 = "An attack...?!"
102060-29 = "Hmm, they came after us? They're smart!"
102060-33 = "...Hmph, did you think you could stop us with something like this? I'll show you how wrong you were."
102060-34 = "All right, let's go, hard-boiled outlaws!"
