[translation]
102190-1 = "第19話;「D.U.白鳥區」防衛"
102190-5 = "接下來是最後的第6個聖所──#n不過尚未確認到這裡的「守護者」。"
102190-6 = "但是，從目前探測到的能量數值來看，這裡的「守護者」將會是比其他守護者更危險的存在──也許，光是這個「守護者」就能凌駕於其他所有的「守護者」。"
102190-7 = "即使連忙發起攻擊，也將難以預測接下來的發展……#n總之先加強D.U.周邊的防禦和偵查吧。"
102190-8 = "我會在其他聖所的攻略結束之前，找出第6聖所的對抗手段的。"
102190-9 = "真的存在對抗手段嗎，部長？"
102190-10 = "那當然囉，英美。你以為我是誰呢？#n即使是現在，我也正進行資料的收集，包在我身上吧。"
102190-11 = "呃，下水道的──"
102190-12 = "完全不對。第一個詞語就錯了唷。#n真是的……英美，你是故意的吧？"
102190-13 = "……"
102190-14 = ""
102190-19 = "好，找到了！那些就交給我們吧！"
102190-20 = "沒錯，D.U.白鳥區的防衛就由我們來負責吧。"
102190-22 = "其實，只是因為那是往水族館路上的障礙物而已★"
102190-23 = "趕快搞定吧～！"
102190-24 = "補課部的兩位，不介意的話要不要一起行動呢？"
102190-26 = "咦！？我，我們也一起，是嗎！？"
102190-27 = "啊啊，那就拜託你們了。"
102190-29 = "唉呀？真是久違了呢。"
102190-30 = "好！出發吧！"
102190-32 = ""
102190-38 = ""
102190-39 = "無限迴轉的軌道……終將通向正義的未來！"
102190-40 = ""
102190-42 = ""
102190-43 = "無限迴轉壽司戰隊．凱坦澤！登場！"
102190-44 = "哈哈哈！世界面臨危機的此刻，我等也不能視而不見！"
102190-45 = "沒錯！現在是我等凱坦澤出場的時候！！"
102190-46 = "不過，這好像真的是危機耶？沒問題嗎？"
102190-47 = "Red，據我所知，今天的工作會有特別津貼。#n以防萬一，我好心提醒你一下。"
102190-48 = "哼，那就沒辦法了。盡力做吧。"
102190-49 = "上吧！！無限迴轉壽司戰隊．凱坦澤，出擊！！"
102190-50 = ""
102190-52 = ""
102190-54 = ""
102190-55 = "……咦，咦？剛才，我好像看見了奇怪的集團……"
102190-56 = "嗯！！我也看見了！！是壽司對吧！"
102190-57 = "咦，壽司？在哪裡在哪裡？"
102190-58 = "壽司是稀有的食物對吧……之前訂外送的時候，對方說本季的利率比較高，所以拒絕外送……"
102190-59 = "不是，壽司和利率有什麼關係啊！"
102190-61 = "呵呵……真不錯呢。#n既然氣氛已經炒熱了，我們也來表現一下吧。"
102190-62 = "上吧！"
102190-63 = ""
