[translation]
103055-2 = "According to the coordinates, it should be this way."
103055-3 = "Over here! There's an entrance connected to the basement!"
103055-4 = "I see... It looks quite deep."
103055-5 = "Hmm, let's go."
103055-6 = ""
103055-15 = "Where...?"
103055-16 = "A mechanical hallway...?!"
103055-17 = "Let's keep going."
103055-18 = ""
103055-24 = "The inside is a little more neat."
103055-25 = "This way! This stairway!"
103055-29 = "Whoa!"
103055-30 = "This..."
103055-31 = ""
103055-34 = ""
103055-43 = "...I see. It wasn't an exaggeration."
103055-44 = "It appears to really be an intergalactic battleship."
103055-45 = "[s] \"All aboard!\""
103055-46 = "Yes! "
103055-48 = "Next Episode; Utnapishtim's Ship 1"
