[translation]
103110-1 = "#title;제11화;처음의 이야기"
103110-11 = "#na;총학생회장;……내 실수였어요."
103110-12 = "#st;[0,0];instant;1;"
103110-16 = "#na;총학생회장;내 결정들. 그리고 그로 인해 초래된 모든 상황들."
103110-18 = "#st;[0,0];instant;1;"
103110-21 = "#na;총학생회장;결국 이 결과에 도달하고서야 당신이 옳았다는 걸 깨닫다니……."
103110-22 = "#na;총학생회장;……그러니 염치없지만 부탁드리겠습니다."
103110-24 = "#st;[0,0];instant;1;"
103110-27 = "#na;총학생회장;[USERNAME] 선생님."
103110-29 = "#st;[0,0];instant;1;"
103110-32 = "#na;총학생회장;어차피 제 말을 잊어버리게 될 테지만, 그래도 상관없겠죠."
103110-33 = "#na;총학생회장;아무것도 기억나지 않아도, 당신은 아마 같은 상황에서 똑같은 선택을 하실 테니……."
103110-34 = "#st;[0,0];instant;1;"
103110-38 = "#na;총학생회장;그러기에 아마…… 중요한 것은 경험이 아니라, 선택."
103110-39 = "#na;총학생회장;당신만이 가능한 선택들."
103110-40 = "#st;[0,0];instant;1;"
103110-44 = "#zmc;instant;0,-50;2600\n#na;총학생회장;책임을 지는 사람에 대해 얘기한 적이 있었지요."
103110-45 = "#zmc;instant;0,-50;2600\n#na;총학생회장;그때의 저는 알지 못했지만…… 지금은 이해할 수 있습니다."
103110-46 = "#zmc;instant;0,-50;2600\n#st;[0,0];instant;1;"
103110-49 = "#na;총학생회장;어른. 책임과 의무, 그리고 그 너머에 있는 당신의 선택."
103110-50 = "#na;총학생회장;그것이 의미하는 바까지도."
103110-52 = "#st;[0,0];instant;1;"
103110-59 = "#st;[-1200,-530];serial;60;― ……."
103110-65 = "#st;[-1200,-530];serial;60;― 그러니까, [wa:900]선생님."
103110-71 = "#st;[-1200,-530];serial;60;― 내가 믿을 수 있는 어른인 [wa:1800]당신만이,"
103110-77 = "#st;[-1200,-530];serial;60;― 이 뒤틀리고 일그러진 종착지가 아닌"
103110-82 = "#st;[-1200,-530];serial;60;― 이 뒤틀리고 일그러진 종착지가 아닌 다른 결과를……"
103110-88 = "#st;[-1200,-530];serial;60;― 그곳으로 이어지는 선택지를……"
103110-93 = "#st;[-1200,-630];serial;60;― 찾을 수 있을 겁니다."
103110-97 = "#na;총학생회장;그러니까, 선생님.#n부디……."
103110-98 = "#st;[0,0];instant;1;"
103110-101 = "#na;총학생회장;우리들과의 인연을,"
103110-102 = "#na;총학생회장;우리들과의 추억…… 함께 해 온 그 모든 날들을…… 부디……."
103110-103 = "#st;[0,0];instant;1;"
103110-115 = "3;유우카 승무원;04;뭐, 뭐야?!\n#3;em;[?!]\n#3;stiff\n#3;a"
103110-116 = "3;하나코 승무원;05;다차원해석 시스템 에러 발생……!!\n#3;a"
103110-117 = "3;하나코 승무원;05;<우트나피쉬팀>의 확률적 중첩 상태가……! 방주와 불일치하고 있어요!\n#3;closeup\n#3;em;[!]\n#3;a"
103110-118 = "3;유우카 승무원;04;뭐?! 시스템이 고장 난 거야?!\n#3;em;[반응]"
103110-119 = "3;유우카 승무원;04\n5;히마리 승무원;06;아, 아니에요…… 이건……. \n#5;al\n#3;m1\n#3;h"
103110-121 = "3;AMAS드론 리오;00;그쪽이 아니야! 값에서 벗어난 건 <아트라하시스의 방주>다!!\n#3;closeup\n#3;a\n#3;em;[!]\n#fontsize;75"
103110-122 = "#st;[0,0];instant;1;"
103110-128 = "3;AMAS드론 리오;00\n#3;a"
103110-129 = "3;AMAS드론 리오;00\n#wait;200"
103110-130 = "3;AMAS드론 리오;00\n5;유우카 승무원;04;리, 리오 회장?!\n#5;em;[?!]\n#5;al\n#3;m1\n#3;h"
103110-132 = "3;하나코 승무원;06;……!!\n#3;a"
103110-133 = "3;히마리 승무원;05;마, 말도 안 돼……. 서, 설마…….\n#3;em;[...]"
103110-134 = "3;히마리 승무원;11;<아트라하시스의 방주> 쪽의 상태가 바뀌었다고요! 설마, 우리가 계산한 값에서 벗어나려고……?!"
103110-135 = "3;AMAS드론 리오;00;……우리가 인지하고 있는 다차원이 아닌, 뭔가 새로운 축을 하나 더 세운 거야.\n#3;em;[반응]"
103110-136 = "3;AMAS드론 리오;00;2차원의 존재에게 3차원을 아무리 설명해봤자 이해할 수 없는 것처럼……."
103110-137 = "3;유우카 승무원;04;뭐, 뭐라고…….\n#3;em;…"
103110-138 = "3;하나코 승무원;02;그렇다는 건…… 다차원해석을 능가하는 계산이 언제든지 가능했다는 건가요……?\n#3;em;[?]"
103110-139 = "3;히마리 승무원;05;설마…… 지금까지의 분석이 전부……."
103110-140 = "#st;[0,0];instant;1;"
103110-142 = "3;히마리 승무원;05\n#3;d\n#wait;1000"
103110-143 = "3;히마리 승무원;06;소용없었다는 얘기……?\n#3;closeup\n#3;a"
103110-145 = "#nextepisode;다음화;빛의 자격 1"
