[translation]
104050-1 = "ตอนที่ 5;ทางเลือกที่สะดวก"
104050-2 = "ตัดการเชื่อมต่อกับเรืออะทราฮาซิสได้แล้ว จากนี้เรือลำนี้จะแฮ็กเรือรบอุตนาพิชทิมของเราไม่ได้ไป#nระยะหนึ่ง"
104050-3 = "ค่ะ ระบบของเรือรบอุตนาพิชทิมที่ปิดไปก็เริ่มฟื้นฟูแล้วค่ะ!"
104050-4 = "ถ้าเป็นแบบนี้ละก็...!! ฝากด้วยนะ รุ่นพี่ฮิมาริ!!"
104050-5 = ""
104050-7 = ""
104050-8 = "ค่ะ! ฉันจะตั้งไฟร์วอลล์ใหม่แล้วเอาการควบคุมของเรือรบอุตนาพิชทิมกลับมาค่ะ!!"
104050-9 = "เราต้องยึดอำนาจการควบคุมของเรืออะทราฮาซิสมาให้ได้ไวๆ ด้วยค่ะ! ริโอะ! สั่งให้โทคิถอนกำลัง#nเถอะค่ะ!"
104050-10 = "......โทคิ! ตอนนี้ทำลายหอคอยนั่นได้แล้ว!"
104050-11 = ""
104050-15 = "ค่ะ เรื่องนั้นฉันจะจัดการเอง...... จนกว่าจะถึงตอนนั้น รีบ......"
104050-16 = "พอได้แล้ว!! รีบถอนกำลังออกมา!!"
104050-19 = ""
104050-20 = ""
104050-21 = ""
104050-22 = "ขอโทษนะคะ...... ท่านริโอะ ฉัน...... ทำแบบนั้นไม่ได้หรอกค่ะ"
104050-23 = ""
104050-26 = "โทคิ!!?"
104050-27 = "ร่างกายของฉัน...... มันไม่ขยับแล้วละค่ะ...... ฉันต้องขวางสิ่งนั้นไว้แท้ๆ......"
104050-28 = "โทคิ... ระ... รอเดี๋ยวนะคะ ฉันขอกำลังเสริมไปแล้ว...... เดี๋ยวพวกเขาก็ไปถึง......"
104050-29 = "....... ไม่หรอกค่ะ ฉันรู้ค่ะว่ากำลังเสริมมาไม่ทันอยู่ดี "
104050-30 = ""
104050-32 = ""
104050-33 = "ที่แห่งนี้มันไกลมาก..... ต่อให้รีบมาแค่ไหน....."
104050-34 = ""
104050-36 = ""
104050-37 = ""
104050-38 = ""
104050-39 = "...... ขอโทษด้วยนะคะ ท่านริโอะ "
104050-41 = "?!!"
104050-42 = "และถึงแม้มันจะเป็นแค่ช่วงเวลาสั้นๆ แต่ฉันก็รู้สึกเป็นเกียรติที่ได้ร่วมงานด้วยค่ะ หัวหน้าฮิมาริ"
104050-43 = "...... มะ... ไม่นะ...... "
104050-44 = "ถึงมันจะสายไปที่จะสารภาพ... แต่ที่จริงแล้ว... ฉัน..."
104050-45 = ".... อยากต่อสู้โดยที่อยู่ฝ่ายเดียวกับ <ชาเล่ต์> มาตลอดเลยค่ะ..."
104050-46 = "และก็... อยากอยู่กับพวกรุ่นพี่ C&C..."
104050-49 = "... ท่านริโอะ ช่วยบอกวิธีระเบิดตัวเองของ <อาบี เอชูห์> หน่อยสิคะ"
104050-50 = "... ว่าไงนะ?!"
104050-51 = "ท่านริโอะต้องเตรียมอะไรแบบนั้นไว้บ้างแล้วไม่ใช่เหรอคะ เตรียมเอาไว้เผื่อว่าฉันคิดจะหักหลังไงคะ"
104050-52 = ""
104050-54 = ""
104050-55 = "ถ้าฉันระเบิดตัวเอง ก็น่าจะทำลายหอคอยนี้ได้ค่ะ พลังงานของ <อาวุธ> ชิ้นนี้ต้องทำได้อยู่แล้ว"
104050-56 = ".... ไม่หรอก โทคิ มันไม่มีระเบิดอะไรแบบนั้นอยู่ตั้งแต่แรกแล้ว ฉันไม่คิดแบบนั้นกับเธอหรอก..."
104050-59 = "หรือมันเป็น <ปัญหารถราง> กันคะ... ระหว่างหนึ่งชีวิตของฉัน... กับการมีอยู่ของคิโวทอส คำตอบมัน#nแน่อยู่แล้วไม่ใช่เหรอคะว่าอันไหนสมเหตุสมผลกว่ากัน"
104050-60 = "ถ้าหากมีใครต้องดึงคันโยก... ก็ต้องเป็นท่านริโอะ..."
104050-61 = "ไม่หรอก โทคิ ไม่... คำถามนั้นน่ะ..."
104050-62 = "คำถามนั้น... มันอาจจะผิดตั้งแต่แรกแล้วก็ได้..."
104050-63 = "คะ......?"
104050-64 = "ถ้าหากเราขอความช่วยเหลือจากคนอื่นที่อยู่ใกล้ๆ ได้... ยะ... อย่างนั้นน่ะ... "
104050-65 = "......."
104050-67 = ".... ถ้ามีทางเลือกที่สะดวกแบบนั้นก็คงดีไม่น้อยเลยนะ..."
104050-69 = "แต่ว่า..."
104050-70 = ""
104050-73 = "พบเป้าหมาย จับเป้าหมายได้แล้ว"
104050-74 = ""
104050-78 = ".......?!!"
104050-79 = "นะ... นี่มัน......"
104050-80 = ""
104050-84 = ""
104050-90 = "พะ...... พวกรุ่นพี่?"
104050-91 = "ว่าไงจ๊ะ~ โทคิจัง~ พวกเรามาช่วยแล้ว!"
104050-92 = "C&C มาแล้วค่ะ โชคดีที่มาทันหวุดหวิดเลยนะคะ"
104050-93 = "ใช่ ดีแล้วละนะที่ยังทัน"
104050-94 = ""
104050-97 = "นี่ รุ่นน้อง"
104050-100 = "พูดอะไรแบบนั้นต่อหน้ารุ่นพี่ได้ยังไงน่ะ หา??"
104050-101 = "มะ... มาได้ยังไงกัน......"
104050-103 = "ฮู่ว ปลอดภัยดีใช่ไหมคะ? "
104050-104 = "นะ... โนอา...?! ทะ... ทำไมเธอถึงได้..."
104050-105 = "ไม่มีทางเป็นแบบนี้ไปได้... วะ... เว้นแต่จะล่วงรู้อนาคต..."
104050-106 = "อยากรู้ว่ามาทันได้ยังไงเหรอคะประธาน? อืม เราออกเดินทางก่อนที่สถานการณ์จะเป็นแบบนี้น่ะค่ะ โดยการนั่งเฮลิคอปเตอร์ที่เร็วที่สุดในมิลเลเนียมมา"
104050-107 = "มะ... หมายความว่ายังไง......? "
104050-109 = "ฉันไปขอร้องมาเองค่ะ"
104050-110 = "......!!"
104050-111 = "ถึงมันจะไม่ใช่ <ฝันบอกเหตุ> แต่มันก็เป็น <ความรู้สึก> ที่คล้ายๆ กันน่ะค่ะ......"
104050-112 = "ฉันรู้สึกว่าสถานการณ์จะเป็นแบบนี้ค่ะ ฉันคงอธิบายได้แค่นี้......"
104050-113 = "ถึงฉันจะก็ไม่ค่อยแน่ใจมากเท่าไร... แต่โชคดีที่โนอาจากเซมิน่าเชื่อคำพูดของฉัน..."
104050-114 = "ฮุฮุฮุ ไม่หรอกค่ะ ทุกคนต่างก็พยายามกันอยู่ ฉันก็แค่ทำในสิ่งที่ฉันทำได้เท่านั้นค่ะ"
104050-115 = "เห็นอย่างนี้ รอบตัวฉันก็มีรุ่นน้องที่มี <เซนส์> ดีอยู่เหมือนกันนะคะ และฉันก็มีลางสังหรณ์แบบนั้น#nเหมือนกัน"
104050-117 = "เอาละ C&C ทุกคน ช่วยพาคุณโทคิกลับมาอย่างปลอดภัยด้วยนะคะ"
104050-118 = ""
104050-120 = ""
104050-121 = "......."
104050-122 = "นั่นสินะคะ ประธานริโอะ "
104050-123 = "บางทีถ้ามันมีทางเลือกที่สะดวกแบบนี้ก็คงจะดีไม่น้อยเลยนะคะ โดยเฉพาะอย่างยิ่งกับคนที่ทุกข์#nทรมานจากการล่วงรู้อนาคต"
104050-124 = "......."
104050-125 = ""
104050-127 = ""
104050-129 = "เอาละ เรื่องนั้นเอาไว้คุยกันทีหลัง ตอนนี้เป็นเวลาทำความสะอาดกันแล้วละค่ะ"
104050-130 = "ใช่ เราต้องจัดการพวกที่ยังเหลืออยู่"
104050-131 = "ดีละ งั้นก็จัดหนักจัดเต็มกันเลย!"
104050-133 = "ได้เวลาลุยแล้ว!"
104050-135 = ""
104050-136 = "ตั้งสติไว้สิ! ประธาน!"
104050-137 = ""
104050-139 = ""
104050-140 = "ถ้าจะขอบคุณอะไรละก็ เอาไว้กลับไปถึงโรงเรียนอย่างปลอดภัยแล้วค่อยทำก็ได้! ตอนนี้ไม่ใช่เวลาที่#nจะมายืนตาลอยอยู่นะ!"
104050-141 = "...... ใช่ จริงสิ เข้าใจแล้ว ยูกะ"
104050-142 = "ให้ตายสิ ครั้งนี้รู้สึกเหมือนได้เห็นอีกด้านของประธานเลย หรือว่าปกติก็เป็นคนแบบนี้อยู่แล้ว......"
104050-143 = ""
104050-145 = ""
104050-146 = "ตายจริง ไม่รู้หรอกเหรอคะ? บิ๊กซิสเตอร์น่ะ ถึงภายนอกจะดูหยิ่งมาก แต่ข้างในเป็นเหมือนถังบำบัดน้ำ#nเสียเชียวนะคะ"
104050-147 = ""
104050-149 = ""
104050-150 = "ยิ่งไม่เข้าใจกว่าเดิมอีกนะ?"
104050-151 = ""
104050-153 = ""
104050-155 = ""
104050-156 = "งานทางนี้ก็เสร็จแล้วเหมือนกันค่ะ ฉันจะใช้หน่วยประมวลผลของอุตนาพิชทิม แล้วเปิด <วงจรระเบิดตัวเอง> ของเรืออะทราฮาซิสอีกครั้งค่ะ ทุกคนเตรียมตัวด้วยค่ะ"
104050-157 = "แต่ว่า ถ้างั้น... "
104050-158 = "ใช่ ถูกแล้ว ถ้าทำแบบนั้น เรือลำนี้ก็จะต้องถูกระเบิดไปพร้อมกับเรืออะทราฮาซิสที่นี่"
104050-159 = "งะ... งั้นพวกเราล่ะ......?"
104050-160 = "....... ฉันจะพาทุกคนกลับไปยังพื้นดินด้วย <วงจรหลบหนี> ที่ฉันสร้างขึ้นมา"
104050-162 = "ตอนต่อไป;เงื่อนไขที่เสมอภาค"
