[translation]
104090-1 = "ตอนที่ 9;บทส่งท้าย 1"
104090-6 = "สวัสดีค่ะ นักเรียนคิโวทอสทุกคน! คาวารุ ชิน่อนจากชมรมข่าวโครโนสค่ะ!"
104090-7 = "ตอนนี้ฉันมาอยู่ที่เขตชิราโทริ D.U. ที่อยู่ระหว่างการฟื้นฟูครั้งใหญ่ค่ะ และอาคารเหล่านั้นที่อยู่ด้านหลัง ก็คืออาคารที่กำลังได้รับการฟื้นฟูอยู่ค่ะ"
104090-8 = "ชิราโทริเป็นเขตที่ได้รับความเสียหายมากที่สุดในคิโวทอส เนื่องจากถูกใช้เป็นสนามในการต่อสู้#nระหว่างปีศาจกับหุ่นยนต์ขนาดมหึมาที่เพิ่งเกิดขึ้นค่ะ"
104090-9 = "แต่ผ่านไปไม่เท่าไรก็ได้รับการฟื้นฟูจนกลับมาชีวิตชีวาเหมือนเดิมแล้วค่ะ! สุดยอดไปเลยนะคะ! การเกิดใหม่ของเมืองก็คือการพัฒนาใหม่สินะคะ! "
104090-10 = "ทางด้านคุณโอคิ อาโออิ หัวหน้าฝ่ายการเงินจากองค์การนักเรียนก็ได้อนุมัติเงินอุดหนุนการฟื้นฟู#nฉุกเฉินพร้อมเน้นย้ำว่า \"ตอนนี้การฟื้นฟูเมืองเป็นสิ่งสำคัญที่สุด\" ค่ะ"
104090-11 = "ท่ามกลางเรื่องมติไม่ไว้วางใจของคุณนานากามิ รินที่ยังไม่จบ การเลือกตัดสินใจเช่นนี้ทำให้ได้รับคำ#nชื่นชมมากมายว่าการฟื้นฟูเมืองต้องมาก่อนการต่อสู้ทางการเมืองค่ะ แต่ว่า......"
104090-12 = "ก็ยังมีคำถามที่ว่า ใครจะเป็นคนรับผิดชอบราคาที่ดินและวัสดุก่อสร้างที่พุ่งสูงขึ้น! สุดท้ายแล้วใครจะ#nได้รับประโยชน์จากการพัฒนาเมืองใหม่! แล้วจะมีการทุจริตให้เห็นหรือไม่? "
104090-13 = "ต่อไปเราจะมาพูดในหัวข้อนี้อย่างลึกซึ้ง......"
104090-14 = "คะ? ขอให้เลิกพูดอะไรไร้สาระงั้นเหรอคะ? คุณเป็นเจ้าของที่ดินตรงนี้เหรอ? ฮะ? "
104090-15 = ""
104090-18 = "ขออภัยสำหรับการเผยแพร่ภาพที่ผิดพลาดค่ะคุณผู้ชม ช่วยรอสักครู่นะคะ"
104090-20 = "...... นี่ก็นานมากแล้วนะคะสำหรับเหตุการณ์นั้นที่เกิดขึ้นในคิโวทอส"
104090-21 = "หอคอยสีแดงปรากฏทั่วทั้งคิโวทอส ศัตรูที่เราไม่รู้จักกรูกันมาโจมตีเรา...... ถึงจะเกิดเรื่องใหญ่เป็น#nประวัติการณ์แบบนี้ แต่ก็ถือว่าชาวเมืองคิโวทอสดูจะเฉยๆ กันมากเลยนะคะ"
104090-22 = "ส่วนใหญ่จะคิดกันว่า เกิดเรื่องวุ่นวายขึ้นก็จริง แต่ <ชาเล่ต์> ก็แก้ไขสถานการณ์ทั้งหมดไว้ได้...... ประมาณนี้ค่ะ "
104090-23 = "แล้วก็มีบางส่วนที่คิดว่านี่เป็นการจัดฉากเพื่อประชาสัมพันธ์ <ชาเล่ต์> หรือไม่ก็เป็นการซ่อนกล้องที่#nมีการร่วมมือกับองค์การนักเรียนด้วยค่ะ "
104090-24 = "แถมใน D.U. ที่เป็นเขตที่ได้รับความเสียหายมากที่สุดก็มีผู้ได้รับบาดเจ็บน้อยมาก และไม่มีรายงานผู้#nเสียชีวิตเลย"
104090-25 = "การที่ความเสียหายมีเพียงเล็กน้อยเมื่อเทียบกับระดับความรุนแรงของเหตุการณ์แล้ว บางคนบอกว่า#nราวกับเป็นปาฏิหาริย์ แต่ก็ต้องยอมรับว่าชาวเมืองส่วนใหญ่ไม่ค่อยอินกับเหตุการณ์นี้เท่าไรค่ะ"
104090-26 = "ดูจากที่ไม่มีการขอความช่วยเหลือหรือการฟื้นฟูความเสียหายในเขตปกครองตนเองอื่นๆ แล้ว ดูเหมือนว่าในพื้นที่อื่นก็คงจะคล้ายๆ กันนะคะ"
104090-27 = "อ้อ มีการวิเคราะห์ออกมาด้วยค่ะว่าคนที่ได้รับความเสียหายมากที่สุดจากเหตุการณ์นี้คือ <องค์การนักเรียน> เพราะอาคารขององค์การนักเรียนและ <แซงค์ทัมทาวเวอร์> ถูกทำลายไปหมดเลยค่ะ!"
104090-28 = "ส่วนควบคุมการบริหารจัดการของคิโวทอสอย่าง <แซงค์ทัมทาวเวอร์> หายไป...... นี่มันเรื่องใหญ่เลย#nนะคะทุกคน! คิโวทอสจะถึงทางตันแล้วหรือเปล่าคะ? หรือว่าจะล่มสลายไปเลย?! "
104090-29 = "...... ผู้ชมบางท่านอาจตั้งคำถามเหมือนกันกับฉันนะคะ "
104090-30 = "เพราะความจริงแล้ว ตั้งแต่ประธานองค์การนักเรียนที่เป็นผู้บริหารสูงสุดหายตัวไป แซงค์ทัมทาวเวอร์ก็#nเป็นอาคารที่มีแต่ชื่อ แต่ไม่มีบทบาทนี่คะ? เพราะงั้นถึงมันจะหายไป ก็ไม่น่าจะมีอะไรเปลี่ยนแปลงมากนะคะ"
104090-31 = "ทางองค์การนักเรียนประเมินว่าเหตุการณ์นี้เป็นการบุกรุกคิโวทอสจากปรากฏการณ์ลึกลับ และไม่ได้อธิบายอะไรเพิ่มให้หายสงสัย...... "
104090-32 = "ส่วนทาง <ชาเล่ต์> ที่ถูกสงสัยว่ามีความเกี่ยวข้องอย่างลึกซึ้งกับเหตุการณ์นี้ "
104090-33 = "ก็ยังไม่ให้คำตอบใดๆ กับคำถามที่ว่า \"เป็นความจริงหรือไม่ที่มีคนบอกว่าเห็นคุณครูวิ่งเปลือยกายไป#nทั่วทุ่ง?\" ค่ะ!"
104090-34 = "ส่วนคำถามที่ว่า \"ถ้าคุณครูผันตัวมาเป็นนักธรรมชาตินิยมสุดโต่งที่ไม่ใส่เสื้อผ้าเลย แล้วทำไมถึงถือ#nโน้ตบุ๊กที่เป็นสิ่งของที่ไม่ได้มาจากธรรมชาติ?\" ก็มีคนตีความว่านี่เป็นการยืนยันการอยู่ร่วมกันของ#nธรรมชาติและอารยธรรมสมัยใหม่......"
104090-35 = "คะ......? อย่าแพร่ทฤษฎีสมคบคิดงั้นเหรอคะ? พูดอะไรกันคะ! นี่มันไม่ใช่ทฤษฎีสมคบคิดนะคะ แต่ว่ามันเป็น......"
104090-36 = ""
104090-39 = "ขออภัยสำหรับการเผยแพร่ภาพที่ผิดพลาดค่ะคุณผู้ชม ช่วยรอสักครู่นะคะ"
104090-40 = ""
104090-43 = "สรุปได้ว่านี่คือแผนการลับขั้นสูงที่สร้างปรากฏการณ์ให้คนแห่ทำตามกันค่ะ! เลิกปิดบังความจริง แล้วเปิดเผยตัวตนออกมาเถอะค่ะ <ชาเล่ต์>!!! "
104090-44 = ""
104090-47 = "ขออภัยสำหรับการเผยแพร่ภาพที่ผิดพลาดค่ะคุณผู้ชม ช่วยรอสักครู่นะคะ"
104090-49 = "...... ขณะนี้องค์การนักเรียนก็เลยอยู่ระหว่างการสร้างแซงค์ทัมทาวเวอร์ขึ้นใหม่ และออกมาประกาศว่า#nการก่อสร้างจะแล้วเสร็จในอีกไม่ช้าค่ะ"
104090-50 = "การสร้างแซงค์ทัมทาวเวอร์ขึ้นใหม่ตามพิมพ์เขียวเดิมของอาคารเดิมถือเป็นโปรเจกต์ใหญ่เลยค่ะ#nเนื่องด้วยความยากของขั้นตอนการทำงาน ทำให้มีข่าวลือว่าการก่อสร้างนี้เป็นการร่วมมือกับบริษัทก่อ#nสร้างเอกชนที่ชื่อ <ไคเซอร์ อินดัสทรี> ด้วยค่ะ"
104090-51 = "แถมยังมีการวิเคราะห์ว่าผู้ที่ได้รับประโยชน์มากที่สุดคือนักลงทุนรายใหญ่จากอุตสาหกรรมการก่อสร้าง#nที่เฟื่องฟูในตลาดอสังหาริมทรัพย์... ส่วนคนที่เดือดร้อนจากราคาสินค้าและอัตราดอกเบี้ยที่พุ่งสูงขึ้น..."
104090-52 = ""
104090-58 = "...... ชิ"
104090-59 = "....... ก็เลยกลายเป็นแบบนี้สินะ หัวหน้าสำนักป้องกัน"
104090-60 = "ถ้าไม่ได้ความช่วยเหลือจากพวกฉันละก็ เธอมีหวังโดนดูถูกยกใหญ่แล้ว"
104090-61 = "พวกคุณเองก็ด้วยไม่ใช่เหรอคะ? ถ้าไม่ได้ฉันช่วยไว้ ป่านนี้ไคเซอร์ก็คงกำลังเซ็นเอกสารล้มละลายกัน#nอยู่แล้วละค่ะ"
104090-62 = "ก็ได้... เอาเป็นว่าความร่วมมือของพวกเราจะยังคงอยู่เหมือนเดิมใช่มั้ย?"
104090-63 = "....... จะให้จับมือกับคนที่แทงข้างหลังกันงั้นเหรอ...... "
104090-64 = "ถ้าเป็นคนธรรมดา นี่คงเป็นเรื่องที่ทำไม่ได้อย่างเด็ดขาด......"
104090-66 = "แต่คนที่ทำในสิ่งที่คนธรรมดาไม่สามารถทำได้ ถือเป็น <ยอดคน> ใช่ไหมล่ะคะ?"
104090-67 = "โฮ้"
104090-68 = "ยอดคนต้องไม่เป็นเหมือนที่น่ารังเกียจแบบนั้นค่ะ ...เพราะงั้น ต่อไปก็ต้องรบกวนด้วยนะคะ นายพล"
104090-69 = "งั้นเหรอ...... หึหึหึ...... ยอดเยี่ยมไปเลยนะ สมแล้วที่เป็นคนที่ประธานใหญ่ยอมรับ"
104090-70 = "เพื่อความยุติธรรมแล้วละก็ ผู้ใหญ่ที่แท้จริงย่อมสามารถจับมือกับศัตรูในวันวานได้"
104090-71 = "ฉันไม่เหมือนกับพวกปัญญาอ่อนที่ถูกครอบงำได้ด้วยอารมณ์ความรู้สึกเล็กๆ น้อยๆ หรอกนะ "
104090-72 = "ก็ดี งั้นต่อไปก็ฝากด้วยละ หัวหน้าสำนักป้องกัน"
104090-74 = "......."
104090-75 = "......."
104090-79 = "อาริสึ พวกเรามาแล้ว"
104090-80 = "เอ๋? อาริสึจัง ทำอะไรอยู่เหรอ?"
104090-81 = "ต่อกันพลาเหรอ?"
104090-82 = ""
104090-84 = ""
104090-85 = "ไม่ใช่ค่ะ นี่ไม่ใช่กันพลา...... "
104090-86 = ""
104090-88 = ""
104090-90 = "หืม? แล้วมันอะไรเหรอ? หุ่นยนต์เหรอ.......?"
104090-91 = "...... ค่ะ นี่น่าจะเป็น...... <เคย์> ค่ะ"
104090-92 = "หะ... หืม?! เคย์งั้นเหรอ? "
104090-93 = "เด็กคนนั้น...... หายไปแล้วตั้งแต่ตอนนั้น......"
104090-94 = "...... ใช่ค่ะ ตอนนั้นเคย์หายตัวไป...... และหลังจากนั้นอาริสึก็ไม่ได้เจอเธออีกเลยค่ะ "
104090-95 = "แต่ตอนนั้น...... ตอนที่เคย์หายไป...... อาริสึรู้สึกว่าอาริสึเห็นหุ่นยนต์หน้าตาแบบนี้อยู่เดี๋ยวหนึ่งน่ะค่ะ"
104090-97 = "อาริสึก็เลยมาสร้างหุ่นแบบนี้ ก่อนที่ความทรงจำจะหายไปค่ะ"
104090-98 = "อืม......"
104090-99 = "อาริสึจัง......"
104090-100 = "สุดท้ายแล้ว... เคย์ก็ช่วยพวกเราเอาไว้ใช่ไหม? บะ... บางที... เคย์อาจจะได้เป็นสหายกับพวกเราก็ได้..."
104090-101 = "...... ใช่ค่ะ ถ้าได้เจอกันใหม่ครั้งหน้า...... อาริสึจะไปขอให้เคย์เป็นสหายของพวกเราค่ะ"
104090-102 = "......."
104090-103 = ""
104090-105 = ""
104090-108 = "เอ๋? สมัครแข่งขันออนไลน์งั้นเหรอ? "
104090-109 = ""
104090-112 = "...... หืม? นี่มันอะไรเนี่ย?"
104090-113 = "ทำไมเหรอพี่?"
104090-114 = "...... ในเมมโมรีมีไฟล์แบ็กอัปที่ไม่เคยเห็นมาก่อนน่ะสิ"
104090-115 = "มันมีอยู่แล้ว แต่พี่ลืมไปเองหรือเปล่า?"
104090-116 = "พูดอะไรของเธอ! ใครจะไปลืมไฟล์แบ็กอัปได้กันเล่า? แถมนี่เป็นชื่อที่เพิ่งเคยเห็นด้วย"
104090-117 = "ไหนดูซิ......"
104090-118 = ""
104090-120 = ""
104090-123 = "นะ... นี่... นี่มัน......?"
104090-124 = "อะไรเหรอ?"
104090-125 = ""
104090-127 = "Kei.sav"
104090-129 = "ข้อมูลแบ็กอัป...... <Kei>......? "
104090-130 = "คะ... เคย์เหรอ? อ่านว่าเคย์ใช่ไหม? "
104090-131 = ".........!!!"
104090-133 = "ระ... รีบไปหารุ่นพี่ฮิมาริกันเถอะ!!"
104090-134 = "ค่ะ!!"
104090-135 = ""
104090-139 = "ยินดีต้อนรับค่ะ ชมรมพัฒนาเกม"
104090-140 = "ว่าไง~"
104090-142 = "เอ๋? ธะ... เธอ?! ทำไมเธอถึงมาอยู่ที่นี่ได้ล่ะ?!"
104090-143 = "สมาชิกสังกัด C&C......?"
104090-144 = "คนของประธานริโอะ......?"
104090-145 = "...... ใช่ค่ะ ฉันคืออาซุมะ โทคิค่ะ พีซ- พีซ-"
104090-146 = ""
104090-148 = ""
104090-149 = "พะ... พีซ-?!"
104090-150 = "หะ... หืม......?"
104090-151 = "หัวหน้าฮิมาริสอนอะไรแปลกๆ ไว้น่ะ......"
104090-152 = "ไม่ใช่อะไรแปลกๆ ค่ะ มันเป็นคาแรกเตอร์ค่ะ เป็นกลยุทธ์ในการเจาะช่องว่างของฝ่ายตรงข้ามน่ะค่ะ"
104090-153 = "ก็นะ... ถ้าเจ้าตัวไม่คิดว่าแปลก ก็ไม่มีปัญหาอะไรหรอก......"
104090-154 = "ประธานริโอะยังคงปลีกวิเวกอยู่เหมือนเคย ฉันก็เลยกำลังหางานทำอยู่ค่ะ"
104090-155 = "โทคิก็เลยมาชะเง้อชะแง้หาอะไรทำอยู่น่ะ ต่อไปคงจะไปห้อง C&C สินะ"
104090-156 = "...... ไม่ค่ะ หลังจากนั้นฉันก็ไม่ได้เจอพวกรุ่นพี่เลยค่ะ ไม่รู้ว่ามีเรื่องอะไรยุ่งๆ กันอยู่หรือเปล่าค่ะ"
104090-157 = "เข้าใจแล้วค่ะ กำลังว่างงานสินะคะ ถ้าไม่ติดอะไร มาอยู่ปาร์ตี้เดียวกันกับพวกฉันไหมคะ?"
104090-159 = "ว่าไงนะ?!"
104090-160 = "อะ... อาริสึจัง......"
104090-161 = ""
104090-163 = ""
104090-164 = "ขอบคุณสำหรับข้อเสนอนะคะ...... แต่ตอนนี้ฉันมีภารกิจอื่นที่ต้องทำค่ะ"
104090-166 = "เอาไว้ถ้ามีโอกาสหน้า...... "
104090-167 = ""
104090-169 = ""
104090-171 = ""
104090-172 = "อุ๊ย? อาริสึเหรอ? "
104090-173 = "สวัสดีค่ะ รุ่นพี่ฮิมาริ "
104090-174 = "พวกเราอยากให้ช่วยดูอะไรให้หน่อยน่ะ!"
104090-175 = "อันนี้น่ะ..."
104090-176 = ""
104090-178 = ""
104090-179 = "เครื่องเล่นเกม......?"
104090-181 = "....... อืม งั้นสินะ"
104090-182 = "มันดูเป็นยังไงบ้าง?"
104090-183 = "คะ... คิดว่ามันมีส่วนเกี่ยวข้องกับเคย์ไหมคะ......?"
104090-184 = "....... "
104090-185 = "... นั่นสิคะ ฉันเองก็ไม่ได้เชี่ยวชาญในเทคโนโลยีของ <ทวยเทพไร้นาม> ก็เลยไม่แน่ใจเหมือนกันค่ะ"
104090-186 = "แต่หากเกิดข้อมูลแบบนี้โดยธรรมชาติละก็... มันคือสิ่งที่เรียกว่า <ปรากฏการณ์ลี้ลับ> อย่างแน่นอนค่ะ"
104090-187 = "แต่ว่า...... ถึงจะบอกว่านี่คือเคย์ แต่ถ้าอยู่ในสถานะนี้ก็คงพิสูจน์ไม่ได้หรอกค่ะ"
104090-188 = "งะ... งั้นเหรอคะ......?"
104090-189 = "ค่ะ ข้อมูลนี้มีขนาดแค่ 2KB เท่านั้น...... ต่อให้วิเคราะห์ในหน่วยบิต ฉันก็ไม่สามารถรู้ได้หรอกค่ะว่ามัน#nคืออะไรกันแน่"
104090-190 = "แต่หากผู้หญิงขี้ขลาดที่เป็นผู้เชี่ยวชาญในสาขานั้นกลับมาละก็......"
104090-191 = "....... ค่ะ อย่างนั้น... เหรอคะ... ยังรู้อะไรไม่ได้นี่เอง"
104090-193 = "อาริสึ...... อยากให้นี่คือเคย์ค่ะ...... เพราะถ้าเป็นอย่างนั้น...... ตอนนั้น......"
104090-194 = "อาริสึ......"
104090-195 = "อาริสึจัง......"
104090-196 = ""
104090-198 = ""
104090-200 = "ตายจริง...... นั่นมัน......?"
104090-201 = "อาริสึคิดถึงเคย์... ก็เลยทำสิ่งนี้ขึ้นมาค่ะ"
104090-202 = "อย่างนี้นี่เอง...... ฮืม ทำออกมาได้สวยเลยนะคะ อาริสึ"
104090-203 = "....... "
104090-204 = "ลองปรับแต่งหุ่นยนต์ตัวนี้ดูไหมคะ?"
104090-205 = "ปรับแต่ง...... เหรอคะ?"
104090-206 = "ถึงจะเรียกว่าปรับแต่ง แต่จริงๆ แล้วก็แค่เพิ่มหน่วยความจำ USB เข้าไปเท่านั้นน่ะค่ะ แต่ถ้าเพิ่มเข้าไป#nแล้ว..."
104090-207 = "....... อ้อ ใส่ข้อมูลของเคย์จังเข้าไปตรงนี้......"
104090-208 = "วะ... ว้าว! อัจฉริยะตัวแม่! อาริสึสร้างหุ่นยนต์นี้จากความทรงจำที่มีต่อเคย์พอดีเลย! แล้วถ้า......"
104090-209 = "เราใส่ข้อมูลนี้เข้าไป......"
104090-210 = "......!!"
104090-211 = "อืม ไม่ขอปฏิเสธค่ะว่าแฮ็กเกอร์สาวผู้มีรอยยิ้มสดใสก็เป็นอัจฉริยะตัวแม่เหมือนกัน แต่ถึงอย่างนั้น ฉันก็ไม่อาจทําให้เกิดเรื่องน่าอัศจรรย์ได้......"
104090-212 = "ฉันแค่... ช่วยทำให้ความปรารถนาของใครสักคนใกล้ความจริงเท่านั้นค่ะ"
104090-214 = "...... ค่ะ!!  เท่านี้ก็พอแล้วค่ะ!"
104090-215 = "ฮุฮุ ถ้างั้นก็วางใจได้เลยค่ะ เรื่องการปรับแต่งฉันถนัดอยู่แล้ว อย่าลืมสิคะว่าทุกคนกำลังอยู่กับอัจฉริยะ#nที่ไม่มีอะไรที่ทำไม่ได้อยู่นะคะ"
104090-216 = "โดยเฉพาะโครงร่างของโทคิที่อยู่ทางนั้น ฉันก็ช่วยปรับนิดแต่งหน่อยไว้เหมือนกันค่ะ พอดีรสนิยมของ#nเธอคนนั้นไม่ค่อยได้เรื่องเท่าไรน่ะ"
104090-217 = ""
104090-220 = "ไหนดูซิ...... ฉันซื้อหน่วยความจำใหม่มาพอดี..... อ้อ เดี๋ยวทำสายคล้องให้ด้วยค่ะ "
104090-223 = "เอาละ เสร็จแล้วค่ะ"
104090-224 = "......!!"
104090-225 = "ขอบคุณนะคะ รุ่นพี่ฮิมาริ "
104090-226 = "ดีเลยนะ อาริสึ"
104090-227 = "อื้ม อาริสึจัง...... แบบนี้ก็ดีเลยนะ"
104090-228 = "พกติดตัวไว้ดีๆ ล่ะ"
104090-230 = "ค่ะ!"
104090-231 = ""
104090-233 = ""
104090-235 = "ตอนต่อไป;บทส่งท้าย 2"
