[translation]
11005-2 = "สำเร็จแล้ว!!"
11005-3 = "ค่ะ"
11005-4 = "ชิงห้องชมรม <ชาเล่ต์> สำเร็จแล้ว ฉันกำลังไปจะไปถึงที่นั่นค่ะ แล้วเจอกันที่ชั้นใต้ดิน"
11005-11 = "ชั้นใต้ดิน อาคารชาเล่ต์"
11005-13 = "อืม... ไม่รู้เลยว่ามันคือของอะไร แบบนี้จะทำลายทิ้งเลยได้ไหมนะ..."
11005-14 = "เอ๋...?"
11005-15 = "[s1] เจอเข้ากับนักเรียนต้องสงสัย\n[s2] ทักทายอย่างยินดี"
11005-16 = "เอ๋???"
11005-17 = "เอ๋???"
11005-18 = "......"
11005-19 = "เอ่อ......"
11005-20 = "ขะ...."
11005-21 = "ขอโทษค่ะ!!"
11005-24 = "[s] \"...?\""
11005-26 = "ชั้นใต้ดิน อาคารชาเล่ต์"
11005-28 = "รอฉันนานไหมคะ? ฉันเพิ่งมาถึงค่ะ"
11005-29 = "เอ๋? มีเรื่องอะไรเกิดขึ้นเหรอคะ?"
11005-30 = "[s] \"ไม่มีอะไรนี่ ไม่มี\""
11005-31 = "แล้วไปค่ะ... ที่นี่มีของที่ประธานองค์การนักเรียนเก็บเอาไว้"
11005-32 = ""
11005-33 = "(พรึ่บ..)"
11005-34 = ""
11005-35 = "...... โชคดีที่คุณครูไม่เป็นอะไรนะคะ"
11005-36 = ""
11005-37 = ""
11005-38 = ""
11005-41 = "รับนี่ไปสิคะ"
11005-42 = "[s] \"แท็บเล็ต......?\""
11005-43 = "ใช่ค่ะ นี่เป็นของที่ประธานองค์การนักเรียนทิ้งเอาไว้ให้คุณครู#nมันเรียกว่า <กล่องแห่งซิสดิม> ค่ะ"
11005-44 = "[s] (เหมือนเคยได้ยินชื่อนี้มาก่อนเลย...)"
11005-45 = ""
11005-46 = "ถึงจะดูเหมือนแท็บเล็ตธรรมดาๆ แต่แท้จริงแล้วเป็นเครื่องที่เราไม่อาจรู้ได้ว่าคืออะไร#nเราไม่รู้ทั้งบริษัทผู้ผลิต, ระบบปฏิบัติการ, โครงสร้างระบบ หรือแม้แต่วิธีเปิดใช้งาน"
11005-47 = "ประธานองค์การนักเรียนบอกไว้ว่า <กล่องแห่งซิสดิม> นี้เป็นของคุณครู#nและด้วยสิ่งนี้ คุณครูจะฟื้นฟูอำนาจควบคุมของทาวเวอร์ได้ค่ะ"
11005-48 = "ถึงพวกเราจะไม่รู้วิธีเปิดใช้งาน แต่ถ้าเป็นคุณครูล่ะก็... อาจจะเปิดเครื่องนี้ได้ก็ได้"
11005-49 = "[s] \".........\""
11005-50 = "......"
11005-51 = "หมดหน้าที่ของฉันแล้วค่ะ จากนี้ชะตาของที่นี่ก็ขึ้นอยู่กับคุณครู..."
11005-52 = "ฉันจะออกไปอยู่ห่างๆ จะได้ไม่เป็นการรบกวนค่ะ"
11005-55 = "........"
11005-56 = "[ns] เปิด <กล่องแห่งซิสดิม>"
