[translation]
11090-2 = "ตอนที่ 9;สงครามเดือดล้างบุญคุณ"
11090-3 = "กลับกันดีๆ ล่ะ!"
11090-4 = "ขอให้กิจการราบรื่นดีนะคะ!"
11090-5 = "อะฮ่าฮ่า! พวกเธอก็สู้ๆ เหมือนกันนะ งานฟื้นฟูโรงเรียนคงไม่ง่ายเลย แล้วท่านอารุคนนี้จะเป็นกำลังใจให้เอง!"
11090-6 = "บ๊ายบาย!"
11090-9 = "เฮ้อ... เด็กพวกนั้นน่ารักดีนะเนี่ย พวกเธอคิดแบบนั้นไหม?"
11090-10 = "......"
11090-11 = "......"
11090-12 = "อารุ... ไม่รู้เหรอว่านั่นมันชุดนักเรียนของที่ไหน?"
11090-13 = "หืม? ไม่รู้สิ ของที่ไหนเหรอ?"
11090-14 = "นั่นมันนักเรียนอะบิดอสไม่ใช่เหรอ"
11090-15 = ""
11090-16 = "หะ... หา?!?! ว่ายังไงนะ?!??!!"
11090-18 = "อะฮ่าฮ่าฮ่า! ตลกชะมัดเลย!"
11090-19 = "ไม่รู้อะไรเลยจริงๆ ด้วย"
11090-20 = "เดี๋ยวนะ? แปลว่าพวกนั้นก็คือเป้าหมายของพวกเราน่ะสิคะ ให้ฉันกลับไปจัดการให้ไหมคะ?"
11090-21 = "อะฮ่าฮ่าฮ่า สายไปแล้วละ ยังไงอีกเดี๋ยวเราก็จะบุกเข้าไปอยู่แล้ว ไว้ตอนนั้นค่อยยืดเส้นยืดสายแล้วกันนะฮารุกะจัง"
11090-22 = "ระ... เรื่องจริงเหรอเนี่ย? พะ... พวกนั้นคือเด็กอะบิดอสงั้นเหรอ...?#nอ่า... ชะ... ชะ... โชคชะตาเล่นตลกอะไรกันอย่างนี้เนี่ย..."
11090-23 = "มัวทำอะไรอยู่เล่าอารุจัง? ได้เวลาไปทำงานกันแล้วสิ~?"
11090-24 = "พวกแรงงานรับจ้างรอคำสั่งของพวกเราอยู่นะ"
11090-25 = "ไม่จริงใช่ไหม... นี่เป้าหมายของเราคือพวกนั้นเหรอ..."
11090-26 = "อะฮ่าฮ่า อารุจังที่ใจดีของเราคงตัดสินใจลำบากแย่เลยนะ"
11090-27 = "ลืมไปแล้วเหรอว่าคติประจำหน่วยรับจ้างของเราคือ \"ไม่ผูกมัดด้วยความรัก แค่ให้เงินมา ปัญหาก็คลี่คลาย\"#nแล้วจะมัวลังเลอะไรอยู่ล่ะ?"
11090-28 = "มะ... มันก็จริงอยู่หรอก..."
11090-29 = "(รู้สึกสังหรณ์ใจไม่ดีแล้วแฮะ...)"
11090-30 = "มะ... ไม่ได้สิ ตั้งสติเดี๋ยวนี้นะอารุ! ใจอ่อนแบบนี้จะบริหารธุรกิจได้ยังไงกันเล่า!?"
11090-31 = ""
11090-32 = "ลุยเลย! เรียกรวมตัวแรงงานรับจ้าง!"
11090-34 = ""
11090-35 = ""
11090-36 = ""
11090-37 = ""
11090-38 = "อะไรกัน ทำไมถึงช้าอย่างนี้?"
11090-39 = "พอดีเจอเรื่องนิดหน่อยน่ะ เตรียมตัวพร้อมแล้วใช่ไหม?"
11090-40 = "แน่นอนอยู่แล้ว พวกเธอจะเจอเรื่องอะไรมาก็ไม่เกี่ยวกับพวกเรา ขอแค่พวกเราเลิกงานตรงเวลาก็พอ นี่พวกเราก็ลดค่าจ้างให้แล้วนะ"
11090-41 = "อย่ามัวคิดเล็กคิดน้อยเลยน่า เอาละ ตามฉันมา! ไปบุกโรงเรียนอะบิดอสเลย!"
11090-42 = ""
11090-43 = "ออกปฏิบัติการ~!"
11090-44 = "เฮ้อ..."
11090-45 = "ฉะ... ฉันจะพยายามให้เต็มที่ค่ะ ท่านอารุ!"
11090-46 = ""
11090-47 = "จะถล่มให้ไม่เหลือเศษซากเลยค่ะ!"
11090-49 = "ตรวจพบกองกำลังขนาดใหญ่ห่างจากทางทิศใต้ของโรงเรียนประมาณ 15 กม. ค่ะ!"
11090-50 = "อย่าบอกนะว่าพวกแก๊งหมวกกันน็อก?"
11090-51 = "ไม่ใช่ค่ะ... ไม่ใช่พวกแก๊งหมวกกันน็อกค่ะ!"
11090-52 = "พวกแรงงานรับจ้างค่ะ! พวกแรงงานรับจ้างพาร์ทไทม์ค่ะ!"
11090-53 = "เอ๋? สงสัยมีใครไปจ้างคนจากตลาดแรงงานเช้ามืดมาล่ะมั้ง? พวกนั้นไม่ใช่ถูกๆ เลยนะ"
11090-54 = "เราจะให้เข้ามาใกล้กว่านี้ไม่ได้นะคะ! คุณครูคะ ช่วยออกคำสั่งด้วยค่ะ-!"
11090-55 = "[s] \"ออกปฏิบัติการกันเถอะ\""
11090-57 = "พบสัญญาณของกลุ่มที่ออกคำสั่งแรงงานอยู่ในด้านหน้าค่ะ!"
11090-58 = "เอ๋... นั่นมันคนที่เจอในร้านราเม็งนี่นา..."
11090-59 = "อะ... อึก..."
11090-60 = "เป็นพวกเธอเองเรอะ!! อุตส่าห์ให้ราเม็งกินจนอิ่ม แต่มาบุกเราเนี่ยนะ?! พวกไม่รู้จักบุญคุณ!!"
11090-61 = "อะฮ่าฮ่าฮ่า! เมื่อกี้นี้ก็ขอบคุณอยู่หรอกนะ แต่งานก็คืองานยังไงล่ะ"
11090-62 = "เสียใจด้วยนะ แต่เราไม่เอาความรู้สึกมาผูกกับงานที่ได้รับมาหรอก แบบนั้นเค้าไม่เรียกว่ามืออาชีพ"
11090-63 = "... อย่างนี้นี่เอง กิจการที่ว่าคือหน่วยรับจ้างสารพัดสินะ"
11090-65 = "จริงๆ เลยนะคะ! ยังเป็นนักเรียนกันอยู่ก็หางานพาร์ทไทม์ที่มันดีๆ หน่อยสิคะ! ว่าแต่หน่วยรับจ้างสารพัดคืออะไรเหรอคะ?"
11090-66 = "มะ... ไม่ใช่งานพาร์ทไทม์นะ! มันคือกิจการที่ยิ่งใหญ่ต่างหาก! เรามีชื่อตำแหน่งกันด้วยนะ!"
11090-67 = "ฉันคือประธาน!"
11090-68 = "คนนั้นคือหัวหน้าฝ่าย"
11090-69 = "ส่วนนั่นก็หัวหน้าอีกคน..."
11090-70 = "เฮ้อ... ประธานอารุ ยิ่งพูดยิ่งดูไม่ดีนะ"
11090-71 = ""
11090-73 = "ใครอยู่เบื้องหลังเรื่องนี้? ไม่สิ... ถามไปก็คงจะไม่ยอมตอบสินะ"
11090-74 = "(แกรก) สงสัยต้องบังคับให้พูดแล้วละ"
11090-75 = "ฮุฮุฮุ เรื่องนั้นมันเป็นความลับทางธุรกิจนะ"
11090-76 = "ทุกคน! บุกได้!!"
