[translation]
11150-2 = "Episode 15;Riding off Into the Sunset!"
11150-3 = "Downtown"
11150-5 = ""
11150-6 = ""
11150-7 = ""
11150-8 = "Phew, we can take these off now, right? It's getting real stuffy."
11150-9 = "We need to keep moving. They're going to catch up to us soon."
11150-10 = "Hoshino's right. They're going to seal off more roads by the minute."
11150-11 = "Everything's been planned and accounted for, so no worries! ☆"
11150-12 = "This way. Hurry."
11150-13 = "Hey, Shiroko...why are you still wearing that? Isn't it hot?"
11150-14 = "She probably doesn't want to take it off because it's helped her discover her true calling. It's like a piece of her soul now, probably."
11150-15 = "Thank goodness Shiroko ended up at Abydos. I bet she would have become a criminal mastermind if she had gone to a different school."
11150-16 = ""
11150-17 = ""
11150-18 = "I don't know about that..."
11150-20 = "...?!"
11150-21 = ""
11150-22 = ""
11150-23 = "..."
11150-25 = "You're through the barricade. You should be safe now."
11150-26 = "Nice! We did it!"
11150-27 = "*sigh* I can't believe you all really pulled a heist on a Black Market bank..."
11150-28 = "Shiroko. You have the transport logs, right?"
11150-29 = "Umm... It's in the bag."
11150-30 = ""
11150-31 = "*click*"
11150-32 = "Huh? What is all this stuff...? Are these bundles of cash?!"
11150-33 = "WH-WHAT?! Shiroko, you went after the cash instead?!"
11150-34 = "No... I asked for the logs, just like we planned. That bank employee is the one who got the wrong idea and gave us this cash."
11150-35 = "Let's see... There's at least 100 million yen in there, from the looks of it.#nWow, we really did rob them of 100 million in five minutes!"
11150-36 = "Nice going! What are you all staring at each other for? Let's take it! "
11150-37 = "..."
11150-38 = ""
11150-39 = "W-Wait a second! You're intending to keep that money?!"
11150-40 = "What's wrong, Ayane? This is our chance to settle the debt."
11150-41 = "But then we really would be nothing but criminals, Serika!"
11150-42 = "We're the ones who shed blood, sweat, and tears to earn this cash in the first place! It was that evil bank who decided to funnel it away into crime!"
11150-43 = "This money would have funded more weapons, ammo, and who knows what else for the real bad guys! Fine, we stole from some criminals. So what? Where's the harm there?!"
11150-44 = "..."
11150-45 = "I agree with Serika. This would've just funded more crime anyway.#nWhatever we do with it, we'll put it to far better use."
11150-46 = "See? Told you! And this will help with Abydos High School's debts for sure!"
11150-47 = "Hmm. That's true... What do you think, Shiroko?"
11150-48 = "You're going to say no anyway, so there's no point in discussing this."
11150-49 = "What?!"
11150-50 = "I can always count on you to know what I'm thinking, Shiroko."
11150-51 = "What we need are those documents! Not the cash."
11150-52 = "If we cross this line today because it's us versus criminals, what about the next time? Or the time after that?"
11150-53 = "..."
11150-54 = "If we start getting desensitized to that sort of thinking, soon we won't see any line at all."
11150-55 = "..."
11150-56 = "Then there'll come a huge crisis one day, and we're gonna end up doing something we really shouldn't, while making excuses that we had no choice."
11150-57 = "I wouldn't want my adorable underclassmen to end up like that."
11150-58 = "And what's the point of protecting the school if that's how we go about it?"
11150-59 = "..."
11150-60 = "We could've just used Nonomi's gold card to pay off the debt if this is the way we were going to go about things."
11150-61 = "Well, I did offer that as a solution, but you were against it..."
11150-62 = "I mean, I understand. If we use illegitimate means to pay off Abydos' debt, we'll just be paying it off in exchange for being beholden to something else..."
11150-63 = "Heh. Something like that."
11150-64 = "So, that's why we're leaving the bag behind. Only take the documents. President's orders."
11150-65 = ""
11150-67 = "Argh! You have to be kidding me! You want us to just dump all this cash?!#nOf all the times to take a stand, this is when you do it?!"
11150-68 = "You heard her. President's orders."
11150-69 = "I can't pretend to fully understand what it's like to be in Abydos' situation...#nbut I do know that taking this cash will only lead to an even bigger mess."
11150-70 = "I think you would regret it in the long run."
11150-71 = "Now that doesn't leave us with much of a choice, does it?#nI'll just get rid of this bag somewhere discreet."
11150-72 = "Much appreciated."
11150-73 = "Hang on! Someone is headed your way!"
11150-74 = "Are the Market Guards after us?!"
11150-75 = "No, it doesn't look like it. Whoever it is, they don't seem hostile."
11150-76 = ""
11150-77 = "Hang on a second. I know this reading. Is that...?"
11150-78 = "I-It's Aru from Problem Solver 68!"
11150-81 = "*pant* *pant* H-Hold up a second!"
11150-82 = "*puts mask back on*"
11150-83 = ""
11150-84 = "Hold on a second! I'm not here to pick a fight."
11150-85 = "(What is SHE doing here?)"
11150-86 = "(Should we attack?)"
11150-87 = "(Not sure. It doesn't look like she's going to make the first move.)"
11150-88 = "(You all know this girl?)"
11150-89 = "(Heh. We go way back.)"
11150-90 = "So, um... I just wanted to say..."
11150-91 = "I watched you hit that bank. I can't believe you robbed a Black Market bank and got away with it in five minutes flat! Outlaws like you guys come only once in a generation. "
11150-92 = "...?!"
11150-93 = "To be honest, it left a huge impression on me. That kind of bravado is a rarity these days. Let's just say I was inspired."
11150-94 = "I-I'm gonna keep working hard, and someday, I'm gonna become an outlaw just like you! A truly free spirit unrestricted by any rules or laws!"
11150-95 = "(What the heck is she going on about...?)"
11150-96 = "S-So please...! At least tell me your name!"
11150-97 = "Name...?"
11150-98 = "Like, what's the name of your group? Or is it a faction, or a club? It doesn't have to be your real names...but I want to know who it is I'm looking up to!"
11150-99 = "(Uh, I think she's got the wrong idea about this...)"
11150-100 = "Oh, now I get it! We'd be happy to tell you!"
11150-101 = "(N-Nonomi?!)"
11150-102 = "We are...the Masked Swimsuit Gang! "
11150-103 = "You said...\"the Masked Swimsuit Gang\"?! "
11150-104 = "That name is so...so...BADASS! I love it!"
11150-105 = "(...)"
11150-106 = "We're supposed to wear swimsuits along with our masks, but#nwe were in such a rush that we only brought our masks with us. "
11150-107 = "(Now she's just making stuff up.)"
11150-108 = "That's right! We're pop idol superstars by day, and swashbuckling vigilantes of justice who fight bad guys by night!"
11150-109 = "I'm Christina! ♧"
11150-110 = "Wow! You even have a gimmick and everything?!"
11150-111 = "Bwahaha! An eye for an eye, a tooth for a tooth! Forsake mercy and walk the path of chaos! That's our motto."
11150-112 = "H-Holy smokes!"
11150-114 = "What kind of joke did we just walk in on?"
11150-115 = "Wow, Aru is totally enraptured! She looks like a kid on a film set!"
11150-117 = ""
11150-118 = "(That ought to be enough, right? Let's start looking for a way out!)"
11150-119 = "All righty, then. Adios! ☆"
11150-120 = "Now, time for us to ride off into the sunset!"
11150-121 = "But it's still the middle of the afternoon..."
11150-122 = "*bolt*"
11150-123 = "..."
11150-124 = "The path of chaos it is! I'm gonna burn that motto into the depths of my soul!"
11150-125 = ""
11150-126 = ""
11150-127 = "..."
11150-128 = "..."
11150-129 = "(We ought to say something to her, but I don't know when or how...)"
11150-130 = "(Leave her be. It'll be funnier this way.)"
11150-131 = ""
11150-133 = "Hey, um..."
11150-134 = "What should we do with this bag? I think those guys left it behind..."
11150-135 = "What? You don't think...the Masked Swimsuit Gang left this here as a gift for me, do you?"
11150-136 = "Uh, no. I don't think so... They probably just forgot about it."
11150-137 = "It feels pretty hefty. I wonder what's inside."
11150-138 = "*click*"
11150-139 = "...!"
11150-140 = "No. Way."
11150-141 = "Isn't...this...?!"
11150-143 = "Uh-oh. I think I forgot to pick up the cash bag."
11150-144 = "What?!"
11150-145 = "We were going to throw it away anyway. Just forget about it."
11150-146 = "Oh, well. I'm sure it'll end up with someone who needs it."
11150-147 = "I hope so too! I hope it goes to someone who could really use the money."
11150-148 = "Maybe we should think about it as a good deed for the day, then. I'd like to think someone who could really use that money found it."
11150-149 = "I think I'm going to be sick to my stomach. Gah! I can't believe this!"
11150-151 = "Huh?!"
11150-152 = "Whaaa?!"
11150-153 = "Now what?"
11150-154 = ""
11150-156 = "So...?"
11150-157 = "Does this mean we won't go to bed on an empty stomach anymore?"
11150-159 = "Back at Problem Solver 68's office..."
11150-160 = "Whaaat?!"
11150-161 = "The Masked Swimsuit Gang was actually those girls from Abydos?!"
11150-162 = "Hahaha! Aru, you look like you just found out Santa Claus doesn't exist!"
11150-163 = "*sigh*"
11150-164 = "The truth finally dawned on Aru."
11150-166 = "Next Episode;The Truth Revealed"
