[translation]
11150-2 = "第15話;朝著夕陽出發吧！"
11150-3 = "市區"
11150-5 = ""
11150-6 = ""
11150-7 = ""
11150-8 = "噗哈，好難呼吸。#n現在可以脫掉了吧？"
11150-9 = "沒時間悠閒了唷～#n快點快點，追兵很快就會追上來的～"
11150-10 = "得盡快離開才行……道路應該馬上就要被封鎖了……"
11150-11 = "不必擔心。已經做好萬全的準備了☆"
11150-12 = "往這邊。動作快。"
11150-13 = "那個，白子前輩……不把面罩脫掉嗎？不礙事嗎？"
11150-14 = "就像感受到了天職或是靈魂的一部份，所以不想脫下來了嗎？"
11150-15 = "幸好白子前輩是在阿拜多斯……#n如果去其他學校的話，一定會闖下不得了的大事……"
11150-16 = ""
11150-17 = ""
11150-18 = "是，是嗎……"
11150-20 = "……！？"
11150-21 = ""
11150-22 = ""
11150-23 = "……"
11150-25 = "已突破封鎖，從這裡開始就算是安全區域了。"
11150-26 = "好耶！大成功！"
11150-27 = "居然真的搶了黑市的暗黑銀行……呼……"
11150-28 = "白子醬，有好好把款項紀錄的文件帶著吧？ "
11150-29 = "嗯，嗯……在背包裡。"
11150-30 = ""
11150-31 = "（喀嚓）"
11150-32 = "……咦？這是什麼！？#n背包裡……有一大疊鈔票……！？"
11150-33 = "咦咦咦咦咦！？白子前輩搶了現金嗎！？"
11150-34 = "不，不是……目標文件確實到手了。 #n這筆錢是銀行職員自己誤會後放進去的……"
11150-35 = "我看看……唔嘿，差不多有一億左右。#n居然真的在五分鐘之內就賺了一億呢。"
11150-36 = "太好了！！還在看什麼！趕快帶回去吧！"
11150-37 = "……"
11150-38 = ""
11150-39 = "請，請等一下！真的要用那筆錢嗎！？ "
11150-40 = "怎麼了嗎綾音醬？我們必須還債呀！"
11150-41 = "要是那麼做的話……就真的是犯罪了哦，茜香醬！"
11150-42 = "犯，犯罪又怎樣！？這些本來就是我們的血汗錢！#n結果都流入那個暗黑銀行裡了啊！"
11150-43 = "而且要是坐視不管的話，這些不就會變成罪犯的武器或彈藥了嗎！#n搶罪犯的錢有什麼錯！？"
11150-44 = "……"
11150-45 = "我同意茜香醬的意見。#n與其成為罪犯的資金，由我們用在更好的地方比較好。"
11150-46 = "看吧！有這筆錢的話，就能減少很多學校的債務哦！？"
11150-47 = "哼嗯……是那樣沒錯……白子醬怎麼看？"
11150-48 = "……星野前輩一定會反對吧。#n我沒有必要發表意見。"
11150-49 = "咦！？"
11150-50 = "不愧是白子醬，很了解我呢～"
11150-51 = "咱們需要的是那些資料，而不是錢。 "
11150-52 = "現在因為是惡人的犯罪資金所以當作沒關係，那下次呢？下下次呢？"
11150-53 = "……"
11150-54 = "一旦咱們習慣這種方式……之後就會變成完全不在乎。"
11150-55 = "……"
11150-56 = "這樣要是咱們哪天又遇到危急的情況……#n八成會以「別無選擇」為藉口，做出不該做的行為吧。"
11150-57 = "唔嘿～大叔我才不想看到可愛的後輩們變成那樣呢～"
11150-58 = "就算能用那種方式守住學校，又有什麼意義呢。"
11150-59 = "……"
11150-60 = "要依賴這種方法的話，#n還不如乾脆一開始就依賴野乃美醬，用他燦爛輝煌的金卡把債還清。"
11150-61 = "……我也提出了同樣的意見，不過被星野前輩反對了……"
11150-62 = "我能理解前輩的想法。如果我們不用正當的方法努力……#n即使還清了債務，阿拜多斯也將不再是原本的阿拜多斯……"
11150-63 = "唔嘿，就是那樣。"
11150-64 = "所以這個背包就留在這裡吧。咱們只拿需要的文件就好了。#n這是委員長的命令哦。"
11150-65 = ""
11150-67 = "啊啊啊！！好煩躁！真搞不懂！#n居然把這麼大筆錢丟掉！？為什麼在這種奇怪的地方這麼認真啊！！"
11150-68 = "嗯，如果這是委員長的命令……"
11150-69 = "雖然我不了解阿拜多斯的情況……#n如果拿著這筆錢，說不定會被捲入其他是非。"
11150-70 = "從某個角度來看，就像是災難的種子一樣……"
11150-71 = "哈哈……那就沒辦法了呢。這個背包我會好好處理掉的。"
11150-72 = "嗯，那就拜託你囉～"
11150-73 = "……！！請等一下！有人正朝這邊接近！"
11150-74 = "……！！是黑市守衛的追兵嗎！？"
11150-75 = "……不。對方似乎沒有敵意。"
11150-76 = ""
11150-77 = "我看看……那是……"
11150-78 = "便，便利屋的亞瑠同學！？"
11150-81 = "哈啊，呼……等，等等！！"
11150-82 = "……！！"
11150-83 = ""
11150-84 = "啊，冷靜下來。我不是敵人……"
11150-85 = "（那傢伙為什麼……？）"
11150-86 = "（要攻擊嗎？）"
11150-87 = "（該怎麼辦呢。攻擊沒有敵意的人好像也不太好……）"
11150-88 = "（是認識的人嗎……？）"
11150-89 = "（唔嘿～算是吧～）"
11150-90 = "那，那個……其，其實也沒什麼重要的事……"
11150-91 = "你們搶銀行的過程我都看到了……居然只花五分鐘就將黑市的銀行洗劫一空，#n而且還能夠從容不迫地脫身……你們真是少見的法外之徒。"
11150-92 = "……！？"
11150-93 = "老實說真的讓我印象深刻。#n沒想到這個時代還有那麼大膽的人……真的很感動。"
11150-94 = "我，我也會努力的！成為不被法律及規則束縛，真正自由的靈魂！#n我想成為那樣的法外之徒！"
11150-95 = "（到底……在說什麼？）"
11150-96 = "所，所以……請，請告訴我你們的名字！！"
11150-97 = "名字……！？"
11150-98 = "那個，還是該說是組織？應該有團隊名稱之類的吧？#n就算不是正式名稱也沒關係……我希望把你們今天的英姿刻在內心深處！！"
11150-99 = "（唔嘿……好像被大大地誤會了呢……）"
11150-100 = "……沒問題！#n你的意思，我完～全明白了！"
11150-101 = "（野，野乃美前輩！？）"
11150-102 = "我們是……泳裝蒙面團！"
11150-103 = "……泳裝蒙面團！？"
11150-104 = "糟，糟糕……！！超酷的！！也太酷了吧！！"
11150-105 = "（……）"
11150-106 = "唔嘿～原本的正式服裝是校園泳衣加上面罩。#n今天是因為情況緊急，所以只戴了面罩而已哦～"
11150-107 = "（在做什麼奇怪的設定！？）"
11150-108 = "沒錯！平時作為偶像活動，一到晚上就會化身為打擊罪惡的正義怪盜！"
11150-109 = "然後我是克莉斯緹娜喲～♧ "
11150-110 = "「喲，喲～♧」……！？#n連，連人設都建立了……！？"
11150-111 = "唔嘿，以眼還眼，以牙還牙。#n不管人情世故，孤高地走在眾人所畏懼的魔境──這就是我們的座右銘！！"
11150-112 = "你，你說什麼──！！"
11150-114 = "……那些孩子在做什麼啊……"
11150-115 = "哇，亞瑠醬完全著迷了。#n表情跟去觀賞特攝片活動的小朋友一樣！"
11150-117 = ""
11150-118 = "（已經可以了吧？該逃走了唷！）"
11150-119 = "那麼就先告辭了。Adios～☆"
11150-120 = "走吧！奔向夕陽！"
11150-121 = "夕陽，還有點早就是了……"
11150-122 = "（唦唦──）"
11150-123 = "…… "
11150-124 = "好！孤高地走在眾人所畏懼的魔境……那句銘言，會永遠刻在我的靈魂！#n我也會加油的！"
11150-125 = ""
11150-126 = ""
11150-127 = "……"
11150-128 = "……"
11150-129 = "（得告訴他事實才行……不過該挑什麼時候說呢？）"
11150-130 = "（反正挺有趣的，暫時先這樣吧）"
11150-131 = ""
11150-133 = "那，那個……"
11150-134 = "這個背包該怎麼辦？#n好像是那些人忘了帶走的……"
11150-135 = "嗯？這難道是……泳裝蒙面團留給我的禮物……？"
11150-136 = "不，這不太可能……只是忘記拿而已吧？"
11150-137 = "還挺重的耶？裡面會是什麼呢。"
11150-138 = "（噠嚓）"
11150-139 = "……！！"
11150-140 = "咦咦咦！？"
11150-141 = "！！這，這是……！！"
11150-143 = "啊……裝現金的背包……忘在那邊了。"
11150-144 = "咦──！？"
11150-145 = "唔嘿～也不錯吧？#n反正本來就是要丟掉的東西～別在意別在意。"
11150-146 = "嗯。肯定會被誰撿走吧。"
11150-147 = "說得也是☆如果是被有經濟困難的人撿走就好了呢。"
11150-148 = "啊哈哈……就當是在做好事吧。#n想像那筆錢能讓餓到沒錢吃飯的人飽餐一頓……"
11150-149 = "嗚嗚……真浪費……不管怎麼想都覺得好浪費！！#n真是的，大家都是濫好人！！"
11150-151 = "咦咦咦咦──！？"
11150-152 = "哇哇哇──！？"
11150-153 = "這是……"
11150-154 = ""
11150-156 = "……？"
11150-157 = "……這樣我們是不是不用再餓肚子了？"
11150-159 = "（便利屋辦公室）"
11150-160 = "什什什什麼麼麼麼──！？！？"
11150-161 = "泳裝蒙面團竟然就是阿拜多斯的人！！？？"
11150-162 = "啊哈哈哈～亞瑠醬超受打擊！笑死！"
11150-163 = "唉……"
11150-164 = "（結果還是跟亞瑠說了）"
11150-166 = "下一話;真相大白"
