[translation]
11234040-1 = "#Y-03"
11234040-2 = ""
11234040-3 = "อืม... วันนี้เนือยๆ ยังไงไม่รู้ หรือว่าฉันจะน้ำตาลตกนะ?"
11234040-4 = "ถ้าได้กินอะไรหวานๆ บางทีหัวอาจจะแล่นก็ได้..."
11234040-5 = "เป็นข้ออ้างรึเปล่า วันนี้เธอกินไปตั้งเยอะแล้วนะ กระเพาะเธอเป็นหลุมดำรึไง"
11234040-6 = "ฮ่าฮ่า! เด็กกำลังโตน่ะ~ เด็กกำลังโต~"
11234040-7 = "ย้ากกกก!!"
11234040-8 = "ยะ... โยชิมิจัง...! จะ... ใจเย็นก่อนนะ...!!"
11234040-9 = "หนีเร็วเข้า~"
