[translation]
11334020-1 = "#st;[-948,432];smooth;100;#Y-02\n#all;hide"
11334020-2 = "3;요시미 밴드;07\n#wait;1000\n#clearST"
11334020-3 = "3;요시미 밴드;07;그러고 보니 인터넷에서 기타 치는 법을 찾아봤는데, <이빨 기타>라든가 이상한 것들이 많더라고.\n#3;em;[반응]"
11334020-4 = "3;아이리 밴드;07;요, 요시미 쨩……? 그, 그거…… 하려고……?\n#3;em;[땀]"
11334020-5 = "3;요시미 밴드;04;……? 그럴 리가 없잖아, 나츠도 아니고. 그냥 신기해서 이야기한 것뿐이야.\n#3;stiff\n#3;em;[?]"
11334020-7 = "4;카즈사 밴드;01\n2;나츠 밴드;05;나 그런 사람 아니라고 했다.\n#2;em;[반응]"
11334020-8 = "4;카즈사 밴드;02;아니었구나……."
11334020-9 = "2;나츠 밴드;05;………….\n#2;em;…"
