[translation]
1202-1 = "Maid & Dismayed Part 1"
1202-5 = "...Hello? Anyone here?"
1202-6 = "Can I come in?"
1202-7 = ""
1202-10 = "Please do. The door is open."
1202-11 = "Hello! Thanks for having me."
1202-12 = ""
1202-15 = ""
1202-17 = "C&C Club Room and Lecture Hall"
1202-19 = ""
1202-20 = "Oh, you're actually here. Thank goodness!"
1202-21 = ""
1202-23 = ""
1202-24 = "*gasp*"
1202-25 = "Hey! Why does everyone react like that? A little welcome wouldn't hurt."
1202-26 = "My apologies. That wasn't my intention."
1202-27 = ""
1202-29 = ""
1202-30 = "Oh my, is that Yuuka?"
1202-31 = "What brings you here today?"
1202-32 = "Do you have a commission for us?"
1202-33 = "I'm afraid I can't accept, since the president is out... If you'd like, I can take down a memo?"
1202-34 = "No, it's okay. It's not exactly a commission."
1202-35 = "Or... maybe it is?"
1202-36 = "I have something a little different to ask."
1202-37 = "Something... different? What do you mean?"
1202-38 = "Well, I mean, it's... actually completely different."
1202-39 = "It's a commission of a sort, but not exactly a mission."
1202-40 = "That...did not clarify anything."
1202-41 = "Oh! Was that a joke? A commission, but not a mission..."
1202-42 = "Heehee. Clever!"
1202-43 = "A-hem. Anyway, it's not a big deal, but..."
1202-44 = "I'm sure you've seen the preparations for the festival happening in the shopping district."
1202-45 = "Yes, of course. In the electronics market."
1202-46 = "I've already seen signs up for themed student cafes."
1202-47 = "Everyone's come up with all sorts of themes to raise money for the festival."
1202-48 = "But, well... There's a problem."
1202-49 = "A problem?"
1202-50 = "Yes... *sigh*"
1202-51 = "The problem is, the students are all from Millennium, so..."
1202-52 = "All of the themes are a bit..."
1202-53 = "Hahaha! I think I know what you're getting at."
1202-54 = "It's all things like \"Bytes and Bites\" or \"Chemistry Lab Cafe\"... All the customers will be scared away."
1202-55 = "*sigh* What's wrong with us? Hyakkiyako and Trinity always say their festivals raise tons of money."
1202-56 = "But, anyway, the shopping district asked the Seminar to do something about it."
1202-57 = "I don't know why it's the Seminar's problem, but... The electronics market is a part of Millennium's district, I guess."
1202-58 = "Hahaha... I see the problem..."
1202-59 = "But, I'm afraid I don't see what it has to do with us."
1202-60 = "...Yes. That."
1202-61 = "Oh, by the way, have I mentioned lately..."
1202-62 = ""
1202-64 = ""
1202-65 = ""
1202-66 = ""
1202-68 = ""
1202-70 = "...how wonderful the maids of C&C are?"
1202-71 = ""
1202-74 = ""
1202-75 = "Where in the world did that come from?"
1202-76 = "A compliment from you is...a bit scary."
1202-77 = "I know it's a disguise, but you are still maids, right?"
1202-78 = "I mean, you've got the outfits and everything."
1202-79 = "And I've heard you all have lots of experience infiltrating maid cafes."
1202-80 = "Yes... I suppose you're right..."
1202-81 = "We have done that a few times..."
1202-82 = "It would be just this once... And, by the way, if you agree, we'll be totally even for everything. You won't owe me anything."
1202-83 = ""
1202-85 = ""
1202-87 = "So... Maybe you can work at a maid cafe...? Just for a week?"
1202-89 = "(One hour later...)"
1202-92 = ""
1202-93 = ""
1202-94 = "What. The. Heck?! What are you talking about?"
1202-95 = "A maid cafe? Have you lost your mind? No, no, no! I can't believe you'd ask me that!"
1202-96 = "Why does everyone think that just because we're wearing maid uniforms, it magically makes us real maids?"
1202-97 = "Well... Usually people wearing maid uniforms ARE maids."
1202-98 = "This is perfect, actually."
1202-99 = "With this, our cover will be airtight. Everyone will know us as maids."
1202-100 = "Stop it. No. Absolutely not!"
1202-101 = "Over my dead body. You hear me? Never!"
1202-102 = "Um... But... The thing is... We already..."
1202-103 = "...?!"
1202-104 = "What? You already what? Spit it out!"
1202-105 = "We already agreed."
1202-106 = "Seminar even allocated a budget for the project, so I don't believe we'll be able to back out."
1202-107 = "We even signed a contract. If we cancel, we'll be fined."
1202-108 = ""
1202-110 = ""
1202-111 = "...Excuse me?"
1202-112 = "What did you say? A contract? You're joking, right? Tell me you're joking!"
1202-113 = "Hang on, hang on. That doesn't even make sense. We signed a contract?"
1202-114 = "Last I checked I was the president, and I didn't sign anything. So how is that possible? Who signed?"
1202-115 = "Oh, that? I did!"
1202-116 = ""
1202-118 = ""
1202-119 = ""
1202-120 = "..."
1202-121 = "..."
1202-122 = "Huh...? What's wrong?"
1202-123 = "Why are you looking at me like that?"
1202-124 = ""
1202-127 = "..."
1202-128 = "Oh... Ohhh..."
1202-129 = "...So you see now what happened."
1202-130 = "Asuna is supposed to make decisions when you're absent, remember?"
1202-131 = "Shut up... I get it... Please, just...stop..."
1202-132 = "Huh? Are you mad at me?"
1202-133 = "Should I not have...?"
1202-134 = "I just thought it sounded like fun! And, if it goes well, they'll even pay us! Wouldn't that be nice?"
1202-135 = ""
1202-137 = ""
1202-139 = "Argh! I won't do it! No!"
1202-140 = "This is...this is fun to you!?"
1202-141 = "Yes! Lots of fun, I think!"
1202-142 = ""
1202-144 = ""
1202-145 = ""
1202-147 = "There's no point arguing. Do you see how excited Asuna is? We have no choice."
1202-148 = "Don't you think it would be better to start planning, anyway?"
1202-149 = ""
1202-152 = ""
1202-153 = "What..."
1202-154 = "What did I do to deserve this...?"
