[translation]
12030-1 = "ตอนที่ 3;บอกลาหน่วยรับจ้างสารพัด 68"
12030-2 = "สำนักงานหน่วยรับจ้างสารพัด 68"
12030-3 = "เฮ้อ..."
12030-4 = "อารุจัง~ มัวยืนถอนหายใจอยู่ตรงนั้นทำไม มาช่วยกันย้ายของเร็วสิ\n\n"
12030-5 = "เฮ้อออ....."
12030-6 = ""
12030-7 = "ให้เอาอันนี้ไว้ไหนเหรอคะ?"
12030-8 = "หมายถึงงานเขียนลายมือที่หาดูยากของอารุจังใช่ไหม? เอาไปรวมกับขยะตรงนั้นเลย"
12030-11 = "จะบ้าเหรอ? ทิ้งไม่ได้นะ! ต้องเอาไปด้วยสิ! \n"
12030-12 = "แต่นั่นเขียนเป็นการบ้านในชั่วโมงคัดลายมือนี่นา ไหนดูซิ \"ร้ายวันละครั้ง\" มีสำนวนแบบนี้ด้วยเหรอเนี่ย?"
12030-13 = "แต่ 10 ปีหลังจากนี้มันจะมีมูลค่า 100 ล้านเยนเลยนะ...\n\n"
12030-14 = "เฮ้อ..."
12030-15 = ""
12030-16 = "อารุจังเอาแต่ทำหน้าบูดแฮะ..."
12030-17 = "เป็นอะไรเหรอประธาน?\n\n\n"
12030-18 = "อารุจังคงไม่อยากย้ายออกจากที่นี่น่ะ"
12030-19 = "แต่พวกเราก็ไม่มีทางเลือกเพราะพวกคณะกรรมการวินัยรู้ที่อยู่ของพวกเราแล้ว แถมยังทำภารกิจลูกค้า#nไม่สำเร็จอีก มันช่วยไม่ได้นี่นา..."
12030-20 = "ไหนจะการต่อสู้กับอะบิดอสที่ยังจบแบบไม่สวยอีก"
12030-21 = "ชะ...ใช่ไหมล่ะ! พวกนั้นกล้าดียังไงถึงหันมาเล่นงานคนที่ต่อสู้เคียงบ่าเคียงไหล่กันน่ะ บะ...แบบนั้นมัน#nขี้ขลาดที่สุด!"
12030-22 = "เฮ้ออ... \n"
12030-23 = "เงินที่เหลือในกระเป๋าเงินนั่นก็หมดไปกับการซ่อมร้านราเม็ง นี่ประธานอารุ เธอนี่มัน..."
12030-24 = "หนวกหูน่า! เงียบไปเลย! \n\n"
12030-25 = "ฉันก็รู้น่า!\n\n\n"
12030-26 = "\n......"
12030-27 = "คนนอกกฎหมายที่ร้ายกาจ... กับตัวฉัน... คง...\n\n"
12030-28 = ""
12030-29 = "เฮ้อ..."
12030-30 = "เป็นท่านประธานที่ยุ่งวุ่นวายจังเลยนะ"
12030-31 = "แต่ก็เป็นอารุจังคนดีคนเดิมของพวกเรานี่นา? อยู่ด้วยแล้วสนุกจะตาย\n\n"
12030-32 = "อื้ม! ใช่แล้วค่ะท่านอารุ! ถะ... ถ้าไม่มีท่านอารุ ฉันก็คงอยู่ไม่ได้ถึงวันนี้หรอกค่ะ...\n"
12030-33 = ""
12030-35 = "ท่านอารุคือคนที่ฉันเคารพมากที่สุดนะคะ! \n\n\n"
12030-36 = "หนวกหูน่า!\n\n\n"
12030-38 = "เอาละ!"
12030-39 = "เท่านี้ก็เรียบร้อย! ย้ายของออกมาหมดแล้วค่ะ!"
12030-40 = "ทีนี้เราจะไปไหนกันล่ะ?"
12030-41 = "อืม...\n"
12030-42 = "ถ้ายังไม่ได้มีแผนว่าจะไปที่ไหน เรากลับเกเฮนน่ากันไหม?\n\n"
12030-43 = "[s] \"ว่าไงทุกคน~\""
12030-45 = "!!\n\n"
12030-46 = "คะ... คุณ...?"
12030-47 = "คะ... ครูจากชาเล่ต์?!"
12030-48 = "ว้าวว คุณครูนี่นา! มาหาพวกเราจริงๆ ด้วย!"
12030-49 = "ทะ... ทำไมถึงมาที่นี่ล่ะ!? คุณเป็นฝ่ายสนับสนุนของพวกอะบิดอสไม่ใช่รึไง?!"
12030-51 = "ก็ใช่อยู่หรอก แต่คุณครูชอบพูดว่าให้เราดีต่อกันไว้นี่นา~"
12030-52 = "ใช่ค่ะ แถมยังช่วยเราตอนที่สู้กับคณะกรรมการวินัยอีก...\n"
12030-53 = "ดูท่าทางแล้วไม่น่าจะมีเจตนาร้ายนะ... อีกอย่างพวกเราก็จะไปแล้วด้วย เราไม่จำเป็นต้องเป็นปฏิปักษ์#nกันหรอก"
12030-54 = "[s] \"จะไปจากที่นี่กันแล้วเหรอ?\""
12030-56 = "ไปเปยอะไรกันเล่า! พวกเราก็แค่ย้ายที่เพื่อหาภารกิจให้ได้เยอะขึ้นต่างหาก! แค่ย้ายที่เฉยๆ!"
12030-57 = "[s] \"งั้นไว้เจอกันใหม่นะ อารุจัง\""
12030-58 = "......\n"
12030-59 = "อา... อะฮ่าฮ่าฮ่า! ได้สิ! ถ้าได้ร่วมมือกันในฐานะพาร์ทเนอร์ทางธุรกิจก็คงไม่เลวเลยนะ คุณครู"
12030-60 = "ถึงแม้ตอนนี้เราจะยุ่งจนไปร่วมมืออะไรด้วยไม่ได้ก็เถอะ เอาไว้คราวหน้าแล้วกันเนอะ"
12030-61 = "เราคงได้มาที่อะบิดอสกันอีกครั้งแหละ เพราะเราถูกใจที่นี่เข้าให้แล้วละนะ"
12030-62 = "ก็... ตามนั้นแหละนะ"
12030-63 = "ค่ะ ใช่แล้วค่ะ"
12030-64 = "ชะ... ใช่! เราจะกลับมากินราเม็งกันอีก!!"
12030-65 = ""
12030-66 = ""
12030-67 = ""
12030-68 = "ก็มันอร่อยนี่นา...\n\n\n\n"
12030-71 = "(รถบรรทุกของหน่วยรับจ้างสารพัด 68 เลี้ยวหายเข้าซอยไป)"
12030-73 = "สวัสดีค่ะคุณเจ้าของร้าน พวกเรามาเยี่ยมค่ะ"
12030-74 = "เป็นยังไงบ้างมาสเตอร์?"
12030-75 = "อ้าว เซริกะจัง แล้วก็อายาเนะจัง เพื่อนของเซริกะจังสินะ มากันแต่เช้าเลยน้า..."
12030-76 = "[s] \"ตอนนี้เป็นยังไงบ้าง?\""
12030-77 = "คุณครูก็มากับเขาด้วยเหรอ? ฉันไม่เป็นอะไรหรอก แค่รอยขีดข่วนนิดๆ หน่อยๆ เอง"
12030-78 = "แต่ว่าร้านของมาสเตอร์...\n\n"
12030-79 = "ขอโทษนะเซริกะจัง ต้องหยุดทำงานพาร์ทไทม์เพราะฉันเลย"
12030-80 = "พูดอะไรน่ะ! นั่นเป็นเพราะร้านของมาสเตอร์ถูกระเบิดไปต่างหาก"
12030-81 = "ฉันตั้งใจจะปิดร้านราเม็งอยู่แล้วละ มันก็แค่ปิดก่อนกำหนดที่ตั้งใจเอาไว้เท่านั้นเอง"
12030-82 = "คะ? จะปิดกิจการเหรอคะ?"
12030-83 = "ใช่แล้ว พอดีเจ้าของตึกมาบอกให้ย้ายออกตั้งนานแล้วละนะ"
12030-84 = "จะ.. เจ้าของตึกเหรอคะ? หมายความว่าอะไรคะ? เจ้าของอาคารในเขตปกครองตนเองอะบิดอสก็คือ#nโรงเรียนอะบิดอสไม่ใช่เหรอ... แล้วทำไมถึง...\n"
12030-85 = "....."
12030-86 = ""
12030-87 = "ไม่ใช่หรอก สภานักเรียนอะบิดอสใช้หนี้ไม่หมด ก็เลยมีการเปลี่ยนเจ้าของอาคารไปเมื่อไม่กี่ปีก่อนน่ะ#nพวกเธอคงไม่รู้สินะ\n"
12030-88 = "คะ?!\n\n"
12030-89 = "จริงเหรอ?! แล้วใครได้เป็นเจ้าของที่ดินที่นี่ล่ะ?!\n"
12030-90 = "[s1] \"สินเชื่อไคเซอร์?\"\n[s2] \"ไคเซอร์ คอร์เปอเรชั่น?\""
12030-91 = "อืม... น่าจะชื่อประมาณนั้นนะ... แต่ฉันไม่ค่อยรู้เรื่องเอกสารสัญญาหรอก"
12030-92 = "อืม... น่าจะชื่อประมาณนั้นนะ... แต่ฉันไม่ค่อยรู้เรื่องเอกสารสัญญาหรอก"
12030-93 = "ถ้าเป็นอย่างนั้น..."
12030-94 = ""
12030-95 = "เซริกะจังกับคุณครูกลับไปที่โรงเรียนก่อนเถอะค่ะ ฉันมีเรื่องที่ต้องไปตรวจสอบนิดหน่อยค่ะ\n"
12030-96 = "หืม? ตรวจสอบอะไรเหรอ? ไปด้วยกันสิอายาเนะจัง!\n"
12030-97 = "งั้นคุณครูไปรอที่ห้องชมรมก่อนเถอะค่ะ เดี๋ยวพวกเราจะตามไปค่ะ!\n"
12030-98 = "[s] \"ได้สิ ครูก็มีเรื่องจะบอกทุกคนเหมือนกัน\""
12030-99 = "มาสเตอร์! เลิกคิดที่จะปิดกิจการไปเลยนะ! เข้าใจไหม?"
12030-100 = "อ้อ เซริกะจัง พอดีว่ามีใครเอากระเป๋าใส่เงินมาไว้ที่ร้านด้วย..."
12030-101 = ""
12030-102 = "[s] \"เอาไว้ซ่อมร้านนะ\""
12030-103 = "หืม?\n\n"
12030-104 = ""
12030-106 = "ไปกันเถอะเซริกะจัง!\n\n"
12030-107 = "อื้อ! ไว้เจอกันนะคุณครู!\n\n"
12030-108 = ""
12030-110 = "ตอนต่อไป;เรื่องเล่าของแต่ละคน 1"
