[translation]
12050-1 = "ตอนที่ 5;เรื่องเล่าของแต่ละคน 2"
12050-2 = "ไคเซอร์ คอนสตรัคชั่น...? อยู่ในไคเซอร์กรุ๊ปเหรอคะ...?!\n\n\n"
12050-3 = "พื้นที่เขตปกครองตนเองอะบิดอสเป็นของไคเซอร์งั้นเหรอคะ?!"
12050-4 = "งั้นร้านชิบะเซกิ ราเม็งก็...?\n\n\n"
12050-5 = "ค่ะ... อาคารร้านราเม็งเป็นของไคเซอร์กรุ๊ปแล้วค่ะ แถมยังสั่งให้คุณเจ้าของร้านออกจากอาคารด้วย...\n"
12050-6 = "เจ้าของร้านก็เลยจะปิดกิจการค่ะ... เขาบอกเราว่าเรื่องนี้ต้องเกิดขึ้นอยู่แล้วสักวัน..."
12050-7 = "......\n"
12050-8 = "...!!"
12050-9 = "ว่าไงนะ?!\n\n"
12050-10 = "ร้านราเม็ง... มะ... ไม่จริงน่า..."
12050-11 = "ไม่เพียงเท่านี้นะคะ อาคารส่วนกลางของอะบิดอสและที่รกร้างที่กลายเป็นทะเลทรายหลายสิบล้าน#nตารางเมตร"
12050-12 = "รวมถึงอาคารกับที่ดินในเมืองที่ยังไม่กลายเป็นทะเลทราย... ส่วนมากก็เปลี่ยนเจ้าของแล้วค่ะ...\n"
12050-13 = "ตอนนี้พื้นที่ที่ทางไคเซอร์ยังไม่ได้สิทธิ์ครอบครองก็มีแต่อาคารหลักและพื้นที่รอบๆ โรงเรียนบางส่วน#nเท่านั้น..."
12050-14 = "แต่ว่าเรื่องนี้มันเกิดขึ้นได้ยังไงเหรอคะ? พื้นที่ในเขตปกครองของโรงเรียนเราซื้อขายได้ด้วยเหรอ..."
12050-15 = "ใครกันนะที่ทำแบบนี้..."
12050-16 = "...คงเป็นสภานักเรียนอะบิดอสน่ะสิ"
12050-17 = "...!"
12050-18 = "เพราะสิทธิในการลงมติเรื่องทรัพย์สินของโรงเรียนเป็นของสภานักเรียน มีแต่สภานักเรียนที่ทำเรื่องนี้ได้"
12050-19 = "ใช่ค่ะ คนที่ทำสัญญานี้คือสภานักเรียนชุดก่อนของอะบิดอส\n"
12050-20 = "แต่ว่าสภานักเรียนอะบิดอสยุบไปตั้งแต่เมื่อ 2 ปีก่อนแล้วนี่คะ"
12050-21 = "ใช่ค่ะ... และหลังจากนั้นก็ไม่มีการซื้อขายแบบนี้กันอีกเลย"
12050-22 = "ถ้าเป็นอย่างนั้น... ถ้าเป็น 2 ปีก่อน... \n"
12050-23 = "พวกสภานักเรียนทำบ้าอะไรลงไปเนี่ย!"
12050-24 = "กล้าดียังไงถึงขายที่ดินของโรงเรียนแบบนี้...? แถมยังไปขายให้ไคเซอร์ คอร์เปอเรชั่นอีก! "
12050-25 = "เจ้าของโรงเรียนคือนักเรียนต่างหากล่ะ! ทำไมถึงทำเรื่องแบบนั้นได้...!!\n\n"
12050-26 = "......"
12050-27 = "มีเรื่องใหญ่ขนาดนี้ แต่พวกเราไม่รู้กันเลย..."
12050-28 = "เขตปกครองตนเองเป็นของโรงเรียน ไม่ว่าใครก็ต้องคิดแบบนี้ไม่ใช่เหรอคะ? พวกเราก็เลยทุ่มเทกับการ#nใช้หนี้ให้โรงเรียน โดยไม่ได้สนใจเรื่องทรัพย์สินของโรงเรียนเลย"
12050-29 = "ถ้าฉันรู้เรื่องนี้ก่อนหน้านี้สักหน่อยละก็..."
12050-30 = "...ไม่หรอก ถึงรู้ไปก็ไม่มีประโยชน์อะไรอยู่ดี"
12050-31 = "เรื่องนี้มันเกิดตั้งแต่ก่อนอายาเนะจังมาเข้าเรียน ไม่สิ ตั้งแต่ก่อตั้งคณะกรรมการแผนงานขึ้นมาซะอีก"
12050-32 = "รุ่นพี่โฮชิโนะ รู้อะไรบางอย่างอยู่เหรอ?\n"
12050-33 = "จริงด้วยสิคะ! รุ่นพี่โฮชิโนะก็เคยเป็นสภานักเรียนอะบิดอสใช่ไหมคะ?"
12050-34 = "หืม? จริงเหรอ? เคยเป็นเหรอ?\n\n"
12050-35 = "ใช่ค่ะ เป็นถึงรองประธานนักเรียนของสภานักเรียนชุดสุดท้ายเลยด้วย..."
12050-36 = ""
12050-37 = "อ่า... ก็ใช่อยู่หรอกนะ แต่ถ้าเป็นเรื่องเมื่อ 2 ปีก่อน ฉันไม่เคยเจอพวกรุ่นพี่พวกนั้นหรอก\n"
12050-38 = "ตอนที่ฉันเข้าไปในสภานักเรียน พวกกรรมการชุดเก่าก็ออกไปกันหมดแล้วน่ะ"
12050-39 = "มีนักเรียนอยู่ไม่ถึงร้อยคน และคุณครูก็ไม่มีเลยสักคน ส่วนการเรียนก็อย่าหวังเลย..."
12050-40 = "ห้องสภานักเรียนเหมือนเป็นห้องเก็บของว่างๆ และไม่มีเอกสารที่กรรมการชุดเก่าเหลือทิ้งไว้เลย#nเพราะตอนนั้นเอาแต่ย้ายอาคารหนีภาวะทะเลทรายกัน\n"
12050-41 = "ถึงจะบอกว่าเป็นสภานักเรียนชุดสุดท้าย แต่ก็มีแค่ประธานนักเรียนคนใหม่กับฉันนี่แหละ"
12050-42 = "ประธานนักเรียนเป็นนักเรียนที่ได้ที่โหล่ของโรงเรียนที่รับตำแหน่งมาโดยไม่ได้รู้เรื่องอะไรเลย ส่วนฉันมัน#nก็แค่เด็กใหม่ที่ชอบหัวร้อนบ่อยๆ..."
12050-43 = "แหะๆ ...ตอนนั้นทุกอย่างมันวุ่นวายมากเลยละ\n\n"
12050-44 = "ที่โหล่ของโรงเรียนได้เป็นประธานนักเรียนงั้นเหรอ? นี่มันสภานักเรียนแบบไหนกัน?\n\n\n"
12050-45 = "หน้าที่กับผลการเรียนมันคนละอย่างกันนะ เซริกะ"
12050-46 = "แต่ผลการเรียนของเซริกะจังก็...\n"
12050-47 = "รู้หรอกน่า!! ฉันแค่ถามไปงั้นๆ แหละน่า จู่ๆ ทำไมมาพูดถึงผลการเรียนฉันล่ะ!!\n"
12050-48 = "แหะๆ~ แต่ก็พูดถูกนะ เราใช้ชื่อว่าสภานักเรียน แต่จริงๆ ก็แค่กลุ่มของเด็กบ้าๆ บอๆ นั่นละนะ"
12050-49 = "ฉันสมัครเข้าสภานักเรียนอย่างไม่ทันตั้งตัวน่ะ... ตอนนั้นต้องไปนู่นไปนี่เยอะเลย\n\n"
12050-50 = "ตอนนั้นก็ไม่รู้ตัวเหมือนกันว่าทำอะไรอยู่... เพราะฉันมันก็แค่เด็กซื่อบื้อคนหนึ่งเท่านั้นเอง"
12050-51 = "......"
12050-52 = "รุ่นพี่โฮชิโนะ..."
12050-53 = "...... นี่ไม่ใช่ความผิดของรุ่นพี่โฮชิโนะหรอก"
12050-54 = "การที่อะบิดอสจัดตั้งคณะกรรมการแผนงานขึ้นได้หลังจากสภานักเรียนถูกยุบไปก็เพราะรุ่นพี่เลยนะ"
12050-55 = "หืม...?\n\n"
12050-56 = "...ถึงรุ่นพี่โฮชิโนะจะขี้เกียจไปบ้าง แต่ก็เป็นคนที่คอยนำพวกเราเสมอๆ เวลามีเรื่องสำคัญ"
12050-57 = "ใช่ค่ะ ตอนที่เซริกะจังหายตัวไป คนแรกที่ไปขอความช่วยเหลือจากคุณครูก็คือรุ่นพี่โฮชิโนะ...\n\n"
12050-58 = "ฉันทำแบบนั้นเหรอ? จำไม่ได้แฮะ...\n"
12050-59 = "[s] \"ใช่แล้วละ\""
12050-60 = "อ๊ะ.... จริงเหรอ?! \n\n"
12050-61 = "แม้จะมีมุมที่น่ารำคาญอยู่บ้าง แต่ฉันก็คิดว่ารุ่นพี่เป็นคนที่น่าเคารพ"
12050-62 = "นี่มันคำชมหรือคำด่ากันนะ...\n"
12050-63 = "อะไรเนี่ย? ทำไมจู่ๆ ชิโรโกะจังก็รับบทซึ้งขึ้นมาล่ะ?! ลุงคนนี้ไม่ชินกับบรรยากาศนี้เลยนะ"
12050-64 = "อืม... ฉันก็แค่อยากบอกเฉยๆ น่ะ"
12050-65 = "อะ... อืม\n"
12050-66 = "......\n"
12050-68 = "แล้วทำไมสภานักเรียนชุดก่อนถึงขายที่ดินให้ไคเซอร์เหรอคะ...?"
12050-69 = "ก็แหงอยู่แล้ว คงจะอยากจับมือกับไคเซอร์น่ะสิ"
12050-70 = "ไม่หรอกค่ะ... ฉันว่าไม่ใช่แบบนั้น\n"
12050-71 = "อ่า ถึงฉันจะไม่รู้จักรุ่นพี่พวกนั้นก็เถอะ แต่ฉันว่าพวกเขาก็คงพยายามเพื่อรักษาโรงเรียนนี้ไว้\n"
12050-72 = "บางทีพวกเขาอาจจะทำแบบนั้นเพราะต้องการใช้หนี้ก็ได้...\n"
12050-73 = "ใช้หนี้..."
12050-74 = "ใช่ค่ะ ฉันก็คิดแบบนี้ เพราะตอนนั้นหนี้ของโรงเรียนก็มีมหาศาลเลย\n"
12050-75 = "แต่ว่าที่ดินก็ราคาไม่สูง ดอกเบี้ยก็เอาแต่เพิ่มขึ้น เลยทำให้ยอดหนี้ไม่ลดลง..."
12050-76 = "ก็เลยต้องขายที่ดินให้เรื่อยๆ เหรอคะ?"
12050-77 = "อะไรเนี่ย... แบบนี้มันแปลกๆ นะ \n\n"
12050-78 = "[s] \"นี่คือการรีดไถที่ดินแบบหนึ่งเลย\""
12050-79 = "หืม?! แปลว่าอะไรเหรอคุณครู?\n"
12050-80 = "[s] \"อะบิดอสติดอยู่ในวงจรอุบาทว์ของพวกนั้นแล้วน่ะ\""
12050-81 = "หือ? \n"
12050-82 = "อ่า..."
12050-83 = "เป็นแบบนั้นเหรอ?"
12050-84 = "คนที่ให้อะบิดอสกู้เงินก็คือพวกไคเซอร์\n"
12050-85 = "...!!"
12050-86 = "ถ้าอย่างนั้น..."
12050-87 = "สินเชื่อไคเซอร์ปล่อยกู้ในยอดที่โรงเรียนก็ใช้คืนไม่หมด แถมยังมีดอกเบี้ยบวกเข้าไปอีก ทำให้เราต้องยอม#nขายที่ดินเพื่อชดใช้หนี้ \n"
12050-88 = "ใช่ค่ะ ทางนั้นคงบอกให้ขายที่ดินตรงทะเลทรายและที่รกร้างแน่เลยค่ะ"
12050-89 = "เพราะยังไงพื้นที่นั้นก็ใช้ประโยชน์ไม่ได้อยู่ดี ถ้าเป็นข้อเสนอแบบนั้น เป็นใครก็ต้องหลงเชื่อ..."
12050-90 = "แต่ถึงจะขายไป หนี้ก็ไม่ได้ลดลง แถมทางนั้นก็ได้ที่ดินไปเพิ่มขึ้นเรื่อยๆ \n\n\n"
12050-91 = "จนเขตปกครองตนเองอะบิดอสกลายเป็นของไคเซอร์อย่างช้าๆ"
12050-92 = "ใช่ พวกมันต้องใช้ลูกไม้นี้แน่ๆ\n"
12050-93 = "งั้นแสดงว่าการที่ให้อะบิดอสกู้เงินตั้งแต่แรก... ก็เพื่อจะยึดที่ดินไป..."
12050-94 = "วางกับดักนี้ไว้นานแล้วสินะ อาจจะตั้งแต่หลายสิบปีก่อนก็ได้..."
12050-95 = "เป็นแผนการใหญ่ที่ชั่วร้ายมากเลย..."
12050-96 = "อะไรกันเนี่ย!! ให้พวกไคเซอร์ขโมยไปง่ายๆ ได้ยังไง! \n\n\n\n"
12050-97 = "พวกสภานักเรียนทำไมถึงได้โง่และไร้ประสิทธิภาพกันแบบนั้น! ถ้าไม่หลงกลคนเลวพวกนั้นละก็...! \n\n"
12050-98 = "[s] \"ไม่ใช่อย่างนั้นหรอก\""
12050-99 = "คุณครู?"
12050-100 = "[s] \"สิ่งที่ไม่ดีคือการหลอกคนอื่นต่างหาก อย่าประณามคนที่ถูกหลอกเลย\""
12050-101 = "......\n"
12050-102 = "......"
12050-103 = "อ่า... เรื่องนั้นฉันก็รู้หรอกน่า! ฉันก็เคยถูกหลอกให้ซื้อกำไลเจอร์เมเนียมมาแล้วไง! ฉันรู้ดีกว่าใครอีกนะ!#nรู้ว่าคนที่ไม่ดีคือคนที่หลอกคนอื่น!\n\n\n"
12050-104 = "แต่ว่า..."
12050-105 = "มันน่าโมโหชะมัด... ทำไมพวกนั้นถึง... \n"
12050-106 = "ลำพังอะบิดอสเองก็ต้องทุกข์ทรมานอยู่แล้ว แล้วทำไมถึงได้ทำเรื่องแบบนั้นได้...\n"
12050-107 = "เซริกะจัง..."
12050-108 = "[s] \"....\""
12050-109 = "......"
12050-110 = "......"
12050-111 = "...คนที่ทุกข์ทรมานจะร้อนรนเพราะความสิ้นหวังยังไงล่ะ\n\n"
12050-112 = "หืม?!\n"
12050-113 = "และคนที่สิ้นหวัง... ก็คงยอมทำได้ทุกอย่าง"
12050-114 = "แหะๆ~ ฉันไปได้ยินใครพูดอะไรทำนองนี้มาน่ะ คิดแบบนี้ก็แล้วกันนะเซริกะจัง\n\n"
12050-116 = "หนี้ของโรงเรียน... สถานการณ์ของอะบิดอส... และเบาะแสที่พวกเรากับคุณครูสืบมาได้"
12050-117 = "ทุกอย่างมันเริ่มปะติดปะต่อกันแล้วค่ะ"
12050-118 = "พอสภานักเรียนถูกยุบไป ไคเซอร์ คอร์เปอเรชั่นก็ไม่สามารถซื้อที่ดินไปได้อีก..."
12050-119 = "ก็เลยจ้างกลุ่มอันธพาลเข้ามาก่อกวนพวกเรา เพื่อจะได้ยึดที่ดินผืนสุดท้ายก็คือโรงเรียนของเราค่ะ!\n"
12050-120 = "สิ่งที่ไคเซอร์ คอร์เปอเรชั่นต้องการไม่ใช่เงิน แต่เป็นที่ดินของเราต่างหากค่ะ!"
12050-121 = ""
12050-122 = "แต่ทำไมถึงต้องอยากได้ที่ดินของพวกเราด้วยล่ะคะ?"
12050-123 = "ที่ส่วนใหญ่ของเขตปกครองตนเองอะบิดอสเป็นพื้นที่รกร้างที่ปกคลุมด้วยทะเลทรายนี่นา...\n"
12050-124 = "นั่นน่ะสิคะ... การเอาที่ดินตรงนี้ไปไม่น่าจะมีประโยชน์อะไรนะ...\n\n"
12050-125 = "[s] \"ครูรู้อะไรบางอย่างมาด้วยละ\""
12050-126 = "คุณครู...?"
12050-127 = "[s] เล่าสิ่งที่ได้ยินจากฮินะให้ทุกคนฟัง"
12050-130 = "...... ครูจากชาเล่ต์\n\n"
12050-131 = "ทั้งแพนเดโมเนียมและสภาน้ำชายังไม่รู้ข้อมูลนี้..."
12050-132 = "...แต่ฉันคิดว่าคุณควรรู้เอาไว้น่ะ"
12050-133 = "ฉันคิดว่าไคเซอร์ คอร์เปอเรชั่นกำลังทำอะไรบางอย่างอยู่แถวๆ เขตทะเลทรายของอะบิดอส... "
12050-135 = "พวกไคเซอร์...\n\n"
12050-136 = "กำลังวางแผนทำบางอย่าง...\n"
12050-137 = "ในทะเลทรายร้างงั้นเหรอคะ...?\n\n\n"
12050-138 = "แล้วทำไมประธานกรรมการวินัยเกเฮนน่าถึงรู้..."
12050-139 = "แล้วทำไมมาบอกคุณครูล่ะ...?\n"
12050-140 = "โอ๊ย หงุดหงิดชะมัด! จะมาลังเลอะไรกันอยู่อีกล่ะ!"
12050-141 = "ทะเลทรายอะบิดอสอยู่ในเขตปกครองตนเองของเรานะ! เราก็ไปที่นั่นกันสิ!\n"
12050-142 = "ถ้าสงสัยว่าเกิดอะไรที่นั่น ก็ไปดูกับตาให้รู้กันไปเลย!\n\n"
12050-143 = "อืม..."
12050-144 = "ว้าว... เซริกะจัง ไม่ได้พูดโดนใจแบบนี้มานานแล้วนะ หม่าม้าคนนี้ดีใจจัง ประทับใจจังเลย"
12050-145 = ""
12050-146 = ""
12050-147 = ""
12050-148 = "อะไรกันเนี่ย! ทำไมจู่ๆ ก็มาให้กำลังใจกันเล่า!"
12050-149 = "อ่า... อะฮ่าฮ่า...\n\n"
12050-150 = "ฉันว่าเซริกะจังพูดถูกนะคะ\n\n"
12050-151 = ""
12050-152 = ""
12050-153 = "[ns1] \"งั้นออกเดินทางกันเลย\"\n[ns2] \"งั้นไปทะเลทรายอะบิดอสเลย\""
12050-156 = ""
12050-157 = ""
12050-158 = "ค่ะ!"
12050-161 = "คุณครู... \n"
12050-162 = "ก่อนจะออกเดินทาง ขอเวลาฉันหน่อยได้ไหม?"
12050-163 = "ฉันมีเรื่องอยากปรึกษาน่ะ...\n"
12050-164 = "[s] ตามชิโรโกะไป"
12050-168 = "......\n\n"
12050-169 = "ดูนี่สิ\n\n"
12050-170 = "[s] รับกระดาษที่ชิโรโกะยื่นให้"
12050-171 = "ฉันเจอในกระเป๋าของรุ่นพี่โฮชิโนะน่ะ\n"
12050-172 = ""
12050-173 = ""
12050-175 = "[ns] \"หนังสือลาออก... คณะกรรมการแผนงาน ทาคานาชิ โฮชิโนะ...?"
12050-176 = "(พยักหน้า) ...."
12050-177 = "หนังสือลาออกจากคณะกรรมการแผนงาน"
12050-178 = "ฉันยังไม่ได้บอกใครเลย... แต่รุ่นพี่โฮชิโนะน่าจะรู้แล้วว่าฉันไปค้นกระเป๋ามา\n"
12050-179 = "[s] \"แล้วไปค้นทำไมเหรอ...?\""
12050-180 = "เมื่อวานตอนที่คณะกรรมการวินัยมาบุกที่นี่ รุ่นพี่ไม่เคยหายไปนานแบบนี้มาก่อนเลย...\n"
12050-181 = "ไม่ว่าจะคิดยังไงก็คิดไม่ออก ฉันก็เลยไปค้นกระเป๋าของรุ่นพี่เข้า แล้วก็เจอของแบบนี้"
12050-182 = "...ขอโทษนะ ถ้าจะโดนดุว่าแค่ไม่เข้าใจก็เลยไปตัดสินคนอื่น ฉันก็สมควรแล้วละ"
12050-183 = "[s3] \"เอาไว้ค่อยดุทีหลังแล้วกันนะ...\"\n[s4] \"ตอนนี้เก็บไว้เป็นความลับก่อนแล้วกัน\""
12050-184 = "อืม... แต่รุ่นพี่โฮชิโนะต้องปิดบังอะไรบางอย่างกับพวกเราอยู่แน่เลย"
12050-185 = "อืม... แต่รุ่นพี่โฮชิโนะต้องปิดบังอะไรบางอย่างกับพวกเราอยู่แน่เลย"
12050-187 = ""
12050-188 = "......"
12050-190 = "ตอนต่อไป;มุ่งสู่ทะเลทรายอะบิดอส 1"
