[translation]
12070-1 = "ตอนที่ 7;มุ่งสู่ทะเลทรายอะบิดอส 2"
12070-3 = "พื้นที่จากนี้ไปคือทะเลทรายร้าง...\n"
12070-4 = "ฉันเคยไปไกลจนถึงเขตเมืองที่ปกคลุมด้วยทราย แต่ไม่เคยมาที่นี่เลยค่ะ...\n"
12070-5 = "ไม่ได้มานานเลยนะเนี่ย~ \n\n\n"
12070-6 = "รุ่นพี่เคยมาที่นี่เหรอ?\n"
12070-7 = "อื้ม เคยมาทำภารกิจในตอนที่เป็นสภานักเรียนอยู่หลายครั้งน่ะ\n"
12070-8 = "ถ้าเข้าไปอีกหน่อยก็จะเจอโอเอซิสที่เคยเป็นที่จัดเทศกาลทะเลทรายอะบิดอส\n"
12070-9 = "อะไรนะ? โอเอซิส? มีโอเอซิสด้วยเหรอ?\n\n"
12070-10 = "ใช่ แต่ตอนนี้มันคงแห้งขอดไปแล้วน่ะ แต่ก่อนมันมีขนาดใหญ่กว่าทะเลสาบซะอีก ว่ากันว่าใหญ่จนเอาเรือ#nลงไปพายได้เลย\n"
12070-11 = "ถึงแม้ฉันจะไม่เคยเห็นเองกับตาตัวเองก็เถอะ"
12070-12 = "เทศกาลทะเลทราย... ฉันก็เคยได้ยินมาเหมือนกัน เห็นว่ามีผู้คนมาเที่ยวกันเยอะ เพราะเป็นเทศกาลที่#nโด่งดังที่สุดของอะบิดอส"
12070-13 = "ใช่ โด่งดังขนาดที่นักเรียนจากโรงเรียนอื่นยังมาเที่ยวเทศกาลนี้เลย แต่นั่นก็เมื่อหลายสิบปีก่อนจะเกิด#nเหตุการณ์ทะเลทรายขึ้น "
12070-14 = "เทศกาล... ฝูงชน... ในพื้นที่ทะเลทรายเนี่ยนะ? ไม่น่าเชื่อเลย...\n"
12070-15 = "เพราะแต่ก่อนที่นี่คือพื้นที่ที่น่าอยู่อาศัยยังไงล่ะ ตอนนั้นไม่มีฝุ่นทรายเลยด้วย\n"
12070-16 = ""
12070-17 = "เรายังต้องไปอีกหน่อยค่ะ กว่าจะถึงเขตที่ประธานกรรมการวินัยเกเฮนน่าพูดถึง"
12070-18 = "แต่ว่าในที่แบบนี้จะมีอะไรเป็นพิเศษกันนะ..."
12070-19 = "เอาเป็นว่าให้ระมัดระวัง แล้วเดินหน้าต่อค่ะ\n"
