[translation]
12175-2 = "#na;PMC 병사;적들의 공격이 시작되었습니다!"
12175-3 = "3;카이저 PMC 이사;01;막아야 한다!! PMC의 병력을 집중해라!!\n#3;a"
12175-4 = "3;카이저 PMC 이사;01;북쪽과 동쪽에서 협공을 해! 북쪽! 북쪽의 대(對) 데카그라마톤 방어대대를 보내라!!"
12175-5 = "#na;PMC 병사;네!"
12175-6 = "#na;PMC 병사;……!! 북쪽에 소수의 병력이 확인되었습니다!"
12175-7 = "3;카이저 PMC 이사;01;뭣?! 아비도스의 지원군인가?!\n#3;stiff"
12175-8 = "#na;PMC 병사;아, 아닙니다……! 숫자는 3명…… 그러나…… 저것은……!"
12175-10 = "3;히나;01;…….\n#3;a"
12175-11 = "1;통신아코;05;카이저 PMC의 증원군, 조우. 대대 규모입니다. 부장님. \n#3;m5\n#1;a"
12175-12 = "3;히나;05;알겠어. 준비해.\n#3;em;[반응]"
12175-13 = "1;이오리;06;하아…… 어쩌다 여기까지 와서…….\n#1;em;…\n#1;a"
12175-14 = "1;치나츠;06;(……저는 왜 끌려온 거죠?)\n#1;a\n#1;em;[땀]\n#1;stiff"
12175-15 = "3;히나;05;업무를 남겨두고 온 거니까 빠르게 끝내고 복귀한다."
12175-16 = "1;통신아코;07;반성문 대신 부장님이 관대하게 허락해주신 봉사활동이니까, 다들 불평은 적당히 하시고요.\n#1;greeting\n#1;em;[음표]"
12175-17 = "3;히나;05;여기서 적을 막는다. 단 한명도 선생에게 접근시키지 않겠어.\n#3;em;[반응]"
12175-18 = "3;히나;05\n#3;m3\n#1;dl\n#wait;1500"
12175-20 = "3;히나;15;간다. \n#3;closeup\n#3;em;[!]"
12175-23 = "#nextepisode;다음화;그럼에도 놓지 않은 1"
