[translation]
12200-1 = "第20話;尾聲"
12200-2 = "您好，老師。"
12200-3 = "阿拜多斯對策委員會，今天也是忙碌的一天。"
12200-4 = "在老師的認可下，對策委員會成為了阿拜多斯高中正式的社團。"
12200-5 = "原本因為是非公認的社團而遇到了很大的麻煩，現在可以安心了。"
12200-6 = "多虧老師的幫忙，對策委員會正式接下了阿拜多斯學生會的職責。"
12200-7 = "雖然我個人很希望星野前輩能接下學生會長的職位，但他本人卻極度抗拒……"
12200-8 = "因此新任學生會長依然從缺。"
12200-10 = "歡迎光臨柴關拉麵店！"
12200-11 = ""
12200-12 = "柴關拉麵改以路邊攤的形式重新開張。"
12200-13 = ""
12200-14 = ""
12200-15 = "生意還是很不錯，茜香醬也重新開始打工了。"
12200-16 = ""
12200-17 = "老闆也比以往充滿鬥志……看來離引退的時間還很遠呢。"
12200-19 = "儘管星野前輩的事件在老師的活躍下得到解決，#n不過阿拜多斯的負債依然還有9億元……和一開始幾乎相同……"
12200-20 = "凱薩信貸在黑市進行非法金融交易一事曝光，因而受到了聯邦學生會的調查。"
12200-21 = "也許是日步美同學讓三一對此展開了某些行動吧……"
12200-22 = "聯邦學生會究竟能調查到什麼程度，老實說實在讓人有點懷疑……#n不過我想至少凱薩信貸無法再像以前一樣為所欲為了。"
12200-23 = "據說在那起事件後，#n凱薩PMC的董事被認定為非法劫持學生的主要嫌犯，並遭到了通緝。"
12200-24 = "不過聯邦學生會無法行動的現在，或許沒辦法那麼輕易地抓到他……"
12200-25 = "凱薩公司似乎主張這件事與他們無關，並立即解雇了董事。#n企業果然就是這樣的呢……"
12200-26 = "當時強制調高利息的行為也引發了問題，#n因此最終我們得以支付比原先更低的利息，這點倒可以算是好事一件呢。"
12200-28 = "不過阿拜多斯自治區的大部分權利，仍舊為凱薩公司所有……"
12200-29 = "畢竟阿拜多斯和凱薩的交易本身的確是有效的。"
12200-30 = "他們在那裡計畫著什麼……依然不得而知。"
12200-32 = "啊，話說便利屋的各位好像又在某個地方開設了事務所……"
12200-33 = "有傳聞說他們回到了格黑娜自治區，#n不過也有消息指出他們到了其他地方，所以實際情況並不清楚……"
12200-34 = "格黑娜風紀委員會似乎正密切關注著他們……各方面都很辛苦呢。"
12200-36 = "至於那個黑色西裝人……"
12200-37 = "雖然以老師和星野前輩提供的情報進行了調查……#n但無論怎麼找都找不到那個人的情報。"
12200-38 = "所有的罪都被歸咎於凱薩董事……黑色西裝人的真名與身分依然一無所知……"
12200-39 = "我所能做的似乎僅止於此，後續調查就交給「夏萊」了。"
12200-41 = "……那麼，阿拜多斯對策委員會的定期會議即將開始。"
12200-42 = "雖然這段時間發生了很多事，不過債務並沒有消失。"
12200-43 = "但每個月要還的利息減少了。"
12200-44 = "沒錯～我們的壓力減少了是事實。#n所以就先悠閒地睡個午覺吧……"
12200-45 = "嗯嗯！大家這陣子都這麼忙，要不要趁這個機會去度假呀？"
12200-46 = "在說什麼啊！！可能是稍微有了點餘裕沒錯，但也不能那樣悠悠哉哉的吧！"
12200-47 = "茜香醬……"
12200-48 = "身為對策委員會會計負責人的我必須要說，我們現在依然面臨危機！一直都是危機！"
12200-49 = "唔，嗯……"
12200-50 = "所以我調查了現在的最新潮流！"
12200-51 = ""
12200-52 = "你們看這個！有人知道是什麼嗎？"
12200-53 = "……電腦零件？"
12200-54 = "這個東西叫GPU！可以用來開採加密貨幣哦！ "
12200-55 = "至於加密貨幣是什麼……怎，怎麼了！？大家！？"
12200-56 = "我有更好的方法。你們看這個──"
12200-57 = "通通駁回～"
12200-58 = "……對策委員會依然是這種感覺。"
12200-59 = "還是跟以前一樣，彷彿什麼都沒有改變……"
12200-60 = "啊哈哈……"
12200-61 = ""
12200-62 = ""
12200-63 = ""
12200-64 = "今後也請您多多指教，老師。"
12200-65 = "失去的事物，未曾放棄的事物"
12200-67 = "對策委員會篇;To be Continued in Chapter 3"
