[translation]
1300005-1 = "#title;함께 걷는 시간"
1300005-2 = "#place;밀레니엄 근교 블랙마켓 제 1지구"
1300005-3 = "#na;아카네;멈추세요! 이 악당분!"
1300005-4 = "#na;(후다닥!)"
1300005-5 = "3;헬멧단;01\n#3;al\n#3;black\n#wait;800"
1300005-6 = "3;헬멧단;01\n#3;dl\n#3;black\n#wait;1500"
1300005-8 = "3;아카네;05\n#3;al\n#wait;1500"
1300005-9 = "3;아카네;05\n#3;m2\n#wait;1000"
1300005-10 = "3;아카네;05\n#3;m4\n#wait;1000"
1300005-11 = "3;아카네;06;크윽… 놓친 건가.\n#3;em;[속상함]"
1300005-12 = "3;아카네;05;정보가 누설된 걸까…… 빠른 대응인걸."
1300005-13 = "3;아카네;05;거래는 막았지만, 아직 문서를 확보하진 못했어. 설마 이쪽으로 도망칠……\n#3;em;[...]\n#3;m3"
1300005-14 = "3;아카네;04;……어머?\n#3;em;[반응]"
1300005-15 = "3;아카네;04;어머어머?! 주인님. 어떻게 여기에……?\n#3;em;[?!]\n#3;shake"
1300005-16 = "3;아카네;02;네? 폭발음을 듣고…… 아 그렇군요. 저는 1억 퍼센트 무관하답니다."
1300005-17 = "3;아카네;04;네? 근데 제가 여기에 왜 있냐고요? 그러니까 지금 막 임무를 마치고……."
1300005-18 = "3;아카네;03;아니. 부활동을 종료하고 돌아가려던 길이었어요.\n#3;em;[음표]"
1300005-19 = "3;아카네;01;후훗. 우연이네요."
1300005-20 = "3;아카네;02;그보다 어떠세요 주인님."
1300005-21 = "3;아카네;99;정숙한 여학생은, 밤이슬을 신발 끝에 묻히지 않는 법이라고 하죠. 최근 키보토스 치안도 예전 같지 않아 겁이 나네요.\n#3;em;[...]"
1300005-22 = "3;아카네;01\n#3;d\n#wait;1000"
1300005-23 = "3;아카네;01\n#3;h\n#3;closeup\n#3;greeting\n#wait;1500\n#3;a"
1300005-24 = "3;아카네;02;함께, 밀레니엄까지 바래다주시겠어요?\n#3;closeup\n#3;em;[하트]"
1300005-26 = "#place;밀레니엄 근교 번화가"
1300005-27 = "3;아카네;02;주인님. 주인님.\n#3;hophop\n#3;a"
1300005-28 = "3;아카네;04;네? 사람들 앞에서는 주인님이라 부르지 말아달라고요?\n#3;em;[?]"
1300005-29 = "3;아카네;01;흐음. 사람들의 시선이 신경 쓰일 수 있겠네요. 그럼 어떻게 불러 드리길 바라시나요?"
1300005-30 = "[s1] \"오빠라고 불러줘.\"\n[s2] \"언니라고 불러줘.\" \n[s3] \"선생님이라고 불러.\""
1300005-31 = "3;아카네;06;으음. 어느 쪽이든…… 곤란하네요.\n#3;em;[땀]"
1300005-32 = "3;아카네;06;으음. 어느 쪽이든…… 곤란하네요.\n#3;em;[땀]"
1300005-33 = "3;아카네;06;으음. 어느 쪽이든…… 곤란하네요.\n#3;em;[땀]"
1300005-34 = "3;아카네;01;아무리 주인님의 명령이라도, 저는 제가 섬겨야 할 분의 호칭을 바꿀 수 없어요."
1300005-35 = "3;아카네;03;저는, 메이드니까요.\n#3;greeting\n#3;em;[반짝]"
1300005-36 = "[s] \"메이드부에 들어가게 된 이유는 뭐야?\""
1300005-37 = "3;아카네;04;네……?\n#3;stiff"
1300005-38 = "3;아카네;03;아 하긴. 메이드부는 다른 부에 비하면 조금 독특하긴 하지요.\n#3;em;[...]"
1300005-39 = "3;아카네;02;카린처럼 '가사'에 대한 걸 배워 현모양처가 되겠다며 찾아온 여학생도 있고……"
1300005-40 = "3;아카네;99;아스나 선배처럼 그저 '네루 선배와 함께 하기위해' 찾아온 사람도 있겠지만……"
1300005-41 = "3;아카네;01;저는 그런 오해나 목적 따위는 없었어요.\n#3;em;[반응]"
1300005-42 = "3;아카네;02;저는 메이드부에 들어가서 메이드가 된 게 아니라……"
1300005-43 = "3;아카네;03;제가 메이드였기 때문에 C&C를 선택한 거죠.\n#3;greeting"
1300005-44 = "3;아카네;01;주인님, 오늘은 어떤 봉사로 주인님을 기쁘게 해드릴 수 있을까요."
1300005-45 = "3;아카네;02;저는 태어날 때부터 그런 것만 생각하고 있었답니다.\n#3;em;[반짝]"
1300005-46 = "3;아카네;04;네? 주변 사람들이 수군거리기 시작한다고요?"
1300005-47 = "3;아카네;05;아하. 그런 게 불편하시다면 제가 청소를……\n#3;m4\n#3;em;[...]"
1300005-48 = "3;아카네;02\n#3;em;[반응]\n#wait;1000"
1300005-49 = "3;아카네;01;후훗. 놀라지 마세요.\n#3;m3"
1300005-50 = "3;아카네;03;농.담.이.니.까.\n#3;em;[음표]"
1300005-52 = "3;아카네;06;실은…… 오늘…… 임무에 실패했어요.\n#3;em;[...]\n#3;a"
1300005-53 = "3;아카네;02;하지만, 비록 목표를 달성하지 못했지만, 주인님과 만나니……"
1300005-54 = "3;아카네;03;그 실패조차도, 행운처럼 느껴지네요.\n#3;em;[반짝]"
1300005-55 = "3;아카네;01;임무에 실패했는데……"
1300005-56 = "3;아카네;02;어째서일까요. 웃음이 멈추지 않아요."
1300005-57 = "3;아카네;03;주인님이 곁에 있기 때문일까요?\n#3;em;[///]"
1300005-58 = "3;아카네;01;고마워요. 주인님이 저를 행복하게 해주셔서……"
1300005-59 = "3;아카네;02;그러니 저도, 주인님을 행복하게 해드리고 싶……\n#3;em;…"
1300005-60 = "2;헬멧단;01\n#2;black\n#2;ar\n#wait;500"
1300005-61 = "3;아카네;04\n2;헬멧단;01\n#2;black\n#2;shake\n#3;m4\n#3;greeting\n#2;h\n#3;h"
1300005-62 = "#na;(툭-)"
1300005-63 = "2;헬멧단;01;으악! 조심해! 눈을 얻다 달고 다니는 거야!\n#2;black\n#2;em;[빠직]\n#2;stiff"
1300005-64 = "3;아카네;06;어머, 죄송합니다. 제가……."
1300005-65 = "3;아카네;05;응?\n#3;em;[?]"
1300005-66 = "2;헬멧단;01;……?\n#2;black\n#2;em;[?]"
1300005-67 = "3;아카네;04;어라?\n#3;shake"
1300005-68 = "2;헬멧단;01;…… 어엇?!\n#2;black\n#2;stiff"
1300005-69 = "2;헬멧단;01;메, 메, 메이드! C&C 아직도 쫓고 있었나?!\n#2;em;[?!]\n#2;black\n#2;shake"
1300005-71 = "#2;hide\n3;아카네;05;아앗! 멈춰요!\n#3;m3\n#3;em;[!]"
1300005-72 = "3;아카네;02;행운이 확실하네요. 주인님과 함께해서!"
1300005-73 = "3;아카네;05;주인님! 저 사람이 블랙 기업의 사주를 받고 밀레니엄 학생들의 개인정보를 훔친 도둑이에요! \n#3;hophop"
1300005-74 = "3;아카네;05;쫓도록 하죠!\n#3;closeup"
1300005-76 = "#na;(결국 아카네와 임무에 성공했다.)"
