[translation]
1300203-1 = "竟然沒加大蒜"
1300203-2 = "夏萊．辦公室"
1300203-3 = ""
1300203-4 = ""
1300203-5 = ""
1300203-6 = "（吃完午餐後，亞伽里帶著比平常開心的表情回來了）"
1300203-7 = "哼哼哼～哼哼哼～♪"
1300203-8 = "啊～今天的午餐真好吃～。#n好久沒發現這麼讚的店家了，真開心。"
1300203-9 = "老師……你午餐又只吃麵包嗎？"
1300203-10 = "這可不行。要是午餐不好好吃，下午工作就沒辦法集中精神了。#n得吃些更有營養的食物才行。"
1300203-11 = "再怎麼麻煩也不要買便利商店隨便解決，請找間餐廳好好用餐。我下次推薦你幾間夏萊附近好吃的餐廳。"
1300203-12 = "[s]「亞伽里中午去了拉麵店嗎？」"
1300203-13 = "哎呀，老師怎麼知道？"
1300203-14 = "沒錯，我今天午餐吃了拉麵。夏萊大樓前面，新開了一家拉麵店。"
1300203-15 = "菜單上面寫說「只要在30分鐘內吃完十人份的巨無霸拉麵就不用錢」，所以我就連續吃了兩碗！真好吃呢～"
1300203-16 = "而且上面還放了滿滿配料，湯汁也很濃郁，是正統的豚骨拉麵。"
1300203-17 = "……話說老師怎麼會知道我中午吃拉麵呢？"
1300203-18 = "咦？你說因為我身上有大蒜味？"
1300203-19 = "哎呀……我都已經仔細刷過牙了，沒想到還是有味道呀……"
1300203-20 = "那家的拉麵確實加了三顆生大蒜，而且我也把湯喝光了……的確勢必會染上大蒜味。"
1300203-21 = "雖然讓老師聞到大蒜味很不好意思，可是不加大蒜的豚骨拉麵又很沒意思……這可該怎麼辦呢？"
1300203-22 = "[s]「我是無所謂啦。」"
1300203-23 = "不行。這對少女來說是非常敏感的問題！"
1300203-24 = "雖然我不想放棄美食，但又不希望自己在老師心中的形象變成「身上帶著大蒜味的學生」……"
1300203-25 = "我得想個辦法才行……"
1300203-27 = "（隔天早晨。一踏入夏萊辦公室，一股強烈的蒜味撲鼻而來……）"
1300203-28 = "老師早安！我等你好久了！"
1300203-29 = "[s]「這，這股強烈的蒜味，到底是……」"
1300203-30 = "我昨天回去之後找了很多種方法，網路上說人只要一直聞相同的味道，久而久之就沒辦法分辨出那種味道了。"
1300203-31 = "所以我想出來的方法——就是讓老師徹底習慣大蒜的味道，這樣一來你就聞不出我身上的大蒜味了！"
1300203-32 = "請看，我替老師準備了很多加了大蒜的料理。"
1300203-33 = "有大蒜麵包，大蒜炒飯，大蒜餃子，醃大蒜……"
1300203-34 = "讓我們一起狂吃大蒜，一起習慣大蒜的味道吧！"
1300203-36 = "（雖然亞伽里準備的食物很美味，但在那之後，蒜味在辦公室殘留了整整一星期……）"
