[translation]
1300009-1 = "Golden Afternoon"
1300009-2 = "Schale Executive Office"
1300009-4 = "..."
1300009-5 = "..."
1300009-6 = ""
1300009-7 = ""
1300009-8 = "Oh, Master. What a coincidence."
1300009-9 = "[s1] \"You made me work all day!\"\n[s2] \"You called me. I wouldn't call that a coincidence.\""
1300009-10 = "Let's not fret over minor details."
1300009-11 = "Let's not fret over minor details."
1300009-12 = "But you are correct to say this is hardly a coincidence."
1300009-13 = "It's more like destiny."
1300009-14 = "..."
1300009-15 = "Heehee. No need to be embarrassed."
1300009-16 = "I...took the liberty of preparing a reward for assisting me in the last mission."
1300009-20 = "A Certain Residence"
1300009-22 = ""
1300009-23 = ""
1300009-24 = ""
1300009-25 = "Hmm. It's cleaner than I thought."
1300009-26 = "This house? It's the place I prepared."
1300009-27 = "Please wait here a moment."
1300009-28 = "Promise me you won't come until I call for you, okay?"
1300009-29 = "Why don't you lie down while you wait? You must be tired from work."
1300009-30 = ""
1300009-31 = "..."
1300009-34 = "Master."
1300009-35 = "Master, wake up."
1300009-38 = "[ns3] Get up and go over.\n[ns4] Sleep a little more..."
1300009-40 = "..."
1300009-41 = "*rustle* *rustle*"
1300009-42 = "...?"
1300009-43 = "Something smells nice."
1300009-44 = "..."
1300009-45 = "*rustle* *rustle*"
1300009-46 = "...?"
1300009-47 = "Something smells nice."
1300009-48 = "(shuffle)"
1300009-50 = "You're up."
1300009-51 = "Heehee. I didn't expect you to actually fall asleep."
1300009-52 = "Well, shall we get started, then? Ahem."
1300009-55 = "― Oh, you're home.[wa:800] "
1300009-57 = "― How was your day?[wa:1040] "
1300009-60 = "― Oh, Master. We just received some of the highest quality tea leaves.[wa:1820] "
1300009-62 = "― Shall I pour you a cup?[wa:1480] "
1300009-65 = "― What's that? This isn't our home?[wa:2020] "
1300009-68 = "― Haha. Don't be silly. Where our home is doesn't matter...[wa:2180] "
1300009-70 = "― ...so long as we're together now."
1300009-73 = "Well? Did you like that little gift I prepared for you?"
1300009-74 = "C&C's Murokasa Akane will always be here to serve you, Master."
