[translation]
1300206-1 = "美食家的尊嚴"
1300206-2 = "格黑娜學園．近郊的中式餐廳"
1300206-3 = "（結束格黑娜學園的工作，在回來的路上去了一趟中餐廳，偶然碰見亞伽里）"
1300206-4 = "哎呀，老師，真巧呢，你是來吃午餐的嗎？"
1300206-5 = "對，我也是。因為這間店有可以吃很多麻婆豆腐的大胃王挑戰。 "
1300206-6 = "老師如果不介意的話，要不要和我一起挑戰呢？"
1300206-7 = "咦？老師只要普通份量的麻婆豆腐就夠了嗎？#n堆得像山一樣高的麻婆豆腐，明明就很享受……"
1300206-8 = "好吧那也沒辦法，我們來點餐吧。"
1300206-9 = "請給我們一份普通麻婆豆腐和一份大胃王麻婆豆腐。"
1300206-10 = "好的。請問大胃王餐點，是給旁邊這位客人嗎？"
1300206-11 = "不，是我的。#n別看我這樣，我對自己的食量很有自信！"
1300206-12 = "呵呵，這樣啊，氣勢不錯呢。不過，我們家的麻婆豆腐可不好對付喔……"
1300206-13 = "請稍等，我立刻把餐點送來。"
1300206-15 = "（總覺得那位店員，笑的很有自信……是我的錯覺嗎？）"
1300206-17 = "讓兩位久等了，這是兩位點的普通麻婆豆腐和大胃王麻婆豆腐。"
1300206-18 = "這道10人份麻婆豆腐，只要在30分鐘內吃完就免費。而且30分鐘內還可以無限續。"
1300206-19 = "……那麼兩位請慢用。"
1300206-20 = "哇～聞起來好辣好香……#n感覺一定很好吃！"
1300206-21 = "那麼，我開動了！"
1300206-22 = "[s]「我要開動了。」"
1300206-23 = ""
1300206-24 = "……嗯？真奇怪，這家店的麻婆豆腐明明不是這個味道啊……？"
1300206-25 = "老師，能讓我吃一口你點的麻婆豆腐嗎？"
1300206-26 = "[s] 把自己點的麻婆豆腐分給她。"
1300206-27 = "（嚼嚼）……原來是這樣。#n竟然還有玩這種小把戲的店家，有點失望呢。"
1300206-28 = "[s]「有什麼問題嗎？」"
1300206-29 = "我比較了一下老師和我點的，大胃王麻婆豆腐明顯特別辣。想必是加入了大量的調味料。……八成是為了妨礙客人完成大胃王挑戰吧。"
1300206-30 = "因為我不挑嘴，所以大家常常會忘記這件事，但我也是美食研究會的一員，我對食物的要求也是很嚴格的。"
1300206-31 = "就算是以份量取勝的大胃王挑戰，身為餐飲業者應該也要有底線才對。而這個舉動……已經越線了。"
1300206-32 = "你不覺得，那些拿食物惡作劇的人……應該遭受該有報應嗎？"
1300206-34 = "……我吃完了！#n麻煩這裡再來一份麻婆豆腐！"
1300206-35 = "（太，太扯了！才開始不到10分鐘，她居然就已經吃完了？）"
1300206-36 = "（那一盤可是10人份的麻婆豆腐耶？！）"
1300206-37 = "不好意思──#n麻煩再給我一份大胃王麻婆豆腐！"
1300206-38 = "不，不好意思，這位客人……既然您已經挑戰成功了，您要不要休息一下……？"
1300206-39 = "你在說什麼呢？一開始不是說「30分鐘內可以無限續」嗎？"
1300206-40 = "既然是挑戰，雙方都要遵守一開始定下的規則才叫公平吧？"
1300206-41 = "就像我也沒有抗議你們故意在大胃王麻婆豆腐加了大量調味料，弄成普通人無法接受的辣度一樣……你不覺得很有道理嗎？"
1300206-42 = "對，對不起！我們不會收兩位的餐錢……拜託請原諒我們吧！"
1300206-43 = "不行。我來這間店是為了吃很多麻婆豆腐，不是來聽你們道歉的。"
1300206-44 = ""
1300206-45 = "好了，請你趕快再給我一盤吧！"
1300206-47 = "（之後，亞伽里大幅刷新了這間店的紀錄，在30分鐘內吃掉了60人份的麻婆豆腐……）"
