[translation]
1300508-1 = "ร้านขายซีดี"
1300508-2 = "ด้านหน้าร้านขายซีดี ย่านการค้า"
1300508-3 = "หืม ครู? บังเอิญจังที่มาเจอกันที่นี่"
1300508-4 = "อื้อ วันนี้ฉันหยุดน่ะ เลยแวะออกมาฟังเพลงที่ร้านขายซีดีนี่"
1300508-5 = "ร้านขายซีดีน่ะสุดยอดเลยนะ เพราะเป็นที่ที่เราสามารถฟังเพลงหลายๆ แนวได้ในที่เดียว"
1300508-6 = "อืม... เพลงนี้ก็ไม่แย่เท่าไหร่"
1300508-7 = "ครูอยากลองฟังดูไหมล่ะ?"
1300508-8 = "[s1] \"ก็ได้\"\n[s2] \"เพลงที่คาโยโกะแนะนำมันค่อนข้างจะ....\""
1300508-9 = "อย่ามัวอึกอักอยู่เลย ลองฟังดูเถอะน่า"
1300508-10 = "อย่ามัวอึกอักอยู่เลย ลองฟังดูเถอะน่า"
1300508-14 = "ดนตรีแจ๊สฟังสบายๆ ค่อยๆ ดังขึ้น...."
1300508-15 = "......"
1300508-16 = ""
1300508-18 = "[ns] \"นี่มัน...ไม่ใช่เพลงแนวเฮฟวี่เมทัลนี่?\""
1300508-19 = "ทำไมถึงคิดว่าฉันจะฟังเพลงเมทัลอีกล่ะ?"
1300508-20 = "แค่ฉันเป็นนักเรียนของเกเฮนน่าไม่ได้หมายความว่าฉันจะชอบฟังแต่เพลงฮาร์ดคอร์หรอกนะ"
1300508-21 = "เพลงแต่ละเพลงมีความหมายในตัวของมันอยู่แล้ว ไม่จำกัดหรอกว่าเป็นเพลงแนวไหน"
1300508-22 = "ฉันชอบเพลงที่เนื้อเพลงสื่อความหมายออกมาได้ดีน่ะ"
1300508-23 = "ครูชอบเพลงแบบไหนเหรอ?"
1300508-24 = "[s] บอกชื่อเพลงที่ชอบกับคาโยโกะ"
1300508-25 = "อืม..... ฉันไม่เคยฟังเพลงพวกนี้เลย"
1300508-26 = "แต่ฉันคงจะชอบแน่ๆ"
1300508-27 = "เพราะเป็นเพลงที่ครูแนะนำมานี่นา"
1300508-28 = "ถ้างั้นฉันจะลองฟังดูนะ..."
1300508-30 = "จากนั้นคุณครูกับคาโยโกะก็ใช้เวลาฟังเพลงด้วยกันตลอดทั้งวัน"
