[translation]
1300315-1 = "Her Secret Notebook"
1300315-4 = "Ah, yes. That's my notebook."
1300315-5 = "Thank you. I'm so sorry to have burdened you with my carelessness."
1300315-6 = "[s1] \"I'm glad I could help.\"\n[s2] \"It was no problem.\""
1300315-9 = ""
1300315-11 = ""
1300315-12 = "I was worried it was lost forever, but here it is."
1300315-13 = "Yes?"
1300315-14 = "You want to know what's in here? If it's private?"
1300315-15 = "[s3] \"You just seem so relieved.\"\n[s4] \"I can tell you treasure it.\""
1300315-18 = "...Ah. I see."
1300315-19 = "You're right. I suppose it seems strange, seeing me so attached to an item."
1300315-20 = "I try not to be materialistic. Most things can be replaced, after all."
1300315-21 = "See, it's just an ordinary record book. It holds every Justice Task Force member's name and contact information."
1300315-22 = "I always emphasize to others how terrible it would be if this got into outside hands, and then I'm the one who misplaced it..."
1300315-23 = ""
1300315-26 = "...You seem disappointed."
1300315-27 = "Well, my notebook is a little special. I've been updating it by hand ever since I was a first-year."
1300315-28 = "Hm? Oh, it's not because of scarcity. We print new ones annually."
1300315-29 = "But... I've developed the habit of keeping personal notes. You could say that I've made the notebook my own."
1300315-30 = "Sensei? Why are you acting so flustered?"
1300315-31 = "[s5] \"Sorry, I didn't mean to peek.\"\n[s6] Hand her the notes that you found near the book."
1300315-34 = ""
1300315-36 = ""
1300315-37 = ""
1300315-38 = ""
1300315-39 = "Ah, I see... These must have spilled out when I dropped the notebook."
1300315-40 = "Don't worry. I appreciate you gathering these. You couldn't help but read a little."
1300315-41 = "...Hm? What are these notes?"
1300315-42 = "I wrote them myself. Is that so strange?"
1300315-43 = "...You're impressed?"
1300315-44 = "You flatter me, Sensei."
1300315-45 = "As Vice President, I'm in charge of handling Justice Task Force assignments."
1300315-46 = "To put the right people in the right place, I must be aware of the members' strengths, weaknesses, personality clashes..."
1300315-47 = "It's not difficult anymore. I just pay a bit of attention and check in with everyone occasionally."
1300315-48 = "I've been doing this for three years, so there's not much to add nowadays."
1300315-49 = "[s7] \"I can tell you care...\"\n[s8] \"You wrote down favorite foods, allergies, birthdays...\""
1300315-52 = "Hobbies, habits, and milestones might not seem important..."
1300315-53 = "They're certainly not useful when it comes to the actual work we do."
1300315-54 = "But these people aren't simply Justice Task Force members. They're ultimately all students, aren't they?"
1300315-55 = "Of all the clubs, they went out of their way to choose the one where they work hard and are frequently unrecognized."
1300315-56 = "My only wish is for them to feel...special. I'd like to make them feel valued."
1300315-57 = "Of course, you would know all about this, right, Sensei?"
1300315-58 = "I must come off as very preachy. My apologies."
1300315-59 = "[s9] \"I'm so moved!\"\n[s10] \"Hasumi...! That's wonderful!\""
1300315-62 = "Please...you're embarrassing me."
1300315-63 = "Hm? Do I only write about Justice Task Force members?"
1300315-64 = "Well, it is a Justice Task Force book, after all. It has a clear purpose."
1300315-65 = "And...I've mostly stayed within parameters."
1300315-66 = "Heehee. But to be honest, I don't know many people outside of the Force."
1300315-67 = "So, while I take notes on everyone I find precious, it just so happens that they're all my fellow club members."
1300315-68 = "...Excuse me? You find WHAT strange, precisely?"
1300315-69 = "That there's a Justice Task Force member with a code name who shares your birthday and passion for gacha games?"
1300315-70 = ""
1300315-72 = ""
1300315-73 = ""
1300315-74 = "Sensei, it's been a pleasure speaking with you."
1300315-75 = "But I'm afraid I've already taken up so much of your time. You're clearly busy."
1300315-76 = "[s] \"Hm? Oh, it's not too bad—\""
1300315-77 = "I simply can't! I've already bothered you so much with returning my notebook..."
1300315-78 = "Oh, and I just remembered that there's an urgent emergency! I must go!"
1300315-79 = "Please excuse me!"
1300315-80 = ""
1300315-82 = ""
1300315-88 = "Hasumi darted out immediately."
