[translation]
1301206-1 = "การทัศนศึกษาของเด็กอนุบาล"
1301206-2 = "ด้านหน้าอาคารส่วนกลาง สถาบันฝึกตำรวจวัลคิรี่"
1301206-4 = "ยินดีต้อนรับทุกคนสู่อาคารหลักของสถาบันฝึกตำรวจวัลคิรี่ค่ะ!"
1301206-5 = "วันนี้ฉันคิริโนะ เจ้าหน้าที่จากสำนักรักษาความปลอดภัยจะช่วยแนะนำสถานที่ให้ทุกคนเองค่ะ"
1301206-6 = "เอ๋~? สำนักรักษาความปลอดภัยเหรอ? ทำไมถึงไม่ใช่นักเรียนจากสำนักความมั่นคงหรือ#nสำนักงานสืบสวนล่ะ?"
1301206-7 = "อุตส่าห์อยากฟังเรื่องราวการปราบอาชญากรที่น่ากลัวๆ แท้ๆ..."
1301206-8 = "ฝันหรือเปล่า? นักเรียนของทางสำนักความมั่นคงกับสำนักงานสืบสวนคงจะงานยุ่ง เลยให้นักเรียนจาก#nสำนักรักษาความปลอดภัยมาแนะนำแทนน่ะสิ"
1301206-9 = "มะ... ไม่ใช่นะคะ! ถึงจะไม่เท่าสำนักความมั่นคง แต่ที่สำนักรักษาความปลอดภัยก็งานยุ่งเหมือนกันนะคะ"
1301206-10 = "พวกเราจะต้องตามหาเจ้าของของสิ่งของที่ลืมไว้ หรือออกตรวจตราเมืองว่ามีเรื่องอันตรายอะไรรึเปล่า..."
1301206-11 = "อะไรกัน ไม่เห็นน่าสนุกเลย~"
1301206-12 = "งานเล็กๆ น้อยๆ ของสำนักรักษาความปลอดภัยไม่เห็นน่าสนใจเลย~"
1301206-13 = "ตะ...แต่ว่า... เรื่องนั้นมัน..."
1301206-14 = "[s1] \"คิริโนะ อย่าเพิ่งลนลานสิ\"\n[s2] \"เริ่มแนะนำตามคู่มือกันเถอะ\""
1301206-15 = ""
1301206-16 = ""
1301206-17 = "ชะ...ใช่แล้วค่ะ! ก่อนอื่นตามฉันไปที่อาคารส่วนกลางก่อนนะคะ"
1301206-18 = "ฉันจะพาทุกคนดูรอบๆ อาคารพร้อมกับเล่าประวัติของสถาบันฝึกตำรวจวัลคิรี่ให้ฟังค่ะ!"
1301206-20 = "ที่นี่คือทางเข้าหอพักนักเรียนของสถาบันฝึกตำรวจวัลคิรี่ค่ะ!"
1301206-21 = "นักเรียนส่วนใหญ่ของสถาบันวัลคิรี่จะอาศัยอยู่ในหอพักของโรงเรียน เพื่อให้สามารถออกปฏิบัติการ#nได้อย่างรวดเร็วในกรณีที่เกิดเหตุด่วนค่ะ"
1301206-22 = "หินจารึกที่อยู่บริเวณด้านหน้าทางเข้าหอพัก คือหินที่จารึกคำกล่าวของท่านประธานคนแรกของเรา#nและเพื่อเตือนให้นักเรียนทุกคนระลึกถึงความรับผิดชอบในฐานะตำรวจ จึงนำมาตั้งไว้ตรงนี้ค่ะ"
1301206-23 = "ซึ่งนั่นก็คือ 'ตำรวจจะต้องคำนึงถึงความปลอดภัยของพลเมืองก่อนเสมอ และปฏิบัติการด้วยหัวใจ#nที่เปี่ยมไปด้วยจิตใจที่ต้องการบริการ...’"
1301206-24 = "เฮ้อ~ ไม่เห็นสนุกเลย~"
1301206-25 = "เรื่องจู้จี้น่าเบื่อพวกนั้นมันสำคัญตรงไหนกัน?"
1301206-26 = "ที่พวกเราอยากรู้น่ะเป็นเรื่องการจับกุมคนร้ายอย่างเท่ๆ ต่างหาก!"
1301206-27 = "ตะ...แต่ว่าการเรียนรู้ภาระหน้าที่ของตำรวจที่ถูกต้องก็เป็นเรื่องที่สำคัญนะคะ"
1301206-28 = "ตำรวจที่ออกปฏิบัติการโดยไม่คำนึงถึงความปลอดภัยของพลเมืองก็ไม่ต่างจากพวกอาชญากรหรอกค่ะ!"
1301206-29 = "พี่สาวเลิกพูดเรื่องพวกนั้นเถอะ เล่าเรื่องพวกคนร้ายที่น่ากลัวๆ ให้ฟังหน่อยสิ!"
1301206-30 = "พี่สาวเคยออกปฏิบัติการแล้วยิงผู้ร้ายบ้างรึเปล่า?"
1301206-31 = "หรือว่าพี่สาว... เป็นนักเรียนของทางสำนักรักษาความปลอดภัยเลยยิงปืนไม่เป็นงั้นเหรอ?"
1301206-32 = "มะ...ไม่ใช่นะคะ! ทักษะการยิงปืนเป็นพื้นฐานที่นักเรียนของโรงเรียนวัลคิรี่ทุกคนพึงมีค่ะ"
1301206-33 = "อีกอย่าง... ทั้งเหตุการณ์ที่เกิดขึ้นที่อาคารส่วนกลางและเหตุการณ์จับตัวประกันเมื่อคราวก่อน#nฉันก็เป็นคนช่วยคลี่คลายนะคะ! ฮะ...ฮะ...ฮะ..."
1301206-34 = "[s3] \"...\"\n[s4] \"ว้าว ถามจริง...?\""
1301206-35 = ""
1301206-36 = "(กระซิบ) ยะ...อย่ามองฉันด้วยสายตาน่าสงสัยแบบนั้นสิคะ! เดี๋ยวพวกเด็กๆ จะสงสัยนะคะ"
1301206-37 = ""
1301206-38 = "(กระซิบ) ยะ...อย่ามองฉันด้วยสายตาน่าสงสัยแบบนั้นสิคะ! เดี๋ยวพวกเด็กๆ จะสงสัยนะคะ"
1301206-39 = "พี่สาวยิงปืนตอนเหตุการณ์จับตัวประกันด้วยเหรอ? ไม่กลัวคนร้ายเหรอ?"
1301206-40 = "นะ...แน่นอนว่าฉันเองก็กลัวอยู่บ้างค่ะ แต่ว่าตอนนั้นมีตัวประกันถูกจับอยู่ด้วย..."
1301206-41 = "คิดว่างานของสำนักรักษาความปลอดภัยจะเป็นเรื่องเล็กๆ น้อยๆ ซะอีก เจ๋งไปเลย!"
1301206-42 = "(ฮือ... ถึงฉันจะไม่ได้พูดโกหกก็เถอะ แต่การหลอกเด็กที่ใสซื่อบริสุทธิ์แบบนี้มันเป็นเรื่อง#nที่น่าเจ็บปวดจริงๆ)"
1301206-43 = "(แต่เพราะอย่างนั้นเลยทำให้เด็กๆ กลับมาสนใจได้อีก ถ้าเป็นแบบนี้ก็คงทัศนศึกษาต่อได้#nอย่างราบรื่นแน่นอน)"
1301206-44 = "พี่สาว กระบอกน้ำที่ติดอยู่ที่เอวคืออะไรอ่ะ? นั่นก็เป็นอาวุธด้วยเหรอ?"
1301206-45 = "อ๋อ... นี่คือระเบิดควันค่ะ ถึงจะไม่ได้ทรงพลังเท่ากับระเบิดมือ แต่มันก็ช่วยสกัดการมองเห็นของ#nอีกฝ่ายได้ ดังนั้นเวลาปฏิบัติการเข้าช่วยเหลือตัวประกันจะใช้งานได้เหมาะมากๆ เลยค่ะ"
1301206-46 = "เหตุการณ์จับตัวประกันที่เกิดขึ้นที่ชิบะทาวน์เมื่อเดือนที่แล้ว ระเบิดควันพวกนี้ก็ช่วยได้เยอะเลยนะคะ!"
1301206-47 = "หมายถึงเหตุการณ์ที่มีพวกนักเรียนติดอาวุธหนักบุกโจมตีร้านพุดดิ้งรึเปล่า?"
1301206-48 = "พี่สาวก็มีส่วนร่วมในปฏิบัติการนั้นด้วยสินะ!"
1301206-49 = "สุดยอดเลย! เก่งจัง!"
1301206-50 = "แหะๆ..."
1301206-51 = "(ถึงระเบิดควันที่ฉันขว้างออกไปจะช่วยอะไรไม่ได้มากก็เถอะ...)"
1301206-52 = "แล้วพวงกุญแจข้างๆ ล่ะ?"
1301206-53 = "นี่ไม่ใช่พวงกุญแจนะคะ แต่เป็นกุญแจมือค่ะ เอาไว้ใช้ในตอนจับกุมพวกอาชญากรค่ะ"
1301206-54 = "เวลาใช้กุญแจมือจะต้องระมัดระวังมากๆ เพราะกุญแจมือพวกนี้แข็งแรงมาก และจะถอดออกไม่ได้#nถ้าไม่มีกุญแจค่ะ"
1301206-55 = "จริงเหรอ? ดูเหมือนมันจะหลุดออกมาได้ง่ายๆ เลยนะ..."
1301206-56 = "ไม่เลยค่ะ เพราะภายในกุญแจมือมีฟันเฟืองอยู่จำนวนมาก แค่ใช้แรงดึงอย่างเดียวจะไม่สามารถ#nปลดกุญแจมือออกได้หรอกค่ะ"
1301206-57 = "ถ้างั้น... ฉันจะสาธิตวิธีการใช้กุญแจมือให้ดูแล้วกันนะคะ"
1301206-58 = "ก่อนอื่น หลังจากควบคุมคนร้ายไม่ให้เคลื่อนไหวได้แล้ว ก็เอากุญแจมือมาใส่ที่ข้อมือข้างหนึ่ง"
1301206-59 = ""
1301206-61 = "และพอปลดกุญแจมืออีกข้างหนึ่งออกจากโครงแล้ว ก็นำมาคล้องกับมืออีกข้างของคนร้ายค่ะ"
1301206-62 = ""
1301206-64 = "เท่านี้ก็จับกุมได้สำเร็จแล้วค่ะ!"
1301206-65 = ""
1301206-67 = ""
1301206-70 = "อย่างที่เห็นค่ะ กุญแจมือพวกนี้แข็งแรงทนทานมากจนพวกคนร้ายไม่สามารถถอดออกหรือหนีไปได้ค่ะ"
1301206-71 = "ว้าวววว สุดยอดเลย!"
1301206-72 = "เพิ่งเคยเห็นการใช้กุญแจมือของจริงครั้งแรกเลย!"
1301206-73 = "ฮิฮิ ฉันดีใจที่ทุกคนชอบนะคะ"
1301206-74 = "ถ้างั้นฉันจะใช้กุญแจไขกุญแจมือออก..."
1301206-75 = "อ๊ะ?!"
1301206-76 = ""
1301206-80 = ""
1301206-81 = "(มือลื่นจนทำกุญแจหล่นไปแล้ว...!)"
1301206-82 = "(ดูเหมือนจะหล่นลงไปในท่อระบายน้ำไปแล้วด้วย...)"
1301206-83 = "มีอะไรเหรอคะพี่สาว? มีปัญหาอะไรเหรอคะ?"
1301206-84 = "เอ่อ คือ...คือว่า..."
1301206-87 = "― (ทะ... ทำยังไงดีคะ...?)[wa:890] "
1301206-89 = "― (ยะ... แย่แล้ว! มะ... มันถอดไม่ออก...?!)[wa:2010] "
1301206-92 = "[ns] \"ทำกุญแจหายรึเปล่าน่ะ?\""
1301206-93 = "― ...คะ? ไม่ใช่ ไม่ใช่นะคะ![wa:480] "
1301206-95 = "― เจ้าหน้าที่ตำรวจอย่างฉัน จะทำกุญแจหายได้ยังไงกันคะ![wa:2030] "
1301206-98 = "― เพราะงั้น... นี่คือ...[wa:920] "
1301206-100 = "― การสาธิต... การฝึกหลบหนีค่ะ![wa:350] "
1301206-103 = "― ในกรณีที่เกิดความผิดพลาด และเกิดถูกจับใส่กุญแจมือเข้า [wa:250] "
1301206-105 = "― ฉันจะสาธิตวิธี หลบหนีให้ทุกคนได้ดูค่ะ![wa:500] "
1301206-108 = "[ns] \"เทคนิคสำคัญแบบนั้นแสดงให้คนอื่นดูได้งั้นเหรอ?\""
1301206-109 = "― ไม่ต้องห่วงค่ะ! ถ้าเป็นตำรวจที่ได้รับการฝึกมาอย่างดีเหมือนกับฉันล่ะก็[wa:250] "
1301206-111 = "― แค่นี้ง่ายมากเลยค่ะ![wa:120] "
1301206-114 = "― ฮึ่บบบ...! ฮึ่บบบ...![wa:1670] "
1301206-117 = "― ขอโทษนะคะ...[wa:10] "
1301206-119 = "― ช่วยฉันด้วยค่ะ คุณครู...[wa:760] "
1301206-122 = "(จากนั้นคิริโนะก็อยู่ในสภาพถูกจับใส่กุญแจมืออยู่พักหนึ่ง จนกระทั่งมีนักเรียนโรงเรียนวัลคิรี่คนอื่น#nเข้ามาช่วย...)"
1301206-124 = ""
1301206-125 = ""
1301206-126 = ""
1301206-127 = "เฮ้อ การแนะนำทัศนศึกษาวันนี้ล้มเหลวโดยสิ้นเชิงเลยค่ะ..."
1301206-128 = "ทั้งที่อยากแสดงภาพพจน์เท่ๆ ของตำรวจให้เด็กๆ เห็นแท้ๆ แต่กลายเป็นว่าดันแสดงให้เห็น#nถึงท่าทางที่ไม่น่าดูและดันถูกจับใส่กุญแจมือเหมือนคนร้ายอีก..."
1301206-129 = "พอเห็นแบบนี้แล้ว คงไม่มีเด็กคนไหนชื่นชมตำรวจอีกแน่ๆ เลยค่ะ"
1301206-130 = "[s5] \"ไม่เป็นไรหรอก\"\n[s6] \"คิริโนะพยายามเต็มที่แล้วนี่นา\""
1301206-131 = "แต่ว่า..."
1301206-132 = "แต่ว่า..."
1301206-133 = "พี่สาววว!"
1301206-134 = "เอ๋? เด็กนักเรียนที่มาทัศนศึกษาวันนี้? มีอะไรเหรอคะ?"
1301206-135 = "ขอบคุณที่มาแนะนำทัศนศึกษาให้พวกเราวันนี้นะ สนุกมากๆ เลย!"
1301206-136 = "แต่ว่า... วันนี้ฉันทำแต่เรื่องผิดพลาดทั้งนั้นเลย"
1301206-137 = "ฉันไม่ได้แสดงให้ทุกคนเห็นส่วนที่ยอดเยี่ยมของโรงเรียนตำรวจวัลคิรี่ แถมยังแสดงด้านที่ไม่น่า#nชื่นชมให้ทุกคนได้เห็นอีก..."
1301206-138 = "แต่ว่าพี่สาวทำแบบนั้นเพราะพวกเราขอร้องนี่นา?"
1301206-139 = "จริงด้วย ฉันชอบมากๆ เลยที่พี่สาวยอมรับฟังคำขอเล็กๆ น้อยๆ ของเรา!"
1301206-140 = "ตอนที่ไปทัศนศึกษาที่โรงเรียนอื่น พวกเขามักไม่ค่อยสนใจเพราะพวกเราเป็นแค่เด็ก"
1301206-141 = "พอโตขึ้นแล้วพวกเราอยากเป็นตำรวจที่ใจดีเหมือนพี่สาวบ้างจัง!"
1301206-142 = ""
1301206-144 = ""
1301206-145 = "ทุกคน... ขอบคุณมากนะคะ"
1301206-146 = "ฉัน...คิริโนะ จะพยายามมากขึ้นเพื่อเป็นเจ้าหน้าที่ตำรวจที่ดีสำหรับทุกคนค่ะ!"
1301206-147 = "[s] \"ดีจังเลยนะที่ทุกคนสนุกแบบนี้\""
1301206-148 = "ค่ะ โชคดีที่ความมุ่งมั่นของฉันสื่อไปถึงเด็กนักเรียนทุกคนนะคะ"
1301206-149 = "แต่ว่าการทำพลาดก็คือการทำพลาดค่ะ ฉันจะใช้เรื่องในวันนี้เป็นบทเรียนเพื่อไม่ให้เกิด#nข้อผิดพลาดซ้ำอีกค่ะ"
1301206-150 = "ฉันจะฝึกฝนให้มากกว่าเดิมเผื่อคราวหน้าทำกุญแจหายก็จะได้ปลดกุญแจออกได้เองค่ะ!"
1301206-151 = "[s] \"เธอเข้าใจอะไรผิดรึเปล่า...\""
