[translation]
13050-1 = "Episode 5;Trans-Desert Railway"
13050-2 = "Admittance accepted. Victory pose!"
13050-3 = "Why's it so cramped here? Where're we supposed to sit? On the ground?"
13050-4 = ""
13050-7 = ""
13050-8 = "..."
13050-10 = "Officers, please refrain from touching others' belongings without permission. No, there's no fridge here. Just sit and be still."
13050-11 = "Jumping on chairs is the opposite of being still. Sit."
13050-12 = "U-Um..."
13050-13 = "Apologies again. Is this the Abydos Foreclosure Task Force club room we are standing in?"
13050-15 = ""
13050-17 = ""
13050-18 = ""
13050-20 = ""
13050-21 = ""
13050-22 = ""
13050-23 = ""
13050-24 = ""
13050-26 = "Shiroko! Whatever you're thinking, hold your horses!"
13050-27 = "...I wasn't going to do anything. I swear."
13050-29 = "Yes. We're the Foreclosure Task Force."
13050-30 = "Well, you found us. Let's get to it, Highlanders."
13050-31 = ""
13050-34 = ""
13050-35 = "Is this...eatable? "
13050-36 = "Hellooo, aren't we guests? Where's our tea?"
13050-38 = "A-Ah! Right... Just a moment..."
13050-39 = "Please don't strain yourselves for their sake. We won't be here long."
13050-40 = "Boo. Booooo!"
13050-41 = "If you could, for once, properly assess the situation, you would understand that we're not welcome guests here, officers."
13050-42 = "These agents were willing to stand up against the giant that is Kaiser Corporation to protect their school."
13050-43 = "Consider this a train engine that could explode at any moment."
13050-44 = ""
13050-46 = ""
13050-47 = ""
13050-48 = ""
13050-49 = ""
13050-50 = "Um..."
13050-52 = "Not that there is any need for real concern. I would easily dispose of them if a fight broke out."
13050-53 = ""
13050-56 = ""
13050-57 = ""
13050-58 = ""
13050-59 = ""
13050-60 = "Deep breaths, Shiroko! Deep breaths!"
13050-61 = ""
13050-64 = ""
13050-66 = "Wasn't going to. Double swear."
13050-67 = "Why're you acting all innocent?! I know you were about to blow a fuse!"
13050-68 = "Oops."
13050-69 = ""
13050-71 = ""
13050-72 = "[ns1] \"Let's get to the point, Suou.\"\n[ns2] \"You came to speak with the Foreclosure Task Force?\""
13050-75 = "Yes."
13050-76 = "Schale's Sensei, correct? My apologies for the earlier situation."
13050-77 = "However, I'm afraid we are not the ones who you will be negotiating with."
13050-78 = "*tchhk* Area secured. It is safe to proceed."
13050-79 = "*cough* *cough* Thank goodness. How can there be so much dust in one place?"
13050-80 = "Yes, how barbaric. I'd rather not stay in this toxic environment any longer than necessary. Let's get indoors."
13050-81 = "Wh-Who are these punks?"
13050-82 = "Please watch your language. These are your creditors, after all."
13050-83 = "...Creditors?"
13050-84 = "Like...our creditors? You brought those sharks here?!"
13050-85 = "Let's lower our voices a little bit, Serika."
13050-86 = "It would appear these are the people who bought out the derivative bonds..."
13050-87 = "[s] \"I suppose we have no other option but to hear them out.\""
13050-88 = "Okay..."
13050-90 = "..."
13050-92 = "Excuse me."
13050-93 = "Hmph. So this is the Abydos Student Council room. It's even more cramped than I expected."
13050-94 = "Nice to meet you. We're the private equity fund invested in this business. To you, we're Abydos' new creditors."
13050-95 = "And I'm their legal representative, speaking on behalf of their interests."
13050-97 = "W-Welcome..."
13050-98 = "Who're you people? Wasn't Nephthys the one that bought out the bonds? You don't seem like Nephthys guys to me."
13050-100 = "You are correct. They did acquire the rights for Abydos' Trans-Desert Railway at a rather exorbitant price."
13050-101 = "However, they couldn't afford such a sum all on their own. It required the funds of many different interested parties."
13050-102 = "They created a private equity fund to meet their ends. We're their investors."
13050-104 = "Private equity fund?"
13050-105 = "It's a privately organized investment group, usually made up of a handful of interested parties."
13050-107 = "As the young lady says. There are many other investors besides just us."
13050-108 = "The Debt Labor Union and Pawnbroker Union here, as well as the Foreclosure Auction Guild, Gelatin Gummies, Zako Business, and—"
13050-110 = "A bunch of sketchy people."
13050-111 = "Ahem! Hmm!"
13050-112 = "Hahaha. She isn't wrong. I also used to trade stolen goods on the black market myself."
13050-113 = "We're not the type of people who like to stand out. Which is where Nephthys, a legitimate company in good public standing, comes in as the sparkling face of it all."
13050-114 = "..."
13050-115 = "You guys just sound shadier and shadier."
13050-116 = "Uh... Um..."
13050-117 = ""
13050-119 = ""
13050-120 = "[ns3] \"I'm sorry, but do you have any proof that you're Abydos' creditors?\"\n[ns4] \"It's to the benefit of both sides to ensure everything's in order.\""
13050-123 = "You dare doubt us?"
13050-124 = "How unpleasant."
13050-125 = "Now, now. Let's all calm down and discuss this like civilized adults."
13050-127 = "*tchhhk*... You have my guarantee that these creditors are legitimate."
13050-128 = "Huh? Who is it now?"
13050-129 = "B-Butler...?"
13050-130 = "You know this person, Nonomi?!"
13050-131 = "Yes. He's an officer of Nephthys Group...as well as the butler who essentially raised me."
13050-133 = "It's been a while, my lady. I'm sorry our meeting had to be under these circumstances."
13050-134 = ""
13050-136 = ""
13050-137 = "I will explain the situation. We organized a private equity fund to raise money and purchase the bonds."
13050-138 = "You'll see their names listed on these contracts for our private equity fund. I'll send you a copy, so please feel free to verify."
13050-139 = "Ah, yes... Thank you."
13050-140 = "With a quick glance, everything they're saying appears to be true. Mm... I see here their affiliations and the rights to the bonds."
13050-142 = "Hmph! As we said!"
13050-143 = "That's proof enough, correct?"
13050-144 = "[s] \"...Yes. Thank you for your patience.\""
13050-146 = "Huh. So they weren't sketchy con artists."
13050-147 = "Serika, please..."
13050-148 = "Hahaha. As long as we're now all on the same page... Moving on."
13050-149 = "As the creditors of this fund, we came here to discuss a rather important issue with you all."
13050-150 = "About the Trans-Desert Railway?"
13050-152 = "..."
13050-154 = "Ah. Yes, yes. Naturally, you students did your homework."
13050-155 = "You're correct. No point in beating around the bush. Our goal is to acquire all rights for the Trans-Desert Railway."
13050-156 = ""
13050-158 = ""
13050-160 = "*nod* *nod*"
13050-161 = "Which is why the private equity fund exists."
13050-163 = "We bought these bonds from Kaiser at nearly fraudulent prices all so we could acquire the rights to the railway."
13050-164 = "Those bonds included the rights to the construction of any uncompleted railways. Therefore, Highlander Academy's earlier actions were breaking no laws."
13050-165 = "Duh! That's what we've BEEN saying. We have the rights, so we getta do what we want. "
13050-166 = "Yuppies. Whatever we want!"
13050-167 = ""
13050-169 = ""
13050-170 = "Please don't antagonize them, officers."
13050-171 = "Um... I'm failing to grasp why you would want the Trans-Desert Railway to begin with."
13050-172 = "Please explain, Butler. Why are you doing this?"
13050-173 = "It appears I'm in a bit of an uncomfortable position... *sigh*"
13050-174 = "I'll handle this, then. Young Nephthys lady."
13050-175 = "I understand the Trans-Desert Railway project is a bit of a sore topic for both Nephthys and Abydos. After all, it singlehandedly accelerated this district's downfall."
13050-176 = "I don't want to hear that from you! You need to tell me what Nephthys is thinking, Butler!"
13050-177 = "It was a dangerous, reckless project to begin with! In fact, building that kind of transportation infrastructure made no sense in this desolate place. "
13050-178 = "There were no resources, no trade, not even an economy to speak of in Abydos at that point!"
13050-179 = "It drained Nephthys and Abydos of all their remaining capital, and then was left to rot. If it weren't for that project...!"
13050-180 = "After all of the pain it caused, you want it back? Why? Why, Butler?"
13050-182 = "What could be the purpose? More pain? More casualties? What is Nephthys thinking?!"
13050-183 = "Calm down, Nonomi."
13050-184 = "Nonomi..."
13050-185 = ""
13050-187 = ""
13050-188 = "...Interesting. But we didn't come here to be interrogated. Let's get to the issue at hand."
13050-189 = "However, before we begin..."
13050-190 = "If you don't mind, I'd like this discussion to move forward with only the involved parties."
13050-191 = "Would anyone who is not a member of the Abydos Student Council please leave?"
13050-192 = "All right. Let's go."
13050-193 = "H-Hey! Keep your dirty paws off of me!"
13050-194 = "Wah. Do we have to? Hikari wanted to play more..."
13050-195 = ""
13050-197 = ""
13050-198 = "I'll take my leave as well."
13050-199 = ""
13050-201 = ""
13050-202 = ""
13050-203 = "Th-Then who will represent Nephthys?"
13050-204 = "Overseer Suou will serve as our representative."
13050-205 = "...Excuse me?"
13050-206 = "I see no problem with it. She may be a Highlander student, but she is currently employed by Nephthys."
13050-207 = "She may be a member of the CCC, but she's also one of ours. I consider her trustworthy."
13050-208 = "Now then, I have other matters to attend to."
13050-209 = ""
13050-211 = ""
13050-212 = "..."
13050-214 = ""
13050-216 = ""
13050-217 = "What in the world is happening..."
13050-218 = "..."
13050-219 = "Um..."
13050-220 = "[s] \"...\""
13050-222 = "Hm? I believe I asked for the Abydos Student Council. To my knowledge, that should only include Takanashi Hoshino."
13050-224 = "N-No way! We're members of the student council too!"
13050-225 = "As she said! The Foreclosure Task Force is the official student council, appointed by our advisor here!"
13050-226 = "[s] \"Correct. As their teacher, I've approved it.\""
13050-227 = "...I see. Hm."
13050-228 = "How odd. The paperwork here states that the only person affiliated with the Abydos Student Council is Miss Hoshino... So there's another student council called the Foreclosure Task Force, as you say?"
13050-229 = "Th-That's..."
13050-231 = "Ah, ah. That's on me. It's because I'm technically affiliated with both."
13050-232 = "The Abydos Student Council may hold the official name, but the Foreclosure Task Force has acted as the student council for years now."
13050-233 = "Hm... It's rather complicated, but I suppose I understand."
13050-234 = "Then, please take a look at this."
13050-235 = ""
13050-237 = ""
13050-239 = "This...?"
13050-240 = "This document was...happened upon in Highlander Academy's document storage recently."
13050-242 = "It's a contract written by the previous Abydos Student Council president, Kuchinashi Yume."
13050-243 = ""
13050-246 = ""
13050-248 = "...!!"
13050-250 = "Next Episode;Sales Contract"
