[translation]
13080-1 = "ตอนที่ 8;สภานักเรียนอะบิดอส 1"
13080-5 = "[ns1] จัดการเอกสารที่รวบรวมมาทั้งคืน\n[ns2] \"พอจะรู้เรื่องที่จำเป็นแล้วละ... งั้นตอนนี้ก็...\""
13080-6 = ""
13080-7 = ""
13080-10 = ""
13080-11 = "กำลังสแตนด์บาย คุณครู [USERNAME] มีอะไรที่ต้องการเหรอคะ? "
13080-12 = "[s] \"อ้อ ขอบใจนะพลาน่า แล้วอะโรน่าล่ะ?\""
13080-13 = "รุ่นพี่อะโรน่ากำลังหลับอยู่ค่ะ รุ่นพี่ขี้เซาน่ะค่ะ เพราะงั้นถ้ามีงานอะไรจะสั่ง ก็ให้สั่งคนขยันอย่างฉันได้#nเลยค่ะ"
13080-14 = "[s3] \"ขอบใจนะ ถ้างั้น...\"\n[s4] สั่งงานพลาน่า"
13080-15 = ""
13080-16 = ""
13080-18 = ""
13080-19 = "รับทราบ แค่นี้เรื่องง่ายๆ ค่ะ เดี๋ยวฉันก็ทำเสร็จแล้วค่ะ"
13080-20 = "แต่ที่สำคัญกว่านั้นคือ คุณครูน่าจะต้องพักสักหน่อยนะคะ การทำงานโต้รุ่งไม่ดีต่อสุขภาพค่ะ"
13080-21 = "[s] \"อื้ม แต่ครูต้องไปที่อะบิดอสตอนนี้เลย ครูไม่มีเวลาแล้ว\""
13080-22 = "เข้าใจแล้วค่ะ ถ้างั้น..."
13080-23 = ""
13080-25 = ""
13080-26 = ""
13080-27 = ""
13080-28 = "ตรวจพบปรากฏการณ์ผิดปกติ"
13080-29 = ""
13080-31 = ""
13080-33 = "[ns] \"พลาน่า...? เป็นอะไรไปน่ะ?\""
13080-34 = ""
13080-46 = "..."
13080-47 = "อะไรกัน...?"
13080-48 = "กระผมคำนวณผิดพลาดงั้นเหรอ...? ทำไมกัน...?"
13080-51 = "[ns] \"กะ... เกิดอะไรขึ้นน่ะ?!\""
13080-53 = "[ns] \"ระเบิดเหรอ...?! แต่เราดันไม่เป็นอะไรเลย...?!\" "
13080-54 = ""
13080-56 = "กะ... เกิดเรื่องใหญ่แล้วค่ะ! คุณครู!"
13080-57 = "[s] \"อะโรน่า? นี่มันเรื่องอะไรกัน...?!\""
13080-60 = "อาคารชาเล่ต์ระเบิดค่ะ!"
13080-61 = "แต่ที่สำคัญกว่านั้นคือ... พลาน่าจัง...!!"
13080-62 = ""
13080-64 = ""
13080-66 = ""
13080-67 = "ฉันใช้การคุ้มกันฉุกเฉิน... เพื่อให้คุณครูปลอดภัย..."
13080-68 = "แต่ว่า... ฉันทำเกินกว่านี้... ไม่ไหวแล้ว..."
13080-69 = ""
13080-71 = ""
13080-73 = "พะ... พลาน่าจัง?!"
13080-75 = "ฉันไม่อยากเห็นคุณครูบาดเจ็บอีกเป็นครั้งที่สอง..."
13080-76 = "[s] \"พลาน่า?! เป็นอะไรหรือเปล่า?!\""
13080-77 = "มะ... ไม่เป็นไรหรอกค่ะคุณครู! พลาน่าจังแค่สลบไปน่ะค่ะ! แต่ว่า เรื่องใหญ่กว่านั้นคือ... "
13080-78 = ""
13080-88 = "[ns] \"...!!!\""
13080-96 = "[ns] (สติเราค่อยๆ...)"
13080-102 = ""
13080-103 = "เป็นอย่างนี้เองสินะ... "
13080-104 = "ระบบคุ้มกันของกล่องนั่นแข็งแกร่งกว่าที่กระผมคำนวณไว้มากเลยนะครับ"
13080-105 = "อาวุธที่ทำลายกำแพงเมืองแห่งเจริโค... [ruby=ARK]หีบ[/ruby]ที่ทำให้เกิดปาฏิหาริย์อันน่าฉงน... กระผมอาจจะประเมินมันต่ำไปก็ได้..."
13080-106 = "ฮึ่ม... แต่ก็ไม่เป็นไรหรอก ถึงจะเพิ่งมารู้เอาตอนนี้ว่าต้องแก้ไขวิธีโจมตี แต่ก็ไม่ได้ถือว่าไร้ความหมาย#nหรอกครับ"
13080-107 = ""
13080-109 = ""
13080-110 = "เพราะวิธีโจมตีที่ 2 <ฝืนขีดจำกัดของร่างกายไม่ได้> ... มันยังคงมีผลอยู่ครับ"
13080-111 = "เรื่องราวที่สำคัญที่สุดกำลังดำเนินอยู่ในที่ที่ไร้ตัวตนของครู ต่อให้ครูฟื้นขึ้นมาก็คงสายไปแล้วละครับ"
13080-113 = "เอาละ ถ้างั้นก็มาเล่นกันต่อเถอะครับ"
13080-120 = ""
13080-121 = "คุณครูไม่รับโทรศัพท์เลยค่ะ..."
13080-122 = ""
13080-124 = ""
13080-125 = "อืม..."
13080-126 = "หรือว่าจะเกิดเรื่องอะไรขึ้นหรือเปล่าคะ?"
13080-127 = "ไม่ใช่ว่าหลับอยู่หรอกนะ?"
13080-129 = "ที่ผ่านมาก็มีหลายครั้งที่ติดต่อไม่ได้... แต่คุณครูก็บอกว่าจะมาล่วงหน้านี่นา..."
13080-130 = "แล้วรุ่นพี่โฮชิโนะล่ะ?"
13080-131 = ""
13080-133 = ""
13080-134 = "รุ่นพี่ก็ติดต่อไม่ได้ค่ะ... "
13080-136 = "จริงๆ เลย ทุกคนไปทำอะไรกันอยู่นะ? "
13080-137 = "..."
13080-141 = "เช้าแล้วสินะ... "
13080-142 = "คงต้องกลับแล้วละ... ชิโรโกะจังกับคุณครู... และทุกคนคงรอกันอยู่"
13080-143 = "ฮืม... ชิโรโกะจังแข็งแกร่งขึ้นเรื่อยๆ จนจะเกินกำลังฉันแล้ว... อีกหน่อยก็คงเก่งกว่าลุงคนนี้แล้ว#nหรือเปล่านะ~?"
13080-144 = "ชิโรโกะจัง... ตอนแรกทั้งตัวเล็ก ทั้งน่ารัก แต่ตอนนี้โตจนทำให้ลุงกลัวเสียแล้ว เฮ้อ~ เวลาผ่านไปไว#nเหมือนโกหกเลย~"
13080-145 = ""
13080-148 = ""
13080-149 = "แต่ที่นี่ก็ไม่เปลี่ยนไปเลยนะ... "
13080-150 = "ก็นะ พื้นที่นี้ถูกทิ้งร้างไว้ ก็คงไม่มีอะไรเปลี่ยนแปลงหรอก"
13080-151 = ""
13080-153 = ""
13080-154 = "รบกวนด้วยค่ะ! ช่วยลงชื่อตรงนี้ให้หน่อยค่ะ!"
13080-155 = ""
13080-157 = ""
13080-163 = ""
13080-166 = ""
13080-168 = "นี่คือการลงชื่อเพื่อการปรับปรุงสภาพแวดล้อมของอะบิดอสค่ะ! "
13080-169 = "เราต้องการความช่วยเหลือจากทุกคนเพื่อไปโน้มน้าวกลุ่มธุรกิจค่ะ!"
13080-171 = "ไม่ละ... ฉันไม่สนใจหรอก... "
13080-172 = ""
13080-174 = ""
13080-175 = "ทำอะไรไร้สาระไม่เข้าเรื่อง... "
13080-176 = ""
13080-178 = ""
13080-179 = "อะ... เอ่อ... ขอโทษนะคะ... ถ้าไม่เป็นการรบกวนเกินไป ช่วยลงชื่อ..."
13080-180 = "ยังไงก็ไร้ความหมายหรือเปล่า เนฟธิสก็บอกว่าจะออกจากเขตปกครองตนเองนี่แล้ว ถ้างั้นการปรับปรุง#nสภาพแวดล้อมจะไปมีประโยชน์อะไร!"
13080-181 = ""
13080-183 = ""
13080-184 = ""
13080-185 = ""
13080-187 = ""
13080-188 = ""
13080-189 = ""
13080-191 = ""
13080-192 = "อ๊ะ...! ตรงนั้นน่ะ! เดี๋ยวก่อน! หยุดนะ! สต็อป!"
13080-193 = ""
13080-196 = ""
13080-197 = ""
13080-198 = "แหะๆๆ... อื้ม เธอนั่นแหละ ฉันรู้จักเธอนะ เป็นนักเรียนใหม่ที่เพิ่งย้ายมาใช่มั้ย? ชื่อว่าอะไรนะ... โฮชิโนะ...? "
13080-199 = ""
13080-201 = ""
13080-202 = ""
13080-203 = ""
13080-204 = "โฮชิโนะจังใช่มั้ย...? เอะ... เอ๋?!"
13080-205 = "ดะ... เดี๋ยวก่อนสิ โฮชิโนะจัง"
13080-213 = ""
13080-214 = "เฮ้อ... "
13080-215 = ""
13080-217 = ""
13080-219 = "เราจะเปิดการบรรยายแผนเสริมสร้างการลาดตระเวนเพื่อความปลอดภัยของเขตปกครองตนเองค่ะ! ช่วยเข้าร่วมและบอกความคิดเห็นของชาวเมืองกันด้วยนะคะ! "
13080-220 = "นี่ค่ะ รับใบปลิวการบรรยายไปนะคะ แล้วก็มา..."
13080-221 = ""
13080-223 = ""
13080-225 = ""
13080-226 = ""
13080-227 = "อ๊ะ...! โฮชิโนะจัง!!"
13080-228 = ""
13080-230 = ""
13080-231 = ""
13080-232 = ""
13080-233 = "ระ... รอด้วย! อย่าหนีสิ!! เดี๋ยวก่อน! ฉันมีเรื่องจะคุยด้วยนะ!"
13080-234 = ""
13080-236 = ""
13080-237 = "วะ... ว้าย...?!"
13080-238 = ""
13080-242 = ""
13080-244 = ""
13080-245 = "ชิ..."
13080-246 = ""
13080-248 = ""
13080-250 = ""
13080-251 = "อ่า ขะ... ขอบใจนะ... "
13080-252 = "อ่า... แบบนี้มัน... ปะ... เป็นเกียรติมากเลยละ นี่เป็นครั้งแรกเลยที่ได้จับมือคนที่มีชื่อเสียงน่ะ..."
13080-253 = "รู้จักฉันเหรอคะ?"
13080-254 = "อื้อ ก็ต้องรู้จักสิ! เป็นนักเรียนใหม่ที่นิสัยไม่ดีและแข็งแกร่งมากยังไงล่ะ! ข่าวลือกระฉ่อนเลย!"
13080-255 = "แต่ก็นะ ถึงมันจะเป็นข่าวลือจากฉันเพียงคนเดียวก็เถอะ..."
13080-256 = "คนที่ไล่กลุ่มคนไม่ดีไปคราวก่อนคือโฮชิโนะจังใช่มั้ย? คนที่ห้ามไม่ให้พวกกลุ่มอันธพาลแปลกๆ สู้กันเองก็ด้วย!"
13080-257 = "อื้ม นี่เป็นการทำเพื่ออะบิดอสนะ ฉันก็ควรมาทักทายในฐานะประธานสภานักเรียนสิ ขอบคุณมากเลยนะ โฮชิโนะจัง "
13080-258 = ""
13080-260 = ""
13080-261 = "กลับบ้านไปเถอะค่ะ ท่านประธานสภานักเรียนยูเมะ ถ้าฟ้ามืดเดี๋ยวพวกคนอันตรายจะออกมาป้วนเปี้ยน#nแถวนี้นะคะ"
13080-262 = "อ่า... งะ... งั้นเหรอ? แต่ว่าฉันยังมีงานต้องทำอีกเยอะเลย..."
13080-263 = ""
13080-265 = ""
13080-266 = ""
13080-267 = ""
13080-268 = ""
13080-269 = "อ๊ะ เอะ... เอ๋...? "
13080-270 = "ว่าแต่... รู้จักชื่อของฉันด้วยเหรอ...?"
13080-281 = ""
13080-282 = "เฮ้อ... เวลาผ่านไปขนาดนี้แล้วเหรอเนี่ย... "
13080-283 = "ยังได้รายชื่อไม่ครบเลย แถมใบปลิวที่ต้องเอาไปแจกก็ยังเหลืออีกเป็นปึก..."
13080-284 = "อืม... ฉันควรเก็บรายชื่อให้ครบภายในสัปดาห์นี้ สัปดาห์หน้าจะได้ไปที่อื่นได้..."
13080-285 = ""
13080-288 = "พะ... พอฟ้าเริ่มมืดลงแล้วก็รู้สึก ปะ... เปล่าเปลี่ยวอยู่เหมือนกันนะเนี่ย... สงสัยต้องกลับบ้านอย่างที่#nโฮชิโนะจังว่าแล้วละ..."
13080-289 = ""
13080-294 = ""
13080-295 = ""
13080-297 = ""
13080-298 = "นั่นใครน่ะ?"
13080-300 = "อ๊ะ...? "
13080-301 = ""
13080-304 = ""
13080-305 = "การบรรยายแผนเสริมสร้างการลาดตระเวนของสภานักเรียนอะบิดอส? อะไรเนี่ย เธอคือนักเรียนอะบิดอสงั้นเรอะ?"
13080-306 = "งั้นก็ดีเลย รู้มั้ยว่าพวกฉันต้องลำบากเพราะพวกเธอจ่ายค่าจ้างช้าน่ะ!"
13080-307 = ""
13080-310 = ""
13080-311 = "คะ? ฉะ... ฉัน... เอ่อ..."
13080-313 = ""
13080-314 = "ถ้าจ่ายค่าจ้างช้า ก็ต้องจ่ายดอกเบี้ยด้วยน่ะสิ! เธอจะรับผิดชอบเรื่องนี้ยังไง! หา?"
13080-315 = ""
13080-319 = ""
13080-320 = "บะ... ใบรวบรวมรายชื่อ..."
13080-322 = "แล้วนี่มันอะไรกัน? ห้ะ?"
13080-323 = ""
13080-326 = "ยะ... หยุดเถอะค่ะ! ฉันต้องเอาไปแจกชาวเมืองพรุ่งนี้นะคะ..."
13080-328 = ""
13080-329 = "แล้วมันยังไงกันเล่า!"
13080-330 = "กำลังหงุดหงิดอยู่พอดี งั้นก็ดีเลย! ต้องระบายความโกรธหน่อยแล้ว!"
13080-331 = ""
13080-333 = ""
13080-336 = ""
13080-338 = ""
13080-341 = ""
13080-343 = ""
13080-352 = ""
13080-354 = ""
13080-355 = ""
13080-360 = ""
13080-362 = "อ่า... อ๊ะ...? ฮะ... โฮชิโนะจัง...?"
13080-364 = "ฉันบอกไปแล้วนี่คะว่าพอกลางคืนแล้วมันอันตรายน่ะ!"
13080-365 = "ทำไมไม่ฟังที่พูดเลยล่ะคะ! ไม่ใช้หัวคิดเลยหรือไง?!"
13080-366 = ""
13080-369 = ""
13080-370 = "ขะ... ขอโทษนะ... "
13080-371 = "แถวนี้มีแต่คนแบบนี้เต็มไปหมดค่ะ! ไม่รู้เหรอคะว่าอะบิดอสในตอนดึกคือเขตปลอดกฎหมายดีๆ นี่เอง?!"
13080-372 = "..."
13080-373 = ""
13080-377 = ""
13080-378 = ""
13080-380 = ""
13080-381 = "ธะ... เธอเป็นใครน่ะ?!"
13080-382 = "ฉันจำหน้าเธอไว้แล้ว! ฝากไว้ก่อนเถอะ!"
13080-383 = ""
13080-385 = ""
13080-387 = "เฮ้อ..."
13080-388 = "ไม่ได้บาดเจ็บตรงไหนใช่มั้ยคะ...? ท่านประธานสภานักเรียนยูเมะ"
13080-389 = "อะ... อื้ม... ขอบใจนะ โฮชิโนะจัง..."
13080-390 = "ทำไมไม่สู้กลับล่ะคะ? การตอบโต้คนพวกนั้นไม่น่าจะใช่เรื่องยากอะไรเลยด้วย"
13080-391 = "ตะ... แต่ว่า... การแก้ปัญหาด้วยการต่อสู้มัน... อืม... มันเหมือนไม่ได้แก้ไขปัญหาจริงๆ แต่กลับเป็นว่า#nยังย่ำอยู่กับที่น่ะ..."
13080-392 = "แล้วพอชินกับมันเข้า เราก็จะเอาแต่แก้ไขปัญหาด้วยวิธีที่ไม่ถูกต้องแบบนั้น..."
13080-393 = "พูดอะไรไม่เห็นจะรู้เรื่องเลยค่ะ..."
13080-394 = "แล้วถ้าอย่างนั้นจะแก้ไขปัญหาด้วยอะไรล่ะคะ?"
13080-395 = "นะ... นั่นสินะ... "
13080-396 = ""
13080-398 = ""
13080-399 = "กลับไปเถอะค่ะ พวกที่หนีไปอาจจะไปพาพรรคพวกกลับมาเล่นงานอีกก็ได้ค่ะ"
13080-400 = ""
13080-402 = ""
13080-403 = ""
13080-404 = "อ๊ะ...? โฮชิโนะจัง?!"
13080-409 = ""
13080-410 = ""
13080-411 = ""
13080-415 = "นี่คือการลงชื่อเพื่อการปรับปรุงสภาพแวดล้อมของอะบิดอสค่ะ!"
13080-416 = "เราต้องการความช่วยเหลือจากทุกคนเพื่อไปโน้มน้าวกลุ่มธุรกิจค่ะ!"
13080-417 = "..."
13080-418 = ""
13080-420 = ""
13080-421 = "ลงชื่อเพื่อ... การปรับปรุงสภาพแวดล้อม..."
13080-422 = "โฮชิโนะจัง...? ทำไมถึงมาอยู่ที่นี่ล่ะ?"
13080-423 = "ถามอะไรแปลกๆ คะ? ก็พวกคนกลุ่มเมื่อวานอาจกลับมาล้างแค้นอีกก็ได้นี่คะ"
13080-424 = "มะ... มาปกป้องฉันเหรอ?!"
13080-425 = "เปล่าค่ะ ก็แค่สะดวกดีที่จะจัดการกับพวกนิสัยไม่ดีที่มารวมตัวกันเพราะหวังจะจัดการเหยื่ออีกทีน่ะค่ะ"
13080-426 = "ฉันเป็นเหยื่องั้นเหรอ?!"
13080-427 = "ไม่ใช่อย่างนั้นหรอกค่ะ สภานักเรียนอะบิดอสมีศัตรูเยอะ แล้วคุณก็ยังเป็นประธานสภานักเรียนด้วย งั้นก็ไม่ต่างจากเหยื่อหรอกค่ะ เหยื่อตัวเป้งเลยละ"
13080-428 = ""
13080-430 = ""
13080-431 = "ฮุฮุฮุ งั้นเหรอ?"
13080-432 = ""
13080-434 = ""
13080-435 = "โฮชิโนะจังเป็นคนไม่กล้าพูดตรงๆ สินะ? ที่จริงแล้วโฮชิโนะจังมาเพราะเป็นห่วงฉันใช่มั้ยล่ะ? แค่ดูจากใบหน้าน่ารักๆ ก็รู้แล้ว บนหน้าผากมีเขียนไว้ว่า \"ฉันเป็นห่วงรุ่นพี่ยูเมะค่ะ!\" อยู่ด้วยนะ"
13080-436 = "คะ... ใครเป็นห่วงกันคะ! แล้วส่วนไหนที่น่ารักไม่ทราบคะ?!"
13080-437 = "อืม... ถึงโฮชิโนะจังจะขมวดคิ้วและทำหน้าน่ากลัวอยู่ก็เถอะ... แต่ที่จริงเป็นการแกล้งทำใช่มั้ยล่ะ?"
13080-438 = ""
13080-440 = ""
13080-441 = "โฮชิโนะจังตัวจริงที่ซ่อนอยู่ภายใต้ใบหน้านั่นน่ะ... อืม... จะว่ายังไงดีนะ... ดูน่ารักกระปุ๊กกระปิ๊กกว่าน่ะ..."
13080-442 = "พะ... พูดอะไรกันคะ! ถ้าจะพูดอะไรเพ้อเจ้ออยู่แบบนี้ ฉันจะกลับแล้วนะคะ!"
13080-443 = "แหะๆ... ขอบใจนะ โฮชิโนะจัง "
13080-444 = "พอมีรุ่นน้องเก่งๆ มาเป็นห่วงเป็นใย ฉันก็อุ่นใจขึ้นมาเลยน่ะ... แล้วก็รู้สึกว่าไว้ใจได้ด้วย..."
13080-445 = "เลิกพูดอะไรไร้สาระแล้วตั้งใจทำงานเถอะค่ะ ท่านประธานนักเรียน"
13080-446 = "ฉันจะช่วยงานของสภานักเรียนครั้งนี้แค่ครั้งเดียวค่ะ"
13080-447 = "แต่ฉันชอบคำว่ารุ่นพี่มากกว่าประธานสภานักเรียนนะ... ถ้าเรียกฉันว่ารุ่นพี่ยูเมะ ฉันจะดีใจกว่านะ..."
13080-448 = ""
13080-450 = ""
13080-451 = "ฟังที่ฉันพูดอยู่มั้ยคะ...?"
13080-455 = "ตอนต่อไป;สภานักเรียนอะบิดอส 2"
