[translation]
13330-1 = "Episode 33;Epiphany"
13330-6 = "..."
13330-9 = "...Yu...me..."
13330-12 = "[ns] \"What in the world happened to Hoshino?!\""
13330-13 = "H-Hoshino..."
13330-14 = "...Her existence has been inverted. "
13330-15 = "The Hoshino you see...is no longer..."
13330-17 = "I-Is there anything we can do?"
13330-18 = ""
13330-20 = ""
13330-21 = "...Negative. There is nothing."
13330-22 = "[ns] \"...?!\""
13330-23 = "H-How can that be...?"
13330-24 = "It's...simply impossible. It would be akin to resurrection."
13330-25 = "[ns] \"Hoshino...!\""
13330-26 = ""
13330-29 = "Yes, the Train Cannon was simply bait. Every move I made! Bait!"
13330-30 = "My true objective was the Great Mystery of Abydos, the Horus of Dawn."
13330-31 = "The sixth koan: Is a truth that never existed, still truth? I have found the answer."
13330-32 = "One day, we will all die. That is an absolute truth, one that has long been decided."
13330-33 = "But a truth we could not comprehend. For death is but a concept."
13330-34 = "We can only witness the deaths of others, never our own. That's why true understanding, true insight of death, forever escapes us! That is the very essence of death!"
13330-35 = "However, Hoshino's pain has elucidated another mystery."
13330-36 = "We have already encountered death, in another form."
13330-37 = "Pain."
13330-38 = "My pain is unknown to others, and the pain of others is unknown to me. Pain. Yes, that indeed is death, in its own right."
13330-39 = "...Yes, this is a mystery reversed through pain. The manifestation of terror."
13330-43 = "Divine amongst the divines. The oldest and greatest power of the gods, the Horus."
13330-46 = "...We have to stop Hoshino. Arona! Sensei!"
13330-47 = "Y-Yes? "
13330-48 = "Takanashi Hoshino has transformed into a being called the Horus. If we leave that...being...it will inevitably, led by its nature, overturn the world."
13330-50 = "In other words... This world will be destroyed at the hands of Hoshino."
13330-51 = "...!!"
13330-52 = "[ns] \"...!\""
13330-53 = ""
13330-58 = ""
13330-59 = "...Yu..."
13330-60 = "...Yu...me..."
13330-62 = "...?!"
13330-63 = "....Hoshino."
13330-64 = "H-Hoshino...?! That thing is Hoshino...?!"
13330-65 = "Wh-What...is happening...?"
13330-66 = ""
13330-68 = ""
13330-69 = "[ns] \"Hina!\""
13330-73 = "Sen...Sensei..."
13330-74 = "[s] \"Hina! Are you okay?!\""
13330-75 = ""
13330-78 = "...couldn't...stop...Ho..shi...no..."
13330-79 = ""
13330-83 = "[ns] \"...!!!\""
13330-87 = ""
13330-88 = "Wh-Wha...?!"
13330-89 = "....Note....book..."
13330-91 = "Get a hold of yourself! Hoshino! "
13330-92 = ""
13330-94 = ""
13330-95 = ""
13330-99 = "Kyaaah?!"
13330-100 = ""
13330-101 = ""
13330-102 = "[ns] \"Hoshino...!\""
13330-103 = "..."
13330-104 = ""
13330-106 = ""
13330-108 = "Sensei! Be careful! Even we can't withstand that attack!"
13330-109 = "Arona! Your hand..!"
13330-110 = ""
13330-112 = ""
13330-113 = ""
13330-120 = "[ns] \"(It's too late... I can't do anything...)\""
13330-125 = "[ns] \"(I couldn't do anything...)\""
13330-127 = "[ns] \"(...Anything.)\""
13330-129 = "[ns1] \"(I can't resurrect the dead.)\"\n[ns2] \"(I can't undo what's been done.)\""
13330-132 = ""
13330-133 = "[ns] \"(I am powerless...Plana.)\""
13330-136 = "Oooh, oooh...!"
13330-137 = "Oh, oh, oooh!"
13330-138 = "Has your time come?"
13330-139 = "Yes! The primordial deity, the Horus! Thus comes Horus' adversary! The mythical beings, who clashed during the very creation of this world, arise!"
13330-140 = "You've risen in response to the divinity of the Horus!"
13330-141 = "The Fury of Set! "
13330-142 = ""
13330-145 = ""
13330-154 = "This is the texture from before the revision of the rules, but no matter!"
13330-155 = "A battle between the Fury of Set and Horus of Dawn! This is a clash of gods over creation itself!"
13330-156 = "Come, reveal your myths to this world! The battle between the Fury of Set and Horus of the Dawn! A tale of unmatched power and brilliance, steeped in mystery and fear!"
13330-157 = ""
13330-160 = "Is a truth that never existed, still truth?"
13330-161 = "To that incomprehensible question, this mystery, this fear, answers back!"
13330-162 = "It's a truth so clearly seen, yet one I have never experienced. A truth beyond experience itself."
13330-163 = "We can never hope to feel the pain of others! And thus, this truth is incomprehensible! Yes, that's it!"
13330-164 = "This world will crumble."
13330-165 = "Such is its fate. Unable to grasp the suffering of others, we were creatures destined for destruction."
13330-168 = "Ah, yes, Black Suit. For you, I've achieved what you could not."
13330-169 = "Isn't this the sight you longed to witness?"
13330-170 = ""
13330-173 = "The destruction of this world."
13330-176 = ""
13330-177 = "Status check. [USERNAME] Sensei, at this rate, the world will be destroyed."
13330-178 = "[s] How do we stop it?"
13330-179 = "Response. ...Hoshino's halo must be destroyed."
13330-180 = ""
13330-185 = "[ns] No. We can't."
13330-186 = "Hoshino is currently transformed into terror itself. Only a divinity that can match that terror can subdue her."
13330-187 = "[s] There must be another way."
13330-188 = "...Even that wouldn't be enough."
13330-189 = "It must be a terror that can rival terror itself..."
13330-190 = "[s] No. We can't."
13330-191 = "Sensei, at this rate, you will... "
13330-192 = ""
13330-196 = "*cough* *cough*... Shiroko..."
13330-197 = "Run...away..."
13330-198 = "Shiroko..."
13330-199 = ""
13330-201 = ""
13330-202 = "...Yu...me..."
13330-203 = ""
13330-205 = ""
13330-206 = ""
13330-212 = "..."
13330-213 = "I get it now."
13330-214 = "This all happened...because I was weak."
13330-215 = "There's no one left who can stop Hoshino."
13330-216 = "It has to be me."
13330-217 = ""
13330-221 = "Ayane, Nonomi, Serika, Hoshino, and Sensei... I'll save you. All of you."
13330-222 = ""
13330-224 = ""
13330-225 = ""
13330-226 = "Yes, I understand. That's the reason for my existence."
13330-229 = ""
13330-232 = "Chroma detected!"
13330-233 = "Wh-Why?! Now, of all times?! "
13330-234 = "Wh-What about Sensei?!"
13330-235 = "Report. Sensei has lost consciousness. Pulse is dropping to dangerous levels. Heartbeat is unstable."
13330-237 = "Sensei's very life is in danger! Arona!"
13330-238 = "...!!"
13330-239 = ""
13330-242 = "I have to stop her!"
13330-243 = ""
13330-246 = ""
13330-248 = "I."
13330-249 = ""
13330-272 = "...Um."
13330-273 = "...Sensei? I think it's about time for you to get up."
13330-274 = "[USERNAME] Sensei?"
13330-278 = ""
13330-279 = ""
13330-281 = "Next Episode;Apology"
