[translation]
13355-2 = "3;호시노 테러 언노운;01\n#3;stiff\n#3;a\n#wait;1500"
13355-3 = "3;호시노 테러 언노운;01;몰……라…… 너희……. 이…… 고통……."
13355-4 = "#st;[0,0];instant;1;"
13355-6 = "3;호시노 테러 언노운;01\n#3;d\n#wait;1000"
13355-7 = "3;시로코 테러 언노운;06;아니. 호시노 선배. 알고 있어.\n#3;em;…\n#3;a"
13355-8 = "3;시로코 테러 언노운;05;왜냐하면 나는…….\n#3;closeup"
13355-11 = "3;지하생활자;00;저, 저, 저게 뭐야……. 저게, 저건…… 저건…….\n#3;em;…\n#3;a"
13355-12 = "3;지하생활자;00;죽음의 신 아누비스……?!\n#fontsize;100\n#3;shake"
13355-13 = "3;지하생활자;00;어, 어, 어떻게? 어떻게? 하지만, 저건…… 저건 저건, 불가능하잖아."
13355-14 = "3;지하생활자;00;그 신성은 이미 저기 있는데……? 저게 어떻게 두 개가 동시에……? 어째서……?\n#3;stiff"
13355-15 = "3;지하생활자;00;호루스의 신격에 맞먹는 저 존재가 하필, 하필이면 하필이면 지금……?!"
13355-16 = "3;지하생활자;00;어째서어어--?? 어어어---?? 이, 이게 뭐야, 이게…….\n#3;stiff"
13355-17 = "3;지하생활자;00;이게 뭐야아아아아아----!!!\n#fontsize;100\n#3;closeup\n#3;shake"
13355-18 = "3;지하생활자;00;이건 반칙, 반칙, 반칙이잖아아아아--!!!\n#fontsize;100\n#3;closeup\n#3;hophop"
13355-19 = "3;지하생활자;00;룰위반, 코덱스의 위반, 반칙이야!! 익명의 행인……!! 이 쓰레기가……!!\n#fontsize;100\n#3;closeup\n#3;stiff"
13355-20 = "3;지하생활자;00;이런 중요한 정보가 있다면 미리 알려줬어야지이이-!!!\n#fontsize;100\n#3;shake\n#3;closeup"
13355-21 = "#st;[0,0];instant;1;"
13355-24 = "3;지하생활자;00 \n#3;h\n#3;em;…\n#wait;2500"
13355-25 = "3;지하생활자;00;<세트의 분노>의 현현이 멈춰버렸다……."
13355-26 = "3;지하생활자;00;이걸로는 엔딩으로 도달할 수 없어……."
13355-27 = "3;지하생활자;00;……. 숨겨둔 다섯 번째 공략법을…… 꺼내지 않으면……!\n#3;stiff"
13355-28 = "3;지하생활자;00;설마, 이것까지 사용하게 만들다니…… [USERNAME] , 정말 끈질기고 끈질긴 녀석이군…….\n#3;closeup"
13355-29 = "#all;hide\n#na;지하생활자;하지만 최후의 최후까지 승리하는 것은 바로 나……! 나다!"
13355-30 = "#st;[0,0];instant;1;"
13355-33 = "#na;지하생활자;내가 이겨야 해!! 내가 이겨야만 해애애애-!!\n#fontsize;100\n#bgshake"
13355-35 = "#nextepisode;다음화;수첩"
