[translation]
13430-1 = "#title;제43화;에필로그 2"
13430-3 = "3;알바세리카;12;감사합니다, 다음에 또 오세요~! \n#3;a\n#3;greeting\n#3;em;[반짝]"
13430-4 = "#st;[0,0];instant;1;"
13430-6 = "#3;hide\n2;총학생회 행정원 A;03\n4;총학생회 행정원 B;00\n#2;h\n#4;h\n#2;em;[재잘]\n#2;hophop\n#wait;1000"
13430-8 = "#3;hide\n2;총학생회 행정원 A;03\n4;총학생회 행정원 B;00\n#2;h\n#4;h\n#2;dr\n#4;dr\n#wait;2000"
13430-9 = "2;알바세리카;03;네, 다음 두 분 이쪽에 앉아주세요!\n#2;ar\n#2;em;[반응]"
13430-10 = "2;알바세리카;12;아, 어서 오세요. 지금은 대기하셔야 하고, 30분 정도? 여기 이름 적어주세요. \n#2;m5\n#2;em;[!]"
13430-11 = "1;마스터;01;세리카 씨, 이쪽도 치워주겠어?\n#1;a\n#1;em;[반응]"
13430-12 = "2;알바세리카;12;네에~ 갑니다!\n#2;em;[음표]\n#2;m3"
13430-13 = "#st;[0,0];instant;1;"
13430-15 = "1;마스터;01\n2;알바세리카;12\n#2;d\n#1;d\n#wait;1500"
13430-17 = "[ns] \"바쁘네. 세리카.\""
13430-18 = "3;시로코;01;응. 최근 사람들이 많아지기 시작한 거 같아.\n#3;a"
13430-19 = "5;아야네;02;그러게요. 시내에 못 보던 가게도 좀 많아진 느낌이고…….\n#5;a\n#5;em;…"
13430-20 = "1;노노미;01;응, 저희에겐 좋은 일인 거 같아요!\n#1;a"
13430-21 = "#st;[0,0];instant;1;"
13430-23 = "3;시로코;01\n5;아야네;02\n1;노노미;01\n#3;d\n#1;d\n#5;d\n#wait;1500"
13430-25 = "3;호시노;02;그치만 사람들이 많아질수록 트러블도 많아지는 법이라서 말야. 하암- 덕분에 잠을 더 못 자고 있달까-\n#3;a"
13430-26 = "3;호시노;00;뭐, 아직까지는 허용범위지만.\n#3;em;…"
13430-27 = "#all;hide\n#na;다람쥐 시민;도둑이야!!\n#fontsize;100"
13430-28 = "#st;[0,0];instant;1;"
13430-30 = "3;호시노;05\n#3;h\n#3;em;[!]\n#wait;1000"
13430-32 = "3;불량배 블랙헬멧단;01;에잇, 비켜! 비켜-!!\n#3;closeup\n#3;hophop"
13430-33 = "#st;[0,0];instant;1;"
13430-35 = "3;불량배 블랙헬멧단;01\n#3;dr\n#3;h\n#wait;1500"
13430-36 = "2;다람쥐 시민;01;공사 대금이 든 지갑을……! 도둑이야!!\n#2;ar\n#2;hophop\n#2;em;[반응]"
13430-38 = "3;시로코;06;내가 갈게! \n#3;a\n#3;em;[!]"
13430-39 = "#st;[0,0];instant;1;"
13430-41 = "3;시로코;05\n#3;dr\n#3;h\n#wait;1500"
13430-43 = "3;알바세리카;04;앗, 시로코 선배! 라면 식기 전에 돌아와야 해!\n#3;em;[반응]\n#3;hophop\n#3;a"
13430-44 = "1;노노미;18;시로코 쨩……!\n#1;a"
13430-45 = "5;호시노;00;괜찮아, 괜찮아. 시로코 쨩 요즘 엄청 빨라서 저 정도라면 금세 따라잡을걸?\n#5;a\n#5;em;[음표]"
13430-46 = "#st;[0,0];instant;1;"
13430-48 = "3;알바세리카;04\n1;노노미;18\n5;호시노;00\n#1;d\n#3;d\n#5;d\n#wait;1000"
13430-49 = "#all;hide\n[ns] \"…………….\""
13430-50 = "3;아야네;02;……선생님? 왜 그러세요?\n#3;a"
13430-51 = "[s] \"……나도 갈게.\""
13430-52 = "3;아야네;09;네?\n#3;shake\n#3;em;[?!]"
13430-54 = "2;불량배 블랙헬멧단;01;크흐흐…. 여기까지 왔으면…….\n#2;a\n#2;em;…"
13430-55 = "#st;[0,0];instant;1;"
13430-57 = "2;불량배 블랙헬멧단;01\n5;시로코 테러 무소속;01\n#5;black\n#5;al\n#2;h\n#wait;1000"
13430-59 = "3;불량배 블랙헬멧단;01\n#3;h\n#3;falldownL\n#wait;1500"
13430-61 = "3;시로코 테러 무소속;05;…….\n#3;a\n#3;em;…"
13430-62 = "#st;[0,0];instant;1;"
13430-64 = "3;시로코 테러 무소속;05\n#3;h\n#wait;1000"
13430-65 = "1;시로코;05\n3;시로코 테러 무소속;05\n#3;h\n#3;m5\n#1;ar\n#1;h\n#wait;1000"
13430-66 = "1;시로코;02\n3;시로코 테러 무소속;02\n#3;shake\n#3;h\n#1;h\n#1;em;[!]\n#3;em;[?!]\n#wait;1000"
13430-67 = "1;시로코;02\n3;시로코 테러 무소속;02\n#3;h\n#1;h\n#wait;1500"
13430-68 = "[ns] \"시로코!!\""
13430-69 = "1;시로코;04;선생님……? \n#1;stiff"
13430-70 = "3;시로코 테러 무소속;03;……. 들켜버렸나.\n#3;em;…"
13430-72 = "3;시로코 테러 무소속;05;……. \n#3;a"
13430-73 = "#st;[0,0];instant;1;"
13430-75 = "1;시로코;01;……. 음. 그럼 나는 지갑을 돌려주고 올 테니까.\n#1;a\n#3;m5"
13430-76 = "3;시로코 테러 무소속;06;도망가지 않아. 내 움직임은 너에게 읽히고 있으니까."
13430-77 = "3;시로코 테러 무소속;03;하긴, 당연하네. 너는 나니까."
13430-78 = "1;시로코;03;……. 응. 그럼 선생님.\n#1;em;[반응]"
13430-79 = "[s] \"응. 시로코. 나는 이쪽 시로코와 잠깐 얘기하고 갈 테니까.\""
13430-80 = "#st;[0,0];instant;1;"
13430-82 = "1;시로코;01\n3;시로코 테러 무소속;03\n#1;m2\n#wait;1000\n#1;h\n#3;h"
13430-83 = "#1;hide\n2;시로코;01\n3;시로코 테러 무소속;03\n#2;h\n#3;h"
13430-84 = "2;시로코;01\n1;불량배 블랙헬멧단;01\n3;시로코 테러 무소속;03\n#1;a\n#1;stiff\n#2;greeting\n#wait;1000\n#1;h\n#2;h\n#3;h"
13430-85 = "1;불량배 블랙헬멧단;01;(해롱해롱)\n#1;em;[zzz]"
13430-86 = "#st;[0,0];instant;1;"
13430-88 = "1;불량배 블랙헬멧단;01\n2;시로코;03\n3;시로코 테러 무소속;03\n#1;dl\n#2;dl\n#1;h\n#2;h\n#3;h\n#wait;1500"
13430-89 = "#1;hide\n#2;hide\n3;시로코 테러 무소속;03\n#3;m3\n#wait;1500"
13430-90 = "3;시로코 테러 무소속;04;……오랜만, 은 아니네. 선생님."
13430-91 = "[s] \"그동안 아비도스 자치구에 있었던 거야?\""
13430-92 = "3;시로코 테러 무소속;06;응…… 잘 알고 있는 곳이 여기밖에 없으니까."
13430-93 = "3;시로코 테러 무소속;04;어디서 지내고 있었냐면…… 아비도스의 빈집들 여기저기."
13430-94 = "3;시로코 테러 무소속;03;수도나 전기가 들어오는 곳도 찾아보면 의외로 많거든. \n#3;em;…"
13430-95 = "[s] \"그렇구나. 건강은 괜찮아? 식사는? 곤란한 건 없어?\""
13430-96 = "3;시로코 테러 무소속;02;매일 체력 단련도 하고 있고, 버려진 폐품을 주워서 이런저런 물건을 조립해서 팔거나 가끔씩 이렇게 자경단 활동도 하고……."
13430-97 = "3;시로코 테러 무소속;01;……혼자 지내는 건 오래전부터 익숙했어. 선생님."
13430-99 = "2;시로코;01\n4;다람쥐 시민;00\n#2;a\n#4;a\n#2;h\n#4;h\n#wait;1000"
13430-100 = "2;시로코;03\n4;다람쥐 시민;00\n#2;h\n#4;h\n#4;greeting\n#4;em;[반짝]\n#wait;1500"
13430-101 = "2;시로코;03\n4;다람쥐 시민;00\n#2;d\n#4;d\n#2;h\n#4;h\n#wait;1000"
13430-102 = "1;노노미;01\n3;호시노;02\n5;알바세리카;12\n#1;a\n#3;a\n#5;a\n#1;h\n#3;h\n#5;h\n#wait;1000"
13430-103 = "1;노노미;01\n3;호시노;02\n5;알바세리카;03\n#1;h\n#3;h\n#5;h\n#5;hophop\n#5;em;[재잘]\n#wait;1500"
13430-104 = "1;노노미;01\n3;호시노;02\n5;알바세리카;03\n#1;d\n#3;d\n#5;d\n#wait;1000"
13430-106 = "2;아야네;01\n4;마스터;00\n#2;a\n#4;a\n#2;h\n#4;h\n#wait;1000"
13430-107 = "2;아야네;01\n4;마스터;00\n#2;h\n#4;h\n#4;em;[음표]\n#wait;1500"
13430-109 = "[ns1] \"저기 가서 라면 먹지 않을래?\"\n[ns2] \"모두 네 안부를 궁금해하고 있어. 시로코.\""
13430-112 = "#st;[0,0];instant;1;"
13430-114 = "3;시로코 테러 무소속;06\n#3;em;…\n#3;h\n#3;a\n#wait;2500"
13430-115 = "3;시로코 테러 무소속;01;……아니. 괜찮아."
13430-116 = "3;시로코 테러 무소속;04;무슨 표정으로 모두를 봐야 할지 잘 모르겠어……."
13430-117 = "[s] \"그럼 다음에라도 같이 보자.\""
13430-118 = "3;시로코 테러 무소속;03;……."
13430-119 = "3;시로코 테러 무소속;01;궁금하지 않아? \n#3;em;[?]"
13430-120 = "[s] \"어떤 게?\""
13430-121 = "3;시로코 테러 무소속;99;나에게 무슨 일이 있었고, 어떤 일들이 펼쳐졌는지."
13430-122 = "3;시로코 테러 무소속;01;어째서 묻지 않는 거야, 선생님?"
13430-123 = "[s] \"알만큼은 아니까, 그 이상은 의미 없지 않을까?\""
13430-124 = "3;시로코 테러 무소속;01;……그런가."
13430-125 = "[s] \"그리고 그런 걸 물으면 시로코를 괴롭히는 게 되는 거잖아?\""
13430-126 = "#st;[0,0];instant;1;"
13430-128 = "3;시로코 테러 무소속;01\n#3;h\n#wait;1500"
13430-129 = "3;시로코 테러 무소속;99;……. 그러네."
13430-130 = "3;시로코 테러 무소속;00;그래도 조금은 알게 된 게 있어. 선생님."
13430-131 = "3;시로코 테러 무소속;02;호시노 선배가 어째서 자신의 본질이 반전된 상태에서 다시 원래대로 돌아올 수 있었는지."
13430-132 = "[s] \"……….\""
13430-133 = "3;시로코 테러 무소속;99;애초에 나와는 달리 불완전한 상태였기도 하고, <색채>가 아닌 다른 무언가를 통해 전환된 것이기도 했지만…….\n#3;em;…"
13430-134 = "3;시로코 테러 무소속;06;하지만 선배는 결국 자신의 본질이었던, 자신의 일부를 버렸던 거야. 그래서……"
13430-135 = "3;시로코 테러 무소속;03;……앞으로 나아갈 수 있었던 거겠지.\n#3;closeup"
13430-136 = "#st;[0,0];instant;1;"
13430-138 = "3;쿠즈노하;04;색채로 완전히 반전된 존재를 원래대로 되돌릴 수 있는 방법 같은 건 이 세상엔 존재하지 않아.\n#3;a"
13430-139 = "3;쿠즈노하;05;그건 죽은 사람을 되살리지 못하는 것과 마찬가지로 당연한 이 세상의 법칙이라네."
13430-140 = "3;쿠즈노하;08;허나……. 그럼에도 불구하고 누군가를 구하고 싶은 것이라면…… 나를 찾아주게나, 선생."
13430-141 = "#st;[0,0];instant;1;"
13430-143 = "[ns] \"하지만, 나는 죽은 사람을 되살리지 못해.\""
13430-145 = "3;유메;01\n#3;h\n#3;closeup"
13430-149 = "[ns3] \"그러니까 이제 쿠즈노하를 쫓는 것은 그만둘 거야.\"\n[ns4] \"대신 바로 내 앞에 도움이 필요한 시로코에게 손을 내밀겠어.\""
13430-152 = "3;시로코 테러 무소속;04\n#3;h\n#3;em;…\n#wait;2500"
13430-153 = "3;시로코 테러 무소속;05;하지만 내가 여기에 있으면 분명 큰 문제가 생길 거야. 선생님. 한 세계에 시로코는 하나뿐이어야 하니까……."
13430-154 = "[s] \"아니. 무슨 문제가 생기더라도…… 내가 어떻게든 해 볼게.\""
13430-155 = "#st;[0,0];instant;1;"
13430-157 = "3;시로코 테러 무소속;02\n#3;h\n#wait;1500\n#3;em;[반응]"
13430-158 = "3;시로코 테러 무소속;03;……훗."
13430-159 = "[s] \"시로코가 웃었다?\""
13430-160 = "3;시로코 테러 무소속;03;자주 듣던 이야기네."
13430-161 = "3;시로코 테러 무소속;03;응. 여기는…… [ruby=어른]선생님[/ruby]이 지켜주고 있는 곳이니까."
13430-162 = "#st;[0,0];instant;1;"
13430-164 = "3;시로코 테러 무소속;03\n#3;h\n#wait;1500"
13430-165 = "3;시로코 테러 무소속;04;프레나파테스와 선생님이 두 사람으로 느껴지지 않아.\n#3;em;…"
13430-166 = "3;시로코 테러 무소속;03;하긴, 그것도 당연한 이야기네. 시로코가 나이듯이."
13430-167 = "[s] \"맞아. 나는 언제나 나야.\""
13430-168 = "3;시로코 테러 무소속;03;응. 그러네. 언제나 같은 상황에서 같은 선택을 하는…… 선생님은 늘 그래왔으니까.\n#3;greeting"
13430-169 = "#st;[0,0];instant;1;"
13430-171 = "3;시로코 테러 무소속;03\n#3;h\n#wait;1500"
13430-172 = "[ns] \"시로코. 이걸 받아.\""
13430-173 = "#st;[0,0];instant;1;"
13430-175 = "3;시로코 테러 무소속;02\n#3;h\n#wait;500"
13430-176 = "3;시로코 테러 무소속;02\n#3;d\n#wait;1000"
13430-177 = "3;시로코 테러 무소속;02\n#3;a\n#3;closeup\n#wait;1000"
13430-178 = "3;시로코 테러 무소속;01\n#3;h\n#3;closeup\n#wait;1500\n#3;greeting"
13430-179 = "3;시로코 테러 무소속;02;……이건, 스마트폰……?\n#3;closeup\n#3;em;[?]"
13430-180 = "3;시로코 테러 무소속;03;……오랜만이네. \n#3;closeup"
13430-181 = "[s] \"그러니까 내 손이 닿는 곳에 계속 있어 줘. 시로코.\""
13430-182 = "#st;[0,0];instant;1;"
13430-184 = "3;시로코 테러 무소속;00\n#3;h\n#3;closeup\n#3;em;…\n#wait;2500"
13430-185 = "3;시로코 테러 무소속;03;……응. 고마워.\n#3;closeup"
13430-186 = "3;시로코 테러 무소속;06;슬슬 모두가 걱정할 테니까, 이만 가 볼게. 선생님. \n#3;closeup"
13430-187 = "3;시로코 테러 무소속;03;……연락할게.\n#3;closeup"
13430-188 = "#st;[0,0];instant;1;"
13430-190 = "3;시로코 테러 무소속;03\n#3;closeup\n#wait;500"
13430-191 = "3;시로코 테러 무소속;03\n#3;d\n#3;closeup\n#wait;1000"
13430-192 = "3;시로코 테러 무소속;04\n#3;a\n#wait;2000"
13430-193 = "3;시로코 테러 무소속;04\n#wait;500"
13430-194 = "3;시로코 테러 무소속;04\n#3;d\n#wait;1000"
13430-196 = "[ns] \"시로코!\""
13430-197 = "3;시로코 테러 무소속;02\n#3;em;[반응]\n#wait;1500\n#3;h\n#3;a"
13430-198 = "[ns] \"그러고 보니, 뭔가 변했어. 너도.\""
13430-199 = "3;시로코 테러 무소속;01;……?"
13430-200 = "[s5] \"내가 장담할 수 있어. 너도 달라졌어. 분명히, 어떤 부분이!\"\n[s6] \"아주 조금이지만, 너도 앞으로 나아간 게 맞아!\""
13430-203 = "#st;[0,0];instant;1;"
13430-205 = "3;시로코 테러 무소속;06\n#3;h\n#wait;1500"
13430-206 = "3;시로코 테러 무소속;03;……응. 나도 알고 있어."
13430-207 = "#st;[0,0];instant;1;"
13430-209 = "#all;hide\n#na;호시노;이 고통도 그 행복도 모두 내 삶의 일부였던 거야."
13430-210 = "#na;호시노;그러니까 아마도……."
13430-211 = "#st;[0,0];instant;1;"
13430-213 = "3;시로코 테러 무소속;03;그러니까 아마도 나도…… 괜찮을 거야. \n#3;closeup"
13430-219 = "#na;아야네;(치익) 목표 확인! 눈으로 확인 가능한 거리까지 접근했습니다!"
13430-220 = "#na;세리카;아니, 설명하지 않아도 이미 잘 보이거든, 아야네 쨩?"
13430-221 = "#st;[0,0];instant;1;"
13430-227 = "#na;노노미;저번에 한번 싸웠었죠? 그때는 사막 한가운데였지만~"
13430-228 = "#na;아야네;(치익) 네, 하지만 조금 달라요, 그때는 색채에……."
13430-229 = "#na;세리카;아니! 설명은 아무래도 됐어! 어쨌든 저걸 그대로 놔뒀다가는 아비도스 시가지가 엉망진창이 되는 거잖아!"
13430-230 = "#na;시로코;응. 그러니 바로 제압한다."
13430-231 = "#zmc;instant;-632,444;1896\n#na;아야네;(치익) 측면을 우회해서 접근하겠습니다! 제가 엄호할 테니 돌입해 주세요!"
13430-232 = "#zmc;instant;-632,-444;1896\n#na;시로코;알겠어."
13430-233 = "#zmc;instant;-632,-444;1896\n#na;노노미;빠르게 돌격이에요~♧"
13430-234 = "#zmc;instant;-632,-444;1896\n#na;세리카;우와아아-! 그런데 호시노 선배는 어디 간 거야?!"
13430-235 = "#zmc;instant;-632,-444;1896\n#na;아야네;(치익) 네? 호시노 선배는……."
13430-236 = "#na;호시노;(치익) 이 아저씨는 이미 도착해 있다고."
13430-237 = "#na;세리카;뭐?! 언제 도착한 거야?"
13430-238 = "#na;호시노;이 녀석의 정면 쪽이야. 빨리 와~ 이 아저씨는 늙어서 오래 버티질 못한다구~"
13430-239 = "#na;시로코;응. 최대한 빨리 갈게."
13430-242 = "2;세리카;06;호시노 선배! 기다렸지?\n#2;a\n#2;hophop\n#2;em;[반응]"
13430-243 = "4;노노미;04;앗?!\n#4;em;[!]\n#4;a\n#4;stiff"
13430-245 = "3;시로코 테러;01\n#3;black\n#3;closeup"
13430-246 = "3;시로코 테러;02;늦었어.\n#3;a\n#3;em;[반응]\n#3;closeup"
13430-248 = "3;시로코;04;……!!\n#3;em;…\n#3;stiff\n#3;a"
13430-249 = "1;노노미;04;당신은……. \n#1;a"
13430-250 = "5;세리카;04;우와, 도와주러 온 거야, 또 다른 시로코 선배?\n#5;a\n#5;jump\n#5;em;[반응]"
13430-251 = "#1;hide\n#5;hide\n3;시로코 테러;05;응. 하지만 도와주는 건 이번뿐만이야."
13430-252 = "1;호시노;01;자아, 지금은 전투에 집중하라고. 빠르게 처치할 거니까.\n#1;a\n#1;em;[!]\n#3;m5"
13430-253 = "3;시로코 테러;05;응. 그럼, 포메이션 B."
13430-254 = "#st;[0,0];instant;1;"
13430-256 = "1;호시노;01\n3;시로코 테러;05\n#1;h\n#3;h\n#3;greeting\n#wait;500"
13430-257 = "#3;hide\n1;호시노;01\n5;복면시로코 테러;05\n#1;h\n#5;h\n#wait;1500"
13430-259 = "3;세리카;11;……. 아니, 그런 포메이션 약속한 적 없지 않아……?\n#3;em;[땀]"
13430-260 = "1;복면노노미;03;응응! 저는 준비 완료예요~♧\n#1;a\n#1;hophop\n#1;em;[반짝]"
13430-261 = "5;통신복면아야네;15;장난칠 시간 없습니다! 비나가 이쪽의 존재를 알아차렸어요!\n#5;a"
13430-262 = "3;세리카;04;……. 말이랑 행동이 일치하지 않잖아, 아야네 쨩…….\n#3;em;[땀]"
13430-263 = "#st;[0,0];instant;1;"
13430-265 = "1;복면노노미;03\n5;통신복면아야네;15\n3;세리카;04\n#1;d\n#3;d\n#5;d\n#1;h\n#3;h\n#5;h\n#wait;1000"
13430-266 = "3;시로코;04;으, 으음…….\n#3;a\n#3;em;…"
13430-267 = "#na;세리카;그리고 아까부터 뭔가 불안한 강아지처럼 안절부절못하지 말라고, 시로코 선배……."
13430-268 = "#st;[0,0];instant;1;"
13430-270 = "4;복면시로코 테러;05\n3;시로코;04\n#3;h\n#3;m1\n#4;al\n#4;h\n#wait;1500"
13430-271 = "4;복면시로코 테러;01;이 복면은 줄 순 없어. 이건 소중한 거니까.\n#4;em;…"
13430-272 = "#st;[0,0];instant;1;"
13430-274 = "4;복면시로코 테러;01\n3;시로코;04\n#3;em;[땀]\n#3;h\n#4;h\n#wait;1500"
13430-276 = "3;호시노;05;자아, 모두들 집중할 시간이야.\n#3;em;[반응]\n#3;closeup"
13430-277 = "#st;[0,0];instant;1;"
13430-279 = "3;호시노;05\n5;복면시로코 테러;05\n#5;a\n#3;m1\n#3;h\n#5;h\n#wait;1500"
13430-280 = "3;호시노;05\n5;복면시로코 테러;05\n#5;h\n#3;h\n#5;greeting\n#wait;500"
13430-281 = "3;호시노;05\n5;시로코 테러;05\n#5;h\n#3;h\n#wait;1500"
13430-282 = "3;호시노;05\n5;시로코 테러;05\n#5;h\n#3;h\n#3;greeting\n#wait;200"
13430-289 = "#st;[-1200,-430];instant;90;호시노"
13430-290 = "#st;[-900,-430];instant;70;[7cd0ff]대책위원회[-]"
13430-291 = "#st;[-1200,-530];serial;60;[log=호시노]좋아, 그럼 가보자고.[wa:1500] 아비도스 학생들.[/log]"
