[translation]
1401-1 = "#title;GUNS N' PEPPERS 1"
1401-2 = "#place;엔지니어부 동아리 작업실"
1401-3 = "5;코토리;01\n#5;h\n#5;a\n#5;greeting\n#wait;1000"
1401-4 = "5;코토리;01\n#5;h\n#5;greeting\n#wait;2000"
1401-5 = "5;코토리;05;으음…… 구동축과 연결된 이 하부 베어링의 무게를 줄이면 이후의 속도가…….\n#5;em;…"
1401-6 = "5;코토리;06\n#5;em;[반응]\n#wait;1500"
1401-7 = "5;코토리;03;어라, 벌써 점심시간이네요. #n우타하 선배! 손이 더러워지는 엔진 정비는 오후로 미루시고 우선 식사부터 하시죠!\n#5;hophop\n#5;em;[음표]\n#5;m3"
1401-8 = "#5;hide\n3;코토리;01\n1;우타하;03;그렇네. 잠시만 기다려줘. 이음매의 용접이 거의 다 끝났거든. #n이 작업만 마치고 같이 학생 식당에 가서 점심을 먹자.\n#1;ar"
1401-9 = "1;우타하;03\n3;코토리;01\n5;히비키;06;하지만 정비에 너무 열중한 탓인지, 작업복 곳곳에 검댕이 잔뜩…….\n#5;al"
1401-10 = "1;우타하;02;그러게. 이렇게 더러워진 작업복 차림으로 학생 식당에 들어갔다가는 다른 학생들에게 폐를 끼치겠어. ……그럼 오늘 점심도 어제처럼 작업실에서 따로 시켜 먹을까?\n#1;em;[?]"
1401-11 = "3;코토리;03;좋은 생각이에요! 안 그래도 햄과 치즈가 잔뜩 올라간 기름진 패스트푸드가 당기던 참이었거든요.\n#3;jump"
1401-12 = "5;히비키;99;다양한 재료를 한 번에 맛볼 수 있고, 손을 더럽히지 않고도 간편하게 나누어 먹을 수 있는 패스트푸드라면…….\n#5;em;…"
1401-13 = "3;코토리;01\n#5;dr\n#1;dl\n#3;d\n#wait;1000"
1401-14 = "#5;hide\n#1;hide\n3;코토리;02;역시 피자 밖에 없죠!\n#3;closeup\n#3;hophop\n#3;em;[반응]\n#3;a"
1401-15 = "1;우타하;01\n#3;hide\n5;히비키;03;동감이야. 작업실에서 먹는 배달 음식으로는 피자만한 게 없지.\n#5;greeting\n#5;em;[반짝]"
1401-16 = "1;우타하;03;후훗, 너희들은 피자를 질리지도 않고 정말 좋아하는구나.\n#1;em;[재잘]"
1401-17 = "1;우타하;02;뭐, 나도 마침 피자가 당기던 참이었으니까. #n평소에 주문하던 것처럼 페퍼로니와 치즈로 시키면 되겠지……?\n#1;m3\n#5;dr"
1401-20 = "1;피자 배달부;08;안녕하세요, <카메하메 피자>입니다! 페퍼로니와 치즈 피자 하나 주문하셨죠?\n#1;ar\n#1;em;[반응]\n#1;greeting"
1401-21 = "5;코토리;02;네, 이쪽 테이블 위에 놓아주세요.\n#5;jump\n#5;al"
1401-22 = "1;피자 배달부;01\n5;코토리;01\n#1;m2\n#5;m4\n#1;h\n#5;h\n#wait;1000"
1401-23 = "1;피자 배달부;03;확인했습니다. 주문 감사합니다!\n#1;greeting"
1401-25 = "5;코토리;03;하아, 이 진한 치즈 냄새…… 냄새만 맡았는데 벌써부터 배가 고파지네요~.\n#5;m3\n#5;em;[음표]"
1401-26 = "#5;hide\n3;히비키;03;잘 먹겠습니다…….\n#3;em;[반짝]\n#3;greeting"
1401-28 = "1;우타하;01\n5;코토리;01\n3;히비키;01"
1401-29 = "5;코토리;03;음, 역시 피자는 페퍼로니 피자가 제일이에요! #n이 고소한 치즈와 짭짤한 페퍼로니 햄의 조화가 정말 최고라니까요!\n#5;em;[반짝]"
1401-30 = "3;히비키;02;나는 치즈 피자가 좋아…… 담백한 치즈 맛이 깔끔하게 느껴지거든."
1401-31 = "1;우타하;02;그런가? 나는 치즈가 많은 게 조금 느끼한 것 같기도…… #n코토리, 거기 차바스코 소스 좀 건네 주지 않을래?"
1401-32 = "5;코토리;01;차바스코 소스는 피자 박스에 들어있지 않았나요? 이쪽에는 없는걸요."
1401-33 = "3;히비키;04;피자 박스 안에는 치즈 가루만 잔뜩…… 아무래도 배달원이 깜박했나봐.\n#3;em;[땀]"
1401-34 = "5;코토리;04;네에? 피자에 차바스코 소스를 깜박하다니, 이 무슨 중대한 실수를!\n#5;em;[?!]\n#5;shake"
1401-35 = "5;코토리;06;괘씸한 배달부를 혼내줄 겸 배달 어플의 리뷰 란에 항의를 잔뜩 써 놓도록 하죠!\n#5;m3\n#5;hophop\n#3;dl\n#1;dl"
1401-37 = "3;우타하;03;진정해, 코토리. 바쁜 일정 속에서 일을 하다 보면 우리도 부품을 한 두 개씩 잃어버릴 때도 있잖아? 이 정도의 실수는 너그럽게 봐주자고."
1401-38 = "3;우타하;02;게다가 부실 캐비닛에 저번에 먹다 남은 차바스코 소스가 남아있을 테니 그걸 가져오면 되는 일이야."
1401-39 = "3;우타하;01\n#3;m1\n#wait;1500"
1401-40 = "3;우타하;01\n#3;stiff\n#wait;1500"
1401-41 = "3;우타하;01\n#3;m4\n#wait;1500"
1401-42 = "3;우타하;01\n#3;em;…\n#wait;2500"
1401-43 = "3;우타하;04;어라? 분명 이 근처에 소스병을 놔뒀었는데…… 그게 어디로 갔지?\n#3;em;[땀]\n#3;stiff"
1401-44 = "1;코토리;02;그 캐비닛은 잡동사니가 어지러이 쌓여 있었으니까, 누군가가 공구를 꺼내다가 치워버린 게 아닐까요?\n#1;ar\n#3;m5"
1401-45 = "3;우타하;06;어휴…… 하는 수 없지. 이번에는 차바스코 소스 없이 피자를 먹는 수 밖에.\n#3;em;[속상함]"
1401-46 = "1;히비키;07;언제 어디서든 소스를 쉽게 꺼낼 수 있는 편리한 도구는 없을까……."
1401-47 = "3;우타하;06\n1;히비키;07\n#1;d\n#3;d\n#wait;1000"
1401-49 = "3;코토리;99;……….\n#3;em;…\n#3;a"
1401-50 = "3;코토리;02;선배. 저희는 피자를 평소에도 자주 시켜 먹으니까, 차라리 이 참에 차바스코 소스병을 항시 패용할 수 있도록 개조해보는 건 어떨까요?\n#3;em;[반응]"
1401-51 = "3;우타하;02;소스병을? 어떻게?\n#3;em;[?]"
1401-52 = "3;코토리;03;예를 들자면…… 학생들이 언제나 몸에서 떼어 놓지 않는 개인화기에 차바스코 소스 분사 장치를 달아놓는다던가!\n#3;em;[!]\n#3;hophop"
1401-54 = "5;히비키;02;……고작 피자 때문에 총에서 총알이 아니라 차바스코 소스가 나오게 하자고?\n#5;al"
1401-55 = "1;우타하;02;그것 참 쓸모없고 한심하기 짝이 없는 아이디어네.\n#1;ar"
1401-56 = "5;히비키;01;…….\n#5;em;…"
1401-57 = "1;우타하;01;…….\n#1;em;…"
1401-58 = "1;우타하;05;당장 만들자.\n#1;em;[반응]\n#1;closeup\n#1;jump\n#1;a"
1401-59 = "5;히비키;05;(끄덕)\n#5;greeting\n#5;closeup\n#5;a"
1401-61 = "3;코토리;03;역시 다들 좋아할 줄 알았어요!\n#3;hophop\n#3;a"
1401-62 = "3;코토리;02;자, 그럼 차바스코 소스병의 역설계부터 시작하도록 하죠!\n#3;closeup"
1401-64 = "#na;……그리하여 엔지니어부 부원들은 어처구니없는 이유로 차바스코 분사 장치가 달린 총을 개발하게 된 것이다……"
