[translation]
1600320-1 = "Special Companions"
1600320-2 = "I contacted Suzumi after I arrived at Trinity."
1600320-3 = ""
1600320-6 = "Soon after, I saw her silhouette approaching from the distance."
1600320-7 = ""
1600320-11 = "Sorry to keep you waiting, Sensei. I didn't expect you to get here so soon."
1600320-12 = "...Ah!"
1600320-13 = ""
1600320-18 = ""
1600320-20 = "...S-Sorry, Sensei."
1600320-21 = "[s1] \"Hm? Did something startle you?\"\n[s2] \"Did you just hide something behind your back...?\""
1600320-24 = "Oh, um, it's nothing really..."
1600320-25 = "Just...these."
1600320-26 = ""
1600320-28 = ""
1600320-29 = ""
1600320-30 = ""
1600320-32 = "They're, um..."
1600320-33 = "They're just the headphones I use when I patrol..."
1600320-34 = "I didn't mean to wear them in front of you! I was in a hurry, and I forgot to take them off. But, of course, I didn't have a song playing, I was just..."
1600320-35 = "Um, nevermind. I'm just rambling. Let's get going. Since you sent me our schedule, I'll lead the way."
1600320-36 = "This way..."
1600320-37 = ""
1600320-39 = ""
1600320-42 = ""
1600320-43 = ""
1600320-44 = "..."
1600320-45 = "[s3] \"Suzumi? Are you okay?\"\n[s4] \"You seem like something's bugging you.\""
1600320-48 = ""
1600320-50 = ""
1600320-51 = "H-Huh?! Oh, uh, well..."
1600320-52 = "Er..."
1600320-53 = "I'm sorry. It's not important, so I didn't want to bring it up, but... I guess it's making you uncomfortable."
1600320-54 = "Like I said, it's not important. It's just...my headphones..."
1600320-55 = "To be honest..."
1600320-56 = "I'm a little worried that I made a bad impression on you."
1600320-57 = "[s5] \"A bad impression?\"\n[s6] \"You're worried about that?\""
1600320-60 = "Well, yes. I was clearly on patrol. Anyone could see that. And yet, wearing headphones seems..."
1600320-61 = "Of course, I don't listen to music all the time, and I always have the volume on low. Mostly I turn it on when I'm on break, or when I need something to occupy me..."
1600320-62 = "I just need a little something when I'm out on long patrols."
1600320-63 = "But, even so..."
1600320-64 = "I think it may make me seem irresponsible, or oblivious. That's all. I guess... I didn't really realize how anxious I got about it."
1600320-65 = "Huh? "
1600320-66 = "Oh, it didn't seem like that to you... Well, great, but—"
1600320-67 = "[s7] \"I'm not just saying that. I mean it.\"\n[s8] \"It's not like anyone assigned you a patrol route.\"\n[s9] \"Besides, you're not doing it for thanks or acclaim.\""
1600320-71 = "That's..."
1600320-72 = "..."
1600320-73 = "...Ha..."
1600320-74 = "I never thought about it that way, but I guess that's right."
1600320-75 = "I started patrolling on my own, just to take a look around the neighborhood."
1600320-76 = "Hm, this sort of thing wouldn't usually bother me. I think I only noticed because I was with you, Sensei."
1600320-77 = "It's... a bit unlike me. I'll reflect on that."
1600320-78 = "But, I'm relieved."
1600320-79 = "Thank you, Sensei. I mean it."
1600320-80 = "What?"
1600320-81 = "My headphones? You think I modified them specially, or even made them myself?"
1600320-82 = "No, nothing like that. I don't have that kind of skill. This is just a normal pair of headphones you can buy in a store."
1600320-83 = "The only thing that's unique about them is how old and beaten up they are."
1600320-84 = "I bought them some time ago, and I often bring them out on long patrols with me."
1600320-85 = "I've even worn them during combat, occasionally. I guess I'm lucky that they haven't broken."
1600320-86 = "If they ever did break..."
1600320-87 = ""
1600320-89 = ""
1600320-90 = "Um, I don't know. I don't really feel like buying new ones, so I guess I would try to get them repaired."
1600320-91 = "[s10] \"Well, you've spent a long time with them.\"\n[s11] \"These headphones are one of your patrol partners.\""
1600320-94 = "You're...talking about them like they're alive."
1600320-95 = "But... I think I know what you mean, anyway."
1600320-96 = "...Haha..."
1600320-97 = "When I was talking about this, it was a pretty boring story... How did you make it into something special, Sensei?"
1600320-98 = "It's a strange feeling, but..."
1600320-99 = "With my headphones, and my gun too... I guess I wasn't patrolling alone all this time after all."
1600320-100 = "[s12] \"I'm always here, too!\"\n[s13] You can call me whenever. It doesn't have to be for patrolling.\""
1600320-103 = "What..."
1600320-104 = ""
1600320-106 = ""
1600320-107 = "Ah."
1600320-108 = "Well, I... Um..."
1600320-109 = "I-I'm sorry. I had a hard time finding words for a moment."
1600320-111 = "Thank you for saying that, but it's okay."
1600320-112 = "I know you're very busy, Sensei. You've got a lot of important things on your plate."
1600320-113 = "Therefore..."
1600320-115 = ""
1600320-116 = "...Mm..."
1600320-117 = "Actually, never mind. I'm sorry, but would you forget what I just said?"
1600320-118 = "Or... I'd rather say thank you than apologize right now."
1600320-119 = "I really appreciate you saying that. If you really don't mind, once in a while..."
1600320-120 = "I'd like to—no."
1600320-121 = ""
1600320-123 = ""
1600320-124 = ""
1600320-126 = "I'd really like to ask you to accompany me, Sensei."
