[translation]
1600005-1 = "#title;잘못된 방식"
1600005-2 = "3;하루카;02;……! 서, 선생님…… 와 주셨군요…… 이번에도……\n#3;a\n#3;em;[반응]"
1600005-3 = "3;하루카;00;와 주셔서 정말로 감사드립니다……\n#3;greeting"
1600005-4 = "3;하루카;07;다, 다시는 절 안 봐 주실 줄 알았어서…… 그래서……\n#3;stiff"
1600005-5 = "3;하루카;00;……네? 괜찮으니 신경 쓰지 말라고요……? 그, 그럴 수는……"
1600005-6 = "3;하루카;10;아, 아니! 제가 결코 선생님의 말씀대로 하지 않겠다는 게 아니고, 그러니까……!\n#3;shake"
1600005-7 = "3;하루카;05;아, 알겠습니다…… 최대한…… 노력해보겠습니다…… 감사합니다……\n#3;em;…"
1600005-8 = "3;하루카;00;그, 그리고…… 이번에야말로…… 제대로 된 상납품……"
1600005-9 = "3;하루카;01\n#3;greeting\n#wait;400"
1600005-10 = "3;하루카;01\n#3;closeup\n#wait;1000"
1600005-11 = "3;하루카;08;여, 여기 있습니다…… 자신은 없지만……\n#3;em;…\n#3;closeup"
1600005-12 = "[s1] \"한정판 프라모델!?\"\n[s2] \"미소녀 피규어!?\""
1600005-13 = "3;하루카;00;더, 더 있습니다…… 여기에도…… 이것도…… 이런 것도 좋아하실 거 같아서…… 전부……\n#3;em;[반응]"
1600005-14 = "3;하루카;00;더, 더 있습니다…… 여기에도…… 이것도…… 이런 것도 좋아하실 거 같아서…… 전부……\n#3;em;[반응]"
1600005-15 = "3;하루카;08;저번처럼…… 제가 만든 게 아니니 하자가 없을 것입니다…… 저번에는 죄송했습니다……"
1600005-16 = "3;하루카;08\n#3;d\n#wait;1000"
1600005-18 = "#na;(하루카가 등에 맨 꾸러미에서 한가득 귀중한 굿즈들이 쏟아져 나왔다.)"
1600005-19 = "#na;(하나 같이 값비싼 것들, 아는 사람들만 그 가치를 알아볼 정도로 귀한 것들이었다.)"
1600005-20 = "#na;(어떻게 하루카가 그 취향들을 알고 있는지는 둘째 치고, 구한 방법들은 대체……)"
1600005-21 = "3;하루카;00;어, 어떠신가요…… 선생님……\n#3;a\n#3;em;[반응]"
1600005-22 = "3;하루카;05;여, 역시…… 별로…… 신가요……?\n#3;stiff"
1600005-23 = "[s3] \"대단해, 하나 같이 훌륭한 것들뿐이야!\"\n[s4] \"이 많은 것들을 다 어디서 구한 거야?\""
1600005-24 = "3;하루카;08;……"
1600005-25 = "3;하루카;08;……"
1600005-26 = "3;하루카;09;……흐흐…… 흐흐흐……\n#3;em;[반응]\n#3;stiff"
1600005-27 = "3;하루카;09;기뻐해주시는 것 같아서…… 저도 기뻐요…… 선생님……\n#3;greeting"
1600005-28 = "3;하루카;09;앞으로도 자주 이렇게…… 선생님을 위해……\n#3;em;…"
1600005-29 = "#na;-치직! 치이익-!\n#fontsize;80"
1600005-30 = "3;하루카;02;……?\n#3;em;[?]\n#3;stiff"
1600005-31 = "#na;점원;……응? 뭐야, 왜 채널이 바뀌어?"
1600005-32 = "#na;점원;브레이킹 뉴스? ……갑자기 속보인가?"
1600005-33 = "3;하루카;07;어…… 엄……"
1600005-34 = "[s] \"……하루카?\""
1600005-35 = "3;하루카;07;……\n#3;stiff"
1600005-36 = "3;하루카;07\n#3;d\n#wait;1000"
1600005-37 = "#na;(TV에서 나오고 있던 방송들이 속속들이 뉴스 속보로 바뀌었다.)"
1600005-38 = "#na;아나운서;속보입니다. 오늘 새벽, 상점가의 굿즈 상점들에서 절도 및 강도 사건이 발생했습니다."
1600005-39 = "#na;아나운서;범행의 특징은 현금을 그대로 놔둔 채 값비싼 희소 굿즈들만 갈취해 갔다는 것으로,"
1600005-40 = "#na;아나운서;범인에게 단순한 금품목적이 아닌, 다른 특수한 목적이 있을 것으로 예상되고 있습니다."
1600005-41 = "#na;아나운서;조사팀에선 아직까지 범인이 트리니티 자치구를 빠져나가지 못했을 것이라는 예측을……"
1600005-42 = "3;하루카;07;……\n#3;em;…\n#3;stiff\n#3;a"
1600005-43 = "[s] \"……하루카.\""
1600005-44 = "3;하루카;04;……!!!\n#3;shake\n#3;em;[?!]"
1600005-45 = "3;하루카;06;그…… 그게……!"
1600005-46 = "3;하루카;07;이, 이렇게 빨리 들킬 줄은 몰랐어서……! 분명히 저녁쯤은 돼야 조사가 이뤄질 줄……!\n#3;shake\n#3;em;[속상함]"
1600005-47 = "3;하루카;10;에, 에……? 그런 이야기가 아니라고요? 그, 그렇군요. 역시 들킨 것부터가 저의 실책……\n#3;stiff"
1600005-48 = "3;하루카;05;예? 그것도 아니라고요? 으, 으음…… 으으…… 죄송합니다……\n#3;em;[반응]"
1600005-49 = "3;하루카;07;죄송합니다…… 죄송……죄송합니다죄송합니다죄송합니다죄송합니다죄송합니다……\n#3;stiff"
1600005-50 = "[s] \"돌려주러 가자.\""
1600005-51 = "3;하루카;04;예, 예!?!? 어, 어째서……! 아직 저희라고 확정돼서 추적이 온 것도 아닌데……\n#3;em;[?!]\n#3;shake"
1600005-52 = "3;하루카;10;아, 아니…… 이건 절대 말대꾸가 아니고……!\n#3;stiff"
1600005-53 = "3;하루카;00;아, 알겠습니다…… 선생님께서 그렇게 말씀하신다면……\n#3;greeting"
1600005-55 = "#na;(이후 모든 상점가 가게들을 돌며 하루카가 갈취해온 굿즈들을 돌려주었다.)"
1600005-56 = "#na;(하루카와 함께 고개 숙여 사과드렸고, 굿즈들은 포장을 뜯지 않았기에 돌려줄 수 있었다.)"
1600005-58 = "3;하루카;05;……\n#3;em;…"
1600005-59 = "3;하루카;07;죄송합니다…… 정말 죄송합니다……\n#3;stiff"
1600005-60 = "3;하루카;10;저 때문에 사과하러 다니시고…… 고개 숙이러 다니시고……\n#3;stiff"
1600005-61 = "3;하루카;07;상납품을 드리겠다고 해놓고 민폐만 잔뜩 끼치고…… 정말이지…… 저란 녀석은……\n#3;em;[속상함]"
1600005-62 = "3;하루카;10;……이제 더는……"
1600005-63 = "3;하루카;05;더는…… 선생님을 귀찮게 하지 않겠습니다……"
1600005-64 = "[s5] \"귀찮지 않아.\"\n[s6] \"상납품 없이 편하게 연락해도 돼.\""
1600005-65 = "3;하루카;06;……네……?\n#3;em;[?!]\n#3;shake"
1600005-66 = "3;하루카;06;……네……?\n#3;em;[?!]\n#3;shake"
1600005-67 = "3;하루카;05;그, 그렇지만…… 이렇게 잔뜩 폐를 끼쳐드렸는데……\n#3;stiff"
1600005-68 = "3;하루카;00;네? 좀 더 편하게 대하라고요……? 제가…… 선생님을……?\n#3;em;[반응]"
1600005-69 = "3;하루카;07;어, 어떻게 그런 짓을……! 아, 아니! 절대 싫다거나 그런 뜻은 아니지만……! 그래도……!\n#3;stiff"
1600005-70 = "3;하루카;10;아아…… 으…… 으으……"
1600005-71 = "3;하루카;05;아, 알겠습니다…… 선생님께서 시키신 거니…… 노, 노력…… 해보겠습니다……\n#3;greeting"
1600005-72 = "3;하루카;00;……저, 저기…… 선생님……"
1600005-73 = "3;하루카;01;정말로…… 화……나신 거 아닌가요……? 제가 싫어지셨다든가……"
1600005-74 = "3;하루카;02;……전혀요……? 어, 어째서…… 저는 이렇게까지 못났는데도……\n#3;em;[?]\n#3;shake"
1600005-75 = "[s7] \"선생님이잖아. 당연한 거지.\"\n[s8] \"그걸 받아주는 게 바로 내 일이야.\""
1600005-76 = "3;하루카;01;……네? 그, 그게 무슨……"
1600005-77 = "3;하루카;01;……네? 그, 그게 무슨……"
1600005-78 = "3;하루카;99;……모, 모르겠어요…… 무슨 뜻인지…… 그게 왜 이유가 되는지……\n#3;em;…"
1600005-79 = "3;하루카;00;나중에……? 천천히 알아가면 된다고요……?"
1600005-80 = "3;하루카;01;……"
1600005-81 = "3;하루카;10;죄, 죄송합니다. 제가 한심한 녀석이라…… 아직 잘 이해는 안 가지만……\n#3;stiff"
1600005-82 = "3;하루카;01;네…… 그렇게 하겠습니다……"
1600005-83 = "3;하루카;03;……헤……헤헤……"
1600005-84 = "3;하루카;08;……고맙습니다…… 선생님……\n#3;greeting\n#3;em;[반짝]"
1600005-86 = "#na;(이후 하루카는 한참동안 더 우물쭈물 거리다 종종걸음으로 사라졌다.)"
1600005-87 = "#na;(돌아가는 길에는, 하루카 덕분에(?) 미처 팔리지 않았던 한정판 굿즈들을 살 수 있었다.)"
