[translation]
1601405-1 = "Gaining Job Experience with Ibuki!"
1601405-3 = ""
1601405-4 = "Hi, Sensei!"
1601405-5 = "Like Ibuki said on MomoTalk, Ibuki is here to talk to you!"
1601405-6 = "[s1] \"Hey! I was waiting for you.\"\n[s2] \"Curious about Sensei's work again?\""
1601405-9 = "You see, Ibuki got a future...something...survey?"
1601405-10 = "Here!"
1601405-11 = ""
1601405-14 = "[ns] \"A Future Plans Survey?\""
1601405-15 = "Yeah! That!"
1601405-16 = "Ibuki is supposed to write about what Ibuki wants to be when she grows up!"
1601405-17 = "Ibuki wanted to get Sensei's opinion, because they're Ibuki's favorite grown up!"
1601405-18 = "[s] \"Future plans, huh... What do you want to do when you grow up, Ibuki?\""
1601405-19 = "Um... The thing is, Ibuki never thought about it."
1601405-20 = "On the way here, Ibuki thought about things Ibuki could do, or what might be fun..."
1601405-21 = "Ibuki thought, and thought, and thought, but Ibuki still has no idea."
1601405-22 = "[s] \"There's no need to rush, Ibuki. You have plenty of time to decide.\""
1601405-23 = "Ugh... If you say so..."
1601405-24 = "But..."
1601405-25 = "[s3] \"...How about we explore the different things you could do?\"\n[s4] \"Sensei will help.\""
1601405-28 = "Yay! Really?"
1601405-29 = "Okay! In that case, Ibuki's got a list of things to try, Sensei!"
1601405-31 = ""
1601405-32 = "Hi! It's Ibuki!"
1601405-33 = "Hello. So you're Ibuki."
1601405-34 = "[s] \"Thanks for helping out. I'm counting on you.\""
1601405-35 = "No problem, Sensei. All right, Ibuki. I'll give you the rundown on police work."
1601405-36 = "Okay! Ibuki will listen carefully!"
1601405-37 = "We go out on patrols, where we look for any issues. We also track down and arrest criminals to keep the citizens safe."
1601405-38 = "The most important thing you need to do police work is a strong sense of justice and responsibility!"
1601405-39 = "Here, try on this police cap."
1601405-40 = ""
1601405-42 = ""
1601405-43 = "Ooh! Ibuki feels like a real police officer!"
1601405-44 = "You're under arrest, Sensei! Heehee."
1601405-46 = ""
1601405-47 = "Our job is to serve delicious food to people."
1601405-48 = "My greatest joy comes from seeing the satisfied smiles of my customers!"
1601405-49 = "Can Ibuki become a cook, too?"
1601405-50 = "Of course! Anyone with patience and tact can become a great cook!"
1601405-51 = "Wanna try chopping up some ingredients? You can use a practice knife"
1601405-52 = "All right! Just you wait, Sensei! Ibuki will cook a tasty meal for you!"
1601405-54 = ""
1601405-55 = "Now, Ibuki... Piloting a tank is a complicated task that requires a lot of people to work together."
1601405-56 = "Ibuki knows that! Ibuki used to ride with Iroha when she did it. Ibuki has seen it before!"
1601405-57 = "That saves us a lot of time, then. Wanna take on the role of the tank commander for today?"
1601405-58 = "You mean Ibuki gets to pick where we go! All right!"
1601405-61 = "From morning to night, I showed Ibuki all sorts of interesting jobs."
1601405-62 = ""
1601405-63 = "[ns5] \"You have fun today, Ibuki?\"\n[ns6] \"Which job did you like the most?\""
1601405-66 = "Hmm..."
1601405-67 = "Honestly... Ibuki is not sure!"
1601405-68 = "[s] \"That makes sense. It's hard to figure out your entire future in a day...\""
1601405-69 = "But..."
1601405-70 = "...Mmm. Ibuki thinks Ibuki gets it!"
1601405-71 = "[s] \"You're not sure but you think you get it?\""
1601405-72 = "Yeah! All right, Ibuki's gonna go home for the day!"
1601405-73 = "Thank you for showing Ibuki so many cool jobs, Sensei! See you later!"
