[translation]
1601603-1 = "ไม่ต้องหาเหตุผลก็ได้..."
1601603-2 = "(คุณครูเข้ามาในเมืองเพื่อทำงานของชาเล่ต์ และกำลังซื้อของนู่นนี่อยู่)"
1601603-3 = ""
1601603-8 = "เอ๋ คุณครู? ได้เจอกันในที่แบบนี้ด้วยสินะคะ"
1601603-9 = ""
1601603-12 = "[ns1] \"หืม...? เสียงนี้มัน...\"\n[ns2] \"มิเนะเหรอ...?\""
1601603-13 = ""
1601603-14 = ""
1601603-17 = ""
1601603-18 = "ออกมาทำงานของชาเล่ต์เหรอคะ? ฮุฮุ บังเอิญจังเลยนะคะ"
1601603-19 = "ฉันเองก็ออกมาเพราะงานของชมรมอัศวินบรรเทาทุกข์เหมือนกันค่ะ ถ้าคุณครูไม่ว่าอะไร ขอฉันไปกับ#nคุณครูด้วยได้มั้ยคะ?"
1601603-20 = ""
1601603-22 = ""
1601603-23 = "คุณครู? ทำไมล่ะคะ? ทำไมถึงทำหน้าแบบนั้นล่ะ..."
1601603-24 = "อ้อ... หมายถึงชุดนี้น่ะเหรอคะ?"
1601603-25 = ""
1601603-27 = ""
1601603-28 = ""
1601603-29 = "อ่า... นั่นสินะคะ ขอโทษด้วยค่ะ ฉันยังไม่ได้อธิบายสินะคะ"
1601603-30 = "นี่เป็นงานของชมรมอัศวินบรรเทาทุกข์ก็จริง แต่เป็นงานแสดงเพื่อให้กำลังใจน่ะค่ะ ฉันเลยคิดว่าชุดนี้#nน่าจะเหมาะกว่าชุดที่ใส่เป็นปกติค่ะ"
1601603-31 = "ก็เป็นอย่างนี้ละค่ะ"
1601603-32 = "[s3] \"อ่า... สุดท้ายก็เป็นงานที่ต้องเหนื่อยสินะ\"\n[s4] \"มิเนะตั้งใจทำงานจังเลยนะ\""
1601603-35 = "ฮุฮุ ไม่หรอกค่ะ เรื่องแค่นี้เอง"
1601603-36 = ""
1601603-38 = ""
1601603-39 = "งั้นในเมื่อหายสงสัยแล้ว... เราไปกันต่อดีมั้ยคะ?"
1601603-40 = ""
1601603-42 = ""
1601603-46 = "(ไม่กี่วันหลังจากนั้น...)"
1601603-52 = "(คุณครูออกมาที่ร้านอาหารระดับหรูที่อยู่แถวนั้นเพื่อคุยงาน)"
1601603-53 = ""
1601603-58 = "หืม...? คุณครู??"
1601603-59 = ""
1601603-63 = ""
1601603-64 = "เอ๋... ได้เจอกันในที่แบบนี้อีกแล้วนะคะ เราเพิ่งบังเอิญเจอกันเมื่อไม่กี่วันก่อนไม่ใช่เหรอคะ?"
1601603-65 = "แต่ฉันก็ดีใจมากเลยนะคะที่บังเอิญเจอคุณครูบ่อยๆ แบบนี้... ฮุฮุ"
1601603-66 = "[s5] \"ใส่ชุดไอดอลอีกแล้ว วันนี้มีการแสดงเหรอ?\"\n[s6] \"มิเนะในชุดไอดอลอีกแล้วแฮะ มีการแสดงที่นี่เหรอ?\""
1601603-69 = "คะ...?"
1601603-70 = "คะ... ครั้งนี้ฉันไม่ได้มาเพราะการแสดงหรอกค่ะ ฉันมาเพราะมีคนแนะนำว่าอาหารของที่นี่อร่อยค่ะ"
1601603-71 = "ส่วนชุดนี้ก็แค่..."
1601603-72 = ""
1601603-74 = ""
1601603-75 = ""
1601603-76 = "..."
1601603-77 = "พะ... พอดีฉันหาชุดที่เป็นทางการและเข้ากับบรรยากาศ ก็เลยได้เป็นชุดนี้มา ค่ะ..."
1601603-78 = "ก็ที่นี่เป็นร้านอาหารที่ค่อนข้างหรูหรานี่คะ ฉันเลยคิดว่าถ้าใส่ชุดที่เหมือนชุดเดรสมา ก็น่าจะเหมาะ#nกับโอกาสค่ะ"
1601603-79 = "[s7] (เหมาะกับโอกาส...?)\n[s8] (อะไรกัน? ความเงียบเมื่อครู่นี้มัน...)"
1601603-82 = "อ่า... เอาเถอะค่ะ เมื่อกี้คุณครูบอกว่ามาที่นี่เพราะมีธุระ ถ้างั้นวันนี้ฉันขอตัวก่อนดีกว่าค่ะ"
1601603-83 = "ขอโทษที่เสียมารยาทนะคะ ถ้างั้นฉันขอตัวก่อน..."
1601603-84 = ""
1601603-86 = ""
1601603-89 = "(หลังจากนั้นคุณครูก็ได้บังเอิญเจอมิเนะอีกเป็นครั้งคราว)"
1601603-92 = ""
1601603-95 = ""
1601603-98 = ""
1601603-100 = "(และในทุกครั้งที่เจอ มิเนะจะอยู่ในชุดไอดอล และมากับข้ออ้างที่ดูจะแปลกขึ้นทุกครั้ง...)"
1601603-101 = ""
1601603-106 = "(และในวันต่อมา...)"
1601603-107 = ""
1601603-112 = "(คืนนั้นคุณครูทำงานจนดึก จึงแวะไปที่ร้านสะดวกซื้อเพื่อให้หายง่วง)"
1601603-113 = ""
1601603-118 = ""
1601603-119 = ""
1601603-120 = ""
1601603-121 = "เอ๋... คุณครู ดึกป่านนี้ยังออกมาข้างนอกอีกเหรอคะ?"
1601603-122 = "อ๊ะ หรือว่าคุณครูยังทำงานอยู่คะ? อืม... ต้องเหน็ดเหนื่อยจนถึงดึกดื่นเลยนะคะเนี่ย"
1601603-123 = "ถึงฉันจะทำงานแทนให้ไม่ได้ แต่ฉันก็อยากขอบคุณที่คุณครูทำงานอย่างหนักเพื่อพวกเราอยู่เสมอค่ะ"
1601603-124 = "แล้วก็..."
1601603-125 = ""
1601603-127 = ""
1601603-128 = ""
1601603-129 = "อ่า..."
1601603-130 = "คือว่า... คุณครู"
1601603-131 = "พอดีตอนนี้... เอ่อ ชุดนี้น่ะค่ะ..."
1601603-132 = "[s9] \"มิเนะ ไม่เป็นไรหรอก...\"\n[s10] \"ไม่ต้องหาข้อแก้ตัวทุกครั้งก็ได้...\""
1601603-133 = ""
1601603-134 = ""
1601603-136 = ""
1601603-137 = "มะ... ไม่ใช่อย่างนั้นนะคะ! พอดีว่า...! เอ่อ...!"
1601603-138 = "อืม...! ฉันต้องพูดยังไงดีนะ เอ่อ..."
1601603-139 = ""
1601603-141 = ""
1601603-142 = "อ้อ แค่ชุดอยู่บ้าน! ตอนนี้ฉันไม่ได้ออกมาข้างนอกในฐานะหัวหน้าชมรมอัศวินบรรเทาทุกข์ แต่ออกมาเพราะเรื่องส่วนตัวค่ะ งั้นนี่ก็เป็นแค่ชุดอยู่บ้านธรรมดา...!!"
1601603-143 = "ไม่สิ เดี๋ยวนะ ปกติเราใส่ชุดแบบนี้เป็นชุดอยู่บ้านหรือเปล่านะ? อืม...!!"
1601603-144 = "งั้นต้องบอกว่าอะไรดีนะ? ฉันควรบอกว่าอะไรถึงจะดูเป็นธรรมชาติเหรอคะ?"
1601603-145 = "ดะ... เดี๋ยวสิ ฉันจะหาเหตุผลต่อหน้าคุณครูแบบนี้ได้เหรอ...!!"
1601603-146 = ""
1601603-148 = ""
1601603-149 = ""
1601603-150 = "หืม? เมื่อกี้คุณครูว่าอะไรนะคะ?"
1601603-151 = "คะ...? ไม่เป็นไรงั้นเหรอคะ? ยะ... ยังไงคะ..."
1601603-152 = "[s11] \"ไม่ต้องแก้ตัวหรอก ครูรู้ว่ามิเนะชอบอะไรน่ารักๆ\"\n[s12] \"ดีแล้วละที่ใส่ชุดตามความชอบของตัวเอง\""
1601603-155 = "อ่า... อย่างนั้นสินะคะ ค่ะ ถ้างั้นก็ค่อยยังชั่ว..."
1601603-156 = "เดี๋ยวนะ..."
1601603-157 = ""
1601603-159 = ""
1601603-160 = ""
1601603-161 = "คุณครู...?"
1601603-162 = "เดี๋ยวนะคะ คุณครู ที่คุณครูพูดเมื่อกี้... อ่า..."
1601603-163 = ""
1601603-168 = ""
1601603-169 = "เอ่อ... ค่ะ"
1601603-170 = "คุณครูรู้ตั้งแต่แรก... เลยสินะคะ..."
1601603-171 = "อย่างนี้นี่เอง..."
1601603-172 = ""
1601603-174 = ""
1601603-175 = ""
1601603-176 = "คุณครูคะ..."
1601603-177 = ""
1601603-179 = ""
1601603-180 = ""
1601603-182 = "[ns13] \"คุณมิเนะ...!? เป็นอะไรไป...!?\"\n[ns14] \"ทำไมทำหน้าเหมือนโกรธกันล่ะ!!\""
1601603-183 = ""
1601603-184 = ""
1601603-185 = "ก็..."
1601603-187 = "ถ้าคุณครูรู้อยู่แล้ว ทำไมไม่บอกกันตั้งแต่ก่อนหน้านี้ล่ะคะ?"
