[translation]
1601802-1 = "#title;대장의 방문"
1601802-3 = "[ns1] \"라~브~!!\"\n[ns2] \"웰컴 투 샬레!!!!!\""
1601802-6 = "3;라브;11;시, 시끄러!!! 목소리 너무 크잖아!!!\n#3;a\n#3;em;[!]\n#fontsize;80"
1601802-7 = "[s3] \"라브가 샬레에 찾아와줬어!\"\n[s4] \"기념일로 정할래!!!!\""
1601802-10 = "3;라브;21;뭐, 뭐뭐뭐뭐!! 뭔 기념일이야!! 무슨 소리야!!\n#3;em;[///]\n#3;stiff"
1601802-11 = "3;라브;22;그보다, 왜 현관에 있던 거야? 뭔가 일이라도 하고 있었어?"
1601802-12 = "[s] \"아니? 사무실에서 달려온 건데?\""
1601802-13 = "3;라브;06;강아지냐고, 무슨!!\n#3;em;[땀]"
1601802-14 = "3;라브;04;굴러서 다치면 어쩌려고!"
1601802-15 = "3;라브;14;하아…… 환영해 주는 건 좋은데 말야.\n#3;em;[속상함]"
1601802-16 = "3;라브;21;선생은…… 그게……."
1601802-17 = "3;라브;22;다른 사람들 시선 신경 안 쓰여?"
1601802-18 = "[s5] \"나 뭔가 옷 이상하게 입고 왔어?\"\n[s6] \"제일 아끼는 옷 입고 온 건데…….\""
1601802-21 = "3;라브;14;아니, 아니! 그런 걸 말하는 게 아니야!"
1601802-22 = "3;라브;02;그…… 뭐냐, 일단 선생은 모범이 되는 사람이고……."
1601802-23 = "3;라브;05;학생회나, 발키리나…… 그런 쪽하고도 많이 교류하잖아."
1601802-24 = "3;라브;14;……하아,\n#3;em;[한숨]"
1601802-25 = "3;라브;21;나 같은 불량 학생하고 같이 있어도 되냐는 말이야."
1601802-26 = "[s] \"응? 그게 왜?\""
1601802-27 = "3;라브;14;아니, 그러니까……."
1601802-28 = "3;라브;15;하, 됐다. 괜한 걱정을 했네. 선생은 아무 생각도 없구나.\n#3;em;[땀]"
1601802-29 = "[s] \"라브는 엄청 좋은 아이인데?\""
1601802-30 = "3;라브;20;엑?!\n#3;jump"
1601802-31 = "[s7] \"연락할 때 조심해서 연락하고,\"\n[s8] \"내 안부도 물어주고,\"\n[s9] \"넘어지지 않게 걱정도 해주고!\""
1601802-35 = "3;라브;20;아, 아니!! 갑자기 무슨 소리야!!\n#3;hophop\n#3;em;[스팀]"
1601802-36 = "3;라브;22;그 정도는 기본이라고! 내가 뭐 엄청 나쁜 사람도 아니고 말이야!"
1601802-37 = "3;라브;14;그래, 알았어. 선생이 괜찮다면 된 거지, 뭐."
1601802-38 = "3;라브;05;그래도, 너무 대놓고 같이 있으면…… 좀 그렇잖아."
1601802-39 = "3;라브;09;이만 가볼게. 건강 조심하고. 계단에서 뛰지 말고.\n#3;em;[재잘]"
1601802-40 = "3;라브;01;그럼 이만-"
1601802-41 = "[ns10] (라브를 샬레로 데려간다)\n[ns11] (샬레에 라브를 데려간다)"
1601802-44 = "3;라브;01\n#3;d\n#wait;2000"
1601802-45 = "3;라브;11;뭐, 뭐해?! 뭐 하는 거야?!\n#3;a\n#3;closeup\n#3;em;[?!]"
1601802-46 = "[s12] \"라브는 내 자랑스러운 학생인걸!\"\n[s13] \"샬레 구경시켜 줄게!\""
1601802-49 = "3;라브;04;샤, 샬레?! 지금?!\n#3;closeup"
1601802-50 = "[s] \"업어줘?\""
1601802-51 = "3;라브;20;더 안되지, 멍청아!!\n#3;em;[///]\n#3;stiff\n#3;closeup"
1601802-52 = "3;라브;21;업지는 말고 그냥 데려가!!\n#3;closeup"
1601802-54 = "#na;(이후, 라브를 데리고 샬레를 구경시켜 주었다.)"
1601802-55 = "#na;(즐거운 시간을 보냈다.)"
