[translation]
1601905-1 = "อัปเกรด"
1601905-2 = "อย่างที่คุณครูทราบว่าฉันได้อาวุธใหม่มาค่ะ"
1601905-3 = "และมันก็อยู่ในสภาพที่ได้รับการ 'อัปเกรด' แล้วค่ะ"
1601905-4 = "[s] \"อื้อ ใช่แล้วละ\""
1601905-5 = "ค่ะ อย่างที่คุณครูทราบว่ามันคือปืนพลังงานคู่"
1601905-6 = "หรือที่เรียกกันว่าอาวุธพลังงานนั่นเองค่ะ"
1601905-7 = "อาวุธพลังงานคืออาวุธที่ใช้งานได้อย่างไม่จำกัด ตราบใดที่มีพลังงานป้อนเข้ามาอยู่ตลอดภายใน#nขอบเขตที่รับรองความทนทานได้ค่ะ"
1601905-8 = "เรียกว่ายิงได้แบบไม่มีลิมิตเลยค่ะ"
1601905-9 = "แค่นั้นยังไม่พอ มันยังเป็นปืนพกคู่ที่แม็กจุกระสุนได้ไม่จำกัดด้วยค่ะ"
1601905-10 = "คุณครู ไม่รู้สึกอะไรเลยเหรอคะ?"
1601905-11 = "[s1] \"กระสุนไม่จำกัด... ปืนพกคู่... อึก... ปวดหัวจัง...!\"\n[s2] \"คะ... ครูก็ไม่ค่อยแน่ใจเหมือนกัน...?\""
1601905-14 = "นี่ไม่ใช่ความคิดเห็นส่วนตัวของฉันหรอกนะคะ แต่ฉันได้ยินมาจากรายการในอินเทอร์เน็ตว่านี่เป็น#nการจับคู่ที่ลงตัวสุดๆ เลยค่ะ"
1601905-15 = "ฉันว่านี่คือการอัปเกรดที่เหมาะกับเฟิสต์แอนด์เพอร์เฟกต์ อะซุมะ โทคิ ในตอนนี้ที่สุดเลยค่ะ เย่ เย่"
1601905-16 = "[s] \"แล้วตกลงว่ามีเรื่องอะไรเหรอ...\""
1601905-17 = "ไม่ใช่เรื่องใหญ่อะไรหรอกค่ะ"
1601905-18 = "ฉันแค่มีความคิดประมาณนี้น่ะ"
1601905-19 = "คุณครู อย่างที่คุณครูทราบว่าฉันมีอาวุธหลายอย่างค่ะ"
1601905-20 = "และในบรรดาของเหล่านั้น ก็มีปลอกแขนอาร์มเกียร์ที่ฉันใช้บ่อยๆ ตอนทำปฏิบัติการแฝงตัวด้วยค่ะ"
1601905-21 = "และในตอนนี้ที่ฉันใช้ระบบอาวุธพลังงานได้"
1601905-22 = "ฉันว่ามันต้องเท่มากแน่ๆ ถ้าอัปเกรดอะไรให้ได้มากที่สุด..."
1601905-23 = "แล้วก็น่าจะสนุกด้วย..."
1601905-28 = "นอกจากนี้ก็น่าจะเป็นประโยชน์ต่อการเพิ่มกำลังต่อสู้ของเราด้วย..."
1601905-29 = "[s] \"เหมือนเพิ่งเผยความรู้สึกที่แท้จริงออกมาเลยนะ?\""
1601905-30 = "ฟังผิดแล้วค่ะ"
1601905-31 = "[s] \"อ๋อ งั้นสินะ?!?! ครูไม่รู้ตัวเลยละเนี่ย!?!?\""
1601905-32 = "เป็นอย่างที่ว่าเลยค่ะ"
1601905-33 = "หืม? ถอนหายใจแบบนั้นหมายความว่าอะไรคะ? ว่ากันว่าถ้าถอนหายใจบ่อยเกินไป โชคลาภจะหนีไปหมดนะคะ"
1601905-34 = "แต่ตราบใดที่มีฉันที่เป็นทั้งหน่วยลาดตระเวน สายลับ และเมดกระต่ายอยู่ที่นี่ ก็คงไม่มีปัญหาค่ะ"
1601905-35 = "[s] \"แล้วสรุปว่าอยากอัปเกรดอะไรเหรอ...\""
1601905-36 = "ค่ะ ฉันกำลังพูดเรื่องนั้นอยู่สินะคะ"
1601905-37 = "ฉันไปลองคิดมาค่ะ"
1601905-38 = "ถ้าเอาระบบอาวุธพลังงานมาใช้กับปลอกแขนอาร์มเกียร์ที่ส่วนใหญ่ประกอบด้วยกระสุนขนาดเล็ก"
1601905-39 = "ปลอกแขนนี้ก็น่าจะใช้เป็นเครื่องยิงจรวดได้นะคะ?"
1601905-40 = "[s] \"เครื่องยิงจรวด!\""
1601905-41 = "สมกับเป็นคุณครูจริงๆ ค่ะ กะไว้แล้วเชียวว่าต้องมีปฏิกิริยาแบบนี้"
1601905-42 = "ว่ายังไงล่ะคะ คุณครู? เป็นไอเดียที่บรรเจิดสุดๆ เลยใช่มั้ยคะ?"
1601905-43 = "รีบยอมรับว่าเป็นอย่างที่ฉันว่า และชมฉันให้ตัวลอยเลยสิคะ"
1601905-44 = "ไม่อยากเห็นฉันตอนใช้เครื่องยิงจรวดเหรอคะ?"
1601905-45 = "ถึงคุณครูจะไม่อยากเห็น แต่ฉันอยากเห็นนะคะ งั้นก็เร็วเข้าสิคะ"
1601905-46 = "[s] \"ครูขอถามอะไรอย่างหนึ่งนะ\""
1601905-47 = "อะไรเหรอคะ คุณครู?"
1601905-48 = "[s] \"ทำไมถึงต้องมาขออนุญาตจากครูด้วยล่ะ?\""
1601905-52 = "..."
1601905-53 = "......"
1601905-54 = "........."
1601905-55 = "[s] \"โทคิ มองตาครู\""
1601905-56 = "ค่ะ คุณครู"
1601905-57 = "[s] \"แล้วก็ตอบมาตามตรง\""
1601905-58 = "..."
1601905-59 = "[s] \"ทำไมถึงเบนสายตาไปทางอื่นล่ะ?\""
1601905-63 = "ช่วยไม่ได้นะคะ งั้นฉันคงต้องบอกแล้วละค่ะ"
1601905-64 = "ฉันไม่ได้รับอนุญาตจากท่านริโอะกับหัวหน้าฮิมาริด้วยเหตุผลด้านความปลอดภัยค่ะ"
1601905-65 = "สาเหตุก็เพราะมีโอกาสสูงที่จะเกิดแผลไหม้เนื่องจากแรงดันความร้อนระหว่างการขับเคลื่อนค่ะ"
1601905-66 = "[s] \"ถ้างั้นก็ยิ่งไม่ได้เลยไม่ใช่เหรอ?\""
1601905-67 = "คุณครู"
1601905-68 = "เมื่อเทียบกับผลลัพธ์บางอย่างแล้วละก็ บางครั้งเราก็อาจมองข้ามความเสียหายหรือความเสี่ยงเล็กๆ น้อยๆ ที่อาจเกิดขึ้นได้นะคะ คุณครูไม่คิดอย่างนี้เหรอคะ?"
1601905-69 = "แต่นี่ไม่ใช่เรื่องเล็กน้อย ก็เลยเป็นปัญหางั้นเหรอคะ?"
1601905-70 = "..."
1601905-71 = "ถึงคุณครูจะมองว่าไม่ใช่เรื่องเล็กน้อย แต่สำหรับฉันมันเป็นเรื่องเล็กน้อยค่ะ งั้นก็รีบๆ อนุญาตสิคะ"
1601905-72 = "[s] \"ไม่ได้\""
1601905-73 = "คุณครู..."
1601905-74 = "[s] \"ต่อให้จ้องกันอย่างนั้นก็ไม่ได้\""
1601905-75 = "ถ้างั้นฉันขอแฮนด์แคนนอนที่ยิงพลังงานออกมาเป็นลำแสงก็ได้"
1601905-76 = "ถ้าอัปเกรดจนยิงได้ครั้งละ 3 นัด และถ้าติดตั้งชิ้นส่วนเพิ่มเติมจนมีระดับพลังงานเพิ่มขึ้นตามไปด้วยได้ ก็น่าจะดีเลยนะคะ"
1601905-77 = "[s] \"ไม่~ อนุมัติ~\""
1601905-78 = "คุณครู..."
1601905-80 = "(คุณครูเหนื่อยกับการปลอบโทคิที่เหมือนจะงอนอยู่นิดหน่อย)"
1601905-81 = "(สุดท้ายคุณครูก็ต้องยอมทำตามคำขอของโทคิด้วยการกอดแน่นๆ และลูบหัว โทคิจึงหายงอน...)"
