[translation]
1801-1 = "วันหยุดของชมรมทวงความยุติธรรม 1"
1801-2 = "โรงงานร้างใกล้ๆ กับสถาบันทรีนิตี้"
1801-3 = "กรี๊ดดดดดด!\n"
1801-5 = "อย่ามาก่อเรื่องวุ่นวายนะ! ถ้าขัดขืนล่ะก็เจอดีแน่!"
1801-6 = "พะ...พวกเธอเป็นใครกันแน่? ทำไมถึงต้องลักพาตัวฉันมาที่นี่ด้วย?"
1801-7 = "เด็กนักเรียนของสถาบันทรีนิตี้จะรู้เรื่องพวกนี้ไปทำไม?"
1801-8 = "พวกเธอจะถูกขังเอาไว้ที่นี่จนกว่าโรงเรียนจะจ่ายเงินค่าไถ่ตัวประกันตามที่เราเรียกร้องไป!#nอย่าได้คิดจะเล่นตุกติกเชียว!"
1801-9 = "คะ?! บะ... บอกสถาบันทรีนิตี้แล้วงั้นเหรอคะ?"
1801-10 = "เอ๊ะ? แน่นอนอยู่แล้ว! เราตัดการติดต่อไปแล้ว พวกเราได้ลักพาตัวนักเรียนของคุณมา#nถ้าอยากได้ตัวพวกเธอคืนล่ะก็..."
1801-11 = "ไม่ได้การ ทุกคนหนีไป... ไม่สิ รีบหลบเร็วเข้า!!!"
1801-12 = "หืม?"
1801-13 = "นั่นเสียงอะไรน่ะ?"
1801-15 = "ตู้มมมมม!!\n"
1801-16 = "ฮะ...เฮือกกก?! "
1801-17 = "อะ...อะไรเนี่ย?! นี่มันเรื่องอะไรกัน?! "
1801-18 = ""
1801-19 = "หึหึหึหึหึ... หึหึหึ"
1801-20 = ""
1801-21 = "คึคึคิกๆๆๆๆๆ!! "
1801-22 = "วะ....หวาาา...??!"
1801-23 = "ผะ...โผล่ออกมาแล้ว!! มันโผล่มาแล้ว!!!"
1801-24 = ""
1801-25 = "ว้ากกกกกก----!!!!"
1801-27 = ""
1801-28 = "โรงพยาบาลกลางของชมรมอัศวินบรรเทาทุกข์"
1801-29 = "...เป็นยังไงบ้างคะ?\n"
1801-30 = "โชคดีที่พวกนักเรียนที่ถูกจับเป็นตัวประกันไม่ได้เป็นอะไรมาก..."
1801-31 = "บางคนดูเหมือนว่าจะมีอาการ PTSD จากความเครียดมากด้วย...#nควรพักผ่อนให้เต็มที่อย่างน้อย 3 สัปดาห์นะคะ"
1801-32 = "....."
1801-33 = "รุ่นพี่เซรินะคะ ฉันกลับมาแล้วค่า~!"
1801-34 = "ฉันส่งตัวพวกแก๊งหมวกกันน็อกเดโกะโบโกะไปที่โรงพยาบาลรัฐในเขตชานเมืองเรียบร้อยแล้วค่ะ!"
1801-35 = "พวกนั้นโดนอัดซะเละจนเหมือนกระป๋องโค้กที่ถูกทุบเลยค่ะ น่ากลัวจนไม่อยากเข้าไปรักษาเลย...!"
1801-36 = "เรื่องนั้นใช่ไหมคะ? คุณซึรุกิจากชมรมทวงความยุติธรรม..."
1801-37 = "ฮานาเอะจัง...."
1801-38 = ""
1801-39 = "อ๊ะ ขะ...ขอโทษ..."
1801-40 = ""
1801-41 = ""
1801-42 = "ถ้างั้นก็ขอรบกวนด้วยนะคะ"
1801-43 = "แหะๆ... ค่า~ ได้เลยค่ะ"
1801-45 = "เฮ้อ..."
1801-46 = "ขอบคุณมากค่ะ รุ่นพี่"
1801-47 = "ต่อไปก็ต้องไปขอบคุณ <ชมรมซิสเตอร์> ที่ไปช่วยหาตัวประกันในอาคารที่ถล่มลงมา..."
1801-48 = "อ่า... นั่นสินะคะ ฉันต้องไปที่นั่นด้วย..."
1801-49 = "ต่อไปก็ต้องไปจัดการเรื่องเรียกร้องค่าเสียหายกับทางฝ่ายบริหาร..."
1801-50 = "อืม... ใช่แล้วค่ะ"
1801-51 = "ต้องไปที่สำนักงานใหญ่ของเซอร์เคิลเพื่อรายงานเรื่องการใช้กระสุนที่มากเกินไปด้วย...."
1801-52 = "....."
1801-53 = "ถ้าเพื่อความยุติธรรมล่ะก็... คงจะเลี่ยงไม่ได้ ฉันคิดแบบนั้นค่ะ"
1801-54 = "แต่ถึงอย่างนั้น...."
1801-55 = "ไม่รู้ว่าทำไมซึรุกิถึงได้ดูเศร้านิดๆ แบบนี้กัน..."
1801-56 = "มันก็เรื่องปกติไม่ใช่เหรอคะ?"
1801-57 = "แต่ว่ายังไงเรื่องนั้นก็...."
1801-58 = "อื้อ...?"
1801-59 = "เป็นอะไรไปคะ รุ่นพี่?"
1801-60 = "อ่า... คลิปวิดีโอจากทางสภาน้ำชาค่ะ"
1801-61 = "คะ? ที่สภาน้ำชาเหรอคะ?"
1801-63 = "ฉันได้ฟังเรื่องที่เกิดขึ้นวันนี้แล้ว ทุกๆ คน"
1801-64 = "ภารกิจกู้ภัยสำเร็จได้ด้วยดีค่ะ#nแต่นักเรียนที่ถูกจับเป็นตัวประกันทั้งหมดก็ต้องเข้ารักษาตัวที่โรงพยาบาล..."
1801-65 = "มีนักเรียนบางคนบอกว่ารู้สึกเจ็บปวดใจและเครียดมากหลังจากที่เห็นหน้าของคุณซึรุกิ..."
1801-66 = "....."
1801-67 = "ฉันลองมาคิดดูแล้ว"
1801-68 = "เพื่อจะหาว่าทำไมถึงเกิดเรื่องแบบนี้ไม่หยุดไม่หย่อนกับชมรมของพวกคุณกันค่ะ"
1801-69 = "ฉันคิดว่าสิ่งที่สำคัญคือ... \"การแลกเปลี่ยน\" ค่ะ"
1801-70 = "จะเรียกว่าการแลกเปลี่ยนดีไหมนะ... จิตสำนึกแห่งความถูกต้องกับ... การแลกเปลี่ยน... ของความรัก"
1801-71 = "ฉันคิดว่าเป็นเรื่องสำคัญที่ชมรมทวงความยุติธรรมทุกคนควรเรียนรู้ อีกนัยหนึ่งก็คือ#nฉันคิดว่าพวกคุณควรได้พบปะกับสมาชิกชมรมอื่นๆ ให้มากขึ้นค่ะ"
1801-72 = "เพราะงั้นฉันถึงคิดแผนการขึ้นมาค่ะ พรุ่งนี้ชมรมทวงความยุติธรรมจะหยุดทำงานหนึ่งวัน"
1801-73 = "แต่ขอให้ทุกคนไปลองเข้าร่วมกิจกรรมของชมรมอื่นๆ ในโรงเรียนแทนนะคะ"
1801-74 = "แผนการของฉันสมบูรณ์แบบดีอยู่แล้ว ฉันคิดว่าจะทำให้ทุกๆ คนเข้าใจความคิดและจิตใจ#nของคนอื่นๆ ได้ดีมากขึ้นค่ะ"
1801-75 = "ฮุฮุ เป็นยังไงคะ? ตั้งตารอกันเลยใช่ไหมล่ะคะ"
1801-76 = "ถ้างั้นทุกคนก็สู้ๆ นะคะ~☆"
1801-78 = "อ๋อ ต้องเข้าร่วมนะคะ ห้ามเบี้ยวค่ะ ไม่มีกรณียกเว้นด้วยค่ะ"
1801-79 = ""
1801-80 = "....."
1801-81 = "...หมายความว่ายังไงคะ รุ่นพี่? ให้ไปสังเกตการณ์ชมรมอื่นเหรอคะ...?"
1801-82 = "ฮ่า... นี่มันอะไรกันอีกล่ะ.... "
