[translation]
1802-1 = "วันหยุดของชมรมทวงความยุติธรรม 2"
1802-2 = "สวนในสถาบันทรีนิตี้"
1802-3 = "(การประชุมตอนมื้อเที่ยงของชมรมการอ่านวรรณกรรม)"
1802-4 = "ได้อ่านหนังสือรวมกลอนเล่มใหม่ของอาจารย์โยชิโมโตะรึยังคะ?"
1802-5 = "ได้แน่นอนค่ะ ทำไมถึงเขียนบรรยายความรู้สึกของผู้หญิงที่เจ็บปวดจากการถูกบอกเลิก#nได้ดีแบบนั้นนะ... อ่านแล้วรู้สึกสะเทือนใจจริงๆ ค่ะ"
1802-6 = "......\n\n"
1802-7 = "จริงสิ ฉันได้ยินมาว่าบทความใหม่ของอาจารย์โนกามิจะตีพิมพ์ตอนปลายเดือนนี้ด้วยล่ะ"
1802-8 = "อุ๊ยตาย จริงเหรอคะเนี่ย? ผลงานเล่มที่แล้วสนุกมากจนฉันรอเล่มใหม่แทบไม่ไหวแล้วค่ะ"
1802-9 = "......"
1802-10 = "แล้ว... คุณมาชิโระคิดยังไงบ้างคะ? ช่วงนี้มีหนังสือสนุกๆ ที่อ่านอยู่บ้างไหมคะ?"
1802-11 = "ฉะ...ฉันเหรอคะ? หนังสือเล่มล่าสุดที่อ่านก็คงเป็น <สิ่งที่เรียกว่าความยุติธรรม> ค่ะ"
1802-12 = "เรื่อง <สิ่งที่เรียกว่าความยุติธรรม>.....? เป็นหนังสือแบบไหนเหรอคะ?#nหนังสือกลอน? บทความ? หรือว่านิยายเหรอคะ?"
1802-13 = "คะ...คือว่าฉันกำลังเขียนตัวอย่างเกี่ยวกับการทำให้เกิดความยุติธรรมขึ้นมา..."
1802-14 = "อ่ะฮ่า หนังสือปรัชญาเหรอคะ เป็นหนังสือที่ยอดเยี่ยม#nเหมาะกับคุณมาชิโระที่เอาจริงเอาจังอยู่เสมอๆ เลยนะคะ"
1802-15 = "ถ้าไม่ติดธุระอะไร ช่วยเล่าเนื้อเรื่องให้ฟังสักหน่อยได้ไหมคะ?"
1802-16 = "การย่อใจความสำคัญของความยุติธรรมเป็นเรื่องที่ยากมาก... อืม..."
1802-17 = ""
1802-19 = "(อืม น่าเบื่อจัง... อยากให้ชมรมทวงความยุติธรรมกลับมาเหมือนเดิมเร็วๆ จัง...)"
1802-20 = "(พวกรุ่นพี่จะเป็นยังไงกันบ้างนะ...)"
1802-22 = "(การประชุมวิสามัญของสภาน้ำชา)"
1802-23 = "อุ๊ย คุณฮาสุมิชงชาได้ดูคล่องแคล่วมากเลยนะคะ"
1802-24 = "ฉันเพิ่งเคยได้ดื่มชาแดงที่รสชาติดีแบบนี้เป็นครั้งแรกเลยค่ะ"
1802-25 = "อุณหภูมิของน้ำและระยะเวลาที่ใช้ในการชงจะส่งผลทำให้รสชาติของชาแตกต่างกันไปค่ะ"
1802-26 = "หากยึดมั่นในหลักพื้นฐานและคุมเวลาได้แล้วล่ะก็ จะสามารถเพลิดเพลินกับชาแสนอร่อยได้นะคะ"
1802-27 = "ดูเหมือนคุณฮาสุมิมักจะคำนึงถึงความยุติธรรมในทุกๆ การกระทำทุกอย่างเลยนะคะ"
1802-28 = "จริงด้วยค่ะ ท่าทางการพูดก็ดูมีระดับ แถมการแต่งตัวก็ดูสง่างาม....!"
1802-29 = "ชมกันเกินไปแล้วค่ะ ฉันยังต้องฝึกฝนอีกเยอะเลยค่ะ"
1802-30 = "ว่าแต่ว่า ใบชาอันนี้กลิ่นหอมมากเลยนะคะ ใบชาของที่ไหนเหรอคะ?"
1802-31 = "ใบชานั่นเป็นของขวัญที่ทางสถาบันเกเฮนน่าส่งมาให้เมื่อคราวที่แล้วค่ะ#nเป็นใบชาแดงที่ปลูกได้ยาก ทาง <สภาน้ำชา> จึงแบ่งมาให้เรานิดหน่อยค่ะ"
1802-32 = "...เกเฮนน่าเหรอคะ?"
1802-33 = "ไม่คิดเลยว่าพวกคนไร้ค่าพวกนั้นจะให้ของขวัญใครเป็นด้วย นี่ถึงกับให้ใบชาพวกเรามาเลยงั้นเหรอ..."
1802-34 = "ฉันยอมเอาน้ำผสมโคลนมาล้างปากยังจะดีซะกว่ามาดื่มของแบบนี้!"
1802-35 = "ช่วยเอาใบชาที่เหลือไปเผารวมกับกองใบไม้ตรงนั้นด้วยนะคะ#nของที่พวกคนไร้ค่าให้มาก็ไม่ต่างจากขยะ ไม่น่าดื่มหรอกค่ะ"
1802-36 = ""
1802-37 = "สมกับเป็นรองหัวหน้าชมรมทวงความยุติธรรมจริงๆ เลยค่ะ#nถ้าเป็นเรื่องเกี่ยวกับเกเฮนน่าแล้วล่ะก็ คุณจะเย็นชาเสมอๆ เลยนะคะ"
1802-38 = "นะ...น่ากลัวจังเลย"
1802-40 = "(การประชุมวันจันทร์ประจำสัปดาห์ของชมรมของหวานหลังเลิกเรียน)"
1802-41 = ".....\n\n"
1802-42 = ".....\n"
1802-43 = "......."
1802-44 = ""
1802-45 = ""
1802-46 = "........"
1802-47 = "(นะ....น่าอึดอัดจัง)"
1802-48 = "(อะไรกันเนี่ย?! ทำไมหัวหน้าของคณะกรรมการเพื่อความยุติธรรมถึงอยู่กับเราได้ล่ะ?!)"
1802-49 = "(ฉันก็ไม่รู้เหมือนกันนั่นแหละ....)"
1802-50 = "ไง..."
1802-51 = "(โล่งอกไปที?! แล้วจะทำยังไงต่อล่ะ?!)"
1802-52 = "(ถะ...ถึงจะถามฉันก็เถอะ....!)"
1802-53 = ""
1802-54 = "(ลองคุยด้วยดีไหมนะ?)"
1802-55 = "(บ้ารึยังไง?! เดี๋ยวก็โดนจับได้หรอก!!)"
1802-56 = ""
1802-57 = "(อะไรเนี่ย?! จะ...จริงเหรอ?!)"
1802-58 = "(ถึงยังไง มันก็ไม่น่าจะใช่แบบนั้นนะ...)"
1802-59 = "....."
1802-60 = "กะ...กรี๊ดดดดดดด!!"
1802-61 = "(เฮือก!)"
1802-62 = "(!!?)"
1802-63 = "(อะ... อ๊ะ?! อะไรน่ะ?! ทำไมทำแบบนั้นล่ะ?)"
1802-64 = "(ไม่รู้สิ! ฉันจะไปรู้ได้ยังไงล่ะ...!)"
1802-65 = "....."
1802-66 = "..."
1802-67 = "(อ๊ะ เงียบไปแล้ว)"
1802-68 = "ฮะ..."
1802-69 = "ฮะฮะฮะฮ่าฮ่าฮ่าฮ่าฮ่าฮ่า------"
1802-70 = ""
1802-72 = ""
1802-73 = "(นะ...น่ากลัวจัง)"
1802-74 = "(พูดไม่รู้เรื่อง....)"
1802-75 = "(อยากกลับบ้านจัง...)"
1802-77 = "สวนในสถาบันทรีนิตี้"
1802-78 = "(วันต่อมา)"
1802-79 = "(หลังหยุดพักผ่อนมาทั้งวัน สมาชิกคณะกรรมการเพื่อความยุติธรรมก็มารวมตัวกัน)"
1802-80 = "การคุยกันอย่างสง่างามเหมือนนักเรียนหญิงคนอื่นๆ ในโรงเรียนทรีนิตี้เป็นเรื่องยากมาก...#nไม่รู้เลยว่ามันยากขนาดนี้ค่ะ"
1802-81 = "ฉันรู้สึกเหมือนว่าหลังจากไปร่วมงานที่สภาน้ำชาก็มีคนเลี่ยงที่จะพบปะฉันมากขึ้นค่ะ...."
1802-82 = "รุ่นพี่ซึรุกิ รุ่นพี่เป็นอะไรหรือเปล่าคะ?"
1802-83 = "....?"
1802-84 = "อ่า..."
1802-85 = "เป็นการพบปะกันที่สนุกจริงๆ "
1802-86 = "ค่อยยังชั่วหน่อยที่ทุกคนชอบน่ะ"
1802-87 = "ฮิฮิ ฮี่ๆ..."
1802-88 = "ฮี่ๆๆๆๆ--!"
1802-89 = "......."
1802-90 = "ฮื้อ? ดูเหมือนสนุกกันใหญ่เลยนะคะ "
1802-91 = "เอาจริงเหรอคะ...."
1802-92 = "ถึงฉันจะไม่ชอบใจที่ต้องทำตามแผนการของคุณนางิสะก็เถอะ#nแต่ก็ค่อยยังชั่วที่ซึรุกิได้ปลดปล่อยความเครียดบ้างค่ะ ถือเป็นโชคดีท่ามกลางเรื่องโชคร้ายค่ะ"
1802-93 = "พอได้เห็นซึรุกิมีสีหน้าสบายใจแบบนี้แล้ว ฉันก็โล่งใจมากค่ะ"
1802-94 = "ชมรมขนมหวานหลังเลิกเรียนเองก็คิดแบบนั้นใช่ไหมคะ?"
1802-95 = ""
1802-96 = ""
1802-97 = "ฮี่ๆๆๆๆ-!"
1802-98 = "วันหยุดของชมรมทวงความยุติธรรม"
