[translation]
1901-1 = "Weekly Prefect Team Meeting"
1901-4 = ""
1901-5 = "Now it's time for us to start the regular weekly Prefect Team meeting."
1901-6 = "*sigh* "
1901-7 = "Ako, I have an important meeting with the Pandemonium Society today, so let's get this over with quickly."
1901-8 = "Fine. The next meeting is in fifteen minutes, so I think we can finish before then."
1901-9 = "First, we need to go over the report on the unidentified explosion that occurred in Zone 97-44."
1901-10 = "We've confirmed that the explosion in Zone 97-44 was caused by a dual-purpose high explosive used for blasting."
1901-11 = "This is certainly the work of the Hot Springs Department... The suspects are currently on the run, and three squads are pursuing them."
1901-12 = "What's their motive?"
1901-13 = "Hot springs development, as always."
1901-14 = "Wait... Isn't Zone 97-44 in the middle of the freeway? They detonated a high-power explosive to develop a hot spring there?"
1901-15 = "That's correct. They have no guilt when it comes to the development of hot springs..."
1901-17 = "So, I have to ask...why are you doing this?"
1901-18 = "It doesn't matter where we find a hot spring, as long as we find them! Dig 'em all up!"
1901-19 = "Hahaha! Burn it all! Burn all this useless trash!"
1901-20 = "Bulldoze everything! It's demolition time! Demolition! Development is all that matters! "
1901-21 = "(I have no idea what they're saying... What am I supposed to do?)"
1901-25 = ""
1901-26 = "This is the gist of Chinatsu's report. I don't understand it, though..."
1901-27 = "I'm guessing they were going to build something like...a freeway rest stop."
1901-28 = "*sigh*"
1901-29 = "The freeway is expected to be backed up for about three months, so that means fifty-four percent of the goods transported..."
1901-30 = "Right. You can leave the rest to the Pandemonium Society. What's next?"
1901-31 = "Okay. The next incident is the explosion in a school dining hall..."
1901-32 = "The dining hall explosion... Was it the Gourmet Research Society?"
1901-33 = "That's correct, President."
1901-34 = "And the motive?"
1901-35 = "This time, it was because, well.. There was no lemon on the karaage..."
1901-36 = "Lemon...?! "
1901-37 = "They took Fuuka, the School Lunch Club president, hostage and argued with the Prefect Team members who came to subdue them."
1901-39 = "Okay, let me ask you a very important question, Prefect Team."
1901-40 = "Should lemon go on karaage or not?!"
1901-41 = "Well, everyone? What do you think?"
1901-42 = "Well, in my opinion...I-I think...there should be lemon..."
1901-43 = "What? That would make the tempura all soggy! Why would you sprinkle lemon juice on it?!"
1901-44 = "But the refreshing scent of lemon cuts through the greasiness of the tempura!"
1901-45 = "Haha! All right...all right. This is apparently a serious gastronomic quest! It's exactly what the Gourmet Research Society wants to see!"
1901-46 = "What's the right thing to do here? Come on, let's figure out the answer, guys!"
1901-47 = "*murmuring* So...lemon would cut through..."
1901-48 = "*murmuring* I mean, then the batter on the tempura would..."
1901-49 = "*murmuring* Then, what about salt?"
1901-50 = "*murmuring* Why change the topic all of a sudden? I mean, I prefer soy sauce!"
1901-51 = "Heehee!"
1901-52 = ""
1901-54 = ""
1901-55 = "(Ugh... I don't care either way... Please, just get me out of here.)"
1901-59 = ""
1901-60 = "(The heated debate escalated into a physical fight. Many of the Prefect Team members, including Iori, were hospitalized. After that, the Gourmet Research Society ran away.)"
1901-61 = "*sigh*"
1901-62 = "Ask the School Lunch Club president to figure out the damage and submit a report. "
1901-63 = "If we lose another dining hall, we'll only have rice balls to eat for lunch!"
1901-64 = "Got it, President."
1901-65 = "Next up... A group that forged absence letters and sold them for 2,000 yen per sheet has been arrested."
1901-66 = "Problem Solver?"
1901-67 = "That's correct. It was Problem Solver 68... They trespassed into the faculty office and made a copy of the absence letter stamp. "
1901-68 = "They shamelessly posted an ad on the academy bulletin board that read, \"Want to skip school? Buy one of our absence letters and leave whenever you want!\""
1901-69 = "Absence letters? But no one asks to be absent at our academy..."
1901-71 = "How come no one is buying any of these?!"
1901-72 = "Ugh! We're doomed, Aru!"
1901-73 = "*fidgets nervously*"
1901-76 = ""
1901-77 = "*sigh*"
1901-81 = ""
1901-82 = "Yep, exactly. So they couldn't even sell one sheet. The crimes here are trespassing and forgery of official documents."
1901-83 = "*sigh*"
1901-84 = "Next..."
1901-85 = "Wait... How many more things are there on the docket?"
1901-86 = "Eighteen more, President."
1901-87 = "What?! These all happened over the course of a week?"
1901-88 = "No, these only cover the last two days. Since the Intelligence Committee is on vacation, the report for the remaining five days will be available at next week's meeting."
1901-89 = "...Oh, no..."
1901-90 = "Ugh..."
1901-91 = "Cheer up, President!"
1901-92 = "*sigh*"
1901-93 = "Weekly Prefect Team Meeting"
