[translation]
2000406-1 = "Enjoying High Places"
2000406-2 = "Higashitsu Beach"
2000406-3 = "Mashiro has been doing volunteer work, so I came to the beach to treat her to some ice cream."
2000406-4 = "[s] \"She said she'd be here...\""
2000406-5 = "Oh, Sensei. I'm here."
2000406-6 = "[s1] \"Mashiro? Where are you?\"\n[s2] \"Are you wearing the ghillie suit again?\""
2000406-7 = "N-No, not at all."
2000406-8 = "N-No, not at all."
2000406-9 = "This time..."
2000406-10 = "...I'm right above you."
2000406-11 = "[s] \"Above me?\""
2000406-12 = ""
2000406-14 = ""
2000406-15 = "I should be asking you why you're here. Why come all this way?"
2000406-16 = "Oh, you've brought ice cream."
2000406-17 = "I'm admittedly parched from the heat. Thank you, Sensei."
2000406-18 = "[s] \"Where were you?\""
2000406-19 = "I was sitting on a coastal watchtower installed over here."
2000406-20 = "I can see the entire beach from atop it."
2000406-21 = "[s] \"You really like high places, Mashiro.\""
2000406-22 = "That isn't why I was on top of the watchtower."
2000406-23 = "I need to have eyes on the entire beach, so it's simply convenient to be at a high place."
2000406-24 = "Being up high also eliminates blind spots, making it easier to shoot. Also..."
2000406-25 = "...the cool breeze reduces the risk of heat stroke, even if I have to wait several hours to take my shot."
2000406-26 = "It doesn't hurt that the scenery is also more picturesque from up high."
2000406-27 = "Speaking of which, why not join me atop the watchtower, Sensei?"
2000406-28 = "The ice cream will taste even better if we enjoy it in front of a beautiful view."
2000406-29 = "[s] \"Wouldn't it be too small for two people?\""
2000406-30 = "Don't worry. It'll be a tight fit, but it should be fine if we sit close together."
2000406-31 = "You're not uncomfortable with sitting close to me...are you?"
2000406-32 = "[s] \"No, it's not like that.\""
2000406-33 = "Then let's go. "
2000406-34 = ""
2000406-35 = ""
2000406-36 = ""
2000406-37 = "The ladder is slippery, so please watch your step and follow me."
2000406-39 = "Mashiro and I looked at the beach from the watchtower until sunset."
