[translation]
2000802-1 = "Whatever, There's Conspiracy!"
2000802-2 = "I arrived at the meeting place Ako and I agreed upon after her unfriendly MomoTalk message and found a huge amount of paperwork piled on the table."
2000802-3 = ""
2000802-5 = ""
2000802-6 = "Uh, this is because...it's connected to this side..."
2000802-7 = ""
2000802-9 = ""
2000802-10 = "*sigh* Really! How am I supposed to do all of THIS?!"
2000802-11 = "[s] \"Hello?\""
2000802-12 = "S-Sensei?!"
2000802-13 = "When did you get here? Don't scare me like that..."
2000802-14 = "*sigh* Seriously."
2000802-15 = "[s] \"Looks like you have a lot on your plate. Everything all right?\""
2000802-17 = "Huh?"
2000802-18 = "This is my typical workload, more or less."
2000802-19 = "And it has to be done by this evening. I've already processed one pile, so I may as well look over those too."
2000802-20 = "This is nothing. I'll be done with most of these in a heartbeat. Heehee. "
2000802-21 = "[s] \"(Your expression just a moment ago tells me a different story...)\""
2000802-22 = "I can't call myself the manager of the Prefect Team if I cry over this measly amount of work."
2000802-23 = "Oh, but never mind that. I called you here for a reason."
2000802-24 = ""
2000802-26 = ""
2000802-27 = ""
2000802-28 = ""
2000802-29 = "Could you check these documents?"
2000802-30 = "[s] \"Request for a Schale report on suspect Prefect Team activities?\""
2000802-31 = "Yes. It turns out that this is something only you can do."
2000802-32 = "I wanted to know if there are any complaints about our Prefect Team from Schale."
2000802-33 = "[s1] \"Yeah, but...\"\n[s2] Politely decline."
2000802-34 = "Hmph. Don't wanna cooperate, huh?"
2000802-35 = "Hmph. Don't wanna cooperate, huh?"
2000802-36 = "Are you sure, though? I thought you'd want to pay me back for all I've done for you."
2000802-37 = "[s] \"And what's that supposed to mean?\""
2000802-38 = "Don't play dumb with me."
2000802-39 = "I look after you on a daily basis. Do you have any idea how difficult it is for the administrator of the Prefect Team—that's me—to take care of your work?!"
2000802-40 = "[s3] \"You do?\"\n[s4] \"I guess there's some truth to that. Maybe. Possibly.”"
2000802-41 = "What's with that lukewarm reaction?"
2000802-42 = "What's with that lukewarm reaction?"
2000802-43 = "Huh?! Wait."
2000802-44 = "Is this what adults do when they don't want to admit something incriminating?! Something about pleading... \"Plead the...\"?"
2000802-45 = "[s] \"I don't know whether that's a right in Kivotos...\""
2000802-46 = ""
2000802-48 = ""
2000802-49 = "Hmm. Either way, I wasn't expecting a straight answer."
2000802-50 = "Then next time."
2000802-51 = ""
2000802-53 = ""
2000802-54 = ""
2000802-55 = ""
2000802-56 = "[ns] \"Describe your thoughts and ideas regarding the Prefect Team in 20 thousand characters or less?\""
2000802-57 = "This is a light test. Think of it as a simple document to verify your true intentions."
2000802-58 = "Oh, and it goes without saying that you shouldn't even think about lying."
2000802-59 = "Don't you think inferring someone's values from their use of context, vocabulary, language, etc. will be easy as pie for a capable administrator like myself?"
2000802-60 = "[s] \"Do you really need to go this far?\""
2000802-61 = "Huh?"
2000802-62 = "Of course I do! Surveillance of dangerous forces is not to be neglected for even one second!"
2000802-63 = "Furthermore, Schale is one of the most cagey organizations around! Its purpose, structure, and history are suspicious, so it's only natural we'd investigate further."
2000802-64 = "[s] \"The Schale you're talking about is me, you know.\""
2000802-65 = "Our Prefect Team has fought enemies who hate us everywhere and in every conceivable form!"
2000802-66 = "But we've never lost or suffered."
2000802-67 = "What would I hide...?"
2000802-68 = "Yes, me! Because I have zero tolerance for any uncertainties!"
2000802-69 = "[s5] \"I see.\"\n[s6] \"I think there's more to it than that, but you do work hard.\""
2000802-70 = "Well, that's excluding the head prefect... But, honestly, I don't think that even this is enough."
2000802-71 = "Well, that's excluding the head prefect... But, honestly, I don't think that even this is enough."
2000802-72 = "Just yesterday, there was a terrorist attack against the Prefect Team. You can't let your guard down."
2000802-73 = "[s] \"Terrorist attack? What happened?\""
2000802-74 = "Well, what happened was..."
2000802-75 = "I was working overtime in the annex building early yesterday morning when suddenly..."
2000802-76 = "We had a blackout!"
2000802-77 = "[s] \"...\""
2000802-78 = "A blackout in the middle of a mission... There's no doubt in my mind."
2000802-79 = "This could only be a terrorist attack organized by rebellious forces who knew that I, the administrator of the Prefect Team, was working overtime alone."
2000802-80 = "They shut down the building's generators to interfere with the Prefect Team's work."
2000802-81 = "Their conniving plans have caused me to be unable to finish my work properly!"
2000802-82 = "[s] \"...Isn't that just a coincidence?\""
2000802-83 = "No! There's no way! Regardless, there are still plenty of people in Gehenna who are looking for weaknesses in the Prefect Team, you know?!"
2000802-84 = "If you allow even the slightest gap to appear, they'll eat you alive!"
2000802-85 = "This situation is also definitely, irrefutably, beyond a shadow of a doubt an act of sabotage against the Prefect Team!"
2000802-86 = "Let us bet on it, Sensei! If I find the culprit, you'll do 10 laps around the gym on your hands."
2000802-87 = "[s] \"C-Calm down.\""
2000802-88 = "The number of suspects is already in the double digits!"
2000802-89 = "This is... Yes! There's no other way! As soon as I return to the academy, I must install 100 security cameras to catch the culprit!"
2000802-90 = ""
2000802-92 = ""
2000802-93 = "Whew."
2000802-94 = "Excuse me. It seems I got a little carried away. Heehee."
2000802-95 = "My goodness, how did that happen?"
2000802-96 = "I may have showed you a side of myself I shouldn't have."
2000802-97 = "[s] \"No, I don't mind it at all, but about the...\""
2000802-98 = "Please forget about today."
2000802-99 = "Then, please take care of the discussed paperwork. I must attend to my next task, so..."
2000802-100 = ""
2000802-102 = ""
2000802-104 = "[s] \"E-Excuse me?\""
2000802-106 = "(For some reason, Ako left in a hurry.)"
