[translation]
2000605-1 = "ร้านอาหารแสนอร่อยของซายะ"
2000605-2 = "ร้านราเม็งสไตล์จีน"
2000605-3 = "ที่นี่คือหนึ่งในร้านราเม็งร้านโปรดของฉันเลยละ!"
2000605-4 = "มาสเตอร์ของร้านนี้จะใช้แต่วัตถุดิบสดใหม่ สร้างสรรค์เมนูใหม่ๆ ที่แสนพิเศษออกมา"
2000605-5 = "เมนูราเม็งที่คิดขึ้นใหม่อาทิตย์นี้ก็คงอร่อยแน่ๆ~♪"
2000605-6 = "เอ๋? ทำไมถึงทำหน้าแบบนั้นล่ะคุณครู? ทำไมทำหน้าพะอืดพะอมแบบนั้นล่ะ"
2000605-7 = "หรือว่าคุณครูไม่ชอบราเม็งสไตล์จีนงั้นเหรอ?"
2000605-8 = "[s1] \"ไม่ได้ไม่ชอบหรอก...\"\n[s2] \"เหมือนได้กลิ่นคาวจากที่ไหนสักแห่ง...\""
2000605-12 = ""
2000605-13 = "อ๊ะ ซายะ มาแล้วสินะ"
2000605-14 = "ว่าไงมาสเตอร์ คราวนี้ฉันจะมาลองชิมเมนูใหม่กับคุณครูด้วยแหละ!"
2000605-15 = "ขอโทษด้วยนะ แต่ว่าอาทิตย์นี้ร้านเราเปิดขายเมนูใหม่ไม่ได้หรอก ถ้าอยากชิมราเม็งใหม่#nอาจจะต้องไปร้านอื่นแล้วละ"
2000605-16 = "ว่าไงนะ? เมื่ออาทิตย์ก่อนมาสเตอร์ยังเตรียมน้ำซุปสูตรใหม่อย่างมีความสุขอยู่เลยนี่นา"
2000605-17 = "หรือว่าน้ำซุปจะมีปัญหาอะไรงั้นเหรอ?"
2000605-18 = "คือว่า... ฉันเตรียมน้ำซุปสูตรใหม่ไว้แล้ว แต่มันดันมีปัญหาที่ยังแก้ไม่ได้อยู่เรื่องหนึ่ง..."
2000605-19 = "ถ้างั้นเธอมาดูน้ำซุปก่อนมั้ยล่ะ?"
2000605-20 = ""
2000605-21 = ""
2000605-22 = "[s] กลิ่นคาวเมื่อกี้นี้..."
2000605-23 = "จริงด้วย น้ำซุปนี้น่ะฉันใช้ปลาคูซายะปรุงขึ้นมา"
2000605-24 = "เนื่องจากใช้ซุปปลาเข้มข้นปรุงขึ้น มันเลยเป็นน้ำซุปที่มีรสชาติเข้มข้นกลมกล่อมที่สุดเท่าที่ฉันเคยทำ#nแต่ฉันยังกำจัดกลิ่นคาวพวกนี้ไม่ได้เลยน่ะสิ"
2000605-25 = "ถ้าขายเมนูนี้ให้กับลูกค้าล่ะก็ชื่อเสียงที่สั่งสมมาในย่านการค้าเทพเต่าดำคงย่อยยับแน่"
2000605-26 = "นะ... น่าเสียดายจัง ฉันอุตส่าห์รอเมนูใหม่ของมาสเตอร์อยู่แท้ๆ..."
2000605-27 = ""
2000605-28 = "เพราะงั้นซายะ... มีซอสสูตรลับอะไรที่ช่วยขจัดกลิ่นคาวได้บ้างไหม?"
2000605-29 = "หืม? ทำไมถึงมาถามฉันล่ะ?"
2000605-30 = "ที่ผ่านมาเธอวิจัยเรื่องผลของวัตถุดิบต่างๆ มาตั้งเยอะใช่ไหมล่ะ?"
2000605-31 = "เพราะงั้นฉันเลยคิดว่าเธอน่าจะรู้จักวัตถุดิบดีๆ ที่มีผลต่อการรับรู้กลิ่นของคน..."
2000605-32 = "มีคำกล่าวว่า นักกินที่ไปชิมอาหารมาหลากหลายมักจะรู้ดีที่สุดยังไงล่ะ"
2000605-33 = "แล้วมันเกี่ยวกับเรื่องนี้ยังไงล่ะ?"
2000605-34 = "ฮุฮุฮุ แต่ก็พอดีเลย!"
2000605-35 = "พอดีฉัน \"บังเอิญ\" มียาตัวหนึ่งที่ช่วยลดกลิ่นที่ไม่พึงประสงค์ได้อยู่ด้วยนะ"
2000605-36 = "[s3] \"พอดีงั้นเหรอ...?\"\n[s4] \"บังเอิญงั้นเหรอ...?\""
2000605-37 = "ทำไมถึงทำหน้าสงสัยแบบนั้นล่ะ?"
2000605-38 = "ทำไมถึงทำหน้าสงสัยแบบนั้นล่ะ?"
2000605-39 = "ถ้าเป็นนักวิจัยที่เก่งกาจละก็ ไม่ว่าจะไปที่ไหนก็ต้องพกวัตถุดิบไปด้วยเพื่อให้พร้อมวิจัยได้ทุกที่ยังไงล่ะ"
2000605-40 = "อีกอย่างมันก็แค่ซอสที่ช่วยขจัดกลิ่นไม่พึงประสงค์เอง ใช้วัตถุดิบธรรมดาก็ปรุงขึ้นมาได้ง่ายๆ แล้ว!"
2000605-41 = "โอ้วววว ถ้างั้นมาทดลองกับราเม็งสูตรใหม่ของฉันเลยแล้วกัน!"
2000605-42 = "ฮุฮุฮุ ถ้างั้นก็มาเริ่มกันเลยดีมั้ย!"
2000605-45 = "― หึหึหึ... แบบนี้นี่เอง กลิ่นฉุนสุดๆ ไปเลยนะ...[wa:4060] "
2000605-47 = "― ถ้าเป็นแบบนี้ละก็... คงจะกินยากแน่ๆ[wa:1410] "
2000605-50 = "― ก่อนอื่น...ก็ใส่สารดับกลิ่นลงไปหนึ่งช้อน เพื่อขจัดกลิ่นคาว[wa:1680] "
2000605-52 = "― แล้วก็ใส่ผงมัสตาร์ดลงไปสองช้อนพูนๆ เพื่อลดประสิทธิภาพการรับกลิ่นลง...[wa:1060] "
2000605-55 = "― อร่อยเหาะแน่นอน~ อร่อยเหาะแน่ๆ~[wa:1280] "
2000605-58 = "― วะ...ว้าก..?[wa:610] "
2000605-60 = "― ดันเผลอใส่...ผงมัสตาร์ดเยอะเกินไปซะแล้ว![wa:930] "
2000605-63 = "― แต่ ก็นะ ไม่เป็นไรหรอกน่า[wa:2250] "
2000605-65 = "― แค่ใส่สารดับกลิ่นเพิ่มลงไปอีกหน่อย แค่นั้นก็เรียบร้อยแล้วล่ะ![wa:1350] "
2000605-68 = "เรียบร้อยแล้ว! ลองชิมดูสิ!"
2000605-69 = "ฉันใส่ซอสสูตรพิเศษลงไปเต็มพิกัดแล้ว คราวนี้ไม่ต้องกังวลเรื่องกลิ่นคาวแล้วละ!"
2000605-70 = "กลิ่นเหม็นคาวหายไปแล้ว..."
2000605-71 = "คราวนี้ก็ลองชิมรสชาติดูหน่อย..."
2000605-72 = ""
2000605-74 = ""
2000605-75 = ""
2000605-76 = ""
2000605-78 = "ผะ...เผ็ดมากกกกก!"
2000605-79 = "แค่กๆๆ นี่มันอะไรกันเนี่้ย! ซอสนี่เผ็ดสุดๆ ไปเลย คงกินต่อไม่ได้แล้วละ!"
2000605-80 = "ฮุฮุฮุ... แบบนั้นแหละ!"
2000605-81 = "ปัญหาก็คือจมูกของเราไวต่อกลิ่นคาวมากเลยได้กลิ่นเร็วน่ะ"
2000605-82 = "เพราะงั้น..."
2000605-83 = "ถ้าใส่ซอสเผ็ดลงไปเยอะๆ ทำให้ประสาทรับกลิ่นเป็นอัมพาตซะ เท่านี้ก็จะไม่ได้กลิ่นแล้วยังไงล่ะ!"
2000605-84 = "ท่านซายะนี่เก่งกาจจริงๆ! โฮะ โฮะ โฮะ!"
2000605-85 = "แต่ว่าถ้าน้ำซุปเผ็ดขนาดนี้... จะมีลูกค้ามากินไหมเนี่ย?"
2000605-87 = ""
2000605-88 = "น้ำซุปเผ็ดมากเลยงั้นเหรอ?"
2000605-89 = "ขอฉันลองชิมหน่อยได้ไหม?"
2000605-90 = "คุณคือ...?"
2000605-91 = "ได้แน่นอน เชิญลิ้มรสซอสสูตรพิเศษของท่านซายะให้เต็มที่เลย!"
2000605-92 = "ไหนดูซิ..."
2000605-93 = ""
2000605-95 = ""
2000605-96 = ""
2000605-97 = ""
2000605-99 = "ผะ...เผ็ดมากกกกก!"
2000605-100 = "[s] \"คิดแล้วว่าต้องพูดแบบนี้...\""
2000605-101 = "แค่กๆๆ... นี่เป็นรสชาติที่เผ็ดจัดจ้านที่สุดที่ฉันเคยกินมาเลย ถ้าเป็นคนทั่วไปละก็ แค่ตักใส่ปากก็ร้องไห้แล้วมั้ง"
2000605-102 = "ถึงรสชาติจะเผ็ดจัดจ้าน... แต่ก็รับรู้ได้ถึงรสชาติที่อร่อยล้ำลึกที่แฝงอยู่ได้ ไม่เลวเลยทีเดียว"
2000605-103 = "อีกอย่าง รสเผ็ดก็ช่วยกระตุ้นความอยากอาหารขึ้นมาอีกด้วย!"
2000605-104 = "ฉันตัดสินใจแล้ว..."
2000605-105 = "ผู้ชนะในราเม็งประจำสัปดาห์ครั้งนี้ก็คือราเม็งเผ็ดถ้วยนี้!"
2000605-106 = "หรือว่าคุณคือนักชิมในตำนาน... อาจารย์เนโกะบาระ?"
2000605-107 = "ฮึ่ม... ไม่สำคัญหรอกว่าฉันเป็นใคร สิ่งที่สำคัญก็คือร้านนี้มีอาหารอร่อยๆ อยู่ต่างหากล่ะ"
2000605-108 = ""
2000605-109 = "อีกไม่นานที่ร้านนี้คงมีคนมารอแน่นขนัดแน่ๆ เอาไว้ฉันจะกลับมาใหม่แล้วกันนะ"
2000605-110 = ""
2000605-112 = ""
2000605-114 = "อะไรกัน ลูกค้าลึกลับคนนั้น จู่ๆ เข้ามากินแล้วก็หายตัวไปซะงั้น"
2000605-115 = "ยังไงก็เถอะ ถือว่าแก้ปัญหาได้แล้ว ฉันกลับก่อนแล้วกันนะ"
2000605-118 = "ที่นี่คือร้านราเม็งที่อาจารย์เนโกะบาระเขียนชมในโซเชียลรึเปล่า?"
2000605-119 = "อาจารย์เขียนไว้ว่าถ้าเป็นคนที่ชอบกินอาหารรสจัดจ้านแล้วล่ะก็ควรจะต้องมาลองสักครั้ง...#nขอสั่งอาหารหน่อย!"
2000605-120 = "ฉันด้วยๆ ขอราเม็งรสเผ็ดชื่อดังหนึ่งที่!"
2000605-121 = "ราเม็งใหม่ยังไม่เปิดขายอย่างเป็นทางการเลยนะ แล้วทุกคนรู้ได้ยังไงน่ะ?"
2000605-122 = "รอสักครู่นะคะ!"
2000605-123 = ""
2000605-124 = "ผะ...เผ็ดจัดจ้านนนน! แต่อร่อยเหาะเลย!"
2000605-125 = "รสชาติเผ็ดจัดจ้านแบบไม่เคยกินที่ไหนมาก่อนเลย! ฉันตกหลุมรักเมนูนี้ซะแล้วสิ..."
2000605-126 = "ละ... ลิ้นชาไปหมดแล้ว แต่ว่าก็หยุดกินไม่ได้เลย...!"
2000605-127 = ""
2000605-129 = ""
2000605-130 = "อะ...อะไรกัน อร่อยจริงเหรอ?"
2000605-131 = "(ฉันคิดไม่ถึงจริงๆ เลยนะเนี่ย...)"
2000605-132 = "[s] \"สีหน้าเหมือนจะบอกว่า 'คิดไม่ถึงจริงๆ' เลยนะ\""
2000605-133 = "มะ...ไม่ใช่สักหน่อย ท่านซายะคิดไว้ตั้งแต่แรกแล้วว่ามันจะต้องอร่อยน่ะ!"
2000605-134 = "ถ้างั้นเรามาลองชิมดูหน่อยมั้ย?"
2000605-136 = "(จากนั้นคุณครูกับซายะก็แบ่งราเม็งสูตรพิเศษชิมกันอย่างเอร็ดอร่อย)"
2000605-137 = "(แล้วจากนั้นคุณครูก็ต้องทนทรมานปวดท้องเหมือนมีไฟไหม้อยู่ในกระเพาะไปอีก 2-3 วัน...)"
