[translation]
2000603-1 = "#title;천재의 휴일"
2000603-2 = "#na;(사야의 메시지가 신경 쓰여 몰래 뒤를 밟아보았다.)"
2000603-4 = "#place;산해경 현무상회"
2000603-5 = "3;사야 사복;04;으으, 어째서 다들 믿어주지 않는 것이냐?!\n#3;em;[속상함]\n#3;stiff\n#3;a"
2000603-6 = "3;사야 사복;99;평범한 치즈 케이크라고 몇 번이나 말했는데도 수상하다며 도망치다니……."
2000603-7 = "3;사야 사복;05;……그래도 오늘은 네즈스케가 함께 있으니, 종업원도 거절하지는 못할 것이다!\n#3;em;[!]"
2000603-8 = "3;사야 사복;02;그렇지, 네즈스케?\n#3;em;[반응]"
2000603-9 = "#na;네즈스케;찍찍……."
2000603-10 = "3;사야 사복;03;좋아. 그럼 바로 가게로 들어가볼까?\n#3;hophop\n#3;em;[음표]"
2000603-11 = "#st;[0,0];instant;1;"
2000603-13 = "3;사야 사복;01\n#3;dl\n#wait;2000"
2000603-14 = "[ns] 사야를 뒤쫓아간다."
2000603-16 = "#place;현무상회 내 케이크 팝업 스토어"
2000603-18 = "3;로봇 종업원;03;어서 오세요, 손님. 몇 분이신가요?\n#3;em;[음표]\n#3;greeting\n#3;a"
2000603-19 = "5;사야 사복;02;한 사람이다!\n#5;em;[반응]\n#5;al\n#3;m1"
2000603-20 = "5;사야 사복;99;왜냐하면 오늘의 나님은 고독한 천재……"
2000603-22 = "3;사야 사복;02;아니, 고독한 미식가니까!\n#fontsize;80\n#3;em;[!]\n#3;closeup"
2000603-24 = "5;사야 사복;02\n1;로봇 종업원;04\n#1;em;…\n#wait;2500"
2000603-25 = "1;로봇 종업원;04;그, 그렇군요……. 자리로 안내해 드리겠습니다.\n#1;em;[땀]\n#1;stiff"
2000603-27 = "3;로봇 종업원;03;주문은 무어로 하시겠습니까?\n#3;greeting\n#3;em;[반짝]\n#3;a"
2000603-28 = "5;사야 사복;02;여기 메뉴판에 있는 <커플 전용 특대 블루치즈 케이크>로!\n#5;al\n#5;em;[!]\n#3;m1"
2000603-29 = "3;로봇 종업원;04;저…… 죄송합니다만, 손님. 그 메뉴는 커플 전용의 한정 메뉴인지라, 1인 손님께서는 주문하실 수 없습니다.\n#3;stiff\n#3;em;[땀]"
2000603-30 = "5;사야 사복;05;뭐? 나님이 다 먹지 못하고 남길까 봐 그러는 것이냐?\n#5;em;[?]"
2000603-31 = "5;사야 사복;01;걱정하지 않아도 괜찮은 것이다. 이래 보여도 나님은 어떤 음식이든 남기지 않는 대식가거든."
2000603-32 = "5;사야 사복;03;한자리에 앉아서 치즈 한 통을 통째로 먹어 치운 적도 있는 것이다!\n#5;em;[재잘]\n#5;hophop"
2000603-33 = "3;로봇 종업원;09;아뇨. 그렇다기보다는 가게의 영업 방침인지라…… 죄송합니다.\n#3;em;…"
2000603-34 = "5;사야 사복;04;치잇, 쩨쩨하기는…….\n#5;stiff"
2000603-35 = "5;사야 사복;02;하지만 그럴 줄 알고 이번에는 일행을 데려왔지!\n#5;em;[반응]\n#5;m3\n#3;dl"
2000603-36 = "5;사야 사복;03;자. 나와라, 네즈스케!\n#5;greeting\n#5;em;[반짝]"
2000603-37 = "#na;네즈스케;찍찍…….\n#3;hide"
2000603-38 = "5;사야 사복;02;내 실험 파트너인 네즈스케인 것이다!"
2000603-39 = "5;사야 사복;03;이제 둘이 되었으니 이 커플 전용 특대 치즈 케이크를 주문할 수 있겠지?\n#5;em;[음표]\n#5;hophop"
2000603-40 = "1;로봇 종업원;04;으음…… 하지만 애완동물을 일행으로 치는 것은 조금…….\n#1;em;[땀]\n#1;ar\n#5;m5"
2000603-41 = "5;사야 사복;05;뭐라고?! 네즈스케는 애완동물이 아니라 나님의 가족이거든!\n#5;stiff\n#5;em;[빠직]"
2000603-42 = "[s1] \"실례합니다만…….\"\n[s2] \"이 학생의 일행인데요…….\""
2000603-43 = "1;로봇 종업원;02;어라? 일행분이 또 계셨었군요.\n#1;em;[?]"
2000603-44 = "1;로봇 종업원;02;어라? 일행분이 또 계셨었군요.\n#1;em;[?]"
2000603-45 = "5;사야 사복;05;선생이 어째서 여기에…….\n#5;em;[반응]"
2000603-46 = "[s] \"방금 말한 커플 전용 치즈 케이크 주세요.\""
2000603-47 = "1;로봇 종업원;08;네, 주문받았습니다. 바로 가져다드리겠습니다.\n#1;em;[음표]\n#1;greeting"
2000603-48 = "1;로봇 종업원;08\n#1;dl\n#wait;1500"
2000603-49 = "5;사야 사복;00;이거 놀랐는 걸. 마침 선생도 이 가게에 방문하고 있었을 줄이야…….\n#5;em;…\n#5;m3"
2000603-50 = "[s] \"사야가 걱정되어서 따라온 것뿐이야.\""
2000603-52 = "3;사야 사복;05;뭐? 설마 전에 보낸 모모톡 내용을 신경 쓰고 있었던 것이냐?\n#3;em;[?]"
2000603-53 = "3;사야 사복;00;그럴 필요는 없었는데…….\n#3;stiff"
2000603-54 = "3;사야 사복;02;하지만 뭐, 마침 잘 된 것이다. 덕분에 먹어보고 싶었던 치즈케이크를 주문할 수 있었으니까.\n#3;em;[반응]"
2000603-55 = "3;사야 사복;01;이곳의 종업원은 원칙주의자라, 주문하기가 좀처럼 어려웠단 말이지."
2000603-56 = "[s3] \"어째서 다른 부원들에게 부탁하지 않은 거야?\"\n[s4] \"……혹시 친구 없어?\""
2000603-57 = "3;사야 사복;04;이미 권한 것이다! 두 차례나!\n#3;hophop"
2000603-58 = "3;사야 사복;04;시, 실례야! 나님에게도 친구는 있는 것이다!\n#3;hophop"
2000603-59 = "3;사야 사복;00;하지만 이상하게도 식사만 권유하면 갑자기 바쁜 일이 생겼다며 도망쳐버려서…….\n#3;em;…"
2000603-60 = "3;사야 사복;99;나님이라고 해서 매일 이상한 약이 섞인 음식만 먹는 것도 아닌데."
2000603-61 = "3;사야 사복;05;다들 너무 의심이 많은 거 아냐?\n#3;em;[?]"
2000603-62 = "[s] \"평소의 업보네.\""
2000603-63 = "3;사야 사복;04;업보라니! 그게 무슨 중상모략인 것이냐!\n#3;hophop"
2000603-64 = "3;사야 사복;05;나님이 다른 사람들에게 강제로 약을 먹인 적은 한 번도 없거든?"
2000603-65 = "3;사야 사복;04;무, 물론 실험을 위해 가짜 약을 섞어서 준 적은 몇 번 있긴 하지만…….\n#3;stiff\n#3;em;[땀]"
2000603-66 = "3;사야 사복;02;여하튼! 다른 학생들이 휴일에 어울려 주지 않아도 나님은 전혀 괴롭지 않은 것이다!\n#3;em;[반응]"
2000603-67 = "3;사야 사복;01;언제나 함께해 주는 네즈스케도 있고……"
2000603-68 = "3;사야 사복;03;애초에 천재의 휴일은 원래 고독한 법이라고 하니까. 음-하-하-핫!\n#3;hophop\n#3;em;[재잘]"
2000603-69 = "[s] \"그럼 나는 돌아갈게.\""
2000603-70 = "3;사야 사복;04;자, 잠깐! 하지만 지금은 케이크가 나올 때까지만 기다려 주는 것이다!\n#3;em;[?!]\n#3;shake"
2000603-73 = "3;로봇 종업원;03;오래 기다리셨습니다. 주문하신 <커플 전용 특대 블루치즈 케이크>입니다.\n#3;em;[반짝]\n#3;greeting\n#3;a"
2000603-74 = "5;사야 사복;02;드디어 나왔다!\n#5;em;[반응]\n#5;al\n#3;m1"
2000603-75 = "5;사야 사복;01;후-후-후. 블루 브레인 치즈를 통째로 사용한 치즈 케이크는 여기서 밖에 맛 볼 수 없단 말이지.\n#5;m3\n#3;dl"
2000603-76 = "5;사야 사복;03;전부터 이게 먹어보고 싶었던 것이다.\n#5;em;[재잘]"
2000603-77 = "#st;[0,0];instant;1;"
2000603-79 = "5;사야 사복;99\n#5;greeting\n#wait;1000"
2000603-80 = "5;사야 사복;99\n#5;greeting\n#wait;1500"
2000603-81 = "5;사야 사복;03;역시 맛있는 것이다~ ♪\n#5;em;[음표]\n#5;hophop"
2000603-82 = "[s] \"뭔가 상한 것 같은 모습의 치즈 케이크가…….\""
2000603-84 = "3;사야 사복;05;겉모습만 보고 판단하지 마! 숙성된 치즈의 맛은 먹어봐야 그 진가를 알 수 있으니까!\n#3;em;[!]"
2000603-85 = "3;사야 사복;02;나님을 믿고 한 입만 먹어보는 것이다.\n#3;em;[반응]"
2000603-88 = "[s5] \"……생각보다 나쁘지 않네.\"\n[s6] \"모양과는 달리 진한 맛이 괜찮은 걸.\""
2000603-89 = "3;사야 사복;03;그렇지? 숙성된 치즈의 맛은 눈이 아니라 혀로 느끼는 것이니까.\n#3;em;[재잘]\n#3;hophop"
2000603-90 = "3;사야 사복;03;그렇지? 숙성된 치즈의 맛은 눈이 아니라 혀로 느끼는 것이니까.\n#3;em;[재잘]\n#3;hophop"
2000603-91 = "3;사야 사복;02;선생이라면 이 맛을 이해할 줄 알았지."
2000603-92 = "3;사야 사복;03;다른 사람과 함께 먹어서 그런지, 오늘따라 치즈 케이크가 더 맛있게 느껴지는 것이다. ♪\n#3;em;[음표]"
2000603-93 = "[s] \"아까는 혼자서 휴일을 보내도 괜찮다며?\""
2000603-94 = "3;사야 사복;04;그, 그렇긴 하지만……! \n#3;em;[땀]"
2000603-95 = "3;사야 사복;05;뭐…… 아주 가끔이라면……"
2000603-96 = "3;사야 사복;00;고독하지 않은 휴일도, 나쁘지 않을지도.\n#3;stiff\n#3;em;[///]"
2000603-98 = "#na;(이후, 사야와 함께 커다란 치즈 케이크를 먹으며 즐거운 휴일을 보냈다.)"
