[translation]
2001403-1 = "#title;길 잃은 토끼"
2001403-2 = "#place;D.U. 교외의 산길"
2001403-3 = "3;사키 헬멧;02;후, 생각한 것보다 훨씬 더 많네.\n#3;a\n#3;stiff\n#3;em;[땀]"
2001403-4 = "3;사키 헬멧;01;채집한 두릅의 양이 생각보다 많아서 가져온 광주리가 부족할 정도야."
2001403-5 = "3;사키 헬멧;03;이만한 양이라면 앞으로 1주일은…… 아니 1달은 두릅만 먹어도 끄떡없겠어!\n#3;em;[음표]"
2001403-6 = "[s] \"그렇게 오래 두면 두릅이 상하지 않을까?\""
2001403-7 = "3;사키 헬멧;01;물론 바로 먹을 몫을 제외하면 보관하기 좋게 가공을 해야지."
2001403-8 = "3;사키 헬멧;99;소금에 절이거나, 말려서 보관하거나…… 여러가지 방법이 있거든.\n#3;em;…"
2001403-9 = "[s] \"사키는 두릅을 정말 좋아하나 보네.\""
2001403-10 = "3;사키 헬멧;01;아니, 딱히? 특별히 두릅을 좋아하는 건 아닌데.\n#3;em;[?]"
2001403-11 = "3;사키 헬멧;01;야생에서 쉽게 구할 수 있는 산나물이나 버섯은 대체로 좋아하는 편이야."
2001403-12 = "3;사키 헬멧;99;보급을 기대할 수 없는 상황에서 지천으로 널린 식물들은 훌륭한 식량원이지."
2001403-13 = "3;사키 헬멧;01;다만 야생의 식물 중에는 독성이 강한 종이 많으니 채집 전에 주의 깊게 살펴봐야 해."
2001403-14 = "3;사키 헬멧;05;……이것도 결국은 생존 훈련의 일환이라고!\n#3;em;[!]"
2001403-15 = "3;사키 헬멧;06;그나저나 두릅을 쫓아 걷다 보니 너무 산속 깊이 들어온 것 같은데."
2001403-16 = "3;사키 헬멧;04;여기가…… 어디지?\n#3;em;[땀]\n#3;stiff"
2001403-17 = "#st;[0,0];instant;1;"
2001403-20 = "[ns] \"길을 잃은 건가……\""
2001403-21 = "3;사키 헬멧;05;다, 당황하지 마. 선생님. 이럴 줄 알고 지도와 나침반을 가져왔으니까!\n#3;hophop"
2001403-22 = "3;사키 헬멧;01;지도와 나침반만 있다면 자신의 위치를 모르더라도 독도법으로 쉽게 길을 찾을 수 있어."
2001403-23 = "[s] \"독도법?\""
2001403-24 = "3;사키 헬멧;03;음. 독도법은 지도를 읽는 방법의 하나로 나침반의 방위를 통해 자신의 위치와 목적지를 파악하는 방법이야.\n#3;em;[반짝]\n#3;greeting"
2001403-25 = "3;사키 헬멧;03;특수전 훈련을 받은 대원이라면 누구나 기본적으로 익히고 있는 스킬이지."
2001403-26 = "3;사키 헬멧;02;어디 보자. 저쪽에 보이는 산봉우리가 아마도 시라이시 봉우리일 테니까……\n#3;m4"
2001403-27 = "3;사키 헬멧;01;도북과 자북의 오차를 산출하여 현재 좌표를 산출하면……."
2001403-28 = "3;사키 헬멧;02;위치를 확인했어. 지금 우리는 여기 지도상의 찰리-9 지점에 있는 모양이야.\n#3;em;[반응]"
2001403-29 = "3;사키 헬멧;06;가장 가까운 도로가 10도 방향으로 3km 떨어진 곳에 있으니까……"
2001403-30 = "3;사키 헬멧;05;이쪽이야, 선생님! 내 뒤를 바짝 따라와.\n#3;hophop\n#3;m5"
2001403-31 = "#st;[0,0];instant;1;"
2001403-33 = "3;사키 헬멧;01\n#3;dr\n#wait;1500"
2001403-35 = "#na;(수 시간 후…….)"
2001403-37 = "3;사키 헬멧;04;이상하다…… 꽤 걸어온 것 같은데, 아직도 도로가 보이질 않아…….\n#3;em;[땀]\n#3;a\n#3;stiff"
2001403-38 = "3;사키 헬멧;06;지도상의 오차 계산은 완벽했을 텐데…… 뭐가 문제였던 거지?"
2001403-39 = "3;사키 헬멧;09;서, 설마 아까 시라이시 봉우리가 아니라 쿠로이시 봉우리였던 건가?"
2001403-40 = "3;사키 헬멧;04;실전에서 이런 초보적인 실수를 하다니…… 미안, 선생님. 내 실수야.\n#3;em;[속상함]"
2001403-41 = "3;사키 헬멧;04;이제는 기준점을 찾으려 해도 날이 어두워서 앞이 보이질 않으니……."
2001403-42 = "3;사키 헬멧;99;날이 밝아질 때까지 비박을 하며 기다려야겠어."
2001403-43 = "#st;[0,0];instant;1;"
2001403-46 = "3;사키 헬멧;04;뭐 하는 거야, 선생님? 지금 핸드폰이나 만지작거릴 때가 아니라고.\n#3;em;[땀]"
2001403-47 = "#st;[0,0];instant;1;"
2001403-50 = "[ns] \"방금 GPS로 위치를 파악했어.\""
2001403-51 = "3;사키 헬멧;08;……GPS?\n#3;em;[?]"
2001403-52 = "3;사키 헬멧;09;GPS로 확인하니 동쪽으로 500m 지점에 샬레로 돌아갈 수 있는 버스 정류소가 있다고?"
2001403-53 = "#st;[0,0];instant;1;"
2001403-55 = "3;사키 헬멧;12\n#3;em;…\n#wait;2500"
2001403-56 = "3;사키 헬멧;10;……GPS로 위치를 확인할 수 있었으면 어째서 진작 알려주지 않았던 거야?"
2001403-57 = "[s1] \"열심히 길을 찾는 사키의 모습이 귀여워서…….\"\n[s2] \"사키의 노력에 찬물을 끼얹고 싶지 않아서…….\""
2001403-58 = "3;사키 헬멧;11;……하아?\n#3;em;[?]"
2001403-59 = "3;사키 헬멧;11;……하아?\n#3;em;[?]"
2001403-60 = "3;사키 헬멧;12;그런 말도 안 되는 이유 때문에 한나절이 넘도록 고생을 했다니……\n#3;stiff"
2001403-61 = "3;사키 헬멧;10;그런 바보 같은 경우가 어딨어!\n#3;closeup\n#3;hophop"
2001403-63 = "#na;(이후, 심야의 버스를 타고 사키와 샬레로 돌아왔다.)"
2001403-64 = "#na;(……교외에서 따온 두릅은 튀겨서 사키와 함께 야식으로 덴푸라를 만들어 먹었다.)"
