[translation]
2001603-1 = "#title;유혹하는 프로일라인"
2001603-2 = "3;이로하;03\n#3;a\n#wait;1500"
2001603-3 = "3;이로하;03\n#3;d\n#wait;1500"
2001603-4 = "3;이로하;03\n#3;closeup\n#3;a\n#wait;1000"
2001603-5 = "3;이로하;03\n#3;closeup\n#3;greeting\n#wait;1500"
2001603-6 = "#na;(이로하가 가까이 다가오자 꽃과 비슷한 달콤한 내음이 코끝을 스친다.)"
2001603-7 = "#na;(이윽고 이로하는 부드러운 목소리로 넌지시 말을 걸어왔다.)"
2001603-8 = "3;이로하;02;……선생님, 이제 그런 건 더는 그만하도록 하죠. 그런 일을 계속해 봤자 괴로워지기만 할 뿐이라는 걸 선생님도 잘 알고 계시잖아요?\n#3;closeup\n#3;em;…"
2001603-9 = "3;이로하;99;저는……. 어디까지나 선생님을 위해서 말씀드리는 거예요. 괴로운 일은 그만하고…….\n#3;closeup"
2001603-10 = "3;이로하;03;네에, 선생님. 부디…… 제 곁으로, 좀 더 가까이…… 이리로 와 주시지 않겠나요?\n#3;closeup\n#3;em;[하트]"
2001603-11 = "#na;(천천히 다가드는 이로하의 손. 점점 더 거리가 좁혀지면서 이로하의 온기가 바로 지근거리에서 느껴지려고 할 때 즈음.)"
2001603-12 = "[ns1] \"그러니까 말했잖아. 이로하\"\n[ns2] \"지금 일이 엄청나게 밀려 있어서 진짜 위험하다니까?!\""
2001603-13 = "3;이로하;00;쳇.\n#3;closeup"
2001603-14 = "3;이로하;00;쳇.\n#3;closeup"
2001603-15 = "[s3] \"정면에서 혀를 차는 거야……?\"\n[s4] \"그보다 이로하! 갑자기 찾아와서 뭘 하는 거야……?\""
2001603-16 = "3;이로하;02;아, 저 말씀이신가요? 별거 아닌데요. 만마전에서 지시받은 업무를 충실히 이행하고 있을 뿐이에요.\n#3;em;[반응]"
2001603-17 = "3;이로하;02;아, 저 말씀이신가요? 별거 아닌데요. 만마전에서 지시받은 업무를 충실히 이행하고 있을 뿐이에요.\n#3;em;[반응]"
2001603-18 = "3;이로하;01;<선생님을 꼬드겨서 저희 만마전으로 끌어들인다> 이미 앞서 말씀드렸잖아요? 뭘 이제 와서 새삼스럽게."
2001603-19 = "[s5] \"아니, 그야 알고는 있지만! 그거랑 일을 방해하는 거랑 무슨 상관인데?!\"\n[s6] \"설마 만마전은 샬레를 방해하면서, 뭔가를 노리고 있는 건가?!\""
2001603-20 = "3;이로하;02;네? ……아. 뭐,\n#3;em;[?]"
2001603-21 = "3;이로하;02;네? ……아. 뭐,\n#3;em;[?]"
2001603-22 = "3;이로하;00;선생님이 그렇게 생각하고 싶으시다면 그냥 그런 걸로 해둘까요?"
2001603-23 = "[s] \"아무런 변명도 준비해두지 않았을 때의 반응이구만!\""
2001603-24 = "3;이로하;05;아니, 그런 말씀은 너무 실례 아닌가요? 아무리 그래도 제가 아무 생각 없이 선생님을 방해할 리가 없잖아요?\n#3;em;[!]\n#3;jump"
2001603-25 = "3;이로하;02;그럼 방해하는 이유가 뭐냐고요……? 그거라면 간단해요."
2001603-26 = "3;이로하;01;저, 여기까지 찾아와서, 일단은 만마전으로 선생님을 꼬드긴다는 명분하에 땡땡이를 치고 있잖아요?"
2001603-27 = "[s] \"결국 명분이라고 말해버렸어! 이 아가씨!\""
2001603-28 = "3;이로하;99;그런데 정작 땡땡이치러 온 저만의 쉼터에서, 다른 사람이 일하고 있는 걸 멍하니 지켜보고 있어야만 한다니."
2001603-29 = "3;이로하;05;아니아니, 그건 아니죠. 선생님. 귀차니스트들은 또 귀차니스트만의 프라이드라는 게 있는 법이거든요?\n#3;hophop"
2001603-30 = "3;이로하;00;간단히 말해서, 저는 땡땡이 치고 있는데 선생님이 옆에서 열심히 일하면서 생색내는 걸 보고 있으려니까. 마치…….\n#3;em;…"
2001603-31 = "3;이로하;05;저만 글러 먹은 거 같잖아요……?\n#3;closeup"
2001603-32 = "[s] \"아니, 글러 먹은 거 맞지!\""
2001603-33 = "3;이로하;03;선생님, 진실이란 때로 말하지 않기에 아름다운 법이에요.\n#3;em;[반짝]"
2001603-34 = "[s7] \"<방금 나 멋진 말 한 듯>하고 으쓱한 표정을 짓는 중에 미안하지만.\"\n[s8] \"전혀 멋지지 않거든?!\""
2001603-35 = "3;이로하;01;흐음, 그 말씀은, 선생님께선 제가 만마전으로부터 받은 임무를 성실히 수행했으면 한다……는 요구인가요?"
2001603-36 = "3;이로하;01;흐음, 그 말씀은, 선생님께선 제가 만마전으로부터 받은 임무를 성실히 수행했으면 한다……는 요구인가요?"
2001603-37 = "3;이로하;07;뭐, 정 원하신다면 못할 것도 없긴 한데요."
2001603-38 = "#st;[0,0];instant;1;"
2001603-40 = "3;이로하;03\n#3;greeting\n#3;d\n#wait;1000"
2001603-43 = "3;이로하;03\n#3;a\n#3;closeup\n#wait;1500"
2001603-44 = "3;이로하;03;선생님……. 역시, 이런 일은 그만하죠……? 그렇게까지 열심히 할 필요, 없잖아요?\n#3;closeup\n#3;em;[하트]"
2001603-45 = "3;이로하;01;저는 알고 있어요- 평소 선생님께서 얼마나 고생을 하고 계시는지……. \n#3;closeup"
2001603-46 = "3;이로하;99;총학생회로부터 내려오는 불합리한 지시나 키보토스 학생들이 저지르는 골치 아픈 사건들을 해결하기 위해, 그야말로 밤낮없이 뛰어다니길 여러 차례…… \n#3;closeup"
2001603-47 = "3;이로하;06;네, 고개를 돌려보면 위나 아래나 전부 골칫덩이뿐. 그사이에 끼여서 고생하는 건 언제나 저희 같은 중간관리자들이죠.\n#3;closeup\n#3;stiff"
2001603-48 = "3;이로하;05;그렇게 제 몸을 깎아가며 노력해본들 알아주는 사람은 소수…….\n#3;closeup"
2001603-49 = "3;이로하;03;차라리 그럴 바엔……. 같이 내팽개쳐버리자구요?\n#3;closeup"
2001603-50 = "3;이로하;99;주어진 업무를 내버려 둔다……. 반드시 해야만 하는 일을 밀어둔다. 모든 건 시야 밖으로 밀쳐내면서 모른척 한다…….\n#3;closeup"
2001603-51 = "3;이로하;03;이거, 생각 외로 엄청나게 기분 좋다구요……? 네에? 선생님……. 저와 함께…….\n#3;closeup"
2001603-52 = "3;이로하;07;땡땡이칠까요?\n#3;closeup\n#3;em;[반짝]"
2001603-53 = "[s] \"……아, 악마의 유혹이다!\""
2001603-54 = "3;이로하;03;후후, 그렇게까지 호들갑 떨 일인가요? 그냥………\n#3;closeup"
2001603-55 = "3;이로하;01;……그냥.\n#3;closeup\n#3;em;…"
2001603-56 = "[s] \"……그냥?\""
2001603-57 = "3;이로하;06;……피곤하네요. 이런 것도.\n#3;closeup\n#3;stiff"
2001603-58 = "3;이로하;06\n#3;d\n#3;closeup\n#wait;1500"
2001603-59 = "3;이로하;00;전부 귀찮아졌어요. 자괴감이 든 달까요. 나, 지금 뭐 하고 있는 거지……? 라는 상태예요.\n#3;a\n#3;em;[속상함]"
2001603-60 = "3;이로하;01;한창 흥분하다가 그 흥분이 식고 마주하는 현실은 괴로운 법이네요……."
2001603-61 = "3;이로하;99;만마전의 업무고 뭐고…… 하아, 돌아가서 하루 종일 책이나 읽고 싶다아……."
2001603-62 = "3;이로하;00;오늘 같은 날, 여기까지 나와서 뭘 하는 건지……."
2001603-63 = "3;이로하;06;……하아.\n#3;em;[땀]\n#3;stiff"
2001603-64 = "3;이로하;00;전부 선생님 때문이에요."
2001603-65 = "[s] \"부, 부당한 이야기다!\""
2001603-66 = "3;이로하;01;전부 귀찮아졌으니, 선생님. 저녁이나 먹으러 가요. 저 마침 좋은 식당을 알고 있으니까. 소개도 해드릴 겸."
2001603-67 = "3;이로하;03;맛있는 걸 먹으면 조금이라도 기분이 풀릴 거 같은데……. 어때요?\n#3;em;[음표]"
2001603-68 = "[s] \"뭐, 하는 수 없지…….\""
2001603-69 = "#st;[0,0];instant;1;"
2001603-71 = "3;이로하;03\n#3;dr\n#wait;700"
2001603-77 = "[ns] \"이로하, 그럼 식당은 어느 방향에 있어?\""
2001603-78 = "3;이로하;01;…….\n#3;a\n#3;em;…"
2001603-79 = "3;이로하;07;후훗. 후후후……!"
2001603-80 = "[s] \"……이로하?\""
2001603-81 = "3;이로하;03;당하셨네요. 선생님.\n#3;em;[재잘]"
2001603-82 = "3;이로하;07;여기까지 나와버린 이상. 하던 일, 땡땡이친 셈이 되어버렸네요?"
2001603-83 = "[s] \"………아!\""
2001603-84 = "3;이로하;03;멋들어지게 작전 성공. \n#3;em;[반짝]"
2001603-85 = "3;이로하;07;그럼 소기의 목적도 달성했으니. 땡땡이치는 사람들끼리, 맛난 저녁을 먹으러 가볼까요? 선생님.\n#3;em;[음표]"
2001603-86 = "[s] \"다, 당했다…….\""
2001603-88 = "#na;(그렇게 이로하에게 끌려 나와 샬레 근처에서 맛있는 저녁을 먹고 돌아갔다)"
