[translation]
2002802-1 = "หัวใจแห่งความอับโชค"
2002802-2 = "(คุณครูมายังชายหาดที่ฮินาตะรออยู่)"
2002802-3 = ""
2002802-9 = "(และพบว่าฮินาตะยืนเก้ๆ กังๆ อยู่ข้างเตียงอาบแดดและร่มกันแดดที่ถูกจัดเตรียมไว้อย่างดีที่ชายหาด)"
2002802-10 = ""
2002802-12 = ""
2002802-13 = ""
2002802-15 = "[ns1] \"ฮินาตะ...? มีเรื่องอะไรเหรอ?\"\n[ns2] \"เป็นอะไรรึเปล่า? สีหน้าดูไม่สู้ดีเลย...\""
2002802-16 = ""
2002802-17 = ""
2002802-19 = ""
2002802-20 = "อะ...อ่า คุณครู!!"
2002802-21 = "ขอบคุณที่มานะคะ ฉันดันทำให้คุณครูเสียเวลากับเรื่องไม่เป็นเรื่องแบบนี้ซะแล้ว..."
2002802-22 = "...คะ? มีเรื่องอะไรงั้นเหรอคะ? ของพวกนี้คืออะไรน่ะเหรอคะ? "
2002802-23 = "คือว่าของพวกนี้..."
2002802-24 = ""
2002802-27 = ""
2002802-29 = "คือว่านี่เป็นเตียงอาบแดด... ส่วนนี่ก็ร่มกันแดด..."
2002802-30 = "ดะ...เดี๋ยวสิ คุณครูไม่มีทางที่จะไม่รู้จักของพวกนี้อยู่แล้วใช่มั้ยล่ะคะ! ขอโทษค่ะ! ฉันพูดอะไรไปก็ไม่รู้!"
2002802-31 = "คือว่าที่ฉันเตรียมของพวกนี้มา... อืม... ก็คือว่า..."
2002802-32 = "คือว่า... ฉันไม่รู้ว่าจะอธิบายยังไงเลยค่ะ... ฮะฮะฮะ..."
2002802-33 = "คือ..."
2002802-34 = "เรื่องนั้นฉันเอง...ก็ไม่รู้จะตอบยังไงเลยน่ะค่ะ เรื่องที่ฉันอยากปรึกษาคุณครู... ก็คือเรื่องนี้แหละค่ะ"
2002802-35 = "ฉันจัดเตรียมของพวกนี้เอาไว้แค่เพราะรู้สึกว่าต้องทำ...น่ะค่ะ"
2002802-36 = "[s3] \"ช่วยอธิบายให้ละเอียดกว่านี้หน่อยได้มั้ย?\"\n[s4] \"ทำเพราะรู้สึกว่าต้องทำงั้นเหรอ?\""
2002802-39 = "อืม... ยิ่งพูดฉันก็ยิ่งไม่เข้าใจแล้วค่ะว่าพูดอะไรไป..."
2002802-40 = "คือฉันคิดว่า... ตอนนี้เป็นเวลาพักผ่อน... และไหนๆ ก็มาถึงที่นี่แล้ว มาพักผ่อนให้สบายใจกันเถอะ...! ประมาณนั้นน่ะค่ะ"
2002802-41 = "ซิสเตอร์คนอื่นๆ พูดกับฉันก่อนออกเดินทางมาว่า \"ตอนที่สืบข้อมูลก็ตั้งใจทำให้เต็มที่ เวลาพักผ่อน#nก็พักให้เต็มที่\" น่ะค่ะ..."
2002802-42 = "แต่ฉันก็ทำแบบนั้นไม่ได้เลยค่ะ จะว่ายังไงดีนะ... เหมือนมีบางอย่างที่กวนใจฉันอยู่ตลอด..."
2002802-43 = "มันเอาแต่สงสัยว่า... ฉันทำแบบนั้นได้จริงๆ หรือเปล่า..."
2002802-44 = "ฮ่าฮ่า... ฮ่า... อาจเป็นเพราะได้มาใช้ชีวิตในแบบที่ต่างไปจากตอนปกติก็ได้นะคะ"
2002802-45 = "ปกติฉันจะต้องรีบตื่นเช้า แล้วก็ใช้เวลาทั้งวันไปกับการทำงานต่างๆ..."
2002802-46 = "พอทำงานทุกอย่างเสร็จก็มักจะเกือบเย็น แล้วก็ต้องไปช่วยซิสเตอร์คนอื่นๆ ทำความสะอาดต่อ..."
2002802-47 = "...และตอนนี้คนอื่นๆ ที่อยู่ที่วิหารก็คงทำแบบนั้นอยู่ใช่มั้ยล่ะคะ? ทำงานตามหน้าที่ของตน... เก็บกวาด#nทำความสะอาด..."
2002802-48 = "และงานที่แต่เดิมเป็นส่วนที่ฉันรับผิดชอบ... พอฉันไม่อยู่ คนอื่นๆ ก็คงจะต้องมาทำแทน..."
2002802-49 = "..."
2002802-50 = "[s5] \"รู้สึกผิดที่ได้มาพักผ่อนคนเดียวสินะ?\"\n[s6] \"รู้สึกเหมือนโยนงานให้คนอื่นเหรอ?\""
2002802-51 = ""
2002802-52 = ""
2002802-54 = ""
2002802-55 = "ฉะ...ฉันรู้ดีค่ะว่าคิดแบบนั้นเป็นเรื่องไม่ดี"
2002802-56 = "แต่ว่า... ถึงยังไงมันก็..."
2002802-57 = "...ฉันไม่ชินกับมันเลยค่ะ ทั้งการคิดแบบนั้น และความรู้สึกแบบนั้น..."
2002802-58 = "เพราะแบบนี้ถึงกังวลว่าจะ 'พักผ่อนให้เต็มที่' ตามที่ซิสเตอร์คนอื่นๆ บอกไม่ได้..."
2002802-59 = ""
2002802-61 = ""
2002802-62 = "...คะ?"
2002802-63 = "ฉันเคยลองนอนบนเตียงอาบแดดหรือยังน่ะเหรอคะ?"
2002802-64 = "ยะ...ยังค่ะ ยังไม่เคยเลย... ฉันรู้สึกแปลกๆ ก็เลยได้แต่ดูอยู่อย่างเดียวน่ะค่ะ..."
2002802-65 = "...ให้ลองนอนบนเตียงอาบแดดนั่นดูก่อนงั้นเหรอคะ?"
2002802-66 = "หะ...หืม? ฉะ...ฉันไม่ค่อยเข้าใจเลยค่ะ..."
2002802-67 = ""
2002802-69 = ""
2002802-70 = "ปะ...เปล่าค่ะ ถ้าคุณครูบอกให้ลองทำละก็ ฉันจะลองดูค่ะ..."
2002802-71 = "เข้าใจแล้วค่ะ ฉันจะลองนอนดูค่ะ"
2002802-72 = ""
2002802-74 = ""
2002802-75 = "ก่อนอื่นก็นั่งลงแบบนี้ แล้วยืดขาออกไป..."
2002802-76 = ""
2002802-78 = ""
2002802-82 = "― [log=히나타 수영복]อืม... หืม...? เอ๋...?[/log][wa:2090] "
2002802-85 = "― [log=히나타 수영복]ตรงนี้...[/log]"
2002802-87 = "― [log=히나타 수영복]มันสบายมากกว่าที่คิดอีกนะคะ...[/log][wa:620] "
2002802-90 = "― [log=히나타 수영복]ลมพัดเย็นสบาย ไม่เย็นจนเกินไป...[/log][wa:1870] "
2002802-92 = "― [log=히나타 수영복]แล้วก็มีร่มเงาบังแดดไม่ให้ส่องโดนหน้าด้วย...[/log][wa:10] "
2002802-95 = "― [log=히나타 수영복]อุ่นสบายดีจัง...[/log]"
2002802-97 = "― [log=히나타 수영복]ถ้านอนอยู่ตรงนี้ละก็ คงจะเผลอหลับแน่ๆ เลยค่ะ[/log][wa:550] "
2002802-100 = "― [log=히나타 수영복]แต่ว่า... เอ่อ...[/log][wa:960] "
2002802-102 = "― [log=히나타 수영복]ถ้ามีแต่ฉันคนเดียวที่ได้นอนพัก ทั้งที่อยู่กับคุณครูแบบนี้...[/log][wa:560] "
2002802-105 = "― [log=히나타 수영복]มะ...มันรู้สึกผิด... ยังไงก็ไม่รู้ค่ะ[/log][wa:1430] "
2002802-108 = "[ns7] \"ไม่เป็นไร ไม่ต้องกังวลเรื่องครูหรอก\"\n[ns8] \"ตอนนี้สนใจแค่ความรู้สึกของตัวเองก็พอ\""
2002802-109 = "― [log=히나타 수영복]ขะ... เข้าใจแล้วค่ะ[/log][wa:560] "
2002802-110 = "― [log=히나타 수영복]ขะ... เข้าใจแล้วค่ะ[/log][wa:560] "
2002802-112 = "― [log=히나타 수영복]ถ้างั้นฉันจะทำตามที่คุณครูบอก...[/log][wa:360] "
2002802-115 = "― [log=히나타 수영복]ปล่อยใจให้สบายๆ...[/log][wa:1480] "
2002802-118 = "― [log=히나타 수영복]...อืม... งืมๆๆ... ฮิฮิฮิ...[/log][wa:5370] "
2002802-121 = "― [log=히나타 수영복]...ฮึก!? มะ...เมื่อกี้ฉันทำอะไรไป...!?[/log][wa:680] "
2002802-124 = "― [log=히나타 수영복]ชะ...ช่วยลืมไปด้วยนะคะ[/log][wa:10] "
2002802-126 = "― [log=히나타 수영복]ช่วยลืมเรื่องเมื่อกี้ไปให้หมดด้วยนะคะ! คุณครู!![/log][wa:150] "
2002802-129 = ""
2002802-130 = "ช่วยลืมไปด้วยนะคะ คุณครู~~!!"
2002802-132 = "(หลังจากที่ปลอบฮินาตะให้ใจเย็นลงแล้ว คุณครูก็ช่วยให้ฮินาตะได้พักผ่อนอย่างสบายๆ อีกครั้ง)"
2002802-133 = "(ฮินาตะลังเลอยู่ครู่หนึ่ง พอกลับไปนอนบนเตียงอาบแดดได้ไม่นาน เธอก็เผลอหลับไป)"
