[translation]
2002002-1 = "รสนิยมของแฮ็กเกอร์อัจฉริยะ"
2002002-2 = "(คุณครูมาที่อาคารชมรมของโรงเรียนมิลเลเนียมหลังจากได้รับการติดต่อจากฮิมาริ)"
2002002-5 = "ทางเดินอาคารชมรม 8 มิลเลเนียม"
2002002-7 = "[ns] \"ฮิมาริบอกให้มาที่นี่ แต่ว่าต้องไปทางไหนต่อล่ะ...?\""
2002002-8 = ""
2002002-11 = "(จู่ๆ ก็มีบางอย่างเข้ามาใกล้ๆ และทำให้เกิดเสียงลมหวีดเบาๆ)"
2002002-12 = ""
2002002-15 = "[ns] \"นี่มัน... โดรนรักษาความปลอดภัยของมิลเลเนียม?\""
2002002-16 = ""
2002002-23 = "[ns] \"หืม? ให้เดินตามไปทางนั้นเหรอ..?\""
2002002-28 = "(คุณครูเดินไปตามทางที่โดรนบินนำไป จนมาหยุดอยู่ที่หน้าห้องชมรมหนึ่ง)"
2002002-29 = ""
2002002-32 = "(ที่ด้านข้างประตูมีแผ่นป้ายเขียนบางอย่างไว้ติดอยู่)"
2002002-33 = "[ns] \"<ชมรมรำลึกการกลั้นหายใจระยะยาว>...?\""
2002002-34 = ""
2002002-40 = "กำลังรออยู่เลยค่ะคุณครู เชิญเข้ามาได้เลยค่ะ"
2002002-41 = ""
2002002-48 = ""
2002002-50 = "ฮุฮุ มาเร็วจังเลยนะคะ เชิญเลยค่ะคุณครู"
2002002-51 = ""
2002002-54 = "ขอบคุณที่ช่วยนำทางคุณครูมาที่นี่ค่ะ ตอนนี้กลับไปทำงานได้แล้วค่ะ"
2002002-55 = ""
2002002-60 = "[ns] \"ฮิมาริ? โดรนเมื่อกี้นี้...\""
2002002-61 = "อ๋อ นั่นเป็นโดรนรักษาความปลอดภัยของทางมิลเลเนียมค่ะ"
2002002-62 = "ฉันเป็นสาวน้อยร่างกายบอบบาง เลยไม่สะดวกที่จะออกไปรับคุณครูเอง จึงจำเป็นต้องหาอุปกรณ์#nที่อยู่รอบๆ เพื่อนำทางคุณครูมาที่นี่ ฉันก็เลยแฮ็ก--"
2002002-63 = ""
2002002-65 = ""
2002002-66 = ""
2002002-68 = "ค่ะ... แฮ็กเข้าระบบโดรนค่ะ"
2002002-69 = "เด็กๆ พวกนี้เหมาะที่จะใช้เป็นอุปกรณ์นำทางใช่มั้ยล่ะคะ?"
2002002-70 = "พวกเขาเป็นเด็กดีมากเลยนะคะ แถมน่ารักอีกด้วยค่ะ..."
2002002-71 = ""
2002002-74 = "[ns] \"ทำเรื่องแบบนั้นได้หน้าตาเฉยเลยแฮะ...\""
2002002-76 = "[ns1] \"ที่นี่คือที่ไหนเหรอ?\"\n[ns2] \"เมื่อกี้มีชื่อแปลกๆ เขียนอยู่ตรงป้ายข้างหน้าด้วย\""
2002002-79 = "เอ๋...? ชะ... ชื่อแปลกขนาดนั้นเลยเหรอคะ? "
2002002-80 = "ฉันใช้เวลาคิดชื่อดีๆ ตั้งสามวันสามคืน กว่าจะคิดชื่อนี้มาได้ และคิดว่าเป็นชื่อที่แสนชาญฉลาด ดูดี และเหมาะที่จะใช้ปกปิดตัวจริง..."
2002002-81 = "แล้วก็คิดว่าเป็นชื่อที่เหมาะสมกับนักเรียนอัจฉริยะแห่งโรงเรียนมิลเลเนียมแล้วแท้ๆ..."
2002002-82 = "[s] (ทำหน้าบึ้งอย่างเห็นได้ชัดเลยแฮะ...!)"
2002002-84 = "[ns] \"มันแปลกแบบดูมีเอกลักษณ์ดีน่ะ ครูว่าชื่อนี้ก็เลิศอยู่นะ\""
2002002-85 = "ฮุฮุฮุ... อย่างนั้นเหรอคะ? "
2002002-86 = "ฉันเองก็คิดอย่างนั้นค่ะ ♪"
2002002-87 = "ไม่ว่าใครจะพูดยังไง มันก็เป็นชื่อที่อัจฉริยะแห่งมิลเลเนียม สาวน้อยน่ารักผู้บอบบาง--"
2002002-88 = "ที่ชื่ออาเกโบชิ ฮิมาริคิดค้นขึ้นค่ะ!"
2002002-89 = ""
2002002-92 = "[ns] \"แล้วฮิมาริมาทำอะไรอยู่ที่นี่เหรอ?\""
2002002-93 = "อ๊ะ ฉันกำลังจะพูดเรื่องนั้นพอดีเลยค่ะ"
2002002-94 = "ถ้าให้อธิบายละก็ อืม... ที่นี่ก็คงจะเป็น <ที่ซ่อน> ลับของฉันละมั้งคะ?"
2002002-95 = "[s] \"ที่ซ่อนเหรอ?\""
2002002-96 = "ใช่แล้วค่ะ ห้องชมรมปรากฏการณ์ลี้ลับหรือห้องของเวอริทัส คงจะถูกพวก <บิ๊กซิสเตอร์> จับตาดูอยู่แน่ๆ ค่ะ"
2002002-97 = "ดังนั้นฉันเลยเจาะระบบฝ่ายบริหารของมิลเลเนียมเพื่อให้ได้สิทธิ์การใช้ห้องเปล่า และเนรมิตที่นี่#nให้เป็นพื้นที่ส่วนตัวของฉันค่ะ"
2002002-98 = "ทำไมฉันต้องทำถึงขนาดนั้นน่ะเหรอคะ?"
2002002-99 = "แน่นอนว่าเพื่อการพักผ่อนของตัวฉันค่ะ สำหรับสาวน้อยน่ารักแสนบอบบางอย่างฉันแล้ว เวลานอนน่ะ..."
2002002-100 = "ไม่สิ เวลาพักผ่อนเพื่อให้สมองได้ผ่อนคลายเป็นเรื่องสำคัญมากนะคะ"
2002002-101 = "[s3] \"งี้นี่เอง... แต่ถ้าถูกจับได้จะไม่โดนเพ่งเล็งเหรอ?\"\n[s4] \"เดี๋ยวก็ถูกโดรน หรือกล้อง CCTV ตรวจจับได้หรอก\""
2002002-102 = "ฮุฮุฮุ... ไม่เป็นไรหรอกค่ะ ถ้าเรื่องโดรนหรือกล้อง CCTV ละก็ ฉันจัดการรับมือเรียบร้อยแล้วค่ะ"
2002002-103 = "ฮุฮุฮุ... ไม่เป็นไรหรอกค่ะ ถ้าเรื่องโดรนหรือกล้อง CCTV ละก็ ฉันจัดการรับมือเรียบร้อยแล้วค่ะ"
2002002-104 = "การวิเคราะห์เส้นทางของโดรนรักษาความปลอดภัยน่ะ ง่ายกว่าการบวกเลขซะอีก แล้วถ้าจำเป็นละก็ ฉันก็สามารถแฮ็กเข้าระบบและปรับเปลี่ยนเส้นทางได้ค่ะ"
2002002-105 = "หรือบางครั้งก็แค่รบกวนการรับสัญญาณของ CCTV นิดๆ หน่อยๆ แล้วก็ปรับองศากล้องให้หันไปทาง#nจุดบอดในเส้นทางที่เราจะเคลื่อนไหว เท่านั้นก็ได้แล้วค่ะ"
2002002-106 = ""
2002002-108 = ""
2002002-109 = ""
2002002-111 = "เท่านี้เส้นทางชีวิตการพักผ่อนของฉันก็ไร้ที่ติแล้วค่ะ!"
2002002-112 = "[s5] \"วางแผนเล่นใหญ่เกินเบอร์เหลือเกินนะ...\"\n[s6] \"แต่ว่าถ้าเป็นสถานที่สำคัญขนาดนั้น ให้ครูมาด้วยจะดีเหรอ...\""
2002002-115 = "อ่า... ค่ะ ถ้าเรื่องนั้นละก็ไม่เป็นไรหรอกค่ะ"
2002002-116 = "ฉันควรขอบคุณคุณครูมากกว่าที่มาถึงที่นี่ค่ะ ไม่สิ ฉันคิดแล้วว่าคุณครูจะต้องมาค่ะ"
2002002-117 = "[s] \"หืม?\""
2002002-118 = "คุณครูเองก็คงทราบดีว่าฉันเป็นบุคคลที่ทุกคนใฝ่ฝันอยากจะพบเจอ เหมือนกับดอกไม้ที่ผลิบานบน#nหน้าผาสูง... "
2002002-119 = "เด็กสาวอัจฉริยะผู้ที่ได้รับการชื่นชมว่างดงามเหมือนดอกไม้แสนสวย เพียงยืนอยู่เฉยๆ ก็งดงาม#nราวกับดอกไม้ผา ครานั่งก็ยังคงงดงามเหมือนดอกโบตั๋น ต่อให้ถอนหายใจก็ยังงดงามเหมือนดอกลิลลี่#nสีขาวบริสุทธิ์..."
2002002-120 = "[s] \"โปรโมตตัวเองได้หน้าตาเฉยมาก!\""
2002002-121 = "เพราะงั้นแล้ว ฉันเลยคิดว่าไม่ควรเปิดเผยจุดอ่อน หรือข้อบกพร่องให้คนอื่นได้เห็นค่ะ"
2002002-122 = "แต่ว่า... สาวน้อยน่ารักที่สมบูรณ์แบบไร้ข้อบกพร่องอย่างฉัน จะให้รู้สึกระแวดระวังตัวจนรู้สึก#nตึงเครียดอยู่ตลอดเวลาก็คงไม่ได้"
2002002-123 = "อะแฮ่ม สิ่งที่ฉันจะพูดก็คือ..."
2002002-124 = "ถ้ามีช่วงเวลาที่สามารถผ่อนคลายได้อย่างเต็มที่..."
2002002-125 = "กับคนที่ไว้ใจ และเข้าหาฉันโดยไม่หวังสิ่งตอบแทนใดๆ"
2002002-126 = "คนที่เห็นตัวตนแท้จริงของฉันแล้วไม่โกรธ ไม่ตำหนิ และคอยอยู่ข้างๆ ฉัน~"
2002002-127 = "คือว่า... "
2002002-128 = "[s] \"คือว่า...?\""
2002002-129 = "ถึงจะจัดเตรียมที่ซ่อนได้สมบูรณ์แล้ว แต่ฉันกลับเบื่อที่จะต้องอยู่คนเดียวน่ะค่ะ"
2002002-130 = "คิดว่าถ้าเป็นคุณครูละก็..."
2002002-131 = "อาจจะเป็นคนที่อยู่กับฉันได้ ก็...เท่านั้นค่ะ"
2002002-132 = "จะเรียกว่าฉันโลภมาก...? หรือเรียกว่าคาดหวังไปเองดีล่ะคะ...?"
2002002-133 = "เพราะงั้น... อืม..."
2002002-134 = "ฉันขอให้คุณครูมาที่นี่ เพราะแบบนั้นแหละค่ะ..."
2002002-135 = "(เหลือบมอง)"
2002002-136 = "[s] \"ถ้าเป็นแบบนั้น ครูก็ยินดีช่วยนะ ฮิมาริ\""
2002002-137 = "อ่า..."
2002002-138 = "[s] \"หืม? ฮิมาริ? เป็นอะไรเหรอ?\""
2002002-139 = ""
2002002-141 = ""
2002002-142 = "ปะ... เปล่าค่ะ"
2002002-143 = "ฮุฮุฮุ... ฉันแค่คิดว่า 'เป็นอย่างที่คิดไว้' เลยน่ะค่ะ"
2002002-144 = "ก็แค่ผลลัพธ์ที่เกิดขึ้น มันเหมือนกับผลลัพธ์ที่สมองอันชาญฉลาดของฉันประมวลผลเอาไว้ล่วงหน้าค่ะ นี่คงเป็นชัยชนะของฉันสินะคะ"
2002002-145 = ""
2002002-148 = "[ns] \"มีอะไรที่ต้องวัดแพ้ชนะด้วยงั้นเหรอ...?\""
2002002-149 = "อย่าใส่ใจเรื่องเล็กๆ น้อยๆ นั่นเลยค่ะ... แค่คุณครูยอมทำตามคำขอของฉันก็พอแล้วละค่ะ"
2002002-150 = "อ๊ะ บอกไว้ก่อนนะคะว่าจะมากลับคำกันทีหลังไม่ได้นะคะ"
2002002-151 = "[s] \"ถ้าเรื่องนั้นไม่ต้องห่วงหรอกนะ ฮิมาริ\""
2002002-152 = "ฮุฮุฮุ..."
2002002-153 = ""
2002002-155 = ""
2002002-156 = ""
2002002-158 = "ถ้างั้นวันนี้ขอรบกวนด้วยนะคะคุณครู"
2002002-161 = "(คุณครูใช้เวลาพักผ่อนกับฮิมาริ และใช้เวลาช่วงบ่ายไปอย่างสบายๆ)"
2002002-166 = "...ตอนนี้ฉันได้ใช้เวลาพักผ่อนกับคุณครูแล้ว "
2002002-167 = "ปกติแล้วเวลาแบบนี้ฉันจะต้องทำหน้ายิ้ม <อรุ่มเจ๊าะ> อย่างพึงพอใจ จากความสำเร็จที่สาวน้อย#nอัจฉริยะผู้น่ารักแสนบอบบางทำได้สำเร็จ"
2002002-168 = "น่าเสียดายที่ไม่นานมานี้มีเรื่องหนึ่งที่ไม่เป็นไปดั่งใจฉันอยู่ค่ะ"
2002002-169 = "[s] \"เอ๋? มีปัญหาอะไรงั้นเหรอ?\""
2002002-170 = "ไม่เชิงว่าเป็นปัญหาหรอกค่ะ แต่ว่า..."
2002002-171 = "อย่างที่คุณครูทราบดี ว่าที่โรงเรียนมิลเลเนียมของเรา ช่วงพักกลางวันทางชมรมกระจายเสียงจะเปิด#nเพลงที่เราขอไปค่ะ"
2002002-172 = "[s7] \"เพิ่งเคยได้ยินเลยนะเนี่ย!\"\n[s8] \"งั้นเหรอ... มีด้วยงั้นเหรอ?\""
2002002-175 = "ถ้าเป็นนักเรียนมิลเลเนียมก็มีสิทธิ์ที่จะขอเพลงทุกคน..."
2002002-176 = "แต่ไม่รู้ทำไม พวกเธอถึงไม่เลือกเปิดเพลงที่ฉันขอไปเลยค่ะ?!"
2002002-177 = "ฉันขอเพลงไปตั้งหลายครั้ง แล้วทำไมพวกเธอไม่เลือกเปิดเพลงของฉันเลยล่ะคะ? คุณครูคิดว่าเป็นเพราะอะไรเหรอคะ?"
2002002-178 = "หรือว่าเพลงที่ฉันขอมันล้ำลึกเกินไป จนสร้างความแตกต่างให้กับนักเรียนคนอื่นๆ คะ...?"
2002002-179 = "ฉัน... กลายเป็นตัวเอกของเรื่องราวแสนเศร้าไปโดยไม่รู้ตัวแล้วงั้นเหรอคะ?"
2002002-180 = "[s] \"ไม่นะ ครูว่าคงไม่ใช่แบบนั้นหรอก...\""
2002002-181 = "ฉันก็แค่... อยากแบ่งปันเพลงที่ชอบกับนักเรียนโรงเรียนมิลเลเนียมทุกคนก็เท่านั้นเอง..."
2002002-182 = "แต่วันนี้ฉันจะไม่ยอมให้น้ำหนักของมารยาทที่พึงมีมาฉุดรั้งฉันเอาไว้อีกแล้วค่ะ..."
2002002-183 = "เพื่อเป็นการฉลองที่สร้างที่ซ่อนของเราสองคน... ของคุณครูกับฉันได้สำเร็จ"
2002002-184 = "คราวนี้มาลองใช้ <วิธีพิเศษ> กันสักหน่อยมั้ยคะ"
2002002-185 = ""
2002002-188 = "[ns] \"หืม...? วิธีพิเศษ?\""
2002002-189 = ""
2002002-192 = "(ขณะนั้นก็มีเสียงออกมาจากลำโพงที่ติดตั้งอยู่ในห้องเรียน)"
2002002-193 = ""
2002002-195 = ""
2002002-197 = "ค่า~! สวัสดีนักเรียนโรงเรียนมิลเลเนียมทุกคนที่ฟังการออกอากาศอยู่นะคะ "
2002002-198 = "วันนี้เราก็มารับประทานมื้อเที่ยง พร้อมกับฟังเพลงที่ขอเข้ามากันเหมือนเดิมนะคะ!"
2002002-199 = "และผู้ที่ส่งคำขอมาคราวนี้..."
2002002-200 = ""
2002002-203 = "มาจากคุณ..."
2002002-204 = ""
2002002-207 = "<สาวน้อยผู้บริสุทธิ์ผุดผ่องที่สุดในมิลเลเนียม>...? คนนี้อีกแล้วเหรอ?"
2002002-208 = "อ๊ะ เพลงที่ฉันขอละค่ะ"
2002002-209 = "[s] \"คิดแล้วเชียว!\""
2002002-210 = "ไม่ไหวๆ แบบนี้ลำบากแน่ๆ"
2002002-211 = ""
2002002-215 = "ไหนดูคนอื่นซิ..."
2002002-216 = "อะไรน่ะ? คนที่ขอเพลงมามีแต่คนนี้เหรอ? คนที่ขอเข้ามาคนอื่นๆ ถูกลบออกไปหมดเลยเหรอเนี่ย? ระบบโดนแฮ็กหรือไง?"
2002002-217 = "นี่มันอะไรกันเนี่ย?"
2002002-218 = "ฮุฮุฮุ..."
2002002-219 = ""
2002002-222 = "[ns] \"ฮิมาริ...? คงไม่ใช่แบบที่ครูคิดหรอกใช่มั้ย?\""
2002002-223 = "แต่ไม่ว่ายังไง เราก็คิดว่าไม่ควรเปิดเพลงนี้..."
2002002-224 = ""
2002002-228 = "อ๊ะ เดี๋ยวสิ! ยะ... หยุดนะ! ทำไมระบบมันไม่ยอมหยุดล่ะ?!"
2002002-229 = ""
2002002-232 = "ระบบอุปกรณ์กระจายเสียงทำงานเองเรอะ?!"
2002002-233 = ""
2002002-244 = "(เสียงดนตรีที่แสนโศกเศร้าดังออกมาจากลำโพง)"
2002002-245 = ""
2002002-248 = "[ns] \"เพลงโปรดของฮิมารินี่... ไม่ธรรมดาเลยนะ\""
2002002-249 = "หัวหน้าชมรมวิศวกรรมแนะนำเพลงนี้ให้ค่ะ"
2002002-250 = "[s] \"เพลงที่ดอกไม้แสนบริสุทธ์ชื่นชอบ...เพลงเอ็นกะ?\""
2002002-251 = "ฮุฮุฮุ นั่งฟังเพลงโปรดกับคนที่อยากอยู่ด้วยในที่ซ่อนแบบนี้..."
2002002-252 = "ก็ได้บรรยากาศดีนะคะ?"
2002002-253 = ""
2002002-256 = "[ns] \"ก็นะ... อืม\""
2002002-258 = "[ns] \"อื้อ ครูว่า... ครูเข้าใจแล้วละ\""
2002002-259 = "คะ? อย่างนั้นเหรอคะ ฮุฮุฮุ"
2002002-261 = "(เสียงความวุ่นวายของชมรมกระจายเสียงยังคงดังคลอเพลงเอ็นกะออกมาจากลำโพงอย่างต่อเนื่อง...)"
2002002-262 = "(คุณครูใช้เวลาอยู่กับฮิมาริจนถึงช่วงเย็น)"
