[translation]
2002805-1 = "#title;둘만의 고민상담"
2002805-3 = "4;히나타 수영복;02\n#4;em;[반응]\n#4;a\n#wait;1000"
2002805-4 = "4;히나타 수영복;03;아, 선생님. 이쪽이에요, 이쪽!\n#4;em;[반짝]\n#4;hophop\n#4;m3"
2002805-5 = "4;히나타 수영복;02;와 주셔서 감사합니다. 사실 어떻게 보면 철없이 떼를 쓰는 것일 수도 있는 일인데……."
2002805-6 = "[s1] \"괜찮아. 학생과 선생님인걸.\"\n[s2] \"히나타의 어리광? 이건 귀하군요.\""
2002805-7 = "4;히나타 수영복;09;하하하……. 좋게 말해 주셔서 감사해요…….\n#4;em;[땀]"
2002805-8 = "4;히나타 수영복;09;하하하……. 그, 그런 가요……?\n#4;em;[땀]"
2002805-9 = "4;히나타 수영복;07;그……. 부탁드리고 싶었던 건…….\n#4;stiff"
2002805-10 = "4;히나타 수영복;06;사실 밖에서는 하지 못했던 거라……."
2002805-11 = "4;히나타 수영복;09;여, 여기서니까……? 다른 분들이 아무도 안 계신 이런 곳이니까……?\n#4;em;[///]"
2002805-12 = "#st;[0,0];instant;1;"
2002805-15 = "4;히나타 수영복;07;선생님과 저……. 둘만 있는 이런 자리니까 겨우 할 수 있는 그런 거거든요……."
2002805-16 = "4;히나타 수영복;06;그, 그러니까……. 음……."
2002805-17 = "[s3] \"편하게 말해도 좋아, 히나타.\"\n[s4] \"난 괜찮으니까. 뭐든 괜찮아.\""
2002805-20 = "4;히나타 수영복;02;……!!\n#4;em;[!]\n#4;stiff"
2002805-21 = "4;히나타 수영복;09;그, 그럼……! 그, 그러면……! 그게 뭐냐면……요……!"
2002805-22 = "#st;[0,0];instant;1;"
2002805-24 = "4;히나타 수영복;09\n#4;em;…\n#wait;2500"
2002805-25 = "4;히나타 수영복;12;고…….\n#4;stiff"
2002805-27 = "3;히나타 수영복;05;고민상담……을!! 해보고 싶어서……!!!\n#3;closeup\n#3;em;[!]\n#fontsize;80"
2002805-28 = "#st;[0,0];instant;1;"
2002805-30 = "3;히나타 수영복;07\n#3;em;[?!]\n#3;shake\n#3;closeup\n#wait;1000"
2002805-32 = "[ns] \"고민상담……?\""
2002805-33 = "3;히나타 수영복;04;네, 네! 사, 사실……. 성당에서도, 자매님들께서 몇 번 자리를 만들어 주시긴 했지만…….\n#3;em;[///]\n#3;stiff"
2002805-34 = "3;히나타 수영복;06;그 때마다 제가 더 당황하거나 머뭇거려서, 제대로 해내지 못했던 적이 꽤 있었거든요."
2002805-35 = "3;히나타 수영복;07;하면서 나아지는 거라고 좋게 말씀들은 해 주셨지만, 그래도 찾아와 주신 분들께 폐가 되고 싶지는 않아서…….\n#3;em;[속상함]"
2002805-36 = "3;히나타 수영복;04;그 이후로는 고민상담은 가급적 피하고 있는 쪽이었어요."
2002805-37 = "3;히나타 수영복;10;물론 저도 일단은 시스터고, 언제까지고 피하고만은 있을 수 없는 일이지만…….\n#3;em;[땀]"
2002805-38 = "3;히나타 수영복;06;그렇다고 고민상담 연습을 해달라는 식으로 누군가에게 부탁드리기에는, 너무 창피해서……. 그래서……."
2002805-39 = "[s5] \"아하. 즉 내가 고민을 상담하면 된다는 거네.\"\n[s6] \"그런 거야 어렵지 않지. 지금 바로 할까?\""
2002805-40 = "#st;[0,0];instant;1;"
2002805-41 = "#st;[0,0];instant;1;"
2002805-43 = "3;히나타 수영복;07\n#3;em;[?!]\n#3;shake\n#wait;1000"
2002805-44 = "3;히나타 수영복;04;네, 네!? 이렇게 바로요……!? 즈, 즉시!? 여기서!?\n#3;em;[///]"
2002805-45 = "3;히나타 수영복;10;그, 그렇지만 주변에 다른 분들……. \n#3;stiff"
2002805-46 = "#st;[0,0];instant;1;"
2002805-48 = "3;히나타 수영복;10\n#3;d\n#wait;1000"
2002805-51 = "3;히나타 수영복;07\n#3;em;…\n#3;a\n#wait;2500"
2002805-52 = "3;히나타 수영복;09;……은 없군요!\n#3;em;[땀]"
2002805-53 = "3;히나타 수영복;04;그러네요! 그래서 굳이 부탁드리려고 했던 거죠!"
2002805-54 = "3;히나타 수영복;06;으으……. 뭔가 막상 시작하려니 떨려요…….\n#3;em;[세로선]"
2002805-55 = "3;히나타 수영복;07;……네? 긴장하지 말라고요? 연습이니까……?\n#3;stiff"
2002805-56 = "3;히나타 수영복;09;그, 그렇죠. 그랬었죠."
2002805-57 = "3;히나타 수영복;06;후우, 후우우……."
2002805-58 = "#st;[0,0];instant;1;"
2002805-60 = "3;히나타 수영복;06\n#3;em;…\n#wait;2500"
2002805-61 = "3;히나타 수영복;12\n#wait;1000"
2002805-62 = "3;히나타 수영복;05;……그럼 시작하겠습니다.\n#3;greeting"
2002805-66 = "3;히나타 수영복;01\n#3;a\n#3;closeup\n#wait;1500"
2002805-67 = "3;히나타 수영복;99;지금부터 하시는 말씀의 비밀은 지켜질 것이며, 저는 그 누구에게도 저희가 나눈 대화를 발설하지 않을 것을 맹세합니다.\n#3;closeup"
2002805-68 = "3;히나타 수영복;02;그러니 우선……. 선생님.\n#3;closeup"
2002805-69 = "3;히나타 수영복;12;저에게 무슨 일로 오셨는지, 선생님께서 가지신 고민이 무엇인지…… 제가 감히 여쭈어봐도 괜찮을까요?\n#3;closeup"
2002805-70 = "[s] \"정말로 솔직하게 말해도 되나요?\""
2002805-71 = "3;히나타 수영복;03;물론이지요. 저는 시스터랍니다. 절대 이런 이야기로 거짓말을 하지 않아요.\n#3;greeting\n#3;closeup"
2002805-72 = "3;히나타 수영복;02;선생님의 진솔한 이야기를 듣고 싶답니다. 가슴 속 깊은……. 무엇도 차리지 않은 속마음을 알려주세요.\n#3;closeup"
2002805-73 = "[s] \"그럼 정말로 말하겠습니다.\""
2002805-74 = "3;히나타 수영복;12;네. 선생님. 말씀해 주세요.\n#3;closeup"
2002805-75 = "3;히나타 수영복;99;제가 듣고 있습니…….\n#3;closeup"
2002805-76 = "[s7] \"그럼……. 돌아가기 싫어요.\"\n[s8] \"계속 여기서 놀고 싶어요.\""
2002805-79 = "3;히나타 수영복;08;네. 그러시군요. 돌아가지 마시고 계속 여기서 놀…….\n#3;closeup"
2002805-80 = "#st;[0,0];instant;1;"
2002805-82 = "3;히나타 수영복;08\n#3;em;…\n#3;closeup\n#wait;2500"
2002805-83 = "3;히나타 수영복;01\n#3;em;[?]\n#3;closeup\n#wait;1000"
2002805-84 = "3;히나타 수영복;02;……네?\n#3;closeup"
2002805-85 = "3;히나타 수영복;07;선생님……? 방금 뭐라고 말씀하신…….\n#3;stiff\n#3;closeup"
2002805-86 = "[s9] \"돌아가기 싫다고! 더 놀고 싶다고요!\"\n[s10] \"뭐든지 말해도 된다고 했잖아요!\"\n[s11] \"아무튼 히나타랑 여기서 더 놀 거야!\""
2002805-87 = "#st;[0,0];instant;1;"
2002805-88 = "#st;[0,0];instant;1;"
2002805-89 = "#st;[0,0];instant;1;"
2002805-91 = "3;히나타 수영복;04\n#3;shake\n#3;em;[?!]\n#wait;1000"
2002805-92 = "3;히나타 수영복;10;서, 선생님……!? 선생님! 진정하세요, 우선 진정하세요, 선생님!\n#3;em;[땀]"
2002805-93 = "3;히나타 수영복;11;그야 마음은 십분 이해하지만……!"
2002805-94 = "3;히나타 수영복;06;그런 말씀이라면야, 저도 당연히 여기서 선생님과 더 둘만의 시간을 많이 보내고 싶지만!"
2002805-95 = "3;히나타 수영복;07;……어?\n#3;shake\n#3;em;[?!]"
2002805-96 = "3;히나타 수영복;04;……아.\n#3;stiff"
2002805-97 = "3;히나타 수영복;11;아, 아니 아니! 아니아니아니아니아니아니아니!\n#3;hophop"
2002805-98 = "3;히나타 수영복;04;이건 절대 그런 게 아니고! 아니, 그런 게 아닌 건 아니지만 아무튼 그런……!\n#3;em;[땀]"
2002805-99 = "3;히나타 수영복;06;제, 제가 무슨 불경한 말씀을……!? 시스터가 된 몸으로 그런 말을 해버리다니……!!\n#3;stiff"
2002805-100 = "[s12] \"아니, 딱히 그런 것 까지는…….\"\n[s13] \"지, 진정해. 히나타. 우선 진정해!\""
2002805-103 = "3;히나타 수영복;10;죄송합니다, 죄송합니다!! 모두에게 죄송합니다!! 선생님께도 죄송합니다!!\n#3;em;[속상함]\n#fontsize;80"
2002805-104 = "3;히나타 수영복;06;흐…….\n#3;stiff"
2002805-106 = "3;히나타 수영복;11;흐아아아아앙---!!\n#3;hophop\n#3;closeup\n#fontsize;100"
2002805-107 = "#st;[0,0];instant;1;"
2002805-109 = "3;히나타 수영복;11\n#3;dl\n#wait;2000"
2002805-111 = "#na;(이후 울상 짓는 히나타를 달래 주며 남은 시간을 보냈다.)"
2002805-112 = "#st;[0,0];instant;1;"
2002805-115 = "#na;(고민상담에 대해서는, 다음 기회에 꼭 다시 연습해 주기로 약속했다.)"
