[translation]
2003605-1 = "Thousands, Millions, Billions of Memories"
2003605-2 = "I headed to Abydos to help Serika clean the club room."
2003605-3 = ""
2003605-7 = ""
2003605-9 = ""
2003605-10 = "Hm."
2003605-11 = "You came. I SAID you didn't have to..."
2003605-12 = "I mean it. I can handle this on my own."
2003605-13 = "If you want, you could sit and wait. I have some snacks around, if you want one..."
2003605-14 = "...You're okay?"
2003605-15 = "You're really here just to help me clean...?"
2003605-16 = "Oh, Sensei..."
2003605-17 = "You can't do that. I didn't send you a MomoTalk message just to make you work."
2003605-18 = "Really, that wasn't my intention."
2003605-19 = "You're not trying to make me into THAT kind of a student, are you? Do you want me to worry about something like this happening every time I send you a MomoTalk message?"
2003605-20 = "...Huh? You still want to help? "
2003605-21 = "You're saying if it bothers me, I can just do something for you afterwards?"
2003605-22 = "Like what...?"
2003605-23 = ""
2003605-25 = ""
2003605-26 = "...Never mind. It's hard to argue when you're being so stubborn."
2003605-27 = "Fine, since you're always buying me food, I'll treat you to ramen this time."
2003605-28 = "But since you wanted to help, you better commit! We're not doing this halfway!"
2003605-29 = "With that said..."
2003605-30 = "Time to start cleaning!"
2003605-33 = "Serika and I worked on cleaning the club room together."
2003605-34 = "The room was already well organized, so most of the work consisted of wiping down hard-to-reach spots."
2003605-36 = "Yeah, I think that ought to do it..."
2003605-37 = "Hmm... Okay! It looks good! Nicely done, Sensei!"
2003605-38 = "[s1] \"You did well too, Serika.\"\n[s2] \"Feels kind of refreshing, doesn't it?\""
2003605-41 = "Well, the two of us got it done twice as fast."
2003605-42 = "So thanks for that, Sensei..."
2003605-43 = ""
2003605-46 = "...Hmm?"
2003605-47 = "[s3] \"That box...?\"\n[s4] \"I haven't seen that box before.\""
2003605-50 = "Oh, that... "
2003605-51 = "Hm, it's sitting there like it belongs there. I'd better take care of it."
2003605-52 = "Funny, I was so focused on cleaning those hidden spots, I left this obvious thing here..."
2003605-53 = ""
2003605-55 = ""
2003605-56 = "...Hold up. Sensei, how'd you know the box was new?"
2003605-57 = "You memorized all the supplies in our club room...?"
2003605-58 = "[s5] \"Things do stay mostly the same around here.\"\n[s6] \"Come here a few times, and you'll memorize it, whether you want to or not.\""
2003605-61 = "S-Sorry about that! Our club room is so empty!"
2003605-62 = "Anyway, this is nothing too special..."
2003605-63 = ""
2003605-65 = ""
2003605-66 = "[ns7] \"A swimsuit...?\"\n[ns8] \"Oh, from the resort.\""
2003605-69 = "I didn't really have a place to put it."
2003605-70 = "I got wrapped up in the mood and bought a cute one, but I haven't had a chance to wear it since then..."
2003605-71 = "So it's just been sitting here like this."
2003605-72 = "And throwing it away seems like a waste..."
2003605-73 = ""
2003605-75 = ""
2003605-76 = "...Huh? Sensei, what did you just say?"
2003605-77 = "...What?"
2003605-78 = "You think I ought to wear it...? Now?"
2003605-79 = "...Right now?!"
2003605-80 = "[s9] \"If you wear it once in a while, it won't go to waste.\"\n[s10] \"There's no law that says you can only wear it at the beach.\""
2003605-83 = "What kind of nonsense is that? Swimsuits are for swimming! It's common sense!"
2003605-84 = "Seriously Sensei, sometimes you just throw out whatever pops into your head."
2003605-85 = "*sigh*"
2003605-86 = "You don't have to go that far to make me feel better. I won't throw it away."
2003605-87 = "It's just that..."
2003605-88 = "It's something...to remember the good time we had together. So..."
2003605-89 = "It's like what you always talk about..."
2003605-90 = ""
2003605-92 = ""
2003605-93 = "M-Memories..."
2003605-94 = "So I ought to hold on to it. Yeah..."
2003605-95 = "..."
2003605-96 = "..."
2003605-97 = "Wh-What?"
2003605-98 = "What's with that face...?! You're smiling at me weird!"
2003605-99 = "[s11] \"*sob* *sob* I'm so moved, Serika...\"\n[s12] \"You're all grown up now, Serika...\""
2003605-102 = "Ahhh!"
2003605-103 = "Stop talking like my dad!"
2003605-104 = "That's it! I can't take it! Forget the ramen! Not even a drop of broth for you!"
2003605-105 = "S-Stop laughing...!"
2003605-107 = "Stop laughing, I mean it!"
