[translation]
2003402-1 = "How to Achieve a Goal"
2003402-2 = "Listen up..."
2003402-3 = "I'm going to participate in the New Year's Eating Contest!"
2003402-4 = "I've handed in my application, scouted the location, analyzed the menu..."
2003402-5 = "My preparations are complete."
2003402-6 = "Heeheehee. I'm excited for this year too. ★"
2003402-7 = "[s] \"This year too?\""
2003402-8 = "Yep, this year too."
2003402-9 = "[s] \"...Excited for what specifically?\""
2003402-10 = "Oh my! What do you mean by that? ★"
2003402-11 = "Well then, Sensei. Ready to go?"
2003402-12 = "[s] \"I'm coming too?\""
2003402-13 = "Yes, yes. If you join me, it'll be a competition to remember."
2003402-14 = "Or would you coldly refuse a hungry student's request?"
2003402-15 = "[s] \"Hungry, you say...\""
2003402-16 = "Exactly. I only ate half of my breakfast to save room for this."
2003402-17 = "Heehee. You really think it's a big deal?"
2003402-19 = "...So you really showed up, Ms. Wanibuchi Akari."
2003402-20 = "We sincerely apologize, but our organizing committee regrets to inform you that your participation in this event cannot be accommodated."
2003402-21 = "We apologize again. Thank you for your understanding."
2003402-22 = "Eh?"
2003402-23 = ""
2003402-25 = ""
2003402-27 = ""
2003402-28 = "[ns] \"What is your reasoning for this?\""
2003402-29 = "Forgive me..."
2003402-30 = "Ms. Akari was last year's winner."
2003402-31 = "Mmm, that's right. I was impressed at how they fried the konjac into tempura to make it even more filling."
2003402-32 = "She was also the winner the year before that..."
2003402-33 = "Oh! That was the year they made a batter out of potatoes and eggs, then mixed it in filets to make a special fish cake."
2003402-34 = "...And with her track record, she's likely to be this year's winner as well..."
2003402-35 = "Oh my. I mean, we won't know until we know, right?"
2003402-36 = ""
2003402-37 = "[ns1] \"(Sometimes the truth is apparent...)\"\n[ns2] \"(There are just unchanging facts of life...)\""
2003402-40 = "Please understand, our New Year's Eating Contest at the New Year's Shopping District..."
2003402-41 = "...was initially an advertisement meant to promote our stores and convince shoppers to try our food."
2003402-42 = "However, whenever Ms. Akari participates, she is guaranteed to win."
2003402-43 = "Therefore, the organizers determined it would no longer be possible for the event to draw crowds with her present."
2003402-44 = "Once the audience knew the outcome was set...interest in the competition waned."
2003402-46 = "Hmm..."
2003402-47 = "As an alternative, we would like to offer you a carefully selected premium New Year's Bento with 10 portions. A top seller. Consider this a consolation prize?"
2003402-48 = "We do hope you understand..."
2003402-49 = "..."
2003402-50 = "I didn't come here to eat premium New Year's Bentos."
2003402-51 = "I came here to sample unique foods like konjac tempura or egg-potato fish cakes! Dishes to push a participants' appetite to the limit."
2003402-52 = "Th-That's...!"
2003402-53 = "Heehee... I wonder what they prepared as the competition meal this year? I'm looking forward to it. ★"
2003402-54 = "[s] \"Well, well, well. I think I just had an idea.\""
2003402-55 = "Yes?"
2003402-56 = "Oh?"
2003402-58 = ""
2003402-59 = "I should \"defend my title as last year's champion?\""
2003402-60 = "Are you suggesting that Ms. Akari take on all the other challengers...directly?"
2003402-61 = "I-Is that safe? Even for Ms. Akari, she'd still be taking on eight challengers!"
2003402-62 = "Oh my... This is sparking my appetite for some competition."
2003402-63 = "I like it. I wasn't trying to win anyway."
2003402-64 = "It wasn't my goal last year, or the year before that."
2003402-65 = "Really?!"
2003402-66 = "[ns] \"(Knowing Akari... I believe it.)\""
2003402-67 = "Yes, I'm okay with that. I'm also excited to see what the competition meal will be this year."
2003402-68 = "J-Just a moment. I'll run this proposal by the organizers. Please wait right here!"
2003402-69 = ""
2003402-71 = ""
2003402-72 = "Heehee!"
2003402-73 = "Thanks to you, I get to have a unique dining experience once again."
2003402-74 = "[s] \"...Go easy on them, okay?\""
2003402-75 = "Hm? Whatever do you mean? ★"
2003402-77 = ""
2003402-78 = "Ladies and gentlemen, let's get started! We are now kicking off the shopping district's...New Year's Eating Contest!"
2003402-79 = "This year's contest will be a bit different... Last year's champion will be taking on all challengers!"
2003402-80 = ""
2003402-81 = "First, let's meet our champ! Here's Wanibuchi Akari, going for her third title!"
2003402-82 = ""
2003402-84 = ""
2003402-85 = "Hehe. Hello everyone. Thank you for your support."
2003402-86 = "And now, let's meet our eight challengers!"
2003402-88 = ""
2003402-90 = ""
2003402-92 = ""
2003402-95 = ""
2003402-96 = ""
2003402-97 = ""
2003402-98 = "And so it begins! As our challengers fiercely clear their plates, our champion seems totally relaxed!"
2003402-99 = ""
2003402-100 = "Mmm! This year's special is a rolled omelet with ground taro and beans. I see..."
2003402-101 = "There are some other competition foods as well. Let's try them all!"
2003402-102 = ""
2003402-103 = ""
2003402-104 = ""
2003402-105 = ""
2003402-106 = ""
2003402-107 = ""
2003402-108 = "Aah! Our challengers are losing steam! "
2003402-109 = ""
2003402-111 = ""
2003402-112 = ""
2003402-113 = ""
2003402-114 = "Meanwhile, reigning champ Akari hasn't slowed down at all! She chomps through whatever is set down before her. The gap in experience is massive!"
2003402-115 = "Oh, the herring roe and kelp rolls are well-seasoned. Yummy."
2003402-116 = "I'm getting a little thirsty. I'll wash it down with some soup."
2003402-117 = ""
2003402-119 = ""
2003402-120 = ""
2003402-121 = ""
2003402-122 = ""
2003402-123 = ""
2003402-124 = ""
2003402-125 = ""
2003402-126 = ""
2003402-127 = ""
2003402-128 = ""
2003402-129 = ""
2003402-130 = "The challengers have started to forfeit one by one. Please don't overdo it! We have ambulances for you on standby!"
2003402-131 = ""
2003402-133 = ""
2003402-134 = ""
2003402-135 = ""
2003402-136 = "Akari is on fire! She's still going, bite after bite! Is there any limit to her stomach? Does a black hole sleep inside her belly?"
2003402-137 = "Oh my. Is everyone done? There are still so many dishes left."
2003402-138 = "Hey, would you mind bringing me the food they didn't finish?"
2003402-139 = "This is an all-you-can-eat contest, so it'd be a shame to waste food."
2003402-146 = ""
2003402-147 = "Yes! Yes! The results are in!"
2003402-148 = "As many of you predicted, this year's winner is... Wanibuchi Akari! She's now our three-time champion!"
2003402-149 = "Heehee... It seems like this year's competition successfully promoted the shopping district."
2003402-150 = "Plus I got to eat lots of yummy food... All thanks to your brilliant idea, Sensei! ★"
2003402-151 = ""
2003402-152 = "Oh, thank you both so much! Our lack of foresight nearly led to a massive mistake."
2003402-153 = ""
2003402-155 = ""
2003402-156 = "Oh, my phone's going off like crazy. What could be causing that?"
2003402-157 = "[s3] \"The people who watched the contest...\"\n[s4] \"...uploaded the whole spectacle onto the internet...\""
2003402-160 = "Oh my. Look at all those views!"
2003402-161 = "Wait, what?!"
2003402-162 = "..."
2003402-163 = "That's wonderful! This will promote our shopping district even more!"
2003402-165 = "B-But, what might happen from here...I'm not really sure."
2003402-167 = "Heehee!"
2003402-168 = ""
2003402-170 = ""
2003402-171 = ""
2003402-172 = "Isn't that just the way of the world? ★"
2003402-174 = "Though Akari's laughter was light and pure, it came off as just a tiny bit chilly."
