[translation]
2003005-1 = "#title;탐구의 길은, 어디에나."
2003005-2 = "#na;(도대체 무슨 바람이 불어서 경기에 참가하겠다는 것인지 알 수 없었지만……)"
2003005-3 = "#na;(기대 반, 호기심 반으로 하루나의 경기를 지켜보기로 했다.)"
2003005-4 = "#st;[0,0];instant;1;"
2003005-6 = "3;하루나 체육복ND;03;아, 선생님. 와 주셨군요.\n#3;em;[반응]\n#3;a"
2003005-7 = "[s1] \"학생을 응원하는 건 선생님이 할 일이니까.\"\n[s2] \"그런데, 무슨 경기에 나가는 거야?\""
2003005-10 = "3;하루나 체육복ND;14;무슨 경기, 가 아니랍니다. 선생님."
2003005-11 = "3;하루나 체육복ND;05;왜냐하면…… '경기들'이니까요!\n#3;em;[!]\n#3;closeup\n#fontsize;100"
2003005-12 = "[s] \"뭣? 하나가 아니라 다수의 경기라고!?\""
2003005-13 = "3;하루나 체육복ND;14;후후후……"
2003005-14 = "3;하루나 체육복ND;13;그만큼 제가 진심이라는 것을 알아주셨으면 하네요."
2003005-15 = "[s3] \"궁금하다. 정말로 궁금해!\" \n[s4] \"도대체 무엇이 하루나의 열의를 이렇게까지 불태웠는지!\""
2003005-18 = "3;하루나 체육복ND;03;후후후, 그 첫 번째 경기는 바로……!\n#3;em;[반응]"
2003005-19 = "#st;[0,0];instant;1;"
2003005-22 = "#na;아나운서;쿠로다테 하루나 선수. 다음 경기 종목인 '빵 먹기 대회'의 출전을 위해, 출발선으로 와 주십시오."
2003005-23 = "[s] \"……아.\""
2003005-24 = "3;하루나 체육복ND;14;그렇습니다. 선생님. 아무리 이런 분위기라고 해도 우리 미식연구회는 미식연구회."
2003005-25 = "3;하루나 체육복ND;03;경기를 위해 준비된 음식들이…… 제대로 된 것인지 확인하는 것은 미식연구회의 사명이라고도 할 수 있겠지요!\n#3;em;[반짝]\n#3;greeting"
2003005-26 = "[s] \"……응. 그래. 다녀와.\""
2003005-27 = "3;하루나 체육복ND;07;응원, 감사합니다."
2003005-28 = "#st;[0,0];instant;1;"
2003005-30 = "3;하루나 체육복ND;01\n#3;m2\n#wait;1200"
2003005-31 = "3;하루나 체육복ND;03;그러면 빵 먹기 경주, 최선을 다해 맛보고 오겠습니다."
2003005-34 = "#na;(하루나는 경쾌한 발걸음으로 출발선을 향해 갔다.)"
2003005-35 = "#st;[0,0];instant;1;"
2003005-38 = "#na;(모든 선수들이 출발선에 나란히 섰고, 그리고……)"
2003005-39 = "#st;[0,0];instant;1;"
2003005-43 = "3;하루나 체육복ND;00\n#3;stiff\n#3;closeup\n#wait;1000"
2003005-44 = "3;하루나 체육복ND;00\n#3;dl\n#wait;1000"
2003005-47 = "#na;(하루나는 중상위권 정도를 유지하면서, 마침내 빵이 매달린 반환점에 도착했다!)"
2003005-50 = "3;하루나 체육복ND;00\n#3;al\n#wait;1200"
2003005-51 = "3;하루나 체육복ND;14;후후후……"
2003005-52 = "[s] \"하루나! 힘내!\""
2003005-53 = "#st;[0,0];instant;1;"
2003005-55 = "3;하루나 체육복ND;02\n#3;em;[반응]\n#3;h\n#wait;1000"
2003005-56 = "3;하루나 체육복ND;03;그러면, 빵 먹기 경주의 하이라이트. 맛보기로 할까요?"
2003005-57 = "#st;[0,0];instant;1;"
2003005-59 = "3;하루나 체육복ND;14\n#3;greeting\n#wait;1500"
2003005-60 = "3;하루나 체육복ND;14;(오물오물)"
2003005-61 = "#st;[0,0];instant;1;"
2003005-63 = "3;하루나 체육복ND;02\n#3;em;[?]\n#wait;1000"
2003005-64 = "3;하루나 체육복ND;09\n#3;greeting\n#wait;1500"
2003005-65 = "3;하루나 체육복ND;11;(오물오물오물오물)"
2003005-66 = "#st;[0,0];instant;1;"
2003005-68 = "3;하루나 체육복ND;11\n#3;em;…\n#wait;2500"
2003005-69 = "3;하루나 체육복ND;11;으음……\n#3;em;[세로선]\n#3;stiff"
2003005-70 = "[s] \"어라, 하루나의 표정이……?\""
2003005-71 = "#st;[0,0];instant;1;"
2003005-73 = "3;하루나 체육복ND;05\n#3;stiff\n#wait;1500"
2003005-75 = "3;하루나 체육복ND;09;이 빵은, 틀려먹었어요!\n#3;closeup\n#bgshake\n#fontsize;100"
2003005-76 = "3;하루나 체육복ND;05;경기에 한 번 사용할 빵이라고 해서, 너무 생각 없이 준비한 것 아닌가요?\n#3;em;[빠직]\n#3;stiff\n#3;closeup"
2003005-77 = "3;하루나 체육복ND;11;표면은 너무 말라 있고, 안은 퍼석하고, 무엇보다 밀가루 맛이 혀끝에 맴도는군요!\n#3;closeup"
2003005-78 = "3;하루나 체육복ND;09;발효 과정과 시간은 제대로 지켜졌나요? 오븐의 예열은 정해진 공정만큼 이루어졌나요? \n#3;closeup"
2003005-79 = "3;하루나 체육복ND;05;믿을 수 없군요. 공장을 통한 대량 생산의 이점은, 최고의 맛을 보장할 수는 없더라도 맛의 최저선을 끌어올리는 데에 있는 것일 텐데─\n#3;closeup\n#3;stiff"
2003005-80 = "#na;아나운서;쿠, 쿠로다테 하루나 선수. 갑자기 경기를 중지하고 빵과 미식에 대한 웅변을 이어 나가기 시작했습니다─?"
2003005-85 = "#na;(……그 뒤로도, 하루나의 맛에 대한 항의는 계속되었다……)"
2003005-88 = "#na;(그리고, 그렇게 다음 경기가 찾아왔다.)"
2003005-89 = "[s] \"좋아. 빵 경기는 그렇다 치고, 다음은?!\""
2003005-90 = "3;하루나 체육복ND;03;네. 다음은 장애물 달리기 경주입니다.\n#3;em;[반응]\n#3;a"
2003005-91 = "[s] \"과연! 이번은 다르구나!\""
2003005-93 = "4;하루나 체육복ND;05\n#4;a\n#4;em;…\n#wait;2500"
2003005-94 = "4;하루나 체육복ND;09;이온 음료를 마실 수 있다는 소식에, 장거리 달리기 경주에 참가했습니다만……"
2003005-95 = "4;하루나 체육복ND;05;설탕 성분이 너무 많아, 오히려 빠른 수분 흡수를 방해하고 있어요!\n#4;stiff\n#4;em;[빠직]"
2003005-96 = "4;하루나 체육복ND;11;물론 당분을 급격하게 소비한 몸에 빠른 에너지원을 공급한다는 것은 중요하지만."
2003005-97 = "4;하루나 체육복ND;09;혀 안쪽까지 진득하게 당분이 달라붙을 정도로 설탕 과다라는 것은, 문제가 있지 않을까요?"
2003005-99 = "3;하루나 체육복ND;05;이온 음료는 이온 음료입니다. 에너지 드링크와는 달라요!\n#3;closeup\n#3;em;[!]\n#fontsize;80"
2003005-100 = "3;하루나 체육복ND;05;단맛을 특히 강조하고 싶었다면, 적당한 양의 인공 감미료를 사용하는 방법은 없었을까요?\n#3;closeup"
2003005-101 = "[s] \"장애물 달리기 경주에서도 가차 없는 평가가?!\""
2003005-102 = "3;하루나 체육복ND;09;아직 끝나지 않았답니다?\n#3;em;[반응]\n#3;closeup"
2003005-105 = "2;하루나 체육복ND;11\n#2;a\n#2;em;[한숨]\n#wait;1200"
2003005-106 = "2;하루나 체육복ND;06;이유는 잘 모르겠지만, 양궁 종목의 참가상으로 생크림 도넛을 제공한다고 하여 참가했습니다만……"
2003005-107 = "2;하루나 체육복ND;05;이건 뭔가요! 생크림 도넛이 아니라 식물유지 크림 도넛이잖습니까!\n#2;stiff"
2003005-109 = "3;하루나 체육복ND;09;생크림이란 생우유에서 크림 층을 건져낸 것을 뜻합니다!\n#3;closeup\n#bgshake\n#fontsize;100"
2003005-110 = "3;하루나 체육복ND;11;아무리 생크림과 최대한 비슷하게 만들었다고 해도, 식물유지 크림에는 어느 정도의 가공 과정이 들어갈 수밖에 없어요!\n#3;closeup"
2003005-111 = "3;하루나 체육복ND;05;아무리 생크림과 비슷하다고 해도, 감칠맛 같은 맛의 차이가 발생할 수 밖에 없죠!\n#3;em;[빠직]\n#3;closeup"
2003005-114 = "#na;(……하루나의 열변은 그런 식으로 경기들을 따라 계속되었다……)"
2003005-117 = "3;하루나 체육복ND;14;드디어…… 마지막 경기로군요.\n#3;em;[...]\n#3;a"
2003005-118 = "3;하루나 체육복ND;00;밀가루 사탕 경주. 숨은 사탕을 입술과 혀로만 찾아내야 하는, 고난도의 경기죠."
2003005-119 = "3;하루나 체육복ND;03;선생님. 보고 계신가요? 마지막까지 응원, 부탁드릴게요?\n#3;em;[반응]"
2003005-120 = "[s] \"응…… 그래. 하루나 다운 종목 선택이야……\""
2003005-124 = "#na;(하루나가 다시 출발선에 섰다.)"
2003005-125 = "#st;[0,0];instant;1;"
2003005-130 = "3;하루나 체육복ND;05\n#3;stiff\n#3;closeup\n#wait;1000"
2003005-131 = "3;하루나 체육복ND;05\n#3;dl\n#wait;1000"
2003005-135 = "#na;(하루나는 피로감이 전혀 느껴지지 않는 달리기로, 사탕이 묻힌 밀가루 판에 얼굴을 묻었다……!)"
2003005-136 = "#st;[0,0];instant;1;"
2003005-139 = "#na;아나운서;선두는 놀랍게도, 게헨나 학원의 쿠로다테 하루나 선수입니다!"
2003005-140 = "#st;[0,0];instant;1;"
2003005-143 = "#na;아나운서;하루나 선수, 달립니다. 달립니다!"
2003005-144 = "#na;아나운서;그대로 결승선을 향해……"
2003005-145 = "#st;[0,0];instant;1;"
2003005-148 = "3;하루나 체육복ND;05\n#3;stiff\n#3;closeup\n#wait;1000"
2003005-150 = "#na;아나운서;골인!\n#fontsize;100"
2003005-151 = "#st;[0,0];instant;1;"
2003005-154 = "#na;아나운서;아앗, 하루나 선수. 결승선을 지나고서도 어딘가로 계속해서 달려가는데요! 하루나 선수가 향하는 곳은, 과연……!"
2003005-158 = "3;하루나 체육복ND;00\n#3;a\n#3;h\n#wait;1000"
2003005-159 = "3;하루나 체육복ND;03;선생님, 보고 계셨나요?\n#3;em;[반짝]"
2003005-160 = "[s] \"물론이야! 1등 축하해!\""
2003005-161 = "3;하루나 체육복ND;07;후후후……"
2003005-164 = "#st;[-1200,-530];serial;60;[wa:500]― [log=하루나 체육복ND]가슴 뛰는, [wa:1300]맛있는 [wa:300]경기였습니다.[/log]"
2003005-166 = "#st;[-1200,-630];serial;60;― [log=하루나 체육복ND]얼굴은 [wa:300]조금 [wa:250]지저분해졌지만……[/log]"
2003005-169 = "#st;[-1200,-530];serial;60;[wa:500]― [log=하루나 체육복ND]그러나, [wa:1050]미지의 [wa:320]영역이라고 할 수 있는 [wa:780]밀가루 속에서.[/log]"
2003005-171 = "#st;[-1200,-630];serial;60;― [log=하루나 체육복ND]자신의 감각만으로 [wa:1550]사탕을 찾아내는 행위는……[/log]"
2003005-174 = "#st;[-1200,-530];serial;60;[wa:500]― [log=하루나 체육복ND]미식을 [wa:400]탐구하는 과정과, [/log]"
2003005-176 = "#st;[-1200,-630];serial;60;― [log=하루나 체육복ND]어딘지 모르게 닮은 것 같아……[/log] [wa:300] "
2003005-179 = "#st;[-1200,-530];serial;60;― [log=하루나 체육복ND]매우 [wa:400]신선했답니다.[/log]"
2003005-182 = "#st;[-1200,-530];serial;60;[wa:200]― [log=하루나 체육복ND]아, [wa:800]그래요! [/log]"
2003005-185 = "#st;[-1200,-530];serial;60;[wa:700]― [log=하루나 체육복ND]선생님. [wa:850]어떠신가요?[/log]"
2003005-188 = "#st;[-1200,-530];serial;60;― [log=하루나 체육복ND]조금 전 받은 [wa:1050]이 사탕…… [/log]"
2003005-190 = "#st;[-1200,-630];serial;60;― [log=하루나 체육복ND]선생님께[wa:1000] 나누어 드릴까요?[/log]"
2003005-193 = "#na;(하루나가 나누어 주겠다는 사탕(?)을 극구 말리면서, 하루나와 함께 돌아왔다……)"
2003005-194 = "#na;(경기 음식들의 품질이 마음에 들지 않았을 텐데도, 하루나의 기분은 묘하게 좋아 보였다.)"
