[translation]
2004002-1 = "ซัตสึกิรู้นะ"
2004002-2 = "(ไม่นานหลังจากได้รับข้อความจากซัตสึกิ...)"
2004002-3 = ""
2004002-6 = "ฮุฮุ ที่นี่คือห้องทำงานของครูสินะ... ดูเรียบง่ายเหมือนที่มาโคโตะจังบอกไว้เลย"
2004002-7 = "อ๊ะ ครูไม่ได้งานยุ่งอยู่ใช่มั้ย?"
2004002-8 = "[s] \"ครูงานยุ่งอยู่ตลอดนั่นละ ว่าแต่มีเรื่องอะไร...\""
2004002-9 = "งั้นเหรอ แต่ถึงอย่างนั้นก็ไม่สำคัญหรอก"
2004002-10 = "เพราะสิ่งที่ฉันเอามาด้วยเป็นสิ่งสำคัญที่ต่อให้มีงานยุ่งแค่ไหนก็ต้องวางเอาไว้ก่อนน่ะ"
2004002-11 = "[s1] \"ไม่คิดจะฟังสิ่งที่ครูพูดตั้งแต่แรกเลยสินะ...\"\n[s2] \"ตกลงมีเรื่องอะไรเหรอ?\""
2004002-14 = "ฮึ่ม ฉันคิดว่าครูพอจะเดาได้แล้วเสียอีก"
2004002-15 = "เลิกแสดงละครแล้วมาคุยกันอย่างผู้เชี่ยวชาญเถอะน่า"
2004002-16 = "เอาเถอะ ตอนนี้แผนการของแพนเดโมเนียม โซไซตี้ที่กำลังดำเนินการอยู่..."
2004002-17 = "แผนการ [ควบคุมสื่อในคิโวทอส] เฟส 1 ของมาโคโตะจังอยู่ในขั้นตอนดำเนินการอย่างสมบูรณ์แล้ว"
2004002-18 = ""
2004002-20 = ""
2004002-21 = ""
2004002-22 = "ดังนั้นครูที่เป็นผู้ร่วมมือของแพนเดโมเนียม โซไซตี้ก็ควรจะให้ความร่วมมืออย่างแข็งขันด้วย"
2004002-23 = ""
2004002-26 = "[ns3] \"ครูไม่เคยบอกว่าจะให้ความร่วมมือในเรื่องแบบนั้นนะ\"\n[ns4] \"แต่แผนการนี้ครูเพิ่งจะเคยได้ยินครั้งแรกเลยนะ?!\""
2004002-29 = "จะเป็นแบบนั้นไปได้ยังไง ข้อมูลจากฝ่ายข่าวกรองของแพนเดโมเนียม โซไซตี้ ไม่มีทางผิดพลาดไปได้หรอก"
2004002-30 = "ครูลงไปเลียรองเท้าของมาโคโตะจังกลางจัตุรัสเกเฮนน่าต่อหน้าทุกคน แล้วสัญญาว่าจะให้ความร่วมมือ#nกับเราไปตราบจนชั่วฟ้าดินสลายไม่ใช่เหรอ?"
2004002-31 = "[s] \"ไม่ใช่นะ!! ไปเอาข้อมูลเหลวไหลแบบนั้นมาจากไหนกัน!!\""
2004002-32 = "ฮึ่ม หรือว่าข้อมูลที่ได้มาจะคลาดเคลื่อน พอฉันข้ามขั้นตอนการตรวจสอบข้อมูลเพราะขี้เกียจ ก็เกิดปัญหาแบบนี้สินะ"
2004002-33 = "[s] \"ข้ามขั้นตอนที่ไม่ควรจะข้ามไปได้ยังไงเนี่ย?\""
2004002-34 = ""
2004002-36 = ""
2004002-37 = "เอาเถอะน่า เอาเป็นว่าฉันแนะนำตัวอย่างเป็นทางการก่อนดีกว่า"
2004002-38 = "ฉันเคียวโงคุ ซัตสึกิ ทายาทคนต่อไปของฝ่ายข่าวกรองแห่งสภานักเรียนเกเฮนน่า"
2004002-39 = "ส่วนฝ่ายข่าวกรองของแพนเดโมเนียม โซไซตี้ที่ฉันเป็นหัวหน้าอยู่น่ะ จะเรียกในทางเทคนิคว่า#nเป็นผู้สืบทอดหลักการของฝ่ายข่าวกรองแห่งสภานักเรียนเกเฮนน่าที่ถอยหลังเข้าคลองสู่ประวัติศาสตร์#nไปแล้วก็ได้"
2004002-40 = "ถึงฉันจะไม่ได้มารับช่วงต่ออย่างเป็นทางการ แต่ฉันก็คิดอย่างนั้นน่ะ"
2004002-41 = "[s] \"คิดเองเออเองหมดเลยสินะ...\""
2004002-42 = "เอาละ แนะนำตัวเท่านี้ก็น่าจะเพียงพอแล้ว งั้นก็มาเข้าเรื่องกันเลย"
2004002-43 = "ถ้าครูไม่ให้ความร่วมมือโดยสมัครใจละก็..."
2004002-44 = "ฉันก็คงไม่มีทางเลือกอื่น นอกจากแบล็กเมล์ด้วยข้อมูลสำคัญที่ฝ่ายข่าวกรองของเราได้มา"
2004002-45 = ""
2004002-47 = ""
2004002-48 = ""
2004002-51 = "[ns] \"ข้อมูลสำคัญงั้นเหรอ...?\""
2004002-52 = "ก็ 'จุดอ่อน' ของครูยังไงล่ะ"
2004002-53 = "ฮุฮุ ว่าไงล่ะ? พร้อมที่จะฟังหรือยัง?"
2004002-54 = "[s] \"......\""
2004002-56 = "[ns] (มีจุดอ่อนเยอะไปหมดจนไม่รู้เลยว่าจะโดนหยิบเรื่องไหนมาพูด...)"
2004002-57 = "อย่างแรกเลย"
2004002-58 = "ครู คุณน่ะ..."
2004002-59 = ""
2004002-61 = ""
2004002-62 = "ได้ยินว่างานอดิเรกคือการวิ่งล่อนจ้อนไปทั่วทุ่งในคิโวทอสใช่มั้ย?"
2004002-63 = "[s] \"นั่นมันก็เรื่องจริง! แต่ไม่ถึงกับเป็นงานอดิเรกนะ!\""
2004002-64 = "ยอมรับจุดอ่อนของตัวเองอย่างง่ายดายแบบนี้เลยเหรอ...?"
2004002-65 = "หรือว่าไม่มองว่าเรื่องแบบนี้เป็นเรื่องที่น่าอายเลยสักนิด? สมกับที่เป็นครูจังเลยนะ"
2004002-66 = "[s] \"มันก็น่าอายอยู่หรอก แต่ว่า...!\""
2004002-67 = "ฮึ่ม แต่มันยังไม่จบแค่นี้หรอก"
2004002-68 = "ฉันมีข้อมูลเรื่องจุดอ่อนของครูอยู่อีกเป็นสิบๆ อย่างเลย"
2004002-69 = "[s] \"มีเยอะขนาดนั้นเลยเหรอ? นี่ครูใช้ชีวิตมายังไง... กันนะ...\""
2004002-70 = "ถ้าคิดว่ากลัวจนฟังต่อไม่ไหว ฉันจะหยุดพูดให้ก็ได้นะ แต่ครูต้องสัญญาว่าจะให้ความร่วมมือกับ#nแพนเดโมเนียม โซไซตี้ไปตราบจนฟ้าดินสลาย"
2004002-71 = "เอาละ จุดอ่อนอย่างต่อไปของครู..."
2004002-72 = "[ns] (กลืนน้ำลาย...)"
2004002-73 = "ครูน่ะ..."
2004002-74 = ""
2004002-76 = ""
2004002-77 = "ได้ยินว่าระดมทุนเพื่อนักเรียนที่ขาดแคลนอาหารอยู่ทุกเดือนเลยใช่มั้ย? ฮุฮุ"
2004002-78 = "[s] \"......\""
2004002-80 = "[ns5] \"แต่นี่มันไม่น่าจะเป็นจุดอ่อนนะ...\"\n[ns6] \"ครูว่ามันเป็นเรื่องที่น่าชื่นชมมากกว่าหรือเปล่า?\""
2004002-83 = "ไม่ ไม่หรอก"
2004002-84 = "คิโวทอสที่เราอาศัยกันอยู่น่ะเป็นโลกป่าเถื่อนที่มีแต่คนที่แข็งแกร่งเท่านั้นที่อยู่รอด"
2004002-85 = "หากเปิดเผยจิตใจที่เมตตากรุณาในโลกที่โหดร้ายแบบนี้ มันก็ไม่ต่างกับการเปิดเผยจุดอ่อนของตัวเอง#nออกมาหรอก"
2004002-86 = "[s] \"ครูแค่ทำเพื่อนักเรียนในฐานะครูน่ะ\""
2004002-87 = "ฮุฮุ จะข้ามเรื่องนี้ไปง่ายๆ งั้นเหรอ?"
2004002-88 = "สมกับที่เป็นครูจังเลยนะ รู้จักใช้ประโยชน์จากช่องโหว่ด้วยการยอมรับ เพื่อให้อีกฝ่ายเอาข้อมูลนั้นไป#nใช้ในทางที่ไม่ดีไม่ได้เหรอเนี่ย"
2004002-89 = "[s] \"ไม่ใช่ นั่นมันไม่ใช่จุดอ่อนตั้งแต่แรกเลยต่างหาก...\""
2004002-90 = "ฮึ่ม แต่ว่าข้อมูลต่อไปมันอันตรายใช่เล่นเลยนะ"
2004002-91 = "จุดอ่อนอย่างที่สามของครู..."
2004002-92 = ""
2004002-94 = ""
2004002-95 = "ตอนครูต้มราเม็งสำเร็จรูป ครูจะเทเศษราเม็งในซองลงหม้อหมดไม่มีเหลือ...!"
2004002-96 = "[s] \"......\""
2004002-98 = "[ns] \"คนอื่นเค้าก็ทำอย่างนั้นกันปกติไม่ใช่เหรอ...?\""
2004002-99 = "ฮุฮุ ถึงจะเป็นการกระทำเดียวกัน แต่ความหมายมันก็ต่างออกไปตามคนที่ทำนะ"
2004002-100 = "เป็นถึงครูจากชาเล่ต์ที่ทั้งเลิศเลอและสมบูรณ์แบบ แต่กลับมาทำตัวเหมือนคนธรรมดาทั่วไป"
2004002-101 = "ถ้านักเรียนได้รู้ความจริงข้อนี้ขึ้นมาล่ะ? ไม่คิดว่าทุกคนจะผิดหวังขั้นสุดจนต้องเบือนหน้าหนีเหรอ?"
2004002-102 = "แต่แพนเดโมเนียม โซไซตี้ของเราไม่เป็นอย่างนั้นหรอกนะ พวกเราน่ะยอมรับข้อบกพร่องแบบนั้นของ#nครูได้..."
2004002-103 = "[s] \"ไม่ละ ไม่ต้องก็ได้...\""
2004002-104 = ""
2004002-106 = "ดูเหมือนว่าครูจะยังอ่านสถานการณ์ไม่ออกนะ"
2004002-107 = "ตอนนี้ฉันกำลังขู่ครูอยู่นะ"
2004002-108 = ""
2004002-110 = ""
2004002-111 = ""
2004002-112 = "ฉันอาจจะเอาจุดอ่อนอันใหญ่หลวงนี้ไปป่าวประกาศให้คนทั้งโลกรู้ก็ได้ อยากให้ความลับถูกเปิดเผย#nมั้ยล่ะ?"
2004002-113 = "[s] \"ถึงจะทำอย่างนั้นก็ไม่เป็นไรหรอก...\""
2004002-114 = ""
2004002-116 = ""
2004002-117 = ""
2004002-118 = "เรื่องใหญ่ขนาดนี้ก็ไม่สนงั้นเหรอ... ฮุฮุ..."
2004002-119 = "ฉันไม่รู้หรอกนะว่าครูพูดอย่างเด็ดเดี่ยวแบบนั้นได้ยังไง งั้นฉันก็คงไม่มีทางเลือกอื่น"
2004002-120 = "ฉันจะพับแผนการแบล็กเมล์ด้วยจุดอ่อนก่อนแล้วกัน"
2004002-121 = "แต่ฉันไม่ได้ยอมแพ้แค่นี้หรอกนะ"
2004002-122 = "ฉันจะทำทุกวิถีทางเพื่อขอความร่วมมือจากครูให้ได้"
2004002-123 = "เอาละ งั้นฉันขอตัวกลับก่อน"
2004002-124 = "[s] \"อืม... กลับดีๆ ล่ะ...\""
2004002-125 = ""
2004002-127 = "ฮุฮุ ครั้งหน้าฉันไม่ใจดีให้เหมือนวันนี้หรอกนะ ตั้งตารอได้เลย"
2004002-128 = ""
2004002-130 = ""
2004002-132 = "[ns] \"เหมือนจะเข้าใจอะไรครูผิดไปมากเลยนะเนี่ย...\""
