[translation]
2004608-1 = "Guarded by the Heavens, Revered by the Earth"
2004608-2 = ""
2004608-3 = "Sensei."
2004608-4 = "I knew you'd come."
2004608-5 = "Welcome back to Hyakkiyako."
2004608-6 = "[s] \"What are you plotting?\""
2004608-7 = "Oh, don't call it that. I'm just seizing an opportunity."
2004608-8 = "And at the risk of ruining the moment, I'll go ahead and say it:"
2004608-9 = "I'm going to take over the world."
2004608-10 = ""
2004608-13 = "I know. Sounds unrealistic, doesn't it? But I've made all kinds of preparations."
2004608-14 = "For example...remember what I said? About how the Yin-Yang Club can't lead Hyakkiyako?"
2004608-15 = "About how we're irrelevant and have no real power?"
2004608-16 = "Even the Gehenna Prefect Team would agree with me on that, and they're flawless, aren't they?"
2004608-17 = "But where did that idea come from? Who first started saying it?"
2004608-18 = "Nyaha... I did."
2004608-19 = ""
2004608-21 = ""
2004608-22 = ""
2004608-23 = "The most dangerous blade is the one you can't see."
2004608-24 = "Show them that your sword is sheathed and peace-bonded, and they'll never even look for the dagger."
2004608-25 = "I've been consolidating power under everyone's noses. Even yours, Sensei."
2004608-26 = "All the power of Hyakkiyako, in one place. No one can stop us now."
2004608-27 = ""
2004608-29 = ""
2004608-32 = ""
2004608-35 = ""
2004608-38 = ""
2004608-39 = "Gehenna and Trinity are busy fighting each other. Millennium is...heh, Millennium."
2004608-40 = ""
2004608-46 = "The Black Dragon has locked its gate for fear of the storm, and the Red Bear is made up of bickering amateurs."
2004608-47 = "Let's not even mention Valkyrie."
2004608-48 = ""
2004608-51 = ""
2004608-52 = "The only possible obstacle I have is the General Student Council...or, to be more precise..."
2004608-53 = ""
2004608-55 = ""
2004608-56 = "Schale's [USERNAME] Sensei."
2004608-57 = "[ns] \"Niya.\""
2004608-58 = "Ah, there's that scary face again. Don't worry. I didn't bring you here to fight."
2004608-59 = "Violence is crude and simple. The superior strategist wins without it."
2004608-60 = "I've watched you for a long time, Sensei. I know how capable you are. There's no need for us to oppose each other, is there?"
2004608-61 = "Pardon the cliché, but wouldn't you rather join us instead? You'll find my terms quite reasonable, I assure you."
2004608-62 = "[ns1] \"Niya, I have something serious to tell you.\"\n[ns2] \"This is going to be long, so pay attention.\""
2004608-65 = "...Did you come all the way here to lecture me?"
2004608-66 = "I see. I must have blinded you with all this."
2004608-67 = ""
2004608-69 = ""
2004608-70 = "Regardless, I'm no longer your student, and you're no longer Sensei to me."
2004608-71 = "You and I are either partners or enemies now."
2004608-72 = "And if you choose to be my enemy..."
2004608-73 = "...I WILL pull this trigger. Does that clarify things?"
2004608-74 = "[s3] \"It doesn't change anything.\"\n[s4] \"Niya, you're still my student, and I'm still your teacher.\""
2004608-77 = ""
2004608-80 = "[ns5] \"And if a student makes a wrong choice...\"\n[ns6] \"...it's my job to correct them.\""
2004608-83 = "...Very well. You seem sincere enough. I'll take you at your word."
2004608-84 = ""
2004608-86 = ""
2004608-87 = ""
2004608-88 = ""
2004608-89 = "How disappointing..."
2004608-90 = ""
2004608-92 = ""
2004608-93 = ""
2004608-94 = "...Ta-da!"
2004608-95 = "Did you like my act, Sensei? Nyahaha..."
2004608-96 = ""
2004608-98 = ""
2004608-99 = "Kind of shook you up, didn't it?"
2004608-100 = "Don't worry. It was all just a little skit I put together."
2004608-101 = "I don't plan on taking over anything, and that video I showed you was fake."
2004608-102 = "I wouldn't get anything out of a war. Hyakkiyako's main income is built on tourism. Who'd want to pay to tour a war zone?"
2004608-103 = "So I bet you're wondering why I said all that just now."
2004608-104 = "Just for fun, basically. I knew you'd react to it."
2004608-105 = "I've called you out here multiple times, and you've always come running. Even for the most trivial things."
2004608-106 = "Wouldn't it be a huge twist if I'd just been using you the whole time, in some twisted game?"
2004608-107 = "Fun fact: if I'd wanted to, I COULD have done everything I just talked about."
2004608-108 = "[s] \"But you haven't.\""
2004608-109 = "Nyahaha! True, I'm just speaking hypothetically."
2004608-110 = "Or...am I?"
2004608-111 = "Am I REALLY not capable of all those things?"
2004608-112 = "[s7] \"Oh, you're capable, in the general sense...\"\n[s8] \"But you haven't...\""
2004608-115 = "...I SAID \"hypothetically,\" didn't I?"
2004608-116 = "Real talk, if I wanted to, I could have built the Yin-Yang Club into something more powerful."
2004608-117 = "Maybe not \"threat to Kivotos\" powerful, but definitely enough to control all the other clubs here in Hyakkiyako."
2004608-118 = "So there's no question of whether I COULD have or not. I could have, for sure."
2004608-119 = "[s9] \"No, you really couldn't have.\"\n[s10] \"You like Hyakkiyako too much.\""
2004608-122 = "Nyaha...?"
2004608-123 = "...You're saying, because I like Hyakkiyako, I'd never do anything to harm it...?"
2004608-124 = "And so you never bought the act in the first place...?"
2004608-125 = "..."
2004608-126 = "Nyahaha! Well, good point!"
2004608-127 = "Wow, maybe I'm just dumb for trying to put one over on you."
2004608-128 = "But I definitely got a reaction out of you, at least."
2004608-129 = "Maybe I should be more on the level with you from here on out."
2004608-130 = "*sigh* Now that I think about it, yeah, I'm sorry. I dragged you out here at this hour, just to watch me go back and forth about myself..."
2004608-131 = "I'm the president of the club that symbolizes balance, but I guess I'm way more yin than yang."
2004608-132 = "Even when I'm \"Nyahaha\"-ing it up, I'm barely keeping balance at all. Though I guess all my adorable juniors and friends are pretty yang-ish, so that helps balance it out."
2004608-133 = "Hmm, I should mention..."
2004608-134 = "...that invitation to join us, to join the Yin-Yang Club, that wasn't part of the act. That was real. What do you say?"
2004608-135 = "[s11] \"I'm always on my student's side, so...\"\n[s12] \"Balance, harmony, those are hard for me too.\""
2004608-138 = "Nyahaha! Good answer. An honest answer."
2004608-139 = "You're good with that, Sensei. You're good with that."
