[translation]
2004608-1 = "ปฐพีแหงนหน้า ผืนนภาก้มมอง"
2004608-2 = ""
2004608-3 = "คุณครู"
2004608-4 = "ฉันกะไว้แล้วค่ะว่ายังไงคุณครูก็ต้องมา"
2004608-5 = "ที่เฮียกคิยาโคของเรา"
2004608-6 = "[s] \"วางแผนอะไรไว้อีกเนี่ย?\""
2004608-7 = "เปล่าค่ะ ไม่มีแผนการอะไรหรอกค่ะ ก็แค่โอกาสมาถึง แล้วฉันก็แค่คว้ามันไว้"
2004608-8 = "ถ้าให้พูดตรงๆ ก็คงดูไม่สง่างาม... แต่ถ้าไม่อยากให้อ้อมค้อม ก็คงต้องบอกว่า"
2004608-9 = "ฉันจะพิชิตคิโวทอสค่ะ♪"
2004608-10 = ""
2004608-13 = "ฟังดูไม่สมจริงเหรอคะ? แต่ฉันก็เตรียมตัวมาอย่างดีเลยนะคะ"
2004608-14 = "ที่บอกกันว่า... ชมรมหยินหยางเป็นผู้นำเฮียกคิยาโคไม่ได้"
2004608-15 = "ชมรมหยินหยางไม่มีอำนาจที่แท้จริง..."
2004608-16 = "แม้แต่คณะกรรมการวินัยเกเฮนน่าที่แข็งแกร่งก็ยังเชื่อแบบนั้นเลยค่ะ"
2004608-17 = "ว่าแต่คำพูดแบบนั้นมีที่มาจากไหน~? แล้วใครเป็นคนเริ่มพูดก่อนนะ~?"
2004608-18 = "อะฮ่า~ ฉันเองละค่ะ"
2004608-19 = ""
2004608-21 = ""
2004608-22 = ""
2004608-23 = "ถ้าเราซ่อนฝักดาบ คนอื่นก็จะยิ่งระแวงดาบที่มองไม่เห็น"
2004608-24 = "แต่ถ้าทำให้คนอื่นเห็นฝักดาบ เราก็ยิ่งซ่อนมีดสั้นที่อยู่กับตัวได้มากขึ้นค่ะ"
2004608-25 = "เพราะอย่างนี้ฉันถึงมีอำนาจแข็งแกร่งที่ไม่มีใครรู้ แม้แต่คุณครูของชาเล่ต์เองก็ตามค่ะ"
2004608-26 = "ในเมื่ออำนาจของเฮียกคิยาโคมาอยู่ตรงนี้แล้ว ไม่ว่าจะมีอะไรรออยู่ปลายทาง ไม่ว่าจะมีใครขวางอยู่ ก็หยุดฉันไม่ได้หรอกค่ะ"
2004608-27 = ""
2004608-29 = ""
2004608-32 = ""
2004608-35 = ""
2004608-38 = ""
2004608-39 = "ทั้งเกเฮนน่ากับทรีนิตี้ที่ยุ่งอยู่กับการทะเลาะกันเอง ทั้งคนประหลาดแห่งมิลเลเนียมที่ไม่มีรากเหง้า"
2004608-40 = ""
2004608-46 = "ไหนจะมังกรดำที่ปิดประตูเพราะกลัวพายุ ส่วนหมีแดงก็เป็นฝูงชนอลหม่านไร้ความสมัครสมานสามัคคี"
2004608-47 = "ส่วนวัลคิรี่ ฉันคิดว่าพวกนั้นไม่มีค่าให้ต้องเอ่ยถึงด้วยซ้ำค่ะ"
2004608-48 = ""
2004608-51 = ""
2004608-52 = "ศัตรูคนเดียวที่ฉันต้องเผชิญตอนนี้ก็คือสภานักเรียน... ไม่สิ ถ้าจะพูดให้ถูกละก็"
2004608-53 = ""
2004608-55 = ""
2004608-56 = "ตายจริง น่าจะมีแค่คุณครู [USERNAME] จากชาเล่ต์คนเดียวนะคะ?"
2004608-57 = "[ns] \"นิยะ\""
2004608-58 = "อุ้ย~ ทำหน้าตาน่ากลัวอีกแล้วนะคะ~ แต่ก็อย่ากังวลไปเลยค่ะ เด็กสาวคนนี้ไม่กล้าท้าคุณครูสู้หรอกค่ะ"
2004608-59 = "การสู้กับศัตรูแล้วชนะเป็นวิธีปกติ แต่การชนะโดยไม่ต้องต่อสู้คือวิธีที่ดีที่สุดค่ะ"
2004608-60 = "ฉันเฝ้าดูความสามารถของคุณครูอย่างใกล้ชิดมาตลอดค่ะ ถ้าไม่จำเป็นฉันก็ไม่อยากเผชิญหน้ากับ#nคุณครูหรอก"
2004608-61 = "ถึงจะเป็นข้อเสนอที่ซ้ำซากไปหน่อย แต่คุณครูจะร่วมมือกับฉันมั้ยล่ะคะ? ฉันจะไม่ปฏิบัติกับคุณครูแย่ๆ แน่นอนค่ะ"
2004608-62 = "[ns1] \"นิยะ ครูมีเรื่องที่อยากบอกจริงจัง\"\n[ns2] \"ครั้งนี้ใช้เวลานานแน่ ตั้งใจเข้าละ\""
2004608-65 = "คุณครูจะ... ปรับทัศนคติฉันเหรอคะ? อุตส่าห์มาตั้งไกลขนาดนี้เนี่ยนะ?"
2004608-66 = "หรือว่ามันกะทันหันมากจนคุณครูไม่ค่อยเข้าใจคะ?"
2004608-67 = ""
2004608-69 = ""
2004608-70 = "ตอนนี้ความสัมพันธ์ระหว่างฉันกับคุณครูไม่ใช่แค่ครูกับนักเรียนแล้วนะคะ"
2004608-71 = "ถ้าเราไม่ได้เป็นคู่หูที่เท่าเทียมกัน ก็จะได้เป็นศัตรูที่ห้ำหั่นกันค่ะ"
2004608-72 = "และถ้าคุณครูเป็นศัตรูของฉันละก็..."
2004608-73 = "ฉันก็จะยิงปืนนี้โดยไม่ลังเลเลยค่ะ เริ่มจะรู้สึกว่าฉันเอาจริงหรือยังคะ?"
2004608-74 = "[s3] \"แต่ก็ไม่มีอะไรเปลี่ยนไปหรอก\"\n[s4] \"ครูเป็นครู และนิยะเป็นนักเรียนของครูเหมือนเดิม\""
2004608-77 = ""
2004608-80 = "[ns5] \"และครูก็ต้องสั่งสอนนักเรียนที่เลือกทางผิด\"\n[ns6] \"และครูก็มีหน้าที่อบรมนักเรียนที่เดินทางผิด\""
2004608-83 = "ดูจากท่าทีแล้วคุณครูก็ไม่น่าพูดโกหก... หรือว่าคุณครูหมายความแบบนั้นจริงๆ คะ?"
2004608-84 = ""
2004608-86 = ""
2004608-87 = ""
2004608-88 = ""
2004608-89 = "น่าผิดหวังนิดหน่อยนะคะเนี่ย~"
2004608-90 = ""
2004608-92 = ""
2004608-93 = ""
2004608-94 = "ท้าดา~"
2004608-95 = "คุณครูชอบการแสดงเซอร์ไพรส์ที่ฉันเตรียมไว้ให้มั้ยคะ? อะฮะฮ่า~"
2004608-96 = ""
2004608-98 = ""
2004608-99 = "จะให้เล่นตามบทไปด้วยก็ยากอยู่ใช่มั้ยคะ~?"
2004608-100 = "ก่อนอื่นฉันขอบอกก่อนค่ะว่ามันเป็นเรื่องโกหกทั้งหมดเลย"
2004608-101 = "แผนการพิชิตคิโวทอสเป็นเรื่องที่ฉันกุขึ้น ส่วนวิดีโอที่ให้ดูก่อนหน้านี้ก็ตัดต่อมาทั้งนั้นค่ะ"
2004608-102 = "ฉันไม่ได้จะก่อสงครามอะไรหรอกค่ะ รายได้หลักของเฮียกคิยาโคมาจากอุตสาหกรรมการท่องเที่ยว แล้วใครจะอยากมาเที่ยวในสนามรบล่ะคะ?"
2004608-103 = "แล้วทำไมฉันถึงโกหกน่ะเหรอคะ...?"
2004608-104 = "ง่ายๆ ค่ะ ก็คุณครูเป็นคนที่อ่านออกง่ายมากยังไงล่ะคะ"
2004608-105 = "ฉันเรียกให้คุณครูมาหาหลายครั้งแล้วค่ะ แล้วทุกครั้งคุณครูก็ตอบรับอย่างจริงใจ โชคดีที่ปัญหาที่ฉันบอกว่ามีมันไม่ใช่ปัญหาใหญ่จริงๆ นะคะ~"
2004608-106 = "แต่ถ้าฉันมีเจตนาร้ายแล้วคิดจะหลอกใช้คุณครูที่ไม่รู้อะไรเลยละก็~ เรื่องราวก็น่าจะแตกต่างออกไป#nใช่มั้ยล่ะคะ~?"
2004608-107 = "ถ้าฉันตัดสินใจจริงๆ การสนทนาเมื่อกี้อาจจะเป็นเรื่องจริงก็ได้นะคะ"
2004608-108 = "[s] \"แต่นิยะไม่ได้ทำแบบนั้นนี่\""
2004608-109 = "อะฮะฮ่า~! ก็ใช่ค่ะ ฉันแค่สมมติให้ฟังน่ะค่ะ"
2004608-110 = "หรือว่าคุณครูคิดว่าฉันไม่กล้าคะ?"
2004608-111 = "คิดว่าอามาจิ นิยะ ไม่มีความสามารถในการทำแบบนั้นเหรอ~?"
2004608-112 = "[s7] \"ถ้าเป็นนิยะ ก็อาจจะทำได้ก็ได้\"\n[s8] \"ถึงจะทำได้ แต่ก็ไม่ได้ทำนี่นา?\""
2004608-115 = "ก็ถึงได้บอกว่าฉันสมมติให้ฟังยังไงล่ะคะ..."
2004608-116 = "ถ้าตั้งใจจริงขึ้นมาละก็ ชมรมหยินหยางก็คว้าอำนาจที่แท้จริงไว้ได้ค่ะ"
2004608-117 = "ถึงมันจะเป็นภัยต่อคิโวทอสก็ตาม แต่อย่างน้อยพวกฉันก็จะควบคุมชมรมน้อยใหญ่ในเฮียกคิยาโคได้#nตามใจค่ะ"
2004608-118 = "อย่าถามว่าเป็นไปได้หรือเปล่าเลยค่ะ ปัญหาน่ะอยู่ที่มัน 'เป็นไปได้' ต่างหาก"
2004608-119 = "[s9] \"ไม่เป็นไร ยังไงก็เป็นไปไม่ได้หรอก\"\n[s10] \"ครูไม่ห่วงหรอก ก็นิยะรักเฮียกคิยาโคนี่นา\""
2004608-122 = "อะฮ่า...?"
2004608-123 = "การที่ฉันรักเฮียกคิยาโค หมายความว่าฉันจะทำร้ายเฮียกคิยาโคไม่ได้งั้นเหรอคะ...?"
2004608-124 = "มันฟังไม่ขึ้นเลยนะ...?"
2004608-125 = "......"
2004608-126 = "อะฮะฮะฮ่า! นั่นสินะคะ นั่นคือจุดบอดที่ถูกต้องเลยค่ะ!"
2004608-127 = "โล่งใจขึ้นมาแล้วนะคะ ฉันรู้สึกเหมือนตัวเองเป็นคนโง่ที่พยายามทำตัวเหนือคุณครูเลยค่ะ"
2004608-128 = "คำตอบเหรอคะ? ค่ะ... ฉันน่าจะได้คำตอบเพียงพอแล้วค่ะ"
2004608-129 = "ฉันคิดว่าฉันควรเชื่อในตัวเองและคุณครูมากกว่านี้อีกหน่อยค่ะ"
2004608-130 = "เฮ้อ... พอมาคิดดู มันก็น่าอายจริงๆ เลยนะคะ ฉันเรียกคุณครูมาในเวลานี้เพื่อมาดูฉันสงสัยในตัวเอง และหาข้อสรุปให้ตัวเองซะงั้น..."
2004608-131 = "ถึงจะชอบพูดถึงศูนย์กลางและสมดุลหยินหยาง แต่ก็อย่างที่เห็นค่ะว่าฉันโอนเอียงไปทางหยินมากกว่า"
2004608-132 = "ถึงฉันจะหัวเราะอะฮะฮ่า~ เหมือนไม่เป็นอะไรอยู่บ่อยๆ แต่ถ้าได้เจอคนที่มีพลังหยาง ฉันก็แทบจะทรงตัวไม่ได้เลยค่ะ~ ไม่ว่าจะเป็นรุ่นน้องที่น่ารัก~ หรือเพื่อนๆ ก็เถอะค่ะ~"
2004608-133 = "แล้วก็..."
2004608-134 = "ข้อเสนอที่ฉันให้ไปเมื่อกี้... ฉันไม่ยกเลิกนะคะ? ว่ายังไงล่ะคะ อยากเข้าชมรมหยินหยางของพวกฉัน#nหรือเปล่า~?"
2004608-135 = "[s11] \"ครูอยู่ข้างนักเรียนเสมออยู่แล้ว\"\n[s12] \"ครูขอข้ามเรื่องยากๆ อย่างสมดุลหรือความกลมกลืนดีกว่า...\""
2004608-138 = "อะฮะฮะฮ่า~ ปฏิกิริยาของคุณครูไม่ทำให้ผิดหวังจริงๆ เลยนะคะ~"
2004608-139 = "ถ้าคุณครูว่าดี ฉันก็ว่าดีด้วยค่ะ~"
