[translation]
2005902-1 = "The Imp and the Villainess"
2005902-2 = "Later, Mutsuki arrived at my office."
2005902-4 = "Hello, Sensei?"
2005902-5 = "[s] \"You're certainly dressed up.\""
2005902-6 = "Yes. There's a good reason for that."
2005902-7 = "You see, a personal contact asked me to complete a job."
2005902-8 = "It involves me portraying a young lady from a wealthy family."
2005902-9 = "One with a terrible personality, in fact... You could say she's a bit of a villainess."
2005902-10 = "[s] \"Wh-What kind of job is this...?!\""
2005902-11 = "That's confidential. Non-disclosure agreements, and all that."
2005902-12 = "The point is... I wanted to practice on someone."
2005902-13 = "I'm such a good girl, so this could be difficult. Sensei... You'll help me out, right?"
2005902-14 = "[s] \"Yes! Leave it to me!\""
2005902-15 = "Kufufu. I knew you'd say that."
2005902-16 = "Now, shall we get started?"
2005902-17 = "..."
2005902-19 = "...!"
2005902-20 = "Ohoho..."
2005902-21 = "Ohohoho!"
2005902-22 = ""
2005902-23 = "Her vibe's completely changed...!"
2005902-24 = "Hey there. You! This lady is parched. Bring me a refreshment at once!"
2005902-25 = "What are you doing, standing and drooling with that slack jaw? Don't you know what kind of refreshment befits a lady such as I?"
2005902-26 = "[s] \"Sh-Should I get some tea...?\""
2005902-27 = "Ohoho, so you DO have a brain in that cute head of yours."
2005902-28 = "Now then. Fetch it at once."
2005902-29 = "...Before I lose my patience."
2005902-30 = "[s] \"Wow, Mutsuki. That really was quite villainous!\""
2005902-31 = "You. What are you blabbering about?"
2005902-32 = "I'll give you three seconds to leave my sight. And come back with some suitable tea!"
2005902-33 = "[s] \"I-I'll be right back!\""
2005902-34 = ""
2005902-39 = ""
2005902-40 = "[ns] \"Here you go!\""
2005902-41 = "This is..."
2005902-42 = "...oolong?!"
2005902-43 = "How dare you bring such low-brow tea to a lady like me. Is this some sort of joke?"
2005902-44 = "[s] \"But I only have oolong tea right now...\""
2005902-45 = "*sigh* That won't do. It seems you need correction. Let's punish you."
2005902-46 = "Now. Recline. You will be my chair."
2005902-47 = "[s] \"The office chair over there...should be more comfortable...\""
2005902-48 = "Droll. Boring. That will not suit a lady such as I."
2005902-49 = "So kneel down and serve as my chair. Now."
2005902-50 = "You should be honored. Not everyone's so lucky."
2005902-51 = "[s] \"U-Understood!\""
2005902-53 = "I dropped down quickly and became Mutsuki's chair."
2005902-55 = ""
2005902-56 = "Ohohoho! Serves you right!"
2005902-57 = "Now, how do you feel? Being nothing more than a toy, an object, for a lady much younger than you?"
2005902-58 = "Being humiliated while pinned under a little girl's butt!"
2005902-59 = "[s] \"I-I like it?\""
2005902-60 = "Huh? You're not uncomfortable?"
2005902-61 = "[s] \"Anything for a cute girl like you, Mutsuki!\""
2005902-62 = "..."
2005902-63 = "Pfft...!"
2005902-64 = "Hahaha!"
2005902-65 = "Oh, Sensei! Hahaha! It's so funny, I can't play along anymore!"
2005902-66 = ""
2005902-68 = ""
2005902-69 = ""
2005902-70 = "[ns] \"Huh? Is it over?\""
2005902-71 = "Kufufu. Don't tell me you wanted to keep going?"
2005902-72 = "Or would you prefer we up the intensity? Should I accessorize with a riding crop or a whip?"
2005902-73 = "Sensei, how would you like a good spanking?"
2005902-74 = "[s] \"W-Well...!\""
2005902-75 = "Hahaha. Just kidding. We don't need to do that."
2005902-76 = "So, that's my character!"
2005902-77 = "How was I? Did I really seem like a villainess? Did you buy it?"
2005902-78 = "[s] \"Yes. I was following your orders without even thinking!\""
2005902-79 = "Hahaha! It was really funny to see you all startled, Sensei."
2005902-80 = "Ah. I'm thirsty from laughing so much. Do you have anything to drink?"
2005902-81 = "[s] \"How about oolong tea, my lady?\""
2005902-82 = "Oh, is this the same one from earlier?"
2005902-83 = "Kufufu, sure. Why not? I like oolong."
2005902-86 = "Ah, that's refreshing!"
2005902-87 = "Mutsuki and I chatted for a while afterward."
2005902-88 = "For some reason... Mutsuki's posh \"ohohoho\" was stuck in my head."
2005902-89 = ""
2005902-91 = ""
2005902-92 = "Ohohoho...!"
2005902-93 = ""
2005902-95 = ""
