[translation]
2005103-1 = "#title;씩씩해 레이사"
2005103-2 = "3;레이사 매지컬;00;선생님!! 이쪽입니다!!\n#3;a\n#3;em;[반응]"
2005103-3 = "[s] \"안녕, 레이사!\""
2005103-4 = "3;레이사 매지컬;03;후후, 순찰 돌기 딱 좋은 날씨입니다!\n#3;jump"
2005103-5 = "3;레이사 매지컬;02;그런데 선생님, 그 커다란 배낭은……."
2005103-6 = "[s1] \"증거품 수집용 가방이란다!\"\n[s2] \"꽉 채우기 전까지는 계속 순찰이야!\""
2005103-9 = "3;레이사 매지컬;03;선생님이 역시 최고예요!!!\n#3;hophop"
2005103-10 = "3;레이사 매지컬;09;그러면, 순찰 시작합니다앗!!!\n#3;em;[음표]"
2005103-12 = "4;레이사 매지컬;01\n#4;al\n#wait;1000"
2005103-13 = "4;레이사 매지컬;09;<마법리버> 아크릴 키링입니다!!\n#4;em;[!]\n#4;jump"
2005103-14 = "4;레이사 매지컬;00;3기 11화에 나왔던 사복 버전이군요!!"
2005103-15 = "4;레이사 매지컬;23;선생님!\n#4;em;[반응]\n#4;m3"
2005103-16 = "[s] \"음! 종류별로 확보해야겠군!\""
2005103-17 = "4;레이사 매지컬;03;완전 동의합니다!\n#4;em;[음표]"
2005103-19 = "2;레이사 매지컬;17;이번에는 파일 홀더입니다!\n#2;a\n#2;em;[!]"
2005103-20 = "[s] \"공부할 때 필요하니 아주 탁월한 구매겠구나!\""
2005103-21 = "2;레이사 매지컬;15;우헤헤-!\n#2;em;[반짝]\n#2;m3"
2005103-22 = "2;레이사 매지컬;15\n#na;???;저기요~"
2005103-23 = "#st;[0,0];instant;1;"
2005103-25 = "2;레이사 매지컬;02\n#2;em;[?]\n#wait;1500"
2005103-26 = "2;레이사 매지컬;02\n#2;d\n#wait;1000"
2005103-27 = "3;백귀야행 모브 관람객 A;01\n#3;a\n#wait;1000"
2005103-28 = "3;백귀야행 모브 관람객 A;02;혹시 사진 한 장, 같이 찍어도 될까요?"
2005103-29 = "3;레이사 매지컬;04;네?!\n#3;shake\n#3;em;[?!]"
2005103-30 = "3;레이사 매지컬;04\n4;백귀야행 모브 관람객 A;03;의상이 너무 잘 어울리셔서 그러는데, 괜찮다면…….\n#4;a\n#3;m2"
2005103-31 = "3;레이사 매지컬;16;어, 으…… 으아…….\n#3;stiff"
2005103-32 = "#st;[0,0];instant;1;"
2005103-34 = "4;백귀야행 모브 관람객 A;03\n3;레이사 매지컬;16\n#3;h\n#4;h\n#3;dl\n#wait;1500"
2005103-35 = "4;백귀야행 모브 관람객 A;04;?!\n#4;em;[?!]"
2005103-36 = "[s] \"잠시만 기다려주세요, 하하…….\""
2005103-38 = "3;레이사 매지컬;06;우우…….\n#3;em;[속상함]\n#3;a"
2005103-39 = "[s] \"괜찮니, 레이사?\""
2005103-40 = "3;레이사 매지컬;15;우헤…… 괜찮습니다 선생님.\n#3;stiff"
2005103-41 = "3;레이사 매지컬;20;사실, 사진을 같이 찍는 건 괜찮지만……."
2005103-42 = "3;레이사 매지컬;06;표정이나 몸짓이 어색할까 봐 걱정되어서 그렇습니다.\n#3;em;[세로선]"
2005103-43 = "3;레이사 매지컬;14;그래서 체육시간도 무섭습니다, 남들이 보기에 이상할까 봐……."
2005103-44 = "3;레이사 매지컬;06;으우, 그래도 아까 그 분께는 설명을 잘 드려야 했을까요.\n#3;em;[훌쩍]"
2005103-45 = "[s3] \"너는 마법소녀란다, 레이사.\"\n[s4] \"레이사가 하면 그게 마법소녀 포즈지!\""
2005103-48 = "3;레이사 매지컬;04;……!"
2005103-49 = "3;레이사 매지컬;17;과연, 마법소녀와 정의의 자경단은 항상 당당해야 하는데!\n#3;em;[!]\n#3;jump"
2005103-50 = "3;레이사 매지컬;23;선생님은 항상 대단하십니다!\n#3;hophop"
2005103-51 = "[s] \"그렇다면 다시 출동이다!\""
2005103-52 = "3;레이사 매지컬;00;네엡-!!!\n#3;em;[음표]"
2005103-53 = "2;관광객 A 놀이공원;01\n3;레이사 매지컬;03\n#2;a\n#3;a"
2005103-55 = "4;관광객 B 놀이공원;00\n2;관광객 A 놀이공원;01\n3;레이사 매지컬;03"
2005103-57 = "5;관광객 D 놀이공원;01\n1;관광객 C 놀이공원;01\n4;관광객 B 놀이공원;00\n2;관광객 A 놀이공원;01\n3;레이사 매지컬;10"
2005103-62 = "3;레이사 매지컬;02;선생님, 저기 보세요.\n#3;em;[반응]\n#3;a"
2005103-63 = "3;레이사 매지컬;09;굉장한 석양입니다."
2005103-64 = "[s] \"아아, 정말이구나.\""
2005103-65 = "3;레이사 매지컬;15;사실 오늘은 순찰보다는 그냥 구경하려고 핑계 댄 건데,\n#3;em;[재잘]"
2005103-66 = "3;레이사 매지컬;00;선생님께서 믿고 와주셔서 기쁩니다."
2005103-67 = "3;레이사 매지컬;03;항상 놀아주셔서, 감사합니다!!\n#3;jump\n#3;em;[!]"
2005103-68 = "[s5] \"자경단의 에이스가 평화를 지킨 거야!\"\n[s6] \"모두에게 미소를 선물했잖니!\""
2005103-71 = "3;레이사 매지컬;15;우헤헤, 선생님도 미소를 선물해 주시는 샬레의 슈퍼스타입니다!\n#3;em;[재잘]"
2005103-72 = "[s] \"그럼 샬레로 돌아가서 증거 분석이다!\""
2005103-73 = "3;레이사 매지컬;00;네!!!\n#3;em;[!]"
2005103-75 = "#na;(이후, 레이사와 샬레로 돌아갔다.)"
2005103-76 = "#na;(굿즈를 하나하나 다시 보며, 방금전의 추억에 젖었다.)"
