[translation]
2005705-1 = "ในจุดที่ยืนเคียงข้างกัน"
2005705-6 = "(คุณครูเดินทางไปยังสถานที่ที่นัดแนะกับอาคาเนะไว้)"
2005705-7 = "(ที่นี่เป็น... ห้องเรียนเปล่า... แปลกๆ... ที่ดูจะไม่มีใครอยู่เลย...)"
2005705-12 = "รู้มั้ยคะว่าฉันคือใคร?"
2005705-13 = "[s] \"?!?!?!\""
2005705-15 = "[ns] \"อะ... อาคาเนะ??!!\""
2005705-16 = "ค่ะ ใช่แล้วค่ะ"
2005705-19 = "เชิญเลยค่ะ คุณครู ฮุฮุ"
2005705-20 = "ตายจริง... ฉันทำให้คุณครูตกใจมากไปสินะคะ ขอโทษค่ะ"
2005705-21 = "[s1] \"ไม่เป็นไรหรอก แต่ห้องนี้มัน...\"\n[s2] \"ว่าแต่ห้องเรียนนี้ไม่มีใครอยู่เลยเหรอ? \""
2005705-24 = "ค่ะ ห้องเรียนนี้น่ะ..."
2005705-25 = "..."
2005705-26 = "ฉันจองไว้เพื่อใช้งานคนเดียวประมาณสองชั่วโมง ระหว่างนี้จะไม่มีใครเข้ามาหรอกค่ะ"
2005705-27 = "ตายจริง? ทำไมทำหน้าเหวอขนาดนั้นล่ะคะ?"
2005705-28 = "หรือว่า... ไม่เชื่อใจฉันเหรอคะ?"
2005705-29 = "[s] \"ไม่ใช่นะ! เชื่อสิ! ต้องเชื่อใจอยู่แล้ว! แต่ว่า...!\""
2005705-30 = "ใช่มั้ยล่ะคะ? ถ้างั้นก็คงไม่มีปัญหาอะไรใช่มั้ยคะ?"
2005705-36 = "แล้วฉันก็เชื่อใจคุณครูมากกว่าใครทั้งหมดด้วยค่ะ"
2005705-37 = "(เมื่อได้ยินเสียงที่เป็นมิตรของอาคาเนะ คุณครูก็ได้แต่พยักหน้าให้ช้าๆ...)"
2005705-40 = "เหตุผลที่ชวนคุณครูมาที่ห้องเรียนว่างๆ นี้น่ะเหรอคะ? คือว่า..."
2005705-41 = "อย่างที่ฉันบอกไปว่าพอคุณครูมาช่วยแนะนำฉัน ฉันก็เข้าหาและอยู่ร่วมกับเพื่อนคนอื่นได้ดีขึ้นค่ะ"
2005705-42 = "แต่ด้วยเหตุผลบางอย่าง... ฉันอยากจะถ่ายทอดมุมหนึ่งนั้นของฉันให้คุณครูได้เห็นด้วยวิธีที่พิเศษ#nออกไปหน่อย..."
2005705-43 = "[s3] \"แต่ว่า... ในห้องที่มีแค่เราสองคน มันน่าจะ...\"\n[s4] \"แต่ถ้าอยู่แค่สองคน ก็น่าจะทำให้เห็นยากหรือเปล่า?\""
2005705-46 = "ฉันไม่คิดอย่างนั้นค่ะ"
2005705-47 = "มีคำที่ว่าสิบปากว่าไม่เท่าตาเห็นไม่ใช่เหรอคะ?"
2005705-48 = "ฉันก็เลยคิดว่า... ต้องทำให้คุณครูสัมผัสถึงตัวตนนั้นของฉันได้ด้วยตัวเองค่ะ"
2005705-49 = "แล้วจะทำด้วยวิธีไหนน่ะเหรอคะ?"
2005705-50 = "ฮุฮุ"
2005705-54 = "คุณครู"
2005705-55 = "ตอนอยู่ในห้องเรียนนี้ คุณครูช่วย..."
2005705-56 = "เป็น 'เพื่อนร่วมชั้น' ของฉันให้หน่อยได้มั้ยคะ?"
2005705-60 = "[ns] \"!?!?!!!!!\""
2005705-63 = "(แล้วคุณครูก็ได้แสดงบทบาทสมมติเป็น 'เพื่อนร่วมชั้น' ของอาคาเนะ)"
2005705-64 = "(ในขณะที่กำลังกังวลว่านี่คือแนวทางการให้คำปรึกษาที่เหมาะสมสำหรับนักเรียนหรือเปล่า...)"
2005705-69 = "ทายซิ~ นี่ใครเอ่ย?"
2005705-70 = "[s] \"อาคาเนะ...?\""
2005705-71 = "อื้อ ใช่แล้วละ"
2005705-76 = "เป็นอะไรไปน่ะ?"
2005705-77 = "คุณ [USERNAME]?"
2005705-78 = "ก็อยากถามหลายเรื่องอยู่ แต่ขอถามเรื่องแว่นตาก่อนงั้นเหรอ?"
2005705-79 = "อืม~ จะเรียกว่าเป็นการเปลี่ยนภาพลักษณ์ได้มั้ยนะ? "
2005705-80 = "แต่ยังไงก็น่าน้อยใจนะ? พอไม่ใส่แว่นแล้ว คุณ [USERNAME] คิดว่าฉันกลายเป็นคนอื่นงั้นเหรอ?"
2005705-81 = "[s] \"ไม่ได้คิดอย่างนั้นเลยนะ\""
2005705-82 = "ฮุฮุ ขอบใจนะ"
2005705-83 = "ในคลาสเรียนเช้านี้น่ะ รู้มั้ยว่าฉันเจออะไรมา..."
2005705-86 = "(แล้วอาคาเนะก็เล่าเรื่องต่ออย่างสนุกสนานและเป็นธรรมชาติ)"
2005705-87 = "(จนคุณครูรู้สึกเหมือนตัวเองได้เป็นเพื่อนร่วมชั้นของอาคาเนะไปแล้วจริงๆ...)"
2005705-90 = "นั่นสินะ... ในเมื่อทำแบบนี้ได้ แล้วทำไมที่ผ่านมาฉันถึงพยายามรักษาระยะห่างโดยไม่รู้ตัวมาตลอดนะ?"
2005705-91 = "..."
2005705-92 = "ที่จริงแล้ว ตอนนี้ฉันก็ยังไม่มั่นใจขนาดนั้นหรอก"
2005705-93 = "ตัวตนที่มีชีวิตชีวาที่กำลังแสดงให้คุณ [USERNAME] เห็นตอนนี้ อาจจะเป็นตัวตนของฉันในอีก#nเวอร์ชั่นหนึ่งที่ฉันสร้างขึ้นมาเองก็ได้"
2005705-94 = "การสร้างภาพลักษณ์ของตัวเองขึ้นมา ในแง่หนึ่งก็เป็นเรื่องธรรมชาติไม่ใช่เหรอ...?"
2005705-95 = "ลึกๆ แล้ว... ฉันอาจกำลังกลัวอยู่ก็ได้"
2005705-96 = "[s] \"กลัวการที่คนอื่นจะได้รู้ตัวตนที่แท้จริงของอาคาเนะเหรอ?\""
2005705-97 = "จะว่าอย่างนั้นก็ได้... แต่อาจจะต่างออกไปนิดหน่อยน่ะ"
2005705-102 = "การที่ทุกคนได้รู้ว่าฉันเป็นใคร การที่ทุกคนได้รู้ 'ในสิ่งที่ฉันก็ไม่รู้มาก่อน'..."
2005705-103 = "การที่ฉันสามารถตอบสนองต่อความคาดหวังของคนอื่นได้"
2005705-104 = "แต่ถึงอย่างนั้น การค้นหาว่าฉันเป็นใครก็ยังเป็นงานที่พยายามแค่ไหนก็ไม่ได้คำตอบ"
2005705-107 = "ฉันน่ะ... คิดว่าตัวเองพอรู้วิธีพูดจาให้เหมาะสมกับสถานการณ์ อย่างเช่นเลือกใช้คำพูดอย่างระมัดระวัง เพื่อไม่ให้กระทบกระเทือนความรู้สึกของคนอื่น"
2005705-108 = "สำหรับเมดแล้ว นั่นก็เป็นคุณสมบัติที่สำคัญอย่างยิ่งเลยด้วย..."
2005705-109 = "แต่นั่นก็เป็นแค่สิ่งที่คนอื่นต้องการ ไม่ใช่การนำสิ่งที่อยู่ภายในตัวฉันออกมาแสดงให้เห็น"
2005705-110 = "แม้แต่ตัวฉันเอง ก็ยังไม่รู้เลยว่ามีอะไรอยู่ในใจกันแน่..."
2005705-111 = "เพราะแบบนั้นละ มันถึงได้รู้สึกว่างเปล่าเหลือเกิน ไม่ว่าฉันจะพูดคุยหรือใช้ถ้อยคำที่เหมาะสมกับ#nสถานการณ์มากแค่ไหน"
2005705-112 = "แต่ฉันก็ก้าวข้ามไปได้ไกลกว่านั้นไม่ได้เลย..."
2005705-113 = "ฉันรู้ว่าฉันที่เป็นคนสร้างกำแพงโปร่งใสนี้ขึ้นมาเอง... แต่จนถึงตอนนี้ ฉันก็ยังไม่รู้ว่าจะข้ามมันไปได้#nยังไง"
2005705-114 = "อย่างที่คุณ [USERNAME] บอกว่าฉันก็เริ่มเป็นฝ่ายเข้าหาคนอื่นก่อนบ้างแล้ว และฉันก็รู้สึกว่าบางอย่างกำลังเปลี่ยนแปลงไปทีละนิด..."
2005705-115 = "แต่ลึกๆ แล้วฉันอดคิดไม่ได้เลยว่า... สิ่งที่ทำอยู่เป็นเพียงแค่การแก้ปัญหาเฉพาะหน้าไปวันๆ เท่านั้นเอง"
2005705-119 = "ขอโทษนะ... คุณ [USERNAME]"
2005705-120 = "คุณอุตส่าห์ทุ่มเทเพื่อฉัน แต่ฉันกลับทำและพูดได้แค่นี้"
2005705-122 = "ฉันรู้สึกเหมือน... ตัวเองทำลายความพยายามทั้งหมดที่คุณ [USERNAME] ทุ่มเทให้#nจนสูญเปล่าไปหมดเลย"
2005705-126 = "ทำไมฉันถึงเป็นแบบนี้ตลอดเลยนะ..."
2005705-129 = "[ns] \"แต่ยังไงก็ขอบใจที่กล้าเปิดเผยเรื่องนี้ให้รู้นะ\""
2005705-130 = "...?"
2005705-131 = "ระ... เรื่องนั้น..."
2005705-132 = "ก็คุณ [USERNAME] เป็นคนพิเศษนี่นา..."
2005705-133 = "คนที่ฉันเปิดอกและบอกความในใจได้น่ะ..."
2005705-134 = "บางทีอาจจะมีแค่..."
2005705-135 = "คุณคนเดียวก็ได้..."
2005705-136 = "[s5] \"อื้อ งั้นเรามาทำให้มีคนแบบนั้นเพิ่มขึ้นกันเถอะนะ\"\n[s6] \"ถึงมันจะต้องใช้เวลานาน และจะต้องลำบากก็ตาม\"\n[s7] \"ที่จริงแล้วเรื่องแบบนั้นน่ะ ไม่ใช่อาคาเนะคนเดียวหรอกที่ไม่เก่ง\""
2005705-140 = "คุณ [USERNAME] เองก็ด้วยเหรอ...?"
2005705-141 = "..."
2005705-142 = "นั่นสินะ..."
2005705-143 = "พอมาคิดดูแล้ว คุณ [USERNAME] เองก็คงไม่ค่อยมีโอกาสทำแบบนั้นเท่าไรสินะ..."
2005705-144 = "[s] \"น่าซึ้งใจมากเลยที่อาคาเนะมาพูดแบบนั้นด้วยน่ะ\""
2005705-145 = "..."
2005705-146 = "ฮุฮุ"
2005705-147 = "รู้อะไรมั้ย บางทีฉันก็คิดแบบนี้นะ"
2005705-148 = "ถ้าเราได้พบกันด้วยวิธีที่แตกต่างออกไป ในช่วงเวลาที่แตกต่างออกไป และในความสัมพันธ์ที่#nแตกต่างออกไป"
2005705-149 = "ถ้าเป็นอย่างนั้น... เราจะใช้ชีวิตในรูปแบบไหนกันนะ"
2005705-150 = "[s] \"แต่ตอนนี้เราก็เป็นแบบนั้นอยู่ไม่ใช่เหรอ?\""
2005705-151 = "ฮุฮุฮุ"
2005705-152 = "นั่นสินะ ตอนนี้ก็เป็นอย่างนั้นเลย อื้อ ตอนนี้น่ะนะ"
2005705-153 = "..."
2005705-154 = "นี่ คุณ [USERNAME]"
2005705-155 = "[s] \"หืม?\""
2005705-156 = "ช่วยอยู่ตรงนั้นแบบนั้นอีกสักเดี๋ยวนะ"
2005705-160 = "(ในขณะที่กำลังจะเอ่ยปากถามว่าทำไม)"
2005705-164 = "นี่แหนะ♬"
2005705-165 = "[ns] \"!!??!!!!!??\""
2005705-166 = "(คุณครูรับรู้ได้ถึงความเป็น 'อาคาเนะ'  จากทุกประสาทสัมผัส...!)"
2005705-167 = "ชู่ว"
2005705-168 = "ถึงนี่จะเป็นห้องเปล่า แต่อาจมีใครเดินผ่านมาเห็นเราก็ได้นะ"
2005705-172 = "ขอบใจนะ คุณ [USERNAME]..."
2005705-173 = "ขอบใจที่ช่วยพูดแบบนั้นนะ"
2005705-174 = "แล้วก็ขอบใจที่ตั้งใจฟังเรื่องราวของฉันด้วย"
2005705-175 = "ฉันดีใจมากเลยละ"
2005705-176 = "อื้อ... จริงๆ นะ"
2005705-178 = "..."
2005705-179 = "[s] \"...\""
2005705-180 = "สวัสดีค่ะ คุณครู"
2005705-181 = "[s] \"อื้อ สวัสดี อาคาเนะ \""
2005705-184 = "― [log=아카네 교복]ฮุฮุ[/log][wa:310] "
2005705-187 = "― [log=아카네 교복]เป็นเรื่องที่น่าอาย[/log]"
2005705-189 = "― [log=아카네 교복]กว่าที่คิดอีกนะคะ[/log]"
2005705-192 = "― [log=아카네 교복]การซื่อสัตย์กับความรู้สึกของตัวเอง[/log][wa:3010] "
2005705-194 = "― [log=아카네 교복]ทำให้เราเองก็ยังต้องแปลกใจอยู่เสมอเลยนะคะ[/log][wa:220] "
2005705-197 = "[ns] \"กะ... ก็ปกติเราไม่ค่อยทำเรื่องแบบนี้บ่อยนักนี่นา...?\""
2005705-198 = "― [log=아카네 교복]ค่ะ เป็นอย่างที่คุณครูว่าเลยค่ะ[/log][wa:1010] "
2005705-201 = "― [log=아카네 교복]แต่สำหรับฉันแล้ว[/log]"
2005705-203 = "― [log=아카네 교복]นั่นคือสิ่งที่จำเป็นต้องทำค่ะ[/log]"
2005705-206 = "― [log=아카네 교복]ขออภัยที่รบกวนในหลายๆ เรื่องเลยนะคะ คุณครู [/log][wa:2260] "
2005705-209 = "― [log=아카네 교복]แต่ฉันก็คิดว่าการได้เจอคุณครู [/log][wa:4570] "
2005705-212 = "― [log=아카네 교복]คือโชคดีของฉันจริงๆ เลยค่ะ [/log][wa:2510] "
2005705-215 = "― [log=아카네 교복]ทุกอย่างจะผ่านไป[/log][wa:1650] "
2005705-217 = "― [log=아카네 교복]และบางอย่างจะถูกลืมค่ะ[/log][wa:10] "
2005705-220 = "― [log=아카네 교복]เรื่องที่เคยเกิดขึ้นที่นี่ก็อาจจะเป็นอย่างนั้นด้วย... [/log][wa:2120] "
2005705-223 = "― [log=아카네 교복]แต่ว่าฉันจะจดจำไว้ค่ะ[/log][wa:2970] "
2005705-225 = "― [log=아카네 교복]ต่อให้คุณครูจะบอกว่าลืมไปแล้ว[/log][wa:480] "
2005705-228 = "― [log=아카네 교복]สิ่งที่ล้ำค่าจะไม่มีวัน[/log]"
2005705-230 = "― [log=아카네 교복]เลือนหายไปแน่นอนค่ะ[/log]"
2005705-233 = "(แล้วอาคาเนะก็กลับไปอย่างไร้ร่องรอย)"
2005705-234 = "(เหมือนกับไม่เคยอยู่ในห้องนี้ตั้งแต่แรก)"
2005705-235 = "(คุณครูแอบสงสัยอยู่แวบหนึ่งว่าทั้งหมดนี้คือความฝันหรือเปล่า)"
2005705-236 = "(แต่สิ่งที่อาคาเนะทิ้งไว้ให้กำลังบอกอย่างเงียบๆ ว่าไม่ใช่ความฝันแต่อย่างใด...)"
