[translation]
2005303-1 = "Ninja Girl is Shy!"
2005303-2 = "Hyakkiyako Shopping District"
2005303-3 = "Your dress is ready, miss."
2005303-4 = "Oh...!"
2005303-5 = "Perfect...!"
2005303-6 = "You can't even spot where I tore it!"
2005303-7 = "That lady was a total pro. What amazing work!"
2005303-8 = "[s] \"I'm glad things worked out.\""
2005303-9 = "Fufu, but we can't end our outing like this!"
2005303-10 = "Give me one moment, Honorable Sensei! I'll be back in a flash!"
2005303-11 = ""
2005303-13 = ""
2005303-15 = "Five minutes passed..."
2005303-16 = "Honorable Sensei!"
2005303-17 = ""
2005303-18 = "Now, let's get moving!"
2005303-19 = "[ns] \"You changed into the dress?!\""
2005303-20 = "Fufu, of course."
2005303-21 = "Clothes, by nature, are meant to be \"practical\"..."
2005303-22 = "Meaning, in order to check her mending job, I should wear and evaluate the dress as early as possible, correct?"
2005303-23 = "[s] \"You have a point!\""
2005303-24 = "But! Just wearing it is not enough."
2005303-25 = "I need to try all sorts of poses in it."
2005303-26 = "And I should also walk, run, and try lifting heavy objects...!"
2005303-27 = "I need to see if the fix can hold up to my daily ninja tasks!"
2005303-28 = "[s] \"You're not entirely wrong...\""
2005303-29 = "Are you convinced, Honorable Sensei?"
2005303-30 = "Good! Because I have already conceived of the most efficient, optimal plan!"
2005303-31 = "As we walk down this alley, we'll pass shops selling all sorts of merch!"
2005303-32 = "Including...my favorite store! You may remember going there with me!"
2005303-33 = "Anyway, we will walk down that alley, finish shopping, and vacate!"
2005303-34 = "That should cover the walking, running, and lifting heavy objects requirements! All done in one go!"
2005303-35 = "And I also heard that some of these stores just got new ninja merch...uh, I mean ninjutsu TOOLS, right?"
2005303-36 = "Isn't that surprising? That means more people are becoming familiar with ninjas! We're a cultural phenomenon!"
2005303-37 = "[s] \"So that was your real goal!\""
2005303-38 = "Oh? You're still coming with me, right?"
2005303-39 = "[s] \"I didn't say that yet...!\""
2005303-40 = "As expected of Honorable Sensei! Let's get moving!"
2005303-41 = ""
2005303-43 = ""
2005303-46 = "Hyakkiyako Merch Shopping District"
2005303-47 = "Ultimately, Michiru dragged me through the shopping district."
2005303-48 = "Okay, now remember that we must stay focused!"
2005303-49 = "Sometimes these stores charge vastly different prices for the same stuff, believe it or not!"
2005303-50 = "So it's important to hone your mental fortitude. Memorize every tag you see so that we can compare the prices."
2005303-51 = "...Of course, this does not apply to ninja merch...no, ninjutsu tools."
2005303-52 = "Since their supplies are so small, and they are so rare and precious, there's no need to compare prices..."
2005303-53 = "But still... Hm?"
2005303-54 = "Found it! A matryoshka shuriken!"
2005303-55 = "See, it's a special shuriken that has a smaller shuriken inside!"
2005303-56 = "It's unblockable! Even if someone is quick enough to catch it after you throw it, another tinier shuriken will pop out and strike them in the face."
2005303-57 = "You may have seen this in Kaigenwoofwoof's early work. It's very historical."
2005303-58 = "And next to it is...a ninja flame smoke bomb!"
2005303-59 = "This pivotal ninjutsu tool shoots out flames instead of smoke once detonated, effectively attacking while obscuring visibility!"
2005303-60 = "[s] \"How is that different from an incendiary weapon...?\""
2005303-61 = "Oh, Sensei, there's no need to fret over such trivial things."
2005303-62 = "Okay, and here we have...the ancient ninja's hologram scroll?!"
2005303-63 = "They have something like THIS in stock?"
2005303-64 = ""
2005303-66 = ""
2005303-67 = ""
2005303-68 = ""
2005303-70 = "I followed Michiru and checked out ninja merch...no, ninjutsu TOOLS, for a while."
2005303-72 = "Nyaha... That was fun..."
2005303-73 = "Although the only one I could afford was the shuriken because I already spent so much money on mending the dress... "
2005303-74 = "But it was so much fun hanging out with you, Honorable Sensei."
2005303-75 = "And um..."
2005303-76 = "Thank you...for staying with me, Sensei..."
2005303-77 = "[s] \"Don't mention it! I had fun too.\""
2005303-78 = "R-Really...?"
2005303-79 = "Hee... Heehee..."
2005303-80 = "B-But still! It's a bit...embarrassing to let our outing end without a proper thank you!"
2005303-81 = "Here! "
2005303-82 = "[s] \"Isn't this...a capsule toy?\""
2005303-83 = "Yes, for you! I got it from a vending machine!"
2005303-84 = "...From the alley's one and only ninja capsule machine!"
2005303-85 = "Although I have no clue what's inside..."
2005303-86 = "...That's part of the fun, right? The surprise?"
2005303-87 = "Now then, shall we open it?"
2005303-89 = "...Eh?"
2005303-92 = "― [log=미치루 드레스]Inside, there's...a ring! What?![/log][wa:3930] "
2005303-94 = "― [log=미치루 드레스]I-Isn't it amazing with the shuriken decoration?! Whoa![/log][wa:3140] "
2005303-97 = "[ns] \"Should I try it on?\""
2005303-98 = "― [log=미치루 드레스]...Hm? Eh? Honorable Sensei? Are you putting it on...?[/log][wa:2780] "
2005303-100 = "― [log=미치루 드레스]N-No, it's not like it matters...![/log][wa:1210] "
2005303-103 = "― [log=미치루 드레스](Huh? Giving a ring to someone...?)[/log][wa:3360] "
2005303-105 = "― [log=미치루 드레스](Isn't this...like a confession?!)[/log][wa:2360] "
2005303-108 = "― [log=미치루 드레스]H-Hold on, Honorable Sensei![/log][wa:1050] "
2005303-110 = "― [log=미치루 드레스]This was definitely not intentional... I mean, well...![/log][wa:1670] "
2005303-113 = "[ns] \"Calm down, Michiru...!\""
2005303-114 = "― [log=미치루 드레스]Ugh, aaah...![/log][wa:2880] "
2005303-117 = "Th-Th-This is...!"
2005303-118 = "W-Well...!"
2005303-119 = "Y-Yah!"
2005303-120 = "*boom*"
2005303-121 = "[ns] \"...\""
2005303-123 = "By the time the smoke cleared, Michiru was gone."
2005303-124 = "And, for some reason, the toy ring from the capsule was on my finger."
