[translation]
2005603-1 = "像在自己家一樣"
2005603-2 = "（工作到中午左右時，按照約定響起了門鈴聲）"
2005603-6 = "[ns1] 「開著呢進來吧～」\n[ns2] 按下開門按鈕"
2005603-10 = "是～在～黑崎小雪，奉命前來！！"
2005603-11 = "今天我會成為老師的得力助手，什麼都交給我吧！"
2005603-12 = "……不過請不要讓我做太多破解密碼的工作！尼哈哈哈哈！！"
2005603-13 = "[s3] 「都好是都好……這身打扮是怎麼回事？」\n[s4] 「呃，是沒關係，但為什麼穿睡衣？」"
2005603-16 = "咦？……啊，這個嗎？"
2005603-17 = "……嗯？夏萊有什麼服裝規定嗎？"
2005603-18 = "啊，沒有特別規定嗎？尼哈哈哈！嚇我一跳還以為一開始就闖禍了……"
2005603-19 = "嗯，這身衣服只是比制服舒服所以才這樣穿的，真的沒有別的理由。"
2005603-20 = "身體舒服的話工作也會更順利吧？"
2005603-21 = "在研討會因為前輩們會嘮叨服裝所以沒辦法只好那樣穿……"
2005603-22 = "這邊的當值是一種幫忙或支援之類的吧？應該不用特別在意服裝吧？"
2005603-23 = "聽說有些學生穿泳裝或兔女郎服來的呢？有什麼問題嗎？"
2005603-24 = "[s5] 「那，那倒是沒錯……」\n[s6] 「你這樣說的話，確實無話可說……」"
2005603-27 = "尼哈哈哈哈！！看吧看吧？就是這麼回事！"
2005603-28 = "那麼，在開始幫老師做事之前……"
2005603-32 = "嘿咻……！"
2005603-33 = "[ns7] 「……小雪同學？」\n[ns8] 「你該不會打算鋪野餐墊躺下來吧？」"
2005603-36 = "……有什麼問題嗎？"
2005603-37 = "你問我在做什麼？那當然是……準備工作啊？"
2005603-38 = "我會躺在這裡，有什麼事就丟給我。我會全部做好然後原封不動地還給你！"
2005603-42 = "……老師。"
2005603-43 = "沒什麼嗎？尼哈哈哈！真是冷淡呢。"
2005603-44 = "好，那麼姿勢也都擺好了……"
2005603-45 = "……開始吧！！今天的工作！！"
2005603-47 = "（之後和在地上打滾的小雪一起開始了當天夏萊的工作）"
2005603-48 = "（小雪乍看之下姿勢很不認真地滾來滾去做事……）"
2005603-52 = "（……但令人驚訝的是，就像他自己說的那樣，真的是瞬間就把工作做完還回來了）"
2005603-58 = "[ns9] 「這樣就是最後一個了。」\n[ns10] 「真厲害。比預期的做了更多呢。」"
2005603-61 = "尼哈哈哈哈！！所以說了嘛？什麼都交給我就好！說到做到～"
2005603-62 = "……咦？什麼？"
2005603-63 = "研討會的工作情況？嗯……"
2005603-67 = "……不可能？哎，別說這種不可能的話……"
2005603-68 = "[s11] 「嗯，我有預感會這樣……」\n[s12] 「有什麼不一樣？」"
2005603-71 = "有什麼不一樣……當然不一樣囉？研討會的辦公室很不舒服呢。"
2005603-72 = "不能躺在地上，衣服也要穿得像正裝一樣的制服……"
2005603-73 = "中途想睡也不能睡，吵鬧會被罵，零食也不太能吃……"
2005603-74 = "說實話在那種工作環境下能有效率才奇怪吧？不是嗎？"
2005603-75 = "嗯……前輩們說因為會有人來訪，該守的規矩還是要守。"
2005603-76 = "那來訪的人也一起不守那些「規矩」不就好了嗎……"
2005603-77 = "……雖然這樣說了，但果然從來沒被採納過！尼哈哈哈哈！！"
2005603-78 = "[s13] 「……原來如此，我懂了。」\n[s14] 「感覺更了解小雪了呢。」"
2005603-81 = "咦～？什麼啊？突然說這種奇怪的話……！"
2005603-82 = "……尼哈。"
2005603-83 = "總之……能幫到老師感覺挺開心的！"
2005603-84 = "那麼今天的工作全部結束了嗎？要關店了嗎？嘎啦嘎啦～"
2005603-85 = "如果沒有其他想要交代的事情，我就先告辭了！"
2005603-86 = "趁著今天的好印象趕快撤退，稍微賺點分數什麼的！"
2005603-87 = "[ns15] 「……啊，小雪。等一下。」\n[ns16] 叫住準備離開的小雪"
2005603-90 = "嗯？老師……？怎麼了？"
2005603-91 = "……是？"
2005603-92 = "咦，可以留下來過夜嗎……？"
2005603-93 = "咦。但那樣的話前提就不一樣了……會不會給老師添麻煩……？"
2005603-94 = "完全不會嗎？時間晚了現在送你走反而比較讓人擔心……？"
2005603-95 = "[s17] 「你辛苦了嘛。我會跟研討會說的。」\n[s18] 「這裡有遊戲機什麼的，你可以隨便玩。」"
2005603-98 = "咦……"
2005603-100 = "……！！！！！"
2005603-101 = "遊……戲機……！！！"
2005603-102 = "尼哈哈哈哈哈哈！！沒辦法呢！！果然老師也挺無聊的吧！？"
2005603-103 = "你都這樣說了我也不好拒絕！剛好今天又穿著睡衣！準備萬全！"
2005603-104 = "走吧老師！休息室的遊戲機和零食都在等著我們呢！！"
2005603-105 = "[s19] 「態度突然變了！」\n[s20] 「全部都是我準備的耶……」"
2005603-108 = "尼哈哈哈哈！！小事小事別在意！"
2005603-109 = "走吧老師！夜晚還很長呢！！"
2005603-110 = "It's show time～!!!"
2005603-112 = "（之後和小雪一起在休息室玩遊戲度過了剩餘的時間）"
2005603-113 = "（小雪擺出一副要通宵的氣勢……）"
2005603-117 = "（果然不出所料，撐不到兩個小時就睡死了）"
