[translation]
2005405-1 = "Safe Operation"
2005405-2 = "[ns] \"Another day has passed us by...\""
2005405-5 = "Did you enjoy your dinner?"
2005405-6 = "[s] \"Well, it wasn't bad, but...\""
2005405-7 = "Hmm? Oh, I see... So you're saying it wasn't good, but it wasn't exactly bad either..."
2005405-8 = "Well, since we're rotating through a limited selection of frozen meals, I think it's only natural to find them a bit...dull."
2005405-9 = "They say that even an objectively delicious combat ration is destined to grow unappetizing after a while. I'd hate for you to grow bored."
2005405-10 = "Well then, Sensei. Let's fix that. First, please take this anti-nausea medicine."
2005405-11 = "[s1] \"Thanks. I get pretty motion sick!\" \n[s2] \"Oh, I should be fine. I have a strong stomach.\""
2005405-12 = "Fufu. As your life support, as one who's always fully prepared for anything..."
2005405-13 = "...It wouldn't hurt you to fall for me a little more."
2005405-14 = "Still, there's always a one-in-a-million chance. Isn't there, Sensei?"
2005405-15 = "You need to take care of yourself. If you fall ill, Sensei... I'll be the one ending up worried. You don't want that, do you?"
2005405-21 = "Well then, Sensei?"
2005405-22 = "Shall we start the performance test?"
2005405-23 = "[ns] \"All right! Let's go!\""
2005405-26 = "[ns] \"Wahhhhh!\""
2005405-28 = "What do you think, Sensei? Should I kick it into high gear?"
2005405-29 = "[ns] \"Your motorcycle is amazing! So fast!\""
2005405-30 = "It's a WHEELCHAIR!"
2005405-31 = "[ns] \"Your wheelchair is amazing!!!\""
2005405-32 = "Hold on tight! Around my waist!"
2005405-33 = "My heart would break if you fell off and hurt yourself!"
2005405-34 = "[ns] \"Okay!!\""
2005405-41 = "Ah, that's so refreshing! I feel so much better now!"
2005405-42 = "So, how do you like my wheelchair?"
2005405-43 = "It shifted gears without shaking, and both rapid acceleration and sudden braking performed flawlessly."
2005405-44 = "Of course, there's no need for any of that with my safe driving—NO, I mean, safe mobility aid operation."
2005405-45 = "If I remove the limiters, I'll be able to go 0-60 mph in as little as 0.956 seconds."
2005405-46 = "[s] \"Please drive safely... Er, I mean, please OPERATE it safely!\""
2005405-47 = "Yes. Of course. This is hardly my first speed test."
2005405-48 = "Hm? Have I been working on this instead of sleeping at night?"
2005405-49 = "..."
2005405-50 = "Can you blame me? There's so little to do out here."
2005405-51 = "I suppose you could consider this both a test of the wheelchair's operational limits AND a reconnaissance mission."
2005405-52 = "Oh, really? You think Eimi, Toki, and our fleet of drones \"provide enough reconnaissance\"?"
2005405-53 = "..."
2005405-54 = "Well, sometimes even a mastermind genius needs real-time field experience!"
2005405-55 = "The field and analysis teams must understand each other's duties. Otherwise, we're bound to make misinformed decisions!"
2005405-56 = "[s] \"Yeah, I see...\""
2005405-57 = "And right here, right now..."
2005405-58 = "We can see things that we can't see anywhere else."
2005405-59 = "Of course, I'm sure the \"grand designers\" of this continent didn't intend to make it worth sightseeing."
2005405-60 = "But you know how things go in this world..."
2005405-61 = "Nothing is ever just about clear intentions and results."
2005405-62 = "Things like astrology, numerology, and symbolism...and perhaps things yet to be discovered..."
2005405-63 = "It's as if parts of the \"world\" are being revealed to us both openly and in secret."
2005405-64 = "That said, I don't think my research will be very applicable here."
2005405-65 = "[s] \"Why is that?\""
2005405-66 = "I suppose I should say it's because the \"laws of the heavens\" here are completely different from the ones I've studied."
2005405-67 = "The positions of the stars, the ways they move, and the formulas that govern them..."
2005405-68 = "In a sense, we've found a place that could truly be considered a new heaven and a new earth."
2005405-69 = "Of course, I could work on constructing a completely new unified astrological theory from scratch."
2005405-70 = "That would truly be quite enjoyable, but..."
2005405-71 = "I don't think there's much time for that, which is a shame."
2005405-75 = "― [log=히마리 결전]It's interesting.[/log][wa:140] "
2005405-77 = "― [log=히마리 결전]We can look up at the night sky like we could back at Millennium.[/log][wa:840] "
2005405-80 = "― [log=히마리 결전]But the stars shining here are a bit different from what we know.[/log][wa:2190] "
2005405-82 = "― [log=히마리 결전]It's a mysterious sensation...that I've had difficulty expressing with words.[/log][wa:1280] "
2005405-85 = "[ns] \"But to me, you feel even more mysterious, Himari.\""
2005405-86 = "― [log=히마리 결전]What...? [/log][wa:320] "
2005405-88 = "― [log=히마리 결전]Th-Thank you. I-I will take that as a compliment.[/log][wa:5750] "
2005405-91 = "― [log=히마리 결전]...Even if we're all under the same night sky,[/log][wa:10] "
2005405-93 = "― [log=히마리 결전]I suppose not everyone can understand each other.[/log]"
2005405-96 = "― [log=히마리 결전]But since we're at least all under that same sky,[/log][wa:1800] "
2005405-98 = "― [log=히마리 결전]it could serve as an opportunity for us to understand one another. [/log][wa:1510] "
2005405-101 = "― [log=히마리 결전]At least that's what I believe.[/log][wa:2650] "
2005405-103 = "― [log=히마리 결전]What about you, Sensei?[/log][wa:1690] "
2005405-109 = "How was it, Sensei? Today's...wheelchair operation."
2005405-110 = "[s3] \"It was definitely impressive.\"\n[s4] \"Let's go out again sometime!\""
2005405-113 = "Huh? O-Okay..."
2005405-114 = "To think that you'd suggest it first..."
2005405-115 = "Ahem."
2005405-116 = "Well then, Sensei?"
2005405-117 = "Let's head back. We have just enough time to take it slow...and arrive before anyone starts worrying."
2005405-120 = "The ride back, as Himari promised, was the epitome of safe driving...NO, safe \"operation.\""
