[translation]
2005903-1 = "The Imp and the Scalper"
2005903-2 = "That night, I went to the Black Market with Mutsuki."
2005903-3 = ""
2005903-7 = "This way, Sensei. Let's go!"
2005903-10 = "[ns] \"It's been a while since I've visited the Black Market Convenience Store.\""
2005903-11 = "I heard they've just stocked a new bomb. I'd love to add it to my collection."
2005903-12 = "Get this. It's a rainbow smokescreen. Not only is it fun, but it disinfects the area AND kills most household pests!"
2005903-13 = "All the mosquitos hiding in my room will not only taste the rainbow, but DIE in it!"
2005903-14 = "What do you think? Very practical, right?"
2005903-15 = "[s] \"Yeah! Should I get some as well?\""
2005903-16 = "Kufufu. So you like the idea, Sensei? Then let's stock up!"
2005903-17 = "It has a rainbow label, so it should stand out..."
2005903-18 = "...Huh?"
2005903-19 = ""
2005903-21 = ""
2005903-22 = ""
2005903-23 = "What's going on? It's not here. Where is...?"
2005903-24 = "[s] \"Not just the rainbow one, but ALL of them.\""
2005903-25 = "Are you looking for bombs?"
2005903-26 = "Sorry. The Helmet Gangsters bought 'em all."
2005903-27 = "[s] \"The Helmet Gang?\""
2005903-28 = "That's right. All we got left are fakes. They're...still intimidating, in a way."
2005903-29 = "But if you want, I can reserve some for you once we get a shipment in."
2005903-30 = "Of course, it'll cost you. Heh heh heh."
2005903-31 = "Hahaha, I'll pass."
2005903-32 = "Seems like a lot of trouble..."
2005903-33 = "Let's go, Sensei. This place is cleaned out."
2005903-37 = "Kufufu. And this smells like a case."
2005903-38 = "I think I'll just have to ask around. Let's see what's REALLY going on."
2005903-40 = ""
2005903-41 = ""
2005903-43 = ""
2005903-44 = ""
2005903-45 = ""
2005903-47 = "A short investigation ensued..."
2005903-49 = "I think the clerk was telling the truth. The Helmet Gang bought up all the bombs."
2005903-50 = "And, from the sound of it, they're selling them for way above retail."
2005903-51 = "A few students mentioned feeling fleeced. They didn't want to pay the markup, but they had to! Bombs are essential items."
2005903-52 = "At this rate..."
2005903-53 = "...We'll be living in a scalper's paradise. We can't allow that, Sensei."
2005903-54 = "[s] \"Bomb scalping, that's a new one...\""
2005903-55 = "Sensei! Let's find those scalpers!"
2005903-56 = "And I happen to have an idea!"
2005903-58 = "We met up a few days later..."
2005903-60 = "Helmet Gang Secret Warehouse"
2005903-61 = "It's almost time..."
2005903-62 = "Ha! I don't know what kind of sucker they are, but buyin' out ALL our bombs? What a windfall!"
2005903-63 = "Keep your guard up. It could be a trap."
2005903-64 = ""
2005903-66 = ""
2005903-67 = "Huh? They're here."
2005903-68 = ""
2005903-70 = ""
2005903-71 = "[ns] \"This way, my lady.\""
2005903-72 = ""
2005903-75 = "..."
2005903-76 = "Ooh, she looks like she's loaded...!"
2005903-77 = "Hey. Are you the buyer?"
2005903-78 = "[s1] \"Excuse me! Don't you know?\"\n[s2] \"This is the Lady Capella, of the Cappellini Family!\""
2005903-81 = "Cappellini Family...? You ever heard of 'em?"
2005903-82 = "You seem like a respectable lady. What do you need all these bombs for?"
2005903-83 = "Droll. Dull. Such a boring question."
2005903-84 = "What does it matter to you? I'll do with them as I please."
2005903-85 = "And all you need to do is take my money, hand over the goods, and crawl back into the sewer."
2005903-86 = "I-I suppose you're right."
2005903-87 = "Of course I am. Now, hand it over. I want to leave this DUMP as soon as possible."
2005903-88 = "Wow. We're really letting her talk to us like this?"
2005903-89 = "Tsk, shut it!"
2005903-90 = "Fine, just show us the money!"
2005903-91 = "Hmph. What suspicious little rats you are."
2005903-92 = ""
2005903-94 = ""
2005903-95 = "Butler [USERNAME]. Open the bag."
2005903-96 = "[s] \"Yes, my lady.\""
2005903-100 = ""
2005903-101 = "That's real cash, right?"
2005903-102 = "Of course it is. Don't tell me that someone of your...nature can't tell a knock-off from the genuine article?"
2005903-103 = "Eh, it might just be the top layer. Move it! Let me see for myself."
2005903-104 = "[s] \"Enough. It's our turn.\""
2005903-105 = "That's right. Now, listen clearly."
2005903-106 = "Show us the bombs you've brought. You can rifle your grubby paws all over my money once I see the merchandise."
2005903-107 = "Hmph. Fine."
2005903-108 = ""
2005903-110 = ""
2005903-113 = "They lifted a tarp, revealing crates upon crates of bombs."
2005903-115 = "Now, am I supposed to believe THESE are real? They sell decorative ones in the stores, you know."
2005903-116 = "Wh-what should we do?"
2005903-117 = "Let her check one."
2005903-118 = "A-All right! This way!"
2005903-119 = ""
2005903-121 = ""
2005903-122 = ""
2005903-123 = ""
2005903-124 = ""
2005903-125 = ""
2005903-126 = "Confirmed. There's nothing like the genuine article, is there?"
2005903-127 = ""
2005903-129 = ""
2005903-130 = "Kufufu. Sensei. They stacked them all in one place. This'll be easy."
2005903-131 = "Lots of explosives piled in a tiny little area. Is this ringing a bell?"
2005903-132 = "[s3] \"I see...\"\n[s4] \"Should I go hide somewhere safe?\""
2005903-135 = "I'll give you three seconds."
2005903-136 = "One, two..."
2005903-137 = "Hey! What are you two whispering about...?"
2005903-138 = "Three!"
2005903-139 = "Huh?"
2005903-140 = ""
2005903-144 = "A-Are you crazy?! That stuff's volatile! I-If you keep shootin'—"
2005903-145 = "Then we'll all...go...KABOOM!"
2005903-146 = "But who cares? It's about sending a message!"
2005903-147 = "Y-You! So you're really not here to buy the—?"
2005903-148 = ""
2005903-152 = "A-Ahh...! Run for it...!!"
2005903-153 = ""
2005903-159 = "Kufufu! And now, we've taken care of the Helmet scalpers and their pathetic excuse for a business."
2005903-160 = "I bet they'll never try to resell bombs again!"
2005903-162 = ""
2005903-163 = "Ahh, that was fun. It's so nice to apply my skills, enjoy my hobby...and I got to teach them a lesson!"
2005903-164 = "Right, Sensei?"
2005903-165 = "[s5] \"That's right, my lady.\"\n[s6] \"Now, you can continue your wholesome bomb collection.\""
2005903-168 = "Hahaha! Sensei! You make a funny butler!"
2005903-170 = "Once it calmed down, we tidied up the scene and left."
2005903-171 = "And I hoped all this mischief was over..."
