[translation]
201060-1 = "Episode 6;Return of the Superhuman"
201060-2 = "...I explained to the student claiming to be the General Student Council President everything that happened while she was gone."
201060-5 = "General Student Council Reception Room"
201060-6 = "...I see."
201060-7 = "So much happened while I was gone... I have no excuses."
201060-8 = ""
201060-10 = ""
201060-11 = "But not everything is adding up to me."
201060-12 = "I don't remember anything about this \"Shittim Chest\" you speak of. And I gave it to you?"
201060-13 = "It looks like an ordinary tablet to me."
201060-14 = "And let's say I did. The idea of a tablet, one that could easily be stolen, that grants full access to the Sanctum Tower's operating system is ridiculously unsafe."
201060-15 = "All it would take is one person with malicious intent to take hold of the Shittim Chest, and we would be facing an irreversible crisis."
201060-16 = "Don't you agree, Sensei?"
201060-19 = ""
201060-23 = "[ns] \"That's true...\""
201060-24 = "Likewise, the Staff of Shaqed, the other artifact that Rin mentioned, looks like an ordinary wristwatch to me."
201060-25 = "And above all, I wouldn't rely on mysterious artifacts of unknown origins and workings to resolve serious matters that would affect the whole of Kivotos."
201060-26 = "This supposed plan of mine is full of holes that I can't comprehend."
201060-27 = "So I believe some adjustments are necessary."
201060-28 = "[s] \"(Is this her angle? To shut down Schale?)\""
201060-29 = ""
201060-33 = "Everything I did, I did based on the document the General Student Council President left in her absence."
201060-34 = ""
201060-36 = ""
201060-37 = ""
201060-38 = ""
201060-39 = "If you really are her, then you would remember this, where you established both Schale and Sensei's appointment to their role."
201060-40 = "..."
201060-41 = ""
201060-43 = ""
201060-44 = "I can't deny that the signature on this document is mine."
201060-45 = "And Schale's accomplishments in Kivotos during my absence are nothing to scoff at. I've already read through the reports."
201060-46 = "And what I really read was that you worked hard to protect the students' autonomy and safety, without once abusing the authority granted to you. I have no intention of denying or rejecting Schale."
201060-47 = "More than anything, I owe you a huge thank you for all you did, on behalf of the General Student Council."
201060-48 = "[s1] \"What a relief...\"\n[s2] \"I was worried I was about to lose my job...\""
201060-51 = "Surely not. I'm not so inflexible that I'd just cast aside the savior of Kivotos because of my faulty memories."
201060-52 = ""
201060-54 = ""
201060-55 = "However..."
201060-56 = "Despite these faulty memories of ours, we'll need to speak more and come to an agreement together."
201060-57 = ""
201060-59 = ""
201060-61 = ""
201060-62 = "If you are the \"real\" General Student Council President..."
201060-63 = "Then why did you abandon your role and disappear without warning?"
201060-64 = "Where have you been this entire time? What were you doing?"
201060-65 = "Unfortunately, I don't think I have a satisfactory answer for you."
201060-66 = "I have clear memories of the last day I carried out my official duties before I—before the General Student Council President disappeared from the records."
201060-67 = "Just like any other day, I reviewed the documents on my desk, signed them, and left the office."
201060-68 = "But everything after that... It's like a thick fog takes over my brain."
201060-69 = "At some points, I wondered if I'd fallen into a coma without realizing it. But I eventually came to consciousness...only to find a completely different Kivotos from the one I'd known."
201060-70 = "And then I met you, who doesn't remember me at all."
201060-71 = "Your explanation is only confusing me more."
201060-72 = "I understand. I know this doesn't answer any of your questions."
201060-73 = "But it's because even I don't understand it myself."
201060-74 = "This world has always been an enigmatic puzzle..."
201060-75 = "If you think about all of the impossible problems and accidents that occur in Kivotos, my memory loss is a drop in the ocean."
201060-76 = "That's why I can't just remain floating in the water, regardless of what does or doesn't make sense."
201060-77 = "I have responsibilities to carry out as the General Student Council President."
201060-78 = "... ..."
201060-79 = "Rin, let's continue this conversation whenever we can."
201060-80 = "And I'll do my best to live up to the General Student Council President, until you can accept me."
201060-81 = "Even if it ends in you rejecting me entirely, I won't run away from my responsibilities."
201060-82 = ""
201060-84 = ""
201060-86 = ""
201060-87 = "How are you...saying the same words that she did...?"
201060-88 = "Now then, if you'll excuse me. I have an entire mountain of work to catch up on."
201060-89 = "Oh, and I'd like to extend the same invitation to you, Schale's Sensei. Please feel free to visit the General Student Council anytime if you wish to speak with me."
201060-90 = ""
201060-92 = ""
201060-98 = "General Student Council Regulatory Committee, Remote Meeting Room 2"
201060-101 = ""
201060-102 = "I apologize for having to make this request of you in our first meeting in so long..."
201060-103 = "But would you be willing to withdraw the Trinity Tea Leaves Distribution Regulations the Tea Party proposed last month, Ms. Nagisa?"
201060-104 = ""
201060-106 = ""
201060-107 = "I was all atwitter, wondering what the General Student Council President wished to discuss with me after her long absence..."
201060-108 = "However, I find myself rather disappointed. Our answer remains the same. As we told the Chief of the Regulatory Committee, we cannot."
201060-110 = "*sigh* You see—"
201060-111 = "This is a rather mild response from Trinity, in fact. This is the bare minimum to ensure our students receive their due share, as well as to streamline our distribution channels."
201060-112 = "We take pride in the care we put into growing and preserving our tea leaves, and these regulations ensure they're not underestimated by the market. We hope you can understand."
201060-113 = "Furthermore, it is to my understanding that the General Student Council does not possess the authority to intercede with ordinances from individual academy districts."
201060-114 = "Could there have been a shift in policy, without having notified us?"
201060-115 = "No, not at all. Of course, each district has the right to propose ordinances based on their needs, and the General Student Council respects such right."
201060-116 = "But please try to see my side of things. Trinity's tea leaves account for a significant share of Kivotos' supply, and demand caused prices to skyrocket once you cut off the city from that source."
201060-117 = "Take Red Winter Academy, who has to import all of their tea leaves. They've found themselves on the short end of the stick here."
201060-118 = "I did not realize that Trinity was responsible for the wellbeing of other academies."
201060-119 = "Actually, while we're on the topic, I just had a cup of the black tea the Tea Party sent to us."
201060-120 = "The freshness and sweet undernotes were innovative. Was it a new blend?"
201060-121 = ""
201060-123 = ""
201060-124 = "...How keen of you. Yes, this blend had a light touch of citrus oil."
201060-125 = "While I'm pleased to hear you enjoyed it, why the change in subject?"
201060-126 = "Well, I just couldn't help but feel that I really wanted a delicious dessert with that smooth cup of lady gray tea."
201060-127 = "For example, like a chocolate pie, generously topped with Red Winter's lingonberries."
201060-128 = "..."
201060-129 = "I was just imagining how Red Winter students would react, and speak of Trinity General School, if they were to try out a Trinity tea that pairs well with their fruits. "
201060-130 = "What do you think, Ms. Nagisa?"
201060-131 = "...I believe fine tea must be served with befitting dessert."
201060-132 = "I understand well what you are implying. I'll reconsider our current distribution regulations."
201060-133 = "That's all I ask. Thank you."
201060-134 = "Yes, of course. It's rather refreshing to share a conversation with another tea sommelier. It's been quite some time since I've split leaves on the nuances of tea."
201060-135 = "The next time you visit the Tea Party, I will treat you to our newest blend."
201060-136 = "I'll be counting down the days."
201060-139 = "Amidst the increase in criminal activity throughout the D.U. lately..."
201060-140 = "An internal investigation from the Defense Office claimed that Gehenna students were responsible for 50% of those incidents over the past few months."
201060-141 = "That said, the Deputy Chief of Defense reportedly sent an official letter to Gehenna requesting cooperation with the investigation but has not received a response yet..."
201060-142 = "Ms. Makoto, as the Chairman of Pandemonium Society, do you know anything about this matter...?"
201060-143 = ""
201060-145 = ""
201060-147 = "Kiheheh... It's a foolish question that's not even worth answering."
201060-148 = "Of course... "
201060-149 = "NOT!"
201060-150 = "..."
201060-151 = "Then would the Pandemonium Society be willing to provide the necessary personnel and resources to better manage criminal activity coming out of Gehenna?"
201060-152 = "Why are you asking that of US?"
201060-153 = "That's the Prefect Team's duty! In Gehenna, out of Gehenna, whatever! It's not the Pandemonium Society's business to keep students in check!"
201060-154 = "In other words, this whole issue is because of...Head Prefect Hina!"
201060-155 = "W-Wait a second. If what you say is true, then we can hardly continue entrusting administrative tasks to the Prefect Team, as you've requested in the past."
201060-157 = "...I see. I fully understand the situation."
201060-158 = ""
201060-160 = ""
201060-161 = ""
201060-163 = ""
201060-164 = "This really was all caused by Head Prefect Hina's incompetence!"
201060-165 = "P-President?"
201060-166 = "H-Huh...? Y-Yes, you finally get it."
201060-167 = "I can't believe I troubled our Chairman Makoto, who must be utterly overwhelmed by managing such an incompetent Head Prefect. I can't even begin to imagine the workload of a leader like yourself. I have no excuses."
201060-168 = "No need to apologize. I, the great Makoto, am a magnanimous figure! I do not discipline those who can reflect on their mistakes."
201060-169 = "Besides, I'm glad that the General Student Council President is someone who I can reason with, unlike a certain someone."
201060-170 = "Is there anything you need from the Pandemonium Society?"
201060-171 = "No, that was all. After all, Chairman Makoto, dealing with the Head Prefect must keep both your hands very, very full."
201060-172 = "I like the way you think!"
201060-173 = "That's right! Route all of those annoying problems to the Prefect Team, since they're the ones responsible for all that stuff in Gehenna!"
201060-174 = "I'll keep that in mind."
201060-175 = "Thank you, have a wonderful day."
201060-176 = ""
201060-178 = ""
201060-179 = ""
201060-180 = ""
201060-181 = "Deputy Chief of Defense. Contact Gehenna's Prefect Team and request their cooperation. Please share all of the data and suspect intel the Defense Office provided us."
201060-182 = "You have my approval for whatever supplies the Prefect Team may request. Send the invoice to the Regulatory Committee team in charge of Gehenna."
201060-183 = "Y-Yes...!"
201060-184 = "And a box of caffeine pills and digestive medicine to President Sorasaki. She'll appreciate them."
201060-187 = ""
201060-188 = ""
201060-189 = "What did you just say to me?!"
201060-190 = "What do you MEAN Morikoori's season-exclusive chocolate pudding won't be released in Red Winter?!"
201060-191 = "All I said was that the General Student Council is the WRONG place to be asking about a specific company's product release..."
201060-192 = "And you're even more wrong for calling the Transportation Office... What a pain."
201060-193 = "Huh? Aren't you in charge of dessert-related tasks in the General Student Council?"
201060-194 = "I saw you once! You were waiting in line at the Garubi pop-up store, so I drew the natural conclusion..."
201060-195 = ""
201060-197 = ""
201060-198 = "Th-That... Um. That was totally someone else?"
201060-199 = "Look, the point is, I can't do anything about pudding! So go ask someone else."
201060-200 = "Ugh! Did you think that the one and only Cherino would fall for such duplicity?"
201060-201 = "This is blatant discrimination! You look to undermine my authority by releasing pudding in other academies and not ours!"
201060-202 = "The Red Winter Office will utilize all possible means to protest the General Student Council until you solve this!"
201060-203 = "(This is seriously annoying.)"
201060-204 = ""
201060-206 = ""
201060-208 = "Do you mind if I interject my opinion here?"
201060-209 = "And you are...?"
201060-210 = "It has been a while, student council president of Red Winter Academy, head of beautification, Great Leader, head of physical education AND the catering department, and the Red Winter Academy's best epicure, Cherino. This is the General Student Council President."
201060-211 = "Your mustache is gleaming magnificently today, as usual. If it's not rude of me to ask, I can't help but to wonder what your mustache-care routine is."
201060-212 = ""
201060-214 = ""
201060-215 = "Ahem, you must feel the weight of authority from my perfectly groomed mustache. Very sharp, President of the General Student Council!"
201060-216 = "However, I unfortunately have no answer for your question! It's au naturel!"
201060-217 = "How very envious! I understand why so many Red Winter students sing high praises about your mustache, President Cherino."
201060-218 = "Anyways, I heard that the new, limited chocolate pudding from Morikoori is very sticky. It's a huge complaint actually, the mess it makes around your mouth when you eat one."
201060-219 = "Wouldn't countless students be devastated if your precious mustache were stained beyond repair...over pudding?"
201060-221 = "Th-That's true..."
201060-222 = "No! I refuse to give up! I've anticipated this limited-edition pudding for months now!"
201060-223 = "I'm sure this will do little to assuage your heavy disappointment, but I actually happen to have some of the limited-edition caramel pudding L'Oiseau Bleu released just a bit ago."
201060-224 = "Would this gift prompt you to be generous enough to let that evil corporation off the hook? Just this one?"
201060-225 = ""
201060-227 = ""
201060-228 = "L'Oiseau Bleu's caramel pudding...!"
201060-229 = "A-Ahem... At your request, I'll let this slide, General Student Council President!"
201060-230 = "But just this once!"
201060-231 = "Thank you for your understanding, Ms. Cherino."
201060-232 = ""
201060-237 = ""
201060-239 = "Momoka..."
201060-240 = ""
201060-242 = ""
201060-243 = "I-I have no clue what she's talking about! I've never been to a dessert pop-up store or anything like that!"
201060-244 = "Even if it's for a once-in-a-lifetime dessert that you love, you can't leave the office during work hours. As members of the General Student Council, we need to set an example for other students."
201060-245 = ""
201060-247 = ""
201060-248 = "(whisper) ...I'm meeting with some pastry company owners next week. I'll try to get you some samples."
201060-249 = ""
201060-251 = ""
201060-252 = "Really?!"
201060-256 = "Wow... The General Student Council President just got back, and she's knocking out all kinds of longstanding issues one by one."
201060-257 = "She's herding those egotistical academy leaders like they're docile lambs. What I wouldn't give to have that kind of charisma!"
201060-258 = "She was gone for too long, but I'm glad she's back."
201060-259 = "I agree. Seriously, no one can ever replace the President."
201060-262 = ""
201060-263 = "..."
201060-264 = "...This won't do."
201060-265 = ""
201060-267 = ""
201060-269 = "Next Episode;Pairing"
