[translation]
206-1 = "記號的世界"
206-4 = ""
206-5 = "……像這樣見面還是第一次吧。在下的名字是「戈爾孔特」。"
206-6 = "因為一些緣故，只能以這種形式問候閣下……#n還請原諒在下以背對狀態問好的無禮。除此之外在下別無他法……"
206-7 = "沒錯！沒錯！"
206-8 = "……是的。順帶一提，這位是代行在下身體的「轉印」。"
206-9 = "我們兩個是象徵彼此是「虛像」及「非現實」的夥伴，同時也是記號。"
206-10 = "沒錯！"
206-11 = "就像所有記號一樣，轉印和在下無法僅憑自己單獨存在。#n所謂的記號無論何時都蘊含由解釋所導出的「文本」。"
206-12 = "然而，這不僅僅是我們的問題。畢竟存在的一切都是記號。#n那才是我和轉印眼中的「世界」。"
206-13 = "只有記號和象徵的地獄，存在主義者的[ruby=Limbo]靈薄獄[/ruby]。"
206-15 = ""
206-16 = "比如……以自身的記號本身作為自己名字的黑色西裝人。"
206-17 = ""
206-19 = ""
206-20 = ""
206-21 = "以及將自己的「文本」為外型顯現的瑪艾斯托洛都是很好的例子。"
206-22 = "瑪艾斯托洛有兩顆頭……這個部分也能視為就連其對解讀「文本」的渴望也被讀取出來了。"
206-23 = ""
206-24 = "而那種事，對這個都市來說也是相同的。#n為何會是這樣的記號呢……"
206-25 = "……看著這片夜景，在下不禁這麼想。"
206-26 = "沒錯！"
206-27 = "至於閣下接下來將遇見的存在……是「記號」的變種。"
206-28 = "戲仿、致敬……或許能說是這些東西，卻又不僅止於此。"
206-29 = "要說的話這就是現代的都市傳說、怪談……或是原本不具意義、俗稱「Creepypasta」的故事自行到達「崇高」境界的罕見案例。"
206-30 = "換句話說，它們是不具備「神祕」和「恐怖」卻能活動的新的「崇高」。#n在無限重複中偶然孕育出的、擁有文本的稀有記號…… "
206-31 = "這是非常耐人尋味且必須被解釋的「記號」。"
206-32 = "因此，我稍微借用了一名偉大藝術家的作品名稱為其命名。"
206-33 = ""
206-34 = "其名為[ruby=The Library of Lore]無盡怪談圖書館[/ruby]。"
206-35 = "沒錯！"
206-36 = "其第一彈是戲仿……是呢，也許有點可笑。#n但換個方向思考，這也算是一個了不起的「記號」。"
206-37 = "玩偶的靈魂突然暴走的怪談。在這之後應該也會持續出現各種致敬的作品吧。 "
206-38 = "這只不過是圖書館資料庫的一部份。對老師來說，應該無法視而不見才對。"
206-39 = "這間圖書館的全貌尚未被掌握。然而正因無法掌握才有趣……可以這麼說吧。"
206-40 = "沒錯！！"
206-41 = ""
206-43 = ""
206-44 = ""
206-45 = "那麼老師，願幸運與你的道路相伴。#n老師會從那些記號中讀出什麼樣的文本……在下非常期待哦。"
