[translation]
208-1 = "The Show Must Go On"
208-3 = "They say that there used to be an animatronic that put on magic shows in another area of this amusement park."
208-4 = "They would have been quite popular at one point, performing all sorts of tricks in front of a large audience... "
208-5 = "But I wonder what's become of them now?"
208-10 = "...Ah. I see."
208-11 = "Now manifested as a Mimesis, that magician is probably still performing their show for an empty audience."
208-12 = "I don't know. Does art necessitate an audience? Is art really art if there's no one to observe it? "
208-13 = "In short, in a discussion of mass appeal and artistry, is so-called \"popular art\" considered a valid form of art?"
208-14 = "But of course!"
208-15 = "...Hahaha, very well. If it were Maestro or Black Suit, they might have tried to fish for another line of reasoning at this point... "
208-20 = "But all I have to say is this."
208-21 = "Even for performance without an audience... Or art without an observer..."
208-22 = "The show must go on!"
208-23 = "But of course!"
208-24 = "...That's all I have to say."
