[translation]
21040-1 = "Episode 4;On That Day, We Met a Girl"
21040-2 = "???"
21040-3 = "What the...?"
21040-4 = "Why aren't the robots still chasing us?"
21040-5 = "They were hot on our heels right up until we entered the factory!"
21040-6 = "I don't get what they're doing, but it works out great for us! Right?"
21040-7 = "I can't take this anymore! What did we do to deserve to be chased by robots?!"
21040-8 = "Calm down, Midori. The worst is behind us."
21040-9 = "This is your fault!"
21040-10 = "Never mind that. What even is this place?"
21040-11 = "Did the General Student Council restrict access to the ruins because they knew about the robots?"
21040-12 = "Actually, I was wondering if those robots could be some sort of secret weapon of the General Student Council."
21040-13 = "But...maybe that's a bit of a stretch."
21040-14 = "I think there's more to this. And..."
21040-15 = "Access denied. Access denied."
21040-16 = "Wh-What was that?"
21040-17 = "Where's that voice coming from?"
21040-18 = "Verifying subject identity. Saiba Momoi. Unqualified."
21040-19 = "What the...? How does it know my name?"
21040-20 = "Verifying subject identity. Saiba Midori. Unqualified."
21040-21 = "What's going on?"
21040-22 = "Verifying subject identity. \"[USERNAME] Sensei.\""
21040-23 = "..."
21040-24 = "Don't tell me..."
21040-25 = "Qualified. You have permission to enter, Sensei."
21040-26 = "Whoa!"
21040-27 = "What was that?! Have you been here before?!"
21040-28 = "No, Sensei looks just as confused as we do."
21040-29 = "Saiba Momoi and Saiba Midori recognized as \"students\" of Sensei. Access as companions...granted."
21040-30 = "Opening bottom door."
21040-31 = "Bottom door? Not...the one in front of us?"
21040-32 = "Wait. By bottom, does it mean...?"
21040-33 = "That can't be. It's just an ordinary floor."
21040-34 = "*clank*"
21040-35 = "Oh. It did mean that. W-We're falling!"
21040-36 = "Waaah!"
21040-37 = ""
21040-39 = "Momoi! Sensei! Aaaaahhhh!"
21040-41 = "..."
21040-44 = "Ugh..."
21040-45 = "*gasp* Momoi? Sensei?!"
21040-46 = "Ugh. I thought we were gonna die."
21040-47 = "Are you okay, Momoi? Where's Sensei...?"
21040-48 = "[s] \"I'm down here.\""
21040-49 = "Aaaah! Wh-What are you doing down there?!"
21040-50 = "What do you mean? Be grateful Sensei broke our fall."
21040-51 = "O-Oh. I guess I was so frazzled that I jumped to conclusions."
21040-52 = "I think you owe Sensei an apology for that one."
21040-53 = "Are you okay?"
21040-54 = "[s1] \"I'm doing pretty all right.\"\n[s2] \"I wouldn't mind staying down here.\""
21040-55 = "A-Anyway...thanks for your help."
21040-56 = "A-Anyway...thanks for your help."
21040-57 = "Luckily, we didn't fall as far as I thought we would. Huh?"
21040-58 = "..."
21040-59 = "What in the...?"
21040-60 = "Is something wrong, Momoi?"
21040-61 = ""
21040-62 = "Huh?!"
21040-69 = "A girl?"
21040-70 = "What's she doing down here? Is she asleep?"
21040-72 = "(poke) (poke) Nothing. It's almost like she's dead."
21040-73 = "Don't say that! I don't think this is a corpse. Take a closer look."
21040-74 = "She doesn't look injured. More like...destroyed."
21040-75 = "Really? Come to think of it, I guess she does kind of look like a mannequin.#nLet's see..."
21040-78 = "(poke) Hmm. Her skin is so soft. Oh, there are some letters here."
21040-79 = "AL-IS..."
21040-80 = "What's that supposed to mean? Is it supposed to be her name?"
21040-81 = "How would you pronounce that?"
21040-82 = "No, wait. That's not a letter. It's actually...AL-1S."
21040-83 = "R-Really?"
21040-84 = ""
21040-85 = "Who is this girl? And what's this place supposed to be?"
21040-86 = "Maybe we should ask her."
21040-87 = "If she wakes up, that is. Let's give her some clothes first. I feel bad leaving her like this."
21040-88 = "Wow, you really did bring an extra change of clothes. Wait! That's my underwear!"
21040-89 = "No, they're mine. The kitty face on the front is different."
21040-94 = "*rustle* Okay. All done."
21040-95 = "*be-beep beep*"
21040-96 = "Huh?"
21040-97 = "What was that noise?!"
21040-98 = "It sounded like some kind of alarm... Are there any robots nearby?"
21040-99 = "No... I think it came from her."
21040-100 = "What? Could it be...?"
21040-101 = ""
21040-102 = "Status update. Contact with approved subject detected. Dormant state deactivated."
21040-104 = ""
21040-105 = ""
21040-106 = "..."
21040-107 = "Sh-She opened her eyes!"
21040-108 = ""
21040-109 = "*whir*"
21040-110 = ""
21040-111 = "Circumstances unknown."
21040-112 = ""
21040-113 = "Attempting conversation. Please explain."
21040-114 = "Explain? You want to know what's going on?"
21040-115 = "That's what we were going to ask you! Who are you? What IS this place?!"
21040-116 = ""
21040-117 = "Sense of self, memory, and purpose not found. No data available."
21040-118 = "What does that mean? And...you're not going to attack us, are you?"
21040-119 = ""
21040-120 = "Negative. The offensive capabilities of this unit cannot be activated when in contact with an approved subject."
21040-121 = "Fascinating. Robotic citizens are common in Kivotos, but I've never seen one that looks like us."
21040-122 = ""
21040-124 = "What do we do now, Sensei?"
21040-125 = "[s3] \"Tell me what you mean by 'approved subject.'\"\n[s4] \"Who are you? And what is this place?\""
21040-126 = ""
21040-127 = "Answer not found. This is presumably the first occurrence of deep consciousness for this unit. Answer unknown."
21040-128 = ""
21040-129 = "Answer not found. This is presumably the first occurrence of deep consciousness for this unit. Answer unknown."
21040-131 = "Deep consciousness? What does that mean?"
21040-132 = "Hmm..."
21040-133 = "Factory basement... No clothes... Memory loss..."
21040-134 = "Heehee, I have a great idea."
21040-135 = "I...really don't like where you're going with this."
21040-136 = ""
21040-138 = ""
21040-139 = ""
21040-140 = "???"
21040-142 = "Millennium Game Development Department"
21040-143 = ""
21040-144 = ""
21040-145 = "???"
21040-147 = "What were you thinking?!"
21040-148 = "Why did you bring her to the club room?!"
21040-149 = ""
21040-150 = "Ugh! Don't choke me! I can't breathe! *cough*"
21040-151 = "I had no choice. I couldn't leave her there with all those scary robots..."
21040-152 = ""
21040-153 = "*munch*"
21040-154 = "Ah! That's my console! Don't put that in your mouth! Spit it out!"
21040-155 = "We couldn't leave her all alone."
21040-156 = ""
21040-157 = "I know that..."
21040-158 = "...but shouldn't we submit a report about her to the General Student Council or Valkyrie?"
21040-159 = "We can't do that. Not until our task is all done."
21040-160 = "What do you mean \"task\"?"
21040-161 = "Hmm. First, we should give her a name. How does \"Aris\" sound?"
21040-163 = ""
21040-164 = "Please confirm Aris as the designated name for this unit."
21040-165 = "W-Wait! You said her name was AL-1S. Where did you get \"Aris\" from?"
21040-166 = "Eh. The other thing would take too long to say, and it's not cute enough. Trust me—a dev knows best. What do you think, Aris?"
21040-167 = ""
21040-168 = "..."
21040-169 = ""
21040-170 = "Confirmed."
21040-171 = "Unit designation: Aris."
21040-172 = "Hahaha! See? Do I know how to pick a cute name or what?"
21040-173 = "Well, as long as she's fine with it."
21040-174 = ""
21040-175 = "Now, let's move on to the next step."
21040-177 = "You can't be serious. This isn't as simple as adopting a cat!"
21040-178 = "Think about it, Midori."
21040-179 = "Why did we risk our lives to get the G.BIBLE in the first place?"
21040-180 = "Huh? It was to make a good game so we can keep our club."
21040-181 = "Exactly."
21040-182 = "To keep our club, we have to meet one of two conditions."
21040-183 = "Making a good game and winning the Millennium Prize is just one of our options."
21040-184 = "But I thought you said it was the only way. After all, we've had no luck recruiting people to work on a retro game."
21040-185 = "Hold on..."
21040-186 = "Momoi. Don't tell me..."
21040-187 = "You're thinking of disguising her as a Millennium Student and having her join our club, aren't you?"
21040-188 = ""
21040-189 = "Aris!"
21040-191 = "You're one of us now!"
21040-192 = ""
21040-193 = "*munch*"
21040-194 = "That's my Game Girl Advance SP! It's the only 16-bit game console in Kivotos with an 8-core, 16-thread custom CPU capable of 8K resolution!"
21040-195 = ""
21040-197 = "*sigh*"
21040-198 = ""
21040-199 = "I hope this works out..."
21040-201 = "Next Episode;I, Aris..."
