[translation]
21070-1 = "Episode 7;Much Too Big to Be Called a Gun"
21070-2 = "Millennium Game Development Department"
21070-3 = "All students in Millennium—or well, Kivotos—have their own personal weapons."
21070-4 = "So, you'll need one too, Aris."
21070-5 = "And there's only one place that'll get you what you need on short notice."
21070-6 = "The Engineering Department."
21070-7 = "That is a new word. \"En...gineer...ing\"?"
21070-8 = "It's a club of experts who make and repair machines here at Millennium."
21070-9 = "Their members are called meisters."
21070-10 = "They do a bunch with machines in general and also handle remodeling the school's weapons..."
21070-11 = "So I betcha they've got some spare weapons lying around."
21070-12 = "All right, let's go!"
21070-14 = "Engineering Department Workshop"
21070-15 = "...I see."
21070-16 = "You want to get a better weapon for your classmate."
21070-17 = "Well, you've come to the right place."
21070-18 = "A competent student is nothing without an appropriate weapon."
21070-19 = "If you look to that corner there, you'll see some prototypes we've put together."
21070-20 = "It's all fair game, so help yourselves."
21070-21 = "Wow! Thanks a bunch, Utaha!"
21070-22 = ""
21070-23 = ""
21070-24 = "Uh, hi. I'm Hibiki, and, um, I'm a first year here... Let's find you something special."
21070-25 = "How about this?"
21070-27 = "Oh, a pistol."
21070-28 = "I get the feeling this girl, uh, doesn't have much combat experience. Am I right?"
21070-29 = "Negative. I have already saved humanity 27 times, defeated the demon king 46 times, and explored hundreds of dungeons."
21070-31 = "..."
21070-32 = "That's, uh, pretty prolific of you."
21070-33 = "Still, it seems like you're new to guns."
21070-34 = "In which case, a pistol is ideal. It has a light plastic frame, and there isn't much recoil.."
21070-35 = "It's a good starter gun, but there's something even better about it."
21070-36 = ""
21070-37 = "This model has a never-before-seen feature that—until recently—has never existed in the history of our school."
21070-39 = "Wh-What is it?"
21070-40 = "It sounds impressive. Please tell us."
21070-41 = "The new feature that will rock the world of firearms is... "
21070-42 = "Bluetooth."
21070-43 = "...Huh?"
21070-44 = "This pistol is the only one in the world that allows wireless music playback and file sharing via Bluetooth."
21070-45 = "It also functions as a digital car key, and can be used to tag into IC panels on public transit services."
21070-46 = "And to top it all off, if you enable the NFC feature, you can use it to make payments at convenience stores."
21070-47 = "Th-That's amazing."
21070-48 = "But imagine how the store clerk would freak out if you whipped out a pistol and said, \"I'll be paying with this!\""
21070-49 = "What do you think, Aris—wait, where did she go?"
21070-50 = "Oh, there she is."
21070-51 = "She's looking at...."
21070-52 = ""
21070-54 = "(stare)"
21070-55 = ""
21070-57 = "Is that...?"
21070-58 = "Heh heh. You have a good eye, customer."
21070-59 = "Who are you?"
21070-60 = "I'm Kotori, one of the Engineering Department's meisters and a master of explanations!"
21070-61 = "...?"
21070-62 = "And you must be Aris, the fourth member of the Game Development Department!"
21070-64 = "Oh, hello again, Kotori. What is this huge thing here?"
21070-67 = "It kind of looks like...a cannon."
21070-68 = "Excellent deduction, Midori. This here was produced using about 70 percent of the club's budget for the second half of the year..."
21070-69 = "Allow me to introduce our most ambitious project yet—a railgun fit for an intergalactic battleship!"
21070-70 = "An intergalactic b-battleship... That's nuts..."
21070-71 = "Didn't a lot of people get horrible colds when you tried making that cryo-sleep hibernation device?"
21070-72 = "Well, I mean, the Direct to Future Express is still in use today..."
21070-73 = "...but now as a refrigerator. We're sending the food into the far future, so it wasn't a complete failure."
21070-74 = "That's quite the name for a fridge!"
21070-75 = "The Engineering Department is going to develop an intergalactic battleship—right after some helicopters and general-purpose work robots!"
21070-76 = "This railgun is the beginning of that plan. A live-ammunition weapon developed for use in the vacuum of space! No one's ever attempted this in the history of Millennium!"
21070-77 = "When you put it that way, it gets me kind of excited!"
21070-78 = "Me too! If anyone can do it, it's our Engineering Department!"
21070-79 = "Heehee! You can count on us!"
21070-80 = "But, actually, we, uh... The whole plan is on ice for the time being."
21070-81 = "Why'd you hype me up just to shoot me down?!"
21070-82 = "Like usual, our problem is not a lack of imagination or passion, but one of budget."
21070-83 = "It took 70 percent of this semester's budget just to make this one gun. To make an intergalactic battleship, we're going to need a thousand times more..."
21070-84 = "Then why did you make this gun in the first place?!"
21070-85 = ""
21070-87 = "What a disappointing question, Momoi."
21070-88 = "It's simple, really. It's because...we love laser beams."
21070-89 = "*nod nod*"
21070-90 = "Well said, Utaha. I agree wholeheartedly of course. If Momoi can't appreciate laser beams, then she's surely a fool."
21070-91 = "I'm surrounded by idiots!"
21070-92 = ""
21070-93 = "By the way, the official name of this passion project is..."
21070-94 = "\"Supernova: The Sword of Light\"!"
21070-95 = "Another overblown name..."
21070-96 = "...!"
21070-97 = "The Sword of Light?!"
21070-98 = "Whoa! Look at Aris' eyes sparkle!"
21070-99 = "Wow! Incredible!"
21070-100 = "I-I've never seen her so excited."
21070-101 = "I...want it."
21070-102 = "...Huh?"
21070-103 = ""
21070-104 = "O great formers of steel, bequeath unto me the might of the dragon's breath."
21070-106 = "Uhhh... I'm glad to hear you're so...passionate."
21070-107 = "But we couldn't possibly fill that request!"
21070-109 = "But you said everything in this corner was fair game!"
21070-110 = "...We have our reasons."
21070-111 = "What reasons, though?"
21070-112 = "Is my level too low? What stats do I need to equip this weapon?"
21070-113 = "That's not really what I mean..."
21070-114 = "With matters like this, you have to be realistic."
21070-115 = "Ah. I knew it. This is about the money. "
21070-116 = "Don't worry, Aris. If I must, I'm willing to part with Midori's FlyStation."
21070-117 = "...That's not it either."
21070-118 = "What are we getting realistic about if the issue's not money?!"
21070-119 = "Don't get me wrong, the budget is something to be concerned about."
21070-120 = "However, there is something more pressing here....#nThis weapon is way too heavy-duty to be used as a personal weapon."
21070-122 = "By itself, the railgun probably weighs 140 kilograms. Add the optical accuracy device and battery...and that's almost 200 kilograms!"
21070-124 = "Hmm..."
21070-125 = "Exactly. We're all happy you're so interested in our creation, and were you able to actually handle it yourself, I imagine we could part with it."
21070-126 = "...?"
21070-127 = "Oh?!"
21070-128 = "Are you certain nothing beguiles your thoughts, technomage?"
21070-129 = "Huh? She's speaking weird again..."
21070-130 = "I-I think she wants to know if you're serious about what you just said."
21070-131 = "Of course I am. How about this, do you want to try holding it?"
21070-132 = "*nod*"
21070-133 = ""
21070-134 = "*scooches forward*"
21070-135 = "She who lifts this weapon on high..."
21070-136 = "...shall rule this land!"
21070-137 = "Haha! That's the spirit."
21070-138 = ""
21070-139 = "*grab*"
21070-140 = "Hup...!"
21070-141 = "B-Be careful. Don't hurt yourself... We really should have the crane over here to—"
21070-142 = ""
21070-143 = "Haaaaah!"
21070-144 = "Wha..."
21070-145 = "HUH?!"
21070-146 = "*woosh*"
21070-147 = "Hooray! I-I did it!"
21070-148 = "No...way..."
21070-149 = "Umm...So how does button layout work? Would this be the R trigger...?"
21070-150 = "W-Wait!"
21070-152 = "Blinding Light!"
21070-153 = ""
21070-155 = "*booooom*"
21070-156 = "Ahhh! The roof!"
21070-157 = "...Amazing."
21070-158 = "I will equip this to my weapon slot."
21070-159 = "W-Wait! Pick something else! We put so much of our budget into that one..."
21070-160 = "It's okay..."
21070-161 = "She should take it."
21070-162 = "Is that really okay, Utaha?"
21070-163 = "No one else can use it anyway."
21070-164 = "Hibiki, put together a shoulder strap and add some handles so Aris can carry it more easily."
21070-165 = "Can do."
21070-166 = "On the plus side, we're going to be able to collect a lot of good data from, uh, real combat scenarios."
21070-167 = "This is crazy. I feel like we just got a super rare item! Thanks guys!"
21070-168 = "Th-Thank you!"
21070-169 = "It's a little early to be thanking us."
21070-170 = "What now?"
21070-171 = ""
21070-172 = "Hibiki. Go get all those drones and robots we were going to throw out."
21070-173 = "...Okay."
21070-175 = "What's Utaha up to?"
21070-176 = "Ah! Maybe she's not going to let the railgun go so easily."
21070-177 = "You catch on quick."
21070-178 = "If you want that weapon..."
21070-179 = ""
21070-181 = "...you'll have to get through us!"
21070-182 = "Oh?!"
21070-183 = "S-Seriously?! I thought you said we could have it if she could lift it, Utaha!"
21070-184 = "W-We just wanted a weapon for Aris..."
21070-186 = "Were it any other weapon, I would happily let it go."
21070-187 = "But for this project, you need to earn my approval first."
21070-188 = "Wh-What does that mean?"
21070-189 = "I guess it's more of a qualification exam than a bid for approval."
21070-190 = "I don't understand... "
21070-191 = ""
21070-193 = "Combat drones and robots detected. Danger confirmed."
21070-194 = "Here they come!"
21070-195 = "Eeek!"
