[translation]
21090-1 = "Episode 9;Yuuka's Questions"
21090-2 = "Millennium Game Development Department"
21090-3 = "(Psst. Hey, Aris, if the Game Development Department is threatening you into staying here, blink your left eye.)"
21090-4 = "(blank stare)"
21090-5 = "What are you whispering about?! What are you trying to do to our Aris?!"
21090-6 = ""
21090-8 = ""
21090-10 = "Here, take a look at this pristine student ID! She's the real deal!"
21090-11 = "Hmm... I already confirmed that she's in the student registry and was issued a student ID card."
21090-12 = "But you're going to have to do better than that to satisfy me."
21090-14 = "(Ack!)"
21090-15 = "(I-Is she onto us?!)"
21090-16 = ""
21090-17 = "Enough preamble, let's begin the interrogation."
21090-18 = "She didn't even try to hide it that time..."
21090-19 = ""
21090-20 = "So, tell me, Aris, how did you come to join the Game Development Department?"
21090-21 = "Well, when I woke up, I was here... Wait, no, that is not right..."
21090-22 = "Momoi, can you please stop glaring daggers at us like that?"
21090-23 = "I, um... I wanted to play Castlemania, and then I heard there was a game club here..."
21090-24 = "Hmm... I see."
21090-25 = "(Nice! You're doing great, Aris!)"
21090-26 = "You said \"game club\" in your previous answer. As I'm sure you're aware by now, the Game Development Department doesn't exist solely to play games."
21090-27 = "If you're to be involved in development, what is your role here?"
21090-28 = "Tank and light-type melee fighter..."
21090-29 = "...What?"
21090-30 = "Whoops! I-I mean... I am a...p-p-pro...glamor!"
21090-31 = "You mean \"programmer\"?"
21090-32 = "Oh, yes, that one! I am the very picture of the perfect programmer."
21090-33 = "(She totally biffed it!)"
21090-34 = "I see... Programming is a difficult position."
21090-35 = "Oh, yes, it is tough being a p-programmer. Sometimes we die from working too much."
21090-36 = "Wh-What?!"
21090-37 = "But it is not actually that big of a deal!"
21090-38 = "DYING isn't a big deal?!"
21090-39 = "Yes! Usually, you just wake up at an inn or give money to the cathedral, and you are totally revived!"
21090-40 = "Huh...? Wh-What are you talking about?"
21090-41 = "Hm? It is common sense, really. Have you not played The Fable of Heroes or any of the games in the Brother series?"
21090-43 = "They are very good. You should give them a try."
21090-44 = "..."
21090-46 = "It's game over..."
21090-48 = "..."
21090-49 = "All right, I think we're done here."
21090-50 = "I think I understand exactly who Aris is now."
21090-52 = "(We're so screwed!)"
21090-53 = "(Wh-Wh-What do w-we do?!)"
21090-54 = ""
21090-56 = "Uh..."
21090-57 = "For one, I can tell you're an odd duck."
21090-58 = "But more than that, you're someone who likes to explore new worlds, work with your friends, and achieve new things..."
21090-59 = ""
21090-60 = "I have no doubt in my mind that you're a member of the Game Development Department."
21090-62 = "Wait, really...?"
21090-63 = "Then that means...?!"
21090-65 = "You've met the necessary requirements to maintain your status as an official club."
21090-67 = "Woohoo!"
21090-68 = "We did it!"
21090-69 = "S-So we keep the club room? Oh, and are we gonna get a budget?!"
21090-70 = "Of course."
21090-71 = "Well, until the end of the semester, that is."
21090-72 = "Wow! Wait...what?"
21090-73 = "Wh-What did you say?!"
21090-74 = "But we have enough people! What more do you want?!"
21090-76 = "Huh? Oh, I thought you already knew."
21090-77 = "Sure, the low member count was an issue, but you also need to produce some tangible results as a club."
21090-78 = "Of course, you get a grace period since these rules just changed recently."
21090-79 = "However, if you can't produce results within a month, your club will be shut down regardless of whether you have four members or four hundred!"
21090-80 = "Th-This can't be happening!"
21090-81 = "But it is! I've already explained this to all the club presidents."
21090-82 = "Now that I think about it, your president, Yuzu, was absent from that meeting."
21090-83 = "Huh?!"
21090-84 = "So the onus to comply with the changes falls to you."
21090-85 = "Grr... This is so unfair!"
21090-86 = "What's unfair about it? In fact, making everyone follow the same rules is the definition of fair, really."
21090-87 = "If I'm being honest, I still have my suspicions about Aris' identity,#nand I had come in here today intent on shutting down this club."
21090-88 = "Huh?!"
21090-89 = "But one thing is clear to me—Aris has a real passion for gaming."
21090-90 = "Given that passion, I don't think I can take away your grace period in good conscience. If that passion is real, it should produce fitting results."
21090-91 = "As I recall, Momoi, didn't you tell me you'd have something amazing to show us at the Millennium Prize?"
21090-92 = "I...guess I did."
21090-93 = "Well, now that you have a new member, you'll have more resources to make your new game all that much more fun, right?"
21090-94 = "I'm looking forward to playing it. Bye!"
21090-95 = ""
21090-97 = "Hold on you... You...! Arrrgh!"
21090-98 = "She's gone..."
21090-100 = "Hmm..."
21090-101 = "So in the end, we're still in big trouble."
21090-102 = "Gah! This sucks! They're just trying to get us kicked out!"
21090-103 = "...I'm sorry. I should have gone to the club meeting."
21090-104 = "I-It's not your fault, Yuzu! Momoi was supposed to go in your place if you couldn't make it!"
21090-105 = "Right, but, um..."
21090-106 = "Well, y'know, the item drop rate was doubled at that time."
21090-107 = "Delete that game right now!"
21090-108 = "Ugh... There's only one option left."
21090-109 = "Yeah..."
21090-110 = "We have to make a game that we can take to the Millennium Prize."
21090-111 = "So we need the G.BIBLE after all! Ugh, does that mean we're going back to the ruins?"
21090-112 = "..."
21090-113 = ""
21090-114 = ""
21090-116 = "This is all my fault."
21090-117 = "Huh? What was that, Yuzu?"
21090-118 = "If you're going back to the ruins...then I'm coming with you."
21090-119 = "You WHAT?!"
21090-120 = "B-But you haven't left the school building in half a year. You've even taken every class online!"
21090-121 = "I need to take responsibility for my mistake... This club belongs to everyone, not just me."
21090-122 = "For the sake of everyone, I want to protect it."
21090-123 = "Yuzu..."
21090-124 = ""
21090-126 = "Bum bum bum! Yuzu has joined the party!"
21090-127 = "All right. Let's do this!"
21090-128 = "Aris. Make sure your weapon and equipment are ready!"
21090-129 = ""
21090-130 = ""
21090-131 = "Loadout complete. I have equipped Supernova: the Sword of Light to my weapon slot."
21090-132 = ""
21090-134 = "That's the spirit! This time, the G.BIBLE is ours! Let's go!"
21090-135 = "..."
21090-136 = "Right."
21090-137 = "We'll protect this club room together!"
21090-139 = "Next Episode;Back to the Ruins"
