[translation]
21135-3 = "#place;밀레니엄 복도 외곽"
21135-4 = "1;마키;00;후후. 아까의 합금강 셔터와는 차원이 달라 보이는 벽이네. 진짜로 갇혀버렸다아~\n#1;em;[음표]\n#1;a"
21135-5 = "5;코토리;02;후훗. 아카네 선배. 이렇게 갇혀버린 것도 인연인데 저와 함께 즐거운 상대성 이론 강의를 시작하도록 할까요?\n#5;em;[반짝]\n#5;hophop\n#5;a"
21135-6 = "1;마키;00\n5;코토리;02\n#1;d\n#5;d\n#wait;1000"
21135-8 = "3;아카네;05;큭! 여기는 콜사인 제로쓰리! a-11 지역에 갇혔다! 콜사인 제로원 응답 바람! 응답 바람!\n#3;em;[!]\n#3;a\n#3;stiff"
21135-9 = "3;아카네;05\n#3;m1\n#wait;500"
21135-10 = "5;아스나;01\n#5;sig\n#5;a\n#wait;1500"
21135-11 = "5;아스나;01\n#5;black"
21135-12 = "#na;시스템;<상대방이 오프라인입니다.>"
21135-13 = "#5;hide\n3;아카네;06;으아아아! 아스나 선배! 대체 어디 있는 거예요! 통신 정도는 켜두시라고요!\n#3;em;[속상함]\n#3;stiff"
21135-14 = "3;아카네;04\n#3;h\n#3;stiff"
21135-15 = "#na;(삐비빅-)"
21135-16 = "3;아카네;04\n#3;m3"
21135-17 = "#na;Connecting, New Message……."
21135-18 = "3;아카네;02\n#3;h\n#na;???;아스나 선배 위치는 모르겠지만. 안심해. 아카네."
21135-20 = "#na;???;게임개발부는 이미, 나의 범위 안에 있다."
21135-21 = "3;카린;01\n#3;closeup\n#3;sig\n#3;a\n#wait;1500"
21135-22 = "#na;From Call Sign 02."
21135-24 = "#nextepisode;다음화;메이드 vs 마이스터즈"
