[translation]
21170-1 = "#title;제17화;끝나지 않은 싸움"
21170-2 = "#place;밀레니엄 본교사 복도"
21170-3 = "3;아스나;05;……\n#3;a"
21170-4 = "1;카린;03;……\n#1;em;[땀]\n#1;a"
21170-5 = "5;아카네;06;……\n#5;a"
21170-6 = "3;아스나;05\n1;카린;03\n5;아카네;06\n#1;d\n#3;d\n#5;d\n#wait;1000"
21170-7 = "3;네루;01;……\n#3;a"
21170-8 = "3;네루;99;그러니까……"
21170-9 = "3;네루;04;게임개발부……였나. 그런 동아리가 있는 줄도 몰랐는데.\n#3;em;[...]"
21170-10 = "3;네루;01;그 꼬맹이들에게 당했다- 이 말이지?\n#3;em;[?]"
21170-11 = "1;아카네;06;……면목 없습니다.\n#1;ar\n#3;m5\n#1;em;[속상함]"
21170-12 = "1;아카네;05;이 의뢰를 수락하고, 작전을 준비한 건 저예요."
21170-13 = "1;아카네;05;메이드부의 의뢰 성공률에 흠집을 낸 건, 죄송할 뿐입니다.\n#1;em;[...]"
21170-14 = "3;네루;05;그딴 건 상관없어."
21170-15 = "1;아카네;04;네?\n#1;stiff"
21170-16 = "3;네루;01;내가 도착했을 때, 리오에게 연락이 왔어."
21170-17 = "1;카린;04;세미나의…… 아니 밀레니엄 학생회장인?\n#1;em;[반응]"
21170-18 = "3;네루;01;그래."
21170-19 = "3;네루;05;의뢰를 철회하겠다고 하더라고."
21170-20 = "1;카린;04;?!\n#1;shake\n#1;em;[?!]"
21170-21 = "1;아카네;04;대체 왜……?"
21170-22 = "3;네루;99;흐음. 아무래도, 리오나 히마리나 시험을 하고 싶었나 본데."
21170-23 = "1;아카네;04;시험이라니…… 저희를요?\n#1;em;[?]"
21170-24 = "3;네루;01;반대다."
21170-25 = "3;네루;05;그 아리스라는 꼬마의 능력이겠지."
21170-26 = "3;네루;03;뭐, 좋아.\n#3;em;[음표]"
21170-27 = "3;네루;07;어차피 의뢰와는 상관없어졌지만."
21170-28 = "3;네루;02;아카네, 조사해 봐.\n#3;em;[반응]\n#3;m4"
21170-29 = "1;아카네;04;네? 무엇을요?\n#1;em;[?]"
21170-30 = "3;네루;01;게임개발부."
21170-31 = "1;아카네;04;갑자기 왜…… 아, 리벤지인가요?"
21170-32 = "3;네루;07;그런 구질구질한 건 관심 없지만, 겸사겸사 할 수도 있겠지.\n#3;em;[음표]"
21170-33 = "3;네루;01;조사가 끝나면, 게임개발부로 간다.\n#3;m5"
21170-34 = "1;아카네;05;바라던 바예요. 지금쯤 그 아이들은, 메이드부에게 한 방 먹였다며 한껏 기뻐하고 있겠죠.\n#1;greeting"
21170-35 = "1;아카네;01;후훗. 그 아이들이 우리가 방문했을 때 어떤 표정을 짓고 있을지, 기대가 되네요.\n#1;m3\n#3;dr\n#1;em;[반짝]"
21170-37 = "3;유즈;04\n1;모모이;04\n5;미도리;04"
21170-38 = "#place;밀레니엄 게임개발부"
21170-39 = "3;유즈;04\n1;모모이;04;……\n#1;em;[...]"
21170-40 = "3;유즈;04\n5;미도리;04;……\n#5;em;[...]"
21170-41 = "3;유즈;04;……"
21170-42 = "3;유즈;04;이 정도로 절망한 건…… 테일즈 사가 크로니클 프로토타입 업데이트 이후…… 처음이야.\n#3;em;[속상함]\n#3;stiff"
21170-43 = "1;모모이;04\n5;미도리;04\n3;유즈;04\n#1;d\n#3;d\n#5;d\n#wait;1000"
21170-45 = "3;아리스;09\n#3;em;[땀]\n#wait;2000\n#3;stiff\n#3;a"
21170-46 = "3;아리스;04;저, 저기…… 모모이.\n#3;m5"
21170-47 = "1;모모이;04;후헤헤. 후헤헤헤 다 끝났어! 끝났다구!!!\n#1;em;[!]\n#1;hophop\n#1;ar"
21170-48 = "3;아리스;09\n#3;em;[땀]\n#wait;2000"
21170-49 = "1;모모이;04\n3;아리스;09\n#3;m1\n#wait;1000\n#1;dl"
21170-50 = "#1;hide\n3;아리스;04;미도리. 괜찮습니까?\n#3;em;[반응]"
21170-51 = "5;미도리;07;아리스 쨩…… 미안…… 지금은 아무 말도 하고 싶지 않아…….\n#5;em;[...]\n#5;al"
21170-52 = "3;아리스;09\n#3;em;[땀]\n#wait;2000"
21170-53 = "5;미도리;07\n3;아리스;09\n#3;m3\n#5;dr\n#wait;1000"
21170-54 = "#5;hide\n3;아리스;04;저기, 유……"
21170-55 = "3;유즈;08;분노…… 파멸…… 부식…… 절망…… 허탈……. 세계는 멸망을 향해……\n#3;em;[...]\n#3;a\n#3;stiff"
21170-56 = "3;아리스;09\n#3;em;[땀]\n#wait;2000\n#3;stiff"
21170-57 = "3;아리스;04;모, 모두! 저는 이해가 잘 안됩니다만……\n#3;hophop"
21170-58 = "3;아리스;09;혹시……"
21170-59 = "3;아리스;09\n#3;d\n#wait;1000"
21170-60 = "3;아리스;04;G.Bible 때문인가요?\n#3;a\n#3;closeup\n#3;em;[?]"
21170-62 = "3;모모이;07;…….\n#3;em;[...]"
21170-63 = "3;미도리;07;…….\n#3;em;[...]"
21170-65 = "3;아리스;09;으음. G.Bible이 거짓말을 한 건 아닌 것 같은데."
21170-67 = "3;모모이;05;웃 기 지 마!\n#3;closeup\n#3;em;[!]\n#3;shake\n#fontsize;90"
21170-69 = "1;모모이;05\n3;아리스;10\n#3;m5\n#wait;500"
21170-70 = "3;아리스;10;?!\n#3;em;[?!]\n#3;shake"
21170-71 = "1;모모이;05;차라리 거짓말인 게 낫지! 차라리 그랬으면 덜 열받았을 거야.\n#1;hophop"
21170-72 = "1;모모이;06;으아아아아 망했어! 우린 폐부라고! 후헤헤헤!\n#1;stiff\n#1;em;[속상함]"
21170-73 = "3;아리스;09;???\n#3;em;[땀]"
21170-75 = "#place;밀레니엄 게임개발부"
21170-76 = "#na;(2시간 전)"
21170-77 = "3;마키;03;안녕! 게임개발부 꼬마 친구들! 친구들을 위해 마키 쨩이 선물을 준비했어요!\n#3;closeup"
21170-79 = "1;마키;03\n5;모모이;03;오오! 드디어!\n#5;hophop\n#1;a\n#5;a"
21170-80 = "1;마키;00;짜잔!\n#1;em;[음표]"
21170-82 = "#na;G.Bible.exe…… 실행 준비 완료."
21170-83 = "5;미도리;03;……마침내…… 우리가 G.Bible을……!\n#5;em;[반짝]\n#5;a"
21170-84 = "1;마키;01;늦어서 미안. 우리도 결국 거울은 다시 학생회에 반납했지만, 그 전에 G.Bible은 확보했어."
21170-85 = "5;모모이;02;엣?! 다시 반납한 거야?\n#5;em;[?]\n#5;stiff"
21170-86 = "1;마키;03;히마리 선배는 이미 다 알고 있더라고. 어차피 그 정도는 줘도 상관없으니 앞으로 무리하지 말래. 헤헷."
21170-87 = "1;마키;02;아, 그리고 G.Bible을 확보하던 중에 <Key>라는 폴더를 발견했어.\n#1;em;[반응]"
21170-88 = "5;모모이;02;케이…… 라고 읽는 건가.\n#5;em;[...]"
21170-89 = "1;아리스;01;……케이?\n#1;em;[?]\n#1;a"
21170-90 = "5;미도리;04;키잖아! 대체 언니는 어떻게 고교에 진학한 거야?!\n#5;em;[?!]\n#5;shake"
21170-93 = "3;마키;01;으음. 이 쪽은 전혀~ 모르겠어. 파일이 깨진 건 아닌 것 같은데. 우리 시대의 기계어라고는 믿기 어려운 형태로 완성되어 있어.\n#3;a"
21170-94 = "3;마키;02;일단 G.Bible은 의뢰 받은 물건이니 제대로 했지만, <Key>까지는 제대로 확인할 수 없었어. 이건 대체 뭐야?\n#3;em;[?]"
21170-95 = "1;모모이;04;우리도 잘 몰라.\n#1;shake\n#1;a"
21170-96 = "3;마키;02\n5;미도리;02;…….\n#5;a"
21170-97 = "3;마키;02\n5;미도리;07;……혹시…… <Key>는…….\n#5;em;[...]"
21170-100 = "#stm;[0,0];serial;128;[56cd7b]당신은 AL-1S 입니까?"
21170-103 = "#place;밀레니엄 게임개발부"
21170-104 = "1;마키;01\n5;미도리;07;……으음. 그때 아리스 쨩을 찾던……?\n#1;a\n#5;a"
21170-105 = "1;마키;00;헤에. 그런 일이 있었어? 뭐, 일단 중요한 건 G.Bible이니까.\n#1;em;[음표]"
21170-106 = "1;마키;01;<Key>에 대한 건 나중에 여유 있을 때 한 번 찾아와~ 같이 분석해줄게."
21170-107 = "1;마키;03;자! 그럼 분명히 전달했다~ 나중에 보자고!\n#1;em;[반짝]\n#1;m3\n#5;dr"
21170-109 = "3;미도리;03;마키 쨩 수고했어~\n#3;greeting"
21170-110 = "3;모모이;03;다음에 만날 때는 비서를 통해 연락 주길 바라~ 왜냐면 난 T.S.C 2로 대박을 칠 거거든!\n#3;hophop\n#3;em;[반짝]"
21170-111 = "3;마키;03;하하. 기대할게.\n#3;greeting\n#3;em;[음표]"
21170-113 = "3;모모이;00;아리스! 유즈! 미도리! 모두 모여!\n#3;hophop\n#3;em;[반응]\n#3;a"
21170-114 = "3;모모이;01;지금부터 G.Bible을 볼 거야."
21170-115 = "3;모모이;99;이 안에 어떠한 내용이 있는지는, 아무도 몰라. 가장 최근에 G.Bible을 봤을 거라 평가받는 어떤 스타 개발자에 의하면"
21170-116 = "3;모모이;00;'게임개발의 진정한 비의, 모두가 알고 있다고 생각했으나, 누구도 알지 못 했던 기적'이라고 말해.\n#3;em;[반짝]"
21170-117 = "3;모모이;01;나는, 그 진리를 깨닫고 싶어. 그 이유는 알 거야."
21170-118 = "5;미도리;99;최고의 게임을…… 만들고 싶으니까.\n#5;em;[...]\n#5;a\n#3;m1"
21170-119 = "3;모모이;00;그래야만, 우리는 이곳에 함께 있을 수 있어."
21170-120 = "3;모모이;07;만약 실패하면…… 유즈는 기숙사로 돌아가 싫은 녀석들을 봐야 하고…… 아리스는…….\n#3;em;[...]"
21170-121 = "5;미도리;07;……만약을 생각하고 싶진 않지만. 선생님이, 샬레가 도와줄 거래."
21170-122 = "5;미도리;07\n3;모모이;07\n#3;d\n#5;d\n#wait;1000"
21170-124 = "3;아리스;09;샬레……? 선생님과 함께는…… 좋습니다만…….\n#3;em;[?]\n#3;stiff\n#3;a"
21170-125 = "3;아리스;01;그럼 아리스는…… 더 이상 이곳에, 모두와 함께 있을 수 없는 겁니까?"
21170-126 = "3;모모이;02;……?!\n#3;shake\n#3;em;[?!]"
21170-127 = "3;모모이;05;그럴 일 따위는 없어! 우린 무조건 최고의 게임을 만들 테니까!\n#3;hophop"
21170-128 = "3;모모이;00;아리스. 너는 이제 'TSC2 해보셨나요? 진짜 갓겜이에요' 라고 말하게 될 거야."
21170-129 = "3;모모이;99;자, 그럼……\n#3;em;[...]"
21170-130 = "3;모모이;05;아리스! 시작해!\n#3;em;[!]"
21170-131 = "3;아리스;00;네.\n#3;greeting"
21170-132 = "3;아리스;99;G.Bible……"
21170-133 = "3;아리스;05;가동!\n#3;closeup\n#3;em;[!]"
21170-135 = "#nextepisode;다음화;G.Bible"
