[translation]
21190-1 = "ตอนที่ 19;ดับเบิ้ลโอ"
21190-2 = "ชมรมพัฒนาเกมมิลเลเนียม"
21190-4 = "พี่โมโมอิ! ยังไม่เสร็จอีกเหรอ?!"
21190-5 = "อย่ามาเร่งกันสิ แค่พิมพ์ตรงนี้ก็เสร็จแล้ว..."
21190-6 = "เหลืออีกแค่ 2 นาทีเอง จะไม่ให้เร่งได้ยังไงล่ะ!"
21190-7 = "ที่ถูกต้องคือเหลือแค่ 96 วินาทีค่ะ พอประโยคนี้จบก็จะเหลือ 92 วินาที..."
21190-8 = "ระ... รู้แล้วน่า! เสร็จแล้ว เสร็จแล้ว!"
21190-9 = ""
21190-12 = "ส่วนตรงนี้ก็เทสแบบง่ายๆ เอา... โอเค"
21190-13 = "ไม่เจอบั้กเลยโมโมอิ!"
21190-14 = "โอ้! โอเคเลย! งั้นส่งละนะ! อัปโหลดไฟล์! ใช้เวลาส่งประมาณ 15 วินาที! อาริสึ!"
21190-15 = "เหลือเวลาอีก 19 วินาที..."
21190-16 = "ขะ... ขอร้องล่ะ..."
21190-17 = ""
21190-18 = ""
21190-20 = "สะ... ส่งเสร็จแล้ว"
21190-22 = "ส่งผลงานเข้าร่วมนิทรรศการรวมผลงานมิลเลเนียมไพรซ์แล้ว"
21190-23 = "ทำได้แล้วววว!"
21190-24 = "เฮ้อ... หวุดหวิดเลย"
21190-25 = "จากนี้ก็เหลือแค่รอฟังผลในอีก 4 วันใช่ไหม?"
21190-26 = "เราทำสำเร็จตามกำหนดการก็จริง แต่ว่ายังไม่รู้ผลลัพธ์หรอกนะ"
21190-27 = "ในอีก 4 วันเราจะได้รู้กันว่าเราจะถูกไล่ออกจากห้องนี้หรือว่าจะได้อยู่ต่อ"
21190-28 = "เพราะงั้นฉันก็เลยอยากเสนออะไรหน่อยน่ะ"
21190-29 = "เราใช้เวลาที่เหลือมาอัปโหลดเทลส์ ซาก้า โครนิเคิล 2 ลงบนเว็บกันดีไหม?"
21190-31 = "?!"
21190-32 = "หืม? ทำไมล่ะ?!"
21190-33 = "ไม่อยากดูผลตอบรับจากคนอื่นก่อนการประเมินของคณะกรรมการกันเหรอ?!"
21190-34 = "อืม ถึงอย่างนั้นก็เถอะ... มันออกจะน่ากลัวอยู่นะ ถ้ามีคอนเมนต์แย่ๆ อีกล่ะ?"
21190-35 = "พูดอะไรแบบนั้นล่ะ! เราไม่ได้ตั้งใจทำเกมนี้เพื่อเล่นสนุกกันเองหรือเพื่อลงประกวด#nในงานมิลเลเนียมไพรซ์ตั้งแต่แรกอยู่แล้วนี่นา!"
21190-36 = "มั่นใจในผลงานหน่อย! พวกเราทุ่มกันสุดตัวแล้วนะ!"
21190-37 = "มันก็จริงอยู่หรอก..."
21190-38 = "อัปโหลดเลย..."
21190-39 = "หืม?"
21190-40 = "สิ่งที่เรียกว่าผลงาน ก็ต้องได้รับการประเมินจากคนอื่นถึงจะเสร็จสมบูรณ์"
21190-41 = "และฉัน… ก็อยากให้เกมของพวกเราสมบูรณ์ด้วย"
21190-42 = "ยูสึจัง..."
21190-43 = "ไม่เป็นไรหรอก ถึงจะมีคนแห่มาคอนเมนต์แย่ๆ เหมือนคราวที่แล้วอีก..."
21190-44 = "แต่เราก็ทำเต็มที่แล้ว และฉันก็... ได้อยู่กับพวกเธอแล้ว... ไม่ว่าจะออกมาเป็นยังไงฉันก็รับได้"
21190-45 = ""
21190-46 = "ฉันไม่เป็นไรจริงๆ"
21190-48 = "......"
21190-49 = "งั้นจะอัปโหลดเลยนะ!"
21190-50 = "อ๊ะ! เดี๋ยวก่อนๆ!"
21190-52 = "ส่งไฟล์สำเร็จ! กว่าจะมีคนเข้ามาคอมเมนต์ก็น่าจะต้องใช้เวลาสัก 2-3 ชั่วโมง#nระหว่างนี้เรามาพักกันหน่อยดีไหม?"
21190-53 = "เฮ้อ... เอาสิ"
21190-55 = "......"
21190-56 = ""
21190-57 = "... (พรึ่บ) "
21190-58 = "หืม? อาริสึ? ทำไมไปนั่งหน้าคอมพิวเตอร์ล่ะ?"
21190-59 = "กำลังรอค่ะ"
21190-60 = "คนอื่นเริ่มดาวน์โหลดเกมไปเล่นแล้ว อาริสึก็เลยสงสัยน่ะค่ะ"
21190-61 = "ถึงจะนั่งรอ แต่เราก็คงไม่ได้รีวิวหรือฟีดแบกที่จริงใจจากคนที่ตั้งใจเล่นเกมจริงๆ หรอก"
21190-62 = "ฉันจะรอค่ะ"
21190-63 = "...... ฉันก็ด้วย ......"
21190-64 = "ยังไงก็กลัวจนนอนไม่หลับอยู่ดีน่ะ"
21190-65 = "ขอรอด้วยดีกว่า"
21190-66 = "อืม...."
21190-67 = "ฉันก็เริ่มตื่นเต้นแล้วเหมือนกัน"
21190-68 = "เฮ้อ จริงๆ ต้องบอกว่ากังวลมากกว่าตื่นเต้นสิ เป็นคนเสนอให้อัปโหลดเองแท้ๆ#nแล้วจะมากังวลทำไมนะ!"
21190-69 = "(ติ๊ง)"
21190-70 = "อ๊ะ! มีคอมเมนต์แรกแล้ว"
21190-71 = "ไหนๆ? ว่าไงบ้าง?"
21190-72 = "<hermet021: นี่มันเจ้าของรางวัลเกมยอดแย่ที่ 1 ของปีนี้นี่นา นึกว่าจะเลิกทำเกมไปแล้วซะอีก#nยังกล้ามาปล่อยภาคต่ออีกเหรอ? 5555>"
21190-73 = "......"
21190-74 = "อะ... อาริสึ อย่าคิดมากเลยนะ..."
21190-75 = "ค่ะ"
21190-76 = "ติดต่อมากิ ฉันจะไปปล่อยลำแสงบีมใส่บ้านเจ้าของ IP นั้นสักหน่อย เดี๋ยวกลับมานะคะ"
21190-77 = "ทำแบบนั้นไม่ได้นะ!"
21190-78 = "อืม..."
21190-79 = "มันก็แค่คำพูดของคนที่ยังไม่ได้เล่นเกม... ไม่ต้องใส่ใจมากหรอก"
21190-80 = "(ติ๊ง)"
21190-81 = "<Kotoha0507: ถึงภาคแรกจะล้มเหลวไม่เป็นท่า แต่ก็ไม่ใช่เกมทั่วไปที่ไม่มีอะไรใหม่#nฉันคาดหวังแล้วล่ะว่าภาค 2 จะมีความแปลกใหม่ที่พัฒนาขึ้นยังไงบ้าง>"
21190-82 = "โอ้! ในที่สุดก็เจอฟีดแบกที่เข้าท่า..."
21190-83 = "(ติ๊ง)"
21190-84 = "<QueenC: กลัวใจจัง ตอนที่เกมจะจบ... ฉันในอนาคตจะคิดอะไรอยู่นะ จะเกลียดตัวเองในอดีต#nที่โหลดเกมนี้มาไหม.. หรือว่าจะคิดว่าเป็นการตัดสินใจที่ดีที่สุดของปีนี้แล้ว?>"
21190-85 = "(ติ๊ง)"
21190-86 = "<kirakiraNO1: ตอนได้เล่นเกมนี้ทำให้ฉันคิดเป็นครั้งแรกว่าเกมคือโรคร้าย#nมันเจ็บปวดตลอดการเล่นเลย แต่ทำไมกันนะ... รู้ตัวอีกทีก็โหลดเกมมาเล่นอีกแล้ว>"
21190-87 = "ยอดไปเลย! มีคนคาดหวังกับเกมของเราด้วย!"
21190-88 = "อืม..... โดยรวมแล้วทุกคนคาดหวังและตื่นเต้นเหมือนกับว่ากำลังดึงระเบิดเวลาที่ยังไม่ได้เปิดเลยล่ะ"
21190-89 = "หรือมันคือจิตวิทยานะ... เหมือนที่เราอยากลองเหยียบกับระเบิดแม้จะรู้ว่ามันคือระเบิดไงล่ะ..."
21190-91 = "(ติ๊ง ติ๊ง)"
21190-92 = "<cat0808:เอาละ อีก 2 ชั่วโมงจากนี้ฉันต้องไปฝึกทำข้อสอบ หรือไม่ก็เล่น TSC 2 ระหว่าง 2 อย่างนี้ ฉันเลือก... TSC 2>"
21190-93 = "<Yousee-me: ของมันแน่อยู่แล้วไม่ใช่เหรอ? ข้อสอบไว้ไปทำเมื่อไหร่ก็ได้#nแต่ไม่ได้เล่น TSC 2 ตั้ง 2 ชั่วโมงใครจะไปทนได้!>"
21190-94 = "ตะ… แต่ฉันว่าไปทำข้อสอบน่าจะดีกว่านะ"
21190-95 = "มะ... มียอดดาวน์โหลดถึง 2,000 ครั้งแล้วเหรอเนี่ย?! แปลกจัง"
21190-96 = "อ่า... ท่าทางจะมีเว็บดังลงข่าวว่าเราปล่อยให้ดาวน์โหลดเกมนะ"
21190-97 = "อ๊าาาา! ตอนแรกฉันก็อยากให้มีคนสนใจ แต่ตอนนี้ชักรู้สึกกลัวขึ้นมาแล้ว!"
21190-98 = ""
21190-100 = "......"
21190-101 = "ใจเต้นเลยล่ะค่ะ..."
21190-102 = "วู้วว! อกจะแตกเพราะทั้งคาดหวังทั้งกังวลเลย!"
21190-103 = "(ตู้มมมม!)"
21190-104 = "?!"
21190-105 = "หัวใจโมโมอิระเบิดออกมาเหรอคะ?"
21190-106 = "ไม่ใช่นะ! ไม่ใช่ฉันสักหน่อย!"
21190-107 = "นี่มันเกิดอะไรขึ้น...! เครื่องเล่นเกมระเบิดงั้นเหรอ?!"
21190-108 = "ระ... หรือว่าเล่นนานเกินไป?"
21190-109 = "ไม่ใช่หรอก! นี่มันกระสุน 13.97 mm! ของรุ่นพี่คาริน...!"
21190-110 = "(ตู้มมมม!)"
21190-111 = "อ๊าาา!"
21190-112 = "พบการโจมตีระยะไกล มาจากทิศ 11 นาฬิกาจากหน้าห้องชมรม! ระยะห่างประมาณ 1 กิโลเมตร...!"
21190-113 = "อึ่ก! หรือว่าจะมาแก้แค้นเรื่องคราวก่อน!?"
21190-114 = "อาริสึจะยิงตอบโต้ค่ะ!"
21190-115 = "ไม่ต้องหรอกอาริสึ! เราออกจากที่นี่กันก่อนดีกว่า! ที่นี่มีคุณครูด้วย และที่สำคัญ..."
21190-116 = "ถ้าต่อสู้ที่นี่ ห้องชมรมของเราได้พังแน่!"
21190-117 = "พี่โมโมอิ..."
21190-118 = "ข้างนอกก็มีกลุ่มสภานักเรียน! มาแก้แค้นเรื่องกระจกงั้นเหรอ?!"
21190-119 = "ระ... เราก็รู้สึกผิดอยู่หรอกนะ แต่จู่ๆ บุกมาแบบนี้มันไม่ยุติธรรมเลย!"
21190-120 = "เฮือก!"
21190-121 = "[s1] \"ตั้งสติไว้\"\n[s2] \"ออกไปข้างนอกกันก่อน\""
21190-122 = "คุณครู...!"
21190-123 = "คุณครู...!"
21190-124 = "ค่ะ!"
21190-125 = "อาริสึ! ฉันกับยูสึจะอยู่ข้างหน้าเอง! เข้าใจที่ฉันสื่อใช่ไหม?"
21190-126 = "ค่ะ"
21190-127 = "อาริสึจะปกป้องคุณครูและทุกคนเองค่ะ"
21190-129 = "ดีล่ะ! ไปกันเลย!!"
