[translation]
21190-1 = "Episode 19;Double O"
21190-2 = "Millennium Game Development Department"
21190-4 = "Momoi! Are you done yet?"
21190-5 = "Gimme a minute... I just need to enter this and I'll be done..."
21190-6 = "We only have two minutes left! There's no time to spare!"
21190-7 = "96 seconds to be exact. Oh, 92 now..."
21190-8 = "Okay! Okay! I'm done!"
21190-9 = ""
21190-12 = "Let's just do a quick test, and... Okay."
21190-13 = "There are no errors, Momoi!"
21190-14 = "All right! Beginning the upload! 15 seconds to delivery! Aris, the time?!"
21190-15 = "19 seconds remaining..."
21190-16 = "Please, please, please..."
21190-17 = ""
21190-18 = ""
21190-20 = "Status: Sent..."
21190-22 = "Thank you for your submission and participation in the Millennium Prize."
21190-23 = "We did it!"
21190-24 = "Pheeew... That was too close."
21190-25 = "Now all we have to do is wait for the announcement in four days."
21190-26 = "We made it in time, but we won't know our fate until the results come."
21190-27 = "In four days, it'll be decided if we have to stay or go."
21190-28 = "So I have a proposal."
21190-29 = "Why don't we try uploading an open web version of Tales Saga Chronicle 2 in the time we have left?"
21190-31 = "Huh?"
21190-32 = "Why would we do that?"
21190-33 = "Cause who cares what the judges think? Don't you want to know what regular-old players have to say about our game?"
21190-34 = "B-But what if they say it's horrible?"
21190-35 = "Think about it this way. We did this for us. The Millennium Prize is just a bonus."
21190-36 = "We did our best, and that's something to be proud of!"
21190-37 = "Well, sure, but..."
21190-38 = "Let's do it."
21190-39 = "Huh?"
21190-40 = "Art is nothing if people never get to experience it."
21190-41 = "I want people to experience what we made."
21190-42 = "Yuzu..."
21190-43 = "It's okay. Even if it's just like last time, and we get an avalanche of nasty comments..."
21190-44 = "...I'll know that we did our best. And we did it together. That's what's truly important."
21190-45 = ""
21190-46 = "I'm all right, honest."
21190-48 = "..."
21190-49 = "Okay! I'm going to upload it now!"
21190-50 = "W-Wait!"
21190-52 = "And...done! In two or three hours, the reviews will be rolling in. I'm going to take a break while we wait."
21190-53 = "Sure..."
21190-55 = "..."
21190-56 = ""
21190-57 = "...*plop*"
21190-58 = "Aris? Why are you sitting in front of the computer?"
21190-59 = "I am waiting."
21190-60 = "People are starting to download the game. I want to know what they think."
21190-61 = "A watched pot never boils, Aris. The real reviews won't come until later."
21190-62 = "Well, I am just going to wait."
21190-63 = "Me too."
21190-64 = "I'm too anxious to sleep anyway."
21190-65 = "So I'll wait with you."
21190-66 = "Ah."
21190-67 = "My heart is pounding."
21190-68 = "Agh! I'm more worried than excited. And I'm the one who suggested we do this!"
21190-69 = "*ding*"
21190-70 = "Oh! It's our first comment!"
21190-71 = "Wh-What?! Really?!"
21190-72 = "helmet021: Yo, the Worst Game of the Year frauds are back! I thought they'd quit after realizing they're talentless hacks but here they are crapping out sequels LOL"
21190-73 = "..."
21190-74 = "Ah... It's okay, Aris. Don't let it get to you."
21190-75 = "Understood."
21190-76 = "I am going to have Maki give me this person's IP address so I can go blast them with a full strength laser beam."
21190-77 = "Y-You can't do that!"
21190-78 = "Midori's right."
21190-79 = "They clearly didn't even try the game, so just try to ignore it."
21190-80 = "*ding*"
21190-81 = "Kotoha0507: The first one was a disaster, but it had a few interesting ideas. I hope they've improved the gameplay this time."
21190-82 = "Hey, now we're getting somewhere."
21190-83 = "*ding*"
21190-84 = "QueenC: I'm scared... When I finish the game, how will my future self judge the current me? Will I curse myself for purposely downloading this game, or will I rejoice at my leap of faith?"
21190-85 = "*ding*"
21190-86 = "kirakiraNO1: the first one made me want to quit games forever lol seriously crap like this make me cringe so hard lmao. Y do I always feel like trying this stuff tho?"
21190-87 = "W-Wow! People are actually excited to play our game!"
21190-88 = "Uh... I feel like they're acting like our game is some kind of ticking time bomb."
21190-89 = "They think they are going to hate it, but want to try it anyway..."
21190-91 = "*ding ding* "
21190-92 = "cat0808: I have a make-up test in two hours, but TSC2 lookin kinda :eyes: I'm thinking of skipping to play. Should I?"
21190-93 = "Yousee-me: Play TSC2, obv! Tests are temporary, getting to play TSC2 on release is eternal. Waiting to play would be a crime against art!"
21190-94 = "Uhhh... They should really go take their test."
21190-95 = "Whoa, we already have over 2000 downloads. How'd that happen?"
21190-96 = "Oh. Someone posted it on a social media aggregate site."
21190-97 = "Ahhh! I was just hoping people wouldn't be apathetic, but now I'm scared!"
21190-98 = ""
21190-100 = "..."
21190-101 = "My heart is beating really fast."
21190-102 = "I can't tell if I'm scared or excited!"
21190-103 = "*BOOM*"
21190-104 = "Huh?!"
21190-105 = "Did Momoi's heart just explode?"
21190-106 = "What?! No, that wasn't me!"
21190-107 = "Then what was it? Did our console finally die?"
21190-108 = "It was getting pretty old..."
21190-109 = "No! This shell is a 13.97 millimeter round! It belongs to Karin!"
21190-110 = "*BOOM BOOM*"
21190-111 = "Eek!"
21190-112 = "Ranged attack confirmed. Position: eleven o' clock. Distance: approximately one kilometer!"
21190-113 = "W-Was our last game really THAT bad?!"
21190-114 = "Preparing to counterattack!"
21190-115 = "Don't, Aris! We have Sensei here."
21190-116 = "And if we fight in here, the club room will be destroyed!"
21190-117 = "Momoi..."
21190-118 = "Student Council forces are outside! Maybe they're here for revenge!"
21190-119 = "I can't believe I felt a little bad for them before!"
21190-120 = "Eek!"
21190-121 = "[s1] \"Calm down.\"\n[s2] \"Let's go outside.\""
21190-122 = "Sensei!"
21190-123 = "Sensei!"
21190-124 = "Right!"
21190-125 = "Yuzu and I will take the lead. You know what that means, right, Aris?"
21190-126 = "Yes."
21190-127 = "I must protect everyone."
21190-129 = "All right. Let's move out!"
