[translation]
221080-1 = "#title;제8화;불가해한 결정"
221080-2 = "1;아미;00\n5;미나토;06\n#1;h\n#5;h\n#1;a\n#5;a\n#wait;1000"
221080-3 = "1;아미;02;……함장. 아직도 결정을 내리지 못하신 건가요?\n#1;em;[…]"
221080-4 = "5;미나토;21;……수개월을 고민한 문제인데, 1주일을 더 기다린다고 답이 나올 리가 없잖아."
221080-5 = "1;아미;07;입항한 이후로도 새미의 처우를 두고 학생들 사이에서 계속해서 말이 나오고 있습니다."
221080-6 = "1;아미;02;더욱이 오늘은 샬레의 선생님께서 새미의 돌발 행동에 휘말려 다치시는 바람에……"
221080-7 = "1;아미;00;학생들 사이에서는 정말 새미가 불운을 불러오는 게 아닌가, 하는 걱정이 커지고 있습니다."
221080-8 = "5;미나토;15;그래서, 새미를 내보내면 이 불운이 모두 사라질까?"
221080-9 = "1;아미;05;……그런 뜻으로 한 말이 아니잖아요!\n#1;em;[!]"
221080-10 = "4;투명;01\n#4;h\n#4;hide\n#na;새미;냥?!"
221080-11 = "1;아미;13;……미안, 새미."
221080-12 = "1;아미;06;너에게 화낸 게 아니야."
221080-13 = "4;투명;01\n#4;h\n#4;hide\n#na;새미;끼잉……"
221080-14 = "1;아미;05;하지만, 샬레의 선생님이 저희 학원에서 부상을 입었다는 건 진지하게 대응해야 할 문제입니다.\n#1;m2"
221080-15 = "5;미나토;14;……알고 있어."
221080-16 = "1;아미;20;혹 이 일 때문에 샬레에서 오디세이아 학원에 책임을 묻는다면, 어떻게 대응하실 생각이신가요?\n#1;em;[…]"
221080-17 = "1;아미;20\n5;미나토;14\n#1;h\n#5;h"
221080-18 = "[ns1] \"그건 걱정하지 않아도 돼.\"\n[ns2] \"내 실수로 다친 거니까…… 누구의 책임도 아니야.\""
221080-21 = "5;미나토;14\n1;아미;02;[USERNAME] 선생님? 그리고 총학생회장님까지……\n#1;em;[?]"
221080-22 = "5;미나토;16;허리를 다치셨다고 들었는데, 벌써 움직이셔도 괜찮나요?\n#5;m4"
221080-23 = "5;미나토;02;일단, 자리에 앉으시지요. 금방 차를 준비해 오겠습니다."
221080-24 = "3;가짜 총학생회장;01;괜찮습니다. 목이라면 이미 충분히 축이고 왔거든요.\n#1;hide\n#5;hide"
221080-25 = "3;가짜 총학생회장;99;그보다 지난 번에 부탁드린 안건에 대해 바로 이야기하고 싶습니다만……"
221080-26 = "3;가짜 총학생회장;02;오늘 '예정된 대화를 뒤로 미뤄야 할 만한' 금기나 의례는 없겠지요?\n#3;em;[?]"
221080-27 = "2;아미;00\n4;미나토;01;물론이지요. 바로 본론을.\n#3;hide"
221080-28 = "#st;[0,0];instant;1;"
221080-30 = "4;미나토;01\n2;아미;00\n#2;h\n#4;h\n#2;greeting\n#4;greeting\n#wait;1500"
221080-31 = "3;가짜 총학생회장;01\n#3;greeting\n#2;hide\n#4;hide\n#wait;1000"
221080-33 = "#na;새미;그릉, 그르릉……"
221080-34 = "#na;가짜 총학생회장;후후, 이 아이는 여전히 태평하네요."
221080-35 = "#st;[0,0];instant;1;"
221080-37 = "3;가짜 총학생회장;01\n#3;a\n#wait;1500"
221080-38 = "3;가짜 총학생회장;01;아직 1주일이 채 지나진 않았습니다만. 고양이의 처분에 대해서는 충분히 고려해 보셨나요?"
221080-39 = "3;미나토;16;죄송합니다만, 아직……\n#3;em;[…]"
221080-40 = "3;가짜 총학생회장;08;역시 학생들의 반대와 원망이 여전히 두려우신가요."
221080-41 = "3;가짜 총학생회장;07;아니면 오디세이아의 관습과 바다의 금기를 어기는 것이 두려우신가요?"
221080-42 = "3;미나토;14;……두가지 모두, 입니다."
221080-43 = "[ns] \"내가 며칠동안 새미를 살펴보았는데……\""
221080-45 = "[ns3] \"분명 새미의 주변에서 불운한 일이 생긴 것도 사실이지만.\"\n[ns4] \"그걸 꼭 새미의 탓으로 돌리기는 어렵다고 생각해.\""
221080-48 = "3;미나토;16;그렇지요. 새미도 결국은 한낱 평범한 고양이일 뿐이니까요."
221080-49 = "4;투명;01\n#4;hide\n#4;h\n#na;새미;냐옹—"
221080-50 = "[s5] \"그럼 새미의 상태가 학원의 운세와는 상관없다고—\"\n[s6] \"함장이 직접 공표할 수는 없는 거야?\""
221080-53 = "3;아미;02;그건……"
221080-54 = "3;미나토;06;……후우.\n#3;em;[한숨]"
221080-55 = "3;미나토;15;솔직히 말씀드리자면……"
221080-56 = "3;미나토;14;오디세이아의 수많은 금기가, 현대에 이르러서는 의미를 잃은 관습에 불과하다는 건 저 역시 알고 있습니다."
221080-57 = "3;미나토;15;토끼나 쥐처럼 과거에는 항해에 치명적이었던 존재들도, 이제는 배의 항행에 아무런 영향을 끼치지 못하지요."
221080-58 = "3;미나토;16;사람도 물자도 부족한 바다 위에서, 이 의미 없는 금기를 피하기 위해 자원을 낭비하는 건 뭍 사람들의 눈에는 우스꽝스럽게 보일지도 모릅니다."
221080-59 = "3;미나토;17;하지만…… 이 금기를 모른 척 하기에, 이 바다는 너무나도 변화무쌍한 장소입니다.\n#3;em;[…]"
221080-61 = "#na;미나토;내일을 확신할 수 없는 변화무쌍한 날씨와……"
221080-62 = "#na;미나토;수면 아래에서 도사리고 있는 수많은 암초와 위협."
221080-63 = "#na;미나토;그리고 사람의 머리로는 납득할 수 없는 불합리한 결과까지."
221080-64 = "#na;미나토;이런 불합리를 마주하면 사람들은 괴로움을 호소하며 도망치려 합니다."
221080-66 = "3;미나토;17\n#3;a\n#wait;1000"
221080-67 = "3;미나토;15;그래서 가끔은 알기 쉬운 명쾌한 '해답'이 존재하기를 희망하지요."
221080-68 = "3;미나토;15\n1;가짜 총학생회장;07;그래서, 오디세이아가 택한 그 해답이 '금기'였다는 말씀이신가요?\n#1;a\n#3;m5\n#1;em;[반응]"
221080-69 = "3;미나토;16;네. 금기는 설명하기 쉬운 인과니까요."
221080-71 = "#na;미나토;바람이 나빠서 항해가 지연되고, 귀중한 식량이 낭비되는 상황이 발생하더라도—"
221080-72 = "#na;미나토;갑작스러운 폭풍우에 열심히 수리한 돛대가 부러져 버리더라도—"
221080-73 = "#na;미나토;거대한 파도에 휩쓸려 소중한 친구가 큰 부상을 입게 되더라도—"
221080-75 = "3;미나토;14;사실은 누군가가 '오래된 금기를 어겼기 때문에' 발생한 인과의 결과라면 어떨까요?\n#3;a"
221080-76 = "3;미나토;15;이 모든 문제를 그저 늙고 병든 고양이 한 마리에게 지울 수 있는 것이라면……"
221080-77 = "3;미나토;17;그 누구도 상처받지 않고 이 불합리한 바다를 항해할 수 있을테니까요."
221080-78 = "4;투명;01\n#4;h\n#4;hide\n#na;새미;……냐옹."
221080-79 = "4;투명;01\n#4;h\n#4;hide\n#na;새미;그릉, 그르릉……"
221080-80 = "3;미나토;16;하지만…… 이게 최선의 결정이었을까요?"
221080-81 = "3;아미;06;………."
221080-82 = "[ns7] \"세상의 불합리함을 마주하는 것은 어른에게도 괴로운 일이지.\"\n[ns8] \"가끔은 거대한 카페트 아래에 이 모든 걸 쓸어 넣고 싶을 지경이야.\""
221080-85 = "3;미나토;02;카페트라…… 재미있는 비유네요."
221080-86 = "3;미나토;14;오디세이아 학원에도 비슷한 이야기가 있긴 하죠."
221080-87 = "3;미나토;15;귀찮고 복잡한 일들을 갑판 아래로 쓸어 넣으면, 밖에서는 보이지 않게 된다고."
221080-88 = "[ns] \"하지만 카페트 아래에 문제는 분명히 존재하고 있어.\""
221080-90 = "[ns9] \"언젠가 카페트를 들추고 그 밑을 청소하지 않는다면……\"\n[ns10] \"문제는 영원히 풀리지 않은 채 그 안에 남아 있을 거야.\""
221080-93 = "#st;[0,0];instant;1;"
221080-95 = "3;미나토;15\n#3;m5\n#wait;1500"
221080-96 = "4;투명;01\n#4;h\n#4;hide\n#na;새미;냥!"
221080-97 = "#st;[0,0];instant;1;"
221080-99 = "3;미나토;99\n#3;em;[...]\n#wait;2500"
221080-100 = "3;미나토;01;이 공을 새미에게 만들어 준 건 1학년 때였어요."
221080-101 = "3;미나토;03;지금 보니…… 그 때는 매듭 묶는 게 미숙했는지 꼬인 부분도 있고, 역방향으로 감긴 매듭도 있네요."
221080-102 = "3;미나토;01;하지만 새미는 유독 이 공을 정말 좋아했어요."
221080-103 = "#st;[0,0];instant;1;"
221080-105 = "3;미나토;01\n#3;m3\n#wait;1500"
221080-106 = "3;미나토;99;함장이라는 자리가 이성적 판단을 해야 하는 위치라는 건 누구보다 잘 알고 있습니다."
221080-107 = "3;미나토;16;하지만…… 저 역시 함장이기 전에 이 일의 당사자입니다."
221080-108 = "3;미나토;06;오랜 기간 함께해 온 친우를 떠나보내는 아쉬움을, 어떻게 이성적인 말 만으로 설득할 수 있나요?"
221080-109 = "#st;[0,0];instant;1;"
221080-111 = "3;미나토;06\n1;가짜 총학생회장;08\n#1;em;[…]\n#1;a\n#1;h\n#3;h\n#3;m5\n#wait;2500"
221080-112 = "1;가짜 총학생회장;01;꼭 마주하거나, 외면하는 것만이 방법은 아닙니다."
221080-113 = "1;가짜 총학생회장;03;납득할 수 있는 상대에게 판단을 대신 부탁하는 것도 하나의 해결책이 될 수 있으니까요."
221080-114 = "3;미나토;02;그 말씀은……?\n#3;em;[?]"
221080-115 = "3;미나토;02\n1;가짜 총학생회장;01;예를 들자면, 총학생회장의 권위를 빌리시는 건 어떠신가요?\n#1;m3\n#3;dr"
221080-116 = "3;가짜 총학생회장;08;<총학생회에서 판단한 결과, 오디세이아에 상주하는 고양이는 위생상의 문제가 있습니다.>\n#1;hide"
221080-117 = "3;가짜 총학생회장;07;<따라서 학원 위생을 위해, 해당 고양이는 총학생회장이 직접 회수하여 관리토록 하겠습니다.>"
221080-118 = "3;가짜 총학생회장;09;……어떠신가요?"
221080-119 = "3;가짜 총학생회장;09\n1;아미;02;확실히, 총학생회의 권위를 인용하여 결정을 하면 대부분의 학생은 납득하겠지요.\n#3;m5\n#1;a"
221080-120 = "1;아미;00;결정에 대한 모든 책임도, 미움도. 오디세이아 학원에는 남지 않을테니까요."
221080-121 = "3;가짜 총학생회장;09\n1;아미;00\n#1;h\n#3;h"
221080-122 = "[ns] \"하지만 대신 총학생회에 반감을 갖는 학생이 생기면 어떻게 해?\""
221080-123 = "1;아미;00\n3;가짜 총학생회장;03;괜찮습니다. 본래 총학생회는 미움 받기 위해 만들어진 조직이니까요.\n#1;dl\n#3;m3"
221080-124 = "3;가짜 총학생회장;99;그리고 바다의 금기가 아무리 이해하기 어렵다 하더라도……\n#3;em;[…]"
221080-125 = "3;가짜 총학생회장;01;평범한 학생에게 학원 밖에서 오는 강력한 권위만큼 불합리하고 불가해한 것도 없으니까요."
221080-126 = "3;미나토;06;그렇게 말씀하시면, 더 이상 제가 내세울 명분은 남아 있지 않군요."
221080-127 = "3;미나토;14;감정을 내려놓고…… 가장 합리적인 판단을 내려야 한다면."
221080-128 = "#st;[0,0];instant;1;"
221080-130 = "3;미나토;14\n#3;d\n#wait;1000"
221080-131 = "3;미나토;17\n#3;a\n#3;closeup\n#wait;1500"
221080-132 = "3;미나토;16;……새미를 잘 부탁드립니다.\n#3;greeting\n#3;closeup"
221080-134 = "#nextepisode;다음화;미움 받을 용기"
