[translation]
22130-1 = "ตอนที่ 13;บิ๊กซิสเตอร์"
22130-2 = "ศูนย์กักกันกลาง ภายในเอริดู"
22130-5 = "ริโอะ แต่ละอย่างที่คุณทำมันดูรสนิยมแปลกๆ ทั้งนั้นเลยนะคะ"
22130-6 = "...ฮิมาริ"
22130-7 = "เธอก็ชอบพูดแบบนั้นกับฉันอยู่เรื่อย บอกว่าเป็นสิ่งสกปรกบ้างละ น้ำเน่าเสียที่เอ่อในถังบำบัดน้ำบ้างละ..."
22130-8 = "......"
22130-9 = "...แต่ก็ไม่เป็นไรหรอก คนที่ตำหนิฉันได้ในมิลเลเนียม..."
22130-10 = "ไม่สิ ในคิโวทอสก็คงมีแต่คนอย่างเธอเท่านั้นละ"
22130-11 = "และเพราะเป็นเธอที่เป็นแบบนี้ ฉันเลยคาดหวังว่าเธอจะเข้าใจในสิ่งที่ฉันกำลังพยายามทำอยู่นะ"
22130-12 = "หมายถึงการทำลายฮาโลของอาริสึเหรอคะ?"
22130-13 = "......"
22130-14 = "คุณอาจจะเชื่อนะคะ... ว่าการกระทำของตัวเองคือการปกป้องมิลเลเนียมและคิโวทอส..."
22130-15 = "แต่สุดท้ายแล้วมันก็เป็นแค่การจับตัวเด็กผู้หญิงมากักตัวไว้ในเมืองร้างแล้วทำลายฮาโลของเธอค่ะ"
22130-16 = "ที่เธอพูดมันก็ไม่ได้ผิดนักหรอก แต่ว่า..."
22130-17 = "อืม ไม่สิ... เพราะเธอมีความคิดแบบนั้น ก็เลยไม่เข้าใจฉัน... และก็คงไม่ยอมรับเหมือนเคย"
22130-18 = "ใช่ค่ะ ฉันไม่เห็นด้วยค่ะ ยิ่งไปกว่านี้... คุณครูจากชาเล่ต์ก็จะไม่อยู่เฉยๆ หรอกค่ะ"
22130-19 = "ใช่ ความเป็นไปได้ที่ครูจะมาพาตัวอาริสึกลับไปมีมากถึง 99.99999% ..."
22130-20 = "แถมกองกำลังที่ดีที่สุดของมิลเลเนียมอย่าง C&C ก็คงจะอยู่กับฝั่งนั้นด้วย"
22130-21 = "ไม่มีใครที่เข้าใจฉันเลยสินะ ไม่มีเลยแม้สักคนเดียว..."
22130-22 = "ริโอะ... ถึงจะรู้อย่างนั้นแล้วแท้ๆ..."
22130-23 = "แต่ก็ไม่เป็นไรหรอก"
22130-24 = "ฮิมาริ ครั้งหนึ่งเธอเคยบอกไว้ว่ากำลังทำ <เซฟเฮ้าส์> อยู่ใช่ไหม?"
22130-25 = "...ถึงมันจะคล้ายๆ กัน แต่ถ้าจะให้พูดให้ชัดเจนขึ้น ก็คงต้องบอกว่าเอริดูแห่งนี้คือ <ปราการ> ที่สร้าง#nขึ้นเพื่อป้องกัน สกัดกั้น และโค่นล้มภัยคุกคามในอนาคต..."
22130-26 = "ริโอะ นี่คุณยัง..."
22130-27 = ""
22130-29 = ""
22130-30 = ""
22130-31 = "ถึงจะไม่มีใครเข้าใจก็ไม่เป็นไร ฉันไม่สนหรอกว่าโลกนี้จะตัดสินว่าฉันเป็นปีศาจร้ายหรืออะไรก็ตาม"
22130-32 = "ฉันแค่ทำในสิ่งที่เชื่อว่าถูกต้องก็เท่านั้น"
22130-33 = ""
22130-34 = "จากการคำนวณตัวแปรทั้งหมด และคิดพิจารณาหลายๆ สาเหตุแล้ว ความน่าจะเป็นที่ฉันจะบรรลุเป้า#nหมายมีมากกว่า 99%"
22130-35 = "ฉันเตรียมการทุกอย่างไว้เรียบร้อยแล้ว เหลือก็แค่ลงมือปฏิบัติการเท่านั้น..."
22130-36 = ""
22130-39 = "คุณริโอะคะ มีรายงานมาจากระบบเฝ้าระวังของเมืองแห่งปราการเอริดูค่ะ"
22130-40 = "อืม... ตามรอยข้อมูลมาที่นี่ได้จริงๆ ด้วยสินะ"
22130-41 = "ถ้างั้นก็ฝากด้วยนะ โทคิ"
22130-42 = "ค่ะ มาดาม"
22130-43 = ""
22130-45 = ""
22130-46 = "พอทุกอย่างจบลง ฮิมาริ... ทั้งเธอเอง..."
22130-47 = "และทั้งครูชาเล่ต์..."
22130-48 = "ก็จะ..."
22130-50 = "......"
22130-52 = ""
22130-59 = "ที่นี่ก็คือ..."
22130-60 = "เอริดู..."
22130-61 = "อาริสึจังอยู่ที่นี่..."
22130-68 = "ดีละ เรายึด <รถไฟส่งสินค้าไร้คนขับ> และมาถึงที่จุดหมายได้สำเร็จตามที่คิดไว้"
22130-69 = "อืม เวอริทัสช่วยเราไว้ได้เยอะเลย คิดไม่ถึงเลยว่าจะแฮ็กระบบรถไฟได้ง่ายๆ แบบไม่ต้องเตรียมตัวล่วง#nหน้าเลย"
22130-70 = "หลังจากที่แฮ็กบันทึกข้อมูลนักเรียนมิลเลเนียมมาได้ ทุกอย่างก็ง่ายไปหมดเลยละค่ะ!"
22130-71 = ""
22130-73 = ""
22130-74 = "กำลังกล่าวหาอะไรพวกฉันอยู่หรือเปล่าน่ะ?"
22130-75 = "เอาเถอะ ยังไงก็ระวังด้วยนะ พอผ่านเส้นทางนั้นไปก็จะออกไปสู่พื้นดินได้ จากนั้นก็ถึงเขต <เอริดู> แล้วละ"
22130-76 = "ถึงพวกเราจะคอยสังเกตการณ์อยู่ทางหน้าจอจนตาแทบจะไม่ขยับไปไหนเลยก็เถอะ~"
22130-77 = "แต่ก็อาจจะมีอันตรายอะไรที่พวกเรามองไม่เห็นก็ได้ ยังไงก็ขอให้ระวังไว้ด้วยนะ"
22130-78 = "[s] \"อื้ม ขอบใจนะ\""
22130-79 = "ก่อนอื่นเราต้องอยู่ตรงนี้เงียบๆ จนกว่า C&C จะลงสนามไปดึงความสนใจของพวกนั้นไป..."
22130-81 = ""
22130-83 = ""
22130-84 = "อ๊ายยย?! นี่มันอะไรกันเนี่ย?!"
22130-85 = "เอ๊ะ ฝีมือไม่เลวเลยนะ นี่มันโดรนหลงทางหรือเปล่า?"
22130-86 = "[s1] \"ไม่หลงทางหรอก มันตั้งใจมาหาเรา!\"\n[s2] \"นี่มัน... โดรนของริโอะ...!\""
22130-87 = "หรือว่า...! นี่เราโดนจับได้แล้วเหรอ?!"
22130-88 = "หรือว่า...! นี่เราโดนจับได้แล้วเหรอ?!"
22130-89 = "ไม่เป็นไรหรอก"
22130-91 = "เรายึดระบบของทางนั้นไว้ได้ก่อนที่จะโดนจับได้แล้วละ แถมเราก็ใช้โอกาสนี้แฮ็กเครือข่ายรอบๆ ไว้ด้วยเลย"
22130-93 = "โห... ทำอะไรแบบนี้ได้ด้วยเหรอ สุดยอดไปเลย!"
22130-94 = "ก็นะ ที่ทำได้ก็เพราะว่าเป็นเวอริทัสยังไงล่ะ ถือว่าเริ่มได้ไม่เลวเลย..."
22130-95 = "[ns] \"เอาละ! งั้นทุกคนเตรียมต่อสู้!\""
