[translation]
22150-1 = "ตอนที่ 15;กับดัก"
22150-2 = "อาสึนะ! ออกโรงค่า!"
22150-10 = "......!"
22150-21 = "ตอนนี้ละ!"
22150-33 = "ถึงจะถอยออกมาก็ไม่มีประโยชน์แล้วค่ะ!"
22150-42 = "คิดว่าจะหนีพ้นเรอะ!"
22150-46 = "(...แข็งแกร่งเหลือเกิน)"
22150-47 = "(C&C ที่ร่วมมือกันทำงานในฐานะสายลับ เป็นชมรมที่มีพลังแข็งแกร่งจริงๆ...)"
22150-48 = "(กลยุทธ์และชั้นเชิงที่สมาชิกทั้งสี่ร่วมมือกันจนกลายเป็นหนึ่งเดียว... นี่คือจุดที่แตกต่างจากกลุ่มกอง#nกำลังของโรงเรียนอื่นอย่างที่สุด)"
22150-51 = "กลยุทธ์ที่ใช้... ไม่มีจุดอ่อนให้เห็นเลยนะคะ"
22150-52 = "ถ้างั้นก็..."
22150-57 = "หัวหน้า นี่มัน...!"
22150-61 = "อะไรกันเนี่ย~? ทำไมจู่ๆ พื้นก็สั่นขึ้นมาล่ะ?!"
22150-62 = "ไม่ใช่แค่นี้นะอาคาเนะ! ฉันรู้สึกแปลกๆ ยังไงก็ไม่รู้!"
22150-63 = "ไม่ใช่แค่พื้นสั่น... แต่อาคารก็ขยับอยู่ด้วย...?"
22150-67 = "นะ...! นี่มันอะไรเนี่ย?!"
22150-68 = "หัวหน้า...!! ระยะระหว่างอาคารมัน...!"
22150-74 = "หยุดสั่น... แล้วเหรอ...?"
22150-75 = "แล้วคนอื่นๆ ล่ะ...?"
22150-81 = "การเปลี่ยนแปลงโครงสร้างของเมืองในบริเวณนี้ ทำให้รุ่นพี่ถูกปิดกั้นกับรุ่นพี่ C&C คนอื่นแล้วละค่ะ"
22150-82 = "ว่าไงนะ? ทำอะไรแบบนั้นได้ด้วยเหรอ?"
22150-83 = "ใช่ค่ะ <เอริดู> ทำหน้าที่เป็นป้อมปราการที่ขับไล่ผู้บุกรุกได้ด้วยค่ะ"
22150-84 = "สิทธิควบคุมปราการนี้ ฉันได้มาจากท่านริโอะ เพื่อเอามาใช้แยกสายลับ C&C ออกจากกันค่ะ"
22150-85 = "แบบนี้อัตราการชนะของรุ่นพี่เนรุก็ลดฮวบเลยนะคะ"
22150-86 = "........."
22150-87 = "เฮ้อ... อัตราอะไรกัน..."
22150-88 = "ไร้สาระเป็นบ้า"
22150-97 = "เฮือก?!  ดะ... เดี๋ยวนะ! ตอนนี้สัญญาณการสื่อสารมัน...!"
22150-98 = "นี่มัน..."
22150-99 = "พวกเธอจริงด้วยสินะ เวอริทัส"
22150-100 = "หรือว่าต้องเรียกว่าพวกรุ่นน้องของ 'ฮิมาริ' กันนะ"
22150-101 = "หืม? คะ... ใครน่ะ?!"
22150-109 = "สัญญาณติดต่อกับเวอริทัสมัน..."
22150-110 = "[s] \"หายไปหมดเลย\""
22150-114 = "ถึงจะคาดการณ์ไว้แล้วก็เถอะ แต่ก็มาถึงที่นี่ได้จริงๆ สินะครู"
22150-115 = "[s1] \"ริโอะ ครูอยากให้เธอหยุด...!\"\n[s2] \"ครูมาขัดขวางเธอไง\""
22150-116 = "อย่างนี้นี่เอง..."
22150-117 = "อย่างนี้นี่เอง..."
22150-118 = "คำพูดและการกระทำของฉันในตอนนั้น..."
22150-119 = "คงจะโน้มน้าวคุณและเด็กๆ ที่อยู่ตรงนี้ไม่ได้เลยสินะ"
22150-126 = "ครู..."
22150-127 = "รู้จักปัญหารถรางไหม?"
22150-128 = "ปัญหา...?"
22150-129 = "... รถราง?"
22150-130 = "ถ้าจะพูดให้เข้าใจง่ายๆ ละก็"
22150-131 = "มันคือปัญหากลืนไม่เข้าคายไม่ออกที่บังคับให้เราเลือกน่ะ ว่าเมื่อเห็นรถไฟเบรกเสียแล่นอยู่บนราง"
22150-132 = "เราจะเลือกเสียสละคนคนเดียวเพื่อช่วยคนจำนวนมาก... หรือจะเลือกให้หลายๆ คนต้องสละชีวิต#nเพื่อคนเพียงคนเดียวกันล่ะ?"
22150-133 = "ใช่แล้ว ในจังหวะนั้นต้องมีใครคนหนึ่งทำหน้าที่ดึงคันโยก"
22150-134 = "...และฉันก็แค่จะทำหน้าที่นั้นด้วยความยินดีก็เท่านั้น"
22150-135 = "ฉันไม่ได้มีเจตนาร้ายอะไร แล้วก็ไม่ได้มีจิตใจปรปักษ์ด้วย ฉันก็เพียงแค่───"
22150-136 = "เลิกพูดอะไรเข้าใจยากๆ ได้แล้ว! เอาอาริสึคืนมานะ!!"
22150-137 = "หืม...? นี่เธอ..."
22150-138 = "ฉันรู้เรื่องทั้งหมดแล้ว!"
22150-139 = "รู้หมดแล้วว่าประธานเอาเรื่องไร้สาระมาพูดตามอำเภอใจ แล้วก็พาตัวอาริสึไป!"
22150-140 = "...นั่นไม่ใช่เรื่องไร้สาระที่พูดตามใจชอบนะ"
22150-141 = "คนที่ได้รับความเสียหายจาก <ธิดาแห่งทวยเทพไร้นาม> อย่างเธอสิที่ต้องรู้ดีกว่าใคร..."
22150-142 = "ไม่รู้! ไม่รู้ๆๆๆ!"
22150-143 = "......!"
22150-144 = "พวกเราแค่จะพาตัวอาริสึกลับไปก็เท่านั้น!"
22150-145 = "พี่โมโมอิ..."
22150-146 = "โมโมอิ..."
22150-147 = "มาใช้ข้ออ้างว่าคิโวทอสจะตกอยู่ในอันตรายเพื่อที่จะจับตัวอาริสึไปแบบนี้น่ะ! ใจแคบที่สุดเลย!"
22150-148 = "รู้เอาไว้ด้วยละว่าเนื้อเรื่องในเกมที่ฉันเขียนทุกวี่ทุกวันมันมีเรื่องเลวร้ายยิ่งกว่านี้อีก!"
22150-149 = "แค่นี้น่ะเรื่องเล็กน้อยออกจะตายไป!"
22150-150 = "...ก็ใช่ ตอนนี้ฉันคงทำให้พวกเธอเข้าใจเลยไม่ได้หรอก"
22150-151 = "...ฉันรู้ดีอยู่แล้วว่าฉันคงไม่ได้รับความเข้าใจจากคนอื่นง่ายๆ"
22150-152 = "ปล่อยหุ่นรบล้ำยุค "
22150-158 = "อ๊ายย?! รสนิยมเห่ยชะมัดเลย!"
22150-159 = "ถึงจะไม่ใช่ดีไซน์แบบพื้นๆ ก็เถอะ..."
22150-164 = "...เรื่องรูปลักษณ์น่ะ มันไม่สำคัญหรอก"
22150-165 = "[s] \"ถึงจะพูดอย่างเย็นชา แต่ครูได้ยินเสียงในใจเธอหมดแล้ว! ริโอะ!\""
22150-166 = "ถึงใครจะไม่เข้าใจ... ก็ไม่เป็นไร ให้มันเป็นไปตามนั้นก็ได้"
22150-167 = "วะ... ว้ายยยย!!"
22150-168 = "[ns] \"ระวังตัวด้วยทุกคน...! มันเข้ามาแล้ว!\""
