[translation]
22230-1 = "Episode 23; Pavane for a Princess 2"
22230-2 = "\"...Failed to secure resources. System shutting down.\""
22230-3 = "Is everyone okay?!"
22230-4 = "Yuuka...!"
22230-5 = "Noa!"
22230-6 = "H-How did you get here...?"
22230-7 = "We realized how critical the situation was, Sensei!"
22230-8 = "Originally, we planned on just informing you of the city's location and keeping out of it, but..."
22230-9 = "Heeheehee. Yuuka said that wasn't enough...and we should see it through to the end."
22230-10 = "[s] \"Yuuka! You're perfect!\""
22230-11 = "P-Please...!"
22230-12 = "By the way, President!"
22230-14 = "...!"
22230-15 = "You embezzled Seminar's funds to make this city. I'm going to seriously punish you later, so you better be ready for it!"
22230-16 = "...Yuuka."
22230-17 = ""
22230-19 = ""
22230-20 = "\"Resource acquisition process error. Emergency situation. All Divi:Sion units, go to Eridu's central tower to protect the protocol executor...\""
22230-21 = ""
22230-24 = "An intruder?"
22230-25 = "That's not possible. There's no remaining troops in the city."
22230-26 = "A logic error must have occurred. I'll bring up the screen to confirm."
22230-27 = ""
22230-28 = ""
22230-29 = ""
22230-30 = ""
22230-31 = ""
22230-35 = "Oh, is that...?!"
22230-36 = ""
22230-39 = "[ns] \"...The Avant Guard! And the Engineering Department!\""
22230-40 = "The Engineering Department is back! We realized something was fishy!"
22230-41 = "There are strange machines all over the place here."
22230-42 = "This must be what the president meant about the threat coming from the ruins."
22230-43 = "Heehee... We'll have to do something about this, then."
22230-44 = "The opponents are monsters from the ruins..."
22230-45 = "...but we're engineers with our sights set on outer space."
22230-46 = ""
22230-48 = ""
22230-49 = ""
22230-50 = ""
22230-51 = ""
22230-52 = "Just in time, we've gained an ally armed with Maki's designs."
22230-53 = "Yes! The enemy of the enemy is our friend! Especially ones we've modified to be our ally!"
22230-54 = "Yes... In particular, it's equipped with firepower that could be used on an intergalactic battleship in the future."
22230-55 = "Even monsters from the ruins are no match for our Avant Guard Mk.2."
22230-56 = "Shall we go? Charge!"
22230-57 = "Yes! Let's destroy the henchmen of the ruins!"
22230-58 = "Wow!"
22230-59 = ""
22230-66 = "Modify the Avant Guard...so the intergalactic battleship weapon can..."
22230-67 = "Huh? What do you mean?"
22230-68 = "[s] \"An intergalactic battleship is everyone's dream!\""
22230-69 = "Umm...I'm not sure what you're saying, Sensei..."
22230-70 = "Incomprehensible. Unable to judge the situation."
22230-71 = "Modify and rerun the command. Followers, avoid battle with unexpected troops and gather at the central tower of Eridu..."
22230-72 = "I'm sorry, but they won't make it that far. The entrance to the tower is blocked by Eimi and the C&C members."
22230-73 = ""
22230-74 = ""
22230-75 = "[s] \"Huh?! Himari? What are you doing here?\""
22230-76 = "Heehee. I ended up here for all kinds of reasons."
22230-77 = "Himari, I thought you ran away..."
22230-78 = "Ran away? I'm disappointed you think so little of me."
22230-79 = "I had a very accurate prediction of how the situation was going to go."
22230-80 = "So I escaped the quarantine facility and came here."
22230-81 = "Like with everything else Rio does, I expected there to be a big commotion."
22230-82 = "Was I right?"
22230-83 = "..."
22230-84 = "By the way, this is Key...the AI trigger for activating the nameless priests' Artifact."
22230-85 = "If left as it is, Aris' personality will be replaced by Key... At last, the princess of the Nameless Gods will awaken, as the nameless priests wished."
22230-86 = "Th-Then...!"
22230-87 = "Himari... If that's true..."
22230-88 = "At this rate, Aris will..."
22230-89 = "But we have a way to stop that."
22230-90 = "[s] \"How? Then do it!\""
22230-91 = "Everyone did an excellent job, but time is of the essence now."
22230-93 = ""
22230-94 = ""
22230-96 = ""
22230-98 = ""
22230-100 = ""
22230-102 = ""
22230-103 = ""
22230-104 = ""
22230-107 = ""
22230-108 = "We need to stop the process before the nameless priests arrive."
22230-109 = "By activating Key, we'll awaken Aris, who is isolated in the depths of its database."
22230-110 = ""
22230-111 = "That'll be our moment to stop it."
22230-113 = ""
22230-115 = "Will that work?"
22230-116 = "And then Aris can come home with us?"
22230-117 = "Yes, it's possible. I'm sure there's diving equipment in Eridu. Right, Rio?"
22230-118 = "But it's impossible! You can't!"
22230-119 = "[s] \"Why's that?\""
22230-120 = "It's too risky. If we enter Aris' mental space, there may be no way to return."
22230-121 = "Who would be willing to even try something like that?"
22230-122 = "I'm looking at them right now. The Game Development Department and Sensei."
22230-123 = "It will be dangerous, but..."
22230-125 = "...We'll do it."
22230-126 = "We'll do whatever it takes."
22230-127 = "We just want to bring Aris home."
22230-128 = "What did I tell you?"
22230-129 = "..."
22230-130 = "Then I'm going to analyze Aris' mental space and create a gap for you."
22230-131 = "You guys are going to have to dive into the data and bring her back."
22230-132 = ""
22230-134 = ""
22230-135 = ""
22230-136 = "[ns] \"...Got it!\""
22230-138 = "Then, let us begin."
22230-143 = "...Ready."
22230-144 = "Good luck, everyone."
22230-148 = "Next Episode; What You Want to Be"
