[translation]
2300206-1 = "Trinity Surgical Procedures"
2300206-2 = "Trinity Remedial Knights Infirmary"
2300206-3 = "Thank you for helping me move the medicine today, Sensei."
2300206-4 = "There was way more missing from the documents than I thought, so it would have taken me all day if I had to organize the warehouse myself."
2300206-5 = "[s] \"It was nothing.\""
2300206-6 = "I was able to stop and catch my breath thanks to you! Heehee."
2300206-7 = "By the way, Sensei. It's slippery because the floor was mopped earlier, so be careful..."
2300206-9 = "*crash*"
2300206-10 = "S-Sensei! Are you okay?"
2300206-11 = ""
2300206-13 = "[ns] \"I'm a little banged up, but I'm okay.\""
2300206-14 = "But your knee is bleeding! We need to get you treated quickly..."
2300206-15 = "We'll have to amputate your leg immediately to prevent infection!"
2300206-16 = "[s] \"S-Stop!\""
2300206-17 = "Huh? What's the problem, Sensei?"
2300206-18 = "If we don't amputate soon, the infection will spread and cause the wound to fester."
2300206-19 = "That's what I read in an old medical book!"
2300206-20 = "[s] \"How old is this medical book?\""
2300206-21 = "I'm not sure. Maybe...500 years old?"
2300206-22 = "Don't worry! According to the book, a skilled doctor can finish the amputation in under a minute..."
2300206-23 = "We gotta do this right away before it gets worse!"
2300206-24 = "[s] \"A bandage should be enough for an injury like this.\""
2300206-25 = "Are you sure?"
2300206-26 = ""
2300206-27 = "Then at least let me disinfect the wound for you first. Please sit still."
2300206-30 = "― All right, I'm going to disinfect the wound,[wa:1020] "
2300206-32 = "― so take off your sock and don't move.[wa:10] "
2300206-35 = "― If I don't disinfect your wound properly,[wa:10] "
2300206-37 = "― you might get an infection. This is dangerous stuff.[wa:2000] "
2300206-40 = "― It might sting a little, but I know you can do it![wa:880] "
2300206-42 = "― Here we go! Let's get this cleaned up![wa:1860] "
2300206-45 = "― All right, good job.[wa:740] "
2300206-47 = "― We're almost done.[wa:10] "
2300206-50 = "― How about I[wa:420] "
2300206-52 = "― cast a spell on you, Sensei? It'll help your wound heal quickly.[wa:10] "
2300206-55 = "― Pain, pain, go away![wa:3240] "
2300206-57 = "― There! It doesn't hurt at all, right?[wa:60] "
2300206-59 = ""
2300206-60 = "Put some medicine on the wound...cover it with a bandage..."
2300206-61 = "Finished! Good job, Sensei."
2300206-62 = "Be careful not to let the bandage fall off!"
2300206-63 = "[s] \"This sure is a colorful bandage.\""
2300206-64 = "Yes, it's my favorite. Not only is it pretty, if you rub the top it smells sweet."
2300206-65 = "However, it can't be attached to large wounds or amputated areas because it's too small."
2300206-66 = "Because of that, cutting off your leg would have been bad."
2300206-67 = "[s] \"You think that's why cutting off my leg was a bad idea?!\""
