[translation]
2300302-1 = "A Hacker's Image"
2300302-2 = "Veritas Hacker's Lounge"
2300302-3 = "I stopped by Veritas' club room on my way back from taking care of Millennium School business at Seminar."
2300302-4 = "Hmm..."
2300302-5 = ""
2300302-6 = ""
2300302-7 = ""
2300302-8 = ""
2300302-9 = "Oh! Hey there, Sensei."
2300302-10 = "Yeah, I just got back from watching Eliminator 4 at the theater."
2300302-11 = "But something about it was...a bit..."
2300302-12 = "[s] \"What's that look for? Was the movie not good?\""
2300302-13 = "Should I say that the movie wasn't fun? Or perhaps it was more that there was a part I didn't like."
2300302-14 = "The movie itself was all right. The special effects were flashy, the characters stood out, and the audience enjoyed it."
2300302-15 = "Yeah...it was mostly fine, except..."
2300302-16 = "The way they depicted hackers in the movie sucked!"
2300302-17 = "[s] \"What did they get wrong?\""
2300302-18 = "Almost everything! But if I had to point out a few things...I'd start off with the costume design."
2300302-19 = "It's true that hackers prefer comfy clothes, but what's with that sloppy hoodie that the hacker in the movie was wearing? They made it look like every hacker is a computer nerd who doesn't know how to dress."
2300302-20 = "Also, the hacking scenes in the movie looked so fake."
2300302-21 = "Do you think it makes sense that a huge corporation's security, locked down with all kinds of security programs, could all be breached at once by a single hacker? Even the most talented hackers have their limits."
2300302-22 = "On top of that, who puts up an ASCII skull after a hack? Talk about corny."
2300302-23 = "I find it hard to believe that a franchise as popular as Eliminator would make such rookie mistakes."
2300302-24 = "[s] \"...Is it really that important?\""
2300302-25 = "Absolutely! It concerns the very nature of Veritas."
2300302-26 = "Popular movies showing hackers in such inaccurate ways is the reason why the public image of white-hat hackers like us is going down the drain."
2300302-27 = "We don't do our hacking for grudges or personal gain. All of Veritas seeks only truth and freedom."
2300302-28 = "But they portrayed hackers as some third-rate script kiddies, simply because that's easier for them to show in their movie. Unforgivable..."
2300302-29 = "[s] \"You totally lost me...\""
2300302-30 = ""
2300302-31 = "...It's no good. I better leave a pointed warning for the company that produced Eliminator."
2300302-32 = "Oh, I'm not going to contact the production company directly. It's simple, really. I just need to hack into their servers."
2300302-33 = "I'll use this opportunity to show them how real-life hackers differ from their fictional ones."
2300302-34 = "Let's see, the address of their home page is..."
2300302-35 = ""
2300302-36 = ""
2300302-37 = "It's protected by a powerful security program, as expected. But it's got no chance of stopping me."
2300302-38 = ""
2300302-39 = ""
2300302-41 = "...There we go. What should I edit first?"
2300302-42 = "I'll start by lowering the movie's review to one star, then lock them out of making any edits..."
2300302-43 = ""
2300302-44 = ""
2300302-45 = "Rewrite all the scripts to warn them about misrepresenting hackers..."
2300302-46 = ""
2300302-47 = ""
2300302-48 = "And put in an ASCII version of the Veritas logo for good measure... Perfect."
2300302-49 = "[s] \"...\""
2300302-50 = "Hm? Sensei, is something wrong?"
2300302-51 = "...You think what I'm doing right now is not too far off from what the hackers did in the movie?"
2300302-52 = "Don't be ridiculous! Unlike the movie, I'm not hacking for personal gain, nor using ASCII art..."
2300302-53 = ""
2300302-54 = "...Okay, maybe I am."
2300302-55 = "Let me make this clear again. Not every hacker does this!"
2300302-57 = "Afterwards, I convinced Hare to restore the homepage she hacked."
