[translation]
2300202-1 = "Painless Injection Process"
2300202-2 = "Trinity Infirmary"
2300202-3 = "Sensei. I've been thinking about how to give painless injections, like you mentioned before."
2300202-4 = "But I think giving an injection requires a lot of study."
2300202-5 = "If I practice dozens, maybe hundreds of times, I'd be as skilled as everyone else, wouldn't I?"
2300202-6 = "[s1] \"Of course.\"\n[s2] \"Hanae, you'll get better at it in no time.\""
2300202-7 = "Heehee! I want to get better at giving quick injections."
2300202-8 = "Heehee! I want to get better at giving quick injections."
2300202-9 = "For that..."
2300202-10 = "Sensei, I want you to be my practice partner for today!"
2300202-11 = "[s] Run away."
2300202-12 = "Sensei! Don't run! Act like an adult!"
2300202-13 = "[s] \"But I don't need an injection!\""
2300202-14 = "Don't worry about it. I've replaced the medicine with vitamins."
2300202-15 = "You'll become super healthy!"
2300202-16 = "All you need to do is lend me your arm."
2300202-17 = "[s] \"But...\""
2300202-18 = "Please, Sensei. It's for the students of Kivotos... Help me out just this once, please?"
2300202-20 = "[s] Give your arm reluctantly."
2300202-21 = "Thank you, Sensei!"
2300202-22 = "I'll do my best not to hurt you!"
2300202-23 = ""
2300202-24 = "Now, take a deep breath... And here it comes..."
2300202-25 = "..."
2300202-26 = "Huh? Is that a Peroro plush flying around?"
2300202-27 = "[s] \"Really? Where?\""
2300202-28 = "Dropped your guard!"
2300202-30 = "Tsk, I failed..."
2300202-31 = "[s] \"Wh-What are you doing?!\""
2300202-32 = "What? I was trying to distract you because the nurse manual told me to make the injection while the patient is unaware..."
2300202-33 = "But I failed, heh."
2300202-34 = "[s] \"It's dangerous to stick needles in people when they're not ready!\""
2300202-35 = "It's fine. Vitamins can be absorbed wherever they're injected into the body."
2300202-36 = "Now, shall we go for a second injection?"
2300202-37 = "[s] \"How many injections do you have planned?!\""
2300202-40 = "After that, my arm became riddled with injection marks."
