[translation]
2402-1 = "#title;수행부의 홍보 영상을 찍자! 2"
2402-2 = "3;카에데;03;아아, 카메라 테스트. 카메라 테스트. \n#3;a\n#3;em;[재잘]\n#3;closeup"
2402-3 = "3;카에데;03;하는 김에 마이크도 테스트~! 잘 보이고 들리나요~오?\n#3;closeup"
2402-4 = "3;카에데;00;자아, 그럼 소개를 시작할게!\n#3;closeup\n#3;greeting\n#3;em;[음표]"
2402-5 = "3;카에데;00\n#3;closeup\n#3;d\n#wait;800"
2402-6 = "3;카에데;00\n#3;a\n#wait;800"
2402-7 = "3;카에데;03;여기는 수행부, 그것도 수행부의 부장이 주로 활동하는 백귀야행 렛서팬더강의 강변!\n#3;em;[반짝]"
2402-8 = "3;카에데;00;이곳을 찾은 이유는 바로……."
2402-9 = "3;카에데;11;여기가 우리 수행부의 부장! 츠바키 선배의 수행장소 중 하나이기 때문이야!\n#3;em;[음표]\n#3;hophop"
2402-10 = "3;카에데;04;앗, 말하기 무섭게 찾았다!\n#3;em;[!]"
2402-11 = "3;카에데;04\n#3;dl\n#wait;1000"
2402-13 = "1;츠바키;07;쿠울…….\n#1;a\n#1;em;…"
2402-14 = "5;카에데;00\n#5;al\n#wait;1000"
2402-15 = "1;츠바키;07\n5;카에데;03;소개하도록 하지!\n#5;h\n#5;em;[반짝]\n#5;greeting"
2402-16 = "1;츠바키;07\n5;카에데;00;카스가 츠바키 선배! 2학년! 16세! 수행부의 부장을 맡고 있는, 잠자는 공주야!"
2402-17 = "1;츠바키;07\n5;카에데;03;츠바키 선배가 얼마나 굉장하냐면……!"
2402-18 = "1;츠바키;07\n5;카에데;04;응?\n#5;em;[반응]"
2402-20 = "1;츠바키;07\n5;카에데;02;앗, 이때 츠바키 선배의 곁으로 고양이가 한 마리가!"
2402-22 = "1;츠바키;07\n5;카에데;04;두 마리 째!\n#5;em;[!]"
2402-24 = "1;츠바키;07\n5;카에데;10;거기에 더해 강아지……. 토끼, 비둘기, 사슴 등등 다른 동물들까지?\n#5;em;[땀]\n#5;stiff"
2402-25 = "1;츠바키;07\n5;카에데;12;계속해서 늘어난다~!\n#5;hophop"
2402-26 = "1;츠바키;07\n5;카에데;12;아마 모두가 츠바키 선배의 잠자는 모습에 반해서인 게 분명해!\n#5;h"
2402-27 = "5;카에데;12\n1;츠바키;07;쿠울.\n#1;em;…\n#1;h"
2402-28 = "1;츠바키;07\n5;카에데;10;괴, 굉장해! 저렇게 많은 동물들이 모여드는데도, 흔들리지 않고 잠자는 저 자세!\n#5;em;[반짝]\n#1;h\n#5;h"
2402-29 = "1;츠바키;07\n5;카에데;10;한 점 흐트러지지 않는 저 모습이야말로, 멋진 레이디의 표본!\n#1;h\n#5;h"
2402-30 = "1;츠바키;07\n5;카에데;11;좋았어. 나도 질 수 없어!\n#5;em;[음표]\n#5;hophop\n#1;h\n#5;h"
2402-31 = "1;츠바키;07\n5;카에데;00;멋진 레이디를 꿈꾸는 수행부의 귀여운 마스코트로서! 츠바키 선배를 따라 수행하는 거야!\n#1;h\n#5;h"
2402-32 = "1;츠바키;07\n5;카에데;03;그럼 살짝, 실례합니다아~\n#1;h\n#5;h"
2402-33 = "1;츠바키;07\n5;카에데;03\n#1;h\n#5;h\n#5;m4\n#wait;1000"
2402-34 = "1;츠바키;07\n5;카에데;03\n#1;h\n#5;h\n#5;m3\n#wait;1000"
2402-35 = "1;츠바키;07\n5;카에데;03\n#1;h\n#5;h\n#5;d\n#1;d\n#wait;1000"
2402-38 = "#na;카에데;와아……."
2402-39 = "#na;카에데;츠바키 선배가 누울 때마다 바라보는 풍경은, 이런 거구나."
2402-40 = "#na;카에데;이런 풍경을 바라보면서 잠자기야말로……."
2402-41 = "#na;카에데;과연……. 이게 멋진 레이디들이 하는 수행……."
2402-42 = "#na;카에데;그럼 나도 눈을 감고 츠바키 선배처럼……."
2402-44 = "#na;카에데;……."
2402-47 = "#na;카에데;앗, 가, 간지러~"
2402-48 = "#na;카에데;잠까안~ 그렇게 뺨을 핥지 마~ 잘 수가 없다구~!"
2402-49 = "#na;카에데;으으음!"
2402-51 = "1;츠바키;07\n5;카에데;07;아, 진짜~!\n#1;a\n#5;a\n#5;em;[땀]\n#5;stiff\n#1;h\n#5;h"
2402-52 = "1;츠바키;07\n5;카에데;04;자, 핥을 거면 여기 츠바키 선배가 있으니까!\n#1;h\n#5;h"
2402-53 = "1;츠바키;07\n5;카에데;04\n#5;m3\n#1;h\n#5;h\n#wait;1000"
2402-54 = "1;츠바키;07\n5;카에데;04\n#5;greeting\n#1;h\n#5;h\n#wait;1000"
2402-55 = "1;츠바키;07\n5;카에데;04\n#1;em;…\n#1;h\n#5;h\n#wait;2500"
2402-56 = "5;카에데;04\n1;츠바키;08;으음…….\n#1;em;[///]\n#1;h\n#5;h\n#1;stiff"
2402-57 = "1;츠바키;08\n5;카에데;03;음! 보람찬 수행이었다! 그럼 다음 소개로!\n#5;hophop\n#5;em;[음표]\n#5;h\n#1;h"
2402-58 = "1;츠바키;08\n5;카에데;03\n#5;dr\n#5;h\n#1;h\n#wait;1000"
2402-60 = "1;츠바키;08\n#1;h\n#1;em;…\n#1;m3\n#wait;2500"
2402-61 = "1;츠바키;07;……쿠울?\n#1;em;[속상함]\n#1;h"
2402-63 = "3;카에데;03;자, 그럼 다음으로 소개할 건 우리 수행부의 부부장이자.\n#3;a\n#3;em;[반짝]"
2402-64 = "3;카에데;00;아름다운 레이디의 표본인 미모리 선배야!"
2402-65 = "3;카에데;04;이 시간이라면 미모리 선배는 분명 저녁밥을 만들고 있을 텐데……."
2402-66 = "3;카에데;04\n1;미모리;03;어머, 카에데 쨩? 무슨 일인가요?\n#1;ar\n#1;em;[반짝]\n#3;m5\n#3;h"
2402-67 = "1;미모리;03\n3;카에데;03;미모리 선배!\n#3;em;[음표]\n#3;hophop"
2402-68 = "3;카에데;03\n1;미모리;00;그건, 카메라……인가요?"
2402-69 = "1;미모리;00\n3;카에데;00;응! 수행부의 일상을 찍고 있어! \n#3;greeting"
2402-70 = "3;카에데;00\n1;미모리;02;수행부의 일상을……? \n#1;em;[?]"
2402-71 = "3;카에데;00\n1;미모리;00;잘은 모르겠지만, 이것도 카에데 쨩이 말한 수행의 일종인 거죠?"
2402-72 = "1;미모리;00\n3;카에데;03;맞아! 이걸로 멋진 레이디가 되어서, 음양부를 쓰러트릴 거야!\n#3;em;[반짝]\n#3;hophop"
2402-73 = "3;카에데;03\n1;미모리;02;네에……? \n#1;em;[?]\n#1;stiff"
2402-74 = "3;카에데;03\n1;미모리;00;어쨌거나 수행 힘내요. 오늘 저녁은 카레니까."
2402-75 = "3;카에데;03\n1;미모리;03;저녁 때까지 늦지 않게 동아리실로 돌아와야 한답니다?\n#1;em;[음표]"
2402-76 = "1;미모리;03\n3;카에데;03;응!\n#3;h"
2402-77 = "3;카에데;03\n1;미모리;01\n#1;dl\n#3;h\n#3;m3\n#wait;1000"
2402-78 = "3;카에데;11;봤지? 미모리 선배는 수행부의 부부장으로, 우리 밥은 물론 많은 걸 챙겨주고 있어!\n#3;em;[반짝]\n#3;hophop"
2402-79 = "3;카에데;00;미모리 선배의 꿈은 멋진 요조숙녀! 그걸 위해 수행하고 있대!"
2402-80 = "3;카에데;04;미모리 선배 또한 츠바키 선배에 지지 않을 만큼 멋진 레이디……."
2402-81 = "3;카에데;04;나도 지고 있을 순 없어. 미모리 선배처럼 되려면, 미모리 선배와 같은 수행을 해야만……."
2402-82 = "3;카에데;00;아! 좋은 생각이 났다!\n#3;em;[!]\n#3;shake"
2402-85 = "3;카에데;03;이게 미모리 선배가 만들고 있는 카레! 냄새, 짱이다!\n#3;a\n#3;em;[반짝]"
2402-86 = "3;카에데;04;잠깐 숟가락으로 한 입만…….후루룩, 챱챱."
2402-88 = "3;카에데;11;!! 맛있어!\n#3;em;[음표]\n#3;hophop"
2402-89 = "3;카에데;00;하지만 미모리 선배가 만들어준 요리를 받아먹기만 해서야, 선배처럼 될 수 없어!"
2402-90 = "3;카에데;00;그러니, 카메라 너머의 여러분! 잘 보고 있어!"
2402-91 = "3;카에데;03;나도 미모리 선배처럼 되기 위해, 카레에 어레인지를 가하는 거야!"
2402-92 = "3;카에데;11;지금도 맛있는 카레지만, 내 힘으로 더욱 맛있게 만들면……!\n#3;em;[하트]\n#3;hophop"
2402-94 = "1;미모리;09;카에데 쨩! 굉장해요! 제 카레가 200%나 더 맛있어 질 줄이야! \n#1;a\n#1;em;[반짝]\n#1;hophop"
2402-95 = "5;츠바키;03;카에데- 굉장해. 한 그릇 더 줘-\n#5;a\n#5;em;[음표]"
2402-97 = "3;카에데;11;우힛, 우히히힛.\n#3;a\n#3;em;[///]\n#3;stiff"
2402-98 = "3;카에데;00;음, 내가 보기에 카레는 무척 맛있지만. 약간 단 맛이 부족한 거 같아!"
2402-99 = "3;카에데;04;그러니 설탕을 조금 더 넣고."
2402-103 = "3;카에데;10;앗, 설탕 뚜껑이?! 왕창 넣어버렸다!\n#3;em;[?!]\n#3;shake"
2402-104 = "3;카에데;10;어, 어쩌지 이걸!"
2402-105 = "3;카에데;00;아!\n#3;em;[!]"
2402-106 = "3;카에데;03;단맛을 중화시키려면……. 짠맛을 더 넣으면 될 거야! \n#3;hophop"
2402-107 = "3;카에데;00;보통 카드 게임에서도 대미지는 그렇게 상쇄되니까!"
2402-108 = "3;카에데;00;여기에 소금을 좀 더……!"
2402-110 = "3;카에데;03;응! 됐다! 뿌듯해!\n#3;a\n#3;greeting"
2402-111 = "3;카에데;00;이걸로 미모리 선배와 같은 수행도 끝!\n#3;em;[음표]\n#3;hophop"
2402-113 = "3;카에데;03;그렇게 해서, 홍보 영상! 전부 찍었어! 선생님!\n#3;a\n#3;em;[반짝]"
2402-114 = "3;카에데;00;여기에 수행부의 전부를, 그 진수를 담았어!"
2402-115 = "[s] \"그래?\""
2402-116 = "3;카에데;11;이것만 투고하면 수행부의 우승도 확실…… 확정! 멋진 레이디 데뷔야!\n#3;hophop"
2402-117 = "3;카에데;10;헉?! 하지만 이걸 공개했다가 엄청난 인기를 끈 나머지…….\n#3;em;[!]"
2402-118 = "3;카에데;10;새로운 입부희망자가 마구마구 쇄도하면 어떡하지?!"
2402-119 = "3;카에데;07;으으음……! 그럼 어쩔 수 없네! 결정! 그 후배들을 직접 이끌어주는 멋진 레이디 선배가 될 수밖에! 이히힛!\n#3;em;[///]\n#3;stiff"
2402-120 = "[s1] \"다 좋은데 말이야.\"\n[s2] \"카에데, 뒤에.\""
2402-121 = "3;카에데;04;응? 뒤? 왜애?\n#3;em;[?]"
2402-122 = "3;카에데;04;응? 뒤? 왜애?\n#3;em;[?]"
2402-123 = "2;츠바키;00\n3;카에데;04\n#2;a\n#wait;1500"
2402-124 = "3;카에데;04"
2402-125 = "2;츠바키;02;(축축끈적찝찝)고양이…… 강아지……. 할짝할짝 지옥의 연쇄…….\n#3;m4\n#2;em;…\n#2;h"
2402-126 = "3;카에데;10"
2402-127 = "2;츠바키;03;카.에.데~~\n#2;em;[반응]\n#3;stiff\n#2;h"
2402-128 = "5;미모리;00\n3;카에데;10\n#5;a\n#wait;1500"
2402-129 = "2;츠바키;03\n3;카에데;10"
2402-130 = "5;미모리;08;카에데 쨩. 동아리실 부엌의 카레에 손을 댄 거, 카에데 쨩이죠?\n#2;m1\n#3;m3\n#5;em;[반응]\n#5;h"
2402-131 = "2;츠바키;03\n3;카에데;10"
2402-132 = "5;미모리;09;자, 여기 앉아요. 저, 약간 진심으로 화났으니까요.\n#5;greeting\n#5;em;[반짝]\n#5;h"
2402-133 = "2;츠바키;03\n5;미모리;09\n3;카에데;10;저, 저건 츠바키 선배와 미모리 선배가 진짜 화났을 때 짓는 표정!\n#3;em;[?!]\n#3;shake"
2402-134 = "2;츠바키;03\n5;미모리;09\n3;카에데;14;이대로 있다간 지옥의 설교 5시간 풀코스……!\n#3;em;[속상함]"
2402-135 = "#2;hide\n#5;hide\n3;카에데;14;히, 히잉. 도, 도와줘. 선생님~!\n#3;hophop\n#3;closeup\n#3;em;[!]"
2402-136 = "[s] \"자업자득입니다.\""
2402-137 = "1;츠바키;03\n5;미모리;09\n3;카에데;14\n#1;a\n#3;stiff\n#3;em;…\n#5;a\n#1;closeup\n#3;closeup\n#5;closeup\n#wait;2500"
2402-138 = "#all;hide\n#na;카에데;으, 으아앙~!\n#fontsize;100"
2402-140 = "#na;(그렇게 수행부의 설교지옥이 시작되었다.)"
2402-141 = "#ENDING;수행부의 홍보 영상을 찍자!"
