[translation]
25-1 = "#na;R50 신규 배경 이펙트 테스트 연출"
25-2 = "3;시로코;01\n#3;h\n#na;검은재"
25-3 = "3;시로코;01\n#3;h\n#na;붉은재"
25-4 = "3;시로코;01\n#3;h\n#na;붉은화면"
25-5 = "3;시로코;01\n#3;h\n#na;섬광"
25-6 = "3;시로코;01\n#3;h\n#na;섬광소리"
25-7 = "3;시로코;01\n#3;h\n#na;오른쪽총격"
25-8 = "3;시로코;01\n#3;h\n#na;아래스크롤1.5"
25-9 = "3;시로코;01\n#3;h\n#na;아래스크롤1.0"
25-10 = "3;시로코;01\n#3;h\n#na;아래스크롤0.5"
25-11 = "3;시로코;01\n#3;h\n#na;위스크롤1.5"
25-12 = "3;시로코;01\n#3;h\n#na;위스크롤1.0"
25-13 = "3;시로코;01\n#3;h\n#na;위스크롤0.5"
25-14 = "3;시로코;01\n#3;h\n#na;왼쪽스크롤1.5"
25-15 = "3;시로코;01\n#3;h\n#na;왼쪽스크롤1.0"
25-16 = "3;시로코;01\n#3;h\n#na;왼쪽스크롤0.5"
25-17 = "3;시로코;01\n#3;h\n#na;오른쪽스크롤1.5"
25-18 = "3;시로코;01\n#3;h\n#na;오른쪽스크롤1.0"
25-19 = "3;시로코;01\n#3;h\n#na;오른쪽스크롤0.5"
25-20 = "#na;R50 신규 배경 이펙트 테스트 종료"
