[translation]
2600703-1 = "อายาเนะในผ้าห่ม"
2600703-2 = "(คุณครูไปที่ห้องพักของอายาเนะเพื่อดูว่ามีอะไรเกิดขึ้นกับอายาเนะหรือไม่)"
2600703-3 = ""
2600703-9 = "(ไม่มีใครตอบ...)"
2600703-10 = ""
2600703-13 = "งือ... งืมมม...? เซริกะจัง..."
2600703-14 = "พวกรุ่นพี่ให้เซริกะจังมาเหรอ...?"
2600703-15 = "อืม... ขอโทษนะ... ขอนอนต่ออีกห้านาทีนะ..."
2600703-16 = ""
2600703-19 = "(....)"
2600703-20 = ""
2600703-23 = "ขอนอนต่ออีกแค่ห้านาทีเอง..."
2600703-24 = "ถึงเซริกะจะมาปลุกเอง วันนี้ฉันก็จะไม่ยอมลุกไปไหนทั้งนั้นแหละ"
2600703-25 = ""
2600703-28 = "วันนี้ไม่ยอมแพ้เลยนะคะ เซริกะจัง..."
2600703-29 = "แต่ก็ไม่มีประโยชน์หรอกค่ะ วันนี้ฉันจะไม่ออกไปไหนทั้งนั้น เซริกะจังยอมแพ้เถอะ..."
2600703-30 = ""
2600703-33 = "[ns] \"....\""
2600703-35 = "[ns] เปิดประตูเข้าไป"
2600703-36 = ""
2600703-42 = "(เมื่อเปิดประตูเข้าไป \"บางอย่าง\" บนที่นอนก็ดึงดูดสายตาให้คุณครูหันไปมอง...)"
2600703-43 = ""
2600703-48 = "[ns] \"....\""
2600703-49 = "ฉันได้ยินเสียงเปิดประตูนะคะ... เข้ามาถึงในห้องเลยเหรอคะ เซริกะจัง"
2600703-50 = "แต่ฉันบอกแล้วนี่คะ... ใครก็เอาฉันออกจากผ้าห่มนี่ไม่ได้..."
2600703-51 = "ฉันจะนอนชดเชยที่นอนไม่พอ..."
2600703-52 = "ที่นี่คือฐานลับของฉัน..."
2600703-53 = "[s] \".....\""
2600703-55 = "[ns] ลองเขย่าอายาเนะดู"
2600703-56 = ""
2600703-59 = "อึก... เหมือนจะเบามือกว่าปกติ แต่ก็แรงอยู่ดี..."
2600703-60 = "แต่ว่าแค่นี้ไม่ทำให้ฐานทัพของฉันหวั่นไหวได้หรอก...!"
2600703-61 = "[s] ลองเขย่าอายาเนะดู"
2600703-62 = ""
2600703-65 = "นี่ เซริกะจัง..."
2600703-66 = "วันนี้ยอมแพ้ไปดีกว่ามั้ยคะ..."
2600703-67 = "ถึงจะเป็นฉันก็เถอะ... แต่มันก็มีขีดจำกัดอยู่เหมือนกันนะ"
2600703-68 = "[s] ลองเขย่าอายาเนะดู"
2600703-69 = ""
2600703-73 = "..."
2600703-74 = "เซ...ริ...กะ...จัง!!"
2600703-75 = "ฉันบอกไปแล้วนะ... ว่าให้หยุดไงเล่า!"
2600703-76 = ""
2600703-79 = "ทำไมไม่ฟังที่คนอื่นพูด...!!"
2600703-80 = ""
2600703-82 = "บ้าง... เลย...ล่ะ..."
2600703-83 = ""
2600703-86 = "เอ๊ะ...?"
2600703-87 = "[s1] \"ว่าไง อายาเนะ...\"\n[s2] \"โทษทีๆ ครูไม่ใช่เซริกะหรอกนะ\""
2600703-88 = "เอ๊ะ...?"
2600703-89 = "เอ๊ะ...?"
2600703-90 = "อะ... อืม..."
2600703-91 = "อะ...อรุณสวัสดิ์ค่ะ คุณครู... ทำไมคุณครูถึงมาอยู่ที่นี่..."
2600703-92 = "เอ๊ะ...? MOMOTALK เหรอคะ?"
2600703-93 = ""
2600703-96 = "อ่า..."
2600703-97 = "อะไรกันเนี่ย... คงเผลอนอนทับแล้วไปโดนปุ่มเข้าน่ะค่ะ..."
2600703-100 = ""
2600703-101 = "คะ...คุณครูคะ..."
2600703-102 = "คือว่า... เอ่อ... คือว่ามัน..."
2600703-103 = "[s3] \"รีบออกไปเร็ว ทุกคนรออยู่นะ\"\n[s4] \"ข้าวพร้อมแล้ว รีบไปกินข้าวกันเถอะ\""
2600703-104 = ""
2600703-105 = ""
2600703-107 = ""
2600703-108 = "ค่ะ..."
