[translation]
2600802-1 = "Did You See? I Succeeded!"
2600802-2 = "I went to the Beach Shack to meet Shizuko."
2600802-3 = "Oh, Sensei!"
2600802-4 = "I've been waiting for you for so long!"
2600802-5 = "[s] \"You're lively, as usual.\""
2600802-6 = "Of course!"
2600802-7 = "As the owner and the face of Momoyodou, I have to be upbeat at all times! "
2600802-8 = "[s] \"So what's the reason you called me?\""
2600802-9 = "Wow, seriously? Do you always have to be so quick to business?"
2600802-10 = "We're at the beach, during the peak of the summer!"
2600802-11 = "And the Beach Shack is getting busy!"
2600802-12 = "Can you play along at least a bit?!"
2600802-13 = "[s1] \"I don't really know what you mean, but okay!\" \n[s2] \"Hm... Seems like a lot of work.\""
2600802-16 = "Ugh... Nevermind!"
2600802-17 = "Stop teasing me, Sensei!"
2600802-18 = "You'll take me seriously when you hear what I have to say!"
2600802-19 = "Then you won't even have to pretend to play along!"
2600802-20 = ""
2600802-22 = ""
2600802-24 = "See, this is a Momoyodou franchise location..."
2600802-25 = "...the Beach Shack!"
2600802-27 = "I've got nothing to hide!"
2600802-28 = "I've nearly achieved franchising through business contracts!"
2600802-29 = "I've partnered with all the Lost Paradise resorts!"
2600802-31 = "And I've picked out the best services and products from each of them..."
2600802-32 = "...and introduced them here at the Beach Shack!"
2600802-33 = "By managing each branch directly as if it's a flagship store,"
2600802-35 = "we've achieved unprecedented profits by harmonizing specialized products"
2600802-36 = "according to the characteristics of each branch"
2600802-37 = "along with common products that can be found anywhere!"
2600802-39 = "Momoyodou's revenue sources are going to be a trade secret from here on out."
2600802-40 = "The drastic increase can't be compared to anything that's come before!"
2600802-41 = "With this momentum, we're going to spread the name of Momoyodou everywhere!"
2600802-42 = "It'll be known all over Kivotos!"
2600802-43 = "You could call it global sales marketing!"
2600802-44 = "[s3] \"That was a pretty lengthy explanation.\"\n[s4] \"That was very impressive, Shizuko.\""
2600802-47 = "You're supposed to praise my business acumen, Sensei!"
2600802-48 = "Ugh! Why do I still feel like you're making fun of me?"
2600802-49 = "You've already visited a few branches? R-Really?"
2600802-50 = "So, how were they? "
2600802-51 = "What did you think of the brand new Momoyodou summer services?"
2600802-52 = "[s] \"I liked them, but it made me miss the previous Momoyodou services.\""
2600802-53 = "Previous services? What could be better than what we're doing now?"
2600802-54 = "Oh...you mean the scatterbrain service and those coordinated performances?"
2600802-55 = "Th-That's...I don't think they were very efficient..."
2600802-56 = "You could say they've dropped down on the priority list. "
2600802-57 = "Or maybe I've simply outgrown them."
2600802-58 = "We don't have the resources..."
2600802-59 = "...to put time into such trivial things."
2600802-60 = "It was a hard decision, but I had to make it. Heehee."
2600802-61 = "[s] \"Shizuko, are you getting enough rest these days?\""
2600802-62 = "Wh-What do you mean...?!"
2600802-63 = "Do I seem strange for some reason?"
2600802-64 = "[s5] \"You used to always look so cute serving customers.\" \n[s6] \"The bigger the franchise gets, the less time you get to serve customers.\""
2600802-67 = "Wh-What?"
2600802-68 = " S-So...about that...!"
2600802-69 = "I had never seen Shizuko's face turn so red before."
2600802-70 = "I-I remembered something I have to do! "
2600802-71 = "I have an intelligent, gorgeous, and smart acquaintance waiting for me at the business department! "
2600802-72 = "I-I'll see you tomorrow!"
2600802-73 = ""
2600802-75 = ""
2600802-77 = "Shizuko ran off somewhere."
2600802-78 = "I worried a little about Shizuko's reaction, but returned to the resort in the end."
