[translation]
2600606-1 = "When You Wish Upon a Meteor"
2600606-2 = "Schale Building Entrance, Late Night"
2600606-3 = "I've been waiting for you, Sensei!"
2600606-4 = "I was so excited for today that I couldn't sleep... I almost overslept."
2600606-5 = "I'm so glad that I'm able to watch the meteor shower like this."
2600606-6 = "Come on, let's hurry to the roof before it's too late!"
2600606-8 = "Roof of the Schale Building, Late Night"
2600606-9 = "Phew, it looks like it hasn't started yet."
2600606-10 = "Are you cold, Sensei?"
2600606-11 = "It's quite chilly late at night, so it's a good idea to bundle up."
2600606-12 = "Heehee. Would you like a cup of tea?"
2600606-13 = "[s] \"Thank you.\""
2600606-14 = ""
2600606-15 = ""
2600606-16 = ""
2600606-17 = ""
2600606-18 = "For some reason...I feel a bit shy being alone with you like this in the middle of the night."
2600606-19 = "We won't need the astronomical telescope I brought with me to observe the meteor shower..."
2600606-20 = "Wh-What should we talk about to pass the time?"
2600606-21 = "[s] \"Nodoka, look up.\""
2600606-22 = "...What?"
2600606-26 = "― Wow, it's a shooting star! Oh... Over there! And over there![wa:3500] "
2600606-29 = "― The sky is full of shooting stars! Meteors are falling like rain![wa:3440] "
2600606-31 = "― I can't believe I'm seeing this with my own two eyes... It's like a dream.[wa:3060] "
2600606-34 = "― A wish? No... I'm okay for today.[wa:5930] "
2600606-37 = "― I'm content enjoying this beautiful view with someone important...[wa:600] "
2600606-39 = "― If I wish for something more, the stars might grow angry with me...[wa:990] "
2600606-42 = "― I'm totally satisfied for now.[wa:1150] "
2600606-45 = "But I wonder how the story of wishing on a shooting star came to be."
2600606-46 = "It's a beautiful concept, but it's just a celestial event that has nothing to do with people's wishes..."
2600606-47 = "What do you think, Sensei?"
2600606-48 = "(I didn't answer. I was already falling asleep.)"
2600606-49 = "Hey, you can't fall asleep here!"
2600606-50 = "Seriously! Sensei!"
2600606-52 = "I watched the night sky with Nodoka until the meteor shower ended."
