[translation]
2600903-1 = "งานพาร์ทไทม์ใหม่"
2600903-2 = "สำนักงานชาเล่ต์"
2600903-3 = "(เช้าวันรุ่งขึ้น ระหว่างที่คุณครูกำลังทำงานในสำนักงาน...)"
2600903-4 = ""
2600903-8 = ""
2600903-10 = "ไม่ไหวหรอกค่ะ...!"
2600903-11 = "ถึงจะได้ยินมาว่าที่นั่นเป็นคาเฟ่คอนเซ็ปต์อ่อนหวานที่ไม่มีลูกค้ามากเท่าไรก็เถอะ..."
2600903-12 = "แต่ฉันไม่รู้มาก่อนเลยค่ะว่ามันเป็นเมดคาเฟ่!"
2600903-13 = "ฉันอุตส่าห์เชื่อใจคุณครู... อุตส่าห์เชื่อใจคุณครูแท้ๆ...!"
2600903-14 = "[s1] \"ใจเย็นๆ ก่อนนะยูสึ\"\n[s2] \"ออกมาระหว่างทำงานพาร์ทไทม์เหรอเนี่ย?\""
2600903-17 = "ไม่ค่ะ ฉันกำลังฝึกต้อนรับลูกค้าก่อนที่จะเปิดร้าน..."
2600903-18 = "แต่คุณเจ้าของร้านบอกว่าตอนเสิร์ฟอาหารในเมดคาเฟ่ ฉันต้องทำท่าน่ารักๆ ด้วย..."
2600903-19 = "...ฉันก็เลยหนีออกมาค่ะ"
2600903-20 = ""
2600903-22 = ""
2600903-23 = "ทะ... ทำยังไงดีคะ? ฉันหายตัวมาระหว่างเทรนงานแบบนี้ คุณเจ้าของร้านต้องเป็นห่วงแน่เลย..."
2600903-24 = "[s] \"ครูจะไปช่วยอธิบายที่ร้านให้เอง\""
2600903-25 = "แง... ขอบคุณนะคะ"
2600903-27 = "[ns3] \"ไม่คิดเลยว่าจะลำบากใจมากขนาดนี้...\"\n[ns4] \"ครูขอโทษที่ไม่ได้อธิบายให้ดีก่อนนะ\""
2600903-30 = "ไม่หรอกค่ะ... ปัญหาอยู่ที่ฉันที่ยังกลัวคนแปลกหน้ามากกว่าค่ะ..."
2600903-31 = "พนักงานทุกคนในคาเฟ่ต่างก็ใจดีอย่างที่คุณครูพูดไว้ค่ะ แต่ไม่รู้ว่าทำไมทุกคนถึงเบิกบานและก็#nกระตือรือร้นกันได้ขนาดนั้น..."
2600903-32 = "ฉันยังแนะนำตัวไม่เสร็จเลย แต่ก็ได้ใส่ชุดเมดแล้ว แล้วก็เริ่มเทรนงานโดยที่ไม่รู้ตัวเลยค่ะ..."
2600903-33 = "ตอนที่ได้ยินว่าต้องใส่ชุดเมดออกไปอยู่ต่อหน้าคนที่ไม่รู้จัก ฉันแทบจะไปไม่เป็นเลย—"
2600903-34 = "[s] \"ใจเย็นก่อนนะยูสึ\""
2600903-35 = "ค่ะ... ได้ค่ะ..."
2600903-36 = "แต่จะทำยังไงดีคะ... นั่นเป็นร้านที่คุณครูแนะนำให้แท้ๆ แล้วฉันก็ไม่อยากทำให้พนักงานที่มาชวนฉัน#nคุยอย่างใจดีต้องผิดหวังด้วย..."
2600903-37 = "ถึงฉันจะไม่กล้าคุยกับคนแปลกหน้า แต่ถ้าให้ทำท่าน่ารักๆ ก็น่าจะพอไหวอยู่..."
2600903-38 = "[s] \"ลองฝึกเอาก็น่าจะได้นะ\""
2600903-39 = "ฝะ... ฝึกเหรอคะ...?"
2600903-40 = "[s5] \"ก่อนอื่นมาฝึกการเป็นเมดหลักสูตรพิเศษกับคนที่คุ้นเคยก่อนดีกว่า\"\n[s6] \"คิดว่าครูเป็นนายท่านในเมดคาเฟ่แล้วกัน!\""
2600903-43 = "ให้ฉันฝึกเป็นเมดโดยมีคุณครูเป็นนายท่านเหรอคะ...?"
2600903-44 = "...แบบนั้นอาจจะได้ผลก็ได้นะคะ คุณครูไม่ได้เป็นคนแปลกหน้า ฉันก็น่าจะประหม่าน้อยลงหน่อย..."
2600903-45 = "...และให้เห็นท่าทางที่น่าอายบ้างก็ไม่น่าจะเป็นอะไร"
2600903-46 = "ถ้างั้น... ฮานาโอกะ ยูสึจะพยายามค่ะ!"
2600903-48 = "(จากนั้นคุณครูก็เริ่มฝึกฝนการเป็นเมดกับยูสึ)"
2600903-49 = ""
2600903-50 = "ชะ... ชะ... ชะ... เชิญค่ะ นะ... นายท่าน!"
2600903-51 = "[s] \"ผิดแล้ว!\""
2600903-52 = "คะ... คะ? ผิดตั้งแต่ตอนทักทายเลยเหรอคะ...?"
2600903-53 = "[s7] \"ที่ที่เมดอยู่คือบ้านของนายท่าน...\"\n[s8] \"ดังนั้นต้องไม่ใช่ 'เชิญค่ะ' แต่เป็น 'กลับมาแล้วเหรอคะ?' สิ!\""
2600903-56 = "ยะ... อย่างนั้นเหรอคะ ไม่รู้เลยว่าต้องละเอียดขนาดนี้..."
2600903-57 = "งั้นก็... กลับมาแล้วเหรอคะนายท่าน?"
2600903-59 = ""
2600903-60 = "ขะ... ข้าวห่อไข่ที่สั่งไว้ได้แล้วค่ะ..."
2600903-61 = "[s] \"หืม จบแค่นี้เหรอ?\""
2600903-62 = "คะ... คะ...? ฉันลืมอะไรไปตรงไหนเหรอคะ?"
2600903-63 = "[s] \"ลืมร่ายคาถาให้อาหารอร่อยขึ้นไง\""
2600903-64 = "คะ... คาถาที่ทำให้อาหารอร่อยขึ้นเหรอคะ...?"
2600903-65 = "<เจ้าข้าวห่อไข่ จงอร่อยขึ้น โมเอะโมเอะ คิ้ว>...?"
2600903-66 = "พะ... พูดแบบนี้แล้วอาหารจะอร่อยขึ้นจริงๆ เหรอคะ..."
2600903-67 = "[s9] \"อร่อยขึ้นแน่นอน\"\n[s10] \"อาหารมันจะเต็มไปด้วยความจริงใจของยูสึไง!\""
2600903-70 = "ถ้าคุณครูว่าอย่างนั้นละก็..."
2600903-71 = "จะ... เจ้าข้าวห่อไข่~ จงอร่อยขึ้น โมเอะโมเอะ คิ้ว คิ้ว!"
2600903-73 = ""
2600903-76 = ""
2600903-77 = ""
2600903-78 = ""
2600903-79 = ""
2600903-80 = "อะ... อ๊าย??! ขะ... ขอโทษค่ะ...! เผลอทำหกจนได้..."
2600903-81 = "ไม่ได้เลอะเสื้อผ้าใช่มั้ยคะ? ขอโทษจริงๆ นะคะ..."
2600903-82 = "...คะ? กลายเป็นว่าชอบที่ฉันเผลอทำพลาดแบบนั้นเหรอคะ...?"
2600903-83 = "เมื่อกี้ที่ฉันทำมันสุดยอดมาก ช่วยชูความโมเอะของเมดโก๊ะๆ กังๆ ไว้ได้งั้นเหรอคะ...?"
2600903-84 = "โลกของเมดนี่ช่าง... ลึกซึ้งจังเลยนะคะ"
2600903-90 = "ต้องใช้พลังงานมากกว่าที่คิดไว้อีกค่ะ..."
2600903-91 = "พอได้ฝึกต่อหน้าคุณครูหลายๆ ครั้ง ฉันว่าตอนนี้ตัวเองน่าจะรวบรวมความกล้าในการพูดต่อหน้าลูกค้า#nแปลกหน้าได้บ้างแล้วค่ะ..."
2600903-92 = "ถึงจะไม่รู้ว่าอยู่หน้างานจริงๆ แล้วจะเป็นยังไงก็เถอะ..."
2600903-93 = "วันนี้คุณครูช่วยฉันไว้หลายอย่างเลย ขอบคุณมากๆ นะคะ"
2600903-94 = "แล้วก็... ถึงตอนนี้จะยังไม่คล่อง แต่ถ้าต่อไป... พอฉันคุ้นเคยแล้ว..."
2600903-95 = "หากคุณครูมีเวลา ช่วยแวะมาร้านที่ฉันทำงานพาร์ทไทม์บ้างนะคะ"
2600903-96 = "แล้วตอนนั้นฉันจะ... ต้อนรับเป็นอย่างดีเลยค่ะ"
