[translation]
2600905-1 = "#title;캐비닛 안의 불청객"
2600905-2 = "#na;(유즈가 아르바이트를 하는 메이드 카페 근처를 지날 일이 있어 가게를 방문해 보았다.)"
2600905-7 = "4;유즈 메이드;02\n#4;a\n#wait;1000"
2600905-8 = "4;유즈 메이드;10\n#4;em;[!]\n#4;jump\n#wait;1000"
2600905-9 = "4;유즈 메이드;09\n#4;stiff\n#wait;1000"
2600905-10 = "#st;[0,0];instant;1;"
2600905-12 = "4;유즈 메이드;09\n#4;d\n#wait;1000"
2600905-14 = "3;유즈 메이드;02;오신다는 이야기는 듣긴 했지만 정말로 오실 줄이야……\n#fontsize;50\n#3;closeup\n#3;a"
2600905-15 = "3;유즈 메이드;09;다, 다녀오셨어요. 주인님……? 카, 카페 <메이드라마틱>입니다……!\n#3;closeup\n#3;greeting"
2600905-16 = "[s1] \"다녀왔어, 유즈.\"\n[s2] \"일은 잘하고 있었어?\""
2600905-19 = "3;유즈 메이드;10;네, 넵! 아직 부족한 부분은 많지만…… 선생님께서 도와주신 덕분에……\n#3;closeup\n#3;jump"
2600905-20 = "#st;[0,0];instant;1;"
2600905-22 = "3;유즈 메이드;10\n#3;closeup\n#3;d\n#wait;1000"
2600905-24 = "3;뚱뚱한 로봇 점장;01\n#3;a\n#wait;1000"
2600905-25 = "3;뚱뚱한 로봇 점장;01;아, 선생님! 오랜만에 방문해 주시는군요."
2600905-26 = "3;뚱뚱한 로봇 점장;01;좋은 학생을 소개해 주셔서 감사합니다. '여왕님' 에게는 여러모로 많은 도움을 받고 있어요."
2600905-27 = "[s] \"여왕님……?\""
2600905-28 = "3;유즈 메이드;09;그, 그게…… 그러니까…… 가게에서는 본명 말고 닉네임을 써야 한다고 해서……\n#3;em;[///]\n#3;stiff"
2600905-29 = "3;유즈 메이드;06;습관처럼 게임에서 쓰던 닉네임을 적었는데, 어째서인지 다들 여왕님이라고 부르기 시작해서……"
2600905-30 = "3;뚱뚱한 로봇 점장;01;메이드 카페의 캐릭터는 독특할수록 좋으니까요. 하하!\n#3;em;[음표]"
2600905-31 = "3;뚱뚱한 로봇 점장;01;여하튼 처음에는 하도 긴장을 하기에 걱정이 많았는데…… 접객도 곧잘 실수 없이 해내고, 손님들에게도 인기가 많아서 다행이었어요."
2600905-32 = "3;뚱뚱한 로봇 점장;01;게다가 지난번에는 카페의 전산 프로그램이 고장 나서 발을 구르고 있었는데, 여왕님이 버그가 난 부분을 해결해 주어서 한숨 놓을 수 있었습니다."
2600905-33 = "3;뚱뚱한 로봇 점장;01;그때만큼은 진짜 '여왕님'이라고 부르고 싶었을 정도였다니까요. 하하핫!\n#3;em;[재잘]\n#3;hophop"
2600905-34 = "3;유즈 메이드;04;아우우……\n#3;stiff"
2600905-35 = "[s] \"새 아르바이트에 잘 적응한 것 같아서 다행이네.\""
2600905-36 = "3;유즈 메이드;10;네, 넵……!\n#3;jump"
2600905-37 = "3;유즈 메이드;06;그, 그럼, 선생님…… 아니, 주인님. 지금 바로 자리로 안내해 드리겠습니다……!\n#3;greeting"
2600905-39 = "#na;(하지만 점장이 말한 것과는 달리 유즈는 지켜보는 내내 실수를 계속 반복하였다……)"
2600905-41 = "2;유즈 메이드;01\n#2;a\n#wait;1000"
2600905-42 = "2;유즈 메이드;02;주, 주문하신 메이드라마틱 특제 오므라이스 나왔습니다……!\n#2;greeting"
2600905-43 = "#na;손님 A;어라? 제가 주문한 건 메론소다뿐인데요……?"
2600905-44 = "2;유즈 메이드;10;죄, 죄송합니다……! 지금 바로 다시 가져올게요……!\n#2;stiff"
2600905-45 = "#all;hide\n3;유즈 메이드;02\n#3;a"
2600905-46 = "3;유즈 메이드;09;그, 그럼, 지금부터 음식이 맛있어지는…… 마법의 주문을 걸어드릴게요……"
2600905-47 = "3;유즈 메이드;06;맛있어져라………\n#3;stiff"
2600905-48 = "3;유즈 메이드;10;………자오리크!\n#3;closeup"
2600905-49 = "#na;손님 B;뭔가…… 다른 주문이 걸린 것 같은데요."
2600905-51 = "#st;[0,0];instant;1;"
2600905-53 = "5;유즈 메이드;09\n#5;a\n#wait;1000"
2600905-54 = "5;유즈 메이드;09\n#5;m4\n#wait;700"
2600905-55 = "5;유즈 메이드;10\n#5;falldownR\n#wait;1000"
2600905-56 = "5;유즈 메이드;10\n#5;m3\n#5;greeting\n#wait;1000"
2600905-57 = "5;유즈 메이드;08\n#5;em;[?!]\n#5;shake\n#wait;1000"
2600905-58 = "5;유즈 메이드;08\n#5;falldownR\n#wait;1500"
2600905-60 = "#na;유즈 메이드;우, 우앗. 죄송해요……!"
2600905-61 = "#na;손님 C;아아…… 끈적끈적한 주스가 셔츠에 잔뜩……"
2600905-62 = "3;유즈 메이드;04;지, 지금 바로 닦아드릴게요…… 정말 죄송합니다……!\n#3;stiff\n#3;a"
2600905-63 = "3;뚱뚱한 로봇 점장;01\n#3;a"
2600905-64 = "#st;[0,0];instant;1;"
2600905-66 = "3;뚱뚱한 로봇 점장;01\n#3;em;[...]\n#wait;2500"
2600905-68 = "3;뚱뚱한 로봇 점장;01;……이상하네. 평소와는 다르게 오늘의 여왕님은 실수가 잦은걸."
2600905-69 = "3;뚱뚱한 로봇 점장;01;여왕님, 잠시 이쪽으로 와 주시겠어요?"
2600905-70 = "3;유즈 메이드;06;우으…… 죄송합니다. 제가 실수로 손님들에게 실례를 거듭해서……\n#3;em;[훌쩍]"
2600905-71 = "3;뚱뚱한 로봇 점장;01;괜찮아요. 그보다 컨디션이 나쁜 게 아닌가요?\n#3;em;[땀]"
2600905-72 = "3;뚱뚱한 로봇 점장;01;오늘따라 뭔가 잔뜩 긴장한 것처럼 보이는데……"
2600905-73 = "3;유즈 메이드;09;그게…… 아무것도 아니에요.\n#3;stiff"
2600905-74 = "#st;[0,0];instant;1;"
2600905-76 = "3;유즈 메이드;02\n#wait;1000"
2600905-78 = "3;유즈 메이드;00\n#3;stiff\n#wait;1000"
2600905-80 = "3;뚱뚱한 로봇 점장;01;아무 일도 아니라면 다행이지만……"
2600905-81 = "3;뚱뚱한 로봇 점장;01;마침 곧 휴식 시간이니, 먼저 휴게실에 가서 한숨 돌리고 오세요."
2600905-82 = "3;유즈 메이드;04;네…….\n#3;em;[속상함]\n#3;stiff"
2600905-83 = "#st;[0,0];instant;1;"
2600905-85 = "3;유즈 메이드;04\n#3;d\n#wait;1000"
2600905-87 = "[ns] \"평소에는 이런 경우가 없었나요?\""
2600905-88 = "3;뚱뚱한 로봇 점장;01;그러게요. 첫날 이후로는 성실하게 실수 없이 잘 해왔으니까요.\n#3;a"
2600905-89 = "3;뚱뚱한 로봇 점장;01;오후에는 별일 없어야 할 텐데……\n#3;em;[한숨]"
2600905-94 = "#na;(……하지만 유즈는 휴게 시간이 끝날 때까지 돌아오지 않았다.)"
2600905-95 = "[ns] 유즈를 찾으러 간다."
2600905-97 = "#na;(가게 내부를 모두 찾아보았지만, 유즈의 모습은 어디서도 보이지 않았다.)"
2600905-98 = "#na;(뒷문을 통해 골목으로 나가보니……)"
2600905-100 = "#st;[0,0];instant;1;"
2600905-102 = "#place;카페 <메이드라마틱> 뒷골목"
2600905-104 = "#na;유즈 메이드;우으으…… 이제 그만 비켜주세요……"
2600905-105 = "#st;[0,0];instant;1;"
2600905-108 = "#na;유즈 메이드;빨리 가게로 돌아가야 하는데…… 치마가 무거워……"
2600905-109 = "[ns] \"유즈……?\""
2600905-112 = "#st;[-1200,-530];serial;60;[wa:1300]― 저기, [wa:1300]그러니까……[wa:80] "
2600905-114 = "#st;[-1200,-630];serial;60;[wa:500]― 자고 있는 사이에, [wa:1200]들어와 [wa:400]버린 것 같아서……"
2600905-117 = "[ns] \"어째서 휴게실에서 쉬지 않고 캐비닛 안에……?\""
2600905-118 = "#st;[-1200,-530];serial;60;[wa:1900]― 그게…… [wa:1700]휴게실에는 [wa:1400]다른 분들도 [wa:800]계시니까……"
2600905-120 = "#st;[-1200,-630];serial;60;[wa:1100]― 자리에 [wa:500]앉아 있으면, [wa:900]말을 [wa:600]걸어오시거든요……"
2600905-123 = "#st;[-1200,-530];serial;60;[wa:1500]― '리본은 어디서 샀어?' [wa:2300]라던가,"
2600905-125 = "#st;[-1200,-630];serial;60;[wa:500]― '쉬는 날에는 뭐해?' [wa:3000]라던가……"
2600905-128 = "#st;[-1200,-530];serial;60;[wa:900]― 여러 질문을 받는 사이에, [wa:2120]무심코 도망쳐 버려서…"
2600905-131 = "#st;[-1200,-530];serial;60;[wa:1000]― 발견한 곳이, [wa:1500]여기였어요……"
2600905-133 = "#st;[-1200,-630];serial;60;[wa:1500]― 설마…… [wa:1500]고양이 [wa:400]휴게소였다니……[wa:1200] "
2600905-136 = "#st;[-1200,-530];serial;60;[wa:700]― 히얏……?! [wa:400]자, [wa:400]잠깐만 [wa:600]기다려 주세요!"
2600905-139 = "#st;[-1200,-530];serial;60;[wa:450]― 나갈게요! [wa:1400]지, [wa:200]지금 [wa:500]나갈 테니까…… [wa:2500]간지러워요!"
2600905-142 = "#na;(고양이를 옮긴 뒤, 유즈를 캐비닛에서 꺼내주었다.)"
2600905-144 = "3;유즈 메이드;06;도, 도와주셔서 감사합니다……\n#3;greeting\n#3;a"
2600905-145 = "3;유즈 메이드;09;그보다 [USERNAME] 선생님은 이곳에 어쩐 일로……"
2600905-146 = "[s3] \"유즈가 돌아오지 않아서 걱정했어.\"\n[s4] \"혹시라도 몸이 좋지 않아 무슨 일이 생겼을까 봐.\""
2600905-149 = "3;유즈 메이드;10;아뇨, 몸은 괜찮아요! 아무런 문제도 없어요……!\n#3;jump"
2600905-150 = "3;유즈 메이드;01;……네? 오전 내내 일하는 동안 계속 긴장한 것처럼 보였다고요?\n#3;em;[?]"
2600905-151 = "3;유즈 메이드;02;저, 그건 아마……"
2600905-152 = "3;유즈 메이드;09;선생님이 계셔서…… 그랬던 것…… 같아요.\n#fontsize;50\n#3;stiff"
2600905-153 = "[s] \"나를 신경 쓰고 있었던 거야?\""
2600905-154 = "3;유즈 메이드;02;………네."
2600905-155 = "3;유즈 메이드;09;지난번의 특훈 덕분에 낯선 손님 앞에서도 조금은 용기를 낼 수 있게 되었는데, 정작 그 모습을 선생님이 보신다고 생각되니 갑자기 긴장이 되어서요……"
2600905-156 = "3;유즈 메이드;09;언제나 소심한 저라도 친절히 도와주시는 선생님께 보답할 수 있는 방법은, 더 나아진 제 모습을 보여드리는 것뿐인데……"
2600905-157 = "3;유즈 메이드;06;평소보다 더 잘해야 한다는 생각이 머리를 가득 메운 탓에…… 평소보다 더 실수를 많이 저지른 것 같아요.\n#3;em;[훌쩍]"
2600905-158 = "[ns] \"그렇게 신경 쓰지 않아도 괜찮아.\""
2600905-160 = "[ns5] \"오늘의 나는 선생님이 아니라……\"\n[ns6] \"한 사람의 주인님으로서 방문한 거니까!\""
2600905-163 = "#st;[0,0];instant;1;"
2600905-165 = "3;유즈 메이드;02\n#3;stiff\n#wait;1000"
2600905-167 = "3;유즈 메이드;03\n#3;em;[///]\n#wait;1000"
2600905-169 = "3;유즈 메이드;99;……그렇네요. 너무 어렵게 생각했을지도 모르겠어요."
2600905-170 = "3;유즈 메이드;02;이 가게에서의 제 역할은 선생님의 학생이 아닌, 한 사람의 메이드일 뿐인데."
2600905-171 = "3;유즈 메이드;01;맞지 않는 옷을 입고 움직이려 하니 자꾸 넘어지고, 우스꽝스러운 모습을 보이게 된 것 같아요."
2600905-172 = "3;유즈 메이드;05;선생님께서 말씀하신 것처럼…… 이 카페에서는 하나오카 유즈가 아닌, 메이드 '여왕님'으로서 선생님을 접객하겠습니다……!\n#3;em;[!]"
2600905-173 = "[s] \"그래. 그걸로 충분해.\""
2600905-174 = "3;유즈 메이드;01;……그보다 오전에 실수를 한 손님들에게 죄송해서 어쩌죠……?"
2600905-175 = "3;유즈 메이드;06;제 실수투성이인 모습에 분명 다들 실망하셨을 텐데……\n#3;em;[훌쩍]"
2600905-176 = "[s7] \"너무 걱정하지 마.\"\n[s8] \"혹시 문제가 생긴다면 나도 같이 사과해 줄게.\""
2600905-179 = "3;유즈 메이드;09;우으…… 네……\n#3;stiff"
2600905-186 = "3;뚱뚱한 로봇 점장;01;여왕님, 어디에 있다가 이제야 오는 거야?\n#3;a"
2600905-187 = "3;유즈 메이드;04;죄, 죄송합니다…….\n#3;stiff"
2600905-188 = "3;뚱뚱한 로봇 점장;01;지금이라도 왔으니 괜찮아."
2600905-189 = "3;뚱뚱한 로봇 점장;01;자, 어서 준비해. 오전에 여왕님이 일하는 모습을 본 손님들이 목이 빠져라 여왕님을 기다리고 있으니까."
2600905-190 = "3;유즈 메이드;10;네, 네에……? 설마 오전의 실수 때문에 항의를 하시려고……?\n#3;em;[?!]\n#3;shake"
2600905-191 = "3;뚱뚱한 로봇 점장;01;아냐, 아냐. 그런 게 아니야.\n#3;jump"
2600905-192 = "3;뚱뚱한 로봇 점장;01;다들 여왕님이 오전에 일하는 모습을 보시고, '근래 보기 드문 정통파 덜렁이 메이드다!'라며 오후 영업이 시작하자마자 여왕님을 지명했거든."
2600905-193 = "3;뚱뚱한 로봇 점장;01;자, 여왕님. 지금 여왕님을 기다리고 있는 손님이 10명도 넘으니까 어서 서둘러서 준비하자고!\n#3;em;[재잘]\n#3;hophop"
2600905-194 = "3;유즈 메이드;08;으, 으아…… 어째서 실수를 했는데 더 인기가……\n#3;stiff"
2600905-195 = "[s] \"손님들이 좋아해 주신다니, 다행이네. 여왕님.\""
2600905-196 = "3;유즈 메이드;04;……더는 무리예요!\n#3;closeup"
2600905-198 = "#na;(이후. 유즈는 부담감에 실수를 계속해서 반복했지만, 메이드 카페의 손님들은 크게 만족해하며 돌아갔다.)"
2600905-199 = "#na;(그날, 메이드 카페에서 유즈의 지명 횟수는 일일 신기록을 경신했다고 한다……)"
