[translation]
2601-1 = "A Grown-Up's Toy Part 1"
2601-3 = "Black Tortoise Promenade Office"
2601-4 = "Hello, President Rumi. Good afternoon."
2601-5 = "Oh, Kokona. Welcome."
2601-6 = "Don't just call me Kokona. Call me Instructor Kokona!"
2601-7 = "I'm also a full-fledged instructor just like you, okay? Seriously... Please don't treat me like a child!"
2601-8 = "Haha, sorry. I'm still not used to calling you that."
2601-9 = "So, what brings \"Instructor Kokona\" to the office today?"
2601-10 = "Are you hungry? Would you like me to cook you some fried rice?"
2601-11 = "No, I'm not here to eat. I'm here to pick up some ingredients."
2601-12 = "Ingredients?"
2601-13 = "Yes. Shun asked me to get ingredients for the Plum Blossom children's meals."
2601-14 = "Did you not receive the notice?"
2601-15 = "Ah, how could I forget? I must have been so busy with work."
2601-16 = "Wait here just a moment. I'll be right back."
2601-18 = ""
2601-19 = "Let's see. I brought cabbage, bamboo shoots, carrots, onions...as well as some dried Chinese noodles and soy milk."
2601-20 = "Oh, and take some of the flat peaches near the entrance. They're sweet, so they should make for a healthy dessert."
2601-21 = "Th-This is a lot, though. Are you sure it's okay?"
2601-22 = "I thought I was only picking up some leftover ingredients..."
2601-23 = "It's more than fine. Those children are the future of Shanhaijing after all. They need to eat healthy and grow up strong!"
2601-24 = "Oh, but maybe it is a little too heavy for you to carry on your own."
2601-25 = "N-No, I can handle it. This is nothing for an instructor like me."
2601-26 = "Splendid, then."
2601-27 = "Oh, I almost forgot. Take this as well."
2601-28 = ""
2601-29 = ""
2601-30 = "What's in the bag? More food?"
2601-31 = "No, it's a special item that Instructor Shun specifically requested from the Black Tortoise Promenade."
2601-32 = "It's..."
2601-33 = ""
2601-34 = "...a secret."
2601-35 = "Huh? Seriously?!"
2601-36 = "That's right. In fact, Shun swore me to secrecy over it."
2601-37 = "Even if you are Shun's younger sister, maintaining the confidentiality of our customers is a matter of trust with Promenade. I'm sorry, but I can't tell you."
2601-38 = "Ugh. Now I'm even more curious."
2601-40 = "It's something hard, and it makes a rattling sound when you shake it. Is it a toy?"
2601-41 = "Well, you're not entirely wrong. I guess if we want to get technical, it could be called a grown-up's toy."
2601-42 = "A grown-up's...toy?"
2601-43 = "Yep. Inside is something that is absolutely not for children—not even ones your age."
2601-44 = "So you'd better not think of secretly checking what's inside on your way back."
2601-45 = "Oh, come on! You and Shun aren't that much older!"
2601-46 = "I'm also a full-fledged instructor, so for me to be the only one who doesn't know is totally unfair!"
2601-47 = "Some things are better left unknown, Kokona."
2601-48 = "For example, the officers of Genryumon, Shanhaijing's Student Council, will deal with all the witnesses when a secret is revealed for the sake of maintaining the school's confidentiality. Isn't that right?"
2601-49 = "That's why Shanhaijing students run away if someone tries to reveal to them a secret about Genryumon—so that they don't hear something they shouldn't."
2601-50 = "Genryumon?! Is what's inside related to them?!"
2601-51 = "Hmm. I can neither confirm nor deny...but let's just assume that it is."
2601-52 = "So, Kokona, having said that, I think it would be best if you simply delivered the item. Don't you?"
2601-53 = "U-Understood!"
2601-54 = "I promise I won't look at what's inside and deliver it straight to Shun!"
2601-55 = "Very good, then. I'll leave it in your capable hands."
2601-56 = ""
2601-58 = ""
2601-59 = ""
2601-60 = "H-Haha. That was a little mean, but it looks like she bought it."
2601-62 = "Black Tortoise Promenade Street"
2601-63 = ""
2601-64 = ""
2601-65 = ""
2601-66 = "The more I think about it, the more curious I am. It's supposed to be a grown-up's toy, right?"
2601-67 = "But President Rumi said I could get in serious trouble if I look. I should just put it out of my mind and deliver it to Shun."
2601-68 = "[s] \"Hi, Kokona.\""
2601-69 = "Oh, Sensei. Hello."
2601-70 = "[s1] \"That looks pretty heavy.\"\n[s2] \"What are you carrying?\""
2601-71 = "This is a bunch of foodstuff from the Black Tortoise Promenade and..."
2601-72 = "This is a bunch of foodstuff from the Black Tortoise Promenade and..."
2601-73 = "...a, uh, grown-up toy for Shun."
2601-74 = "[s] \"...Come again?\""
2601-76 = "Oh, no! President Rumi said I'm not supposed to tell anyone about that!"
2601-77 = "This is bad. Those terrifying people from Genryumon could appear and take us away at any moment..."
2601-78 = "Wait. You're an adult, Sensei, so maybe it's all right for you to know about things like grown-up toys."
2601-79 = "[s] \"...What exactly IS it?\""
2601-80 = "I'm not sure either. All I know is that it's supposedly something Shun ordered from the Black Tortoise Promenade."
2601-81 = "Judging by the outside of the bag, it's some kind of long, hard device..."
2601-82 = "President Rumi said that something seriously bad could happen if I were to peek at it, so I have to keep it a secret."
2601-83 = "What do you think it could be?"
2601-84 = "[s3] \"Maybe it's just a new gun.\"\n[s4] \"Do you think it's a hair straightener?\""
2601-85 = "Hmm. I guess it could be."
2601-86 = "I guess a gun that's too powerful and complex would need to be kept out of the hands of children."
2601-87 = "Maybe it's a terrifying new weapon developed with forbidden technology..."
2601-88 = "No way. If it were something that normal, there wouldn't be any need to hide it, right?"
2601-89 = "Besides, everyone knows Shun's hair is naturally perfectly straight."
2601-90 = "It's gotta be some kind of new terrifying weapon that's too dangerous for children, or maybe it's some kind of bomb..."
2601-91 = "Hold on. What time is it? I can't believe how late it already is."
2601-92 = "I'm going to miss afternoon snacks if I keep dawdling like this. I should hurry."
2601-93 = ""
2601-94 = ""
2601-95 = "Sensei, you have to keep Shun's grown-up toy a secret! Promise me!"
2601-96 = ""
2601-98 = ""
2601-101 = "Plum Blossom Garden"
2601-103 = "Hey, I'm back!"
2601-104 = "Goodness, that's a lot of ingredients. Thank you for picking them up."
2601-105 = "Yeah, President Rumi gave me a lot more than I was expecting."
2601-106 = "Cabbages, bamboo shoots, carrots... She even let us have flat peaches for dessert."
2601-107 = "She also asked me to deliver that thing you ordered separately."
2601-108 = "H-Huh?!"
2601-109 = ""
2601-111 = ""
2601-112 = ""
2601-113 = ""
2601-114 = "Oh, Rumi. I told her that I would go pick it up later!"
2601-115 = "Ahem... You didn't see what was inside, did you, Kokona?"
2601-116 = "No. President Rumi said not to look at it and that it's not meant for children."
2601-117 = "That's good to hear."
2601-118 = "Great job, Kokona. I'll bring out the snacks soon, so please gather the students."
2601-119 = ""
2601-121 = ""
2601-122 = "Kokona, Kokona. What did you get from the Black Tortoise Promenade?"
2601-123 = "Don't just call me Kokona. Call me Instructor Kokona!"
2601-124 = "I was just picking up food for everyone. Your snacks will be ready soon, so just be patient, okay?"
2601-125 = "What about that bag you gave to Shun? I heard something rattling inside. Is it also food?"
2601-126 = "No, that's not for eating. It's a toy for grown-ups."
2601-127 = "A grown-up toy? I wanna see too! What kind of toy is it?!"
2601-128 = "No! I told you that it's for grown-ups and grown-ups ONLY. Something really bad will happen if kids see it."
2601-129 = "Why? Is it a scary toy?"
2601-130 = "Y-Yeah... It's super scary! It's all spiky and bumpy! It's really ugly-looking too, so kids cry the second they see it."
2601-131 = "(Scary...)"
2601-132 = "Oh, and this is a secret, okay? You can never tell anyone you know about it."
2601-133 = "Yeah, okay."
2601-134 = "Good. Aren't you a good listener?"
2601-135 = "I'm going to go help Shun with the snacks, so sit tight just a little longer."
2601-136 = ""
2601-138 = ""
2601-140 = "Did you see those bags Kokona and Shun had a little while ago? What was inside?"
2601-141 = "Yeah, Kokona brought food, and Shun's bag had a grown-up toy inside."
2601-142 = "A grown-up toy? What's that?"
2601-143 = "It's something that Shun secretly bought from the Black Tortoise Promenade. It's an ugly toy with spiky thorns..."
2601-144 = "Scary..."
2601-145 = "What's going on? Are you telling a scary story?"
2601-146 = "Yeah. This is a secret, but Shun..."
2601-148 = "News of Shun's purchase of a suspicious toy soon spread throughout the Shanhaijing area from the mouths of the Plum Blossom Garden students..."
