[translation]
2601203-1 = "Emergency Situation Preparations"
2601203-2 = "To help Kirino train, I went back to Valkyrie Police School's swim training facility."
2601203-3 = ""
2601203-5 = ""
2601203-6 = "Hi, Sensei!"
2601203-7 = "Like I mentioned, today's training will be on land, no swimming involved!"
2601203-8 = "No going in the water at all."
2601203-9 = "[s] \"(I heard you the first time...)\""
2601203-10 = "The most essential first aid skill for any lifeguard is, hands down, CPR."
2601203-11 = "It's a vital skill for saving drowning victims."
2601203-12 = "By performing chest compressions, you artificially circulate their blood to protect the brain from damage."
2601203-13 = "Statistically, survival rates are 2.4 times higher when CPR is performed, versus when it's not."
2601203-14 = "[s1] \"Wow, impressive! You've really studied hard, haven't you?\"\n[s2] \"With this kind of knowledge, you're practically an expert!\""
2601203-17 = "...according to what's written in this Lifeguard Manual for New Valkyries!"
2601203-18 = "[s] \"Well, it's good to read the manual.\""
2601203-19 = "All right, let's start the training! First, we set up the training dummy—"
2601203-20 = ""
2601203-22 = ""
2601203-23 = "Huh?"
2601203-24 = "[s3] \"What dummy?\"\n[s4] \"I don't see a dummy...\""
2601203-27 = "I-I must have left it in the supply room..."
2601203-28 = "Ah, blah. The supply room's all the way on the opposite side of the school. What do you think, should I run over there real quick?"
2601203-29 = "B-But I only have so much pool time reserved..."
2601203-30 = "[s5] \"I guess we have no choice.\"\n[s6] \"I'll be your dummy.\""
2601203-33 = "What? You'd do that?"
2601203-34 = "That'll definitely make the training more realistic."
2601203-35 = "Are you sure you're okay with that?"
2601203-36 = "[s] \"I'm here to help you with your training, and that's what I'll do.\""
2601203-37 = "Th-Thank you!"
2601203-38 = "And in return, I'll put in my very best effort."
2601203-41 = "I decided to lie down with my eyes closed, pretending I was unconscious."
2601203-42 = "Oh, no! Sensei, wake up! You, by the exit, please call an ambulance immediately! I'll handle the first aid until they get here!"
2601203-43 = "F-First, check their pulse and breathing...!"
2601203-44 = "[s] \"(She's measuring the pulse by hand and listening for breathing. By the book.)\""
2601203-45 = "Then, ensure the airway is clear!"
2601203-46 = "[s] \"(She's lifting up my chin, making sure the airway's properly aligned.)\""
2601203-47 = "Um, next, I..."
2601203-48 = ""
2601203-51 = "[ns] \"(Hmm...?)\""
2601203-52 = "I'm going to use the AED!"
2601203-53 = ""
2601203-56 = "[ns] \"(Wait, what?)\""
2601203-57 = ""
2601203-58 = "[ns7] \"Wh-What are you doing?!\"\n[ns8] \"That's dangerous!\""
2601203-61 = "Huh? But the manual says to use the AED on cardiac arrest patients..."
2601203-62 = "It's essential for increasing their survival chances!"
2601203-63 = "[s] \"This is training! Can't we just pretend to use it?\""
2601203-64 = "According to the manual, more realistic training gives us the best odds of winning the battle."
2601203-65 = "So please lie down. Training dummies are supposed to lie still!"
2601203-66 = "[s9] \"Y-You don't want to get TOO fixated on the manual!\"\n[s10] \"The 'battle'? Who are we even fighting against?!\""
2601203-69 = "...All right. If you insist, Sensei, we'll just have to skip that step."
2601203-70 = "The manual says that after using the AED, the next step is..."
2601203-71 = ""
2601203-73 = ""
2601203-74 = ""
2601203-75 = "Oh. Y-You know, I think you have a point about not following the manual too closely."
2601203-76 = "You can't do EXACTLY what you'd do in a real emergency, not while you're training."
2601203-77 = "I-It's not that I...I don't want to do that part with you, Sensei...but it feels like it's a bit too soon...!"
2601203-78 = "[s] \"You think?!\""
2601203-79 = "Yeah. Yeah, okay..."
2601203-80 = "Let me just go get the training dummy."
2601203-81 = "Thanks for being my substitute dummy, even just for a little while."
2601203-82 = ""
2601203-84 = ""
2601203-85 = "[ns11] \"...\"\n[ns12] \"(Hmm, she dropped the manual...)\""
2601203-91 = "According to the manual, the next step after AED use is mouth-to-mouth resuscitation."
