[translation]
2601302-1 = "Unseen, Yet Still Here"
2601302-2 = "Ah, [USERNAME] Sensei."
2601302-3 = "Hello."
2601302-4 = "[s1] \"You look happy, Atsuko.\"\n[s2] \"You look excited, Atsuko.\""
2601302-7 = "Is that so?"
2601302-8 = "I believed I was hiding it, but..."
2601302-9 = "I suppose you can tell."
2601302-10 = "You're correct. I'm rather excited. It must be all the anticipation for the festival."
2601302-11 = "Also, at Outlaw Beach, I don't have to hide or run away from anyone."
2601302-12 = "I even have a camera."
2601302-13 = "I've been finding photography very enjoyable."
2601302-14 = "The ability to capture and preserve precious moments..."
2601302-15 = "So I was hoping to find good locations to take photos today."
2601302-16 = "Would you accompany me, Sensei?"
2601302-17 = "[s] \"Of course!\""
2601302-18 = "Let's go, then."
2601302-20 = "I plan to start with taking pictures of whatever catches my eye."
2601302-21 = "I very luckily happened upon this digital camera at the Black Market."
2601302-22 = "It's a bit old, but holds up performance-wise."
2601302-23 = "Ah, Sensei. Wait."
2601302-24 = "I like the feeling of that advertisement."
2601302-25 = "[s] \"The advertisement?\""
2601302-26 = "Yes. The typography of \"yakisoba, shaved ice, corn...\""
2601302-27 = "The picture will remind me of the sweet smells, sizzling sounds, and all the delicious tastes of the festival when I look at it later."
2601302-28 = "It'll be a good memory."
2601302-29 = ""
2601302-30 = ""
2601302-31 = "Let's find our next subject."
2601302-33 = "A stroll by the shore... It's very refreshing."
2601302-34 = "Ah, Sensei, watch your step! You nearly stepped on a hermit crab."
2601302-35 = "[s] \"Whoa. That was a close call.\""
2601302-36 = "Heehee. It's adorable."
2601302-37 = "Now, pose nicely. This is my reward for rescuing you."
2601302-38 = ""
2601302-40 = ""
2601302-41 = "Mhm, a good shot. Goodbye, Mister Hermit Crab."
2601302-42 = "Please return to the ocean, where it's safe."
2601302-43 = "Now this moment will be captured in this picture, forever. This is the purpose of a photograph."
2601302-44 = "What shall I capture next?"
2601302-46 = "Atsuko and I continued walking around the beach and the festival, taking photos."
2601302-48 = "Where did the time go...?"
2601302-49 = "[s3] \"The sunset is really beautiful.\"\n[s4] \"How about taking one last picture today?\""
2601302-52 = "Yes, I like that. Where should I...? Hm..."
2601302-53 = "Ah!"
2601302-54 = ""
2601302-58 = "My camera!"
2601302-59 = "What a relief. The soft sand broke its fall."
2601302-60 = "Ah. The battery cover opened, however."
2601302-61 = "I hope no sand got in..."
2601302-62 = "...Um..."
2601302-63 = "[s] \"The battery socket...is empty.\""
2601302-64 = ""
2601302-66 = ""
2601302-67 = "Ah... Right. I meant to put a battery in this morning, but it completely slipped my mind."
2601302-68 = "That must be why the screen wasn't turning on. I simply assumed it was because the camera is a bit old..."
2601302-69 = "That would mean that all the pictures we took today..."
2601302-70 = "[s] \"Not a single one was actually taken.\""
2601302-71 = ""
2601302-73 = ""
2601302-74 = "...I really enjoyed myself today, but it was all for nothing."
2601302-75 = "To think that, because of one careless moment, I'm leaving empty-handed."
2601302-76 = "The advertisement, hermit crab, and the rest of today's memories are all gone now."
2601302-77 = "...All the memories I made with you, Sensei."
2601302-78 = "[s] \"...That's not true.\""
2601302-79 = "It's...not?"
2601302-80 = "I failed to capture even a single picture..."
2601302-81 = "I intended on reminiscing while looking at the photos I took today."
2601302-82 = "[s] \"The memories are still there, even without the pictures.\""
2601302-83 = ""
2601302-85 = "[ns] \"The fact that we enjoyed the festival together won't change.\""
2601302-86 = ""
2601302-87 = "...That is true."
2601302-88 = "The joyful memories will always be etched into our minds."
2601302-89 = "I'll even cherish the simple times we spent talking, just like this."
2601302-90 = "You've taught me another lesson. Thank you, Sensei."
2601302-91 = "[s] \"Next time, I'll bring some extra batteries.\""
2601302-92 = "Heehee."
2601302-93 = "Yes. We shall explore the festival together again, Sensei."
2601302-94 = "I won't make the same mistake again."
