[translation]
2601102-1 = "Am I the Legend?"
2601102-2 = "After getting a message from Saten, I headed to the shopping district."
2601102-3 = ""
2601102-7 = "Even from a distance, I could see the excitement shining in her eyes."
2601102-8 = ""
2601102-10 = ""
2601102-11 = ""
2601102-12 = ""
2601102-13 = ""
2601102-14 = ""
2601102-15 = "Wow... I can't believe it... I really can't believe it!"
2601102-16 = "Is this real? I didn't wander into some theme park, did I? Am I on a hidden camera show?"
2601102-17 = "Or maybe a movie's filming... It's got to be that, right?"
2601102-18 = "People with wings, people with horns, people with animal ears and tails..."
2601102-19 = "There's even actual animal people!"
2601102-20 = "[s1] \"...Saten?\"\n[s2] \"What are you up to?\""
2601102-23 = ""
2601102-25 = ""
2601102-26 = ""
2601102-27 = ""
2601102-28 = "And up in the sky, a bright pillar of light and a halo...!!"
2601102-29 = "[s3] \"You're awfully excited...\"\n[s4] \"Um... Saten?\""
2601102-32 = "...?! Ahh!"
2601102-33 = "Oh! Oh, it's just you, Sensei!"
2601102-34 = "You scared me... I'm still shaken after running away from a talking dog man..."
2601102-35 = "I mean... He looked like a cute little puppy, but still..."
2601102-36 = "Yes...?"
2601102-37 = "I don't need to be scared of them? They aren't evil?"
2601102-38 = "Oh... Um..."
2601102-39 = ""
2601102-41 = ""
2601102-42 = "...It's not like I was scared or anything."
2601102-43 = "[s5] \"Is that so?\"\n[s6] \"Then your reaction just now...\""
2601102-46 = "Well... Sure, I was startled..."
2601102-47 = "Oh, you're not worried about me, are you? Sorry! I didn't mean to."
2601102-48 = "It's just... I've never seen any of these things before, and now I'm seeing them all here all at once."
2601102-49 = "If you don't look too closely, this place is a lot like Academy City. But pay attention, and the differences are huge..."
2601102-50 = "And..."
2601102-51 = "It's like every urban legend I've ever read about coexists here..."
2601102-52 = "It's all so amazing!"
2601102-53 = "But... Um..."
2601102-54 = ""
2601102-56 = ""
2601102-57 = "One thing... Just one thing doesn't really live up to my...expectations, I guess you could say."
2601102-58 = "Everyone here acts as if this is completely normal, so it doesn't really feel like an urban legend..."
2601102-59 = "[s7] \"To them, this is completely normal.\"\n[s8] \"Urban legends are in the eye of the beholder.\""
2601102-62 = "I guess that makes sense..."
2601102-63 = ""
2601102-65 = ""
2601102-66 = "Oh?"
2601102-67 = "Wait! Does that mean... Am I the urban legend here?!"
2601102-68 = "[s9] \"You mean as a person from another world?\"\n[s10] \"If you look at it that way, I guess so.\""
2601102-71 = "...!"
2601102-72 = "Right? I hadn't considered it from that angle!"
2601102-73 = "The real urban legend...was me all along..."
2601102-74 = "Oooh..."
2601102-75 = "Sensei...? Um..."
2601102-76 = ""
2601102-78 = ""
2601102-79 = ""
2601102-80 = ""
2601102-81 = "Am I...mysterious to you?"
2601102-82 = "[s11] \"I don't know what to say to that.\"\n[s12] \"Um... Sure?\""
2601102-85 = "Your face says otherwise... What a shame."
2601102-86 = "It's fine if I'm still just me. I guess I haven't seen anything today that's really special for the people living here."
2601102-87 = "But surely you have urban legends of your own here, right? Like ghost stories or tales of the occult!"
2601102-88 = "[s13] \"Look at you pivot.\"\n[s14] \"You don't know when to give up, do you?\""
2601102-91 = "Of course not! If something is important to you, you keep chasing it!"
2601102-92 = "Let's go hunting for urban legends, Sensei! One worthy of this amazing world!"
2601102-93 = ""
2601102-95 = ""
2601102-96 = "[ns] \"...\""
2601102-98 = "[ns] Follow Saten's lead."
2601102-100 = "I followed an excited Saten as she explored Kivotos."
2601102-101 = "As I expected, we didn't find any urban legends..."
