[translation]
3001-1 = "Shadow of the Canned Food Part 1"
3001-2 = ""
3001-4 = "Private Security Advisor Company, Blackstone Office"
3001-5 = ""
3001-6 = ""
3001-8 = ""
3001-9 = "Heehee... The plan is going smoothly."
3001-10 = "I pay some thugs to attack a small school, and then I swoop in and offer them security against the thugs! If there's no demand for your product, make some!"
3001-11 = "I guess taking a page out of Kaiser's book really was the right call!"
3001-12 = "If I continue down this path, I'll become an even bigger military corporation than even the Kaiser Group!"
3001-13 = ""
3001-17 = ""
3001-19 = "Boss! We're under attack!"
3001-20 = "What? Who has the audacity to attack our company?"
3001-21 = "Is it those Valkyrie brats? Didn't we bribe the executives in the Defense Office already?"
3001-23 = "Th-They're not police. They're SRT agents!"
3001-24 = "SRT?! I thought the General Student Council already closed down SRT Academy!"
3001-25 = "How did they know we were here?!"
3001-26 = "Ugh... We've invested so much into this business..."
3001-27 = "I won't give it all up now!"
3001-28 = ""
3001-33 = ""
3001-34 = "SRT! Everyone put your hands up and take a step back!"
3001-35 = "RABBIT 1, reporting. Time is 1330 hours. I've arrived at Point Whiskey."
3001-36 = "...We already subdued the guards at the entrance. Move to the next phase."
3001-38 = "Who do they think they are!"
3001-40 = "Are you a representative of this security company?"
3001-41 = "A report \"accidentally\" obtained from the Valkyrie Security Bureau last week shows evidence you're behind the recent string of raids on small schools."
3001-42 = "Despite this evidence, the Valkyrie Security Bureau seems to have failed to arrest them due to the complex administrative procedures of the Defense Office."
3001-43 = "Unfortunately for you, SRT Academy was specifically created to bypass red tape."
3001-45 = "Ugh... I never thought we'd get caught like this."
3001-46 = "But I can't let small fries like you ruin the company I worked so hard for!"
3001-47 = "I'm the head of PMC, and I've been a mercenary for a long time. I'm confident in my close-combat skills!"
3001-48 = ""
3001-50 = ""
3001-51 = ""
3001-52 = ""
3001-53 = "Come on! Bring it on!"
3001-54 = ""
3001-58 = ""
3001-59 = ""
3001-60 = "S-Sniping on these streets...?!"
3001-61 = ""
3001-63 = ""
3001-64 = ""
3001-66 = "...RABBIT 4. Target eliminated."
3001-67 = "I'll continue watch here."
3001-69 = "Ugh, the boss is down..."
3001-70 = "We've been caught! And I don't exactly want to tangle with special agents from SRT."
3001-71 = "L-Let's run!"
3001-72 = "Like hell I'd let you!"
3001-73 = ""
3001-83 = "Sight A clear. All the enemies cleared out quickly."
3001-84 = "S-Sight B too. We subdued everyone who didn't g-get away."
3001-85 = "Great job, everyone."
3001-86 = "Immobilize the incapacitated enemies, and let's request Valkyrie Police School's services for post-processing."
3001-87 = "And then we'll head back home."
3001-89 = "Wasn't that a PMC base? Find any goodies for me?"
3001-90 = "Even if they're supplies marked for disposal, I could still use them somehow."
3001-91 = "Unfortunately, all we have here are small arms, and most are equipment and ammunition not compatible with our current gear."
3001-92 = "We have no choice but to dispose of them or hand them over to Valkyrie Police School."
3001-94 = "Not that I came here for rewards or anything, but it would've been a nice bonus to find something."
3001-95 = "M-Miyako, Saki. What about these boxes?"
3001-96 = "They're labeled: \"Food.\""
3001-97 = ""
3001-99 = ""
3001-102 = "These are...war rations."
3001-103 = "And they're not expired!"
3001-104 = "Haha! Awesome! I guess we get a few rewards!"
3001-105 = "Did you say food? What is it? Huh? Tell me!"
3001-107 = "A lot of different kinds of rations. They're generally treated for preservation..."
3001-108 = "So these are much better for us living out of a tent than the bento boxes we've been eating."
3001-109 = "A-And look how many there are..."
3001-111 = "I know I'm being picky, but some of these kind of suck though."
3001-112 = "\"Vegetarian omelet with cheddar cheese,\" \"oatmeal porridge,\" \"freeze-dried red bean rice for colder regions...\""
3001-113 = ""
3001-115 = ""
3001-117 = "Ugh... I've had this mixed seafood sauce before. It's awful."
3001-118 = "I thought rations were generally tasteless."
3001-119 = "In the old days, war rations were pretty gross, but that's not the case anymore."
3001-120 = "Since delicious food really raises a soldier's morale, it benefits the troops if the rations taste better."
3001-121 = "In the past, because science hadn't developed that far yet, battle rations were hard and bland. Nowadays it's possible to enjoy even moist and savory foods, no matter where you are."
3001-122 = "They've also developed special items like tofu \"meat\" for vegetarians and soldiers with allergies, so you can enjoy a variety of types of war rations."
3001-124 = "I-I see..."
3001-125 = "Saki... Y-You know so much about everything..."
3001-126 = "B-But even if you learned about them in t-textbooks, when did you try it?"
3001-127 = "Yeah, spill the sauce, weirdo. We've only had battle rations a few times in training."
3001-129 = "W-Well..."
3001-130 = "I heard war rations were the staple food of the special forces, so I was curious, okay?"
3001-131 = "I was too excited to wait, so I bought and tried them before I joined SRT..."
3001-132 = "Oh? Ohoho? That doesn't sound like something our bookworm would do."
3001-133 = "It's finally the time to admit it, Saki! You joined to try out all the cool stuff SRT had, right? Not because of duty or whatever!"
3001-134 = "C'mon, we're all a bunch of nerds. You can be honest here."
3001-135 = "Sh-Shut up! That's totally unrelated!"
3001-137 = "Regardless of the taste, I'm glad we don't have to worry about food for a while."
3001-138 = "Let's pack it up and head home."
3001-140 = "...That night."
3001-141 = ""
3001-145 = ""
3001-146 = ""
3001-147 = "The current time is 0500. Nothing going on."
3001-148 = ""
3001-150 = ""
3001-151 = "There's not a lotta light, and there's only crickets chirping."
3001-152 = "I hate guard duty at night! It's so scary!"
3001-153 = "But I can eat the canned foods when I'm done...so I should work hard."
3001-154 = "It's like Saki said, yummy food makes soldiers happy!"
3001-155 = ""
3001-158 = ""
3001-159 = "Wh-What was that? Is it an intruder?"
3001-160 = "Maybe it's a thief coming after the canned goods!"
3001-161 = ""
3001-165 = ""
3001-166 = "St-Stop! I'll shoot if you m-move!"
3001-167 = ""
3001-169 = ""
3001-170 = "Th-there's no one here?"
3001-171 = ""
3001-173 = ""
3001-174 = ""
3001-175 = "Maybe it was a wild animal...?"
3001-176 = ""
3001-178 = ""
3001-179 = ""
3001-180 = ""
3001-183 = "*click*"
3001-184 = "Oh, did that canned food..."
3001-185 = ""
3001-187 = ""
3001-188 = ""
3001-189 = "...just move?"
3001-190 = ""
3001-192 = ""
3001-193 = ""
3001-194 = "No way..."
3001-195 = ""
3001-201 = "*click* *click* *click* *click*"
3001-202 = "...!?!!#%$!"
3001-204 = ""
