[translation]
31050-1 = "ตอนที่ 5;นักเรียนที่สอบตก 2"
31050-4 = "ฉันได้ยินมาแล้วล่ะค่ะ... ว่าคุณครูจะมาดูแลชมรมชั้นเรียนเสริมให้ชั่วคราว..."
31050-5 = "น่าเสียดายนะคะ คุณครูน่าจะมีเรื่องยุ่งมากมาย แต่พวกฉันกลับช่วยอะไรไม่ได้เลย..."
31050-6 = "[s] \"ขอพาตัวสองคนนั้นไปได้ไหม?\""
31050-7 = "ว่าไงนะ?! มีสิทธิ์อะไร?! ไม่ได้เด็ดขาด! พวกนี้เป็นนักโทษร้ายแรงนะ!"
31050-8 = "โคฮารุ คุณครูคือผู้รับผิดชอบชาเล่ต์ และได้รับมอบหมายหน้าที่จากสภาน้ำชามาค่ะ"
31050-9 = "ตามกฎแล้วคุณครูสามารถพาตัวนักเรียนพวกนี้ไปได้ เพราะเป็นผู้ดูแลชมรมชั้นเรียนเสริมนี่คะ"
31050-10 = "ตะ.. แต่ว่า... ถ้ารุ่นพี่ว่าอย่างนี้... ก็..."
31050-11 = "ฮึ่ม! แต่ก็สมแล้วล่ะ! ต้องมาดูแลนักโทษแบบนี้! แถมยังเป็นชมรมชั้นเรียนเสริมอีก!#nทั้งน่าอายและน่าสมเพช!"
31050-12 = "ฮ่ะฮ่ะฮ่ะฮ่าา! เหมาะสมแล้ว! เป็นคนร้ายและคนหัวไม่ดีในร่างเดียวกันไปอีก!#nถ้าเป็นฉันคงทนต่อความอับอายไม่ได้และแทรกแผ่นดินหนีไปแล้ว!"
31050-13 = "โคฮารุ... เฮ้อ..."
31050-14 = ""
31050-15 = "อ่า..."
31050-16 = "[s] \"งั้นเราก็เหลือแค่คนเดียวใช่ไหม?\""
31050-17 = "อ่า... ใช่ค่ะ จริงสิ... ฉันยังไม่ได้บอกเลย..."
31050-18 = "อีกคนหนึ่งคือ... คุณชิโมเอะ โคฮารุ... น่ะค่ะ"
31050-19 = "......"
31050-20 = ".... หือ? ฉันเหรอ?"
31050-21 = ""
31050-22 = ""
31050-24 = "ชิ"
31050-26 = "โม"
31050-28 = "เอะ"
31050-32 = "โค"
31050-34 = "ฮา"
31050-36 = "รุ"
31050-38 = "ชิโมเอะ โคฮารุ ชั้นปีที่ 1 สมาชิกชมรมชั้นเรียนเสริม"
31050-39 = "สอบตกหลายครั้งจนมีสิทธิ์ซ้ำชั้น"
31050-40 = "หมายเหตุ จะไม่พิจารณาให้กลับเข้าชมรมทวงความยุติธรรมจนกว่าจะสอบผ่าน"
31050-43 = ""
31050-44 = "ตายจริง? คนนี้ก็เป็นสมาชิกชมรมชั้นเรียนเสริมเหรอ?"
31050-45 = "(ฮึ่ม ฮึ่ม)"
31050-46 = "......"
31050-47 = ""
31050-49 = "อ่า... แหะๆๆ... ชมรมชั้นเรียนเสริมของเรา... อยู่ที่นี่กันครบหมดเลยนะคะ..."
31050-50 = "ตะ... ตอนนี้... ต่อไปก็ต้องคุยปัญหาของพวกเรา..."
31050-51 = "ฮุฮุ ทีนี้ให้ทำอะไรต่อเหรอคะ? คุณหัวหน้าอะจิทานิ?"
31050-52 = "เมื่อนักเรียนหญิงกับผู้ใหญ่อยู่ด้วยกันหลังเลิกเรียน... อืม... สิ่งที่พอจะทำได้...#nจะเป็นเรื่องแบบนั้นหรือเปล่านะ..."
31050-53 = "เรื่องแบบนั้น...? จะเรื่องอะไรก็ช่างเถอะ แต่ถ้าเป็นห้องนี้ ฉันทนนั่งได้อีกเดือนหนึ่งเลย"
31050-54 = "โลกแตกเลยได้ไหม..."
31050-55 = ""
31050-56 = "......"
31050-57 = "คุณครูคะ... ขอฝากด้วยนะคะ..."
31050-58 = "[s] \"อืม ครูจะพยายามนะ\""
31050-59 = "ค่ะ... ขอบคุณมากค่ะ ฉันเองก็จะพยายามเหมือนกัน..."
31050-61 = "ตอนต่อไป;เวลาแห่งการแนะนำตัว"
