[translation]
3201-1 = "การแสดงพิเศษขององค์หญิงวาราคุ (1)"
3201-2 = "ค่ะ ถ้างั้นวาระถัดไป..."
3201-3 = "ชมรมหยินหยางของเราจะจัดการแสดง <เทศกาลขอบคุณ เฮียกคิยาโค> ในงานเทศกาลครั้งนี้ค่ะ"
3201-4 = "ถึงชื่อการแสดงจะดูยิ่งใหญ่เกินไป แต่ก็ไม่จำเป็นต้องแตกต่างจากการแสดงที่เคยทำมาหรอกค่ะ"
3201-5 = "การแสดงนี้ไม่ได้มีอะไรมากเป็นพิเศษ เดี๋ยวฉันจะเป็นคนเตรียมงานนี้เองค่ะ"
3201-6 = ""
3201-8 = ""
3201-9 = ""
3201-10 = "เดี๋ยวก่อน~"
3201-11 = "ว่าไงคะ ชิเซะจัง? มีอะไรเหรอคะ?"
3201-12 = "อืม~"
3201-13 = "ฉันจะเตรียมการแสดงครั้งนี้เอง"
3201-14 = "ชิเซะจัง...?"
3201-16 = "อะฮ่า ชิเซะจะเตรียมการแสดงเองเลยเหรอ..."
3201-17 = "แบบนั้นก็อาจจะสนุกก็ได้นะ~?"
3201-18 = "มะ...ไม่ถึงกับต้องให้ชิเซะจังมาเตรียมงานด้วยตัวเองหรอกค่ะ"
3201-19 = "พวกฉากหรืออุปกรณ์ตกแต่งบนเวทีก็ใช้ของที่เหลือจากการแสดงครั้งที่แล้วได้ และอย่างที่บอกไป#nเมื่อก่อนหน้านี้ว่ามันไม่ใช่การแสดงยิ่งใหญ่อะไร..."
3201-20 = "แต่ว่านะ การแสดงคราวนี้มันพิเศษนะ~"
3201-21 = "ฉัน... ขอเตรียมเองได้มั้ย?"
3201-22 = "(นะ...น่ารักเกินไปแล้ว...!)"
3201-23 = "อะ... อะแฮ่ม เข้าใจแล้วค่ะ"
3201-24 = "ถ้างั้นฉันจะช่วยเรื่องซื้ออุปกรณ์กับเรื่องตกแต่งเวทีเองค่ะ"
3201-25 = "นี่เป็นการแสดงที่ชิเซะจังลงมือเตรียมเองทั้งที จะให้ขาดตกอะไรไปไม่ได้เด็ดขาดค่ะ"
3201-26 = "อืม~ ต้องทำถึงขนาดนั้นเลยเหรอ?"
3201-27 = "ชิเซะน่าจะเตรียมเองได้หมดอยู่แล้วนะ"
3201-28 = "ในฐานะรองหัวหน้าชมรมหยินหยาง มันเป็นงานของฉันที่ต้องคอยช่วยสนับสนุนให้จัดการแสดงได้#nอย่างราบรื่นค่ะ"
3201-29 = "และมันก็เป็นงานที่ฉันทำมาโดยตลอดด้วยค่ะ"
3201-31 = "(อีกอย่าง ถ้าให้ชิเซะจังทำทุกอย่างคนเดียว... ฉันคงจะรู้สึกผิดเพราะมันจะเหมือนว่าโยนภาระงาน#nของฉันไปให้ชิเซะจังน่ะสิ) "
3201-32 = "(แล้วฉันก็ยังเป็นห่วงเธอด้วย...)"
3201-33 = "อื้ม ไม่เป็นไรหรอก"
3201-34 = "คาโฮะไปพักเถอะนะ~"
3201-35 = "วันนี้เหมาะกับการนั่งมองคุณพระอาทิตย์ด้วย~"
3201-36 = "งานนี้ให้ฉันจัดการเอง~"
3201-37 = "ฉันจะออกไปซื้อของ เดี๋ยวมานะ"
3201-38 = ""
3201-40 = ""
3201-41 = "ดะ... เดี๋ยวก่อนสิคะ ชิเซะจัง!"
3201-42 = "อ่า... ไปซะแล้ว"
3201-43 = "ท่าทางกับคำพูดที่ผิดไปจากปกติ..."
3201-44 = "ระ...หรือว่าชิเซะจังเข้าวัยต่อต้านกันแล้วคะ?!"
3201-45 = "อะฮะฮ่า~ คาโฮะนี่ก็จริงๆ เลยนะ กังวลเกินไปแล้วรึเปล่า เอาน่าๆ คราวนี้เรามาตั้งหน้าตั้งตารอกันไม่ดี#nกว่าเหรอ?"
3201-46 = "ชิเซะเองก็คงมีไอเดียของตัวเองอยู่นั่นแหละ~"
3201-47 = "ระ...เรื่องนั้นมันก็แน่อยู่แล้วค่ะ! ไม่ใช่ว่าฉันไม่ถูกใจการแสดงที่ชิเซะจังจะทำหรอกนะคะ... ก็แค่..."
3201-48 = "ถ้าเกิดว่าพอไปที่ย่านการค้าแล้วโดนคนจำนวนมากรุมล้อมเข้าล่ะ...!"
3201-49 = "แล้วถ้าเกิดว่ามีคนคิดไม่ดีลักพาตัวชิเซะจังไปล่ะ...!"
3201-51 = "อะฮะฮ่า แบบนั้นมันเวอร์ไปหน่อยรึเปล่า~?"
3201-52 = "ไม่ใช่การแสดง <องค์หญิงวาราคุ> สักหน่อย"
3201-53 = "ฉะ... ฉันกังวลจริงๆ นะคะ!"
3201-54 = "เพราะงั้น... ฉันจะคอยจับตาดูชิเซะจังไว้เองค่ะ!"
3201-55 = "คุณนิยะเองก็มาด้วยกันสิคะ!"
3201-56 = "เอ๋~? ฉันต้องไปด้วยเหรอ?"
3201-57 = ""
3201-58 = "เร่เข้ามาจ้า เร่เข้ามา!"
3201-59 = "เดี๋ยวนะ ดูซิใครมาเนี่ย ท่านชิเซะนี่นา! ฮ่าฮ่า!"
3201-60 = "สวัสดี~ ยินดีที่ได้เจอนะ~"
3201-61 = ""
3201-62 = ""
3201-64 = "อ่า... ว่าแต่การสะกดรอยตามแบบนี้น่ะ..."
3201-65 = "เราน่าจะเป็นฝ่ายที่ตกอยู่ในอันตรายมากกว่ารึเปล่านะ~"
3201-66 = "ชะ... ช่วยเงียบเสียงด้วยค่ะ เดี๋ยวก็ถูกจับได้หรอกค่ะ!"
3201-67 = "วิธีที่จะดูแลความปลอดภัยพร้อมกับเคารพการตัดสินใจเรื่องการเตรียมงานด้วยตัวคนเดียวของชิเซะจัง#nน่ะ มันมีแค่วิธีนี้วิธีเดียวนะคะ!"
3201-68 = "เสียงคาโฮะจังดังกว่าอีก..."
3201-69 = "อึก...!"
3201-70 = "เอาน่า คอยดูอยู่ห่างๆ ไปก่อนเถอะ"
3201-71 = ""
3201-72 = "จากที่เห็น คงจะมาซื้อของเตรียมการแสดง <เทศกาลขอบคุณ เฮียกคิยาโค> สินะ"
3201-73 = "ถ้างั้นก็...ไหนดูซิ..."
3201-74 = "อ๊ะ อยู่ตรงนี้เอง"
3201-75 = "ร่มสีครามที่คุณคาโฮะมักจะซื้อไปไงล่ะ"
3201-76 = "ใช่แล้วค่ะ ชิเซะจัง!"
3201-77 = "ร่มย้อมสีที่เป็นงานศิลปหัตถกรรมเก่าแก่ของเฮียกคิยาโคจะช่วยเสริมให้การแสดงดูมีมนต์ขลังขึ้นค่ะ...!"
3201-78 = ""
3201-80 = ""
3201-81 = ""
3201-82 = "ไม่ละ ขอเป็นร่มคันสีชมพูอันนั้นแทนดีกว่า~"
3201-83 = ""
3201-85 = "?!"
3201-86 = "ชิเซะจัง ทำไมกัน...?"
3201-87 = "การแสดงครั้งที่แล้วก็ใช้ร่มสีครามนี่นา... หรือว่าที่จริงแล้วชิเซะจังไม่ชอบกันนะ?!"
3201-88 = "โฮ่ โฮ่... อาจเป็นงั้นก็ได้"
3201-90 = "การต่อต้านเล็กๆ ของไอดอลชิเซะงั้นรึ"
3201-91 = ""
3201-92 = "สีชมพูพีชอันนี้ใช่มั้ย?"
3201-93 = "เอ้านี่!"
3201-94 = "ขอบคุณน้า~"
3201-95 = "ยินดีเสมอ! ขาดเหลืออะไรก็แวะมาได้เลยนะ"
3201-97 = "สวัสดีขอรับ ท่านชิเซะ! มาเลือกซื้อของเหรอครับ?"
3201-98 = "อื้อ ต้องใช้ตุ๊กตาด้วยน่ะ~"
3201-99 = "เอาตัวที่น่ารักๆ นะ"
3201-100 = "กำลังเตรียมงานแสดง <เทศกาลขอบคุณ เฮียกคิยาโค> อยู่สินะครับ?"
3201-101 = "ถ้างั้นขอแนะนำเป็นตุ๊กตาโคเคชิที่อยู่ด้านนี้เลยครับ"
3201-102 = "ใช่แล้วค่ะ ตุ๊กตาเป็นของสำคัญมากๆ ในพิธีแสดงความขอบคุณในงานเทศกาล!"
3201-103 = "ถึงคราวนี้สีร่มที่เลือกจะต่างจากการแสดงครั้งก่อน... แต่ก็เหมือนกับที่เจ้าของร้านพูดค่ะ งานแสดงความขอบคุณจะขาดตุ๊กตาโคเคชิไปไม่ได้! "
3201-104 = "เลือกตุ๊กตาโคเคชิคือสิ่งที่ถูกต้องแล้วค่ะ ชิเซะจัง!"
3201-105 = "อะฮะฮ่า... คอยดูอยู่เงียบๆ เถอะน่า~"
3201-107 = "ตุ๊กตาโคเคชิ..."
3201-108 = "ไม่เห็นจะน่ารักเลย ฉันชอบแบบนี้มากกว่า~"
3201-109 = "หมายถึงตุ๊กตาจิ้งจอกตัวนี้เหรอครับ? คาดไม่ถึงเลยนะครับเนี่ย นี่ครับ..."
3201-110 = "เลือกแบบอื่นอีกแล้วเหรอ...?"
3201-111 = "อื้อ เด็กคนนี้คือรองหัวหน้าคาโฮะ~"
3201-113 = "มะ...หมายถึงฉันงั้นเหรอคะ?!"
3201-114 = "โอ้~ จริงด้วย สมกับเป็นชิเซะจริงๆ สายตาเฉียบแหลมมาก~"
3201-116 = "แล้วก็ขอคุณดารุมะตรงนั้นด้วย~"
3201-117 = "ครับ ได้แล้วครับ!"
3201-118 = "น้องคนนี้คือหัวหน้านิยะ~"
3201-120 = "หะ...หืม?! ทำไมฉันถึงเป็นตุ๊กตาดารุมะล่ะ?"
3201-121 = "คะ...คงไม่ได้หมายความว่าฉันเหมือนเจ้าตุ๊กตาดารุมะหรอกใช่มั้ย...?"
3201-122 = "ขอบคุณนะ จะใช้ให้ดีๆ เลย~"
3201-123 = "ครับ ขอบคุณมากเช่นกันครับ ขอให้งานแสดงผ่านไปอย่างราบรื่นนะครับ!"
3201-125 = ""
3201-126 = ""
3201-128 = "ชิเซะจัง?! เครื่องดื่มที่ใช้ในงานพิธี คราวนี้ก็ซื้อน้ำส้มแทนเครื่องดื่มแบบดั้งเดิมงั้นเหรอ?!"
3201-130 = ""
3201-131 = ""
3201-133 = "ซื้อแก้วลายการ์ตูนแทนชุดถ้วยน้ำชาแบบดั้งเดิม?!"
3201-134 = ""
3201-135 = ""
3201-136 = ""
3201-138 = "คราวนี้ก็ซื้อพุดดิ้งกับไอศกรีมมาด้วย?!"
3201-142 = ""
3201-143 = "แฮ่ก... แฮ่ก..."
3201-144 = "ตะ...ต้องรีบวิ่งกลับมาแบบนี้ด้วยเหรอ?"
3201-145 = "จะ...จะให้ชิเซะจังเห็นพวกเราไม่ได้นี่คะ"
3201-146 = "เรื่องนั้นมันก็ใช่อยู่หรอก ว่าแต่ว่าชิเซะคิดจะทำอะไรกันแน่นะ..."
3201-147 = "ซื้อมาแต่ของที่ไม่เคยใช้ทั้งนั้นเลย..."
3201-148 = "นะ...นั่นสิคะ ชิเซะจังน่ะ... "
3201-149 = "จะต้องมีความคิดอะไรดีๆ อยู่แน่นอนค่ะ แต่ว่า..."
3201-150 = ""
3201-152 = ""
3201-154 = "มาแล้ว~"
3201-155 = ""
3201-158 = ""
3201-160 = "นั่งดูคุณพระอาทิตย์อยู่เหรอ?"
3201-161 = "อ๊ะ ชะ...ชิเซะจัง! กลับมาแล้วเหรอคะ?"
3201-162 = "ซื้อของเรียบร้อยดีมั้ยคะ?"
3201-163 = "อื้อ สมบูรณ์แบบ~"
3201-164 = "การแสดงต้องผ่านไปได้ด้วยดีแน่"
3201-165 = "งะ... งั้นเหรอคะ ค่อยยังชั่วหน่อยค่ะ"
3201-166 = "ถ้างั้น... ฉันไปเตรียมตัวก่อนนะ~"
3201-167 = ""
3201-169 = ""
3201-170 = "ชิเซะจัง..."
