[translation]
32080-1 = "#title;제8화;보이기 시작하는 희망"
32080-2 = "3;아즈사;07;늦어!\n#3;a\n#3;em;[반응]"
32080-3 = "3;히후미;04;아하하…… 아즈사 쨩…… 먼저 와 있었네요?\n#3;a\n#3;em;[땀]"
32080-4 = "1;아즈사;01;당연하지. 난 이미 해가 뜨기 전에 준비를 끝내고 여기서 예습과 복습을 하고 있었어.\n#1;ar\n#1;em;[반짝]\n#3;m5"
32080-5 = "5;하나코;02;어머나…… 오늘따라 의욕이 넘치네요, 아즈사 쨩.\n#3;hide\n#5;a"
32080-6 = "1;아즈사;07;당연해. 오늘도 모의 시험을 칠 거잖아?"
32080-7 = "5;히후미;02;아, 네. 맞아요. 오늘도 예정대로 시험을 칠 건데……. 시험 준비를 하고 있었던 거예요, 아즈사 쨩?\n#5;em;[?]"
32080-8 = "1;아즈사;99;음. 평가 시험도 이틀밖에 남지 않았고, 언제까지 모두에게 걱정을 끼칠 수는 없으니까."
32080-9 = "#st;[0,0];instant;1;"
32080-11 = "1;아즈사;01\n#1;m3\n#5;dr\n#wait;1000"
32080-13 = "3;아즈사;07;오늘에야말로 낙제를 벗어나겠어.\n#3;closeup\n#3;em;[!]"
32080-14 = "3;코하루;05;뭐, 뭐야…… 기합이 엄청 들어가 있어…….\n#3;a\n#3;em;…"
32080-15 = "3;아즈사;07;시험 범위의 예상 문제들도 몇 번이고 반복해서 풀어두었고. 대비는 완벽해.\n#3;em;[반짝]"
32080-16 = "1;코하루;11;나, 나도 지지 않을 거니까! 정의실현부의 엘리트의 힘을 보여 주겠어!\n#1;ar\n#1;hophop"
32080-17 = "1;코하루;11\n3;아즈사;07\n5;하나코;03;네♡ 그럼 저도 최선을 다해서 노력할게요!\n#5;al\n#5;em;[하트]"
32080-18 = "[s] \"모두들 뜨겁네.\""
32080-19 = "#st;[0,0];instant;1;"
32080-21 = "1;코하루;11\n3;아즈사;07\n5;하나코;03\n#1;d\n#3;d\n#5;d\n#wait;1000"
32080-22 = "3;히후미;00;아, 아하하…… 그럼 이 기세를 몰아…… 모의 시험을 바로 시작해볼까요?\n#3;a\n#3;em;[반응]"
32080-24 = "#na;제3차 보충수업부 자체 모의 시험"
32080-26 = "[ns] \"그럼 시작-!\""
32080-30 = "#zmc;instant;316,-111;1896\n#na;아즈사;……."
32080-33 = "#zmc;instant;-632,222;1896\n#na;하나코;응, 이건 이렇게……♡"
32080-36 = "#zmc;instant;0,222;1896\n#na;코하루;이, 이거 알고 있는 거야……! 끄, 끄응……. 그러니까……."
32080-37 = "#st;[0,0];instant;1;"
32080-40 = "#na;히후미;(모두들…… 어쩐지 시험 치는 속도가 빨라진 느낌이…….)"
32080-41 = "#st;[0,0];instant;1;"
32080-44 = "#na;(시험 종료 후, 모두의 채점 결과가 나왔다.)"
32080-45 = "3;히후미;05;……선생님. 그럼 발표를.\n#3;a"
32080-46 = "[s] 시험 결과를 확인한다."
32080-47 = "#st;[0,0];instant;1;"
32080-50 = "#stm;[0,400];smooth;80;제3차 보충수업부 자체 모의 시험 결과"
32080-52 = "#stm;[0,250];instant;70;하나코 - 69점 [007eff](합격)[-]"
32080-54 = "#stm;[0,150];instant;70;아즈사 - 73점 [007eff](합격)[-]"
32080-56 = "#stm;[0,50];instant;70;코하루 - 61점 [007eff](합격)[-]"
32080-58 = "#stm;[0,-50];instant;70;히후미 - 75점 [007eff](합격)[-]"
32080-60 = "1;히후미;00;해, 해냈어요?! 모, 모두 다 합격?!\n#1;a\n#1;shake\n#1;em;[?!]"
32080-61 = "5;코하루;03;지, 진짜야?! 저, 정말!?\n#5;a\n#5;hophop\n#5;em;[반응]"
32080-62 = "1;아즈사;03;……!! 해냈어! \n#1;em;[반짝]"
32080-63 = "5;하나코;03;어머나♡\n#5;em;[하트]"
32080-64 = "#st;[0,0];instant;1;"
32080-66 = "1;아즈사;03\n5;하나코;03\n#1;dl\n#5;dr\n#wait;1000"
32080-68 = "3;히후미;03;저, 정말이에요! 아즈사 쨩, 60점이 아니라 70점을 넘겨버렸어요! 굉장해요! 엄청난 상승폭이에요!\n#3;a\n#3;hophop\n#3;em;[반응]"
32080-69 = "1;아즈사;02;으, 응!! \n#1;ar\n#1;em;[반짝]"
32080-70 = "#1;dl\n5;코하루;00\n3;히후미;00;코하루 쨩!! 아슬아슬했지만, 아니, 그러니까 더 값어치있는 성적이에요! 해냈어요!\n#3;m2\n#5;al"
32080-71 = "#1;hide\n5;코하루;00;지, 진짜 내 점수야?! 정말……? \n#5;em;[?!]\n#5;shake"
32080-72 = "5;코하루;03;……아, 아하하하하! 봤지? 봤어? 이게 바로 나의 실력이라고!\n#5;hophop\n#5;em;[재잘]"
32080-73 = "3;히후미;03;네! 맞아요! 진짜 힘을 숨기고 있었나봐요! 진짜 엘리트예요!\n#3;em;[반짝]\n#3;greeting"
32080-74 = "1;하나코;03\n3;히후미;01;하나코 쨩……. 그리고…….\n#3;m4\n#5;dr\n#1;ar"
32080-75 = "1;하나코;03;어머나…… 운이 좋았네요. 우후후후♡\n#5;hide\n#1;em;[하트]"
32080-76 = "3;히후미;01;다행이에요……. 하나코 쨩…… 아우…….\n#3;stiff"
32080-77 = "1;하나코;02;히, 히후미 쨩……?"
32080-78 = "3;히후미;99;하나코 쨩에게 무슨 일이 있었는지는 모르지만…… 실력이 녹슬지 않아서 다행이에요……. \n#3;em;…"
32080-79 = "1;하나코;05;히후미 쨩……."
32080-80 = "3;히후미;01;예전의 그 실력을 되찾을 수 있도록 저도 계속 도울테니까……. 아우…….\n#3;stiff"
32080-81 = "3;히후미;01\n1;하나코;05;응…… 저도 미안해요……. 걱정을 끼쳐서…….\n#1;m2\n#1;em;…"
32080-83 = "3;히후미;03;……해서, 약속대로 모모프렌즈 굿즈 시상식을 시작하겠습니다!\n#3;em;[반짝]\n#3;closeup\n#3;a"
32080-84 = "#st;[0,0];instant;1;"
32080-87 = "1;아즈사;01;음……!! 음!\n#1;a\n#1;em;[반짝]"
32080-88 = "5;하나코;04;…….\n#5;a"
32080-89 = "1;코하루;10;……."
32080-90 = "5;히후미;03;자아, 자아! 모두가 고를 기회가 있어요! 원하는 걸 가져갈 수 있다구요?\n#5;hophop\n#5;em;[반짝]"
32080-91 = "1;아즈사;01;과연……! 원하는 걸……! 으음……!!\n#1;stiff"
32080-92 = "5;하나코;04;저는 사양할게요.\n#5;greeting"
32080-93 = "1;코하루;10;나도 됐어.\n#1;em;…"
32080-94 = "5;히후미;04;아우……. \n#5;em;[땀]"
32080-95 = "1;아즈사;06;나는…… 나는 어쩌지? 나는…….\n#1;stiff"
32080-96 = "1;아즈사;07;고르려고 해도, 도무지…… 고를 수가 없어! \n#1;em;[!]"
32080-97 = "1;아즈사;07;저 새카맣고 뿔이 난 것도 좋은 것 같고, 안경을 쓴 하마도 좋아 보여……!!\n#1;hophop\n#1;em;[반응]"
32080-98 = "5;히후미;04;하마가 아니라 페로로 님은 새……."
32080-99 = "1;아즈사;99;음…… 어쩌지? 둘 중에 하나를 골라야 한다면……. 아, 안돼……."
32080-100 = "1;아즈사;04;……히후미, 나, 나는 무리야…… 고를 수가 없어. 히후미가 대신 골라줘…….\n#1;em;[땀]"
32080-101 = "5;히후미;04;제, 제가요? \n#5;em;[?]"
32080-102 = "5;히후미;01;으, 으음. 그러니까 스컬맨 님과 페로로 박사님 중에 하나를 고르는 거라면……."
32080-103 = "#st;[0,0];instant;1;"
32080-105 = "5;히후미;01\n#5;m4\n#wait;1000"
32080-106 = "5;히후미;01;……."
32080-107 = "#st;[0,0];instant;1;"
32080-109 = "5;히후미;01\n#5;greeting\n#wait;1500"
32080-110 = "#all;hide\n#na;히후미;그럼 인텔리한 페로로 박사님으로!"
32080-111 = "1;아즈사;02;이건가……! 과연!!! 이건가!!!\n#1;em;[반응]\n#1;a"
32080-112 = "5;히후미;03;네, 페로로 박사님은 엄청 아는 것도 많고 공부도 잘한다는 설정이거든요. \n#5;a\n#5;em;[반짝]\n#5;greeting"
32080-113 = "5;히후미;00;지금의 괄목할 만한 성장을 하고 있는 아즈사 쨩이랑 잘 어울리는 거 같아서 골라봤어요!"
32080-114 = "1;아즈사;99;……그렇군. 인텔리한 박사님."
32080-115 = "5;히후미;04;무, 물론 공부를 너무 많이하는 바람에 정신을 놓아버렸다는 뒷설정도 있지만……."
32080-116 = "[s] \"마음에 들었나 봐. 아즈사.\""
32080-117 = "1;아즈사;08;응, 진짜 좋아. 마음에 들어. ……헤헤헤.\n#1;em;[반짝]"
32080-118 = "1;아즈사;03;고마워, 히후미. 평생 소중히 간직할게."
32080-119 = "5;히후미;04;네? 아즈사 쨩, 그렇게까지 대단한 건 아니라구요? 아즈사 쨩이 해내서 받은 거잖아요. \n#5;em;[?]"
32080-120 = "1;아즈사;03;응…… 그래도…… 친구에게 받은 첫 선물이니까……."
32080-121 = "1;아즈사;07;이제부터 이 하마를 히후미라고 생각하겠어!\n#1;em;[!]"
32080-122 = "5;히후미;04;네?! 그, 그건 좀……. 그리고 새라구요, 아즈사 쨩……! 하마가 아니라구요?\n#5;shake\n#5;em;[?!]"
32080-123 = "#st;[0,0];instant;1;"
32080-125 = "1;아즈사;07\n5;히후미;04\n#1;d\n#5;d\n#wait;1000"
32080-126 = "3;하나코;04;으응…… 취향의 세계는 넓네요. \n#3;a"
32080-127 = "3;코하루;10;……기분 나빠.\n#3;em;…"
32080-129 = "#na;(모두들 사기가 충만해져서, 이후 공부는 좋은 분위기로 진행되었다.)"
32080-133 = "#na;(그렇게 또 하루가 지나가고, 시간은 흘러……)"
32080-135 = "3;히후미;05;……드디어 내일이에요, 여러분.\n#3;a"
32080-136 = "3;코하루;00;으응……."
32080-137 = "3;아즈사;01;음. 2차 평가 시험인가."
32080-138 = "3;하나코;02;어머나…… 벌써 시간이 그렇게 되었네요. 눈 깜짝할 사이였어요. \n#3;em;[반응]"
32080-139 = "3;히후미;05;네…… 일주일이라는 짧은 시간이었지만, 그동안 저희의 노력은 헛되지 않았다고 믿습니다."
32080-140 = "3;히후미;06;모의 시험 결과…… 저희는 충분히 2차 평가 시험에서 낙제를 면할 수 있다는 것을 확인했어요!\n#3;em;[반응]"
32080-141 = "3;히후미;06;하지만 저희는 자만하지 않고, 더 정진해야 합니다! 마지막 남은 오늘도 최선을 다하는 거예요!\n#3;closeup\n#3;em;[!]"
32080-142 = "3;아즈사;01;당연하지. 100점을 목표로 노력하겠어.\n#3;greeting"
32080-143 = "1;코하루;11;나, 나도 마찬가지야! \n#1;a\n#1;hophop"
32080-144 = "5;하나코;03;어머나. 그럼 저도 그런 걸로…… 후후♡\n#5;a\n#5;em;[하트]"
32080-145 = "#st;[0,0];instant;1;"
32080-147 = "3;아즈사;01\n1;코하루;11\n5;하나코;03\n#1;d\n#3;d\n#5;d\n#wait;1000"
32080-148 = "3;히후미;05;저, 저는 100점은 무리지만…… 아무튼!\n#3;a"
32080-149 = "3;히후미;06;자, 마지막 날도 힘내서 공부를 시작하는 거예요!\n#3;em;[반응]"
32080-150 = "[s] \"오오-!\""
32080-153 = "3;나기사;01;……. 기다리고 있었습니다. 오랜만에 뵙는 것 같네요, 선생님.\n#3;a"
32080-154 = "3;나기사;02;잘 지내셨습니까? 합숙은 어떠셨나요? 별일은 없으셨나요?\n#3;em;[?]"
32080-155 = "[s] \"이번엔 무슨 일이야?\""
32080-156 = "3;나기사;03;……후후. 합숙은 말하자면 좀 더 학생들을 철두철미하게 관찰하라는 저의 배려였습니다."
32080-157 = "3;나기사;01;어떠셨나요? 소기의 성과는 있었습니까? 무언가 알아내신 것이 있으신가요?"
32080-158 = "3;나기사;02;즉, 배신자는 누구인 것 같나요?"
32080-159 = "[s] \"나는 그것에 동의하지 않는다고 했어.\""
32080-160 = "3;나기사;01;……그러셨죠. 하지만 2차 평가시험을 앞둔 지금, 다시 한번 그 부분을 재확인하고 싶었습니다."
32080-161 = "3;나기사;99;그래서 이렇게 모신 거죠."
32080-162 = "#all;hide\n#na;나기사;그리고 아마 미카 씨도 접촉하신 것 같은데……."
32080-163 = "#st;[0,0];instant;1;"
32080-165 = "3;나기사;01\n#3;d\n#wait;1000"
32080-166 = "3;나기사;01\n#3;a\n#3;closeup\n#wait;1500"
32080-167 = "3;나기사;03;미카 씨가 뭐라고 하던가요? 무언가 알려준 게 있었나요?\n#3;closeup\n#3;em;[반짝]"
32080-169 = "#nextepisode;다음화;검은 손길"
