[translation]
32130-1 = "Episode 13;In Spite of Everything"
32130-2 = "The Make-Up Work Club continued to study hard every day in preparation for the third exam."
32130-3 = ""
32130-5 = ""
32130-7 = ""
32130-8 = ""
32130-9 = ""
32130-10 = ""
32130-11 = ""
32130-12 = ""
32130-13 = ""
32130-14 = ""
32130-15 = ""
32130-16 = ""
32130-19 = ""
32130-20 = ""
32130-21 = ""
32130-22 = ""
32130-24 = "Fourth Make-Up Work Club Mock Exam Results"
32130-25 = "Hanako: 100 Points [007eff](Pass)[-]"
32130-26 = "Azusa: 82 Points [FF6666](Fail)[-]"
32130-27 = "Koharu: 74 Points [FF6666](Fail)[-]"
32130-28 = "Hifumi: 79 Points [FF6666](Fail)[-]"
32130-30 = ""
32130-31 = ""
32130-42 = ""
32130-43 = ""
32130-44 = ""
32130-45 = ""
32130-48 = ""
32130-49 = ""
32130-50 = ""
32130-51 = ""
32130-53 = "Fifth Make-Up Work Club Mock Exam Results"
32130-54 = "Hanako: 100 Points [007eff](Pass)[-]"
32130-55 = "Azusa: 94 Points [007eff](Pass)[-]"
32130-56 = "Koharu: 90 Points [007eff](Pass)[-]"
32130-57 = "Hifumi: 93 Points [007eff](Pass)[-]"
32130-59 = ""
32130-60 = ""
32130-71 = "Sixth Make-Up Work Club Mock Exam Results"
32130-72 = "Hanako: 100 Points [007eff](Pass)[-]"
32130-73 = "Azusa: 91 Points [007eff](Pass)[-]"
32130-74 = "Koharu: 83 Points [FF6666](Fail)[-]"
32130-75 = "Hifumi: 89 Points [FF6666](Fail)[-]"
32130-77 = ""
32130-79 = ""
32130-80 = ""
32130-82 = "Six days until the final exam."
32130-85 = "Five days until the final exam."
32130-88 = "Four days until the final exam."
32130-91 = "Three days until the final exam."
32130-94 = "Two days until the final exam."
32130-97 = "One day until the final exam."
32130-100 = "Tomorrow's the big day."
32130-101 = "That it is. "
32130-102 = "..."
32130-103 = "They aren't going to change the time and place again at the last second, are they?"
32130-104 = ""
32130-106 = ""
32130-107 = "I've checked, and nothing's changed as of yet."
32130-108 = "It's still the same time and place, but we have to score a 90 or higher too. "
32130-109 = "Trinity Building 19, Classroom 32. It's on the outskirts of the district, but not unreasonably far away."
32130-110 = "The exam begins at 9 AM—exactly as scheduled."
32130-111 = "The only strange thing I've noticed this week is how quiet the main campus has been. I haven't seen any students around at all."
32130-112 = "I'm going to keep an eye on the noticeboard just in case."
32130-113 = "But you need to get a good night's sleep just like the rest of us."
32130-114 = "I'll be fine. It's the least I can do for everyone."
32130-115 = "That's not true at all! You've helped us immensely this week. The rest of us were only able to raise our scores as high as we did because of your tutoring."
32130-116 = "You're giving me too much credit. It was you three who put in all the hard work."
32130-117 = "You were burning the candle at both ends every single night to study."
32130-118 = "[s] \"I think you should all be proud.\""
32130-119 = "Scoring a 90 or higher on any test can be hard, but maybe—just maybe—if all the questions seem familiar, then..."
32130-120 = "..."
32130-121 = "That's just wishful thinking! I'm gonna cram all night this time! "
32130-122 = "They can't fail me if I score 100 points! Just watch!"
32130-123 = "That's true Koharu, but I really think you should rest tonight. "
32130-124 = "We all know how hard you've been working. Don't let it go to waste by being too tired to focus tomorrow."
32130-125 = "True. Your body needs to be just as prepared as your mind."
32130-126 = "That goes for you too, Azusa."
32130-127 = "I know. I'll be well-rested—for tonight at least."
32130-128 = ""
32130-130 = ""
32130-131 = "It all comes down to tomorrow."
32130-132 = "I... No, let's leave it at that. I promise to pass tomorrow."
32130-133 = "Me too! I'm not going down like this!"
32130-134 = "It's strange. I was feeling kinda down about our chances. But you two are right—I should be more optimistic."
32130-135 = "You should. Everyone's done the best they can do. "
32130-136 = "[s] \"The situation is dire, sure, but have faith in yourselves.\""
32130-137 = "Yes, Sensei."
32130-138 = "Right."
32130-139 = "Yes."
32130-140 = "..."
32130-142 = "Less than 12 hours until the final exam."
32130-148 = "..."
32130-149 = ""
32130-151 = ""
32130-153 = "..."
32130-155 = ""
32130-156 = "The fated day has changed, Azusa."
32130-157 = "It has?"
32130-158 = ""
32130-159 = "Tomorrow morning. Wait for further orders at the agreed point."
32130-160 = "H-Hold on, Saori. Tomorrow, I'm supposed to be... "
32130-161 = "Is there a problem?"
32130-162 = "Preparations are incomplete. Changing to an earlier date poses an immense risk."
32130-163 = "The decision is final. Trust your training and be ready, Azusa."
32130-164 = "..."
32130-165 = "The course of history will change tomorrow—for both Arius and Trinity."
32130-166 = "Don't lose sight of your mission. You are to destroy the halo of the Tea Party's leader, Kirifuji Nagisa. Nothing else matters."
32130-167 = "..."
32130-168 = "I know you can handle yourself. Just as you did with Seia."
32130-169 = "Understood. I won't object any further."
32130-170 = "I should prepare for tomorrow's mission."
32130-171 = ""
32130-173 = ""
32130-174 = ""
32130-175 = "Azusa."
32130-176 = "...?"
32130-177 = "Never forget. Vanitas vanitatum."
32130-178 = "Everything is in vain. Of course."
32130-179 = "All efforts, achievements, and even failures are meaningless in the end."
32130-180 = "I've never lost sight of that—not even once."
32130-181 = ""
32130-183 = ""
32130-185 = "..."
32130-187 = "..."
32130-189 = "Next Episode;A Confession"
