[translation]
32180-1 = "Episode 18;The Way of the World Part 2"
32180-2 = "The Sisterhood...?"
32180-3 = "Urawa Hanako!"
32180-4 = "That's right. I did eventually decide to take someone up on their offer and made a pact of my own."
32180-5 = "A pact?"
32180-6 = "Nothing you need to concern yourself with. Besides..."
32180-7 = ""
32180-10 = ""
32180-11 = "*cough* May peace and happiness be with you today."
32180-12 = "Apologies for barging in like this."
32180-13 = "We've decided to break our customs and involve ourselves with the Tea Party's internal struggle."
32180-14 = "Misono Mika of the Tea Party. You are under arrest for attempting and instigating harm to your fellow Tea Party members."
32180-16 = ""
32180-17 = "You must be Utazumi Sakurako of the Sisterhood."
32180-18 = "Hahaha! This is my first time fighting the Sisterhood! So is this the trump card you've had up your sleeve? "
32180-19 = "Just how did you manage to get them involved, Hanako?"
32180-20 = "I knew you were acquainted with them at one point, just as you were with everyone. What did you offer in return, I wonder. These interlopers wouldn't lift a finger unless they stood to gain something from it."
32180-21 = "..."
32180-22 = "How intriguing, though I do find it annoying to have more pests to exterminate."
32180-23 = "Sounds to me like you're becoming restless, Mika."
32180-24 = "I planned to clean out the cathedral when I became host anyway. This just saves me some time."
32180-25 = ""
32180-27 = ""
32180-29 = "All right, everyone. Shall we get started?"
32180-30 = ""
32180-32 = ""
32180-33 = "Do you really intend to keep fighting?! It's pointless, Mika. Put down your weapon."
32180-34 = "That may be true, but I can't simply surrender. Not after coming this far."
32180-36 = "I'll stop at nothing."
