[translation]
33030-1 = "Episode 3;Postmortem Part 3"
33030-2 = "Trinity Confinement"
33030-3 = ""
33030-4 = ""
33030-5 = "I thought I'd never see you again."
33030-6 = "Please. You know that we're inseparable, whether we like it or not. "
33030-7 = "You're right. It's been that way ever since we were little girls."
33030-8 = "..."
33030-9 = "So why did you come? It couldn't have been to interrogate me. They've been putting me through the wringer enough as is already."
33030-10 = "Whatever it is, it must be important if you came all the way here in person."
33030-11 = "..."
33030-12 = "It's about Arius' Squad."
33030-13 = "The covert special operations unit organized by Arius' student council president. "
33030-14 = "What more do you want to know? I've already said everything I know during my interrogation. "
33030-15 = "From how I got in contact with Arius, to the roles of each Squad member..."
33030-16 = "Yes, I'm aware. "
33030-17 = "Do you think I'm still hiding something? Wanna torture it out of me? I've heard the Sisterhood is a big fan of that kind of stuff."
33030-18 = "Those were the former Council's methods, not the Sisterhood's. Something so inhumane would never be tolerated in today's day and age."
33030-19 = "I know, I know. You hate things like that—I was only messing with you."
33030-20 = "..."
33030-21 = "I know this must sound weird coming from me, but is Arius really a big deal anymore?"
33030-22 = "They don't have access to more troops, weapons, or supplies without me backing them."
33030-23 = "Even if Squad still has it out for Trinity, isn't the Justice Task Force more than capable of handling them and any other remaining soldiers from Arius?"
33030-24 = "Yes, that's been taken into consideration already. Arius shouldn't be a threat as far as the Eden Treaty is concerned."
33030-25 = "I thought so... Oh, and for the record, I did try to find the location of their district, but it wasn't easy. "
33030-26 = "The only person who knows how to enter it is Saori, the leader of Squad."
33030-27 = "If you really want to know, you could always ask Azusa. She may have betrayed them, but she was still an Arius student."
33030-28 = "Normally I could, but...  "
33030-29 = "Oh, I get it. She's under Schale's protection now, isn't she?"
33030-30 = "You really did get on Sensei's bad side, huh, Nagi? Now you're too uncomfortable to ask for a favor."
33030-31 = "Sensei's allegiances are with the students, so they're not going to do anything that would put Azusa in jeopardy."
33030-32 = "..."
33030-33 = "The two of you probably haven't seen each other since everything that happened, have you? It's written all over your face."
33030-34 = "You can't bring yourself to face Sensei after being so harsh. Aw, even you can be a bashful young lady, Nagi. Hahaha."
33030-35 = "Not that I don't know what it feels like."
33030-36 = "Sensei has come to visit a lot. It was hard having to decline each time."
33030-37 = "Well, I'm stuck here either way. I guess Sensei could use Schale's sway to force a meeting, but they would never do that—which somehow makes it even more annoying."
33030-38 = "They never quite do what you want them to. I tried leaking all that misinformation, and it still didn't faze Sensei."
33030-39 = "Things would have been so much simpler if Sensei had just believed one of us and did as they were told."
33030-40 = "Or had they simply leaked everything I said, I wouldn't be in this predicament."
33030-41 = "..."
33030-42 = "Well, either way. Don't you think everything turned out for the best?"
33030-43 = "The real traitor is imprisoned, Arius is hardly a threat... "
33030-44 = "...and now the Eden Treaty can be signed as planned. You can finally find the peace you've been longing for, Nagi."
33030-45 = "Such a happy ending. Isn't that nice?"
33030-46 = "..."
33030-47 = "No, it's not. "
33030-48 = "What do you have to be happy about, Mika? You're the traitor. "
33030-49 = "You tried to destroy my halo."
33030-50 = ""
33030-51 = "..."
33030-52 = "And for what? Because you hate Gehenna? You were willing to kill a friend you've known for most of your life over something as petty as that?"
33030-53 = "And Seia too. Why? "
33030-54 = "..."
33030-55 = "I was terrified when word of Seia's supposed death reached me... "
33030-56 = "I couldn't help but think I was next."
33030-57 = "She's the wisest of us and even has prophetic dreams that she's used to her advantage. No one at Trinity is more dangerous than her. That's why she was targeted first."
33030-58 = "And given your...political prowess, I assumed I was next. "
33030-59 = "What is that supposed to mean?"
33030-60 = "Anyway, I knew everything would fall on your shoulders if something were to happen to me, and I couldn't let that happen."
33030-61 = "I was desperate to find the culprit before it came to that. I didn't want you to be left all alone. I didn't want you to be hurt either."
33030-63 = "But who could be behind it? Gehenna? The General Student Council? Or that Big Sister from Millennium? Perhaps the tyrant from Red Winter? Or maybe the Dark Monarch of Shanhaijing..."
33030-64 = "Or was there a traitor in our midst? It seemed unthinkable, but then again..."
33030-65 = "And then I... I... "
33030-66 = "Slow down, Nagi. "
33030-67 = "It isn't that complicated. I hate Gehenna—so much that I was willing to kill a dear old friend. All right? "
33030-68 = "Is that really all there is to it? There wasn't some kind of mistake or misunderstanding or subconscious belief that you couldn't control or...?"
33030-69 = "Hahaha. What other reason could there be?"
33030-70 = "This is why I always liked you, Nagi. You're just so pure. Pure and naive."
33030-71 = "There's nothing you're missing. I tried to kill Seia and then you. That's all there is to it."
33030-72 = "You know how extreme I can be when it comes to my likes and dislikes. I just can't get along with those scum from Gehenna. I don't want to link arms with them and pretend to be friends."
33030-73 = "Doesn't it make your skin crawl just having to coexist in the same city with them?"
33030-74 = "And that's why you formed an alliance with Arius?"
33030-75 = "Obviously. What else was a murderer like me supposed to do? "
33030-76 = "Even if Seia is alive, I was still the one who tried to kill her.#nThat isn't going to change."
33030-77 = "And you never even realized it, Nagi."
33030-78 = "But how...?"
33030-79 = "How did you know me for so long without realizing the truth? "
33030-80 = "You should know the answer to that better than I do. "
33030-81 = "Because we're strangers at the end of the day. We've put up so many walls between us that there's no way we could ever truly know one another."
33030-82 = "... "
33030-83 = "I'll be leaving now, Mika."
33030-84 = "Take care, Nagi. Sorry I can't see you out."
33030-86 = ""
33030-87 = "..."
33030-88 = ""
33030-90 = ""
33030-91 = "Why lie to her like that?"
33030-92 = "I sure do have a lot of visitors today. So you're next, huh, Hanako?"
33030-93 = "Yes, but this isn't a personal visit. I'm here on business. "
33030-94 = "That makes sense. Since you didn't enter with Nagi, then are you here on the Sisterhood's behalf? Following their orders now?"
33030-95 = "Not that it matters to me either way. Anyway, what were you talking about just now? I wasn't lying."
33030-96 = "..."
33030-97 = "I've been performing a postmortem investigation on your actions based on all the information I've received from the Sisterhood."
33030-98 = "In other words, I've been analyzing what Misono Mika's motive was."
33030-99 = "Wow, how daring to admit that right in front of the person in question. A little tasteless too."
33030-100 = "You tried to destroy the Eden Treaty because of your hatred of Gehenna. That much is clear."
33030-101 = "..."
33030-102 = "What I don't know is who goaded you into that decision or why you ultimately teamed up with Arius to become the new host."
33030-103 = "Your initial plan was probably to simply abduct Seia and hold her captive. Really, that's all that needs to happen for the title of host to change hands."
33030-104 = "But Arius' Squad had different plans. They were out to destroy Seia's halo from the very beginning."
33030-105 = "That isn't where the story ends, though."
33030-106 = "You were initially told that Seia was dead. "
33030-107 = "And I'm guessing that's when you began to have a mental breakdown."
33030-108 = "You likely fell into panic. You became a \"murderer\" in your own mind, and nothing was going to convince you otherwise."
33030-109 = "There was no turning back. You weren't going to stop until you achieved what you set out to do. What other choice was there?"
33030-110 = "You must have been wallowing in despair and driven by destructive impulse. "
33030-111 = "Hooold on just a second. "
33030-112 = "Don't you know it's rude to psychologically analyze someone straight to their face? "
33030-113 = "I was the one who gave the order to kill Seia, and I was the one who stabbed my childhood friend, Nagi, in the back. Despair? Impulsive? What are you talking about? Are you an idiot?"
33030-114 = "No, but I do have a very good memory."
33030-116 = ""
33030-117 = "Destroying her halo wasn't part of the plan, though. Give me a little credit—I'm not a murderer."
33030-118 = "It's all because of that little mishap that things have gotten out of hand like this."
33030-119 = "Get it? I can't turn back now because of that—because of you."
33030-121 = ""
33030-122 = "There are a few other things that don't add up."
33030-123 = "I was under the impression there really was a traitor out there, but I didn't think she would reveal herself then and there."
33030-124 = "After all, that would mean throwing away her biggest advantage: anonymity."
33030-125 = "No strategist would choose to do that. It doesn't make any sense..."
33030-126 = "That is one regret I had. I really goofed that one up."
33030-127 = "You didn't let me finish. It doesn't make any sense...unless you were afraid that Arius was going to kill Nagisa too. "
33030-128 = "..."
33030-129 = "Isn't that right? You were afraid they would kill her like they did Seia."
33030-131 = ""
33030-132 = "So hand her over. I promise not to kill her. She may have to spend the rest of her school life in confinement, but it won't be so bad."
33030-134 = ""
33030-135 = "..."
33030-136 = "You're stronger than you're given credit for, Mika. Sure, you proved you're just as strong in combat as someone like the Justice Task Force's president, but it's more than that."
33030-137 = "I did my best to keep my composure during our confrontation, but in reality,#nI knew how precarious the situation was."
33030-138 = "I had to be prepared for the worst case scenario—that even the Sisterhood would be forced to retreat."
33030-139 = "But then you surrendered. You were resigned after hearing that Seia was still alive."
33030-140 = "Enough."
33030-141 = "What are you trying to say?"
33030-142 = "Are you taking pity on me? Will you claim I never meant a single word I said or that I didn't intend for any of those terrible things to happen? That I was just a confused, stupid little girl who made a bad choice or two?"
33030-143 = "Hahaha!"
33030-144 = "You're so funny, Hanako. Absolutely hilarious."
33030-145 = ""
33030-147 = ""
33030-148 = "It really isn't that complicated. I'm just a traitor—a murderer who sold out her friends and allies to hold on to a grudge in her twisted, treacherous heart."
33030-149 = "I'm not trying to hide that fact anymore. I deserve to be hated after everything I did."
33030-150 = "Even if I did have some other underlying motives, how would you ever know for sure? "
33030-151 = "The truth as you know it can only be what you see. So denying what's right in front of you makes you blind. Isn't that right, Hanako?"
33030-152 = "Why desperately cling to something you can't possibly prove? Hmm? "
33030-153 = "I just wanted...to... "
33030-154 = "Say, how is Seia doing right now? You two were close, weren't you?"
33030-155 = "Are you sure she's safe? Was the real lie that she was dead all along? If that's not the case, then why can't I see her?"
33030-156 = "You wouldn't just torment me with lies like that, would you? That's so malicious. Maybe you're the one we need to be suspicious of."
33030-157 = "... "
33030-158 = "I'll be going now, Mika. "
33030-159 = "I won't share my speculations with anyone else. Not even Nagisa."
33030-160 = "Do whatever fancies you. It doesn't really concern me."
33030-161 = "I will. And I'll keep all of this from [USERNAME] Sensei too."
33030-162 = "..."
33030-163 = "That's what you deserve for betraying Sensei, isn't it?"
33030-164 = "..."
33030-165 = "Take care, Mika. "
33030-166 = ""
33030-168 = ""
33030-169 = "..."
33030-170 = "..."
33030-171 = ""
33030-173 = ""
33030-176 = "I may be despicable, but you're downright cruel, Hanako."
33030-178 = "[ns] \"...\""
33030-179 = "So much for keeping quiet about it. That's what she said. "
33030-180 = "I just wanted to tease her a little bit...but I may have gone too far again."
33030-181 = "I should apologize to her some time for losing my composure like that."
33030-182 = "For now, I think that sums up everything we know about the incident. "
33030-183 = "Mika despises Gehenna so much that she conspired against her fellow Tea Party members."
33030-184 = "She ordered the attack on Seia, which Squad carried out. That was when Azusa destroyed the room Seia was staying in. "
33030-185 = "Each party was acting with their own motives in mind."
33030-186 = "The end result was them stepping on each other's toes due to constant distrust and misunderstandings."
33030-187 = "Leading us to where we are now. That's everything we know, Sensei."
33030-188 = "[ns] \"It still feels like something's missing.\""
33030-190 = "[ns] \"Could this have started with Mika wanting to tease Seia?\""
33030-191 = "Where's this coming from?"
33030-192 = "It's a bit of an extreme thought experiment, but in that case... "
33030-193 = "Hmm. Let's consider Mika's personality first. "
33030-194 = "Everyone knows Mika and politics don't mix, and despite the recent...revelations, that seems to hold true. She's the type to act before weighing the pros and cons."
33030-195 = "It could be that she was looking to get back at Seia for always admonishing her and treating her like a child."
33030-196 = "Admittedly, Seia is the type that can...push people's buttons sometimes."
33030-197 = "Still, if Mika was just looking for a little friendly revenge, why involve Arius? "
33030-198 = "It just doesn't seem realistic. Actually, had she used that excuse, I would have called it too convenient. "
33030-199 = "[s] \"Maybe.\""
33030-200 = "Don't tell me you're conceding on that idea already."
33030-201 = "[s] \"But what if Mika really did want to reconcile with Arius?\""
33030-202 = "... "
33030-203 = "You're proposing that she approached Arius in the hope of reconciling, but all they did was take advantage of her. They used her hatred of Gehenna against her."
33030-204 = "No, what you really mean is..."
33030-205 = "...it's impossible to know Mika's true intentions from the outside looking in."
33030-206 = "[s] \"Can we prove anyone has ever reached paradise?\""
33030-207 = "The fifth koan... "
33030-208 = "Those who reach paradise cannot be found—and should not exist—outside of paradise... Therein lies the paradox of trying to prove paradise's existence."
33030-209 = "[s] \"In other words, how can you prove someone else's sincerity?\""
33030-210 = "..."
33030-211 = "That's right. If we could truly understand someone else's perspective, it wouldn't be theirs anymore. In which case, it would be impossible to prove their sincerity. "
33030-212 = "In this analogy, paradise would be the sincerity of others. Is that what you mean to say?"
33030-213 = "That may be. It's impossible to touch someone's heart directly. "
33030-214 = "We can't prove the sincerity it holds, just as we can't prove anyone has ever reached paradise."
33030-215 = "It's a paradox, through and through. So it's impossible to know anyone's true intentions? "
33030-216 = "[s] \"Seemingly.\""
33030-217 = "..."
33030-218 = "[ns] \"There's no point in trying to prove the impossible.\""
33030-220 = "[ns] \"That's why you have to have faith.\" "
33030-222 = "[ns] \"You have to believe in paradise, and you have to put trust in others.\""
33030-223 = "..."
33030-224 = "I suppose you're right. "
33030-225 = "That's how you've always been, Sensei. Even from the very beginning when there was so much doubt swirling and so many lies."
33030-226 = ""
33030-229 = ""
33030-232 = ""
33030-235 = ""
33030-238 = ""
33030-241 = ""
33030-244 = ""
33030-247 = ""
33030-250 = ""
33030-252 = ""
33030-253 = "You were even fair to Mika and Nagisa. "
33030-254 = "You're the kind of person who will always trust their students...even if it leads to betrayal. Right?"
33030-255 = "[s] \"I do my best to sympathize with them, even if it comes to that.\""
33030-256 = "Why? How can you be so understanding?"
33030-257 = "[s1] \"It's a teacher's job to trust their students.\"\n[s2] \"Adults have a responsibility to lead by example.\""
33030-260 = ""
33030-264 = "[ns3] \"I have faith that those two will make up some day.\"\n[ns4] \"I hope Nagisa and Mika can open up to each other.\""
33030-269 = "[ns] \"Maybe not now, but someday surely.\""
33030-272 = "[ns5] \"Maybe once the Eden Treaty has been put to rest.\"\n[ns6] \"I'd like to bring them together and talk.\"\n[ns7] \"Hopefully, all of us can bury the hatchet and move on.\""
33030-273 = "I think that's a wonderful idea. I'd like for all of us to get together once all of this is over."
33030-274 = "I think that's a wonderful idea. I'd like for all of us to get together once all of this is over."
33030-275 = "I think that's a wonderful idea. I'd like for all of us to get together once all of this is over."
33030-276 = "There's no reason we shouldn't keep struggling to reach one another, right?"
33030-277 = "[s] \"It's the only thing we can do.\""
33030-278 = "You're absolutely right."
33030-282 = "Next Episode;What Comes Next"
