[translation]
33070-1 = "ตอนที่ 7;วันแห่งการมอดไหม้และเถ้าถ่าน (1)"
33070-3 = "กรี๊ดดดดดดด!!"
33070-4 = "ทางนี้~ มีคนบาดเจ็บทางนี้ค่ะ!"
33070-5 = "แค่กๆ แค่กๆ"
33070-7 = "เกิดเหตุฉุกเฉินค่ะ! เกิดระเบิดไม่รู้ที่มาในวิหารโบราณค่ะ! นี่มันอะไรกัน...!"
33070-8 = "ตอนนี้ไฟกำลังลุกโชนวิหารโบราณค่ะ! ไม่นะ! ยอดวิหารกำลังถล่มลงมาแล้ว!"
33070-9 = "นางิจัง... "
33070-12 = "กรี๊ดดดด!!"
33070-13 = "อ๊ากกก! ระวังนะ!"
33070-14 = "ทำยังไงดี... ตอนนี้..."
33070-15 = ""
33070-17 = ""
33070-18 = "อาซึสะจังหายตัวไปค่ะ!"
33070-19 = "พะ...พวกรุ่นพี่... ทำยังไงดี... "
33070-20 = "ไม่นะคะโคฮารุจัง ฮิฟุมิจัง! "
33070-21 = "อย่าเพิ่งรีบร้อนจนกว่าจะเข้าใจสถานการณ์สิคะ!"
33070-22 = "คะ? แต่ว่า... อาซึสะจัง..."
33070-24 = "อาซึสะจังต้องดูแลตัวเองได้อยู่แล้วละค่ะ ตอนนี้เราจะแยกย้ายกันไม่ได้นะคะ!"
33070-25 = "ตะ... แต่ว่า... "
33070-26 = "ฮานาโกะจัง... โคฮารุจัง.... เราจะทำยังไงกันดี..."
33070-30 = "(เกิดเรื่องอะไรขึ้นน่ะ...?)"
33070-31 = "(ระเบิด...? ถูกโจมตี? สถานการณ์เป็นยังไงเนี่ย?)"
33070-32 = "(เสียงนั่นมัน... เสียงของวัตถุที่บินด้วยความเร็วสูง? และยิ่งมีพลังยิงขนาดนี้...)"
33070-33 = "(ขีปนาวุธร่อน? ระบบป้องกันการต่อสู้ทางอากาศรวดเร็วขนาดที่ไม่สามารถสกัดกั้นได้...?)"
33070-34 = "(เครื่องยนต์แรมเจ็ต...? ในคิโวทอสมีเทคโนโลยีแบบนี้ด้วยเหรอ...)"
33070-35 = "(ไม่หรอก มันไม่น่าจะระเบิดได้แรงถึงขนาดนั้น... หรือว่ามีระเบิดซ่อนอยู่ในวิหารโบราณอยู่ก่อนแล้ว?)"
33070-36 = "(ตรงไหนนะที่เป็นกลอุบาย...? แล้วใครกัน? ทรีนิตี้เหรอ? หรือว่าชมรมซิสเตอร์? ในเวลานี้มัน...)"
33070-38 = "(ไม่ดีกว่า... หยุดคิดเถอะ ตอนนี้ต้องโฟกัสตรงนี้ก่อน) "
33070-39 = "(โชคดีที่อาโกะปลอดภัย... งั้นต้องรีบเคลื่อนไหวแล้ว...)"
33070-40 = "(......)"
33070-41 = "คุณครูล่ะ...!!?"
33070-43 = "คะ... คุณฮินะยังยืนอยู่เลยค่ะ"
33070-44 = "ทำยังไงดีล่ะคะ? ยืนหยัดอยู่ท่ามกลางการโจมตีขนาดนั้นได้ไง ยอดเยี่ยมเลย ทำไมยังสู้ต่อได้อีก...#nโดนขนาดนั้นน่าจะเจ็บนะ น่าจะทรมานมากเลย... แต่ทำไมถึง..."
33070-46 = "จัดการซะ อย่าปล่อยฮินะไปเด็ดขาด "
33070-47 = "ค่ะ... ค่ะ! ฉะ... ฉันจะพยายามค่ะ! "
33070-48 = ""
33070-49 = ""
33070-50 = ""
33070-51 = "ขอโทษนะคะ ขอโทษที่เกิดเรื่องแบบนี้นะคะ... แหะๆ"
33070-53 = "(โรงเรียนสาขาอาเรียส)"
33070-54 = "ขะ... ขอโทษด้วยนะคะ คุณจะไปไหนไม่ได้ค่ะ... แหะๆ... ฉันเองก็ได้รับคำสั่งมาอีกที..."
33070-56 = "......."
33070-57 = "หลบไป"
33070-58 = "มะ... มันต้องเจ็บปวดมากแน่ๆ ค่ะ"
33070-59 = ""
33070-63 = "หึหึหึหึหึหึหึ! "
33070-64 = "สำเร็จ! เป็นไปตามแผน! ฮะฮะฮ่ะฮ่ะฮ่าาาา!!!"
33070-65 = "รุ่นพี่มาโคโตะ... ทำอะไรลงไปคะเนี่ย..."
33070-66 = "คนที่ขัดขวางหายไปหมดแล้วล่ะ ทั้งสภาน้ำชา ทั้งฮินะที่ไม่อยากจะมองให้เสียสายตา"
33070-67 = "นี่เธอไม่รู้เหรออิโรฮะ? นี่แหละที่เรียกว่ายิงปืนนัดเดียวได้นกสองตัว "
33070-69 = "เรากับอาเรียสที่เกลียดชังทรีนิตี้แอบติดต่อกันอย่างลับๆ มานานแล้วล่ะ!"
33070-70 = "เรารู้ทั้งการทะเลาะกันภายในของสภาน้ำชา แล้วก็การยึดอำนาจด้วย เพื่อแผนการในวันนี้ไงล่ะ!"
33070-72 = "ยึดอำนาจ...? "
33070-73 = "ทำแบบนั้นตามอำเภอใจได้ไง... รุ่นพี่ไม่ได้คิดจะทำสนธิสัญญาเอเดนตั้งแต่แรกแล้วสินะคะ"
33070-74 = "ใช่! เราไม่สนใจเรื่องแบบนั้นหรอก คิดไปก็ปวดหัวเปล่าๆ!#nสิ่งเดียวที่เราสนใจคือการกำจัดคนที่จะมาขวางทาง!"
33070-75 = "เพื่อดึงตัวพวกสภาน้ำชาที่ไม่ยอมเปิดเผยตัวออกมาไงล่ะ!#nเราก็แค่แกล้งเห็นดีเห็นงามกับสัญญาเอเดนอะไรนั่น!"
33070-76 = "แล้วก็ได้กำจัดฮินะไปพร้อมกันด้วย หึหึหึ!"
33070-77 = "อาเรียสให้ความช่วยเหลือเรื่องนี้ไว้มากมายเลยล่ะ เครื่องบินลำนี้เป็นของขวัญของมิตรภาพที่ทางนั้น#nเตรียมไว้ให้ ศัตรูของศัตรูก็คือเพื่อน ไม่สิ ขอเรียกว่าพันธมิตรเลยดีกว่า หึหึหึหึ! "
33070-78 = "เอาล่ะ จงไปติดต่ออาเรียส เริ่มปฏิบัติการทำลายทรีนิตี้ได้"
33070-79 = "ทุกคนที่ขัดขวางเราก็หายไปหมดแล้ว ทั้งฮินะและนางิสะ"
33070-81 = "เราจะลบทรีนิตี้ออกจากแผนที่เลย!"
33070-83 = "รุ่นพี่มาโคโตะ... อาเรียสเกลียดชังพวกเรามากกว่าทรีนิตี้นะคะ#nไม่มีทางที่พวกนั้นจะมาจับมือกับเราหรอกค่ะ"
33070-84 = ""
33070-86 = ""
33070-88 = "ว่าไงนะ...?!"
33070-89 = "เอ๋? ตรงนี้มีกล่องอะไรเยอะแยะเลย อะไรกันเนี่ย? โปรดระวัง? วัตถุไวไฟ? ระเบิดเหรอ? "
33070-90 = "เฮ้อ... ในที่สุดก็เกิดเรื่องแบบนี้อีกจนได้นะคะรุ่นพี่มาโคโตะ "
33070-92 = "ตู้มมมมมมมมม!!"
33070-96 = "ทีม II รายงานด้วย"
33070-97 = "ทีม II รายงาน เราเข้ามาในวิหารโบราณแล้ว ใกล้ปะทะกับชมรมทวงความยุติธรรมแล้ว หัวหน้าล่ะ?"
33070-98 = "อื้ม งานทางนี้เสร็จแล้ว "
33070-99 = "ตอนนี้ทีม III กำลังปะทะกับฮินะค่ะ! ส่วนทีม V กำลังลงไปชั้นใต้ดินตามแผนการค่ะ!"
33070-100 = "เข้าใจแล้ว เดี๋ยวฉันจะรีบไปสมทบ"
33070-102 = "ทรีนิตี้กับเกเฮนน่า... ในที่สุดก็ถึงเวลาชำระหนี้ความเกลียดชังที่ยาวนานแล้ว "
33070-103 = "ใช่แล้วล่ะ อาเรียสจะตัดสินทุกอย่าง..."
33070-105 = "ในนามของสวรรค์..."
33070-107 = "...ครู!"
33070-108 = "คุณครู! ตั้งสติไว้ก่อนนะคะ!"
33070-109 = "[s] \"อะโรน่า...?\""
33070-110 = "เป็นอะไรหรือเปล่าคะ? เกิดเรื่องใหญ่แล้วค่ะ คุณครูต้องตั้งสติไว้นะคะ!"
33070-111 = "[s] \"เกิดเรื่องอะไรขึ้นน่ะ?\""
33070-112 = "วิหารโบราณถูกระเบิดจนพังไปแล้วค่ะ หนูพยายามปกป้องคุณครูมากเลย..."
33070-113 = "คุณครูไม่ไหวแล้วเหรอคะ... รับพลังจากหนูไปนะ... ตั้งสติแล้วทำใจดีๆ ไว้ก่อนนะคะ!"
33070-114 = "[s] \"หืม...? อะโรน่า?\""
33070-115 = ""
33070-120 = ""
33070-122 = ""
33070-125 = "[ns] (เมื่อกี๊มัน...)"
33070-127 = "คุณครู…!"
33070-129 = "คุณครู... แค่กๆ แค่กๆ... ปลอดภัยใช่ไหมคะ?"
33070-130 = "[ns] (ขยับตัวไม่ได้...)"
33070-131 = "โล่งอกไปที ทำไมถึงมาอยู่ในเศษซากพังทลายแบบนี้ได้ล่ะคะ... "
33070-132 = "รอเดี๋ยวนะคะ ฉันจะขยับก้อนปูนนั้นให้เองค่ะ...!"
33070-133 = ""
33070-136 = "การมีพละกำลังมันเป็นประโยชน์อย่างนี้นี่เอง... เอาละค่ะคุณครู พอจะลุกไหวไหมคะ?"
33070-137 = "[ns] ลุกขึ้น"
33070-139 = "ไม่มีตรงไหนบาดเจ็บเลยเหรอคะ? ระเบิดรุนแรงขนาดนี้ ทำไมไม่มีแผลเลย... นี่มันยิ่งกว่าปาฏิหาริย์อีก..."
33070-140 = ""
33070-142 = ""
33070-143 = "คุณครู! ไม่เป็นอะไรใช่ไหมคะ?"
33070-144 = "อึ่ก... คุณครู!!"
33070-145 = "ชมรมทวงความยุติธรรม... เดี๋ยวนะ แผลนั่นมัน..."
33070-146 = "[s] \"ทุกคนไม่เป็นอะไรใช่ไหม? \""
33070-147 = "แค่นี้ไม่เป็นอะไรหรอกค่ะ แต่ว่าระเบิดนี้ทำให้สมาชิกส่วนใหญ่ของชมรมทวงความยุติธรรม#nต่อสู้ไม่ได้เลยค่ะ"
33070-148 = "คุณนางิสะกับคุณซากุระโกะที่อยู่ที่นี่... รวมถึงคนสำคัญๆ ที่มาที่นี่ก็... หายตัวไปแล้วค่ะ... นอกจากนี้..."
33070-149 = "คนจากเกเฮนน่าก็หายตัวไปด้วยค่ะ... นี่มันเกิดเรื่องอะไรกันคะ..."
33070-151 = "!!"
33070-152 = ""
33070-157 = ""
33070-158 = "มายังพื้นที่ยุทธศาสตร์และพบชมรมทวงความยุติธรรมที่เหลือ...#nไม่สิ ไม่ใช่คนที่เหลือแต่เป็นทุกคนในชมรม"
33070-159 = "ซึรุกิกับฮาสุมิ... ช่วยส่งกองกำลังมาทางนี้ทีสิ จะเข้าปะทะแล้วนะ"
33070-161 = "โรงเรียนสาขาอาเรียส...?! "
33070-162 = "ทำไมถึงมีกองกำลังขนาดนั้น...?! มาได้ยังไงคะเนี่ย?!  แถวนี้น่าจะถูกปิดกั้นไปหมดแล้วนี่! "
33070-163 = "ยะ... อย่าบอกนะว่า...!"
33070-166 = ""
33070-167 = "มาทางชั้นใต้ดิน? ผ่านสุสานใต้ดินใต้วิหารโบราณเหรอ...?"
33070-168 = "......."
33070-169 = "สถานการณ์นี้มัน... แบบนี้เองเหรอ เป็นฝีมือของอาเรียสสินะคะ"
33070-170 = "ยกโทษให้ไม่ได้ค่ะ... คุณต้องชดใช้บาปที่ทำลงไปมาเดี๋ยวนี้..."
33070-171 = "ฮาสุมิ..."
33070-172 = ".......!"
33070-173 = "ใจเย็นๆ ก่อน"
33070-174 = "อืม... จริงด้วยค่ะซึรุกิ"
33070-175 = "ขอบคุณนะคะ ตอนนี้ความปลอดภัยของคุณครูคือสิ่งสำคัญที่สุด เราจะพาคุณครูออกไปจากที่นี่ค่ะ"
33070-176 = "อื้ม ส่วนเรื่องที่ต้องออกแรง ให้เป็นหน้าที่ฉันเอง"
33070-177 = "หึหึหึหึ... โดนแน่... "
33070-178 = "คนที่จะฆ่าเจ้าพวกนี้!  ก็คือฉันเองงงงงง!!"
33070-180 = "คิกคิกคิกกกกกกก!"
33070-181 = "ไปเถอะค่ะคุณครู!"
