[translation]
33240-1 = "#title;제24화;우리의 것이 아닌 증오"
33240-2 = "3;사오리 부상;S2_07;나는…….\n#3;a"
33240-3 = "3;사오리 부상;S2_09;시라스…… 아……즈사…….\n#3;em;…\n#3;stiff"
33240-4 = "#st;[0,0];instant;1;"
33240-7 = "3;아즈사 부상;01;하아…… 하아…… 하아…….\n#3;a\n#3;stiff\n#3;em;…"
33240-8 = "#st;[0,0];instant;1;"
33240-10 = "3;아즈사 부상;99\n#3;falldownL\n#wait;1500"
33240-12 = "[ns] \"아즈사!\""
33240-13 = "#na;아즈사 부상;못 움직이겠어…… 선생님……."
33240-15 = "3;아츠코 부상;01\n#3;a\n#wait;1500"
33240-16 = "3;아츠코 부상;01;……."
33240-17 = "#na;아즈사 부상;아츠코……."
33240-18 = "#na;사오리 부상;쿨럭…… 공주님…… 어째서…… 도망치지 않고……."
33240-19 = "#all;hide\n#na;아츠코 부상;우리가 졌어. 아즈사."
33240-20 = "#st;[0,0];instant;1;"
33240-22 = "3;아즈사 부상;04\n#3;closeup\n#3;em;[?!]\n#3;shake\n#wait;1500"
33240-23 = "3;사오리 부상;S2_08;아, 안돼. 공주님……. 말을 하면……. 그녀가…….\n#3;stiff\n#3;em;[반응]\n#3;closeup"
33240-24 = "3;아츠코 부상;99;괜찮아. 이제 다 끝났어."
33240-25 = "3;아츠코 부상;01;어차피 그녀는 나를 살려둘 생각이 없었을 거야. ……이젠 아무래도 상관없어."
33240-26 = "5;사오리 부상;S2_05;……?\n#5;a\n#3;m2"
33240-27 = "3;아츠코 부상;01;그러니까, 이제 그만하자. 사오리.\n#3;em;…"
33240-28 = "5;사오리 부상;S2_05;……그만하자고?"
33240-29 = "5;사오리 부상;S2_07;아리우스로 돌아가자고? 가봤자 살해당할 거야…… 공주님…….\n#5;em;[반응]"
33240-30 = "3;아츠코 부상;01;응. 도망치자. 같이."
33240-31 = "5;사오리 부상;S2_02;도망치자고……?"
33240-32 = "3;아츠코 부상;01;응."
33240-33 = "3;아츠코 부상;99;아즈사가 알려줬어."
33240-34 = "3;아츠코 부상;01;이건…… 우리의 증오가 아냐.\n#3;m3\n#5;dr"
33240-35 = "#5;hide\n3;아츠코 부상;01;애초에 우리의 것이 아니었어. 이 증오는 배워진 것이야. 학습된 것이야. 우리의 것이라고 믿고 있었을 뿐."
33240-36 = "3;아츠코 부상;99;아즈사는 그걸 알고 있었던 거겠지.\n#3;em;…"
33240-37 = "3;아즈사 부상;01;……."
33240-38 = "3;아츠코 부상;01;아즈사가 진짜로 배우고 싶었던 지식들. 보충하고 싶었던 지식들."
33240-39 = "3;아츠코 부상;01;그랬구나. 아즈사는 좋은 어른을 만났구나.\n#3;greeting"
33240-40 = "3;아츠코 부상;01;아즈사는 자기가 있어야 할 <학교>를 찾은 것 같네.\n#3;em;[반응]"
33240-41 = "3;아츠코 부상;99;그러니까, 사오리."
33240-42 = "#all;hide\n#na;아츠코 부상;……도망치자."
33240-43 = "#na;아츠코 부상;아리우스에게서도."
33240-44 = "#na;아츠코 부상;우리 것이 아닌 증오에게서도."
33240-45 = "3;사오리 부상;S2_07;우리는 도망칠 수…….\n#3;stiff\n#3;em;…"
33240-47 = "3;마에스트로;01\n#3;stiff\n#3;a\n#wait;1500"
33240-48 = "3;마에스트로;01;멋지군. 저것이 바로 어른인가."
33240-49 = "3;마에스트로;01;지성과 품격, 예의와 신념…… 축적한 경험과 지혜…… 모든 것이 우러러볼 수밖에 없는…….\n#3;em;…"
33240-50 = "#all;hide\n#na;마에스트로;그렇군. 저자라면…… 혹시라도 저자라면……."
33240-51 = "3;마에스트로;01;내 <숭고>에 답해줄 수 있을지도 모른다……!!\n#3;stiff\n#3;closeup\n#fontsize;90"
33240-54 = "3;아즈사 부상;05;이, 이건…….\n#3;a\n#3;em;[!]"
33240-55 = "3;아츠코 부상;01;……이건 설마."
33240-56 = "3;아츠코 부상;01;그 <교의>의 완성품이…… 벌써……?\n#3;em;[반응]\n#3;stiff"
33240-57 = "[s] (이것은…….)"
33240-58 = "3;아츠코 부상;01;……지금까지와는 차원이 달라……."
33240-59 = "5;사오리 부상;S2_07;무슨 일이…….\n#3;m1\n#5;a"
33240-60 = "#st;[0,0];instant;1;"
33240-62 = "3;아츠코 부상;01\n5;사오리 부상;S2_07\n#3;d\n#5;d\n#wait;1000"
33240-64 = "3;아즈사 부상;04;서, 선생님…… 이건…….\n#3;closeup\n#3;a"
33240-65 = "3;아즈사 부상;06;이건…… 지금까지와 달라……. 이건…… 도, 도망치지 않으면……. 이건…….\n#3;em;…\n#3;stiff\n#3;closeup"
33240-66 = "[s] \"알고 있어. 이건 말하자면 치사한 반칙 같은 거지.\""
33240-67 = "3;아즈사 부상;01;선생님……?\n#3;closeup"
33240-68 = "[ns1] \"꺼내지 않으려고 했는데.\"\n[ns2] 어른의 카드를 꺼낸다."
33240-69 = "#st;[0,0];instant;1;"
33240-70 = "#st;[0,0];instant;1;"
33240-73 = "3;마에스트로;01;……오오. 오오오. 저것은, 저것은!\n#3;a\n#3;stiff"
33240-74 = "3;마에스트로;01;그런가. 저것이 예의, 그 <카드>인가!\n#3;em;[반응]"
33240-75 = "3;마에스트로;01;삶을, 시간을 대가로 지불하고 얻게 되는 힘……. 근원도, 한계도, 우리조차도 알 수 없는 불가해한 힘……!!"
33240-76 = "3;마에스트로;01;그 골콩트라면 저것을 어떻게 불렀을지 궁금하군……. 그래, 마치, 메타적인…… 그런 말을 했을 것이다.\n#3;stiff"
33240-77 = "3;마에스트로;01;좋다, 보여다오! 선생. 당신이 지금껏 지불한 그 대가를."
33240-78 = "3;마에스트로;01;그 힘을 보여다오-!\n#3;em;[!]\n#fontsize;90"
33240-79 = "#st;[0,0];instant;1;"
33240-81 = "3;마에스트로;01\n#3;d\n#wait;1000"
33240-82 = "3;마에스트로;01\n#3;a\n#wait;1000\n#3;closeup"
33240-83 = "3;마에스트로;01;나의 작품에 전력으로 응해다오……!!\n#3;closeup\n#3;shake\n#fontsize;90"
