[translation]
34020-1 = "#title;제2화;불편한 다과회"
34020-2 = "3;나기사;01\n#3;a\n#wait;1500\n#3;h"
34020-3 = "3;나기사;02;와주셔서 감사합니다. 선생님. 오랜만의 트리니티 방문이네요. \n#3;em;[반짝]"
34020-4 = "[s] \"안녕. 나기사. 그리고 모두들.\""
34020-5 = "3;나기사;01\n1;사쿠라코;02;또 뵙네요. [USERNAME] 선생님. 저번엔 신세를 많이 졌습니다.\n#1;greeting\n#1;a"
34020-6 = "3;나기사;01\n1;사쿠라코;01\n5;미네;01;……. 처음 뵙겠습니다. 구호기사단의 단장을 맡고 있는 미네입니다. \n#5;em;…\n#5;a"
34020-7 = "[s1] \"응. 잘 부탁해.\" \n[s2] \"어쩐지 신기한 조합이네.\""
34020-8 = "5;미네;01\n3;나기사;01\n1;사쿠라코;99;후후……. 신기하다고 할까, 나기사 씨를 곤란하게 만들 조합이라고 할까."
34020-9 = "5;미네;01\n3;나기사;01\n1;사쿠라코;99;후후……. 신기하다고 할까, 나기사 씨를 곤란하게 만들 조합이라고 할까."
34020-10 = "3;나기사;01\n1;사쿠라코;01\n5;미네;99;저는 호스트를 곤란하게 만들 생각은 없었습니다만."
34020-11 = "3;나기사;01\n1;사쿠라코;01\n5;미네;02;신념과 긍지를 품고 있는 기사단의 일원으로서, 그릇된 모습이 보인다면 바르게 되돌릴 뿐입니다."
34020-13 = "3;미네;01;설령 그것이 정의실현부나 티파티라고 할지라도요.\n#3;closeup\n#3;em;[반응]"
34020-14 = "1;사쿠라코;04\n5;미네;01\n3;나기사;99;…….\n#3;em;…"
34020-15 = "5;미네;01\n3;나기사;99\n1;사쿠라코;99;……그런 말이 이미 충분히 나기사 씨를 곤란하게 만들고 있는 것 같지만요.\n#1;em;[땀]"
34020-16 = "1;사쿠라코;01\n5;미네;01\n3;나기사;02;자, 바쁘신 선생님 앞에서 잡담은 이 정도로 하고. \n#3;em;[반응]"
34020-17 = "1;사쿠라코;01\n5;미네;01\n3;나기사;01;선생님을 모신 이유는 저번의 에덴조약 사태 이후의 상황 공유와 사건의 뒤처리에 대한 여러 가지를 논의하려고 했던 것……이었습니다만."
34020-18 = "5;미네;01\n3;나기사;01\n1;사쿠라코;01;……."
34020-19 = "3;나기사;01\n1;사쿠라코;01\n5;미네;99;……."
34020-20 = "1;사쿠라코;01\n5;미네;99\n3;나기사;04;어째선지, 시스터후드와 구호기사단의 리더가 이 자리에 참석하겠다고 해서…… 이렇게 되어버렸네요.\n#3;em;[땀]"
34020-21 = "5;미네;99\n3;나기사;04\n1;사쿠라코;01;……시스터후드도 예전과는 많이 달라져서요. 이제 이런 자리에 빠질 수는 없겠죠."
34020-22 = "3;나기사;04\n1;사쿠라코;01\n5;미네;02;저 역시 트리니티에서 가장 오랜 역사를 지닌 동아리인 <기사단>의 수장으로서 의무를 수행하려는 것뿐입니다."
34020-23 = "1;사쿠라코;01\n5;미네;01\n3;나기사;04;…….\n#3;em;…"
34020-24 = "[s] \"어…… 요컨대, 두 사람은 티파티를 견제하려는 목적으로……?\""
34020-25 = "5;미네;01\n3;나기사;04\n1;사쿠라코;99;아뇨, 관심이 많은 것뿐이죠."
34020-26 = "3;나기사;04\n1;사쿠라코;99\n5;미네;01;저는 그런 정치적인 일들은 잘 모릅니다."
34020-27 = "1;사쿠라코;01;에덴조약 사태는 어찌저찌 마무리되었지만, 그 사건의 배경에 대한 후속 조치와 상황 분석은 여전히 진행 중이죠.\n#1;m3\n#3;dr\n#5;dr\n#1;em;[반응]"
34020-28 = "1;사쿠라코;99;저희 또한 이 사건과 무관하지 않기에, 연구 분석의 일정 부분은 시스터후드가 담당하고 있습니다."
34020-29 = "1;사쿠라코;02;이번 자리는 그런 정보의 공유 및 후속 조치에 대해 논의를 하기 위한 것이라고 봐주시면 됩니다.\n#1;greeting"
34020-31 = "3;미네;01;네. 그런 것으로.\n#3;em;[반응]"
34020-32 = "[s] \"어…… 그, 그렇구나.\""
34020-33 = "3;나기사;99;……."
34020-34 = "3;미네;02;어째서 티파티가 아니라 우리들이? 라는 의문이 드신다면, 그 부분은 제가 답변드리겠습니다."
34020-35 = "3;미네;99;지금 티파티에는 도움이 필요합니다.\n#3;em;…"
34020-36 = "3;나기사;10;……."
34020-37 = "3;미네;01;에덴조약 사태 전후로, 티파티의 일원이 호스트를 공격하는 사건이 벌어졌고, 그 결과를 초래한 당사자가 감옥에 갇히는 초유의 사태가 발생했습니다."
34020-38 = "3;미네;05;설마 세이아 님을 공격한 배후가 미카 님이었다니……."
34020-39 = "3;나기사;10;……."
34020-40 = "3;사쿠라코;99;……."
34020-41 = "3;미네;02;그 뒤 세이아 님을 지켜낸 것은, 여러분도 잘 아시듯이 저였습니다. 그래서 저도 나름대로 이 사건을 조사해 왔습니다."
34020-42 = "3;미네;01;미카 님은 결과적으로 아리우스에게 이용당한 것이라 볼 수 있겠지만…… 그렇다고 그녀의 죄가 사라지는 것은 아닙니다.\n#3;em;…"
34020-43 = "1;나기사;01\n3;미네;05;게다가 지금 호스트인 나기사 님은 <샬레>의 초법적 권한이라는 편법을 이용해 다른 학생들을 퇴학시키려고 했고요.\n#1;a\n#3;m5"
34020-44 = "1;나기사;10;……."
34020-45 = "3;미네;99;피해를 입은 소녀들에게는 사과를 했고, 모든 일은 다 잘 마무리되었다고 들었으나……."
34020-46 = "3;미네;05;그렇다고 나기사 님의 행동이 없던 게 되지는 않습니다.\n#3;em;[반응]"
34020-47 = "1;나기사;99;……."
34020-48 = "3;미네;01;세이아 님은 다행히 학원으로 복귀할 수 있었지만…… 건강이 예전보다 더 악화되어서 자신의 방 밖으로 외출조차 못 하는 몸이 되었고요."
34020-49 = "3;미네;02;따라서 지금의 <티파티>에는 좀 더 많은 관심이 필요하다는 것이 제 판단입니다.\n#3;m4\n#3;em;[반응]"
34020-51 = "3;사쿠라코;99;과연."
34020-52 = "3;나기사;10;……. 친절한 설명 감사드려요. 미네 단장.\n#3;em;…"
34020-53 = "#st;[0,0];instant;1;"
34020-55 = "3;미네;99\n#3;greeting\n#wait;1500"
34020-56 = "3;미네;01\n#3;h\n#wait;2500"
34020-57 = "[ns] (부, 불편한 분위기다…….)"
34020-58 = "3;미네;01\n1;사쿠라코;07;미네 단장은 요한 분파의 수장이기도 하면서 트리니티에서 가장 오래된 역사를 자랑하는 동아리의 리더.\n#1;ar\n#3;m5\n#1;em;[반응]"
34020-59 = "1;사쿠라코;01;원래라면 티파티에 참석할 수 있는 권리가 있었지만…… 구호의 가치를 수행하기 위해 그녀 스스로 그 권리를 사양했었죠."
34020-60 = "#3;hide\n5;미네;01;과거의 이야기입니다."
34020-61 = "1;사쿠라코;01\n5;미네;01\n3;나기사;07;……이 사태의 핵심은 결국 아리우스 분교로 수렴됩니다.\n#3;a"
34020-63 = "#na;나기사;에덴조약 회담장의 습격, 그 사건의 배후로 지목된 것이 바로 아리우스 분교."
34020-65 = "1;마코토;00\n5;미카;00\n#1;a\n#5;a\n#1;h\n#5;h"
34020-66 = "#na;나기사;마코토 의장과 미카는 둘 다 아리우스의 손에 놀아난 것일 뿐이고……."
34020-67 = "1;마코토;05\n5;미카;00\n#1;m3\n#5;dr\n#1;em;[반응]\n#1;h"
34020-68 = "#na;나기사;마코토 의장은 오히려 자신이 피해자이며, 트리니티의 분파인 아리우스가 자신들을 공격한 것이니 우리 쪽에 모든 책임이 있다고 주장하고 있지만요."
34020-69 = "#na;나기사;미용실 비용도 우리에게 청구하겠다, 라고 알 수 없는 이야기를…… 뭐, 이건 넘어가고."
34020-71 = "3;사쿠라코;99;아리우스가 이 모든 것을 뒤에서 조종했다면……. 그들에 관한 몇 가지 의문이 남게 됩니다.\n#3;a"
34020-72 = "3;사쿠라코;07;첫 번째. 아리우스 분교는 어째서 에덴조약을 방해했는가?"
34020-73 = "3;미네;05;아리우스 분교는 오랫동안 우리 트리니티와 게헨나를 증오해 왔다고 들었습니다. 한번에 두 학원의 요인들을 무력화시킬 수 있는 좋은 기회였겠죠.\n#3;em;…"
34020-74 = "3;나기사;07;그리고 에덴조약이라는 <계약>을 이용해서 불가해한 병력을 손에 넣었고요……. 세이아 씨는 그렇게 설명했어요."
34020-75 = "3;미네;01;네. <유스티나 성도회>의 모습을 한 유령들. 그것들이 그대로 트리니티나 게헨나로 진격하는 데 성공했다면 두 학원은 무력하게 무너졌을 겁니다.\n#3;greeting"
34020-76 = "1;사쿠라코;99;…….\n#1;a\n#3;m5"
34020-77 = "3;미네;02;대체 그건 뭐였던 겁니까?\n#3;em;[반응]"
34020-78 = "1;나기사;99;거기에 대해서는 몇 가지 가설이 있긴 한데…… 그걸 뒷받침하는 증거를 찾질 못한 상태예요…….\n#1;em;…"
34020-79 = "3;미네;05;성도회는 본래 시스터후드의 전신이었던 집단. 사쿠라코 님, 이 부분에 대해서 숨기고 있는 것은 없습니까?"
34020-80 = "1;사쿠라코;01;……. 네. 아쉽게도요."
34020-81 = "3;미네;99;시스터후드는 비밀이 많은 집단이죠. 정보의 통제나 은닉, 왜곡에도 능하고요."
34020-82 = "#st;[0,0];instant;1;"
34020-84 = "3;미네;01\n#3;m4\n#wait;1500"
34020-86 = "3;미네;02;학원 안에 시스터후드를 믿을 수 없다고 생각하는 소녀들이 많이 있다는 건 알고 계신가요?\n#3;closeup"
34020-87 = "#st;[0,0];instant;1;"
34020-89 = "4;미네;02\n1;사쿠라코;99\n#wait;500"
34020-90 = "4;미네;02\n1;사쿠라코;01\n#1;m2\n#wait;1500"
34020-92 = "3;사쿠라코;02;……. 가령, 미네 단장처럼?\n#3;em;[반응]\n#3;closeup"
34020-93 = "3;나기사;04;…….\n#3;closeup"
34020-94 = "3;미네;01;…….\n#3;closeup"
34020-95 = "[s] (부, 불편해…….)"
34020-96 = "#st;[0,0];instant;1;"
34020-98 = "3;미네;01\n#3;closeup\n#3;d\n#wait;1500"
34020-99 = "3;사쿠라코;99;……제가 시스터후드의 모든 비밀을 알고 있을 거라 생각하신다면 그건 오산이에요. \n#3;a"
34020-100 = "3;사쿠라코;01;시스터후드에서는 저조차도 알지 못하는 비밀이 많이 있답니다. 내부 사정이라 자세하게 설명은 못 하지만."
34020-101 = "5;미네;99;……그렇군요. 실례했습니다.\n#5;a\n#3;m1"
34020-102 = "#3;hide\n1;나기사;04;하아…….\n#1;em;[속상함]"
34020-103 = "5;미네;02;트리니티의 방호 시스템을 무력화시켰던 그 순항 미사일……. 그쪽의 분석은 아직입니까?"
34020-104 = "1;나기사;01;네. 분석을 진행했지만 현재로선 출처도 구조도 불명…… 결론은 키보토스에 존재하는 기술이 아닌 것 같다는 추측뿐……."
34020-105 = "5;미네;01;……결국, 아리우스 분교는 우리가 알지 못하는 힘을 최소 두 개는 확보하고 있다는 거군요."
34020-106 = "1;사쿠라코;07;네. 그리고 그 부분은 두 번째 의문으로 이어지게 됩니다.\n#1;em;[반응]"
34020-107 = "1;사쿠라코;01;두 번째. 아리우스 분교는 무엇을 계획하고 있는가?"
34020-108 = "5;미네;05;…….\n#5;em;…"
34020-109 = "5;나기사;99;……여기에 대해서는 저희는 아무것도 알 수 없어요."
34020-110 = "5;나기사;07;무엇보다 우리는 아리우스 자치구가 어디에 있는지도 알지 못합니다.\n#5;em;[반응]"
34020-111 = "1;사쿠라코;01;……네. 그건 오래전부터 수수께끼였죠. 다만 저번 사건을 계기로 몇 가지 실마리를 얻긴 했어요."
34020-112 = "1;사쿠라코;07;그들은 그때 통공의 고성당 지하에 있는 카타콤을 통해 잠입했습니다."
34020-113 = "1;사쿠라코;99;그동안의 아리우스 학생들의 잠입 루트도 전부 카타콤과 연관되어 있었죠. 순항 미사일의 발사 위치도 트리니티 내에 있는 유적지구였고요.\n#1;em;…"
34020-114 = "5;미네;02;트리니티 자치구에 존재하는 지하 유적은 엄청나게 많지 않습니까? 그걸 모두 찾아내서 통제하는 건 불가능할 텐데.\n#5;em;[?]"
34020-115 = "1;나기사;05;게다가 카타콤은 아직까지도 그 규모가 밝혀지지 않은 미궁…… 거기서 자력으로 아리우스 자치구를 찾는 것도 매우 어려운 일일 거구요."
34020-116 = "5;미네;01;흐음……."
34020-117 = "1;나기사;07;세이아 씨의 말로는 그 자치구는 우리가 이해할 수 없는 어떤 힘으로 보호되고 있는 것 같다고 하더군요.\n#1;em;[반응]"
34020-118 = "1;나기사;99;그렇지 않고서야 이렇게까지 모습을 숨길 수 있다는 게 설명되지 않는다고……."
34020-119 = "5;미네;99;또 이해할 수 없는 힘인가요……."
34020-120 = "1;나기사;01;과거에 아리우스 소속이었던 아즈사 씨의 말로는, 매 임무 때마다 카타콤의 출구가 기록된 지도를 받았었다고 하더군요."
34020-121 = "#st;[0,0];instant;1;"
34020-123 = "5;미네;05\n#5;stiff\n#5;em;[!]\n#5;h\n#wait;1500"
34020-124 = "1;나기사;02;문제는 그 지도의 동선은 매번 달라지고 게다가 음어화까지 되어 있어서…… 배신자인 자신은 이제 아리우스 자치구로 돌아가는 길을 모른다고……."
34020-125 = "5;미네;05;……그 소녀를 취조한 겁니까?"
34020-126 = "1;나기사;04;네? 네?!\n#1;shake\n#1;em;[?!]"
34020-127 = "5;미네;05;시라스 아즈사, 그 아이에게 아리우스의 정보를 말하게 한 건가요?\n#5;m4\n#5;em;[반응]"
34020-128 = "5;미네;09;그 아이는 이미 충분한 대가를 치렀습니다! 자신이 있던 자치구에서 배신자로 낙인찍히면서까지 우리를 위해 노력해주었어요!\n#5;m3\n#1;dl"
34020-130 = "3;미네;09;간신히 마음의 평화를 찾았을 아이에게 우리 입장만을 위해서 또 다시 아리우스의 정보를 캐묻다니……. 이런 잔인한……!\n#3;closeup\n#3;em;[빠직]"
34020-131 = "3;나기사;04;아, 아뇨! 취조나 그런 게 아니라, 어디까지나 본인이 스스로 말해준 것으로…….\n#3;closeup\n#3;stiff\n#3;em;[속상함]"
34020-133 = "1;나기사;04\n5;미네;09;그 소녀가 과연 그렇게 느꼈겠습니까! 티파티의 강압적인 권위를 이용해서 연약한 소녀를 강제로……!!\n#5;em;[반응]"
34020-134 = "1;나기사;04;네?! 네?!\n#1;shake\n#1;em;[?!]"
34020-135 = "5;미네;09\n1;나기사;04\n3;사쿠라코;07;진정하세요, 미네 단장. 그런 게 아니니까요.\n#3;ar\n#3;em;[반응]"
34020-136 = "1;나기사;04\n3;사쿠라코;07\n5;미네;01;……아닌가요?"
34020-137 = "1;나기사;04\n5;미네;01\n3;사쿠라코;99;네. 나기사 씨가 냉정하고 잔인한 사람이긴 하지만 이번에는 아니에요. 아즈사 씨가 무례한 대우를 받진 않았어요. \n#3;greeting"
34020-138 = "#st;[0,0];instant;1;"
34020-140 = "5;미네;01\n3;사쿠라코;99\n1;나기사;04\n#1;em;[땀]\n#wait;1500\n#1;h\n#3;h\n#5;h"
34020-141 = "1;나기사;04\n5;미네;01\n3;사쿠라코;01;무엇보다, <보충수업부>는 샬레의 선생님이 담임으로 있는 조직. 그런 일이 있었다면 선생님이 가만히 있지 않았겠죠."
34020-142 = "1;나기사;04\n3;사쿠라코;01\n5;미네;01;……그렇군요."
34020-143 = "1;나기사;04\n3;사쿠라코;01\n5;미네;99;실례했습니다. 나기사 님.\n#5;greeting"
34020-144 = "3;사쿠라코;01\n5;미네;01\n1;나기사;04;…….\n#1;stiff"
34020-145 = "[s3] (나기사의 찻잔이 떨리고 있는데……)\n[s4] \"괘, 괜찮아? 나기사?\""
34020-146 = "3;사쿠라코;01\n5;미네;01\n1;나기사;99;……네. 저도 알고 있어요. \n#1;em;…"
34020-147 = "3;사쿠라코;01\n5;미네;01\n1;나기사;99;……네. 저도 알고 있어요. \n#1;em;…"
34020-148 = "3;사쿠라코;01\n5;미네;01\n1;나기사;01;히후미 씨…… 하나코 씨, 코하루 씨, 아즈사 씨…….\n#1;m3\n#3;dr\n#5;dr"
34020-149 = "#3;hide\n#5;hide\n1;나기사;04;보충수업부의 모두는 본래 자신들이 책임져야 할 것보다 훨씬 더 많은 것들을 짊어졌어요……."
34020-150 = "1;나기사;10;그들이 짊어진 짐 중엔 제가 원인이 되었던 것들도 있었죠……. \n#1;em;…"
34020-151 = "1;나기사;10;저도 염치라는 것이 있어요……. 저도 그 정도는 알고 있어요."
34020-152 = "1;나기사;99;그래서 에덴조약 사태 이후의 이런 뒤처리에는 그 아이들이 관여되지 않도록 어떻게든 노력을 했어요……."
34020-153 = "1;나기사;04;이런 지저분한 진흙탕 싸움은 우리들의 몫이어야만 하니까……. 그 아이들이 또다시 이런 일을 겪게 해서는 안 된다고 생각을……."
34020-154 = "[s] \"나기사…….\""
34020-155 = "#1;hide\n3;미네;99;……그렇군요. 나기사 님, 말씀에 동의합니다. 실례를 범한 것을 용서해 주시길.\n#3;em;…"
34020-156 = "3;사쿠라코;01;……저도 동감이에요."
34020-157 = "3;사쿠라코;01;저도 마음 같아서는 하나코 씨에게 정말 많은 책무를 넘기고 싶지만……"
34020-158 = "3;사쿠라코;99;저와 했던 계약도 그걸로 끝나버렸고……. 다시 그녀에게 무거운 짐을 지워서는 안 된다고 생각했어요."
34020-159 = "3;사쿠라코;07;그래서 지금은 우리들만의 힘으로 남은 문제들을 해결하려고 하고 있습니다. 그게 우리가 할 수 있는 최소한의 예의겠죠.\n#3;em;[반응]"
34020-160 = "3;사쿠라코;01;하지만 선생님은 저희와 끝까지 함께 해 주실 거라 믿고 있습니다.\n#3;greeting"
34020-161 = "[s] \"응, 물론이지.\""
34020-162 = "3;나기사;01;……네. 감사합니다. 선생님."
34020-164 = "3;미네;01;카타콤은 규모도 파악되지 않은 거대한 미로인데, 거기서도 매번 바뀌는 입구를 찾아야 한다라……. 확실히 어려운 문제겠군요.\n#3;a"
34020-165 = "5;사쿠라코;01;어쩌면…… 그 통로를 알고 있는 사람들에게 물어보면 될지도요.\n#5;a\n#3;m1"
34020-166 = "3;미네;02;그 통로를 알고 있는 사람……?\n#3;em;[?]"
34020-168 = "3;사오리;00\n#3;a\n#wait;1500"
34020-169 = "#na;사쿠라코;습격을 주도했던 <아리우스 스쿼드>의 리더, 조마에 사오리. 그녀는 확실하게 그 길을 알고 있을 거예요."
34020-170 = "#na;미네;……과연. 그 모든 습격을 지휘한 게 그 사오리였으니까……."
34020-171 = "#na;나기사;하지만 그 <스쿼드>의 행방은 아직도 오리무중이에요……. 이미 자치구로 도망쳤을 가능성이 높아요."
34020-172 = "#na;사쿠라코;그렇다면 한 명 더 있지 않나요?"
34020-173 = "#na;미네;……."
34020-174 = "#na;나기사;네……? 또 누가……."
34020-175 = "#st;[0,0];instant;1;"
34020-177 = "3;사오리;00\n#3;d\n#wait;1500"
34020-178 = "3;미카;00\n#3;a\n#wait;1500"
34020-179 = "#na;사쿠라코;미소노 미카."
34020-180 = "#na;나기사;……네?!\n#fontsize;100"
34020-182 = "3;나기사;04;그, 그런……. 미카 씨는 본인 입으로 아리우스 자치구의 위치만큼은 모른다고…….\n#3;a\n#3;stiff"
34020-183 = "3;나기사;04\n1;사쿠라코;07;……그녀는 오랫동안 아리우스와 내통해 왔어요. 그런 그녀가 아리우스의 위치를 모른다는 건 좀 이상한 일 아닐까요?\n#1;a"
34020-184 = "1;사쿠라코;07\n3;나기사;04;……."
34020-185 = "1;사쿠라코;07\n3;나기사;04\n5;미네;02;……확실히 미카 님은 아리우스 학생들과 접선하여 보급품들을 전달한 기록이 남아 있습니다.\n#5;a\n#5;em;…"
34020-186 = "1;사쿠라코;07\n3;나기사;04\n5;미네;01;쿠데타를 꾸미기 위해 아리우스의 지원을 얻기 위해서……, 지금은 그렇게 생각하는 게 자연스럽습니다만."
34020-187 = "1;사쿠라코;07\n5;미네;01\n3;나기사;04;미카 씨는…… 하지만……."
34020-188 = "1;사쿠라코;01\n3;나기사;04\n5;미네;99;그동안의 미카 님의 평판과 행실은 그다지 모범적이라고 말할 수는 없습니다."
34020-189 = "1;사쿠라코;01\n3;나기사;04\n5;미네;01;잘 알고 계시겠지만 미카 님은 티파티라는 이유만으로 많은 자신의 실수나 문제를 무마해 왔죠."
34020-190 = "1;사쿠라코;01\n3;나기사;04\n5;미네;05;지금 학원에서 벌어지고 있는 미카 님에 대한 규탄과 소요, 여론 또한 그녀가 그동안 보여준 행동들과 관계가 없진 않겠죠."
34020-191 = "[s] (……소요?)"
34020-192 = "1;사쿠라코;01\n5;미네;05\n3;나기사;04;미카 씨가…… 거짓말을 했다고는…… 아리우스 자치구의 위치를 숨겨서…… 무엇을……."
34020-193 = "5;미네;05\n3;나기사;04\n1;사쿠라코;01;……."
34020-194 = "3;나기사;04\n1;사쿠라코;01\n5;미네;01;나기사 님이 미카 님을 어떻게 생각하는지는 잘 알고 있습니다."
34020-195 = "3;나기사;04\n1;사쿠라코;01\n5;미네;99;무례한 질문이겠지만, 미카 님을 가장 잘 알고 있는 분이 있다면 그건 바로 오랫동안 그녀를 곁에서 지켜보아 온 나기사 님이겠죠."
34020-196 = "1;사쿠라코;01\n5;미네;99\n3;나기사;99;……."
34020-197 = "#st;[0,0];instant;1;"
34020-199 = "5;미네;01\n#5;m3\n#1;dl\n#3;dl\n#wait;1500"
34020-201 = "3;미네;02;나기사 님이 보시기에, 미카 님은 아직도 우리에게 숨기는 것이 있다고 생각하십니까?\n#3;em;[반응]\n#3;closeup"
34020-203 = "3;미카 비무장;12\n#3;a\n#wait;2500"
34020-204 = "3;나기사;04\n#3;h"
34020-205 = "3;나기사;04;그건……."
34020-206 = "[s] (나기사…….)"
34020-207 = "#st;[0,0];instant;1;"
34020-209 = "3;나기사;99\n#wait;2500"
34020-210 = "3;나기사;01;……. 아뇨. 저는 미카 씨를 믿어요."
34020-211 = "3;사쿠라코;07;……."
34020-212 = "3;미네;01;……."
34020-213 = "3;나기사;04;확실히…… 그동안의 미카 씨는 착한 학생이라고 할 수는 없겠지만……. \n#3;em;…"
34020-214 = "3;나기사;07;그래도 지금 저는 미카 씨를 믿어요. 그게 제가 이번에 깨달은 교훈이니까요!"
34020-215 = "3;나기사;05;제가 믿으니까, 다른 사람들도 그렇게 믿게 할 거예요! 네! 내일 청문회에 저도 참석해서 미카 씨를 변호하겠어요! \n#3;em;[반응]"
34020-216 = "3;나기사;05;당신들에게! 아니, 필요하다면 이 학원 전체에 말이에요!"
34020-217 = "3;나기사;07;설령 그 때문에 저에게 문제가 생겨도…….\n#3;stiff"
34020-218 = "3;나기사;07\n1;사쿠라코;01;……. 아뇨. 저는 그냥 가설을 이야기해 본 것뿐, 다른 의도는 없었어요. 나기사 씨.\n#1;a"
34020-219 = "3;나기사;07\n1;사쿠라코;01\n5;미네;99;……실례했습니다. 무례했다면 사과드립니다.\n#5;greeting\n#5;a"
34020-220 = "[s] \"어…… 저기…….\""
34020-221 = "1;사쿠라코;01\n5;미네;01\n3;나기사;04;……하아."
34020-222 = "1;사쿠라코;01\n5;미네;01\n3;나기사;99;네, 그러네요. 슬슬 시간도 이렇게 되었고…… 이 자리도 마무리를 지어야겠어요."
34020-223 = "1;사쿠라코;01\n5;미네;01\n3;나기사;02;오늘 시간을 내주셔서 감사했어요. 두 분.\n#3;em;[반짝]"
34020-224 = "1;사쿠라코;01\n3;나기사;01\n5;미네;03;……네. 오늘 만나 뵙게 되어 감사했습니다."
34020-225 = "1;사쿠라코;01\n3;나기사;01\n5;미네;99;그리고 저 또한 지금의 이 사태…… 미카 님에게 쏟아지는 비난과 분노에 대해서는 매우 우려스럽게 생각하고 있습니다."
34020-226 = "1;사쿠라코;01\n3;나기사;01\n5;미네;01;제 나름의 방법을 찾아보도록 하겠습니다. 그럼.\n#5;greeting"
34020-227 = "3;나기사;01\n5;미네;01\n1;사쿠라코;01;네. 그럼 저도 대성당으로 돌아갈게요. \n#1;greeting"
34020-228 = "1;사쿠라코;01\n5;미네;01\n3;나기사;02;네. 조심히 가세요. 배웅은 하지 않을게요."
34020-229 = "#st;[0,0];instant;1;"
34020-233 = "3;나기사;99;하아…….\n#3;a"
34020-234 = "3;나기사;04;하아아…… 위가…… 아프네요.\n#3;stiff\n#3;em;[속상함]"
34020-235 = "[s] \"수고했어. 나기사.\""
34020-236 = "3;나기사;04;……감사합니다. 선생님. 어쩐지 보여주기 싫은 모습만 계속 보여주게 되는 것 같지만……."
34020-237 = "[s5] \"그런데…… 미카에게 무슨 일이 있는 거야?\"\n[s6] \"아까부터 뭔가…….\""
34020-238 = "3;나기사;99;……아아. 네. 선생님은 아직 모르시겠네요."
34020-239 = "3;나기사;99;……아아. 네. 선생님은 아직 모르시겠네요."
34020-240 = "3;나기사;07;내일 오전에 미카 씨의 청문회가 열릴 예정이에요."
34020-241 = "[s] \"청문회?!\""
34020-242 = "3;나기사;10;말이 청문회이지, 사실 그동안의 행동에 대한 징계성에 가까운…… 사문위원회라고 봐야 해요."
34020-243 = "3;나기사;99;거기서 지금까지의 미카 씨가 저지른 죄와 부정…… 특히 에덴조약과 관계된 것들이 집중적으로 논의될 예정이고……."
34020-244 = "#st;[0,0];instant;1;"
34020-246 = "3;나기사;99\n#3;em;…\n#wait;2500"
34020-247 = "#all;hide\n#na;나기사;……. 선생님."
34020-248 = "#st;[0,0];instant;1;"
34020-250 = "3;나기사;99\n#wait;1500"
34020-251 = "3;나기사;10;미카 씨는…… 퇴학당하게 될 거예요."
34020-253 = "#nextepisode;다음화;감옥 안의 프린세스"
