[translation]
34040-1 = "Episode 4; Between a Dream and a Mirage"
34040-3 = "[ns] \"You saw the fall of Kivotos...?\""
34040-4 = "..."
34040-5 = "Yes, I witnessed it."
34040-6 = "I don't know when it is going to happen, but I do know how. "
34040-7 = "[s] \"What did you see?\""
34040-9 = "An enormous tower emerges from a blood red sky."
34040-12 = "It erodes the entire world, enveloping everything with its sinister power. It's accompanied by an awful screech."
34040-13 = "Then, the fragments of our destroyed world rage like a storm, then crumble into pieces. I remember a black light shining down..."
34040-15 = "And at last, Kivotos falls."
34040-16 = "Not a trace is left behind."
34040-18 = "[ns] \"...\""
34040-19 = "My heart hopes it was a nightmare. But it could've been anything: a snippet of our past or a vision of the future.  "
34040-20 = "All I'm left with is an endless series of questions. I'm determined to find the answers to them."
34040-21 = "..."
34040-22 = "To learn more, I've been venturing into the realm of lucid dreams."
34040-23 = "They exist on the edge of reality and dreams, making it difficult to discern the future from the past."
34040-24 = "Even when I'm awake I feel like I'm in an endless dream."
34040-25 = "[s] \"That sounds dangerous...\""
34040-26 = "I suppose it may be."
34040-27 = "I've always been afraid of the future. But I couldn't run away this time."
34040-28 = "I won't rest until I find out our fate. This is my responsibility."
34040-29 = "The tower... The destruction... It was caused by something outside of Kivotos."
34040-30 = "This is just my guess...but the cause may be Gematria..."
34040-31 = "I believe you also know of that mysterious organization."
34040-32 = "[s] \"You think Gematria is involved?!\""
34040-40 = "There has to be some way to stop the apocalypse."
34040-41 = "[s] \"Seia.\""
34040-42 = "Yes? "
34040-43 = "[s1] \"If it's related to Gematria, you have to stop this now.\"\n[s2] \"This is too dangerous for you alone.\""
34040-44 = "..."
34040-45 = "..."
34040-46 = "Yes, I know. Chasing after such mysterious beings, the danger is very real."
34040-47 = "[s3] \"On top of that, you can't keep pushing yourself like this.\"\n[s4] \"Just don't do it alone. We can work together.\""
34040-50 = "..."
34040-51 = "[s] \"Someone needs you here in reality a lot more than your dreams do.\""
34040-55 = "...Mika."
34040-56 = "You're right, Sensei."
34040-57 = "I was lost in my dreams and lost focus of what's important."
34040-61 = "I can't help Mika if something happens to me."
34040-62 = "I've been foolish."
34040-63 = "Mika's situation is beyond dire."
34040-64 = "She grew up like a princess in a fairy tale, beloved by all. So it's no surprise that she grew up expecting the world to cater to her every whim."
34040-65 = "For her to experience something like this... Being the target of everyone's hatred for the first time in her life..."
34040-66 = "I don't know if she can handle it."
34040-67 = "Right. Helping Mika is the top priority right now.  "
34040-68 = "How could I have been so blind?"
34040-69 = "It feels like I'm finally shaking off my dreams. Thank you, Sensei. I must help my friend."
34040-70 = "[s] \"Mika will be thrilled. She really wants to apologize.\""
34040-71 = "Apologize? When I've already forgiven her?"
34040-72 = "Ah. That might've been in a dream."
34040-73 = "I see... Mika thinks I still haven't forgiven her."
34040-74 = "She must see me as the biggest victim of her actions."
34040-77 = "Oh, Mika. What a dummy."
34040-78 = "She's always been self-centered, impulsive, thoughtless, and she's even self-destructive at times."
34040-79 = "Mika would be the perfect cheeky, arrogant fairy tale princess."
34040-80 = "But that wasn't the role she got."
34040-82 = "She was the villainess who tried to bully someone she didn't like."
34040-83 = "And she eventually became entangled in a horror story of violence and murder instead."
34040-87 = "But if any salvation still exists for her..."
34040-88 = "...it's in the fact that I didn't die, and her soul remains innocent of murder."
34040-89 = "That tough smile she puts on is fueled by that one thought."
34040-90 = "For her, a lot is riding on my well-being."
34040-91 = "Mika..."
34040-92 = "I wasn't kind to her, yet she frets this much."
34040-93 = "This is long overdue."
34040-94 = "We're not grade schoolers anymore. I'm ashamed we've been so scared to speak openly with each other."
34040-95 = "I'll request Mika be brought here now."
34040-96 = "I want to have a proper conversation with her...and tell her I'll be attending the hearing."
34040-97 = "The most grievous of her crimes is injuring me, so it would be very meaningful if I speak for her."
34040-102 = "Y-You called, ma'am?"
34040-103 = "I'm sorry to bother you. Could you please bring Mika to me?"
34040-104 = "M-Mika? I will request Nagisa's approval to do so."
34040-105 = "Thank you. Um... Please also inform Nagisa I would like to speak Mika privately, if possible."
34040-106 = "Yes, ma'am!"
34040-111 = "[ns] \"I'll go circle back with Nagisa in the meantime.\""
34040-112 = "Thank you. It was nice speaking with you, Sensei."
34040-113 = "I'm a bit tired, so I'll lie down while I wait for Mika."
34040-114 = "Apologies, Sensei. If you'll excuse me."
34040-115 = "[s] \"I'll see you at the hearing, Seia. Take care.\""
34040-116 = "You as well, Sensei."
34040-118 = "(I informed Nagisa that both Mika and Seia would attend tomorrow's hearing.)"
34040-119 = "(She was happy to hear the news and seemed a little less stressed. I decided to return to Schale early to prepare for tomorrow's hearing.)"
34040-124 = "Let's move on to the next agenda."
34040-125 = "But of course!"
34040-126 = "I don't disagree, but there's something I want to confirm first."
34040-130 = "(...)"
34040-131 = "(Oh... I fell asleep waiting for Mika.)"
34040-132 = "(I think the lucid dreaming has taken a toll on my health. And it's been getting more difficult to wake up.)"
34040-133 = "(More importantly...where am I?)"
34040-135 = "Please speak, Maestro."
34040-136 = "..."
34040-138 = "(This is...! C-Could it really be?)"
34040-139 = "I have an...inquiry for Beatrice."
34040-144 = "Me? By my guest."
34040-145 = "(This is...Gematria?!)"
34040-147 = "Next Episode; Inscrutable Seekers"
