[translation]
34095-2 = "อย่างนี้เองสินะ... ตอนนั้นเป็นศัตรูที่ขยาด แต่ตอนนี้เป็นพันธมิตรที่..."
34095-3 = "นี่สินะ... ความสามารถของผู้ใหญ่... ต้องบอกว่ายอดเยี่ยมหรือน่ากลัวดีนะ..."
34095-4 = "ถ้าเป็นอย่างนี้ต่อไป... คงจะ..."
34095-5 = "ไม่มีเวลาคุยเรื่องไร้สาระแล้ว รีบไปกันเถอะ"
34095-6 = "อืม... ไปกันเถอะ"
34095-7 = "ค่ะ!"
34095-8 = ""
34095-10 = ""
34095-12 = "ตอนต่อไป;ไปยังเขตปกครองตนเองอาเรียส 2"
