[translation]
34100-1 = "Episode 10; To the Arius District 2"
34100-2 = "We can enter the catacombs through here."
34100-3 = "Based on how the troops were able to find us, she already knows we're using this passage."
34100-4 = "Be on guard. She'll stop at nothing."
34100-5 = "I know it was our only option, but we're proceeding too predictably."
34100-6 = "It's no surprise she found us so quickly."
34100-7 = "A-Are we sure this is a good idea then?"
34100-8 = "It's our only idea."
34100-9 = ""
34100-11 = ""
34100-13 = ""
34100-14 = "We're charging through."
34100-15 = "There was never any other option. And I think the unknown variable Sensei brings to the formula will make them tread carefully."
34100-16 = "Heehee... I'm excited to work with Sensei.  "
34100-17 = "[s] \"I'll do my best to live up to your expectations.\""
34100-18 = ""
34100-20 = ""
34100-21 = "There will be well-trained, elite soldiers waiting for us.  "
34100-22 = "We'll lead the way. Sensei, follow closely behind."
34100-23 = "We must beat them here if we have any hope of saving Hime."
34100-24 = "Let's tear them apart!"
