[translation]
34140-1 = "Episode 14;Face-to-Face"
34140-3 = ""
34140-4 = "All clear. Move up."
34140-5 = "Oh geez, life really is suffering."
34140-6 = "Does it feel a little too quiet to anyone else? I've never seen it so abandoned."
34140-7 = "There're a number of unfamiliar things about this street.  "
34140-8 = "I've felt off since we arrived."
34140-9 = "We may have been gone for a long time, but everything feels different."
34140-10 = "..."
34140-11 = "Like, has this area always had all this crazy stuff?  "
34140-12 = "Cruise missiles installed everywhere, weapons for distribution everywhere you look.  "
34140-13 = "Come to think of it, don't you think the Mimesises are really weird? We just accepted them without question."
34140-14 = ""
34140-16 = ""
34140-19 = "How long has Arius had that cruise missile?"
34140-20 = "When did you gain control of those mysterious soldiers?"
34140-21 = "Even a bomb capable of shattering halos..."
34140-22 = "How is any of this possible?"
34140-23 = ""
34140-24 = "..."
34140-25 = "Enemy approaching. Hide."
34140-26 = ""
34140-28 = ""
34140-32 = ""
34140-35 = ""
34140-37 = "Isn't that..?"
34140-38 = "Th-The Council?! Is it the Saint Justina Council? Why're they so scary looking?"
34140-39 = "How can they be here? Sensei cancelled our contract."
34140-40 = "If you think about it..."
34140-41 = "The objective during the Eden Treaty plot was to secure the Mimesis ability."
34140-42 = "Hime did as the wooden doll in the cathedral basement told her to, just as she was instructed."
34140-43 = "With the Council troops secured, our mission was to occupy the Trinity and Gehenna districts."
34140-44 = "But we lost to Schale."
34140-45 = "Yes... We failed in both securing the Mimesis ability and occupying the academies.  "
34140-46 = "But...she'd already secured the Mimesis ability...?"
34140-47 = ""
34140-49 = ""
34140-53 = "GRAAAAAAAH."
34140-54 = "Wh-What was that...?  "
34140-55 = "It's the scream of Ambrosius, a tactical weapon utilized during the Eden Treaty. It seemed to be some form of a Mimesis."
34140-56 = "So, that means...  "
34140-57 = "Yes. Perhaps she only needed one successful Mimesis."
34140-58 = "Our real mission must have been to take Hime to the old cathedral and activate the Mimesis."
34140-59 = "If so, our mission to occupy Gehenna and Trinity... "
34140-60 = "...never...actually mattered to her?"
34140-61 = "..."
34140-62 = "Then was the meaning of all this? All this pain..."
34140-63 = "Whatever COULD it mean, little one?"
34140-64 = ""
34140-66 = ""
34140-68 = ""
34140-70 = ""
34140-71 = "...We're surrounded?!  "
34140-72 = "How did you..."
34140-73 = "She knew this was our only way in."
34140-74 = ""
34140-76 = ""
34140-77 = "A+ for you, little Misaki.  "
34140-78 = "...Madame."
34140-79 = "This is my territory. You can't so much as take a breath here without me knowing."
34140-80 = "Your childish plans were obvious from the start. Did you really think you could outsmart me, children?"
34140-81 = "Sh-She read us like a m-magazine!"
34140-82 = "Indeed. We've just been playing into her game."
34140-83 = "..."
34140-84 = "And yes, Saori. You were correct."
34140-85 = "From the beginning, your true mission was to bring the royal blood to the old cathedral and manifest the Council."
34140-86 = "All I needed was for you to open a path to the Mimesis ability. Of course, Maestro doesn't like me treading on his supposed area of expertise much."
34140-87 = "..."
34140-88 = "Trinity and Gehenna were little flies that landed on my chessboard."
34140-89 = "I only used them as an excuse to fuel the deep-seated hate within your district. It made you little fools...so very, very easy to control."
34140-90 = "...?!"
34140-91 = "In that sense, I suppose you actually did fulfill your mission! I couldn't have gotten the Mimesis ability without you.  "
34140-92 = "Not only that, you handed over the royal blood so nicely. What an obedient little child you are, Saori."
34140-93 = "I was only obedient to keep Hime safe! You lied to us."
34140-94 = "Yes, yes. So tragic, so sad. Anyways, I have more important matters to attend to.  "
34140-95 = ""
34140-97 = ""
34140-100 = "U-Ugh!"
34140-102 = "And we finally meet, [USERNAME] Sensei.  "
34140-103 = "[s] \"How do you know who I am?\""
34140-104 = "Schale's educator. The beloved Sensei. Your reputation truly precedes you. I've anticipated this meeting for some time now."
34140-105 = "Allow me to introduce myself. I am Beatrice, a member of Gematria, but you may call me Madame."
34140-106 = "[s] \"I can't say I'm pleased to meet you, Beatrice. You're the...ruler of Arius?\""
34140-107 = "Tch. Insolence. Yes, I was the only one in Gematria who successfully established an estate. And look at how mine flourishes."
34140-108 = "Aren't you curious how I've brought the entire student body under my control? I'll tell you my secrets...for a few in return, of course."
34140-109 = "[s1] \"I don't care about your twisted methodologies.\"\n[s2] \"I already know how your type works.\""
34140-110 = "Oh? You're just as I imagined you'd be.  "
34140-111 = "Oh? How disappointing. "
34140-112 = "You see, despite the way I look, I have no special powers or abilities.  "
34140-113 = "I have at times wished for it...mind control, brainwashing. It certainly could have saved me a considerable amount of time. But we adults must do things our way, as you well know."
34140-114 = "Hate, contempt, anger, disgust... Such intense, all-encompassing emotions. They're laughably easy to manipulate.  "
34140-115 = "I do love the elegance of it. All I had to do was ignite the flame and watch my carefully laid-out plans burn the world down. At least, they would have before you intervened."
34140-117 = "But those silly little brats you're trying so hard to save were already waging a civil war before I came along. Did you know that, Sensei?"
34140-118 = "All that deep-seated rage...that boiling hatred against the world. I simply...utilized it. I would hardly consider them poor, innocent little students."
34140-119 = "Of course all those students you fervently protect are the same. Human nature is violent and selfish at its core."
34140-122 = "You need only turn your gaze at Trinity to understand. You've witnessed it, Sensei. Their hatred. Their cruelty."
34140-123 = ""
34140-124 = "When you consider it that way, isn't there a beauty to my methods?  "
34140-125 = "All I do is reach my hand into the insatiable void of hate they already possess and rip it open further. And then I fill that hole with my own teachings until my voice is the only command they follow."
34140-126 = "And forcing them to commit heinous crimes under my command... The guilt they inherently suffer makes them latch onto me even harder. Is it my fault? Is it theirs? I do love watching them unravel."
34140-127 = "You see, I distort the very fabric of their reality. Their emotions are no longer their own, their relationships with each other falling to the wayside as I become the only lifeboat in the middle of a treacherous sea."
34140-128 = "Paradise is only paradise if it's exclusive. And in mine, adults dominate, exploit, and devour these unfortunate souls."
34140-129 = "The more hellish for them, the more comfortable this paradise becomes for me.  "
34140-130 = "Now, my dearest Sensei. Why don't you run along and let me prey upon my loyal subjects in peace?"
34140-132 = "Would you mind giving up on the royal blood?"
34140-133 = "I've spent so much effort on her. You wouldn't want me to waste it, would you? And I promise, you'll benefit from her sacrifice, too."
34140-134 = "Aren't you the least bit curious? What the sacrifice of one insignificant student can achieve?"
34140-135 = "I'll make a world built just for you. Don't you like the sound of that, Sensei?"
34140-137 = "Come join me, and I'll tell you everything. About our new world, and secrets about the world we currently live in."
34140-138 = "Kivotos is...truly...a marvel. A sublime tale of mystery and horror."
34140-139 = ""
34140-140 = "And I can show you the truth behind all of it. Take my hand, Sensei. It's the last time you'll see it extended."
34140-141 = "[ns] \"Enough out of you.\""
34140-142 = "Oh?"
34140-143 = "[s3] \"I'm not interested in your delusional, twisted dreams.\"\n[s4] \"I don't need a truth that demands innocent blood.\""
34140-144 = "Hahaha. They were right. You are resolute in your ways.  "
34140-145 = "Hahaha. They were right. You are resolute in your ways. "
34140-146 = "If our truths can't align, I can only see you as my adversary."
34140-147 = "So...is this Eden Treaty your paradise? A bumbling, idealistic world where love and friendship overcome all?"
34140-148 = "You're really no better than those naive children."
34140-149 = "You can't slap the word paradise onto something and sell it to them. As an adult, you should be teaching the truth."
34140-150 = "\"Paradise is the origin of the first sin...\""
34140-151 = "Real paradise is hate. It's anger and remorse. It's the evil that lies within all of us."
34140-152 = "[ns] \"Beatrice.\""
34140-153 = ""
34140-154 = "[ns5] \"You've insulted our way of living long enough.\" \n[ns6] \"Your methods are an insult to everything I stand for.\"\n[ns7] \"As an adult, I cannot forgive you.\""
34140-159 = "...So that's the path you choose, Sensei?  "
34140-160 = "So be it. I'll be waiting for you in the basilica."
34140-161 = "Why don't we take bets on whether you can make it to me?"
34140-162 = "Sensei, you truly are an incomprehensible presence."
34140-164 = "Black Suit perceives you as a rival. Quite a compliment, coming from him."
34140-165 = "Maestro is absolutely fascinated with you. He thinks you alone can understand him."
34140-166 = "To Golconde, you're a metaphor that completes his eternal search."
34140-167 = "And I perceive you as an adversary. We reject each other, like oil and water."
34140-169 = "My natural enemy."
34140-170 = ""
34140-174 = ""
34140-175 = ""
34140-177 = "(...)"
34140-178 = "(...)"
34140-179 = "(Yes, yes, yes. W-We're...ready!)"
34140-180 = "Squash them. Grind them under your heel."
34140-181 = ""
34140-183 = ""
34140-184 = ""
34140-185 = "[ns] \"I'm with you, Squad!\""
34140-186 = "BEATRICE!"
