[translation]
34155-3 = "#na;미카;콜록, 콜록……."
34155-4 = "3;사오리;15;하아…… 하아…….\n#3;a\n#3;stiff"
34155-5 = "3;사오리;15\n1;미사키;S2_11;간신히 제압했나…….\n#1;a"
34155-6 = "5;히요리;04;으, 으으…… 쓰러트린 건가요.\n#5;a\n#5;em;[땀]"
34155-7 = "#st;[0,0];instant;1;"
34155-9 = "5;히요리;04\n1;미사키;S2_11\n3;사오리;15\n#1;d\n#3;d\n#5;d\n#wait;1500"
34155-10 = "3;미카;13;끄응…… 아파……. 역시 선생님이 있으면 번거롭네…….\n#3;a\n#3;greeting"
34155-11 = "[s1] \"미카…… 세이아는 분명 무사할 거야.\"\n[s2] \"그러니까 트리니티로 돌아가 있어. 널 다치게 하고 싶지 않아!\""
34155-12 = "3;미카;13;선생님…….\n#3;stiff"
34155-13 = "3;미카;13;선생님…….\n#3;stiff"
34155-14 = "3;미카;17;미안해……. 난 늘 이런 식이지……"
34155-15 = "3;미카;17;나 같은 문제아는…… 선생님의 마음을 몇 번이고 아프게 한 아이는……. 선생님의 곁에 있을 수 없다는 것도 잘 알아…….\n#3;em;…\n#3;closeup"
34155-16 = "#st;[0,0];instant;1;"
34155-18 = "3;미카;17\n#3;h\n#3;closeup\n#wait;1000"
34155-19 = "#all;hide\n#na;미카;그치만, 그치만…… 난……."
34155-21 = "#na;미카;나는…… 나는……."
34155-23 = "#na;미카;돌아갈 곳이 없어……. 트리니티에도……, 어디에도……."
34155-24 = "#na;미카;나는 트리니티의 배신자에다가 공공의 적이고…… 몇 번이고 세이아 쨩을 다치게 하는 마녀라서……."
34155-25 = "#na;미카;학원에서 쫓겨나면 나기 쨩도, 선생님도…… 소중한 사람들도 두 번 다시 못 만나게 될 거란 것도 잘 알아……."
34155-26 = "#na;미카;학생이 아니게 된다면…… 나 같은 문제아 따위, 선생님도 더 이상 만나주지 않을 거야……."
34155-27 = "#na;미카;나에게 더 이상 행복한 미래 따위 없다는 것도 잘 알고 있어……."
34155-28 = "#na;미카;그야 나는 악당이니까……. 살인자니까……."
34155-29 = "#na;미카;그러니까…… 나에게 남은 건 [ruby=.]이[/ruby][ruby=.]런[/ruby] [ruby=.]것[/ruby] 밖에 없단 말야……."
34155-30 = "#na;미카;그런데 너희는…… 어째서!!\n#fontsize;90\n#bgshake"
34155-31 = "#na;미카;나는 소중한 걸 다 잃어버렸는데! 전부 뺏겨버렸는데!\n#fontsize;90"
34155-32 = "#na;미카;그런데 어째서 너희는!\n#fontsize;90"
34155-34 = "3;사오리;07;…….\n#3;a"
34155-35 = "5;히요리;06;…….\n#5;a"
34155-36 = "5;히요리;06\n3;사오리;07\n1;미사키;S2_05;…….\n#1;a"
34155-37 = "#st;[0,0];instant;1;"
34155-39 = "5;히요리;06\n3;사오리;07\n1;미사키;S2_05\n#1;d\n#3;d\n#5;d\n#wait;1000"
34155-40 = "3;미카;18;너희를 그냥 두면, 너희가 아무런 대가도 치르지 않고 희희낙락하는 걸 그냥 두고 보면…….\n#3;a"
34155-41 = "3;미카;18;나는……\n#3;stiff"
34155-42 = "3;미카;19;나는…… 아무것도 아니게 돼……."
34155-43 = "3;미카;19;나에겐 어떤 의미도 남지 않아……."
34155-44 = "3;미카;18;그치만……."
34155-45 = "#all;hide\n#na;미카;나는 어떻게 해야 할지……."
34155-46 = "#na;미카;……."
34155-47 = "3;미카;13;스쿼드를, 사오리를 그냥 둘 수 없어…….\n#3;closeup"
34155-48 = "3;미카;13;저 여자가 아무렇지도 않게 뻔뻔하게 선생님의 호의를 받고 있어선 안 돼…….\n#3;closeup"
34155-49 = "3;사오리;16;…….\n#3;closeup"
34155-50 = "3;미카;20;선생님, 그러니까 나를 막아선 안 돼.\n#3;closeup\n#3;em;…"
34155-51 = "#st;[0,0];instant;1;"
34155-53 = "3;미카;20\n#3;closeup\n#wait;250"
34155-54 = "3;미카;20\n#3;closeup\n#3;d\n#wait;1000"
34155-56 = "3;미카;20\n#3;a\n#3;stiff\n#wait;1500"
34155-57 = "3;미카;20\n#3;m4\n#wait;850"
34155-58 = "3;미카;20\n#3;dr\n#wait;200"
34155-63 = "[ns] \"미카! 안 돼, 기다려!!\""
34155-64 = "5;히요리;02;가, 가버렸어요……?\n#5;a"
34155-65 = "1;미사키;S2_11;무슨 속셈이지……. 저 여자는. \n#1;a"
34155-66 = "5;히요리;02\n1;미사키;S2_11\n3;사오리;16;그렇게까지…… 내가 증오스러운 건가. 미카.\n#3;a"
34155-67 = "5;히요리;02\n1;미사키;S2_11\n3;사오리;17;……그렇군. 뻔뻔하다고 생각해도 어쩔 수 없겠지."
34155-68 = "5;히요리;02\n3;사오리;17\n1;미사키;S2_05;리더. 어떡하지? 저 여자는 계속 우리를 추격할 것 같은데…… 이대로 바실리카로 돌입하는 건 위험할지도 몰라.\n#1;em;[반응]"
34155-69 = "5;히요리;02\n3;사오리;17\n1;미사키;S2_11;아리우스와 성도회…… 거기에 스토커 추격자까지…… 이건 꽤 골치 아픈 상황일지도 몰라."
34155-70 = "5;히요리;02\n1;미사키;S2_11\n3;사오리;05;……아니, 이대로 구교사 지하의 회랑을 통해 바실리카로 진입한다."
34155-71 = "5;히요리;02\n1;미사키;S2_11\n3;사오리;08;그녀가 뭘 꾸미고 있든 상관없어. 가자……. 시간이 없어. \n#3;em;[!]"
34155-72 = "#st;[0,0];instant;1;"
34155-74 = "5;히요리;01\n1;미사키;S2_05\n3;사오리;05\n#3;dr\n#1;h\n#3;h\n#5;h\n#wait;2000"
34155-75 = "#3;hide\n5;히요리;10;네, 네!\n#5;hophop\n#5;em;[반응]"
34155-76 = "#st;[0,0];instant;1;"
34155-78 = "1;미사키;S2_05\n5;히요리;10\n#5;dr\n#wait;2000\n#1;h\n#5;h"
34155-79 = "#5;hide\n1;미사키;S2_99;……어쩔 수 없나. "
34155-80 = "1;미사키;S2_02;가자, 선생님도.\n#1;m2"
34155-81 = "#st;[0,0];instant;1;"
34155-83 = "1;미사키;S2_01\n#1;dr\n#wait;2000"
34155-85 = "[ns3] 따라간다.\n[ns4] (미카…….)"
34155-91 = "#nextepisode;다음화;지하 회랑"
