[translation]
34180-1 = "ตอนที่ 18;พวกเราอีกคน"
34180-9 = "ฮิโยริ มิซากิ ทางนี้ มาซ่อนตรงนี้"
34180-10 = "พะ... พี่คะ..."
34180-11 = "ชู่ว! เงียบๆ สิ ก้มหัวลงไป"
34180-12 = "ค่ะ แต่ว่าคนที่อยู่ตรงกลางตรงนั้นคือใครเหรอคะ? เธอใส่ชุด... สะ... สวยมากเลย..."
34180-13 = "ฉันเองก็ไม่รู้... เธอคงเป็นคนสำคัญละมั้ง"
34180-14 = "องค์หญิงไง คนที่มีเชื้อสายสูงส่งน่ะ"
34180-15 = "อะ... องค์หญิง?! องค์หญิงงั้นเหรอคะ?"
34180-16 = "นะ... ในโลกนี้มีองค์หญิงด้วยเหรอคะ? คงเป็นคนที่ต่างจากหัวขโมยอย่างพวกเรา..."
34180-17 = "คงไม่ต้องขโมยอาหาร... ไม่ต้องถูกหิมะกัด... และไม่ต้องมานอนข้างถนนใช่ไหมคะ...? คนแบบนั้น#nใช่ไหมคะ?"
34180-18 = "หะ... หืม...?"
34180-19 = "ใช่สินะคะ ฉันนึกว่าโลกนี้มีแต่ความเจ็บปวดเสียอีกค่ะ... ที่จริงก็มีองค์หญิงสวยๆ แบบนั้นอยู่ด้วย... ตื้นตันใจจังค่ะ ฮือออออ!"
34180-20 = "อย่าร้องสิ เดี๋ยวโดนจับได้นะ!"
34180-21 = "ขอโทษค่ะพี่... ฮือออออ! แต่ว่า... ฮืออออ"
34180-22 = "ถึงจะได้ชื่อว่าองค์หญิง แต่ก็อยู่ในสถานการณ์ที่ไม่ต่างจากพวกเราหรอก ไม่สิ อาจจะแย่กว่าเราก็ได้"
34180-23 = "......?"
34180-24 = "ถึงมันจะดูเหมือนการเดินขบวนอยู่ก็จริง แต่มันก็เป็นขบวนที่ส่งตัวประกันของเราไปหาศัตรู เธออาจจะเป็นเชลยสงครามก็ได้นะ"
34180-25 = "ยังไงองค์หญิงคนนั้นก็ต้องหนาวและอดตายในคุกที่เยือกเย็น ถ้าอย่างน้อยได้กินเศษอาหารบ้างก็#nคงจะดีนะ"
34180-26 = "แงงง..."
34180-27 = "พอเถอะมิซากิ ฮิโยริกลัวหมดแล้วนะ"
34180-28 = "....... แล้วจะเอายังไงต่อล่ะ? มาถึงที่นี่แล้วทั้งที จะแค่เดินดูแล้วกลับไปงั้นเหรอ? พี่ซาโอริ?"
34180-29 = "ไม่หรอกก็ต้องจู่โจมอยู่แล้วสิ เราจะใช้ประโยชน์จากฝูงชนแล้วขโมยของราคาแพงไปให้ได้เยอะๆ เลย"
34180-30 = "เอาละ ไปกันเถอะ"
34180-38 = "พอได้แล้ว!!"
34180-39 = "หลบไปซะ หัวหน้าหน่วย 8"
34180-40 = "จะทำลายฮาโลกันเลยรึยังไง!!? บอกว่าให้พอได้แล้ว!"
34180-41 = "ขอร้องละ... หยุดเถอะ... ฮือ... ฮือ..."
34180-42 = "เด็กคนนั้นต่อต้านเรา ไม่ใช่คนแกร่งธรรมดาๆ เลย ถ้าไม่หลีกไปละก็ เธอเองก็จะเป็นแบบเดียวกัน"
34180-43 = "แค่ก... แค่ก... อย่ามาตลกนะ... ใครจะ..."
34180-44 = "กล้าดียังไง!!"
34180-45 = "เดี๋ยวก่อน!!"
34180-46 = "ฉะ... ฉัน...!! ฉันจะสอนเด็กคนนี้เอง!"
34180-47 = "สอน......?"
34180-48 = "ทำอะไรไม่เข้าเรื่องอีกแล้ว..."
34180-49 = "ฮิโยริกับมิซากิก็เกรดดีมาก สะ... ส่วนองค์หญิง ฉันก็กำลังสอนอยู่"
34180-50 = "เพราะฉะนั้นให้เป็นหน้าที่ของฉันเถอะ ฉันจะสั่งสอนและตักเตือนให้เอง...!!"
34180-53 = "เจ็บนะ..."
34180-54 = "อย่าทำแบบนี้อีกนะ! มิซากิ! ไม่ได้เด็ดขาด...!!"
34180-55 = "ทำไมล่ะ...?"
34180-56 = "หืม...?"
34180-57 = "ทำไมต้องเจอความเจ็บปวดที่ไร้ความหมายแบบนี้ไปเรื่อยๆ ด้วย?  "
34180-58 = " ทั้งหนาว ทั้งหิวทั้งเจ็บตัว ทำไมถึงมีแต่วันที่เจ็บปวดซ้ำแล้วซ้ำเล่า  "
34180-59 = "ทำไมล่ะ? ทำไมพี่ถึงบีบบังคับความเจ็บปวดที่ไม่มีความหมายกับพวกเราด้วย? มันมีความหมายอะไรเหรอ?"
34180-60 = "ระ... เรื่องนั้น..."
34180-61 = "แบบว่า... เรื่องนั้นมัน..."
34180-62 = "เห็นมั้ย... พี่ก็ตอบไม่ได้ พี่แกล้งทำเป็นรู้ทุกอย่าง แต่ที่จริงพี่เองก็ไม่รู้อะไรเลยเหมือนกัน "
34180-63 = ""
34180-65 = "มะ... มิซากิ... รอเดี๋ยวก่อนสิ!"
34180-66 = "รอก่อนสิ! ฉะ... ฉัน..."
34180-68 = "ฉันทำผิดไปแล้ว... ยกโทษให้ฉันเถอะ... ฉันผิดไปแล้ว..."
34180-69 = "ขอโทษ... ขอโทษจริงๆ ฉันจะไม่ทำแบบนั้นอีกแล้ว..."
34180-70 = "ฉันจะไม่ขัดคำพูดของผู้ใหญ่อีก ฉันจะไม่ขัดขืน... จะไม่คาดหวังใดๆ..."
34180-71 = "จะไม่หวังให้ตัวเองมีความสุขขึ้นอีกแล้ว... ฉันจะไม่ทำแบบนั้นแล้ว..."
34180-72 = "ยกโทษให้ฉันด้วยเถอะ ขอร้องละ..."
34180-74 = "ได้โปรด... เมตตา..."
34180-75 = "เมตตา..."
34180-77 = "ทำไมถึงขัดขืนขนาดนั้นล่ะ? อาซึสะ?"
34180-78 = "สัญลักษณ์แห่งการปรองดองเหรอ...? มันก็แค่คำหลอกลวงเท่านั้น เธอไม่ใช่คนแบบนั้นหรอก"
34180-79 = "สิ่งที่เธอได้เตรียมตัวและร่ำเรียนมา มันจะถูกใช้ประโยชน์ใน <ภารกิจฆาตกรรม> ต่างหากล่ะ"
34180-80 = "เพราะฉะนั้นจงล้มเลิกและยอมรับซะเถอะว่าทุกอย่างมันไร้ความหมาย"
34180-81 = "อาซึสะ...?"
34180-82 = "เธอ... เธอว่าอะไรนะ? เธอหมายความว่าอะไร? รอก่อน เดี๋ยวสิ..."
34180-85 = "จะไปไหนน่ะ? อาซึสะ!"
34180-86 = "รอก่อนสิ! เธอพูดว่าอะไรน่ะ? เธอหมายความว่ายังไง... แล้วจะไปที่ไหนน่ะ? พวกเรายังอยู่ที่นี่อยู่เลย..."
34180-87 = "อาซึสะ..."
34180-88 = "เธอ... นี่เธอ... รู้อยู่แล้วเหรอ? เธอ... รู้คำตอบนั้นอยู่แล้ว...?"
34180-89 = "บอกฉันหน่อยสิ ฉันน่ะ... ฉัน..."
34180-90 = "นี่ฉัน... ต้องทำยังไง..."
34180-92 = ""
34180-93 = "....... อาซึสะ..."
34180-94 = "อาซึสะ...?"
34180-95 = "...!! อะ... อึก!"
34180-96 = ""
34180-98 = ""
34180-99 = "อึก..."
34180-100 = ""
34180-103 = "เธอไม่ไหวแล้วละ... คงทำอะไรต่อทั้งๆ ที่มีบาดแผลพวกนี้ไม่ไหวแล้วละนะ ซาโอริ"
34180-104 = "นั่นน่ะสินะ..."
34180-105 = "อืม ฉันแพ้แล้วสินะ ก็สมควรแล้ว... แพ้ตั้งแต่แรกแล้ว..."
34180-106 = "พอกันที..."
34180-107 = "พอแล้วงั้นเหรอ...?"
34180-108 = "อืม... ฉันไม่รู้ว่าจะต้องทำยังไงต่อไปแล้ว"
34180-109 = "ฉันคิดว่านี่คือสิ่งที่ถูกต้องก็เลยมาในเส้นทางนี้ตลอด... แต่พอมองย้อนกลับไป ทุกอย่างมันก็ผิดไปเสียหมด..."
34180-110 = "อาซึสะ..."
34180-111 = "......?"
34180-112 = "ตอนนั้นเธออยากถามอะไรจากอาซึสะงั้นเหรอ?"
34180-113 = "เธอได้ยินด้วยเหรอ..."
34180-114 = "อาซึสะจังชมรมชั้นเรียนเสริมคือสายลับที่ถูกเลือกให้มาช่วยในแผนการปฏิวัติตั้งแต่แรกไม่ใช่รึไง?"
34180-115 = "หากไม่มีความช่วยเหลือจากคุณครู ก็คงเป็นแค่หมากที่ไม่ได้สำคัญอะไร..."
34180-116 = "อาซึสะน่ะ..."
34180-117 = "ไม่ได้ถูกเลือกให้เป็นสายลับตั้งแต่แรกหรอก"
34180-118 = "อะไรนะ...?"
34180-119 = ""
34180-121 = ""
34180-122 = ""
34180-123 = "ในตอนแรกนั่นน่ะ... "
34180-124 = "อาซึสะจะถูกกำหนดให้เป็น <สัญลักษณ์แห่งการปรองดอง>"
34180-125 = "..."
34180-126 = "อะไรกัน..."
34180-127 = "การปรองดองระหว่างทรีนิตี้กับอาเรียส... เธอเองไม่ใช่เหรอที่ใช้คำอะไรแบบนั้น มิกะ  "
34180-128 = "พูดอะไรของเธอน่ะ... เรื่องนั้น... อื้อ นึกออกแล้ว ตอนที่พูดอ้อมค้อมเพื่อหลอกคุณครู..."
34180-129 = "ไม่ใช่ มันคือคำที่เธอพูดตอนมาหาพวกเราครั้งแรกต่างหาก"
34180-130 = "ก่อนที่จะเกิดการบุกรุกไปหาเซอาเสียอีก มันไม่ได้มีการวางแผนอะไรไว้ตั้งแต่แรกเลย ทั้งสนธิสัญญาเอเดน ทั้งแผนการปฏิวัติของเธอ"
34180-131 = "......."
34180-132 = "ตอนนั้นเธอ... พูดแค่ว่าอยากคืนดีกับอาเรียส"
34180-133 = ""
34180-134 = "ว่าไงๆ เธอเป็นใครฉันไม่รู้หรอกนะ นักเรียนอาเรียสใช่รึเปล่า...?"
34180-135 = "อืม... วันนี้อากาศดีเนอะว่าไหม? ทั้งปลอดโปร่ง แล้วก็..."
34180-136 = "เด็กทรีนิตี้สินะ เธอต้องการอะไร"
34180-137 = "โอ้... สงสัยจะไม่ชอบการคุยละลายพฤติกรรมสินะ ก็ได้ งั้นฉันจะเข้าเรื่องเลยแล้วกัน"
34180-138 = ""
34180-140 = ""
34180-142 = "ฉัน... อยากคืนดีกับนักเรียนอาเรียสน่ะ"
34180-143 = "คืนดี...?"
34180-144 = "อื้ม ถึงมันอาจจะฟังดูหักดิบไปหน่อยก็เถอะนะ ก็..."
34180-145 = "พวกเธอคงจะยังแค้นพวกฉันอยู่ใช่มั้ยล่ะ?"
34180-146 = "ถึงได้ปฏิเสธความช่วยเหลือของพวกฉันและขององค์การนักเรียน แล้วมาอยู่อย่างโดดเดี่ยว และดื้อดึงในเขตปกครองตนเองลับๆ แบบนี้ เพราะความแค้นในอดีต..."
34180-147 = "......."
34180-148 = "อื้ม แต่ความแค้นระหว่างสองฝ่ายมันยิ่งใหญ่เกินกว่าจะแก้ไขได้ แถมยังมีความเข้าใจผิดที่สะสม#nมาตั้งเยอะ... ปัญหานี้ไม่ง่ายเลยละ"
34180-149 = "มันก็สมควรแล้วละนะที่นางิจังกับเซอาจังจะไม่เห็นด้วย..."
34180-150 = "แต่ถึงอย่างนั้นก็เถอะ... การอยู่ร่วมกันอย่างสงบสุขมันยากขนาดนั้นเลยเหรอ? หากทั้งสองฝ่ายต่าง#nพยายามกัน สักวันหนึ่งมันก็น่าจะเป็นไปได้ ใช่ไหมล่ะ?"
34180-151 = "ฉันคิดแบบนั้น... ก็เลยมาหาพวกเธอ จะได้เป็นการพยายามทีละนิดๆ ไง"
34180-152 = "จะให้ฉันเชื่อได้ยังไงว่าคำพูดนั้นเป็นความจริง...?"
34180-153 = "อืม... ฉันพอจะเข้าใจปฏิกิริยาตอบกลับของเธออยู่หรอก ฉันก็เลยลองคิดมาแล้วน่ะ"
34180-154 = "ให้นักเรียนอาเรียสของเธอย้ายมาเรียนที่ทรีนิตี้สักคนมั้ยล่ะ? มาแบบไม่มีใครรู้ไง   "
34180-155 = "ถ้ามีฉันช่วยสนับสนุนอยู่จากข้างหลังยังไงก็ทำได้อยู่แล้ว เห็นอย่างนี้แต่ฉันก็เป็นถึง สมาชิกสภาน้ำชาเลยเชียวนะ"
34180-156 = "......."
34180-157 = "เราจะใช้สิ่งนั้นเป็นการพิสูจน์ให้ทุกคนเห็นว่านักเรียนอาเรียสสามารถใช้ชีวิตอยู่ในโรงเรียนของเรา#nได้โดยไม่มีปัญหาใดๆ"
34180-159 = "พูดง่ายๆ คือให้นักเรียนคนนั้นเป็น <สัญลักษณ์แห่งการปรองดอง> ของเรา เป็นยังไงล่ะ? น่าสนใจใช่ไหม? หือ?"
34180-160 = ""
34180-162 = ""
34180-163 = "เป็นแผนที่ไม่น่าเป็นไปได้เลย..."
34180-164 = "ตะ... แต่ว่า... หากมีนักเรียนสัญลักษณ์คนนั้น ฉันว่าทั้งเซอาจังและนางิจังก็จะเห็นด้วยนะ!"
34180-165 = "..."
34180-166 = "เข้าใจแล้ว เธอรอพวกเราติดต่อกลับไปก็แล้วกัน นี่ไม่ใช่ปัญหาที่ฉันจะตัดสินใจคนเดียวได้"
34180-167 = "อ๊ะ? ดะ... เดี๋ยวก่อนสิ? มีนักเรียนให้ไปเรียนจริงๆ เหรอ?"
34180-168 = "......."
34180-169 = ""
34180-171 = ""
34180-172 = ""
34180-175 = "อาซึสะ นี่คือภารกิจ"
34180-176 = ""
34180-179 = "อะไรเหรอ...?"
34180-181 = "คืนดีกันงั้นเหรอคะ? ช่างเป็นความคิดที่น่าสมเพชและไร้เดียงสาเหลือเกินค่ะ ถ้าไม่ใช่กับดัก ก็คงเป็นเรื่องที่แปลกประหลาดมากๆ เลยค่ะ"
34180-182 = "ฮึ่ม... ไม่ต้องรีบร้อนหรอกค่ะ ไว้เรามารอดูกันว่าจริงๆ แล้วจะเป็นแค่เด็กไร้เดียงสา หรือว่าจะเป็นงูพิษ#nกันแน่"
34180-183 = "ปฏิเสธไปก่อนค่ะ แล้วก็พูดจาจูงใจไปเรื่อยๆ เพื่อรักษาความสัมพันธ์ของเธอคนนั้นไว้ จากนั้นก็#nล้วงเอาข้อมูลของทรีนิตี้มาค่ะ"
34180-184 = "นั่นคือการ... ปฏิเสธเหรอคะ?"
34180-185 = "ก็ใช่สิคะ สัญลักษณ์แห่งการปรองดองเหรอ? ฝันกลางวันอยู่รึไงคะ โลกสวยจังเลยนะคะ ฉันจะใช้มันเป็นเครื่องมือในการล้วงข้อมูลของทรีนิตี้ค่ะ "
34180-186 = "......."
34180-187 = "ว่าไงล่ะ? ซาโอริ? มีปัญหาอะไรหรือเปล่าคะ? หรือว่าแอบไปเตรียมการอะไรตามอำเภอใจ#nโดยไม่ได้รับการอนุญาตจากฉันคะ?"
34180-188 = "ปะ... เปล่าค่ะ มาดาม"
34180-189 = "ไม่ได้ลืมใช่ไหมคะ? เหตุผลที่พวกเธอต้องทนทุกข์ทรมาน เหตุผลที่ต้องหนาวกาย ต้องหิวท้อง และต้องหมดหวังน่ะ"
34180-190 = "ค่ะ... ทั้งหมดนั้นเป็นเพราะทรีนิตี้ที่ขับไล่พวกเราออกมาค่ะ"
34180-191 = "ใช่ค่ะ เราไม่จำเป็นต้องคืนดีกับศัตรู แล้วก็อย่าลืมความแค้นนั้นเด็ดขาด"
34180-192 = "ค่ะมาดาม  ฉันจะไม่ลืมเด็ดขาดค่ะ"
34180-194 = "ฉันก็ไม่รู้ว่าทำไมถึงเป็นอย่างนั้น... แต่ถ้าเป็นอาซึสะละก็... ถ้าเป็นอาซึสะ..."
34180-195 = "หรือตอนนั้น... ฉันคิดว่าอยากให้อาซึสะช่วยเป็นสัญลักษณ์นั้น..."
34180-196 = "......."
34180-197 = "แต่โอกาสที่จะพิสูจน์สิ่งนั้นได้ยังไม่เคยมาถึงเลยนี่สิ..."
34180-198 = ""
34180-199 = ""
34180-200 = ""
34180-201 = "ที่นี่คือที่ที่เซอาจังอยู่..."
34180-202 = "ฉันจะส่งเซอาจังไปพักฟื้นที่โรงพยาบาลระยะยาว และจะรับตำแหน่งโฮสต์ต่อเอง อื้อ"
34180-203 = "เพราะงั้น... ฝากด้วยนะ"
34180-205 = "......."
34180-206 = "มาดามไม่พลาดโอกาสนั้น เพราะสำหรับมาดามแล้ว เซอาคือคนที่กวนใจเธอ"
34180-207 = "เธออาจจะคิดว่าพวกเราเป็นแค่ทหารส่วนตัวที่ใช้งานง่ายสินะ เพราะถ้าไม่อย่างนั้นก็คงไม่บอก#nตำแหน่งลับสุดยอดของเซอาให้"
34180-208 = "ไม่ใช่หรอก เราไม่ใช่กลุ่มอันธพาลแบบนั้น พวกเรา..."
34180-210 = "คือฆาตกรที่ศึกษา <วิธีทำลายฮาโล> แล้วฝึกฝนจนได้เครื่องมือนั้นมา..."
34180-212 = "ภารกิจฆ่าเซอาด้วย <ระเบิดทำลายฮาโล> ถูกมอบหมายให้พวกเราทำ"
34180-216 = "ส่วนอาซึสะ... จะต้องมาเข้าร่วมภารกิจเพราะความรู้เกี่ยวกับทรีนิตี้ที่เตรียมไว้เพื่อเป็นสัญลักษณ์#nแห่งการปรองดอง"
34180-224 = "....... นางิจังกำลังทำอะไรแปลกๆ อยู่"
34180-225 = "......."
34180-226 = "เธอน่าจะสติหลุดหลังจากเซอาจังตายไป ข้อตกลงสันติภาพกับเกเฮนน่างั้นเหรอ... เชื่อเค้าเลย นางิจังนี่... "
34180-227 = "เอาละ เพราะงั้นฉันเลยอยากเริ่มแผนการที่ฉันเสนอไว้คราวก่อนน่ะ"
34180-229 = "ส่งสายลับเข้าไปในทรีนิตี้ แต่ครั้งนี้ต้องใช้วิธีที่รัดกุมมากกว่าตอนเซอาจังนะ"
34180-231 = "เธอน่ะ..."
34180-232 = "ฉันไม่อาจเข้าใจเธอได้เลย ฉันประมาณการไม่ได้ด้วยซ้ำว่าเธอต้องการอะไร และไล่ตามอะไรอยู่"
34180-233 = "ถ้าจะให้คิดว่าที่เป็นแบบนี้เพราะเป็นคนโง่มันก็ได้อยู่... แต่ว่า... ฉันปล่อยไปง่ายๆ แบบนั้นไม่ได้"
34180-234 = "ถึงแม้ในตอนที่ได้ยินคำว่า <คืนดี> จากเธอเป็นครั้งแรก... ฉันก็คิดว่าเธอพูดอะไรเหลวไหล... "
34180-235 = "แต่ถ้ามันไม่ใช่ล่ะ? พวกเราอาจจะมีโอกาสได้มีอนาคตแบบนั้นบ้างก็ได้..."
34180-236 = "ฉันก็เลยลบความคิดแบบนั้นออกไปไม่ได้เลย..."
34180-237 = "......."
34180-238 = "มิกะ ฉันว่าบางทีเธอ..."
34180-239 = ""
34180-241 = ""
34180-242 = ""
34180-243 = "เธออาจจะอยากคืนดีกับพวกเราจริงๆ ก็ได้"
34180-244 = "......."
34180-245 = "เธอคือคนที่มาหาพวกเราด้วยเจตนาดี ส่วนคนที่ตบตาและหลอกลวงเจตนาดีๆ ของเธอ#nและพาเธอไปตกนรกก็คือฉันเอง"
34180-246 = "และเพราะเธอไม่สามารถยอมรับนรกนี้ได้... ก็เลยหลอกลวงและปฏิเสธความทรงจำของตัวเองไงล่ะ"
34180-247 = "ใช่แล้ว ไม่ใช่แค่เธอหรอกนะ..."
34180-248 = "ทั้งการที่องค์หญิงต้องใช้ชีวิตโดยซ่อนน้ำเสียงและใบหน้า ทั้งการที่ฮิโยริกับมิซากิถูกดึงมาเข้าร่วม#nในสควอด..."
34180-249 = "แล้วก็อาซึสะที่ต้องเป็น <ฆาตกร> แทนที่จะได้เป็น <สัญลักษณ์แห่งการปรองดอง> และต้องถูกส่ง#nไปยังทรีนิตี้อีกครั้งในฐานะ <สายลับ> เพื่อหลอกลวงและตบตาทุกคน..."
34180-250 = "ทุกอย่างมันเกิดขึ้น ก็เป็นเพราะฉันเอง"
34180-251 = "ฉันน่ะ... ไม่ได้เป็นหมาล่าเนื้ออะไรนั่นหรอก ฉัน..."
34180-252 = "ฉันคือโรคร้าย... ที่ทำให้ทุกอย่างรอบตัวต้องเจ็บปวดต่างหากล่ะ"
34180-253 = "..."
34180-254 = "เรื่องที่อยากถามอาซึสะน่ะเหรอ...? ใช่... ฉันมีเรื่องที่อยากถาม..."
34180-255 = "ถึงแม้จะต้องประสบเรื่องทั้งหมดมา แต่อาซึสะก็... "
34180-256 = "ดูมีความสุขดี..."
34180-257 = "อาซึสะที่ไม่แสดงความรู้สึกต่อใครเลย ไม่ยอมรับเราและเลือกที่จะใช้ชีวิตโดดเดี่ยวเดียวดาย..."
34180-259 = "เด็กที่อ้างว้าง เย็นชาเหมือนธารน้ำแข็ง..."
34180-270 = "ได้รวมพลังกับเพื่อนๆ และผู้ใหญ่นิสัยดี..."
34180-271 = "จนผ่านความยากลำบากและความเจ็บปวดมาได้ในที่สุด...  "
34180-272 = "และได้ก้าวไปข้างหน้า... ภายใต้ท้องฟ้าสีครามที่แจ่มใสและเปี่ยมไปด้วยความสุข"
34180-274 = "ไม่... เป็นไปไม่ได้ เรื่องแบบนั้นมัน... เป็นเรื่องโกหกทั้งเพ มันคือการหลอกลวง!"
34180-275 = "เป็นภาพลวงตาที่จะหายไปในสักวันหนึ่ง!"
34180-276 = ""
34180-279 = "ต่อให้อธิษฐานไปมากแค่ไหนมันก็ไม่มีอะไรเปลี่ยนแปลงไปอยู่ดี!"
34180-280 = "อาซึสะ พวกเรามีความสุขไม่ได้หรอก เธอก็รู้ดีไม่ใช่เหรอว่าทุกอย่างมันเปล่าประโยชน์!"
34180-282 = "แต่ว่า... สุดท้ายแล้วฉันก็ยอมรับไม่ได้..."
34180-285 = "อืม แบบนี้สินะ..."
34180-286 = "ทั้งความแค้นของพวกเรา... ทั้งคำพูดที่ว่า <ทุกอย่างจะว่างเปล่าและไร้ประโยชน์>... การกระทำ#nทุกอย่างที่ผ่านมาของฉัน..."
34180-287 = "ทุกอย่างคือเรื่องโกหกสินะ..."
34180-288 = "ฉันทั้งโง่และอ่อนแอ... ฉันเป็นเหมือนโรคร้ายที่พาทุกคนไปสู่ความพินาศ... "
34180-290 = ""
34180-299 = "อะไรกัน สุดท้ายแล้วทุกอย่างเป็นอย่างนี้เองเหรอ ฉันเป็นต้นเหตุของเรื่องทุกอย่าง"
34180-300 = "ที่อาซึสะดูมีความสุขขึ้นก็เพราะเธอได้จากฉันไป"
34180-301 = "ที่ผ่านมาฉันอยากปฏิเสธความจริงนั้นให้ถึงที่สุด..."
34180-303 = "อาซึสะ เธอรู้เรื่องนี้อยู่แล้วเหรอ? อาซึสะ เธอรู้คำตอบอยู่แล้วใช่ไหม?"
34180-304 = "อาซึสะ... ฉันน่ะ..."
34180-305 = "ฉันจะมีความสุขได้บ้างรึเปล่า...?"
34180-306 = "ทำยังไงฉันถึงจะมีความสุขได้เหมือนเธอ? โอกาสแบบนั้นยังมีอยู่รึเปล่า? มันจะเป็นไปได้บ้างมั้ย...? ตัวฉันยังคาดหวังเรื่องแบบนั้นได้รึเปล่า...?"
34180-307 = "ถ้าหากว่า... ฉัน..."
34180-310 = "ถ้าได้เจอกับผู้ใหญ่นิสัยดีๆ เร็วกว่านี้สักนิด..."
34180-311 = "ฉันคนนี้... จะมีชีวิตที่ต่างออกไปไหมนะ..."
34180-312 = "ฉันจะได้พบจุดจบอื่น ที่ไม่ใช่จุดจบที่น่าสังเวชแบบนี้ไหมนะ..."
34180-313 = "ฉัน... จะได้... โอกาสแบบนั้นไหม..."
34180-314 = "อาซึสะ... ตอนนั้นเธอ... พูดว่ายังไงเหรอ?"
34180-315 = "ฉัน... คือว่า..."
34180-316 = ""
34180-319 = "พอได้แล้วละ... มิกะ"
34180-320 = "จะทำอะไรตามใจก็ทำเลย เอาไปให้เท่าที่เธอโดนแย่งไปเลยสิ"
34180-321 = "คนที่ทำให้ผู้ที่มีจิตใจอ่อนโยนอย่างเธอต้องตกเป็น <แม่มด> ที่มีแต่ความแค้น... ก็คือฉันเอง"
34180-322 = "ฉันแย่งหลายสิ่งหลายอย่างมาจากผู้คนมากมาย ให้มันจบแบบนี้ก็สมควรแล้วละ..."
34180-323 = ""
34180-326 = ""
34180-327 = ""
34180-329 = ""
34180-330 = ""
34180-332 = "อ่า... ฉันคิดมาตลอดว่านี่เป็นบทบาทของอาซึสะ... แต่ดันเป็นเธอเองงั้นสินะ มิกะ..."
34180-333 = ""
34180-337 = ""
34180-339 = ""
34180-340 = "......."
34180-341 = "ฉัน... ฉันน่ะ..."
34180-342 = "ฉัน... ทำไม่ได้... ทำแบบนั้นไม่ได้..."
34180-343 = "ฉันทำแบบนั้นไม่ได้... เพราะว่า..."
34180-344 = "ฉัน..."
34180-345 = "ฉันเองก็อยากได้โอกาสแบบนั้นมาตลอดเหมือนกัน..."
34180-346 = "ฉันเอง... ก็อยากมีความสุขเหมือนกัน..."
34180-347 = "ถ้าฉันได้เจอคุณครูเร็วกว่านี้อีกสักหน่อย... เหมือนกับเธอละก็ ถ้ามันเป็นอย่างนั้น... ฉันก็อาจจะแก้ไขความผิดพลาดของฉันได้..."
34180-348 = ""
34180-349 = ""
34180-350 = ""
34180-351 = ""
34180-352 = "ความเจ็บปวดของฉันมันยิ่งใหญ่เกินกว่าบาปที่ก่อ ไม่ยุติธรรมเลย! ถึงจะสวดภาวนาขอความเมตตามากแค่ไหน..."
34180-353 = "แต่ว่า... มันก็ไม่มีประโยชน์อยู่ดี"
34180-354 = "ฉันทำในสิ่งที่ไม่อาจย้อนคืนกลับมาได้ ฉันไม่รู้ว่าต้องทำยังไงถึงจะได้รับการให้อภัย "
34180-355 = "โอกาสที่สองเหรอ...?"
34180-356 = "ใช่ ฉันหวังว่าเมื่อเช้านี้มาถึง... ฉันจะได้โอกาสแบบนั้น... โอกาสที่คุณครูและทุกคนมารวมตัวกัน#nเพื่อฉัน... แต่ก็ไม่มีอะไรแบบนั้นเลย... มันไม่มีอนาคตแบบนั้น..."
34180-357 = "ในโลกที่ทุกอย่างว่างเปล่าและไร้ประโยชน์ ทำได้แค่หวังในการไถ่บาป และรับความทุกข์ระทม..."
34180-359 = "เธอ... ไม่ต่างจากฉันเลย ซาโอริ..."
34180-360 = "เธอไม่มีวันมีความสุขได้ เหมือนกับที่ฉันไม่มีความสุข"
34180-361 = "เป็นไปไม่ได้หรอก เราย้อนเวลากลับไปไม่ได้ และคงไม่มีโอกาสที่สองที่จะเปลี่ยนอนาคตได้..."
34180-363 = "บางทีฉันอาจจะต้องการให้เธอได้รับความเจ็บปวดที่ <ยุติธรรม> ก็ได้"
34180-364 = "แต่เพราะเป็นอย่างนี้... ฉันเลยทำไม่ได้..."
34180-365 = "ถ้าฉันตัดสินใจให้มันจบแบบนี้..."
34180-366 = "มันจะเป็นการพิสูจน์ว่าฉันไม่มีทางได้รับการไถ่บาป..."
34180-367 = ""
34180-369 = ""
34180-370 = ""
34180-371 = "มิกะ... นี่เธอ..."
34180-372 = "ทำไมกัน? ทำไมเธอถึงไม่ใช้ระเบิดทำลายฮาโลล่ะ? ทำไม? "
34180-373 = "......!!"
34180-374 = "ฉันได้ยินมาว่าเธอมีระเบิดอยู่ใช่มั้ยล่ะ? เธอมีโอกาสที่จะใช้มันไม่ใช่เหรอ? แล้วทำไมถึงไม่ใช้ล่ะ?"
34180-375 = "ใช้ไปเลยน่าจะดีกว่า ถ้าเป็นแบบนั้นแล้ว... ฉันน่ะ..."
34180-376 = "ระเบิดอะไรนั่นน่ะ... ฉันไม่มีมันมาตั้งแต่แรกแล้ว"
34180-377 = "มันถูกคุณครูยึดไปแล้วน่ะ..."
34180-378 = "หืม...?"
34180-379 = "ยึดไปเหรอ? คุณครูน่ะเหรอ? "
34180-380 = "เอ่อ...? ว่าไงนะ? ยึดไปเหมือนหนังสือติดเรทหรือยึดพวกเหล้าเบียร์อย่างนั้นเลยน่ะเหรอ?"
34180-381 = ""
34180-383 = ""
34180-384 = ""
34180-385 = "[ns] \"ใช่แล้ว ของอันตรายต้องถูกคุณครูยึด\""
34180-386 = "?!"
34180-387 = "คะ... คุณครู...?!"
34180-388 = "คะ... คุณครู... ทำไมถึงมาอยู่ที่นี่ได้...!?  "
34180-390 = "ตอนต่อไป;โอกาสที่ไม่มีที่สิ้นสุด"
