[translation]
34210-1 = "#title;제21화;돌파"
34210-4 = "3;미카;06;하아…… 하아…….\n#3;em;…\n#3;a"
34210-5 = "#st;[0,0];instant;1;"
34210-7 = "3;미카;06\n#3;d\n#wait;1000"
34210-8 = "3;유스티나 성도회 학생 A;01\n#3;a\n#wait;500"
34210-9 = "3;유스티나 성도회 학생 A;01\n1;유스티나 성도회 학생 A;01\n#1;a\n#1;h\n#3;h\n#wait;300"
34210-10 = "3;유스티나 성도회 학생 A;01\n1;유스티나 성도회 학생 A;01\n5;유스티나 성도회 학생 A;01\n#5;a\n#1;h\n#3;h\n#5;h\n#wait;2000"
34210-12 = "[ns] \"미카!! 괜찮아?\""
34210-13 = "3;미카;12;……."
34210-14 = "3;미카;12;……저 녀석들은 내가 유인할게.\n#3;em;…"
34210-15 = "#st;[0,0];instant;1;"
34210-17 = "3;사오리 부상;S2_22\n#3;shake\n#3;em;[?!]\n#wait;1500"
34210-18 = "3;미카;26;사오리……, 네가 아츠코를 구하려고 이렇게 집착하는 이유를 알 것 같아……."
34210-19 = "3;미카;99;알아…… 나도 그랬으니까. 그러니까……."
34210-20 = "3;미카;12;저 녀석들을 내가 유인할 테니, 아츠코를 구하러 가."
34210-21 = "3;미카;15;선생님……. 미안해. 늘 말썽만 부려서……. 문제만 일으키는 불량 학생이라서…….\n#3;em;…"
34210-22 = "3;미카;14;그치만…… 고마워. 나에게도 다음 기회가 있다고 말해줘서…….\n#3;greeting"
34210-23 = "5;사오리 부상;S2_15;너는…….\n#5;a\n#3;m1"
34210-24 = "3;미카;05;뭘 꾸물거리는 거야, 사오리! 선생님을 데리고 포위를 뚫어!! 시간이 없잖아?!\n#3;em;[반응]"
34210-25 = "#st;[0,0];instant;1;"
34210-27 = "3;미카;05\n5;사오리 부상;S2_15\n#3;h\n#5;h\n#5;em;…\n#wait;2500"
34210-28 = "5;사오리 부상;S2_17;……그래. 알겠어."
34210-29 = "[s] \"미카, 조심해…….\""
34210-30 = "3;미카;02;……응, 선생님. 걱정하지 마, 알잖아? 나는 꽤 강하다는 거. \n#3;m3\n#5;dr"
34210-31 = "#st;[0,0];instant;1;"
34210-33 = "#5;hide\n3;미카;12\n#3;h\n#wait;1000"
34210-34 = "3;미카;24\n#3;closeup\n#wait;1000\n#3;h"
34210-44 = "3;사오리 부상;S2_07;…….\n#3;em;…"
34210-45 = "1;미사키;11;……정말이지 제멋대로인 여자네. \n#1;a\n#3;m5"
34210-46 = "3;사오리 부상;S2_07;그래……. 서두르자."
