[translation]
34225-3 = "Arrrrgh! N-No! My manifestation...!"
34225-4 = "How could this be? Was the ritual incomplete... My...power...!"
34225-5 = "You ingrates! Insects! How dare you!"
34225-6 = "Barbara, I summon you... No. I summon all the troops within the basilica!"
34225-7 = "Come to me!"
34225-8 = ""
34225-12 = "*pant* *pant*"
34225-13 = "Sh-She's summoning more of the scary ghosts?!"
34225-14 = "Ugh... We won't last long in our states..."
34225-15 = "You can still stand, can't you? Pick up your weapons!"
34225-16 = "Get to her, before reinforcements get here!"
34225-17 = "Gather, my children! Protect your creator!  "
34225-19 = "Next Episode; Kyrie for the Students Part 1"
