[translation]
34230-1 = "Episode 23; Kyrie for the Students Part 1"
34230-3 = ""
34230-5 = ""
34230-6 = ""
34230-7 = ""
34230-8 = ""
34230-9 = ""
34230-10 = ""
34230-11 = ""
34230-12 = "*pant* *pant*"
34230-13 = "This...is the worst. Everything hurts."
34230-14 = ""
34230-16 = ""
34230-18 = "But I'm not... I'm not done yet."
34230-19 = ""
34230-29 = ""
34230-30 = "..."
34230-31 = ""
34230-33 = ""
34230-34 = "Is this a schola cantorum?"
34230-35 = ""
34230-37 = ""
34230-38 = "A pipe organ...sheet music... It must be."
34230-39 = ""
34230-41 = ""
34230-42 = "A gramophone, too. It's funny to think that Arius must have had chapel class, just like us."
34230-43 = ""
34230-45 = ""
34230-47 = "Silly me. Of course it's not working. It's like, a thousand years old at this point."
34230-48 = "..."
34230-49 = ""
34230-51 = ""
34230-53 = ""
34230-54 = ""
34230-56 = "*sigh*"
34230-57 = "Koharu, wasn't it so cool when Sensei showed up to save you?"
34230-58 = "Yeah, Koharu looked like a princess from a fairy tale that day. I like that kind of story."
34230-59 = "A story where the main character shows up and rescues a despairing princess."
34230-60 = "Maybe it's a little childish, but I think it's beautiful."
34230-61 = "...I wanted to be a princess, too."
34230-62 = "Hah. But I've never heard of a witch who transforms into a princess."
34230-63 = "It wouldn't be a fairy tale if the villain got the happy ending."
34230-64 = "...I sure did turn into a villain, huh? I'm sorry, Saori. I really thought it was only fair for you to suffer like I did."
34230-65 = "But if I really think about it..."
34230-66 = "I'm sure you just wanted to be saved."
34230-67 = "You really are like me. You wanted to find happiness too."
34230-68 = "Saori, I know why you're obsessed with Atsuko..."
34230-69 = "Even if you lied, cheated, and hurt everyone around you, it would all be okay if it meant saving your princess."
34230-70 = "You thought maybe you could absolve yourself, just a little bit. Am I right?"
34230-71 = "I know because Seia and I both thought the same way."
34230-72 = ""
34230-75 = ""
34230-76 = "That's why I'm rooting for you, Squad."
34230-77 = ""
34230-79 = ""
34230-80 = "I'll pray for your salvation."
34230-81 = "Just as I desperately wish for my suffering to subside...  "
34230-82 = "I hope yours does as well."
34230-83 = "Just as I wish and pray and beg for a second chance."
34230-84 = "I hope you get infinite chances."
34230-85 = "I long to be forgiven..."
34230-86 = "...so I forgive you."
34230-87 = "I like that ending better than anything \"fair.\""
34230-91 = ""
34230-93 = ""
34230-95 = ""
34230-97 = "Even if you save Atsuko, your future will be filled with suffering."
34230-98 = "You'll be chased for the rest your life, wandering through dirty back alleys, living a cold, hungry, miserable life."
34230-99 = "But if despite that..."
34230-100 = "If, despite all that, you truly believe you can find happiness in your future..."
34230-101 = "Save Atsuko. Save yourselves."
34230-102 = "It's too late for me...but I weirdly believe you guys can do it."
34230-103 = "Sensei will be by your side. I'm sure of it."
34230-104 = "Yeah... Sensei will help you through it."
34230-106 = "I really do hope you find the answers to your questions."
34230-107 = ""
34230-111 = "Huh? "
34230-112 = ""
34230-116 = "The gramophone? How did it start working...?"
34230-117 = ""
34230-119 = ""
34230-120 = "Ah... A song of mercy."
34230-121 = "I never did like this song very much."
34230-122 = "Well, enough of my monologue."
34230-126 = ""
34230-128 = ""
34230-131 = ""
34230-133 = ""
34230-134 = ""
34230-136 = ""
34230-137 = "Where are you going in such a hurry, huh? Do you have a class reunion or something?"
34230-138 = "I can't let you pass, unfortunately. Past here, the characters of a fairy tale are fighting for their salvation."
34230-139 = "Villains like us aren't allowed to enter."
34230-140 = "Okay, Sensei. Save those kids."
34230-141 = ""
34230-143 = ""
34230-144 = "I'll guard this place, one way or another."
34230-153 = "― [i]Kyrie[/i]"
34230-155 = "[i]Eleison[/i]"
34230-168 = "Next Episode; Kyrie for the Students Part 2"
