[translation]
3601-1 = "#title;단맛과 노스탤지어 1"
3601-2 = "3;나기사 스탠딩;17;후우……\n#3;a"
3601-3 = "3;나기사 스탠딩;19;네, 시작하시죠, 회의."
3601-4 = "3;나기사 스탠딩;02;특이사항 있으면 말씀해 주세요."
3601-5 = "5;티파티 부원 A;02;예, 나기사 님. 먼저 어제 18시경 카페 거리에서 총격전이 벌어졌습니다.\n#3;m1\n#5;al"
3601-6 = "5;티파티 부원 A;01;한정판 디저트에 얹어진 딸기의 소유권을 두고 벌어진 다툼이 총격전으로 번진 것으로 확인되었고요."
3601-7 = "#st;[0,0];instant;1;"
3601-9 = "3;나기사 스탠딩;02\n5;티파티 부원 A;01\n#3;h\n#5;h\n#3;em;…\n#wait;2500"
3601-10 = "3;나기사 스탠딩;24;딸기요……?\n#3;em;[?]"
3601-11 = "3;나기사 스탠딩;13;고작 딸기 하나 때문에……?\n#3;stiff"
3601-12 = "5;티파티 부원 A;02;정의실현부의 하스미 부부장이 비번인 관계로 츠루기 부장이 출동해 상황을 제압한 것으로 보고되었습니다."
3601-13 = "3;나기사 스탠딩;17;……츠루기 부장이라면…… 구호기사단이 꽤 바빠졌겠군요.\n#3;em;…"
3601-14 = "5;티파티 부원 A;01;예, 안 그래도 구겨진 캔…… 아니 구겨진 학생들이 많이 이송되어 구호기사단이 늦게까지 응급처치했습니다."
3601-15 = "#st;[0,0];instant;1;"
3601-17 = "3;나기사 스탠딩;23\n5;티파티 부원 A;01\n#3;h\n#5;h\n#3;em;[한숨]\n#wait;1200"
3601-18 = "3;나기사 스탠딩;20;좋습니다. 구호기사단 측은 약품과 붕대의 소모가 컸을 것 같으니……."
3601-19 = "3;나기사 스탠딩;13;관련 예산이 추가로 필요하다면 요청서를 올려 달라고 구호기사단 측에 전달 바랍니다."
3601-20 = "#st;[0,0];instant;1;"
3601-22 = "3;나기사 스탠딩;13\n5;티파티 부원 A;01\n#3;h\n#5;h\n#5;greeting\n#wait;1000"
3601-23 = "3;나기사 스탠딩;13\n5;티파티 부원 A;01\n#3;h\n#5;h\n#5;dr\n#3;m3\n#wait;1000"
3601-24 = "3;나기사 스탠딩;22;다음은요?"
3601-25 = "1;티파티 부원 B;02;다음 사안은 바로 그 구호기사단 측에서 벌어진 일입니다만…….\n#1;ar\n#3;m5"
3601-26 = "1;티파티 부원 B;04;의료 기구함에 들어있던 전기톱을 보고 패닉에 빠진 환자들이 탈출하는 사건이 벌어지는 바람에……. \n#1;stiff"
3601-27 = "1;티파티 부원 B;06;……치료실 하나가 완전히 기능이 마비되었습니다.\n#1;em;[세로선]"
3601-28 = "3;나기사 스탠딩;04;그…… 의료 기구함에 왜 전기톱이…… 하아…….\n#3;em;[땀]"
3601-29 = "3;나기사 스탠딩;13;……예, 그럼 구호기사단이 보유하고 있는 의료 기구들을 전수조사 하도록 하세요."
3601-30 = "#st;[0,0];instant;1;"
3601-32 = "3;나기사 스탠딩;13\n1;티파티 부원 B;01\n#1;h\n#3;h\n#1;greeting\n#wait;1000"
3601-33 = "3;나기사 스탠딩;13\n1;티파티 부원 B;01\n#3;h\n#1;h\n#1;dl\n#3;m3\n#wait;1000"
3601-34 = "3;나기사 스탠딩;02;자 그럼… 혹시 또 보고할 사안이 있나요?"
3601-35 = "3;티파티 부원 C;01;예, 금일 새벽 1시경에 본관 건물 옥상에서 알몸의 학생이 목격되었습니다."
3601-36 = "3;티파티 부원 C;02;본 학생이 많지는 않지만, 옥상에 귀신이 나타났다는 등의 유언비어로 번지고 있어서 조치가 필요할 것 같습니다."
3601-37 = "3;나기사 스탠딩;11;…….\n#3;em;…"
3601-38 = "3;나기사 스탠딩;16;후후…….\n#3;stiff"
3601-39 = "3;나기사 스탠딩;99;알몸……인가요."
3601-40 = "3;나기사 스탠딩;12;새벽에…… 옥상에…… 알몸……."
3601-41 = "3;나기사 스탠딩;03;왜 귀신이 아닌 거죠……?"
3601-42 = "3;티파티 부원 C;02;나기사 님……?\n#3;em;[?]"
3601-43 = "3;나기사 스탠딩;99;차라리 귀신이면 마음이라도 편할 텐데…….\n#3;em;…"
3601-44 = "3;나기사 스탠딩;08;해결 불가능한 문제면 그냥 아무것도 하지 않아도 되는데…….\n#3;closeup"
3601-45 = "3;나기사 스탠딩;09;……후후.\n#3;closeup"
3601-46 = "3;나기사 스탠딩;03;후후…… 후후후…… 후후후후…….\n#3;closeup\n#3;em;[재잘]"
3601-47 = "#st;[0,0];instant;1;"
3601-49 = "3;나기사 스탠딩;03\n#3;closeup\n#3;falldownR\n#wait;1500"
3601-51 = "4;티파티 부원 A;06;나기사 님?!\n#4;al\n#4;em;[?!]"
3601-52 = "2;티파티 부원 B;06;눈이 풀렸어요!\n#2;ar"
3601-54 = "3;티파티 부원 C;07;구호기사단! 구호기사단을 불러요! 빨리!\n#3;em;[!]\n#3;hophop"
3601-56 = "3;미카;04;나기 쨩이 과로 때문에 쓰러졌다고?!\n#3;shake\n#3;a\n#3;closeup"
3601-57 = "3;세이아;99;예. 정확히는 번아웃 증후군, 이라고 하더군요.\n#3;em;…"
3601-58 = "3;세이아;01;일단 다행히 신체적으로는 큰 문제가 없습니다만……."
3601-59 = "3;세이아;02;시험 삼아 시판용 페트병 홍차를 먹여 봤는데, 아무런 반응이 없더군요."
3601-61 = "1;미카;11;잠깐, 그렇다면 진짜로 심각한 상황 아니야?!\n#1;em;[?!]\n#1;ar\n#3;m5"
3601-62 = "3;세이아;01;맞아요. 한동안 일을 떠나서 휴식과 정신적인 케어가 필요하다는 진단이 내려졌습니다."
3601-63 = "1;미카;12;정신적인 케어…….\n#1;em;…"
3601-64 = "1;미카;08;한정판 디저트라도 구해 온다면 도움이 될까?\n#1;stiff"
3601-65 = "3;세이아;04;……회의록 보니까 그건 별 도움이 안 될 것 같던데요.\n#3;em;[땀]"
3601-66 = "3;세이아;99;일단 나기사는 트리니티를, 이 일터를 떠나는 게 최우선이에요."
3601-67 = "3;세이아;01;여기 계속 있으면 쉬어도 쉰다는 느낌이 들지 않을 테니까요."
3601-68 = "1;미카;12;으음, 트리니티 바깥에서 나기 쨩이 쉴 만한 곳을 찾아야 하는구나."
3601-69 = "3;세이아;01;예. 현재로선 그게 최선이에요."
3601-70 = "1;미카;08;으음…….\n#1;em;…\n#1;m3\n#3;dr"
3601-71 = "1;미카;12;트리니티 밖…… 나기 쨩이 좋아할 만한 곳……."
3601-72 = "1;미카;09;아!\n#1;em;[!]"
3601-74 = "3;세이아;01;미카?"
3601-75 = "1;미카;03;산해경으로 가자! \n#1;hophop\n#1;ar\n#3;m5"
3601-76 = "3;세이아;04;산해경 고급중학교로요……? 어째서죠?\n#3;em;[?]"
3601-77 = "1;미카;01;그곳 외곽에 유명한 홍차 공방이 있다고 들었거든!"
3601-78 = "1;미카;10;공방 견학을 신청하면 시음도 할 수 있고, 찻잎 블렌드도 체험할 수 있다고 들었어!\n#1;em;[반짝]"
3601-79 = "1;미카;03;나기 쨩은 홍차 좋아하니까 그곳에 가면 기운을 좀 차리지 않을까?\n#1;jump"
3601-80 = "3;세이아;02;……오랜만에 합리적인 발상을 떠올리네요, 미카."
3601-81 = "1;미카;04;응? 오랜만이라니?"
3601-82 = "1;미카;08;세이아 쨩 나를 평소에 어떻게 생각했길래…….\n#1;stiff\n#1;em;[세로선]"
3601-83 = "3;세이아;03;어쨌든, 좋은 아이디어예요."
3601-84 = "1;미카;03;그치 그치?\n#1;em;[반짝]\n#1;hophop"
3601-85 = "1;미카;12;그럼, 이동은 어떻게 할까나……."
3601-86 = "1;미카;08;나기 쨩은 많이 피로한 상태니까, 기차나 버스보다는 차가 좋을 것 같은데."
3601-87 = "1;미카;02;티파티 공용 차고에 있는 차를 쓸까?\n#1;em;[반응]"
3601-88 = "3;세이아;01;그곳의 차를 쓰려면 수행원이 동승해야 해요."
3601-89 = "3;세이아;99;그러면 결국 업무의 연장이라는 느낌을 받게 될 겁니다."
3601-90 = "1;미카;08;흐음, 그러면 어떻게…….\n#1;em;[속상함]"
3601-91 = "3;세이아;01;일단 여기서는 제 오토바이를 쓰도록 하죠."
3601-92 = "3;세이아;02;마침 사이드카도 장착되어 있어서, 세 명도 충분히 탈 수 있습니다."
3601-93 = "1;미카;03;우와, 그럼 세이아 쨩 운전하는 거 오랜만에 보겠네!\n#1;hophop"
3601-94 = "1;미카;02;좋아, 그럼 공방 투어는 내가 예약할게!"
3601-95 = "3;세이아;01;예, 부탁해요, 미카."
3601-96 = "1;미카;01;자 그럼, 나기 쨩 리프레쉬 투어…….\n#1;m3\n#3;dr\n#1;em;…"
3601-98 = "3;미카;10;시작이야!\n#3;closeup"
