[translation]
41040-1 = "Episode 4; Chief of Staff's Circumstances"
41040-2 = "Pleasure, Sensei."
41040-3 = "My name is Shiranui Kaya. Chief of defense of the General Student Council Administration Board."
41040-4 = "[s1] \"Administration Board...?\"\n[s2] \"Chief of defense...?\""
41040-5 = "You haven't heard of it?"
41040-6 = "You haven't heard of it?"
41040-7 = "Administrator Rin didn't explain about the board, did she?"
41040-8 = "[s] \"Nope.\""
41040-9 = "Ack. Truly a woman of few words."
41040-10 = "Well then, allow me to be your teacher, Sensei!"
41040-11 = "The General Student Council exists to process all of Kivotos' administrative tasks. This heady task is mainly handled through the Administration Board."
41040-12 = "The Administration Board is composed of eleven committees, such as the Treasury and the Regulatory Committee. Senior Administrator Rin, as you know, is in charge of the general office which oversees all of this."
41040-13 = "And I'm from the Defense Office! We're a hard-working group keeping the students and citizens safe from any bad guys who threaten Kivotos."
41040-14 = "[s] \"That must keep you pretty busy.\""
41040-15 = "Heehee, it would be remiss of me to claim that. It's not hard to give orders. Director Kanna and her staff are the ones who are running ragged to keep the peace."
41040-19 = "But you know, things have been unstable since the General Student Council President disappeared. Uncertainty, political unrest, the whole shebang."
41040-20 = "If it weren't for Schale stepping up to fill the hole, I certainly would be as busy as you think."
41040-21 = "So I'll have to thank you again for all you've done. Maybe over a cup of tea one day."
41040-22 = "[s3] \"You said you could help me with the SRT Academy students.\"\n[s4] \"Does the Defense Office manage SRT Academy, then?\""
41040-23 = "Well you see, the Valkyrie Police School students are under the Defense Office's command, but..."
41040-24 = "Well you see, the Valkyrie Police School students are under the Defense Office's command, but..."
41040-30 = "That entire explanation I just gave of our organization's structure? None of it applies to SRT Academy."
41040-32 = "Kivotos has many academy districts outside the General Student Council's jurisdictions, or clubs that privately manage security within their districts."
41040-33 = "For example, if a student breaks the law within the Gehenna district, then they're punished by the Gehenna Prefect Team's laws. Not ours."
41040-36 = "But say a student commits a crime in shared zones like D.U., where Schale is, then the Valkyrie students will step in. Easy enough, right?"
41040-37 = "But the problem occurs if a student commits a crime in one district, and then flees to another. Who, then, is allowed to arrest them? There are even cases of Student Councils from different academies helping to hide them away."
41040-38 = "We do try to send notices seeking cooperation in these types of situations, but, well, the schools don't always get along."
41040-43 = "Thus, we come to the creation of SRT Academy."
41040-44 = "SRT Academy was intended to be kind of like you, actually. An extrajudicial force that can take action against criminals regardless of where they are. Naturally, with the approval of the General Student Council president."
41040-49 = "In order to achieve that goal, only the most talented of students were selected. And they were armed with the best of the best equipment."
41040-52 = "And, to be sure, they quickly proved their effectiveness. The FOX Squad, a troop consisting of senior SRT students, successfully arrested Wakamo, known as the Fox of Calamity and an elusive criminal throughout Kivotos."
41040-53 = "And then... Poof. The General Student Council president disappeared."
41040-55 = "The president was gone, and so was the person responsible for SRT Academy and all its operations."
41040-56 = "I would like to say no one wanted to take charge of the highly-trained, incredibly well-armed students. But it was more like no one could."
41040-57 = "Our Defense Office was put in charge of the SRT students at first, but our...attempts were restricted because of their state-of-the-art equipment."
41040-58 = "And in the end, SRT Academy was reduced to an empty shell."
41040-59 = "[s] \"I don't feel like that's a good enough reason to close it down.\""
41040-60 = "That wasn't the only reason."
41040-61 = "Honestly, most executives wanted to maintain SRT Academy for when the General Student Council hopefully returned."
41040-62 = "I was among those."
41040-63 = "But... Well... You see, the FOX Squad members realized that their existence was being threatened. They weren't the type to stand idly by while we dismantled their way of living."
41040-64 = "[s5] \"The FOX Squad...\"\n[s6] \"The students you mentioned before?\""
41040-65 = "Yes. The top squad of SRT Academy that arrested Wakamo, the Fox of Calamity, and several other serious criminals."
41040-66 = "Yes. The top squad of SRT Academy that arrested Wakamo, the Fox of Calamity, and several other serious criminals."
41040-67 = "Until just last month, the SRT students were still armed with all of their advanced equipment."
41040-68 = "Catching wind of plans to shutter the school, the FOX Squad armed themselves and attacked the General Student Council—targeting a few of the loudest voices against them—before vanishing completely."
41040-69 = "Not only were some of the Sanctum Tower's facilities burned down, but many student council members were seriously injured and hospitalized."
41040-70 = "That was when the senior administrator stepped in. She ordered the full closure of SRT Academy and immediate retrieval of all weapons."
41040-74 = "But before we could do so, the RABBIT Squad ran away, taking the weapons with them."
41040-75 = "You won't find a single sympathetic soul in the General Student Council right now."
41040-76 = "Sensei, I hear you really care about all your students."
41040-77 = "Honestly, I'm at the end of my rope here. The RABBIT Squad members are going to have their academic records expunged. The remains of SRT Academy will be a handful of criminals and vagrants."
41040-78 = "But they're not vagrants. They're elite students who were handpicked for SRT Academy."
41040-79 = "To lose such talented students... It would be a loss to all of Kivotos."
41040-80 = "The end of my long monologue comes to this. Can you convince the RABBIT Squad members to transfer to Valkyrie?"
41040-81 = "If they agree to transfer, I'll convince the other chiefs of staff not to expel them."
41040-82 = "[s] \"I don't know if I can.\""
41040-83 = "I do know I'm asking no small task of you..."
41040-84 = "[s] \"It's not about convincing them.\""
41040-88 = "[ns] \"But I can't force them down a path they don't want.\""
41040-90 = "...I suppose the rumors about you were true, Sensei."
41040-91 = "All these students have fought tooth and nail to join SRT Academy because they believed in it. And as their teacher, you won't ask them to bend their ideals to suit the General Student Council's needs."
41040-92 = "Well, I suppose I never agreed with forcing them out either. How would I look the President in the eye when she comes back?"
41040-93 = "What a situation. Technically, the RABBIT Squad should be punished to the severest degree possible for their actions..."
41040-94 = "But rules are meant to be broken!"
41040-95 = "Ch-Chief of staff?"
41040-96 = "Oops, I'm not supposed to say things like that, aren't I?"
41040-97 = "Let's forget about that one, Director Kanna."
41040-98 = "Sensei, the Defense Office will gladly cooperate with you."
41040-99 = "I'd like to see the happy ending you envision. Please, guide the students to their dreams."
41040-100 = "Instead of the Disciplinary Council, I'll let you decide the RABBIT Squad's fate."
41040-101 = "Send them wherever they want to go, keep them in Schale. Whatever you want."
41040-102 = "Well, unless what you want is to reopen SRT Academy. My influence has its limits."
41040-103 = "[s] \"Are you sure about this?\""
41040-104 = "Haha! I've never been more sure."
41040-105 = "The Administration Board has faith in me, and I'll make it up to the other chiefs of staff one way or another."
41040-106 = "It's a small price to pay for our ultimate goal, right?"
41040-112 = "Please guide SRT Academy to whichever future you believe in, Sensei."
41040-114 = "Next Episode;Unresolved Distrust"
