[translation]
41050-1 = "Episode 5;Unresolved Distrust"
41050-2 = "Valkyrie Police School Main Building Lobby"
41050-5 = ""
41050-8 = "Everyone... How are you doing?"
41050-9 = "I didn't know you were here, Miyako."
41050-10 = "Miyako... Thank goodness."
41050-12 = "The gang's all here. Looks like they finally ran out of questions."
41050-13 = "They ran outta lollipops so I'm pretty much done with this place."
41050-14 = "Moe, they're hardly going to just let us walk out of here."
41050-15 = "The fact that we're all here together means they've decided our sentencing."
41050-16 = "And after everything we've done... I expect our academic records will be expunged."
41050-17 = "Oh, boo-hoo. SRT Academy went ka-boom, so it doesn't matter what they do."
41050-19 = "B-But, what if it's even scarier than getting kicked out of school?"
41050-20 = "Hm. Well, I guess."
41050-21 = "Watch out, Miyu. They're gonna drag us to an underground facility and do weird, illegal experiments on us. You'll be first since you're the smallest."
41050-22 = "M-M-Me?!"
41050-23 = "...It's over for us."
41050-24 = ""
41050-26 = ""
41050-28 = ""
41050-29 = "I'm sorry. If I had been better..."
41050-30 = "You all wouldn't be in this situation."
41050-31 = "Why are you apologizing to us?"
41050-32 = "You think we would ever do something we didn't want to, even if you were the squad leader?"
41050-33 = "Don't take this the wrong way. Or do, actually. But Miyako, you're not leader of anything anymore now that the academy's gone."
41050-34 = "Don't act all high and mighty. We had no expectations of you from the beginning."
41050-35 = "I... I just..."
41050-36 = "[s] \"Hello, everyone.\""
41050-37 = "This weirdo?!"
41050-38 = "The Schale Sensei?"
41050-39 = "Eeeek!"
41050-40 = "[s] \"I guess I'm not very welcome here.\""
41050-42 = "You're still here, Sensei?"
41050-43 = "Do you have unfinished business at Valkyrie?"
41050-44 = "...Are we the unfinished business?"
41050-45 = "[s] \"Yep. I'm here to deliver the Administration Board's decision.\""
41050-47 = "...N-Noooo!"
41050-48 = "Spit it out. We'll take whatever you throw at us."
41050-49 = "*gulp*"
41050-50 = ""
41050-53 = "[ns1] \"The RABBIT Squad is free.\"\n[ns2] \"You're free to go.\""
41050-56 = "Huh?"
41050-57 = "For once, I'm speechless."
41050-58 = "Does this mean we can go back to SRT Academy?"
41050-59 = "[s] \"Free to go anywhere except SRT.\""
41050-60 = "I had my hopes up for a moment."
41050-63 = ""
41050-64 = "We must have been placed in Schale's charge since Sensei was the one to successfully suppress us."
41050-65 = "I understand the situation now."
41050-66 = "What is your order, Sensei?"
41050-67 = "[s] \"What do you want your order to be?\""
41050-68 = "I don't think that's how that works."
41050-69 = "I-I just wanna go back home..."
41050-70 = "I want a fluffy bed and a shower. My social battery is spent after all that interrogation nonsense."
41050-71 = "[s] \"Why don't you rest at the Schale dorms for a while?\""
41050-72 = "...Suspicious."
41050-73 = "What respectable teacher invites female students to their dorms? Hmm?"
41050-75 = "I find it hard to trust you as well."
41050-76 = "You probably h-hate us because of what happened..."
41050-77 = "You've come up with an evil plan, haven't you?"
41050-78 = "I've heard rumors that Schale is ridden with wiretapping devices."
41050-79 = "A-Are you going to blackmail us?"
41050-80 = "Heehee. Sensei wants to use us for their shameful desires."
41050-81 = "[s3] \"Why would I do any of that?! I'm a teacher!\"\n[s4] \"What kind of a person do you think I am?!\""
41050-84 = "We can't accept your offer."
41050-85 = "Our mission from the beginning has been to resist the General Student Council's decision to shut down SRT Academy. Seeking comfort in the Schale dorms would negate all our actions."
41050-87 = "And where at Schale would we continue our regular training?"
41050-88 = "Resting and relaxing in the dorms isn't conducive to the rigor and discipline we believe in at SRT."
41050-89 = "Are you gonna let me blow things up at Schale? Huh?"
41050-90 = "I-I still think Sensei is scary..."
41050-91 = "[s] \"Why don't you camp out in the park, then?\""
41050-93 = "Kousagi Park? Where we had our protest?"
41050-94 = "...That actually isn't a bad idea. The park reminds me of our field warfare training grounds. It's sort of comforting."
41050-95 = "And all my toys are still there!"
41050-96 = "I g-guess it's the closest to home we have..."
41050-98 = "The optics aren't great if we do return there, however. It'll look as if we're being allowed to continue our protest."
41050-99 = "Are you sure you're okay with that?"
41050-100 = "[s5] \"Sure. I'll pack your bags.\"\n[s6] \"When's the move?\""
41050-101 = "We're not your usual powerless students to protect, Sensei."
41050-102 = "We're not your usual powerless students to protect, Sensei."
41050-103 = "We still don't trust you, and we still don't need your help."
41050-104 = "No amount of kind words or gestures will change our minds."
41050-105 = "[s7] \"I've known that from the start.\"\n[s8] \"I'm really just here to help.\""
41050-106 = ""
41050-107 = ""
41050-109 = ""
41050-110 = "...You confound me."
41050-111 = "Until next time, then."
41050-112 = "Next time, you'll be our enemy!"
41050-113 = "Haven't we been from the beginning?!"
41050-114 = ""
41050-116 = ""
41050-120 = "M-Miyako! Wait for me!"
41050-122 = "Next Episode;Food Delivery Operation"
