[translation]
42040-1 = "ตอนที่ 4;การพบกันโดยบังเอิญ"
42040-3 = "... นี่ RABBIT 1 ขณะนี้เวลา 16:25 น."
42040-4 = "ฉันกำลังติดตามตำแหน่งของผู้ต้องสงสัยที่บุกรุกเข้าจุดเซียร์ร่าจากสัญญาณ GPS ที่ RABBIT 3 แจ้งมา ตอนนี้เข้ามาถึงพื้นที่เป้าหมายแล้วค่ะ"
42040-5 = "ขณะนี้จุดจอดโรมิโอมีฝนตกลงมา ทำให้ทัศนวิสัยจะใช้ได้แค่ในรัศมี 500 เมตรเท่านั้นค่ะ ทุกคนอย่าลืมพิจารณาถึงข้อนี้กันด้วยนะคะ"
42040-6 = "นะ... นี่ RABBIT 4... ไม่รู้ว่าเป็นเพราะอากาศหรือเปล่า แต่ตอนนี้ไม่มีใครเดินผ่านแถวนี้เลย..."
42040-7 = "นอกจากนี้ก็ไม่พบหน่วยรบคนไหนถูกซุ่มโจมตี... ฉันพร้อมสนับสนุนการลอบยิงจากจุดนี้ ไม่ว่าจะให้ยิงไปทางไหนก็ตาม"
42040-8 = "รับทราบ RABBIT 2 ช่วยรีบรายงานด้วยค่ะ"
42040-9 = "นี่ RABBIT 2 ฉันกำลังทำลายระบบวงจรปิดภายนอกของอาคาร ถ้าทำสำเร็จ เซ็นเซอร์เตือนของอาคาร#nน่าจะไม่ทำงานไปสักพักเลย"
42040-10 = "แต่ว่า......"
42040-11 = "มีปัญหาอะไรหรือเปล่าคะ RABBIT 2?"
42040-12 = "ไม่หรอก ไม่ได้มีปัญหาอะไร... แต่อาคารนี้มันคุ้นตามากๆ น่ะ"
42040-14 = "หืม? ไม่มีบันทึกว่าเราเคยมาทำภารกิจแถวๆ นี้เลยนะ จำสลับกับที่อื่นหรือเปล่า?"
42040-15 = "ฉันก็รู้น่าว่าไม่เคยมา ฉันแค่จะบอกว่า... โครงสร้างของอาคารนี้มันคุ้นตาแปลกๆ น่ะ"
42040-16 = "อืม โครงสร้างของที่นี่มัน... คล้ายๆ กับโครงสร้างสนามฝึกต่อสู้ในอาคารของ SRT เลย มันมีการจัดวางในอาคารเหมือนเขาวงกต 3 ชั้นที่มีทางเข้า 3 แห่ง..."
42040-17 = "จริงด้วยแฮะ ถ้าเป็นการฝึกซ้อมเหมือนแต่ก่อน ป่านนี้คงได้เกิดการปะทะไปแล้วเนอะ ฮุฮุฮุ..."
42040-19 = "แต่ว่าเราก็ไม่มีปฏิกิริยาอะไรเป็นพิเศษเลย... ตรงกันข้ามยังรู้สึกสบายใจในพื้นที่แบบนี้เพราะเคยฝึก#nซ้อมมาแล้วหลายต่อหลายครั้งด้วย"
42040-20 = "จริงด้วยค่ะ พอเป็นสถานที่ที่คุ้นเคย ก็น่าจะคาดเดาสถานการณ์ที่ไม่คาดคิดได้ง่ายหน่อยนะคะ"
42040-21 = "แต่ปกติแล้วอาคารแบบนี้จะมีข้อได้เปรียบในการป้องกันมากกว่า ตอนที่มีการต่อสู้จำลองในโรงเรียน สถิติการชนะเป็นของฝ่ายที่ป้องกันได้ดีกว่า ฉันก็เลยกังวลนิดหน่อยน่ะ..."
42040-22 = "ทำไมถึงกลัวขนาดนั้นล่ะซากิ เราคือ SRT นะ"
42040-23 = "ถึงศัตรูจะโผล่มาพร้อมกับอาวุธที่เราไม่เคยเห็น แต่เราก็แค่สู้กลับไปด้วยพลังที่เรามีก็พอแล้วนี่ ฮุฮุ..."
42040-24 = "คงงั้นแหละเนอะ? ต่อให้เป็นพวกหัวกะทิจาก PMC แต่ถ้าต้องประจันหน้ากับเราก็คงสู้ไม่ได้หรอก..."
42040-25 = "ฉันจะช่วย... สนับสนุนทางด้านหลังให้เอง"
42040-26 = "ถ้าอย่างนั้นจะเริ่มบุกกันแล้วนะคะ RABBIT 2 ไปที่ตำแหน่งได้"
42040-27 = ""
42040-29 = ""
42040-31 = "จะเจาะละนะ"
42040-32 = ""
42040-34 = ""
42040-36 = "ได้ทางเข้าแล้ว!"
42040-37 = "RABBIT 1 เข้าไปในอาคาร!"
42040-40 = ""
42040-41 = "เคลียร์โซน A เรียบร้อย"
42040-42 = "โซน B เคลียร์!"
42040-43 = "ไปต่อโซน C ทันที!"
42040-44 = ""
42040-46 = ""
42040-47 = "(... แปลกจังเลยนะคะ เราบุกเข้ามาลึกขนาดนี้แล้วแต่ยังไม่มีใครออกมาตอบโต้อีก พวกนั้นเฝ้าระวังเรา#nอยู่จริงไหมคะเนี่ย?)"
42040-48 = "(ไม่มีการเคลื่อนไหวที่สะดุดตาหรือกับดักอะไรแท้ๆ แต่เหมือนเรากำลังพลาดอะไรสักอย่างเลย...)"
42040-49 = "นี่ RABBIT 2 เรียก RABBIT 1 ข้างหน้านี้มีสิ่งกีดขวางจนเข้าไปไม่ได้เลย ทำยังไงดีล่ะ? ให้ฝ่าไปเลยมั้ย?"
42040-50 = ""
42040-52 = ""
42040-53 = "ไม่ค่ะ ขืนทำอะไรเสียงดังเข้า ศัตรูจะรู้ว่าเราอยู่ตำแหน่งนี้นะคะ ทำแบบนี้เสี่ยงเปล่าๆ เราอ้อมไปกันเถอะค่ะ"
42040-54 = "หมายถึงทางโถงกลางที่เปิดโล่งใช่ไหม... เข้าใจแล้ว"
42040-55 = "ทำปฏิบัติการต่อเลย—"
42040-56 = ""
42040-59 = "อึก...!"
42040-60 = ""
42040-62 = ""
42040-63 = "เสียงปืนเมื่อกี้มัน...?"
42040-64 = "RABBIT 2 รายงานด้วยค่ะ RABBIT 2!"
42040-65 = "สัญญาณขาดไปเหรอ...? ติดต่อไม่ได้เลย..."
42040-66 = "RABBIT 4 ขอข้อมูลสังเกตการณ์ด้วยค่ะ RABBIT 3 ช่วยตรวจสอบข้อมูล GPS ด้วยค่ะ!"
42040-67 = ""
42040-70 = "เราถูก... กวนสัญญาณเหรอคะ?"
42040-71 = "(จากสถานการณ์แล้ว เราไม่น่าจะขอความช่วยเหลือจากทั้ง RABBIT 2 และสมาชิกคนอื่นได้เลย)"
42040-72 = "(เปิดการรบกวนสัญญาณในตอนที่จู่โจมด้านหน้า เพื่อให้สมาชิกแต่ละคนติดต่อกันไม่ได้สินะ...)"
42040-73 = "(ถึงจะดูเหมือนง่าย แต่การจัดการกับศัตรูพร้อมกันแบบที่ติดต่อกันไม่ได้ต้องใช้ทักษะการทำงานเป็น#nทีมสูงมาก... ถ้าเป็นทหารรับจ้างหรือนักเรียนธรรมดาก็ไม่สามารถทำได้เลย)"
42040-74 = "(ก่อนอื่นคงต้องไปช่วย RABBIT 2 ก่อน...)"
42040-75 = ""
42040-77 = ""
42040-78 = ""
42040-79 = ""
42040-81 = ""
42040-83 = "(ซุ่มโจมตีเหรอ? เข้ามาถึงระยะนี้เลย...?)"
42040-84 = ""
42040-85 = "........."
42040-86 = ""
42040-88 = ""
42040-97 = "(อึก... ทางเดินก็แคบมากจนอาวุธหลักเกะกะไปหมด...)"
42040-98 = "(เราไม่คุ้นชินกับสถานการณ์ที่ต้องต่อสู้ระยะประชิดด้วย แต่ก็คงช่วยไม่ได้...)"
42040-99 = ""
42040-101 = ""
42040-102 = "(งั้นก็ต้องทำให้ฝ่ายตรงข้ามเสียจุดศูนย์ถ่วงเสียก่อน—)"
42040-103 = "...... ฟ็อกซ์ทรอต"
42040-104 = "(จากระยะนี้... อย่าบอกนะว่าใช้ระเบิดแสง)"
42040-105 = ""
42040-111 = ""
42040-112 = ""
42040-113 = "1.5 วินาที... ถึงจะเป็นเพราะความเครียดจากการต่อสู้ที่เกิดจากเสียงดังและแสงวาบก็เถอะ"
42040-114 = "จากคู่มือ CQB แล้ว การแทรกเข้าไปในระยะยิงเป็นการตัดสินใจที่ไม่เลว แต่ในสถานการณ์นั้นแล้ว การใช้หัวปะทะไปแรงๆ เลยน่าจะดีกว่าการใช้มือดึงนะ"
42040-115 = "อึก...!"
42040-116 = "อย่าฝืนดึงมือออกเลย ถ้าพลาดขึ้นมา แขนเธอหักได้เลยนะ"
42040-117 = "คุณคือใครคะ...? ดูไม่เหมือนทหารรับจ้างหรือนายหน้าทั่วไปเลย..."
42040-118 = "... สำคัญด้วยเหรอว่าฝ่ายตรงข้ามคือใคร? ถ้าได้ทำปฏิบัติการ ก็ต้องคิดถึงกรณีที่แย่ที่สุดไว้เสมอสิ"
42040-119 = "ต่อให้ตัวเองจะเป็นนักสู้เจนสนามที่มีอาวุธที่ยอดเยี่ยม แต่พออยู่ในสนามรบก็อาจจะถูกสยบได้ด้วย#nกระสุนเพียงนัดเดียวก็ได้"
42040-120 = "หน่วยรบพิเศษที่เก๋าเกม ต้องทำตัวเหมือนคนขี้ขลาดมากกว่านักรบที่กล้าหาญน่ะ"
42040-121 = "เสียงนี้มัน..."
42040-122 = "ไม่ได้เจอกันนานเลยนะ หัวหน้ากองสึคิยูกิ"
42040-123 = ""
42040-125 = ""
42040-127 = "... ดีจังเลยนะที่ได้เจอกันอีกครั้งแบบนี้"
42040-128 = "รุ่นพี่ยูกิโนะ...?!"
42040-130 = "ตอนต่อไป;เงาของรุ่นพี่"
