[translation]
42070-1 = "第7話;政變"
42070-2 = "（發表緊急聲明數小時前──聯邦學生會會議室）"
42070-4 = ""
42070-5 = "……下一個議題為決定凱薩公司及其經營團隊在災難情況下趁隙引發內亂、#n試圖奪取聯邦學生會的權限，其懲處程度的案件。"
42070-6 = "照理來說，本案是行政委員會恢復正常的當下就該最優先處理的……"
42070-7 = "……然而由於上次的事件，D.U.許多通訊和物流設施遭到破壞，#n為了市民的安全和便利而優先進行了D.U.的修復作業，本案的討論就暫時被保留。"
42070-8 = ""
42070-10 = ""
42070-11 = "……感謝說明。"
42070-12 = "和剛才說明的一樣，凱薩公司在上次事件時率領士兵襲擊了聯邦學生會。#n試圖奪取聖所之塔的權限，並將其能力運用在他們挖掘到的超古代兵器上。"
42070-13 = "所幸，多虧夏萊的老師和各自治區學生會成員的協助，得以阻止局勢惡化……"
42070-14 = "……要是沒能阻止他們，不只是聯邦學生會，連奇普托斯本身都可能會崩潰。"
42070-15 = "我認為造成此一情況的原因，#n是由於凱薩公司是從國防到物流都能控制的超巨型企業。"
42070-16 = "為了避免類似情況再次發生，應當對凱薩公司和其經營團隊進行最高等級的懲處。"
42070-17 = ""
42070-20 = "請等一下。#n雖然凱薩公司動員士兵、以武力占領聯邦學生會是事實……"
42070-21 = "但是他們之所以能夠輕易進入聖所之塔，#n不都是因為琳行政官擅自召開緊急對策委員會，使聯邦學生會陷入混亂嗎？"
42070-23 = "琳，琳前輩確實召開了緊急對策委員會沒錯，#n但要說那是直接的原因……"
42070-24 = "那麼，對於琳行政官搭乘了凱薩公司挖掘的超古代兵器的證言又該怎麼解釋？"
42070-25 = "……難道沒有琳行政官和凱薩公司串通的可能性嗎？"
42070-26 = "怎，怎麼能胡說八道……"
42070-27 = "……懷疑身為當事人的我，這點我完全可以理解。"
42070-28 = "如果對這次事件的決議案通過，開始調查凱薩公司的話，我承諾將會誠實配合。"
42070-30 = "（竊竊私語）我說碧前輩……這個會議還沒有要結束嗎？#n我們連午餐都還沒吃啊？"
42070-31 = "還沒哦，議題大約還剩下3個左右吧。"
42070-32 = "從會議開始到現在經過8小時32分15秒……#n這種程度的馬拉松會議，在防衛室是家常便飯了吧？"
42070-33 = "午餐就吃剛才發的飯糰忍耐一下吧。"
42070-35 = "我有拿到飯糰嗎……？"
42070-36 = ""
42070-37 = "再說了，把超越法規的權限交給夏萊老師的，不也是琳行政官嗎？"
42070-38 = "就算聯邦學生會長留下的筆記上寫著「那個」內容，#n我們也無法確認那個筆記的真偽。"
42070-39 = "……留下筆記的確實是聯邦學生會長沒錯。"
42070-40 = "必要的話，要進行筆跡鑑定辨別真偽也──"
42070-41 = "首席行政官，任何事情都有先後順序！"
42070-42 = "就算是你是聯邦學生會長代理，我們也無法容忍無視行政委員會決定的行為！"
42070-43 = "我一直都是依照流程和規定來解決問題……"
42070-44 = ""
42070-45 = "（竊竊私語）我問你哦，李。#n你有拿到飯糰嗎？"
42070-46 = "呵啊……我好睏，才不想吃什麼飯糰呢～"
42070-47 = "不是，我說的不是你的，而是我的飯糰……"
42070-48 = ""
42070-49 = "況且凱薩公司是奇普托斯首屈一指的大企業。"
42070-50 = "凱薩工業、凱薩建設、凱薩超商……#n要是這些企業停止運作，奇普托斯的失業人口將會暴增。"
42070-51 = "如此一來勢必會引發前所未有的混亂。#n這個責任又要由誰來負責呢？"
42070-52 = "……考慮到凱薩公司的影響力，只要求適當的罰金作結似乎也……"
42070-53 = ""
42070-54 = "那個，桃香……"
42070-55 = "就算用那種眼神看我，這包明太子洋芋片也不會分給你的哦？"
42070-56 = "要是肚子餓的話，吃發的飯糰不就好了。（喀滋喀滋）"
42070-58 = "不是，所以說我根本就沒拿到飯糰啊！？"
42070-59 = ""
42070-61 = ""
42070-62 = "……看來似乎難以繼續討論下去了呢。"
42070-63 = "首席行政官。今天先到此結束，之後再重新開始討論如何？#n我想大家應該也需要一些思考的時間。"
42070-64 = "……我明白了。"
42070-65 = "今天就先散會吧。#n剩下的議題明天再繼續。"
42070-66 = "大家辛苦了。"
42070-67 = ""
42070-70 = ""
42070-73 = ""
42070-74 = "呼……"
42070-75 = "雖然有預想過……但溝通起來比想像中還困難呢。"
42070-76 = ""
42070-79 = "辛苦了，首席行政官。"
42070-80 = "啊，防衛室長。"
42070-81 = "防衛室長也辛苦了。"
42070-82 = "特地來找我就代表……找我有事嗎？"
42070-83 = "不，只是想閒聊一下而已。#n話說剛才真的辛苦您了呢……"
42070-84 = "別這麼說。"
42070-85 = "……各位幹部們真的很令人困擾。"
42070-86 = "明明是應該好好議論的場合，大家卻都在各說各話……"
42070-87 = "必須考慮所有人意見的首席行政官有多麼煩惱，我心裡也明白。"
42070-88 = "這也沒辦法。事情會演變成這樣，我也有責任。"
42070-89 = "只能一步步地花時間說服幹部們了吧。"
42070-90 = "……是否真的有必要徵求幹部們的同意呢？"
42070-91 = "您雖然是統領室的首席行政官，但同時也是聯邦學生會長的代理。"
42070-93 = "如果以聯邦學生會長代理的權威來命令幹部們，不就能更輕鬆地處理事情了嗎？"
42070-94 = "權威啊……"
42070-95 = "那是像加了毒藥的聖杯一樣的東西哦，防衛室長。"
42070-96 = "確實可能是張便利的王牌沒錯，但越是使用越會招致自身的毀滅。"
42070-97 = "即使意見與我不同，我也不應該用權威壓制他人。"
42070-98 = "何況我也……沒有將代理的工作進行得十全十美的自信……"
42070-99 = "唉……"
42070-101 = "……你果然沒有擔任聯邦學生會長代理的資格。"
42070-102 = ""
42070-105 = "…………"
42070-106 = "……防衛室長，這是在做什麼？"
42070-109 = "琳，我以前就覺得你很礙眼了。"
42070-110 = "明明沒有半點能力，卻獨佔了聯邦學生會長的信賴……"
42070-111 = "在成為聯邦學生會長代理後，居然仍舊試圖集合周圍的意見來推行事務……"
42070-112 = "那種像是愚民政治的作法沒辦法解決任何事情。"
42070-113 = "奇普托斯應該由[ruby=聯邦學生會長]「超人」[/ruby]來指揮才對。"
42070-114 = "……聯邦學生會長目前處於失蹤狀態哦，不知火室長。"
42070-115 = "並且，守住他的容身之處就是首席行政官的職責。"
42070-117 = "呵呵，真的是這樣嗎。"
42070-118 = "其實那天，我在夏萊的地下找到了一個有趣的東西。"
42070-119 = ""
42070-120 = "那就是──被隱藏起來的聯邦學生會長的信。"
42070-121 = "聯邦學生會長的信……？"
42070-122 = "沒錯。根據這封信的內容，聯邦學生會長在自己出事時，#n想委託執行代理工作的似乎並非行政官，而是防衛室長哦。"
42070-123 = "換句話說，應該成為聯邦學生會長代理的人物不[ruby=七神琳]是你，[/ruby][ruby=不知火香耶]而是我才對[/ruby]。"
42070-124 = "那是，什麼意思……"
42070-125 = "……話又說回來，如此重要的書信為何會被藏在夏萊的地下室呢？"
42070-126 = "聯邦學生會長失蹤時，擁有出入夏萊大樓權限的就只有七神琳，你一個人而已。"
42070-127 = "此外，隱藏這封信最能得利的人──也同樣是你。"
42070-128 = "……你有證據證明那真的是聯邦學生會長親自寫下的嗎？"
42070-129 = "我要求進行筆跡鑑定。#n如果那真的是聯邦學生會長親筆所寫，簽名也同樣──"
42070-130 = "當然，確認真偽固然重要。#n就像留在聯邦學生會長室裡的那份筆記一樣。"
42070-131 = "但是……如今的聯邦學生會裡，會相信你的人究竟還剩多少呢？"
42070-132 = "……難道。"
42070-133 = ""
42070-136 = ""
42070-137 = "七神琳行政官，我以藏匿公文及濫用職權的嫌疑緊急逮捕你。"
42070-138 = "依據聯邦學生會幹部規定第78條，#n聯邦學生會長代理的職務將在調查結束前遭到停止。"
42070-139 = "信件的真偽姑且不論──#n如今眼下需要一名新的聯邦學生會長代理呢。"
42070-140 = "……原來這一切都是你的計劃。"
42070-141 = "等到聯邦學生會長回來，一切的真相都會公諸於世的。"
42070-142 = "呵呵，如此一來反而是放任事情發展至此的你會遭到責罵不是嗎？"
42070-143 = "…………"
42070-144 = "那麼各位，請鄭重送首席行政官一程吧。#n啊啊，之後也請繼續進行監視哦。"
42070-145 = "是，防衛室長大人！"
42070-146 = ""
42070-148 = ""
42070-151 = ""
42070-154 = "……人力資源室長。#n目前在聯邦學生會大樓附近進行的示威管制還順利嗎？"
42070-155 = "啊啊，防衛室長，我正想聯絡你呢。"
42070-156 = "目前示威相當順利哦。我以公共設施的事故與交通室和調停室的消極處理為由募集了示威隊伍，結果募到了大量的人員。"
42070-157 = "本來還打算出錢雇用他們的，#n但不知什麼原因，他們只說示威交給他們就擅自活動了起來……"
42070-158 = "不愧是我母校的學生。#n真是機靈啊。"
42070-159 = "而且防衛室長傳達的情報也幫了不少忙。"
42070-160 = "不過其中有不少是不在事故現場就難以獲得的情報……究竟是怎麼得到的呢？"
42070-161 = "……那個情報是示威所必要的嗎？"
42070-162 = "這個嘛……倒也不能這麼說……"
42070-163 = "算了，總之有那麼多的學生們在大樓前示威，#n就算是對派系鬥爭不感興趣的中立派幹部，對琳行政官的印象也會惡化的吧。"
42070-164 = "要是舉行不信任表決，我想很多人都會毫無異議地投下贊成票的……"
42070-165 = "辛苦了。#n麻煩繼續進行示威的管制。"
42070-166 = ""
42070-169 = ""
42070-171 = "灰音，要發送給體育協會的公文怎麼樣了？"
42070-172 = "按照你的指示，會議一結束就立刻送過去囉！"
42070-173 = ""
42070-175 = ""
42070-176 = "啊……不，嚴格來說並不是馬上……"
42070-177 = "因為我實在太餓了，所以在會議結束之後先去食堂吃了點東西……"
42070-178 = "……不必報告那些瑣碎的事情。"
42070-179 = "所以體育界的反應怎麼樣？"
42070-180 = "聽到琳行政官為了自身利益而偽造公文之後，大家似乎都很失望。#n畢竟我們都對不正當的行為和隱蔽情報很嚴格。"
42070-181 = "話說上次FOX小隊之所以會襲擊聯邦學生會也是琳行政官的指使，這是真的嗎？#n所以才會急著要關閉SRT特殊學園……"
42070-182 = "沒錯哦。#n如果沒別的事──"
42070-183 = "那些狐狸真是毫不留情啊。#n我一打算抵抗就馬上被用關節技固定了哦！SRT特殊學園連關節技都有教嗎？"
42070-184 = "…………"
42070-185 = "嗚嗚，要是那時候投降就好了……#n害我的肩膀到現在還在痛……"
42070-186 = "……灰音，我掛電話囉。"
42070-187 = "啊，先等等。剛剛到底是誰把我的飯糰──"
42070-188 = ""
42070-191 = "看這個情況，應該不必擔心不信任表決會被否決了吧。"
42070-192 = "那麼最後……"
42070-193 = ""
42070-195 = ""
42070-197 = "……禮賓隊？"
42070-198 = "是，沒錯……立刻準備發表緊急聲明。"
42070-199 = "也請盡快聯絡克洛盧斯頻道和各自治區的電視台。#n畢竟準備攝影器材也是需要時間的。"
42070-200 = "……不信任表決很快就會結束吧。#n結果就跟已經確定了一樣。"
42070-201 = "好的，就這樣進行。"
42070-202 = "……啊，還有，預計將有貴客來訪，請做好接待準備。"
42070-203 = "沒錯，名字是──"
42070-206 = "──[USERNAME]老師。"
42070-208 = "下一話;新任代理"
