[translation]
42170-1 = "ตอนที่ 17;ความพยายามที่สูญเปล่า"
42170-2 = "โคะอุซางิ การ์เด้น"
42170-6 = "(วันต่อมา คุณครูออกมาเก็บกวาดของที่กองทหาร RABBIT ทิ้งไว้ที่สวนสาธารณะตั้งแต่เช้า...)"
42170-7 = ""
42170-11 = "พอเจ้าของไม่อยู่ ก็ถือโอกาสเข้ามาค้นข้าวของในค่ายของเด็กนักเรียนผู้หญิงเลยนะคะ..."
42170-12 = "คุณครู [USERNAME] เป็นผู้ใหญ่ที่แปลกจริงๆ ด้วยสินะคะ"
42170-13 = ""
42170-18 = ""
42170-19 = "[ns] \"กลับมาแล้วเหรอ มิยาโกะ\""
42170-20 = "ค่ะ"
42170-21 = ""
42170-23 = ""
42170-24 = ""
42170-25 = "RABBIT 1 กลับมาที่ค่าย RABBIT อย่างปลอดภัยตามที่รายงานไว้แล้วค่ะ"
42170-26 = "[s] \"แล้วสมาชิกคนอื่นไม่ได้มาด้วยเหรอ?\""
42170-27 = ""
42170-29 = ""
42170-30 = "ฉันคงไม่อาจขอร้องสมาชิกคนอื่นได้หรอกค่ะ..."
42170-31 = "ฉันสละตำแหน่งหัวหน้ากองด้วยการตัดสินใจของฉันเอง แต่ตอนนี้จะให้ฉันขอให้ทุกคนทิ้งชีวิตอันสุข#nสบายและกลับมาที่ค่ายอีกรอบเพราะอุดมการณ์ของฉันเหรอคะ แบบนั้นมันรู้สึกผิดเกินไปค่ะ"
42170-32 = "... สมาชิกทุกคนหลักแหลมกว่าฉันค่ะ ต่อให้ไม่มีคุณครูช่วย พวกเธอก็ต้องหาอุดมการณ์ที่แน่วแน่ของตัวเองได้ค่ะ"
42170-33 = "แต่ว่าก่อนหน้านั้น"
42170-34 = "ฉันมีเรื่องอยากปรึกษาคุณครูค่ะ"
42170-36 = "(... คุณครูได้ฟังแผนการร้ายขององค์การนักเรียนกับกองทหาร FOX จากมิยาโกะ)"
42170-39 = "[ns1] \"พวกนั้นจะระเบิดชั้นใต้ดินของสถานีเหรอ?\"\n[ns2] \"... นั่นมันก่อการร้ายเลยนะ?!\""
42170-42 = "ชู่ว คุณครู พูดเสียงดังไปแล้วค่ะ"
42170-43 = "นี่เป็นปฏิบัติการลับสุดยอดที่กรรมการในองค์การนักเรียนก็รู้แค่บางคนเท่านั้น ถ้าชาวเมืองมาได้ยินเข้า#nละก็ ต้องเกิดเรื่องยุ่งเหยิงขึ้นแน่นอนค่ะ"
42170-44 = "[ns] \"ขอโทษที พอดีครูตกใจไปหน่อย...\""
42170-46 = "[ns] \"หัวรบแรงดันความร้อนนั่นเป็นระเบิดที่ร้ายแรงมากเลยเหรอ?\""
42170-47 = "ค่ะ ระเบิดแรงดันความร้อนเป็นระเบิดพิเศษที่พัฒนาขึ้นเพื่อซุ่มโจมตีขีปนาวุธโตชก้า#nหรือไม่ก็สนามเพลาะที่ใช้อาวุธทั่วไปโจมตีได้ยากค่ะ"
42170-48 = "ทันทีที่ถูกยิงออกไป มันจะเผาไหม้ออกซิเจนทั้งหมดที่อยู่ในรัศมีของการระเบิดในพริบตา จากนั้นจะเกิดเปลวไฟและคลื่นกระแทกที่ทรงพลังค่ะ"
42170-49 = "แค่ใช้ระเบิดแรงดันความร้อนบนพื้นดินก็มีอานุภาพมากพอแล้ว แต่ยิ่งใช้ในชั้นใต้ดินแบบปิดก็จะยิ่งมี#nประสิทธิภาพมากขึ้นเพราะคุณสมบัติการระเหยไปตามละอองที่กระจายอยู่ภายในพื้นที่ปิดค่ะ"
42170-50 = "ไม่เพียงทุกคนในรัศมีที่จะถูกกวาดไปด้วยแรงระเบิดนะคะ แต่คลื่นกระแทกจะทำให้อาคารรอบๆ พังทลายลงเหมือนกับเกิดแผ่นดินไหวรุนแรงเลยค่ะ"
42170-51 = "หากข้อมูลของโปรเจกต์ <A.N.T.I.O.C.H.> ที่เปิดเผยออกมาเป็นความจริง... ขอบเขตความเสียหาย#nน่าจะกินรัศมี 5 กม. และในนั้นก็จะมีโคะอุซางิ ทาวน์ด้วยค่ะ"
42170-52 = "[s] \"ทำไมถึงมีระเบิดแบบนี้ได้นะ...\""
42170-53 = "... ทางนั้นคงตั้งใจจะสร้างความหวาดกลัวน่ะค่ะ"
42170-54 = ""
42170-56 = "ถึงแม้รุ่นพี่ยูกิโนะจะบอกว่านี่เป็นปฏิบัติการเพื่อฟื้นฟูสถาบัน SRT ก็ตาม แต่ว่าเป้าหมายสุดท้ายของ#nปฏิบัติการนี้คือการประกาศอย่างเป็นทางการว่าองค์การนักเรียนมีกำลังที่แข็งแกร่งค่ะ"
42170-57 = "ถ้าได้เห็นรักษาการแทนประธานองค์การนักเรียนคนใหม่ใช้อาวุธที่ทรงพลังอย่างไม่ลังเลแล้วละก็ กลุ่มกองกำลังที่ไม่พอใจนโยบายของเธอก็คงมุทะลุมาต่อต้านกันลำบากค่ะ"
42170-59 = "... ไม่ว่าจะด้วยจุดประสงค์อะไรก็ตาม แต่หากปฏิบัติการนี้ลุล่วงขึ้นมา มันก็จะเกิดความเสียหายที่ไม่#nอาจหาทางแก้ไขได้ค่ะ"
42170-60 = "และฉันก็อยากจะหยุดปฏิบัติการนี้ ก่อนที่พวกรุ่นพี่จะเดินก้าวข้ามแม่น้ำที่ไม่มีทางหวนกลับมาได้ค่ะ"
42170-61 = "ครั้งหนึ่งรุ่นพี่เคยเปิดทางให้เราเดินหน้าต่อไปได้ แต่ว่าคราวนี้ฉันอยากจะป้องกันเส้นทางที่พวกรุ่นพี่จะ#nกลับมาให้เต็มที่ค่ะ"
42170-62 = "แต่ฉันเองก็ไม่รู้ว่าต้องเริ่มจากที่ไหน และเริ่มจากอะไร ฉันไม่แน่ใจเลยค่ะ..."
42170-63 = "... ฉันขอความคิดเห็นจากคุณครูได้ไหมคะ"
42170-64 = ""
42170-67 = "[ns] \"มีวิธีขัดขวางการระเบิดไหม?\""
42170-68 = "หัวรบนั้นน่าจะหนักราวๆ 1 ตัน เราลำเลียงมันด้วยกำลังของคนไม่ได้หรอกค่ะ ถ้าไม่มีเครื่องมือหนักๆ ก็ไม่น่าจะแย่งหัวรบนั่นมาได้ค่ะ"
42170-69 = "แต่ถึงอย่างนั้น เราก็จะยอมให้กองกำลังของไคเซอร์ ซิเคียวริตี้ที่คุ้มกันอาคารสถานีรถไฟอยู่เข้าถึง#nเครื่องมือหนักๆ ไม่ได้ด้วย..."
42170-70 = "... ในกรณีที่เลวร้ายที่สุด พวกนั้นอาจจะระเบิดหัวรบเสียก่อนที่การขนส่งจะเสร็จสิ้นก็เป็นไปได้ค่ะ"
42170-71 = "หากต้องการหยุดการระเบิดก่อนที่อีกฝ่ายจะรู้สึกถึงความผิดปกติ เราก็ต้องใช้คนจำนวนน้อยเพื่อที่จะ#nเข้าถึงหัวรบได้อย่างรวดเร็ว แล้วแยกส่วนท่อจุดชนวนออกให้มันทำงานไม่ได้ค่ะ"
42170-72 = "[s] \"คนจำนวนน้อยๆ งั้นเหรอ...\""
42170-74 = "[ns] \"คนที่จะหยุดหน่วยรบพิเศษได้ ก็ต้องเป็นหน่วยรบพิเศษละนะ\""
42170-75 = "... แปลว่าคนที่จะสู้กับ SRT ได้ ก็มีแค่ SRT เหรอคะ?"
42170-76 = "ที่จริงฉันคิดว่าหากพวกรุ่นพี่ FOX เข้าไปข้องเกี่ยวด้วย ฉันก็ควรเตรียมตัวเพื่อการสู้รบพิเศษไว้ค่ะ..."
42170-77 = "ฉันด้อยกว่าทั้งเรื่องอาวุธ ทั้งประสบการณ์ ทั้งสมรรถภาพ... แล้วฉันจะเอาชนะพี่ๆ ได้ไหมคะ?"
42170-78 = "[s3] \"ถ้ามิยาโกะเชื่อแบบนั้น\"\n[s4] \"ก็ต้องทำได้แน่นอนอยู่แล้ว\""
42170-79 = ""
42170-80 = ""
42170-82 = ""
42170-83 = "ค่ะ..."
42170-84 = "เพราะถ้าหากไม่เชื่อมั่นในตัวเองแล้วละก็ ฉันคงจะโน้มน้าวใครไม่ได้เลย"
42170-85 = "งั้นตอนนี้ฉันจะเชื่อมั่นในตัวเองค่ะ"
42170-86 = "RABBIT 1 จะขอเริ่มปฏิบัติการค่ะ!"
42170-88 = "สถานีโคะอุซางิ"
42170-90 = ""
42170-93 = ""
42170-97 = "นี่คือ RABBIT 1 ขณะนี้เวลา 10:30 น.  ฉันเพิ่งมาถึงจุดปฏิบัติการเลยค่ะ"
42170-98 = "ถึงจะคาดเดาเอาไว้แล้วก็ตาม... แต่ว่าที่นี่มีการรักษาเขตแดนเข้มงวดกว่าที่คิดอีกนะคะ"
42170-99 = ""
42170-101 = ""
42170-102 = "ทางเข้าออกหลักมีการ์ดยืนคุ้มกันอยู่ 6 คน แล้วก็ยังมีการ์ดอย่างน้อย 2 กลุ่มที่กำลังลาดตระเวนแถวๆ สถานีอยู่..."
42170-103 = "ถ้าเป็นแบบนี้ ฉันว่าคงไม่มีทางเข้าไปในอาคารสถานีรถไฟโดยไม่ให้การ์ดพวกนั้นจับได้แน่เลยค่ะ"
42170-104 = "[s] \"บุกจากด้านหน้าไปเลยไม่ได้เหรอ?\""
42170-105 = "ถ้าอีกฝ่ายมีกันแค่สามคนก็น่าจะโจมตีพร้อมกันแล้วฝ่าไปได้อยู่หรอกค่ะ..."
42170-106 = "แต่ถ้าหากอีกฝ่ายมีมากกว่านั้น ศัตรูอาจเสริมกองกำลังระหว่างที่เราฝ่าไปก็ได้ค่ะ"
42170-107 = "...พอไม่มีสมาชิกคนอื่นๆ แล้วก็รู้สึกถึงความว่างเปล่าขึ้นมาเลยนะคะ"
42170-108 = "อยากให้มีคนมาช่วยในปฏิบัติการเบี่ยงเบนความสนใจจากศัตรูจังเลย..."
42170-109 = ""
42170-112 = "... แย่ละสิ แย่แล้วๆ ใครกันเนี่ย"
42170-113 = ""
42170-115 = ""
42170-116 = ""
42170-119 = ""
42170-120 = ""
42170-121 = "นี่สินะที่เขาว่ากันว่า ศัตรูกับผู้มีพระคุณมาเจอกันบนสะพานไม้ที่มีท่อนเดียว พวกเรานี่จะบังเอิญอะไร#nกันขนาดนี้ครับเนี่ย"
42170-122 = "[s] \"คุณคือ...\""
42170-123 = ""
42170-124 = "ครั้งหนึ่งผมเคยเป็นผู้แสวงหาความยากจนแต่ซื่อสัตย์ และเป็นผู้บำเพ็ญตนที่ดื่มด่ำกับธรรมชาติที่#nปราศจากการแต่งเติม..."
42170-125 = "แต่ตอนนี้ผมได้กลายมาเป็นส่วนหนึ่งของสังคมที่สง่าผ่าเผย—"
42170-126 = ""
42170-129 = ""
42170-130 = "ใช่แล้ว เดการ์ตยังไงล่ะ!"
42170-131 = ""
42170-134 = "[ns5] \"ดีใจที่ได้เจออีกครั้งนะ เดการ์ต\"\n[ns6] \"... มาทำอะไรตรงนี้เหรอ?\""
42170-137 = "นี่คุณใช้สายตาดูจากชุดแล้วก็ยังมองไม่ออกเหรอครับ?"
42170-138 = "เอาเถอะ ก็คุณคงจะได้ใช้ชีวิตบนเอกสิทธิ์ที่ห่างไกลจากกฎระเบียบนี่เนอะครับ"
42170-139 = ""
42170-141 = ""
42170-142 = "ผมถูกไคเซอร์ ซิเคียวริตี้ลากตัวไปอบรมหลายอย่างเลยละครับ"
42170-143 = "พวกนั้นสอนให้รู้ว่ามันแย่แค่ไหนที่ไม่ยอมทำงานและเอาแต่ใช้ชีวิตเป็นปรสิตในโครงสร้างพื้นฐานของ#nสังคม..."
42170-144 = "และการใช้แรงงานจนเหงื่อท่วมมันมีคุณค่าศักดิ์สิทธิ์แค่ไหน...!"
42170-145 = "พอผ่านการอบรมอย่างสมบูรณ์แบบ ผมก็ได้เกิดใหม่เป็นยามของไคเซอร์ ซิเคียวริตี้ผู้มีส่วนร่วมใน#nการรักษาความปลอดภัยในสังคมครับ!"
42170-147 = "งะ... งั้นเหรอคะ..."
42170-148 = "การตรวจค้นบุคคลที่น่าสงสัยคือหน้าที่ของยามผู้รักษาความปลอดภัย! โดยเฉพาะอย่างยิ่งคนที่มา#nแอบดูสถานีอย่างน่าสงสัยอยู่ในที่ร่มอย่างพวกคุณแล้ว ยิ่งต้องตรวจค้นเข้าไปใหญ่เลยครับ!"
42170-149 = ""
42170-151 = ""
42170-152 = "ต่อให้เป็นคนที่เคยมีบุญคุณอันใหญ่ยิ่ง แต่ผมก็ไม่อาจละเลยหน้าที่ได้ ช่วยให้ความร่วมมือในการตรวจ#nค้นด้วย...!"
42170-153 = "เอ่อ คือว่า..."
42170-154 = "[s] \"ช่วยหลับหูหลับตาให้สักครั้งได้มั้ย?\""
42170-155 = "หืม? ให้ช่วยทำเป็นไม่รู้ไม่เห็นงั้นเหรอครับ?"
42170-156 = "คุณครูจะดูหมิ่นความภาคภูมิใจของผมในฐานะยามของไคเซอร์ ซิเคียวริตี้และพลเรือนที่ดีของสังคม#nอย่างนั้นเหรอครับ!"
42170-157 = "ผมมีหน้าที่ต้องรักษาสถานีรถไฟให้พวกพ้องชาวความสุขเล็กๆ ได้อยู่อย่างปลอดภัยและสะอาด..."
42170-159 = "... ไคเซอร์ คอร์เปอเรชั่นกำลังจะทำลายสถานีโคะอุซางินะคะ"
42170-160 = ""
42170-163 = ""
42170-164 = "วะ... ว่าไงนะครับ?!"
42170-165 = "คุณอาจจะไม่เชื่อนะคะ แต่ความจริงแล้ว..."
42170-167 = "(...มิยาโกะสรุปเรื่องที่เกิดขึ้นมาจนถึงตอนนี้ให้เดการ์ตฟัง)"
42170-170 = "... ข้อมูลมันฟังดูไม่น่าเชื่อถือเท่าไรเลยนะครับ"
42170-171 = "ติดตั้งระเบิดในสถานีที่ชาวเมืองใช้งานเพื่อขยายอำนาจให้กับตัวเองเนี่ยนะ นี่ไม่ใช่เรื่องที่คนดีๆ จะคิด#nได้หรอกนะครับ"
42170-172 = "แต่พอมาย้อนนึกถึงสิ่งที่ไคเซอร์ คอร์เปอเรชั่นเคยทำมา ก็ใช่ว่าจะเข้าใจไม่ได้อยู่หรอกครับ"
42170-173 = "ช่วงที่เข้ารับการอบรมจากไคเซอร์ ซิเคียวริตี้ ผมก็รู้สึกได้อย่างกระจ่างแจ้งเลยละครับว่าคนพวกนี้โลภ#nมากขนาดไหน..."
42170-174 = "ทั้งที่สัญญากันไว้แท้ๆ ว่าถ้าทำงานเป็นยามของไคเซอร์ ซิเคียวริตี้ จะให้พุดดิ้งเป็นของว่างวันละถ้วย..."
42170-175 = "แต่เมื่อวานก็บอกว่าพุดดิ้งหมดสต็อก แล้วก็ให้บุกมาเป็นของว่างแทน!"
42170-176 = "ยะ... อย่างนั้นสินะคะ..."
42170-178 = "...แต่ผมก็อดทนกับความอัปยศอดสูนี้ได้อยู่นะครับ"
42170-179 = "ถึงจะมีบางจุดที่ยังขาดตกไปบ้าง แต่ผมก็คิดว่าการทำเป็นหลับหูหลับตาบ้างมันก็เป็นคุณธรรมที่คน#nในสังคมควรมี...!"
42170-180 = "คนใหญ่คนโตอย่างองค์การนักเรียนกับไคเซอร์ คอร์เปอเรชั่นก็เป็นเจ้าของความมั่งคั่งกันอยู่แล้ว แล้วพวกเขาจะมาระเบิดสถานีโคะอุซางิอีกเนี่ยนะครับ...?"
42170-181 = "สถานีโคะอุซางิเป็นทั้งถิ่นฐานของชาวเมืองและที่พักพิงของพวกพ้องที่หางานไม่ได้เลยนะ"
42170-182 = "... ยกโทษให้ไม่ได้ ไอ้พวกชนชั้นนายทุนเอาแต่ได้!"
42170-183 = "วางใจผมได้เลย ถ้าเป็นการปกป้องสถานีโคะอุซางิและพวกพ้องแล้วละก็ กระผมจะให้ความร่วมมือ#nอย่างเต็มที่เลยครับ!"
42170-185 = "ขอบคุณที่เข้าใจนะคะ คุณเดการ์ต"
42170-186 = "ทางนั้นมีคนกันเยอะ ฉันต้องขอให้คุณช่วยหลอกล่อให้พวกนั้นกระจายกำลังก่อนค่ะ"
42170-187 = "ถ้าเป็นเรื่องต่อสู้ละก็ไม่มีปัญหาหรอก แต่ตอนโดนรวบตัวคราวนั้น ผมโดนริบอาวุธไปหมดแล้วเลย..."
42170-188 = "ปืนพกที่มีตอนนี้ก็มีแต่กระสุนหลอกซะด้วยครับ"
42170-189 = "เรื่องนั้นไม่มีปัญหาค่ะ ฉันมีกระสุนปืนเหลือเฟือ เดี๋ยวจะให้ยืมไปใช้นะคะ"
42170-190 = ""
42170-192 = ""
42170-193 = "อ๊ะ ไม่ได้แตะกระสุนที่เย็นและมีน้ำหนักแบบนี้มานานแล้วนะครับเนี่ย"
42170-194 = "กำลังเหลือทนกับการดูถูกและโดนข่มเหงมาอย่างยาวนานอยู่พอดี..."
42170-195 = "ขอบคุณนะครับคุณมิยาโกะ จากนี้ไป เดการ์ต ผู้นำกลุ่มความสุขเล็กๆ คนนี้จะออกโรงเองครับ!"
42170-197 = "ทีนี้งานที่เหลือก็คือก่อความวุ่นวายให้การ์ดเพ่งความสนใจไปทางอื่น..."
42170-198 = ""
42170-202 = ""
42170-203 = ""
42170-204 = ""
42170-205 = ""
42170-206 = "พวกพ้องความสุขเล็กๆ! ถ้าได้ยินเสียงวิทยุนี้ ให้รีบออกมาจากสถานีโคะอุซางิทันที!"
42170-207 = "ไคเซอร์ คอร์เปอเรชั่นที่เป็นดั่งฝูงปีศาจแห่งความโลภกำลังจะทำให้สถานที่อันศักดิ์สิทธิ์ของชาวเรา#nมีอันต้องแปดเปื้อน!"
42170-208 = "... เอ๋? หัวหน้า ไม่ได้เลิกเป็นกลุ่มความสุขเด็กๆ อะไรนั่นแล้วหรอกเหรอ?"
42170-209 = "ไม่ใช่ความสุขเด็กๆ <ความสุขเล็กๆ> ต่างหากเล่า! กลุ่มผู้แสวงหาความสุขเล็กๆ แบบไม่ต้องได้มา#nครอบครอง! ย่อสั้นๆ ว่า 'ความสุขเล็กๆ'!"
42170-210 = ""
42170-212 = ""
42170-213 = "ฮืม... ผมยังไม่ล้มเลิกการใช้ชีวิตที่ไม่ครอบครองสิ่งใดหรอกนะครับ"
42170-214 = "ที่ผ่านมาผมแค่พยายามแทรกซึมตัวเข้าไปเพราะอยากเข้าใจอย่างถ่องแท้ว่าคนที่ได้ครอบครองสิ่งอื่น#nเขามีความคิดอย่างไร และมีความปรารถนาอะไรในใจ!"
42170-215 = "และผลจากการทำอย่างนั้น... มันทำให้ผมรู้ว่าปุถุชนจากไคเซอร์ คอร์เปอเรชั่นที่พยายามหยั่งรากลง#nในพื้นที่นี้ก็คือฝูงปีศาจชั่วร้ายที่คบค้าสมาคมไม่ได้ครับ"
42170-216 = "คนไม่มีศีลธรรมที่คิดเอาแต่ได้ต้องได้รับการสั่งสอน... จงรู้ไว้ว่าการไม่ครอบครองสิ่งใดคือความสุขใจ!"
42170-217 = "ก็ได้นะ... ยังไงก็ไม่มีอะไรทำอยู่แล้ว ถ้าเรียกก็จะไปช่วยแล้วกัน"
42170-218 = "ถ้าเป็นการทำให้คนไม่ดีต้องเจอความยุ่งยากละก็... ไม่ว่าอะไรก็ทำได้อยู่แล้ว"
42170-219 = "เพื่อโลกที่สดใส ไร้ฝูงปีศาจแห่งความโลภ!"
42170-220 = "<ความสุขเล็กๆ> ลุยกันเลย!"
42170-221 = ""
42170-223 = ""
42170-226 = "ระ... รอไปด้วยกันสิ..."
42170-227 = "[s] \"ไปซะแล้ว...\""
42170-228 = "... ถ้าเป็นอย่างนี้คงหลอกล่อศัตรูลำบาก แต่ก็คงทำให้ศัตรูไขว้เขวได้สักพักนะคะ"
42170-229 = "ฉันเองก็จะไปช่วยอีกแรงค่ะ รบกวนคุณครูช่วยสั่งการด้วยนะคะ!"
