[translation]
42190-1 = "#title;제19화;어비스"
42190-5 = "3;미야코;05;선생님, 이쪽입니다.\n#3;em;[반응]\n#3;a"
42190-6 = "3;미야코;11;키리노 씨가 알려준 수직 계단은 이쪽 통로로 이어지고 있습니다."
42190-7 = "3;미야코;11;경사가 가파르니 넘어지지 않도록 발아래를 주의해 주십시오."
42190-8 = "#st;[0,0];instant;1;"
42190-15 = "3;미야코;10;……확실히 수상쩍은 공간이군요.\n#3;a"
42190-16 = "3;미야코;99;급하게 돌관공사를 한 것처럼 안전 난간과 마감재의 처리는 미흡한 데 비해, 전력 공급과 통신에 필요한 배선은 제대로 연결되어 있으니……"
42190-17 = "#st;[0,0];instant;1;"
42190-19 = "3;미야코;02\n#3;em;[반응]\n#3;h\n#wait;1000"
42190-20 = "3;미야코;10\n#3;h\n#3;m2\n#wait;800"
42190-21 = "3;미야코;10\n#3;greeting\n#wait;1500"
42190-22 = "3;미야코;05;여기, 다 쓴 적외선 케미컬 라이트가 바닥에 버려져 있습니다."
42190-23 = "3;미야코;11;아마 선배들도 이 통로를 따라 지하 시설에 진입한 모양입니다.\n#3;em;…"
42190-24 = "[s] \"그 케미컬 라이트는 무슨 의미야?\""
42190-25 = "3;미야코;02;이 케미컬 라이트는 어두운 곳에서 작전을 하는 특수부대원들이 진입 여부와 피아 식별을 위해 사용하는 일종의 표식입니다.\n#3;m3"
42190-26 = "3;미야코;99;그 말인즉…… 이 너머에 FOX 소대의 대원들이 매복하고 있을 가능성이 높겠네요."
42190-27 = "3;미야코;05;선생님. 안전한 진입을 위해 도어 브리칭을 개시하겠습니다.\n#3;em;[반응]"
42190-28 = "3;미야코;10;유탄에 맞아 다치지 않도록 멀리 떨어져 주세요."
42190-29 = "#st;[0,0];instant;1;"
42190-33 = "3;미야코;99\n#3;h\n#wait;1000"
42190-34 = "3;미야코;05;그럼…… 진입합니다!\n#3;em;[!]\n#3;closeup"
42190-35 = "#st;[0,0];instant;1;"
42190-40 = "3;미야코;04\n#3;shake\n#3;em;[?!]\n#3;h\n#wait;1000"
42190-44 = "[ns] \"이 시설은 도대체……\""
42190-45 = "3;미야코;99;……군용 격납고로군요.\n#3;a"
42190-46 = "#st;[0,0];instant;1;"
42190-48 = "3;미야코;11\n#3;m4\n#wait;1200"
42190-49 = "3;미야코;05;곳곳에 적재된 군용 장비와 이를 운반하기 위한 레일과 엘리베이터가 보입니다."
42190-50 = "3;미야코;10;이만한 규모의 격납고라면…… 최소 1개 대대 규모의 병력 정도는 무장시킬 수 있겠군요."
42190-51 = "[s] \"시민들이 이용하는 역 아래에 어째서 이런 군사 시설을……?\""
42190-52 = "3;미야코;02;확신하기는 어렵습니다만……\n#3;em;…\n#3;m3"
42190-53 = "3;미야코;10;보통 군사 시설은 시민들에게는 기피되는지라, 시내에서 멀리 떨어진 교외에 건설되는 것이 일반적이니까요."
42190-54 = "3;미야코;11;이렇게 시내 한 가운데에 격납고를 건설할 수 있다면, 부대 운용 및 장비 운송에 필요한 비용을 크게 아낄 수 있겠지요."
42190-55 = "3;미야코;99;더군다나 이 시설은 역 아래에 연결되어 있으니 '유사시'에는 철로를 통해 D.U. 각지에 손쉽게 군사력을 투사할 수도 있으니……"
42190-58 = "3;미야코;99\n#3;h"
42190-60 = "3;미야코;10;카이저 그룹이 코우사기 타운의 개발에 집착하던 이유를, 이제야 조금 알 것 같네요."
42190-61 = "[s] \"폭탄이 터진다면 모두 쓸모없어지겠지만.\""
42190-62 = "3;미야코;03;……네."
42190-63 = "3;미야코;99;폭탄이 터지고 나면 처음부터 존재하지 않았던 것처럼 없었던 일이 되어버리겠지요."
42190-64 = "3;미야코;11;그도 그럴 것이 이 장소는 사회의 그림자 속에서 살아가던 자존감 낮은 시민들조차 알지 못했던, 비밀스러운 장소니까요."
42190-65 = "3;미야코;05;이렇게 깊은 지하에서만 그들은 추악한 속내를 솔직하게 드러낼 수 있었을 겁니다."
42190-66 = "3;미야코;10;자존심조차 꺾지 못한 욕망을 투기할 수 있는 이 장소는, 그들에게 얼마나 값진 곳이었을까요."
42190-67 = "3;미야코;99;그리고 이 값진 시설을 부수어 버리면서까지 얻고자 하는 공포는 얼마나 대단한 것일까요.\n#3;stiff\n#3;em;[속상함]"
42190-68 = "[s] \"……혹시 긴장했어?\""
42190-69 = "3;미야코;03;……아뇨. 전혀."
42190-70 = "3;미야코;10;그 누구도 인정해 주지 않는, 그 누구에게도 말할 수 없는 정의가 힘을 가질 수 없는 것처럼."
42190-71 = "3;미야코;03;아무에게도 보이지 않는 공포는 유통기한이 끝난 폐기 도시락보다 더 무가치하거든요."
42190-72 = "3;미야코;99;……저도 바닥에 내던져지고 나서야 깨달았습니다."
42190-73 = "3;미야코;99;타인에게서 물려받은 이 권위의 이름이 얼마나 무가치한지를."
42190-74 = "3;미야코;10;현재 시각은 1130시. 탄두의 기폭까지 시간이 얼마 남지 않았습니다.\n#3;em;[반응]"
42190-75 = "3;미야코;05;우선 저희가 해야 할 일은—"
42190-76 = "#st;[0,0];instant;1;"
42190-81 = "3;미야코;02\n#3;em;[!]\n#3;h\n#wait;1000"
42190-82 = "3;미야코;05;잠시 기다려 주세요, 선생님.\n#3;m2"
42190-83 = "3;미야코;11;이곳은 선배들이 먼저 포석을 깔아 둔 작전 지역이기 때문에 섣불리 접근하는 것은 위험합니다."
42190-84 = "3;미야코;05;우선은 드론을 보내 이 앞의 상황을 정찰하도록 하겠습니다.\n#3;m3"
42190-85 = "#st;[0,0];instant;1;"
42190-87 = "3;미야코;99\n#3;greeting\n#3;h\n#wait;1500"
42190-88 = "3;미야코;10;드론, 가동."
42190-89 = "#st;[0,0];instant;1;"
42190-102 = "3;미야코;10;……역시 저격이 있었네요.\n#3;em;…\n#3;a"
42190-103 = "3;미야코;05;탄흔의 깊이와 탄속을 고려할 때, 적 저격수가 사용하는 것은 12.7mm 대물 저격용 탄환…… 오토기 선배의 솜씨군요."
42190-104 = "3;미야코;99;평범한 적을 상대한다면 피해를 감내하고 돌격하겠지만, 분명 오토기 선배라면 다음 한 발로 급소를 노릴 겁니다."
42190-105 = "3;미야코;10;아무리 저라도 급소에 대물 저격용 탄환을 직격 당한다면 버틸 수 없겠지요."
42190-106 = "3;미야코;06;최소한 방탄 장비로 무장한 포인트 맨이 있었더라면……\n#3;em;[속상함]\n#3;stiff"
42190-108 = "#na;???;……이제 와서 우릴 찾는 거야?"
42190-109 = "#st;[0,0];instant;1;"
42190-111 = "3;미야코;08\n#3;em;[!]\n#3;h\n#wait;1000"
42190-112 = "3;미야코;04;이 목소리는……\n#3;stiff"
42190-113 = "#st;[0,0];instant;1;"
42190-115 = "3;미야코;04\n#3;d\n#wait;1000"
42190-117 = "#st;[0,0];instant;1;"
42190-121 = "1;모에;02\n5;미유ND;03\n3;사키;00\n#1;a\n#3;a\n#5;a\n#1;h\n#3;h\n#5;h\n#wait;1500"
42190-122 = "3;사키;10;……세상에 소대원을 버리고 가는 소대장이 어딨어?"
42190-123 = "5;미유ND;06;너무해, 미야코 쨩……\n#5;em;[속상함]\n#5;stiff"
42190-124 = "1;모에;05;섭섭하네. 최소한 함께 할지 한 마디 정도는 물어볼 수 있었잖아?\n#1;em;[반응]"
42190-126 = "3;미야코;04;저, 그게 그러니까……\n#3;em;[땀]\n#3;stiff"
42190-127 = "3;미야코;06;……죄, 죄송합니다. 여러분에게는 무리한 부탁을 하게 될 거라고 생각해서……"
42190-128 = "1;사키;11;뭐가 무리한 부탁인데?\n#1;em;[?]\n#1;ar\n#3;m5"
42190-129 = "3;미야코;06;……여러분에게 희생을 강요하게 될 테니까요."
42190-130 = "3;미야코;99;제가 가고자 하는 길에는 규율 잡힌 생활도, 강력한 화기도, 안락한 시설도 없습니다."
42190-131 = "3;미야코;02;오직 제가 생각하는 정의만이 충족되는 괴로운 삶이 계속될 텐데……\n#3;em;…"
42190-132 = "3;미야코;06;어떻게 제가 생각하는 정의를 위해 여러분이 원하는 삶을 포기해달라고 말하겠나요?"
42190-133 = "#st;[0,0];instant;1;"
42190-135 = "3;미야코;06\n1;사키;10\n#1;stiff\n#1;em;[빠직]\n#1;h\n#3;h\n#wait;800"
42190-136 = "3;미야코;06\n1;사키;10\n#1;m3\n#1;h\n#3;h\n#wait;500"
42190-139 = "3;사키;10\n5;미야코;08;……아얏.\n#3;h\n#5;h\n#5;shake\n#5;em;[?!]"
42190-140 = "3;사키;11;……역시 말이 안 통하는 소대장이야."
42190-142 = "4;미유ND;00\n2;모에;02;뭐가 네가 생각하는 정의라는 거야. 이건 SRT 모두의 정의잖아?\n#2;em;[반응]"
42190-143 = "4;미유ND;03;……선배들의 모습을 동경해 SRT에 입학한 건 우리도 마찬가지거든."
42190-145 = "3;사키;03;가혹한 상황 속에서도 중심을 잃지 않는 엄격한 규율을.\n#3;em;[!]\n#3;closeup"
42190-146 = "3;모에;13;그 어떤 악인이라도 일격에 제압할 수 있는 강대한 힘을!\n#3;em;[!]\n#3;closeup"
42190-147 = "3;미유ND;05;두려운 적 앞에서도 흔들리지 않는 대담한 용기를……\n#3;stiff\n#3;closeup"
42190-148 = "3;미유ND;03;낯선 것과 맞서 싸우는 것은 두렵지만, 소대원들과 함께라면 두렵지 않아.\n#3;closeup\n#3;em;[///]"
42190-150 = "4;사키;01\n2;모에;03;승산이 있는 상황에서만 터트리는 축포는 파멸의 맛이 덜하거든.\n#2;em;[음표]"
42190-151 = "4;사키;02;세상에는 교범에 적혀 있지 않은 진리도 있으니까……"
42190-152 = "#st;[0,0];instant;1;"
42190-154 = "2;모에;02\n4;사키;01\n#2;h\n#4;h\n#wait;800"
42190-155 = "2;모에;02\n4;사키;01\n#2;h\n#4;h\n#wait;800"
42190-156 = "2;모에;02\n4;사키;01\n3;미유ND;03\n#3;a\n#2;m1\n#4;m5\n#2;h\n#4;h\n#3;h\n#wait;1500"
42190-157 = "2;모에;03\n4;사키;03\n3;미유ND;11\n#2;em;[반짝]\n#3;em;[반짝]\n#4;em;[반짝]\n#2;greeting\n#3;greeting\n#4;greeting\n#2;h\n#3;h\n#4;h"
42190-158 = "#na;일동;미야코의 정의를 믿을게!\n#fontsize;100"
42190-159 = "#st;[0,0];instant;1;"
42190-161 = "2;모에;03\n4;사키;03\n3;미유ND;11\n#2;d\n#3;d\n#4;d\n#2;h\n#3;h\n#4;h\n#wait;1200"
42190-163 = "3;미야코;08\n#3;em;…\n#3;h\n#3;a\n#wait;2500"
42190-164 = "3;미야코;99;……"
42190-165 = "3;미야코;03;……알겠습니다."
42190-166 = "3;미야코;05;그럼 모두 돌입에 앞서 장비를 점검해 주세요. 준비가 끝나는 즉시 작전을 하달하겠습니다.\n#3;em;[반응]"
42190-168 = "1;모에;02\n5;사키;01\n3;미유ND;00;FOX 선배들과의 실전이라…… 조금 긴장될지도.\n#3;stiff"
42190-169 = "5;사키;04;그러게. 마치 어두운 굴속에서 보이지 않는 검은 괴물과 맞서 싸우는 기분이야.\n#5;em;[땀]"
42190-170 = "1;모에;00;그러고 보니 전에 말했던 트리니티의 오래된 소설에 그런 장면이 나오지 않았나?\n#1;em;[?]"
42190-171 = "5;사키;02;응. 야생 토끼와 기사단이 싸우는 그 소설에 분명 그런 장면이 있었지."
42190-172 = "5;사키;99;토끼가 지키던 어두운 굴에 들어간 기사단이 끝내 발견한 메시지가 분명—\n#5;m3\n#1;dl\n#3;dl"
42190-174 = "#na;미야코;<용맹하고 순수한 마음을 가진 자만이 카르바노그의 굴속에서 길을 찾으리라.>"
42190-175 = "#st;[0,0];instant;1;"
42190-177 = "3;사키;02\n#3;em;[반응]\n#3;h\n#wait;1200"
42190-178 = "3;사키;02\n#3;d\n#wait;1000"
42190-180 = "3;미야코;99\n#3;a\n#wait;1200"
42190-181 = "3;미야코;03;……저도 그 이야기는 좋아한답니다."
42190-182 = "[s] \"그보다 작전명은 정했어?\""
42190-183 = "3;미야코;02;그러고 보니 이번 작전은 작전명을 정하는 것을 잊고 있었네요……"
42190-184 = "3;미야코;03;마침 말도 나왔으니, 이번 작전명은 그 이야기의 제목으로 할까요?\n#3;em;[반응]"
42190-185 = "1;모에;02\n5;미유ND;03\n3;사키;07;좋아!\n#3;em;[재잘]\n#3;hophop"
42190-186 = "1;모에;03;나는 찬성이야.\n#1;greeting"
42190-188 = "3;미야코;99;네. 그럼……\n#3;em;…"
42190-189 = "#st;[0,0];instant;1;"
42190-194 = "#na;미야코;<카르바노그의 토끼> 작전, 시작하겠습니다!\n#fontsize;100"
