[translation]
51-1 = "#na;R64 흰색 실루엣 출력 테스트"
51-2 = "#na;흰색 실루엣 출력 테스트"
51-3 = "3;히마리;00;히마리 일반 실루엣 출력\n#3;h"
51-4 = "3;히마리;00;히마리 흰색 실루엣 출력\n#3;white\n#3;h"
51-5 = "#st;[0,0];instant;1;"
51-8 = "3;아야네;00;아야네 일반 실루엣 출력\n#3;h"
51-9 = "3;아야네;00;아야네 흰색 실루엣 출력\n#3;white\n#3;h"
51-10 = "#st;[0,0];instant;1;"
51-13 = "3;이즈나;00;이즈나 일반 실루엣 출력\n#3;h"
51-14 = "3;이즈나;00;이즈나 흰색 실루엣 출력\n#3;white\n#3;h"
51-15 = "#na;테스트 종료"
