[translation]
51070-1 = "#title;제7화;청춘(?)에 매진하는 소녀 1"
51070-2 = "3;유카리;06\n#3;a\n#wait;1200"
51070-3 = "[ns] \"청춘……? 이게 무슨 소리야?\""
51070-4 = "3;유카리;12;……핫! 그러고 보면……\n#3;em;[!]\n#3;stiff"
51070-5 = "3;유카리;08;예전에 렌게 선배로부터 이런 말을 들은 적이 있사와요."
51070-7 = "2;유카리;02\n#2;em;[///]\n#2;a\n#wait;1200"
51070-8 = "2;유카리;10\n#2;em;[반짝]\n#2;hophop\n#2;m4\n#wait;1200"
51070-10 = "2;유카리;10\n1;렌게 실루엣;00\n#1;ar\n#2;m5\n#2;h\n#1;h\n#1;black\n#wait;1500"
51070-11 = "2;유카리;10\n1;렌게 실루엣;00;그러고 보면 유카리, 너는 중학생 때부터 이곳에 들어오고 싶어 했었지.\n#1;em;[반응]\n#1;black"
51070-12 = "2;유카리;07;네!\n#2;em;[반짝]\n#2;greeting"
51070-13 = "1;렌게 실루엣;00;<운명적인 그때 밤의 만남이 계기였다.> 라니.\n#1;black"
51070-14 = "1;렌게 실루엣;00;처음 들었을 땐 이런 고생스러운 곳에 일부러 들어오려고 하다니, 무진장 괴짜구만. 하고 생각했었는데.\n#1;black"
51070-15 = "2;유카리;00;무슨 그런 말씀을! 백화요란은 엘리~트들이 모이는 대단한 곳! 저 유카리, 엘리~트인 제가 들어가야 할 동아리가 있다면 이곳 밖에 없다고 진즉 마음을 먹고 있었사와요!\n#2;em;[반응]\n#2;hophop"
51070-16 = "1;렌게 실루엣;00;……하긴, 너는 중학생 때부터 정말 줄기차게 매일 같이…… \n#1;em;[한숨]\n#1;black"
51070-17 = "1;렌게 실루엣;00;이곳에 오면 안 된다고 키쿄가 타박할 때마다 매번 부루퉁한 표정을 지은 채 돌아갔다가, 다음 날이 되면 보란 듯이 다시 나타났었지.\n#1;m3\n#1;black\n#2;dr"
51070-18 = "1;렌게 실루엣;00;매일 아침 4시에 일어나 단련을 하고, 돌아와서는 밥을 먹고, 학교 수업을 듣고 또다시 단련에 단련을 거듭하고 하는, 이런 거의 대체 어디가 좋다고…….\n#1;black"
51070-20 = "3;유카리;00;앗, 하지만 저 유카리. 렌게 선배는 물론 다른 선배들과도 함께하는 활동이 무척 즐거운걸요?\n#3;em;[반응]"
51070-21 = "3;렌게 실루엣;00;아니…… 그렇게까지 말하면, 나도 그, 할 말은 없지만.\n#3;black\n#3;stiff"
51070-22 = "3;렌게 실루엣;00;그래도 말이지…… 가끔은 그런 상상을 해본 적 없어?\n#3;em;…\n#3;black"
51070-24 = "3;유카리;02;……?\n#3;em;[?]"
51070-25 = "1;렌게 실루엣;00;백화요란의 활동만이 아니라, 친구들과 함께 새콤달콤한 청춘 이벤트를 겪어보고 싶다던가…….\n#1;ar\n#3;m5\n#1;black"
51070-26 = "3;유카리;10;네, 단 한 번도 없사와요!\n#3;em;[!]\n#3;jump"
51070-27 = "3;유카리;10\n1;렌게 실루엣;00;우와앗…… 바로 즉답이네. 이 녀석.\n#1;em;[///]\n#1;stiff\n#1;black"
51070-28 = "3;유카리;14;그러는 렌게 선배는 어떠신가요! 백화요란의 활동!\n#3;em;[반짝]\n#3;m4\n#3;hophop"
51070-29 = "3;유카리;10\n1;렌게 실루엣;00;……아니 뭐, 나도 키쿄를 따라 여기 들어온 뒤로는 재미있는 일도 많았고.\n#1;black"
51070-30 = "3;유카리;10\n1;렌게 실루엣;00;나구사 선배에, 너까지 만났으니…… 후회하는 건 아니지만.\n#1;black"
51070-31 = "#st;[0,0];instant;1;"
51070-33 = "1;렌게 실루엣;00\n#1;black\n#1;m3\n#3;dr\n#wait;1200"
51070-35 = "3;렌게 실루엣;00;그래도 말이지. 조금은 다른, 그런 청춘을 보낼 수 있었다면…….\n#3;em;[반응]\n#3;black\n#3;closeup"
51070-36 = "3;렌게 실루엣;00;운동부가 아닌, 문화계 동아리 같은 곳에서──\n#3;closeup\n#3;black"
51070-37 = "#st;[0,0];instant;1;"
51070-40 = "3;유카리;02\n#3;em;…\n#wait;2500"
51070-42 = "3;유카리;08;……그때엔 무슨 소리인지 잘 이해할 수 없었지만. \n#3;a"
51070-43 = "3;유카리;05;저 유카리. 대화 이후에 아주 조금, 정말로 아주 약간 그런 생각을 하긴 했사와요.\n#3;em;[반응]"
51070-44 = "3;유카리;08;혹시 렌게 선배는, 다른 부활동에 관심이 생기셨던 게 아닐까……? 라고. 괜한 착각이라고도 생각하지만…….\n#3;m2"
51070-45 = "[s] \"어디로 보나 청춘에 미련이 뚝뚝 흘러넘치는 대화였지 않아?!\""
51070-46 = "#st;[0,0];instant;1;"
51070-48 = "3;유카리;02\n#3;em;[!]\n#wait;1000"
51070-49 = "3;유카리;12;헉! 역시 그랬던가요!\n#3;stiff"
51070-50 = "3;유카리;08;과연……. 그렇다는 건 지금 렌게 선배는…….\n#3;m3"
51070-51 = "3;유카리;04;이 쪽지에 적힌 그대로 청춘을 누리고 싶어 잠깐의 방황을?!\n#3;em;[?!]\n#3;shake"
51070-52 = "3;유카리;05;어쩐지 <청춘을 보낸다면 역시 문화계 활동이지. 땀내 나는 백화요란 활동보다 그쪽이 산뜻하잖아.> 같은 말도 하셨던 건 괜한 이야기가 아니었던 것이로군요!"
51070-53 = "[s] \"그쪽이 오히려 확정 100%의 발언인데?!\""
51070-54 = "3;유카리;08;으으음, 언제나 누구보다 앞에 서서, 열심히, 저희들이 다치지 않도록 솔선해서 활약한 렌게 선배였는데…….\n#3;m4"
51070-55 = "3;유카리;08;이것을 보아하니…… 나구사 선배가 사라진 뒤로…… 특히나 백화요란의 활동이 정지된 이후……."
51070-56 = "#st;[0,0];instant;1;"
51070-58 = "3;유카리;02\n#3;em;[!]\n#wait;1000"
51070-59 = "3;유카리;04;끝내 렌게 선배는 참지 못하고 청춘에 대한 갈망이 폭발해 버린 것이와요! 틀림없사와요!\n#3;stiff"
51070-60 = "3;유카리;12;자! 이러고 있을 게 아니라 바로 찾으러 가시죠! 선생님!\n#3;hophop\n#3;m3"
51070-61 = "#st;[0,0];instant;1;"
51070-63 = "3;유카리;12\n#3;dl\n#wait;1500"
51070-65 = "1;유카리;05\n#1;ar\n#1;h\n#wait;1500"
51070-66 = "1;유카리;02;……근데 저……\n#1;stiff"
51070-67 = "#st;[0,0];instant;1;"
51070-70 = "1;유카리;08\n#1;em;[///]\n#1;m3\n#wait;1500"
51070-71 = "1;유카리;05\n#1;h\n#wait;1200"
51070-72 = "1;유카리;14;어디로 가면 좋을까요?\n#1;em;[땀]\n#1;stiff"
51070-73 = "#st;[0,0];instant;1;"
51070-79 = "[ns] \"자, 이게 카호가 전해준 문화계 동아리 리스트야.\""
51070-80 = "3;유카리;02;정말로 음양부로부터 이렇게나 쉽게 동아리 목록을 받아낸 것이군요!\n#3;em;[땀]\n#3;stiff\n#3;a"
51070-81 = "3;유카리;10;괴, 굉장하시어요!"
51070-82 = "3;유카리;04;헉…… 이것이 설마 말로만 듣던, 음양부의 부장과 부부장조차 굴복시키는 샤알-레의 권력……?\n#3;em;[?!]\n#3;shake"
51070-83 = "3;유카리;08;소녀 유카리, 실은 정말로 위험하신 분과 같이 있는 것일까요?!"
51070-84 = "[s] \"그러니까 오해라니까…….\""
51070-85 = "3;유카리;05;으음!"
51070-86 = "3;유카리;12;어쨌거나 받은 리~스투를 따라, 지금부터 렌게 선배를 추적하겠사와요!\n#3;em;[!]\n#3;jump"
51070-88 = "#place;클로렐라 생태관찰부"
51070-90 = "3;유카리;02;리~스투에 따르면 첫 번째 동아리 장소는 이곳인 모양이어요…….\n#3;em;…\n#3;a"
51070-91 = "3;유카리;05;어디 그럼…….\n#3;m2"
51070-92 = "#st;[0,0];instant;1;"
51070-94 = "3;유카리;05\n#3;greeting\n#wait;1500"
51070-95 = "3;유카리;00;실례하겠습니다!\n#3;em;[반응]"
51070-96 = "#st;[0,0];instant;1;"
51070-102 = "2;클로렐라 백귀야행 동아리 부원 A;03\n4;클로렐라 백귀야행 동아리 부원 B;01\n#2;hophop\n#2;em;[재잘]\n#4;a\n#2;a\n#2;h\n#4;h\n#wait;1000"
51070-103 = "2;클로렐라 백귀야행 동아리 부원 A;03\n4;클로렐라 백귀야행 동아리 부원 B;00\n#4;greeting\n#4;em;[음표]\n#2;h\n#4;h\n#wait;1000"
51070-105 = "5;유카리;01\n2;클로렐라 백귀야행 동아리 부원 A;03\n4;클로렐라 백귀야행 동아리 부원 B;00\n#2;m1\n#4;m3\n#5;al\n#5;h\n#2;h\n#4;h\n#wait;1500"
51070-106 = "5;유카리;01\n2;클로렐라 백귀야행 동아리 부원 A;02\n4;클로렐라 백귀야행 동아리 부원 B;02\n#2;em;[?]\n#4;em;[?]\n#5;h\n#2;h\n#4;h\n#wait;1000"
51070-107 = "2;클로렐라 백귀야행 동아리 부원 A;01;응? 손님?"
51070-108 = "4;클로렐라 백귀야행 동아리 부원 B;01;뭐야? 무슨 일이야?\n#4;em;[반응]"
51070-109 = "[s] \"안녕, 다른 게 아니라…….\""
51070-111 = "3;유카리;00;네! 저희는 렌게 선배를 찾아왔사와요!\n#3;em;[!]\n#3;closeup"
51070-113 = "4;클로렐라 백귀야행 동아리 부원 B;01\n2;클로렐라 백귀야행 동아리 부원 A;01;렌게……?\n#2;em;[?]"
51070-114 = "4;클로렐라 백귀야행 동아리 부원 B;02;무슨 말을 하는 거야? 렌게라니, 그게 누군데?"
51070-116 = "3;유카리;02;렌게 선배는…… 그러니까.\n#3;stiff"
51070-117 = "3;유카리;00;렌게 선배여요!\n#3;em;[!]\n#3;jump"
51070-119 = "4;클로렐라 백귀야행 동아리 부원 B;01\n2;클로렐라 백귀야행 동아리 부원 A;04;……엉?\n#2;em;[?]\n#2;h"
51070-121 = "3;유카리;07\n#3;h"
51070-122 = "[ns] \"유카리, 좀 더 자세한 정보를 전달하지 않으면…….\""
51070-123 = "3;유카리;02;앗, 그런가요?\n#3;em;[땀]"
51070-124 = "3;유카리;08;으으음…… 렌게 선배는…… 설명하자면 그러니까…….\n#3;stiff"
51070-125 = "3;유카리;08;때로는 <아침 단련을 빠진 녀석에겐 벌칙이다!>라며 야단을 치시거나……."
51070-126 = "3;유카리;02;또 어쩔 때는 입가에 밥풀을 묻힌 저를 보시고는 재밌다는 듯이 웃으시거나…….\n#3;em;[반응]"
51070-127 = "3;유카리;08;또 우연히 같이 쇼핑하러 나갔다가 길거리에서 날뛰는 망량즈를 보면 참지 않고 뛰쳐나가기도 하는 분이라…… 저도 무척이나 존경하고 있는 그런……."
51070-128 = "#st;[0,0];instant;1;"
51070-131 = "4;클로렐라 백귀야행 동아리 부원 B;04\n2;클로렐라 백귀야행 동아리 부원 A;04\n#2;em;…\n#4;em;…\n#2;h\n#4;h\n#wait;2500"
51070-132 = "4;클로렐라 백귀야행 동아리 부원 B;04;……미안, 무슨 소리를 하는지 모르겠는데.\n#4;em;[땀]\n#4;stiff"
51070-134 = "3;유카리;04;네, 네엣?! 이걸로도 부족하다는 말씀이시어요?!\n#3;em;[?!]\n#3;shake"
51070-135 = "[s1] \"방금 유카리가 한 말로 알 수 있는 정보는…….\"\n[s2] \"유카리가 렌게를 평소 어떻게 생각하고 있는지 정도가 아닐까…….\""
51070-138 = "3;유카리;08;으으음…… 이런 느낌이 아니라.\n#3;em;[속상함]\n#3;stiff"
51070-139 = "3;유카리;08;그밖에 구체적인 정보라고 하면…… 렌게 선배는…… 또 붉은 머리가 엄청나게 멋진……."
51070-141 = "4;클로렐라 백귀야행 동아리 부원 B;05\n2;클로렐라 백귀야행 동아리 부원 A;01;붉은 머리?"
51070-142 = "[s] \"역시 이런 방법으로는 찾기 어려…….\""
51070-143 = "2;클로렐라 백귀야행 동아리 부원 A;02;붉은 머리라면 혹시 얼마 전에 체험 입부했던 그 아이를 말하는 거 아냐?\n#2;em;[?]"
51070-144 = "#st;[0,0];instant;1;"
51070-147 = "3;유카리;02\n#3;em;[!]\n#3;h\n#wait;1000"
51070-149 = "2;클로렐라 백귀야행 동아리 부원 A;02\n4;클로렐라 백귀야행 동아리 부원 B;00;아…… 그 물빛 하오리를 입고 있던 걔 말이지?\n#4;em;[반응]"
51070-151 = "3;유카리;10;네, 바로 그분이어요! 역시 이 동아리에도 오셨던 거군요!\n#3;em;[반짝]\n#3;hophop"
51070-152 = "3;유카리;14;분명 렌게 선배라면 여기 <클로렐라 생태관찰부>에서도 에이스에 준하는 활약을……!"
51070-154 = "4;클로렐라 백귀야행 동아리 부원 B;01\n2;클로렐라 백귀야행 동아리 부원 A;04;뭐랄까…… 좀 이해하기 어려운 말들을 했었, 지?\n#2;em;…"
51070-155 = "4;클로렐라 백귀야행 동아리 부원 B;02;<우리 함께 전국 대회를 노리면서 밤샘 연습을 해보자! 체력엔 자신이 있어!> 같은 이야기를 한다던가."
51070-156 = "4;클로렐라 백귀야행 동아리 부원 B;01;……근데 클로렐라 생태관찰에서 전국 대회라니, 그런 게 있었나? \n#4;em;[?]"
51070-157 = "2;클로렐라 백귀야행 동아리 부원 A;06;<클로렐라 생태관찰의 진수를 가르쳐줘! 너희들에게 부끄럽지 않도록! 전력으로 해내 보이겠어!> 같은 말을 하기도 해서, 그게 좀…….\n#2;em;[땀]\n#2;stiff"
51070-158 = "#st;[0,0];instant;1;"
51070-160 = "4;클로렐라 백귀야행 동아리 부원 B;01\n2;클로렐라 백귀야행 동아리 부원 A;06\n#2;d\n#4;d\n#2;h\n#wait;1000"
51070-162 = "3;유카리;02\n#3;em;…\n#3;a\n#wait;2500"
51070-163 = "[ns] \"으음, 어째 이야기를 들어보니…… 상당히…….\""
51070-164 = "3;유카리;08\n#3;stiff\n#wait;1500"
51070-165 = "3;유카리;10;……과연 렌게 선배다운 활약이어요!\n#3;em;[!]\n#3;closeup\n#fontsize;100"
51070-166 = "#st;[0,0];instant;1;"
51070-169 = "[ns] \"어?! 활약, 인 걸까?!\""
51070-170 = "3;유카리;14;렌게 선배는 타협 따윈 하지 않는 분이시니까요!\n#3;em;[반짝]\n#3;hophop\n#3;closeup"
51070-171 = "3;유카리;07;그래서 말인데, 여러분. 그 렌게 선배는 지금 어디에……!\n#3;closeup"
51070-172 = "3;유카리;07\n1;클로렐라 백귀야행 동아리 부원 A;00;아, 여기엔 없어.\n#1;em;[반응]\n#1;ar\n#3;m5"
51070-173 = "1;클로렐라 백귀야행 동아리 부원 B;01;체험입부 기간이 끝나던 당일 날에……."
51070-174 = "#st;[0,0];instant;1;"
51070-176 = "3;유카리;02\n#3;em;[?]\n#3;h\n#wait;1000"
51070-179 = "3;렌게 실루엣;00\n#3;ar\n#3;h\n#3;black\n#wait;1000"
51070-180 = "3;렌게 실루엣;00;으으윽! 미안……!\n#3;em;[땀]\n#3;black"
51070-181 = "3;렌게 실루엣;00;요 며칠 체험입부 기간 동안…… 내 멋대로 떠들기만 하고 마음대로 하려고 해서 폐를 끼쳤어.\n#3;stiff\n#3;black"
51070-182 = "#st;[0,0];instant;1;"
51070-185 = "4;클로렐라 백귀야행 동아리 부원 B;01\n2;클로렐라 백귀야행 동아리 부원 A;01\n#2;em;[?]\n#4;em;[?]\n#4;h\n#2;h\n#wait;1000"
51070-186 = "4;클로렐라 백귀야행 동아리 부원 B;01\n2;클로렐라 백귀야행 동아리 부원 A;02;아니…… 그 정도까지는……."
51070-188 = "3;렌게 실루엣;00;……하지만 덕분에 깨달았어…….\n#3;em;[반응]\n#3;black"
51070-190 = "2;클로렐라 백귀야행 동아리 부원 A;04\n4;클로렐라 백귀야행 동아리 부원 B;04;응?"
51070-191 = "5;렌게 실루엣;00;진지하게 클로렐라 생태를 관찰하는 너희들을 보면서, 아직 겉핥기에 불과한 나의 어중간함을 말이야.\n#5;al\n#2;m1\n#4;m3\n#5;black"
51070-192 = "5;렌게 실루엣;00;역시 이 부활동에 평생을 바쳐온 너희들에 비하면, 난 아무것도 아니야.\n#5;black"
51070-193 = "4;클로렐라 백귀야행 동아리 부원 B;04\n2;클로렐라 백귀야행 동아리 부원 A;04;아니, 평생을 바친 적은 딱히…….\n#2;stiff\n#2;em;[땀]"
51070-194 = "5;렌게 실루엣;00;그러니 미안! 정식 입부는…… 아쉽지만…… 포기할게. \n#5;hophop\n#5;m3\n#2;dl\n#4;dl\n#5;black"
51070-195 = "5;렌게 실루엣;00;아, 하지만 그래도 너희들의 뜨거운 열정! 가슴 깊이 이해했으니까. 클로렐라 관찰! 앞으로도 계속해서 응원하겠어!\n#5;black"
51070-197 = "3;렌게 실루엣;00;나중에 전국대회에 참가하면! 꼭 보러 올 테니까!\n#3;greeting\n#3;em;[반짝]\n#3;closeup\n#3;black"
51070-198 = "#st;[0,0];instant;1;"
51070-201 = "2;클로렐라 백귀야행 동아리 부원 A;04\n4;클로렐라 백귀야행 동아리 부원 B;04\n#2;em;…\n#4;em;…\n#2;h\n#4;h\n#wait;2500"
51070-204 = "4;클로렐라 백귀야행 동아리 부원 B;04\n2;클로렐라 백귀야행 동아리 부원 A;04;……라면서 체험 입부가 끝나고는 가버렸거든.\n#2;em;[땀]\n#2;stiff\n#2;a\n#4;a"
51070-205 = "4;클로렐라 백귀야행 동아리 부원 B;02;저기 말이야.\n#4;em;[반응]"
51070-206 = "4;클로렐라 백귀야행 동아리 부원 B;01;클로렐라 생태관찰 전국 대회……. 지금이라도 참가 준비 신청을 하는 게 좋을까?"
51070-208 = "3;유카리;02;그런가요……"
51070-209 = "3;유카리;07;혹시 어디로 가셨는지는 아시나요?\n#3;em;[?]"
51070-210 = "1;클로렐라 백귀야행 동아리 부원 A;02;글쎄…… 우리도 우리지만.\n#1;ar\n#3;m5"
51070-211 = "1;클로렐라 백귀야행 동아리 부원 A;01;최근엔 이곳이고 저곳이고 동아리들은 전부 <등불 축제>의 출품작을 준비하느라 바쁠 시기라. 거기까진 모르겠네."
51070-214 = "[ns] \"렌게를 만나지 못해서 아쉬운걸.\""
51070-215 = "3;유카리;00;네, 하지만 원래 추측했던 대로 렌게 선배가 청춘을 위해 문화계 동아리 활동을 하고 있단 걸 확인한 건 큰 소득이어요!\n#3;em;[반짝]\n#3;a"
51070-216 = "#st;[0,0];instant;1;"
51070-218 = "3;유카리;01\n#3;h\n#3;m4\n#wait;1200"
51070-219 = "3;유카리;00;방침은 틀리지 않았사오니, 그럼 바로 다음 동아리로 가시죠!\n#3;em;[반응]"
51070-221 = "#place;SF 전략 시뮬레이션 쇼기부"
51070-223 = "3;쇼기부 백귀야행 동아리 부원 A;02;백화요란의 빨간머리 말이지.\n#3;em;[반응]\n#3;a"
51070-224 = "3;쇼기부 백귀야행 동아리 부원 A;01;맞아. 기억나네. 우리 동아리에도 왔었어."
51070-225 = "3;쇼기부 백귀야행 동아리 부원 A;04;뭔가…… 되게 특이한 사람이었지?\n#3;em;[땀]"
51070-226 = "5;쇼기부 백귀야행 동아리 부원 B;02;쇼기 승부를 겨루던 도중에 궁지에 몰리길래. 한 수 물러줄까? 라고 말하니까.\n#5;em;…\n#5;al\n#3;m1"
51070-228 = "3;쇼기부 백귀야행 동아리 부원 B;01\n#3;greeting\n#3;a\n#wait;1500"
51070-230 = "3;렌게 실루엣;00\n#3;shake\n#3;em;[?!]\n#3;black\n#wait;1000"
51070-231 = "3;렌게 실루엣;00;이, 이건……! 원래라면 규칙상 허용되지 않지만…… 동아리 활동이라는 친목 활동에서 용인되는…… 아주 가벼운 룰의 일탈……! \n#3;em;[땀]\n#3;black"
51070-232 = "3;렌게 실루엣;00;하지만……! 하지만!\n#3;stiff\n#3;black"
51070-233 = "1;쇼기부 백귀야행 동아리 부원 B;02;아, 그건 싫어?\n#1;em;[?]\n#1;ar\n#3;m5"
51070-234 = "#st;[0,0];instant;1;"
51070-236 = "1;쇼기부 백귀야행 동아리 부원 B;03\n#1;greeting\n#wait;1000"
51070-237 = "1;쇼기부 백귀야행 동아리 부원 B;00;그럼 이걸로 장군이야.\n#1;em;[음표]"
51070-238 = "#st;[0,0];instant;1;"
51070-240 = "3;렌게 실루엣;00\n#3;shake\n#3;em;[?!]\n#wait;1000\n#3;black"
51070-242 = "3;렌게 실루엣;00;졌습니다아아앗!!\n#3;closeup\n#fontsize;100\n#3;black\n#bgshake"
51070-245 = "3;쇼기부 백귀야행 동아리 부원 B;02;같은 일이 있고 나니까. 거기서 잠깐 흔들려 버린 자신에게 환멸이 났다면서 미안하다고 연신 고개를 숙이고는 떠나갔어.\n#3;a"
51070-247 = "1;유카리;10;그것참……! 렌게 선배다운 활약이어요!\n#1;em;[반짝]\n#1;hophop\n#1;ar\n#3;m5"
51070-249 = "#place;피트니스 라쿠고부"
51070-250 = "3;피트니스 백귀야행 동아리 부원 A;02;아아, 렌게라면 여기도 왔었어.\n#3;em;[반응]\n#3;a"
51070-251 = "4;피트니스 백귀야행 동아리 부원 B;02;우리들의 라쿠고를 들으며 청춘의 꿈을 키우고 있었어! 라고 말해주는 게 기쁘긴 했지만.\n#4;a\n#3;m2"
51070-252 = "3;피트니스 백귀야행 동아리 부원 A;04;축제 준비로 바쁘다 보니 부원을 받을 형편이 안 되어서 입부는 거절했지만 말이야.\n#3;em;[속상함]\n#3;stiff"
51070-254 = "#place;배틀 카루타부"
51070-255 = "3;카루타부 백귀야행 동아리 부원 A;03;아, 맞아맞아. 그런 애가 찾아왔었지.\n#3;em;[음표]\n#3;a"
51070-256 = "1;카루타부 백귀야행 동아리 부원 B;02;뜨거운 청춘 카루타 배틀을 동경하고 있었다고…….\n#1;ar\n#3;m5"
51070-257 = "3;카루타부 백귀야행 동아리 부원 A;04;뭐, 축제가 코앞이니 받아주지 못했지만…….\n#3;em;[땀]\n#3;stiff"
51070-258 = "#st;[0,0];instant;1;"
51070-260 = "1;카루타부 백귀야행 동아리 부원 B;02\n3;카루타부 백귀야행 동아리 부원 A;04\n#1;d\n#3;d\n#wait;1200"
51070-262 = "3;유카리;02\n#3;em;…\n#3;a\n#wait;2500"
51070-264 = "#na;(그렇게 몇 개나 되는 동아리를 돌았을까.)"
51070-268 = "[ns] \"자, 여기 음료수.\""
51070-269 = "#st;[0,0];instant;1;"
51070-271 = "3;유카리;02\n#3;em;[반응]\n#3;a\n#wait;1200"
51070-272 = "3;유카리;06;아, 네. 감사합니다아…….\n#3;stiff"
51070-273 = "#na;(제법 많은 동아리를 돌아다녔지만, 끝내 렌게의 꼬리는 잡을 수가 없었다.)"
51070-274 = "3;유카리;08;설마 렌게 선배, 이렇게나 많은 동아리에 체험 입부하여 활동하고 계셨을 줄은…….\n#3;em;…"
51070-275 = "3;유카리;08;그렇다고는 해도…… 다들 렌게 선배에 대해 하시는 말씀들이 참……."
51070-276 = "[s] \"응, 아무래도 다들 신랄하게…….\""
51070-277 = "3;유카리;10;네! 다른 분들 모두! 신랄하게 렌게 선배를 높이 평가하고 있었사와요!\n#3;hophop\n#3;em;[반짝]"
51070-278 = "3;유카리;02;네? 신랄하다. 는 표현은 그럴 때 쓰는 게 아니야?"
51070-279 = "3;유카리;99;우후후, 무슨 말씀을!"
51070-280 = "3;유카리;07;말이란 어디까지나 어떻게 말하고 받아들이는지 나름인 것이어요!\n#3;em;[!]\n#3;closeup"
51070-281 = "3;유카리;00;모두가 렌게 선배에 대해 잊지 않고 말씀해 주신다는 건 그만큼 렌게 선배가 동아리 활동에 진심을 다하고 계셨단 방증!\n#3;closeup"
51070-282 = "3;유카리;14;렌게 선배는 옛날부터 어중간하게 타협하지 않고 끝장을 봐야 돼! 라고 외치는 분이셨으니까요.\n#3;em;[반짝]\n#3;greeting\n#3;closeup"
51070-283 = "[s] \"유카리는 렌게를 무척 좋아하고 신뢰하고 있구나.\""
51070-284 = "3;유카리;07;네! 저 유카리가 무척이나 존경하고 있답니다!\n#3;em;[반응]"
51070-285 = "3;유카리;99;흠흠."
51070-286 = "#st;[0,0];instant;1;"
51070-288 = "3;유카리;01\n#3;m4\n#wait;1200"
51070-289 = "3;유카리;02;그럼 이다음으로 계속해서 저희는 어디로 가야……."
51070-291 = "#na;???;선생님 발……견!!"
51070-292 = "#st;[0,0];instant;1;"
51070-295 = "3;카에데;11\n#3;black\n#3;stiff\n#3;h\n#3;closeup\n#wait;500"
51070-296 = "3;카에데;11\n#3;black\n#3;jump\n#3;h\n#3;closeup\n#wait;300"
51070-300 = "[ns] \"우, 우와앗?!\""
51070-301 = "3;카에데;11\n#3;black\n#3;closeup"
51070-303 = "3;카에데;11\n#3;em;[재잘]\n#3;hophop\n#3;a\n#3;closeup\n#wait;1700"
51070-304 = "[ns] \"카에데?!\""
51070-306 = "3;유카리;04;서, 선생님?! 괜찮으시와요?!\n#3;em;[?!]\n#3;shake"
51070-307 = "3;카에데;11\n1;미모리;04;카, 카에데 쨩?! 그렇게 달려들면 선생님께서 곤란해하시니까요!\n#1;em;[땀]\n#1;hophop\n#1;ar\n#3;m5"
51070-308 = "5;츠바키;07;후아아암…….\n#5;em;…\n#5;al\n#3;m3"
51070-309 = "[s] \"카에데랑 미모리, 거기다 츠바키까지……?\""
51070-310 = "5;츠바키;07\n1;미모리;04\n3;카에데;11\n#3;h\n#1;h\n#5;h\n#wait;100"
51070-312 = "#nextepisode;다음화;청춘(?)에 매진하는 소녀 2"
