[translation]
51170-1 = "ตอนที่ 17;ปีศาจเดินขบวน 1"
51170-2 = "จัตุรัสที่จัดเทศกาลโคมไฟ"
51170-4 = "ทุกอย่างพร้อมแล้วค่ะ!"
51170-5 = ""
51170-7 = ""
51170-9 = ""
51170-10 = ""
51170-12 = "ขอเชิญพบกับคุณมิโกะค่า!"
51170-13 = ""
51170-15 = ""
51170-19 = ""
51170-20 = "ว้าว! เข้ากับคุณหนูมากเลยเจ้าค่ะ ตามที่คาดไว้เลย!"
51170-22 = "รู้สึกไม่สบายตัวตรงไหนหรือเปล่าคะ? หรือว่าอยากได้อะไรเพิ่มไหม..."
51170-24 = "ไม่เป็นไรเจ้าค่ะ ข้าชินกับชุดแบบนี้แล้ว"
51170-25 = "ฮุฮุ! เจ้าค่ะ! สมกับที่เป็นคนจากตระกูลคาเดโนะโคจิ! การได้เห็นคุณหนูทำหน้าที่ในวันนี้คือสิ่งที่#nพวกข้าปรารถนามาตลอดเจ้าค่ะ!"
51170-26 = "ข้าละโล่งใจเหลือเกินที่คุณหนูออกจากเฮียกกะเรียวรัน แล้วกลับมาทำงานของตระกูลแบบนี้...!"
51170-27 = "ใช่เจ้าค่ะ! สิ่งนี้จะทำให้ทุกอย่างกลับไปถูกต้องเหมือนเดิม ไม่มีอะไรให้กังวลอีกต่อไปแล้วเจ้าค่ะ!"
51170-28 = ""
51170-31 = ""
51170-32 = "อะแฮ่ม ยูคาริ"
51170-33 = "อย่างที่ทราบกันว่าไคลแมกซ์ของงานเทศกาลในครั้งนี้คือระบำพิธีกรรมจาก <คุณมิโกะแห่งตระกูลคาเดโนะโคจิ> ค่ะ"
51170-34 = "เราเตรียมอุปกรณ์ถ่ายทอดสดไว้เรียบร้อยแล้ว ทุกคนในเฮียกคิยาโคสามารถรับชมระบำจากยูคาริได้#nทั้งทางโทรทัศน์และอินเทอร์เน็ต..."
51170-35 = "และความหมายของระบำก็คือการส่งท้ายปีเก่าต้อนรับปีใหม่..."
51170-37 = "ใช่ค่ะ! เป็นระบำเพื่อแสดงความปรารถนาในวันพรุ่งนี้ที่ดีกว่า และเพื่ออนาคตที่สดใสกว่าเดิมค่ะ!"
51170-38 = "น่าเสียดายที่ขนบธรรมเนียมนี้ไม่ได้รับการสืบทอดมา 20 ปีแล้ว แต่ในที่สุดเราก็จะได้รับชมกันวันนี้ค่ะ!"
51170-39 = "ฉันเองก็ตื่นเต้นมากเลยค่ะ!"
51170-40 = ""
51170-43 = ""
51170-44 = "สำหรับลำดับขั้นของพิธีกรรม เราได้หาข้อมูลและสรุปเตรียมไว้ให้แล้ว..."
51170-45 = "ฮุฮุ ถ้าเรื่องนั้นละก็ ไม่ต้องห่วงหรอกเจ้าค่ะ คุณหนูได้ร่ำเรียน <ระบำ> ที่เกี่ยวข้องกับพิธีกรรมมาตั้งแต่#nยังเล็กๆ แล้วเจ้าค่ะ"
51170-46 = "...งั้นเหรอคะ?"
51170-48 = "เจ้าค่ะ นั่นเป็นงานและหน้าที่ที่ข้าต้องทำอยู่แล้ว"
51170-49 = "ไม่ต้องห่วงหรอกเจ้าค่ะ เรื่องลำดับขั้นตอนของพิธีน่ะ ข้าจำได้หมดแล้ว"
51170-50 = "ถ้าอย่างนั้นก็ค่อยยังชั่วหน่อย..."
51170-51 = "...แต่จะไม่เป็นไรจริงๆ ใช่ไหมคะ...?"
51170-52 = "เจ้าค่ะ"
51170-53 = "ข้า..."
51170-54 = "ข้า... ไม่เป็นไรเจ้าค่ะ"
51170-55 = "เข้าใจแล้วค่ะ"
51170-56 = "เอาละ งั้นก็ไปขึ้นเวทีเลยค่ะ!"
51170-57 = ""
51170-59 = ""
51170-60 = ""
51170-61 = "เจ้าค่ะ... เรื่องราวทั้งหมด"
51170-62 = ""
51170-64 = ""
51170-66 = "คงจะต้องเป็นแบบนี้"
51170-67 = ""
51170-72 = "เรื่องมันก็เป็นอย่างนี้แหละ"
51170-73 = "ศึกชิงตำแหน่งกับยูคาริ... เธอทำลงไปจริงๆ เหรอเนี่ย..."
51170-74 = "ไม่สิ ฉันไม่อยากจะเชื่อตั้งแต่ที่บอกว่ายูคาริจะเปิดศึกชิงตำแหน่งกับเธอแล้ว แต่ก็เอาเถอะ..."
51170-75 = "...แล้วทำไมถึงมาบอกเรื่องนี้กับฉันล่ะ?"
51170-76 = "......"
51170-77 = "ยูคาริไปหาเธอก่อนที่จะมาห้องไกล่เกลี่ยใช่ไหม?"
51170-78 = "ในแง่ของความเป็นพี่เป็นน้องกันแล้ว ฉันคิดว่าฉันจำเป็นต้องบอกให้รู้ไว้น่ะ"
51170-79 = "ยูคาริ... ต่อให้พูดถึงขนาดนั้นแล้วก็ยังไม่ล้มเลิกสินะ..."
51170-80 = "ชิ! แล้วยังไงล่ะ ฉันเตือนไปแล้วนี่ว่าต่อให้กลับไปมันก็ไม่มีประโยชน์อะไรอยู่ดี"
51170-81 = "งั้นก็พอกันที คิเคียว"
51170-82 = "...พอกันทีงั้นเหรอ?"
51170-83 = "เธอไม่ต้องติดต่อฉันมาเหมือนมีอะไรติดค้างอยู่แบบนี้หรอก"
51170-84 = "ไม่ต้องใส่ใจด้วย มันไม่มีประโยชน์ ฉัน... ตัดสินใจแล้วน่ะว่าจะไปตามหาชีวิตวัยรุ่นของฉัน"
51170-85 = "กับเฮียกกะเรียวรันที่จบไปแล้วน่ะ เรื่องนั้นฉันไม่สนใจหรอก"
51170-86 = ""
51170-88 = ""
51170-90 = ""
51170-91 = "......... ก็ได้"
51170-92 = "เธอก็เป็นอย่างนั้นแหละ เธอออกไปเพื่อสิ่งนั้น"
51170-93 = "เข้าใจแล้ว... เธอพูดได้ดีแล้วละ ฉันก็เห็นด้วย เอาเป็นว่าเราคุยกันจบแค่ตรงนี้แล้วกัน เรนเกะ เธอเองก็ทำตามใจตัวเองเถอะ"
51170-94 = "ในฐานะเพื่อน อย่างน้อยฉันก็จะหวังให้เธออยู่ดีกินดี มีความสุขในอนาคต"
51170-95 = "ขอให้กินเก่งจนอ้วนจ้ำม่ำอีกสัก 10 กิโลเลย"
51170-96 = "ว่าไงนะ?! นี่เธอ เดี๋ยวก่อน...!"
51170-97 = ""
51170-99 = ""
51170-100 = "อะไรกัน คิดจะพูดแต่สิ่งที่ตัวเองอยากพูดแล้วก็หนีเลยงั้นเหรอ?! ยัยคิเคียว!"
51170-101 = "อึก......!"
51170-102 = "เธอนั่นแหละต้องกินข้าวเยอะๆ ล่ะ รู้มั้ย?! ฮึ่ม!"
51170-103 = "ฮู่ว... ฮู่ว... เฮ้อ... จริงๆ เลย..."
51170-104 = "มันจบไปแล้วไม่ใช่เหรอ แล้วทำไมถึงยัง..."
51170-106 = "ว้ายยย?!"
51170-107 = "อะไรเหรอ?! เกิดเรื่องอะไรน่ะ?! รุ่นพี่เรนเกะ!"
51170-108 = "เรนเกะจัง?"
51170-109 = "ฮ้าววว"
51170-110 = ""
51170-113 = ""
51170-114 = "มะ... ไม่มีอะไรหรอก"
51170-115 = "ก็แค่เรื่องของทางนี้... เรื่องที่จบไปแล้วน่ะ"
51170-116 = "เรื่องของเฮียกกะเรียวรันใช่ไหมคะ?"
51170-117 = "มันก็ใช่..."
51170-118 = "ไม่หรอก จากนี้ไม่เป็นไรแล้ว! กับอีแค่เรื่องของเฮียกกะเรียวรัน ฉันไม่สนหรอก!"
51170-119 = "ฮืม มีงานเทศกาลแบบนี้ทั้งที แค่สนุกกับเทศกาลในฐานะสมาชิกชมรมฝึกฝนก็ยุ่งมากอยู่แล้ว ฉันไม่มีเวลาว่างมาใส่ใจเรื่องอื่นที่ไม่มีประโยชน์หรอก"
51170-120 = "เพราะว่า... การสนุกกับเทศกาลก็เป็นส่วนหนึ่งของการฝึกฝน! ชีวิตวัยรุ่นไม่เคยรอใคร อย่างน้อยตอนนี้ก็ต้องใช้ชีวิตวัยรุ่นให้คุ้มหน่อยสิสาวๆ!"
51170-121 = "ใช่มั้ย? หัวหน้าสึบากิ รองหัวหน้ามิโมริ คาเอเดะ"
51170-122 = ""
51170-124 = ""
51170-126 = ""
51170-127 = "โกหกไม่เก่งเลยนะคะ เรนเกะจัง"
51170-129 = "หืม...?"
51170-131 = ""
51170-132 = "ก็แค่เรื่องของเฮียกกะเรียวรันงั้นเหรอคะ ใจจริงแล้วไม่ได้คิดแบบนั้นสักหน่อย?"
51170-133 = "ใช่! รุ่นพี่เรนเกะ ถึงจะเข้าชมรมนี้มาแต่ก็พูดเรื่องเฮียกกะเรียวรันไม่หยุดเลย ไม่รู้ตัวเหรอว่ายังตัดใจไม่ได้น่ะ!"
51170-135 = "มะ... ไม่ใช่นะ...! ฉันก็ไม่ถึงกับขนาดนั้น..."
51170-136 = "ถ้าไม่ได้สนใจแม้แต่นิดเดียวจริงๆ... ก็คงไม่รับโทรศัพท์ แล้วก็คงไม่โมโหแบบนั้นด้วยนะ"
51170-137 = ""
51170-139 = ""
51170-141 = "สึบากิจังพูดถูกค่ะ เรนเกะจัง ไม่ได้อยากให้เฮียกกะเรียวรันจบไปทั้งแบบนี้ใช่ไหมคะ?"
51170-142 = "ฮุฮุ ถึงจะอยากปฏิเสธ แต่รุ่นพี่มิโมริเป็นนักอ่านใจที่เก่งที่สุดในสหพันธ์เฮียกคิยาโคเลยนะ! รุ่นพี่มิโมริอ่านใจรุ่นพี่เรนเกะออกหมดแล้วละ!"
51170-143 = "โกหกไปก็เปล่าประโยชน์อยู่ดีละนะ รุ่นพี่เรนเกะ!"
51170-144 = "มะ... ไม่ขนาดนั้นหรอก คาเอเดะจัง! ฉันไม่ได้อ่านใจใครหรอกนะคะ~!"
51170-145 = ""
51170-147 = ""
51170-149 = ""
51170-150 = "...ทำไมทุกคนถึงพูดแบบนั้นล่ะ?"
51170-151 = "มันเป็นเรื่องที่... จบไปแล้วไม่ใช่เหรอ"
51170-152 = "ต่อให้พูดอีกกี่ครั้ง ไม่ว่าจะรุ่นพี่นางุสะ ไม่ว่าจะสมาชิกคนอื่นๆ... รวมถึงคนที่ไม่น่าออกจากชมรมไป ก็ไม่กลับมาหรอก"
51170-153 = "ฉันว่าปล่อยให้... ทุกอย่างมันจบลงแหละดีแล้ว"
51170-154 = "นี่ฉันก็แค่ละทิ้งทุกอย่าง... แล้วออกมาตามหาชีวิตวัยรุ่นเหมือนคนอื่น แต่แล้ว... ทำไม..."
51170-155 = "แต่เรนเกะก็อ่อนโยนต่อยูคาริมากนะ"
51170-156 = "ฉันน่ะเหรอ...? อ่อนโยนกับยูคาริ? ไม่ใช่สักหน่อย"
51170-157 = "ตอนนั้นฉันเอาแต่พูดจาทำร้ายจิตใจยูคาริ..."
51170-158 = "เรนเกะบอกว่าชมรมที่คนรอต้องเจ็บปวดหัวใจ ชมรมแบบนั้นไม่ต้องมีก็ได้"
51170-159 = "ที่เรนเกะพูดออกไปตอนนั้น... ฉันว่าทุกคนน่าจะรู้ว่าเรนเกะพูดด้วยความเอาใจใส่ ด้วยความหวังว่า#nรุ่นน้องจะไม่ต้องเจ็บปวด... ที่เรนเกะพูดแบบนั้นเพราะเห็นแก่ยูคาริยังไงล่ะ"
51170-160 = "แล้วก็ยังพูดด้วยนะคะว่าเป็นเพื่อนกับคิเคียวจังมาตั้งแต่สมัยเด็ก"
51170-161 = "......"
51170-162 = "คนเราน่ะ บางทีก็พูดในเรื่องที่ไม่ตรงกับความรู้สึกของตัวเองเพราะความเป็นห่วงนะ"
51170-163 = "ยิ่งเป็นห่วงมาก บางทีก็เลยโกรธจนเผลอพูดอะไรที่อาจจะเก็บมาเสียใจภายหลังออกไปโดยไม่รู้ตัว..."
51170-164 = "ฉันรู้ดีเพราะเคยทำแบบนั้นน่ะค่ะ"
51170-166 = "รุ่นพี่มิโมริก็ด้วยเหรอ?! จริงเหรอ?!"
51170-167 = "ฮุฮุ ใช่ค่ะ คาเอเดะจัง"
51170-168 = "ฉันเองก็เป็นเพื่อนสมัยเด็กของสึบากิจังนี่คะ? ระหว่างเราก็มีเรื่องอะไรเกิดขึ้นเยอะแยะเลยด้วย"
51170-169 = "ใช่ไหมคะ? สึบากิจัง"
51170-171 = "ตอนที่มิโมริโกรธน่ะ น่ากลัวจริงๆ นะ..."
51170-173 = "โอ้ว! ฉันเองก็เหมือนจะเข้าใจแล้วเลย!"
51170-174 = "คะ... คะ?!"
51170-175 = "สองคนนี้น่ะ จริงๆ เลยนะคะ..."
51170-176 = ""
51170-178 = ""
51170-179 = "เพราะงั้น เรนเกะจัง"
51170-180 = ""
51170-183 = ""
51170-184 = "ฉัน..."
51170-185 = "ฉันออกจากเฮียกกะเรียวรันมาแล้ว... และมาลองทำกิจกรรมของชมรมฝึกฝนแล้ว จะให้ไปทำอะไรน่าละอายใจได้ไง..."
51170-186 = "แต่เรนเกะจังก็ยังมีสิ่งที่อยากบอกให้คนสำคัญรู้ไม่ใช่เหรอคะ?"
51170-187 = "...ยังไม่สายไปงั้นเหรอ... มันจะไม่ดู... หน้าไม่อายเหรอ...?"
51170-188 = "คิดแค่ว่าอยากทำเรื่องสำคัญหรือไม่ก็พอค่ะ เรนเกะจัง"
51170-189 = "รองหัวหน้ามิโมริ..."
51170-190 = ""
51170-192 = ""
51170-194 = ""
51170-195 = "...การทดลองทำกิจกรรมชมรมของเรนเกะสิ้นสุดเพียงเท่านี้ นี่คือคำสั่งของหัวหน้าชมรม"
51170-197 = "หืม?!"
51170-199 = "ตอนนี้คือเวลาที่ต้องทำสิ่งที่อยากทำนะ ถ้าเป็นเรื่องนั้นละก็..."
51170-200 = "พวกเราเองก็จะช่วยอีกแรงค่ะ"
51170-201 = "ด้วยความผูกพันของชมรมฝึกฝน! ใช่มั้ยล่ะ?!"
51170-203 = "สึบากิ มิโมริ คาเอเดะ..."
51170-204 = ""
51170-206 = ""
51170-207 = ""
51170-208 = ""
51170-209 = "อื้ม... ฉันมีเรื่องที่อยากทำอยู่น่ะ"
51170-210 = ""
51170-211 = "คิเคียวบอกฉันไว้น่ะ"
51170-212 = "ว่าฉันพูดแรงกับยูคาริไปหน่อย"
51170-213 = "เพราะงั้น... ก็เลยกังวลขึ้นมา และอยากให้ฉันไปดูยูคาริหน่อย"
51170-215 = "...สั่งให้คนอื่นทำในสิ่งที่ตัวเองก็ทำได้ ก็ดูเป็นเรื่องที่เข้ากับยัยคิเคียวอยู่หรอก"
51170-216 = "แต่ฉันก็อยากจะไปหายูคาริแล้วคุยกับเธอดู"
51170-218 = ""
51170-219 = "ค่ะ ถ้าอย่างนั้นเราก็ไปด้วยกันเลยค่ะ"
51170-220 = "ดีละ! ออกเดินทางพร้อมกันสินะ!"
51170-222 = "ขอบใจนะทุกคน"
51170-223 = ""
51170-226 = ""
51170-230 = "อ๊ะ ดอกไม้ไฟ!"
51170-231 = "เทศกาลโคมไฟเริ่มต้นขึ้นอย่างเป็นทางการแล้วสินะคะ"
51170-232 = "พวกเรารีบไปกันเถอะค่ะ ก่อนจะไม่ทัน..."
51170-233 = ""
51170-237 = "ว้ากกก นะ... หนีไป!"
51170-238 = ""
51170-241 = ""
51170-242 = "มีเรื่องอะไรเหรอ?"
51170-243 = ""
51170-246 = ""
51170-247 = ""
51170-248 = ""
51170-250 = ""
51170-252 = ""
51170-253 = "...เอ๋?! รุ่นพี่สึบากิ! รุ่นพี่มิโมริ! นะ... นั่นมันอะไรน่ะ?!"
51170-254 = "!!"
51170-255 = ""
51170-256 = "...ไม่รู้เลยว่าคืออะไร แต่ไม่น่าจะใช่พวกที่น่าผูกมิตรด้วยเลยนะ"
51170-257 = ""
51170-259 = ""
51170-261 = ""
51170-264 = ""
51170-266 = "อึก...! ทุกคนระวังให้ดี!"
51170-267 = "มาแล้ว!"
51170-268 = ""
51170-276 = ""
51170-278 = "นะ... นะ... นะ... นี่มันอะไรกัน?!"
51170-279 = ""
51170-281 = ""
51170-282 = ""
51170-284 = "วะ... ว้ายยย!!"
51170-285 = ""
51170-289 = ""
51170-291 = ""
51170-293 = ""
51170-295 = ""
51170-297 = "หัวหน้า! เป็นยังไงบ้างคะ?!"
51170-298 = "หัวหน้าาาา~!"
51170-300 = "อ่า... อื้ม! ข้าน้อยไม่เป็นไร...!"
51170-301 = "แต่ว่า... ลานเทศกาลเละหมดแล้ว...!"
51170-302 = "ปีศาจพวกนั้นออกมาจากตรงไหนน่ะ?!"
51170-304 = "หัวหน้า... นี่มันเหมือนกับตอนที่ท้องฟ้าเป็นสีแดงตอนนั้นเลย..."
51170-305 = "คะ... คะ?! มะ... เหมือนกับตอนนั้น... งั้นเหรอคะ?!"
51170-306 = "ทะ... ท่านหัวหน้า! อิซุนะจัง!! ทะ... ทำยังไงดีล่ะคะ?!"
51170-308 = "ขะ... ขะ... ข้าน้อยก็ไม่รู้เหมือนกัน!"
51170-309 = "พวกมันออกมาจากทุกทิศทางเลย...! ระ... เราต้องเริ่มทำอะไรจากตรงไหนก่อนเนี่ย...!"
51170-310 = ""
51170-312 = ""
51170-314 = "(ระ... หรือว่าต้องหนี?!)"
51170-315 = "(แต่ว่า... ถ้ายังมีคนอยู่ในลานเทศกาลก็อันตราย...)"
51170-316 = "(แต่ว่า! ในฐานะหัวหน้าชมรม เราจะให้อิซุนะกับสึคุโยะต้องตกอยู่ในอันตรายไม่ได้...!)"
51170-317 = ""
51170-320 = ""
51170-321 = ""
51170-322 = ""
51170-324 = "ว้ายยย!!"
51170-325 = "ท่านหัวหน้า!!"
51170-326 = ""
51170-329 = ""
51170-330 = ""
51170-332 = "ไม่เป็นไรค่ะ! หัวหน้า! ท่านสึคุโยะ! ไม่ต้องห่วงนะคะ!"
51170-334 = ""
51170-335 = "อะ... อิซุนะ?"
51170-336 = "อิซุนะจัง...?"
51170-338 = "ตอนนี้นายท่านอยู่ที่สหพันธ์เฮียกคิยาโคค่ะ!"
51170-339 = "นายท่านมาขอความช่วยเหลือจากพวกเราชมรมวิจัยศาสตร์นินจาน่ะค่ะ!"
51170-340 = ""
51170-343 = ""
51170-345 = "เพราะงั้นอิซุนะจะพยายามให้เต็มที่เลย!"
51170-346 = "...อื้ม! อิซุนะพูดถูกแล้วละ! ก่อนอื่นมาช่วยเหลือผู้คนที่นี่กันเถอะ!"
51170-347 = "ถ้าเกิดเรื่องแบบนี้... ท่านอาจารย์จะต้องทำอะไรสักอย่างแน่ๆ!"
51170-348 = ""
51170-350 = ""
51170-352 = "ระหว่างนี้พวกเราชมรมวิจัยศาสตร์นินจา... ในฐานะสายลับพิเศษของเฮียกคิยาโคจะไปช่วยคนที่ตกอยู่#nในอันตรายก่อน!"
51170-354 = "ค่ะ... ค่ะ! รับทราบค่ะ!"
51170-355 = "ถ้างั้นก็! ออกปฏิบัติการค่ะ! นินนิน!"
51170-365 = "รองหัวหน้าคาโฮะ! ตอนนี้มีใครก็ไม่รู้ออกมาก่อความวุ่นวายอยู่ที่ชายขอบนอกลานงานเทศกาล"
51170-366 = "เราได้ข่าวว่ามีผู้ได้รับบาดเจ็บจากความวุ่นวายที่เกิดขึ้นในฝั่งตะวันตกเรื่อยๆ เลย!"
51170-367 = "รองหัวหน้าคาโฮะ! กลุ่มการค้าแจ้งมาว่ามีปีศาจปริศนาปรากฏตัว...!"
51170-369 = "รองหัวหน้าคาโฮะ! ต้องทำยังไงดี...!"
51170-371 = "ทุกคนใจเย็นๆ กันก่อนนะคะ! ตั้งสติกันก่อน...!"
51170-372 = "นี่มัน... อะไรกัน..."
51170-373 = "<สิ่งลึกลับน่าขนลุก> มาปรากฏตัวในงานเทศกาลงั้นเหรอ... จะทำยังไงดี... คุณนิยะ!"
51170-374 = ""
51170-376 = ""
51170-378 = ""
51170-379 = "จู่ๆ ก็เกิดการโจมตีปริศนาในจังหวะจัดงานเทศกาล... เบาะแสที่เราพอจะคาดคะเนได้ของเรื่องที่เกิดขึ้น#nตอนนี้..."
51170-380 = "มีอยู่อย่างเดียว"
51170-382 = "...ชมรมความงามของธรรมชาติ"
51170-383 = ""
51170-387 = "...ฉันมองว่าจดหมายฉบับนั้นเป็นการข่มขู่ถึงเหตุการณ์จลาจลในเฮียกคิยาโค"
51170-388 = ""
51170-392 = "ก็เลยไปดึงชาเล่ต์เข้ามาเอี่ยวใน <ข่าวลือ> ที่น่าสับสนนั่น... นี่เป็นการตัดสินใจที่แย่ที่สุดของฉันเลย"
51170-393 = "ว่าแต่... ฉันอ่านเกมผิดพลาดตั้งแต่แรกเลยเหรอ?"
51170-395 = "ชมรมความงามของธรรมชาติควรจะเป็นแค่เรื่องลึกลับที่หลงเหลืออยู่ในบันทึกและข่าวลือเท่านั้น"
51170-396 = "จะบอกว่า... มันมีอยู่จริงงั้นเหรอ?"
51170-397 = "นี่ฉันพลาดอะไรไปตอนไหนนะ? มีปัจจัยที่ไม่ได้คำนึงถึง... หรือมีเบาะแสที่มองไม่เห็นงั้นเหรอ?"
51170-399 = "คุณนิยะ"
51170-401 = "...ถ้าพิจารณาจากจังหวะที่ปรากฏตัวแล้ว หรือว่าพวกนั้นจะมีความเกี่ยวข้องกับเรื่องของคุซึโนฮะ? หรือว่า..."
51170-402 = "คุณนิยะ..."
51170-403 = "เกี่ยวกับเฮียกกะเรียวรันเหรอ...? เรื่องที่หัวหน้าหายตัวไป ถึงฉันจะคิดว่ามันน่าสงสัยอยู่หน่อยๆ ก็เถอะ แต่ทางนั้นมีข้อมูลอะไรที่จงใจซ่อนไว้หรือเปล่า?"
51170-404 = "หรือจริงๆ ฉันควรเค้นถามจากทางนั้นตั้งแต่แรกเพื่อป้องกันภัยคุกคาม?"
51170-405 = "คุณนิยะ...!"
51170-406 = "ข้อมูลที่ฉันไม่รู้... ความลับที่วิเคราะห์ไม่ได้... ต้องรู้ให้ได้ว่าความผิดพลาดร้ายแรงเกิดขึ้นตรงไหน..."
51170-407 = ""
51170-409 = ""
51170-411 = "นิยะ...!"
51170-412 = ""
51170-421 = ""
51170-422 = "หัวหน้านิยะ นี่แน่ะ ดีดหน้าผากซะเลย"
51170-423 = ""
51170-427 = ""
51170-429 = ""
51170-430 = "อึ้กกก?! ชะ... ชิเซะ...?!"
51170-431 = "ชิเซะจัง?!"
51170-432 = ""
51170-434 = ""
51170-436 = "......"
51170-437 = "!!"
51170-438 = "ต่อให้น่ากลัว"
51170-439 = "อย่ามัวเมินหนี"
51170-440 = "พร้อมพลีใจลุย"
51170-441 = "หัวหน้านิยะ จะอยู่เฉยๆ ไม่ได้นะ"
51170-442 = "ดูสิ ทุกคนกำลังกลัวนะ"
51170-443 = ""
51170-445 = ""
51170-447 = "ชิเซะจัง..."
51170-448 = "...อ่า"
51170-449 = "อ่า..."
51170-450 = "....."
51170-451 = ""
51170-453 = ""
51170-454 = ""
51170-455 = "อะฮะฮ่า ชิเซะพูดถูกแล้วละ"
51170-456 = "ถ้าหัวหน้าชมรมหยินหยางเอาแต่เก็บตัวอยู่ที่นี่แบบนี้ก็เป็นตัวอย่างที่ดีให้ทุกคนไม่ได้น่ะสิ~"
51170-457 = "คาโฮะ ติดต่อชมรมเทศกาลให้หน่อย แล้วถามสถานการณ์ตอนนี้มาให้ด้วย"
51170-459 = "ค่ะ... ได้ค่ะ!"
51170-460 = ""
51170-462 = ""
51170-466 = "อ่า ตอนนี้เชื่อมต่อสัญญาณไม่ได้เลยค่ะ น่าจะมีอะไรมารบกวนการติดต่อ..."
51170-467 = "งั้นเหรอ? มันก็น่าเข้าใจได้อยู่หรอกนะ ก็วุ่นวายกันเสียขนาดนี้นี่เนอะ"
51170-468 = "อืม งั้นก็ช่วยไม่ได้ ก็ดี งั้นฉันจะออกไปหาเอง"
51170-469 = "แต่ว่าคาโฮะ เธอช่วยขอข้อมูลจากกลุ่มการค้าเฮียกคิยาโคที่เคยให้ความร่วมมือในการจัดงานเทศกาล#nให้หน่อยได้มั้ย?"
51170-470 = "ตอนนี้เราต้องจัดระเบียบสถานการณ์และเตรียมหลักฐานที่จะตัดสินใจได้อย่างครอบคลุมก่อน ฝากจัดระเบียบและรวบรวมข้อมูลตามเวลาและสถานที่ให้ฉันหน่อยนะ"
51170-471 = "ส่วนเรื่องที่ตัดสินใจผิดพลาดน่ะ เอาไว้มาจัดการทีหลัง"
51170-473 = "....ค่ะ! รับทราบค่ะ! วางใจฉันได้เลยค่ะ!"
51170-474 = "ทุกคน! ได้ยินแล้วใช่ไหมคะ? จากนี้ชมรมหยินหยางจะเคลื่อนไหวตามคำสั่งของคุณนิยะค่ะ!"
51170-476 = "ตั้งแต่บัดนี้ไปคือการแข่งขันกับเวลาค่ะ! เราต้องพยายามอย่างเต็มที่ ฝากทุกคนด้วยนะคะ!"
51170-477 = "ได้ค่ะ!!"
51170-479 = "ตอนต่อไป;ปีศาจเดินขบวน 2"
