[translation]
51240-1 = "ตอนที่ 24;เรื่องธรรมดา"
51240-3 = "ฉันไม่อยากเป็นคนที่น่าอายของอายาเมะ"
51240-4 = "ฉันกลัวว่าตัวตนที่แท้จริงจะถูกเปิดเผย ก็เลย... แสร้งแสดงเป็นคนที่เหมาะสมกับอายาเมะ"
51240-5 = ""
51240-7 = ""
51240-9 = ""
51240-15 = "พอย้อนกลับไปมอง ฉันก็เห็นว่าคนอื่นคาดหวังในตัวฉันอยู่"
51240-16 = "ฉันก็เลยกลัว"
51240-17 = ""
51240-19 = "เพราะฉันไม่ใช่คนอย่างนั้น ทุกคนเข้าใจผิดในตัวฉันอยู่"
51240-20 = "ทุกคนเข้าใจว่าฉันเก่ง มีความสามารถโดดเด่น และดีพอเทียบเท่าอายาเมะได้"
51240-21 = ""
51240-22 = "แต่ฉัน... แค่อยากเป็นคนที่อายาเมะภูมิใจก็เท่านั้น"
51240-23 = "ฉันก็แค่ดิ้นรนบากบั่นอย่างสุดชีวิต... เพื่อให้เป็นอย่างนั้น แต่ว่า..."
51240-25 = "[ns] \"ถ้าอย่างนั้น แค่นั้นก็เพียงพอแล้ว\""
51240-26 = "......?!"
51240-27 = ""
51240-32 = ""
51240-33 = ".........ว่ายังไง... นะคะ?"
51240-34 = "[ns1] \"การแสร้งทำเป็นคนอื่นที่ไม่ใช่ตัวเอง...\"\n[ns2] \"แล้วหวังให้มันเป็นความจริง มันผิดตรงไหน?\""
51240-35 = ""
51240-36 = ""
51240-39 = "[ns3] \"ต่อให้เป็นเรื่องโกหก แต่หากพยายามรักษามันมาตลอด...\"\n[ns4] \"สุดท้ายแล้วมันก็จะเป็นจริงได้\""
51240-42 = "[ns5] \"การที่ใครสักคนจะพยายามตบแต่งตัวเองขึ้นมาน่ะ...\"\n[ns6] \"มันเป็นเรื่องธรรมดาของทุกคนนั่นแหละ...\""
51240-46 = "[ns] \"เป็นเรื่องปกติที่ไม่ว่าใครก็ทำกัน\""
51240-47 = "อะไรกัน..."
51240-48 = "คิดว่าจะคลี่คลายสถานการณ์ด้วยการใช้วาทศิลป์แบบนั้นเหรอคะ?"
51240-49 = "การโกหกยังไงก็เป็นการโกหกวันยังค่ำ... และสุดท้ายมันก็จะสร้างบาดแผลให้ทุกคน จนนำมาสู่โศกนาฏกรรมแบบนี้ไงคะ"
51240-50 = "[s] \"ต่อให้มันเป็นเรื่องโกหกต่อตัวเอง แต่กับคนอื่นอาจไม่ใช่แบบนั้นก็ได้\""
51240-51 = ""
51240-53 = ""
51240-56 = "(อย่างตอนที่ยูคาริได้เจอนางุสะเป็นครั้งแรก)"
51240-59 = "บาดเจ็บตรงไหนหรือเปล่า?"
51240-60 = "กล้าเผชิญหน้าอย่างไม่ท้อถอย แม้จะมีความอยุติธรรมอยู่ตรงหน้า"
51240-61 = ""
51240-63 = ""
51240-64 = ""
51240-65 = "เท่สุดๆ ไปเลย"
51240-66 = "......!"
51240-67 = "จากนี้ไปให้พวกเราเฮียกกะเรียวรันเป็นคนจัดการเอง"
51240-69 = "(อย่างตอนที่สมาชิกเฮียกกะเรียวรันอยู่ด้วยกัน)"
51240-72 = "เรนเกะ... เป็นเด็กที่เก่งกาจมาก ...คนไม่ได้เรื่องอย่างฉันเทียบเรนเกะไม่ติดเลยละ"
51240-73 = "ฉันภูมิใจในตัวเรนเกะมาก ยูคาริเองก็คิดเหมือนกันใช่ไหม?"
51240-74 = "เจ้าค่ะ!"
51240-75 = "ยูคาริ... นั่นแปลว่าเรนเกะเหนือกว่ารุ่นพี่นางุสะนะ"
51240-76 = "เฮือก...?!"
51240-77 = "พวกเธอนี่ พอกันได้แล้ว แบบนี้คนฟังเค้าก็เขินเป็นนะ?!"
51240-78 = "ฉันไม่ได้ดีใจหรอกนะที่ได้ยินคำแบบนั้นจากคนที่ยอดเยี่ยมแบบนั้นน่ะ ฉันอายมากกว่าอีก"
51240-79 = ""
51240-81 = ""
51240-83 = "...ฮุฮุ"
51240-85 = "(อย่างตอนที่ตัดสินใจเด็ดเดี่ยวว่าจะออกจากเฮียกกะเรียวรัน)"
51240-87 = "คิเคียว เธอน่ะเก่งมากนะ สมาชิกของเราเชื่อฟังเธอในฐานะที่ปรึกษายุทธศาสตร์ของเฮียกกะเรียวรัน"
51240-88 = "...แถมไม่ใช่กับแค่สมาชิกด้วย ฉันเองก็เหมือนกัน"
51240-91 = "[ns] \"ถึงตอนแรกมันอาจจะเป็นแค่การแสดง แต่มันก็ช่วยให้...\""
51240-93 = "[ns7] \"มันช่วยให้นางุสะได้รู้จักเพื่อนทั้งสามมากกว่าใคร\"\n[ns8] \"ช่วยทำให้เป็นคนที่เข้าอกเข้าใจคนอื่นด้วย\""
51240-96 = "[ns] \"ใช่... เป็นเหมือนใครบางคน... ที่นางุสะใฝ่ฝัน\""
51240-97 = "......!!!"
51240-98 = "[s] \"การคอสเพลย์หรือพยายามดิ้นรนเพื่อให้อยู่ตรงนั้นได้มันผิดตรงไหน?\""
51240-99 = "ต่อให้มันทำให้ทุกคนแตกคอกันและทะเลาะกันน่ะเหรอคะ?!"
51240-100 = "ต่อให้รู้ว่ามันจะสร้างบาดแผล! ก่อความท้อแท้! และกลายเป็นความแค้นในที่สุด ก็ยังจะพูดแบบนั้นออกมาอีกเหรอ...!"
51240-101 = "[s9] \"ที่จริง... การอยู่ร่วมกันในสังคม\"\n[s10] \"อาจจะมีทั้งเรื่องให้เกลียดหรือทะเลาะกันก็ได้\""
51240-104 = "[ns] \"แล้วก็มีเรื่องให้พูดให้ร้ายและสร้างแผลในใจด้วย\""
51240-107 = "[ns] \"แต่เรื่องแบบนี้เป็นเรื่องธรรมดาที่เกิดขึ้นได้กับทุกคน\""
51240-109 = "[ns11] \"ขอแค่เราพยายามคืนดีกันหลังทะเลาะกันก็พอ\"\n[ns12] \"และครูก็จะพยายามอย่างเต็มที่ให้ทุกคนคืนดีกันได้\""
51240-110 = ""
51240-111 = ""
51240-113 = ""
51240-114 = "............พูดอะไรเพ้อเจ้อ"
51240-115 = "กับอีแค่คำพูดโลกสวยแบบนั้นน่ะ..."
51240-116 = "คำพูดพวกนั้นน่ะ...! มันไม่สง่างามเลยสักนิด! มันเป็นเรื่องเล่าที่แย่ที่สุด!"
51240-117 = "คำพูดเหลวไหลที่เหยียบย่ำ <ตำนานร้อยเรื่องราว> น่ะ ฉันจะเหยียบย่ำมันให้หมดเอง...!"
51240-118 = "ครูจากชาเล่ต์! เริ่มที่แกก่อนเลย...!"
51240-119 = ""
51240-123 = "ข้าไม่ยอมให้ทำแบบนั้นหรอกเจ้าค่ะ!"
51240-124 = ""
51240-127 = ""
51240-128 = ""
51240-131 = ""
51240-132 = "[ns] \"ยูคาริ...!\""
51240-133 = ""
51240-136 = ""
51240-137 = "ฟื้นขึ้นมาได้... เหรอคะ? คุณโดนคาตาชิโระกลืนกินไปแล้วนี่? ทำไมถึง...?"
51240-139 = "ข้าได้ยินเสียงจากในความมืดเจ้าค่ะ"
51240-140 = "เสียงของท่านอาจารย์..."
51240-141 = "และที่สำคัญ... คือเสียงที่ชัดเจนของรุ่นพี่นางุสะ"
51240-142 = ""
51240-144 = ""
51240-145 = "และนั่นทำให้ ข้า ยูคาริผู้นี้! ฟื้น! คืน! ชีพ! ขึ้นมา ณ ตรงนี้เจ้าค่ะ!"
51240-146 = ""
51240-148 = ""
51240-150 = "พูดบ้าอะไรของเธอ"
51240-151 = "ลืมไปแล้วเหรอคะ? ที่ทุกคนในโลกผลักไส ปฏิเสธ และเหยียบย่ำหัวใจของคุณน่ะ"
51240-152 = "เพราะอย่างนั้นถึงได้เกิด <คาตาชิโระ> ขึ้นมาไง..."
51240-153 = "แล้วทำไมตอนนี้ถึงมาทำเหมือนให้อภัยทุกอย่าง...!"
51240-154 = "ก็เพราะว่า! ข้าไม่อนุญาตให้หัวใจได้รับบาดแผลจากเรื่องพวกนั้นยังไงล่ะเจ้าคะ!"
51240-155 = "[s] \"ยูคาริ...\""
51240-156 = "ถึงหัวใจห้องหนึ่งของข้าจะปวดร้าว... และก็เหมือนจะระเบิดออกมาด้วยความเจ็บปวด!"
51240-157 = "แต่ว่า คำพูดของท่านอาจารย์ที่ข้าได้ยินในตอนที่สติเหลืออยู่ริบหรี่..."
51240-158 = "ถึงมันจะสายเกินไปสักหน่อย... แต่สุดท้ายข้าก็ตระหนักได้เจ้าค่ะ!"
51240-160 = "ตระหนักได้งั้นเหรอ? เรื่องอะไร?"
51240-161 = ""
51240-164 = ""
51240-165 = "ว่ามันเป็นเรื่องธรรมดาเจ้าค่ะ"
51240-166 = ""
51240-169 = ""
51240-171 = "คนที่โกหกไม่ได้มีแค่รุ่นพี่นางุสะคนเดียว"
51240-172 = "ข้าเองก็เหมือนกัน"
51240-173 = "ทั้งรุ่นพี่เรนเกะและรุ่นพี่คิเคียวก็ด้วย"
51240-179 = "ที่บอกว่าเหมือนหน้าไหว้หลังหลอกน่ะ... อาจจะเป็นเพราะความกลัว เพราะต้องการทำเพื่อคนอื่น หรือเพื่อต้องการโกหกตัวเองก็ได้เจ้าค่ะ"
51240-180 = "และต่อให้เรื่องแบบนั้นทำให้ต้องชอกช้ำใจ ต้องโดนชี้นิ้วด่าว่าหลอกลวง หรือต้องทะเลาะกัน..."
51240-181 = ""
51240-183 = ""
51240-184 = "มันก็เป็นเรื่องธรรมดาที่เกิดขึ้นได้ไม่ว่ากับใครเจ้าค่ะ"
51240-185 = "[s] \"...อื้ม\""
51240-187 = "ว่าไงนะ...?"
51240-188 = "ต่อให้เราทะเลาะกันเพราะเรื่องนั้น แต่ขอเพียงแค่เราคืนดีกันได้!"
51240-189 = ""
51240-194 = ""
51240-195 = "ถ้าท่านอาจารย์ว่าอย่างนั้น... ข้าก็จะเชื่อและทำตามเจ้าค่ะ!"
51240-196 = "ข้าอยากคืนดีกับทุกคน! ต่อให้พวกเราจะสร้างบาดแผลและทะเลาะกันก็ตาม!"
51240-197 = "แต่ข้าก็ยังอยากให้พวกเราคืนดีกันและกลับไปเป็นเฮียกกะเรียวรันเหมือนเมื่อก่อน!"
51240-199 = "อะไรกัน... พูดอย่างกับบทละครน้ำเน่า...!"
51240-200 = "คุณบอกว่าชื่อยาบูกิ ชูโระใช่ไหมเจ้าคะ?"
51240-201 = "ข้า ยูคาริผู้นี้! ขอประกาศเปิดศึกต่อสู้กับคุณ! เพื่อปกป้องเฮียกกะเรียวรันทุกคนเจ้าค่ะ!"
51240-202 = "และนี่คือการตัดสินใจแน่วแน่ของอิล~ ลีทแห่งเฮียกกะเรียวรันเจ้าค่ะ!"
51240-203 = "เฮอะ! เอาเถอะ อยากจะพูดอะไรก็พูดไปเลย"
51240-204 = "ยังไงซะคาตาชิโระที่เกิดขึ้นจากเธอก็ยังคงอยู่ ณ ที่แห่งนี้...!"
51240-205 = ""
51240-207 = ""
51240-209 = ""
51240-210 = ""
51240-211 = ""
51240-213 = ""
51240-215 = "ถ้าใช้งานให้ดี แม้แต่นางุสะ! ครูจากชาเล่ต์! หรือยัยเด็กที่ไม่รู้จักเจียมตัว!"
51240-216 = "ทั้งหมดจะต้อง...!"
51240-217 = ""
51240-220 = ""
51240-221 = ""
51240-223 = ""
51240-224 = "...... หา?"
51240-225 = ""
51240-228 = ""
51240-229 = "ย้ากกก!! พวกเรามาแล้ว!"
51240-230 = "...ยูคาริ! ปลอดภัยดีหรือเปล่า?!"
51240-231 = ""
51240-234 = ""
51240-235 = "...อ่า"
51240-236 = "อ๊ะ! รุ่นพี่เรนเกะ! รุ่นพี่คิเคียว!!"
51240-238 = "ฮู่ว... ยังไม่สายเกินไปสินะ"
51240-239 = "[s] \"ทั้งสองคน?! มากันถึงที่นี่เลยเหรอ! มาได้ยังไง...!\""
51240-240 = "พวกฉันได้ความช่วยเหลือจากคนอื่นน่ะ ก็เลยมาถึงที่นี่ได้!"
51240-241 = "สถานการณ์ตอนนี้... คงกำลังดุเดือดเลยใช่ไหมล่ะ"
51240-242 = ""
51240-244 = ""
51240-246 = ""
51240-247 = "...ยาบูกิ ชูโระ สมาชิกชมรมความงามของธรรมชาติ"
51240-248 = "ฉันขอแนะนำเธอในฐานะที่ปรึกษายุทธศาสตร์ของเฮียกกะเรียวรันนะ ยอมจำนนแต่โดยดีเสียเถอะ"
51240-249 = ""
51240-251 = ""
51240-252 = "เฮอะ"
51240-253 = "ฮ่าฮ่า"
51240-254 = "อะฮ่าฮ่าฮ่าฮ่า!"
51240-255 = ""
51240-257 = ""
51240-258 = "ถ่อมาถึงตรงนี้ เพื่อจะทำให้เรื่องทั้งหมดเป็นแค่เรื่องที่ตื้นเขินแค่นี้น่ะเหรอ?"
51240-259 = "...ก็ได้ ดีเลย ดีเลยค่ะ งั้นก็ลองดูสักตั้งค่ะ"
51240-260 = "ถ้าจะมาทำให้ <ตำนานร้อยเรื่องราว> ของฉันเละเทะละก็..."
51240-261 = "งั้นฉันก็แค่ต้องรีเซ็ตทุกอย่าง! แล้วเริ่มใหม่ตั้งแต่แรก!"
51240-262 = ""
51240-264 = ""
51240-265 = ""
51240-267 = ""
51240-268 = ""
51240-269 = ""
51240-271 = ""
51240-272 = "ฉันจะทำให้พินาศทั้งหมดเลย!"
51240-273 = "เฮียกกะเรียวรันจะต้องไม่มีเหลือ!"
51240-275 = "...คิเคียว ยูคาริ คุณครู!"
51240-276 = "[s] \"อื้ม\""
51240-277 = "ถ้ามาถึงที่นี่ ก็ไม่มีที่ให้ถอยแล้ว"
51240-278 = "มีเท่าไรก็ใส่ให้หมด! จากนี้ไปคือการต่อสู้เจ้าค่ะ!"
