[translation]
52115-1 = "第11話;通往彼岸之路"
52115-2 = "惠比壽分校外圍．雪原"
52115-4 = "……所以你說已經查出了他們的根據地，是真的嗎？"
52115-5 = ""
52115-8 = ""
52115-9 = "啊，我剛才沒說過嗎？"
52115-11 = "並沒有。"
52115-12 = "剛才突然默默跑了出去，我們只能跟著追出來……"
52115-13 = ""
52115-16 = ""
52115-17 = "抱歉抱歉。#n因為我聽說魑魅魍魎或黃昏會吞噬黑暗而變強……"
52115-18 = "想說要趁天黑之前行動，結果就太著急了。"
52115-19 = "意思是花鳥風月部的根據地……就在這附近嗎？"
52115-20 = "不過棕櫚同學不是什麼都沒說嗎？#n委員長是怎麼知道的呢？"
52115-21 = "就像我早上提過的一樣，是透過這個付喪神的殘骸確定的。"
52115-22 = ""
52115-24 = ""
52115-25 = ""
52115-26 = "你們看這裡，有看見傘的握柄上刻著的符號嗎？"
52115-27 = "之前聽說城鎮附近出現付喪神的傳聞的時候，#n我就特意在一些舊物上刻了特殊的符號，並放置在周圍的出入口。"
52115-28 = "如果付喪神是由花鳥風月部的怪書製造出來的話，#n只要確認那些舊物上的符號，就能推測出他們是從哪裡來的了。"
52115-30 = "原來還有這種方法……"
52115-32 = "在應對敵人攻擊的同時還能想到這種計策，真不愧是百花繚亂的委員長！"
52115-33 = "所以我們現在是朝著這個符號指示的方向走囉？"
52115-35 = "嗯。刻著這個符號的傘，當時被我放置在北邊的出入口。"
52115-36 = "而北邊出口的外面就是這片荒涼的雪原，似乎沒有什麼特別的建築或設施……"
52115-37 = "不過根據村民們的說法，大約在步行半天路程的地方有座古老的宅邸。"
52115-38 = "說到北方雪原彼端的宅邸……應該就是「彼岸邸」吧。"
52115-39 = ""
52115-42 = ""
52115-43 = "……「彼岸邸」？#n光聽名字就讓人感覺怪陰森的。"
52115-44 = "記錄顯示，那是很久以前統治這片領地的家族曾使用的宅邸。#n不過由於現已無人造訪的關係，已經荒廢了數十年之久。"
52115-45 = "我自己也沒有實際去過，因此不清楚那裡現在的狀態……"
52115-46 = "花鳥風月部的成員，很可能躲藏在那裡。"
52115-47 = "說不定就連近期在附近出沒的百物語也……"
52115-48 = "[s1] 「不過就這樣貿然過去沒問題嗎？」\n[s2] 「會不會有陷阱之類的……」"
52115-49 = ""
52115-50 = ""
52115-53 = ""
52115-54 = "沒問題的！不是有句話叫「擇日不如撞日」嗎？"
52115-55 = "既然已經抓住他們的尾巴就該乘勝追擊。#n如果猶豫不決的話又會讓他們逃掉的。"
52115-56 = "況且現在的百花繚亂還有最強戰力──菖蒲委員長在啊！"
52115-57 = "沒錯！就在這裡寫下無敵百花繚亂傳說嶄新的一頁吧！"
52115-58 = "但是百物語可不是用簡單的方法就能對付的……"
52115-59 = ""
52115-61 = ""
52115-62 = "大家已經忘記上次的戰鬥了嗎？#n普通的射擊對百物語根本不管用。"
52115-63 = "源自怪書的怪談，只有從大預言者葛葉大人手中獲得資格的人才能擊倒……"
52115-64 = "雖然我也不想說得太冒犯……#n不過就算菖蒲委員長再怎麼全能，如果無法正確運用百蓮之力也無濟於事。"
52115-65 = "沒，沒有那種事。#n就算是我，也比不上菖蒲──"
52115-66 = "話說回來，如果我們沒來的話……委員長打算怎麼一個人擊敗百物語呢？"
52115-68 = "這個嘛……"
52115-69 = "雖然無法對抗從怪書衍生的怪談，#n不過對於怪書本身或使用怪書的部員，我覺得「總會有辦法」應付。"
52115-70 = "總會有辦法……？#n我所認識的菖蒲委員長，是會在如此缺乏對策的情況之下貿然行動的人嗎？"
52115-71 = "誰知道呢？#n也許是因為被逼到絕境的關係，性格也變得更積極了吧。"
52115-72 = "而且最重要的是……我相信值得依靠的朋友名草。"
52115-73 = ""
52115-76 = ""
52115-77 = "……我？"
52115-78 = "昨晚，當我看見名草自由運用著百蓮的模樣後就明白了。"
52115-79 = "原來獲得大預言者葛葉認可的正統繼承者，就是這副模樣啊。"
52115-80 = "那就是百花繚亂的委員長應該展現的姿態。"
52115-81 = "不，不是這樣的，菖蒲。#n和菖蒲比起來，我根本──"
52115-82 = "別再貶低自己了，名草。"
52115-83 = ""
52115-85 = ""
52115-87 = "你可是我重要的朋友哦？"
52115-88 = ""
52115-90 = ""
52115-92 = "重要的朋友在不懈努力下超越了我，還獲得部員們的認可……我怎麼可能會嫉妒呢？"
52115-93 = "我始終相信，名草你總有一天會綻放出最美的花朵。"
52115-94 = "雖然沒能獲得葛葉大人的認可，確實令我感到遺憾……#n然而這也代表你擁有某些我所沒有的東西。"
52115-95 = "就像我們之前約好的一樣──無論你是弱小還是強大，我都會一直在你身邊。"
52115-96 = "所以現在……請幫我完成委員長最後的使命吧。"
52115-97 = ""
52115-99 = ""
52115-101 = ""
52115-102 = ""
52115-103 = "……那當然。"
52115-105 = "哦哦……這個發展也太青春了吧！"
52115-106 = "……好！就用這股燃燒的熱情，把花鳥風月部一舉擊潰吧！"
52115-107 = "小女子以前讀的運動漫畫裡，也出現過這種對話！"
52115-108 = "原來蓮華前輩所說的青春，就是這麼讓人心潮澎湃的東西啊……！"
52115-110 = "哈哈……感覺再反對也說不過去了呢。"
52115-111 = "好吧，如果名草前輩沒意見的話，我也不會勉強反對。"
52115-112 = "……不過這孩子為什麼也跟來了？"
52115-113 = ""
52115-115 = ""
52115-117 = ""
52115-118 = "你以為我想來啊！？明明是你們強行把我拖來的好不好！"
52115-119 = "如果把這孩子單獨留下，不知道他又會做出什麼。#n至少得在我們眼皮底下看著才行。"
52115-120 = "而且他也可能趁我們不在的時候，再用怪書召喚出百物語不是嗎？"
52115-122 = "這點應該不用擔心吧。#n這個小不點手上的怪書《稻生物怪錄》已經在上次的事件中毀掉了──"
52115-123 = ""
52115-125 = ""
52115-126 = "……等一下。#n既然之前的怪書不能用了，那他昨晚是怎麼召喚出付喪神的？"
52115-127 = ""
52115-129 = ""
52115-130 = "莫非……花鳥風月部擁有的怪書不只一本！？"
52115-132 = "……有這種可能。#n如果怪書只有一本的話，應該不會交到這種愛惹事的小不點手上才對。"
52115-133 = "你說誰是愛惹事的小不點啊！#n雛罌粟大人是信任我的能力才會把怪書交給我──"
52115-134 = ""
52115-136 = ""
52115-137 = "蓮華、紫，幫我抓住他的手。"
52115-138 = ""
52115-140 = ""
52115-142 = ""
52115-145 = ""
52115-146 = ""
52115-147 = "你，你們要幹嘛！？"
52115-149 = "我要搜身。要是他還藏著我們沒發現的怪書可就麻煩了。"
52115-150 = "好，那我來抓住他的腿。"
52115-151 = ""
52115-153 = ""
52115-157 = ""
52115-158 = "你，你們到底要幹什麼！#n以為這樣就能找到怪書嗎──"
52115-159 = ""
52115-164 = "噫噫！？哈……哈哈哈！哈哈哈哈！#n快，快住手……！"
52115-165 = "在這裡嗎？還是在這裡……？"
52115-166 = "快，快給我住手……我絕對不會原諒你們的……！"
52115-167 = ""
52115-171 = ""
52115-172 = ""
52115-173 = "桔梗前輩，這裡有一本文庫大小的書！"
52115-174 = "做得漂亮，紫。"
52115-175 = ""
52115-178 = ""
52115-179 = "那，那本書不行啊！"
52115-180 = "哦～？這個反應哪怕不是真的怪書，至少也是很重要的東西吧？"
52115-181 = "名草前輩，快打開來看看吧！"
52115-183 = "嗯，我看看……"
52115-184 = ""
52115-186 = ""
52115-193 = "[log]標題[/log]"
52115-194 = "[log]史上最強怪談家[/log]"
52115-198 = "[log]作者[/log]"
52115-199 = "[log]朽木修羅[/log]"
52115-203 = "[log]傾瀉的子彈與炸彈，[/log]"
52115-205 = "[log]在鋼鐵般的[ruby=Body]肉體[/ruby]前皆為無力。[/log]"
52115-207 = "[log]史上最[ruby=Storyteller]強怪談家的[/ruby]傳聞，傳遍百鬼夜行。[/log]"
52115-211 = "[log][ruby=Icy Snow]擁有冰雪般冷[/ruby]冽雙眼的她，[/log]"
52115-213 = "[log]今日也將於漆[ruby=Darkness]黑闇夜之[/ruby]中誘惑人心。[/log]"
52115-215 = "[log]違抗之人將以[ruby=Life]鮮血[/ruby]償還代價。[/log]"
52115-219 = "[log]只需一根手指，[/log]"
52115-221 = "[log]她所操縱的[ruby=Monster]怪異[/ruby]，便將撲向惹怒[ruby=Storyteller]怪談家[/ruby]的──[/log]"
52115-223 = "[log]那些可悲又[ruby=Stupid]愚蠢[/ruby]的傢伙。[/log]"
52115-227 = "[log]尤其對[ruby=A Bunch Of Fools]囂張的百花繚亂絕不寬[/ruby]恕。[/log]"
52115-229 = "[log]他們將會哭著回家。[/log]"
52115-233 = "[log]這就是所有人恐懼的──[/log]"
52115-234 = "[log]究極[ruby=Storyteller]怪談家[/ruby]。[/log]"
52115-237 = ""
52115-238 = "啊。"
52115-239 = "啊……"
52115-240 = "啊啊……"
52115-241 = "[s]「唔嗯……」"
52115-242 = ""
52115-244 = ""
52115-246 = ""
52115-247 = "紫，再找找看吧？#n他一定還藏著其他怪書。"
52115-248 = ""
52115-251 = ""
52115-252 = "為什麼要裝作沒看見啦！你剛才明明都看到了不是嗎！"
52115-253 = "這是……你寫的小說嗎？"
52115-254 = "不，說是小說有點奇怪吧。#n這完全就是──"
52115-255 = "唔，唔唔……！"
52115-256 = "你們這些人到底想怎樣！#n不只擅自翻我的東西，甚至還把人家珍藏的作品公開朗讀！？"
52115-257 = "要是有人聽到之後，搶先把我苦思冥想出的原創題材寫成小說還爆紅的話……"
52115-258 = "你們要怎麼負責！？"
52115-259 = "[s]「啊，你擔心的是這個……？」"
52115-260 = "這點你不用擔心啦。"
52115-261 = "反正能用這個題材寫出作品的作家應該不多……"
52115-262 = ""
52115-264 = ""
52115-265 = "……這麼說也有道理。#n就算題材再好，要是缺乏文筆也寫不出優秀的作品。"
52115-266 = ""
52115-268 = ""
52115-269 = "咳哼。話說……各位覺得怎麼樣？#n我問的不是怪談，而是我的原創故事。"
52115-270 = "看你們的表情，好像都驚嘆到說不出話來了呢。#n沒關係，我特別給你們一個搶先發表感想的機會。"
52115-271 = "就讓我來聽聽，你們對我的傑作──《史上最強怪談家》的感想如何吧！"
52115-272 = ""
52115-275 = ""
52115-276 = "那個……小女子覺得……"
52115-277 = "……還是先趕路吧。#n想在天黑之前抵達彼岸邸的話，必須加緊腳步。"
52115-278 = "沒，沒錯！現在不是發表感想的時候！"
52115-280 = "結果沒有怪書啊……白白浪費時間了呢。"
52115-281 = "不過至少比會害人的怪談好多了嘛。#n至於有不有趣就……"
52115-282 = "[s]「……建議你先多讀其他的書會比較好哦？」"
52115-283 = ""
52115-285 = ""
52115-287 = ""
52115-288 = "唔唔，唔唔唔……"
52115-289 = "名草醬～～～！"
52115-291 = "下一話;勘解由小路家的巫女 "
