[translation]
52150-1 = "Episode 15;The End of a Sweet Dream"
52150-6 = ""
52150-7 = "*yawn*"
52150-8 = ""
52150-12 = "You look tired, Ayame. Did you not sleep well?"
52150-13 = "You could say that. I had this dream..."
52150-15 = "Oh no, was it a nightmare? You seem troubled."
52150-16 = "No, no. It was a good one, actually."
52150-17 = "I dreamed of a peaceful world...so peaceful that not a single problem ever darkened the Hyakkaryouran's doorstep."
52150-18 = ""
52150-22 = "You still seem distressed, though..."
52150-23 = ""
52150-25 = ""
52150-26 = "Hm... It's easy to dismiss the unpleasantness of a bad dream to just that, a dream. You'll forget about it as soon as you wake up."
52150-27 = "But with happy dreams...well, it's a harsh juxtaposition to the reality you end up waking up to."
52150-28 = "It makes you long for that dream world. Like you want to reject reality altogether."
52150-29 = "...At least, that's what I heard in a movie once!"
52150-31 = "At the time, I couldn't understand it, but Ayame was right all along."
52150-32 = "The happiness of a dream lingers more painfully than the darkness of one."
52150-33 = "If this was just a dream...then I truly wish I had never awoken."
52150-34 = ""
52150-47 = ""
52150-49 = "...You're awake."
52150-50 = ""
52150-53 = ""
52150-54 = ""
52150-55 = "...Ayame?"
52150-56 = "It's been a long time, Nagusa."
52150-57 = "How...did I get here?"
52150-58 = ""
52150-60 = ""
52150-61 = "Where are the others? [USERNAME] Sensei?"
52150-62 = "Don't worry. They're all in the next room over."
52150-63 = "No one is seriously injured. Schale's Sensei is asleep, but also safe."
52150-64 = ""
52150-66 = ""
52150-67 = "...Then was it not you we met at Ebisu?"
52150-68 = "You say, \"It's been a long time.\" That can only mean that the Ayame I met earlier..."
52150-69 = "Mhm. An illusion, created by the Hundred Ghost Stories, that feeds upon fear."
52150-70 = "Feeds upon...fear? But I wasn't afraid of you..."
52150-71 = "That illusion was born from you, and you alone."
52150-72 = ""
52150-74 = ""
52150-75 = "You must have realized it, no? That perfect version of me you so desperately wished for..."
52150-76 = "...you knew it was a sickly-sweet dream, a precarious one, poised to shatter. You were afraid of the cruel reality that lingered on the fringes."
52150-78 = "No... I truly believed..."
52150-79 = ""
52150-81 = ""
52150-82 = "Lies!"
52150-83 = "You haven't changed at all! You use your ignorance as a shield for your desires, relying on others to achieve what you can't."
52150-84 = "How much longer are you going to hide behind your incompetence for?"
52150-85 = ""
52150-87 = "...You're right about one thing. Not everything my shadow said was a lie. I'd felt that I'd reached my limits as president. That's why I sought out Kuzunoha."
52150-88 = "That's just how worn down I was from constantly fielding everyone's requests and wishes."
52150-91 = "Nagusa. Each and every one of you fell for the smile I wore for your sake. All while I hated you all."
52150-92 = "I hated all the weaklings who came crawling to me, begging that I fulfill their every whim and fancy."
52150-93 = "Those members who preached lofty ideals, but seemed to be allergic to taking action."
52150-94 = "And...you. You, who gave up at the slightest resistance, turning to me with those pathetic, tear-filled eyes of yours."
52150-95 = ""
52150-97 = ""
52150-98 = "...I hated it all."
52150-99 = ""
52150-101 = ""
52150-102 = "But I was still the president of the Hyakkaryouran. So I went looking for Kuzunoha, to beg her to grant me the power to protect this \"reality.\" I came away from my search with empty hands and baseless rumors."
52150-103 = "That's when I realized that it didn't matter if this supposed prophet survived only as a rumor. With the power of a tome, I could bring even a rumor to life."
52150-104 = "If I couldn't be everywhere at once, I only needed the ability to watch everyone at once."
52150-105 = "No, Ayame... That ending has no happy conclusion. Kokuriko has deceived you into false hopes."
52150-106 = "No, Nagusa. You can't understand."
52150-107 = "You fail to understand who I was. The feelings I bore."
52150-108 = "No, what are you saying? All we need is to speak to each other with sincerity, with our heart's truth, and we'll be able to come to an understanding."
52150-109 = ""
52150-111 = ""
52150-112 = "Why do you willingly trick yourself with these sweet nothings?"
52150-113 = "The time for sincerity is long gone. You were afraid of my truths. You turned your gaze away from me in favor of the self-serving illusion you placed on a pedestal in your mind."
52150-114 = "Ayame, I..."
52150-115 = "After all, you already know my heart's truth, don't you?"
52150-116 = "From the very beginning, I never saw you..."
52150-117 = ""
52150-119 = ""
52150-121 = "[log=아야메 황혼 1]...as a friend, not once.[/log]"
52150-126 = "Next Episode;Harmony"
