[translation]
52280-1 = "第28話;一同等待花開之時"
52280-2 = "醫院內的病房"
52280-3 = ""
52280-5 = "是，請進～"
52280-6 = ""
52280-9 = "哎呀，[USERNAME]老師？"
52280-10 = "您怎麼會突然……"
52280-11 = "[s1]「我聽說仁耶住院了，所以就過來探望一下。」\n[s2]「身體還好嗎？」"
52280-14 = "喵哈哈……看來我似乎讓您費心了呢，真不好意思。"
52280-15 = "如您所見，我非常健康。#n上次事件中受的傷也幾乎痊癒了。"
52280-16 = "雖然只是輕微擦傷，但那終究是百物語造成的傷口。#n佳穗他一直擔心會有後遺症的風險……"
52280-17 = "所以我才會住院接受治療和各種檢查，並不是因為受了什麼重傷，還請您放心。"
52280-18 = "[s]「那就好。」"
52280-19 = "坦白說……只有我一個人這樣住院，實在有點不好意思呢。"
52280-20 = "畢竟就連在現場拚命戰鬥的百花繚亂和其他社團成員們，似乎都已經回歸日常了……#n卻只有我還躺在病床上。"
52280-21 = "不過既然有了正當理由，這次我就算偷懶也沒人敢說什麼了吧……呵呵。"
52280-22 = "[s]「不過你床邊的桌子上怎麼堆滿了文件……」"
52280-23 = ""
52280-25 = ""
52280-26 = "這，這個嘛……"
52280-27 = "我當然也想無所事事地好好偷懶……#n可惜有些流言如果置之不理就會越傳越廣，甚至變得難以收拾。"
52280-28 = "尤其在這種大事件剛結束之後，總會有愛嚼舌根的人不斷湧現呢。"
52280-29 = "所以我只好被迫先處理優先度高的文件。"
52280-30 = "絕～對不是因為喜歡工作才這樣做的哦？"
52280-31 = "[s3]「好好好。」\n[s4]「看見一如既往的仁耶真讓人安心。」"
52280-34 = "那麼我先向您報告已確認事項中最重要的議題……"
52280-35 = "……和樂祭已經圓滿落幕了！"
52280-36 = ""
52280-39 = "[ns]「這……算是重要議題嗎？」"
52280-40 = "那當然。能親眼欣賞知世喵可愛表演的機會，可是不可多得的哦？"
52280-41 = "而且這次發表的新曲，似乎在社群媒體上也引發了話題。"
52280-42 = "佳穗甚至還認真地跑來找我商量，該不該趁這個機會讓知世喵正式出道成為偶像呢。"
52280-43 = "雖然他也在煩惱「如果知世醬變忙，自己能守在他身邊的時間也會減少」就是了～"
52280-44 = "[s]「這麼說來，我有件關於祭典的事情想問……」"
52280-45 = "是，您請說。"
52280-46 = "[s5]「和樂祭一開始，一目的力量就減弱了對吧？」\n[s6]「所以百鬼夜行的祭典，果然也是驅逐百物語的儀式嗎？」"
52280-49 = ""
52280-51 = ""
52280-52 = "哎呀，怎麼會呢～"
52280-53 = "我當時是為了動搖薊同學才說得煞有其事的樣子，其實祭典純粹只是祭典而已。"
52280-54 = "雖說古老的祭典起源於迎接天神的祭祀，#n如今卻早已沒有人記得，也沒有人真正去實行了。"
52280-55 = "……話雖如此，假如費時準備的祭典臨時中斷，仍有許多人會感到難過對吧？"
52280-56 = "給難過的孩子糖果，給耍賴的孩子提醒。"
52280-57 = "這根本算不上什麼陰陽之理，不過是生活中簡單的道理罷了～"
52280-58 = "[s7]「……沒想到那充滿自信的宣言只是在虛張聲勢啊。」\n[s8]「幸好花鳥風月部信以為真，所以選擇立刻撤退。」"
52280-61 = ""
52280-63 = ""
52280-64 = "說到花鳥風月部，就讓我想起了惠比壽分校的土生薊同學。"
52280-65 = "由於惠比壽分校的情況，我過往只在書信往來中略知一二，#n沒想到這次特地派學生去調查的結果顯示……"
52280-66 = "惠比壽分校的自治委員會，早在數十年前就停止運作了。"
52280-67 = "當地居民也沒有人記得土生薊這個名字，甚至就連之前寄出的公文也沒有人收過……"
52280-68 = "[s]「也就是說……」"
52280-69 = "……沒錯。"
52280-70 = ""
52280-72 = ""
52280-73 = "往後惠比壽自治區的行政業務，也得由我們來處理了。"
52280-74 = ""
52280-77 = "[ns]「問題在這裡嗎！？」"
52280-78 = "那當然！畢竟原本能自行運作的行政業務突然出現了空缺……"
52280-79 = "看來花鳥風月部一直暗中借用自治委員會的名義來隱藏身份呢。"
52280-80 = "雖然隱瞞身份、欺騙學生以謀取私利的行為確實可惡，#n不過他們在處理自治區行政業務這方面，倒是沒什麼問題……"
52280-81 = "如今文書作業日漸增加……我離悠閒自在的生活也越來越遠了呢……嗚嗚……"
52280-82 = "[s]「之後還有發現花鳥風月部的蹤跡嗎？」"
52280-83 = "沒有。他們就和之前一樣，在事件結束後如同蒸發一般完全消失了。"
52280-84 = "無論是雛罌粟部長、薊同學，還是和我們在一起的棕櫚同學都是。"
52280-85 = "當他意識到自己做了什麼好事時的那副表情，真想拍下來留作紀念呢……實在可惜。"
52280-86 = "[s]「你性格還真壞……」"
52280-87 = "喵哈哈……不過棕櫚同學的小說帳號還在，#n如果情況有變的話，或許還會有新連載出現吧？"
52280-88 = "棕櫚同學的文章，拿來打發時間還算不錯……我個人還挺期待他的新作的。"
52280-89 = "……雖然劇情總是亂七八糟的就是了。"
52280-90 = "[s]「和之前相比，這個評價是不是有點苛刻？」"
52280-91 = "這也沒辦法。#n畢竟說故事的人，本來就是會因為一點小事而喪失意志的脆弱存在。"
52280-92 = "得好好哄哄他，下次才有機會寫出更有希望的故事……您說對吧？"
52280-93 = "[s]「說的也是。希望下一個故事能夠和平一點。」"
52280-94 = ""
52280-97 = "[ns]「話說菖蒲後來怎麼樣了……？」"
52280-98 = "啊啊，菖蒲委員長的話……"
52280-99 = ""
52280-101 = ""
52280-102 = "我想還是向他的朋友們詢問比較好吧？"
52280-104 = "百鬼夜行．祭典街道"
52280-106 = "（百鬼夜行的街道和以往一樣人潮洶湧）"
52280-107 = "（充滿了享受祭典的人們，以及準備祭典的人們……）"
52280-108 = "（彷彿這條街上的祭典從未中斷一樣）"
52280-109 = ""
52280-113 = ""
52280-114 = ""
52280-115 = "啊，主公！"
52280-116 = ""
52280-118 = ""
52280-119 = "老師大人，你平安無事啊！"
52280-120 = "祭典結束後一直聯絡不上您……我很擔心呢！"
52280-121 = "[s9]「抱歉，我後來又被各個地方呼來喚去……」\n[s10]「忙著處理各種事情，所以才遲遲沒跟你們打聲招呼。」"
52280-124 = "沒關係！只要主公平安，伊樹菜就放心了！"
52280-125 = "話說老師大人要去哪裡呢？#n陰陽部的部室應該在那邊才對……"
52280-126 = "[s11]「我要去一趟百花繚亂的部室。」\n[s12]「想去看看菖蒲和名草的情況。」"
52280-129 = "菖蒲……就是那個百花繚亂的委員長對吧？"
52280-130 = "我聽說事件結束之後，他正式回歸百花繚亂了……"
52280-131 = ""
52280-133 = ""
52280-134 = ""
52280-135 = "陰陽部和百花繚亂都對外宣稱「當時現身的菖蒲委員長是花鳥風月部捏造出來的」。"
52280-136 = "雖然我也不太相信菖蒲委員長會做出那種事情……"
52280-137 = "不過我們當時見到的菖蒲委員長，實在真實得讓人難以否認……"
52280-138 = "老師大人知道些什麼嗎？"
52280-139 = "[s]「這個嘛……」"
52280-141 = "那，那不可能是真的！"
52280-142 = "……伊樹菜？"
52280-143 = "伊樹菜以前也差點被壞心的大人騙去破壞祭典……#n因為那時的伊樹菜身邊，並沒有能傾訴忍者真心的夥伴。"
52280-144 = "如果當時身邊能有朋友告訴伊樹菜「那是不對的」……#n或許伊樹菜就不會走上錯誤的道路了。"
52280-145 = "伊樹菜聽說菖蒲閣下和名草閣下是認識許久的老朋友。"
52280-146 = "只要名草閣下在他身邊……菖蒲閣下就不可能做出那種壞事！"
52280-147 = "沒，沒錯！而且我也聽說過，菖蒲委員長是個正直又溫柔的人！"
52280-148 = "其中肯定有什麼誤會。"
52280-150 = "這樣啊……果然傳聞終究只是傳聞吧～"
52280-151 = "[s]「是啊，盲信傳聞是很危險的。」"
52280-152 = ""
52280-155 = "[ns13]「話說當時忍術研究部好像也出現了奇怪的變化……」\n[ns14]「現在已經恢復原狀了嗎？」"
52280-158 = "啊，對啊對啊！老師大人你聽我說！"
52280-159 = "就在怪物襲擊和樂祭舞台的時候，我突然湧出了一股驚人的力量哦！"
52280-160 = "簡直就跟中了禁忌妖刀的詛咒一樣……變得超強的！"
52280-161 = "對，對呀！好像真的可以在現實中使用忍術一樣，跑得非常非常快！"
52280-162 = "雖然沒有實際試過，但說不定就連要在濕掉的紙門上奔跑都沒問題！"
52280-163 = "跑在濕紙門上的場景……"
52280-164 = "是《徬徨的孤獨忍者77人組》的高潮場景吧！#n伊樹菜也很想在現實中嘗試看看！"
52280-165 = ""
52280-167 = ""
52280-168 = "[ns]「三千留……會覺得失去那股力量很可惜嗎？」"
52280-169 = "嗯？我覺得無所謂啊？"
52280-170 = "唔嗯……#n雖然仔細想想，那股力量或許能用來做些小小三千留頻道的新企劃沒錯……"
52280-171 = "不過就算有那種莫名其妙的力量，也沒辦法讓大家更了解忍者的魅力。"
52280-172 = "忍者的價值並不是來自於強大的力量，而是彼此之間的羈絆。"
52280-173 = "與其成為擁有傳說力量的忍者，不如成為擁有許多夥伴的普通忍者……"
52280-174 = ""
52280-176 = ""
52280-177 = "《徬徨的孤獨忍者77人組》裡也是這麼說的！"
52280-178 = "伊樹菜也這麼覺得！"
52280-179 = "我，我也是……！"
52280-180 = ""
52280-181 = "[ns]「……老師我也這麼認為。」"
52280-183 = "[ns15]「那下次一起在夏萊看那部電影吧？」\n[ns16]「我之前在視聽室裡裝了超讚的環繞音響哦！」"
52280-186 = "哦哦……真想馬上去看呢！"
52280-187 = "可，可是部長。現在不是應該去整理和樂祭的器材嗎……？"
52280-188 = "啊哈哈……說的也是。#n那還是等下次再去吧！"
52280-189 = "嗯！下次一定要一起去！"
52280-190 = "路，路上小心……老師！"
52280-194 = "百花繚亂部室前訓練場"
52280-195 = ""
52280-196 = ""
52280-198 = "等一下，蓮華。#n你手上拿的是繡球花苗吧。"
52280-199 = "而你現在挖的地方則是山茶花苗旁邊的花壇……#n把夏季花種在冬季花旁邊，開花的時候該怎麼欣賞？"
52280-200 = "那種事我也知道好嗎……#n而且就是要混種，一年四季才都有花可以看啊？"
52280-201 = "……與其一直在上面嘮叨，不如下來幫忙怎麼樣？"
52280-202 = "不行。得有人在上面俯瞰全局才行。#n知道什麼叫「當局者迷，旁觀者清」嗎？"
52280-203 = "說得那麼好聽，其實你只是不想弄髒手而已吧？"
52280-204 = ""
52280-206 = ""
52280-207 = "……我才沒有。"
52280-208 = "那你敢不敢跟我交換！#n這樣太不公平了──"
52280-209 = ""
52280-211 = ""
52280-212 = ""
52280-213 = ""
52280-214 = ""
52280-215 = "哎呀，老師來了！"
52280-216 = "……歡迎，老師。"
52280-217 = ""
52280-218 = "[ns17]「你們好呀！」\n[ns18]「我是不是打擾你們忙碌了……？」"
52280-221 = "沒關係，現在並不是在忙百花繚亂的事。#n我們……"
52280-222 = "小女子正在和前輩們一起種花！"
52280-223 = "[s]「花……？」"
52280-224 = "嗯。我聽說和樂祭結束後的下一個祭典，是到各處欣賞花朵的賞花祭。"
52280-225 = "所以才會拿準備祭典時剩下的種子……"
52280-226 = "撒在訓練場前的花壇，所有人一起栽種！"
52280-227 = "如果能看著伴隨四季盛開的花朵，想必能讓前來訓練場的每天都充滿期待吧！"
52280-228 = "雖然專心訓練的時候，可能也沒空在意周圍的景色就是了。"
52280-229 = ""
52280-231 = ""
52280-232 = "紫，可以幫我把上面的麻袋遞過來嗎？"
52280-233 = "還挺重的，小心別受傷了哦。"
52280-234 = "是～"
52280-235 = ""
52280-236 = ""
52280-238 = "[ns]「你的手臂已經沒事了嗎？」"
52280-239 = "嗯，已經恢復原狀了。#n這隻右臂……還有菖蒲也是。"
52280-240 = "那天遺留在雪原中的一切……都回到了原本的位置。"
52280-241 = "只是菖蒲他……從那天起就一直沒有醒來。"
52280-242 = "雖然身體看起來並沒有異常……卻像陷入了深沉的睡眠一樣，閉著眼睛一動也不動。"
52280-243 = "[s]「是墜入黃昏的後遺症嗎？」"
52280-244 = "這還無法確定，不過醫生表示比較可能是心理方面的因素。"
52280-245 = "說是他的身體拒絕醒來。"
52280-246 = "呿，本來想在他醒來後好好唸他一頓的……結果居然一直睡個不停。"
52280-247 = "雖然有想過要不要強行叫醒他，不過名草前輩說就讓他繼續睡比較好。"
52280-248 = "因為選擇繼續在睡夢中思考，是菖蒲自己的意志。"
52280-249 = "雖然無法得知菖蒲在夢裡思考著什麼……"
52280-250 = "……至少我們能在身邊等待他醒來。"
52280-251 = ""
52280-253 = ""
52280-254 = ""
52280-255 = "前輩，這顆種子是什麼花呢？"
52280-256 = "這是……櫻花。"
52280-257 = "種下之後會長成櫻花樹，所以最好和其他灌木保持距離。"
52280-258 = "哎呀，所以之後就能看到新的櫻花了嗎？真令人期待～"
52280-259 = "不過要等櫻花樹開花，可能得等上好幾年……這樣真的沒問題嗎？"
52280-260 = "就算現在種下去，我們在學園的期間恐怕也看不到它開花的樣子。"
52280-261 = ""
52280-263 = ""
52280-264 = "……沒關係。"
52280-265 = "就算我們沒機會，未來也會有人見到的。"
52280-268 = "就像過去的前輩們一樣。"
52280-277 = "總有一天，這裡也會迎來百花齊放的時刻。"
52280-278 = "在那天到來之前，我會永遠等待著你。"
52280-283 = "等待將在某天醒來的朋友。"
