[translation]
62080-1 = "Episode 8;Porta Pacis 2"
62080-2 = ""
62080-3 = ""
62080-4 = "...Mystery? Seriously?"
62080-5 = "Are we summoning ghosts next? Some vengeful spirits?"
62080-6 = "President!"
62080-7 = "Ugh..."
62080-8 = ""
62080-10 = ""
62080-11 = ""
62080-12 = "I've...never heard of this."
62080-13 = "You wouldn't have. Honestly, I believed it to be nothing but a legend or myth at first."
62080-14 = "I haven't spoken of this to anybody."
62080-15 = "However, just before the Eden Treaty, Beatrice went to the Porta Pacis archive."
62080-16 = "I was the only one she told of this."
62080-17 = ""
62080-19 = ""
62080-20 = ""
62080-21 = "!"
62080-22 = "Eh...?"
62080-23 = ""
62080-25 = ""
62080-26 = ""
62080-27 = "B-But no one was allowed to go there..."
62080-28 = "Do you think Beatrice cared?"
62080-29 = "That's...true..."
62080-30 = "Beatrice had many secrets, and this was one of them."
62080-31 = "...Then could it be that Saint Justina Council's Mimesises manifested because...?"
62080-32 = "Perhaps. We'll likely never know."
62080-33 = "...At most, I think we can say they were likely related in one way or another."
62080-34 = "And, as you all know, the appearance of strange phenomena also began to increase across Arius."
62080-35 = "Yes... I remember. There were suddenly lots of new things I'd never seen before. And we had...lots and lots of weapons..."
62080-36 = "We didn't think that much of it, I guess. We just thought...that adults are different from us... Adults are incredible..."
62080-37 = "[s] \"...\""
62080-38 = "But the \"began to increase\" part is important here."
62080-39 = "Hm...? Does that mean..."
62080-40 = "Yeah."
62080-41 = "Although rare, strange occurrences have always happened here, in Arius."
62080-43 = "...Sure, every school has their ghost stories, but, with Arius... It was on a different level."
62080-44 = "It wasn't until after I left Arius that I realized the number of occurrences here wasn't normal."
62080-45 = ""
62080-47 = ""
62080-48 = ""
62080-49 = "[ns] \"Why...are they happening here?\""
62080-50 = "I can't say exactly why."
62080-51 = "However..."
62080-52 = "I believe this place simply...ended up like that."
62080-53 = "There was always \"something\" in Arius."
62080-54 = "Lament, grudge, resentment, rage, resignation... They all gather here to fester."
62080-55 = "They say that a strong enough desire or resolve will manifest itself in some form or another."
62080-56 = "B-But isn't that just a...metaphor..."
62080-57 = "But we've already seen them. Like the Saint Justina Council and Barbara, no?"
62080-58 = "...We did. But I thought that was just Madame's... Beatrice's doing."
62080-59 = "Maybe I was averting my eyes to it... The other side of Arius' \"truth.\""
62080-60 = "I can't say anything for certain. However, sometimes I can't help but be afraid."
62080-61 = "That swirling mass of negative emotions... Just what could be lying beneath them?"
62080-62 = "Just imagining it...terrifies me."
62080-63 = "..."
62080-64 = "Ugh..."
62080-65 = ""
62080-67 = ""
62080-68 = ""
62080-69 = "...Let's talk about the Book of Revelation, everyone. "
62080-70 = "Since, in any case...that seems to be at the core of the events taking place in Arius right now."
62080-71 = "Yes. Thank you, Shimiko."
62080-72 = "Of course, Atsuko."
62080-73 = "The Book of Revelation is the last chapter of the scripture that has been passed down in both Trinity and Arius."
62080-74 = "After all, the scriptures used in both academies are the same. The two may have diverged, due to differences in interpretation, but the source remained one and the same."
62080-75 = "However, in Trinity, the Book of Revelation is used as a...reference text, kind of."
62080-76 = "A book of ethical lessons, advice, and proverbs... That's all."
62080-77 = "Arius' research and interest in the Book of Revelation were much more intense."
62080-78 = "...They were interested in the \"end of the world\" as discussed in the Revelation."
62080-79 = "[s] \"Doesn't that mean...?!\""
62080-80 = "...One way or another, Arius' leadership wanted to bring about the end of the world."
62080-81 = "..."
62080-82 = "I'll be honest, Sensei. That's exactly it."
62080-83 = "M-M-M-M-M-M-Misaki?!"
62080-84 = "What's with that reaction? Am I lying? And this is Sensei we're talking to."
62080-86 = "...I can understand."
62080-87 = "A neglected child will set fire to their village just to feel the warmth of the flames."
62080-88 = "To someone who has nothing left to lose, the end of the world might even feel like salvation."
62080-89 = "Because at the very least, that would make them feel like things are fair..."
62080-90 = "They say that for an individual, their death and the end of the world are ultimately the same thing, right?"
62080-91 = "Then I think it's more than plausible for someone to see it the other way around at some point."
62080-93 = "Yes. It's dangerous when people tunnel vision. They tend to confuse means and goals."
62080-94 = "..."
62080-95 = "..."
62080-96 = "In the Book of Revelation, a group of seven angels appear three times. We call them the \"Angels of Revelation.\""
62080-98 = "I thought of it as nothing more than a myth, originating from our fear and suffering."
62080-99 = "Arius was always fond of the Book of Revelation, after all."
62080-100 = "...Like Atsuko said earlier, strong human emotions tend to manifest themselves in some way."
62080-102 = "The three groups of angels, recorded in the Book of Revelation, signal the end of the world."
62080-103 = "The first is seven \"angels opening the seals,\" followed by seven \"angels blowing the trumpet,\" and lastly seven \"angels pouring out bowls.\""
62080-104 = "You said you all heard the trumpet, right? I did too. That must have been the \"angels blowing the trumpet.\""
62080-105 = "Based on the text, there were four blows of the trumpet."
62080-106 = "This aligns with the voice we heard from the sky."
62080-107 = "\"Because of the trumpet blasts about to be sounded by the three other angels.\""
62080-108 = "[s] \"What happens if all seven angels blow their trumpets?\""
62080-109 = "Fufu. I wonder."
62080-110 = "If, by any chance, everything in the Book of Revelation comes true..."
62080-111 = "Then it'll be seven angels with bowls of wrath next."
62080-112 = "And once everything pours out onto the earth in order, the world will end..."
62080-113 = "In its place will be a new world for those who are faithful. That's what we were taught."
62080-114 = "...Yes. If everything follows the Book of Revelation, that is."
62080-115 = "But were they truly the Seven Trumpeting Angels?"
62080-116 = "Do you think they could be something else?"
62080-117 = ""
62080-119 = ""
62080-120 = "...Perhaps. Honestly speaking, everything is up in the air right now."
62080-121 = "Something has always brewed deep within Arius, and this land has seen tragedy after tragedy."
62080-125 = ""
62080-126 = ""
62080-127 = "W-We're really here..."
62080-128 = "Uh... Augh..."
62080-130 = "Everyone, be quiet. It's just a building. Don't panic."
62080-132 = "Y-Yes."
62080-134 = "Our destination is the archive, located underneath Porta Pacis."
62080-135 = "It's said the \"truth\" of Arius lies dormant there."
62080-136 = "There may be clues about the Trumpeting Angels there."
62080-137 = "As you all well know, this place has been locked for over a hundred years..."
62080-139 = "S-Subaru? The door's...open...?"
62080-141 = "What?! Does that mean someone's already been here...?"
62080-142 = ""
62080-144 = ""
62080-145 = "No, it's okay. This works out."
62080-146 = "I've heard that the one who opens the door will find themselves forever lost at the end of their journey."
62080-147 = "...Someone's very kindly opened the door for us, so we have one fewer thing to worry about."
62080-149 = "Does that mean we're really..."
62080-150 = "...going down...there?"
62080-152 = "..."
62080-153 = "No. I'll be the only one going."
62080-154 = "Something scary could happen down there, you know?"
62080-156 = "...!"
62080-157 = "G-Got it, Subaru..."
62080-158 = "What should we do, then...?"
62080-160 = "Set up a base here, please."
62080-162 = "A base?"
62080-164 = "Yes. You've all trained for this, so don't worry."
62080-165 = "But make sure..."
62080-166 = "...you're ready to respond to attacks from both outside and in."
62080-168 = "That's...!"
62080-169 = "Could it be for in case anything happens to you...?"
62080-171 = "Don't make me repeat myself."
62080-173 = "Ah!!"
62080-174 = "G-Got it!"
62080-175 = ""
62080-177 = ""
62080-178 = ""
62080-179 = "[ns] \"Some people couldn't hear the trumpet?\""
62080-180 = "Yeah. We were divided into people who could hear the trumpet..."
62080-181 = "..."
62080-182 = "...and people who couldn't."
62080-183 = "Do you know why?"
62080-184 = "I'm not sure... I was in the group of people who could..."
62080-185 = "..."
62080-186 = "And Subaru couldn't..."
62080-187 = "*sob*"
62080-188 = "Wh-Why are you crying...?"
62080-189 = "Sorry. I'm sorry... It's just..."
62080-190 = "I did have a feeling something must have happened yesterday."
62080-191 = "E-Eek?!"
62080-192 = "I apologize. I don't mean to pressure you at all."
62080-193 = "However, if you feel comfortable, could you share what happened?"
62080-194 = "Where did the other students go? Why did only you return to Sensei...?"
62080-195 = "And how did you know those students were headed to Porta Pacis?"
62080-196 = "[s] \"Atsuko, that's...\""
62080-197 = "Hm?"
62080-198 = "..."
62080-199 = "I see. So you said you would wait until Maia feels comfortable, Sensei."
62080-201 = "Maia curled up in place and started shaking like a leaf..."
62080-202 = "Everyone seemed a little unsure what to do, then..."
62080-203 = ""
62080-204 = "U-Um... I think it's...okay to tell Sensei what happened."
62080-205 = "Hiyori...?"
62080-206 = "Sao-Sao, shh."
62080-207 = "I-I'm sorry. I'm not very good at talking... People often say I'm a bit clueless... H-Heehee..."
62080-208 = "But still, I th-think you went through something really rough...and painful...and sad..."
62080-209 = "When that happens, it helps to just talk... Kinda let it out to someone, you know...?"
62080-210 = "Just talk...to anyone...?"
62080-211 = "Y-Yes! In this case, it'd be Sensei...and us too. Ah! But w-we can leave if you feel uncomfortable! I didn't mean to...!"
62080-212 = ""
62080-213 = "...We can hang up too."
62080-214 = "Yes. Whatever you need!"
62080-215 = ""
62080-216 = "It's okay! You can...really trust Sensei. At least, I do."
62080-217 = "No matter what you say, Sensei always tries to help you. They bought me stomach medicine once...and even magazines..."
62080-218 = "I-I mean, Sensei doesn't just magically fix all your problems! You have to figure out wh-what you're good at, too..."
62080-219 = "...Although, maybe Sensei did do everything for me..."
62080-220 = "But still! I'm told that's how a student can learn how to stand up on their own later..."
62080-221 = "Ugh, I don't know how to explain this well... A-Anyways! When it comes to stuff like this..."
62080-222 = "...just holding onto it, and suffering by yourself, only hurts you more."
62080-223 = "S-Students from our school especially have a hard time with stuff, like talking or asking for help... I'm still working on that too..."
62080-224 = "S-So, I thought this might help a little...! H-Heehee..."
62080-226 = "Hiyori..."
62080-227 = ""
62080-229 = ""
62080-230 = ""
62080-231 = ""
62080-232 = "So, sh-should we step outside now? You know, since there are lots of things in this world that'd be embarrassing to tell too many people?"
62080-233 = "Yeah, I guess. Let's take a walk and survey the area."
62080-234 = "Yes. Let's go do that."
62080-236 = "E-Excuse me!"
62080-238 = "Hm?"
62080-239 = "Y-Yes...?"
62080-241 = "..."
62080-242 = "I want to do it. To tell everyone..."
62080-244 = "...You don't have to push yourself..."
62080-245 = "She finally mustered up courage, so it should be okay. Right, Ui?"
62080-246 = "I mean, I'd never..."
62080-247 = ""
62080-249 = ""
62080-250 = ""
62080-251 = "[ns] \"Are you sure?\""
62080-252 = "...Yes."
62080-253 = "I think I want to hear everyone's opinions...so I can form my own resolve!"
62080-255 = "Maia slowly began recounting the events of the previous night."
62080-256 = "...We were all stunned into silence, apprehensive of saying the wrong thing."
62080-257 = ""
62080-258 = "..."
62080-259 = "..."
62080-260 = "..."
62080-261 = "W-Waah! Waaaah!!"
62080-262 = ""
62080-264 = ""
62080-265 = ""
62080-266 = "H-Hiyori? If you cry like that..."
62080-267 = "It's just too much! This is too sad! How could anyone not feel sad, listening to her story?! WAAAH!!"
62080-268 = ""
62080-270 = ""
62080-271 = ""
62080-272 = ""
62080-274 = "H-H-H-H-Hiyori?! Um, if you...!"
62080-275 = "Waaaaaaah!"
62080-276 = "I-I... I was barely...holding back too... *sniff*"
62080-277 = "That's exactly what I MEAAAN!!"
62080-278 = ""
62080-279 = "You're very kind, Hiyori."
62080-280 = "Yeah... She always has been. Misaki?"
62080-281 = "Stop it. D-Don't look at me."
62080-282 = "Fufu. In times like these, you're supposed to cry your heart out."
62080-283 = "I'm not crying!"
62080-284 = ""
62080-285 = "[ns] \"Thank you so much for sharing with us.\""
62080-286 = "N-Not at all. Actually, thank you...everyone, for hearing me out..."
62080-287 = "But it comes back to the question... Why did only some of us hear the trumpet?"
62080-288 = "...I have a guess. Based off what we've learned so far."
62080-289 = "I identified one common factor in each of the two groups."
62080-290 = "What...are they?"
62080-291 = "Their participation in Sensei's class."
62080-292 = "What? B-But we all went to that class..."
62080-293 = "But participation isn't quite the same as attendance. Like how you can read the words on a page but not understand a word of it."
62080-294 = "...There are people on the outside who read the summaries of books and speak as if their opinion is fact and law!"
62080-295 = "...And there are even people who think books are for decorating walls and bookshelves...!"
62080-296 = "In the first place, a book is a conversation between the writer and the reader! You can't just skim it and think you've communicated properly!"
62080-298 = "Show some respect! Respect the books! Respect them!!"
62080-300 = "Ui? You're losing the thread..."
62080-302 = "Eeek?!"
62080-303 = "M-My apologies. Anyways... Just like how reading is like that, the same goes for classes."
62080-304 = "Firstly, studying is the process of taking in something that's not yours, knowledge that you didn't know."
62080-305 = "Class is the process of a teacher giving you that knowledge, so that you can then take it and study more."
62080-306 = "You can go to class all you want, but if you don't pay attention..."
62080-307 = "...or if you forget everything as soon as you get home, then what was the point of even attending?"
62080-308 = "Ah...!"
62080-309 = "Of course, this is just speculation. But you're the only person who can corroborate it."
62080-310 = "From what I understand, the students who heard the trumpet's blow, the sign of the end of the world..."
62080-311 = "They must have been the students who were more open to accepting foreign knowledge and ideas."
62080-312 = "In other words, students who were less resistant to new perspectives coming into Arius."
62080-313 = "What do you think?"
62080-314 = "You're right! I think that makes sense! You're amazing, Ui!"
62080-315 = "N-Not at all... It was all just logic-based conjecture..."
62080-316 = "How many times have I told you that you should accept sincere compliments with sincere gratitude?"
62080-317 = "Eeek?!"
62080-318 = "A-And if they were open to seeing and accepting the outside world..."
62080-319 = "...then they'd likely already begun having doubts about Arius as a whole."
62080-320 = "...Knowledge and education are considered among the strongest stimuli for personal growth and change."
62080-321 = ""
62080-323 = ""
62080-324 = ""
62080-325 = "If they're beginning to harbor doubts, wouldn't that mean...?"
62080-326 = "Yes."
62080-327 = "Sooner or later, those students could end up like her..."
62080-328 = "They might be branded as \"enemies\" at any moment, by the students who don't want Arius to change."
62080-330 = "Does that mean the Trumpeting Angels might be...?"
62080-331 = "Who knows. They could really be the angels from the Book of Revelation..."
62080-332 = "But I suppose it'd be fair to say there's a lot of room for interpretation."
62080-333 = "It could be some sort of a \"phenomenon,\" created by a collection of Arius students'..."
62080-334 = "...hostilities, anxieties, angers, and other negative emotions directed toward the outside world..."
62080-335 = "..."
62080-336 = "It's just as Ui said. That's also what I believe."
62080-337 = "However, if that is what those Trumpeting Angels are..."
62080-338 = "Then what's within them..."
62080-340 = "...is something darker and far more sinister than one could have thought."
62080-342 = "Next Episode;Apocrypha"
