[translation]
62100-1 = "#title;10화;둥지"
62100-2 = "2;니코 아리우스 학생 A 마스크OFF;09\n4;니코 아리우스 학생 B 마스크OFF;04\n#2;h\n#4;h\n#2;a\n#4;a\n#wait;1000"
62100-3 = "2;니코 아리우스 학생 A 마스크OFF;04;부탁드립니다, 사오리 선배! 이만 돌아가 주세요!\n#2;jump\n#2;em;[!]"
62100-4 = "4;니코 아리우스 학생 B 마스크OFF;06;저희는 여기를 지키라는 명령을 받았어요! 누구도 들어오지 못하게 하라고요!\n#4;hophop"
62100-6 = "3;사오리;S2_20;대립하기만 해서는 아무것도 변하지 않는다!\n#3;em;[반응]"
62100-7 = "3;사오리;S2_19;너희들이 우리를 탐탁지 않게 생각하고 있다는 것은 알고 있지만…… 그래도 길을 열어 주었으면 한다!"
62100-8 = "3;사오리;S2_15;우리는 단지…… 수업 거부를 하고 있는 카케하시 스바루와, 상담을 하러 온 것뿐이다!"
62100-9 = "3;사오리;S2_20;애초에 여기는, 누구에게도 허락되지 않은 장소였다!\n#3;jump\n#3;em;[!]"
62100-11 = "4;니코 아리우스 학생 B 마스크OFF;06\n2;니코 아리우스 학생 A 마스크OFF;09;그, 그건 그렇긴 한데……!\n#2;stiff"
62100-12 = "4;니코 아리우스 학생 B 마스크OFF;05;어떻게 하지……?"
62100-13 = "2;니코 아리우스 학생 A 마스크OFF;05;그래도 스바루 선배는…… 여기를 지키라고 했어."
62100-14 = "4;니코 아리우스 학생 B 마스크OFF;04;그냥 진지 만들고 있으라고 했던 것 같은데…….\n#4;em;[땀]"
62100-15 = "2;니코 아리우스 학생 A 마스크OFF;06;밖에서든 안에서든 나오지 못하게 하라고 했으니까, 비슷한 말일 거야!"
62100-16 = "4;니코 아리우스 학생 B 마스크OFF;05;역시 돌아가 주세요! 안 그러면 저희도 발포할 수밖에–\n#4;jump"
62100-17 = "#st;[0,0];instant;1;"
62100-20 = "2;니코 아리우스 학생 A 마스크OFF;07\n4;니코 아리우스 학생 B 마스크OFF;04\n#2;h\n#4;h\n#2;em;[!]\n#4;em;[!]\n#wait;1500"
62100-21 = "2;니코 아리우스 학생 A 마스크OFF;04;누, 누구야?!\n#2;hophop"
62100-22 = "2;니코 아리우스 학생 A 마스크OFF;04\n4;니코 아리우스 학생 B 마스크OFF;04\n#na;니코 아리우스 학생들;아, 미안……. 발포라는 말이 들려서……."
62100-23 = "#st;[0,0];instant;1;"
62100-25 = "2;니코 아리우스 학생 A 마스크OFF;04\n4;니코 아리우스 학생 B 마스크OFF;04\n#2;h\n#4;h\n#2;d\n#4;d\n#wait;1000"
62100-26 = "1;미사키;02\n5;히요리;10\n3;사오리;S2_02\n#1;h\n#3;h\n#5;h\n#1;a\n#3;a\n#5;a\n#wait;1000"
62100-27 = "1;미사키;02\n5;히요리;10\n3;사오리;S2_00;……쏜 건가."
62100-28 = "1;미사키;05;그래. 쐈네."
62100-29 = "5;히요리;04;어쩐지 이렇게 될 것 같긴 했는데요오…….\n#5;em;[세로선]"
62100-31 = "3;마이아;04;괘, 괜찮으시겠어요?! 숫자 차이가 너무 나는데요……\n#3;shake\n#3;em;[?!]"
62100-32 = "3;마이아;04\n1;아츠코;S2_02;걱정하지 마.\n#1;ar\n#3;m4"
62100-33 = "3;마이아;15;근거라도 있나요?!\n#3;hophop"
62100-35 = "3;미사키;03;근거라……."
62100-36 = "3;아츠코;S2_02;역시 보여주는 게 빠르겠지?"
62100-37 = "3;아츠코;S2_03;부탁할게. 선생님.\n#3;em;[음표]"
62100-38 = "[s] \"왜 가장 중요할 때 결론은 이렇게 되는 걸까!\""
62100-39 = "3;아츠코;S2_05;그건……."
62100-41 = "#na;아츠코;어떤 의미로는, 아리우스식이니까?"
