[translation]
63040-1 = "Episode 4;Royal Blood"
63040-2 = "Royal blood."
63040-3 = "Special blood. A special lineage."
63040-4 = "For as long as I remember, I was placed on an imaginary pedestal for this one, intangible thing."
63040-5 = "To me, it meant nothing."
63040-6 = "After all, I was treated like trash, all the same."
63040-7 = "The more \"special\" I was, the more restrictions I had. The more things I couldn't speak of."
63040-9 = "Thank you, Sao-Sao."
63040-10 = "I was able to endure because of you."
63040-12 = "Thank you, [USERNAME] Sensei."
63040-13 = "Our meeting is what finally allowed me to be myself."
63040-15 = "Misaki, and Hiyori too."
63040-16 = "If not for each one of you, I would have remained a voiceless doll, a sacrifice."
63040-17 = "My entire life would've been spent as someone else's symbol."
63040-18 = ""
63040-19 = "Did learning the mysteries of Arius make you feel powerful?"
63040-20 = "Did you graze paths with what lies sleeping under this land, and believe you were unstoppable?"
63040-21 = ""
63040-23 = ""
63040-24 = "Too bad for you. That amount of knowledge..."
63040-25 = "...it was my birthright, before it was even a thought in your mind."
63040-26 = "But at least now I can be certain of one thing."
63040-27 = "The Angels of Revelation were merely a phenomenon brought about by Kakehashi Subaru."
63040-28 = "You weren't even aware what you'd done at first, correct? But, without realizing it, you summoned them."
63040-29 = "I hope you're not too disappointed."
63040-30 = "This isn't the Trumpeting Angel of the scriptures."
63040-31 = "There was a chance, however. This phenomenon could have transcended into the true seven Trumpeting Angels."
63040-32 = "If only you could have been a flawless judge."
63040-33 = "A...\"flawless judge\"?"
63040-34 = "Like I said, you're not the only one of Arius here."
63040-35 = "You're not the sole keeper of Arius' secrets."
63040-36 = "Thus...revelation, so to speak, has been mine since long ago."
63040-37 = "I was simply forbidden to speak of it. I still am."
63040-38 = "That is what it is to carry the royal blood of Arius."
63040-39 = "Even so, I should thank you, Subaru."
63040-40 = "I can speak a bit more freely now, since you've exposed a part of it."
63040-41 = "It is rather refreshing. Do you know how suffocating it can be to be the only one in the room to know something?"
63040-42 = "[ns] \"So what exactly is it, Atsuko?\""
63040-43 = "Before us, that angel...rather, that angel-shaped thing..."
63040-44 = ""
63040-46 = "Simply put, it is a phenomenon, the manifestation of Arius' energy and emotions."
63040-47 = "I told you a while ago, remember? That Arius has become a land where the inexplicable happens."
63040-48 = ""
63040-49 = "[ns] \"Ah...!\""
63040-50 = ""
63040-51 = "There was always \"something\" in Arius."
63040-52 = "Lament, grudge, resentment, rage, resignation... this place is where all of that comes to gather."
63040-54 = "...One way or another, Arius' leadership wanted to bring about the end of the world."
63040-55 = ""
63040-56 = ""
63040-57 = "I'll be honest, Sensei. That's exactly it."
63040-60 = ""
63040-61 = "A neglected child will set fire to their village just to feel the warmth of the flames."
63040-62 = "To someone who has nothing left to lose, the end of the world might even feel like salvation."
63040-63 = ""
63040-64 = "[ns1] \"You mean to say it could have...transcended?\"\n[ns2] \"You also said it'd be possible with a 'flawless judge,' right?\""
63040-67 = "Yes. Whatever was simmering beneath the surface in Arius was powerful enough to make that happen."
63040-68 = "...At the very least, it was enough to pay 'some kind of result' back to Trinity."
63040-69 = "If, literally, Subaru had been flawless."
63040-70 = "So you're saying there was some kind of flaw?"
63040-71 = "There was."
63040-72 = "And that flaw was this child."
63040-73 = "Ah...!"
63040-74 = ""
63040-75 = ""
63040-77 = "I... I..."
63040-78 = "It seems you finally understand."
63040-79 = "The moment you abandoned this child, there was no longer any justification for your actions."
63040-80 = "It would have been better if you had used yourself as the medium to construct this phenomenon."
63040-81 = "Instead, you chose of your own will to become the Trumpeting Angel."
63040-82 = "I understand. You, and all those who remained in Arius, must have so fervently desired to play the role of judge."
63040-83 = "There was an intrinsic issue, however."
63040-84 = "A judge must be flawless."
63040-85 = "\"Whoever digs a hole and scoops it out falls into the pit they have made.\""
63040-86 = "You remember that verse, don't you?"
63040-87 = "If nothing else, if only Maia had..."
63040-88 = "Even if you hadn't sought out Sensei, you still had potential to become a judge."
63040-91 = "Don't abandon me!"
63040-92 = ""
63040-94 = ""
63040-103 = "Ah..."
63040-104 = "Ah... Aaah..."
63040-105 = ""
63040-106 = "Subaru?"
63040-107 = "I heard a faint voice. Could it be...maybe...?"
63040-108 = "..."
63040-109 = ""
63040-111 = ""
63040-113 = ""
63040-114 = ""
63040-115 = ""
63040-116 = "H-Hiyori...?"
63040-117 = "If you have something you'd like to say, you can say it, Maia!"
63040-118 = ""
63040-120 = ""
63040-121 = "Th-That's why we came all this way, right?"
63040-123 = "..."
63040-124 = ""
63040-126 = ""
63040-127 = "Yes, thank you, Hiyori."
63040-130 = "Um, Subaru? Um, there's something I've wanted to tell you. For a long time now."
63040-131 = ""
63040-132 = "It's okay, Subaru."
63040-133 = "Everything...is okay."
63040-134 = "...!"
63040-135 = "I definitely don't understand everything, but I think I understand you pretty well, Subaru."
63040-136 = "You, the Squad, and everyone in Arius..."
63040-137 = "And you, [USERNAME] Sensei. I really...like all of you."
63040-138 = "So I don't want Arius to disappear."
63040-139 = "I just want Arius to become a better school."
63040-140 = "S-So what I'm trying to say is..."
63040-141 = ""
63040-143 = ""
63040-144 = "So... Um..."
63040-145 = "Please help me, Subaru!!"
63040-147 = "...!"
63040-148 = "I really, really love when you play the harmonica!!"
63040-150 = "Next Episode;Harmonica 2"
