[translation]
70006020-1 = "Fine Dining, Cookies, and Aid Episode 2"
70006020-2 = "It began with a strange rumor...about me."
70006020-4 = "Saint Teresa General Hospital Lobby"
70006020-5 = "Um..."
70006020-6 = ""
70006020-8 = ""
70006020-9 = "Captain? Is something wrong? You look sad."
70006020-10 = "Oh, let ME cheer you up!"
70006020-12 = "Don't worry. I'm fine. ...There's a rumor going around about me."
70006020-14 = "A rumor?"
70006020-15 = "Is it the one where you like to collect medical supplies because you like the smell of patches?"
70006020-17 = "Not that."
70006020-18 = "What about the one where the reception's a front for you to find new targets?"
70006020-19 = "Not that either..."
70006020-20 = "I did hear one about how you're secretly eating protein cookies at tea time so you can bulk up..."
70006020-21 = "No...!"
70006020-22 = "Where are you hearing any of that?! It's all wrong! VERY wrong!"
70006020-23 = "Don't worry too much! We know you're not actually like that!"
70006020-24 = "Nonetheless, it's disturbing how fast these stories spread."
70006020-25 = "All I've ever wanted was to foster the spirit of aid, in as many people as possible."
70006020-27 = "Sorry to hear..."
70006020-28 = "How can we fix this?"
70006020-29 = ""
70006020-31 = ""
70006020-32 = "Oh, I know!"
70006020-33 = "We bake a bunch of cookies and hand them out to as many people as possible."
70006020-34 = "When they taste the love we put into those cookies, all the misunderstandings about the captain will just go away!"
70006020-36 = "Oh, we should make the cookies cute! Like little animals. Chicks or something."
70006020-37 = "A chick-shaped cookie. That's a great idea!"
70006020-39 = "...So we decided to make chick cookies, but there was a problem."
70006020-40 = "I've never baked cookies before."
70006020-41 = "Serina and Hanae helped, but the first attempt was a total disaster."
70006020-42 = "They didn't look like chicks. They looked like some twisted monsters from hell..."
70006020-43 = "So I sought advice from a famous bakery in Trinity, but..."
70006020-44 = "Their recipes were too fancy, with filling and icing and such. Perhaps they assumed I was more advanced than I truly was."
70006020-45 = "So you still preferred the chick cookies."
70006020-46 = "You know what they say. Cuteness is justice."
70006020-47 = "That aside, I went looking for more advice, and I came across Fuuka in the shopping district."
70006020-48 = "Schale's shopping district is a melting pot, of course. One might find Trinity and Gehenna students shopping side by side."
70006020-49 = "And so, the famous Remedial Knights met Fuuka."
70006020-51 = "Indeed. But we need not rush that story..."
70006020-53 = "I picked up lots of fresh ingredients today."
70006020-54 = "This will be enough for a while..."
70006020-55 = "...as long as THEY don't show up this time."
70006020-56 = ""
70006020-59 = ""
70006020-60 = "Hm..."
70006020-61 = ""
70006020-63 = ""
70006020-64 = "Oh... Hello. Can I help you with something...?"
70006020-65 = "Hello there. Are you interested in aid work, by any chance?"
70006020-66 = "...Excuse me?"
70006020-67 = "I am Mine, captain of Trinity General School's Remedial Knights."
70006020-69 = "T-Trinity? The captain?!"
70006020-70 = "Indeed. The moment I saw you from afar, I felt a strange sense of kinship."
70006020-71 = "The care with which you chose those ingredients, it reminded me of how I agonize over choosing medical supplies."
70006020-72 = "I-Is that so...?"
70006020-73 = "Seeing the concern upon your very kind face, I took you for an aid worker. Are you?"
70006020-74 = "Uh... I'm the president of Gehenna's School Lunch Club..."
70006020-75 = ""
70006020-77 = ""
70006020-78 = ""
70006020-79 = "I knew it...! My eyes did not deceive me!"
70006020-80 = "Might we take a moment to talk? I have a feeling we'll get along famously."
70006020-81 = "Huh? But...you're Trinity, I'm Gehenna..."
70006020-82 = "A meaningless distinction, compared to the great cause of aid. Is it not?"
70006020-83 = "Well...yeah, you're right about that. I believe in feeding the hungry no matter who they are..."
70006020-85 = "...although some are a handful."
70006020-86 = "A handful...?"
70006020-88 = "So that's how you heard about us."
70006020-89 = "They also asked me to help them make cookies."
70006020-90 = "I figured, if the Remedial Knights wanted to be friendly, why not?"
70006020-91 = "So if you could, just give it a rest today, and the Knights and I will go buy some cookie ingredients."
70006020-92 = "As you wish. Consider our lunch request on hold."
70006020-93 = "We have a new plan instead."
70006020-94 = "Mine, with your permission, may the Gourmet Research Society handle the tasting of your chick cookies?"
70006020-95 = "I sensed the aura of gourmet food the moment I heard the story."
70006020-96 = "Heehee, I want to taste them! ★"
70006020-97 = "Yeah, I love cookies!"
70006020-98 = "Tasting's free, right? Heeheehee..."
70006020-100 = "Well, you're all back on your feet, I see."
70006020-101 = "Tasting... Perhaps the Gourmet Research Society would know taste better than we do."
70006020-102 = "I don't think anything good will come out of getting them involved..."
70006020-104 = "Don't worry. We're merely curious about the cookies, that's all."
70006020-105 = "And with your help, Fuuka, they'll come out perfectly."
70006020-106 = "Well...they will, but..."
70006020-107 = "What do you say, Captain?"
70006020-108 = "I'm all for it! Making cookies with you, it sounds great!"
70006020-110 = "Very well. We will all go together."
70006020-111 = "Ah, I'm getting a bad feeling..."
70006020-113 = ""
70006020-114 = ""
70006020-115 = ""
70006020-116 = ""
70006020-117 = ""
70006020-118 = ""
70006020-120 = ""
70006020-121 = ""
70006020-123 = ""
70006020-124 = ""
70006020-125 = ""
70006020-126 = ""
70006020-128 = "A short time later..."
70006020-130 = "Trinity Kitchen"
70006020-131 = "Ah, they smell delicious. How much longer until they're done?"
70006020-132 = "Just a bit. Almost."
70006020-134 = "All right, let's get ready, then."
70006020-135 = "Are we really okay to be here right now?"
70006020-137 = "Of course we are. Just enjoy, like we planned."
70006020-138 = ""
70006020-140 = ""
70006020-141 = "...Liiike we planned."
70006020-142 = "Does that mean if they taste bad, you're going to blow it all up?"
70006020-143 = "Heeheehee, I wonder..."
70006020-145 = "The wait is finally over!"
70006020-146 = "Captain Mine's cute cookies are finished!"
70006020-147 = ""
70006020-149 = ""
70006020-150 = ""
70006020-151 = ""
70006020-152 = "..."
70006020-154 = "Come on, show us!"
70006020-155 = "I'm sure everyone will like them."
70006020-157 = "A-All right."
70006020-158 = "Everyone...! These are the cookies I've made."
70006020-159 = ""
70006020-161 = ""
70006020-162 = ""
70006020-164 = "Ooh, I feel warm simply looking at them."
70006020-165 = "The presentation's solid, that's for sure. ★"
70006020-166 = "They're so cute! It feels like a shame to eat them!"
70006020-167 = "Can we, though? Can we eat them now?"
70006020-169 = "Ha, all this praise... My cheeks must be so red..."
70006020-170 = "There's no smoke without fire, as they say. In other words, we all speak the truth."
70006020-171 = "Unlike these rumors you've concerned yourself with. One can't go through life taking everything at face value. We here see the real Mine for who she truly is."
70006020-172 = "...!"
70006020-174 = "Wow! It worked, Captain!"
70006020-175 = "Now everyone will get to know the real you!"
70006020-177 = "W-Wonderful..."
70006020-178 = "All right, let's taste them already!"
70006020-179 = ""
70006020-181 = ""
70006020-183 = "Heeheehee, should I eat the head first? Or the body?"
70006020-184 = "Eat the head first. It's merciful."
70006020-186 = "Then, time to dig in...!"
70006020-187 = ""
70006020-189 = ""
70006020-191 = ""
70006020-193 = ""
70006020-194 = ""
70006020-195 = ""
70006020-197 = "Wait, this taste...!"
70006020-198 = "This is dangerous... ★"
70006020-199 = "I never had a cookie like this in my life...!"
70006020-200 = "How should I put this... Basically..."
70006020-201 = "This tastes INCREDIBLE!!"
70006020-203 = "The rich, sweet egg taste that spreads in your mouth. It's irresistible!"
70006020-204 = "I really love the youthful vibe you get from this crispy texture."
70006020-205 = "This cookie tastes cute! I've eaten a lot of things. I've never TASTED cuteness before!"
70006020-206 = "...There's more to enjoying food than taste, of course. One also enjoys the care that went into making it."
70006020-207 = "And these cookies are filled with your care, Mine."
70006020-208 = "Gourmet food, no question."
70006020-209 = "...S-Such praise."
70006020-210 = "Thank you all so much. Getting recognized by the Gourmet Research Society gives me great confidence."
70006020-211 = "Honestly, I was dreading failure..."
70006020-212 = "Fufu, I'm really glad I didn't blow this place up."
70006020-213 = "I KNEW you were thinking of that!"
70006020-214 = "But they're all delicious, right?"
70006020-215 = "For sure! Can I have some more?"
70006020-217 = "Of course. Have all you like. I made plenty for all."
70006020-218 = "Wow...!"
70006020-220 = "Captain, these cookies are going to show everyone how you feel."
70006020-221 = "That's right! I'm sure even Vice President Hasumi, from the Justice Task Force, will like them."
70006020-223 = "Vice President Hasumi... I hope she doesn't laugh at me."
70006020-225 = "Oh, she's picky about desserts, but she won't laugh at these!"
70006020-226 = "I hope this brings you two closer together."
70006020-228 = "H-Hmm...!"
70006020-229 = "Anyway, thank you so much. Thanks to all of you, I experienced something new."
70006020-230 = "I especially owe a huge thanks to Fuuka. Thanks to her incredible guidance, these cookies..."
70006020-231 = ""
70006020-233 = ""
70006020-234 = "...Huh? Fuuka?"
70006020-236 = "Huh? Where did she go? She was here when we were making them."
70006020-237 = "I don't think I've seen her since the tasting started..."
70006020-239 = "Well, Remedial Knights, we'll be heading out."
70006020-240 = "Mmph...! Mmmph!"
70006020-241 = "Fuuka?! Why are you all tied up?!"
70006020-242 = "When did she...!"
70006020-243 = "When you took the cookies and left the kitchen."
70006020-244 = "The cookies were so nice, they distracted you... ★"
70006020-245 = "And in that short amount of time...?"
70006020-247 = "Heeheehee, you know how many times we've done this with Fuuka? It's easy."
70006020-248 = "Don't BRAG about it...!"
70006020-249 = "Mmph! Mmmph...!"
70006020-250 = "Oh, she wants to hurry and make lunch for us!"
70006020-251 = "Let's get moving, then. Ah, we should call Juri first..."
70006020-252 = ""
70006020-254 = ""
70006020-255 = ""
70006020-256 = "Haruna. Did you find Fuuka?"
70006020-257 = "Yes. She is safely under our protection."
70006020-258 = "We found her picking out ingredients."
70006020-259 = "Oh, that's where she was. Great, just please keep watching over her."
70006020-260 = "Oh, leave it to us. We certainly will."
70006020-261 = ""
70006020-263 = ""
70006020-264 = "Well, I believe that's everything."
70006020-265 = "Thank you for the cookies! ★"
70006020-266 = ""
70006020-268 = ""
70006020-269 = ""
70006020-270 = ""
70006020-271 = ""
70006020-272 = "How dare you treat a friend that way?!"
70006020-273 = "Medicine knows no borders! We will pursue you wherever you go!"
70006020-274 = ""
70006020-278 = "Sh-She blew a hole in the wall..."
70006020-279 = "Ahaha... This \"changing her image\" thing might be a little harder than we thought."
70006020-281 = "Gourmet Research Society...! You will not escape!"
70006020-282 = "Fufu, you're not catching us this time!"
70006020-283 = "Mmph! Mmmmph!"
70006020-284 = ""
70006020-290 = "And so began a great chase..."
70006020-291 = "Fine Dining, Cookies, and Aid"
