[translation]
70001030-1 = "\n#title;테르마이 아카이 3"
70001030-2 = "2;노도카 온천ND;06\n4;시구레 온천ND;04\n#2;h\n#4;h\n#2;a\n#4;a\n#wait;1000"
70001030-3 = "2;노도카 온천ND;34;결국 이곳이 마지막인가……\n#2;em;[땀]"
70001030-4 = "4;시구레 온천ND;00;어쩔 수 없잖아. 방문한 목욕 시설마다 저마다의 단점이 있었으니까."
70001030-5 = "2;노도카 온천ND;06;그건 그렇긴 하지만……"
70001030-6 = "2;노도카 온천ND;34;그래도 밀레니엄 학원의 물건만큼은 구입하고 싶지 않았는데."
70001030-7 = "4;시구레 온천ND;02;……어째서?\n#4;em;[?]"
70001030-8 = "2;노도카 온천ND;12;뭔가 밀레니엄 학원에서 제작한 물건이라고 하면, 기본적으로 엄청난 수준의 첨단 기술이 포함되어 있다는 인상이 강하잖아?"
70001030-9 = "2;노도카 온천ND;18;휴게실에서 커피를 뽑아주는 자판기에도 인공지능이 달려 있다는 소문이 있는데, 목욕 시설은 더더욱 비용이 만만치 않을 거야……"
70001030-10 = "4;시구레 온천ND;01;에이…… 그래도 그건 너무 터무니없는 소문 아닐까?"
70001030-11 = "4;시구레 온천ND;00;일단 가격을 문의하고 난 뒤에 돌아가도 늦지는 않으니까."
70001030-12 = "2;노도카 온천ND;13;으응……\n#2;em;…"
70001030-13 = "#st;[0,0];instant;1;"
70001030-15 = "2;노도카 온천ND;02\n4;시구레 온천ND;07\n#2;h\n#4;h\n#wait;2500"
70001030-17 = "1;우타하;06\n3;코토리;04\n5;밀레니엄 기숙사장;04\n#1;h\n#3;h\n#5;h\n#1;a\n#3;a\n#5;a\n#wait;1000"
70001030-18 = "1;우타하;06\n3;코토리;04;기, 긴급 철거라니요?!\n#3;jump\n#3;em;[?!]"
70001030-19 = "1;우타하;06\n3;코토리;04;저희가 새로 개조한 기숙사 목욕 시설에 무슨 문제가 있었나요?"
70001030-20 = "5;밀레니엄 기숙사장;04;아, 아뇨. 특별히 당장 문제가 있는 건 아니지만……\n#5;em;[땀]"
70001030-21 = "5;밀레니엄 기숙사장;02;잠시 뒤에 다른 학원에서 오신 특사 여러분이 저희 기숙사를 견학하실 예정이거든요."
70001030-22 = "5;밀레니엄 기숙사장;05;그런데 세미나의 검토도 받지 않은 엔지니어 부의 발명품을 다른 학원의 학생들에게 보여주는 건 조금……"
70001030-23 = "1;우타하;99;이해할 수가 없군. 우리도 엄연한 밀레니엄 사이언스 스쿨의 일원으로서, 우리가 만든 발명품을 외부에 선보일 자격이 있을 텐데."
70001030-24 = "1;우타하;05;오히려 그렇게 중요한 자리에 선보일 물건이라면 우리 엔지니어 부에게 맡겨주는 편이 더 낫지 않겠어?\n#1;em;[반응]"
70001030-25 = "5;밀레니엄 기숙사장;04;하지만 여러분이 그동안 만든 물건은ㅡ"
70001030-27 = "3;노도카 온천ND;02\n#3;a\n#wait;1000"
70001030-28 = "3;노도카 온천ND;02;저, 죄송합니다…… 붉은겨울 학원에서 왔는데요."
70001030-29 = "3;노도카 온천ND;02\n5;밀레니엄 기숙사장;06;버, 벌써 오셨나요?!\n#3;m1\n#5;al\n#5;em;[?!]"
70001030-30 = "5;밀레니엄 기숙사장;04;죄송합니다…… 아직 시설의 정리가 완전히 끝나지 않아서요."
70001030-31 = "3;노도카 온천ND;02;그런가요? 겉으로 보기에는 이미 깨끗하게 다 정리된 것처럼 보이는데……"
70001030-32 = "#st;[0,0];instant;1;"
70001030-34 = "5;밀레니엄 기숙사장;04\n1;노도카 온천ND;02\n3;우타하;99\n#1;h\n#3;h\n#5;h\n#3;ar\n#wait;1000"
70001030-35 = "3;우타하;99;음, 그 말대로야. 새로운 목욕 시설의 준비는 완벽해!\n#3;greeting\n#3;em;[음표]"
70001030-36 = "5;밀레니엄 기숙사장;06;우, 우타하 부장……!\n#5;jump"
70001030-37 = "1;노도카 온천ND;02;새로운 목욕 시설이요……?"
70001030-38 = "1;밀레니엄 기숙사장;06\n3;우타하;99\n5;노도카 온천ND;13\n2;히비키;01\n4;코토리;99\n#1;hide\n#3;hide\n#5;hide\n#2;h\n#4;h"
70001030-39 = "2;히비키;01\n4;코토리;99;이번에 밀레니엄 기숙사에 새롭게 설치한 목욕 시설의 기능에 대해서는 제가 직접 설명드리겠습니다!\n#4;jump"
70001030-40 = "2;히비키;01\n4;코토리;99;먼저, 가운데 위치한 이 신형 욕조는 첨단 인공지능이 탑재되어 있기 때문에, 사용자의 니즈에 맞추어 실시간으로 물의 온도를 조절할 수 있지요."
70001030-41 = "2;히비키;01\n4;코토리;00;욕조에 탑재된 첨단 인공지능이 사용자의 피부 온도와 반응을 자동으로 분석하기 때문에 귀찮게 온수와 냉수를 섞을 필요가 없어요!\n#4;em;[재잘]"
70001030-42 = "2;히비키;02;거기에 더해 물을 덥히는 데 쓰이는 보일러는 주변의 열원으로부터 열을 흡수하는 히트 펌프 방식이기 때문에 냉매로도 사용할 수 있지……"
70001030-43 = "2;히비키;03;이 냉매를 활용한 냉장고 기능도 욕조에 포함되어 있기 때문에, 목욕 중에 차가운 음료수를 마실 수도 있어……"
70001030-45 = "3;시구레 온천ND;01\n#3;a\n#wait;1000"
70001030-46 = "3;시구레 온천ND;00;냉장고가 딸린 욕조라니…… 그거 멋진데?\n#3;em;[음표]"
70001030-48 = "3;우타하;01;그리고 이 목욕 시설에는 게으름뱅이들을 위한 자동 목욕 보조 기능도 포함되어 있거든."
70001030-49 = "3;우타하;99;욕조에 설치된 인공지능에게 음성으로 명령하면 여러 개의 로봇 팔이 튀어나와 몸을 자동으로 깨끗이 씻겨주지."
70001030-50 = "3;우타하;03;이 욕조 하나만으로도 여러 개의 가전을 대체할 수 있다고."
70001030-52 = "3;노도카 온천ND;12;저…… 이야기만 들으면 정말 멋진 제품이긴 한데요……"
70001030-53 = "3;노도카 온천ND;13;역시 이 정도의 기술이 집약된 목욕용품을 구입하려면 돈이 많이 들겠죠……?"
70001030-55 = "3;코토리;99;비용에 대해서는 걱정하지 않으셔도 좋아요!\n#3;jump"
70001030-56 = "3;코토리;00;이 신형 목욕 시설은 아직 테스트를 충분히 거치지 않은 시제품이기 때문에 제작비만 받고 시공부터 수리까지 저희 엔지니어부에서 직접 책임져 드립니다!\n#3;em;[재잘]"
70001030-58 = "3;히비키;07;물론 시운전 중에 발생하는 사고에 대해서는 책임지지 않는다는 계약서를 추가해야 하지만……"
70001030-59 = "#st;[0,0];instant;1;"
70001030-61 = "3;히비키;01\n#3;greeting\n#wait;1500"
70001030-62 = "3;히비키;01\n#3;greeting\n#wait;1500"
70001030-63 = "3;히비키;02;……이 정도까지 할인해 줄 수 있어."
70001030-65 = "#st;[0,0];instant;1;"
70001030-67 = "3;노도카 온천ND;02\n#3;em;…\n#wait;2500"
70001030-68 = "3;노도카 온천ND;16;이러면 평범한 목욕 시설보다 훨씬 저렴하잖아요?\n#3;em;[반짝]"
70001030-69 = "3;노도카 온천ND;03;계약할게요! 바로 밀레니엄과 계약하겠어요!\n#3;jump"
70001030-70 = "3;노도카 온천ND;03\n5;밀레니엄 기숙사장;01;저, 외부 학원에서 오신 분이라 잘 모르시는 것 같은데……\n#5;al\n#3;m1"
70001030-71 = "5;밀레니엄 기숙사장;02;저희 엔지니어부의 발명품은 성능만큼은 확실하지만, 늘 예상치 못한 부가 기능이 하나씩 추가되는 것으로 악명이 높거든요……"
70001030-72 = "5;밀레니엄 기숙사장;04;안전성 테스트를 하려면 시간이 더 걸릴 것 같으니, 이번에는 다른 학원의 시설을 사용하시는 것이……"
70001030-73 = "3;노도카 온천ND;10;상관없어요. 오히려 구입한 제품에 추가 기능이 있다면 더 좋은 게 아닌가요?"
70001030-74 = "#st;[0,0];instant;1;"
70001030-76 = "5;밀레니엄 기숙사장;04\n3;노도카 온천ND;10\n#5;d\n#3;d\n#wait;1000"
70001030-77 = "5;밀레니엄 기숙사장;04\n3;노도카 온천ND;10\n#5;hide\n#3;hide"
70001030-78 = "1;히비키;01\n3;우타하;01\n5;코토리;01\n#1;h\n#3;h\n#5;h\n#1;a\n#3;a\n#5;a\n#wait;1000"
70001030-79 = "3;우타하;99;음, 좋은 자세야. 공짜로 덤을 준다는 데 거절하는 건 손해 보는 짓이지.\n#3;greeting"
70001030-80 = "1;히비키;03;서비스~ 서비스~\n#1;em;[음표]"
70001030-82 = "3;노도카 온천ND;03;붉은겨울 학원의 특사로서 즉시 승인하겠습니다!"
70001030-83 = "3;노도카 온천ND;08;엔지니어부 여러분이 제작한 신형 목욕 시설을 저희 붉은겨울 학원의 기숙사에도 설치해 주세요!"
70001030-85 = "1;히비키;01\n3;우타하;01\n5;코토리;02;맡겨만 주세요!\n#5;jump"
70001030-86 = "#st;[0,0];instant;1;"
70001030-88 = "1;히비키;03\n3;우타하;03\n5;코토리;03\n#1;h\n#3;h\n#5;h\n#1;em;[반짝]\n#3;em;[반짝]\n#5;em;[반짝]\n#wait;2500"
70001030-89 = "#all;hide\n#place;붉은겨울 학원 공용 기숙사"
70001030-91 = "4;체리노 온천ND;01\n#4;a\n#wait;1000"
70001030-92 = "4;체리노 온천ND;02;흐음…… 이게 이번에 특별반 녀석들이 밀레니엄 학원에서 새로 들여온 목욕 시설인가……"
70001030-93 = "4;체리노 온천ND;99;겉보기에는 멀쩡해 보이지만, 밀레니엄의 헛똑똑이들이 붉은겨울 학원을 사보타주하기 위해 수상한 장치를 추가했을지도 몰라."
70001030-94 = "4;체리노 온천ND;08;그렇다면 붉은겨울 학원의 학생회장이자, 미화부장이자, 서기장이자, 체육부장 등인…… 이 몸이 학생들의 안전을 위해 먼저 시험해 보지 않을 수 없지."
70001030-95 = "4;체리노 온천ND;03;……절대로 개인적인 호기심 때문에 먼저 들어가 보려는 게 아니니까!"
70001030-96 = "#st;[0,0];instant;1;"
70001030-98 = "4;체리노 온천ND;01\n#4;m3\n#wait;1000"
70001030-99 = "4;체리노 온천ND;02;어디 보자…… 설명서에 따르면 욕조에 설치된 인공지능이 자동으로 목욕을 시켜준다고?"
70001030-100 = "4;체리노 온천ND;03;여봐라, 인공지능. 이 체리노님의 머리를 감겨 보거라."
70001030-101 = "#na;목욕 로봇;<네, 자동 목욕 보조 기능을 활성화합니다.>"
70001030-102 = "#st;[0,0];instant;1;"
70001030-107 = "4;체리노 온천ND;02;오오…… 신기하군. 로봇 팔이 마치 사람 손처럼 머리를 감겨주고 있어."
70001030-108 = "4;체리노 온천ND;99;으음…… 생각보다 나쁘지 않은데……"
70001030-109 = "#st;[0,0];instant;1;"
70001030-113 = "4;체리노 온천ND;08;……으읏! 잠깐, 눈에 비누가 들어갔잖아!\n#4;stiff"
70001030-114 = "4;체리노 온천ND;05;좀 더 상냥하게 머리를 감기지 못할까! 숙청해 버린다!\n#4;jump"
70001030-115 = "#na;목욕 로봇;<숙청………>"
70001030-116 = "#na;목욕 로봇;<죄송합니다. '숙청'의 의미를 이해하지 못했습니다. 자동 목욕 보조 기능을 재개합니다.>"
70001030-117 = "4;체리노 온천ND;07;숙청이라는 표현도 이해하지 못하다니, 형편없는 지능의 로봇이로군!"
70001030-118 = "4;체리노 온천ND;01;됐다! 머리는 내가 직접 감을 테니, 이 손 치우거라!\n#4;jump"
70001030-119 = "#na;목욕 로봇;<주의. 로봇 팔이 작동하는 중에 욕조에서 이탈하면 부상의 위험이 있습니다.>"
70001030-120 = "#st;[0,0];instant;1;"
70001030-123 = "#na;목욕 로봇;<……사용자의 안전을 위해 구속 모드로 전환합니다.>"
70001030-124 = "4;체리노 온천ND;04;우읏……? 로봇 팔이 움직이지 못하게 몸을 억죄고 있잖아……?"
70001030-125 = "4;체리노 온천ND;04;이거 놔라! 목욕은 이제 되었다니까?"
70001030-126 = "#na;목욕 로봇;<충분한 목욕 효과를 보기 위해서는 비누칠을 하기 전에 더운물에 피부를 5분 이상 이완시키는 게 좋습니다.>"
70001030-127 = "#na;목욕 로봇;<그리고 비누칠을 할 때는 평소에 손이 잘 닿지 않는 귀 뒤와 손목 등을 집중적으로 문질러 주는 게 좋습니다.>"
70001030-128 = "4;체리노 온천ND;04;그만! 그만해! 이건 명령이다!\n#4;hophop"
70001030-129 = "#na;목욕 로봇;<사용자의 급격한 심박수 변환을 확인……>"
70001030-130 = "#na;목욕 로봇;<심신 안정에 도움이 되는 클래식 음악을 연주하겠습니다……>"
70001030-131 = "#st;[0,0];instant;1;"
70001030-138 = "#na;체리노 온천ND;그마아아아안!\n#fontsize;100"
70001030-139 = "#st;[0,0];instant;1;"
70001030-143 = "#na;(잠시 뒤……)"
70001030-144 = "1;토모에;01"
70001030-145 = "1;토모에;01\n5;체리노 온천ND;S2_13\n#1;h\n#5;al\n#wait;2500"
70001030-146 = "1;토모에;01\n5;체리노 온천ND;S2_13\n#1;h\n#5;m4\n#wait;2500"
70001030-147 = "1;토모에;01\n5;체리노 온천ND;S2_13\n#1;h\n#5;m3\n#wait;2500"
70001030-148 = "1;토모에;02;어머나, 체리노 쨩. 오늘은 꽤 오랫동안 탕에 들어가 계셨네요.\n#1;em;[반응]"
70001030-149 = "1;토모에;01;흠뻑 젖은 모습이 샤워를 막 마치고 나온 치와와 같아 보여서…… 뭔가 귀엽네요. 후후."
70001030-150 = "5;체리노 온천ND;S2_13;…….\n#5;em;…"
70001030-151 = "1;토모에;00;게다가 피부도 뽀송뽀송해 보이는 게…… 오늘은 열심히 비누칠을 해서 제대로 씻으신 모양이군요?"
70001030-152 = "1;토모에;01;밀레니엄 학원에서 들여온 새 목욕 시설이 마음에 드시는 것 같아 다행이에요."
70001030-153 = "5;체리노 온천ND;S2_09;……이야……\n#5;shake"
70001030-154 = "1;토모에;02;……네?"
70001030-156 = "3;체리노 온천ND;S2_05;……이 목욕 시설을 만든 녀석들은 모두 숙청이야!\n#3;closeup\n#fontsize;100"
70001030-158 = "#na;(이후 엔지니어 부에서 설치한 신형 목욕 시설은 모두 철거되었고, 227호 특별반 학생들은 다시 구교사로 쫓겨나게 되었다……)"
70001030-159 = "#na;(이 일로 인해 한동안 밀레니엄 학원과 붉은겨울 학원 사이의 관계가 서먹해져 여러 가지 문제가 추가로 발생했지만…… 그것은 또 다른 이야기이다.)"
70001030-161 = "#Ending;테르마이 아카이"
