[translation]
70003010-1 = "#title;하이랜더 운행 일지 1"
70003010-5 = "3;하이랜더 기관사;01\n#3;a\n#wait;1000"
70003010-6 = "3;하이랜더 기관사;03\n#3;greeting\n#wait;1500"
70003010-7 = "3;하이랜더 기관사;00;안녕하세요-! 저는 하이랜더 철도학원의 하이랜더 기관사입니다.\n#3;em;[재잘]"
70003010-8 = "3;하이랜더 기관사;00;오늘은 키보토스 내부 순환선의 운행이 예정되어 있는데요!"
70003010-9 = "3;하이랜더 기관사;02;아시다시피 내부 순환선은 연간 사건사고가 가장 많이 발생하는 노선이죠.\n#3;em;…"
70003010-10 = "3;하이랜더 기관사;08;운행 중에는 특이 사항이 발생하더라도 보통 내부 인력만으로 대응해야 해서, 살짝 긴장이 되네요."
70003010-11 = "3;하이랜더 기관사;05;문제가 커지거나 하면 병력을 요청하기도 하는데, 출동해서 도착하는 데에도 시간이 걸리고……\n#3;em;[속상함]"
70003010-12 = "3;하이랜더 기관사;02;아무래도 즉각 처리할 수 없는 일들이 종종 있다 보니, 조금 힘들기도 합니다."
70003010-13 = "3;하이랜더 기관사;99;……"
70003010-14 = "3;하이랜더 기관사;06;네에…… 그런 일이 조금 많긴 한데요……\n#3;stiff"
70003010-15 = "#st;[0,0];instant;1;"
70003010-17 = "3;하이랜더 기관사;08\n#3;em;[...]\n#wait;2500"
70003010-18 = "3;하이랜더 기관사;00;아하하, 어쨌든~!\n#3;hophop\n#3;em;[재잘]"
70003010-19 = "3;하이랜더 기관사;03;그렇게 전반적인 차량 관리나 운행 중 발생하는 사건사고에 대응하다 보면 근무 시간이 훅~ 지나간답니다!"
70003010-20 = "3;하이랜더 기관사;00;좋은 건진 모르겠지만 아무튼!\n#3;em;[!]"
70003010-21 = "3;하이랜더 승무원;00;뭐 하는 거야? 영상 통화?\n#3;closeup\n#3;em;[반응]"
70003010-22 = "3;하이랜더 기관사;04;앗, 아니……"
70003010-23 = "3;하이랜더 기관사;06;그게……\n#3;stiff\n#3;em;…"
70003010-24 = "#st;[0,0];instant;1;"
70003010-26 = "3;하이랜더 기관사;06\n5;하이랜더 승무원;01\n#5;em;[?]\n#3;m1\n#3;h\n#5;h\n#5;a\n#wait;1500"
70003010-27 = "3;하이랜더 기관사;08;브, 브이로그를 찍고 있었어요……\n#3;em;[땀]"
70003010-28 = "5;하이랜더 승무원;00;브이로그?"
70003010-29 = "3;하이랜더 기관사;04;네에……! 그, 뭐냐! 하이랜더 철도학원의 진면목을 좀 더 많은 이들에게 알리고자……\n#3;em;[!]"
70003010-30 = "5;하이랜더 승무원;05;헤에……\n#5;em;…"
70003010-31 = "3;하이랜더 기관사;07;그, 그리고 승객분들이 우리가 어떤 일을 하는지 알게 되면 좀 더 협조해 주지 않을까…… 하는 그런 마음으로……\n#3;stiff"
70003010-32 = "5;하이랜더 승무원;01;하긴. 그냥 열차 타고 빙글빙글 돌기만 하는 줄 아는 사람들도 많으니까."
70003010-33 = "5;하이랜더 승무원;06;얼마 전에도 \"네놈들이 하는 게 뭐냐!\"라며 소란을 피우던 승객이 있었지……\n#5;em;[한숨]"
70003010-34 = "3;하이랜더 기관사;08;그러니까요……\n#3;stiff\n#3;em;[속상함]"
70003010-35 = "5;하이랜더 승무원;03;그런 사람들이 워낙 많으니까, 뭐라도 해서 조금이라도 진상이 줄어들면 의미가 있겠네."
70003010-36 = "5;하이랜더 승무원;00;어쨌든 곧 출발이니까, 준비하자구.\n#5;em;[반응]"
70003010-37 = "3;하이랜더 기관사;02;네, 넵!\n#3;em;[!]"
70003010-38 = "#st;[0,0];instant;1;"
70003010-40 = "3;하이랜더 기관사;02\n5;하이랜더 승무원;00\n#5;d\n#3;h\n#5;h\n#wait;2000"
70003010-41 = "3;하이랜더 기관사;07;휴우……\n#3;m3\n#3;em;[한숨]"
70003010-42 = "3;하이랜더 기관사;01;어쨌든 오늘의 운행! 힘내보겠습니다. 이달의 우수 학생을 목표로……!\n#3;jump"
70003010-45 = "#place;열차 기관실"
70003010-46 = "3;하이랜더 기관사;03;흠…… 다행히 지금까지는 큰 이상 없이 운행 중이네요.\n#3;a\n#3;em;…"
70003010-47 = "3;하이랜더 기관사;02;객실 상황은 어떤가요?"
70003010-48 = "3;하이랜더 기관사;01\n#na;하이랜더 승무원;아- 객실도 이상 무."
70003010-49 = "3;하이랜더 기관사;01\n#na;하이랜더 승무원;3호차에서 좌석을 잘못 앉은 승객이 있었지만, 큰 문제 없이 잘 해결되었음."
70003010-50 = "3;하이랜더 기관사;03;다행이네요. 계속 이렇게 이상이 없으면 좋을 텐데……\n#3;greeting"
70003010-51 = "#st;[0,0];instant;1;"
70003010-54 = "3;하이랜더 기관사;05\n#3;em;[반응]\n#wait;1500"
70003010-55 = "3;하이랜더 기관사;02;아, 말하자마자……"
70003010-56 = "3;하이랜더 기관사;08;5호차에서 너무 춥다고 에어컨을 꺼달라는 민원이 들어왔네요.\n#3;em;[땀]"
70003010-57 = "3;하이랜더 기관사;01;에어컨 가동 온도를 조금 올려야겠어요.\n#3;greeting"
70003010-59 = "#na;(잠시 후……)"
70003010-60 = "3;하이랜더 기관사;01"
70003010-62 = "3;하이랜더 기관사;05;엣…… 역시 또 5호차 민원인데……\n#3;em;[속상함]"
70003010-63 = "3;하이랜더 기관사;06;너무 덥다고 에어컨을 강하게 틀어달라고……"
70003010-64 = "3;하이랜더 기관사;06\n5;하이랜더 엔지니어;02;그거, 아까랑 같은 사람?\n#5;al\n#3;m1\n#5;em;[반응]"
70003010-65 = "3;하이랜더 기관사;07;아니요, 다른 분이에요."
70003010-66 = "5;하이랜더 엔지니어;09;끄응…… 이런 경우가 제일 난감하다니까. 어느 장단에 맞춰야 하는 거야?\n#5;em;[땀]"
70003010-67 = "3;하이랜더 기관사;08;어쩔 수 없죠. 불편해서 민원을 넣는 거니까……"
70003010-68 = "#st;[0,0];instant;1;"
70003010-70 = "5;하이랜더 엔지니어;01\n3;하이랜더 기관사;08\n#3;h\n#5;h\n#wait;1500"
70003010-71 = "5;하이랜더 엔지니어;04\n3;하이랜더 기관사;08\n#3;h\n#5;h\n#3;em;…\n#wait;2500"
70003010-72 = "5;하이랜더 엔지니어;04\n3;하이랜더 기관사;04;앗, 아아……! 객실, 객실 나와주세요.\n#3;em;[반응]"
70003010-73 = "5;하이랜더 승무원;00;왜? 무슨 일이야?\n#5;sig\n#5;a"
70003010-74 = "3;하이랜더 기관사;04;다, 다시 5호차에서 신고가 들어왔는데…… 객실에서 덥다며 옷을 벗는 승객이 있다고 하네요……\n#3;em;[땀]"
70003010-75 = "5;하이랜더 승무원;04;아이고…… 출동할게.\n#5;sig"
70003010-76 = "5;하이랜더 승무원;00;에어컨 온도는 합의가 필요할 것 같으니, 추운 승객분께는 담요를 가져다드리면 되겠지?\n#5;sig"
70003010-77 = "3;하이랜더 기관사;08;객실 내에서 옷을 벗는 승객보다는 그게 낫겠죠……?"
70003010-78 = "3;하이랜더 기관사;99;잘 부탁드려요……\n#3;greeting"
70003010-80 = "#place;7호 차량"
70003010-81 = "1;불량배 모브 B;00\n2;불량배 모브 A;00\n#1;a\n#2;a\n#1;h\n#2;h\n#wait;1500"
70003010-82 = "1;불량배 모브 B;03\n2;불량배 모브 A;03\n#1;em;[재잘]\n#2;em;[음표]\n#1;h\n#2;h\n#wait;3000"
70003010-83 = "1;불량배 모브 B;03\n2;불량배 모브 A;03\n5;승객 A;00\n#5;al\n#1;h\n#2;h\n#wait;1000"
70003010-84 = "5;진상 승객 A;00;에잉~ 요즘 젊은것들이란.\n#5;em;[속상함]"
70003010-85 = "#st;[0,0];instant;1;"
70003010-87 = "1;불량배 모브 B;00\n2;불량배 모브 A;00\n5;진상 승객 A;00\n#2;em;[?]\n#1;h\n#5;h\n#2;h\n#5;h\n#wait;1500"
70003010-88 = "5;진상 승객 A;00;어른이 보이면 자리도 재깍재깍 양보하고 그래야지.\n#5;em;[스팀]"
70003010-89 = "1;불량배 모브 B;05;뭐야?\n#1;em;[?]"
70003010-90 = "2;불량배 모브 A;05;저기요, 여기 지정좌석제인데요."
70003010-91 = "5;진상 승객 A;00;아, 모르겠고! 빨리 일어나서 자리 비켜! 나 다리 아프다고!\n#5;hophop\n#fontsize;80"
70003010-92 = "2;불량배 모브 A;04;저거 뭘 들고 있는 거야? 막대기?\n#2;em;[땀]"
70003010-93 = "1;불량배 모브 B;04;어어, 할배! 그 샤쿠하치 안 내려놔?\n#1;stiff"
70003010-95 = "3;진상 승객 A;00;이 버르장머리 없는 놈들 같으니!! 내가 네놈들만 할 때는~!!\n#3;closeup\n#3;em;[!]\n#fontsize;80"
70003010-96 = "3;불량배 모브 A;02;뭐 이런 진상이 다 있어?!\n#3;em;[빠직]\n#3;closeup"
70003010-97 = "#st;[0,0];instant;1;"
70003010-99 = "1;불량배 모브 B;02\n2;불량배 모브 A;02\n5;진상 승객 A;00\n#1;h\n#2;h\n#5;h\n#3;hide\n#5;hophop\n#wait;1000"
70003010-100 = "5;진상 승객 A;00\n1;불량배 모브 B;02\n2;불량배 모브 A;02\n#1;hophop\n#1;em;[빠직]\n#2;em;[빠직]\n#1;h\n#2;h\n#wait;1500"
70003010-105 = "5;진상 승객 A;00\n1;불량배 모브 B;00\n2;불량배 모브 A;00\n3;하이랜더 승무원;01\n#5;h\n#1;h\n#3;h\n#2;h\n#3;a\n#2;m1\n#1;dl\n#wait;1500"
70003010-106 = "5;진상 승객 A;00\n2;불량배 모브 A;00\n3;하이랜더 승무원;04;하아…… 그, 어르신? 그거 내려놓으시구요. 다들 진정하세요.\n#3;em;[세로선]"
70003010-107 = "5;진상 승객 A;00;아앙? 넌 또 뭐야?\n#fontsize;80\n#5;stiff"
70003010-108 = "5;진상 승객 A;00\n2;불량배 모브 A;05;어이! 저 할배가 먼저 시작했다고!\n#2;em;[스팀]\n#2;hophop"
70003010-109 = "2;불량배 모브 A;05\n5;진상 승객 A;00\n3;하이랜더 승무원;06;여기서 이러시면 곤란하구요. 일단 객실 바깥 통로로 이동해주시면……\n#3;em;[땀]\n#3;stiff"
70003010-110 = "5;진상 승객 A;00;웃기고 있네! 고객이 왕인데, 어디 이래라 저래라야?\n#5;em;[!]\n#fontsize;80"
70003010-111 = "3;하이랜더 승무원;05;아니, 다른 분들께 피해가 가고 있으니까…… 일단 이동하셔서……"
70003010-112 = "1;불량배 모브 B;02;여긴 우리가 돈 주고 산 좌석이라고!\n#1;em;[스팀]\n#1;hophop\n#1;ar\n#2;m2"
70003010-113 = "2;불량배 모브 A;02;저 영감이 문제니까 우리는 여기서 한 발짝도 움직이지 않을 거야!!\n#2;hophop\n#2;em;[!]"
70003010-114 = "3;하이랜더 승무원;04;아니, 저기……"
70003010-115 = "5;진상 승객 A;00;뭐, 영감?? 이런 개념 없는 어린 것들 봐라! 어른한테 못하는 말이 없어!\n#5;em;[빠직]\n#5;hophop\n#fontsize;80"
70003010-116 = "#st;[0,0];instant;1;"
70003010-118 = "3;하이랜더 승무원;04\n5;진상 승객 A;00\n1;불량배 모브 B;02\n2;불량배 모브 B;02\n#1;dl\n#2;dl\n#5;dl\n#1;h\n#2;h\n#5;h\n#3;h\n#wait;1500"
70003010-119 = "3;하이랜더 승무원;01;……"
70003010-120 = "3;하이랜더 승무원;06;왜 항상 이런 일이 벌어지는 걸까……?\n#3;em;[땀]\n#1;hide\n#2;hide\n#5;hide"
70003010-121 = "#st;[0,0];instant;1;"
70003010-123 = "3;하이랜더 승무원;06\n1;열차 탑승객 B;02;저기요. 하이랜더 승무원 맞으시죠?\n#1;a\n#1;em;[반응]\n#3;m4"
70003010-124 = "3;하이랜더 승무원;00;아, 네.\n#3;em;[반응]"
70003010-125 = "1;열차 탑승객 B;08;저 사람들 좀 빨리 어떻게 해주세요. 시끄럽잖아요."
70003010-126 = "3;하이랜더 승무원;04;그, 최선을 다하고 있긴 한데……\n#3;em;[땀]"
70003010-127 = "1;열차 탑승객 B;07;아니, 다 끌어내든 해서 여기서 치워달라고요. 이게 뭐예요, 지금.\n#1;em;[빠직]"
70003010-128 = "3;하이랜더 승무원;06;아, 알겠습니다……\n#3;stiff"
70003010-130 = "3;하이랜더 승무원;06;불편을 끼쳐드려 죄송합니다……\n#3;em;[세로선]\n#3;closeup"
70003010-131 = "3;하이랜더 기관사;01\n#3;a\n#1;hide"
70003010-133 = "3;하이랜더 기관사;02\n#3;em;[반응]\n#wait;1500"
70003010-134 = "3;하이랜더 기관사;06;7호 차량에서 소란이요? 으음, 알겠습니다.\n#3;stiff"
70003010-135 = "3;하이랜더 기관사;07;일단 현장에서 최대한 조치해 보시고, 어려울 경우 지원 갈게요."
70003010-136 = "3;하이랜더 기관사;08;네, 네. 조금만 고생 부탁드립니다."
70003010-137 = "#st;[0,0];instant;1;"
70003010-139 = "3;하이랜더 기관사;08\n#3;greeting\n#wait;1500"
70003010-140 = "3;하이랜더 기관사;05;하아……\n#3;em;[한숨]"
70003010-141 = "3;하이랜더 기관사;01;왠지 좀 조용하다 했더니, 역시나네요."
70003010-142 = "#st;[0,0];instant;1;"
70003010-144 = "3;하이랜더 기관사;02\n#wait;1500"
70003010-145 = "3;하이랜더 기관사;04;엑? 이번엔 8호, 3호 차량에서도……?\n#3;shake\n#3;em;[?!]"
70003010-147 = "#place;8호 차량"
70003010-148 = "#st;[0,0];instant;1;"
70003010-150 = "3;진상 승객 C;00\n4;진상 승객 B;00\n#3;ar\n#4;al\n#3;h\n#4;h\n#wait;600"
70003010-151 = "3;진상 승객 C;00\n4;진상 승객 B;00\n#3;stiff\n#3;h\n#4;h\n#wait;600"
70003010-152 = "3;진상 승객 C;00\n4;진상 승객 B;00\n#4;m5\n#3;h\n#4;h\n#wait;200"
70003010-153 = "3;진상 승객 C;00\n4;진상 승객 B;00\n#3;m2\n#3;h\n#4;h\n#wait;1000"
70003010-154 = "3;진상 승객 C;00;어이! 나가는 사람 먼저야! 조심 좀 해!\n#3;em;[빠직]"
70003010-155 = "4;진상 승객 B;00;뭐야? 그쪽이 잘 피해 갔어야 하는 거 아뇨!"
70003010-156 = "4;진상 승객 B;00;아니면 당신이 먼저 양보를 하든가!\n#4;hophop"
70003010-157 = "3;진상 승객 C;00;뭐라고? 지금 그걸 말이라고 해?!\n#3;em;[스팀]\n#3;hophop\n#fontsize;80"
70003010-159 = "#place;3호 차량"
70003010-160 = "3;불법영업 학생;01\n#3;greeting\n#3;a\n#wait;1500"
70003010-161 = "3;불법영업 학생;08;자, 자! 차내에 계신 승객 여러분~! 잠시 양해의 말씀 드립니다~!\n#3;em;[반응]"
70003010-162 = "#st;[0,0];instant;1;"
70003010-164 = "3;열차 탑승객 C;00\n#3;em;[?]\n#wait;1500"
70003010-165 = "3;불법영업 학생;03;제가 누구냐? 중요하지 않습니다!"
70003010-166 = "3;불법영업 학생;11;중요한 것은 단 하나!\n#3;m4"
70003010-167 = "3;불법영업 학생;08;여러분께서 정말 좋은 물건 하나 챙겨갈 수 있는 기회를 얻으셨다는 사실이죠!\n#3;em;[재잘]"
70003010-168 = "3;불법영업 학생;03;과연 그게 무엇이냐~! 다들 궁금하실 겁니다!\n#3;m2"
70003010-169 = "3;불법영업 학생;03\n#na;열차 탑승객 C;뭐야, 잡상인이잖아. 빨리 신고해."
70003010-170 = "3;불법영업 학생;08;원적외선과 음이온을 방출해 혈액 순환에 좋고! 총열의 탄매도 감소시켜 주며 그저 몸에 지니기만 해도 탄 걸림 현상까지 싸악 없애주는!\n#3;hophop\n#3;m4"
70003010-171 = "3;불법영업 학생;10;바로 게르게르 게르마늄 팔찌~!! 키보토스를 강타한 히트 상품이죠!\n#3;em;[!]\n#3;m3"
70003010-172 = "3;불법영업 학생;08;없어서 못 판다는 바로 그 팔찌를 제가! 여러분을 위해 이렇게 찾아왔습니다. 날이면 날마다 오는 기회가 아닙니다~!!\n#3;hophop\n#3;m2"
70003010-173 = "3;불법영업 학생;03;원래 정가는 5천 엔이지만, 이 열차에 타신 행운의 승객님들께는 단돈 천 엔만 받습니다! 그야말로 특별가 그 자체~!!\n#3;greeting\n#3;m3"
70003010-174 = "3;불법영업 학생;03\n#na;열차 탑승객 A;어, 뭐야…… 그렇게 싸게 판매한다니, 한번 사볼 만할지도……?"
70003010-175 = "3;불법영업 학생;03\n2;열차 탑승객 D;02;그, 그러게…… 탄 걸림 현상도 없애준다니. 대박인데……\n#2;ar\n#2;em;…"
70003010-176 = "#st;[0,0];instant;1;"
70003010-178 = "3;불법영업 학생;01\n2;열차 탑승객 D;01\n#2;greeting\n#wait;1000\n#3;h\n#2;h"
70003010-179 = "2;열차 탑승객 D;01\n3;불법영업 학생;02;아, 손님! 만지셨으니 사셔야 합니다~!\n#3;em;[반응]"
70003010-180 = "2;열차 탑승객 D;04;뭐, 뭐야? 호기심에 잠깐 만져봤을 뿐이라고……\n#2;m1\n#2;em;[?!]"
70003010-181 = "2;열차 탑승객 D;04\n3;불법영업 학생;08;이건 저희 밀레니엄 유사과학부 특제 상품이라 만진 사람에게 즉시 각인되어 버리거든요!\n#3;hophop"
70003010-182 = "2;열차 탑승객 D;06;그, 그런……\n#2;stiff\n#2;em;[훌쩍]"
70003010-183 = "3;불법영업 학생;06;하아, 어쩔 수 없죠.\n#3;em;[한숨]"
70003010-185 = "3;불법영업 학생;08;제가 특별히~! 원래는 이러면 안 되지만, 손님께는 더 저렴하게 판매하도록 하겠습니다.\n#3;closeup\n#1;hide"
70003010-186 = "3;불법영업 학생;10;5개 세트에 3천 엔! 크아~ 거저다, 거저~!!\n#3;em;[재잘]\n#3;hophop\n#3;closeup"
70003010-188 = "4;열차 탑승객 C;02\n2;열차 탑승객 D;04;엣…… 그럼 2개를 공짜로 얻는 셈 아냐?\n#2;em;[반응]"
70003010-189 = "2;열차 탑승객 D;04\n4;열차 탑승객 C;04;이, 이러면 안 사는 게 바보 같은데?"
70003010-190 = "2;열차 탑승객 D;04\n4;열차 탑승객 C;04\n3;불법영업 학생;10;에잇, 기분이다!!\n#3;a\n#2;m1\n#4;m5\n#3;em;[!]"
70003010-192 = "3;불법영업 학생;08;특별히 이 객차에서는!! 손님 여러분 모두를 이 가격에 모시겠습니다~!!\n#3;closeup"
70003010-193 = "3;불법영업 학생;09;거기다 선착순 세 분께~!! 백귀야행에서 어렵게 공수해 온 액막이 부적도  드립니다!\n#3;hophop"
70003010-194 = "4;열차 탑승객 D;02\n5;열차 탑승객 C;02;저, 저 살래요!\n#4;al\n#5;al"
70003010-195 = "2;열차 탑승객 B;02\n1;열차 탑승객 A;02;나도, 나도!!\n#1;ar\n#2;ar"
70003010-197 = "#place;6호 차량"
70003010-198 = "5;하이랜더 승무원;07;거기!! 짐칸 위에 올라가지 마세요! 내려오세요!\n#5;al\n#5;em;[!]"
70003010-199 = "5;하이랜더 승무원;07\n#na;진상 승객 D;아앙? 난 여기서 편하게 누워가겠어!"
70003010-200 = "5;하이랜더 승무원;04;올라가시면 위험합니다! 내려오시라구요!\n#5;em;[속상함]\n#5;m4"
70003010-201 = "#st;[0,0];instant;1;"
70003010-204 = "1;진상 승객 D;00;어이, 어이! 앉을 곳이 없다고! 이건 객차에 자리를 충분히 만들지 않은 네놈들 잘못 아니냐?\n#1;a\n#1;em;[!]"
70003010-205 = "5;하이랜더 승무원;00;예?\n#5;stiff"
70003010-206 = "5;하이랜더 승무원;05;손님, 혹시 승차권 좀 보여주시겠어요?\n#5;em;[반응]"
70003010-207 = "1;진상 승객 D;00;그게 뭐야? 기차를 타는 데 승차권이 왜 필요해?\n#1;em;[?]"
70003010-208 = "#st;[0,0];instant;1;"
70003010-210 = "1;진상 승객 D;00\n5;하이랜더 승무원;01\n#5;em;[...]\n#1;h\n#5;h\n#wait;2500"
70003010-212 = "3;하이랜더 승무원;07;손님, 다음 정거장에서 내려주셔야겠습니다!!\n#3;em;[!]\n#3;closeup"
70003010-213 = "3;진상 승객 D;00;뭐어-? 네가 뭔데?? 책임자 불러와!!\n#3;closeup\n#fontsize;80\n#3;em;[!]"
70003010-215 = "#place;4호 차량"
70003010-216 = "3;하이랜더 엔지니어;08;헉, 헉…… 여긴가?\n#3;al\n#3;em;[땀]"
70003010-217 = "3;하이랜더 엔지니어;04;저, 손님들! 통로를 가로막고 마작을 하다니, 이러면 다른 승객들이 불편하잖아!"
70003010-218 = "1;헬멧단 간부;00;아, 직원인가? 잘 왔다! 어이, 같이 하자고! 안 그래도 한 명이 내려버려서 말이야!\n#1;em;[반응]\n#1;a"
70003010-219 = "3;하이랜더 엔지니어;09;응? 아니, 무슨 말……\n#3;em;[?]"
70003010-220 = "5;용역알바 A;00;사람이 모자라다고! 빨리 여기 앉아!\n#5;a\n#5;em;[!]"
70003010-221 = "3;하이랜더 엔지니어;06;나, 나는 규칙도 몰라……! 아니, 그전에 여기서 마작을 하면 안 된다니까?\n#3;em;[땀]\n#3;stiff"
70003010-222 = "5;용역알바 A;00;으헤헤, 우리가 알려줄 테니까 일단 앉아봐!!\n#5;em;[재잘]"
70003010-224 = "3;하이랜더 기관사;01\n#3;a\n#wait;1500"
70003010-225 = "3;하이랜더 기관사;05;네, 네에! 하이랜더 기관사입니다……!\n#3;greeting"
70003010-226 = "3;하이랜더 기관사;09;지원이요?! 어디로……\n#3;em;[?!]\n#3;shake"
70003010-227 = "#st;[0,0];instant;1;"
70003010-229 = "3;하이랜더 기관사;01\n#3;em;[...]\n#wait;2500"
70003010-230 = "3;하이랜더 기관사;06;네?! 전 객실이요……??\n#3;closeup\n#fontsize;100\n#bgshake"
