[translation]
80000094-1 = "เด็กสาวในวัยแรกแย้ม"
80000094-2 = "อ๊ะ คุณครู~!"
80000094-3 = "ทางนี้ค่ะ ทางนี้! ฉันอยู่ทางนี้ค่ะ~!"
80000094-4 = "อะฮ่าฮ่าฮ่า! คิดไว้แล้วเชียว~ ว่าคุณครูน่าจะมาถึงประมาณช่วงนี้ ฉันเลยมาเตรียมสถานที่เอาไว้ก่อนไง#nล่ะคะ"
80000094-5 = "คะ...? มีเรื่องอะไรอย่างนั้นเหรอคะ?"
80000094-6 = "โธ่... พูดอะไรน่าเศร้าแบบนั้นล่ะคะ วันดีๆ แบบนี้จะมีอะไรได้อีก"
80000094-7 = "ก็แค่พูดไปเรื่อยใช่มั้ยล่ะคะ แหงอยู่แล้ว... ก็วันนี้เป็นวันวาเลนไทน์นี่คะ!"
80000094-8 = "คุณครูมาที่นี่ทั้งๆ ที่รู้อยู่แล้วไม่ใช่เหรอคะ? ไม่ต้องแกล้งทำเป็นไม่รู้ก็ได้ค่ะ"
80000094-9 = "ถ้างั้นก็ขอเข้าเรื่องเลยแล้วกัน..."
80000094-10 = ""
80000094-12 = ""
80000094-13 = ""
80000094-15 = "...แต่นแต๊น~!!"
80000094-16 = "[s1] \"ขอบคุณนะ อิจิกะ\"\n[s2] \"น่ารักจนใจเจ็บ ครูจะกินให้อร่อยเลยนะ\""
80000094-19 = "......"
80000094-20 = "...? เอ๋...?"
80000094-21 = "ทำไม... เอ่อ... รับไปง่ายๆ แบบนั้นเลยล่ะคะ?"
80000094-22 = "คิดว่าจะแสดงปฏิกิริยาที่ต่างไปจากนี้นิดหน่อยซะอีก..."
80000094-23 = "คะ...?"
80000094-24 = "ถ้าทำแบบนั้นฉันจะดีใจกว่านี้รึเปล่าน่ะเหรอคะ? ก็ไม่เชิงหรอกค่ะ..."
80000094-25 = "ฮะฮ่า พอได้ยินคุณครูถามแบบนั้นแล้วก็รู้สึกเขินนิดๆ เลยค่ะ..."
80000094-26 = "แต่ก็ใช่ค่ะ เป็นอย่างที่คุณครูพูดนั่นแหละค่ะ พูดกันตรงๆ เข้าประเด็นไม่ยืดเยื้อแบบนี้ก็เหมาะกับฉัน#nมากกว่าจริงๆ~"
80000094-27 = "อันที่จริง ตอนแรกฉันคิดว่าอย่างน้อยก็อาจจะโดนถามว่า 'ไปหามาจากไหน' หรือ 'ไปหามาได้ยังไง' ซะอีก..."
80000094-28 = "คะ...?"
80000094-29 = "ไม่ใช่ว่าฉันทำเองงั้นเหรอคะ...?"
80000094-30 = "เอ่อ... ที่พูดมา... มันก็ใช่อยู่หรอก"
80000094-31 = ""
80000094-33 = ""
80000094-34 = "ฮู่ว~"
80000094-35 = "คุณครู..."
80000094-36 = "คำถามเมื่อกี้มันเกินไปหน่อยนะคะ ฮะฮะ..."
80000094-37 = "ยังไงก็เถอะ ถ้ามาถามเรื่องแบบนั้นตรงๆ ละก็... มันไม่เกินไปหน่อยรึยังไงคะ?"
80000094-38 = "ถ้าถามในสิ่งที่รู้คำตอบอยู่แล้วแบบนั้น ฉันที่พยายามเตรียมตัวมาอย่างหนักแบบนี้ก็ชวนคุยต่อ#nไม่ได้นะคะ"
80000094-39 = "เห็นแบบนี้ฉันเองก็เป็นเด็กผู้หญิงเหมือนกันนะคะ ช่วยละเอียดอ่อนกว่านี้สักหน่อยเถอะค่ะ..."
80000094-40 = "ฮึ่ม..."
80000094-41 = "งืมๆ ค่ะ ไม่ว่าจะคิดยังไงก็ได้คำตอบเหมือนเดิมค่ะ วันนี้น่ะ ต่อให้คุณครูบอกว่าขอโทษ มันก็ไม่มี#nประโยชน์หรอกค่ะ..."
80000094-42 = "คะ...?"
80000094-43 = "ถ้างั้นจะต้องทำยังไงให้หายโกรธเหรอคะ? เฮ้อ..."
80000094-44 = "เรื่องนั้นก็ถามโต้งๆ แบบนี้อีกงั้นเหรอคะ? ถ้ายังไม่เลิกทำแบบนี้เดี๋ยวก็เกิดเรื่องใหญ่หรอกค่ะ"
80000094-45 = "เรื่องใหญ่อะไรงั้นเหรอคะ...? ไม่เป็นไรหรอก... งั้นเหรอคะ?"
80000094-46 = ""
80000094-48 = ""
80000094-49 = "ถึงจะเกิดเรื่องใหญ่ขึ้นตอนนี้ก็ไม่เป็นไรงั้นเหรอคะ...?"
80000094-50 = "แน่ใจนะคะ? รับผิดชอบไหวแน่นะคะ?"
80000094-51 = "โฮ่..."
80000094-52 = "เฮ้อ..."
80000094-53 = "ก็ดีค่ะ ในเมื่อคุณครูพูดแบบนั้น..."
80000094-54 = "ถ้างั้นเรื่องที่เกิดขึ้นหลังจากนี้ ถือเป็นความรับผิดชอบของคุณครูนะคะ... จะเรียกว่ากรรมตามสนอง#nดีไหมนะ..."
80000094-55 = "อืม... ทำยังไงก็ได้แบบนั้นละมั้งคะ?"
80000094-56 = "เอาละนะ..."
80000094-57 = ""
80000094-59 = ""
80000094-60 = "คุณครู...?"
80000094-61 = ""
80000094-63 = ""
80000094-65 = "'อ้าม~' สิคะ"
80000094-66 = ""
