[translation]
80000115-1 = "A Sweetness That Never Gets Old"
80000115-3 = "Sen!"
80000115-4 = "Se!"
80000115-5 = "I!"
80000115-6 = ""
80000115-8 = ""
80000115-9 = "Can you visit Trinity in few days?"
80000115-10 = "There's something that I want to give you."
80000115-11 = "No asking what it is. It's a secret, okay?"
80000115-12 = "Okay. I'll see you then."
80000115-13 = "[ns] \"In few days... I see. I'll look forward to it.\""
80000115-14 = ""
80000115-15 = ""
80000115-16 = "H-Huh? L-Look forward to it?"
80000115-17 = "I-I don't know what you're talking about. A-Ahaha... B-Besides, you don't even know what I'm going to give you..."
80000115-18 = "Y-You shouldn't think about it too much... Otherwise, it won't be a surprise! It has to be something that feels like \"Ta Da!\""
80000115-20 = "[ns] \"Don't fret. I'll be on time. See you then, Mika.\""
80000115-21 = ""
80000115-22 = ""
80000115-23 = "Th-This is bad! Sensei, you're not supposed to be looking forward to it! My plan's ruined!"
80000115-24 = "Wh-What do I do?!"
80000115-25 = ""
80000115-27 = ""
80000115-29 = "A few days later, at Trinity after classes..."
80000115-30 = ""
80000115-33 = "I went to our meeting place, but I couldn't find Mika."
80000115-34 = ""
80000115-37 = "[ns] Try calling her."
80000115-38 = ""
80000115-42 = "...I'm busy. Who is— H-Huh?! S-Sensei?!"
80000115-43 = "Wait, what time is— Noo!! Already?!"
80000115-44 = "Sorry, Sensei! Please wait just a moment! All right, um... The timer is...160? Wait, no, that's the pre-heat temperature... Seven minutes? Okay, I'll be there in just seven minutes, Sensei!"
80000115-45 = "I need to ch-change first... Wh-What? W-Wait! Is something burning? Oh n-no!!"
80000115-46 = ""
80000115-53 = "[ns] \"...Hmm.\""
80000115-54 = ""
80000115-57 = "[ns] \"I know where she is.\" Head to the place Mika's holed up in."
80000115-58 = ""
80000115-62 = "Culinary Lab 7"
80000115-63 = ""
80000115-64 = "*cough* *cough* Guess you're not supposed to use the oven to melt chocolates... Ugh..."
80000115-65 = "...Huh?"
80000115-66 = "[s] \"Hi Mika.\""
80000115-67 = "S-Sensei?!"
80000115-68 = "[s] \"I came here because I was worried.\""
80000115-69 = "W-Worried? How did you even know I was here? W-Wait! H-Hold on!!"
80000115-70 = "Hold it! Don't come any closer!"
80000115-71 = "[s] \"...Huh??\""
80000115-72 = "I...just got out of the gym class...and I'm dusty from organizing the gym storage... And I haven't changed!"
80000115-73 = "And yes... I know there's whipping cream and chocolate all over my face..."
80000115-74 = "[s] \"Don't worry about all that, Mika.\""
80000115-75 = "Yeah. I figured you'd say something like that..."
80000115-76 = "But I am worried about it, Sensei! You shouldn't trouble a young girl's heart!"
80000115-77 = "[s] \"G-Got it...\""
80000115-78 = "Please wait for me in the next classroom. I'll be there real soon."
80000115-80 = "I decided to wait in one of the empty classrooms next door as Mika asked."
80000115-81 = ""
80000115-86 = ""
80000115-87 = ""
80000115-89 = ""
80000115-90 = ""
80000115-91 = ""
80000115-92 = "Did I keep you waiting, Sensei?"
80000115-93 = "I'm sorry for running late. The student in charge of organizing the gym storage wasn't feeling well, so I helped with organizing some more..."
80000115-94 = "I was going to let you know I'd be late... But then I got surprised seeing you here."
80000115-95 = "Anyway... While it's a bit late, my preparations are all complete."
80000115-96 = "[s] \"That thing you're hiding behind your back?\""
80000115-97 = "...Yeah. Right. For today..."
80000115-98 = "I made this for you, Sensei."
80000115-99 = "Ta-da!"
80000115-100 = ""
80000115-102 = ""
80000115-104 = ""
80000115-105 = "It was supposed to be a surprise... But ahaha...things didn't go as planned."
80000115-106 = "I had to borrow an oven from a culinary lab... I couldn't grab any premium ingredients either."
80000115-107 = "But I still wanted to make it myself."
80000115-108 = "It might look like a mess because it's my first time trying to bake... I think the chocolate coating got burnt a little... But... Still... I mean..."
80000115-109 = ""
80000115-111 = ""
80000115-113 = ""
80000115-114 = ""
80000115-115 = "Enjoy this...CHOCOLATE roll cake."
80000115-116 = "[s1] \"Thank you. I'm honored to get to try your homemade roll cake.\"\n[s2] \"It really is a surprise! Thank you, Mika. It looks great.\""
80000115-117 = ""
80000115-118 = ""
80000115-120 = ""
80000115-121 = ""
80000115-122 = ""
80000115-123 = "S-Sure... "
80000115-124 = "[s] \"But aren't you tired of roll cakes? Why did you go with that?\""
80000115-125 = "Hm? Ahahaha, you have a point."
80000115-126 = "But I've eaten roll cakes the most, so I know a lot about them, from the texture to key flavors..."
80000115-127 = "I can't be too adventurous my first time baking, right? So, I went with what I know."
80000115-128 = "[s] \"Hm. Is that so...?\""
80000115-129 = ""
80000115-131 = ""
80000115-132 = ""
80000115-133 = "Um. By the way, Sensei, how DID you know where I was?"
80000115-134 = "I think I said something like pre-heat, but there are dozens of labs with ovens here at Trinity..."
80000115-135 = "And I didn't tell anyone that I was going there... So how...?"
80000115-136 = "[s] \"Well, I've memorized your daily schedule.\""
80000115-137 = "H-Huh?"
80000115-138 = "[s3] \"I know which culinary lab you usually go to for your classes.\" \n[s4] \"It was also the closest lab to the field where your gym class took place.\""
80000115-141 = "I-I see... Well, I suppose it's a given... You are a teacher after all..."
80000115-142 = "But to know my full schedule..."
80000115-143 = ""
80000115-145 = ""
80000115-146 = "Heehee. Am I getting special treatment as Ms. Persona Non Grata?"
80000115-147 = "Well. Even so, that makes me smile a little."
80000115-148 = "[s5] \"No, I've seen you working hard.\"\n[s6] \"I know you've had a tough row to hoe, Mika. So keep your chin up.\""
80000115-149 = ""
80000115-150 = ""
80000115-152 = ""
80000115-153 = ""
80000115-154 = "...Okay!"
