[translation]
80000019-1 = "ไอเทมกิจกรรม"
80000019-2 = "ห้องชมรมพัฒนาเกม"
80000019-3 = "(คุณครูแวะมาที่ห้องชมรมพัฒนาเกมหลังจากไม่ได้มานาน และมานั่งเล่นเกม RPG ออนไลน์กับยูสึ)"
80000019-4 = ""
80000019-10 = "อ๊ะ คุณครู บอสของศัตรูไปทางนั้นแล้วค่ะ"
80000019-11 = "ตอนนี้ HP ของศัตรูใกล้จะหมดแล้ว ถ้าป้องกันการโจมตีครั้งนี้ได้ก็จะเคลียร์เรดครั้งนี้ได้แล้วค่ะ"
80000019-12 = "ช่วยอดทนจนกว่า... ฉันจะเตรียมสกิลโจมตีเสร็จด้วยนะคะ!"
80000019-13 = ""
80000019-20 = "สำเร็จแล้วค่ะ คุณครู!"
80000019-21 = "เคลียร์ด่านนี้ได้เพราะคุณครูมาช่วยไว้เลยนะคะ"
80000019-22 = "ถ้าฉันเล่นคนเดียวคงจะไม่มีทางทำได้แน่ๆ ขอบคุณที่มาช่วยฉันนะคะ!"
80000019-23 = "[s] \"แต่ดูเหมือนยูสึจะจัดการคนเดียวหมดเลยนะ...\""
80000019-24 = "มะ...ไม่ใช่หรอกค่ะ ที่ฉันบุกเข้าไปจัดการบอสได้ง่ายๆ ก็เป็นเพราะคุณครูคอยช่วยใช้สกิลบัฟ#nให้ฉันตลอดนะคะ"
80000019-25 = "นอกจากนี้ ระบบของตัวเกมก็ทำมาให้ลงเรดบอสคนเดียวไม่ได้ด้วยค่ะ..."
80000019-26 = "ตอนนี้เรามาแบ่งไอเทมที่ดรอปจากบอสกันก่อนดีมั้ยคะ?"
80000019-28 = "ดาบอันนี้ฉันมีแล้ว ส่วนเกราะอันนี้ก็ระดับต่ำกว่าอันที่ฉันมีอยู่..."
80000019-29 = "ไอเทมที่ดรอปจากเรดบอสวันนี้ ฉันให้คุณครูทั้งหมดเลยค่ะ"
80000019-30 = "[s] \"ให้ครูทั้งหมดเลยเหรอ?\""
80000019-31 = "ใช่ค่ะ คุณครูเลือกไอเทมที่ต้องการไปได้เลยค่ะ"
80000019-32 = ""
80000019-34 = ""
80000019-35 = "แล้วก็..."
80000019-36 = "คุณครูช่วยรับไอเทมนี้ไปด้วยได้ไหมคะ?"
80000019-38 = "[s] \"นี่คือ...?\""
80000019-39 = "ไอเทมช็อกโกแลตพิเศษที่จะรับได้เฉพาะในกิจกรรมวาเลนไทน์เท่านั้นค่ะ"
80000019-40 = "ถึงมันจะเป็นแค่ไอเทมช่วยฟื้น HP ธรรมดาๆ... แต่ฉันก็อยากให้คุณครูเป็นของขวัญค่ะ..."
80000019-41 = "ถ้าฉันให้ช็อกโกแลตจริงๆ เป็นของขวัญคุณครูได้ก็น่าจะดีกว่านี้... แต่ฉันไม่มีความกล้า#nพอที่จะออกไปซื้อช็อกโกแลตในที่ที่คนเยอะๆ ค่ะ..."
80000019-42 = "ถึงจะเป็นแค่ไอเทมช็อกโกแลตในเกมที่กินจริงๆ ไม่ได้..."
80000019-43 = "แต่คุณครูก็ช่วยเก็บไว้ด้วยนะคะ"
80000019-45 = "(จากนั้นคุณครูก็เก็บไอเทมช็อกโกแลตที่ได้รับเป็นของขวัญจากยูสึไว้ในคลังเก็บของอย่างดี)"
