[translation]
80000091-1 = "Sweets for the Sweet"
80000091-2 = "Oh, by the way, Sensei."
80000091-3 = "I got a new hobby!"
80000091-4 = "[s1] \"It's good to have hobbies.\"\n[s2] \"What is it?\""
80000091-5 = "It's..."
80000091-6 = "It's..."
80000091-7 = "Making cocktails!"
80000091-8 = "[s] \"No! That's a bad hobby!\""
80000091-9 = "Huh? What are you worried about?"
80000091-10 = "Obviously I'm making non-alcoholic cocktails."
80000091-11 = "Even though I'm suspended right now, I'm still a student. I wouldn't drink alcohol. Heehee..."
80000091-12 = "[s] \"...\""
80000091-13 = "Hm? Are you doubting me?"
80000091-14 = "I'll make you a glass of my favorite cocktail. I just developed the recipe recently, actually!"
80000091-15 = "You can try it for yourself and see if there are any suspicious ingredients."
80000091-16 = "Okay! Let's make it."
80000091-18 = "Hands moving with confidence, Shigure began to make the cocktail."
80000091-19 = ""
80000091-25 = "Here. A glass of my most exquisite creation..."
80000091-26 = ""
80000091-28 = ""
80000091-30 = "Shigure's Bittersweet Special."
80000091-31 = "[s] \"It sounds kind of sinister...\""
80000091-32 = "Cocktails all have names like that. Don't worry about it."
80000091-33 = "Just taste it, and let me know what you think."
80000091-34 = ""
80000091-37 = "[ns] \"Well, it's definitely non-alcoholic.\""
80000091-39 = "[ns3] \"It's just sweet enough, and the aftertaste is light and smooth.\"\n[ns4] \"This is really delicious!\""
80000091-40 = "Right?"
80000091-41 = "Right?"
80000091-42 = "I was aiming for a balance of ingredients with chocolate as the base, but with a sweet, refreshing flavor that didn't end up being too heavy."
80000091-43 = "It took a lot of trial and error, but I think it turned out great in the end!"
80000091-44 = "I'm really glad you like it too, Sensei."
80000091-45 = "[s] \"The flavor's really well-balanced. What's your secret?\""
80000091-46 = "...Don't you think it's a bit rude to just ask me for the recipe I put so much effort into?"
80000091-47 = "I wasn't planning on telling anyone, but..."
80000091-48 = "Heehee. I'll tell you, Sensei, as long as you promise to keep it a secret."
80000091-49 = "Shigure's Bittersweet Special is actually not that different from any other chocolate cocktail, except..."
80000091-50 = "You have to add one unsweetened chocolate at the very end, to balance out the flavor."
80000091-51 = "Unsweetened chocolate is quite bitter by itself, but mixed into the cocktail, it prevents the sweetness of the other ingredients from being overwhelming."
80000091-52 = "Making a great cocktail is all about understanding the properties of your ingredients and using them at the right time."
80000091-53 = "[s] \"You're pretty well-versed in mixology, Shigure.\""
80000091-54 = "You think? I don't know. I think I'm pretty average, honestly."
80000091-55 = ""
80000091-57 = ""
80000091-58 = "But I think you might have the makings of a great bartender."
80000091-59 = "[s] \"Me? Why?\""
80000091-60 = "Well, because you're so good at assessing each student's strengths and weaknesses, and putting them in the right places for them to succeed."
80000091-61 = "Watching students realize their strengths and work with others to create something great, thanks to your advice..."
80000091-62 = "Well, I can't help but think of a well-made cocktail."
80000091-63 = "You make it possible for a hard-to-mix unsweetened chocolate like me to feel useful."
80000091-64 = ""
80000091-66 = ""
80000091-68 = "So, please take the cocktail as a gift, with my gratitude."
80000091-69 = "I'm looking forward to another year together, Sensei."
