[translation]
80000073-1 = "Concentrate on the Conversation"
80000073-4 = "[ns1] \"I'm here, Ui.\"\n[ns2] \"Order up! I've got two Americanos for Ui?\""
80000073-5 = "Oh, good timing, Sensei. I just finished setting up."
80000073-6 = "Oh, good timing, Sensei. I just finished setting up."
80000073-7 = ""
80000073-10 = "Come this way. I picked out a spot for us."
80000073-11 = "Also..."
80000073-12 = ""
80000073-14 = ""
80000073-15 = ""
80000073-17 = "[ns3] \"Chocolate chip cookies... They look a little... squished.\"\n[ns4] \"Do you like this kind of cookie texture, Ui?\""
80000073-18 = "Uh... I'm not really picky about food... I didn't put that much thought into it."
80000073-19 = "Uh... I'm not really picky about food... I didn't put that much thought into it."
80000073-20 = "Oh, the books? I put them a safe distance away. You never know..."
80000073-21 = "These cookies are soft and less crumbly, but a cookie is a cookie, after all. More importantly, I don't want any crumbs to get on the books."
80000073-22 = "I always move them for safety if I'm going to be eating or drinking something that could leave a stain."
80000073-23 = "Anyways, are we really doing this just because it's Valentine's Day...?"
80000073-24 = "Huh? Am I not really interested? Well, hm...maybe a little?"
80000073-25 = "But is anyone really that into eating chocolate? I think people just get excited about the atmosphere."
80000073-26 = "Like right now, for example... We're sitting together, without my books..."
80000073-27 = "It's probably something like that. Yes. You and I are all alone together, Sensei..."
80000073-28 = ""
80000073-30 = ""
80000073-31 = "...?!"
80000073-32 = "[s5] \"Ui?\"\n[s6] \"Why'd you get tense all of a sudden?\""
80000073-33 = "Uh... Um... Er..."
80000073-34 = "Uh... Um... Er..."
80000073-35 = "... My apologies. I'm...inexplicably nervous. Did I say something strange?"
80000073-36 = "Maybe it was \"without my books.\" I shouldn't have said that."
80000073-37 = "Up until now, when you've visited, I've had a book in my hands, so I never thought we were alone..."
80000073-38 = "But I couldn't bring one for something like this, could I?"
80000073-39 = "And you, Sensei..."
80000073-40 = "You seem unaffected, of course."
80000073-41 = "I think..."
80000073-42 = "[s7] \"You think…?\"\n[s8] \"Your face just froze...\""
80000073-43 = "Something doesn't feel right about this. I shouldn't be the only anxious one..."
80000073-44 = "Something doesn't feel right about this. I shouldn't be the only anxious one..."
80000073-45 = "..."
80000073-46 = "Hm..."
80000073-47 = ""
80000073-49 = ""
80000073-50 = ""
80000073-51 = "[ns9] \"You're sitting next to me out of nowhere?!\"\n[ns10] \"U-Ui! That's, um, a bit close...\""
80000073-52 = "Phew."
80000073-53 = "Phew."
80000073-54 = "Good. Your face tells me we're even now."
80000073-55 = "Don't mind me. I just thought it would be better if we were both nervous."
80000073-56 = ""
80000073-58 = ""
80000073-59 = "N-Now, let's both be uncomfortable..."
80000073-60 = "And eat our cookies and coffee... I-I'll go first..."
80000073-61 = "[s] \"...\""
80000073-63 = "[ns] Pick up the squishy chocolate cookie."
80000073-65 = "Ui and I quietly shared our coffee and non-crumble cookies."
80000073-66 = "But the awkwardness quickly vanished once Ui began to criticize some passersby that she saw."
