[translation]
80000105-1 = "ความแตกต่างในการรับรู้"
80000105-3 = "อ่า... เจอตัวแล้ว"
80000105-4 = ""
80000105-6 = ""
80000105-7 = "อยู่นี่นี่เอง คุณครู... ฉันกำลังตามหาอยู่พอดี"
80000105-8 = "หืม...?"
80000105-9 = "เปล่าหรอก ไม่ได้มีเรื่องใหญ่อะไร แล้วก็ไม่ใช่เรื่องสำคัญด้วย"
80000105-10 = "ถ้างั้นฉันขอไม่พูดอะไรให้ยืดยาว แล้วขอเข้าเรื่องเลยแล้วกัน"
80000105-11 = ""
80000105-13 = ""
80000105-14 = ""
80000105-15 = ""
80000105-16 = ""
80000105-17 = ""
80000105-19 = "[ns1] \"หรือว่านี่คือ... ช็อกโกแลต?\"\n[ns2] \"วันวาเลนไทน์...?\""
80000105-22 = "สีหน้าดูประหลาดใจอย่างที่คาดไว้เลย..."
80000105-23 = "ก็นะ ฉันก็พอคิดเอาไว้ล่วงหน้าบ้างแล้วว่าคุณครูจะคิดยังไง"
80000105-24 = "เพราะงั้นแล้ว ฉันเลยอยากใช้โอกาสนี้แก้ไขเรื่องนั้นสักหน่อย"
80000105-25 = "จนถึงตอนนี้ฉันก็ได้รับความช่วยเหลือหลายๆ อย่างและมีเรื่องที่ต้องขอบคุณคุณครูอยู่มากมาย"
80000105-26 = "แล้วก็ฉัน..."
80000105-27 = "ฉันเองก็... ไม่ได้ระวังตัวกับคุณครู หรือว่าไม่ได้ไม่ชอบคุณครูหรอก..."
80000105-28 = ""
80000105-30 = ""
80000105-31 = "ฉันนี่พูดอะไรไร้สาระจริงๆ... ลืมๆ เรื่องเมื่อกี้ไปเถอะ"
80000105-32 = "อย่างที่บอกไปว่านี่เป็นส่วนหนึ่งของการปรับความเข้าใจระหว่างเรา ฉันเลยพยายามมาก เพราะกังวล#nว่าคุณครูจะไม่ดีใจที่ได้รับของชิ้นนั้นไปน่ะ"
80000105-33 = "หวังว่าคุณครูจะชอบมันนะ"
80000105-34 = "[s3] \"แน่นอน ครูชอบมากเลยนะ\"\n[s4] \"ว้าว! ช็อกโกแลตของอาโออิ!!\""
80000105-37 = ""
80000105-39 = ""
80000105-40 = "ตอบกลับทันทีเลยงั้นเหรอ..."
80000105-41 = "อืม...? อยากซื้อกาแฟเลี้ยงฉันเป็นการตอบแทนงั้นเหรอ?"
80000105-42 = "ฉันไม่มีเหตุผลที่จะปฏิเสธอยู่แล้ว... แต่จะว่ายังไงดีล่ะ คุณครูดูผ่อนคลายมากกว่าเมื่อกี้อีกนะ"
80000105-43 = "เป็นผลของช็อกโกแลตงั้นเหรอ? แต่ว่าคุณครูก็ยังไม่ได้แกะห่อช็อกโกแลตเลยนะ"
80000105-44 = "ระยะห่างระหว่างพวกเรา..."
80000105-45 = "[s5] \"หืม? ระยะห่างอะไรเหรอ?\"\n[s6] \"ครูไม่เคยคิดแบบนั้นเลยนะ?\""
80000105-48 = "...?"
80000105-49 = "อืม..."
80000105-50 = "อืม......"
80000105-51 = "ฮุ..."
80000105-52 = "งั้นเหรอ... อืม... คุณครู..."
80000105-53 = "คนอย่างคุณนี่นะ..."
80000105-54 = "[s7] \"อาโออิ? เป็นอะไรรึเปล่า?\"\n[s8] \"กังวลอะไรอยู่งั้นเหรอ?\""
80000105-57 = "......"
80000105-58 = "คือ... เรื่องเล็กๆ น้อยๆ น่ะ รู้สึกเหมือนมีแค่ฉันที่เสียหายอยู่ฝ่ายเดียว "
80000105-59 = "หืม...? "
80000105-60 = "ถ้ากังวลเรื่องอะไรก็บอกได้เลยงั้นเหรอ? คุณครูยินดีรับฟังฉันตลอดงั้นเหรอ...?"
80000105-61 = ""
80000105-63 = ""
80000105-64 = ""
80000105-65 = "ฉันเข้าใจแล้วละ... "
80000105-66 = "คุณครูต่างหากที่ไม่ดี ไม่ใช่ฉันสักหน่อย"
80000105-67 = "[s] \"อะไรนะ...?\""
80000105-68 = ""
80000105-70 = ""
80000105-71 = ""
80000105-72 = "ปะ... เปล่า ฉันแค่พูดคนเดียวเฉยๆ ไม่ต้องใส่ใจหรอก ฉันมีงานอื่นที่ต้องทำอยู่ ขะ... ขอตัวก่อนนะ"
80000105-73 = ""
80000105-75 = ""
80000105-76 = ""
80000105-77 = ""
80000105-79 = "(อาโออิรีบกลับไปด้วยท่าทางที่รีบร้อนด้วยเหตุผลบางอย่าง)"
80000105-80 = ""
80000105-84 = "(และช็อกโกแลตที่อาโออิให้มาก็รสชาติอร่อยมากๆ...)"
