[translation]
80000014-1 = "#title;의도치 않은 선물"
80000014-2 = "#place;샬레 업무관"
80000014-5 = "3;아야네;08;안녕하세요, 선생님. 좋은 아침입니다.\n#3;a"
80000014-6 = "3;아야네;09;샬레에 오는 길에 기차가 연착되어서…… 조금 늦고 말았네요. 죄송합니다…….\n#3;greeting\n#3;em;[땀]"
80000014-7 = "[s] \"아니야. 5분밖에 늦지 않았는걸.\""
80000014-8 = "3;아야네;01;참, 오는 길에 역에서 이걸 샀는데요……."
80000014-9 = "#st;[0,0];instant;1;"
80000014-11 = "3;아야네;01\n#3;d\n#wait;1000"
80000014-13 = "3;아야네;03;선물용 초콜릿 세트입니다. 부디 맛있게 드셔 주세요.\n#3;em;[음표]\n#3;a"
80000014-14 = "[s] \"어째서 갑자기 초콜릿을……?\""
80000014-15 = "3;아야네;01;선생님께는 언제나 신세를 지고 있으니까요.\n#3;em;[반응]"
80000014-16 = "3;아야네;01;게다가 전에 말씀하시길, 요새는 잠을 아무리 자도 피로가 가시질 않는다고 하셨잖아요?"
80000014-17 = "3;아야네;03;초콜릿에 포함된 카페인과 테오브로민은 피로 회복에 효과가 있다고 하니, 틈이 날 때마다 하나씩 드셔 주세요."
80000014-18 = "3;아야네;08;사실은 어찌 된 일인지 역 앞에 초콜릿 세트가 엄청나게 진열되어 있기에 무심코 구입한 것이지만……\n#3;stiff"
80000014-19 = "3;아야네;09;……네? 바, 발렌타인 초콜릿이요?\n#3;em;[?]"
80000014-20 = "3;아야네;12;그렇네요. 생각해보니 오늘은 발렌타인 데이…… 그럼 제가 지금 드린 초콜릿은 발렌타인 초코……"
80000014-21 = "3;아야네;10;저, 저기 그러니까 이건 그런 감정으로 전달 드린 게 아니라……!\n#3;shake\n#3;em;[!]"
80000014-22 = "3;아야네;10;아니, 선생님께 그런 감정이 없다고 하면 거짓말이겠지만…… 그게 아니라!\n#3;hophop"
80000014-23 = "3;아야네;04;오, 오늘은 절대로 그런 의미에서 전달 드린 게 아니니까요……!\n#3;em;[땀]\n#3;stiff"
80000014-24 = "3;아야네;07;무, 물론 선생님께서 그런 의미로 받아들이셔도 하는 수 없지만…… 오히려 환영이지만……\n#3;m2"
80000014-25 = "3;아야네;10;하으, 만약 동아리 사람들이 이 사실을 알게 된다면 어쩌죠…….\n#3;em;[?!]\n#3;jump\n#3;m3"
80000014-26 = "3;아야네;04;분명 \"헤에, 아야네는 얌전한 척하면서 아침 일찍부터 먼저 선수를 치는 그런 아이였구나~\" 하면서 저를 경멸 어린 시선으로 쳐다보기라도 한다면……\n#3;hophop\n#3;m4"
80000014-27 = "3;아야네;07;무, 물론 선생님께서 비밀로 해주신다면…… 아니, 말씀하시고 싶으시면 하셔도 괜찮지만…….\n#3;em;[///]\n#3;stiff\n#3;m3"
80000014-29 = "#na;(이후, 당황해 하는 아야네를 진정시킨 뒤, 느긋하게 초콜릿을 함께 먹었다.)"
