[translation]
80000023-1 = "Romantic Bombardment"
80000023-2 = "Engineering Department Workshop"
80000023-3 = "I came to the Engineering Department after Hibiki's last message."
80000023-4 = "Hey, Sensei."
80000023-5 = "Thanks for coming to see my new invention."
80000023-6 = "Ta-da."
80000023-8 = "[s1] \"Is this a...?\"\n[s2] \"An artillery shell?\""
80000023-9 = "Yeah. It's a 60 millimeter mortar shell—the same one I usually use."
80000023-10 = "Yeah. It's a 60 millimeter mortar shell—the same one I usually use."
80000023-11 = "But here's the kicker: It's not filled with gunpowder."
80000023-12 = "It's filled with chocolate."
80000023-13 = "[s] \"Chocolate?\""
80000023-14 = "Yeah. Concentrated cacao paste, to be exact."
80000023-15 = "Fire the shell, the cacao paste separates with the high heat, and ka-bam.#nChocolate swamp where it lands."
80000023-16 = "It was a request for a Valentine's Day event, but I took it upon myself to increase its power and scope."
80000023-17 = "[s] \"That's pretty impressive.\""
80000023-18 = "Yeah. I thought it needed to be big enough for everyone to enjoy."
80000023-19 = "The only issue is, I've finished development..."
80000023-20 = "...but I haven't had a chance to test it."
80000023-21 = "So...can I fire this at the Schale building?"
80000023-22 = "Imagine the romantic atmosphere as chocolate flows down the walls."
80000023-23 = "[s] \"Yeah... No. That's dangerous and not romantic at all.\""
80000023-24 = "Hmm..."
80000023-25 = "I guess someone could get hurt if they got hit by it..."
80000023-26 = "Oh! Then how about the Trinity Plaza fountain?"
80000023-27 = "Imagine how happy Trinity students would be if their boring old fountain turned into a chocolate dream."
80000023-28 = "[s3] \"That's still just as dangerous!\"\n[s4] \"Do you want to start a war between Millennium and Trinity?!\""
80000023-29 = "Okay, good point..."
80000023-30 = "Okay, good point..."
80000023-31 = "I guess I'll just give it to you, then."
80000023-32 = ""
80000023-34 = ""
80000023-35 = ""
80000023-36 = "Feel free to use it if you ever get a chocolate craving."
80000023-37 = "I can't guarantee it'll taste good, though."
