[translation]
80000074-1 = "#title;해본 적 없는 일"
80000074-2 = "#na;(카즈사의 연락을 받고, 방과 후 비어 있는 교실로 찾아갔다.)"
80000074-3 = "3;카즈사;03;아, 선생님. 시간 맞춰 왔네.\n#3;a\n#3;em;[음표]"
80000074-4 = "3;카즈사;01;응? 무슨 일 있냐고? 아아. 아냐. 딱히 부탁할 게 있다거나 그런 건 아니고……."
80000074-5 = "3;카즈사;06;벼, 별……. 다른 이유 있겠어? 알면서 모른척하지 말라고.\n#3;stiff\n#3;em;[///]"
80000074-6 = "3;카즈사;99;오늘 같은 날이니까……. 당연히 이거 때문에 부른 거지. ……자."
80000074-7 = "#st;[0,0];instant;1;"
80000074-9 = "3;카즈사;01\n#3;m5\n#wait;1000"
80000074-11 = "[ns1] \"초코 딸기 케이크네.\"\n[ns2] \"발렌타이 데이라 이거구나.\""
80000074-12 = "3;카즈사;03;뭐, 그렇지……. 모처럼이니까……. 이런 날이니까 말이야."
80000074-13 = "3;카즈사;03;뭐, 그렇지……. 모처럼이니까……. 이런 날이니까 말이야."
80000074-14 = "3;카즈사;04;그, 그냥 그런 것뿐이야. 어차피 다른 녀석들도 많이 줬을 거 아냐. 선생님한텐 딱히 특별한 일 아니라는 것 정도는 나도 안다고.\n#3;m3\n#3;em;[속상함]"
80000074-15 = "3;카즈사;01;……뭐? 그렇지 않다고?"
80000074-16 = "3;카즈사;02;정말 기쁘다고……? 안 잊을 거라고?"
80000074-17 = "#st;[0,0];instant;1;"
80000074-19 = "3;카즈사;04\n#3;em;…\n#wait;2500"
80000074-20 = "3;카즈사;99;……후우……. 선생님 진짜, 또 그런 말을 아무 자각도 없이……."
80000074-21 = "3;카즈사;01;……에휴. 아니다. 이제 그런 말로 일일이 따지는 것도 입 아프니 그냥 넘어가자.\n#3;em;[한숨]"
80000074-22 = "3;카즈사;02;그나저나 선생님 취향을 모르니 그냥 적당히 고른 거라, 마음에 들지는 잘 모르겠……"
80000074-23 = "3;카즈사;01;……응?"
80000074-24 = "3;카즈사;01;그런데 왜 그냥 초콜릿이 아니라 초코 케이크냐고?\n#3;em;[?]"
80000074-25 = "3;카즈사;06;그, 글쎄. 고를 땐 별 생각 없었는데?\n#3;stiff"
80000074-26 = "3;카즈사;04;그러고 보니 평소에 내가 자주 사 먹던 딸기 케이크랑 비슷한 거 같기도 하고……. 맛만 초코 맛으로 달라진 느낌일지도.\n#3;em;…"
80000074-27 = "3;카즈사;01;……뭐?"
80000074-28 = "3;카즈사;12;그냥 자기 먹고 싶은 거 고르다가 겸사겸사 얻어걸린 거냐고……?\n#3;em;[?]"
80000074-29 = "3;카즈사;09;무, 무슨 말을 또 그렇게 해 당신은!!\n#3;hophop"
80000074-30 = "3;카즈사;08;참, 나 어이가 없네! 줘도 난리구만, 줘도 난리야! 먹기 싫으면 이리 내. 내가 먹을 테니까!"
80000074-31 = "3;카즈사;05;이쪽은 나름대로 고심해서 고른 물건이라고. 알아? 내가 뭐 평소에 선물을 해봤어, 뭘 사서 같이 나눠 먹길 해봤어?"
80000074-32 = "3;카즈사;06;제 딴에는 안 하던 짓 용기 내가지고 한 건데, 말장난이나 치고 있고 말이야!\n#3;stiff\n#3;em;[속상함]"
80000074-33 = "3;카즈사;02;……뭐라고?"
80000074-34 = "3;카즈사;10;평소에도 디저트 많이 주지 않았냐고? 같이 먹은 적도 많지 않느냐고?"
80000074-35 = "3;카즈사;08;무슨 말도 안 되는……!\n#3;hophop"
80000074-36 = "3;카즈사;05;소리를…… 하고 앉았……\n#3;em;…"
80000074-37 = "3;카즈사;01;……어……?"
80000074-38 = "3;카즈사;01;……?\n#3;em;[?]"
80000074-39 = "3;카즈사;04;어라. 듣고 보니……. 선생님. 우리 이런 게 처음은 아니었던가……?"
80000074-40 = "[s3] \"응. 이것저것 자주 나눠 먹었지.\"\n[s4] \"자각이 없는 건 그쪽이셨고요.\""
80000074-43 = "#st;[0,0];instant;1;"
80000074-45 = "3;카즈사;10\n#3;em;…\n#wait;2500"
80000074-46 = "3;카즈사;10;……어……. 어, 음…….\n#3;stiff"
80000074-47 = "3;카즈사;04;……선생님."
80000074-48 = "3;카즈사;02;어쩌면……. 어쩌면 말이야……. 이건 그냥 해 보는 말인데……."
80000074-49 = "3;카즈사;01;……나…… 사실……"
80000074-50 = "3;카즈사;04;……꽤…… 꼬리 치는 타입이었던 걸까…….\n#3;em;[세로선]"
80000074-51 = "[s5] \"그 정도로 그런 생각은 좀 과하지.\"\n[s6] \"이상한 말 말고 케이크나 드세요.\""
80000074-52 = "3;카즈사;04;………….\n#3;em;…"
80000074-53 = "3;카즈사;04;………….\n#3;em;…"
80000074-54 = "3;카즈사;99;……으, 응…….\n#3;stiff"
80000074-55 = "3;카즈사;04;역시 그렇겠지……."
80000074-57 = "#na;(이후 카즈사와 초코 케이크를 나눠 먹으며 남은 시간을 보냈다.)"
80000074-58 = "#na;(그리고 카즈사는 그게 발렌타인 선물이라는 것도 잊어버리고, 딸기 부분부터 냅다 먹어버렸다.)"
