[translation]
80000136-1 = "ฉันทำเองเลยนะ!"
80000136-2 = "สำนักงานชาเล่ต์"
80000136-3 = "(คุณครูกลับมาจากไปทำงานภาคสนามก็สังเกตเห็นอะไรบางอย่างที่ไม่เคยเห็นมาก่อนในห้อง)"
80000136-7 = "(มีช็อกโกแลตที่แกะห่อแล้ววางอยู่ที่มุมหนึ่งในห้องสำนักงาน)"
80000136-11 = "(เอ๋ นั่นมัน... หรือว่า....)"
80000136-12 = "[ns] \"ริตสึงั้นเหรอ...?\""
80000136-13 = "ค่ะ! ถูกต้องแล้วค่ะ!!"
80000136-14 = "เซอร์ไพรส์ช็อกโกแลตสุดพิเศษ! ที่เตรียมมาเพื่อคุณครูโดยเฉพาะ!"
80000136-15 = "แฮปปี้ วาเลนไทน์นะ คุณครู!"
80000136-16 = "[s] \"ขอบใจนะ ริตสึ!\""
80000136-17 = "แหะๆ"
80000136-18 = "ว่าแต่ว่าทำไมคุณครูถึงรู้ได้ทันทีที่เห็นเลยล่ะ?"
80000136-19 = "ว่าฉันเป็นคนวางช็อกโกแลตไว้ตรงนั้นน่ะ?"
80000136-20 = "[ns] \"ครูจะไม่รู้ได้ยังไง\""
80000136-25 = "[ns] \"ช็อกโกแลตมันใหญ่กว่าตู้เย็นในห้องสำนักงานอีก\""
80000136-26 = "อ้อ...!"
80000136-27 = "แต่ไม่ต้องห่วงหรอกนะ คุณครู!"
80000136-28 = "[s] \"หืม? เป็นห่วงเรื่องอะไรเหรอ?\""
80000136-29 = "นี่เป็นช็อกโกแลตที่ไม่ต้องเก็บไว้ในตู้เย็นหรอก!"
80000136-30 = "แล้วก็ไม่ต้องห่วงเรื่องอากาศร้อนด้วย!"
80000136-31 = "เพราะว่า..."
80000136-32 = "นี่คือช็อกโกแลตที่ไม่มีวันละลายยังไงล่ะ!"
80000136-33 = "[s1] \"ช็อกโกแลตที่ไม่ละลายเหรอ?!\"\n[s2] \"ใช้วิธีไหนทำขึ้นมาเนี่ย...!\""
80000136-36 = "ถ้าอยากรู้ก็ลองจับดูมั้ย คุณครู?"
80000136-37 = "(คุณครูลองทำตามที่ริตสึบอก ค่อยๆ ยื่นมือไปจับผิวช็อกโกแลตอย่างระมัดระวัง)"
80000136-38 = "[ns] \"นี่... นี่มัน...!\""
80000136-39 = "แหะๆ เป็นไงบ้าง? ทีนี่รู้เคล็ดลับรึยัง?"
80000136-40 = "[s] \"ถ้าเป็นแบบนี้คงไม่มีวันละลายแน่\""
80000136-44 = "[ns] \"ช็อกโกแลตที่ทำจากหินเหรอเนี่ย...!\""
80000136-45 = "ใช่แล้ว! ฉันแกะสลักมาจากหินอ่อนสีน้ำตาลละ!"
80000136-46 = "เป็นไงล่ะ?"
80000136-47 = "[s3] \"ฝีมือประณีตสุดๆ เลยแฮะ\"\n[s4] \"เห็นครั้งแรกก็ดูไม่ออกเลยว่าเป็นหินหรือเป็นช็อกโกแลต...\""
80000136-50 = "แหะๆ ได้รับคำชมจากคุณครูด้วย!"
80000136-51 = "หืม? ฉันแกะสลักหินก้อนใหญ่ขนาดนี้ได้ยังไงน่ะเหรอ?"
80000136-52 = "ก็นะ มายืนตรงนี้ใกล้ๆ สิ คุณครู"
80000136-53 = "ฉันจะอธิบายให้ฟังอย่างละเอียดเลย!"
80000136-55 = "(หลังจากนั้น คุณครูก็นั่งมองช็อกโกแลต (?) และฟังเรื่องราวการแกะสลักอย่างละเอียดจากริตสึ)"
80000136-56 = "(ไม่สิ แต่เรื่องสำคัญกว่านั้น...)"
80000136-59 = "[ns5] \"ยกเข้ามาในห้องสำนักงานได้ยังไงน่ะ ริตสึจัง?\"\n[ns6] \"อุปกรณ์รักษาความปลอดภัยก็น่าจะทำงานอยู่นะ...\""
80000136-62 = "หืม? ตรงท่อระบายอากาศด้านในสุดไม่มีสักหน่อย"
80000136-67 = "(หลังจากริตสึกลับไป คุณครูก็เริ่มตรวจสอบระบบรักษาความปลอดภัยใหม่อย่างละเอียด)"
