[translation]
80000057-1 = "#title;익숙해진 모습"
80000057-2 = "#na;(늦은 밤, 업무 도중 잠시 들를 일이 있어서 휴게실로 향했다.)"
80000057-3 = "#st;[0,0];instant;1;"
80000057-8 = "[ns1] \"……?\"\n[ns2] 불을 켜서 확인한다."
80000057-11 = "#st;[0,0];instant;1;"
80000057-15 = "#na;(불이 켜지자 발치에 떨어져 있던 무언가의 모습이 눈에 들어왔다.)"
80000057-16 = "#st;[0,0];instant;1;"
80000057-25 = "[ns] \"…….\""
80000057-27 = "[ns3] \"세리나.\"\n[ns4] \"숨어 있지 않아도 돼.\""
80000057-30 = "1;세리나;04;아, 아하하……. 안녕하세요. 선생님…….\n#1;em;[///]\n#1;greeting\n#1;a"
80000057-31 = "1;세리나;05;쉬시는 동안 드시면 좋겠다 싶어서……. 살짝 놔두고만 가려고 했던 건데…….\n#1;m3"
80000057-32 = "1;세리나;06;다, 당분은 머리도 힘 나게 해 주니까요! 이런 때일수록 도움이 될 거 같아서, 그래서……!\n#1;em;[!]\n#1;hophop"
80000057-33 = "1;세리나;04;무, 물론 오늘이 발렌타인 데이라는 이유도 있긴 하지만……요.\n#1;stiff"
80000057-34 = "1;세리나;03;……사, 사실 그쪽 이유가 좀 더 큽니다……. 네……. 아하하…….\n#1;em;[땀]\n#1;greeting"
80000057-35 = "1;세리나;04;호, 혹시 민폐…… 였을까요? 그랬다면 죄송해요……."
80000057-36 = "1;세리나;05;……네?\n#1;em;[?]"
80000057-37 = "1;세리나;04;괜찮으시다고요……? 우, 우선 앉으라고요? 어, 어째서……."
80000057-38 = "1;세리나;02;온 김에 뭐라도 마시고 가라고요……?\n#1;em;[?!]\n#1;shake"
80000057-39 = "1;세리나;01;서, 선생님……? 뭔가 그……. 오늘은 전혀 개의치 않아 하시는 느낌이네요……?"
80000057-40 = "[s5] \"슬슬 익숙해질 때도 됐으니까.\"\n[s6] \"세리나를 경계할 이유는 없으니까.\""
80000057-41 = "1;세리나;02;그, 그렇군요. 저야 이해해 주신다면 정말로 감사하지만…….\n#1;em;[반응]"
80000057-42 = "1;세리나;02;그, 그렇군요. 저야 이해해 주신다면 정말로 감사하지만…….\n#1;em;[반응]"
80000057-44 = "1;세리나;03;……아. 바로 드시네요. 그 초콜릿."
80000057-45 = "1;세리나;04;네? 아. 당분 섭취라고요……? 네. 그렇죠……. 일부러 좀 영양도 좋은 걸로 가져왔어요."
80000057-46 = "1;세리나;01;입맛에는 맞으신 모양이네요. 다행이네요!\n#1;em;[반짝]\n#1;greeting"
80000057-47 = "#st;[0,0];instant;1;"
80000057-49 = "1;세리나;99\n#1;em;…\n#wait;2500"
80000057-50 = "1;세리나;04;그, 그럼 전 이만……. 다음에 또, 필요하실 때 찾아오는 것으로…….\n#1;m4"
80000057-51 = "[s] \"세리나.\""
80000057-52 = "1;세리나;02;네, 네!? 왜, 왜 그러세요, 선생님?\n#1;em;[?!]\n#1;jump"
80000057-53 = "[s7] \"돌아갈 땐 그냥 정문으로 나가도 돼.\"\n[s8] \"고마워. 잘 먹을 게.\""
80000057-54 = "1;세리나;99;…….\n#1;em;[...]"
80000057-55 = "1;세리나;99;…….\n#1;em;[...]"
80000057-56 = "1;세리나;01;……후후. 후후후……."
80000057-57 = "1;세리나;03;……네, 선생님. 선생님도 너무 무리하진 마세요.\n#1;em;[음표]\n#1;greeting"
80000057-60 = "#na;세리나;……다음에 또 뵙겠습니다."
