[translation]
80000015-1 = "The Snacks of an Optimizer"
80000015-2 = "Millennium Campus"
80000015-3 = ""
80000015-4 = "I spotted Eimi sitting and eating alone in the courtyard at Millennium."
80000015-5 = "[s] \"Hey, Eimi.\""
80000015-6 = "Oh. Hello, Sensei."
80000015-7 = "What a coincidence. I was just winding down from a recent mission."
80000015-8 = "[s] \"What's that you're eating?\""
80000015-9 = "Chocolate."
80000015-10 = "I expel a lot of energy when I'm out in the field, so eating high-calorie chocolate with lots of sugar is effective after a mission."
80000015-11 = ""
80000015-13 = ""
80000015-16 = "Would you like one?"
80000015-17 = ""
80000015-18 = ""
80000015-22 = "[ns] \"Oh. Huh...\""
80000015-23 = "Is something wrong?"
80000015-24 = "Come to think of it, even students who love sweets are reluctant to buy these ones for some reason."
80000015-25 = "Maybe that's why they were overstocked at the store and I was able to buy them at a discount."
80000015-26 = "[s] \"I mean, the shape is sort of...\""
80000015-27 = "The shape? Why would something like that make a difference?"
80000015-28 = "The ingredients are all that matter. What it looks like is irrelevant."
80000015-29 = "And if that means you can buy them at a discount, then that makes them all the better choice."
80000015-30 = "Though I admit I bought too much. I don't want any of it to go to waste,#nso here. You take it, Sensei."
80000015-32 = "I was stopped for questioning by a Valkyrie Police School student on my way back to Schale because of the suspicious shape of Eimi's chocolates."
