[translation]
80000086-1 = "#title;Sweet Logistics"
80000086-2 = "#na;(모에를 도와 RABBIT 소대의 보급품을 정리하던 중…….)"
80000086-3 = "#st;[0,0];instant;1;"
80000086-6 = "#na;(갑작스러운 소나기로 인해 온몸이 흠뻑 젖어버리고 말았다…….)"
80000086-8 = "#place;코우사기 공원"
80000086-9 = "3;모에;15;하아…… 분명 일기 예보에서는 하루 종일 맑다고 했었는데, 예고도 없이 소나기라니……\n#3;em;[땀]\n#3;a"
80000086-10 = "3;모에;16;다행히 선생님이 도와준 덕분에 중요한 전자기기나 탄약이 물에 젖는 건 막을 수 있었지만……"
80000086-11 = "3;모에;06;갈아입을 옷도 없는데 완전히 젖어버리고 말았네.\n#3;em;[속상함]"
80000086-12 = "3;모에;18;이런 파멸적인 상황은 나쁘지 않지만, 어쩐지 한기가 드는 게 감기에 걸릴 것 같은 걸……"
80000086-13 = "[s] \"샬레에 가서 남는 체육복이라도 가져올까?\""
80000086-14 = "3;모에;04;옷이 젖은 채로 샬레까지 돌아간다고? 그랬다가는 선생님이 감기에 걸릴 걸."
80000086-15 = "#st;[0,0];instant;1;"
80000086-17 = "3;모에;15\n#3;em;…\n#wait;2500"
80000086-18 = "3;모에;12;지금 바로 모닥불을 지필테니, 불 곁에서 옷을 말리고 가는 게 어때?"
80000086-19 = "3;모에;02;벌써 해도 비치기 시작했으니 한나절이면 옷이 마를 거야. 잠깐만 기다려봐.\n#3;em;[음표]"
80000086-21 = "#na;(모에가 마른 장작을 모아 불을 피우기 시작했다……)"
80000086-22 = "3;모에;17\n#3;a"
80000086-23 = "3;모에;17;하…… 따듯해라……\n#3;em;[하트]"
80000086-24 = "3;모에;02;젖은 몸이 마르면서 몸이 덥혀지니 이제야 좀 살 것 같네……"
80000086-25 = "[ns] \"그러게. 따듯하니 기분이 좋네……\""
80000086-26 = "3;모에;12\n#3;em;[반응]\n#wait;1500"
80000086-27 = "3;모에;13;후후, 후후후……"
80000086-28 = "3;모에;13;뜨겁게 타오르는 모닥불을 보고 있노라니 갑자기 '그게' 떠오르네……"
80000086-29 = "3;모에;16;모닥불 앞에서만 맛볼 수 있는 달콤한 파멸……\n#3;em;…"
80000086-30 = "3;모에;18;오랫동안 잊고 있었는데, 이 불길을 보니 갑자기 떠오르고 말았어……"
80000086-31 = "3;모에;09;하아, 하아…… 어쩌지, 선생님……? 역시……\n#3;stiff"
80000086-32 = "3;모에;11;못 참겠어!\n#3;closeup"
80000086-35 = "[ns] \"잠깐…… 기다려, 모에! 무얼 하려는 건지 모르겠지만, 멈춰!\""
80000086-37 = "1;모에;15\n#5;a"
80000086-38 = "1;모에;15\n#wait;2500"
80000086-39 = "1;모에;12;……응? 선생님은 안 먹을 거야, 이 스모어?\n#1;em;[?]"
80000086-40 = "[s] \"스모어……?\""
80000086-41 = "1;모에;12;응. 기왕 모닥불을 피웠으니 마시멜로 하나 정도는 구워도 괜찮을 것 같아서.\n#1;m3\n#1;em;[음표]"
80000086-42 = "1;모에;13;마시멜로는 그냥 먹어도 충분히 달콤하고 맛있지만, 불에 구우면 단맛과 쫀득한 식감이 배가되어서 엄청나게 맛있어지거든……!"
80000086-43 = "1;모에;02;예전부터 캠핑 중에 모닥불을 피울 일이 있으면 소대원들이랑 함께 마시멜로를 구워서 스모어 쿠키를 만들어 먹곤 했거든."
80000086-44 = "1;모에;17;후후…… 이렇게 선생님과 함께 모닥불을 쬐며 마시멜로를 굽는 것도 운치가 있네."
80000086-45 = "[s] \"과자를 굽는 것 정도라면 문제는 없지만……\""
80000086-47 = "[ns] \"이 스모어의 어디가 파멸적인거야?\""
80000086-48 = "1;모에;04;선생님은 보고도 모르는 거야? 이 스모어가 품고 있는 폭력적인 위력을?\n#1;em;[?]"
80000086-49 = "1;모에;15;스모어는 크래커 위에 달콤한 마시멜로를 얹은 뒤, 그 위에 달달한 초콜릿을 하나 더 얹어서 만드는 엄청나게 달콤한 디저트."
80000086-50 = "1;모에;16;당연히 맛은 끝내주지만, 칼로리만큼은……"
80000086-51 = "[s] \"그야말로 파멸적인 수준이겠네……\""
80000086-52 = "1;모에;05;맞아. 다이어트를 꿈꾸고 있는 사람이라면 절대 입에 대서는 안 되는 파멸의 디저트지."
80000086-53 = "1;모에;13;하지만 이 파멸을 감내해야만 얻을 수 있는 쾌락 또한 존재하는 법이니까……"
80000086-54 = "1;모에;02;선생님, 어때? 나와 함께 이 파멸을 맛보지 않을래……?\n#1;em;[하트]"
80000086-56 = "#na;(이후, 모에와 함께 모닥불 앞에서 사이좋게 스모어를 나누어 먹었다…….)"
80000086-57 = "#na;(모에가 만들어준 스모어는 맛있었지만, '파멸'이라는 말이 떠오를 만큼 달착지근했다.)"
