[translation]
83302200500-5 = ""
83302200500-6 = "Waaahhh! Hina, thank you for coming!"
83302200500-7 = ""
83302200500-9 = ""
83302200500-11 = ""
83302200500-12 = "I dispatched those...things that were making a mess of your club room..."
83302200500-13 = "But Juri, what happened here?"
83302200500-14 = "It's...It's...!"
83302200500-15 = "Th-The thing is... Um..."
83302200500-16 = "Waaahhh! They kidnapped Fuuka again!"
83302200500-17 = "She told me to wait until she got back, but...! "
83302200500-18 = "The deadline for the Pandemonium Society's food order is almost here..."
83302200500-19 = "I was scared that the Pandemonium Society might use the missed deadline as an excuse to cut the School Lunch Club's budget, so I...I...I—! *sob*"
83302200500-20 = "Breathe, Juri. It's okay. Let's walk through the order of events."
83302200500-22 = ""
83302200500-25 = ""
83302200500-27 = "Based on what you said..."
83302200500-28 = "You felt that the deadline for the Pandemonium Society's catering order was too close for further delay."
83302200500-29 = "*sniffle* Y-Yes..."
83302200500-30 = "But at the same time, Fuuka was..."
83302200500-31 = "She was abducted by the Gourmet Research Society at the worst possible time."
83302200500-32 = "*sniffle* Y-Yes, that's exactly right..."
83302200500-33 = "But you were scared of what might happen to your club if you didn't finish the order. So you tried your best to fulfill it yourself, even though Fuuka asked you to wait."
83302200500-34 = "And you remembered how the president of the Hot Springs Department believed there was an amazing hot spring beneath the School Lunch Club. She must have told you how to access the hot water vein."
83302200500-35 = "Which you decided to use to make hot spring eggs..."
83302200500-36 = "And as a result...those things appeared."
83302200500-38 = "*sniff* *sniffle* Yes! That's all true...! It's all my fault!"
83302200500-39 = "(And Makoto ended up in that state after consuming Juri's food.)"
83302200500-40 = "Waaahhh! Hina! Fuuka! I'm s-sorry!"
83302200500-41 = "You have nothing to apologize for, Juri."
83302200500-42 = "Even if it led to some trouble, you were just doing your best to cope with extreme circumstances."
83302200500-43 = "*sniff* H-Hina!"
83302200500-44 = "However... It would only cause further problems if we left Fuuka in the hands of her abductors."
83302200500-45 = "Thank you for your help. I'll attend to Fuuka, so don't worry about her any longer."
83302200500-46 = "Okay! Thank you, Hina! I'll leave it to you!"
