[translation]
83301300300-5 = ""
83301300300-6 = "Makoto. There's something we need to discuss. "
83301300300-7 = ""
83301300300-9 = ""
83301300300-10 = ""
83301300300-11 = "Kiheheheh! Somehow I doubt there's anything I need to discuss with you!"
83301300300-12 = "Not even our pursuit of the Hot Springs Department, after they caused you so much trouble?"
83301300300-13 = "Hmph! Even then, the thought of colluding with the Prefect Team sticks in my throat!"
83301300300-14 = "What nonsense! The two of us could never work together!"
83301300300-15 = "...Yes, I suspected you would say as much."
83301300300-16 = ""
83301300300-18 = ""
83301300300-20 = "(After Makoto, the person who would know the most information would be...)"
