[translation]
83302400200-5 = ""
83302400200-6 = "ตายจริง คุณฮินะ! น่าจะงานยุ่งอยู่ไม่น้อยเลย แต่ก็ยังอุตส่าห์มาที่ห้องขังด้วยตัวเองแบบนี้"
83302400200-7 = "ฉันไม่รู้ว่าจะต้องต้อนรับยังไงเลยละค่ะ ฮุฮุ"
83302400200-8 = ""
83302400200-10 = ""
83302400200-14 = ""
83302400200-15 = "ฮารุนะ ฉันไม่คิดว่าจำเป็นต้องถามหรอกนะ แต่ก็ขอถามตามมารยาท"
83302400200-16 = "เธอจับตัวฟูกะไปทำไม?"
83302400200-17 = "ฮุฮุ มันก็แน่อยู่แล้วไม่ใช่เหรอคะ"
83302400200-18 = "อาหารสำหรับปาร์ตี้ของปีนี้ที่คุณฟูกะกำลังเตรียมส่งให้แพนเดโมเนียม โซไซตี้..."
83302400200-19 = "ถ้ามีแต่คนในแพนเดโมเนียม โซไซตี้ได้ชิมก่อน มันก็คงจะน่าเสียดายมากๆ เลยนี่คะ?"
83302400200-20 = "ในฐานะของหัวหน้าชมรมชิมอาหารของเกเฮนน่า!"
83302400200-21 = "ฉันคิดว่าพวกฉันต้องเป็นฝ่ายที่ได้ชิมอาหารนั่นก่อนถึงจะถูกต้อง ก็เท่านั้นเองค่ะ!"
83302400200-22 = "อืม... ไม่จำเป็นต้องถามจริงด้วย เพราะสุดท้ายแล้วพวกเธอก็ก่อเหตุวุ่นวายด้วยเหตุผลเดียวกับทุกครั้ง"
83302400200-23 = "พวกเธอนี่...ต่อให้อยู่ในห้องขังกี่ครั้งก็ไม่เปลี่ยนเลยสินะ"
83302400200-24 = "แน่นอนอยู่แล้วค่ะ เพราะถ้าเป็นการทำเพื่ออาหารอร่อยๆ แล้วละก็ ไม่ว่าจะงานหินแค่ไหน ชมรมชิมอาหารก็ทำได้"
83302400200-25 = "ก็ดี ฉันขอจบเรื่องแค่นี้ อยู่สงบๆ และสำนึกผิดในนี้ไปสักพักแล้วกัน"
83302400200-26 = ""
83302400200-28 = ""
83302400200-32 = "ฮุฮุ ค่า~ แล้วฉันจะตั้งตารอการได้เจอกันในครั้งหน้านะคะ คุณฮินะ"
