[translation]
83306075101-4 = "4;불량배 A;01\n2;불량배 B;04\n#4;a\n#2;a\n#4;h\n#2;h\n#wait;1000"
83306075101-5 = "4;불량배 A;02;으으윽…… 눕고 싶어! 병원 침대에 누워 땡땡이를 치고 싶어!\n#4;stiff"
83306075101-6 = "2;불량배 B;06;하지만 벌레는 역시 무섭다고! 누워 있는 사이에 이불 속으로 들어오기라도 하면……!\n#2;em;[속상함]"
83306075101-7 = "4;불량배 A;06;히에에에엑?!\n#4;em;[?!]\n#4;shake"
