[translation]
83303300300-5 = ""
83303300300-6 = "ทะ... ท่านประธานฮินะ! มีเรื่องที่ต้องจัดการด่วนเลยค่ะ!"
83303300300-7 = "มีอะไรเหรอ?"
83303300300-8 = "คือว่า... มีข่าวว่าพวกเด็กเจ้าปัญหาที่ท่านประธานไปจัดการมา..."
83303300300-9 = "เที่ยวไปก่อความไม่สงบแล้วป่าวร้องต่างๆ นานาว่า..."
83303300300-10 = "<มาทําลายความคาดหวังประธานของแพนเดโมเนียม โซไซตี้งั้นเรอะ เรายอมไม่ได้!>"
83303300300-11 = "แล้วก็ <เราคือนักเลงที่อุทิศชีวิตให้กับความจงรักภักดี! เราขอประกาศสงครามกับคณะกรรมการวินัย#nทุกคน!> ด้วยค่ะ"
83303300300-12 = "จงรักภักดีงั้นเหรอ... สงสัยจังว่าประธานของแพนเดโมเนียม โซไซตี้ไปมีคุณงามความดีอะไรกับเด็ก#nเจ้าปัญหาพวกนั้น"
83303300300-13 = "ก็ดี ถ้าอยากก่อความไม่สงบแบบนั้นนักละก็ ครั้งนี้ฉันจะทำให้พูดอะไรไม่ออกเลย"
