[translation]
83306030100-5 = ""
83306030100-6 = "*sigh* How troublesome."
83306030100-7 = "What's wrong, Ako? Has something happened?"
83306030100-8 = "Oh... Head Prefect."
83306030100-9 = "The Prefect Team has been receiving a lot of prank calls while you've been away from the office."
83306030100-10 = "Prank calls? Why? What are they about?"
83306030100-11 = "Well... It's not like they have much to say... They just hang up after spouting some nonsense."
83306030100-12 = "I don't think the calls have any meaning outside harassment."
83306030100-13 = "I'd love to pull the phone line and ignore them if I could."
83306030100-14 = "But the Prefect Team can't afford to miss any urgent or emergency calls that come in, so I can't."
83306030100-15 = "Hmm. Allow me to answer the next call, then."
83306030100-16 = "Ah! There's no need! I can't waste your time on bothersome nonsense like—"
83306030100-17 = "Ako. It's interfering with your work, right?"
83306030100-18 = "Your time matters to me too."
83306030100-19 = "Head Prefect Hina..."
83306030100-20 = "Then please, I'll leave this matter to you."
