[translation]
84301500100-5 = "กะแล้วเชียว..."
84301500100-6 = "นี่คือชิปที่น่าสงสัยจริงๆ แต่ยากที่จะคิดว่านี่คือสิ่งที่สร้างขึ้นในมิลเลเนียม ไม่น่าใช่ฝีมือของนักเรียนที่นี่"
84301500100-7 = "ดูออกถึงขนาดนั้นเลยเหรอคะ?"
84301500100-8 = "ฉันยังยืนยันไม่ได้หรอก... แต่ฉันก็รู้วิสัยของเด็กโรงเรียนนี้ดี ไม่มีใครคิดทำเรื่องอะไรแบบนี้หรอก"
84301500100-9 = "รู้วิสัยของนักเรียนงั้นเหรอคะ?"
84301500100-10 = "ฉันเป็นประธานนักเรียนของมิลเลเนียมนะ ฉันต้องรู้สิว่านักเรียนชอบอะไรและต้องการอะไร จะได้สร้างโรงเรียนที่ทำให้ทุกคนพึงพอใจได้มากที่สุด"
84301500100-11 = "ถึงแม้ช่วงหนึ่งฉันจะเคยเลือกวิธีที่ผิดก็เถอะ..."
84301500100-12 = "คนเราทุกคนต่างทำผิดพลาดในเรื่องวิธีการกันทั้งนั้นละค่ะ ฉันคิดว่าคุณไม่ควรเก็บไว้ในใจจนถึงตอนนี้#nนะคะ"
84301500100-13 = "ไม่หรอก... ฉันน่ะ..."
84301500100-14 = "ฉัน... ฉันในตอนนี้คง..."
84301500100-15 = ""
84301500100-17 = ""
84301500100-18 = ""
84301500100-19 = "หายไปคนหนึ่งนะคะเนี่ย..."
84301500100-20 = "อย่างที่ฉันเคยบอกไป เนรุมีงานอย่างอื่นต้องทำต่างหากน่ะ เนรุออกไปทำงานนั้นสักพักแล้ว อีกเดี๋ยวก็คงกลับมาแล้วละ"
84301500100-21 = "ฉันว่าเรามาตรวจสอบชิปที่เอามากันก่อนดีกว่า ฉันจะใช้เวลาไม่นาน ช่วยรอหน่อยนะ"
