[translation]
84306100500-5 = "Good work. That went more smoothly than I expected."
84306100500-6 = "It seems Mikamo Neru's intuition is more accurate than my calculations when it comes to missions and infiltrations. I suppose that's due to the difference in our reference data."
84306100500-7 = "I couldn't have done it without your scanning device. But thank you, I'm glad it worked out."
84306100500-8 = "...If you don't mind me asking, what exactly did I find?"
84306100500-9 = "It looked like a regular toy gun."
84306100500-10 = "...Oh, you mean this?"
84306100500-11 = "It's a \"heightening ray.\" It hits the target with a vast amount of energy, which makes the target taller for a few minutes."
84306100500-12 = "That's incredible."
84306100500-13 = ""
84306100500-15 = ""
84306100500-16 = "...Wait, but why did we need to recover it, then? Isn't that the kind of thing you'd expect to see at this Expo?"
84306100500-17 = "Normally, yes. If we could be sure that it stayed within acceptable parameters."
84306100500-18 = "Acceptable parameters?"
84306100500-19 = "Making someone taller by tens of centimeters wouldn't be cause for alarm, in this context. As you say, this is the sort of venue where one would expect such experimental tech."
84306100500-20 = "But suppose the device malfunctioned, and made someone taller by tens of meters instead."
84306100500-21 = "Oh, tens of meters..."
84306100500-22 = "...Wait, what?"
84306100500-23 = "Wh-Why would they even allow such a thing in the exhibition hall...?!"
84306100500-24 = "They're looking for investors. Research costs enormous amounts of money."
84306100500-25 = "They claim that once the ray is done, they'll be able to \"feed tens of people with just one strawberry,\" but..."
84306100500-26 = "...it's too much of a liability for the Expo. Unfortunately, we have to confiscate it for now."
84306100500-27 = "...I...see. I understand."
84306100500-28 = "(Now I feel bad for fidgeting with it on the way back here. What would've happened if I'd accidentally shot myself?)"
84306100500-29 = "I'll call you again soon, I'm sure."
84306100500-30 = "For now, good work. Go take some time for yourself."
