[translation]
84306100502-5 = ""
84306100502-6 = "เรากำลังคุยกันเรื่องเทคโนโลยีที่ถูกขโมยไปน่ะ มันเรียกว่าเทคโนโลยีเพิ่มความสูงของวัตถุ สุดยอดไปเลยใช่มั้ยล่ะ?"
84306100502-7 = "ฉันเองก็เคยคิดอยู่หลายครั้ง... แต่ก็พับไอเดียนี้ไปก่อนเพราะยังติดเรื่องความเสถียร ขอถามได้มั้ยว่าเธอแก้ปัญหาได้ยังไง?"
84306100502-8 = "อ้อ เรื่องความเสถียรน่ะเหรอ!? คือ... คือว่า... เอ่อ..."
84306100502-9 = "ตะ... ตอนนี้จำไม่ค่อยได้น่ะ...! ไว้ถ้านึกออก ถ้านึกออกแล้วจะมาบอกนะ!!"
