[translation]
84305100100-5 = ""
84305100100-6 = "แล้วนี่... จะให้ฉันทำอะไรล่ะ?"
84305100100-7 = "ถามว่าจะให้ทำอะไรงั้นเหรอ...?"
84305100100-8 = "ก็เธอเคยพูดไว้เองว่าถ้าจะเข้าไปโดยไม่มีข้อมูลไบโอเมตริกซ์ของเธอ งานก็จะซับซ้อนมากขึ้นนี่นา?"
84305100100-9 = "แล้ว 'วิธีที่ซับซ้อนมากขึ้น' มันคืออะไรกันล่ะ?"
84305100100-10 = "มีเพียงวิธีเดียวที่จะเข้าไปโดยไม่ต้องผ่านการตรวจสอบ"
84305100100-11 = "และวิธีนั้น... ทำคนเดียวไม่ได้ ถ้าเป็นไปตามที่ฉันคาดการณ์ งานนี้ต้องทำสองคน"
84305100100-12 = "งั้นก็พอดีเลยนี่ ตอนนี้เราก็มีสามคน เอาเธอออกก็เหลือสองพอดี"
84305100100-13 = "ถ้าต้องไปสองคน ฉันไปกับเซอาดีกว่าไปกับเธอ นี่ไม่ได้มาจากความรู้สึกส่วนตัวอะไรหรอก มันคือข้อเท็จจริงน่ะ"
84305100100-14 = "เพราะงานนี้เราต้องเคลื่อนไหวอย่างลับๆ และต้องเป็นคนที่รู้จักการซ่อนตัวด้วย"
84305100100-15 = "ทำงานกันได้ไม่นาน... แต่เหมือนว่าจะมีความเชื่อใจในตัวเซอาจะมากขึ้นเลยนะ เนรุ"
84305100100-16 = "ก็ไม่เชิงหรอก... ฉันแค่บอกว่าคนที่มีประสบการณ์ในการทำงานมาแล้วย่อมเหมาะสมกว่ามือใหม่ที่ยัง#nไม่เคยทำอะไรน่ะ"
84305100100-18 = "นี่เกี่ยวกับประสบการณ์เหรอคะ? แต่ว่างานที่ฉันทำครั้งนี้ไม่ใช่การแทรกซึมนะ..."
84305100100-19 = "ไม่หรอก นี่มันก็เรียกว่า 'การแทรกซึม' ได้แล้วละ ตอนเจอฉันครั้งแรกก็ทำได้ดีเลย"
84305100100-20 = "เนรุ แต่อย่างที่ฉันบอกไปก่อนหน้านี้ว่ามันเสี่ยงเกินไป"
84305100100-21 = "เซอาไม่ใช่นักเรียนมิลเลเนียม แล้วก็เป็นถึงสมาชิกสภาน้ำชาของทรีนิตี้"
84305100100-22 = "ถ้าผิดพลาดอะไรขึ้นมา มิลเลเนียมก็ต้องเผชิญปัญหาไปด้วย..."
84305100100-23 = "พูดมากจริงๆ ถ้าเธอไปที่นั่นแล้วเก้ๆ กังๆ จนถูกจับตัวได้จะเสี่ยงกว่าอีก"
84305100100-24 = "ยังไงการสันนิษฐานนั่นก็ไม่มีความหมายหรอก เพราะ 'สถานการณ์ผิดพลาด' ที่เธอพูดถึงคือ#nสถานการณ์เลวร้ายที่สุดที่แก้ไขอะไรไม่ได้แล้วต่างหากล่ะ"
84305100100-25 = "แต่พวกเราก็ 'จะทำให้ไม่เกิดสถานการณ์แบบนั้น' กันตั้งแต่แรกไม่ใช่เหรอ? "
84305100100-26 = "ใช่มั้ยล่ะ? ฉันพูดถูกใช่มั้ย? ทำไม มีอะไรจะเถียงอีกไหม?"
84305100100-27 = "เรื่องนั้น..."
84305100100-29 = "..."
84305100100-30 = "ไม่หรอก... ฉันเข้าใจแล้ว"
84305100100-31 = "โอ้...? อะไรเนี่ย ยอมรับได้เร็วเกินคาดเลย"
84305100100-32 = "เราคุยกันรู้เรื่องกว่าเดิมเยอะเลยนะเนี่ย"
84305100100-33 = "อ้อ จะว่าไปแล้ว เซอา"
84305100100-34 = "คะ...?"
84305100100-35 = "ได้ไปด้วยกันมันก็ดีอยู่หรอกนะ แต่ก็อย่างที่ฉันบอกไว้ตอนแรก ฉันจะไม่ดูแลหรือคอยใส่ใจเธออยู่#nหรอกนะ ดูแลตัวเองเอาด้วยแล้วกัน"
84305100100-36 = "ท้ายที่สุดแล้ว ฉันก็แค่ต้องการ 'คนที่จะร่วมงานด้วย' ก็เท่านั้น"
84305100100-37 = "..."
84305100100-38 = "ฮุฮุ..."
84305100100-39 = "ฉันรู้ค่ะ แต่ถ้าเจอเรื่องที่ยากเกินไปสำหรับฉัน ฉันจะรีบบอกทันทีค่ะ"
84305100100-40 = "ถ้าเกิดเรื่องแบบนั้นฉันคงต้องขอโทษ แต่ฉันเชื่อว่าเนรุจะช่วยฉันในเรื่องนั้นนะคะ"
84305100100-41 = "ก็เอาสิ แบบนั้นแหละดีแล้ว ดีกว่าฝืนตัวเองจนเกิดเรื่องอะไรให้ฉันปวดหัวเพิ่มน่ะ"
84305100100-43 = "..."
84305100100-44 = "งั้นฉันจะเตรียมแผนการเลย..."
