[translation]
84303100200-5 = ""
84303100200-6 = "เป็นแขกต่างโรงเรียนที่ชอบเล่นซ่อนหาสินะ! ต่อไปจะไปซ่อนที่ไหนเหรอ? ฉันจะหาให้เจอก่อนให้ได้เลย!"
84303100200-8 = "ขอโทษค่ะ ที่นี่มีอะไรน่าสนใจเยอะแยะไปหมด... ฉันก็เลยกลับมาช้าเพราะมัวไปเดินดูนู่นนี่อยู่น่ะค่ะ"
84303100200-10 = "ถ้าเป็นอย่างนั้นจริงๆ ก็ค่อยยังชั่วหน่อยนะ..."
84303100200-11 = "ไม่ต้องขอโทษหรอก... พวกเราก็ไม่ได้มาเพื่อสอดส่องคุณอยู่แล้ว"
84303100200-12 = "แต่ถ้าจะหายไปนานเกิน หรือรู้สึกเหมือนจะเกิดเรื่องอะไรขึ้นก็บอกพวกเรานะ"
84303100200-14 = "ฮุฮุ พวกคุณเป็นทั้งไกด์และต้องดูแลฉันด้วย นี่น่าจะเป็นงานยากแท้ๆ... แต่พวกคุณก็เอาใจใส่ฉันดีเลยนะคะ ขอบคุณค่ะ"
84303100200-15 = ""
84303100200-18 = "หืม...?"
84303100200-19 = ""
84303100200-21 = "(ริโอะติดต่อมาเหรอ...?)"
84303100200-22 = ""
84303100200-24 = "เอ๋ มีใครโทรมาอีกแล้ว... ขอโทษนะคะ ฉันขอตัวสักครู่"
84303100200-26 = "ไม่ต้องสนใจพวกเราหรอก"
84303100200-27 = "พวกเราจะอยู่ที่นี่กัน ไว้คุยโทรศัพท์เสร็จแล้วก็กลับมาหานะ"
84303100200-29 = "เข้าใจแล้วค่ะ เดี๋ยวฉันกลับมานะคะ"
