[translation]
84312101305-5 = ""
84312101305-6 = "เบอร์ติดต่อเหรอ? เอ่อ... จะไม่เป็นไรเหรอ?"
84312101305-7 = "ไม่ใช่ว่าฉันไม่สะดวกหรอก ก็แค่ไม่เคยมีใครมาขอเบอร์ติดต่อก่อนน่ะ..."
84312101305-8 = "หืม? จริงเหรอ? คาดไม่ถึงแฮะ เธอทั้งคูลและเท่ขนาดนี้ คิดว่าจะเป็นที่นิยมในหมู่เพื่อนซะอีก"
84312101305-9 = ""
84312101305-11 = ""
84312101305-12 = "ปะ... เป็นที่นิยมเหรอ!? ฉะ... ฉันเนี่ยนะ!?"
84312101305-13 = "ดะ... เดี๋ยวก่อน! ปกติเธอพูดอะไรแบบนี้ออกมาตรงๆ... ก็ได้งั้นเหรอ!?"
84312101305-14 = "ทำไมล่ะ...?? มันเป็นปัญหาตรงไหน?"
84312101305-15 = ""
84312101305-17 = ""
84312101305-19 = ""
84312101305-20 = "(อืม... พอจะรู้แล้วละ นักเรียนที่นี่ก็มีด้านที่แตกต่างกับนักเรียนของเราอยู่นิดหน่อยนะ)"
84312101305-21 = "(ซึ่งมันก็เป็นด้านที่ดีด้วย...)"
