[translation]
90001045-2 = ""
90001045-3 = "It's slowing down! Toki!"
90001045-4 = "Yes, Ms. Rio! Commencing attack!"
90001045-5 = ""
90001045-11 = ""
90001045-12 = "An effective hit! Although...we appear to have let it get away."
90001045-13 = "A tactical retreat. A shame that it escaped, yet again."
90001045-14 = ""
90001045-17 = ""
90001045-18 = "Fact: the retreat is to our advantage. We require time to assess and reorganize."
90001045-19 = "Geburah's signal...lost. It moves very efficiently. Oh, well."
90001045-20 = ""
90001045-21 = ""
90001045-22 = "..."
90001045-23 = ""
90001045-25 = ""
90001045-26 = ""
90001045-27 = ""
90001045-28 = "..."
90001045-29 = "Hello, Ms. Rio. That was an efficient entrance, in many ways. Excellent timing. "
90001045-30 = ""
90001045-32 = ""
90001045-33 = "But...are you okay, President Himari?"
90001045-34 = "I have completely, absolutely no idea why you feel the need to check on me, but I'm fine! I don't feel jealous in any way, shape, or form that a certain someone came in on a trail of blazing glory and stole the spotlight!"
90001045-35 = "Because I am benevolent! And generous! And kind! Do you understand, Eimi?!"
90001045-36 = "Yes. I understand that the president is sulking."
90001045-37 = "You slander as effortlessly as you breathe!"
90001045-38 = ""
90001045-40 = ""
90001045-41 = ""
90001045-42 = "Hmph. Let's begin with the most superficial greeting I can muster."
90001045-43 = "It's nice to see you again, Rio. How have you been?"
90001045-44 = ""
90001045-45 = ""
90001045-46 = "I..."
90001045-47 = "Did you not hear me say that we'll begin with a superficial greeting?"
90001045-48 = ""
90001045-50 = ""
90001045-51 = ""
90001045-52 = "[ns] \"You can start with a simple 'hello,' Rio.\""
90001045-53 = "Ah. Yes. Understood. Um..."
90001045-54 = "Hello. It's...nice to see you. How have you been? Um."
90001045-55 = "Yes. I sincerely return the sentiment, Ms. Rio. "
90001045-56 = "Have you been sleeping well? I hope you are not staying up all night and sleeping in until the afternoon."
90001045-57 = "?!"
90001045-58 = "Managing your circadian rhythm is the only thing that housekeeping robots cannot assist you with."
90001045-59 = "Th-That has been..."
90001045-60 = "I'm trying..."
90001045-62 = "(I believe I can visualize what Ms. Rio and Toki's life together was like.)"
90001045-63 = ""
90001045-65 = ""
90001045-66 = ""
90001045-67 = ""
90001045-68 = "Ahem! Should we inch our way over to the point now?"
90001045-69 = "To begin, you haven't returned to Millennium all this time. Where have you been hiding out?"
90001045-70 = "That's..."
90001045-71 = "Furthermore! A certain Seminar treasurer has quite a bit to say to you!"
90001045-72 = "?!"
90001045-73 = "I also simply cannot look past your dramatic reveal, at such a crucial moment at that."
90001045-74 = "Surely you weren't thinking..."
90001045-75 = "...\"I need to do something to justify my return. I can't show my face again unless I have something to offer.\""
90001045-76 = ""
90001045-78 = ""
90001045-79 = "...I was tracking down every clue I could find to the Nameless Gods' powers."
90001045-80 = "The Nameless Gods'...powers?"
90001045-81 = "Yes. It didn't simply disappear after it manifested on...that day. There were traces of it left all over Kivotos."
90001045-82 = "I wasn't expecting to run into you during my investigation."
90001045-83 = "(Her investigation into the Nameless Gods' powers...led her to Decagrammaton's prophets?)"
90001045-84 = ""
90001045-86 = ""
90001045-87 = "I'm still doing my utmost to prepare for and prevent the unknown phenomenon that could devastate Kivotos. That hasn't changed, not since I first established the Super Phenomenon Task Force."
90001045-88 = "I'm not charismatic or very skilled at social interactions. So I wanted to do what I'm able to do."
90001045-89 = "It was how I hoped...to find redemption."
90001045-90 = ""
90001045-91 = "..."
90001045-92 = "Fine. I can accept that. However!"
90001045-93 = "You simply offloaded the responsibilities of the Super Phenomenon Task Force on me and disappeared. You put me in a position where I couldn't refuse!"
90001045-94 = "Despite your dislike of me, I knew you would follow through."
90001045-95 = "...From a certain perspective, that could be seen as a threat!"
90001045-96 = "[s3] \"Now, now, let's not fight...\"\n[s4] \"We could have been in big trouble if Rio hadn't come, right?\""
90001045-99 = "...Yes. Even I can acknowledge that."
90001045-100 = "In fact, even outside of this incident, we all owe you a debt. In one form or another."
90001045-101 = "What I was really trying to say was to stop waffling with useless things like \"redemptions\" or \"justifications\" and just come back to Millennium..."
90001045-102 = "Huh? What was that? Did you say something?"
90001045-103 = "Forget it!"
90001045-104 = "However, the Super Phenomenon Task Force ended up fulfilling its role exactly as intended, Ms. Rio."
90001045-105 = "Yes. And I, excellent agent and perfect maid, also played my role perfectly."
90001045-106 = "...Toki aside, as the founder of the Super Phenomenon Task Force, how do you feel?"
90001045-107 = ""
90001045-109 = ""
90001045-110 = "I'm...still figuring that out."
90001045-111 = "I thought you would answer like that."
90001045-112 = "What I can say for certain is that the events occurring here are significant, and the ripples will spread far throughout Kivotos."
90001045-113 = "To summarize, you know things that we don't."
90001045-114 = "And I'm sure that, along that way, we've gathered data that you haven't."
90001045-115 = "So here is my proposal. An exchange of information. "
90001045-116 = "That is the logical conclusion. Shall we undertake that endeavor as we continue our pursuit of Geburah?"
90001045-117 = "I accept those terms. Eimi. Do you know the direction Geburah retreated to?"
90001045-118 = "Affirmative. I remember."
90001045-119 = "What are we waiting for? Let's move out, Sensei."
90001045-121 = "Next Episode;Variable"
