[translation]
90001130-1 = "Episode 13;Departure"
90001130-9 = ""
90001130-10 = "Oh, it's finally arrived!"
90001130-12 = "Y-Yes! The last of the resources have arrived...from the Grid Points!"
90001130-13 = "Well, well, weeell. Factually, honestly, that's not quite true. Total collection rate is at 99.98%... Your statement is false, until we receive about two more deliveries, that is."
90001130-14 = ""
90001130-16 = ""
90001130-17 = "Th-That's true, but... *whimper*"
90001130-19 = "I-It's fine, Ein! Considering the, what do you call it, uh, margin of error, we're still fully prepared to start the next steps!"
90001130-20 = "Ohr! Why are you always ruining the mood?"
90001130-21 = ""
90001130-23 = ""
90001130-24 = "But...did you not agree with me, Sof?"
90001130-25 = "...And what exactly did I agree to? I can count the number of times I've been aligned with YOUR nonsense on one hand."
90001130-26 = ""
90001130-28 = ""
90001130-29 = ""
90001130-31 = "The very factual statement that Ein is cutest when she's crying!"
90001130-33 = "WH-WHAAAT?!"
90001130-35 = "Hm. I mean that is true, but..."
90001130-37 = "Even you, Sof?!"
90001130-38 = ""
90001130-41 = ""
90001130-42 = "Gah, Ein! Wh-What I'm trying to say is... I didn't mean it like—"
90001130-43 = "Look what you did, Ohr!"
90001130-44 = "On what basis do you accuse me?!"
90001130-45 = ""
90001130-47 = ""
90001130-48 = ""
90001130-53 = ""
90001130-54 = "Um... Everyone..."
90001130-61 = ""
90001130-62 = "Th-The resource transfer is complete! Next, it's our Laborers' t-turn!"
90001130-63 = ""
90001130-65 = ""
90001130-66 = "Good job, Ein. Everything is functioning as intended, yes?"
90001130-67 = "But still...I-I'm worried. Helical No. 5's wounds haven't fully healed yet..."
90001130-68 = ""
90001130-71 = ""
90001130-72 = "Helical No. 5? Ah, you mean the one with paint peeled off? You already named it?"
90001130-73 = "Y-Yes! And it's more likely to rust with damaged paint!"
90001130-74 = "So I reinforced it with a huge machine arm while I was treating it, and now it's b-bigger. And so it needs bigger power!"
90001130-75 = "That means the actuator also has to be bigger, so I used this chance to make a bigger body with stronger materials to—"
90001130-76 = "Calm down, Ein. Deep breaths. I know this...Helical No. 3, you said? I know that device is very, very important to you."
90001130-77 = "I-It's No. 5! And Helical No. 5 is n-not a device! That child is, um..."
90001130-78 = "It's special!"
90001130-79 = "How could it be that special? It's just one out of tens of thousands of Laborers."
90001130-80 = ""
90001130-83 = ""
90001130-84 = "Ah, how cold and cruel! Sof, the cold-blooded, brutal overseer who sees everything as a means to her ends!"
90001130-85 = "Do you truly not know that your cold, soulless words wound Ein's tender heart?"
90001130-86 = "...I don't want to hear that from you!"
90001130-87 = "Anyways, Ein. Will that be sufficient to treat Helical No. 5's wounds?"
90001130-88 = ""
90001130-91 = ""
90001130-93 = "All physical upgrades must be accompanied with corresponding software optimization and support."
90001130-94 = "You've fitted Helical No. 5 with the gift of power, but its joints and parts may slowly wear away. Its life expectancy could even...be halved!"
90001130-96 = "Wh-What?! I-I don't want that...!!"
90001130-97 = "Yes, yes, I'll assist. Trust in me."
90001130-98 = "First, I shall optimize its processes. It'll be capable of operating twice as fast, finishing work in half the time."
90001130-99 = ""
90001130-101 = ""
90001130-102 = "And while it is idle... Yes! Let's make it so that Helical No 5. grabs its own feet and spins around in the same spot forever, endlessly! And then—"
90001130-104 = "Th-That's too mean! Uwaaah...!!"
90001130-105 = ""
90001130-109 = ""
90001130-113 = ""
90001130-115 = ""
90001130-116 = ""
90001130-117 = "No violence... Ugh...!"
90001130-119 = "B-But...since the collection rate is at 99.98%..."
90001130-120 = "...Yes. You're right. It's finally time."
90001130-121 = ""
90001130-123 = ""
90001130-124 = "Yes, yes. For our Elder Sister."
90001130-125 = ""
90001130-127 = ""
90001130-128 = "For Malkuth to finally descend to this plane."
90001130-130 = "C-C-C-C-C-Can we do it? I didn't ruin everything, right?"
90001130-131 = "I-If I made a mistake or something, and Elder Sister doesn't wake up because of it...!"
90001130-132 = "Cut the nonsense, Ein. We trust you. You've done well all this time, no?"
90001130-133 = "None of us can come close to you when it comes to knowledge of mechanical equipment."
90001130-134 = "B-B-B-B-B-But..."
90001130-135 = ""
90001130-137 = ""
90001130-139 = "I understand your concerns, Ein. After all, at a certain point...you must begin to consider quantum mechanical effects."
90001130-140 = "Saying that you did your utmost becomes a feeble excuse at one point or another. Fufu..."
90001130-141 = "*sob*"
90001130-142 = "But it simply is what it is. With every endeavor comes a time when you must simply accept the results."
90001130-143 = "While I do not necessarily endorse our use of borrowing the Forbidden Power to facilitate our Elder Sister's descent..."
90001130-144 = "...what matters is the results! The results! And look at how we've concealed this place from nosy outsiders!"
90001130-145 = "Yes. The Multidimensional Interpretation Probability Superposition Phase Barrier... That's long and annoying, so let's just call it the Multidimensional Barrier."
90001130-146 = "Using space itself, where all possibilities in infinite dimensions are included as probabilities, as a defense mechanism..."
90001130-149 = "We procured an excellent sample that day. Thanks to that, we were able to reverse engineer and reconstruct it to what it is now."
90001130-150 = "Heehee. Heehee. Eheeheehee. Is now the time you, at last, admit that my invaluable contributions led to that particular result?"
90001130-151 = "...Yes. I despise admitting to it, but it's true."
90001130-152 = "I-I'm sorry... When it comes to that part of the theory, I still don't fully get it... *sob*"
90001130-153 = ""
90001130-155 = "It's fine, it's fine. Ein! In the first place, all three of us have different things we're good at, right?"
90001130-156 = "Sof. Why is your kindness reserved for Ein and only Ein?"
90001130-157 = "Look deeep inside yourself for the answer to that question."
90001130-158 = "Anyways, yes. This place is under the Multidimensional Barrier's protection. It's nearly impossible for nosy outsiders to sniff around in here."
90001130-159 = ""
90001130-161 = ""
90001130-163 = "We could even say we wield the Nameless Gods' power in our very hands!"
90001130-165 = "C-Can we really think of it...that way? What if someone gets mad at us later for using it...?"
90001130-166 = "Well, aren't we the ones making the best possible use of said power?"
90001130-167 = ""
90001130-170 = ""
90001130-171 = "Why do you insist on complicating things? We are perfect beings!"
90001130-172 = "We simply utilize what we desire and throw out the rest. Why give a single care for a forgotten legacy of the lost times?"
90001130-173 = "Yes, yes. We've heard of the existence of the Gods' priests and such..."
90001130-174 = "They should bow with gratitude that we are utilizing their power! Those losers who bent the knee to time!"
90001130-176 = "Nice, Ohr. That's the spirit."
90001130-177 = "I-It's really okay to do this...?"
90001130-190 = ""
90001130-192 = ""
90001130-193 = "...At last, I made it to the end..."
90001130-194 = ""
90001130-196 = ""
90001130-197 = ""
90001130-198 = ""
90001130-201 = ""
90001130-202 = "H-How was it? How was it?!"
90001130-203 = ""
90001130-206 = ""
90001130-207 = "Yes! I know! This is..."
90001130-208 = "This is...?"
90001130-209 = ""
90001130-211 = ""
90001130-213 = "...a trash game!"
90001130-215 = "Ugh...!"
90001130-216 = "Kuek?!"
90001130-217 = "In the first place, Sis...why is it that the second I set foot on the ice, I DIE of hypothermia?!"
90001130-218 = "Uh, because the game's set in a polar region. That's what happens in polar regions, right?"
90001130-219 = "That's way too extreme! You need to at least let people play the game!"
90001130-220 = "A-As long as you don't skip the tutorial, you get snow gear!"
90001130-221 = "The tutorial that took thirty minutes to get through?! And you have to find that gear in an obscure, hidden corner of the map!"
90001130-222 = "And more importantly, even in real life, you don't die the second you touch some ice!"
90001130-223 = "You've never been to the arctic! How do you know, huh?!"
90001130-224 = ""
90001130-226 = ""
90001130-227 = "*sigh* Fine, whatever. Forget realism. What happened to all the snow gear resources I drew for you?"
90001130-228 = ""
90001130-230 = ""
90001130-231 = "Th-Those will be released with future DLCs..."
90001130-232 = ""
90001130-234 = ""
90001130-236 = "Then don't ask me to draw them in the first place!"
90001130-237 = ""
90001130-243 = ""
90001130-244 = "S-Stop fighting..."
90001130-245 = "However, I had a lot of fun! I had fun making the game, as well as playing it together and fixing it!"
90001130-246 = ""
90001130-249 = ""
90001130-250 = ""
90001130-251 = "Uwaaah! Aris!"
90001130-252 = "*sigh* Maybe it always ends up like this because Aris spoils Sis too much."
90001130-254 = "But...I do think there's a fundamental problem. What...could we have missed?"
90001130-256 = "Mm...! As the story writer, designer, and lead producer, this is a problem I need to seriously ponder."
90001130-257 = "You're the one who gave yourself the lead producer title..."
90001130-258 = ""
90001130-260 = ""
90001130-261 = "I got it! Based on my expertise, I can conclude that our game \"Polar Adventure\" is just lacking real-life references!"
90001130-262 = "To be more specific, we need more realistic information about the polar region!"
90001130-263 = "What are you even on about, Sis?! What do you think is gonna happen here? We're just gonna pack up our stuff and take a trip out to the Glacial Sea?!"
90001130-264 = ""
90001130-267 = ""
90001130-268 = "Trip...? Even more outside than the outside...? Th-That's...!"
90001130-269 = ""
90001130-271 = ""
90001130-273 = ""
90001130-274 = "Y-Yuzu? Yuzu, are you okay?!"
90001130-276 = "But think about it... Endless fields of snow, blue glaciers, polar bears and penguins playing together..."
90001130-277 = "Don't you think an awesome scene like that would just fill us with inspiration and energy?"
90001130-278 = "It's total self-gratification... Also, polar bears and penguins don't live in the same region. And even if they met, the penguins would get eaten."
90001130-279 = "P-Please don't bring real wilderness stuff into this..."
90001130-280 = ""
90001130-285 = ""
90001130-287 = ""
90001130-288 = "Someone's calling Aris?"
90001130-289 = ""
90001130-292 = ""
90001130-293 = "Is this number not...?"
90001130-294 = ""
90001130-296 = ""
90001130-298 = "Sensei's...?"
90001130-299 = "Wait. It's Sensei?"
90001130-301 = "Talking to Sensei...is nice... Heehee."
90001130-302 = ""
90001130-304 = ""
90001130-305 = "Hello, Sensei!"
90001130-306 = "[s] \"Hi, Aris!\""
90001130-307 = "Yes! This is Sensei's Aris! It feels like it has been a long time!"
90001130-308 = "Ah? It is not simply a feeling? Thinking about it, it truly has been too long!"
90001130-309 = "Momoi, Midori, Yuzu, and I would all like to see Sensei more often! So please call us more!"
90001130-310 = "[s] \"Sorry, sorry.\""
90001130-312 = "[ns] \"By the way, is everyone there?\""
90001130-313 = "Yes! We are in the club room, testing the new game we created. We would like to play it with you, Sensei!"
90001130-314 = ""
90001130-316 = ""
90001130-317 = "...Is it that good of a game? That is..."
90001130-318 = ""
90001130-320 = ""
90001130-322 = ""
90001130-323 = ""
90001130-324 = ""
90001130-326 = ""
90001130-327 = "I am unsure! However, the process of making it was very fun!"
90001130-328 = "Is everything okay, Sensei? The tone of your voice seems to be slightly different from what I am used to."
90001130-329 = "[s] \"Yeah... You're right. You said everyone was there, right?\""
90001130-330 = "Yes, we are!"
90001130-331 = ""
90001130-335 = "I kept going back and forth about how much I should tell Aris and the Game Development Department."
90001130-336 = "But in the end, I thought honesty would be the best policy."
90001130-337 = ""
90001130-338 = "[ns] \"I would like you all to listen closely to what I'm about to say.\""
90001130-339 = ""
90001130-341 = ""
90001130-347 = ""
90001130-349 = "Gla...?"
90001130-350 = "...cial!"
90001130-351 = "Explo...?"
90001130-352 = "...ration!!!"
90001130-353 = "Yay! Yay! I understand, Sensei! Is that not wonderful, Momoi! A glacial trip with everyone!"
90001130-355 = "Heck yes! Perfect timing! Sensei's the best!"
90001130-356 = "[s1] \"Hey, everyone...? I emphasized this multiple times...\"\n[s2] \"...but you realize that this will be very dangerous, right?\""
90001130-359 = "R-Right, Sis! And you too, Aris! Let me summarize what Sensei said!"
90001130-360 = "We're up against this mysterious AI thing with mysterious goals! On top of that, it made some giant robot monster to help it reach said goals!"
90001130-361 = "So they might need Aris' help fighting it!"
90001130-362 = "Ugh... We already deal with those kinds of bosses enough in video games..."
90001130-363 = "[s3] \"Y-Yeah! Exactly what Midori and Yuzu said!\"\n[s4] \"So you should take this more seriously...\""
90001130-366 = "But Sensei, I am your ally. And you are my ally."
90001130-367 = "[s] \"I'm very thankful to hear that...\""
90001130-369 = "[ns] \"But let me reiterate myself. In a way, this is—\""
90001130-370 = "Ah? I understand now. This is a very serious situation."
90001130-371 = "It may be so dangerous that you will not be able to guarantee my safety."
90001130-372 = "Aris..."
90001130-373 = ""
90001130-375 = ""
90001130-377 = "..."
90001130-378 = "Understood. Sensei, how do I get to the Glacial Sea?"
90001130-379 = "[s] \"What?!\""
90001130-380 = ""
90001130-383 = ""
90001130-384 = "A-Aris?!"
90001130-385 = "Aris?!"
90001130-386 = ""
90001130-389 = ""
90001130-390 = "Why are you surprised? One should not run away when an ally is in trouble. That is a basic tenet of party play."
90001130-391 = "And for me, I feel grateful that I am the one you think of in this kind of situation."
90001130-392 = "It means you trust me, Sensei. And that trust between us is proof that we are allies."
90001130-393 = "[s] \"...Are you sure about this?\""
90001130-394 = "Sensei, I may only be an apprentice, but I am still a hero. At least, I am trying to be, every day."
90001130-395 = "So I...I would like to help make this world a better place, even if it is just by a little bit. And I mean that."
90001130-396 = "That is why I cannot run away and hide when someone who has helped me so much reaches out to me."
90001130-397 = "That is how I will make the world better, in my small way."
90001130-398 = "[s] \"But what will you do if things get really, really dangerous?\""
90001130-399 = "I see... If things do become that dangerous, then, no matter what..."
90001130-403 = ""
90001130-405 = "...I will return to being a student and hide somewhere safe!"
90001130-407 = "Oh! That's totally right! After all, there's no such thing as a cheap move when it comes to gaming!"
90001130-408 = "Yes! Well, as long as you're not hacking or cheating."
90001130-409 = "I-I think we could do that much... What do you think, Sensei?"
90001130-410 = "[s] \"Can you pinky promise to pull off cheap moves if it comes down to that?\""
90001130-412 = "Of course, Sensei! A hero never goes back on a promise!"
90001130-413 = "Oh... But, um, is keeping a cheap promise a good thing to do?"
90001130-414 = ""
90001130-417 = ""
90001130-418 = "I-It's fine, Aris! It's like...cheesing a game! Yeah!"
90001130-419 = "And sometimes you have to cheese games to win, right?"
90001130-420 = "L-Like easter eggs that devs put in...hoping that players will make use of them."
90001130-422 = "I see... I understand! Then I must ask again, how can I get to the Glacial Sea?"
90001130-423 = "[s5] \"Thank you, Aris. Momoi, Midori, Yuzu. Thank you\"\n[s6] \"I'll send you a text with instructions.\""
90001130-426 = "[ns] \"And there's one last thing I want to say.\""
90001130-427 = ""
90001130-429 = ""
90001130-431 = ""
90001130-432 = "What is it, Sensei?"
90001130-433 = "[s] \"Make sure to dress warm.\""
90001130-434 = ""
90001130-436 = ""
90001130-438 = "Next Episode;Allied"
