[translation]
90000100-1 = "#title;제11화;케테르 공략"
90000100-2 = "3;히마리;S2_03;준비되셨죠, 여러분?\n#3;sig\n#3;a"
90000100-3 = "1;에이미;05;응. 준비 완료.\n#1;em;[반응]\n#1;a\n#3;m5"
90000100-4 = "3;히마리;S2_99;곧 케테르가 이쪽으로 올 거예요. 조우 즉시 준비한 대로 작전을 실행, 녀석과 전투를 시작합니다.\n#3;sig"
90000100-5 = "3;히마리;S2_05;계획이 성공한다면 케테르를 최소 12시간 동안은 무력화시킬 수 있을 거예요.\n#3;sig"
90000100-6 = "1;에이미;02;그러면 우리는 케테르가 지키고 있던 폐허의 <연구지구>로 진입하는 거고."
90000100-7 = "3;히마리;S2_03;네. 그렇죠.\n#3;sig"
90000100-8 = "#st;[0,0];instant;1;"
90000100-11 = "3;히마리;S2_11;케테르가 오고 있네요. 그럼, 작전 시작합니다!\n#3;sig"
90000100-12 = "[s] \"좋아. 해보자고.\""
