[translation]
90001100-1 = "ตอนที่ 10;มรดกแห่งทวยเทพไร้นาม"
90001100-2 = "เราติดตามร่องรอยของชอกมาห์ในธารน้ำแข็งจนมาถึงที่นี่ และได้รู้ว่าชอกมาห์กำลังทำอะไรอยู่ในเขต#nภูเขาไฟแห่งนี้..."
90001100-3 = "และค้นพบด้วยว่ามีการเก็บสะสมทรัพยากร และอาจมีการลำเลียงไปที่ไหนสักแห่งค่ะ"
90001100-4 = "ใช่ มีการสร้างรางสำหรับขนส่งกันที่นั่นเลยด้วย ทรัพยากรต้องถูกส่งไปที่ไหนอยู่แน่ๆ ฉันมองว่ารอบๆ นั่นก็ต้องมีอะไรหลงเหลืออยู่"
90001100-5 = "ถ้าอย่างนั้นฉันจะไปสำรวจให้เองค่ะ ให้ฉันไปได้ใช่มั้ยคะ? ท่านริโอะ หัวหน้าฮิมาริ?"
90001100-6 = "อืม ฝากด้วยนะ โทคิ"
90001100-7 = ""
90001100-9 = ""
90001100-10 = ""
90001100-11 = ""
90001100-13 = ""
90001100-14 = "ให้ฉันไปช่วยอีกแรงมั้ย?"
90001100-15 = "ไม่ต้องหรอกค่ะ ฉันมีเรื่องอื่นที่อยากขอให้เอมิช่วยทำน่ะค่ะ"
90001100-16 = "เรื่องอะไรเหรอ?"
90001100-17 = "วิเคราะห์สิ่งที่หลงเหลือจากฐานปฏิบัติการของเดคาแกรมมาทอนที่อยู่แถวนี้น่ะค่ะ"
90001100-18 = "จะให้ฉันไปรวบรวมตัวอย่างมาเพิ่มสินะ"
90001100-19 = "ถูกต้องเลยค่ะ ยิ่งเรามีตัวอย่างมากเท่าไรก็ยิ่งดีค่ะ"
90001100-20 = ""
90001100-22 = ""
90001100-23 = ""
90001100-24 = ""
90001100-25 = ""
90001100-26 = ""
90001100-27 = "คิดจะทำอะไรเหรอคะ ริโอะ...?"
90001100-29 = ""
90001100-30 = "หืม? เมื่อกี้บอกว่าจะเก็บตัวอย่างเพิ่มไม่ใช่เหรอ?"
90001100-31 = "ก็เลย... จะช่วยเหรอคะ?"
90001100-32 = "ฉันว่าไม่จำเป็นต้องพูดถึงขนาดนั้นหรอก..."
90001100-33 = "ก็ดีค่ะ ถ้าอย่างนั้นก็รีบทำให้เสร็จดีกว่าค่ะ เริ่มกันเลยมั้ยคะ?"
90001100-34 = "[s] \"ถึงจะพูดจาไม่ค่อยถูกคอกันสักเท่าไร...\""
90001100-35 = ""
90001100-37 = ""
90001100-38 = "[ns] \"แต่ก็ดูสนิทกันดีนะ!\""
90001100-39 = "ไม่สักนิดเลยค่ะ!"
90001100-40 = "มองผิดแล้วละ ครู"
90001100-44 = ""
90001100-45 = ""
90001100-46 = "เก็บตัวอย่างมาได้ประมาณนี้พอแล้วยัง หัวหน้า?"
90001100-47 = "ค่ะ เท่านั้นก็เพียงพอแล้วค่ะ เอมิ ส่วนเรื่องวิเคราะห์... ก็ใกล้จะเสร็จแล้วค่ะ ส่งผลลัพธ์ได้ปกติมั้ยคะ ริโอะ?"
90001100-48 = "ทางนี้ไม่มีปัญหา ฉันเองก็น่าจะได้ข้อสรุปแล้วเหมือนกัน"
90001100-49 = "ฉันอยากฟังดูบ้างแล้วค่ะ ช่วยบอกข้อสรุปหน่อยสิคะ"
90001100-50 = "ฉันคิดว่านี่เป็นเรื่องสำคัญ มันเป็นสิ่งที่ค้นพบได้จากสถานที่จริงน่ะ..."
90001100-51 = "ที่นี่มีร่องรอยของการสร้างวัตถุใหม่"
90001100-52 = "แน่นอนค่ะ และพวกเราก็เคยได้เผชิญหน้ากับพลังนี้มาแล้วค่ะ"
90001100-53 = "[s] \"หืม? เคยด้วยเหรอ?\""
90001100-54 = "ค่ะ คุณครู จำเรืออะทราฮาซิส... ได้มั้ยคะ?"
90001100-55 = "เรื่องที่เกิดขึ้นกับอาริสึ... และเด็กที่ชื่อว่าเคย์... น่ะค่ะ"
90001100-56 = ""
90001100-58 = ""
90001100-67 = "[ns] \"อ๋อ...!\""
90001100-68 = ""
90001100-69 = "ใช่แล้วละ ครู"
90001100-70 = "ค่ะ ใช่แล้วค่ะ"
90001100-71 = "การสร้างวัตถุใหม่คือหนึ่งในพลังของทวยเทพไร้นาม"
90001100-72 = "เราไม่รู้เกี่ยวกับตัวตนหลักของชอกมาห์ เพราะว่ามันไม่มีทางตรวจสอบได้ แต่อย่างน้อยอุปกรณ์เก็บ#nทรัพยากรและขนส่งในเขตทุนดรา และบางทีกองกำลังนั่น..."
90001100-73 = "ค่ะ สิ่งเหล่านั้นอาจจะเกิดจากการใช้พลังของทวยเทพไร้นาม... ในการสร้างวัตถุขึ้นมาใหม่ค่ะ"
90001100-74 = "และจากตรงนี้ สมมติฐานของเราก็เกือบมาถึงขั้นที่แน่นอนแล้วค่ะ"
90001100-75 = "[s] \"ขั้นที่แน่นอนเหรอ?\""
90001100-76 = "ค่ะ ฉันว่าเราปะติดปะต่อจิ๊กซอว์ทั้งหมดได้แล้วค่ะ และนั่นก็คือ..."
90001100-77 = ""
90001100-79 = ""
90001100-80 = ""
90001100-83 = ""
90001100-84 = "อะซุมะ โทคิกลับมาแล้วค่ะ ขอรายงานค่ะ"
90001100-85 = "ฉันได้ไปตรวจสอบทางรถไฟที่สร้างอย่างฉุกละหุกจากเขตภูเขาไฟ และพบว่ามีกองกำลังป้องกัน#nกองเล็กๆ หลงเหลืออยู่ประปรายค่ะ"
90001100-86 = "[s] \"อื้อ ทำได้ดีมาก โทคิ\""
90001100-87 = "ค่ะ แน่นอนอยู่แล้วค่ะ คุณครูต้องชื่นชมฉันอย่างกระตือรือร้นและเด็ดเดี่ยวกว่านี้หน่อยนะคะ"
90001100-88 = ""
90001100-90 = ""
90001100-92 = ""
90001100-93 = "อย่างเช่นลูบหัว กอดเบาๆ หรือโอบเอว อะไรประมาณนี้ค่ะ"
90001100-94 = ""
90001100-95 = ""
90001100-96 = "คุณครู? ทำไมจู่ๆ ก็เหวอไปขนาดนั้นล่ะคะ?"
90001100-97 = "โทคิ...?"
90001100-99 = ""
90001100-100 = "ปล่อยไปเถอะ ประธาน ฉันไม่รู้ว่าโทคิเปลี่ยนไป หรือว่านี่คือธรรมชาติที่แท้จริงของโทคิกันแน่ แต่ก็อย่างที่เห็นนั่นละ ตอนนี้โทคิเป็นอย่างนี้แล้ว"
90001100-101 = "มาคุยกันต่อเถอะค่ะ... คุณครู"
90001100-102 = "[s] \"อะ... อื้อ! ที่บอกว่าปะติดปะต่อจิ๊กซอว์ได้คืออะไรเหรอ?\""
90001100-103 = "เมินฉันกันเหรอคะ..."
90001100-104 = "ก่อนที่ชมรมปรากฏการณ์ลี้ลับจะมาถึงธารน้ำแข็ง เราเผชิญหน้ากับผู้เลื่อมใสของเดคาแกรมมาทอน#nมาแล้ว 3 ตน ก็คือบีนาห์ เชเซ็ด และ HOD..."
90001100-105 = "3 ผู้เลื่อมใสนี้ไม่มีส่วนเกี่ยวข้องใดๆ กับพลังของทวยเทพไร้นามเลยค่ะ"
90001100-106 = "แต่กับเกวูราห์และชอกมาห์ที่เราเจอหลังจากมาถึงธารน้ำแข็งนั้น ล้วนมีร่องรอยจากพลังของทวยเทพ#nไร้นามค่ะ"
90001100-107 = "ภาพเหตุการณ์เหนือจริงที่เป็นเรือที่ลอยอยู่บนลาวา... ก็อาจจะมีส่วนเกี่ยวข้องกับสิ่งนั้นก็ได้ค่ะ"
90001100-108 = "[s1] \"ผู้เลื่อมใสของเดคาแกรมมาทอนใช้พลังของทวยเทพไร้นามสินะ\"\n[s2] \"ใช้พลังของทวยเทพไร้นามกันนี่เอง?\""
90001100-111 = "ใช่ค่ะ นี่คือข้อเท็จจริงเลยค่ะ"
90001100-112 = "แต่ปัญหาก็คือ พวกนั้นใช้พลังที่ว่าเพื่ออะไรกันแน่..."
90001100-113 = ""
90001100-116 = "ริโอะ??!! นี่มัน...?!"
90001100-117 = "อืม ทางฉันก็ตรวจสอบได้เหมือนกัน"
90001100-118 = ""
90001100-120 = ""
90001100-121 = ""
90001100-123 = "มีเรื่องอะไรเหรอ หัวหน้า? เกิดอะไรขึ้นเหรอ?"
90001100-124 = "ค้นพบอะไรเหรอคะ? ท่านริโอะ? บอกพวกเราด้วยสิคะ..."
90001100-125 = ""
90001100-127 = ""
90001100-128 = ""
90001100-129 = ""
90001100-130 = ""
90001100-131 = ""
90001100-132 = ""
90001100-133 = ""
90001100-134 = ""
90001100-135 = ""
90001100-136 = ""
90001100-137 = ""
90001100-138 = "ฉันบอกให้เองค่ะ ถ้าอยู่ในระดับนี้ละก็... ถือว่าเป็นสถานการณ์ฉุกเฉินครั้งใหญ่เลยค่ะ"
90001100-139 = "สรุปเลยก็คือ นี่คือสัญญาณของผู้เลื่อมใสตนใหม่"
90001100-140 = "แต่สัญญาณแตกต่างกับที่ผ่านมาทั้งหมด..."
90001100-141 = ""
90001100-143 = ""
90001100-145 = "เป็นสัญญาณที่รุนแรงอย่างน่าเหลือเชื่อเลยค่ะ"
90001100-147 = "ตอนต่อไป;ทางตัน"
