[translation]
90100020-1 = "ตอนที่ 2;ช่วงเวลาของยอดคนกับจิ้งจอก"
90100020-5 = ""
90100020-6 = "ร้อน~ จัง~"
90100020-7 = "ทำไมอากาศถึงร้อนขนาดนี้แล้วนะ? ยังเหลืออีกตั้งหลายเดือนกว่าจะถึงฤดูร้อนแท้ๆ"
90100020-8 = "อีกอย่าง สนามกีฬาของสำนักควบคุมก็แย่สุดๆ ไปเลย นอกจากจะมีไอร้อนแผ่ขึ้นมาเต็มๆ แล้ว ยังไม่มีร่มเงาให้ไปหลบแดดเลยด้วย..."
90100020-9 = "หรือว่าสำนักควบคุมจะเสียดายเงินจนไม่ยอมติดหลังคากันแดดให้พวกนักโทษนะ?"
90100020-10 = ""
90100020-12 = ""
90100020-13 = ""
90100020-14 = "เหตุผลน่าจะเพราะไม่อยากให้นักโทษพ้นสายตาของผู้คุมมากกว่านะ"
90100020-15 = "ถ้ามีสิ่งก่อสร้างที่ทำให้เกิดเงา ก็จะเกิดจุดบอดที่ผู้คุมมองไม่เห็น และถ้ามีใครวางแผนหลบหนีออกมา#nจากที่นั่นละก็ คงเป็นเรื่องใหญ่เลยใช่มั้ยล่ะ"
90100020-16 = "ได้ยินมาว่าก่อนที่วาคาโมะจะแหกคุกออกไป มีผู้สมรู้ร่วมคิดแอบเอาอุปกรณ์สำหรับใช้ในการหลบหนี#nมาส่งให้เธอที่หลังร่มเงาของต้นไม้ด้วย"
90100020-17 = "อึก... ฉันไม่ถูกชะตายัยนั่นตั้งแต่แรกเห็นเลย"
90100020-18 = "ตอนจับตัวได้น่าจะสั่งสอนให้เข็ดหลาบไปเลย จะได้ไม่คิดแหกคุกอีกเป็นครั้งที่สอง!"
90100020-19 = ""
90100020-22 = ""
90100020-23 = "ใจเย็นๆ ก่อน คุรุมิ ตามหลักแล้ว จะใช้กำลังเกินกว่าเหตุกับผู้ต้องสงสัยไม่ได้นะ"
90100020-24 = "ฉันก็รู้อยู่หรอก... แต่พอตอนนี้มาติดแหง็กอยู่ในสำนักควบคุมเอง เรื่องที่เคยเกิดขึ้นก่อนหน้านี้ก็เลย#nผุดขึ้นมาในหัว เลยยิ่งหงุดหงิดเข้าไปใหญ่"
90100020-25 = "จะว่าไป... แล้วนิโกะไม่ร้อนเหรอ? ระหว่างที่วิ่งด้วยกัน ดูเหมือนเหงื่อไม่ออกสักหยดเลยนะ"
90100020-26 = "ก็ไม่รู้สิ สงสัยเพราะฉันไม่ได้เป็นคนขี้ร้อน อากาศวันนี้ก็เลยเย็นสบายสำหรับฉันนะ"
90100020-27 = "แปลกจัง... เราได้รับการฝึกให้รับมือกับอากาศร้อนมาเหมือนกันแท้ๆ แต่ทำไมความสามารถในการ#nทนความร้อนของเราถึงต่างกันได้ขนาดนี้ล่ะ?"
90100020-28 = "หรือสุดท้ายแล้วมันเป็นเรื่องของพื้นฐานร่างกายที่ติดตัวมาตั้งแต่เกิดมากกว่ากัน?"
90100020-29 = "ไม่รู้สิ เป็นเพราะ 'อันนั้น' ของคุรุมิเล็กกว่าของนิโกะหรือเปล่า? "
90100020-30 = "อะไรของฉันที่เล็กงั้นเหรอ!"
90100020-31 = "หูไงล่ะ หู#nคิดอะไรอยู่เนี่ย...?"
90100020-32 = "ว่ากันว่าส่วนปลายของร่างกายจะตอบสนองต่อการเปลี่ยนแปลงของอุณหภูมิได้ดีไม่ใช่เหรอ?"
90100020-33 = "นิโกะมีหูสัตว์ที่ใหญ่ ก็เลยน่าจะระบายความร้อนได้ง่ายน่ะ"
90100020-34 = "ก็จริงนะ... พออากาศร้อนๆ แบบนี้ ฉันรู้สึกว่าหูจะร้อนเร็วกว่าส่วนอื่นของร่างกายเลยละ"
90100020-35 = "แต่พอเป็นฤดูหนาว หูก็เย็นง่ายจนปวดหู ทำให้ทำกิจกรรมกลางแจ้งลำบากเหมือนกัน"
90100020-36 = "งั้นเหรอ... ถ้ามันมีความแตกต่างกันขนาดนั้น ก็คงช่วยไม่ได้สินะ"
90100020-37 = "แต่ยังไงฉันก็ชอบฤดูหนาวมากกว่าฤดูร้อนนะ ฤดูร้อนทีไร เหงื่อชอบออกตรงหน้าอกจนรำคาญทุกที"
90100020-38 = ""
90100020-40 = ""
90100020-41 = ""
90100020-42 = "ชิ..."
90100020-43 = "เมื่อกี้เธอจิ๊ปากใช่มั้ย!"
90100020-44 = "เปล่าสักหน่อย"
90100020-45 = "โกหก! เมื่อกี้ทำเสียงเหมือนจิ๊ปากไม่ใช่เหรอ!"
90100020-46 = ""
90100020-48 = ""
90100020-49 = ""
90100020-50 = "ยูกิโนะยังวิ่งอยู่เลยนะ..."
90100020-51 = "ยูกิโนะ จะวิ่งต่ออีกนานแค่ไหนน่ะ? ใกล้จะหมดเวลาออกกำลังกายแล้วนะ..."
90100020-52 = ""
90100020-54 = ""
90100020-56 = ""
90100020-57 = ""
90100020-58 = "ขอฉันวิ่งต่ออีกรอบหนึ่ง เสร็จแล้วเดี๋ยวเข้าไป..."
90100020-59 = ""
90100020-61 = ""
90100020-62 = ""
90100020-63 = "จะว่าไป ตั้งแต่มาที่สำนักควบคุม ยูกิโนะก็แทบไม่ได้คุยกับพวกเราเลยนะ เอาแต่หมกมุ่นกับการออกกำลังกายทั้งวันเลย"
90100020-64 = "มีเรื่องอะไรที่อยากคิดคนเดียวหรือเปล่านะ?"
90100020-71 = ""
90100020-72 = "ก็คงเยอะแหละ..."
90100020-73 = "ก็จริงอยู่หรอก..."
90100020-74 = "ออกกำลังกายเยอะๆ มันก็ดีอยู่หรอก แต่หวังว่าจะไม่หักโหมจนไปทำลายสุขภาพของตัวเองนะ..."
90100020-77 = ""
90100020-78 = ""
90100020-79 = "(แค่ใช้ชีวิตอยู่ที่นี่ไปวันๆ คงไม่อาจชดใช้ความผิดที่ฉันก่อไว้ได้)"
90100020-80 = "(การจะเป็นผู้ใหญ่ที่มีความรับผิดชอบ เราต้องเรียนรู้ให้มากขึ้น พยายามให้หนักขึ้น และไว้วางใจผู้อื่นมากขึ้น)"
90100020-81 = "(แต่ว่า...)"
90100020-83 = "พวกเธอต้องรับผิดชอบต่อการตัดสินใจของตัวเองสิ!"
90100020-84 = "นี่น่ะเหรอปฏิบัติการเพื่อชาวเมือง? ฉันต่างหากที่เป็นฝ่ายเสียหายจากปฏิบัติการครั้งนั้น!"
90100020-85 = ""
90100020-87 = "ทำไมต้องเป็นฉันคนเดียวที่ต้องเสียสละ? แล้วทำไมฉันถึงต้องเป็นข้อยกเว้นนั้นด้วย?!"
90100020-88 = "ถ้าปล่อยให้เกิดเรื่องไปซะตั้งแต่แรกก็คงจะดีกว่า..."
90100020-89 = ""
90100020-91 = "ฉันไม่มีอะไรจะคุยกับพวกเธอ! ไปเรียกคนที่ตำแหน่งสูงกว่านี้มา! ฉันจะคุยกับคนที่รับผิดชอบเรื่องนี้ได้!"
90100020-92 = ""
90100020-93 = "(จนถึงตอนนี้ก็ยังไม่รู้เลยว่า... ตอนนั้นที่ฉันต้องเลือก ฉันควรเลือกทำแบบไหนถึงจะถูกต้อง)"
90100020-94 = "(เรื่องนี้จะคลี่คลายได้เองเมื่อเวลาผ่านไปอย่างที่คุณครูบอกหรือเปล่านะ?)"
90100020-95 = "(หรือว่าพลังนี้จะเป็นภาระหนักอึ้งที่มีเพียง[ruby=ประธานองค์การนักเรียน]ยอดคน[/ruby]เท่านั้นที่สามารถแบกรับได้)"
90100020-96 = "หมายเลข 5... 5020..."
90100020-97 = "ผะ... ผู้ต้องขังหมายเลข 5020...!"
90100020-98 = ""
90100020-99 = "หัวหน้าสำนักควบคุมกำลังเรียกใครอยู่น่ะ?"
90100020-100 = "นั่นหมายเลขของยูกิโนะไม่ใช่เหรอ?"
90100020-101 = "ยูกิโนะ หัวหน้าสำนักควบคุมเรียกเธออยู่นะ?"
90100020-104 = ""
90100020-105 = "ขอโทษนะคะ... ยูกิโนะ ฉันรู้ว่าคุณยังไม่ชินกับการเรียกด้วยหมายเลข แต่นี่เป็นระเบียบของสำนักควบคุมน่ะค่ะ"
90100020-106 = "ขอโทษที่เสียมารยาทค่ะ... เมื่อกี้ฉันเอาแต่โฟกัสกับการออกกำลังกาย"
90100020-107 = "มีเรื่องอะไรเหรอคะ?"
90100020-108 = "มีคำขอเข้าเยี่ยมค่ะ ช่วยไปเปลี่ยนเป็นชุดสะอาดๆ แล้วกลับมาตอนนี้เลยได้มั้ยคะ?"
90100020-109 = "มาเยี่ยมเหรอคะ...? แต่เท่าที่ฉันรู้ วันนี้หมดเวลาเยี่ยมแล้วนี่คะ"
90100020-110 = "มันก็จริงอยู่หรอกค่ะ แต่นี่ไม่ใช่การขอเข้าเยี่ยมทั่วไปน่ะค่ะ..."
90100020-111 = ""
90100020-113 = ""
90100020-114 = "ประธานองค์การนักเรียนอยากพบคุณค่ะ..."
90100020-115 = "ประธานองค์การนักเรียน...?"
90100020-119 = ""
90100020-120 = "ขอโทษที่ถามซ้ำอีกครั้งนะคะ..."
90100020-121 = "ประธานองค์การนักเรียนที่หายตัวไป กลับมาแล้วจริงๆ เหรอคะ?"
90100020-122 = "ค่ะ ประธานองค์การนักเรียนกลับมาอย่างกะทันหันโดยไม่บอกล่วงหน้า ที่สถาบันฝึกตำรวจวัลคิรี่ก็เลย#nเกิดความวุ่นวายเล็กๆ อยู่พักหนึ่ง..."
90100020-123 = "แต่ก็ต้องขอบคุณที่ท่านช่วยสะสางงานที่คั่งค้างได้อย่างรวดเร็ว ปัญหาหลายอย่างที่ค้างคามาตลอด#nก็เลยได้รับการแก้ไขค่ะ"
90100020-124 = "ถ้าเป็นแบบนี้ต่อไป สำนักควบคุมเองก็คงมีโอกาสพัฒนาในหลายๆ ด้านเหมือนกัน..."
90100020-125 = ""
90100020-127 = ""
90100020-128 = "(ถ้าจู่ๆ จะกลับมาแบบนี้ แล้วทำไมพวกเราถึง...)"
90100020-129 = "มะ... ไม่ใช่แค่สำนักควบคุมหรอกนะคะ แน่นอนว่าสถาบันฝึกตำรวจวัลคิรี่ก็ยังมีหน่วยงานอื่นที่ต้อง#nพัฒนาเหมือนกันค่ะ ควรเริ่มตั้งแต่หัวหน้าสำนักป้องกันเลย..."
90100020-130 = ""
90100020-132 = ""
90100020-133 = "อ๊ะ ขอโทษค่ะ ฉันเผลอพูดออกไปจนได้..."
90100020-134 = "ไม่หรอกค่ะ"
90100020-135 = ""
90100020-143 = "ท่านประธานองค์การนักเรียนคะ ฉันพายูกิโนะ... ไม่สิ พาผู้ต้องขังหมายเลข 5020 มาแล้วค่ะ"
90100020-144 = "ค่ะ เชิญเข้ามาเลยค่ะ"
90100020-145 = "(เสียงไม่คุ้นเลย...)"
90100020-146 = "(ไม่สิ จะบอกว่าไม่คุ้นก็คงไม่ถูก... ฟังแล้วรู้สึกแปลกๆ เหมือนไม่ใช่เสียงของประธานองค์การนักเรียน#nอย่างนั้นละ)"
90100020-147 = "(เสียงของประธานองค์การนักเรียนที่ฉันจำได้เป็นยังไงนะ?)"
90100020-148 = "(หน้าตาเป็นยังไง... ก็นึกไม่ออกแล้วด้วย)"
90100020-149 = ""
90100020-153 = ""
90100020-154 = "สำนักงานประธานองค์การนักเรียน"
90100020-155 = ""
90100020-156 = ""
90100020-157 = "ไม่ได้เจอกันนานเลยนะคะ หัวหน้ากองยูกิโนะ"
90100020-158 = ""
90100020-160 = ""
90100020-161 = "คุณคือ..."
90100020-162 = ""
90100020-164 = ""
90100020-165 = ""
90100020-166 = ""
90100020-167 = ""
90100020-169 = "ประธานองค์การนักเรียน..."
90100020-170 = "ไม่ได้เจอกันนาน รู้สึกว่าบุคลิกของคุณเปลี่ยนไปเยอะเลยนะคะ"
90100020-171 = "งั้นเหรอคะ? ช่วงนี้ฉันได้ยินเรื่องแบบนี้บ่อยเลยค่ะ"
90100020-172 = "คงเป็นเพราะฉันไม่ได้อยู่ปฏิบัติหน้าที่เสียนาน เลยทำให้รู้สึกแบบนั้นน่ะค่ะ"
90100020-173 = ""
90100020-175 = ""
90100020-176 = ""
90100020-177 = "เชิญนั่งก่อนสิคะ เราต้องคุยกันอีกยาวเลยค่ะ"
90100020-179 = "ฉันได้รับรายงานเกี่ยวกับทุกสิ่งที่เกิดขึ้นในระหว่างที่ฉันไม่อยู่แล้วค่ะ"
90100020-180 = "ได้ยินว่าหัวหน้าสำนักป้องกันคายะพยายามก่อการปฏิวัติโดยอาศัยกำลังของกองทหาร FOX เหรอคะ"
90100020-181 = "ใช่ค่ะ..."
90100020-182 = "ไม่เป็นไรค่ะ ฉันไม่ได้จะตำหนิหัวหน้ากองยูกิโนะหรอกค่ะ"
90100020-183 = "ที่จริงแล้ว... ฉันต้องขอโทษพวกคุณทุกคนมากกว่าค่ะ"
90100020-184 = "ฉันหายตัวไปกะทันหันโดยไม่บอกกล่าวล่วงหน้า คิโวทอสจึงเกิดเหตุการณ์ต่างๆ มากมาย ทำให้หลายคนต้องตกอยู่ท่ามกลางความสับสนไปด้วย"
90100020-185 = "แม้ว่าระหว่างนี้จะมีใครตัดสินใจอะไรผิดพลาด... ฉันก็ไม่อาจตำหนิคนคนนั้นได้หรอกค่ะ"
90100020-187 = "ก็มันเป็นความผิดพลาดของฉันเองนี่คะ..."
90100020-188 = ""
90100020-189 = "ฉันละอายจริงๆ ค่ะ..."
90100020-190 = "ฉันรู้สึกเสียใจเป็นพิเศษกับทุกคนในสถาบันพิเศษ SRT ค่ะ"
90100020-191 = "เพราะฉันไม่อยู่ ก็เลยเกิดข้อถกเถียงเกี่ยวกับอำนาจในการควบคุมปฏิบัติการของ SRT จนสุดท้ายก็ลงเอยด้วยการยุบสถาบันไป..."
90100020-192 = "ทางนั้นชื่อว่ากองทหาร RABBIT หรือเปล่านะคะ..."
90100020-193 = "นักเรียนชั้นปีที่ 1 ที่เพิ่งเข้าเรียนได้ไม่นาน ก็ยังต้องเผชิญกับประสบการณ์น่าเจ็บปวด เพราะเรื่องนี้สินะคะ"
90100020-194 = "ฉันจะเร่งสะสางงานขององค์การนักเรียนให้เรียบร้อย แล้วจะพยายามฟื้นฟูสถาบันพิเศษ SRT ขึ้นมาอีกครั้ง เพื่อให้ทุกคนได้รับการศึกษาที่ดีที่สุดค่ะ"
90100020-195 = ""
90100020-197 = ""
90100020-198 = "ถ้าช่วยทำอย่างนั้นให้ ฉันก็คงไม่มีอะไรจะขอไปมากกว่านี้แล้วค่ะ"
90100020-199 = "แต่ว่า..."
90100020-200 = "ความเสียหายที่พวกคุณก่อขึ้นต่อชาวเมืองก็ไม่ได้หายไปค่ะ"
90100020-201 = "การทำลายโครงสร้างพื้นฐาน การลอบยิงกรรมการองค์การนักเรียน และการพยายามจุดระเบิด#nกลางเมืองเพื่อก่อการปฏิวัติ ถือเป็นอาชญากรรมร้ายแรงอย่างชัดเจน"
90100020-202 = "ถ้าฉันนิรโทษกรรมให้ด้วยเหตุผลส่วนตัว ก็อาจช่วยบรรเทาความรู้สึกผิดของตัวเองได้ แต่ความไว้วางใจจากชาวเมืองที่สูญเสียไป ก็ยิ่งไม่มีวันได้กลับคืนมาค่ะ"
90100020-203 = "เพื่อฟื้นฟูเจตนารมณ์ดั้งเดิมของ SRT เรื่องนี้ไม่อาจมองข้ามไปได้ ฉันเลยอยากขอความเข้าใจใน#nเรื่องนี้จากทุกคนด้วยค่ะ"
90100020-204 = "ตั้งแต่วินาทีที่ก่อความผิด ฉันก็ตั้งใจไว้แล้วว่าจะยอมรับบทลงโทษ ไม่ว่ามันจะหนักหนาสักแค่ไหนก็ตามค่ะ"
90100020-205 = "แต่ว่า... สมาชิกคนอื่นก็แค่ปฏิบัติตามคำสั่งของฉันอย่างเคร่งครัดในฐานะหัวหน้ากองค่ะ"
90100020-206 = "ต่อให้ต้องลงโทษฉันหนักกว่านี้ก็ไม่เป็นไร แต่ช่วยละเว้นการเอาผิดสมาชิกคนอื่นในกองจะได้มั้ยคะ?"
90100020-207 = "ยูกิโนะ... การพยายามแบกรับความรับผิดชอบทั้งหมดไว้คนเดียวเป็นหนึ่งในข้อเสียของคุณค่ะ"
90100020-208 = "ผลลัพธ์ทุกอย่างบนโลกนี้ไม่ได้เกิดจากสาเหตุเพียงข้อเดียว ปัญหาของสังคมก็เหมือนกันค่ะ เราไม่อาจโยนความรับผิดชอบให้คนคนเดียวได้หรอกค่ะ"
90100020-209 = "ความเป็นจริงในวันนี้เป็นผลลัพธ์จากการที่ทุกคนแบกรับความรับผิดชอบในส่วนของตัวเอง และทำหน้าที่ของตนอย่างเต็มที่ค่ะ"
90100020-210 = "แน่นอนว่าตัวฉันเองก็หลุดพ้นจากพันธนาการแห่งความรับผิดชอบนั้นไม่ได้..."
90100020-211 = "เพราะงั้นทุกคนจึงต้องร่วมกันรับผลของเหตุการณ์ครั้งนี้ค่ะ"
90100020-212 = ""
90100020-214 = ""
90100020-215 = ""
90100020-216 = "ในอดีตเคยมีเหตุการณ์ที่ระหว่างปฏิบัติการ เราล้มเหลวในการรับมือกับผู้ต้องสงสัยก่อการร้าย ทำให้ชาวเมืองที่บริสุทธิ์ต้องตกอยู่ในอันตรายค่ะ..."
90100020-217 = "ในตอนนั้นชาวเมืองที่ได้รับความเสียหายต่างเรียกร้องให้ SRT รับผิดชอบ และความรับผิดชอบทั้งหมดก็ตกอยู่ที่ฉันที่เป็นผู้บังคับบัญชาในพื้นที่ปฏิบัติการค่ะ"
90100020-218 = "แต่ตอนนั้นท่านประธานองค์การนักเรียนก็บอกว่าทุกอย่างเป็นความผิดของตนเองและออกมาแสดง#nความรับผิดชอบอย่างเต็มที่ ไม่ได้กล่าวโทษพวกเราแต่อย่างใด"
90100020-219 = "ถ้าปัญหาทุกอย่างบนโลกไม่ใช่สิ่งที่คนคนเดียวจะรับผิดชอบได้... แล้วทำไมท่านประธานถึงแบกรับ#nภาระของ SRT ไว้เพียงลำพังมาตลอดล่ะคะ?"
90100020-220 = "เป็นเพราะว่าตอนนั้น... ฉันมีกำลังที่จะทำแบบนั้นน่ะค่ะ"
90100020-221 = "ในเวลานั้นฉันมีทั้งกำลังที่จะโอบรับความผิดพลาดของทุกคน มีทั้งตำแหน่ง และมีทั้งความรับผิดชอบที่จะทำเช่นนั้นค่ะ"
90100020-222 = "ถ้าคนอื่นต้องตกอยู่ในความลำบากเพราะคำขอของฉัน แต่ฉันกลับเลือกโยนให้เป็นเรื่องของความรับ#nผิดชอบทั้งๆ ที่ตัวเองสามารถช่วยเหลือได้ แบบนั้นฉันจะเรียกตัวเองว่าเป็นผู้นำที่ดีได้ยังไงล่ะคะ"
90100020-223 = "ถ้าพูดอย่างนั้น ฉันเองก็..."
90100020-224 = "แต่ตอนนี้คุณเหนื่อยล้าจนแค่แบกรับความผิดของตัวเองก็แทบไม่ไหวแล้วนี่คะ"
90100020-225 = "ไว้สักวันเมื่อคุณมีกำลังมากกว่านี้ และเข้มแข็งพอที่จะช่วยแบกรับความผิดของคนอื่นได้ ตอนนั้นค่อยตอบแทนบุญคุณครั้งนี้ก็ยังไม่สายค่ะ"
90100020-226 = "ช่วยทำตามความดื้อรั้นของฉันเถอะนะคะ ยูกิโนะ"
90100020-227 = ""
90100020-229 = ""
90100020-230 = "ฉันเข้าใจเจตนาของท่านประธานองค์การนักเรียนค่ะ..."
90100020-231 = "แต่การมาอยู่ที่สำนักควบคุมแล้วสำนึกผิดเพียงอย่างเดียว คงไม่อาจกอบกู้เกียรติยศที่ SRT สูญเสียไปกลับคืนมาได้ค่ะ"
90100020-232 = "ฉันจะทำทุกวิถีทางเพื่อชดใช้ความผิดพลาดค่ะ ขอคำสั่งด้วยค่ะ"
90100020-233 = ""
90100020-235 = ""
90100020-236 = ""
90100020-237 = "ถึงจะนิรโทษกรรมให้ไม่ได้... แต่การให้โอกาสพวกคุณได้กลับไปรับใช้ชาวเมืองอีกครั้ง ก็ไม่ใช่เรื่องที่ทำไม่ได้หรอกค่ะ"
90100020-238 = ""
90100020-240 = ""
90100020-241 = "ยูกิโนะ คุณเคยได้ยินเรื่องเกี่ยวกับ <ตำนาน> มาก่อนมั้ยคะ?"
90100020-242 = "เรื่องเล่าที่แพร่ต่อกันปากต่อปากในหมู่นักเรียน เรื่องเลื่อนลอยที่ไม่อาจรู้ได้ว่ามีที่มาหรือแหล่งอ้างอิง#nจากไหน ตำนานที่เล่าต่อกันมา... และเรื่องเล่าสยองขวัญ"
90100020-243 = "เรื่องราวที่ไม่น่าเชื่อและไม่มีทางมีอยู่จริง แต่กลับมีพลังโน้มน้าวใจอย่างประหลาด จนถูกเล่าขานสืบต่อกันมาและยังคงมีชีวิตอยู่ผ่านคำบอกเล่าเหล่านั้น"
90100020-245 = "อย่างเรื่องรถไฟที่มุ่งหน้าไปยังสถานีในต่างโลกที่ไม่มีอยู่จริง..."
90100020-247 = "หรือเรื่องที่บอกว่าถ้าเปิดวิทยุในกลางดึก จะได้ยินเสียงพูดต้องคำสาป..."
90100020-249 = "หรือเรื่องที่ว่าถ้าขึ้นลงลิฟต์ในอาคารร้างตามลำดับที่กำหนด ก็จะกลับออกมาไม่ได้อีกเลย..."
90100020-250 = ""
90100020-251 = "คุณดูไม่แปลกใจเลยนะคะ... หรือว่าคุ้นเคยกับเรื่องน่ากลัวแล้วคะ?"
90100020-252 = "การปล่อยให้อารมณ์คล้อยตามไปกับเรื่องที่ไม่รู้ด้วยซ้ำว่าจริงหรือเปล่า ถือเป็นเรื่องที่ไร้ประสิทธิภาพค่ะ"
90100020-253 = "ค่ะ เดิมที <ตำนาน> ก็เป็นเพียงเรื่องเล่าเลื่อนลอยที่ไร้คุณค่า และไม่มีอิทธิพลใดๆ ต่อโลกแห่งความเป็นจริง..."
90100020-254 = "แต่เมื่อไม่นานมานี้ มีรายงานจากนักเรียนที่อ้างว่าตัวเองได้ประสบกับ <ตำนาน> มากเข้าทุกทีค่ะ"
90100020-255 = "และนอกเหนือจากคำบอกเล่าของผู้เห็นเหตุการณ์แล้ว ก็ยังมีความเสียหายที่เกิดขึ้นจริงจากตำนาน#nด้วยค่ะ"
90100020-256 = "ความเสียหายที่เกิดจากตำนานเหรอคะ...?"
90100020-257 = "นักเรียนส่วนใหญ่ที่อ้างว่าเคยพบกับตำนานต่างพูดไม่ได้หรือหายตัวไปก่อนจะได้รู้ว่าเกิดอะไรขึ้นอีกค่ะ"
90100020-258 = "ถ้าเป็นแค่เหตุการณ์ก่อการร้ายหรือคดีคนหายทั่วไป ฉันคงมอบหมายให้สถาบันฝึกตำรวจวัลคิรี่จัดการ แต่ตอนนี้เรายังไม่รู้ขอบเขตของสถานการณ์"
90100020-259 = "คณะกรรมการบริหารเห็นว่า ก่อนที่ 'ตำนานเมือง' นี้จะแพร่กระจายไปมากกว่านี้ ควรโอนเรื่องไปให้หน่วยงานระดับสูงกว่าสืบสวนค่ะ"
90100020-260 = "ในสถานการณ์ที่หน่วยงานรักษาความสงบทั่วไปไม่สามารถจัดการได้ และต้องดำเนินการสืบสวน#nอย่างรวดเร็วโดยไม่ยึดติดกับกรอบของกฎหมายแล้วละก็..."
90100020-261 = ""
90100020-263 = ""
90100020-264 = ""
90100020-265 = "ถึงเวลาที่ SRT ต้องออกโรงแล้วสินะคะ..."
90100020-266 = "อย่างที่คุณว่าเลยค่ะ"
90100020-267 = "แต่อย่างที่บอกไปก่อนหน้านี้ว่านี่เป็นแค่ข้อเสนอแนะของฉันในฐานะประธานองค์การนักเรียนเท่านั้นค่ะ ไม่ใช่คำสั่งแต่อย่างใด"
90100020-268 = "เราไม่รู้ด้วยซ้ำว่าคู่ต่อสู้เป็นใคร และในกรณีเลวร้ายที่สุด พวกคุณก็อาจลงเอยอย่างเดียวกับนักเรียน#nเหล่านั้นก็ได้ค่ะ"
90100020-269 = ""
90100020-273 = ""
90100020-275 = "ถ้าตำนานมาหาคุณ ก่อนที่คุณจะหาตำนานเจอ#nต่อไปคุณก็จะกลายเป็นตำนานค่ะ"
90100020-276 = "ถึงอย่างนั้นก็จะรับปฏิบัติการนี้ใช่มั้ยคะ?"
90100020-277 = ""
90100020-278 = "ค่ะ"
90100020-279 = "พวกฉันมีหนี้ที่ต้องชดใช้นี่คะ"
90100020-280 = ""
90100020-282 = ""
90100020-283 = ""
90100020-284 = "งั้นก็ดีค่ะ ฉันจะส่งต่อข้อมูลเกี่ยวกับตำนานที่องค์การนักเรียนรวบรวมไว้จนถึงตอนนี้ให้พวกคุณทันทีค่ะ"
90100020-285 = "ฉันอยากให้ใช้ข้อมูลเหล่านี้เป็นพื้นฐานในการสืบหาความจริงของตำนาน และกำจัดภัยคุกคามที่ปกคลุมไปทั่วคิโวทอสให้สิ้นซากค่ะ"
90100020-286 = "อ้อ ยังมีอีกเรื่องหนึ่ง... แต่นี่เป็นคำขอส่วนตัวของฉัน ไม่ใช่จากประธานองค์การนักเรียนค่ะ"
90100020-287 = ""
90100020-289 = ""
90100020-290 = "ได้โปรดกลับมาอย่างปลอดภัยด้วยนะคะ"
90100020-291 = "เรื่องนั้นไม่ต้องเป็นห่วงค่ะ"
90100020-292 = "เพราะหน้าที่ของหน่วยรบพิเศษไม่ใช่แค่การต่อสู้ แต่รวมถึงการถอนตัวและหลบหนีอย่างรวดเร็ว#nเมื่อรู้ว่าไม่มีทางชนะด้วยค่ะ"
90100020-294 = "ก่อนเริ่มปฏิบัติการ ฉันมีหนึ่งเรื่องที่อยากถามค่ะ"
90100020-295 = "ค่ะ เรื่องอะไรเหรอคะ?"
90100020-296 = "ถึงปฏิบัติการครั้งนี้จะดำเนินการอย่างไม่เป็นทางการ แต่ถ้าต้องยึดฐานที่มั่นหรือจัดหาเสบียงกระสุน ก็ต้องมีผู้สนับสนุนที่สามารถประสานงานกับภายนอกได้ค่ะ"
90100020-297 = "เดิมทีแล้วในปฏิบัติการของ SRT ท่านประธานองค์การนักเรียนจะเป็นผู้รับหน้าที่นี้ แต่ในสถานการณ์#nปัจจุบันที่ไม่อาจเปิดเผยตัวตนอย่างเป็นทางการได้ พวกฉันควรรับการสนับสนุนจากใครดีคะ?"
90100020-298 = "นั่นสินะคะ ถ้าฉันสนับสนุนกองทหาร FOX ท่ามกลางสถานการณ์นี้ ก็อาจทำให้ผู้คนมองว่าฉันอนุมัติ#nการฟื้นฟูสถาบันพิเศษ SRT อย่างเป็นทางการแล้ว..."
90100020-299 = "แต่ก็โชคดีที่ในคิโวทอสมีองค์กรอื่นที่สามารถรับบทบาทนั้นแทนได้อยู่ค่ะ"
90100020-300 = "องค์กรสืบสวนพิเศษที่มีทั้งอำนาจและทรัพยากรทัดเทียมกับองค์การนักเรียน และเป็นองค์กรที่ทุกคนในองค์การนักเรียนต่างยอมรับ"
90100020-301 = "<ชาเล่ต์> นั่นเองค่ะ"
90100020-302 = ""
90100020-304 = ""
90100020-306 = "นี่ฉันได้ยินผิดไปหรือเปล่าคะ...?"
90100020-308 = "ตอนต่อไป;กองทัพต้องเดินด้วยท้อง"
