[translation]
90101110-1 = "Episode 11;Epilogue"
90101110-2 = "After the incident was resolved and things had settled down, I went to visit the General Student Council."
90101110-5 = "[ns] \"Rinny!\""
90101110-6 = "General Student Council Reception Room"
90101110-7 = ""
90101110-8 = "Ah, [USERNAME] Sensei."
90101110-9 = "It's been a while. I hope you've been well."
90101110-10 = "...More importantly, don't call me \"Rinny.\""
90101110-11 = "[s1] \"I came to help brighten your day!\"\n[s2] \"I missed you, Rinny, it's been so long...\""
90101110-13 = "*sigh*"
90101110-14 = "Moving past your jokes, you have something to discuss with me, yes?"
90101110-15 = "Such as requesting ANOTHER extension for Schale's budget expenditure report?"
90101110-16 = "Or perhaps finally submitting your business trip report to the Board of Administration?"
90101110-17 = "[s] \"Ugh...\""
90101110-18 = ""
90101110-20 = ""
90101110-21 = "Or could it be that you're here to ask about the progress on the glass shard you asked me to analyze?"
90101110-22 = "[s3] \"Can't believe we're already talking about work...\"\n[s4] \"I really was concerned about you, you know!\""
90101110-25 = "There's nothing to worry about. These days, I've been fine."
90101110-26 = "After that fake..."
90101110-27 = "Sorry. After the President returned, business at the General Student Council is more or less back to normal."
90101110-28 = "She looks and talks nothing like the real president, but she is comparable in her overall competence."
90101110-29 = "Perhaps even better, in some ways."
90101110-30 = "Anyway, thanks to that, I'm able to take about one day a week off now."
90101110-31 = "[s5] \"A day in a week...\"\n[s6] \"And that's...good to you?\""
90101110-34 = "Yes. More breaks than that may disrupt my daily routine."
90101110-35 = ""
90101110-37 = ""
90101110-38 = "About the glass shard... I've tried various methods to analyze it."
90101110-39 = "I've observed no changes in the world beyond, even during a full 24-hour cycle, and it doesn't seem to react to light or other outside stimuli."
90101110-40 = "You called it a \"glass shard,\" but I'd equate it to more of a mirror."
90101110-41 = "[s] \"What makes you say that?\""
90101110-42 = "The material we use for glass allows us to look outside, like in windows."
90101110-43 = "So it doesn't matter from what angle we look out, it'll remain the same."
90101110-44 = "A mirror reflects light, rather than transmitting it, which is how it reflects the image of the observer back toward them."
90101110-46 = "But the image you can see in the shard doesn't fade in the light nor does it emit its own light in the darkness."
90101110-47 = "It looks more like a reflection."
90101110-48 = "If this image is reflecting Kivotos, and not another world..."
90101110-49 = "Isn't it more accurate to class it a mirror, rather than a glass shard?"
90101110-50 = "[s] \"Does that mean this field or the abyss could be places in Kivotos?\""
90101110-51 = "That's my current hypothesis."
90101110-52 = "But they don't resemble anywhere in Kivotos that I know."
90101110-54 = "...Just like the lake in the president's photo."
90101110-55 = ""
90101110-56 = "[ns] \"...Kivotos in a mirror.\""
90101110-57 = "Now that I think about it, I remember reading something like that in Trinity's classic literature."
90101110-58 = "It was about a girl who, in a dream, walks into a mirror and comes out the other side into a new world. It was similar to the one she knew, but entirely different in other ways."
90101110-59 = "Everything vanishes the moment when the queen on the chessboard wakes up, and that world is nothing but a fleeting dream."
90101110-60 = "I can't help but wish that the unbelievable reality we're living in is a dream, sometimes."
90101110-61 = "[s] \"I wouldn't want this time I've spent with you to not be real, though.\""
90101110-62 = "...Do you talk like that to other students?"
90101110-63 = "Please consider your position before you speak. You can't afford those kinds of misunderstandings."
90101110-64 = "[s] \"So mean...\""
90101110-65 = "Anyway."
90101110-66 = "I can't claim to know every single inch of Kivotos, so it'd be presumptuous of me to say that the scenery we observe in the shard absolutely doesn't exist here."
90101110-67 = "So I plan on leaving D.U. on my next day off and see what I can find."
90101110-68 = "[s] \"Can I tag along?\""
90101110-69 = "If you wish. I wouldn't mind you accompanying me."
90101110-70 = "[s7] \"Yay! My second date with Rinny!\"\n[s8] \"I'll pack lunch!\""
90101110-73 = "...Never mind. I'll go by myself."
90101110-74 = "[s] \"You're so mean, Rinny!\""
90101110-75 = "Stop calling me Rinny!"
90101110-80 = "FOX Squad HQ"
90101110-81 = "[ns9] \"Did everyone eat already?\"\n[ns10] \"I was going to order something for dinner...\""
90101110-84 = ""
90101110-86 = "[ns] \"...Crab?\""
90101110-87 = "Ah. We're caught."
90101110-88 = "What do you mean \"caught\"? That would imply that we're doing something wrong, which we are not!"
90101110-89 = "Haha. We wanted to see if the crabs had decent yield."
90101110-90 = "I-If you give us a moment..."
90101110-91 = "...we can explain."
90101110-92 = "[s11] \"IS there anything to explain here?\"\n[s12] \"Unless you're black marketing crabs all of a sudden.\""
90101110-95 = "Um, well, so..."
90101110-96 = "[s] \"...What did you do?\""
90101110-97 = "I-It's not like that!"
90101110-99 = "[ns] \"...Ah. It's the Carpaccio Family's crab.\""
90101110-100 = "Bingo. We managed to recover most of them, but the Carpaccios didn't want them."
90101110-101 = "Something about PTSD and being done with crabs..."
90101110-102 = "Apparently the workers who saw the giant crab now get panic attacks from the sounds of pincers clicking."
90101110-103 = "They tried to control others through fear, and it turned right back around on them. Oh, the irony!"
90101110-104 = "Eh. They got exactly what they deserved."
90101110-105 = "Anyway, the rumor these days is that the Carpaccios were using the crabs for suspicious business. No one wanted them, so the port was going to throw them away. We figured it was a waste of food."
90101110-106 = "It's not like our memories of crabs are all that great at this point either."
90101110-107 = "But we can't blame perfectly delicious food for that."
90101110-108 = "The chance to feast on a pile of crabs like this? It's a luxury!"
90101110-109 = "So I'm gonna eat until I get sick. Heehee."
90101110-110 = "Ahem."
90101110-111 = "Anyways, apologies for the late invitation..."
90101110-112 = "But would you like to join us for some crab, Sensei?"
90101110-113 = ""
90101110-115 = ""
90101110-116 = ""
90101110-117 = "[ns] \"Is it really okay for me to join the party?\""
90101110-118 = "Of course. We have plenty."
90101110-122 = "They're just about done, as well."
90101110-123 = "Let's see..."
90101110-124 = ""
90101110-127 = "Huh, it really is different..."
90101110-128 = "It's sooo juicy... It's completely different from Yokozuna's crab and fish sausage!"
90101110-129 = "Are you serious? Of course some phony sausages made of flour and cheap fish can't compare."
90101110-130 = "Fufu, once you try real crab, you'll never go back."
90101110-131 = ""
90101110-135 = "...Really? It's different, but I actually think the fish sausage is better."
90101110-136 = "WHAT?! Stick out your tongue, right now! Lemme see! There's gotta be something wrong with it!"
90101110-137 = "I mean, c'mon. These plain crabs don't have the greasiness of fish sausages. I want it to slide down my throat!"
90101110-138 = "And look at this! It took forever for me to get this teeny tiny amount of meat out of the shell! What is this, a meal for shrimp?!"
90101110-139 = "If you're just going to keep complaining, then give it to me! I'll eat it."
90101110-140 = ""
90101110-144 = "I believe what Otogi is trying to say is that these crabs don't have very good yield."
90101110-145 = "It's to be expected. It's not crab season, and these likely had a traumatic time in a drum barrel. They were bound to turn out like this."
90101110-146 = ""
90101110-147 = ""
90101110-148 = "...When it comes to yield, do bigger crabs mean more meat?"
90101110-149 = "And following that thought, how much meat do you think we could've gotten from that monster crab's claw?"
90101110-150 = "Didn't you fight that thing alongside us? You really want to try EATING it?"
90101110-151 = "You couldn't PAY me to eat that crab. It had a blue chunk of metal sticking out of it AND it spewed disgusting liquid at us."
90101110-152 = "You're too narrowminded. Imagine what a mouthful of a huge crab claw bigger than your face would taste like."
90101110-153 = "..."
90101110-154 = "Ah, she thought it."
90101110-155 = "I did NOT!!"
90101110-158 = ""
90101110-159 = "I've only had processed crabs before, but having it from a hot pot like this is quite good."
90101110-160 = "It looks like the other ingredients are ready too..."
90101110-161 = "Here you go, Sensei. It's hot, so be careful."
90101110-162 = ""
90101110-165 = "[ns13] \"It's sweet and salty, as if it had already been seasoned.\"\n[ns14] \"I kinda want rice with this.\""
90101110-168 = "Ah, would you like some rice?"
90101110-169 = "I cooked some rice for inarizushi tomorrow."
90101110-170 = "Niko, I just had this idea."
90101110-171 = "What if we seasoned the rice with this crab...?"
90101110-172 = "Doesn't that sound good?"
90101110-173 = "That's..."
90101110-174 = "It's got to be delicious!"
90101110-175 = "You're a genius, Otogi! How have we never thought of this before?"
90101110-176 = "Because crab meat is expensive, duh."
90101110-177 = "But we have an excess of crab today..."
90101110-178 = "I'll go bring all the cooked rice we have."
90101110-179 = "Um, can we also bring some military crackers from the storage box while we're at it?"
90101110-180 = "I think crab meat with mayo would go great with crackers..."
90101110-181 = "Now YOU'RE the genius, FOX 3."
90101110-182 = "Let's do it!"
90101110-183 = "Don't do it in front of the fire. It's dangerous."
90101110-184 = "Fufu, I guess I'll have to cook more rice later."
90101110-186 = "The FOX Squad and I had a great time finishing off the rest of the crabs."
90101110-187 = ""
90101110-192 = ""
90101110-193 = "Trinity Old Library Entrance"
90101110-195 = ""
90101110-196 = "*cough* *cough*"
90101110-197 = "President, were you restoring old texts with the windows closed again?"
90101110-198 = "I can see the dust particles in the air. How can you read like this?"
90101110-199 = ""
90101110-201 = ""
90101110-202 = "I-It's just been so hot! If you open the window, you'll let all the hot air in!"
90101110-203 = "Also, direct sunlight is the enemy of old texts..."
90101110-204 = "Too bad. I'm ventilating this room right now."
90101110-205 = ""
90101110-207 = ""
90101110-208 = ""
90101110-209 = ""
90101110-212 = ""
90101110-213 = ""
90101110-215 = "E-Eeek..."
90101110-217 = "Phew, that's more like it."
90101110-218 = "Also, I don't think I've seen those books before."
90101110-219 = "A merchant's transaction records from Hyakkiyako's warring states period..."
90101110-220 = "An original copy of \"Koi About Love\" author's \"Sledgehammer\" that was recalled due to defective printing..."
90101110-221 = "And this is...Saint Justina Council's stenographic record from the first Trinity Council?"
90101110-222 = ""
90101110-224 = ""
90101110-225 = "Why is this over here?!"
90101110-226 = "Don't tell me, President... Did you make another copy during restoration again?"
90101110-227 = "Wh-What do you mean \"again\"? I don't do it that often—"
90101110-228 = "Ahem. Chieru brought me this book."
90101110-229 = "Chieru... Hasn't she been gone for quite some time now?"
90101110-230 = "If I recall correctly, she went into the catacombs to search for ancient manuscripts. She went missing three months ago..."
90101110-231 = "That's her. She's back now. With a trove of new books she \"excavated.\""
90101110-232 = "She's back in her dorm room now, reading all the books she missed. She'll be there for a while."
90101110-233 = "Well, I'm glad to hear that she's okay."
90101110-234 = "Especially after last time. She caused quite a few problems with Gehenna when she was found near Hinnom Volcano."
90101110-235 = "A nightmare... A true nightmare. Do you remember? They kept saying they would only let her go if the Library Committee president visited them in person."
90101110-236 = ""
90101110-238 = ""
90101110-239 = "By the way, Shimiko. Chieru had a question before she left."
90101110-240 = "She was asking if you remember any news articles about \"Perorodzilla.\""
90101110-241 = ""
90101110-243 = ""
90101110-244 = ""
90101110-245 = ""
90101110-246 = "...Perorodzilla?"
90101110-248 = "Lore Pursuit;To be Continued in Chapter 3"
