[translation]
90101100-1 = "ตอนที่ 10;คุณค่าที่ไม่เสื่อมคลาย"
90101100-6 = "อึก... เจ้าตัวนั้น ทำไมถึงแข็งแกร่งขนาดนี้?"
90101100-7 = "FOX 3 รายงาน เกราะของเป้าหมายหนาเกินไป กระสุนขนาด 11 มม. ใช้ไม่ได้ผลเลย!"
90101100-8 = "ขอสนับสนุนการยิงด้วย!"
90101100-9 = ""
90101100-13 = ""
90101100-14 = "ฉันกำลังล่อเป้าหมายไปทางจุดเบต้าเพื่อเตรียมซุ่มยิง"
90101100-15 = "FOX 4 บรรจุกระสุนใหม่เป็นกระสุนระเบิดแรงสูง แล้วรออยู่ที่ตำแหน่งปัจจุบัน"
90101100-16 = "เอ๋ ไม่ใช้กระสุนเจาะเกราะหรอกเหรอ?"
90101100-17 = "แค่เจาะเกราะอย่างเดียวไม่พอหรอก"
90101100-18 = "เจ้านั่นน่ะ ฟื้นฟูตัวเองได้ในช่วงเวลาสั้นๆ"
90101100-19 = "ถ้าไม่จัดการให้จบในทันที เปลือกนอกของมันจะหนาขึ้นจนจัดการได้ยากกว่าเดิม"
90101100-20 = "ว้าว... เกราะชีวภาพนี่ พอได้สู้จริงแล้วน่ารำคาญเอาเรื่องเลยแฮะ"
90101100-21 = "FOX 2 ยิงกระสุนลูกซองเดี่ยวเข้าใส่ช่วงท้องของมันได้มั้ย?"
90101100-22 = ""
90101100-23 = "ถ้าจะโจมตีให้ได้ผล ฉันต้องเข้าไปใกล้พอสมควรเลย... ช่วยถ่วงเวลาให้หน่อยนะ"
90101100-24 = "ฉันจะลองเชื่อมต่อกับเครนที่ควบคุมจากระยะไกลให้เอง"
90101100-25 = ""
90101100-31 = "อีก 10 วินาที..."
90101100-32 = "รับทราบ!"
90101100-33 = ""
90101100-38 = "เป้าหมายถูกโจมตีแล้ว"
90101100-39 = ""
90101100-42 = "FOX 4 ซุ่มยิงไปที่ส่วนหกเหลี่ยมตรงท้องที่ FOX 2 เพิ่งโจมตีไปได้มั้ย? "
90101100-43 = "ตรงนั้นแหละจุดอ่อนของปู"
90101100-44 = "ระยะ 700 เมตร ลมพัดจากเหนือไปใต้ด้วยความเร็ว 12 นอต"
90101100-45 = "แค่นี้ไม่เหนือบ่ากว่าแรงฉันหรอก"
90101100-46 = ""
90101100-49 = "แทงโก้ดาวน์ เป้าหมายถูกทำลายแล้ว"
90101100-50 = "ตอนนี้แหละ FOX 3 จุดชนวนเคลย์มอร์!"
90101100-51 = "ตายซะ เจ้าสัตว์เปลือกแข็งน่าขยะแขยง!"
90101100-52 = ""
90101100-60 = "ว้าก นี่มันอะไรเนี่ย? มีของเหลวกลิ่นคาวพุ่งออกมาจากปากปูเต็มไปหมดเลย!"
90101100-61 = "อื้อ... เหม็นคาวจัง รู้สึกเหมือนทั้งตัวส่งกลิ่นคาวไปหมดเลย..."
90101100-62 = "แหะๆ... กลับไปคงต้องรีบซักชุดนักเรียนทันทีเลยละ"
90101100-63 = ""
90101100-64 = "อ่า... อ่า..."
90101100-65 = "สัตว์ประหลาดถูกกำจัดแล้ว ตอนนี้พื้นที่นี้ปลอดภัยแล้วละ"
90101100-66 = "ละ... เหลือจะเชื่อ... ปูในข่าวลือนั่นมีอยู่จริง..."
90101100-67 = "ปะ... เป็นปูไม่ได้... ไม่สิ เป็นไปไม่ได้..."
90101100-68 = ""
90101100-70 = ""
90101100-71 = ""
90101100-72 = "ตกใจมากเลยละสิ? ถึงกับพูดผิดๆ ถูกๆ เลย"
90101100-73 = "ก็ได้เห็นสัตว์ประหลาดลึกลับที่คิดว่าไม่มีอยู่จริง จะช็อกก็ไม่แปลกหรอก"
90101100-74 = "ที่ผ่านมาฉันต้องลำบากตั้งมากเพื่อเก็บตราสารหนี้และงานศิลปะของแฟมิลี่ไว้ในโกดังนี้แท้ๆ..."
90101100-75 = "แต่กลับถูกสัตว์ประหลาดปูบ้าบอนั่นทำลายทุกอย่างพังพินาศหมด!"
90101100-76 = "บอสไม่เอาฉันไว้แน่...!"
90101100-77 = "อ้อ เรื่องนั้นเองหรอกเหรอ...?"
90101100-78 = "ก็ว่าทำไมถึงยึดติดกับงานรักษาความปลอดภัยของท่าเรืออย่างผิดปกติขนาดนี้... ที่แท้ก็เป็นเพราะเหตุผลนี้นี่เองสินะคะ"
90101100-79 = "ถือซะว่ากรรมตามสนองก็แล้วกัน ฉันไม่เห็นใจด้วยหรอก"
90101100-80 = "จากนี้ก็เหลือแค่ส่งข้อมูลให้กรมความมั่นคงสาธารณะของวัลคิรี่ เดี๋ยวพวกนั้นก็คงจัดการต่อเอง"
90101100-81 = "ต่างจากข่าวลือเรื่องปูยักษ์ที่ทำร้ายคน เรื่องนี้คงมีเหตุผลมากพอให้วัลคิรี่ออกมาลงมือละนะ"
90101100-82 = ""
90101100-84 = ""
90101100-85 = "..."
90101100-86 = "[s] \"ไม่เป็นไรใช่มั้ย?\""
90101100-87 = "ค่ะ ฉันอยู่แนวหลังตลอด ฉันไม่เป็นไรค่ะ"
90101100-88 = "คนที่ต้องเสี่ยงอันตรายจริงๆ คือนิโกะกับคุรุมิมากกว่า..."
90101100-89 = "[s] \"ครูไม่ได้หมายถึงเรื่องปฏิบัติการหรอก...\""
90101100-90 = ""
90101100-93 = "[ns1] \"ตอนสอบสวนเมื่อกี้ดูอารมณ์รุนแรงเลยนะ\"\n[ns2] \"ตอนนั้นนึกถึงเรื่องอะไรงั้นเหรอ?\""
90101100-96 = "ตอนนั้น..."
90101100-97 = "ต้องขอโทษด้วยค่ะ ฉันเผลอใช้อารมณ์มากเกินไป นั่นไม่ใช่เรื่องปกติของฉันเลย"
90101100-98 = "ระหว่างสอบสวน จู่ๆ ฉันก็นึกถึงเรื่องในอดีตขึ้นมา... ก็เลยโกรธค่ะ"
90101100-99 = "[s] \"โกรธอีกฝ่ายเหรอ?\""
90101100-100 = "ฉันก็ไม่แน่ใจค่ะ..."
90101100-101 = "ตอนนั้นฉันโกรธมาก แต่พอมาทบทวนดู ก็ไม่รู้เหมือนกันว่ากำลังโกรธใคร"
90101100-102 = "ฉันโกรธอีกฝ่าย... หรือโกรธตัวเองในอดีตที่เคยทำผิดพลาดแบบเดียวกัน"
90101100-103 = "หรือกำลังโกรธสังคมนี้เอง ที่ปล่อยให้เรื่องแบบนี้เกิดขึ้นซ้ำแล้วซ้ำเล่ากันแน่"
90101100-104 = "ถึงจะคิดว่าเป็นการบ่นเหมือนเด็กๆ แต่ฉันก็ทนกับสถานการณ์ที่ไม่เป็นไปตามที่ควรจะเป็นไม่ได้จริงๆ ค่ะ"
90101100-105 = "[s3] \"ไม่ใช่แค่เด็กหรอกนะ ผู้ใหญ่เองก็ด้วย\"\n[s4] \"ผู้ใหญ่เองก็โกรธเหมือนกัน เมื่ออะไรๆ ไม่เป็นไปอย่างที่หวัง\""
90101100-108 = "คุณครูก็เหมือนกันเหรอคะ...?"
90101100-109 = "[s5] \"แน่นอนสิ\"\n[s6] \"ถ้าไม่รู้สึกอะไร ก็แปลว่าไม่ได้คาดหวังอะไรตั้งแต่แรกไม่ใช่เหรอ?\""
90101100-112 = ""
90101100-114 = ""
90101100-115 = "อย่างที่สมาชิกของการ์ปัชโช่ แฟมิลี่บอก สิ่งที่พวกเขาทำในครั้งนี้ไม่มีปัญหาในทางกฎหมายค่ะ"
90101100-116 = "พวกเขาแค่ปล่อยข่าวลือ สร้างภาพลักษณ์ แล้วอาศัยการประกวดราคาที่ถูกกฎหมาย เพื่อหาผลประโยชน์ก็เท่านั้น"
90101100-118 = "แต่ผลจากเรื่องนั้นทำให้ผู้คนจำนวนมากตกอยู่ในความหวาดกลัว และท้ายที่สุดก็เกิดความเสียหาย#nที่ไม่อาจมองข้ามได้ค่ะ"
90101100-119 = "ฉันรู้สึกมานานแล้วว่า ต่อให้วางกฎให้รัดกุมแค่ไหน ก็แทบไม่มีประโยชน์ในการจัดการคนชั่วเลย"
90101100-120 = "เพราะพวกคนชั่วชำนาญในการหาช่องโหว่ที่ไม่ได้เขียนไว้ในกฎ แล้วนำไปใช้ในทางที่ผิดค่ะ"
90101100-121 = ""
90101100-122 = "ตรงกันข้าม กฎที่ซับซ้อนกลับสร้างความลำบากให้ชาวเมืองส่วนใหญ่ และบางครั้งก็ทำให้ผู้บริสุทธิ์ต้องกลายเป็นผู้เสียหาย"
90101100-123 = "เช่นเดียวกับความยุติธรรมที่สมบูรณ์แบบ... กฎที่สามารถควบคุมคนชั่วได้อย่างสมบูรณ์แบบก็ไม่มีอยู่#nบนโลกนี้ใช่มั้ยคะ?"
90101100-124 = "[s] \"ก็คงต้องถือว่าไม่มีอยู่จริงละนะ\""
90101100-125 = "เป็นอย่างนั้นจริงๆ สินะคะ"
90101100-126 = "[s] \"โดยปกติแล้ว กฎไม่ได้ถูกสร้างขึ้นมาเพื่อผู้คนหรอก\""
90101100-127 = ""
90101100-129 = ""
90101100-130 = "คะ...?"
90101100-131 = "[s7] \"ที่จริงแล้ว ผู้คนถูกเปลี่ยนให้เข้ากับกฎมากกว่า\"\n[s8] \"อันที่จริง ผู้คนถูกเปลี่ยนให้เข้ากับกฎมากกว่า\""
90101100-132 = ""
90101100-133 = ""
90101100-136 = "[ns9] \"ต่างจากจิตใจของคนที่สั่นคลอนและเปลี่ยนแปลงอยู่ตลอดเวลา\"\n[ns10] \"กฎที่ถูกบันทึกไว้แล้วจะไม่เปลี่ยนแปลง และแก้ไขได้ยากด้วย\""
90101100-139 = "[ns] \"ผู้คนก็เลยตกอยู่ใต้อำนาจของกฎที่อดีตสร้างขึ้นได้ง่ายน่ะ\""
90101100-140 = "ถ้าอย่างนั้น ถ้าไม่ต้องการตกอยู่ใต้อำนาจของอดีต"
90101100-141 = "ผู้คนที่ไม่อาจเข้าใจกันและสั่นคลอนอยู่ตลอดเวลา ควรยึดถือสิ่งใดในการใช้ชีวิตเหรอคะ?"
90101100-142 = "[s] \"ก็ต้องสร้างหลักนำทางด้วยคุณค่าที่ไม่เสื่อมคลาย ไม่ใช่ด้วยกฎ\""
90101100-143 = "คุณค่า... ที่ไม่เสื่อมคลาย"
90101100-144 = "[ns] \"ยูกิโนะ ความยุติธรรมของตัวเองก็ยังคงไม่เสื่อมคลายใช่มั้ย?\""
90101100-145 = ""
90101100-147 = ""
90101100-148 = "ฉันอยากเชื่อว่าเป็นแบบนั้นค่ะ..."
90101100-149 = "[s] \"งั้นก็ทบทวนกฎกันใหม่ โดยยึดมั่นในความยุติธรรมที่ไม่เสื่อมคลายนั้นกัน\""
90101100-150 = "ค่ะ"
90101100-151 = ""
90101100-153 = ""
90101100-154 = ""
90101100-155 = ""
90101100-156 = "กำลังคุยเรื่องอะไรเหรอ ดูจริงจังกันเชียว?"
90101100-157 = "หรือว่ากำลังนัดคุณครูไปเที่ยวช่วงสุดสัปดาห์โดยไม่ชวนพวกเราอยู่เหรอ?"
90101100-158 = "ไม่มีทางหรอก เราแค่กำลังหารือกันว่า หลังจากจัดการสถานที่แล้ว จะรายงานต่อองค์การนักเรียนว่า#nยังไงก็เท่านั้น"
90101100-159 = ""
90101100-161 = ""
90101100-163 = ""
90101100-164 = "พวกเรากลับมาแล้ว~"
90101100-165 = "เหนื่อยหน่อยนะ FOX 2#nในที่เกิดเหตุไม่มีชาวเมืองคนอื่นอยู่ใช่มั้ย?"
90101100-166 = "อื้อ ฉันรีบติดต่อสำนักงานท่าเรือให้ควบคุมการเข้าออกไว้ ดูเหมือนว่าจะไม่มีใครได้รับผลกระทบจาก#nเหตุการณ์วุ่นวายนี้นะ"
90101100-167 = "แต่ว่า... ฉันพบสิ่งนี้ตรงจุดที่ปูยักษ์ตัวนั้นล้มอยู่น่ะ"
90101100-169 = "[ns] \"นี่มัน...\""
90101100-170 = "ดูไม่เหมือนสิ่งตกค้างจากปูเลย"
90101100-171 = "อื้อ... ดูเหมือนเศษแก้ว ไม่สิ เหมือนเศษกระจกที่สะท้อนโลกอีกใบหนึ่งเลย"
90101100-172 = "ก่อนหน้านี้เราเคยเห็นของแบบนี้แล้วใช่มั้ย?"
90101100-173 = "อื้อ ตอนที่กำจัดคุเนะคุเนะได้ ก็มีเศษกระจกแบบนี้หลงเหลืออยู่บนพื้นเหมือนกัน"
90101100-174 = "ตอนนั้นมันสะท้อนภาพทุ่งหญ้าที่คุเนะคุเนะยืนอยู่ แต่หลังกระจกชิ้นนี้กลับมองไม่เห็นภาพอะไรเลย"
90101100-175 = "เห็นแค่เป็นสีครามเข้มเกือบดำ หรือว่ามันกำลังแสดงภาพใต้ทะเลที่ปูถือกำเนิดขึ้นกันนะ?"
90101100-176 = "ไม่ว่าจะเป็นอะไรก็ตาม การที่ตำนานที่พวกเราต่อสู้ด้วยทิ้งสิ่งตกค้างที่มีลักษณะคล้ายคลึงกันไว้นั้น มันก็ตีความได้ว่า..."
90101100-177 = ""
90101100-178 = "ความเป็นไปได้ที่ว่า \"ตำนานเมืองที่เพิ่มขึ้นอย่างฉับพลันเมื่อเร็วๆ นี้ รวมถึงผู้สูญหายที่เกี่ยวข้อง ไม่ได้เกิดจากความบังเอิญธรรมดา\" ก็ยิ่งสูงขึ้นแล้วสินะ"
90101100-179 = "ถึงหลักฐานที่รวบรวมได้จนถึงตอนนี้ เรายังไม่อาจยืนยันอะไรได้เลยก็เถอะ"
90101100-180 = "คุณครู ครั้งนี้ก็ขอฝากให้ช่วยจัดการเศษแก้วชิ้นนี้แทนด้วยนะคะ"
90101100-181 = "[s] \"อื้อ ครูจะเก็บไว้เอง\""
90101100-182 = "เฮ้อ... เหนื่อยจัง..."
90101100-183 = "ถ้างั้น พวกเราก็ค่อยๆ กลับกัน..."
90101100-184 = ""
90101100-186 = ""
90101100-187 = "หืม...? พวกลูกปูที่กำลังกรูกันอยู่แถวตู้คอนเทนเนอร์นั่นมันอะไรกันน่ะ?"
90101100-188 = "เพราะสู้กับปูยักษ์มา เลยแยกแยะขนาดผิดเพี้ยนไปแล้วหรือเปล่า? นั่นไม่ใช่ลูกปู แต่เป็นปูโตเต็มวัยขนาดปกติต่างหากล่ะ"
90101100-189 = "แต่จู่ๆ ปูมากมายขนาดนี้โผล่มาจากไหนกัน?"
90101100-190 = ""
90101100-192 = ""
90101100-193 = "อ้อ... น่าจะเป็นปูที่การ์ปัชโช่ แฟมิลี่ซื้อมาเพื่อข่มขู่ผู้คนนะ"
90101100-194 = "ตอนที่โกดังถล่มเมื่อกี้ พวกมันคงอาศัยจังหวะนั้นหนีออกมาน่ะ"
90101100-195 = "จริงด้วย ดูจากทิศทางการเคลื่อนที่แล้ว เหมือนพวกมันกำลังมุ่งจากโกดังไปยังทะเลเลย"
90101100-196 = ""
90101100-198 = ""
90101100-199 = ""
90101100-200 = "ปูจำนวนมากพากันมุ่งหน้าไปยังทะเลโดยมีท่าเรือที่ถูกทำลายเป็นฉากหลัง เห็นภาพแบบนี้แล้วรู้สึกขนลุกขึ้นมาเลยนะ"
90101100-201 = "เหมือนเห็นเป็นฝูงปูที่ทำลายถิ่นฐานของมนุษย์กำลังกลับคืนสู่ทะเลเลย"
90101100-202 = "ช่วงนี้แถบทะเลใกล้เคียงคงจับปูได้เป็นจำนวนมากโดยไม่ทราบสาเหตุสินะ...?"
90101100-203 = "แล้วถ้ามีคำให้การของผู้ที่พบเห็นปูทำลายอาคารเพิ่มเข้ามาอีกละก็..."
90101100-204 = "ต่อไปอาจเกิดตำนานเมืองเรื่องใหม่ ว่ามีฝูงปูปีศาจจำนวนมากออกมาทำลายที่อยู่อาศัยของมนุษย์ก็ได้"
90101100-205 = "แบบนั้นไม่เอาด้วยหรอก! แค่ปูตัวเดียวยังเล่นเอาเหนื่อยแทบแย่เลย แล้วจะให้สู้กับฝูงปูตั้งมากมายได้ยังไงกัน?"
90101100-206 = ""
90101100-208 = ""
90101100-209 = "ฉันว่าดูเหมือนยังเร็วเกินไปหน่อยที่จะประกาศยุติปฏิบัติการนะ"
90101100-210 = "สมาชิกทุกคน ตั้งแต่นี้ไปให้ใช้กำลังทั้งหมดจับปูที่กำลังเดินเพ่นพ่านอยู่ทั่วท่าเรือ"
90101100-211 = ""
90101100-213 = ""
90101100-214 = "ทั้งหมดนี่เลยเหรอ...? พวกเราเนี่ยนะ?"
90101100-215 = "ปูมากมายขนาดนี้ ชาติไหนจะจับหมดล่ะ!"
90101100-216 = "[s11] \"แต่นี่อาจช่วยป้องกันปัญหาที่จะตามมาภายหลังได้นะ...\"\n[s12] \"ครูจะช่วยอีกแรง จะได้ป้องกันไม่ให้เกิดปัญหาอื่นตามมาไง\""
90101100-219 = "ให้ตายสิ..."
90101100-221 = "ฉันคงไม่อยากแม้แต่จะเห็นปูไปอีกพักใหญ่เลย!"
90101100-223 = "(หลังจากนั้น คุณครูกับกองทหาร FOX ก็วิ่งวุ่นอยู่ทั่วท่าเรือตลอดทั้งคืน เพื่อจับปูที่หลบหนีออกมา#nจากโกดัง...)"
90101100-225 = "ตอนต่อไป;บทส่งท้าย"
