[translation]
90100070-1 = "ตอนที่ 7;วิญญาณร้ายยามเที่ยงวัน"
90100070-2 = "เขตธุรกิจที่ 3 พื้นที่ 2"
90100070-4 = ""
90100070-5 = "FOX 3 รายงาน ขณะนี้กำลังลงพื้นที่สอบถามในเขตธุรกิจที่ 3 พื้นที่ 2 ที่พบผู้เสียหายรายแรก"
90100070-6 = "ผู้เสียหายรายแรกเป็นพนักงานขายของบริษัทยาในละแวกนี้ คาดว่าคงเดินไปมาแถวนี้บ่อยๆ แม้กระทั่งในตอนกลางวันที่อากาศร้อน"
90100070-7 = "แต่นอกจากแสงแดดที่สะท้อนจากกระจกอาคารจนแสบตาแล้ว ก็ไม่เห็นมีอะไรที่ดูอาจทำให้เข้าใจผิด#nว่าเป็นหุ่นไล่กาสีขาวได้เลย"
90100070-8 = ""
90100070-11 = "พื้นที่รื้อถอนในเขตปิดกั้นระดับ A"
90100070-12 = ""
90100070-13 = "FOX 4 รายงาน ขณะนี้กำลังตรวจค้นพื้นที่รื้อถอนในเขตปิดกั้นระดับ A จุดที่พบผู้เสียหายรายที่ 3"
90100070-14 = "ผู้เสียหายรายที่ 3 เป็นคนงานในพื้นที่รื้อถอน ด้วยลักษณะของพื้นที่ คาดว่าเขาคงต้องทำงานในลานโล่งที่ไม่มีร่มเงาอยู่บ่อยๆ"
90100070-15 = "มีฝุ่นฟุ้งปกคลุมไปทั่วบริเวณ อย่าว่าแต่หุ่นไล่กาสีขาวเลย แม้แต่ของสีขาวสักชิ้นฉันก็ยังมองไม่เห็น นอกจากอากาศที่ร้อนจัดแล้วก็ไม่มีความผิดปกติอื่น"
90100070-16 = ""
90100070-19 = "ตลาดกลางแจ้งสึคิเทน"
90100070-20 = ""
90100070-21 = "FOX 2 รายงาน ขณะนี้กำลังลงพื้นที่ตลาดกลางแจ้งสึคิเทนที่พบผู้เสียหายรายที่ 6"
90100070-22 = "ผู้เสียหายรายที่ 6 เป็นพ่อค้าที่ขายอาหารแผงลอยในตลาดแห่งนี้ คงเป็นเพราะอากาศที่ร้อนจัด ร้านค้าแถวนี้ก็เลยปิดทั้งหมดและแทบไม่มีผู้คนเลย"
90100070-23 = "อืม... เป็นไปได้มั้ยนะว่าผู้เสียหายจะเข้าใจผิด คิดว่านักท่องเที่ยวที่ใส่เสื้อผ้าสีขาวเป็นหุ่นไล่กา?"
90100070-24 = "แต่นอกจากนี้ก็เหมือนจะไม่มีอะไรที่น่าสังเกตเป็นพิเศษแล้วละ"
90100070-26 = "ทางด่วน KV เลขที่ 35"
90100070-27 = ""
90100070-28 = "FOX 1 รายงาน ขณะนี้กำลังตรวจค้นทางด่วน KV เลขที่ 35 จุดที่พบผู้เสียหายรายที่ 9"
90100070-29 = "ผู้เสียหายรายที่ 9 เป็นช่างซ่อมบำรุงสังกัดกรมบำรุงรักษาถนน D.U. และประสบเหตุขณะตรวจสอบสะพาน"
90100070-30 = "ฉันตรวจสอบอย่างละเอียดแม้กระทั่งใต้สะพานที่เป็นจุดพบผู้เสียหายแล้ว แต่ว่า..."
90100070-31 = ""
90100070-33 = ""
90100070-34 = "ยังไม่เพียงพอสินะ..."
90100070-35 = ""
90100070-37 = ""
90100070-38 = ""
90100070-39 = "อะ... อะไรไม่เพียงพอ? น้ำเหรอ หรือว่าร่างกายต้องการน้ำมากกว่านี้?"
90100070-40 = "คงหมายความว่า ตอนนี้เรายังมีเบาะแสไม่มากพอที่จะระบุตัวหุ่นไล่กาสีขาวได้น่ะ"
90100070-41 = "ขออย่างเดียว อย่าบอกว่าให้กลับไปตรวจสอบตั้งแต่จุดแรกอีกรอบก็พอ..."
90100070-42 = "แต่ว่า..."
90100070-43 = ""
90100070-46 = "[ns1] \"สวัสดี ชาเล่ต์ EATS มาแล้ว!\"\n[ns2] \"ครูเอาน้ำเย็นกับเครื่องดื่มชูกำลังมาให้!\""
90100070-49 = "อ๊ะ คุณครู..."
90100070-50 = "เอาเครื่องดื่มมาให้ถึงที่นี่เลยเหรอคะ? ครั้งนี้คุณครูไม่ต้องตามมาด้วยก็ได้แท้ๆ"
90100070-51 = "[s3] \"ดูเหมือนทุกคนจะใช้เวลานานมากกว่าที่คิดนะ\"\n[s4] \"เจอปัญหาอะไรกันอยู่หรือเปล่า...?\""
90100070-54 = "ไม่มีปัญหาใหญ่อะไรค่ะ แต่เรายังมีข้อมูลไม่มากพอที่จะสนับสนุนคำให้การของผู้เสียหาย..."
90100070-55 = "เห็นทีเราจะต้องขยายขอบเขตการตรวจค้นและเริ่มลงพื้นที่สอบถามใหม่อีกครั้งค่ะ"
90100070-56 = ""
90100070-58 = ""
90100070-59 = "อึก..."
90100070-60 = ""
90100070-61 = "[ns5] \"อากาศร้อนแบบนี้ ไว้ค่อยทำทีหลังไม่ได้เหรอ?\"\n[ns6] \"ครูว่าค่อยทำต่อหลังพระอาทิตย์ตกดินก็ได้นะ...\""
90100070-64 = "แบบนั้น... ไม่ได้หรอกค่ะ"
90100070-65 = "เพราะหลักฐานในที่เกิดเหตุอาจเปลี่ยนแปลงไปตามช่วงเวลาและสภาพอากาศ ไม่ใช่แค่ตามสถานที่เท่านั้นค่ะ"
90100070-66 = "ผู้เสียหายทุกรายถูกพบในช่วงกลางวันที่มีแสงแดดจัด ถ้าเราลงพื้นที่หลังพระอาทิตย์ตกมันก็ไม่มี#nประโยชน์ค่ะ"
90100070-67 = "ถ้ามองในแง่การเก็บรวบรวมหลักฐาน แบบนั้นก็คงมีประสิทธิภาพที่สุด แต่ก็ควรคำนึงถึงสภาพร่างกายของสมาชิกในกองสักหน่อยนะ"
90100070-68 = "ฉันว่าทุกคนจะเริ่มเหนื่อยล้าจากการทำงานกลางแดดร้อนจัดมาหลายวันแล้ว"
90100070-69 = ""
90100070-71 = ""
90100070-72 = "งั้นก็ช่วยไม่ได้..."
90100070-73 = "ทุกคนไปพักผ่อนแถวนี้ก่อนแล้วกัน ฉันจะไปลงพื้นที่ต่อไปเอง..."
90100070-74 = "เฮ้อ..."
90100070-75 = "กลับไปทำตามนิสัยเดิมอีกแล้วสินะ"
90100070-76 = "ยูกิโนะ เธอคิดเหรอว่าถ้าพูดแบบนั้นแล้วพวกเราจะไปพักผ่อนอย่างสบายใจได้น่ะ? หรือเธอคิดว่าพวกเราเป็นสมาชิกแย่ๆ ที่ทำเป็นไม่เห็นความเหน็ดเหนื่อยของหัวหน้ากอง?"
90100070-77 = "ฉะ... ฉันไม่ได้มีเจตนาแบบนั้น..."
90100070-78 = "[ns7] \"ประธานองค์การนักเรียนไม่ได้กำหนดตารางเวลาไว้เป็นพิเศษนี่\"\n[ns8] \"ค่อยๆ ทำปฏิบัติการแบบไม่ต้องรีบร้อนดีมั้ย?\""
90100070-81 = "แต่ว่า... ระหว่างที่เราเสียเวลาอยู่แบบนี้ อาจมีผู้เสียหายรายใหม่เพิ่มขึ้นอีกก็ได้ค่ะ"
90100070-82 = "ถ้ามีเรื่องให้ชาวเมืองบาดเจ็บอีกเพราะฉันปฏิบัติหน้าที่บกพร่อง"
90100070-83 = "ถ้าฉันไม่อาจตัดสินใจและรับผิดชอบให้เร็วกว่านี้ได้..."
90100070-84 = ""
90100070-86 = ""
90100070-87 = ""
90100070-88 = ""
90100070-89 = ""
90100070-90 = "เดี๋ยวก่อน มีเป้าหมายไม่ทราบฝ่ายกำลังมุ่งหน้ามาทางนี้จากบริเวณทางแยกยกระดับ"
90100070-91 = "ดูจากการเคลื่อนไหวกับความเร็วของเป้าหมายแล้ว... เหมือนจะเป็นคนนะ?"
90100070-92 = "มีคนเดินข้ามทางยกระดับมางั้นเหรอ? ใช่กรมบำรุงรักษาถนนมาซ่อมบำรุงถนนหรือเปล่า?"
90100070-93 = "ไม่นะ ในตารางงานของกรมบำรุงรักษาถนนไม่มีกำหนดการซ่อมบำรุง"
90100070-94 = "อย่าบอกนะว่าเป็น 'หุ่นไล่กาสีขาว' ในข่าวลือ..."
90100070-95 = "รีบไล่ตามไปก่อนที่จะหายตัวไปที่อื่นเร็วเข้า"
90100070-96 = ""
90100070-101 = ""
90100070-102 = ""
90100070-103 = "นักเรียนที่กำลังวิ่งอยู่ตรงนั้นคือเป้าหมายไม่ทราบฝ่ายที่ว่าเหรอ?"
90100070-104 = "เอ่อ ขอโทษนะคะ..."
90100070-107 = ""
90100070-108 = "เอ๋ มีคนอยู่ในที่แบบนี้ด้วยเหรอ...?"
90100070-109 = "มีอะไรให้ฉันช่วยหรือเปล่าคะ?"
90100070-110 = "ไม่ๆๆ คนที่ต้องการความช่วยเหลือน่าจะเป็นทางนั้นมากกว่านะ"
90100070-111 = "ข้างหน้านี้ห้ามคนเดินเท้าสัญจรผ่านน่ะ เพื่อความปลอดภัย ฉันแนะนำให้เลี่ยงไปใช้เส้นทางอื่นดีกว่า"
90100070-112 = "อากาศร้อนขนาดนี้ เธอขึ้นมาเดินบนทางยกระดับที่อันตรายเพื่ออะไรกัน?"
90100070-113 = "เพื่ออะไรงั้นเหรอ มันก็แน่นอนอยู่แล้ว..."
90100070-114 = ""
90100070-116 = ""
90100070-117 = "ฉันกำลังฝึกเส้นทางอยู่ค่ะ!"
90100070-118 = "[s] \"แต่งตัวแบบนี้น่าจะมาจากสหพันธ์เฮียกคิยาโค...\""
90100070-119 = "เอ๋ คุณครู [USERNAME]?"
90100070-120 = "ใช่ค่ะ ฉันคืออาซาคุสะ นัตสึกิ จากชมรมรถลากของเฮียกคิยาโคค่ะ! ตั้งแต่งานเทศกาลครั้งก่อน ก็ไม่ได้เจอกันนานเลยนะคะ!"
90100070-121 = "ถ้าคุณครูไม่ติดอะไร... มานั่งรถลากดูมั้ยคะ?"
90100070-122 = "ถ้าเป็นตอนนี้ละก็ ใช้บริการรถลากถูกกว่าแท็กซี่อีกนะคะ จะไปที่ไหนใน D.U. ก็ได้ค่ะ!"
90100070-123 = "[s9] \"ไม่เป็นไรดีกว่า แต่ขอถามอะไรหน่อย...\"\n[s10] \"จะว่าไป ครูมีเรื่องอยากถามอย่างหนึ่ง...\""
90100070-127 = "สรุปว่า... เธอกำลังฝึกลากรถบนทางด่วน เพราะคิดว่าอาจมีลูกค้าที่อยากเดินทางออกนอกเขตปกครอง#nตนเองงั้นเหรอ?"
90100070-128 = "ใช่ค่ะ เพราะหลักพื้นฐานของการขนส่งผู้โดยสาร คือการพาลูกค้าไปถึงจุดหมายที่ต้องการอย่างรวดเร็ว ด้วยเส้นทางที่สั้นที่สุดยังไงล่ะคะ!"
90100070-129 = "ถ้าไม่ศึกษาเส้นทางไว้ล่วงหน้า แล้วพาลูกค้าอ้อมไปอ้อมมา ลูกค้าอาจหมดความเชื่อมั่นก็ได้ค่ะ!"
90100070-130 = "อืม... ก็จริงนะ เวลาคนขับแท็กซี่จู่ๆ ก็เลี้ยวเข้าทางที่ไม่คุ้น ฉันเองก็เคยกังวลเหมือนกันว่าค่าโดยสาร#nจะบานปลายหรือเปล่า"
90100070-131 = "แท็กซี่กับรถลากมันเหมือนกันที่ไหนล่ะ?!"
90100070-132 = "เมื่อกี้บอกว่าชื่อนัตสึกิจังใช่มั้ย? ขอโทษนะ แต่บนทางด่วนของ D.U. ห้ามรถลากสัญจรน่ะ เห็นทีต้องไปใช้เส้นทางอื่นแล้วละ"
90100070-133 = "หา? จริงเหรอคะ?"
90100070-134 = "อึก... ที่เฮียกคิยาโคเองก็เพิ่งออกข้อบังคับได้ไม่นาน ไม่คิดเลยนะว่าใน D.U. ก็เป็นไปด้วย"
90100070-135 = "การเอารถลากขึ้นทางด่วนนี่ ต่อให้ไม่มีข้อบังคับ ก็น่าจะรู้กันอยู่แล้วว่าอันตรายนะ..."
90100070-136 = "ที่สำคัญกว่านั้น ฉันแปลกใจมากกว่าที่เธอคิดจะลากรถบนทางด่วนในอากาศแบบนี้ อากาศร้อนขนาดนี้ ต่อให้เป็นนักกีฬาที่แข็งแรง แต่ถ้าวิ่งเกินครึ่งวันก็คงเวียนหัวได้เลยนะ"
90100070-137 = "ถึงจะร้อนอยู่บ้าง... แต่ฉันไม่เป็นไรค่ะ! สำหรับคนลากรถแล้ว เรื่องแบบนี้เจอกันเป็นประจำอยู่แล้วค่ะ!"
90100070-138 = "พื้นถนนลาดยางที่รถลากวิ่งจะคายความร้อนขึ้นมาโดยตรง คนลากรถก็เลยชินกับการวิ่งในบริเวณที่#nอุณหภูมิสูงกว่าปกติน่ะค่ะ"
90100070-139 = "ถ้าเทียบกับช่วงพีคของหน้าร้อนแล้ว ระดับนี้ยังถือว่าเย็นสบายอยู่เลยค่ะ!"
90100070-140 = "[s11] \"แต่ก็ระวังเป็นลมแดดด้วยนะ แล้วก็เอานี่ไปดื่มด้วย\"\n[s12] \"เอ้า นี่เครื่องดื่มเย็นๆ นัตสึกิจังก็รับไปดื่มด้วยนะ\""
90100070-143 = "อ่า... ขอบคุณค่ะ"
90100070-144 = "ได้รับเครื่องดื่มจากคุณครูของชาเล่ต์ในสถานที่ที่ไม่คาดคิดเลยแบบนี้... วันนี้ฉันดวงดีจังเลยนะคะ"
90100070-145 = ""
90100070-147 = ""
90100070-148 = ""
90100070-149 = "จะว่าไป เมื่อกี้ที่บอกว่าชอบไปลากรถบนถนนที่ร้อนจัดและไม่มีร่มเงา ฉันเลยอยากถามอะไรหน่อย..."
90100070-150 = "เคยเห็น 'หุ่นไล่กาสีขาว' ที่ดูน่าสงสัยตามถนนบ้างหรือเปล่า?"
90100070-151 = "หุ่นไล่กาสีขาวเหรอคะ...?"
90100070-152 = "อื้อ ถ้าจะมีจุดร่วมอะไรที่น่าสังเกตเป็นพิเศษ ก็คงมีแค่ว่าทุกคนที่เห็นหุ่นไล่กานั่น ต่างก็เป็นลมหมดสติและก็มีอาการชักเหมือนๆ กัน..."
90100070-153 = "นั่นใช่ 'คุเนะคุเนะ' หรือเปล่าคะ?"
90100070-154 = "คุเนะคุเนะ...?"
90100070-155 = "อ่า แต่คุเนะคุเนะมักถูกพบเห็นตามทุ่งนาในชนบทเป็นส่วนใหญ่ ฉันไม่เคยได้ยินว่ามีใครพบมันใน#nย่านใจกลางเมืองที่รายล้อมไปด้วยอาคารแบบนี้เลย..."
90100070-156 = "จะเจอที่ไหนก็ไม่สำคัญหรอก ว่าแต่คุเนะคุเนะที่ว่ามันคืออะไรเหรอ?"
90100070-157 = "ขอโทษที่ตอบคำถามจริงจังด้วยคำตอบแปลกๆ แบบนี้นะคะ... แต่คุเนะคุเนะเป็นหนึ่งในตำนานเมืองที่#nโด่งดังของเขตปกครองตนเองเฮียกคิยาโคค่ะ"
90100070-158 = "มันเป็นตำนานเมืองที่เพิ่งเริ่มโด่งดังเมื่อไม่นานมานี้ แต่ต่างจากเรื่องลึกลับอื่นๆ ที่มักมีบรรยากาศชวน#nขนลุกตรงที่คุเนะคุเนะมักปรากฏให้เห็นตามทุ่งโล่งในวันที่อากาศแจ่มใสค่ะ"
90100070-159 = "ถ้ามองจากระยะไกล มันจะดูเหมือนหุ่นไล่กาสีขาวที่กำลังเต้นรำ แต่ก็ไม่มีใครรู้หรอกค่ะว่าตัวตนที่แท้จริงเป็นคนหรือหุ่นไล่กากันแน่"
90100070-160 = "นั่นก็เพราะทุกคนที่เข้าใกล้และได้เห็นตัวตนที่แท้จริงของมัน ต่างก็เสียสติและกลายเป็นคุเนะคุเนะไปด้วย"
90100070-161 = "แล้วก็ยิ้มอย่างน่าขนลุก และบิดตัวไปมาช้าๆ..."
90100070-162 = "อะไรกันน่ะ น่ากลัวจัง"
90100070-163 = "ก็เพราะเป็นแค่ตำนานเมืองน่ะค่ะ ฉันว่าที่เฮียกคิยาโคเองก็แทบไม่มีใครเชื่อเรื่องนี้จริงจังด้วยค่ะ ยกเว้นแต่จะเป็นคนลากรถอย่างพวกฉัน"
90100070-164 = "หืม? หมายความว่านัตสึกิเชื่อว่าคุเนะคุเนะมีอยู่จริงงั้นเหรอ?"
90100070-165 = "จะบอกว่าเชื่อในตำนานเมืองก็คงไม่เชิง... แค่พอเข้าใจว่าทำไมตำนานแบบนี้ถึงแพร่กระจายก็เท่านั้นค่ะ"
90100070-167 = "เวลามองพื้นถนนลาดยางในวันที่ร้อนจัด บางทีก็จะเห็นไอร้อนสีขาวลอยขึ้นมา ดูเหมือนควันสีขาวที่กำลังไหวไปมาใช่มั้ยล่ะคะ?"
90100070-168 = "วันแบบนั้นมักจะร้อนกว่าปกติอยู่แล้ว ถ้าฝืนลากรถก็อาจเป็นลมแดดได้ค่ะ"
90100070-169 = "คำเตือนที่ว่า \"ถ้าเห็นหุ่นไล่กาสีขาวกำลังบิดตัวอยู่ใกล้เส้นขอบฟ้าก็ให้กลับบ้านไป\" นั่นอาจเป็นคำเตือนที่ใช้ได้จริงกว่าที่คิดก็ได้นะคะ"
90100070-171 = ""
90100070-172 = "ไอร้อนงั้นเหรอ..."
90100070-173 = "อย่างนี้สินะ... ไอร้อนนี่เอง"
90100070-174 = "ขอบใจนะ เธอช่วยพวกเราได้เยอะเลยละ"
90100070-175 = "คะ... คะ...? มะ... ไม่เลยค่ะ"
90100070-176 = ""
90100070-178 = ""
90100070-179 = ""
90100070-180 = "คุณครู [USERNAME] ฉันขอยุติปฏิบัติการภาคสนามของวันนี้ และกลับกองบัญชาการทันทีค่ะ"
90100070-181 = "[s] \"อะ... อื้อ ได้สิ งั้นก็กลับกันเถอะ\""
90100070-182 = ""
90100070-184 = ""
90100070-185 = ""
90100070-186 = "[ns] \"นัตสึกิจังก็ระวังแดดร้อนด้วยนะ กลับดีๆ ล่ะ~\" "
90100070-187 = "ค่ะ เดินทางกลับกันดีๆ นะคะ...!"
90100070-188 = ""
90100070-193 = ""
90100070-194 = "จะว่าไป นักเรียนในชุดกะลาสีกลุ่มนั้น ดูคุ้นหน้าแปลกๆ..."
90100070-195 = "หรือว่าเมื่อก่อนเคยมาทัศนศึกษาที่สหพันธ์เฮียกคิยาโคนะ?"
90100070-197 = "ตอนต่อไป;เหนือไอแดดระอุ"
