[translation]
901010600110-6 = ""
901010600110-7 = "FOX 2 รายงาน ตอนนี้ฉันมาถึงจุดอัลฟาแล้ว"
901010600110-8 = ""
901010600110-10 = ""
901010600110-11 = "รับทราบ สมาชิกคนอื่นรายงานต่อได้"
901010600110-12 = ""
901010600110-14 = ""
901010600110-16 = ""
901010600110-17 = "FOX 3 มาถึงจุดเซียร์ราพร้อมกับ FOX 4 แล้ว"
901010600110-18 = "พวกเราจะเฝ้าระวังรอบๆ และสนับสนุน FOX 2 จากระยะไกลให้"
901010600110-20 = "รับทราบ..."
901010600110-21 = "เป้าหมายของปฏิบัติการวันนี้คือสืบหาที่อยู่ของมิยากุจิ ชาวประมงผู้สูญหายที่เรายังตรวจสอบไม่ได้#nในการแฝงตัวครั้งก่อน และสืบหาต้นตอของข่าวลือ"
901010600110-22 = "ถึงคนส่วนใหญ่ที่เกี่ยวข้องกับท่าเรือจะดูไม่สนใจข่าวลือนี้ แต่ก็อาจมีบางอย่างที่เรามองข้ามไป เพราะงั้นคอยสังเกตให้ละเอียดด้วย"
901010600110-24 = "รับทราบ!"
901010600110-27 = "ว่าแต่ FOX 1 ที่ออกไปสืบสวนเมื่อวาน ไม่เจอหลักฐานใหม่อะไรเป็นพิเศษเลยเหรอ?"
901010600110-28 = "ที่ไปสืบสวนเมื่อวานเหรอ...?"
901010600110-29 = "อื้อ ก็เมื่อวานเธอบอกว่ามีเรื่องที่อยากไปสืบเอง ก็เลยขอตัวออกไปช่วงบ่ายไม่ใช่เหรอ?"
901010600110-30 = "นึกว่าจะออกไปหาหลักฐานเกี่ยวกับปูถังเหล็กคนเดียวเสียอีก... ไม่ใช่หรอกเหรอ?"
901010600110-31 = "อ่า... หมายถึงเรื่องเมื่อวานสินะ"
901010600110-32 = "ไม่มีอะไรหรอก ฉันออกไปทำธุระส่วนตัวน่ะ"
901010600110-34 = "โอ้~ ธุระส่วนตัวงั้นเหรอ"
901010600110-35 = "ทำไมถึงทำปฏิกิริยาแบบนั้นล่ะ FOX 3...?"
901010600110-36 = "ก็แค่รู้สึกว่า นี่เป็นครั้งแรกเลยที่เห็น FOX 1 ขอตัวไปทำ 'ธุระส่วนตัวจริงๆ' ในวันหยุดน่ะ"
901010600110-37 = "ช่วงนี้มีอะไรเปลี่ยนไปในความรู้สึกของเธอหรือเปล่า?"
901010600110-38 = "หรือว่าที่ยูกิโนะเปลี่ยนไป จะเป็นเพราะคุณครู [USERNAME]..."
901010600110-39 = "หยุดคุยเรื่องนอกประเด็นที่ไม่เกี่ยวกับปฏิบัติการเถอะ"
901010600110-40 = "FOX 2 ขอฝากด้วยนะ"
901010600110-41 = "ฮุฮุ ถ้างั้นฉันจะเริ่มเลยนะ"
