[translation]
901010600120-7 = ""
901010600120-8 = "สวัสดีค่ะ!"
901010600120-9 = ""
901010600120-11 = ""
901010600120-13 = ""
901010600120-14 = "อ๊ะ นักเรียนที่เคยเอาซูชิเต้าหู้หวานมาแจกนี่นา?"
901010600120-15 = "วันนี้มาทำโปรเจกต์หรือโปรโมตอะไรอีกงั้นเหรอ?"
901010600120-16 = "เปล่าค่ะ น่าเสียดายที่กิจกรรมรีวิว <FOX EATS> จบไปแล้วน่ะค่ะ..."
901010600120-17 = ""
901010600120-19 = ""
901010600120-20 = "แต่ฉันยังมีเครื่องดื่มชูกำลังที่เหลือจากกิจกรรมครั้งก่อนอยู่เยอะเลย สนใจรับไว้สักขวดมั้ยคะ?"
901010600120-21 = "ถ้าให้กันฟรีๆ ก็ไม่มีเหตุผลให้ปฏิเสธหรอกนะ..."
901010600120-22 = ""
901010600120-24 = ""
901010600120-25 = "วันนี้จับปูได้เยอะมั้ยคะ?"
901010600120-26 = "ได้เยอะสิ เยอะจนเกือบทำเรือคว่ำเลยละ"
901010600120-27 = "ถ้าราคาปูไม่ตกฮวบก็คงดีหรอก"
901010600120-28 = "นั่นสินะคะ ทั้งที่จับได้ตั้งเยอะ แต่กลับขายไม่ได้ราคาที่ควรจะเป็น น่าเสียดายจริงๆ เลยค่ะ"
901010600120-29 = "จะว่าไป ที่นี่ใช้ลอบจับปู แล้วเอาเหยื่อใส่ไว้ในลอบอีกทีหรือเปล่าคะ?"
901010600120-30 = "ปกติปูที่จับด้วยอวนหรือลอบ มักจะขาหักหรือก้ามเสียหาย แต่ปูที่จับได้ที่นี่ดูสะอาดและอยู่ในสภาพดี#nมากเลยนะคะ"
901010600120-31 = "แค่การจับปูแต่ละตัวก็ยังพิถีพิถันขนาดนี้ ฉันว่าราคาปูจะกลับมาคงที่ในไม่ช้าแน่นอนค่ะ"
901010600120-32 = ""
901010600120-35 = ""
901010600120-36 = "หนูนี่ไม่เหมือนเด็กสมัยนี้เลยนะ... "
901010600120-37 = "ถ้าคนหนุ่มสาวสมัยนี้เป็นแบบหนูทุกคน ฉันก็คงไม่ต้องลำบากหาคนมาทำงานขนาดนี้หรอก"
901010600120-38 = "มีปัญหาเรื่องการหาคนทำงานเหรอคะ?"
901010600120-39 = "ไม่มีอะไรมากหรอก แค่เด็กใหม่ที่ชื่อมิยากุจิที่ทำงานอยู่บนเรือประมง จู่ๆ ก็ดันหายตัวไป แล้วฉันก็ยังหาคนอื่นมาทำแทนไม่ได้เลย"
901010600120-40 = "เจ้ามิยากุจินั่นเล่นหนีหายไปโดยไม่ได้บอกใครสักคำ... ถ้าเจอตัวอีกเมื่อไร ยังว่าจะเตะก้นสักทีอยู่เลย"
901010600120-41 = "ต้องลำบากน่าดูเลยนะคะ"
901010600120-42 = "แต่ถ้าจู่ๆ ก็หายตัวไปแบบนี้ แปลว่าเกิดเรื่องอะไรกับคุณมิยากุจิหรือเปล่าคะ?"
901010600120-43 = "อาจจะป่วยหนัก หรือว่าประสบอุบัติเหตุเข้า..."
901010600120-44 = "ฮึ เด็กแข็งแรงอย่างหมอนั่น จู่ๆ จะมาป่วยเป็นโรคอะไรได้?"
901010600120-45 = "คงหนีไปเพราะทนงานจับปูไม่ไหวน่ะสิ ตอนซ่อมอุปกรณ์ประมงก็บ่นอยู่ทุกวันว่าทำงานนี้ต่อไปไม่ไหว"
901010600120-46 = "งานจับปูลำบากขนาดนั้นเลยเหรอคะ?"
901010600120-47 = "จะบอกว่าเป็นงานง่ายก็คงไม่ได้หรอก แต่ถ้ามีความอดทน ใครๆ ก็ทำได้"
901010600120-48 = "ถ้าไม่เชื่อก็ลองไปถามลูกเรือคนอื่นดูสิ ทุกคนรู้กันหมดว่าเจ้าหมอนั่นอ่อนแอแค่ไหน"
901010600120-49 = "เด็กสมัยนี้นี่นะ..."
